### ISSUE TITLE
[BUG] "incorrect magic number [72 84 84] , 0x170303 is expected"

### ISSUE THREAD

**Issue by Wenlong-Shaw** [Dreamacro/clash#1000]
配置好ShadowsocksR接电参数后，测速日志报错。错误如题"incorrect magic number [72 84 84] , 0x170303 is expected"。

**Comment by Wenlong-Shaw** [comment]
找到原因了，是因为不支持 “chacha20” 的加密算法导致的。

**Comment by Dreamacro** [comment]
当做问题已经解决了，先 close
