### ISSUE TITLE
远程连接Clash提供的Socks5端口是否安全？

### ISSUE THREAD

**Issue by DaPoHou** [Dreamacro/clash#1002]
服务器使用Clash开启Socks5 port 7891
手机App代理设置Socks 5代理，设置为服务器ip和7891端口
那么在手机和服务器之间的连接是否加密？能否被识别？是否安全？
请赐教，感谢！

**Comment by ysc3839** [comment]
不加密，能被识别，不安全。

**Comment by DaPoHou** [comment]
> 不加密，能被识别，不安全。

感谢回复！
因为服务器A无公网ip，想通过其中转。
我的方案是：手机--->家用路由器---frp+tls--->国内服务器A clash---->境外服务器

其中从手机到家用路由器这段感觉不太安全，所以想请教各位。有什么更安全方式吗？

**Comment by ysc3839** [comment]
WiFi 开启加密，且不让不可信设备连接的情况下，局域网一般认为是安全的。
个人认为 frp 更不安全，没记错的话 frp 的 TLS 并没有安全检查，有中间人攻击的可能性。

**Comment by DaPoHou** [comment]
Frp已经提供tls双方证书验证功能了。
家用路由器将服务器A的Socks 5端口对外开放。
手机和家用路由器不在一个局域网。
如果Clash能作为服务端支持Socks tls，是不是会更好？

**Comment by whitegerry** [comment]
> > 不加密，能被识别，不安全。
> 
> 感谢回复！
> 因为服务器A无公网ip，想通过其中转。
> 我的方案是：手机4G--->家用路由器---frp+tls--->国内服务器A clash---->境外服务器。
> 
> 手机和家用路由器不在一个局域网。
> 其中从手机到家用路由器这段感觉不太安全，所以想请教各位。有什么更安全方式吗？

手机到路由器可以s's，路由到其它地方可以用gost接一下

**Comment by Dreamacro** [comment]
@DaPoHou 该说的 @ysc3839  都说了。

> 如果 Clash 能作为服务端支持 Socks tls，是不是会更好？

Clash 是一个客户端软件，大概率不支持 socks5 tls, 如果需要可以用 caddy 之类的做一个 tcp forward。clash 是支持连接 socks5 tls 的
