### ISSUE TITLE
[Feature] 命令支持自动选择最优、自动切换

### ISSUE THREAD

**Issue by jiangxiaoqiang** [Dreamacro/clash#1003]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

现在是直接使用命令启动：

```
./clash -f config.yaml
```

能否直接命令支持自动切换最优节点，例如：

```
./clash -f config.yaml -urlTest
```

### 环境 Environment

OpenWRT

Powered by LuCI Master (git-20.088.29068-cebe120) / OpenWrt R20.3.19 GDQ IPv4 LB v4.1[2020] 

### 说明 Description

在UI界面上配置太过于繁琐，选项太多，很难弄清各个选项的含义以及互相关系。 所以直接登录系统使用命令启动非常简洁。但是遇到的问题是，无法知道使用的哪个节点，不知是否选择最优节点（目前实际速度只有200多KB，正常速度在10MB/s）。

能否实现自动检测延迟，可用性，自动切换。

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash
可以试一下我这个项目，目前大家反馈设置还是比较简洁方便的

节点选择需要根据你的配置文件进行，可以使用或者安装dashboard面板来解决
比如 [clash.razord.top](url)
