### ISSUE TITLE
Matching a subdomain containing certain prefix and/or suffix

### ISSUE THREAD

**Issue by emlimap** [Dreamacro/clash#1004]
I am trying to write a rule that specifically matches a subdomain containing certain prefix & suffix, i.e. `abc*xyz.example.com` but doesn't seem to be working. Tried it with all variants of DOMAIN types. Not sure if this is possible at the moment as there is no example of this in here https://lancellc.gitbook.io/clash/clash-config-file/rules

First example is a simple wildcard matching the middle of a subdomain
```
ssh*dash-i.akamaihd.net
```
This should cover some domains like

```
sshd1livetvdash-i.akamaihd.net
sshindidash-i.akamaihd.net
sshd2livetvdash-i.akamaihd.net
```

Another example with just prefix

`live*.hotstar.com`

This should cover domains like `liveXXX.hotstar.com` where XXX is a combination of letters & numbers.

While the first example could be achieved using `DOMAIN-KEYWORD` with keyword `dash-i.akamaihd.net`. There maybe false positives but can be fixed by adding individual rules to redirect them else where. From what I have noticed as long as the more specific rules go above `DOMAIN-SUFFIX` and `DOMAIN-KEYWORD` ones, they take priority. Correct me if I am wrong.

Second one is a bit more tricky because live keyword would cause way too much false positives and on the other hand don't want to redirect the whole domain as only the live channels are geo-restricted.

**Comment by Dreamacro** [comment]
This is difficult to implement according to current logic, reference: https://github.com/Dreamacro/clash/blob/master/component/trie/domain.go

**Comment by Dreamacro** [comment]
long time no response, close
