### ISSUE TITLE
[Feature]希望能添加订阅规则的base64解码支持

### ISSUE THREAD

**Issue by nov12** [Dreamacro/clash#1005]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash log

![image](https://user-images.githubusercontent.com/10071412/95403782-c2c4c180-0945-11eb-86a0-f976e830fbc2.png)

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
2020.08.16 Premium

* 使用者的操作系统 (the OS running on the client)
Win 10

### 说明 Description

某些机场订阅是Base64编码的，如果使用provider来自动订阅更新，则会出现无法使用的情况，提示编码错误。希望能添加base64编码解码支持。

**Comment by Dreamacro** [comment]
这个似乎不是我要解决的问题 配置文件没必要进行编码

**Comment by TomIsFat** [comment]
> 感谢你向 Clash Core 提交 Feature Request！ 在提交之前，请确认：
> 
>     * [x]  我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的请求
> 
> 
> 请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。
> 
> 我都确认过了，我要继续提交。
> 
> 请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 _Needs more information_ 标记并在收到更多资讯之前关闭 issue。
> ### Clash log
> 
> ![image](https://user-images.githubusercontent.com/10071412/95403782-c2c4c180-0945-11eb-86a0-f976e830fbc2.png)
> ### 环境 Environment
> 
>     * Clash Core 的操作系统 (the OS that the Clash core is running on)
>       2020.08.16 Premium
> 
>     * 使用者的操作系统 (the OS running on the client)
>       Win 10
> 
> 
> ### 说明 Description
> 
> 某些机场订阅是Base64编码的，如果使用provider来自动订阅更新，则会出现无法使用的情况，提示编码错误。希望能添加base64编码解码支持。

请问这个问题解决了吗，目前在网上也未能寻求到解决方案
