### ISSUE TITLE
[Feature]增加对于 chacha20的支持

### ISSUE THREAD

**Issue by convictss** [Dreamacro/clash#1008]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log
无

### 环境 Environment

win10，Clash.for.Windows-0.11.10-win

### 说明 Description
增加对于 chacha20的支持，增强对兼容性

**Comment by nb5p** [comment]
chacha20属于已被Shadowsocks弃用的加密算法

**Comment by convictss** [comment]
> chacha20属于已被Shadowsocks弃用的加密算法

那看来是我所使用的节点供应商的加密算法比较落后了

**Comment by Wenlong-Shaw** [comment]
希望大佬能增加对于 chacha20的支持。

**Comment by Dreamacro** [comment]
Duplicate of #978
