### ISSUE TITLE
Feature request: allow lan access require user name and pwd.

### ISSUE THREAD

**Issue by umlearn** [Dreamacro/clash#101]
我在家里 nas 上通过 docker 安装了 clash。我的 nas 是可以通过公网 ip 访问的，意思是我可以在外网通过设置 proxy 到家里的 ip 和端口既可以实现代理功能。
这样就带来了一个问题，仅有的一个端口用于验证服务可能就不太安全了，可不可以增加对 lan 访问设置用户名和密码呢？

**Comment by Dreamacro** [comment]
implementation in #216
