### ISSUE TITLE
[Bug]最新Premium在启用tun后无法正确代理udp

### ISSUE THREAD

**Issue by kriser-pan** [Dreamacro/clash#1011]
------------------------------------------------------------------

### Clash config

tun:
  enable: true
  stack: system # or gvisor
  dns-listen: 0.0.0.0:53
  dns-hijack:
    - tls://dns.google:853
    - 8.8.8.8:53
</details>

### Clash log

level=debug msg="Proxy UDP is not supported"

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Debian 10.6

### 说明 Description

同一个config下,使用最新1.2的Premium版并启用tun后udp连接无法被正确代理,退回到1.1版后一切正常.

**我预期会发生……？**

正确代理tcp与udp流量.
**实际上发生了什么？**

TCP流量正常, udp流量被return.

**Comment by Dreamacro** [comment]
需要其他代理信息

**Comment by akw5454521** [comment]
节点有标注udp为true吗

**Comment by kriser-pan** [comment]
> 
> 
> 节点有标注udp为true吗

THX, 问题已解决,确实是节点未标注udp为true的原因,但是同样的配置文件在1.1版本下udp是可以正常使用的...难道是1.1默认udp为true而1.2改为了默认false吗...?

**Comment by kriser-pan** [comment]
@Dreamacro 
大佬,我这边还遇到另外一个问题,在hosts中标注了静态解析的域名为内网ip,但是实际nslookup时还是会解析到动态的公网IP,是我dns的配置有问题吗?以下是dns相关配置:(相关域名与IP已做处理)
hosts:
'wp.域名.cn': 150.xxx.xxx.xxx
'+.域名.cn': 172.16.1.249
'+.域名.cn': fe80::5054:ff:fe87:f9e9
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 61.177.7.1
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - 8.8.8.8
    - 119.29.29.29
    - 223.5.5.5 # default value
  #fallback:
    #- tls://dns.google:853
#  fallback-filter:
#    geoip: true
#    ipcidr:
    # - 240.0.0.0/4

**Comment by Dreamacro** [comment]
第二个 `+.域名.cn` 覆盖了第一个的值，导致只能返回 AAAA 记录的结果，另外包含可能包含有特殊字符的字符串，应该用引号包裹消除歧义

**Comment by akw5454521** [comment]
> > 节点有标注udp为true吗
> 
> THX, 问题已解决,确实是节点未标注udp为true的原因,但是同样的配置文件在1.1版本下udp是可以正常使用的...难道是1.1默认udp为true而1.2改为了默认false吗...?

#934

之前有bug，不管标注与否都是udp可用状态，最新修复了bug，所以必须标注了

**Comment by kriser-pan** [comment]
> 
> 
> 第二个 `+.域名.cn` 覆盖了第一个的值，导致只能返回 AAAA 记录的结果，另外包含可能包含有特殊字符的字符串，应该用引号包裹消除歧义

hosts部分已修改为:
`hosts:`
`'wp.khomelab.cn': 150.109.69.236`
`'+.khomelab.cn': 'fe80::5054:ff:fe87:f9e9'`

实际nslookup输出依然是:
`root@kDocker:~# nslookup www.域名.cn`
`Server:         127.0.0.1`
`Address:        127.0.0.1#53`

`www.域名.cn canonical name = 域名.cn.`
`Name:   域名.cn`
`Address: 114.217.xxx.xxx`

个人感觉是hosts部分并没有被读取

**Comment by Dreamacro** [comment]
`$ nslookup -type=aaaa www.khomelab.cn`

**Comment by kriser-pan** [comment]
root@kDocker:~# nslookup -type=aaaa www.khomelab.cn
Server:         127.0.0.1
Address:        127.0.0.1#53

www.khomelab.cn canonical name = khomelab.cn.

并没有v6地址...

**Comment by Dreamacro** [comment]
`$ dig AAAA www.khomelab.cn @127.0.0.1 -p 53`

**Comment by kriser-pan** [comment]
`root@kDocker:~# dig AAAA www.khomelab.cn @127.0.0.1 -p 53`

`; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> AAAA www.khomelab.cn @127.0.0.1 -p 53`
`;; global options: +cmd`
`;; Got answer:`
`;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13892`
`;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0`

`;; QUESTION SECTION:`
`;www.khomelab.cn.               IN      AAAA`

`;; ANSWER SECTION:`
`www.khomelab.cn.        1       IN      CNAME   khomelab.cn.`

`;; Query time: 0 msec`
`;; SERVER: 127.0.0.1#53(127.0.0.1)`
`;; WHEN: Sat Oct 17 17:23:47 CST 2020`
`;; MSG SIZE  rcvd: 73`

**Comment by Dreamacro** [comment]
我这里没有问题，先检查一下你自己的配置。如果你能确保你自己的配置没有任何问题，脱敏后把配置贴出来

**Comment by kriser-pan** [comment]
`redir-port: 7892`
`mixed-port: 7890`

`allow-lan: true`

`bind-address: "*"`
`mode: rule`
`log-level: debug`
`external-controller: :7891`
`external-ui: /kdocker/clash/ui`
`secret: ""`

`hosts:`
`'wp.khomelab.cn': 150.xxx.xxx.xxx`
`'+.khomelab.cn': 'fe80::5054:ff:fe87:f9e9'`

`dns:`
`  enable: true`
  `listen: 0.0.0.0:53`
  `ipv6: true`

  `default-nameserver:`
    `- 61.177.7.1`
    `- 119.29.29.29`
    `- 223.5.5.5`
  `enhanced-mode: redir-host`
  `use-hosts: true`

`  nameserver:`
  `  - 8.8.8.8`
`    - 119.29.29.29`
`    - 223.5.5.5 # default value`
    
`tun:`
`  enable: true`
  `stack: system`
  `dns-listen: 0.0.0.0:53`
  `dns-hijack:`
    `- tls://dns.google:853`
    `- 8.8.8.8:53`

`proxies:`
    `- name: "vmess"`
    `type: vmess`
    `server: v2.server.com`
    `port: 443`
    `uuid: xxxxxxxxxxxxxxxxxxxxxxxxxx`
    `alterId: 68`
    `cipher: auto`
    `udp: true`
    `tls: true`
    `# skip-cert-verify: true`
    `servername: v2.server.com`
    `network: ws`
    `ws-path: /v2ray`
    `ws-headers:`
     ` Host: v2.server.com`
   
  `- name: "ssr"`
   ` type: ssr`
    `server: 150.xxx.xxx.xxx`
    `port: 19306`
    `cipher: aes-128-cfb`
    `password: "password"`
    `obfs: plain`
    `protocol: auth_chain_a`
    `udp: true`
    
  `- name: "unblockmusic"`
    `type: http`
    `server: 127.0.0.1`
    `port: 5200`
    
`proxy-groups:`
   `- name: "auto"`
    `type: url-test`
    `proxies:`
      `- vmess`
      `- ssr`
    `url: 'http://www.gstatic.com/generate_204'`
    `interval: 300`

  `- name: "fallback-auto"`
    `type: fallback`
    `proxies:`
      `- vmess`
      `- ssr`
    `url: 'http://www.gstatic.com/generate_204'`
    `interval: 300`

   `- name: "load-balance"`
    `type: load-balance`
    `proxies:`
      `- vmess`
      `- ssr`
    `url: 'http://www.gstatic.com/generate_204'`
    `interval: 300`

  `- name: Proxy`
    `type: select`
    `proxies:`
      `- vmess`
      `- ssr`
      `- auto`   

`rules:`
    `#网易云`
  `- DOMAIN-SUFFIX,music.163.com,unblockmusic`
  `- DOMAIN-SUFFIX,interface.music.163.com,unblockmusic`
  `- DOMAIN-SUFFIX,interface3.music.163.com,unblockmusic`
  `- DOMAIN-SUFFIX,apm.music.163.com,unblockmusic`
  `- DOMAIN-SUFFIX,apm3.music.163.com,unblockmusic`
  `- DOMAIN-SUFFIX,man.netease.com,unblockmusic`
  `- DOMAIN-SUFFIX,api.iplay.163.com,unblockmusic`
  `- IP-CIDR,39.105.63.80/32,unblockmusic`
  `- IP-CIDR,45.254.48.1/32,unblockmusic`
  `- IP-CIDR,47.100.127.239/32,unblockmusic`
  `- IP-CIDR,59.111.160.195/32,unblockmusic`
  `- IP-CIDR,59.111.160.197/32,unblockmusic`
  `- IP-CIDR,59.111.181.35/32,unblockmusic`
  `- IP-CIDR,59.111.181.38/32,unblockmusic`
  `- IP-CIDR,59.111.181.60/32,unblockmusic`
  `- IP-CIDR,101.71.154.241/32,unblockmusic`
  `- IP-CIDR,103.126.92.132/32,unblockmusic`
  `- IP-CIDR,103.126.92.133/32,unblockmusic`
  `- IP-CIDR,112.13.119.17/32,unblockmusic`
  `- IP-CIDR,112.13.122.1/32,unblockmusic`
  `- IP-CIDR,115.236.118.33/32,unblockmusic`
  `- IP-CIDR,115.236.121.1/32,unblockmusic`
  `- IP-CIDR,118.24.63.156/32,unblockmusic`
  `- IP-CIDR,193.112.159.225/32,unblockmusic`
  `- IP-CIDR,223.252.199.66/32,unblockmusic`
  `- IP-CIDR,223.252.199.67/32,unblockmusic`

  `# LAN`
  `- DOMAIN,injections.adguard.org,DIRECT`
  `- DOMAIN,local.adguard.org,DIRECT`
  `- DOMAIN-SUFFIX,local,DIRECT`
  `- IP-CIDR,127.0.0.0/8,DIRECT`
  `- IP-CIDR,172.16.0.0/12,DIRECT`
  `- IP-CIDR,192.168.0.0/16,DIRECT`
  `- IP-CIDR,10.0.0.0/8,DIRECT`
  `- IP-CIDR,17.0.0.0/8,DIRECT`
  `- IP-CIDR,100.64.0.0/10,DIRECT`
  
  `- GEOIP,CN,DIRECT`
  `- MATCH,Proxy`

**Comment by lizenghui** [comment]
> ### Clash config
> tun:
> enable: true
> stack: system # or gvisor
> dns-listen: 0.0.0.0:53
> dns-hijack:
> - tls://dns.google:853
> - 8.8.8.8:53
> 
> ### Clash log
> level=debug msg="Proxy UDP is not supported"
> 
> ### 环境 Environment
> * 操作系统 (the OS that the Clash core is running on)
>   Debian 10.6
> 
> ### 说明 Description
> 同一个config下,使用最新1.2的Premium版并启用tun后udp连接无法被正确代理,退回到1.1版后一切正常.
> 
> **我预期会发生……？**
> 
> 正确代理tcp与udp流量.
> **实际上发生了什么？**
> 
> TCP流量正常, udp流量被return.

进程必须root用户启动！
