### ISSUE TITLE
[Bug]华为云Ubuntu系统，配置文件external-controller 127.0.0.1与0.0.0.0问题

### ISSUE THREAD

**Issue by qianli2017** [Dreamacro/clash#1013]
使用华为云Ubuntu系统，安装了clash，配置好相关，执行，得到提示：
。。。。   
INFO[0000] Start initial compatible provider ♻️ 自动选择    
INFO[0000] RESTful API listening at: 127.0.0.1:9090       
INFO[0000] HTTP proxy listening at: :7890               
INFO[0000] SOCKS proxy listening at: :7891
华为云提供了IPv4弹性公网IP，防火墙开放9090等端口后，用弹性公网IP:9090无法访问。

而同时在该VPS上安装的Nginx服务器可正常访问80端口，显示的端口信息如下：
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1009/nginx: master
tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      998/clash               （注意此处的差别） 

于是我试着更改config.yaml中的127.0.0.1 为0.0.0.0，重启后得到如下提示：
。。。。   
INFO[0000] Start initial compatible provider ♻️ 自动选择    
INFO[0000] RESTful API listening at: 0.0.0.0:9090       
INFO[0000] HTTP proxy listening at: :7890               
INFO[0000] SOCKS proxy listening at: :7891

但实际上查看端口情况，如下：
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1009/nginx: master
tcp6      0      0 :::9090                 0.0.0.0:*               LISTEN      998/clash               （注意此处的差别）

查询资料知道关键一点：
如果端口查看出是0.0.0.0这种情况，则外部网络可正常访问，而如果是127.0.0.1则只能本机访问。
请求解决：
当配置中写为0.0.0.0时，能否在运行clash后，正确配置端口为准确的如查看到的0.0.0.0:9090，而不是:::9090。

请解决这个问题。感谢你们的付出。

**Comment by kallydev** [comment]
这是预期行为并不是 Bug，叫 Dual-stack IP
可以参考 https://github.com/golang/go/issues/9334
