### ISSUE TITLE
[Feature] 希望provider能在remote config更新的同时一起更新

### ISSUE THREAD

**Issue by Sansui233** [Dreamacro/clash#1015]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Mac OS 10.14.6
* 使用者的操作系统 (the OS running on the client)
Mac OS 10.14.6
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

希望能够在更新remote config的同时，也能更新相关的provider。

在本地测试provider时，发现目前的provider只会根据interval更新，无法在更新config时更新。如果想强制更新provider只能删掉已下载的provider文件。虽然这并非无法解决的问题，但算是非常麻烦的操作。

部署到远程服务器上时，当有一段时间服务器维护处于不可用状态后，只能根据interval更新的provider也会变得不可用。

**Comment by Dreamacro** [comment]
可以在ui界面上点选“更新”

**Comment by Sansui233** [comment]
感谢，Clash for windows的GUI可以，ClashX还不行，应该在GUI的repo提个issue

**Comment by Dreamacro** [comment]
clashx 可以,打开 dashboard 操作

**Comment by Sansui233** [comment]
> clashx 可以,打开 dashboard 操作

好的，我之前可能瞎了，现在看见了在provider右上角
