### ISSUE TITLE
无法启动clash

### ISSUE THREAD

**Issue by Caesar-Victory** [Dreamacro/clash#1016]
开发者您好！操作系统版本为: Ubuntu 20.04.1LTS 在使用命令 ./clash-freebsd-clash-v1.2.0 -d .运行时出现报错：段错误，核心已转储,请求帮助！万分感谢

**Comment by Dreamacro** [comment]
Ubuntu 是 linux

**Comment by Caesar-Victory** [comment]
开发者您好！
ubuntu是基于Debian的发行版，使用Linux内核这一点我很清楚。在使用Clash的时候，我无法使用,提示为：段错误，核心已转储，附截图，以及文件夹权限状态
附加信息：您开发的软件已经被正确识别为可执行文件，权限已经勾选，但是不能用鼠标点按直接启动，当然命令仍然不行。
望回复，谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dreamacro/clash"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 上午10:02
收件人:&nbsp;"Dreamacro/clash"<clash@noreply.github.com&gt;;
抄送:&nbsp;"419997284"<419997284@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Dreamacro/clash] 无法启动clash (#1016)





 
Ubuntu 是 linux

**Comment by fenguoerbian** [comment]
你用着linux但是下了个bsd的版本
