### ISSUE TITLE
[Bug]clash使用ssr节点的协议参数格式为"端口:参数"时,如果参数中含有":",clash无法使用该节点

### ISSUE THREAD

**Issue by fairythm** [Dreamacro/clash#1019]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by nameless3721** [comment]
![image](https://user-images.githubusercontent.com/50364156/96352658-d7504900-10ff-11eb-96c0-685ccc5ae5ad.png)
无问题的 请检查是否服务端或客户端配置错误协议参数是用来作单端口鉴权带:是常态

**Comment by ouyangrui** [comment]
确实无法使用，单端口ssr  同一线路  小飞机正常使用  clash一直无法连接，希望检查一下bug

**Comment by nameless3721** [comment]
> 确实无法使用，单端口ssr 同一线路 小飞机正常使用 clash一直无法连接，希望检查一下bug

那肯定是你参数格式错误 这边一直正常用
