### ISSUE TITLE
http://clash.razord.top

### ISSUE THREAD

**Issue by Maplebb** [Dreamacro/clash#1021]
操作系统：linux ubuntu 20.04
配置好服务配置文件，将网络代理调整好后在terminal打开clash后连接http://clash.razord.top显示连接被重置，无法进入dashbroad。

**Comment by Dreamacro** [comment]
试试先把代理关掉或者把这个地址加到白名单上？

**Comment by Maplebb** [comment]
请问把地址加到白名单是指用ufw允许9090端口的访问吗

**Comment by Maplebb** [comment]
把代理关掉不行，但是网页错误的显示会有变化，错误显示从此网页无法正常运作变成了无法访问此网页

**Comment by Dreamacro** [comment]
这只是一个正常的网页，不需要运行 clash 也能打开，要是真的打不开我也不知道是什么问题了

**Comment by Maplebb** [comment]
尝试了用sudo ufw allow 9090添加端口白名单后谷歌和其他外网可以正常使用，但是http://clash.razord.top仍然无法打开，显示连接被重置，请问是否有解决办法呢？

**Comment by Maplebb** [comment]
还有我在手机上尝试了下，http://clash.razord.top不运行clash无法正常打开，手机上运行了clash能正常打开。

**Comment by nameless3721** [comment]
![image](https://user-images.githubusercontent.com/50364156/96352727-842ac600-1100-11eb-8a4c-b80b84203788.png)
该网址已被部分运营商污染 打不开请 dig clash.razord.top 检查返回ip  该网址污染不算大用 223.5.5.5 dns一般就能正确解析 解析正确还打不开 可以尝试直连是否 tcping clash.razord.top ip是否正确和是否连通
