### ISSUE TITLE
建议调整规则优先级

### ISSUE THREAD

**Issue by Mycroft-Hu** [Dreamacro/clash#1023]
在使用qBittorrent这类BT软件下载的时候，难免会遇到连接到国外的IP。在打开了TAP模式的时候，qBittorrent连接到的IP如果匹配了就会通过Proxy来连接，而我在配置文件中设置了qBittorrent,DIRECT，但是仍然会走Proxy，如果能调整为，优先用户的配置，忽略其他的规则，这样就会好很多。

### 环境 Environment
* Clash Core 的操作系统 (the OS that the Clash core is running on)
0.12.1
* 使用者的操作系统 (the OS running on the client)
Windows 10 2004

**Comment by Dreamacro** [comment]
issue 与本项目没有直接联系
