### ISSUE TITLE
【问题咨询】clash 的 fake-ip 功能是否跟 shadowsocks 的 remote-dns 是一回事？

### ISSUE THREAD

**Issue by kbore** [Dreamacro/clash#1024]
按照下面链接的说法：
当 TCP 连接建立时，Clash DNS 会直接返回一个保留地址的 IP（即 Fake IP；Clash 默认使用 198.18.0.0/16，下文以此为例），同时 Clash 继续解析域名规则和 IP 规则。
https://blog.skk.moe/post/alternate-surge-koolclash-as-gateway/

我的问题是 Clash 如何继续解析域名的？我的猜测有几种
1. 直接由本机向配置文件里的 nameserver 请求DNS解析？但是我访问私网的自建域名也是 OK，这个无法解释。
2. 实际上走 remote-dns，那么问题又来了，remote-dns 解析的话，对应的 dns 地址是谁？默认 remote server吗？

综上，我想知道在 clash 上如何配置才能实现 remote-dns 功能的？

**Comment by Dreamacro** [comment]
只要能拿到域名，就是 remote-dns

**Comment by kbore** [comment]
> 只要能拿到域名，就是 remote-dns

理论上是这样的，但是感觉跟 clash 配置文件对不上。配置项里没有开 dns 时，内网域名解析失败的，但是科学上网地址解析是OK的。就感觉很奇怪。

**Comment by Dreamacro** [comment]
没开 dns 的时候, 用的是 go 默认的 dns resolver 也就是走系统的 dns

**Comment by nameless3721** [comment]
> > 只要能拿到域名，就是 remote-dns
> 
> 理论上是这样的，但是感觉跟 clash 配置文件对不上。配置项里没有开 dns 时，内网域名解析失败的，但是科学上网地址解析是OK的。就感觉很奇怪。

因为拿到域名就远程解析 所以本地结果只对直连有用 走代理是直接把域名传送到服务器就没什么用即使空ip 服务器能解析就可以了 (本地解析结果可能只是用来匹配 IP-CIDR规则用吧?)
![image](https://user-images.githubusercontent.com/50364156/96352609-6577ff80-10ff-11eb-994b-3552b43d9090.png)ss服务端log是直接得到clash发送的域名来解析

**Comment by kbore** [comment]
> > > 只要能拿到域名，就是 remote-dns
> > 
> > 
> > 理论上是这样的，但是感觉跟 clash 配置文件对不上。配置项里没有开 dns 时，内网域名解析失败的，但是科学上网地址解析是OK的。就感觉很奇怪。
> 
> 因为拿到域名就远程解析 所以本地结果只对直连有用 走代理是直接把域名传送到服务器就没什么用即使空ip 服务器能解析就可以了 (本地解析结果可能只是用来匹配 IP-CIDR规则用吧?)
> ![image](https://user-images.githubusercontent.com/50364156/96352609-6577ff80-10ff-11eb-994b-3552b43d9090.png)ss服务端log是直接得到clash发送的域名来解析



> 没开 dns 的时候, 用的是 go 默认的 dns resolver 也就是走系统的 dns

感谢两位的答疑, 这段时间无意间翻到一篇博客详细解释了这个问题.  
- [浅谈在代理环境中的 DNS 解析行为 | Sukka's Blog](https://blog.skk.moe/post/what-happend-to-dns-in-proxy/)
