### ISSUE TITLE
[Bug]路由器开启TUN分流自身流量时，启用fakeip出现回环

### ISSUE THREAD

**Issue by vernesong** [Dreamacro/clash#1025]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
openwrt
* 网路环境或拓扑 (network conditions/topology)
单臂路由
* iptables，如果适用 (if applicable)
iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -j MARK --set-mark 0x162
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. 给予cap_net_admin权限后使用nobody用户启动clash的tun，模式为fakeip
2.在防火墙中主要使用以下命令绕过内核发出的流量以实现路由器本机代理
iptables -t mangle -A OUTPUT -m owner ! --uid-owner 65534 -j MARK --set-mark 0x162
3. 设置规则match, DIRECT
3. 切换其他用户尝试直接连接任意一个fakeip地址
**我预期会发生……？**

路由本机非nobody用户的流量成功分流，以上第三个步骤后连接正常（域名映射存在）或者连接失败（映射不存在）
**实际上发生了什么？**

非nobody用户流量成功分流，以上第三个步骤后开始出现表现为198.18.0.1尝试连接另一个fakeip地址的回环，此现象在启动初期容易复现。
### 可能的解决方案 Possible Solution

clash在fakeip域名映射存在时，对于直接请求fakeip的连接正常返回，找不到对应映射时则应该丢弃或拒绝此连接请求。以免在判定为直连后在路由表中又命中tun路由规则而被送回到clash。

**Comment by Dreamacro** [comment]
试试最新dev

**Comment by vernesong** [comment]
昨天测试看到redir模式下tun也会回环，本机和下游客户端只要向fakeip地址发送请求，在判定为DIRECT时就会复现，下游请求可以DROP，但本机的这种流量可能也需要return掉。

**Comment by vernesong** [comment]
解决，dev绑定interface
