### ISSUE TITLE
TUN system模式下 ，同设备下wireguard过来的数据处理有问题，无法上外网

### ISSUE THREAD

**Issue by Esinchung** [Dreamacro/clash#1026]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```
interface-name: eth0
mixed-port: 7890
#redir-port: 23456
socks-port: 1080
allow-lan: true
mode: Rule
log-level: debug
external-controller: 0.0.0.0:6170
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.19.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'time.windows.com'
    - 'time.nist.gov'
    - 'time.apple.com'
    - 'time.asia.apple.com'
    - '*.ntp.org.cn'
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
  fall-back:
    - tcp://8.8.8.8:53
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 255.255.255.255/32
tun:
  enable: true
  stack: system
  dns-hijack:
    - tcp://8.8.8.8:53
    - 8.8.8.8:1053
</details>

### Clash log

```
……
```
- 2020-10-18 08:30:50[debug] Final UDP is not supported
- 2020-10-18 08:30:50[info] [UDP] 10.0.10.216:123 --> 198.18.11.158 doesn't match any rule using DIRECT
- 2020-10-18 08:30:50[info] [TCP] 10.0.10.85:36764 --> clients4.google.com match DomainKeyword(google) using ✅C[🇭🇰A1z]
- 2020-10-18 08:30:51[info] [TCP] 10.66.66.2:55489 --> www.googleapis.com match DomainKeyword(google) using ✅C[🇭🇰A1z]
- 2020-10-18 08:30:52[info] [TCP] 10.66.66.2:63580 --> www.google.com match DomainKeyword(google) using ✅C[🇭🇰A1z]
- 2020-10-18 08:30:54[info] [TCP] 10.66.66.2:63581 --> www.google.com match DomainKeyword(google) using ✅C[🇭🇰A1z]
- 2020-10-18 08:30:54[warning] dial DIRECT error: dial tcp4 10.0.10.2:0->74.125.203.188:5228: i/o timeout
- 2020-10-18 08:30:55[debug] [DNS] response msg empty: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0x5fa0, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:"www.google.com.", Qtype:0x41, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}
- 2020-10-18 08:30:55[info] [TCP] 10.66.66.2:55490 --> www.google.com match DomainKeyword(google) using ✅C[🇭🇰A1z]
### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
armv8 archlinux （N1设备）
* 网路环境或拓扑 (network conditions/topology)
手机-wireguard-client>N1旁路由-wireguardserver>N1-clash-Premium-Tun>主路由>外网
旁路由：10.0.10.2
主路由：10.0.10.1
wireguard：10.66.66.1
# ip route show
default via 10.0.10.1 dev eth0 proto static 
10.0.10.0/24 dev eth0 proto kernel scope link src 10.0.10.2 
10.66.66.0/24 dev wg0 proto kernel scope link src 10.66.66.1 
198.19.0.0/16 dev utun proto kernel scope link src 198.19.0.1
# ip rule                                   
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……无
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

预期两种模式都可以
**实际上发生了什么？**

system内核模式下在上述特殊环境下有问题，手机端表现为无法上外网，只能内网访问
局域网下，system模式是正常工作的

**Comment by Esinchung** [comment]
Clash 2020.10.17.gf7c455b linux arm64 Sat Oct 17 07:13:48 UTC 2020

**Comment by Esinchung** [comment]
同内核相同配置改成gvisor模式是没问题的

**Comment by Dreamacro** [comment]
我这里跑基于 wireguard 的 tailscale 是正常的

拓扑: mbp-tailscale-client > NUC-clash > 主路由 > 外网

**Comment by Esinchung** [comment]
测试环境可能不同，用手机移动网络连接vpn到家会无法上外网，奇怪同内核gvisor一点问题没有，不纠结了，目前用gvisor也好用的，谢谢

**Comment by Esinchung** [comment]
搞定了，是我的wireguard配置问题，加一条 iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT 就ok了

**Comment by sunliang711** [comment]
> 搞定了，是我的wireguard配置问题，加一条 iptables -A FORWARD -i eth0 -o wg0 -j ACCEPT 就ok了

请教以下，我的wireguard是跑在docker里的，这条规则怎么修改呢？
