### ISSUE TITLE
Clash 性能问题

### ISSUE THREAD

**Issue by vonnyfly** [Dreamacro/clash#1027]
Clash 在 AC66U B1 路由器只能跑到 15MB/s, CPU 就 96%了. 停掉 clash 后可以跑 50MB/s.
在不换路由器的方法下,有进一步提升性能的方法吗?

**Comment by Dreamacro** [comment]
不要用 TUN 改用 redir 和 tproxy

**Comment by xuan880** [comment]
推荐tun和redir混用,redir处理tcp,tun处理udp.

**Comment by DotWho** [comment]
> 推荐tun和redir混用,redir处理tcp,tun处理udp.

如何混用，指导下

**Comment by vonnyfly** [comment]
这就是使用 redir + iptables。
直连下只进行规则匹配，性能就上不去。

**Comment by nameless3721** [comment]
MerlinClash 有 大陆IP白名单绕行 模式了 可以试试

**Comment by vonnyfly** [comment]
已更新路由器到 AC 86U，不存在性能问题了。
