### ISSUE TITLE
设置透明路由时, POSTROUTING与-m owner --uid-owner冲突

### ISSUE THREAD

**Issue by Cirn09** [Dreamacro/clash#1029]
参考https://github.com/Dreamacro/clash/issues/158 设置透明路由，其他部分都没问题，
唯独
```
iptables -t nat -A PREROUTING -p tcp -j clash
iptables -t nat -A clash -m owner --uid-owner 1002 -j RETURN
```
这两条互斥，设置了任意一个后，另一个就会报错

```
iptables v1.8.2 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in xxx
```
单独设置就没有问题

下面是完整配置
```
# Generated by xtables-save v1.8.2 on Mon Oct 19 21:21:22 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:clash - [0:0]
#-A POSTROUTING -s 192.168.0.0/24 -j MASQUERADE
-A PREROUTING -p tcp -j clash
-A OUTPUT -p tcp -j clash

-A POSTROUTING -s 192.168.0.0/24 -j MASQUERADE

-A clash -d 10.0.0.0/24 -j RETURN
-A clash -d 127.0.0.0/8 -j RETURN
-A clash -d 127.16.0.0/12 -j RETURN
-A clash -d 127.0.0.0/8 -j RETURN
-A clash -d 192.168.0.0/16 -j RETURN
-A clash -d 255.255.255.255/32 -j RETURN
#-A clash -m owner --uid-owner 1002 -j RETURN
-A clash -p tcp -j REDIRECT --to-ports 51423
-A PREROUTING -p tcp -j clash
-A OUTPUT -p tcp -j clash


COMMIT
# Completed on Mon Oct 19 21:21:22 2020
# Generated by xtables-save v1.8.2 on Mon Oct 19 21:21:22 2020
```
求教透明路由的正确姿势

**Comment by DotWho** [comment]
> 参考#158 设置透明路由，其他部分都没问题，
> 唯独
> 
> ```
> iptables -t nat -A PREROUTING -p tcp -j clash
> iptables -t nat -A clash -m owner --uid-owner 1002 -j RETURN
> ```
> 
> 这两条互斥，设置了任意一个后，另一个就会报错
> 
> ```
> iptables v1.8.2 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in xxx
> ```
> 
> 单独设置就没有问题
> 
> 下面是完整配置
> 
> ```
> # Generated by xtables-save v1.8.2 on Mon Oct 19 21:21:22 2020
> *nat
> :PREROUTING ACCEPT [0:0]
> :INPUT ACCEPT [0:0]
> :POSTROUTING ACCEPT [0:0]
> :OUTPUT ACCEPT [0:0]
> :clash - [0:0]
> #-A POSTROUTING -s 192.168.0.0/24 -j MASQUERADE
> -A PREROUTING -p tcp -j clash
> -A OUTPUT -p tcp -j clash
> 
> -A POSTROUTING -s 192.168.0.0/24 -j MASQUERADE
> 
> -A clash -d 10.0.0.0/24 -j RETURN
> -A clash -d 127.0.0.0/8 -j RETURN
> -A clash -d 127.16.0.0/12 -j RETURN
> -A clash -d 127.0.0.0/8 -j RETURN
> -A clash -d 192.168.0.0/16 -j RETURN
> -A clash -d 255.255.255.255/32 -j RETURN
> #-A clash -m owner --uid-owner 1002 -j RETURN
> -A clash -p tcp -j REDIRECT --to-ports 51423
> -A PREROUTING -p tcp -j clash
> -A OUTPUT -p tcp -j clash
> 
> 
> COMMIT
> # Completed on Mon Oct 19 21:21:22 2020
> # Generated by xtables-save v1.8.2 on Mon Oct 19 21:21:22 2020
> ```
> 
> 求教透明路由的正确姿势

https://lancellc.gitbook.io/clash/start-clash/clash-udp-tproxy-support

**Comment by lizenghui** [comment]
> 参考#158 设置透明路由，其他部分都没问题，
> 唯独
> 
> ```
> iptables -t nat -A PREROUTING -p tcp -j clash
> iptables -t nat -A clash -m owner --uid-owner 1002 -j RETURN
> ```
> 
> 这两条互斥，设置了任意一个后，另一个就会报错
> 
> ```
> iptables v1.8.2 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in xxx
> ```
> 
> 单独设置就没有问题
> 
> 下面是完整配置
> 
> ```
> # Generated by xtables-save v1.8.2 on Mon Oct 19 21:21:22 2020
> *nat
> :PREROUTING ACCEPT [0:0]
> :INPUT ACCEPT [0:0]
> :POSTROUTING ACCEPT [0:0]
> :OUTPUT ACCEPT [0:0]
> :clash - [0:0]
> #-A POSTROUTING -s 192.168.0.0/24 -j MASQUERADE
> -A PREROUTING -p tcp -j clash
> -A OUTPUT -p tcp -j clash
> 
> -A POSTROUTING -s 192.168.0.0/24 -j MASQUERADE
> 
> -A clash -d 10.0.0.0/24 -j RETURN
> -A clash -d 127.0.0.0/8 -j RETURN
> -A clash -d 127.16.0.0/12 -j RETURN
> -A clash -d 127.0.0.0/8 -j RETURN
> -A clash -d 192.168.0.0/16 -j RETURN
> -A clash -d 255.255.255.255/32 -j RETURN
> #-A clash -m owner --uid-owner 1002 -j RETURN
> -A clash -p tcp -j REDIRECT --to-ports 51423
> -A PREROUTING -p tcp -j clash
> -A OUTPUT -p tcp -j clash
> 
> 
> COMMIT
> # Completed on Mon Oct 19 21:21:22 2020
> # Generated by xtables-save v1.8.2 on Mon Oct 19 21:21:22 2020
> ```
> 
> 求教透明路由的正确姿势

貌似是冲突的啊   -m owner --uid-owner 应该只能用在本机流量吧  你用在PREROUTING上当然冲突了。
