### ISSUE TITLE
DNS请求都失败后，在内部进行重试

### ISSUE THREAD

**Issue by Fndroid** [Dreamacro/clash#103]
Chrome浏览器在DNS请求失败后，1分钟内不会再重试，页面显示不能找到IP地址，在短时间内不能访问网页。
Clash内部可以考虑进行重试保障DNS能进行响应，代理机器出现网络波动也是比较常见的

**Comment by comzyh** [comment]
怪不得我每次出现 Chrome 报告 `DNS_PROBE_FINISHED_NXDOMAIN`  的时候，去 dig 看都一切正常。

**Comment by Dreamacro** [comment]
@comzyh 
`DNS_PROBE_FINISHED_NXDOMAIN` 发生的原因可能是因为没有解析 `Extra` 中的 A/AAAA 记录，dev 分支已经补上了

**Comment by Fndroid** [comment]
大半天测试，似乎正常了

**Comment by Fndroid** [comment]
今天访问gist的时候又出现了，依然是那个被污染的ip（243.185.187.39）
