### ISSUE TITLE
如何让局域网里某一台主机直接走代理，而其他按照配置分配

### ISSUE THREAD

**Issue by Eintler** [Dreamacro/clash#1032]
clash部署到路由器

这样配置- IP-CIDR,192.168.0.0/16,DIRECT

局域网里所有主机直连，但是比如让192.168.1.2这台主机访问网址时只走代理，其他机器还是按照配置走呢。

应该如何修改配置文件，还是目前clash不支持呢？

先不考虑192.168.1.2这台主机自己安装clash的情况。

**Comment by Dreamacro** [comment]
`192.168.1.2/32`

**Comment by Eintler** [comment]
- SRC-IP-CIDR,192.168.1.200/32,auto,no-resolve
这样是吧 @Dreamacro 
多谢啦
