### ISSUE TITLE
Request for redistributing the premium version

### ISSUE THREAD

**Issue by DDoSolitary** [Dreamacro/clash#1033]
Hello, I'm a package maintainer from [Arch Linux CN Community](https://github.com/archlinuxcn) and I'm considering packaging the premium version of clash and redistributing it through the [archlinuxcn package repository](https://repo.archlinuxcn.org/) to make it easier to install on Arch Linux systems.

As the premium version is close-sourced and I couldn't find any license or EULA for it, here I'm asking for permission to redistribute the binaries.

If you agree, I will:

- package the binaries using the script from the [clash-premium-bin](https://aur.archlinux.org/packages/clash-premium-bin/) AUR package, which doesn **not** modify the binaries but only adds some auxiliary files (e.g. systemd unit files).
- upload the package to the [archlinuxcn package repository](https://repo.archlinuxcn.org/), which is publicly accessible.
- **not** make profits from the packages we provide.

**Comment by Dreamacro** [comment]
Sure, but at the moment only docker images are updated rollingly (using GitHub actions published in dreamacro/clash-premium). premium version on github releases generally follows normal releases.

**Comment by Dreamacro** [comment]
One thing to note is that when a new version is released, the download link for the old version will not work (overwrite the release)

**Comment by DDoSolitary** [comment]
Thanks for the info! The package is now available at https://repo.archlinuxcn.org/

> Sure, but at the moment only docker images are updated rollingly (using GitHub actions published in dreamacro/clash-premium). premium version on github releases generally follows normal releases.

I think it's better to follow normal releases for a distro package so it is OK to use the files from GitHub Releases

> One thing to note is that when a new version is released, the download link for the old version will not work (overwrite the release)

Generally once the package is built, it won't be built again until the AUR package maintainer updates the build script (which normally occurs when you release a new version), so I think it's no big deal.

> I cannot find a good place to distribute artifacts.

I've also tried several services for distributing dev snapshots for some of my own projects. Probably you can take a look at SourceForge's web hosting service, which allows you to use SFTP to manage files with a limitation on single file size (about several hundred megabytes). My dev snapshot download site: https://ddosolitary-builds.sourceforge.io/

**Comment by DCjanus** [comment]
Hi, would you mind to release pemium versions with version tag? I'm trying to package clash-premium to [NixOS](https://nixos.org/), to reproducible build, there would be really nice to have a persistence release, rather than something might be overrided.

I'm not very familiar with github release, looks like that we've able to release specific version without code:
![图片](https://user-images.githubusercontent.com/15802727/149790687-fb04a14d-d6ef-4368-ade1-7a98f47af0b0.png)

And looks fine:
![图片](https://user-images.githubusercontent.com/15802727/149790790-b777c0b9-fcae-47eb-a616-289a5b57c981.png)

**Comment by Dreamacro** [comment]
@DCjanus 我也想有个地方能够放置这些二进制文件，但是目前并没有发现一个合适的地方

**Comment by DCjanus** [comment]
能大概了解一下现在不太期望放在 GitHub Release 的原因吗？从我的理解来说，只要给每个 premium  版本的二进制打一个形如 `premium-2022.01.03` 的版本号，好像就可以持久化存储了。

**Comment by Dreamacro** [comment]
@DCjanus 因为 premium 是闭源的，所以在另一个仓库的不准确的 commit 打 tag 没有太多意义

**Comment by DCjanus** [comment]
了解了，我也看看能不能找到一些比较合适的办法存放这些二进制。

我看到目前 NixOS 的构建函数里支持了从 IPFS 上拉取文件，你会介意我尽可能多的存放尝试存放在 IPFS 上吗？

其实我的另一个想法是单独开一个 GitHub repo，存放历史版本的 premium。
