### ISSUE TITLE
[Feature]Premium版本增加freebsd tun支持

### ISSUE THREAD

**Issue by zh-yjie** [Dreamacro/clash#1035]
freebsd12.1
启动Premium版本clash日志：ERRO[0000] Start Tun interface error: CreateTUN not supported on current platform。
希望增加freebsd tun的支持

**Comment by yuanl** [comment]
I will be great if Clash can run on some BSD based firewall in Tun mode.

**Comment by Dreamacro** [comment]
@yuanl add this feature to the next milestone

**Comment by yuanl** [comment]
Let me know if you need a test helping hand.

**Comment by Dreamacro** [comment]
[clash-freebsd-amd64.zip](https://github.com/Dreamacro/clash/files/5898243/clash-freebsd-amd64.zip)

@yuanl 

NOTE:
1. SetGateway may not work, it uses macOS code now.
2. interface-name use syscall on macOS and Linux, but use the binding local address on FreeBSD (https://github.com/Dreamacro/clash/blob/master/component/dialer/bind_others.go)

**Comment by yuanl** [comment]
@Dreamacro this build work well on my `12.1-RELEASE-p12-HBSD`
However, it shows below output if I send `INT` signal to clash with `ctrl-C`.
```
...
DEBU[0197] Packet Received error: read /dev/tun: file already closed
DEBU[0197] Packet Received error: read /dev/tun: file already closed
DEBU[0197] Packet Received error: read /dev/tun: file already closed
DEBU[0197] Packet Received error: read /dev/tun: file already closed
```

**Comment by Dreamacro** [comment]
TUN device and stack(system, gvisor) are decoupled. Are you sure that gvisor mode created the TUN correctly and bind the gateway properly?

**Comment by Dreamacro** [comment]
@yuanl any progress?
