### ISSUE TITLE
tunnel包里的tcpQueue和udpQueue问题

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#1038]
# tcpQueue

https://github.com/Dreamacro/clash/blob/b1795b1e3d13a2c8898fc457b7b8b4147b41f4ee/tunnel/tunnel.go#L19

因为process里handleTCP都是直接从通道里读一个conn然后马上就用goroutine执行了

https://github.com/Dreamacro/clash/blob/b1795b1e3d13a2c8898fc457b7b8b4147b41f4ee/tunnel/tunnel.go#L105-L108

所以这里直接用无缓冲通道应该就够了吧🤔

# udpQueue

https://github.com/Dreamacro/clash/blob/b1795b1e3d13a2c8898fc457b7b8b4147b41f4ee/tunnel/tunnel.go#L97-L103

这里因为UDP的包处理是用worker的，所以应该有一定概率在包多的时候udpQueue的缓冲会满，导致上层调用AddPacket的地方可能会阻塞

https://github.com/Dreamacro/clash/blob/b1795b1e3d13a2c8898fc457b7b8b4147b41f4ee/tunnel/tunnel.go#L43-L46

所以这里像这样写，选择在阻塞的时候直接把包丢了是不是更好一点？（不过这里问题不是很大😑）

```go
func AddPacket(packet utils.UDPPacket) {
	select {
	case udpQueue <- packet:
	default:
		// do something?
	}
}
```

**Comment by Dreamacro** [comment]
tcpQueue 这边倒没啥疑问，带 buffer 的 channel 并不会造成多么大的资源浪费

udpQueue 这边我实际用 iperf 测试了一下，吞吐量和 CPU 占用两者都差不多，没有明显的改善

**Comment by xjasonlyu** [comment]
啊这，我后来试了一下，不用infiniteChannel之后，UDP多（比如同时有几千个包）的时候似乎会造成不同程度的延时，对于UDP来说延时应该比吞吐量更重要吧👀

iperf3单线程或者哪怕加参数-P128最多就100+的同地址UDP包，所以不太能明显感受到，但是多开几个进程跑着，在用比如DNS工具去测现在的延时，应该就能感觉到抖动。

另外一点是UDP包多的时候会调用产生大量日志

https://github.com/Dreamacro/clash/blob/b1795b1e3d13a2c8898fc457b7b8b4147b41f4ee/log/log.go#L32-L36

这里写到`logCh`的时候也可能因为`observable`包处理不及时（尤其是在另一边请求API的/logs时）导致某个UDP worker又阻塞了一下🤔然后大概就这个意思

所以有没有更好一点的解决方案？

**Comment by Dreamacro** [comment]
observable 里有个 benchmark，在那个 benchmark 下，不使用 infiniteChannel 的情况下结果比较可观，这也是为什么移除 infiniteChannel （另一个原因是这个仓库没有跟进新的 go 约定了，即 go module）

**Comment by Dreamacro** [comment]
对于延时问题，可以在 AddPacket 那直接丢包。因为处理包的能力是有限且固定的，在没法处理的情况下，不允许阻塞的话只能丢包。丢包应该是比较好的方式，避免产生背压

**Comment by xjasonlyu** [comment]
是的，设置一个合适的udpQueue缓冲大小做无阻塞写入就好了

**Comment by Dreamacro** [comment]
所以这个 udp queue 的缓冲设置多少合适呢
