### ISSUE TITLE
[Bug] tunnel UDP race condition

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#1039]
刚开了个-race参数跑了一下测试，然后看到了这个race问题。

问题出在handleUDP是有多个workers的，当多个同样key的UDP包到tunnel时
https://github.com/Dreamacro/clash/blob/ba060bd0eee01c5a537311591aca7dea5c7f1fca/tunnel/tunnel.go#L185-L186

会拿到一个waitgroup和loaded

第一个拿到loaded的goroutine会在判断完后调用Add
https://github.com/Dreamacro/clash/blob/ba060bd0eee01c5a537311591aca7dea5c7f1fca/tunnel/tunnel.go#L189-L190

其余的会直接调用Wait
https://github.com/Dreamacro/clash/blob/ba060bd0eee01c5a537311591aca7dea5c7f1fca/tunnel/tunnel.go#L225

因为是多个workers，这里第一个key的UDP不一定能确保在其他Wait前就调用Add，然后就race了。

**Comment by xjasonlyu** [comment]
解决办法似乎只要在启动goroutine之前

https://github.com/Dreamacro/clash/blob/ba060bd0eee01c5a537311591aca7dea5c7f1fca/tunnel/tunnel.go#L188-L190

判断调用一次Add就可以了，吧👀

**Comment by Dreamacro** [comment]
这里尽管在 wg.Add(1) 前 wg.Wait() 了，但是由于拿不到 PacketConn 而丢包，并不会产生 panic。我觉得这是一个可以接受的结果，你有什么更好的方案么

**Comment by xjasonlyu** [comment]
应该可以用条件变量sync.Cond解决，晚点PR
