### ISSUE TITLE
域名多ip如果一个ip有问题不会自动尝试其它ip

### ISSUE THREAD

**Issue by xuan880** [Dreamacro/clash#104]
例如打开v2ex的网站，本地dig解析出两个ip
www.v2ex.com.           35      IN      CNAME   global.v2ex.com.
global.v2ex.com.        55      IN      A       101.226.196.39
global.v2ex.com.        55      IN      A       115.238.195.153
看日志发现一直尝试通过115.238.195.153这个有问题的ip连接
2019-01-22 17:48:07[warning] Proxy[DIRECT] connect [www.v2ex.com] error: dial tcp 115.238.195.153:443: i/o timeout
导致网站打不开，浏览器不通过代理的话会走101.226.196.39这个正常的ip，网站打开正常。
希望clash内部在一个ip出现问题导致连接失败的时候，自动尝试使用解析出来的其它ip。

**Comment by Dreamacro** [comment]
现在不会，之后可以看一下好不好处理这个问题

**Comment by hd5970** [comment]
可以和并发DNS一样, 选择最先完成握手的那个连接

**Comment by chang-tse** [comment]
@Dreamacro 借楼反馈一个问题

启用 Clash DNS 功能，同时设置 `ipv6` 为 `true`，解析 Google 等双栈网站，返回结果只有 IPv4。接下来 Clash 也只会通过这个解析返回的 v4 地址进行连接。

请问开发者，Clash 的这种表现符合预期么？设置 `ipv6` 为 `true` 具有什么效果？

**Comment by Dreamacro** [comment]
@chang-tse 通过 HTTP/SOCKS 请求进来的域名会按 ipv6 解析。DNS Server 的话不影响解析过程，只是作为一个普通的 Server

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/blob/c0a2473160f9da2ea2116358fed33a3e6a77ae5a/dns/resolver.go#L240
