### ISSUE TITLE
个别网站无法访问

### ISSUE THREAD

**Issue by motorar** [Dreamacro/clash#1040]
个别网站无法访问
http://www.yygrammar.com/

是一家国内学习类站点。发现用安卓端clash可以正常访问，但开启windows端clash后无法访问。请验证。

**Comment by xuezhi420** [comment]
可以上 我试了下

**Comment by qiujiangkun** [comment]
我这里无法打开youtube，但可以上google
Your connection is not private
Attackers might be trying to steal your information from www.youtube.com (for example, passwords, messages, or credit cards).

**Comment by babyzhang** [comment]
我这边正常的，可能与网络环境也有关系
