### ISSUE TITLE
[Bug]经常出现全部timeout的情况，我发了日志，麻烦告知一下原因可以吗。

### ISSUE THREAD

**Issue by oyeatkuso007** [Dreamacro/clash#1045]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

### 更多信息 More Information
![QQ图片20201028100016](https://user-images.githubusercontent.com/73586683/97422889-66076600-1949-11eb-918d-84dddd4d09fa.jpg)
![QQ图片20201028100128](https://user-images.githubusercontent.com/73586683/97422905-6acc1a00-1949-11eb-9a0d-2b4f2b86a684.jpg)

**Comment by akw5454521** [comment]
服务商的DNS出现问题了吧，找服务商

**Comment by yankeeguyu** [comment]
把默认的dns内容修改一下就可以了，改成google的

**Comment by oyeatkuso007** [comment]
> 把预设的dns内容修改一下就可以了，改成google的

是改本机的DNS吗，我试过了。没用
还是要改哪里的？

**Comment by yankeeguyu** [comment]
你本地/etc/re**这个里面的nameserver

**Comment by oyeatkuso007** [comment]
> 你本地/etc/re**这个里面的nameserver

麻烦可以告知详细吗，我在C:\Windows\System32\drivers\etc没找到这个文件。还是这个nameserver是叫别的名字。我是小白

**Comment by yankeeguyu** [comment]
我还以为你是Linux或者Mac...，windows就不怎么知道了，你购买代理服务了吗？应该是你的服务问题吧！

**Comment by Dreamacro** [comment]
是 windows 版本过低

**Comment by yankeeguyu** [comment]
> 是 windows 版本过低

还以为他用的unix内核
