### ISSUE TITLE
[Bug]编辑外部控制设置

### ISSUE THREAD

**Issue by mrliu666666** [Dreamacro/clash#1046]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description
请问我这个外部控制设置哪里填写错了？

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

显示dashboard
**实际上发生了什么？**

![图片](https://user-images.githubusercontent.com/43879190/97474080-ab965400-1986-11eb-90d1-3e87a348df96.png)

**Comment by xjasonlyu** [comment]
啊这，你这Host要填的是你的Clash主机IP，而不是`0.0.0.0`啊🤦

**Comment by mrliu666666** [comment]
> 啊这，你这Host要填的是你的Clash主机IP，而不是`0.0.0.0`啊🤦
那请问除了host其他两个是那也填的吗

**Comment by xjasonlyu** [comment]
其他和config一样就可以了
