### ISSUE TITLE
[Feature]rule支持双条件吗? 比如src ip = xxx, 国内连接, ban这样的

### ISSUE THREAD

**Issue by ask-github** [Dreamacro/clash#1051]
SRC-IP-CIDR: SRC-IP-CIDR,192.168.1.201/32,DIRECT

这种加上 geo-ip,cn这种限制

**Comment by Dreamacro** [comment]
用 premium 的 script

**Comment by luvletter2333** [comment]
> 用 premium 的 script
请问premium的特性有计划开源吗？
