### ISSUE TITLE
增加如图代理设置

### ISSUE THREAD

**Issue by smile-magic** [Dreamacro/clash#1053]
![image](https://user-images.githubusercontent.com/35910947/97659467-0c6a7d00-1aaa-11eb-959c-028219f2b39d.png)

在重启电脑或者取消系统代理时,这里会清空.
打开系统代理会带入 默认 配置,自定义一些域名会丢失

希望增加可配置自定义数据功能.

需求原因: 如果不配置自定义的域名,无法访问本机host域名

**Comment by Dreamacro** [comment]
clash 有 hosts 配置

**Comment by juewuy** [comment]
可以写一个本地的pac文件

**Comment by spacexnasa** [comment]
> ![image](https://user-images.githubusercontent.com/35910947/97659467-0c6a7d00-1aaa-11eb-959c-028219f2b39d.png)
> 
> 
> 
> 在重启电脑或者取消系统代理时,这里会清空.
> 
> 打开系统代理会带入 默认 配置,自定义一些域名会丢失
> 
> 
> 
> 希望增加可配置自定义数据功能.
> 
> 
> 
> 需求原因: 如果不配置自定义的域名,无法访问本机host域名
> 
> 

clashx  github有一段高级配置，plist的，你按照操作就行了
