### ISSUE TITLE
[Bug] dns resolver client race condition

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#1056]
有多个DNS请求的时候，会在这里调用client

https://github.com/Dreamacro/clash/blob/87e4d9429098fcf2421713641426b88256d1decc/dns/resolver.go#L147-L153

然后client在这里赋值给c.Client.Dialer，就会导致竞争

https://github.com/Dreamacro/clash/blob/87e4d9429098fcf2421713641426b88256d1decc/dns/client.go#L42-L52

**Comment by Dreamacro** [comment]
这里应该还好，因为 dns 库里调用时也是只使用一次
