### ISSUE TITLE
[Bug] certificate validation in Windows fails to validate IP in SAN

### ISSUE THREAD

**Issue by oyeatkuso007** [Dreamacro/clash#1059]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

### 更多信息 More Information
![QQ图片20201028100016](https://user-images.githubusercontent.com/73586683/98092331-81cab900-1ec1-11eb-84ef-47bc3f3b08b7.jpg)
![QQ图片20201028100128](https://user-images.githubusercontent.com/73586683/98092354-87c09a00-1ec1-11eb-9b87-3244cd6a4c7f.jpg)
[2020-11-04-114036.log](https://github.com/Dreamacro/clash/files/5486769/2020-11-04-114036.log)

**Comment by Dreamacro** [comment]
先把这个 doh 改掉吧，如果你并不需要 doh 的话

**Comment by Dreamacro** [comment]
没法复现，无论是 macOS 还是 Windows 10

**Comment by trott90** [comment]
DOH理论上不能用IP的

**Comment by Dreamacro** [comment]
看起来和这个 issue 类似 https://github.com/golang/go/issues/37176

**Comment by Dreamacro** [comment]
用的是低版本的 windows 吧？
