### ISSUE TITLE
clash premium(2020.10.09) tun模式,无法代理本机,不知道哪出问题了

### ISSUE THREAD

**Issue by LSSCP** [Dreamacro/clash#1060]
请问有人来解惑吗..谢谢了.

参考https://comzyh.gitbook.io/clash/real-ip-tun-example 配置的.

把clash塞到了刚买的树莓派上当旁路由.官方raspbian系统.
主路由192.168.2.1链接光猫负责博号
pc设置树莓派地址(192.168.2.2)为网关一切正常.
但是树莓派本身无法访问被墙网站.都是直连目标地址,不按规则走代理线路.

搞不懂哪出问题了.感觉是本机出去的流量没打上标记?

..除了配置,还需要提供什么其他的log吗?

-------------------------------
系统配置
创建用户clash启动clash

adduser clash
sudo ip tuntap add mode tun user clash name utun
sudo ip link set utun up

sudo setcap cap_net_bind_service,cap_net_admin+ep /home/clash/etc/clash

-------------------------------------
sudo iptables -t mangle -N CLASH 
sudo iptables -t mangle -F CLASH
sudo iptables -t mangle -A CLASH -d 0.0.0.0/8 -j RETURN
sudo iptables -t mangle -A CLASH -d 10.0.0.0/8 -j RETURN
sudo iptables -t mangle -A CLASH -d 127.0.0.0/8 -j RETURN
sudo iptables -t mangle -A CLASH -d 169.254.0.0/16 -j RETURN
sudo iptables -t mangle -A CLASH -d 172.16.0.0/12 -j RETURN
sudo iptables -t mangle -A CLASH -d 192.168.0.0/16 -j RETURN
sudo iptables -t mangle -A CLASH -d 224.0.0.0/4 -j RETURN
sudo iptables -t mangle -A CLASH -d 240.0.0.0/4 -j RETURN

sudo iptables -t mangle -A CLASH -j MARK --set-xmark 126
sudo iptables -t mangle -A PREROUTING -j CLASH

sudo iptables -t mangle -A OUTPUT -m owner --uid-owner 1001 -j RETURN
sudo iptables -t mangle -A OUTPUT -j CLASH

sudo ip route add default dev utun table 126
sudo ip rule add fwmark 126 lookup 126

---------------------------------
clash配置:config.yaml
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
tun:
  enable: true
  stack: system
experimental:
  interface-name: en0
proxies:略
proxy-groups:略
rules:略
--------------------

**Comment by LSSCP** [comment]
本机dns第一条设成127.0.0.1后可以了...

**Comment by cqked** [comment]
> 本机dns第一条设成127.0.0.1后可以了...

所以，根本不用iptables
