### ISSUE TITLE
[Feature]建议增加针对策略组的UDP控制

### ISSUE THREAD

**Issue by We1eVen** [Dreamacro/clash#1061]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Openwrt

### 说明 Description
由于游戏加速的需求，我在Openwrt上部署了Clash，并开启了UDP转发，但是Youtube移动端会自动使用QUIC进行流媒体加载，影响使用体验。

### 可能的解决方案 Possible Solution
增加针对策略组的UDP控制，这样就可以直接禁止Youtube规则策略组的UDP通信

**Comment by akw5454521** [comment]
直接配置两个一样的proxy，udp分别true和false，Globalmedia这类group走false的那个proxy

**Comment by We1eVen** [comment]
@akw5454521 感谢分享，我也考虑过这种方式，但它既不优雅也不太方便，因为我喜欢直接使用订阅转换，而非编辑配置文件

**Comment by Dreamacro** [comment]
added at 4735f61fd1f6a5c65773eecf20600dfaeaa21568

**Comment by We1eVen** [comment]
感谢大佬

**Comment by flyhigherpi** [comment]
- name: 📹 YouTube
    type: select
    proxies:
      - 🇭🇰 香港总集
      - DIRECT
    disableUDP: true
发现油管还是访问了udp
r4---sn-i3belnls.googlevideo.com:443
📹 YouTube / 🇭🇰 香港总集 / 🇭🇰 香港IEPL / 🇭🇰 香港 IEPL+ 02 2
DomainSuffix
2 minutes
192.168.2.212:65163
173.194.4.9
Redir(udp)

**Comment by Dreamacro** [comment]
@flyhigherpi `disable-udp`

**Comment by We1eVen** [comment]
@flyhigherpi 确实如此，[相关讨论](https://github.com/Dreamacro/clash/issues/1167)刚刚看了，只能说这个功能与我们理想的控制方式不同。只能怪我自己太菜不会写script
