### ISSUE TITLE
[Feature] 希望能加入一个新功能，有多条线路的时候load-balance模式下不能很好的负载均衡

### ISSUE THREAD

**Issue by kongkong9527** [Dreamacro/clash#1062]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
无Log
```

### Clash log

```
无Log
```

### 环境 Environment

Clash、Clash Premium 两个版本的程序，在各系统中运行。

### 说明 Description

在多条线路的时候load-balance模式下，由于采用
“load-balance: The request of the same eTLD will be dial to the same proxy.”
的设计，比如看油管的视频的时候，并不能根据请求的地址负载均衡到各个线路上。同时开启多个视频的时候，视频都集中在一条线路上。
希望能增加一个“hash-balance”标签。

如下形式：

  - name: ♻️ 哈希均衡
    type: hash-balance
    url: http://www.gstatic.com/generate_204
    interval: 360
    proxies:

### 可能的解决方案 Possible Solution

代码更改如下
![image](https://user-images.githubusercontent.com/17898171/98243348-c54c2280-1fa8-11eb-9066-dcc9c7a5d7fb.png)

![image](https://user-images.githubusercontent.com/17898171/98243440-eb71c280-1fa8-11eb-9ec2-d4169908fa5a.png)

![image](https://user-images.githubusercontent.com/17898171/98243469-f4629400-1fa8-11eb-9aa9-a94cac33f7a5.png)

在 clash\adapters\outboundgroup 路径下增加一个新文件loadbalance.go
代码如下：

```golang
package outboundgroup

import (
	"context"
	"encoding/json"
	"net"

	"github.com/Dreamacro/clash/adapters/outbound"
	"github.com/Dreamacro/clash/adapters/provider"
	"github.com/Dreamacro/clash/common/murmur3"
	"github.com/Dreamacro/clash/common/singledo"
	C "github.com/Dreamacro/clash/constant"

	"golang.org/x/net/publicsuffix"
	"github.com/Dreamacro/clash/log"
)

type HashBalance struct {
	*outbound.Base
	single    *singledo.Single
	maxRetry  int
	providers []provider.ProxyProvider
}

func getHost(metadata *C.Metadata) string {
	if metadata.Host != "" {
		// ip host
		if ip := net.ParseIP(metadata.Host); ip != nil {
			return metadata.Host
		}

		if etld, err := publicsuffix.EffectiveTLDPlusOne(metadata.Host); err == nil {
			return metadata.Host
		}
	}

	if metadata.DstIP == nil {
		return ""
	}
	log.Infoln("metadata.DstIP.String()======>>[%v]", metadata.DstIP.String())
	return metadata.DstIP.String()
}

func (lb *HashBalance) DialContext(ctx context.Context, metadata *C.Metadata) (c C.Conn, err error) {
	defer func() {
		if err == nil {
			c.AppendToChains(lb)
		}
	}()

	proxy := lb.Unwrap(metadata)

	c, err = proxy.DialContext(ctx, metadata)
	return
}

func (lb *HashBalance) DialUDP(metadata *C.Metadata) (pc C.PacketConn, err error) {
	defer func() {
		if err == nil {
			pc.AppendToChains(lb)
		}
	}()

	proxy := lb.Unwrap(metadata)

	return proxy.DialUDP(metadata)
}

func (lb *HashBalance) SupportUDP() bool {
	return true
}

func (lb *HashBalance) Unwrap(metadata *C.Metadata) C.Proxy {
	key := uint64(murmur3.Sum32([]byte(getHost(metadata))))
	proxies := lb.proxies()
	buckets := int32(len(proxies))
	for i := 0; i < lb.maxRetry; i, key = i+1, key+1 {
		idx := jumpHash(key, buckets)
		proxy := proxies[idx]
		if proxy.Alive() {
			return proxy
		}
	}

	return proxies[0]
}

func (lb *HashBalance) proxies() []C.Proxy {
	elm, _, _ := lb.single.Do(func() (interface{}, error) {
		return getProvidersProxies(lb.providers), nil
	})

	return elm.([]C.Proxy)
}

func (lb *HashBalance) MarshalJSON() ([]byte, error) {
	var all []string
	for _, proxy := range lb.proxies() {
		all = append(all, proxy.Name())
	}
	return json.Marshal(map[string]interface{}{
		"type": lb.Type().String(),
		"all":  all,
	})
}

func NewHashBalance(name string, providers []provider.ProxyProvider) *HashBalance {
	return &HashBalance{
		Base:      outbound.NewBase(name, "", C.HashBalance, false),
		single:    singledo.NewSingle(defaultGetProxiesDuration),
		maxRetry:  3,
		providers: providers,
	}
}

```

**Comment by akw5454521** [comment]
不怕各大网站出于风控考虑把你号封了？

**Comment by kongkong9527** [comment]
> 不怕各大网站出于风控考虑把你号封了？
本地客户端通过 中间的CDN线路连接到远端的同一个VPS。
我们已知中间线路速度是小于远端VPS的网络速度，通过好几条线路充分利用远端VPS的网络速度。

希望能设计一个功能，可以设置某个网站（或某一类网站）下的各类子链接，随机负载均衡到指定的几条线路上（这几条线路都连接到远端的同一个VPS上），load-balance采用 eTLD方式来做， 目前观察看是无法实现这种场景的使用。

不知道实现可行性，希望能探讨一下这个问题。

**Comment by kongkong9527** [comment]
> 不怕各大网站出于风控考虑把你号封了？

本地客户端通过 中间的CDN线路连接到远端的同一个VPS。
我们已知中间线路速度是小于远端VPS的网络速度，通过好几条线路充分利用远端VPS的网络速度。

希望能设计一个功能，可以设置某个网站（或某一类网站）下的各类子链接，随机负载均衡到指定的几条线路上（这几条线路都连接到远端的同一个VPS上），load-balance采用 eTLD方式来做， 目前观察看是无法实现这种场景的使用。

不知道实现可行性，希望能探讨一下这个问题。

**Comment by akw5454521** [comment]
> > 不怕各大网站出于风控考虑把你号封了？
> 
> 本地客户端通过 中间的CDN线路连接到远端的同一个VPS。
> 我们已知中间线路速度是小于远端VPS的网络速度，通过好几条线路充分利用远端VPS的网络速度。
> 
> 希望能设计一个功能，可以设置某个网站（或某一类网站）下的各类子链接，随机负载均衡到指定的几条线路上（这几条线路都连接到远端的同一个VPS上），load-balance采用 eTLD方式来做， 目前观察看是无法实现这种场景的使用。
> 
> 不知道实现可行性，希望能探讨一下这个问题。

噢不好意思是我理解错了，我以为是指多台VPS连接同一网站，如果是多条CDN连接同一VPS的话那没有风控问题，不过这个实现感觉需要服务端(或者CDN)支持吧？

**Comment by kongkong9527** [comment]
> > > 不怕各大网站出于风控考虑把你号封了？
> > 
> > 
> > 本地客户端通过 中间的CDN线路连接到远端的同一个VPS。
> > 我们已知中间线路速度是小于远端VPS的网络速度，通过好几条线路充分利用远端VPS的网络速度。
> > 希望能设计一个功能，可以设置某个网站（或某一类网站）下的各类子链接，随机负载均衡到指定的几条线路上（这几条线路都连接到远端的同一个VPS上），load-balance采用 eTLD方式来做， 目前观察看是无法实现这种场景的使用。
> > 不知道实现可行性，希望能探讨一下这个问题。
> 
> 噢不好意思是我理解错了，我以为是指多台VPS连接同一网站，如果是多条CDN连接同一VPS的话那没有风控问题，不过这个实现感觉需要服务端(或者CDN)支持吧？

目前是套用多个CDN线路连接 同一个VPS，看起来没有问题，正好VMess 是一个无状态协议，正好符合多个CDN连接向VPS请求的的使用场景，据目前使用来看，没有发现异常。

**Comment by Dreamacro** [comment]
那你用 round robin 吧

**Comment by kongkong9527** [comment]
> 那你用 round robin 吧

func strategyRoundRobin() strategyFn {
	idx := 0
	return func(proxies []C.Proxy, metadata *C.Metadata) C.Proxy {
		length := len(proxies)
		for i := 0; i < length; i++ {
			idx = (idx + 1) % length
			proxy := proxies[idx]
			if proxy.Alive() {
				return proxy
			}
		}

		return proxies[0]
	}
}


你好，我想问一下，最近推出了这个功能，但是从代码看，每次都从0开始索引，可以完成RoundRobin算法得设计？

**Comment by Dreamacro** [comment]
这是一个闭包，外面的 idx 会被里面使用和赋值，所以每次调用这个函数 idx 会从上一个的 idx 继续。

**Comment by TcDhlPro** [comment]
> > 不怕各大网站出于风控考虑把你号封了？
> 
> 本地客户端通过 中间的CDN线路连接到远端的同一个VPS。 我们已知中间线路速度是小于远端VPS的网络速度，通过好几条线路充分利用远端VPS的网络速度。
> 
> 希望能设计一个功能，可以设置某个网站（或某一类网站）下的各类子链接，随机负载均衡到指定的几条线路上（这几条线路都连接到远端的同一个VPS上），load-balance采用 eTLD方式来做， 目前观察看是无法实现这种场景的使用。
> 
> 不知道实现可行性，希望能探讨一下这个问题。

**目前就觉得只有ShadowsocksR可以完美实现真正的负载均衡, clash折腾了半天还是会集中在1条线路上, 也可能我不会设置clahs吧, 反正没找到哪里可以配置的**

**Comment by lmingzhi** [comment]
> 

`strategy` 需要选择 `round-robin`!!!

strategy 有2中类型：

1. `consistent-hashing` 同一个域名下会持续使用同一个ip, 默认选择该项，防止频繁跳ip被网站ban
2. `round-robin`  每访问一个链接，顺序更换节点访问，应该是你想要的


```yaml
proxy-groups:
  # load-balance: The request of the same eTLD+1 will be dial to the same proxy.
  - name: "load-balance"
    type: load-balance
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin 
    # strategy: consistent-hashing # or round-robin
```

**Comment by Bitcion** [comment]
> > **目前就觉得只有ShadowsocksR可以完美实现真正的负载均衡, clash折腾了半天还是会集中在1条线路上, 也可能我不会设置clahs吧, 反正没找到哪里可以配置的**
> 
> `strategy` 需要选择 `round-robin`!!!
> 
> strategy 有2种类型：
> 
> 1. `consistent-hashing` 同一个域名下会持续使用同一个ip, 默认选择该项，防止频繁跳ip被网站ban
> 2. `round-robin`  每访问一个链接，顺序更换节点访问，应该是你想要的
> 
> ```yaml
> proxy-groups:
>   # load-balance: The request of the same eTLD+1 will be dial to the same proxy.
>   - name: "load-balance"
>     type: load-balance
>     proxies:
>       - ss1
>       - ss2
>       - vmess1
>     url: 'http://www.gstatic.com/generate_204'
>     interval: 300
>     strategy: round-robin 
>     # strategy: consistent-hashing # or round-robin
> ```

一个节点多个cdn还是round-robin好

**Comment by oiiogong** [comment]
round-robin 每访问一个链接，顺序更换节点访问，应该是你想要的。确实是我想要的。谢谢

**Comment by hcym** [comment]
这个策略是比较好

**Comment by shallker** [comment]
> 

我希望实现以下的动态均衡策略：
第一：我有10个代理服务器节点
第二：算法每隔1分钟，对10个代理服务器节点分别做个心跳测速，然后把速度最快的那个服务器节点标记为FASTEST
第三：每次的HTTP请求，都是自动通过那个FASTEST节点传输出去

round-robin 是否能帮我实现？

@lmingzhi 大神帮忙指教

**Comment by vtroisWhite** [comment]
> 

这听起来不就是url-test吗

**Comment by vtroisWhite** [comment]
> 这个策略是比较好



> > 
> 
> 我希望实现以下的动态均衡策略： 第一：我有10个代理服务器节点 第二：算法每隔1分钟，对10个代理服务器节点分别做个心跳测速，然后把速度最快的那个服务器节点标记为FASTEST 第三：每次的HTTP请求，都是自动通过那个FASTEST节点传输出去
> 
> round-robin 是否能帮我实现？
> 
> @lmingzhi 大神帮忙指教


这听起来不就是url-test吗

**Comment by shallker** [comment]
我刚去搜索了下文档，url-test 是我想要的，感谢大神回复！
