### ISSUE TITLE
问几个小白问题

### ISSUE THREAD

**Issue by echo860** [Dreamacro/clash#1064]
麻烦耐心解答这几个问题
1.这个的exe版本在哪里？
2.我用的另一个有exe版本的clash，但是那个PAC做得不好，国外网打开快，国内打开慢，这个怎么样呢？
3.还有LAN怎么设置？<自动检测设置>，<自动配置脚本>，<为LAN使用代理服务器>这三个选哪个？

**Comment by angelknight007** [comment]
这里只有内核，exe去clash for windows项目

**Comment by cookcc** [comment]
请问打开clash后，内外网的访问流量都走clash代理了么？还是会智能区分只在访问外网时走代理，或者是否可自定义配置想走代理的外网地址，其它默认不走代理？

**Comment by angelknight007** [comment]
> 请问打开clash后，内外网的访问流量都走clash代理了么？还是会智能区分只在访问外网时走代理，或者是否可自定义配置想走代理的外网地址，其它默认不走代理？

都会走clash，但是走不走代理要看你的规则，可以随意自定义

**Comment by cookcc** [comment]
> > 请问打开clash后，内外网的访问流量都走clash代理了么？还是会智能区分只在访问外网时走代理，或者是否可自定义配置想走代理的外网地址，其它默认不走代理？
> 
> 都会走clash，但是走不走代理要看你的规则，可以随意自定义

这个怎么自定义，有文档或例子可参考么，比如我希望访问github.com时才走代理访问外网，其它希望不走代理怎么配置

**Comment by angelknight007** [comment]
> > > 请问打开clash后，内外网的访问流量都走clash代理了么？还是会智能区分只在访问外网时走代理，或者是否可自定义配置想走代理的外网地址，其它默认不走代理？
> > 
> > 
> > 都会走clash，但是走不走代理要看你的规则，可以随意自定义
> 
> 这个怎么自定义，有文档或例子可参考么，比如我希望访问github.com时才走代理访问外网，其它希望不走代理怎么配置

https://lancellc.gitbook.io/clash/
