### ISSUE TITLE
Termux package available

### ISSUE THREAD

**Issue by pschmitt** [Dreamacro/clash#1065]
Heyhey,

this ain't a feature request but an FYI that clash is now available on the [Termux](https://termux.com/) main repo.

```bash
pkg install clash
```

Ref:
- https://bintray.com/termux/termux-packages-24/clash 
- https://github.com/termux/termux-packages/pull/5995

**Comment by Dreamacro** [comment]
That's cool, but I'd be interested to know why you need to use it on the Android terminal emulator.

**Comment by pschmitt** [comment]
It basically boils down to the fact that I do work with termux quite a lot (odd, I know) and need to use multiple SOCKS5 proxies for borh work and homelab projects. For me its way easier to set `https_proxy` once (-> clash) and forget about it rather than changing its value every time i need to access another environment.

**Comment by Dreamacro** [comment]
Okay, I hope you enjoy the clash. 👏
