### ISSUE TITLE
openwrt TUN模式透明代理应该怎么设置iptable

### ISSUE THREAD

**Issue by l619534951** [Dreamacro/clash#1068]
自己折腾了两天了，总是有问题，路由器都刷了好多次了，有谁可以给个转发规则吗？clash启动成功了，想要的效果就是连上路由器的WIFI或者网线以后可以直接实现fan墙。

**Comment by xjasonlyu** [comment]
TUN模式应该可以不用设置iptables的吧，不过clash的tun底层实现没有公开也不太清楚。。

**Comment by l619534951** [comment]
> TUN模式应该可以不用设置iptables的吧，不过clash的tun底层实现没有公开也不太清楚。。
不行，你开个ubuntu试一下，tun模式一样不能直接翻的

**Comment by xjasonlyu** [comment]
你看下路由表嘛，我之间试的时候记得默认是对198.18.0.0/15的目的地址走tun，所以要开fakedns，，后来全局就直接用tun2socks加clash解决了。。

**Comment by DotWho** [comment]
TUN模式不用设置iptables，只是一些软件需要设置下代理

**Comment by juewuy** [comment]
如果是openwrt发行版可以使用openclash
如果是定制版可以使用[ShellClash](https://github.com/juewuy/ShellClash)
没必要自己折腾
