### ISSUE TITLE
关于common/pool的小问题

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#1070]
pool实现里大小超过65536的Get就会返回nil，

https://github.com/Dreamacro/clash/blob/b1795b1e3d13a2c8898fc457b7b8b4147b41f4ee/tunnel/connection.go#L139

那这么写的意义在哪里。。

**Comment by Dreamacro** [comment]
pool.RelayBufferSize 是 20 KiB, 65536 是 64 Kib

**Comment by xjasonlyu** [comment]
🌚🌚🌚是我傻了。
