### ISSUE TITLE
[Bug]采用DEV最新合并，TPROXY TCP的问题

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#1071]
开启tproxy tcp后，谷歌报不安全。油管能进页面，视频有缩略图。但是任意视频都无法播放，空转。
解决，为PREROUTING添加DNS转发端口即可。
![image](https://user-images.githubusercontent.com/67776691/98823987-b3b5bf80-246d-11eb-9ed5-5466fb5122dd.png)
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 23453
详述：
环境：
路由ASUS AX88U
PC端口网卡全自动
手机WIFI DHCP
**--------只开启tproxy tcp代理-------**
iptables内容
modprobe xt_TPROXY
# 设置策略路由
ip rule add fwmark 1 lookup 100
ip route add local default dev lo table 100
# 代理外部设备
iptables -t mangle -N merlinclash
iptables -t mangle -F merlinclash
iptables -t mangle -A merlinclash -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A merlinclash -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A merlinclash -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A merlinclash -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A merlinclash -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A merlinclash -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A merlinclash -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A merlinclash -d 240.0.0.0/4 -j RETURN	
iptables -t mangle -A merlinclash -p tcp -j TPROXY --on-port "23458" --tproxy-mark 1
#SSH端口
iptables -t mangle -A PREROUTING -p tcp --dport 22 -j ACCEPT
# 应用规则
iptables -t mangle -A PREROUTING -i br0 -j merlinclash 
**IPTABLE各表情况**
----------------------------------------------------- nat表 PREROUTING 链 --------------------------------------------------------
Chain PREROUTING (policy ACCEPT 452 packets, 48643 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1        3   156 cloud_music  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set music dst
2       16   672 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1194
3    42147 4259K VSERVER    all  --  *      *       0.0.0.0/0            119.131.119.110     
4        3   288 VSERVER    all  --  *      *       0.0.0.0/0            192.168.1.2         

----------------------------------------------------- nat表 OUTPUT 链 ------------------------------------------------------------
Chain OUTPUT (policy ACCEPT 504 packets, 30668 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
----------------------------------------------------- nat表 merlinclash 链 --------------------------------------------------------
iptables: No chain/target/match by that name.
----------------------------------------------------- nat表 clash_dns 链 --------------------------------------------------------
iptables: No chain/target/match by that name.
----------------------------------------------------- nat表 cloud_music 链 --------------------------------------------------------
Chain cloud_music (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1        0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/8           
2        0     0 RETURN     all  --  *      *       0.0.0.0/0            10.0.0.0/8          
3        0     0 RETURN     all  --  *      *       0.0.0.0/0            127.0.0.0/8         
4        0     0 RETURN     all  --  *      *       0.0.0.0/0            169.254.0.0/16      
5        0     0 RETURN     all  --  *      *       0.0.0.0/0            172.16.0.0/12       
6        0     0 RETURN     all  --  *      *       0.0.0.0/0            192.168.0.0/16      
7        0     0 RETURN     all  --  *      *       0.0.0.0/0            224.0.0.0/4         
8        0     0 RETURN     all  --  *      *       0.0.0.0/0            240.0.0.0/4         
9        0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 5200
10       3   156 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 5300
----------------------------------------------------- mangle表 merlinclash 链 --------------------------------------------------------
Chain merlinclash (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1      251 34307 RETURN     all  --  *      *       0.0.0.0/0            192.168.0.0/16      
2        0     0 RETURN     all  --  *      *       0.0.0.0/0            10.0.0.0/8          
3        0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/8           
4        0     0 RETURN     all  --  *      *       0.0.0.0/0            127.0.0.0/8         
5        0     0 RETURN     all  --  *      *       0.0.0.0/0            169.254.0.0/16      
6        0     0 RETURN     all  --  *      *       0.0.0.0/0            172.16.0.0/12       
7        8   368 RETURN     all  --  *      *       0.0.0.0/0            224.0.0.0/4         
8        1   328 RETURN     all  --  *      *       0.0.0.0/0            240.0.0.0/4         
9      245 38806 TPROXY     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            TPROXY redirect 0.0.0.0:23458 mark 0x1/0xffffffff
10       1    80 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set china_ip_route dst
----------------------------------------------------- mangle表 PREROUTING 链 --------------------------------------------------------
Chain PREROUTING (policy ACCEPT 1582 packets, 919K bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1    75620 7039K MARK       all  --  tun21  *       0.0.0.0/0            0.0.0.0/0            MARK xset 0x1/0x7
2        0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
3        0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
4      508 74535 merlinclash  all  --  br0    *       0.0.0.0/0            0.0.0.0/0           
-----------------------------------------------------------------------------------------------------------------------------------

**配置文件相关**：
port: 3333
socks-port: 23456
redir-port: 23457
tproxy-port: 23458
allow-lan: true
tproxy: true
mode: rule
log-level: error
external-controller: 192.168.2.1:9990
experimental:
  ignore-resolve-fail: true
external-ui: dashboard
secret: "clash"

hosts:
  router.asus.com: 192.168.2.1
  services.googleapis.cn: 74.125.193.94

dns:
  enable: true
  listen: 0.0.0.0:23453
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - https://223.5.5.5/dns-query
    - tls://101.101.101.101:853
    - https://doh.pub/dns-query
  fallback:
    - tls://1.0.0.1:853
    - tcp://208.67.222.222:443
    - tls://dns.google
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
**现象：**
1.不需做DNS端口劫持，PC&手机也能直接打开外网；
2.谷歌能正常打开；
3.油管能打开页面，有缩略图，但是视频空转。
![image](https://user-images.githubusercontent.com/67776691/98821765-f0cc8280-246a-11eb-975d-c50db84f68c2.png)

4.测试PORNXXX能播放视频

**Comment by Dreamacro** [comment]
@maskedeken /cc

**Comment by ekenchan** [comment]
跟DNS污染有关？

**Comment by flyhigherpi** [comment]
> 跟DNS污染有关？

应该是dns没走clash接管导致无法解析域名。对比了前后发现面板conn里，
接管前:全是ip，油管没视频
接管后:出现xxx.googlevedio.com:443，油管视频正常。
已经正常使用上了。
