### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by zheyuanWang** [Dreamacro/clash#1073]
你好, 

我在打开clash的情况下, 可以流畅访问 onedrive网页版; 本地onedirve网盘同步正常;
但是OneNote无法进行同步:

![image](https://user-images.githubusercontent.com/39280197/98920030-e2648200-24cf-11eb-99c7-f6474c8fb645.png)

请问同步onenote需要单独进行特别配置么?

**Comment by CDOM** [comment]
我的也是这个问题，VPN关闭，OneNote同步正常，但是打开后就同样的错误。想咨询下如何解决？
