### ISSUE TITLE
[Feature] 能否在load-balance类型支持tolerance参数

### ISSUE THREAD

**Issue by bash99** [Dreamacro/clash#1074]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

我都确认过了，我要继续提交。

### 环境 Environment

* Clash 2020.10.09 Premium

### 说明 Description
有一组节点，通常速度较快，偶尔会出现线路问题，部分节点变慢。
希望利用load-balance方式使用这批节点，同时如果延时超过200ms就排除。

**Comment by SplitGemini** [comment]
附议

**Comment by GeekSheldon** [comment]
别烦了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Guo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月21日(星期六) 中午11:30
收件人:&nbsp;&quot;Dreamacro/clash&quot;<clash@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Dreamacro/clash] [Feature] 能否在load-balance类型支持tolerance参数 (#1074)

**Comment by Artoria2e5** [comment]
tolerance 的定义其实真的就是 tolerance，公差。urltest 里面如果一个节点没多慢超过这么多时间，就认为一样快。

https://github.com/Dreamacro/clash/blob/4d66da2277ddaf41f83bd889b064c0a584f7a8ad/adapter/outboundgroup/urltest.go#L92-L94
