### ISSUE TITLE
[Feature]是否可以加入naive支持

### ISSUE THREAD

**Issue by openips** [Dreamacro/clash#1076]
目前测试效果最好的客户端 部署也极其方便

**Comment by LitingLin** [comment]
用socks5串起来就可以了吧
go实现就不naive了

**Comment by openips** [comment]
之前可以  master版本的op+最新clash sock5直接naive报错

**Comment by Dreamacro** [comment]
需要客户端自己能走固定的网口并设置网口，不然接管所有流量就回环了

**Comment by openips** [comment]
有道理 我试试看

**Comment by openips** [comment]
> 需要客户端自己能走固定的网口并设置网口，不然接管所有流量就回环了

如何做呢 clash控制vps节点ip走直连？

**Comment by Dreamacro** [comment]
和 clash 这边其实没有关系了，如果那个客户端能直接指定网卡的话就很简单了，不能的话只能通过 ip 白名单

**Comment by openips** [comment]
明白了 谢谢
