### ISSUE TITLE
[Feature]clash对多核超线程cpu的支持是怎样的

### ISSUE THREAD

**Issue by bleeee** [Dreamacro/clash#1077]
在安装了esxi+openwrt的双核四线程机器上，千兆网络进行speedtest测速时只有500M左右，通过netdata查看，cpu占用率到达25%左右就没办法提高了

**Comment by Dreamacro** [comment]
可以用 iperf 试试

**Comment by sumsethan** [comment]
**Clash版本**：premium 2020.11.20 及1.3.0均测试
**网络环境**：广州移动600M
**Clash运行设备**：Phicomm N1 w/ Armbian 5.3.0-aml-g12 Kernel
**iptables-v4：**

> root@Gateway-N1:~# cat /etc/iptables/rules.v4
> # Generated by xtables-save v1.8.2 on Mon Nov 16 11:48:23 2020
> *filter
> :INPUT ACCEPT [1547:371933]
> :FORWARD ACCEPT [0:0]
> :OUTPUT ACCEPT [1575:342549]
> COMMIT
> # Completed on Mon Nov 16 11:48:23 2020
> # Generated by xtables-save v1.8.2 on Mon Nov 16 11:48:23 2020
> *nat
> :PREROUTING ACCEPT [20:3675]
> :INPUT ACCEPT [126:10535]
> :POSTROUTING ACCEPT [163:10856]
> :OUTPUT ACCEPT [163:10856]
> :clash - [0:0]
> :CLASH_DNS - [0:0]
> -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 1053
> -A PREROUTING -d 8.8.4.4/32 -p tcp -j REDIRECT --to-ports 7892
> -A PREROUTING -d 8.8.8.8/32 -p tcp -j REDIRECT --to-ports 7892
> -A PREROUTING -p tcp -j clash
> -A OUTPUT -p udp -m udp --dport 53 -j CLASH_DNS
> -A clash -d 0.0.0.0/8 -j RETURN
> -A clash -d 10.0.0.0/8 -j RETURN
> -A clash -d 127.0.0.0/8 -j RETURN
> -A clash -d 169.254.0.0/16 -j RETURN
> -A clash -d 172.16.0.0/12 -j RETURN
> -A clash -d 192.168.0.0/16 -j RETURN
> -A clash -d 224.0.0.0/4 -j RETURN
> -A clash -d 240.0.0.0/4 -j RETURN
> -A clash -d 192.168.88.3/32 -j RETURN
> -A clash -p tcp -j REDIRECT --to-ports 7892
> -A CLASH_DNS -p udp -j REDIRECT --to-ports 1053
> COMMIT
> # Completed on Mon Nov 16 11:48:23 2020
> # Generated by xtables-save v1.8.2 on Mon Nov 16 11:48:23 2020
> *mangle
> :PREROUTING ACCEPT [1550:372105]
> :INPUT ACCEPT [1546:371865]
> :FORWARD ACCEPT [0:0]
> :OUTPUT ACCEPT [1574:342497]
> :POSTROUTING ACCEPT [1574:342497]
> :clash - [0:0]
> -A PREROUTING -p udp -j clash
> -A clash -d 0.0.0.0/8 -j RETURN
> -A clash -d 10.0.0.0/8 -j RETURN
> -A clash -d 127.0.0.0/8 -j RETURN
> -A clash -d 169.254.0.0/16 -j RETURN
> -A clash -d 172.16.0.0/12 -j RETURN
> -A clash -d 192.168.0.0/16 -j RETURN
> -A clash -d 224.0.0.0/4 -j RETURN
> -A clash -d 240.0.0.0/4 -j RETURN
> -A clash -d 192.168.88.3/32 -j RETURN
> -A clash -p udp -j TPROXY --on-port 7892 --on-ip 0.0.0.0 --tproxy-mark 0x1/0xffffffff
> COMMIT
> # Completed on Mon Nov 16 11:48:23 2020
> 

**描述**：
使用clash作为网关运行在 N1上，N1本地未代理，本地使用speedtest测速：

> root@Gateway-N1:~# speedtest 
> 
>    Speedtest by Ookla
> 
>      Server: China Mobile,Guangdong - Shenzhen (id = 4515)
>         ISP: China Mobile Guangdong
>     Latency:     8.42 ms   (0.04 ms jitter)
>    Download:   716.94 Mbps (data used: 678.8 MB)                               
>      Upload:    29.97 Mbps (data used: 51.9 MB)                               
> Packet Loss:     0.0%
>  Result URL: https://www.speedtest.net/result/c/e6f45b26-15a6-48d6-9268-f7d9eb1731ac
> 
使用其他设备，DNS及gateway均设置为N1地址，使用speedtest测速：

> root@SmokePing:~# speedtest -s 4515
> 
>    Speedtest by Ookla
> 
>      Server: China Mobile,Guangdong - Shenzhen (id = 4515)
>         ISP: China Mobile Guangdong
>     Latency:     6.86 ms   (0.20 ms jitter)
>    Download:   433.28 Mbps (data used: 458.0 MB)                               
>      Upload:    29.92 Mbps (data used: 52.2 MB)                               
> Packet Loss: Not available.
>  Result URL: https://www.speedtest.net/result/c/793dcf4a-a0e3-4708-913c-915da0d96edc
测速时N1设备（4核 1.5GHz aarch64）通过htop可见clash单核跑满100%，CPU整体占用29%左右。

#EOF

**Comment by Dreamacro** [comment]
试试 iperf3 过 clash 的测试（-p）, 或者 speedtest 本身包含多线程么

**Comment by sumsethan** [comment]
是的speedtest是一个多线程测速方式

![](https://github.com/sumsethan/jpg/raw/main/%E6%88%AA%E5%B1%8F2020-11-30%2015.31.10.png)

**Comment by sumsethan** [comment]
**找到一台G口机再次用iperf3测试了一下
**环境同上**
**不过clash：**
```
root@Gateway-N1:~# iperf3 -Rc *.*.*.* -t 1 -P 10
Connecting to host *.*.*.*, port 5201
Reverse mode, remote host *.*.*.* is sending
[  5] local 192.168.88.2 port 49114 connected to *.*.*.* port 5201
[  7] local 192.168.88.2 port 49116 connected to *.*.*.* port 5201
[  9] local 192.168.88.2 port 49118 connected to *.*.*.* port 5201
[ 11] local 192.168.88.2 port 49120 connected to *.*.*.* port 5201
[ 13] local 192.168.88.2 port 49122 connected to *.*.*.* port 5201
[ 15] local 192.168.88.2 port 49124 connected to *.*.*.* port 5201
[ 17] local 192.168.88.2 port 49126 connected to *.*.*.* port 5201
[ 19] local 192.168.88.2 port 49128 connected to *.*.*.* port 5201
[ 21] local 192.168.88.2 port 49130 connected to *.*.*.* port 5201
[ 23] local 192.168.88.2 port 49132 connected to *.*.*.* port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  8.28 MBytes  69.4 Mbits/sec                  
[  7]   0.00-1.00   sec  9.85 MBytes  82.6 Mbits/sec                  
[  9]   0.00-1.00   sec  5.91 MBytes  49.6 Mbits/sec                  
[ 11]   0.00-1.00   sec  10.1 MBytes  84.5 Mbits/sec                  
[ 13]   0.00-1.00   sec  7.62 MBytes  63.9 Mbits/sec                  
[ 15]   0.00-1.00   sec  5.30 MBytes  44.4 Mbits/sec                  
[ 17]   0.00-1.00   sec  12.0 MBytes   101 Mbits/sec                  
[ 19]   0.00-1.00   sec  8.07 MBytes  67.6 Mbits/sec                  
[ 21]   0.00-1.00   sec  9.21 MBytes  77.2 Mbits/sec                  
[ 23]   0.00-1.00   sec  6.12 MBytes  51.3 Mbits/sec                  
[SUM]   0.00-1.00   sec  82.4 MBytes   691 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-1.00   sec  9.86 MBytes  82.7 Mbits/sec   17             sender
[  5]   0.00-1.00   sec  8.28 MBytes  69.4 Mbits/sec                  receiver
[  7]   0.00-1.00   sec  13.4 MBytes   113 Mbits/sec  282             sender
[  7]   0.00-1.00   sec  9.85 MBytes  82.6 Mbits/sec                  receiver
[  9]   0.00-1.00   sec  7.64 MBytes  64.1 Mbits/sec    0             sender
[  9]   0.00-1.00   sec  5.91 MBytes  49.6 Mbits/sec                  receiver
[ 11]   0.00-1.00   sec  12.3 MBytes   103 Mbits/sec    4             sender
[ 11]   0.00-1.00   sec  10.1 MBytes  84.5 Mbits/sec                  receiver
[ 13]   0.00-1.00   sec  9.37 MBytes  78.6 Mbits/sec    0             sender
[ 13]   0.00-1.00   sec  7.62 MBytes  63.9 Mbits/sec                  receiver
[ 15]   0.00-1.00   sec  7.43 MBytes  62.3 Mbits/sec    6             sender
[ 15]   0.00-1.00   sec  5.30 MBytes  44.4 Mbits/sec                  receiver
[ 17]   0.00-1.00   sec  14.1 MBytes   118 Mbits/sec    0             sender
[ 17]   0.00-1.00   sec  12.0 MBytes   101 Mbits/sec                  receiver
[ 19]   0.00-1.00   sec  10.1 MBytes  84.6 Mbits/sec    0             sender
[ 19]   0.00-1.00   sec  8.07 MBytes  67.7 Mbits/sec                  receiver
[ 21]   0.00-1.00   sec  11.2 MBytes  94.1 Mbits/sec    0             sender
[ 21]   0.00-1.00   sec  9.21 MBytes  77.2 Mbits/sec                  receiver
[ 23]   0.00-1.00   sec  8.21 MBytes  68.9 Mbits/sec    0             sender
[ 23]   0.00-1.00   sec  6.12 MBytes  51.3 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec   104 MBytes   869 Mbits/sec  309             sender
[SUM]   0.00-1.00   sec  82.4 MBytes   691 Mbits/sec                  receiver

iperf Done.

```
**过clash：**
```
root@SmokePing:~# iperf3 -Rc *.*.*.* -t 1 -P 10
Connecting to host *.*.*.*, port 5201
Reverse mode, remote host *.*.*.* is sending
[  5] local 192.168.88.8 port 57324 connected to *.*.*.* port 5201
[  7] local 192.168.88.8 port 57326 connected to *.*.*.* port 5201
[  9] local 192.168.88.8 port 57328 connected to *.*.*.* port 5201
[ 11] local 192.168.88.8 port 57330 connected to *.*.*.* port 5201
[ 13] local 192.168.88.8 port 57332 connected to *.*.*.* port 5201
[ 15] local 192.168.88.8 port 57334 connected to *.*.*.* port 5201
[ 17] local 192.168.88.8 port 57336 connected to *.*.*.* port 5201
[ 19] local 192.168.88.8 port 57338 connected to *.*.*.* port 5201
[ 21] local 192.168.88.8 port 57340 connected to *.*.*.* port 5201
[ 23] local 192.168.88.8 port 57342 connected to *.*.*.* port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  6.73 MBytes  56.5 Mbits/sec                  
[  7]   0.00-1.00   sec  1.58 MBytes  13.2 Mbits/sec                  
[  9]   0.00-1.00   sec  3.50 MBytes  29.3 Mbits/sec                  
[ 11]   0.00-1.00   sec   950 KBytes  7.78 Mbits/sec                  
[ 13]   0.00-1.00   sec  4.59 MBytes  38.5 Mbits/sec                  
[ 15]   0.00-1.00   sec  1.67 MBytes  14.0 Mbits/sec                  
[ 17]   0.00-1.00   sec   441 KBytes  3.62 Mbits/sec                  
[ 19]   0.00-1.00   sec  2.54 MBytes  21.3 Mbits/sec                  
[ 21]   0.00-1.00   sec  4.09 MBytes  34.3 Mbits/sec                  
[ 23]   0.00-1.00   sec  7.89 MBytes  66.1 Mbits/sec                  
[SUM]   0.00-1.00   sec  33.9 MBytes   285 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-1.00   sec  10.1 MBytes  84.6 Mbits/sec  2134             sender
[  5]   0.00-1.00   sec  6.73 MBytes  56.5 Mbits/sec                  receiver
[  7]   0.00-1.00   sec  5.33 MBytes  44.7 Mbits/sec  1227             sender
[  7]   0.00-1.00   sec  1.58 MBytes  13.2 Mbits/sec                  receiver
[  9]   0.00-1.00   sec  1.32 MBytes  11.1 Mbits/sec  239             sender
[  9]   0.00-1.00   sec  3.50 MBytes  29.3 Mbits/sec                  receiver
[ 11]   0.00-1.00   sec  9.33 MBytes  78.3 Mbits/sec  1687             sender
[ 11]   0.00-1.00   sec   950 KBytes  7.78 Mbits/sec                  receiver
[ 13]   0.00-1.00   sec  2.61 MBytes  21.9 Mbits/sec  600             sender
[ 13]   0.00-1.00   sec  4.59 MBytes  38.5 Mbits/sec                  receiver
[ 15]   0.00-1.00   sec  3.84 MBytes  32.2 Mbits/sec  829             sender
[ 15]   0.00-1.00   sec  1.67 MBytes  14.0 Mbits/sec                  receiver
[ 17]   0.00-1.00   sec  1.66 MBytes  13.9 Mbits/sec  296             sender
[ 17]   0.00-1.00   sec   441 KBytes  3.62 Mbits/sec                  receiver
[ 19]   0.00-1.00   sec  8.40 MBytes  70.5 Mbits/sec  818             sender
[ 19]   0.00-1.00   sec  2.54 MBytes  21.3 Mbits/sec                  receiver
[ 21]   0.00-1.00   sec  3.83 MBytes  32.1 Mbits/sec  980             sender
[ 21]   0.00-1.00   sec  4.09 MBytes  34.3 Mbits/sec                  receiver
[ 23]   0.00-1.00   sec  11.1 MBytes  93.4 Mbits/sec  1942             sender
[ 23]   0.00-1.00   sec  7.89 MBytes  66.1 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  57.6 MBytes   483 Mbits/sec  10752             sender
[SUM]   0.00-1.00   sec  33.9 MBytes   285 Mbits/sec                  receiver

iperf Done.
```
EOF

**Comment by bleeee** [comment]
> **找到一台G口机再次用iperf3测试了一下**
> **环境同上**
> **不过clash：**
> 
> ```
> root@Gateway-N1:~# iperf3 -Rc *.*.*.* -t 1 -P 10
> Connecting to host *.*.*.*, port 5201
> Reverse mode, remote host *.*.*.* is sending
> [  5] local 192.168.88.2 port 49114 connected to *.*.*.* port 5201
> [  7] local 192.168.88.2 port 49116 connected to *.*.*.* port 5201
> [  9] local 192.168.88.2 port 49118 connected to *.*.*.* port 5201
> [ 11] local 192.168.88.2 port 49120 connected to *.*.*.* port 5201
> [ 13] local 192.168.88.2 port 49122 connected to *.*.*.* port 5201
> [ 15] local 192.168.88.2 port 49124 connected to *.*.*.* port 5201
> [ 17] local 192.168.88.2 port 49126 connected to *.*.*.* port 5201
> [ 19] local 192.168.88.2 port 49128 connected to *.*.*.* port 5201
> [ 21] local 192.168.88.2 port 49130 connected to *.*.*.* port 5201
> [ 23] local 192.168.88.2 port 49132 connected to *.*.*.* port 5201
> [ ID] Interval           Transfer     Bitrate
> [  5]   0.00-1.00   sec  8.28 MBytes  69.4 Mbits/sec                  
> [  7]   0.00-1.00   sec  9.85 MBytes  82.6 Mbits/sec                  
> [  9]   0.00-1.00   sec  5.91 MBytes  49.6 Mbits/sec                  
> [ 11]   0.00-1.00   sec  10.1 MBytes  84.5 Mbits/sec                  
> [ 13]   0.00-1.00   sec  7.62 MBytes  63.9 Mbits/sec                  
> [ 15]   0.00-1.00   sec  5.30 MBytes  44.4 Mbits/sec                  
> [ 17]   0.00-1.00   sec  12.0 MBytes   101 Mbits/sec                  
> [ 19]   0.00-1.00   sec  8.07 MBytes  67.6 Mbits/sec                  
> [ 21]   0.00-1.00   sec  9.21 MBytes  77.2 Mbits/sec                  
> [ 23]   0.00-1.00   sec  6.12 MBytes  51.3 Mbits/sec                  
> [SUM]   0.00-1.00   sec  82.4 MBytes   691 Mbits/sec                  
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-1.00   sec  9.86 MBytes  82.7 Mbits/sec   17             sender
> [  5]   0.00-1.00   sec  8.28 MBytes  69.4 Mbits/sec                  receiver
> [  7]   0.00-1.00   sec  13.4 MBytes   113 Mbits/sec  282             sender
> [  7]   0.00-1.00   sec  9.85 MBytes  82.6 Mbits/sec                  receiver
> [  9]   0.00-1.00   sec  7.64 MBytes  64.1 Mbits/sec    0             sender
> [  9]   0.00-1.00   sec  5.91 MBytes  49.6 Mbits/sec                  receiver
> [ 11]   0.00-1.00   sec  12.3 MBytes   103 Mbits/sec    4             sender
> [ 11]   0.00-1.00   sec  10.1 MBytes  84.5 Mbits/sec                  receiver
> [ 13]   0.00-1.00   sec  9.37 MBytes  78.6 Mbits/sec    0             sender
> [ 13]   0.00-1.00   sec  7.62 MBytes  63.9 Mbits/sec                  receiver
> [ 15]   0.00-1.00   sec  7.43 MBytes  62.3 Mbits/sec    6             sender
> [ 15]   0.00-1.00   sec  5.30 MBytes  44.4 Mbits/sec                  receiver
> [ 17]   0.00-1.00   sec  14.1 MBytes   118 Mbits/sec    0             sender
> [ 17]   0.00-1.00   sec  12.0 MBytes   101 Mbits/sec                  receiver
> [ 19]   0.00-1.00   sec  10.1 MBytes  84.6 Mbits/sec    0             sender
> [ 19]   0.00-1.00   sec  8.07 MBytes  67.7 Mbits/sec                  receiver
> [ 21]   0.00-1.00   sec  11.2 MBytes  94.1 Mbits/sec    0             sender
> [ 21]   0.00-1.00   sec  9.21 MBytes  77.2 Mbits/sec                  receiver
> [ 23]   0.00-1.00   sec  8.21 MBytes  68.9 Mbits/sec    0             sender
> [ 23]   0.00-1.00   sec  6.12 MBytes  51.3 Mbits/sec                  receiver
> [SUM]   0.00-1.00   sec   104 MBytes   869 Mbits/sec  309             sender
> [SUM]   0.00-1.00   sec  82.4 MBytes   691 Mbits/sec                  receiver
> 
> iperf Done.
> ```
> 
> **过clash：**
> 
> ```
> root@SmokePing:~# iperf3 -Rc *.*.*.* -t 1 -P 10
> Connecting to host *.*.*.*, port 5201
> Reverse mode, remote host *.*.*.* is sending
> [  5] local 192.168.88.8 port 57324 connected to *.*.*.* port 5201
> [  7] local 192.168.88.8 port 57326 connected to *.*.*.* port 5201
> [  9] local 192.168.88.8 port 57328 connected to *.*.*.* port 5201
> [ 11] local 192.168.88.8 port 57330 connected to *.*.*.* port 5201
> [ 13] local 192.168.88.8 port 57332 connected to *.*.*.* port 5201
> [ 15] local 192.168.88.8 port 57334 connected to *.*.*.* port 5201
> [ 17] local 192.168.88.8 port 57336 connected to *.*.*.* port 5201
> [ 19] local 192.168.88.8 port 57338 connected to *.*.*.* port 5201
> [ 21] local 192.168.88.8 port 57340 connected to *.*.*.* port 5201
> [ 23] local 192.168.88.8 port 57342 connected to *.*.*.* port 5201
> [ ID] Interval           Transfer     Bitrate
> [  5]   0.00-1.00   sec  6.73 MBytes  56.5 Mbits/sec                  
> [  7]   0.00-1.00   sec  1.58 MBytes  13.2 Mbits/sec                  
> [  9]   0.00-1.00   sec  3.50 MBytes  29.3 Mbits/sec                  
> [ 11]   0.00-1.00   sec   950 KBytes  7.78 Mbits/sec                  
> [ 13]   0.00-1.00   sec  4.59 MBytes  38.5 Mbits/sec                  
> [ 15]   0.00-1.00   sec  1.67 MBytes  14.0 Mbits/sec                  
> [ 17]   0.00-1.00   sec   441 KBytes  3.62 Mbits/sec                  
> [ 19]   0.00-1.00   sec  2.54 MBytes  21.3 Mbits/sec                  
> [ 21]   0.00-1.00   sec  4.09 MBytes  34.3 Mbits/sec                  
> [ 23]   0.00-1.00   sec  7.89 MBytes  66.1 Mbits/sec                  
> [SUM]   0.00-1.00   sec  33.9 MBytes   285 Mbits/sec                  
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-1.00   sec  10.1 MBytes  84.6 Mbits/sec  2134             sender
> [  5]   0.00-1.00   sec  6.73 MBytes  56.5 Mbits/sec                  receiver
> [  7]   0.00-1.00   sec  5.33 MBytes  44.7 Mbits/sec  1227             sender
> [  7]   0.00-1.00   sec  1.58 MBytes  13.2 Mbits/sec                  receiver
> [  9]   0.00-1.00   sec  1.32 MBytes  11.1 Mbits/sec  239             sender
> [  9]   0.00-1.00   sec  3.50 MBytes  29.3 Mbits/sec                  receiver
> [ 11]   0.00-1.00   sec  9.33 MBytes  78.3 Mbits/sec  1687             sender
> [ 11]   0.00-1.00   sec   950 KBytes  7.78 Mbits/sec                  receiver
> [ 13]   0.00-1.00   sec  2.61 MBytes  21.9 Mbits/sec  600             sender
> [ 13]   0.00-1.00   sec  4.59 MBytes  38.5 Mbits/sec                  receiver
> [ 15]   0.00-1.00   sec  3.84 MBytes  32.2 Mbits/sec  829             sender
> [ 15]   0.00-1.00   sec  1.67 MBytes  14.0 Mbits/sec                  receiver
> [ 17]   0.00-1.00   sec  1.66 MBytes  13.9 Mbits/sec  296             sender
> [ 17]   0.00-1.00   sec   441 KBytes  3.62 Mbits/sec                  receiver
> [ 19]   0.00-1.00   sec  8.40 MBytes  70.5 Mbits/sec  818             sender
> [ 19]   0.00-1.00   sec  2.54 MBytes  21.3 Mbits/sec                  receiver
> [ 21]   0.00-1.00   sec  3.83 MBytes  32.1 Mbits/sec  980             sender
> [ 21]   0.00-1.00   sec  4.09 MBytes  34.3 Mbits/sec                  receiver
> [ 23]   0.00-1.00   sec  11.1 MBytes  93.4 Mbits/sec  1942             sender
> [ 23]   0.00-1.00   sec  7.89 MBytes  66.1 Mbits/sec                  receiver
> [SUM]   0.00-1.00   sec  57.6 MBytes   483 Mbits/sec  10752             sender
> [SUM]   0.00-1.00   sec  33.9 MBytes   285 Mbits/sec                  receiver
> 
> iperf Done.
> ```
> 
> EOF

谢谢分享数据，我回去本地架服务器测一下
