### ISSUE TITLE
如何添加ipv6 dns server？

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#1078]
例子一
fallback:
    - 2001:4860:4860::8844
    - tls://1.0.0.1:853
    - tcp://208.67.222.222:443
    - tls://dns.google
报错Parse config error: DNS NameServer[0] format error: address 2001:4860:4860::8844: too many colons in address"
例子二
fallback:
    - [2001:4860:4860]::8844
    - tls://1.0.0.1:853
    - tcp://208.67.222.222:443
    - tls://dns.google
还是报错Parse config error: yaml: line 11016: did not find expected '-' indicator"
例子三：
fallback:
    - [2001:4860:4860::8844]
    - tls://1.0.0.1:853
    - tcp://208.67.222.222:443
    - tls://dns.google
报错：Parse config error: yaml: unmarshal errors:\n line 11017: cannot unmarshal !!seq into string"

**Comment by ysc3839** [comment]
试试
```
fallback:
- '[2001:4860:4860::8844]'
```
