### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by mxbmxl** [Dreamacro/clash#1079]
没有发现如何在配置文件中配置 Proxies > GLOBAL，该项默认是 DIRECT，比如我想让clash启动后根据配置文件让Proxies>GLOBAL默认选择auto而不是DIRECT，应该怎么配置呢？
![image](https://user-images.githubusercontent.com/5501792/99148259-ac86ef80-26c1-11eb-8295-2991037fd16f.png)

**Comment by juewuy** [comment]
curl -sS -X PUT -H "Authorization: Bearer ${secret}" -H "Content-Type:application/json" http://localhost:${db_port}/proxies/GLOBAL -d "{\"name\":\"auto\"}" >/dev/null
