### ISSUE TITLE
[Feature] Return NXDomain for REJECT rules

### ISSUE THREAD

**Issue by LitingLin** [Dreamacro/clash#1082]
- [√] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

似乎配置reject规则后，dns请求仍然会返回有效ip

**Comment by Dreamacro** [comment]
REJECT 和 dns 返回啥并没有关系啊

**Comment by LitingLin** [comment]
好的，我明白了。
我自己套个dnsmasq
感谢大佬
