### ISSUE TITLE
透明代理无法访问部分网站

### ISSUE THREAD

**Issue by junknet** [Dreamacro/clash#1083]
环境：Arch+Kde桌面
个人桌面电脑透明代理实现的思路：建立clash用户,systemd以clash用户启动clash，nftables hook住output链，规则为非clash用户发送的流量 重定向到redir-port.
设置如下:
nftabales部分:
![11](https://user-images.githubusercontent.com/55597646/99183997-f1bb2800-277a-11eb-92f8-b9d0cd3d4abf.png)

clash config.yaml 部分:
![11111](https://user-images.githubusercontent.com/55597646/99184026-2c24c500-277b-11eb-9f82-29de0b40a8c7.png)

systemd 部分:
![12](https://user-images.githubusercontent.com/55597646/99184028-33e46980-277b-11eb-9a66-e38dd9392a2f.png)

访问google.com 页面如下(以排除dns解析等问题):
![qwe](https://user-images.githubusercontent.com/55597646/99184055-5d04fa00-277b-11eb-85e3-23653678c2a0.png)

google.com duckduckgo.com 无法访问
facebook,youtube  可以访问

**Comment by juewuy** [comment]
DNS污染
