### ISSUE TITLE
[Bug]WARN[0000] MMDB invalid, remove and download

### ISSUE THREAD

**Issue by liu-xuewen** [Dreamacro/clash#1086]
sudo ./clash
WARN[0000] MMDB invalid, remove and download

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)

Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by spacexnasa** [comment]
> sudo ./clash
> 
> WARN[0000] MMDB invalid, remove and download
> 
> 
> 
> 
> 
> 
> 
> ### 环境 Environment
> 
> 
> 
> * 操作系统 (the OS that the Clash core is running on)
> 
> 
> 
> 
> 
> Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> 
> 

你少了-d参数，可以单独下载这个mmdb文件
