### ISSUE TITLE
[Feature] Keep the GitHub Wiki up-to-date and make it more detailed

### ISSUE THREAD

**Issue by tddschn** [Dreamacro/clash#1089]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求
This is not a feature request, but a request to improve the documentation of this project.

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

The GitHub Wiki is not outdated - e.g., `PROCESS-NAME` directive was mentioned in the release note but not seen in the wiki. I'd love to contribute to the wiki but I do not have write access to the wiki.

For [Surge](https://nssurge.com), `PROCESS-NAME` requires full path to the executable like `/Applications/Authy Desktop.app/Contents/MacOS/Authy Desktop`, however, according the [unofficial documentation](https://lancellc.gitbook.io/clash/clash-config-file/rules/process-based-rule#process-name), full path is not required. 

In some other cases, the [unofficial documentation](https://lancellc.gitbook.io/clash/) provides more detailed info than the. [official wiki](https://github.com/Dreamacro/clash/wiki), but there're still not enough example to illustrate some configurations.

### 可能的解决方案 Possible Solution
Clash is a project used by hundreds of thousands of people, not just in mainland China, but across the world. It is an indispensable tool that we love and use. A better documentation can benefit countless users. Hereby I suggest a few improve to the Clash wiki / documentation:
- Update the Wiki when a new configuration option is available (like `PROCESS-NAME`)
- Illustrate how a feature can be configured with more detailed example*s*
- Work with the author of the [unofficial documentation](https://lancellc.gitbook.io/clash/) and maybe merge part of that documentation into the official wiki
- Use unambiguous English, see the example below - what does `hosts` do? Is it like `/etc/hosts` or does it specify the DNS servers used when connecting to these domains?
![image](https://user-images.githubusercontent.com/45612704/99819550-91692380-2b8a-11eb-8e34-a8f649bc03ee.png)

**Comment by Dreamacro** [comment]
Maintaining a documentation page is tedious and labor-intensive, and for a non-commercial application, there is a bit of a gap between the latest code and wiki. Unfortunately, github doesn't allow everyone to pull request their change to the wiki (but it does allow git clone).

I've tried to be as consistent as possible with the code, but there are still occasional lapses. Some additional information has been added to the wiki.

**Comment by tddschn** [comment]
I really do appreciate your effort which makes the Internet greatly more accessible in mainland China. :) 

Documentation is an important part of software development - it allows users and devs alike to gain deeper understanding of clash without having to go through the Go source code. 
And AFAIK, most of users have switched from the open source version of clash to the premium one for various reasons, and they cannot learn how clash works by reading the source code even if they want to.

GitHub wiki can be set to allow editing from any logged in users, see this example: https://github.com/zricethezav/gitleaks/wiki
Wikis are meant to be edited by a group of people, in the case of clash wiki, the developers and power users.

See the GitHub doc for more info about wiki permissions: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis
