### ISSUE TITLE
clash tproxy tcp&udp代理与openvpn如何兼容

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#1090]
手机码字，回头补上信息。
--------------clash设定:------------
port: 3333
socks-port: 23456
redir-port: 23457
tproxy-port: 23458
allow-lan: true
tproxy: true
mode: rule
log-level: error
external-controller: 192.168.2.1:9990
experimental:
  ignore-resolve-fail: true
external-ui: dashboard
secret: "clash"

hosts:
  router.asus.com: 192.168.2.1
  services.googleapis.cn: 74.125.193.94

dns:
  enable: true
  listen: 0.0.0.0:23453
  ipv6: false
  enhanced-mode: redir-host 
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - tls://1.0.0.1:853
    - tls://dns.google
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
目前openvpn设备回家已经能正常走tcp&udp代理；
![image](https://user-images.githubusercontent.com/67776691/99870446-ea2dd000-2c0d-11eb-9f54-1e60dd918974.png)

但是当开启大陆白名单绕行。
iptables写法：
iptables -t mangle -A merlinclash -p udp -m set ! --match-set china_ip_route dst -j TPROXY --on-port "$tproxy_port" --tproxy-mark 0x01/0x01
iptables -t mangle -A merlinclash -p tcp -m set ! --match-set china_ip_route dst -j TPROXY --on-port "$tproxy_port" --tproxy-mark 0x01/0x01

DNS-iptables写法：
iptables -t nat -A PREROUTING -p udp -m set ! --match-set china_ip_route dst --dport 53 -j REDIRECT --to-ports 23453
此时能够正常访问外网，而国内全部断网；
设备打开下baidu.com。查连接显示：
![image](https://user-images.githubusercontent.com/67776691/99870493-5c061980-2c0e-11eb-881e-82a82645465f.png)

哪里设置问题请指正。附上iptables各表内容
![image](https://user-images.githubusercontent.com/67776691/99870514-9c659780-2c0e-11eb-9ebd-e06c8072b86d.png)

**Comment by DotWho** [comment]
同问，linux下iptables要怎么配
