### ISSUE TITLE
linux下启动问题

### ISSUE THREAD

**Issue by pptfz** [Dreamacro/clash#1091]
使用如下命令启动
```
[root@devops clash]# ./clash -d .
WARN[0000] MMDB invalid, remove and download 
```
---

但是是有这个MMDB文件的
```
[root@devops clash]# ls
clash  config.yaml  Country.mmdb
```

重新启动会报错MMDB文件无效
```
root@devops clash]# ./clash -d .
WARN[0000] MMDB invalid, remove and download  
```

死循环，这个不知道怎么解决

**Comment by ysc3839** [comment]
有这个文件不代表文件没损坏，log 已经说了 MMDB invalid。

**Comment by flyhigherpi** [comment]
-f指定路径好像

**Comment by Student414** [comment]
cat /etc/systemd/system/clash.service

```
[Unit]                                                         
Description=Clash Daemon                                       
                                                               
[Service]                                                      
ExecStart=/usr/local/bin/clash -d /etc/clash/                  
                                                               
[Install]                                                      
WantedBy=multi-user.target [Unit]                              
Description=Clash Daemon                                       
                                                               
[Service]                                                      
ExecStart=/usr/local/bin/clash -d /etc/clash/                  
                                                               
[Install]                                                      
WantedBy=multi-user.target 
```

**Comment by juewuy** [comment]
何不试试[ShellClash](https://github.com/juewuy/ShellClash)？

**Comment by nowhere99** [comment]
Country.mmdb 用户属性不对

**Comment by Xtreme-Light** [comment]
问题解决了没有？那个方法是有效的，怎么没有什么说明

**Comment by Xtreme-Light** [comment]
上面几个人的回答没一个在点子上的，估计 提问的人自己发现了问题所在，关闭了问题。我在这里追加一点内容，方便后续用户遇到相同问题快速解决。

1. config.yaml和Country.mmdb在同一个目录，都在~/.config/clash中，
2. 由于在~/.config/clash中，不同用户启动就可能会导致缺乏文件，比如自己用户装好的，然后root去启动，root的家目录中就没有对应的文件。
3. Country.mmdb 可以自己下载放到~/.config/clash中。

~~Country.mmdb用户属性不对~~ 
~~有这个文件不代表文件没损坏，log 已经说了 MMDB invalid。~~ 一般都会确定文件有没有下载完整
~~clash.service~~ 这个是去配置clash作为服务的，和执行clash报错有什么关系

**Comment by Xtreme-Light** [comment]
> 上面几个人的回答没一个在点子上的，估计 提问的人自己发现了问题所在，关闭了问题。我在这里追加一点内容，方便后续用户遇到相同问题快速解决。
> 
> 1. config.yaml和Country.mmdb在同一个目录，都在~/.config/clash中，
> 2. 由于在~/.config/clash中，不同用户启动就可能会导致缺乏文件，比如自己用户装好的，然后root去启动，root的家目录中就没有对应的文件。
> 3. Country.mmdb 可以自己下载放到~/.config/clash中。
> 
> ~Country.mmdb用户属性不对~
> ~有这个文件不代表文件没损坏，log 已经说了 MMDB invalid。~ 一般都会确定文件有没有下载完整
> ~clash.service~ 这个是去配置clash作为服务的，和执行clash报错有什么关系
> 
> 看题主遇到的问题估计就是和我一样的，ls直接 显示了三个文件。
> 其实clash执行后是去~/.config/clash中加载配置的，不是当前目录，所以题主下载好了也出现了问题。
> 
> 我也是按照其他人的教程走的，直接放到了同目录，可能是clash不同版本的执行方式不同？？教程过于古老导致出现这样的问题？反正已经解决了。

还是拎出来鞭尸一下，我参照的教程就是码农家园的为树莓派安装clash ：
https://www.codenong.com/cs106602785/
如果你也是用的这个教程，注意一下，==教程里让放的config.yaml的位置不对==。

**Comment by juewuy** [comment]
啊这，你自己折腾半天不如用ShellClash，对各种Linux系统的支持已经很完善了
你趟过的没趟过的坑早就被我趟过了

**Comment by Xtreme-Light** [comment]
> 啊这，你自己折腾半天不如用ShellClash，对各种Linux系统的支持已经很完善了
> 你趟过的没趟过的坑早就被我趟过了

我看见了你上面的回复，所以也试了一下ShellClash。自动化的确很强大，但是我因为解决了问题，就没再切换过去，只是试了一下引导。
对于这个Issue提出而不给出解决方案，下面都是不相关的回答才补充几句，毕竟没头没尾算什么事。你说对吧。
另外你这个ShellClash我会收藏一下，以后再试试，万分感谢你的付出！ @juewuy 

![image](https://user-images.githubusercontent.com/33019145/102962581-19dc3a80-4522-11eb-8576-3a897ed4f169.png)

**Comment by Doublefire-Chen** [comment]
把本地电脑用过的Country.mmdb拷贝过去覆盖原有文件，然后重新启动clash就行了

**Comment by Student414** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Andruegoing** [comment]
> 上面几个人的回答没一个在点子上的，估计 提问的人自己发现了问题所在，关闭了问题。我在这里追加一点内容，方便后续用户遇到相同问题快速解决。
> 
> 1. config.yaml和Country.mmdb在同一个目录，都在~/.config/clash中，
> 2. 由于在~/.config/clash中，不同用户启动就可能会导致缺乏文件，比如自己用户装好的，然后root去启动，root的家目录中就没有对应的文件。
> 3. Country.mmdb 可以自己下载放到~/.config/clash中。
> 
> ~Country.mmdb用户属性不对~ ~有这个文件不代表文件没损坏，log 已经说了 MMDB invalid。~ 一般都会确定文件有没有下载完整 ~clash.service~ 这个是去配置clash作为服务的，和执行clash报错有什么关系
> 
> 看题主遇到的问题估计就是和我一样的，ls直接 显示了三个文件。 其实clash执行后是去~/.config/clash中加载配置的，不是当前目录，所以题主下载好了也出现了问题。
> 
> 我也是按照其他人的教程走的，直接放到了同目录，可能是clash不同版本的执行方式不同？？教程过于古老导致出现这样的问题？反正已经解决了。

很多教程里都没提到不同用户的配置目录需要分别设置的问题，我也是卡了一天多才看到你的话，十分感谢
当然归根结底还是学艺不精，常年玩的高手可能遇到这个问题就意识到了

**Comment by 459737087** [comment]
> > 上面几个人的回答没一个在点子上的，估计 提问的人自己发现了问题所在，关闭了问题。我在这里追加一点内容，方便后续用户遇到相同问题快速解决。
> > 
> > 1. config.yaml和Country.mmdb在同一个目录，都在~/.config/clash中，
> > 2. 由于在~/.config/clash中，不同用户启动就可能会导致缺乏文件，比如自己用户装好的，然后root去启动，root的家目录中就没有对应的文件。
> > 3. Country.mmdb 可以自己下载放到~/.config/clash中。
> > 
> > ~Country.mmdb用户属性不对~ ~有这个文件不代表文件没损坏，log 已经说了 MMDB invalid。~ 一般都会确定文件有没有下载完整 ~clash.service~ 这个是去配置clash作为服务的，和执行clash报错有什么关系
> > 看题主遇到的问题估计就是和我一样的，ls直接 显示了三个文件。 其实clash执行后是去~/.config/clash中加载配置的，不是当前目录，所以题主下载好了也出现了问题。
> > 我也是按照其他人的教程走的，直接放到了同目录，可能是clash不同版本的执行方式不同？？教程过于古老导致出现这样的问题？反正已经解决了。
> 
> 很多教程里都没提到不同用户的配置目录需要分别设置的问题，我也是卡了一天多才看到你的话，十分感谢 当然归根结底还是学艺不精，常年玩的高手可能遇到这个问题就意识到了

请问这个Country.mmdb从哪里下载

**Comment by Andruegoing** [comment]
> > > 上面几个人的回答没一个在点子上的，估计 提问的人自己发现了问题所在，关闭了问题。我在这里追加一点内容，方便后续用户遇到相同问题快速解决。
> > > 
> > > 1. config.yaml和Country.mmdb在同一个目录，都在~/.config/clash中，
> > > 2. 由于在~/.config/clash中，不同用户启动就可能会导致缺乏文件，比如自己用户装好的，然后root去启动，root的家目录中就没有对应的文件。
> > > 3. Country.mmdb 可以自己下载放到~/.config/clash中。
> > > 
> > > ~Country.mmdb用户属性不对~ ~有这个文件不代表文件没损坏，log 已经说了 MMDB invalid。~ 一般都会确定文件有没有下载完整 ~clash.service~ 这个是去配置clash作为服务的，和执行clash报错有什么关系
> > > 看题主遇到的问题估计就是和我一样的，ls直接 显示了三个文件。 其实clash执行后是去~/.config/clash中加载配置的，不是当前目录，所以题主下载好了也出现了问题。
> > > 我也是按照其他人的教程走的，直接放到了同目录，可能是clash不同版本的执行方式不同？？教程过于古老导致出现这样的问题？反正已经解决了。
> > 
> > 
> > 很多教程里都没提到不同用户的配置目录需要分别设置的问题，我也是卡了一天多才看到你的话，十分感谢 当然归根结底还是学艺不精，常年玩的高手可能遇到这个问题就意识到了
> 
> 请问这个Country.mmdb从哪里下载

https://github.com/alecthw/mmdb_china_ip_list

**Comment by Student414** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by meethigher** [comment]
> 上面几个人的回答没一个在点子上的，估计 提问的人自己发现了问题所在，关闭了问题。我在这里追加一点内容，方便后续用户遇到相同问题快速解决。
> 
> 1. config.yaml和Country.mmdb在同一个目录，都在~/.config/clash中，
> 2. 由于在~/.config/clash中，不同用户启动就可能会导致缺乏文件，比如自己用户装好的，然后root去启动，root的家目录中就没有对应的文件。
> 3. Country.mmdb 可以自己下载放到~/.config/clash中。
> 
> ~Country.mmdb用户属性不对~ ~有这个文件不代表文件没损坏，log 已经说了 MMDB invalid。~ 一般都会确定文件有没有下载完整 ~clash.service~ 这个是去配置clash作为服务的，和执行clash报错有什么关系
> 
> 看题主遇到的问题估计就是和我一样的，ls直接 显示了三个文件。 其实clash执行后是去~/.config/clash中加载配置的，不是当前目录，所以题主下载好了也出现了问题。
> 
> 我也是按照其他人的教程走的，直接放到了同目录，可能是clash不同版本的执行方式不同？？教程过于古老导致出现这样的问题？反正已经解决了。

感谢

**Comment by Student414** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dbsxdbsx** [comment]
我发现这个问题到现在还是有。我是在NixOs里装机时发现的。我发现就算是把它自己下载的mmdb拷贝出来放到公开的repo里，再把它下载到`~/.config/clash/Country.mmdb`, 它还是会报错`MMDB invalid, remove and download`. "invalid"就说明它其实是找到的，但它认为是invalid的，真的很莫名。

**Comment by Student414** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wocaishiniliu** [comment]
Country.mmdb文件要在当前用户的.config/clash文件下面

**Comment by Student414** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
