### ISSUE TITLE
[Feature]HTTPS client with upstream SSR servers.

### ISSUE THREAD

**Issue by hongyi-zhao** [Dreamacro/clash#1095]
Hi,

Currently, I noticed that clash will accept HTTP connection on 7890 port and socks5(h) connection on 7891 port with the SSR upstream servers. But it seems that the HTTPS client connection is still unsupported yet.

Do you have any plan for adding this feature into clash?

Regards,
HY

**Comment by Dreamacro** [comment]
I'm not clear what you mean by not supporting HTTPS connections here.

**Comment by hongyi-zhao** [comment]
Sorry for my vague description. See the following testings for more what I mean.

```
$ curl -x https://127.0.0.1:7890 http://cachefly.cachefly.net/100mb.test -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:7890 

$ curl -x http://127.0.0.1:7890 http://cachefly.cachefly.net/100mb.test -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100M  100  100M    0     0  19.9M      0  0:00:05  0:00:05 --:--:-- 23.0M
```

So, I want to let clash expose a proxy with the form *https://127.0.0.1:7890* with the upstream SSR servers.

**Comment by Dreamacro** [comment]
It is enough to use the http proxy, which can also proxy HTTPS traffic (CONNECT)

**Comment by hongyi-zhao** [comment]
Thanks for your clarification.
