### ISSUE TITLE
[Bug]high warning event generated

### ISSUE THREAD

**Issue by serfend** [Dreamacro/clash#1096]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……window 10 企业版
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1.打开360
2.打开clash

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

什么都不发生

**实际上发生了什么？**

不断产生告警：

高危程序：***\clash.exe
发起来源：C:\WINDOWS\System32\cmd.exe
目标文件：C:\WINDOWS\System32\ROUTE.EXE
拦截时间：2020.11.23 21:21

程序正在进行远程线程注入，将代码藏匿到其他进程来运行，木马通常以此来隐藏自己的恶意行为。如果您不认识此程序，请阻止。

**Comment by luwah** [comment]
允许clash进入白名单或关闭360？

**Comment by serfend** [comment]
问题是为什么一定要进行线程注入呢，我发现我阻止注入后也不影响使用，只是会一直报拦截
![image](https://user-images.githubusercontent.com/20139227/99975040-ab9a4000-2ddc-11eb-847d-3f8b3790e64c.png)

**Comment by Dreamacro** [comment]
这是 clash for windows 的问题不是 clash 的问题。看起来是在设置路由 @Fndroid

**Comment by akw5454521** [comment]
这个应该在CFW那里提问吧，不过在那儿问了也没用，要是信360的话还是别用Clash(以及大部分梯子)了

**Comment by serfend** [comment]
是因为cfw自身原因导致需要添加路由吗，还是说clash提供此功能，以此来实现系统全局代理。
另外看到还有注入其他进程的行为。
发起来源：C:\Users\huawei\AppData\Local\Programs\Clash for Windows\Clash for Windows.exe
目标文件：C:\Program Files (x86)\sogoupinyin\9.8.0.3746\SGTool.exe
拦截时间：2020.11.24 09:00
程序正在进行远程线程注入，将代码藏匿到其他进程来运行，木马通常以此来隐藏自己的恶意行为。如果您不认识此程序，请阻止。

**Comment by Fndroid** [comment]
用route命令查了下路由表，用来识别本地网卡

**Comment by AkariiinMKII** [comment]
> 用route命令查了下路由表，用来识别本地网卡

为避嫌可以给auto detect加个开关（
