### ISSUE TITLE
[Feature]请教Clash core 1.3.0 是否已经支持 VmessAEAD 和 VLESS

### ISSUE THREAD

**Issue by jimmygiven** [Dreamacro/clash#1098]
看了最近两个版本的release说明，没有提到 VmessAEAD 和 VLESS ，但是看Milestone里VLESS是1.3.0的更新内容，请问目前core对这两项的支持情况如何呢？
小白不太懂更新的发布的逻辑，还请各位多多包涵

**Comment by Dreamacro** [comment]
还没有，AEAD 目前还没正式敲定（stable），vless 由于种种原因现在不太清楚状况，暂不支持

**Comment by jimmygiven** [comment]
> 还没有，AEAD 目前还没正式敲定（stable），vless 由于种种原因现在不太清楚状况，暂不支持

好的。谢谢解答。
