### ISSUE TITLE
FAKEIP模式因为在NAT OUTPUT链加了语句导致国内上不去

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#1099]
像是一个坑。
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 23453
加完，国外翻墙正常。
国内访问全断网。
求解呢？排查了一下午。

**Comment by huyz-git** [comment]
因为你这样会导致 clash 在发起直连时，请求的 dns 也被 redirect 回了 clash 里，从而导致 clash 试图连接一个 fake ip。
正确的做法是，你在透明代理其他部分是如何排除 clash 的流量的，这里就也要相应的排除 clash。比如，用另一个 uid 1234 跑 clash，那就不要 redirect uid 1234 产生的 dns 流量：
```
iptables -t nat -A OUTPUT -m owner --uid-owner 1234  -p udp --dport 53 -j RETURN
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 23453
```

**Comment by flyhigherpi** [comment]
> 因为你这样会导致 clash 在发起直连时，请求的 dns 也被 redirect 回了 clash 里，从而导致 clash 试图连接一个 fake ip。
> 正确的做法是，你在透明代理其他部分是如何排除 clash 的流量的，这里就也要相应的排除 clash。比如，用另一个 uid 1234 跑 clash，那就不要 redirect uid 1234 产生的 dns 流量：
> 
> ```
> iptables -t nat -A OUTPUT -m owner --uid-owner 1234  -p udp --dport 53 -j RETURN
> iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 23453
> ```

原来这样，华硕路由不支持这些指令。蛋疼。

**Comment by huyz-git** [comment]
> > 因为你这样会导致 clash 在发起直连时，请求的 dns 也被 redirect 回了 clash 里，从而导致 clash 试图连接一个 fake ip。
> > 正确的做法是，你在透明代理其他部分是如何排除 clash 的流量的，这里就也要相应的排除 clash。比如，用另一个 uid 1234 跑 clash，那就不要 redirect uid 1234 产生的 dns 流量：
> > ```
> > iptables -t nat -A OUTPUT -m owner --uid-owner 1234  -p udp --dport 53 -j RETURN
> > iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 23453
> > ```
> 
> 原来这样，华硕路由不支持这些指令。蛋疼。

或者你也可以，给 clash 配置专门的 dns，并确保这个 dns 在你的系统的其他地方不会出现。
比如 clash 配置 223.5.5.5，然后系统其他地方都不会用到 223.5.5.5 这个 dns，此时在 iptables 绕过这个 dns 也行：
```
iptables -t nat -A OUTPUT -p udp --dport 53 --dst 223.5.5.5 -j RETURN
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 23453
```

或者更简单一点，给 clash 配置（且仅配置）非 53 端口的 dns，如 DoH，DoT。这样 clash 在直连时发出的 DNS 请求也不会被重定向。

**Comment by juewuy** [comment]
没必要一定使用output
大多数时候preouting链更适合

**Comment by flyhigherpi** [comment]
> 没必要一定使用output
> 大多数时候preouting链更适合

output是给路由自身走clash上github更新插件的东西用。

**Comment by ttimasdf** [comment]
iptables 问题需要在 clash 里面提 issue 么……

路由器本机走代理直接 `export http_proxy https_proxy` 就可以了吧
