### ISSUE TITLE
Can't open software in windows

### ISSUE THREAD

**Issue by zhangyq008** [Dreamacro/clash#11]
I have a go environment and the environment variables are set.
    
![snipaste_2018-10-06_22-17-34](https://user-images.githubusercontent.com/42995962/46572296-092d6180-c9b6-11e8-87b7-6c4a5fb6053f.png)
![snipaste_2018-10-06_22-16-33](https://user-images.githubusercontent.com/42995962/46572301-134f6000-c9b6-11e8-99e2-23bc4aca9593.png)

**Comment by Dreamacro** [comment]
First, the Golang environment is not required to use `clash`. you can run `clash-win64.exe` directly.

The configuration file in `$HOME/.config/clash`, for Windows, you can go https://en.wikipedia.org/wiki/Home_directory to find your `$HOME`
