### ISSUE TITLE
[Feature] 把 premium 每个新版本分开 tag

### ISSUE THREAD

**Issue by Artoria2e5** [Dreamacro/clash#1101]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### Clash core config & log & env

开发过程建议，无意义

### 说明 Description

Clash 目前把所有的 premium 版本放在同一个 release 上，在 [releases 列表](https://github.com/Dreamacro/clash/releases) 里的排序一直靠后很有问题。应该在每个 premium 版本的时候都 tag 一个 release，以便在列表中保持靠前。

考虑到 premium 并没有对应的源码，可以开一个只有 markdown 文件的 branch 用来 tag。

**Comment by Undefined-User** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium

**Comment by Artoria2e5** [comment]
我知道那个在那里啊……
