### ISSUE TITLE
[Feature]请求支持XTLS

### ISSUE THREAD

**Issue by eMeab** [Dreamacro/clash#1103]
XTLS 对于性能有巨大提升。 希望clash也能支持一下

**Comment by akw5454521** [comment]
V社区都没了吧

**Comment by eMeab** [comment]
> V社区都没了吧

分开了.  现在是 Xray-core[https://github.com/XTLS/Xray-core](url)

**Comment by canflyx** [comment]
希望加入xray就可以了
