### ISSUE TITLE
[Bug]authentication问题

### ISSUE THREAD

**Issue by iHandle** [Dreamacro/clash#1104]
config.yaml里authentication字段设置：
```
authentication:
  - "usr:pwd"
```
在浏览器使用witchyOmega可以正常代理，但是设置git http.proxy无法正常代理。
```
➜  ~ git config --global http.proxy http://usr:pwd@127.0.0.1:7890  
➜  ~ git clone https://github.com/Dreamacro/clash.git            
Cloning into 'clash'...
fatal: unable to access 'https://github.com/Dreamacro/clash.git/': Proxy CONNECT aborted

# 去掉config.yaml的authentication字段后
➜  ~ git config --global http.proxy http://127.0.0.1:7890 
➜  ~ git clone https://github.com/Dreamacro/clash.git    
Cloning into 'clash'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 4167 (delta 1), reused 2 (delta 0), pack-reused 4158
Receiving objects: 100% (4167/4167), 911.98 KiB | 188.00 KiB/s, done.
Resolving deltas: 100% (2454/2454), done.
```

**Comment by Dreamacro** [comment]
```
git config --global http.proxyAuthMethod 'basic'
```

Source: https://git-scm.com/docs/git-config#git-config-httpproxyAuthMethod

**Comment by Dreamacro** [comment]
I would checkout if I can support git's `anyauth`.

**Comment by iHandle** [comment]
> 
> 
> ```
> git config --global http.proxyAuthMethod 'basic'
> ```
> 
> Source: https://git-scm.com/docs/git-config#git-config-httpproxyAuthMethod

Thanks!

**Comment by Dreamacro** [comment]
@iHandle support `anyauth` on dev branch

**Comment by rexSurprise** [comment]
配置
![image](https://user-images.githubusercontent.com/64947085/131632575-09c955b5-d2e7-4a52-9fa2-d675384e928b.png)
SwitchOmega这么设置
![image](https://user-images.githubusercontent.com/64947085/131632342-69d1b00a-8711-4bcb-9b63-95f622b93dab.png)
倒是连接不上，日志如下
![image](https://user-images.githubusercontent.com/64947085/131632510-fe8cb375-e85b-4e78-b723-446ff6ee83e1.png)
出现这样的错误

**Comment by rexSurprise** [comment]
![image](https://user-images.githubusercontent.com/64947085/131633205-55971454-6efe-4052-ad4c-0514e2dab9e8.png)

**Comment by zyfyy** [comment]
```
export http_proxy=http://usr:pass@127.0.0.1:7890
```
just good

**Comment by zyfyy** [comment]
> config.yaml里authentication字段设置：
> 
> ```
> authentication:
>   - "usr:pwd"
> ```
> 
> 在浏览器使用witchyOmega可以正常代理，但是设置git http.proxy无法正常代理。
> 
> ```
> ➜  ~ git config --global http.proxy http://usr:pwd@127.0.0.1:7890  
> ➜  ~ git clone https://github.com/Dreamacro/clash.git            
> Cloning into 'clash'...
> fatal: unable to access 'https://github.com/Dreamacro/clash.git/': Proxy CONNECT aborted
> 
> # 去掉config.yaml的authentication字段后
> ➜  ~ git config --global http.proxy http://127.0.0.1:7890 
> ➜  ~ git clone https://github.com/Dreamacro/clash.git    
> Cloning into 'clash'...
> remote: Enumerating objects: 9, done.
> remote: Counting objects: 100% (9/9), done.
> remote: Compressing objects: 100% (9/9), done.
> remote: Total 4167 (delta 1), reused 2 (delta 0), pack-reused 4158
> Receiving objects: 100% (4167/4167), 911.98 KiB | 188.00 KiB/s, done.
> Resolving deltas: 100% (2454/2454), done.
> ```

使用插件反而不能和@[rexSurprise](https://github.com/rexSurprise) 一样
