### ISSUE TITLE
[Bug]ClashX pro Apple Sillicon 版本退出后没有取消系统proxy

### ISSUE THREAD

**Issue by luokebi** [Dreamacro/clash#1106]
------------------------------------------------------------------

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
MacOs Big Sur 11.0.1 (M1)
……

### 说明 Description
取消"Set as system proxy"和退出app都不能还原系统代理设置

**我预期会发生……？**
退出app之后取消系统proxy

**实际上发生了什么？**
退出app之后系统代理设置还在，导致无法上网

**Comment by yichengchen** [comment]
可以提供CXP的log吗，我在dtk上试了一下没问题。是每次都会发生吗？

**Comment by luokebi** [comment]
@yichengchen 我刚才又试了一下，这次又没问题，我现在怎么也重现不出来了，我只能描述一下当时的情景

1. 当时连接着一个网络，电脑合盖了（未关机）
2. 第二天，到了另一个地方，打开电脑，这时没有联网，这时我手动退出了cxp
3. 手动连上网，发现上不了网
4. 再次打开cxp,发现可以上了，这时立即再次退出cxp，又没法上了
5. 随后测试退出或者反选"设置为系统代理"均没有改变系统proxies

另外cxp这个版本好像没有跟随系统语言变化语言

**Comment by Dreamacro** [comment]
seems fixed, close
