### ISSUE TITLE
[Bug] tproxy 端口收到非 tproxy 流量时 clash 大量建立连接

### ISSUE THREAD

**Issue by huyz-git** [Dreamacro/clash#1107]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
tproxy-port: 5000
mode: Direct
loglevel: info
```

</details>

### Clash log

```
INFO[0025] [TCP] 127.0.0.1:41496 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41498 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41500 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41502 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41504 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41506 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41508 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41510 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41512 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41514 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41516 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41518 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41520 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41522 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41524 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41526 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41528 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41530 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41532 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41534 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41536 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41538 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41540 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41542 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41544 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41546 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41548 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41550 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41552 --> 127.0.0.1 using DIRECT 
INFO[0025] [TCP] 127.0.0.1:41554 --> 127.0.0.1 using DIRECT
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Archlinux
* 网路环境或拓扑 (network conditions/topology)
lo only
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
此 bug 不涉及 DNS
* 其他 (any other information that would be useful)
……

### 说明 Description

clash 的 tproxy 端口收到非 tproxy 流量（如 nmap，curl，telnet 等）时，日志里大量刷出 `INFO[0025] [TCP] 127.0.0.1:41554 --> 127.0.0.1 using DIRECT` 的信息，有时最终会以 `too many open files` 结束，有时则一直刷。

### 重现问题的具体布骤 Steps to Reproduce

1. 创建一个有 tproxy 端口的配置，其余配置随意，mode: Direct 也行
2. 往 tproxy 端口里发送一些非 tproxy 流量，比如：
  - nmap 127.0.0.1 -p 5000
  - curl 127.0.0.1:5000
  - telnet 127.0.0.1 5000
  - dig @127.0.0.1 -p5000 github.com

**我预期会发生……？**

clash 不应该因此大量建立连接

**实际上发生了什么？**

clash 大量建立连接，日志大量刷出 `INFO[0025] [TCP] 127.0.0.1:41554 --> 127.0.0.1 using DIRECT`

**Comment by Dreamacro** [comment]
same as #425

**Comment by huyz-git** [comment]
> same as #425

原来如此
我只搜了 tproxy 没找到相关 issue，没想到 redir 那边已经有人提过了

**Comment by DotWho** [comment]
> ### Clash config
> config.yaml
> ### Clash log
> ```
> INFO[0025] [TCP] 127.0.0.1:41496 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41498 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41500 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41502 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41504 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41506 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41508 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41510 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41512 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41514 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41516 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41518 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41520 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41522 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41524 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41526 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41528 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41530 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41532 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41534 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41536 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41538 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41540 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41542 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41544 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41546 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41548 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41550 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41552 --> 127.0.0.1 using DIRECT 
> INFO[0025] [TCP] 127.0.0.1:41554 --> 127.0.0.1 using DIRECT
> ```
> 
> ### 环境 Environment
> * 操作系统 (the OS that the Clash core is running on)
>   Archlinux
> * 网路环境或拓扑 (network conditions/topology)
>   lo only
> * iptables，如果适用 (if applicable)
>   无
> * ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
>   此 bug 不涉及 DNS
> * 其他 (any other information that would be useful)
>   ……
> 
> ### 说明 Description
> clash 的 tproxy 端口收到非 tproxy 流量（如 nmap，curl，telnet 等）时，日志里大量刷出 `INFO[0025] [TCP] 127.0.0.1:41554 --> 127.0.0.1 using DIRECT` 的信息，有时最终会以 `too many open files` 结束，有时则一直刷。
> 
> ### 重现问题的具体布骤 Steps to Reproduce
> 1. 创建一个有 tproxy 端口的配置，其余配置随意，mode: Direct 也行
> 2. 往 tproxy 端口里发送一些非 tproxy 流量，比如：
> 
> * nmap 127.0.0.1 -p 5000
> * curl 127.0.0.1:5000
> * telnet 127.0.0.1 5000
> * dig @127.0.0.1 -p5000 github.com
> 
> **我预期会发生……？**
> 
> clash 不应该因此大量建立连接
> 
> **实际上发生了什么？**
> 
> clash 大量建立连接，日志大量刷出 `INFO[0025] [TCP] 127.0.0.1:41554 --> 127.0.0.1 using DIRECT`
> 
> ### 可能的解决方案 Possible Solution
> ### 更多信息 More Information

请教用tproxy 端口的话 iptables 该如何配置
