### ISSUE TITLE
[Feature]Clash支持的规则类型能否添加udp类型

### ISSUE THREAD

**Issue by fishg** [Dreamacro/clash#1108]
Clash支持的规则类型能否添加udp类型的单独配置，这样方便把udp定向指定到支持udp的代理。在配置多个代理的情况，可能其中部分代理支持udp，部分不支持，能针对udp单独配置规则控制上就方便很多。

**Comment by akw5454521** [comment]
直连的udp咋办

**Comment by xiakeng** [comment]
我是这么做的。

首先设置proxy-group的udp-diabled(或者把平时用来上网视频不需要udp的proxy取消udp:true)，让平时访问网页视频的流量忽略udp
在Match后面加入udp规则
类似：
- MATCH,🐟漏网之鱼

# Udp
- DOMAIN-KEYWORD,googlevideo,DIRECT
- DOMAIN-KEYWORD,fnz,💻FNZUdp
- MATCH,🖧UdpRedirect


这样，直连和geoip还是可以直连udp
由于🐟漏网之鱼设置了udp-diabled，所有没有命中规则的会走🖧UdpRedirect
也可以设置另外的proxy-group比如💻FNZUdp，针对不同的udp请求走不同的proxy

**Comment by fishg** [comment]
@xiakeng 感谢~明白udp-diabled怎么用了

**Comment by fishg** [comment]
@xiakeng udp-diabled 配置模板能发个片段吗？我不太确认配置到哪个位置
