### ISSUE TITLE
[Feature]replace webosocket client

### ISSUE THREAD

**Issue by yukunwu** [Dreamacro/clash#1109]
我都确认过了，我要继续提交。

### 说明 Description

参见文章 https://yalantis.com/blog/how-to-build-websockets-in-go/
或者参见下面文档，作者是如何提升ws性能，减少资源占用的
[1m connections for websocket.pdf](https://github.com/Dreamacro/clash/files/5615293/1m.connections.for.websocket.pdf)
建议
客户端使用:[gowebsocket](https://github.com/sacOO7/gowebsocket)
服务端使用:[gobws](https://github.com/gobwas/ws)

**Comment by Dreamacro** [comment]
服务端用 github.com/gobwas/ws 倒是还行，这库我也用过，但 clash 是一个客户端

至于 https://github.com/sacOO7/gowebsocket 就敬谢不敏了，这个库看起来并没有维护了，也没经过太多生产环境的验证。还不如 https://github.com/nhooyr/websocket

**Comment by yukunwu** [comment]
fine,哈哈，作者能优化最好，clash确实比较耗资源

**Comment by Dreamacro** [comment]
@yukunwu 耗资源应该是相对的吧，ws 功能目前只在 vmess 和流式 API 里用到，如果用 ss 之类的应该是无关的吧？相比 v2ray-core，clash 的占用应该是稍低的吧

**Comment by yukunwu** [comment]
是的，只能说 to be better
