### ISSUE TITLE
[Bug] 转发onion、i2p等域名时DNS解析错误

### ISSUE THREAD

**Issue by proxy-rules** [Dreamacro/clash#1111]
------------------------------------------------------------------

### Clash config

```yaml
- rules:
  - DOMAIN-SUFFIX,onion,tor
```

### Clash log

```
ResolveMsg failure: All DNS requests failed, first error: dns: bad rdata
```

**我预期会发生……？**

onion、i2p这类域名无需解析，直接转发。

**实际上发生了什么？**

### 可能的解决方案 Possible Solution

支持`DOMAIN-SUFFIX`使用`no-resolve`

**Comment by proxy-rules** [comment]
可能相关的issue #994

**Comment by Dreamacro** [comment]
这里应该没啥问题，DOMAIN-SUFFIX 就是不解析 ip 的，前提是进来的流量里直接包含着域名（redir-host 必然解析）。或者直接用 socks5 或 http 代理

**Comment by proxy-rules** [comment]
感谢回复。此问题已解决。

**Comment by xingdaos** [comment]
> 感谢回复。此问题已解决。

请问是如何解决的，我目前也遇到了这个问题
