### ISSUE TITLE
[Feature]能否提供专用于直连的socket或者http端口呢

### ISSUE THREAD

**Issue by Hermaros** [Dreamacro/clash#1113]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------
是否可能提供一个额外的端口提供直连服务，方便在透明代理等运行方式下保证BT下载qq或者其他需要直连且可以设置代理服务器的软件直接出站。

**Comment by luwah** [comment]
PROCESS-NAME in rules:
PROCESS-NAME,nc,DIRECT
# routes the process nc to DIRECT. (support macOS、Linux、FreeBSD and Windows)

**Comment by Hermaros** [comment]
@luwah 但这类规则只对来自本机的连接有效，而且会受dns反查的影响，导致权重低于所有域名类规则。所以曾考虑过在clash的运行端再运行一个socket桥接进程，再针对这个桥接进程做进程名规则，但不知道有没有现成的软件可实现桥接，而且也不确定是否会如预期运作。

**Comment by Hermaros** [comment]
又想了一下，似乎再运行一个ss全局直连就行，我反倒想复杂了。

**Comment by kongminhao** [comment]
src_ip,192.168.x.x,DIRECT
