### ISSUE TITLE
[Bug] clash.razord.top IPv6 Host "Connections" function is invalid

### ISSUE THREAD

**Issue by iTZQing** [Dreamacro/clash#1114]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS 11.0.1（20B29）

* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
No
* 其他 (any other information that would be useful)
Browser：Safari 14.0.1, Chrome 87.0.4280.88
Clash by Router (Padavan) Ver. 2020.11.20

### 说明 Description

使用 IPv6 本地地址進入 Clash Web 管理頁面 http://clash.razord.top ，無法使用“連接”功能，查看不了連結列表。

### 重现问题的具体布骤 Steps to Reproduce

1. 進入 http://clash.razord.top
2. 填入本地地址 (IPv6) 和端口及密碼點擊“確定”進入
3. 選擇“連接”

**我预期会发生……？**

正常使用所有功能

**实际上发生了什么？**

無法使用“連接”功能，查看不了連結列表。

### 可能的解决方案 Possible Solution

使用 IPv4 地址沒有問題，但是 v6 地址的問題依舊存在。
 
### 更多信息 More Information
<img width="1546" alt="截圖 2020-12-04 上午1 19 02" src="https://user-images.githubusercontent.com/5062100/101065602-4f9b9c80-35d0-11eb-8036-c186800964c5.png">
<img width="1546" alt="截圖 2020-12-04 上午1 19 22" src="https://user-images.githubusercontent.com/5062100/101065613-532f2380-35d0-11eb-93e2-40980e4e38f2.png">

**Comment by Dreamacro** [comment]
dashboard 的 bug，等有空解决

**Comment by iTZQing** [comment]
> dashboard 的 bug，等有空解决

還有 HTTPS 的網站 https://clash.razord.top ，不管什麼情況下都無法使用的問題。流程步驟和以上相似（不管是 v6 還是 v4 地址，有無 Secret）
需要我新開一個 issues 來供標記麼 xddd😂

**Comment by Dreamacro** [comment]
@iTZQing https 的 dashboard 不能用不算是一个 bug https://github.com/Dreamacro/clash-dashboard/pull/33#issuecomment-633226557
