### ISSUE TITLE
Clash的dns fallback 到底走不走代理呢？

### ISSUE THREAD

**Issue by fishg** [Dreamacro/clash#1115]
Clash的dns fallback 到底走不走代理呢？ 在链接信息里完全看不到dns请求信息

**Comment by Dreamacro** [comment]
不走代理

**Comment by fishg** [comment]
因为发现有时候解析很慢，而且不能获得代理server当地就近的ip，是否考虑支持dns server走代理转发呢？或者有已经支持的方法？

**Comment by LazyZhu** [comment]
Check https://github.com/Dreamacro/clash/pull/868 `Feature: Use Proxy to Lookup Fallback DNS`
@fishg

**Comment by fishg** [comment]
> Check #868 `Feature: Use Proxy to Lookup Fallback DNS`
> @fishg

看起来还没有结论，这个问题是否考虑进一步解决？

**Comment by Loyalsoldier** [comment]
https://github.com/Dreamacro/clash/pull/868#issuecomment-740563188

**Comment by fishg** [comment]
> [#868 (comment)](https://github.com/Dreamacro/clash/pull/868#issuecomment-740563188)

868 已经被关闭，不知道还会不会被关注。
