### ISSUE TITLE
[Feature] 多 Outbound interface 支持

### ISSUE THREAD

**Issue by no1xsyzy** [Dreamacro/clash#1118]
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

我都确认过了，我要继续提交。

------------------------------------------------------------------

### 环境

* 网路环境或拓扑

1. 多个 interface，可能是多张网卡或者 VPN（Zerotier 之类的）

### 说明

当存在多个 interface 的时候 DIRECT 不能选择正确的 interface

### 可能的解决方案（按推荐顺序）

1. 新增一个 proxy type，内容仅配置一个 outbound Interface（同时可以用于 relay？）
2. 支持不确定的 Outbound interface（根据系统路由表决定）
3. 配置多个 Outbound interface

**Comment by sbilly** [comment]
感觉支持并行和 zerotier 没关系。比如有两个公网 IP 的 v2ray 或 ss，clash 在一个连接中只能使用一个吧？

**Comment by no1xsyzy** [comment]
@sbilly 啊确实，我只考虑了我的场景

**Comment by no1xsyzy** [comment]
更新了一下内容，使其更一般化。有任何想法吗？

**Comment by david9991** [comment]
其实就是 Surge 的 Bind Network Interface 这个功能，很常用。像我有个k8s homelab，会涉及到很多外部 VPN 的问题。目前还只有 Surge 可以满足。

**Comment by GainSury** [comment]
还有一个问题，Windows only，多网卡direct选择的出口没有根据路由表出，而是根据interface的数字排序出流量

**Comment by horizonl** [comment]
同有此需求，两张网卡，一张查文献一张打游戏，写了路由表貌似没起作用。
