### ISSUE TITLE
clashx pro 问题

### ISSUE THREAD

**Issue by spacexnasa** [Dreamacro/clash#1119]
clashx pro 目前最新版
big sure 最新正式版

config.yaml

port: 3128
socks-port: 1080
redir-port: 3127
mixed-port: 3129
external-controller: 127.0.0.1:9090
allow-lan: true
bind-address: '0.0.0.0'
ipv6: false
mode: rule

proxies:
   - { 'name': "vk" , 'type': 'socks5', 'server': 1.1.1.1, 'port': 33211,'username': 'ok', 'password': 'okaok' ,'tls':  false, 'udp': false }
proxy-groups:
   - { name: fortest, type: select, proxies: ['vk'] }
----
- IP-CIDR,10.8.1.0/24, fortest,no-resolve
---
目前一切正常，但是有个小问题，我在 yaml 文件里面配置了 socks5代理，为了测试

curl 命令行下， curl -x http://1.1.1.1:33211  http://10.8.1.2  访问是没有问题的，浏览器里面有问题，经过排查，当 clashx 开启之后，会自动在 代理里面加内容 
192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local, timestamp.apple.com
这里可以去掉么？
![image](https://user-images.githubusercontent.com/3109626/101335501-405c6d80-38b4-11eb-9195-69a73060f9dd.jpeg)

<img width="609" alt="clash问题" src="https://user-images.githubusercontent.com/3109626/101335108-b6140980-38b3-11eb-8102-dbcf09a65c39.png">

如图

**Comment by Dreamacro** [comment]
@yichengchen

**Comment by yichengchen** [comment]
参加clashx readme https://github.com/yichengchen/clashX Advance Config部分设置ignoreList.plist

**Comment by spacexnasa** [comment]
> 参加clashx readme https://github.com/yichengchen/clashX Advance Config部分设置ignoreList.plist

谢谢作者的指导，还有@Dreamacro ，更改之后，问题解决了，之前有看到过这个，不理解啥意思，碰到了问题，经过指导，终于明白了。再次感谢你们的付出。
