### ISSUE TITLE
[Feature]显示实时速率功能能否可以忽略DIRECT的流量

### ISSUE THREAD

**Issue by get-set** [Dreamacro/clash#1120]
个人非常中意“显示实时速率”的功能，不过在意这个功能的大多是关心是否用掉了购买的流量，所以，请问该功能是否可以过滤掉DIRECT等不产生代理费用的流量？谢谢！

**Comment by akw5454521** [comment]
这个还是以服务商的统计数据为准吧，难道要一直盯着仪表盘心算吗

**Comment by get-set** [comment]
不是盯着仪表盘心算哈，有时也是方便看配置规则是否走了代理（这个比较直观，比如看优酷或ytb的时候，抬眼就知道哪个网站在跑代理流量，当然啦也可以把控制台调出来）。
因为Clash的配置功能还是挺强大的，所以我想的是把系统、终端、各种IDE直接都配置上代理，所以现在“显示实时速率”中的速度基本就是全部带宽，既然是代理软件，还是比较关注真正有多少流量走了代理。
个人意见哈~

**Comment by shawn-bluce** [comment]
这个思路着实是有点奇怪，我一度以为是有什么程序在偷跑流量，从梯子服务商哪儿又看不到，hhh
