### ISSUE TITLE
[Bug] git fetch `ssh_dispatch_run_fatal: message authentication code incorrect`

### ISSUE THREAD

**Issue by smallst** [Dreamacro/clash#1121]
------------------------------------------------------------------
使用clash代理无法进行 `git fetch` ，或者说无法完整进行 `git fetch` ，通常连接了 10% 左右后会出现标题所示错误。
而使用代理方法本身的客户端（比如ss，v2ray）不会有这个问题。

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by Dreamacro** [comment]
是这个吗 #1104

**Comment by smallst** [comment]
可能相似？但触发情况不一样
目前我的触发情况分两种，一：使用 openclash作为路由器代理，电脑端直接 git fetch git@github.com/xxx。 二：使用本地 clash，然后用 proxychains git fetch git@github.com/xxx. 两种方式都触发一致的验证错误。

**Comment by Dreamacro** [comment]
那就不一样了，你这个是 ssh 的连接，没遇到过这个错误，有其他电脑试试都有这个错误么

**Comment by smallst** [comment]
有的，我试试

**Comment by smallst** [comment]
应该和 https://github.com/Dreamacro/clash/issues/995 是同一个 issue，不准备重新开放这个了
