### ISSUE TITLE
[Feature] Script 模式能支持匹配 process_name 吗

### ISSUE THREAD

**Issue by huyz-git** [Dreamacro/clash#1125]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
mode: Script
script:
  code: |
    def main(ctx, metadata):
      ctx.log(str(metadata.keys()))
      ctx.log(str(dir(ctx)))
      return "Proxy"
```

### Clash log

```
INFO[0000] ["type", "network", "host", "src_ip", "src_port", "dst_port", "dst_ip"]
INFO[0000] ["geoip", "log", "proxy_providers", "resolve_ip", "rule_providers"]
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Linux
* 使用者的操作系统 (the OS running on the client)
Linux
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

在 Script 模式下，通过 `ctx.log(str(metadata.keys()))` 发现，`metadata` 只有 `["type", "network", "host", "src_ip", "src_port", "dst_port", "dst_ip"]` 这些 key，没有记录 process name 的 key。
同时，通过 `ctx.log(str(dir(ctx)))` 发现，`ctx` 只有 `["geoip", "log", "proxy_providers", "resolve_ip", "rule_providers"]` 这些方法，也没有“获取 process name”的方法。
于是在我的理解里，现在的 script 模式好像不能匹配 process name。这样的话 script 模式甚至还没法实现所有 rule 模式中能实现的匹配方式。

### 可能的解决方案 Possible Solution

能否给 `metadata` 加个 `process_name` 的 key，或者给 `ctx` 加个 `resolve_process_name` 的方法。

**Comment by Dreamacro** [comment]
最近在弄 tracing，等抽空就加

**Comment by Dreamacro** [comment]
done

**Comment by huyz-git** [comment]
> done

我刚刚发现这个函数好像有一个 bug，当某个 metadata 调用 resolve_process_name 失败之后，script 里后面的匹配都不会被执行，

此时日志里有
```
[warning] [Metadata] parse failed: no such process
```
的记录。随后这个 metadata 好像直接就被丢掉了，没有发起连接。

一个简易的复现脚本：
```python
def main(ctx,metadata):
  ctx.log("before process")
  process_name = ctx.resolve_process_name(metadata)
  ctx.log(process_name)
  return "DIRECT"
```
或者：
```python
def main(ctx,metadata):
  process_name = ctx.resolve_process_name(1)
  return "DIRECT"
```
前者当匹配到无法解析进程名的流量时，该流量未建立连接。后者则任何流量都不会建立连接。

可能的解决方案有两个：
- 按 resolve_ip 函数那样处理，当无法解析进程名的时候，返回空字符串，不要报错
- 在 script 里支持 python 的 try except 语法

**Comment by Dreamacro** [comment]
@huyz-git 确实有这个问题，但是如果直接返回空，错误信息就会丢失。resolve_ip 也是类似的，当这类函数发生错误时，你会觉得这类错误信息很重要吗

**Comment by huyz-git** [comment]
> @huyz-git 确实有这个问题，但是如果直接返回空，错误信息就会丢失。resolve_ip 也是类似的，当这类函数发生错误时，你会觉得这类错误信息很重要吗
错误信息是否重要这个我也说不清楚。

刚刚试了下，好像 resolve_ip 出错时也会导致 metadata 被丢掉
但 resolve_ip 出错导致丢 metadata 这个影响并不大，因为若 metadata 没有 dst_ip，host 又不能 resolve_ip，那么这个 metadata 通常情况下本来就没法正常连接。因此丢了它通常也无所谓。
但是 resolve_process_name 这个出错的影响就比较大，因为这样就有可能出现一个完全正常的 metadata 仅仅由于无法解析进程名而被丢掉。因此我觉得最好能有办法使得 resolve_process_name 出现错误时不会连带着把 metadata 丢掉。

我想到的一个方法就是支持一下 python 的 try except 语法。这样就可以实现既保留错误信息，又保证规则匹配在任何时候都能正常进行。

**Comment by huyz-git** [comment]
另外这个 wiki 样例是不是需要改一下：
```python
def main(ctx, metadata):
    # ctx.rule_providers["geoip"].match(metadata) return false

    ip = ctx.resolve_ip(metadata["host"])
    if ip == "":
        return "DIRECT"
    metadata["dst_ip"] = ip

    # ctx.rule_providers["iprule"].match(metadata) return true

    return "Proxy"
```
这个例子让人很容易误解为，resolve_ip 出错时只是返回空字符串，后续的 script 还能正常执行。但实际上它并不是这样。

**Comment by Dreamacro** [comment]
resolve_ip 在 throw 的情况下，其实还是可以正常工作的。如果后续的规则能匹配到代理的话。

try except 这个目前 starlark-go 似乎还不支持。

wiki 里的代码才是我预期的效果，throw 不影响这个函数的执行。

报错信息这个问题的话，就以你自己的使用情况来说，你觉得你需要这个错误信息吗

**Comment by huyz-git** [comment]
> resolve_ip 在 throw 的情况下，其实还是可以正常工作的。如果后续的规则能匹配到代理的话。

是么？
```python
def main(ctx,metadata):
  ctx.resolve_ip("aa")
  return "PROXY"
```
这个脚本我这里实测是所有流量都无法连通的。

报错信息就我自己使用情况而言，我觉得并不需要。
因为当我收到一个空字符串的进程名时候，我已经可以通过这个结果知道进程名没被解析出来了。

如果要保留错误信息，还有一种方法就是把错误信息放到函数返回值里，比如：
```
process_name, err = ctx.resolve_process_name(metadata)
if err!=None:
  ctx.log("resolve process name failed with error: " + err)
else:
  if process_name = "some_process":
    return "DIRECT"
```

**Comment by Dreamacro** [comment]
> resolve_ip 在 throw 的情况下，其实还是可以正常工作的。如果后续的规则能匹配到代理的话。

我这里的意思是，即使返回的是空字符串，但是流量也许会被正确转发到代理上。例如 foo.com 这个域名在我本地没有意义，但是在代理机上是个有意义的域名，这个情景也不算是少见的。
