### ISSUE TITLE
OpenWRT的源码在哪里

### ISSUE THREAD

**Issue by a13519** [Dreamacro/clash#1128]
OpenWRT的源码在哪里？找遍github没有openwrt的源码，luci-app-clash不公布源码，取而代之的是秘密下载点，这很不安全，很可能被人安装后门，恳请指点openwrt源码地址，杜绝安全隐患。

谢谢

**Comment by wggglggg** [comment]
openwrt 软路由， 你下的哪一个版本？

**Comment by a13519** [comment]
OpenWrt 19.07.3

**Comment by wggglggg** [comment]
> OpenWrt 19.07.3

https://p3terx.com/archives/build-openwrt-with-github-actions.html/comment-page-1#comments

自己在线编一个, 几个小时就拿到

**Comment by a13519** [comment]
谢谢🙏

**Comment by a13519** [comment]
怎么编译clash的OpenWrt package？这个clash的源码可以不加改动编译成openwrt的package吗？

**Comment by wggglggg** [comment]
> 怎么编译clash的OpenWrt package？这个clash的源码可以不加改动编译成openwrt的package吗？

你这个openwrt package是什么?  只是编一个clash?不是编整个openwrt+clash?

**Comment by a13519** [comment]
都可以，我只是想知道这个clash源码是不是可以直接拿来在openwrt的编译环境里编译

**Comment by a13519** [comment]
因为目前我发现以前还有clash的openwrt包，现在必须在luci-app-clash里自动下载

**Comment by a13519** [comment]
也看不出它从哪里下载的，我想自己编译

**Comment by wggglggg** [comment]
> 都可以，我只是想知道这个clash源码是不是可以直接拿来在openwrt的编译环境里编译

有一个编译.config 和 feeds.conf.default 配置,  .config指定要放什么app在openwrt里面,  feeds.conf.default负责收集这些app所需的源码

**Comment by a13519** [comment]
OK， thanks alot

**Comment by wggglggg** [comment]
[config and feeds.zip](https://github.com/Dreamacro/clash/files/6203619/config.and.feeds.zip)
这两个你直接拿去编,  我之前 有钩上 openclash  和  clash

**Comment by wggglggg** [comment]
> OK， thanks alot

[config and feeds.zip](https://github.com/Dreamacro/clash/files/6203627/config.and.feeds.zip)

这两个你直接拿去编, 不用修改 .config.   我之前 已经有钩上 openclash 和 clash

**Comment by a13519** [comment]
万分感谢 :-)

**Comment by wggglggg** [comment]
> 万分感谢 :-)

在线编,其它的方法跟那个网页的方法走, 我试了一次能成.

**Comment by a13519** [comment]
o了
