### ISSUE TITLE
[Feature]类Surge的出网卡默认功能

### ISSUE THREAD

**Issue by iamwwc** [Dreamacro/clash#1132]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Feature
可否增加Surge的这个功能，公司的VPN开启后会创建新的tun，需要手动更改clash的配置才能将流量定向到公司内网。

预期是clash发现这个网卡不存在就fallback到现有逻辑，存在就将流量通过这个网卡送出去

![image](https://user-images.githubusercontent.com/24750337/102187004-60141700-3eee-11eb-97fb-d0e88e6d0b28.png)

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

**Comment by kongminhao** [comment]
好像有吧？

# 出站网卡接口
interface-name: en0

是想要增加一条默认的配置？就是下面那个框选的吗？

**Comment by iamwwc** [comment]
> 好像有吧？
> 
> ```
> # 出站网卡接口
> interface-name: en0
> ```
> 
> 是想要增加一条默认的配置？就是下面那个框选的吗？

是的，默认的配置，如果有就使用这个网卡，如果不存在就忽略掉en0

**Comment by iamwwc** [comment]
@kongminhao 
劳心看下，调用前确认下有没有这个utun，如果没就改为nil 😊
https://github.com/Dreamacro/clash/blob/1e5593f1a9e11714fbeff1d0adecfe68f48a697d/hub/executor/executor.go#L165

**Comment by kongminhao** [comment]
似乎跟 `surge` 一样的实现思路比较好一点，分代理配置 `interface-name` 和 `allow-other-interface`，在 `macos` 下，由于 `Darwin` 内核的限制，如果你开启 `vpn` 后路由表中没有对应条目，是会直接被拒绝的。 I'm working on this.
