### ISSUE TITLE
[Bug] 连接失败

### ISSUE THREAD

**Issue by alynnchen** [Dreamacro/clash#1134]
莫名的连接失败,  配置--> 托管配置 --> 一直更新失败(下载失败),  代理无法使用

2020/12/18 16:26:33:548  [debug] helper version 1.5 require version 1.5
2020/12/18 16:26:33:548  [info] check helper using time: 0.017849087715148926
2020/12/18 16:26:33:551  [info] Trying start proxy
2020/12/18 16:26:33:555  [debug] enableProxy
2020/12/18 16:26:33:557  [info] set up autoUpateTimer
2020/12/18 16:26:33:558  [info] Tigger config auto update check
2020/12/18 16:26:33:558  [info] [Auto Upgrade] Requesting 土星通信
2020/12/18 16:26:33:560  [debug] loggingWebSocket did Connect
2020/12/18 16:26:33:560  [debug] trafficWebSocket did Connect
2020/12/18 16:26:38:255  [info] [Auto Upgrade] Finish 土星通信 result: 下载失败
2020/12/18 16:26:38:255  [info] Saving Remote Config Setting

**Comment by midezhanghao** [comment]
我也一样，自动托管配置不了
