### ISSUE TITLE
[Feature] 通过 API 获取 Clash 中某个代理的出口信息

### ISSUE THREAD

**Issue by Emphasia** [Dreamacro/clash#1135]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 说明 Description
类似于现在通过API获取Clash中某个代理的delay信息的方式获取代理的出口信息（出口IP）
考虑的是代理的服务器IP与出口不一致的情况
或者直接把/proxies/:name/delay测试目标网址的结果也返回来好像也可以..

**Comment by Dreamacro** [comment]
这么做的使用场景是什么

**Comment by Emphasia** [comment]
> 这么做的使用场景是什么

有的代理套了中转 直接查服务器区域得到的是国内的入口 如果能获取对应的国外出口区域 对于分流策略的选择会更准确一点 我是这么想的 😂

**Comment by Dreamacro** [comment]
理论上机场服务都会标明是从哪中转到哪 而不是靠自己手动去查询具体的出口地址,不太清楚为什么会有这种需求

**Comment by Emphasia** [comment]
> 理论上机场服务都会标明是从哪中转到哪 而不是靠自己手动去查询具体的出口地址,不太清楚为什么会有这种需求

源于用的机场不稳定 线路的标记有问题 国内转到香港再转到其他国家统一都标的香港和实际不符
（所以其实最简单的应该是去找机场 但要是能额外有这个功能的话就可以直接获取出口节点的信息 避开节点名中存在的错误或信息不全等情况 配合上延迟就可以有通用的分流策略
好像是个很小众没啥必要的需求..😅

**Comment by Dreamacro** [comment]
你可以切换代理后直接 curl -x ip:port ip.sb 拿到出口 ip。

**Comment by Emphasia** [comment]
> 你可以切换代理后直接 curl -x ip:port ip.sb 拿到出口 ip。

好的 谢谢
