### ISSUE TITLE
[Feature]确认一下，openclash tun模式下开启udp会让原本nat类型改变

### ISSUE THREAD

**Issue by bleeee** [Dreamacro/clash#1136]
路由器不开启clash时nat类型为symmetric，xbox网络里面，检测类型是严格，丢包是0%，有延迟

服务器支持udp，打开clash的udp转发，外网的stun显示fullcone，这时候stun.qq.com和stun.miwifi.com等国内stun也显示fullcone.

但是xbox网络里面，检测类型是开放，丢包却是100%，延迟-1

**Comment by isweibin** [comment]
请在 OpenClash 项目下提 [Issue](https://github.com/vernesong/OpenClash/issues)。

**Comment by ackurdeeve** [comment]
> 请在 OpenClash 项目下提 [Issue](https://github.com/vernesong/OpenClash/issues)。win10也有这个问题，没开tun是fullcone,开了以后变portrestrict

**Comment by shikkoku** [comment]
> 
> win10好像也有这个问题，没开tun是fullcone,开了以后变portrestrict。

Clash for Windows也是这样。用wintun模式会变成portrestrict。
