### ISSUE TITLE
[Feature]请支持trojan+xtls

### ISSUE THREAD

**Issue by DLGum** [Dreamacro/clash#1138]
### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
win10，安卓，ios

* 其他
电脑clash_for_windows_pkg，安卓magisk模块cpfm，ios小水滴
（小水滴使用clash订阅也不知是不是使用了clash核心）

### 说明 Description

请添加trojan+xtls支持。
在xray昨天的1.1.4更新里Trojan XTLS已就绪。
https://github.com/XTLS/Xray-core/releases
vless跟trojan是非常类似的东西，但vless有强大的xtls加持。可惜迟迟没有分享标准。
clash一直没添加vless的支持，在tg讨论里xray作者好像也没有短期内搞分享标准的意思。
不过现在trojan也能用上xtls了。

**Comment by akw5454521** [comment]
啊这，我都把trojan换成trojan-go了😂

**Comment by eggydutch** [comment]
https://github.com/Dreamacro/clash/pull/946
看讨论D大暂时未有支持意向

**Comment by DLGum** [comment]
> #946
> 看讨论D大暂时未有支持意向

蓝瘦。

**Comment by matianhe3** [comment]
有动向记得分享.
