### ISSUE TITLE
大年初一发个帖：节点连通测试和节点连通对比

### ISSUE THREAD

**Issue by FormosaZh** [Dreamacro/clash#114]
关于节点连通测试的问题，已经解决一部分了，但是今天的我又有了更多的HTTPS节点，所以仍有更多的连通测试是超时的，随着节点越来越多，节点延迟对比也成了问题，我想在一个界面下看到几十个节点的对比结果和连续测试对比结果，可以实现吗？

![default](https://user-images.githubusercontent.com/27438860/52269832-1cf3cf00-297a-11e9-8581-0de073bef2ce.png)

**Comment by Dreamacro** [comment]
Windows 界面相关的问题请移步 https://github.com/Fndroid/clash_for_windows_pkg

**Comment by Fndroid** [comment]
> Windows 界面相关的问题请移步 https://github.com/Fndroid/clash_for_windows_pkg

他这个http类型测速失败应该不是GUI的问题

**Comment by Dreamacro** [comment]
HTTPS 代理只支持 CONNECT 模式，不知道你的节点是哪种实现方式

**Comment by FormosaZh** [comment]
应该就是CONNECT模式吧，节点较多，我怎样能在windows下查看到用这种方式建立的连接？
