### ISSUE TITLE
[Feature]上网环境经常变化，请问dns配置段中的nameserver的参数能否取系统当前的默认配置

### ISSUE THREAD

**Issue by jetvster** [Dreamacro/clash#1141]
因为我的工作环境老发生变化，移动、联通、电信都会有，也是经常出差，如果只用固定的nameserver经常会碰到不能解析或者解析的地址访问非常缓慢的情况，所以经常需要调整配置，我相信可能不止我一个人有这种情况。
所以如果dns中能增加参数支持自动获取系统的nameserver并设置，可能就解决了这个麻烦，不知能否在后续版本中实现，谢谢各位大大～

**Comment by grayguest** [comment]
clash api是可以改写config.yaml的，目前只发现secret无法改写。

**Comment by shunf4** [comment]
可以试下我的 fork：https://github.com/shunf4/clash/tree/feat/localresolve

实现细节和配置方法可以看 commit 说明：https://github.com/shunf4/clash/commit/344eaba3839299f977515377554deda29b1d2e42
