### ISSUE TITLE
[Feature]如果新增应用流量，怎么做？

### ISSUE THREAD

**Issue by matthuo333** [Dreamacro/clash#1144]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [y] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

如果新增诸如disney plus 的流量，如何做呢？顺便问下，是基于应用特征识别？还是域名和ip?
### 更多信息 More Information

**Comment by cielpy** [comment]
这并不是一个 Feature Request，发在 Discussions 讨论比较合适

很多规则集都要针对各种流媒体的规则，比如 https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/StreamingMedia/Video/DisneyPlus.yaml

**Comment by matthuo333** [comment]
嗯。如何定时下载并更新到配置文件呢？ 目前是通过手动自定义加入的流媒体规则

**Comment by cielpy** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
