### ISSUE TITLE
[Feature]优化Release二进制文件名

### ISSUE THREAD

**Issue by wenhaoy** [Dreamacro/clash#1145]
为方便制作自动化脚本，关于Release ( https://github.com/Dreamacro/clash/releases )资源的文件名，希望以下两点优化：

1. 取消资源名称中的版本号，方便使用 /owner/name/releases/latest/download/asset-name.zip 获取最新资源(https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/linking-to-releases)

2. Linux资源中CPU指令集描述部分，建议与`uname -m`命令返回结果一致，增加aarch64类型。( https://stackoverflow.com/questions/45125516/possible-values-for-uname-m )

**Comment by Dreamacro** [comment]
1. 查看了几个其他仓库，发现带版本号的和不带版本号的差不多是 1:1
不带版本的
https://github.com/denoland/deno/releases
https://github.com/starship/starship/releases
https://github.com/vi/websocat/releases

带版本的
https://github.com/sharkdp/bat/releases
https://github.com/helm/helm/releases
https://github.com/ogham/dog/releases

不知道目前有没有依赖这个版本号的，如果没有的话，确实可以改
2. 这里的命名依照的是 https://golang.org/doc/install/source#environment go 本身的 GOOS 和 GOARCH，在我看来还是依照 go 的命名规则去进行平台的划分比较合适，避免因为 go 本身的改变让映射关系变得混乱
