### ISSUE TITLE
[Bug] snell 代理的 mode 参数是必须的吗

### ISSUE THREAD

**Issue by dante2046** [Dreamacro/clash#1147]
https://lancellc.gitbook.io/clash/clash-config-file/proxies/config-a-snell-proxy
这里显示 obfs-opts:{mode: http} 是一个可选的项目，但是不填写此项会提示 mode missing

**Comment by Dreamacro** [comment]
是必须的

**Comment by dante2046** [comment]
> 是必须的

好的，那我想知道当snell-server 配置 obfs = none的时候，clash配置中，mode的值应该是？

**Comment by Dreamacro** [comment]
@dante2046 我没有在 snell 的项目里看到可以设置 obfs = none 的文档，有相关链接吗

**Comment by dante2046** [comment]
> @dante2046 我没有在 snell 的项目里看到可以设置 obfs = none 的文档，有相关链接吗

抱歉，是obfs = off
在 surge mac 内置的snell server 中看见的配置

https://manual.nssurge.com/others/snell-server.html

surge mac 内置的 这个暂时还不支持v2参数，可能是我菜 在surge mac配置中写 obfs = http 并不能在客户端上正常连接，也刚刚在cfw 中尝试 mode : off 报错

**Comment by Dreamacro** [comment]
好的，dev 现在支持了不写 obfs-opts，即不使用 obfs

**Comment by akw5454521** [comment]
啊，原来可以不混淆的吗，我一直以为混淆是必需的
