### ISSUE TITLE
[Feature] proxy-groups Fallback 类型能否添加指定超时时间？

### ISSUE THREAD

**Issue by fishg** [Dreamacro/clash#1148]
不同的服务器节点在不同时段的延迟差别很多大，希望能够指定Fallback 类型的探测超时时间来过滤掉超过一定延迟的节点。

**Comment by akw5454521** [comment]
看起来有些用，不过都超了咋办

**Comment by fishg** [comment]
> 看起来有些用，不过都超了咋办

都超了这组就是不可用状态，跟所有节点失联一样。这种情况是靠更上层的代理组规则来处理，或者用户自己放入足够的备选节点规避了。
