### ISSUE TITLE
通过docker op 配置clash后，导致不能出海，向大神求助，急！

### ISSUE THREAD

**Issue by matthuo333** [Dreamacro/clash#1149]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
* OP ，Docker
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

之前通过在软路由配置后，是没问题的。
然后，通过在docker 中的op进行配置clash, 日志均正常,UI显示成功。但是就不能出海。
经对比以上两个环境下的iptables，发现 openclash_output 链中的规则和正确环境下的不一样。即如下，仅有2条，

0 | 0.00 B | RETURN | all | * | * | 0.0.0.0/0 | 0.0.0.0/0 | match-set localnetwork dst
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | 0.00 B | REDIRECT | tcp | * | * | 0.0.0.0/0 | 198.18.0.0/16 | redir ports 7892

另外，在Mangle 表中，也新增了 openclash链，这个也是和正确环境不同。
是这里导致不能出海，对么？ 这里和kernel配置有关么？

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by matthuo333** [comment]
通过ipt反向查kernel配置文件，发现下面几个未打开，clash是不是底层依赖这个几个模块？
# CONFIG_IP_ROUTE_MULTIPATH is not set
# CONFIG_IP_MROUTE_MULTIPLE_TABLES is not set
# CONFIG_NETFILTER_XT_MATCH_POLICY is not set
# CONFIG_NFT_MASQ_IPV4 is not set
# CONFIG_NFT_REDIR_IPV4 is not set

**Comment by Dreamacro** [comment]
参考这个吧 https://github.com/Kr328/clash-premium-installer
