### ISSUE TITLE
Lose connection every 5 minutes

### ISSUE THREAD

**Issue by littlef0x** [Dreamacro/clash#115]
I use CFW as GUI client. For CFW0.5.22(with Clash 0.11.1), connection breaks every 5-10 minutes, while CFW0.5.21(with Clash 0.10.2) works well. According to CFW's release page, the only change between 0.5.21 and 0.5.22 is upgrading Clash core. So I guess it is a Clash bug. Here's the log, which seems to be a Golang variable scope problem:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x76f724]

goroutine 3619 [running]:
github.com/Dreamacro/clash/rules.(*IPCIDR).IsMatch(0xc0001f7800, 0xc000342050, 0xc0001f7800)
	/home/travis/gopath/src/github.com/Dreamacro/clash/rules/ipcidr.go:27 +0x44
github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc00009a4b0, 0xc000342050, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:179 +0x135
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc00009a4b0, 0x8dbae0, 0xc0001b2080)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:135 +0x523
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:93 +0x9a

**Comment by Dreamacro** [comment]
The bug is fixed in dev branch. But not release yet ...
