### ISSUE TITLE
通过大神推荐的clash-premium-installer，docker环境下的op权限受限，还有其它方法安装么

### ISSUE THREAD

**Issue by matthuo333** [Dreamacro/clash#1150]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description
经大神推荐，让在clash-premium-installer 这个项目，进行安装，可是由于docker环境权限受限，不知还有其它安装方法么？
目前报错：

~/clash-premium-installer# ./installer.sh install
-ash: ./installer.sh: Permission denied

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by matthuo333** [comment]
给对象增加权限后，又提示，install 找不到。。。

**Comment by Dreamacro** [comment]
为什么不能在原讨论下继续回答呢

**Comment by matthuo333** [comment]
之前的thread中没法输入。。。
