### ISSUE TITLE
TUN模式下，通过API上传配置，导致CPU占用

### ISSUE THREAD

**Issue by xqXQzzz1** [Dreamacro/clash#1151]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>
mixed-port: 7890

allow-lan: false

mode: Rule

log-level: info

external-controller: 127.0.0.1:9090

external-ui: yacd

dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  nameserver:
    - 223.5.5.5
    - 180.76.76.76
    - 119.29.29.29
    - 117.50.10.10
    - 114.114.114.114
    - https://dns.alidns.com/dns-query
    - https://doh.360.cn/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.8.8
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
proxies:
 
proxy-groups:

rules:

tun:
  enable: true
  stack: gvisor # only gvisor
  dns-hijack:
    - 198.18.0.2:53 
  macOS-auto-route: true
  macOS-auto-detect-interface: true 
</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
* window10 20H2
* 网路环境或拓扑 (network conditions/topology)
……
![image](https://user-images.githubusercontent.com/35725489/103144781-2521a700-476a-11eb-9f62-b25cd1ea2d1c.png)

* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1.  参数macOS-auto-detect-interface设为true，通过API，将配置重载时，会从clash的网络设备一直访问dns中设置的的地址，如图所示
![image](https://user-images.githubusercontent.com/35725489/103144707-0bcc2b00-4769-11eb-933a-c4ca23945e95.png)
导致CPU占用将近100%。
put操作通过curl实现：curl -s -X PUT -d !data! --write-out %%{http_code} http://127.0.0.1:9090/configs
!data!为对应的json，返回代码204.
2. 启动时，相同配置则不会有上述情况。
3. 如果将参数macOS-auto-detect-interface设为false，再设置合适的interface-name，利用api时上传时不会出现如1的情况。

**我预期会发生……？**

**实际上发生了什么？**

### 可能的解决方案 Possible Solution

希望可以优化一下macOS-auto-detect-interface的问题。

**Comment by Dreamacro** [comment]
前几天已经修复，这里临时发一个编译后的文件你先试试，没问题的话明天会发一个修复版本

[clash-windows-amd64.exe.zip](https://github.com/Dreamacro/clash/files/5742687/clash-windows-amd64.exe.zip)

**Comment by xqXQzzz1** [comment]
> 前几天已经修复，这里临时发一个编译后的文件你先试试，没问题的话明天会发一个修复版本
> 
> [clash-windows-amd64.exe.zip](https://github.com/Dreamacro/clash/files/5742687/clash-windows-amd64.exe.zip)

没有问题了。
