### ISSUE TITLE
[Bug]docker容器运行op, 启动均正常。但DNS和出海均有问题.请大神指点，在线等

### ISSUE THREAD

**Issue by matthuo333** [Dreamacro/clash#1152]
--------------------------调试的LOG信息----------------------------------------

#===================== 系统信息 =====================#
主机型号: Amlogic
固件版本: OpenWrt SNAPSHOT r2907-71e335c0b
LuCI版本: git-20.256.12360-1a54222-1
内核版本: 3.14.29
处理器架构: aarch64_generic

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.12.18.gaf66a7a
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.3.0-4-g4b1b494
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/clash-stand1.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
interface-name: eth0
external-ui: "/usr/share/openclash/dashboard"
dns:
  use-hosts: true
  listen: 127.0.0.1:7874
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
  - 'proxy.golang.org'
##Custom fake-ip-filter END##
  nameserver:
    - 114.114.114.114
    - 119.29.29.29
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
    - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
7    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.199.1   0.0.0.0         UG    0      0        0 br-lan
10.147.20.0     0.0.0.0         255.255.255.0   U     0      0        0 ztwfuhbsgp
192.168.199.0   0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.199.1 dev br-lan proto static src 192.168.199.192 
10.147.20.0/24 dev ztwfuhbsgp proto kernel scope link src 10.147.20.94 
192.168.199.0/24 dev br-lan proto kernel scope link src 192.168.199.192 
#ip rule show
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      15179/clash
tcp        0      0 :::7890                 :::*                    LISTEN      15179/clash
tcp        0      0 :::7891                 :::*                    LISTEN      15179/clash
tcp        0      0 :::7892                 :::*                    LISTEN      15179/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           15179/clash
udp        0      0 :::7891                 :::*                                15179/clash
udp        0      0 :::7892                 :::*                                15179/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.2
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface lan
nameserver 192.168.199.1
search lan

#===================== 测试本机网络连接 =====================#

#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#
Multiple Start Scripts Running, Exit...
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Others"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Hulu"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Netflix"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Spotify"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Disneyplus"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Microsoft"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Youtube"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Netease Music"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider HBOGo"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Telegram"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider PayPal"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider PrimeVideo"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Scholar"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Steam"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Proxies"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial compatible provider Apple"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial rule provider Netflix"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial rule provider Youtube"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial rule provider Hulu"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial rule provider PrimeVideo"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial rule provider HBOGo"
time="2020-12-25T23:42:45+08:00" level=info msg="Start initial rule provider Disneyplus"
time="2020-12-25T23:42:45+08:00" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-12-25 23:42:30 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
如上，补充：Docker Container环境
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
见上调试信息
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
更多见上调试信息

### 说明 Description

我想实现旁路由出海，且“指哪打哪”基于应用的分流策略。因为资源要求，需要通过docker 环境下进行。

### 重现问题的具体布骤 Steps to Reproduce

正常部署配置clash流程

**我预期会发生……？**

旁路由出海
**实际上发生了什么？**

DNS解析有问题，无法出海
### 可能的解决方案 Possible Solution

是模块安装不全？但是相应模块在op默认的tencent源中下载安装不到对应的软件包，更换推荐清华的源，仍不行。

**Comment by Dreamacro** [comment]
在这里补充 https://github.com/Dreamacro/clash/discussions/1149 不要再开 issue 了谢谢
