### ISSUE TITLE
混淆模式为websocket的yaml如何写法

### ISSUE THREAD

**Issue by yzqiang666** [Dreamacro/clash#1153]
obfs=websocket&obfsParam=ss.xxxxx.workers.dev&path=/
以上的yaml用
plugin: v2ray-plugin
    plugin-opts:
      mode: websocket
      host: ss.xxxxx.workers.dev
      path: "/" 
      tls: false
      mux: false

在shadowrocket 小火箭中可以通过，但android中的clash不能通过。
改为plugin: obfs后mode条目又不支持websocket,
请问正确写法。

**Comment by Fffdmin** [comment]
# Shadowsocks(Websocket + TLS)
 ``` - name: "1"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket # no QUIC now
      tls: true # wss
      # skip-cert-verify: true
      # host: bing.com
      path: "/s"
      # mux: true
      # headers:
      #   custom: value```
