### ISSUE TITLE
[Feature]Add metrics/tracing , etc..

### ISSUE THREAD

**Issue by xiekeyi98** [Dreamacro/clash#1155]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

### 说明 Description

当前，我感觉 clash 缺少一些 metrcis 和 tracing。 看到 issue 列表中有一些使用久了就不行，或者一些类似的「幽灵问题」，是否考虑增加一些诸如统计当前连接数/gc时间/goroutines数的计划？
### 可能的解决方案 Possible Solution

- https://tip.golang.org/pkg/runtime/metrics/ (go1.16 草案）
- 关于统计当前 tcp 连接数，没有找到很多 golang 原生一点的办法，一般还是依赖于 unix。

**Comment by Dreamacro** [comment]
要看 goroutine 之类的完全可以直接用 pprof 解决。

目前在做的 tracing 可能不是你想的那种，是这样的

![image](https://user-images.githubusercontent.com/8615343/103227766-1f92af80-496a-11eb-89b9-4148f668a08f.png)

**Comment by xiekeyi98** [comment]
> 要看 goroutine 之类的完全可以直接用 pprof 解决。
> 
> 目前在做的 tracing 可能不是你想的那种，是这样的
> 
> ![image](https://user-images.githubusercontent.com/8615343/103227766-1f92af80-496a-11eb-89b9-4148f668a08f.png)

我是感觉都有 grafana 了，也可以把 pprof 的一些信息放过来。
