### ISSUE TITLE
vless tcp xtls-rprx-direct

### ISSUE THREAD

**Issue by rvpn** [Dreamacro/clash#1162]
Hi everybody, 

Is clash already support this type of tunneling? 

vless tcp xtls-rprx-direct.

If yes, can I see your .YAML examples?

**Comment by eggydutch** [comment]
> Hi everybody,
> 
> Is clash already support this type of tunneling?
> 
> vless tcp xtls-rprx-direct.
> 
> If yes, can I see your .YAML examples?
At this moment, NO.
啊

**Comment by cjwddtc** [comment]
> Hi everybody,
> 
> Is clash already support this type of tunneling?
> 
> vless tcp xtls-rprx-direct.
> 
> If yes, can I see your .YAML examples?

vless不是一个正式发布的协议，开发者也没有承诺过某个会被向后兼容的版本，所以不可能实现该功能，这个issue和 #1185 重复了，关了吧
