### ISSUE TITLE
请问用rule-providers时behavior如何选择？ classical/ipcidr/domain 三者又有什么区别？

### ISSUE THREAD

**Issue by vitaminx** [Dreamacro/clash#1165]
请问用rule-providers时behavior如何选择？ classical/ipcidr/domain 三者又有什么区别？
如果在payload:下面有PROCESS-NAME规则，又该选择哪一种模式？
谢谢！

**Comment by Dreamacro** [comment]
classical 是朴素的规则，支持其他所有的 rule，但由于整个 rule 是一起的，所以当包含需要解析 dns 的规则时，整个 rule 被视为需要 dns 解析，所以要对 classical 做适当拆分（当然如果不在乎 dns 解析忽略即可）

ipcidr 和 domain 是对大量的 ipcidr 和域名规则做优化，能在有大量规则的同时还保持着很快的匹配速度，当然这是以牺牲内存为代价换来的匹配速度（以目前的实现来说，几十万的规则大概占用几十兆内存）。台式机不在乎那点内存，但一些性能受限的设备可能很在乎。

根据自己的需要决定需要什么样的代理规则，对于我来说一条 GEOIP 就够了。

**Comment by vitaminx** [comment]
> 
> 
> classical 是朴素的规则，支持其他所有的 rule，但由于整个 rule 是一起的，所以当包含需要解析 dns 的规则时，整个 rule 被视为需要 dns 解析，所以要对 classical 做适当拆分（当然如果不在乎 dns 解析忽略即可）
> 
> ipcidr 和 domain 是对大量的 ipcidr 和域名规则做优化，能在有大量规则的同时还保持着很快的匹配速度，当然这是以牺牲内存为代价换来的匹配速度（以目前的实现来说，几十万的规则大概占用几十兆内存）。台式机不在乎那点内存，但一些性能受限的设备可能很在乎。
> 
> 根据自己的需要决定需要什么样的代理规则，对于我来说一条 GEOIP 就够了。

感谢解答！
基本明白了区别
在payload:后面的语法上三者是否有区别？

**Comment by Dreamacro** [comment]
domain 的写法和 hosts 一致

**Comment by vitaminx** [comment]
> 
> 
> domain 的写法和 hosts 一致

谢谢！
我去学习一下😂

**Comment by grayguest** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
这个非官方文档写了示例，可以看看。

**Comment by huhu415** [comment]
我感觉这个rules-provider是不是太臃肿了，如果我想一个域名走一个规则，比如x.com走香港，youtube.com走日本，用这个rules-provider就要提供一个两个http或两个文件，然后还要给x.com这个一个名字，再这个名字,香港。另一个也是，感觉好臃肿。
