### ISSUE TITLE
测试disable-udp出现个规则匹配的BUG

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#1167]
![image](https://user-images.githubusercontent.com/67776691/103520497-35482d80-4eb2-11eb-8cea-593abb4f1a06.png)
 rule中带googlevideo的规则分别是：
![image](https://user-images.githubusercontent.com/67776691/103520600-5ad53700-4eb2-11eb-9981-82f8efb7b252.png)
![image](https://user-images.githubusercontent.com/67776691/103520640-6b85ad00-4eb2-11eb-9048-c17e38c3f290.png)
而国外网站中并没有googlevideo的匹配。只有google
![image](https://user-images.githubusercontent.com/67776691/103520706-89eba880-4eb2-11eb-897d-dead5832fe91.png)
可是YOUTUBE策略组开启了disable-udp后。同样的域名，如第一图，会匹配一条YOUTUBE redir（tcp）跟一条国外网站 redir(udp)？？？？
![image](https://user-images.githubusercontent.com/67776691/103521037-1302df80-4eb3-11eb-9910-2bf86783dbed.png)
![image](https://user-images.githubusercontent.com/67776691/103521051-17c79380-4eb3-11eb-9bcb-24b85bcdc84b.png)
---step2--------
然后我把国外网站的disable-udp打开
![image](https://user-images.githubusercontent.com/67776691/103521603-003cda80-4eb4-11eb-80b2-6f9ca8c10b79.png)
然后YOUTUBE的udp自然钻到了漏网之鱼的规则上
![image](https://user-images.githubusercontent.com/67776691/103521703-282c3e00-4eb4-11eb-9c51-f5822e8847a3.png)
所以防不住YOUTUBE一定要建立udp连接

**Comment by zm24120** [comment]
感觉是软件逻辑问题吧~

当 YOUTUBE  策略组 开启disableudp后，
clash略过了
DOMAIN-SUFFIX,googlevideo.com,YouTuBe

然后下载查询规则（如果实现disable-udp参数的预想，是否应该是UDP匹配到disable规则，给direct或者reject？）

然后匹配到了，
DOMAIN-KEYWORD,google.com,国外网站
-----------------------------------------------

如果继续开启， 国外网站 策略组 的disableudp
googlevideo.com的 流量  就会略过  上面两条，最后到了漏网之鱼（MATCH）

**Comment by Dreamacro** [comment]
这个逻辑没有问题，`disable-udp` 是针对这个 group 的，并不是针对 group 下的代理的。

第一个图里，Youtube 被 disable 了，但是匹配到了「国外网站」，但是国外网站这个 group 没有 disable 所以走了 udp。后面依次类推。

关于组合逻辑类的 rule (host === 'youtube.com' && type === 'udp')，推荐用 script

**Comment by flyhigherpi** [comment]
> 这个逻辑没有问题，`disable-udp` 是针对这个 group 的，并不是针对 group 下的代理的。
> 
> 第一个图里，Youtube 被 disable 了，但是匹配到了「国外网站」，但是国外网站这个 group 没有 disable 所以走了 udp。后面依次类推。
> 
> 关于组合逻辑类的 rule (host === 'youtube.com' && type === 'udp')，推荐用 script

以为是在当前策略组阻止用udp连接了。

**Comment by qzi** [comment]
这个 disable-udp 默认值是啥
