### ISSUE TITLE
请教关于clash TUN如何设置iptables.

### ISSUE THREAD

**Issue by nkta3m** [Dreamacro/clash#1171]
我想在路由器上使用clash TUN，不知道是否需要设置iptables？如果需要的话，该如何写iptables？谢谢。

**Comment by emacsnt** [comment]
除了dns，TUN基本上不需要iptables，只需要route，让国外的流量走TUN interface即可。劫持dns是唯一需要iptables来处理的，参考
https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/setup-system-stack-in-real-ip-mode
https://comzyh.gitbook.io/clash/

**Comment by nkta3m** [comment]
感謝 @emacsnt ,可是看了半天也沒看懂該怎麼做,好像这两个方法完全不同，试用第一个后，路由器直接进不去，重新刷机了，哪位有时间详细给讲讲，感谢！

**Comment by nkta3m** [comment]
我试了第二个介绍，route把fakeip转去tun，然而依然不成功

**Comment by luwah** [comment]
建议参考[clash-premium-installer](https://github.com/Kr328/clash-premium-installer)

**Comment by nkta3m** [comment]
感谢 @luwah 这个我也参考看过，不过水平有限，还没弄好

**Comment by emacsnt** [comment]
目前太笼统了,如果要分析问题,还是要给出你的路由器的信息
route表
ifconfig信息
clash安装的版本
iptables信息

**Comment by nkta3m** [comment]
我的路由器是OpenWrt 19.07.5，clash是2020.12.27的版本，然后使用Fake_ip模式，config的配置如下：
![屏幕快照 2021-01-10 19 09 35](https://user-images.githubusercontent.com/13484700/104121192-683d6600-5377-11eb-8040-c627857c74e0.png)

因为dns的53端口与dnsmasq冲突，所以转发了53端口
![屏幕快照 2021-01-10 19 08 35](https://user-images.githubusercontent.com/13484700/104121198-712e3780-5377-11eb-945b-cf8186588dc9.png)
其他的就是默认没动过

**Comment by nkta3m** [comment]
启动clash后如下：
![屏幕快照 2021-01-10 19 19 52](https://user-images.githubusercontent.com/13484700/104121401-e5b5a600-5378-11eb-91e2-a77f6fc3ae52.png)

**Comment by nkta3m** [comment]
route表的信息如下：
![屏幕快照 2021-01-10 19 21 30](https://user-images.githubusercontent.com/13484700/104121478-899f5180-5379-11eb-9273-ea17f3c25dd1.png)

**Comment by emacsnt** [comment]
1, nslookup 返回地址是不是198.18.x.x？ 如果不是dns劫持的iptable有问题
2，dns设置部分没有设置fallback dns，所以dns被污染的，参考https://lancellc.gitbook.io/clash/clash-config-file/dns 正确设置dns

**Comment by nkta3m** [comment]
nslookup如果在电脑上面查询，返回结果是198.18.x.x，如果在路由器上执行，不返回198.18.x.x
![屏幕快照 2021-01-10 20 49 10](https://user-images.githubusercontent.com/13484700/104123352-bb1e1a00-5385-11eb-91a1-702a81683a81.png)
![屏幕快照 2021-01-10 20 49 18](https://user-images.githubusercontent.com/13484700/104123353-be190a80-5385-11eb-8226-8a94cd6db0df.png)

然后fallback dns现在设置了，电脑上访问google或是twitter没问题，可是很奇怪的是手机上不去google、twitter、ins等都不行

**Comment by nkta3m** [comment]
![屏幕快照 2021-01-10 20 54 40](https://user-images.githubusercontent.com/13484700/104123424-1b14c080-5386-11eb-97de-43a024bb55a4.png)

**Comment by nkta3m** [comment]
我现在把fallback换下面的，手机还是无法访问
![屏幕快照 2021-01-10 20 58 01](https://user-images.githubusercontent.com/13484700/104123524-a8581500-5386-11eb-934f-37d3ab5c4795.png)

**Comment by emacsnt** [comment]
网络拓扑结构都没说清楚，看这个iptables -J DNAT, clash没有安装在openwrt路由器上？
如果clash安装在路由器上，不应该-j DNAT,  应该用 -j REDIRECT --to-port 5353
不过不要用iptables了，还不够熟悉iptables，建议去掉所有的iptables，然后在Openwrt的dhcp和dns里面设置DNS forwardings
到127.0.0.1#5353保存应用即可。

**Comment by emacsnt** [comment]
fallback dns只能放国外dns服务器，不能放国内的，都有污染的风险。
所以dns.rubyfish.cn最好都删掉。

**Comment by nkta3m** [comment]
clash 是安装在openwrt路由器上的，iptables改成 -j REDIRECT --to-port 5353了，我再试试看

**Comment by nkta3m** [comment]
感谢指点，问题没有解决，我把情况总结一下：
1. clash安装在OpenWrt上面
2. 不管iptables 使用-j DNAT --to-destination 127.0.0.1:5353 或是 -j REDIRECT --to-port 5353都是ok的
3. clash使用普通版本不带TUN，手机或电脑都可以正常访问google/twitter。
4. clash使用TUN版本（2020.12.27版），电脑可以正常访问，手机无法访问google/twitter等

**Comment by nkta3m** [comment]
我猜测问题出在我的server端，不支持udp，然后手机估计走了udp了，所以电脑通，手机不通

**Comment by emacsnt** [comment]
> 我猜测问题出在我的server端，不支持udp，然后手机估计走了udp了，所以电脑通，手机不通

猜测错误，
1，不启用udp转发，大部分应用不受影响；
2，iptables很多小错误，建议仔细学习一下；
3，前面的链接是clash官方推荐的用户手册，值得认真看完

**Comment by flyhigherpi** [comment]
> 感谢指点，问题没有解决，我把情况总结一下：
> 
> 1. clash安装在OpenWrt上面
> 2. 不管iptables 使用-j DNAT --to-destination 127.0.0.1:5353 或是 -j REDIRECT --to-port 5353都是ok的
> 3. clash使用普通版本不带TUN，手机或电脑都可以正常访问google/twitter。
> 4. clash使用TUN版本（2020.12.27版），电脑可以正常访问，手机无法访问google/twitter等

openwrt直接看openclash的tun方案撒。
我等一个华硕路由的tun方案。

**Comment by nkta3m** [comment]
感谢各位的耐心帮助，本人实在搞不定，还是继续使用非TUN的了。
