### ISSUE TITLE
question - how to pick vpn site without using browser and http://clash.razord.top/

### ISSUE THREAD

**Issue by lab4quant** [Dreamacro/clash#1173]
Hello, I'm using clash on linux, i followed steps i found on internet, it works, but it would need to open http://clash.razord.top/ using browser to pick vpn site

Is there anyway to pick vpn site using command line only?

thanks a lot!

**Comment by Dreamacro** [comment]
For now, you can call clash's RESTful API directly. Or you can contribute to https://github.com/Dreamacro/clash-ctl

**Comment by lab4quant** [comment]
@Dreamacro, thanks for the update, i don't know about golang dev ...
so can i call restful api with linux bash? any example?

**Comment by Dreamacro** [comment]
https://clash.gitbook.io/doc/restful-api/proxies

**Comment by lab4quant** [comment]
@Dreamacro , sorry, i googled a bit, but still confused ...

is it something like this?

```
curl -X POST -d "name=myvpnsite" http://127.0.0.1/
```

i don't understand path/body parameter, what's the difference?

thank you!

**Comment by Dreamacro** [comment]
always `application/json`

**Comment by lab4quant** [comment]
@Dreamacro, like this?

i only supplied `name` parameter, not sure what the doc says about path/body parameter ...

```
curl -X POST -H "Content-Type: application/json" \ 
       -d '{"name": "myvpnsite"}' \ 
       http://127.0.0.1/
```

**Comment by Dreamacro** [comment]
In gitbook, it is divided into path params, queries, and body. It's clear

**Comment by lab4quant** [comment]
@Dreamacro , thank you,
i believe i can take it from here (after several trys)
