### ISSUE TITLE
[Feature] 希望可以添加策略组启用和禁用功能

### ISSUE THREAD

**Issue by Edger** [Dreamacro/clash#1176]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

如题，希望可以添加策略组启用和禁用功能，这样一些不常用的策略组平时可以禁用掉。例如苹果的相关服务，有时候要用策略指定节点访问，平时则一般不需要指定，这时候就可以把苹果的策略组禁用掉。

**Comment by luwah** [comment]
现有方案是用#注释相关策略组，其实平时不需要指定的话，DIRECT就可以满足你的要求，在特定情况下再select相应节点即可。

**Comment by akw5454521** [comment]
没想象出来应用场景

**Comment by luwah** [comment]
一个策略组无非是proxy，DIRECT，REJECT这几种可能，所以“禁用策略组”的时候约等于DIRECT；当然，如果不想看到该策略组，那么在config中使用#注释对应策略组即可达到目的，需要启用时取消#注释即可。
