### ISSUE TITLE
[Feature] 规则增加按照协议类型分流的功能

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#1178]
建议规则增加按照协议类型分流的功能，或者说规则可以按照tcp和udp分开处理，我看貌似script脚本是可以拿到协议类型的，但是似乎朴素的rule好像无法按照这个分流（至少那个配置文件的demo里面没有），这个功能对于游戏加速还是非常实用的。

**Comment by SplitGemini** [comment]
+1，+ bittorrent
