### ISSUE TITLE
[Feature]可否提供iOS版本的framework或者library

### ISSUE THREAD

**Issue by LinkZen1991** [Dreamacro/clash#1181]
### 说明 Description

可否在Release Assets提供iOS版本的framework或者library呢，这样可以让更多iOS版本的Clash更容易生产出来。或者提供Build脚本也可以。

### 可能的解决方案 Possible Solution

Static Library or Framework or Build Script

**Comment by Kr328** [comment]
go 编译出来的 动态链接库 与 本地层互操作 需要用到 cgo

cgo 和 C/OC/Swift 互操作 不是简单的 函数调用 就能完成 还需要开发者处理 大量类型转换 以及 大量的内存管理 (Go 是 GC / C 衍生是手动分配释放

对于 clash 这些互操作并不是必要的 并且 与平台相关 构建时也需要目标平台的 C 语言编译套件 

加入这些功能会大大增加 clash 维护难度 也会大大提升构建平台的要求

这些操作不应该由 clash 自身实现 而是应该由 某个平台的具体开发者实现

**Comment by Ariesly** [comment]
有没有可能和这个一样
https://github.com/Jigsaw-Code/outline-go-tun2socks
利用gomobile做成一套各个平台能用的库
https://github.com/Jigsaw-Code/outline-client/tree/master/cordova-plugin-outline
然后封包成跨平台可用的plugin.

**Comment by Kr328** [comment]
首先 gomobile 并没有回避掉 cgo 的问题 对平台编译器依赖大

你可以看看现在的 action 只需要在一个机器 ubuntu 上 安装一个 golang 构建就能完成

而引入 gomobile 或者说 cgo 后 就需要 Android SDK/NDK 和 xcode 对构建环境要求增大

而且 clash 本身设计并不希望依赖任何特定平台

其次 gomobile 需要以一个特定的 go package 生成对应的 Stub， clash 本身设计时 API 分散在各个不同的 package，额外设计一个 API package 只会增加维护成本，对 core 本身并没有任何用处

**Comment by LinkZen1991** [comment]
> 首先 gomobile 并没有回避掉 cgo 的问题 对平台编译器依赖大
> 
> 你可以看看现在的 action 只需要在一个机器 ubuntu 上 安装一个 golang 构建就能完成
> 
> 而引入 gomobile 或者说 cgo 后 就需要 Android SDK/NDK 和 xcode 对构建环境要求增大
> 
> 而且 clash 本身设计并不希望依赖任何特定平台
> 
> 其次 gomobile 需要以一个特定的 go package 生成对应的 Stub， clash 本身设计时 API 分散在各个不同的 package，额外设计一个 API package 只会增加维护成本，对 core 本身并没有任何用处

感谢回复，本人没有GO和网络编程相关技术栈，刚在github看到了一个仓库（修改go-tun2socks），不知道这个方案能否可行。
[https://github.com/hello-david/SwiftV2Ray](url)
> 引用

```
// Tun2socks + V2RayCore 修改和使用
package tun2socks

import (
	"context"
	"runtime"
	"runtime/debug"
	"strings"
	"time"

	"github.com/eycorsican/go-tun2socks/common/log"
	"github.com/eycorsican/go-tun2socks/core"
	"github.com/eycorsican/go-tun2socks/proxy/v2ray"
	vcore "v2ray.com/core"
	vproxyman "v2ray.com/core/app/proxyman"
)

type PacketFlow interface {
	WritePacket(packet []byte)
}

func InputPacket(data []byte) {
	lwipStack.Write(data)
}

var lwipStack core.LWIPStack

func StartV2Ray(packetFlow PacketFlow, configBytes []byte) {
	if packetFlow == nil {
		return
	}

	lwipStack = core.NewLWIPStack()
	v, err := vcore.StartInstance("json", configBytes)
	if err != nil {
		log.Fatalf("start V instance failed: %v", err)
	}

	sniffingConfig := &vproxyman.SniffingConfig{
		Enabled:             true,
		DestinationOverride: strings.Split("tls,http", ","),
	}

	debug.SetGCPercent(5)
	ctx := vproxyman.ContextWithSniffingConfig(context.Background(), sniffingConfig)
	core.RegisterTCPConnHandler(v2ray.NewTCPHandler(ctx, v))
	core.RegisterUDPConnHandler(v2ray.NewUDPHandler(ctx, v, 30*time.Second))
	core.RegisterOutputFn(func(data []byte) (int, error) {
		packetFlow.WritePacket(data)
		runtime.GC()
		debug.FreeOSMemory()
		return len(data), nil
	})
}
```

**Comment by Kr328** [comment]
https://github.com/hello-david/SwiftV2Ray

这个也依赖 cgo

**Comment by Ariesly** [comment]
> 首先 gomobile 并没有回避掉 cgo 的问题 对平台编译器依赖大
> 
> 你可以看看现在的 action 只需要在一个机器 ubuntu 上 安装一个 golang 构建就能完成
> 
> 而引入 gomobile 或者说 cgo 后 就需要 Android SDK/NDK 和 xcode 对构建环境要求增大
> 
> 而且 clash 本身设计并不希望依赖任何特定平台
> 
> 其次 gomobile 需要以一个特定的 go package 生成对应的 Stub， clash 本身设计时 API 分散在各个不同的 package，额外设计一个 API package 只会增加维护成本，对 core 本身并没有任何用处

可用不必在这个core中添加，比如添加个ClashKit的库提供跨平台的组件.
ClashKit只负责产生组件.  对于构建环境，只在这边增大，不影响原的core

**Comment by Dreamacro** [comment]
https://github.com/yichengchen/clashX/blob/master/ClashX/goClash/main.go
https://github.com/trojan-gfw/igniter-go-libs/blob/master/clash/clash.go

这些都是各自 GUI 中直接使用 clash 的方式

**Comment by Since1999** [comment]
> ### 说明 Description
> 可否在Release Assets提供iOS版本的framework或者library呢，这样可以让更多iOS版本的Clash更容易生产出来。或者提供Build脚本也可以。
> 
> ### 可能的解决方案 Possible Solution
> Static Library or Framework or Build Script
> 
> ### 更多信息 More Information



> > 首先 gomobile 并没有回避掉 cgo 的问题 对平台编译器依赖大
> > 你可以看看现在的 action 只需要在一个机器 ubuntu 上 安装一个 golang 构建就能完成
> > 而引入 gomobile 或者说 cgo 后 就需要 Android SDK/NDK 和 xcode 对构建环境要求增大
> > 而且 clash 本身设计并不希望依赖任何特定平台
> > 其次 gomobile 需要以一个特定的 go package 生成对应的 Stub， clash 本身设计时 API 分散在各个不同的 package，额外设计一个 API package 只会增加维护成本，对 core 本身并没有任何用处
> 
> 感谢回复，本人没有GO和网络编程相关技术栈，刚在github看到了一个仓库（修改go-tun2socks），不知道这个方案能否可行。 [https://github.com/hello-david/SwiftV2Ray](url)
> 
> > 引用
> 
> ```
> // Tun2socks + V2RayCore 修改和使用
> package tun2socks
> 
> import (
> 	"context"
> 	"runtime"
> 	"runtime/debug"
> 	"strings"
> 	"time"
> 
> 	"github.com/eycorsican/go-tun2socks/common/log"
> 	"github.com/eycorsican/go-tun2socks/core"
> 	"github.com/eycorsican/go-tun2socks/proxy/v2ray"
> 	vcore "v2ray.com/core"
> 	vproxyman "v2ray.com/core/app/proxyman"
> )
> 
> type PacketFlow interface {
> 	WritePacket(packet []byte)
> }
> 
> func InputPacket(data []byte) {
> 	lwipStack.Write(data)
> }
> 
> var lwipStack core.LWIPStack
> 
> func StartV2Ray(packetFlow PacketFlow, configBytes []byte) {
> 	if packetFlow == nil {
> 		return
> 	}
> 
> 	lwipStack = core.NewLWIPStack()
> 	v, err := vcore.StartInstance("json", configBytes)
> 	if err != nil {
> 		log.Fatalf("start V instance failed: %v", err)
> 	}
> 
> 	sniffingConfig := &vproxyman.SniffingConfig{
> 		Enabled:             true,
> 		DestinationOverride: strings.Split("tls,http", ","),
> 	}
> 
> 	debug.SetGCPercent(5)
> 	ctx := vproxyman.ContextWithSniffingConfig(context.Background(), sniffingConfig)
> 	core.RegisterTCPConnHandler(v2ray.NewTCPHandler(ctx, v))
> 	core.RegisterUDPConnHandler(v2ray.NewUDPHandler(ctx, v, 30*time.Second))
> 	core.RegisterOutputFn(func(data []byte) (int, error) {
> 		packetFlow.WritePacket(data)
> 		runtime.GC()
> 		debug.FreeOSMemory()
> 		return len(data), nil
> 	})
> }
> ```

老哥解决了吗？我现在也在看这块
