### ISSUE TITLE
关于dns-hijack的一些疑惑，希望解惑

### ISSUE THREAD

**Issue by LittleRey** [Dreamacro/clash#1182]
1.dns-hijack的工作原理，wiki里只是说在fake ip模式下的用法，没有说redit-host模式下用法,请说的详细具体一点
2.Preium内核是否支持tcp dns处理，如果不支持，是否要启用dns-hijack拦截tcp dns

**Comment by emacsnt** [comment]
个人的浅见，班门弄斧，还务见笑：
1， dns-hijack是经过路由器的udp/tcp dns请求[请求的目的地并非在路由器上]被clash拦截，然后用了clash内置的dns来回答这个dns请求。主要解决的是 google Home这类固定dns服务器为8.8.8.8的应用
2，Premium内核内置dns是否支持tcp协议，不影响tcp dns请求正常工作，hijack主要是为了处理udp请求的，tcp的dns本来就可以被clash正确处理。

**Comment by Dreamacro** [comment]
一般来说，属性在哪个字段下面，那么里面的字段就属于这个字段的一部分。在这里 `dns-hijack` 属于 `tun`，也就是这个功能是 tun 的一部分，不是局限于 fakeip 或 redir-host。

dns 其实分为两部分，一个是作为服务端，clash 目前只支持使用 udp 作为服务端。但是如果作为一个客户端，clash 支持的种类就稍微多了一些: DoH TCP UDP DoT。对于 hijack，其本质是拦截 dns 请求，并作为客户端使用 clash 里的配置请求，所以除了能用多个 upstream 之外，还能让 clash 知道域名和 ip 的映射关系。`dns-hijack` 本身是支持拦截 tcp 和 udp 的，因为这两个方案都是明文传输。
