### ISSUE TITLE
[Feature]ShadowsocksR 的加密方式里面没有none

### ISSUE THREAD

**Issue by fanrongboy** [Dreamacro/clash#1186]
我一直选择不加密的，用过不下10种客户端，第一次碰到没有none选项的，事实上协议里支持ahead的都已经自带加密了，选none完全没有问题，速度还快

**Comment by fanrongboy** [comment]
![image](https://user-images.githubusercontent.com/26063705/104810535-2b1e1b80-5830-11eb-82a0-8f6fa616c8bc.png)

**Comment by xuezhi420** [comment]
这个问题之前就提很久了，一直没加上

**Comment by SplitGemini** [comment]
因为这部分不是作者写的

**Comment by shikkoku** [comment]
你找Lean提下？

**Comment by dukh1216** [comment]
> 我一直选择不加密的，用过不下10种客户端，第一次碰到没有none选项的，事实上协议里支持ahead的都已经自带加密了，选none完全没有问题，速度还快

是你用的插件版本太旧了

![image](https://user-images.githubusercontent.com/56962531/105111792-a61b5680-5afc-11eb-9086-feccd1b67af4.png)

**Comment by shikkoku** [comment]
> > 我一直选择不加密的，用过不下10种客户端，第一次碰到没有none选项的，事实上协议里支持ahead的都已经自带加密了，选none完全没有问题，速度还快
> 
> 是你用的插件版本太旧了
> 
> ![image](https://user-images.githubusercontent.com/56962531/105111792-a61b5680-5afc-11eb-9086-feccd1b67af4.png)

这是基于Clash内核的?

**Comment by dukh1216** [comment]
> > > 我一直选择不加密的，用过不下10种客户端，第一次碰到没有none选项的，事实上协议里支持ahead的都已经自带加密了，选none完全没有问题，速度还快
> > 
> > 
> > 是你用的插件版本太旧了
> > ![image](https://user-images.githubusercontent.com/56962531/105111792-a61b5680-5afc-11eb-9086-feccd1b67af4.png)
> 
> 这是基于Clash内核的?

当然不是 我只是想说你这一段是作者用的lean的旧代码，更新了作者没跟进。另外我不太明白 如果没有什么必须使用clash的原因的话，ssrplus和passwall这一类的插件其实更适合普通用户。

**Comment by CoderTonyChan** [comment]
是不是那个merge合了就OK？
