### ISSUE TITLE
[Feature] 可否在配置文件中对单个proxy-provider或rule-provider中自定义header

### ISSUE THREAD

**Issue by AlphaAnother** [Dreamacro/clash#1193]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

`curl -H 'Authorization: token the_token' -O https://raw.githubusercontent.com/user/repo/branch/a.yaml`
需要使用从github私有库下载的节点列表和规则集，现在因为无法自定义header来通过私有库验证所以只能下载后手动替换。如果能在配置文件对单个proxy-provider或rule-provider中自定义header就好了。

**Comment by Dreamacro** [comment]
私有库点击 Raw 之后会有一串带 Token 的 url，直接用那个就可以了

**Comment by AlphaAnother** [comment]
> 私有库点击 Raw 之后会有一串带 Token 的 url，直接用那个就可以了

这个链接不能长时间保持吧

**Comment by sddpljx** [comment]
> > 私有库点击 Raw 之后会有一串带 Token 的 url，直接用那个就可以了
> 
> 这个链接不能长时间保持吧

尝试使用GitHub Gists呢？Gists可以设置为私密，并且链接也不会失效。

**Comment by AlphaAnother** [comment]
> > > 私有库点击 Raw 之后会有一串带 Token 的 url，直接用那个就可以了
> > 
> > 
> > 这个链接不能长时间保持吧
> 
> 尝试使用GitHub Gists呢？Gists可以设置为私密，并且链接也不会失效。

谢谢提醒！不说我都忘了还有gist可以用了···
