### ISSUE TITLE
[Feature] 可否修改 proxy-providers 中User-Agent 字段，以兼容v2board等模板

### ISSUE THREAD

**Issue by deddey** [Dreamacro/clash#1195]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

在v2board 等机场模板中，所有的过墙软件的订阅链接都是相同的，根据请求链接的User-Agent 不同值返回不同的订阅。对于clash的订阅，需要在User-Agent 中包含关键字 “clash” ，才会返回clash配置。

### 可能的解决方案 Possible Solution

建议修改proxy-providers 中User-Agent 的值为 “clash” 或“clash/(版本号)”，以兼容该类机场模板，谢谢

**Comment by LinEvil** [comment]
Same Request
虽然这显然是机场模板的问题，但我觉得 clash 需要一个 UA。

**Comment by tsln1998** [comment]
sspanel 路由支持传入订阅类型，故不在本 issue 影响范围内
```php
//通用訂閲
$app->group('/sub', function (): void {
    $this->get('/{token}/{subtype}', App\Controllers\SubController::class . ':getContent');
});
```

题主说到的 v2board 确实是依靠 User-Agent 自动识别客户端类型，但同时也允许使用 Request Param 覆盖 UA 值

https://github.com/v2board/v2board/blob/0e75b835074322ad5e1d02ac688ac53e564bad71/app/Http/Controllers/Client/ClientController.php#L15

```php
public function subscribe(Request $request)
{
    $flag = $request->input('flag')
        ?? (isset($_SERVER['HTTP_USER_AGENT'])
            ? $_SERVER['HTTP_USER_AGENT']
            : '');
   // ...
}
```

例：

原订阅地址:

> http://example.com/api/v1/client/subscribe?token=AAAAAA

强制返回 Clash 配置的订阅地址:

> http://example.com/api/v1/client/subscribe?token=AAAAAA&flag=clash
