### ISSUE TITLE
[咨询确认]关于clash和openclash的Premium版本

### ISSUE THREAD

**Issue by emacsnt** [Dreamacro/clash#1196]
[关于clash和openclash的Premium版本](https://github.com/vernesong/OpenClash/issues/1165)
请教了OpenClash的作者，他说是一样的，但是两者文件体积差了很多，而且clash的Premium版本是闭源的，想请教  @Dreamacro 对于这个版本差异的看法

**Comment by Dreamacro** [comment]
我也不知道这个是从哪出来的，根据版本信息 `2021.01.01.g0ab75c5` 拿到 0ab75c5 这个 commit id，这个 id 是确实存在的，但却高于 12.27 的那个版本。但是我看了 github 和 gitlab 的 premium 仓库，没发现有他。

体积大小可能是套了一个 upx 壳。

**Comment by emacsnt** [comment]
谢谢Dreamacro回答， 看起来还是应该用clash原版安全一点。
issue我关闭了

**Comment by ttimasdf** [comment]
https://github.com/vernesong/OpenClash/issues/1165#issuecomment-766278964

**Comment by Dreamacro** [comment]
@ttimasdf 应该不是的，这个 commit id 是 premium 仓库里的。和那个 pr 不是同一个东西
