### ISSUE TITLE
Clash配置文件fallback应该是udp

### ISSUE THREAD

**Issue by iamwwc** [Dreamacro/clash#1197]
配置文件有个错误 https://github.com/Dreamacro/clash/wiki/configuration

```
 # fallback:
  #   - tcp://1.1.1.1
```

感觉应该是`udp://1.1.1.1`

一直报 connection reset by peer，发现开头竟然是 `tcp`，可是DNS是UDP请求，我理解的对吗

------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by luwah** [comment]
配置文件里有备注，并且这个配置文件只是示例

Supports UDP, TCP, DoT, DoH. You can specify the port to connect to. All DNS questions are sent directly to the nameserver, without proxies involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS

**Comment by iamwwc** [comment]
> 配置文件里有备注，并且这个配置文件只是示例
> 
> Supports UDP, TCP, DoT, DoH. You can specify the port to connect to. All DNS questions are sent directly to the nameserver, without proxies involved. Clash answers the DNS question with the first result gathered.
> nameserver:
> - 114.114.114.114 # default value
> - 8.8.8.8 # default value
> - tls://dns.rubyfish.cn:853 # DNS over TLS
> - https://1.1.1.1/dns-query # DNS over HTTPS

我说的是fallback，不是namespace

**Comment by luwah** [comment]
根据注释内容，fallback与nameserver是并发处理的，都支持多种DNS方式，只是根据fallback-filter，最终选取回报结果的方式不同

**Comment by iamwwc** [comment]
> 根据注释内容，fallback与nameserver是并发处理的，都支持多种DNS方式，只是根据fallback-filter，最终选取回报结果的方式不同

哦哦，学到了，谢谢:)

**Comment by ygsk10** [comment]
支持的，tcp 的 DNS 查询会被牠 reset

**Comment by iamwwc** [comment]
> 支持的，tcp 的 DNS 查询会被牠 reset

不明白，既然支持，为啥cloudflare又会reset呢

**Comment by ygsk10** [comment]
会被 GFW reset

**Comment by iamwwc** [comment]
> 会被 GFW reset
那为啥udp不会被reset呢？

**Comment by pfangzhi** [comment]
> > 会被 GFW reset
> > 那为啥udp不会被reset呢？

gfw可以直接检查udp的报文，可以知道你在查询啥，tcp GFW识别不到你在干啥所以就宁杀一千不放一个。懂了没

**Comment by iamwwc** [comment]
> > > 会被 GFW reset
> > > 那为啥udp不会被reset呢？
> 
> gfw可以直接检查udp的报文，可以知道你在查询啥，tcp GFW识别不到你在干啥所以就宁杀一千不放一个。懂了没

如果dns查询不走代理，国内裸连1.1.1.1，为啥能正确查询出google的dns？按你这么说，知道了在查询google，为啥不直接反馈错误的结果

**Comment by ygsk10** [comment]
[TCP reset attack - Wikipedia](https://en.wikipedia.org/wiki/TCP_reset_attack)
>TCP reset attack, also known as "forged TCP resets", "spoofed TCP reset packets" or "TCP reset attacks", is a way to tamper and terminate the Internet connection by **sending a forged TCP reset packet**


[User Datagram Protocol - Wikipedia](https://en.wikipedia.org/wiki/User_Datagram_Protocol)
>UDP uses a simple **connectionless** communication model with a minimum of protocol mechanisms. UDP provides checksums for data integrity, and port numbers for addressing different functions at the source and destination of the datagram. It has **no handshaking dialogues**

**Comment by kongminhao** [comment]
可以试试 `dig @1.1.1.1 google.com +tcp`

**Comment by Skyxim** [comment]
> > > > 会被 GFW reset
> > > > 那为啥udp不会被reset呢？
> > 
> > 
> > gfw可以直接检查udp的报文，可以知道你在查询啥，tcp GFW识别不到你在干啥所以就宁杀一千不放一个。懂了没
> 
> 如果dns查询不走代理，国内裸连1.1.1.1，为啥能正确查询出google的dns？按你这么说，知道了在查询google，为啥不直接反馈错误的结果

你确定能正常查出，你试试关闭clash之后再擦，有可能你的udp被代理到远程了查询了给你，不用代理国内都是污染了相关域名的查询的
