### ISSUE TITLE
[Feature] dns通过代理解析

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#1201]
clash的dns似乎是通过tls或者tcp来保证不被防火墙干扰的，这样做的优点是设计更简洁，dns模块本身不会耦合其他模块。
但是这样会有一个问题，这样解析出来的ip地址不一定是最适配代理的，因为dns服务器有时会根据源ip的位置返回不同的解析结果，以优化源ip访问该域名的是延迟和速度，而使用大陆的ip进行解析将无法利用这一点获得最优的ip。

实际使用中我发现我用透明代理翻墙时访问github的速度特别慢。我猜想可能是由于这个原因导致的。

是不是可以考虑fallback列表中的dns使用代理节点进行解析？

**Comment by isweibin** [comment]
[https://github.com/Dreamacro/clash/issues/968#issuecomment-692609859](url)
Clash 的 DNS 解析结果只用于判断，最终都会发送到远端服务器重新解析，对 fallback 列表中的 DNS 使用代理节点解析没有必要，在 Issue 中搜索一下相关 DNS 问题，你会更加理解。

**Comment by XuuKoo** [comment]
> [可能帮助你理解一个回答](https://github.com/Dreamacro/clash/issues/968#issuecomment-692609859)
> 
> Clash 的 DNS 解析结果只用于判断，最终都会发送到远端服务器重新解析，对 fallback 列表中的 DNS 使用代理节点解析没有必要，在 Issue 中搜索一下相关 DNS 问题，你会更加理解。

有设置规则的域名确实会远程解析，没有匹配到代理规则但最后MATCH，PROXY的好像并不会远程解析啊，而是用vps连接这个解析到的ip？
