### ISSUE TITLE
[Bug] time="2021-01-27T14:06:57+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"

### ISSUE THREAD

**Issue by 404LT** [Dreamacro/clash#1202]
win10打开clash-windows-amd64.exe文件，一直卡在这个界面
![image](https://user-images.githubusercontent.com/8578596/105950079-bb6a2500-60a8-11eb-92a5-9473d0fb4a7d.png)

------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by Dreamacro** [comment]
这是 Windows 运行二进制程序共有的 feature

**Comment by 404LT** [comment]
> 这是 Windows 运行二进制程序共有的 feature

可是这个弹窗没有小时，clash的ui界面也没有出来呢

**Comment by Dreamacro** [comment]
这个仓库是二进制程序，并不包含 GUI 部分
