### ISSUE TITLE
全局模式能否配置？

### ISSUE THREAD

**Issue by pc10201** [Dreamacro/clash#1205]
配置文件中基本都是rule模式的配置

全局模式默认的规则是直连

能否在配置文件中将全局模式的规则设置为自动选择最快节点或者某个节点呢？

**Comment by luwah** [comment]
Clash router working mode
rule: rule-based packet routing
global: all packets will be forwarded to a single endpoint
direct: directly forward the packets to the Internet
mode: global #全局

url-test select which proxy will be used by benchmarking speed to a URL.
```
  - name: "auto"
    type: url-test
    proxies:
```
但是你的意思应该是速度最快？这里是指低延时
如果只是某个节点，那就type: select

**Comment by Dreamacro** [comment]
我对「全局」的理解是这样的，所有通过 inbound 进来的连接或包，我都通过同一个 outbound 走出去，无论这个 outbound 是 DIRECT REJECT 还是其他的。

「直连」就是所有通过 inbound 进来的连接或包，我都通过 DIRECT 走出去

由于我不知道你想从哪个 outbound 出去，所以 Global 模式指向了一个包含所有代理的 Selector 组，通过改动这个组里选择的 outbound 最终走出去

**Comment by pc10201** [comment]
因为clash全局代理的处理逻辑跟其他代理软件不一样

clash切换到全局模式后，默认是direct，还得手动再选一次节点才能科学上网

有办法不用手动再选吗？提前在配置文件中配置好
或者直接选择最快的代理节点？

**Comment by akw5454521** [comment]
> 因为clash全局代理的处理逻辑跟其他代理软件不一样
> 
> clash切换到全局模式后，默认是direct，还得手动再选一次节点才能科学上网
> 
> 有办法不用手动再选吗？提前在配置文件中配置好
> 或者直接选择最快的代理节点？

不是Clash全局模式逻辑跟其他软件不一样，是Clash本身的逻辑就跟其他不一样，不是单节点的代理，全局模式下反倒跟其他更相像了。至于全局模式下默认direct排在最前边原因，这个就不清楚了，可以问问D大。但如果需要经常在rules和global之间切换，那说明规则部分还有可以改进的地方，建议编辑规则

**Comment by kaaass** [comment]
希望能增添一个GLOBAL Selector的默认选项（如issue #600）

**Comment by BruceLee569** [comment]
模式切换没有api调用么？我想知道GUI应用是怎么实现切换的？

**Comment by kaaass** [comment]
> Global模式选择节点好像没看到有api可以调用？我想知道GUI应用是怎么实现节点手动选择的？

API 应该和其他一样，`PUT /proxies/GLOBAL` 切换。

**Comment by BruceLee569** [comment]
> > Global模式选择节点好像没看到有api可以调用？我想知道GUI应用是怎么实现节点手动选择的？
> 
> API 应该和其他一样，`PUT /proxies/GLOBAL` 切换。

嗯嗯 我抓包也看到了，官方文档好多接口都没写 🤣

**Comment by ndxx** [comment]
除了 #600 以外还有  #1213 也提到了这个问题。
其实上面项目Owner对于Global模式的解释我也完全可以理解。但是避免相似的issue被stale之后自动关闭，然后又被重复提起，我这里还是想说一下，之所以被反复提起这个issue，是因为不用gui的clash用户也挺多的，配置文件里修改Global模式之后还要调用外部api来修改默认的DIRECT代理显得不那么优雅和方便。

**Comment by Dreamacro** [comment]
@ndxx 如果不使用任何 GUI，那又怎么设置具体 Global 的具体节点，难道整个代理只有一个节点么。不太能想象完全不调用 API 来使用，除非你不需要调整任何选择的节点

**Comment by kaaass** [comment]
@Dreamacro 如果增加诸如 GLOBAL Selector 的默认选项的话，应该可以实现不调用 API 来使用吧。比如将其指向 `url-test` 的 group 就能实现节点自动选择。此外，比较常见的一种配置方式是增加一个统一的 group 用来专门选择节点，这样如果让 GLOBAL 默认选择这个 group 的话操作起来会更加方便，比如从 Rule 切换到 Global 就不需要在 GLOBAL 里专门设置了。

**Comment by ndxx** [comment]
@Dreamacro @kaaass 大伙回复的非常积极啊。关于具体如何设置Global的节点，我觉得除了像 #600 里提出的那种增加配置文件中的额外选项的这种思路以外，似乎还可以从现有代码的逻辑层面做一个简单调整：

config.go文件的277行附近的代码块[https://github.com/Dreamacro/clash/blob/master/config/config.go#L277](url)，将append “DIRECT”和“REJECT”的相关逻辑放到处理完用户自己的proxyList之后。这样调整，可以将目前配置文件中proxies的第一个节点作为Global模式下的默认节点。

这样可以让非gui用户至少有一个workaround，每次简单的切换Rule和Global模式的时候不用再调用一次外部api去修改global的默认proxy。当然具体的实施我想应该不会么简单，甚至也许这个思路也行不通，仅供参考。

**Comment by JoinGitHubBa** [comment]
> 我对「全局」的理解是这样的，所有通过 inbound 进来的连接或包，我都通过同一个 outbound 走出去，无论这个 outbound 是 DIRECT REJECT 还是其他的。
> 
> 「直连」就是所有通过 inbound 进来的连接或包，我都通过 DIRECT 走出去
> 
> 由于我不知道你想从哪个 outbound 出去，所以 Global 模式指向了一个包含所有代理的 Selector 组，通过改动这个组里选择的 outbound 最终走出去


站在程序的角度理解“全局”非常正确。

我代表全体小白的理解是，
direct 用退出程序更直观，我目的是翻墙，为什么还要 direct。
reject 想不出有什么使用场景，非要用来去广告 adguard 不是更香。

还有比如 urltest 分组，如果能选择隐藏就更好了，反正选不了😄。

**Comment by murazi** [comment]
全局模式添加chrome的Google账号不可链接，但用V2R的全局模式就可以连接，我也搞不太明白这个全局模式，也不知道哪里修改规则去调整

**Comment by whenov** [comment]
如果全局模式允许DIRECT作为outbound的话，那么直连模式似乎有点多余，只要rule和global两个模式就够了

**Comment by hfj8210** [comment]
这个全局只是针对节点选择，比如Global指定节点是日本某个节点，那么你在油管选任何节点都比起作用，也就是说Global指定哪个节点，所有代理都是用这个节点。

**Comment by grayguest** [comment]
哇，我说我配置Global模式，为啥会多出一个Direct和Reject，而且默认是选择Direct，不知道现在这个问题能用配置文件直接删除Direct和Reject吗
