### ISSUE TITLE
可否支持系统默认DNS

### ISSUE THREAD

**Issue by uniway** [Dreamacro/clash#121]
希望能够支持系统默认DNS，速度快很多

**Comment by Dreamacro** [comment]
先说如何拿系统的 DNS Server: unix 是从 /etc/resolv.conf 中拿，Windows 好像没有什么好的方法，只能通过调用命令拿到。

当网络环境发生变化的时候（比如切换 Wifi）, DNS Server 会发生变化，但 Clash 本身不知道网络环境发生了变化。于是自定义 DNS 没法去支持这个功能。

还有就是如果不使用自定义 DNS 功能的话，其实是走系统默认 DNS 的。

**Comment by Semidio** [comment]
也许可以每隔一定时间获取一次系统DNS？

**Comment by Dreamacro** [comment]
@Semidio 先教教我怎么拿 windows 的 dns

**Comment by Semidio** [comment]
ipconfig | findstr /R "网关" or ipconfig | findstr /R "DNS\ Servers"
netsh interface ip show dns | findstr /R "DNS"
echo exit | nslookup | findstr /R "Address"

**Comment by Semidio** [comment]
@Dreamacro 
ipconfig | findstr /R "网关" or ipconfig | findstr /R "DNS\ Servers"
netsh interface ip show dns | findstr /R "DNS"
echo exit | nslookup | findstr /R "Address"

**Comment by BirkhoffLee** [comment]
這邊後來的決議我記得是交給 Clash 的衍生版？總之這個功能暫時不可能實作
