### ISSUE TITLE
[Feature] 代理的域名能否使用default-nameserver来解析

### ISSUE THREAD

**Issue by emacsnt** [Dreamacro/clash#1214]
没有使用fallback dns，而且只在namerserver中设定可信dns，这些可信dns都需要翻墙才能使用，而proxy本身的域名观察到要通过nameserver来解析，这样就变成了死循环，出现错误context deadlock.
所以，是否可以使用default-nameserver(国内dns)来解析proxy的域名。因为proxy都需要国内直接连接，所以可以使用国内dns来解析。

**Comment by LazyZhu** [comment]
可以设置 `hosts`:
```
 'dns.google': 8.8.8.8

**Comment by emacsnt** [comment]
不是dns服务器域名的解析，这个default-nameserver可以工作，我说的是代理站点的域名，clash用的nameserver来解析的。机场代理的域名很多，而且是动态的，如果为代理域名配置host非常麻烦

**Comment by LazyZhu** [comment]
我懂你意思了, 常见解决方法是增加一个 boot dns 选项来专门解决这个问题, 很多DoH客户端都是用的这个方法.

**Comment by Dreamacro** [comment]
@LazyZhu 这个就是所谓的 boot dns，解决 DoH 域名的，但不是解决 proxy 域名的

**Comment by Dreamacro** [comment]
clash 内部的连接都是不走代理的，即使 proxy 的域名用 default nameserver 解析出来了也没用

**Comment by LazyZhu** [comment]
@Dreamacro
这可能也是clash为了简化DNS模块吧, 随着DoH普及这个问题也频繁被提出来了, 如 https://github.com/Dreamacro/clash/pull/868, 除了代理远程DNS解析, 为了解决CDN解析的问题, DNS走代理的需求一直很多, SS + DNS2SOCKS 就是最常用的, 还有 https://github.com/XTLS/Xray-core/pull/147 等.

**Comment by LazyZhu** [comment]
@Dreamacro 
题外话, cash 好像有保存最近10次的延迟检测, 但是只利用了最近的一次, 可否扩展下功能, 像 https://github.com/v2fly/v2ray-core/pull/589 一样提高检测代理准确度. V2Ray v5 添加的这个检测机制个人使用一个星期后要好于cash现在的一次性检测, 特别是在网络高峰时期.

**Comment by emacsnt** [comment]
@Dreamacro
不需要proxy本身走代理，只需要proxy域名解析用default-nameserver来解析. 因为我的场景比较特殊，dns配置没用国内的dns，所以Proxy域名解析不到。
逻辑上来分析，proxy站点应该和国内直连的，否则proxy套proxy就有点问题了，所以proxy的域名解析应该属于default-nameserver的工作。

目前状态下，要带域名的proxy正常工作，一定要有不需要走代理的dns来配合工作，感觉这个局限应该是被解决的。

**Comment by akw5454521** [comment]
不懂为什么要只在nameserver里设定国外dns，上网不会慢吗

**Comment by emacsnt** [comment]
@akw5454521 完全彻底分流国内国外了， 国内所有流量不经过clash，这样可以保护隐私，国内dns不会知道有访问国外站点的记录

**Comment by emacsnt** [comment]
default-nameserver(boot-dns)的存在理由 是为了解析nameserver和fall-back里面的DoH和DoT的域名，因为它们自己不能解析出自己的地址
同样，为了让大部分DoH和DoT可以正常工作，需要通过default-nameserver解析出代理的域名，因为大部分DoH和DoT需要翻墙才能工作。
基于以上的理由，default-nameserver应该有负责解析DoH，DoT以及代理的域名。代理域名由default-nameserver负责解析是逻辑自洽的，而且可以防止隐私泄露。

**Comment by emacsnt** [comment]
通过下面的issue解决代理节点域名的解析分流
#1376 
https://github.com/Dreamacro/clash/pull/1406
