### ISSUE TITLE
域名中出现-时代理失败

### ISSUE THREAD

**Issue by VoVAllen** [Dreamacro/clash#122]
例如访问"a-a.baidu.com"使用clash代理直接显示连接被重置，在clash的log中也看不到该域名

**Comment by VoVAllen** [comment]
仅在rule模式有这个问题，global模式下正常

**Comment by Dreamacro** [comment]
我这没问题，能提供一个具体的网址吗

**Comment by VoVAllen** [comment]
我试了一下好像和rule有关，把这个rule去掉就好了
下面这个是我用的rule，用了之后域名带杠就不正常了
https://gist.github.com/VoVAllen/a5df9c4caad77548543467b54521459c

我是在上Instagram的时候发现这个问题的，图片加载不出来

**Comment by Dreamacro** [comment]
这个规则我这没有问题

**Comment by beyondkmp** [comment]
有dns 配置吗？先不用dns 配置看下行不行？

Dreamacro <notifications@github.com> 于 2019年2月21日周四 19:54写道：

**Comment by VoVAllen** [comment]
试一下这个链接您看rule模式下能访问吗
[link](https://scontent-hkg3-2.cdninstagram.com/vp/e174780ada0262bb98db895b77c12400/5D2414B0/t51.2885-19/s150x150/51940791_1124898364354738_283225987632594944_n.jpg?_nc_ht=scontent-hkg3-2.cdninstagram.com)

**Comment by Dreamacro** [comment]
@VoVAllen 正常

**Comment by VoVAllen** [comment]
我建了了个私有仓库分享我的clash配置文件求帮忙看一下，我用的是clash for windows

https://github.com/VoVAllen/clash_config/invitations

[config link](https://github.com/VoVAllen/clash_config/blob/master/config%20link)
多谢！
