### ISSUE TITLE
[Bug] Trojan x509 error: certificate signed by unknown authority

### ISSUE THREAD

**Issue by zexxlin** [Dreamacro/clash#1224]
使用Trojan协议时，clash在TLS握手阶段报错：certificate signed by unknown authority。

使用的为letsencrypt申请的免费证书，浏览器可验证通过。若将skip-cert-verify置为true，可能遭遇中间人攻击，是否有更为妥善的解决方案？

**Comment by Dreamacro** [comment]
看看 https://github.com/matrix-org/synapse/issues/4764

**Comment by zexxlin** [comment]
感谢大佬，改成fullchain就行了，之前给的单证书。
