### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by bcookatpcsd** [Dreamacro/clash#1225]
# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true
  listen: 127.0.0.1:5399
  ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 192.168.10.195:5300

I have a nameserver listening on a different server on port 5300.. 

is there anyway to get to it?

Or does the dns only go to :53

Thanks in advance.

**Comment by Dreamacro** [comment]
```yaml
dns:
  enable: true
  nameserver:
    - 192.168.10.195:5300
```
