### ISSUE TITLE
请问bind interface 如何使用

### ISSUE THREAD

**Issue by clqs** [Dreamacro/clash#1226]
我安装上0.41.14 beta以后，无法实现科学上网。gfw以内没有问题。出不去。而且，绑定的接口似乎也没有生效，在网上查了很久，没有相关的介绍，请大神指教。万分感谢

**Comment by luwah** [comment]
你是指openclash，建议首先查询对应wiki，然后在那里提问，并建议提问时提供相关config。因为问题未必出在bind interface上。
