### ISSUE TITLE
[Bug]  Trojan connect error: x509: certificate is valid

### ISSUE THREAD

**Issue by Kevin-Ben** [Dreamacro/clash#1229]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```json
{"name":"56.中继中转隧道线路覆盖", "password":"1b3e73d1-c1ba-3f3e-ad6b-72e061981758", "port":1056, "server":"scdn.1056.folvkq.china-ncdn-nrds.com", "skip-cert-verify":false, "sni":"SCDN.1056.FOLVKQ.China-nCDN-nRDS.com", "type":"trojan"}
```

```go
		trojanOption := &TrojanOption{}
		err = decoder.Decode(mapping, trojanOption)
		if err != nil {
			break
		}
		proxy, err = NewTrojan(*trojanOption)
```
</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Mac Os
* 网路环境或拓扑 (network conditions/topology)
家庭网络，中国电信
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
使用阿里云DNS
* 其他 (any other information that would be useful)
……

### 说明 Description
`go` 引入 `"github.com/Dreamacro/clash/adapters/outbound"`
使用 `outbound.ParseProxy`，传入上面的Json

错误提示：connect error: x509: certificate is valid for shost.j01h2106.kxrrgu.china-nhost-nsql.com

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by Dreamacro** [comment]
证书是 `shost.j01h2106.kxrrgu.china-nhost-nsql.com` 的

而不是 `SCDN.1056.FOLVKQ.China-nCDN-nRDS.com` 的
