### ISSUE TITLE
[Bug]tun的fakeip模式正常使用一端时间后挂掉

### ISSUE THREAD

**Issue by Zhuangkh** [Dreamacro/clash#1231]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true

external-controller: 0.0.0.0:9090
external-ui: dashboard

interface-name: ens18

tun:
  enable: true
  #system # or gvisor
  stack: system
  dns-hijack:
     - 192.168.0.3:2323
     - tcp://8.8.8.8:53
  macOS-auto-route: true

dns:
  enable: true
  listen: 0.0.0.0:3223
  ipv6: true
  default-nameserver:
    - 127.0.0.1:2323
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 

```

</details>

### Clash log

```
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=info msg="[UDP] 192.168.0.245:58669 --> stun6.chat.bilibili.com match RuleSet(StreamingSE) using StreamingSE[DIRECT]"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=info msg="[UDP] 192.168.0.245:58671 --> stun6.chat.bilibili.com match RuleSet(StreamingSE) using StreamingSE[DIRECT]"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=info msg="[UDP] 192.168.0.245:58734 --> stun6.chat.bilibili.com match RuleSet(StreamingSE) using StreamingSE[DIRECT]"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
2月 17 14:04:02 bypass clash[7718]: time="2021-02-17T14:04:02+08:00" level=debug msg="[Rule] find process name Process error: no such process"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Linux version 4.19.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27)
* 网路环境或拓扑 (network conditions/topology)

使用clash作为旁路由网关，dns服务为pihole（先过pihole去广告，pihole上游为clash的dns）

* iptables，如果适用 (if applicable)

> ipset create localnetwork hash:net
> ipset add localnetwork 127.0.0.0/8
> ipset add localnetwork 10.0.0.0/8
> ipset add localnetwork 169.254.0.0/16
> ipset add localnetwork 192.168.0.0/16
> ipset add localnetwork 224.0.0.0/4
> ipset add localnetwork 240.0.0.0/4
> ipset add localnetwork 172.16.0.0/12
> ip tuntap add user root mode tun utun
> ip link set utun up
> ip address replace 172.31.255.253/30 dev utun
> ip route replace default dev utun table 0x162
> ip rule add fwmark 0x162 lookup 0x162
> iptables -t mangle -N CLASH
> iptables -t mangle -F CLASH
> iptables -t mangle -A CLASH -d 198.18.0.0/16 -j MARK --set-mark 0x162
> iptables -t mangle -A CLASH -m addrtype --dst-type BROADCAST -j RETURN
> iptables -t mangle -A CLASH -m set --match-set localnetwork dst -j RETURN
> iptables -t mangle -A CLASH -j MARK --set-mark 0x162
> iptables -t nat -N CLASH_DNS
> iptables -t nat -F CLASH_DNS 
> iptables -t nat -A CLASH_DNS -p udp -j REDIRECT --to-ports 3223
> iptables -t mangle -I OUTPUT -j CLASH
> iptables -t mangle -I PREROUTING -m set ! --match-set localnetwork dst -j MARK --set-mark 0x162
> iptables -t nat -I OUTPUT -p udp --dport 53 -j CLASH_DNS
> iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to 3223
> iptables -t filter -I OUTPUT -d 172.31.255.253/30 -j REJECT

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

参考[Setup Gvisor in Fake-IP mode](https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/setup-gvisor-in-fake-ip-mode)一文配置了使用tun的fakeip模式的旁路由，正常使用过程中一切正常。

在使用一段时间后（无法准确估计时间，试过一天多，试过几小时），clash无法正常工作接受请求。日志中出现大量 find process name Process error。重启clash后正常。

**我预期会发生……？**

能够正常稳定的使用clash

**实际上发生了什么？**

**Comment by Dreamacro** [comment]
@Kr328 有没有什么想法

**Comment by Kr328** [comment]
大约是 DNS 回环了

OUTPUT 链 Clash 的 DNS 流量 被重新定向到 Clash 的 DNS 服务器

脚本中并没有任何排除 Clash 的 DNS 重定向的命令

**Comment by Zhuangkh** [comment]
> 大约是 DNS 回环了
> 
> OUTPUT 链 Clash 的 DNS 流量 被重新定向到 Clash 的 DNS 服务器
> 
> 脚本中并没有任何排除 Clash 的 DNS 重定向的命令

确实有这个可能..但是dns回环的话clash大概不应该有dns的请求日志在..? @Kr328 

> 2月 18 11:00:53 bypass clash[23642]: time="2021-02-18T11:00:53+08:00" level=debug msg="[DNS] arc.msn.com --> 52.139.154.55"
> 2月 18 11:00:53 bypass clash[23642]: time="2021-02-18T11:00:53+08:00" level=debug msg="[DNS] img-s-msn-com.akamaized.net --> 23.78.141.203"
> 2月 18 11:00:04 bypass clash[23642]: time="2021-02-18T11:00:04+08:00" level=debug msg="[DNS] css.etimg.com --> 104.75.254.204"

**Comment by Zhuangkh** [comment]
啊我悟了 我这个方案没必要转发dns的流量的 上一条回复测试的时候误把iptables规则清了所以dns请求正常

不过删了关于dns的转发规则还是会有不少`find process name Process error: no such process`

**Comment by Dreamacro** [comment]
> 啊我悟了 我这个方案没必要转发dns的流量的 上一条回复测试的时候误把iptables规则清了所以dns请求正常
> 
> 
> 
> 不过删了关于dns的转发规则还是会有不少`find process name Process error: no such process`
> 
> 

其他机器的流量应该不会有 process name

**Comment by Zhuangkh** [comment]
去掉了dns转发规则后虽然还有一些process错误但是暂时没出现应用宕机的情况。
