### ISSUE TITLE
[Bug] Clash Premium latest docker Tun 模式运行一段时间下载速度会变慢，容器重启后速度可以恢复

### ISSUE THREAD

**Issue by leeaash** [Dreamacro/clash#1236]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

### 更多信息 More Information
运行设备：unifi udm 
container engine: podman
非docker方式下似乎未遇到此问题

**Comment by Dreamacro** [comment]
网络模式是 host 么

**Comment by leeaash** [comment]
> 网络模式是 host 么, 没有其他的日志？

是host模式，clash日志貌似看不出问题，目前我也没找到好的troubleshooting方法来定位问题。
另外我现在不台确实是否非docker模式似乎也是有问题的，但可能只是时间长短的问题。但我刚才重启了一个运行很久的clash进程，speedtest的测速确实比重启前要改善很多

**Comment by Dreamacro** [comment]
gvisor 还是 system

**Comment by leeaash** [comment]
> gvisor 还是 system

用的都是gvisor

**Comment by Dreamacro** [comment]
改用 system 呢，latest 这个 tag 是不断变化的，你用的是最新的吗，中间更新过一次 gvisor 版本

**Comment by leeaash** [comment]
> 改用 system 呢，latest 这个 tag 是不断变化的，你用的是最新的吗，中间更新过一次 gvisor 版本

我改system再观察
latest不是1227那个版本，是你3天前push的，应该算最新的吧

**Comment by xuhuanxxx** [comment]
podman+macvlan+tun模式，刚好遇到同样的问题，大概8小时之后，流量就像进了黑洞，容器重启之后恢复正常。下次再看下podman是不是发生了啥。。

**Comment by wmyfelix** [comment]
虽然不是Docker但是也遇到了相同问题，切换system试试。
