### ISSUE TITLE
[Feature]请求实现URL Rewrite功能

### ISSUE THREAD

**Issue by xyxu1024** [Dreamacro/clash#1238]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

请求实现URL Rewrite功能，典型的例子是访问google.cn是跳转至google.com，#165 #272 

### 可能的解决方案 Possible Solution

[272#issuecomment-586992806](https://github.com/Dreamacro/clash/issues/272#issuecomment-586992806)
当中提到添加rewrite关键字

```
rewrite:
  - URL-REWRITE, ^http://www\.google\.cn http://www.google.com, header # 302 or REJECT
  - HEADER-REWRITE, ^http://example.com,header-replace=User-Agent, Unknown
```

**Comment by love4taylor** [comment]
作者没计划做 MITM https://github.com/Dreamacro/clash/issues/709#issuecomment-632006318

**Comment by NyaMisty** [comment]
> 作者没计划做 MITM [#709 (comment)](https://github.com/Dreamacro/clash/issues/709#issuecomment-632006318)

？不做mitm跟你不做url rewrite有关系吗？这俩工作层级都不一样，连url rewrite都没有还做啥mitm？
