### ISSUE TITLE
[Bug] tproxy ipv6 tcp 不工作

### ISSUE THREAD

**Issue by h0cheung** [Dreamacro/clash#1239]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
tproxy-port: 7892
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
external-controller: 127.0.0.1:9090
secret: ...
experimental:
  ignore-resolve-fail: false
```

</details>

### Clash log

日志中没有任何 tcp ipv6 相关内容（udp ipv6 正常）

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Arch Linux
* 网路环境或拓扑 (network conditions/topology)
普通电信家宽双栈网络
* iptables，如果适用 (if applicable)

ip6tables 隐藏了部分 ID（<> 部分，net_cls 用于绕过部分进程流量，比如 clash 自身），隐藏掉的链均为空规则（policy ACCEPT）。ipv4 部分与 ipv6 几乎相同且正常工作，故略去。

mangle:
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
TPROXY     udp      anywhere             anywhere             ! match-set localnetwork6 dst TPROXY redirect :::7892 mark <mark>/0xffffffff
TPROXY     tcp      anywhere             anywhere             ! match-set localnetwork6 dst TPROXY redirect :::7892 mark <mark>/0xffffffff

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
CLASH6     all      anywhere             anywhere    

Chain CLASH6 (1 references)
target     prot opt source               destination         
RETURN     all      anywhere             anywhere             cgroup <net_cls id>
RETURN     all      anywhere             anywhere             match-set localnetwork6 dst
MARK       all      anywhere             anywhere             MARK set <mark>
```

nat:
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   udp      anywhere             anywhere             udp dpt:domain redir ports 1053

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
CLASH_DNS6  udp      anywhere             anywhere             udp dpt:domain

Chain CLASH_DNS6 (1 references)
target     prot opt source               destination         
RETURN     all      anywhere             anywhere             cgroup <net_cls id>
REDIRECT   udp      anywhere             anywhere             redir ports 1053
```

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)

ipv6 路由规则：

```shell
ip -6 route replace local default dev lo table <table id>
ip -6 rule add fwmark <mark> lookup <table id>
```

### 说明 Description

tproxy ipv6 tcp 完全不工作，通过 `ip6tables -t mangle -L -v` 可以看到有流量进入 `TPROXY     tcp      anywhere             anywhere             ! match-set localnetwork6 dst TPROXY redirect :::7892 mark <mark>/0xffffffff`，但 clash 无任何反应。请求连接的程序会一直等待直至超时。

### 重现问题的具体布骤 Steps to Reproduce

按如上路由及 ip6tables 规则配置并使用 clash 的 ipv6 tproxy。

**我预期会发生……？**
tcp 与 udp 都正常工作

**实际上发生了什么？**
ipv6 只有 udp 工作

### 更多信息 More Information
clash 版本：dev 分支最新

**Comment by Kr328** [comment]
能用 tcpdump 抓抓包吗

**Comment by flyhigherpi** [comment]
嗯哼，有一台华硕ac5300用户反映同样问题，
不过我的AX88U一切正常

**Comment by h0cheung** [comment]
> 能用 tcpdump 抓抓包吗

tcpdump 不太熟悉，用 wireshark 抓了一下，使用 telnet 连接 cloudflare-dns.com 的 ipv6 地址 443 端口，telnet 一直 trying 直到 timeout。
lo 上 SYN 和 SYN-ACK 后为三个 bad tcp 包，然后对方再发 SYN-ACK，本机 RST，再然后为大量 bad tcp。
wifi 网卡上没有相关流量。

**Comment by h0cheung** [comment]
排查了几遍还是没有头绪，暂时回到 comzyh 的 tun 版本

**Comment by Y32Gcnte8z** [comment]
我也遇到一样的问题，我用lsof看发现没有监听ipv6的tproxy端口，只监听了ipv4的，看来是clash没有支持ipv6的tproxy
