### ISSUE TITLE
请问clash可以单独配置为某个域名下的所有子域名使用特定DNS进行解析吗

### ISSUE THREAD

**Issue by lqdflying** [Dreamacro/clash#124]
请问clash可以单独配置为某个域名下的所有子域名使用特定DNS进行解析吗?
比如*.163.com的所有匹配域名使用1.1.1.1来解析——类似这样子.
这个功能的好处是假如我的DDNS托管在某个域名服务商，那么我的DDNS自然是使用这个域名服务商自己的DNS服务器来解析会刷新的更快

**Comment by Dreamacro** [comment]
如果只是为了 DNS 记录变更刷新的更快的话，我想没必要增加 clash 的复杂度

**Comment by Fndroid** [comment]
可以配置一个[overture](https://github.com/shawn1m/overture)，然后提供给Clash

**Comment by lqdflying** [comment]
> 可以配置一个[overture](https://github.com/shawn1m/overture)，然后提供给Clash

名了，感谢大佬
