### ISSUE TITLE
[Feature]读取 SNI 来进行域名匹配

### ISSUE THREAD

**Issue by Jkkoi** [Dreamacro/clash#1240]
- [ x ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### 说明 Description

希望可以支持 **通过读取 SNI ([服务器名称指示](https://zh.m.wikipedia.org/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%90%8D%E7%A7%B0%E6%8C%87%E7%A4%BA)) 来进行域名匹配**

以便于支持安卓自带的 私有DNS(系统级的 DoT)
或使用其他 DNS 服务的特殊内容（比如自建除广告 DNS）

**Comment by fishg** [comment]
这个特性还是不错的，可以极大的减少dns依赖

**Comment by Dreamacro** [comment]
这个说明看起来像是 MITM 而不是读取 sni，读取 DoT 的 sni 只能拿到 DoT 的域名, 并不能拿到对这个 dns server 请求的内容。

对于 MITM, 目前没有打算做这个功能

**Comment by fishg** [comment]
目前如果dns不走clash，似乎按域名分流规则无法工作，这种情况下看连接信息都是ip，没有ip与域名的对应关系。

**Comment by Dreamacro** [comment]
对于透明代理来说这是必然的，即使是非侵入式的 hijack 也是需要走 clash 内部的 dns 的，不然的话软件哪来的域名和 ip 的映射关系。

**Comment by fishg** [comment]
是否可以考虑类似 xray sniffing的嗅探的方式获得对应关系？

**Comment by Dreamacro** [comment]
你仔细想想,sniff 了又和现在的 hijack 有什么区别呢

**Comment by fishg** [comment]
如果是终端运行hijack倒是没什么差别，但是如果是中转服务器只提供s5接入，中转服务器hijack就没法工作了吧

**Comment by Dreamacro** [comment]
s5 是 socks5 吗？socks5 可以直接带域名请求，不存在需要 hijack dns 的问题

**Comment by fishg** [comment]
> s5 是 socks5 吗？socks5 可以直接带域名请求，不存在需要 hijack dns 的问题

是只socks5。也对啊，正常s5 应该代理前不解析的。我用的有点复杂，客户端 vmess-> 中转机(v2ray->s5->clash->规则分流)，看起来v2在转s5 outbounds 时已经是解析过了，跟浏览器直接走s5有些不太一样

**Comment by Dreamacro** [comment]
这我觉得不合理，socks5 的 outbound 不应该把域名部分消除了的，我猜是因为你用的客户端目前不支持类似 fakeip 或者域名映射的东西，导致你客户端也只能拿到 ip。这个就不是 clash 的问题了

**Comment by escape0707** [comment]
我刚刚在这里https://github.com/Dreamacro/clash/issues/1554提到一个同样的问题。我想还是用中文也叙述一遍。

我在自己的机器上跑clash和tproxy，同时还需要放行qbittorrent。我目前是把clash和qbit都放到一个专门放行的cgroup里。但是整个系统的dns还是用的clash的（clash用的路由器的）。这种情况下如果不能在netfilter中控制放行的cgroup的dns请求，则放行组仍然使用clash dns。如此一来我不知道该如何设置fake-ip了。如果是按照v2ray的做法，我可以按照不改动系统dns，只将需要代理的进程的dns请求捕获，放行有特殊需求的cgroup中的进程。

**Comment by nobody-99** [comment]
> 这个说明看起来像是 MITM 而不是读取 sni，读取 DoT 的 sni 只能拿到 DoT 的域名, 并不能拿到对这个 dns server 请求的内容。
> 
> 对于 MITM, 目前没有打算做这个功能

楼主的意思应该是读取https链接的SNI来进行分流

不用fake-ip 又能在透明代理中正确分流域名
