### ISSUE TITLE
[Feature]请求增加profile缓存文件.cache自定义路径的设置项

### ISSUE THREAD

**Issue by testiknn** [Dreamacro/clash#1241]
clash 1.4.0 版终于可以自动保存select状态。但只支持存放在$HOME/.cache，由于我是/tmp/clash/里运行clash，clash启动后生成的.cache文件是保存在了/tmp/clash/.cache，这样重启就没了。
请求增加可自定义保存路径的设置项功能。

**Comment by Dreamacro** [comment]
你可以设置 HOME 目录的位置到非 /tmp 下，./clash -d /path
