### ISSUE TITLE
[Bug] cache文件读取不了

### ISSUE THREAD

**Issue by JingxinLee** [Dreamacro/clash#1243]
WARN[0000] [CacheFile] read cache /home/ljx/.config/clash/.cache failed: gob: unknown type id or corrupted data 
文件读取失败导致无法保存上次的选择。

**Comment by Dreamacro** [comment]
`rm /home/ljx/.config/clash/.cache`

**Comment by JingxinLee** [comment]
> `rm /home/ljx/.config/clash/.cache`

不管用啊，删除了之后再选择节点，还是会自动创建 .cache， 打开面板还是选择之前的节点，没有保留上次的节点选择。

**Comment by JingxinLee** [comment]
感觉应该是我在Ubuntu下面自己创建的clash.desktop没root启动

**Comment by Dreamacro** [comment]
把你的 cache 文件传上来看看？

**Comment by JingxinLee** [comment]
[.cache.zip](https://github.com/Dreamacro/clash/files/6015228/default.cache.zip)

**Comment by JingxinLee** [comment]
> 把你的 cache 文件传上来看看？

用zip上传了，直接传传不了

**Comment by Jkkoi** [comment]
![IMG_20210220_230852_512.jpg](https://user-images.githubusercontent.com/39653010/108600178-a2ffd880-73d0-11eb-92cb-cb449a27a999.jpg)
文件前面有这一坨就可以自动恢复
多次切换节点会导致这一坨消失
（我测试是两到三次）

**Comment by wwqgtxx** [comment]
这个问题我也遇到过，表现和 @Jkkoi 的情况一致，多切换几次就会导致文件头消失

**Comment by Dreamacro** [comment]
fixed in 65ecbbc
