### ISSUE TITLE
1.4.1 Premium, TUN模式, gvisor 运行报错

### ISSUE THREAD

**Issue by leeaash** [Dreamacro/clash#1248]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 4088
redir-port: 4018
allow-lan: true
mode: Rule
log-level: silent
external-controller: '0.0.0.0:6170'
secret: ''
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  enhanced-mode: redir-host
  default-nameserver:
    - 114.114.114.114
  fallback: 
    - tcp://1.1.1.1:53
    - tls://1.1.1.1:853
    - tcp://1.0.0.1:53 
    - tls://1.0.0.1:853
  nameserver:
    - 172.x.x.x

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 114.114.114.114:53
```

</details>

### Clash log

```
Feb 22 01:42:11 raspberrypi systemd[1]: Started Clash Service.
Feb 22 01:42:11 raspberrypi clash[3852]: panic: unaligned 64-bit atomic operation
Feb 22 01:42:11 raspberrypi clash[3852]: goroutine 43 [running]:
Feb 22 01:42:11 raspberrypi clash[3852]: runtime/internal/atomic.panicUnaligned()
Feb 22 01:42:11 raspberrypi clash[3852]: #011runtime/internal/atomic/unaligned.go:8 +0x24
Feb 22 01:42:11 raspberrypi clash[3852]: runtime/internal/atomic.Store64(0x255d3cc, 0x100000, 0x0)
Feb 22 01:42:11 raspberrypi clash[3852]: #011runtime/internal/atomic/asm_arm.s:278 +0x14
Feb 22 01:42:11 raspberrypi clash[3852]: gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetSendBufferSize(0x255d360, 0x100000, 0x0, 0x42924400)
Feb 22 01:42:11 raspberrypi clash[3852]: #011gvisor.dev/gvisor@v0.0.0-20210128144215-8226803c1070/pkg/tcpip/socketops.go:605 +0x60
Feb 22 01:42:11 raspberrypi clash[3852]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.newEndpoint(0x257a600, 0x800, 0x24fe880, 0x4)
Feb 22 01:42:11 raspberrypi clash[3852]: #011gvisor.dev/gvisor@v0.0.0-20210128144215-8226803c1070/pkg/tcpip/transport/tcp/endpoint.go:886 +0x1d4
Feb 22 01:42:11 raspberrypi clash[3852]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).createConnectingEndpoint(0x256e180, 0x2555400, 0x12cbc775, 0xa8f65bdd, 0x2bcbf84, 0x24fe880, 0x1290a62b, 0x12cbc775)
Feb 22 01:42:11 raspberrypi clash[3852]: #011gvisor.dev/gvisor@v0.0.0-20210128144215-8226803c1070/pkg/tcpip/transport/tcp/accept.go:214 +0xa4
Feb 22 01:42:11 raspberrypi clash[3852]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).startHandshake(0x256e180, 0x2555400, 0x2bcbf84, 0x24fe880, 0x0, 0x0, 0x0, 0x0)
Feb 22 01:42:11 raspberrypi clash[3852]: #011gvisor.dev/gvisor@v0.0.0-20210128144215-8226803c1070/pkg/tcpip/transport/tcp/accept.go:249 +0x84
Feb 22 01:42:11 raspberrypi clash[3852]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).performHandshake(0x256e180, 0x2555400, 0x2bcbf84, 0x24fe880, 0x0, 0x0, 0x76f142e0, 0x20)
Feb 22 01:42:11 raspberrypi clash[3852]: #011gvisor.dev/gvisor@v0.0.0-20210128144215-8226803c1070/pkg/tcpip/transport/tcp/accept.go:317 +0x48
Feb 22 01:42:11 raspberrypi clash[3852]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0x2b84060, 0x24fe880, 0x0, 0x0, 0x0)
Feb 22 01:42:11 raspberrypi clash[3852]: #011gvisor.dev/gvisor@v0.0.0-20210128144215-8226803c1070/pkg/tcpip/transport/tcp/forwarder.go:155 +0xe8
Feb 22 01:42:11 raspberrypi clash[3852]: github.com/Dreamacro/clash/proxy/stack/gvisor.(*Gvisor).Start.func1(0x2b84060)
Feb 22 01:42:11 raspberrypi clash[3852]: #011github.com/Dreamacro/clash/proxy/stack/gvisor/gvisor.go:163 +0x38
Feb 22 01:42:11 raspberrypi clash[3852]: created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
Feb 22 01:42:11 raspberrypi clash[3852]: #011gvisor.dev/gvisor@v0.0.0-20210128144215-8226803c1070/pkg/tcpip/transport/tcp/forwarder.go:94 +0x204
Feb 22 01:42:11 raspberrypi systemd[1]: clash.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 22 01:42:11 raspberrypi systemd[1]: clash.service: Failed with result 'exit-code'.
Feb 22 01:42:11 raspberrypi systemd[1]: clash.service: Service RestartSec=100ms expired, scheduling restart.
Feb 22 01:42:11 raspberrypi systemd[1]: clash.service: Scheduled restart job, restart counter is at 8.
Feb 22 01:42:11 raspberrypi systemd[1]: Stopped Clash Service.
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Raspbian GNU/Linux
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

system模式可以正常工作

**Comment by psikent** [comment]
同样的错误……是不是386的包打错了

**Comment by Dreamacro** [comment]
32bit 其实原生是不支持的，所以用了一个 fork 的版本去做 patch。可能因为更新了 gvisor 的版本，之前的 patch 需要做改动但编译没有报错。

**Comment by xjasonlyu** [comment]
是，gVisor在之后的版本有不止一个地方用了64位的atomic操作。

**Comment by Dreamacro** [comment]
@xjasonlyu 但是老的版本会有奇怪的 panic ，才尝试升级的

**Comment by xjasonlyu** [comment]
@Dreamacro premium版本没开源所以怎么实现的不清楚🤔，我在自己的[tun2socks](https://github.com/xjasonlyu/tun2socks)里是尽量用最新版gVisor的，后面的稳定性我自己用下来没啥问题。gVisor更新得比较快问题修复的也快，而且后面的一些Endpoint之类的API也有变动。

**Comment by Dreamacro** [comment]
目前借用了 https://github.com/comzyh/gvisor/tree/clash-premium 这个分支

**Comment by xjasonlyu** [comment]
那用到atomic 64bit操作的地方挺多的，感觉每个地方都魔改成xAddr会不会不太优雅😐。。话说uber/atomic的库也能在32bit上用，他为啥不专门对32bit的arch做单独的处理防止出问题。

**Comment by Dreamacro** [comment]
你目前兼容 32bit 的 patch 是什么样的

**Comment by xjasonlyu** [comment]
> 你目前兼容 32bit 的 patch 是什么样的

没有兼容，只是能编译通过而已🌚。gVisor官方的32bit支持都咕咕咕那么久了🤷‍♂️。

**Comment by xjasonlyu** [comment]
@leeaash 你直接装个64位的raspbian就OK了。

**Comment by leeaash** [comment]
> @leeaash 你直接装个64位的raspbian就OK了。

armv7l的只有32位的吧，不过system模式可以用

**Comment by xjasonlyu** [comment]
@leeaash 你是第几代raspberry pi啊，3B之后都支持64位

**Comment by leeaash** [comment]
> @leeaash 你是第几代raspberry pi啊，3B之后都支持64位

3B, 貌似可以装64位的OS.

**Comment by xjasonlyu** [comment]
@Dreamacro 看看这个 https://github.com/golang/go/issues/11891#issuecomment-433623786 ，把64位的变量移到结构体顶部就可以由编译器保证64位对齐，但我没有去验证过。

**Comment by comzyh** [comment]
> > 你目前兼容 32bit 的 patch 是什么样的
> 
> 没有兼容，只是能编译通过而已🌚。gVisor官方的32bit支持都咕咕咕那么久了🤷‍♂️。

咕咕了很久了，估计他们在等这个 https://github.com/golang/go/issues/599

**Comment by xjasonlyu** [comment]
> 你目前兼容 32bit 的 patch 是什么样的

https://github.com/xjasonlyu/gvisor/commit/27a6751e19c2a40c61d77997fd397132af0a8e6c

实际测试是可行的，那个counter结构体其实不需要修改，count字段已经是对齐的了。解决32位下内存不对齐可以直接把需要原子操作的变量移到结构体顶部，或者手动用`_ [4]byte`对齐就好了，这可能是目前较可行的patch。 @Dreamacro

**Comment by comzyh** [comment]
> > 你目前兼容 32bit 的 patch 是什么样的
> 
> [xjasonlyu/gvisor@27a6751](https://github.com/xjasonlyu/gvisor/commit/27a6751e19c2a40c61d77997fd397132af0a8e6c)
> 
> 实际测试是可行的，那个counter结构体其实不需要修改，count字段已经是对齐的了。解决32位下内存不对齐可以直接把需要原子操作的变量移到结构体顶部，或者手动用`_ [4]byte`对齐就好了，这可能是目前较可行的patch。 @Dreamacro

Golang 只保证结构体创建的时候以8字节对齐，但不保证结构体内的子结构体以8字节对齐。考虑到`SocketOptions`是`endpoint`的子结构 （https://github.com/google/gvisor/blob/05c2d6c038777818932d3991c0de9cfa2a7bea51/pkg/tcpip/transport/tcp/endpoint.go#L690），只要endpoint中结构变动了，那么这个patch的8字节对齐就不能保证了。
当然，对于特定的版本，经过测试，那么这个patch对这个固定的版本是有效的。但是这个patch本质上和在变量前面加4字节的padding没有区别，如果上游更新了相关结构体，那么这个patch需要重新测试才可以应用在新的版本上。

**Comment by xjasonlyu** [comment]
https://github.com/google/gvisor/commit/b1d57877264c2b94e3024375efc9914881f0bbe8

现在终于至少官方支持编译32位的了🙉

**Comment by Dreamacro** [comment]
@xjasonlyu 那能正常用么

**Comment by xjasonlyu** [comment]
官方只是能让netstack “buildable”，想让32位下能正常运行的话，里面需要原子操作的变量还是要对齐先的。

~~魔改一下，把atomic包都换成uber的就行了🌚，保证能正常用~~

**Comment by Dreamacro** [comment]
~~有没有 PATCH 我可以 cherry-pick 来直接用？~~

**Comment by xjasonlyu** [comment]
正打算明天改来着

**Comment by comzyh** [comment]
> 正打算明天改来着
+Watch 😄

**Comment by xjasonlyu** [comment]
https://github.com/xjasonlyu/gvisor/commit/eb40de9b30e3d48e4905c637a54a4024eb568fd5

gvisor的tcpip里包只有`sendBufferSize`变量可能会导致panic，所以把结构体对齐就行了，我编译后在32bit系统下测试正常运行没有报错。

**Comment by comzyh** [comment]
https://github.com/google/gvisor/pull/5694
等这个进去吧

**Comment by xjasonlyu** [comment]
> [google/gvisor#5694](https://github.com/google/gvisor/pull/5694)
> 等这个进去吧

合并进去了

**Comment by Dreamacro** [comment]
应该 fix 了
