### ISSUE TITLE
When is support for UDP planned?

### ISSUE THREAD

**Issue by OneHappyForever** [Dreamacro/clash#125]
Hello,

Looking forward to UDP support and system wide traffic capture interface (even if the app doesn’t support system proxy settings).

Are they planned, and when do you think they’ll be completed?

No pressure!

**Comment by Dreamacro** [comment]
As for UDP or other features, It's not that the difficulty of code implementation, but integrate the new feature into the existing system.

Not all nodes support UDP. when a `Proxy Group` has many nodes but only partial support UDP, the situation becomes complicated: If match a proxy which UDP unsupported, the connection should close? Should each `Proxy Group` have a UDP nodes queue? There are many things worth discussing and think about.

**Comment by OneHappyForever** [comment]
Potential solutions: 
- Have the option to enable and disable UDP (maybe a tick box next to the connect button)
- Be able to choose which server to use for UDP (like quantumult for iOS), and option to not enable

Just some ideas, I don’t know how realistic they are

**Comment by Dreamacro** [comment]
The Socks5 UDP was pushed on `dev` branch. Now support direct and shadowsocks
