### ISSUE TITLE
[Bug] 使用 Cisco AnyConnect VPN 导致 Clash 找不到 host 或路由错误

### ISSUE THREAD

**Issue by techial1042** [Dreamacro/clash#1252]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 1080
allow-lan: true
mode: Rule
log-level: info
```

没有配置 DNS 和 TUN。

</details>

### Clash log

```
22/02/2021, 20:16:31.393  [warning] [TCP] dial DIRECT (match RuleSet/lancidr) to 0.96.150.136 error: dial tcp4 0.96.150.136:443: connect: no route to host
22/02/2021, 20:08:55.649  [debug] trafficWebSocket did disconnect
22/02/2021, 20:08:57.651  [error] The operation couldn’t be completed. Can't assign requested address
22/02/2021, 20:08:57.651  [debug] trafficWebSocket did disconnect
22/02/2021, 20:09:18.139  [error] The operation couldn’t be completed. Can't assign requested address
22/02/2021, 20:09:18.139  [debug] trafficWebSocket did disconnect
22/02/2021, 20:09:21.910  [info] ClashX quit need clean proxy setting
22/02/2021, 20:09:21.910  [debug] disableProxy
22/02/2021, 20:09:21.912  [info] ClashX quit wait for clean up
22/02/2021, 20:09:21.971  [info] ClashX quit after clean up finish
22/02/2021, 20:09:22.189  [info] ClashX will terminate
22/02/2021, 20:09:25.870  [info] applicationWillFinishLaunching
22/02/2021, 20:09:25.910  [info] applicationDidFinishLaunching
22/02/2021, 20:09:25.910  [info] Appversion: 1.40.0.1 1.40.0.1
22/02/2021, 20:09:25.933  [info] postFinishLaunching
22/02/2021, 20:09:25.991  [debug] checkInstall
22/02/2021, 20:09:25.994  [info] initClashCore
22/02/2021, 20:09:25.994  [info] initClashCore finish
22/02/2021, 20:09:25.998  [info] Trying start proxy
22/02/2021, 20:09:25.999  [info] Start proxy done
22/02/2021, 20:09:26.002  [info] set up autoUpateTimer
22/02/2021, 20:09:26.002  [info] Tigger config auto update check
22/02/2021, 20:09:26.009  [debug] helper version 2.3 require version 2.3
22/02/2021, 20:09:26.009  [info] check helper using time: 0.01663804054260254
22/02/2021, 20:09:26.043  [info] Saving Remote Config Setting
22/02/2021, 20:09:26.043  [error] enableProxy fail: 0 0
22/02/2021, 20:09:26.402  [info] port config updated,new: 1080,1080
22/02/2021, 20:09:26.402  [debug] enableProxy
22/02/2021, 20:09:26.410  [error] The operation couldn’t be completed. Can't assign requested address
22/02/2021, 20:09:26.410  [error] The operation couldn’t be completed. Can't assign requested address
22/02/2021, 20:09:26.410  [debug] loggingWebSocket did disconnect
22/02/2021, 20:09:26.410  [debug] trafficWebSocket did disconnect
22/02/2021, 20:09:27.412  [error] The operation couldn’t be completed. Can't assign requested address
22/02/2021, 20:09:27.412  [debug] trafficWebSocket did disconnect
22/02/2021, 20:09:29.414  [error] The operation couldn’t be completed. Can't assign requested address
22/02/2021, 20:09:29.414  [debug] trafficWebSocket did disconnect
22/02/2021, 20:09:31.040  [info] start crash logger
22/02/2021, 20:09:33.416  [error] The operation couldn’t be completed. Can't assign requested address
22/02/2021, 20:09:33.416  [debug] trafficWebSocket did disconnect
22/02/2021, 20:09:43.909  [info] ClashX quit need clean proxy setting
22/02/2021, 20:09:43.909  [debug] disableProxy
22/02/2021, 20:09:43.910  [info] ClashX quit wait for clean up
22/02/2021, 20:09:43.958  [info] ClashX quit after clean up finish
22/02/2021, 20:09:44.174  [info] ClashX will terminate
22/02/2021, 20:09:46.918  [info] applicationWillFinishLaunching
22/02/2021, 20:09:46.953  [info] applicationDidFinishLaunching
22/02/2021, 20:09:46.953  [info] Appversion: 1.40.0.1 1.40.0.1
22/02/2021, 20:09:46.976  [info] postFinishLaunching
22/02/2021, 20:09:47.029  [debug] checkInstall
22/02/2021, 20:09:47.033  [info] initClashCore
22/02/2021, 20:09:47.033  [info] initClashCore finish
22/02/2021, 20:09:47.036  [info] Trying start proxy
22/02/2021, 20:09:47.038  [info] Start proxy done
22/02/2021, 20:09:47.040  [info] set up autoUpateTimer
22/02/2021, 20:09:47.041  [info] Tigger config auto update check


```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

当我使用 Cisco AnyConnect VPN 连接时，Clash 代理其他请求时候会出现 network error

但我关闭 VPN 后，并且使用命令 flush （`sudo route -n flush`）路由表后，重启 Clash 就正常了。

如果我在 VPN 连接过程中，flush 路由表，确实可以让 clash 正常工作，可以正常代理，但这就影响到了 VPN 的正常工作。

个人猜想是因为路由表修改导致 clash 无法正常运行。

### 重现问题的具体布骤 Steps to Reproduce

1. 
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by Dreamacro** [comment]
会不会冲突和 VPN 的实现方式有关系。比如 tailscale 也是一个类 vpn 程序，但只写入一个较为精细的路由表，这个时候 clash 和 tailscale 完全不冲突。

而某些 vpn 需要单独设置一个 dns 来正常解析内部域名，会复写系统设置。同时可能会写入范围较大的路由表，这个时候 clash 的增强模式就会和 vpn 冲突。

解决方法就是：暂时关闭增强模式，或者针对你的 vpn 做相应的设置

**Comment by techial1042** [comment]
@Dreamacro  hi，感谢回复。

我在 macOS 使用的是 ClashX Pro 客户端，我测试一下关闭增强模式，看看是否还会影响。

若还是会冲突，需要如何解决呢？

关于 VPN，VPN 只能设置 Use System Proxy，除此之外没有其他的可设置项目了。

**Comment by Dreamacro** [comment]
这取决于你 VPN 的工作方式，可能需要有相关工具的经验（查看路由表添加情况、系统代理是否被修改、系统 dns 是否被修改）

**Comment by clockcloud** [comment]
遇到了类似的问题，我的解决方案，供参考：

改用 OpenConnect  连接 VPN，通过 --script-tun 选项配合 ocproxy 或 tunsocks 将 vpn 转换为 http 或者 socks5 代理，将代理作为节点加入 clash，添加规则分流
由于工作环境是 win10 + WSL2，为了方便就直接把 OpenConnect 放在了 WSL 里，理论上都在一个系统里应该也没啥问题

https://www.infradead.org/openconnect/nonroot.html

还发现了 kubectl 部分命令不支持 socks5 代理，只好自己编译 tunsocks 用 http 代理

**Comment by SimonGhost** [comment]
遇到了类似的问题，开启TUN后，公司内网网址，邮箱服务器，公司给电脑安装的电脑使用记录监控上报等等地址都无法访问，后来把内部的dns和wins服务器地址加上就好了。

**Comment by BirkhoffLee** [comment]
> 遇到了类似的问题，我的解决方案，供参考：
> 
> 改用 OpenConnect 连接 VPN，通过 --script-tun 选项配合 ocproxy 或 tunsocks 将 vpn 转换为 http 或者 socks5 代理，将代理作为节点加入 clash，添加规则分流 由于工作环境是 win10 + WSL2，为了方便就直接把 OpenConnect 放在了 WSL 里，理论上都在一个系统里应该也没啥问题
> 
> https://www.infradead.org/openconnect/nonroot.html
> 
> 还发现了 kubectl 部分命令不支持 socks5 代理，只好自己编译 tunsocks 用 http 代理

我剛剛試了一下，我的 VPN 是支持 UDP 的，但是使用 tunsocks 之後無法透過 SOCKS5 proxy 轉發 udp packet，你有遇到類似的問題嗎？

**Comment by BirkhoffLee** [comment]
Just added my solution to this in the wiki.

https://github.com/Dreamacro/clash/wiki/Examples#use-with-openconnect

Both ocproxy and tunsocks use lightweight networking stack, there could be significant performance loss. In addition I found out that UDP does not work (OpenConnect <- ocproxy/tunsocks <- Clash).

You actually only need to stop OpenConnect from modifying the default routes, then alter the route rules for a bit to make packets actually flow through the interfaces and use `interface-name` to specify an outbound interface.

**Comment by tgut** [comment]
我把clash设置为直接链接模式，暂时解决问题
