### ISSUE TITLE
更新之后无法下载配置文件，重装过，网络正常

### ISSUE THREAD

**Issue by midezhanghao** [Dreamacro/clash#1256]
网络正常，clash提示更新之后就用不了了，无法下载配置文件，

![1](https://user-images.githubusercontent.com/76832486/109017176-e7051d00-76f1-11eb-9474-c03051c43818.png)
![2](https://user-images.githubusercontent.com/76832486/109017182-e8364a00-76f1-11eb-86fd-e2e726264955.png)
![3](https://user-images.githubusercontent.com/76832486/109017184-e8cee080-76f1-11eb-8c4e-6560bb043a30.png)
![4](https://user-images.githubusercontent.com/76832486/109017187-e9677700-76f1-11eb-82f6-7f00d3381c7e.png)
![5](https://user-images.githubusercontent.com/76832486/109017192-ea000d80-76f1-11eb-95fe-e1d66c3828e2.png)

**Comment by midezhanghao** [comment]
但是在其他电脑（以前没装过的）上安装最新版本就可以，General 界面都不一样

**Comment by techblack** [comment]
1.这个是Clash-Core的仓库
2.CFW最新版是14.6，你这是6.1差了一个世纪了。

**Comment by midezhanghao** [comment]
> 1.这个是冲突-核心的仓库，你反馈错地方了，你应该去cfw去反馈
> 2.CFW最新版是14.6，你这是6.1差了一个世纪了。

1,感谢回复
2，那么请问cfw在哪里，我在上面这个软件里面显示的就是这个版本，然后里面链接到的就是这里，不好意思，麻烦了

**Comment by techblack** [comment]
> > 1.这个是冲突-核心的仓库，你反馈错地方了，你应该去cfw去反馈
> > 2.CFW最新版是14.6，你这是6.1差了一个世纪了。
> 
> 1,感谢回复
> 2，那么请问cfw在哪里，我在上面这个软件里面显示的就是这个版本，然后里面链接到的就是这里，不好意思，麻烦了

https://github.com/Fndroid/clash_for_windows_pkg

**Comment by muyihao** [comment]
请问大佬ubuntu上这个怎么安装啊，我直接下载到release的执行文件，但是那样不行～，可以跟我说下安装顺序吗，被自己菜哭了
