### ISSUE TITLE
[Bug]频繁查询节点域名AAAA解析

### ISSUE THREAD

**Issue by tudnew** [Dreamacro/clash#1262]
版本：v1.4.1
平台：Windows 20H2
![2021-02-27_22-12-23](https://user-images.githubusercontent.com/50667472/109390044-5117ff00-794a-11eb-96cc-44418cbf7dfe.png)

节点没有IPv6地址，也能正常使用，但就是频繁查询域名，一天下来查询几千次......

**Comment by LinEvil** [comment]
环境 Win10 20H2，网卡有分配 ipv6 地址，可以复现。
几乎每次 clash 建立新连接，都会向 DNS 服务器请求一次节点域名的 AAAA 结果，
配置文件中的 ipv6 与 dns:ipv6 选项不影响此问题。
![image](https://user-images.githubusercontent.com/13027656/112546162-0deb6780-8df4-11eb-8eaf-87458a9bfb5d.png)

**Comment by Dreamacro** [comment]
@tudnew 开启了 clash 的 dns 功能吗

**Comment by tudnew** [comment]
@Dreamacro 没有启动clash内置dns

**Comment by Dreamacro** [comment]
@tudnew 启动了 clash 的内置 dns 功能的话，就会有缓存，否则的话走的是 go 自己的解析流程。

@LinEvil 只要开启了 ipv6 功能，肯定会去查询域名的 AAAA 记录的，但是会有一定时间的缓存，时间过后才会再次请求解析 AAAA 记录

**Comment by LinEvil** [comment]
@Dreamacro 我没有开启 ipv6 功能

**Comment by Dreamacro** [comment]
@LinEvil 把 dns 配置发出来

**Comment by tudnew** [comment]
> @tudnew 启动了 clash 的内置 dns 功能的话，就会有缓存，否则的话走的是 go 自己的解析流程。
> 
> @LinEvil 只要开启了 ipv6 功能，肯定会去查询域名的 AAAA 记录的，但是会有一定时间的缓存，时间过后才会再次请求解析 AAAA 记录

这个是否可以加个选项，需要的情况下关闭它频繁查询结果，只要能连接远程IP就一直用这个IP，节点查询太多怕容易引起不必要的注意。

**Comment by Dreamacro** [comment]
@tudnew 不开启 clash 的 dns 选项无法控制 go 的 dns 行为（也没必要控制）

**Comment by LinEvil** [comment]
> @LinEvil 把 dns 配置发出来

`ipv6: false
dns:
    enable: false
    ipv6: false`

系统 dns 是交给 adguard 控制的，使用私有 DoH 服务器。

**Comment by Dreamacro** [comment]
@LinEvil  你 dig 一下节点域名的 AAAA 记录，发上来，域名可以脱敏

**Comment by tudnew** [comment]
> > @LinEvil 把 dns 配置发出来
> 
> ipv6: false
> dns:
> enable: false
> ipv6: false
> 
> 系统 dns 是交给 adguard 控制的，使用私有 DoH 服务器。

dns:
  enable: false
这个是禁用内置DNS吧，我也是这样设置的。。。

**Comment by LinEvil** [comment]
对，我没有使用 clash 的 dns 功能。

**Comment by Dreamacro** [comment]
那没啥问题吧，毕竟 adguard 也有一层缓存，不影响使用的

**Comment by LinEvil** [comment]
> @tudnew 不开启 clash 的 dns 选项而使用默认行为的情况下，无法控制 go 的 dns 行为（也没必要控制）

也就是说这是 go 的问题？

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/blob/6c83ff3496542f12297eb971a611d3d3aea90297/component/resolver/resolver.go#L93

golang 里没有方法可以让这个方法拥有缓存，`ResolveIPv6` 这个方法从逻辑上来说不应该有自己的缓存。再加上系统的 dns 或者第三方 dns server 都会有缓存功能，我觉得这个不算是一个问题

**Comment by Dreamacro** [comment]
不过确实可以解决在不开 ipv6 选项的时候不去查询 AAAA 记录，我加一下

**Comment by Dreamacro** [comment]
@LinEvil 4ad9761b32708b966321c95bc58279303e11a9cf 现在在关闭 ipv6 并且使用系统 dns 的情况下，应该不会在请求 AAAA 记录了

**Comment by LinEvil** [comment]
dev 测试有效，等一个 premium release
