### ISSUE TITLE
[Feature]能不能让 fallback DNS通过代理节点连接？

### ISSUE THREAD

**Issue by tudnew** [Dreamacro/clash#1264]
看了很久配置说明，没发现可以用代理节点连接DNS服务器解析，从实验上也发现是通过本地网络直接请求解析。
连接国外那些DNS丢包率和延迟实在太高了，有时候解析延迟能到几秒.....

**Comment by xdays** [comment]
同求，最近DNS[老出问题](https://www.solidot.org/story?sid=67104)

**Comment by HouCoder** [comment]
现在我的方案是用 overture 来让 dns 走代理，然后 clash 用 overture 的代理。https://github.com/shawn1m/overture

**Comment by tudnew** [comment]
> 现在我的方案是用overture来让dns走代理，然后clash用overture的dns。https [://github.com/shawn1m/overture](https://github.com/shawn1m/overture)

确实不错，查询流畅多了。

**Comment by Sentsuki** [comment]
GFW是把所有的海外 DOH / DOT 都墙了吗，这几天 Clash 疯狂报 all dns requests failed，不设置大陆DNS根本没法上网

**Comment by tudnew** [comment]
> GFW是把所有的海外 DOH / DOT 都墙了吗，这几天 Clash 疯狂报 all dns requests failed，不设置大陆 DNS 根本没法上网

应该还有部分幸存的。 https://kb.adguard.com/general/dns-providers

**Comment by Sentsuki** [comment]
> > GFW是把所有的海外 DOH / DOT 都墙了吗，这几天 Clash 疯狂报 all dns requests failed，不设置大陆 DNS 根本没法上网
> 
> 应该还有部分幸存的。 https://kb.adguard.com/general/dns-providers

[情况不容乐观](https://www.v2ex.com/t/759435)

**Comment by tudnew** [comment]
那也没办法，DOT DOH都有致命的特征缺陷。

**Comment by Dreamacro** [comment]
我理解正确的做法应该是让 clash 拿到正确的域名而不是通过代理走 dns 请求。

* 如果你使用系统代理（HTTP/Socks5）, 不要使用任何慢的 dns server，利用规则或 GEOIP，clash 会把域名发到代理上
* 如果你是用 TUN 之类的，打开 redir-host 或 fakeip，让 clash 能拿到域名信息，其他同上

**Comment by kurdsvv** [comment]
DoH 直连被gfw阻断,超时

**Comment by BraveSail** [comment]
> 我理解正确的做法应该是让 clash 拿到正确的域名而不是通过代理走 dns 请求。
> 
> * 如果你使用系统代理（HTTP/Socks5）, 不要使用任何慢的 dns server，利用规则或 GEOIP，clash 会把域名发到代理上
> * 如果你是用 TUN 之类的，打开 redir-host 或 fakeip，让 clash 能拿到域名信息，其他同上

这样客户端似乎无法获取到正确的ip了，假如要让客户端能获取到正确IP（有这个需求），只能通过fallback了吧？

**Comment by phlinhng** [comment]
> > 我理解正确的做法应该是让 clash 拿到正确的域名而不是通过代理走 dns 请求。
> > 
> > * 如果你使用系统代理（HTTP/Socks5）, 不要使用任何慢的 dns server，利用规则或 GEOIP，clash 会把域名发到代理上
> > * 如果你是用 TUN 之类的，打开 redir-host 或 fakeip，让 clash 能拿到域名信息，其他同上
> 
> 这样客户端似乎无法获取到正确的ip了，假如要让客户端能获取到正确IP（有这个需求），只能通过fallback了吧？

现在有 fake-ip-filter

**Comment by salzburgrujvnun** [comment]
> 现在我的方案是用 overture 来让 dns 走代理，然后 clash 用 overture 的 dns。https://github.com/shawn1m/overture

看说明只能通过 SOCKS5 代理（仅限 TCP），无法支持trojan， vmess。

**Comment by XuuKoo** [comment]
> 现在我的方案是用 overture 来让 dns 走代理，然后 clash 用 overture 的 dns。https://github.com/shawn1m/overture

可以分享一下clash、overture的配置嘛。
