### ISSUE TITLE
[Bug] 透明代理时添加 "IP-CIDR6,::ffff:0:0/96,DIRECT,no-resolve" 规则会匹配到 "0.0.0.0/0"

### ISSUE THREAD

**Issue by Limgmk** [Dreamacro/clash#1265]
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 我已经使用 dev 分支版本测试过，问题依旧存在
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

### Clash config
<summary>config.yaml</summary>

```yaml
rules:
  - IP-CIDR6,::ffff:0:0/96,DIRECT,no-resolve
```

### Clash log

```
WARN[0016] [TCP] dial DIRECT (match IPCIDR/0.0.0.0/0) to 91.108.56.183 error: dial tcp4 91.108.56.183:80: i/o timeout
WARN[0017] [TCP] dial DIRECT (match IPCIDR/0.0.0.0/0) to 91.108.56.196 error: dial tcp4 91.108.56.196:443: i/o timeout
WARN[0017] [TCP] dial DIRECT (match IPCIDR/0.0.0.0/0) to 91.108.56.196 error: dial tcp4 91.108.56.196:80: i/o timeout
WARN[0017] [TCP] dial DIRECT (match IPCIDR/0.0.0.0/0) to 91.108.56.183 error: dial tcp4 91.108.56.183:443: i/o timeout
WARN[0024] [TCP] dial DIRECT (match IPCIDR/0.0.0.0/0) to www.google.com error: dial tcp4 216.58.200.36:443: i/o timeout
```

### 环境 Environment

* 操作系统 Linux

### 说明 Description

***当使用 tun 或者 redir、tproxy 进行透明代理时*** :  
在配置文件中添加了上述 ipv6 规则之后，所有的流量都会匹配到 ```0.0.0.0/0``` 从而出现类似上面的错误，  
但是 ```::ffff:0:0/96``` 似乎是一个保留地址段，而且并不是一个 IPv4 地址段。
仅使用 http 或者 socks 代理时即使是相同的 rules 却没有这个问题

**Comment by Dreamacro** [comment]
golang 的 parseCIDR 会把 `::ffff:0:0/96` 变成 `0.0.0.0/0` https://play.golang.org/p/Pn1NyDpj7HU
