### ISSUE TITLE
[Bug]Clash在MacOS系统下无法读取实时流量

### ISSUE THREAD

**Issue by morckclient** [Dreamacro/clash#1272]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

`port: 10801
allow-lan: true
mode: Rule
external-controller: '127.0.0.1:59803'
secret: ''
log-level: silent`

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)

MacOS Big Sur 版本11.0.1

### 说明 Description

出现问题前已确认：
 - 设置 `external-controller` 为 `127.0.0.1:59803`
 - 59803 端口无占用
 - yaml文件无错误
 - yaml文件中设置 `secret` 的值为空，没有采用加密
 - 在Windows环境下测试正常
 
问题：
 - 开启Clash后访问 `http://127.0.0.1:59803/traffic` 即使Clash可以正常使用也无法读取实时流量
 - 读取的Json如下：
`{"up":0,"down":0}
{"up":0,"down":0}
{"up":0,"down":0}......`

**Comment by Dreamacro** [comment]
它获取的流量不是系统的流量，是流经 clash 的流量

**Comment by wp0qw** [comment]
是的，例如我访问youtube视频，它还是 {"up":0,"down":0} {"up":0,"down":0} {"up":0,"down":0}

**Comment by Dreamacro** [comment]
youtube 的流量不是持续的，是断续的，所以有缓冲的时候是 0 很正常

**Comment by wp0qw** [comment]
好的，换了台mac突然又可以了，麻烦了。
