### ISSUE TITLE
[Feature] 节点测速和切换的日志问题

### ISSUE THREAD

**Issue by ihotte** [Dreamacro/clash#1274]
目前 DEBUG 级别的 LOG 并没有包含节点测速和切换的相关日志信息，不知能否将测速和切换的信息写入调试日志？

还有就是目前节点测速不知道是不是单次测速，能否考虑多次测速取平均值计算延迟，单次延迟测速的结果和实际速度偏差貌似有点大。

**Comment by akw5454521** [comment]
多次倒没必要，主要是第一次测速会受到dns解析速度的影响，我觉得连续测两次取第二次的结果比较好
