### ISSUE TITLE
如何能让路由器自身发起的流量出海？[Bug]

### ISSUE THREAD

**Issue by matthuo333** [Dreamacro/clash#1276]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

请教大神，目前局域网中的其它设备经OP（Docker 运行的）后均可正常出海，但是OP中本身发起的流量确不行，比如OP中curl google.com， 一直未有反馈。 

一直查不出原因，请大神指点。

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by ttimasdf** [comment]
首先，这不是个bug，你发到这不会有人看，我要是开发者的话，这种off topic的问题我会直接删除。其次，OpenWrt的配置问题与 Clash Core 本身无关。最后，你根本就没看模板。。

建议阅读： [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E6%85%8E%E9%80%89%E6%8F%90%E9%97%AE%E7%9A%84%E8%AE%BA%E5%9D%9B)

**Comment by matthuo333** [comment]
> 首先，这不是个bug，你发到这不会有人看，我要是开发者的话，这种off topic的问题我会直接删除。其次，OpenWrt的配置问题与 Clash Core 本身无关。最后，你根本就没看模板。。
> 
> 
> 
> 建议阅读： [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E6%85%8E%E9%80%89%E6%8F%90%E9%97%AE%E7%9A%84%E8%AE%BA%E5%9D%9B)

发的是issue，不是bug, 谢谢你的建议。

**Comment by matthuo333** [comment]
> 首先，这不是个bug，你发到这不会有人看，我要是开发者的话，这种off topic的问题我会直接删除。其次，OpenWrt的配置问题与 Clash Core 本身无关。最后，你根本就没看模板。。
> 
> 
> 
> 建议阅读： [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E6%85%8E%E9%80%89%E6%8F%90%E9%97%AE%E7%9A%84%E8%AE%BA%E5%9D%9B)

没严格按照模版写issue，不等于没看模版，不知你以据什么认为我没看？
