### ISSUE TITLE
Standardized configuration after prerelease

### ISSUE THREAD

**Issue by Dreamacro** [Dreamacro/clash#128]
Because of problems left over from Surge, there are so many non-standard places now.

For Example:

```yml

# kebab-case but Proxy or Rule is not
log-level: info

# should be Proxies
Proxy:

# should be Rules
Rule:

```

Give your suggestions to enhance usability. BTW, the format of configuration should not be restricted to Surge.

**Comment by xuhaoyang** [comment]
I hope that use JSON to config. Program is easy to parse and verify it, but its difficult for our to write 
i think we need some GUI utils to help our generate config. Not write config by ourself.

**Comment by SukkaW** [comment]
@xuhaoyang YAML is human friendly and it is easy to convert YAML to JSON.

**Comment by freewlan** [comment]
采用小驼峰命名，应该更容易阅读，并且符合很多人的使用习惯（程序员）

如
logLevel: info

proxiesGroup:

**Comment by Dreamacro** [comment]
@xuhaoyang 

There are so many libs for yaml with mainstream language. As for GUI editor, there is a problem that has to be said: should the barrier for users be lower? clash live in the legal gray zone, I don't think it's a good thing. I prefer to let people who are willing to learn to have a good internet environment.

BTW, yaml 1.2 is fully JSON compatible, you can let your configuration in pure JSON.

**Comment by xuan880** [comment]
> 采用小驼峰命名，应该更容易阅读，并且符合很多人的使用习惯（程序员）
> 
> 如
> logLevel: info
> 
> proxiesGroup:

但是使用这个代理的人中还是普通人最多，这种方式对一般人来说并不友好。

**Comment by oocococo** [comment]
把配置容易写错的单元也加进配置的结构体里  ,     然后只要读到了需要的就忽略其他的
比如有PROXY,PROXIES,PROXYS,
读到了PROXY就忽略其他两个,没读到就继续读

**Comment by lujiajing1126** [comment]
> I hope that use JSON to config. Program is easy to parse and verify it, but its difficult for our to write
> i think we need some GUI utils to help our generate config. Not write config by ourself.

`YAML` or `TOML` should be considered, but not `JSON` of course.
The syntax of `JSON` is too redundant to write manually.

And `YAML` and `TOML` can both easily translated to `JSON`

**Comment by lujiajing1126** [comment]
> Because of problems left over from Surge, there are so many non-standard places now.
> 
> For Example:
> 
> ```yaml
> # kebab-case but Proxy or Rule is not
> log-level: info
> 
> # should be Proxies
> Proxy:
> 
> # should be Rules
> Rule:
> ```
> 
> Give your suggestions to enhance usability. BTW, the format of configuration should not be restricted to Surge.

Vote for `kebab-case`, the plural form may not be necessary.

**Comment by SukkaW** [comment]
https://github.com/Dreamacro/clash/issues/128#issuecomment-468931984

@lujiajing1126 Although `JSON` is hard to read and write, but it is easy for automated generate and parse.

So the best idea is to let Clash compatible with `JSON`, `TOML` and `YAML`.

**Comment by Dreamacro** [comment]
@SukkaW `YAML` also easy for parsing and generating, and `YAML` is more friendly than `TOML` in clash.

**Comment by soffchen** [comment]
kebab-case +1

**Comment by comzyh** [comment]
I have a question，(will) the config file designed to be editable by using clash API ？

**Comment by beyondkmp** [comment]
```yaml
Rule:
- DOMAIN-SUFFIX,google.com,auto
- DOMAIN-KEYWORD,google,auto
- DOMAIN,google.com,auto
- DOMAIN-SUFFIX,ad.com,REJECT
- IP-CIDR,127.0.0.0/8,DIRECT
- SOURCE-IP-CIDR,192.168.1.201/32,DIRECT
- GEOIP,CN,DIRECT
- DNS-FAILED, DIRECT
- MATCH,auto
```
I want to add DNS-FAILED rule, so I can use special proxy when resolving failed.

**Comment by Dreamacro** [comment]
@beyondkmp 

The `DNS-FAILED` and `FINAL` are similar. They are order independent. In my opinion, `Rule` is order related. 

Compare these two ways of configuration.

```yml
Rule:
  - DOMAIN-SUFFIX,google.com,auto
  - DNS-FAILED,DIRECT

Rule:
  - DNS-FAILED,DIRECT
  - DOMAIN-SUFFIX,google.com,auto
```

They will take the same effect. something contrary to our architecture. This is also why I renamed `FINAL` to `MATCH`.

**Comment by beyondkmp** [comment]
> @beyondkmp
> 
> The `DNS-FAILED` and `FINAL` are similar. They are order independent. In my opinion, `Rule` is order related.
> 
> Compare these two ways of configuration.
> 
> ```yaml
> Rule:
>   - DOMAIN-SUFFIX,google.com,auto
>   - DNS-FAILED,DIRECT
> 
> Rule:
>   - DNS-FAILED,DIRECT
>   - DOMAIN-SUFFIX,google.com,auto
> ```
> 
> They will take the same effect. something contrary to our architecture. This is also why I renamed `FINAL` to `MATCH`.

ok, I got it. But resolving some domains failed, I hope that these domains go directly instead of return empty error. Some old or uncommon domains always encounter this problem.

**Comment by ezksd** [comment]
clash配置和surge本来就不是完全兼容的（比如把surge配置原封不动拖过来就用）。只要有简单的示例配置和较完整的文档，我觉得改过来问题不大。

**Comment by ruisiji** [comment]
There are three cases that are widely used:

* camel case: `fooBar`
* kebab case: `foo-bar`
* snake case: `foo_bar`

I vote for camel case(`fooBar`) since this is a Golang project, Golang prefers camel case, it is better to respect the project language.

**Comment by Dreamacro** [comment]
@ruisiji This issue discusses standardized configuration. Do you mean code style?

**Comment by ruisiji** [comment]
@Dreamacro I mean config.yaml format:

```
port: 7890
socksPort: 7891
allowLan: true

proxies:
- a
- b
- c

proxyGroups:
- a
- b
- c

rules:
- a
- b
- c
```

**Comment by Dreamacro** [comment]
@ruisiji But docker, which mainstay on Golang, its docker-compose.yml use snake case (https://docs.docker.com/compose/compose-file/)

**Comment by ruisiji** [comment]
@Dreamacro Snake case is used most by python projects.

As far as I know, docker compose is a python project at the beginning, so maybe docker compose want to keep the configuration format unchanged when migrate to golang.

**Comment by nb5p** [comment]
个人认为 最外层用大写 次层用kebab case 看起来更整齐。

`proxy-provider`能不能改成下面的格式，现在配置是使用变量做key，确实不太合理。

```yaml
Proxy Provider:
  - name: provider1
    type: http
    url: https://example.com/provider1.yaml
  - name: provider2
    type: file
    path: path/to/provider2.yaml
```

**Comment by tvrcgo** [comment]
kebab-case +1

**Comment by Dreamacro** [comment]
In 1.0.0 kebab-case was fully used.
