### ISSUE TITLE
use clash premium as a service in windows

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1281]
Hi due to some bugs which clash clients have I decided to use clash core premium itself without client.
How can I make the exe file run like service? and more important I want to bring the window on screen whenever I want to see the live logs.
is there any solution for these?
thanks

**Comment by bigtan** [comment]
`nssm install Clash`

`clash.exe -d .`

**Comment by fsheidaiee** [comment]
> `nssm install Clash`
> 
> `clash.exe -d .`

can you explain more? what are these commands? how do I use them?

**Comment by bigtan** [comment]
![image](https://user-images.githubusercontent.com/5222251/110244591-5f919680-7f9a-11eb-8f83-dbc270c05c7a.png)
![image](https://user-images.githubusercontent.com/5222251/110244598-6d471c00-7f9a-11eb-8f97-c08ec0f8b56c.png)

nssm    https://nssm.cc/
wintun https://www.wintun.net/

`
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  

dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
  - 119.29.29.29
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
`

**Comment by fsheidaiee** [comment]
> ![image](https://user-images.githubusercontent.com/5222251/110244591-5f919680-7f9a-11eb-8f83-dbc270c05c7a.png)
> ![image](https://user-images.githubusercontent.com/5222251/110244598-6d471c00-7f9a-11eb-8f97-c08ec0f8b56c.png)
> 
> nssm https://nssm.cc/
> wintun https://www.wintun.net/
> country.mmdb https://github.com/alecthw/mmdb_china_ip_list
> 
> ```
> tun:
>   enable: true
>   stack: gvisor
>   dns-hijack:
>     - 198.18.0.2:53
>   macOS-auto-route: true
>   macOS-auto-detect-interface: true
>   
> 
> dns:
>   enable: true
>   listen: 0.0.0.0:53
>   nameserver:
>   - 119.29.29.29
>   - 8.8.8.8
>   enhanced-mode: fake-ip
>   fake-ip-range: 198.18.0.1/16
> ```

thanks
whats the use of this line in dns section?
  listen: 0.0.0.0:53
I didnt have this line, I saw some posts that use 1053 as port. what is its purpose?

**Comment by fsheidaiee** [comment]
and how can I see realtime logs with nssm?

**Comment by bigtan** [comment]
listen section copied from the doc   https://lancellc.gitbook.io/clash/clash-config-file/dns

**Comment by fsheidaiee** [comment]
> listen section copied from the doc https://lancellc.gitbook.io/clash/clash-config-file/dns

thanks
how can I see realtime logs with nssm?

**Comment by bigtan** [comment]
> > listen section copied from the doc https://lancellc.gitbook.io/clash/clash-config-file/dns
> 
> thanks
> how can I see realtime logs with nssm?

don't know
