### ISSUE TITLE
the use of listen line for dns in tun mode

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1283]
Hi
1. as you see here
[clash documents for tun mode](https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/setup-gvisor-in-real-ip-mode)
there is a line;
  listen: 0.0.0.0:1053
whats the use of this line in windows? in[ this document](https://docs.cfw.lbyczf.com/contents/tun.html#macos) i dont see this line.
is it necessary to put this line? what for? in which conditions I have to put this line?
2.  which port do I have to put? in the previous document I see 1053 port, in others I see 53. which port should be used in windows 10?
thanks

**Comment by luwah** [comment]
The default port is 53. 
You can set a custom port as you wish. Port 1053 is an example.

**Comment by fsheidaiee** [comment]
> The default port is 53.
> You can set a custom port as you wish. Port 1053 is an example.

ok but now in my config I don't have this line with tun mode. is it necessary to put this line? what is its benefit?

**Comment by fsheidaiee** [comment]
> If some devices (like non-rooted Android) cannot bind port 53, you can set another port.

I meant the whole line not only the port.
I don't have the below line in my config. is it necessary? what does the line do? my clash is working even without it.
listen: 0.0.0.0:1053

**Comment by luwah** [comment]
If you don't have the parameter in your config, the clash would automatically listen to port 53 by default (I think). The key in this line is the port.

**Comment by fsheidaiee** [comment]
> If you don't have the parameter in your config, the clash would automatically listen to port 53 by default (I think). The key in this line is the port.

thanks a lot
