### ISSUE TITLE
[Feature]请问对vmessAEAD的支持提上日程了吗？

### ISSUE THREAD

**Issue by ha-ku** [Dreamacro/clash#1285]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

project V的开发者们已在文档中宣部“VMessAEAD 协议已经经过同行评议并已经整合了相应的修改，VMess MD5 认证信息 的淘汰机制已经启动”。我搜索了issue发现clash似乎尚未支持AEAD，想请问对此的支持进度如何了？

**Comment by betaxab** [comment]
支持支持支持。

**Comment by Shangbaize-Daoye** [comment]
用clash的时候，服务器端error.log里一直有这种提示：
```
2021/03/23 12:48:41 [Warning]
github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding:
Critical Warning: potentially invalid user:
a non VMessAEAD connection is received.
From 2022 Jan 1st, this kind of connection will be rejected by default.
You should update or replace your client software now.
```
你们谁知道这个怎么关掉，令alterID=0对现在clash来说没用。
我尝试在v2ray那里加环境变量v2ray.vmess.aead.forced=false也不行。

**Comment by IceCodeNew** [comment]
希望能尽快支持。

**Comment by Dreamacro** [comment]
done
