### ISSUE TITLE
change home directory location in windows

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1286]
Hi
I have clash executable file and config.yaml and country.mmdb files all in a folder. but when I run clash, it creates a .config folder within my user folder in windows 10. is there a way to set the home directory where ever I want?
thanks

**Comment by isweibin** [comment]
You can use -d option set configuration directory.

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/configuration#specifying-configuration-directory

**Comment by fsheidaiee** [comment]
> https://github.com/Dreamacro/clash/wiki/configuration#specifying-configuration-directory

how can I change the exe file to run in the current directory by default?
