### ISSUE TITLE
请问下 是否有支持trojan-go多路复用功能的计划？

### ISSUE THREAD

**Issue by XuuKoo** [Dreamacro/clash#1289]
同为go语言，且相比vmess的mux不太稳定，trojan-go的smux可以日常正常使用。

**Comment by akw5454521** [comment]
支持一下，实现trojan-go应该比xray的工作量要少

**Comment by LiuTangLei** [comment]
trojan-go支持cdn加速也很舒服，可以白嫖cloudflare的cdn加速

**Comment by skill7899** [comment]
是不是还没有支持

**Comment by geeklihui** [comment]
看 wiki 的 configuration 里还没有 mux 相关选项，估计是还没支持吧...

**Comment by leic4u** [comment]
+1 请求支持
