### ISSUE TITLE
[Feature Request] 支持内置 DNS 默认监听在 fake-ip 子网 .2 地址上

### ISSUE THREAD

**Issue by laggardkernel** [Dreamacro/clash#1290]
Solved: 开启内置 DNS 但不监听任何地址，直接设置系统 DNS 192.18.0.2，通过 hijack-dns 转发到内置 DNS。

--- 

感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

------------------------------------------------------------------

### 说明 Description

```
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G103

# clash premium
❯ clash -v
Clash 2021.03.10 darwin amd64 Wed Mar 10 13:30:39 UTC 2021
```

希望能支持将 Clash premium 内置 DNS 监听地址设置在子网 `.2` 地址，如 `192.18.0.2`。以避免与系统中已存在的其他 DNS 服务冲突。

系统中可能已经存在默认的 DNS 服务监听在 `127.0.0.1` 或者 `0.0.0.0` 上。为了避免 Clash 启动时内置 DNS 监听地址与这些服务冲突，或者说为了避免 Clash 启动前需要手动关闭已经存在的 DNS 服务，建议将内置 DNS 监听的默认地址设为 `192.18.0.2` （需要配合 `fake-ip-range` 变化）

对于自身服务避免与其他 DNS 的冲突的解决方案

- system-resolved 好像是默认监听在 `127.0.0.53`
- Surge 则是采用了上面描述的监听在 fake-ip 子网 `.2` 地址

个人认为方案 2 好一点。目前 clash premium 不支持内置 DNS 监听在 fake-ip 子网段。

**Comment by Dreamacro** [comment]
可以把 `192.18.0.2` 加到 hijack dns 列表里，clashx pro 就是这么干的

**Comment by laggardkernel** [comment]
谢谢解答，`hijack-dns` `192.18.0.2` 不开监听确实可以。ClashX 增强模式应该是忽略了用户配置的 DNS `listen` 端口，强制使用了 `0.0.0.0`。直接使用 ClashX 内置 DNS 监听 `0.0.0.0` 可能还是会与系统已经存在的其它 DNS 冲突。不过后者属于 ClashX 的问题了。
