### ISSUE TITLE
[Bug]开启Merlin Clash之后，KMS激活使用的SRV记录无法解析

### ISSUE THREAD

**Issue by babylife** [Dreamacro/clash#1293]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Merlin Clash
* 网路环境或拓扑 (network conditions/topology)
NAT
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. install KMS, turn off clash
2. use nslookup query srv of below record., it will return the record
C:\Windows\system32>nslookup -type=srv _vlmcs._tcp.lan
服务器:  K3.lan
Address:  192.168.50.1

_vlmcs._tcp.lan SRV service location:
          priority       = 0
          weight         = 100
          port           = 1688
          svr hostname   = K3.lan
K3.lan  internet address = 192.168.50.1

3, turn on clash, the same query will no records return
**我预期会发生……？**

same record will return as the kms.conf should be added to dnsmasq 
**实际上发生了什么？**

no return record

**Comment by luwah** [comment]
hosts:
    K3.lan: 192.168.50.1

**Comment by babylife** [comment]
> hosts:
> 
>     'K3.lan': 192.168.50.1

A记录解析没有问题，我要解析的是srv记录
