### ISSUE TITLE
混合代理端口在哪设置，为什么每次重新启动软件都会重新生成新的端口？

### ISSUE THREAD

**Issue by Evllis** [Dreamacro/clash#1294]
![Xnip2021-03-14_13-50-11](https://user-images.githubusercontent.com/13903944/111058856-49209900-84cc-11eb-877e-3ccab6c447b8.png)

如图，这里的端口谁知道在哪设置啊，要不然每次启动软件，都会重新生成一个新的端口，又要重新其它软件的代理接口很不方便。谢谢。

**Comment by xuhuanxxx** [comment]
```
# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port，混合端口
mixed-port: 7893
```

**Comment by Evllis** [comment]
> ```
> # Port of HTTP(S) proxy server on the local end
> port: 7890
> 
> # Port of SOCKS5 proxy server on the local end
> socks-port: 7891
> 
> # Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
> redir-port: 7892
> 
> # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> # tproxy-port: 7893
> 
> # HTTP(S) and SOCKS5 server on the same port，混合端口
> mixed-port: 7893
> ```

@xuhuanxxx 谢谢你朋友，搞定了。
