### ISSUE TITLE
[Bug]rule-provider中的自动更新时间周期interval不起作用。

### ISSUE THREAD

**Issue by ben-august** [Dreamacro/clash#1295]
------------------------------------------------------------------

### Clash config

<details>
# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: false

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: warning

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: true

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `${API}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

  # Firebase Cloud Messaging
  'mtalk.google.com': 108.177.125.188
  # Google Dl
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 1.1.1.1
    - 223.5.5.5
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 1.1.1.1
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853 
    - https://223.5.5.5/dns-query
        
  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    ipcidr:
      # - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'

#
# https://github.com/Dreamacro/clash/wiki/premium-core-features
#
# tun:
#   enable: true
#   stack: system # or gvisor
#   # dns-hijack:
#   #   - 8.8.8.8:53
#   #   - tcp://8.8.8.8:53
#   macOS-auto-route: true # auto set global route
#   macOS-auto-detect-interface: true # conflict with interface-name

proxies:
# 支持的协议及加密算法示例请查阅 Clash 项目 README 以使用最新格式：https://github.com/Dreamacro/clash/wiki/configuration

  - name: "Bwh"
    type: ss
    server: ·······
    port: ·········
    cipher: aes-256-gcm
    password: “········”
    # udp: true
    
  - name: "Anynode"
    type: ss
    server: ······
    port: ········
    cipher: aes-256-gcm
    password: “······”
    # udp: true

  - name: "Relay"
    type: ss
    server: ········
    port: ·······
    cipher: aes-256-gcm
    password: “··········”
    # udp: true
    

# 服务器节点订阅
proxy-providers:

proxy-groups:

  # 代理节点选择
  - name: "PROXY"
    type: select
    proxies:
      - Bwh
      - Relay
      - Anynode
      
  # Netflix流媒体服务
  - name: Netflix
    type: select
    proxies:
      - Relay
      - Anynode

# 关于 Rule Provider 请查阅：https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
rule-providers:
# name: # Provider 名称
#   type: http # http 或 file
#   behavior: classical # 或 ipcidr、domain
#   path: # 文件路径
#   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
#   interval: # 自动更新间隔，仅在类型为 HTTP 时可用

  Banad:
    type: http
    behavior: classical
    path: ./RuleSet/Banad.yaml
    url: https://raw.sevencdn.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
    interval: 86400

  Rejectlist:
    type: http
    behavior: classical
    path: ./RuleSet/Rejectlist.yaml
    url: https://raw.sevencdn.com/lhie1/Rules/master/Clash/Provider/Reject.yaml
    interval: 86400

  Rejectlist2:
    type: http
    behavior: classical
    path: ./RuleSet/Rejectlist2.yaml
    url: https://raw.sevencdn.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Advertising.yaml
    interval: 86400

  ADlist:
    type: http
    behavior: domain
    path: ./RuleSet/ADlist.yaml
    url: https://raw.sevencdn.com/Loyalsoldier/clash-rules/release/reject.txt
    interval: 86400
    
  Netflixstreaming:
    type: http
    behavior: classical
    path: ./RuleSet/Netflix.yaml
    url: https://raw.sevencdn.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml
    interval: 86400

  proxylist:
    type: http
    behavior: domain
    path: ./RuleSet/proxylist.yaml
    url: https://raw.sevencdn.com/Loyalsoldier/clash-rules/release/proxy.txt
    interval: 86400

  telegram:
    type: http
    behavior: ipcidr
    path: ./RuleSet/telegramlist.yaml
    url: https://raw.sevencdn.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    interval: 86400
    
  applelist:
    type: http
    behavior: domain
    path: ./RuleSet/applelist.yaml
    url: https://raw.sevencdn.com/Loyalsoldier/clash-rules/release/apple.txt
    interval: 86400
    
  icloudlist:
    type: http
    behavior: domain
    path: ./RuleSet/icloudlist.yaml
    url: https://raw.sevencdn.com/Loyalsoldier/clash-rules/release/icloud.txt
    interval: 86400
    
  chinaip:
    type: http
    behavior: ipcidr
    path: ./RuleSet/chinaip.yaml
    url: https://raw.sevencdn.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
    interval: 86400
    
# 规则
rules:

  - RULE-SET,Rejectlist2,REJECT
  - RULE-SET,Rejectlist,REJECT
  - RULE-SET,ADlist,REJECT
  - RULE-SET,Banad,REJECT

  - DOMAIN-SUFFIX,64clouds.com,PROXY
  - DOMAIN-SUFFIX,mobisystems.com,PROXY
  
  - RULE-SET,telegram,PROXY
    
  - RULE-SET,applelist,DIRECT
  - RULE-SET,icloudlist,DIRECT
  
  - RULE-SET,Netflixstreaming,Netflix
  
  - RULE-SET,proxylist,PROXY

  
  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT

  # （可选）使用来自 ipipdotnet 的 ChinaIP 以解决数据不准确的问题，使用 ChinaIP.yaml 时可禁用下列直至（包括）「GEOIP,CN」规则
  # - RULE-SET,ChinaIP,DIRECT
  # Tencent
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  # GeoIP China
  - RULE-SET,chinaip,DIRECT
  - GEOIP,CN,DIRECT

  - MATCH,DIRECT
</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

规则中的自动更新interval貌似不起作用，控制台中查看规则还是几天前更新的。
### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by xyxu1024** [comment]
相同的问题

**Comment by honeyjuice** [comment]
相同的问题+1

**Comment by jiapenghe** [comment]
相同的问题+1

**Comment by Mosney** [comment]
据我的观察，如果引用的资源没有变化，那么本地资源也就不会更新。这个显示时间似乎是拿`现在时间`-`本地资源的更新时间`，所以合理推测实际上并不是没有自动更新，而是自动更新后发现没有新的更新

**Comment by ben-august** [comment]
> 据我的观察，如果引用的远程资源没有变化，那么本地资源也就不会更新。这个显示的更新时间似乎是展示`现在时间`-`本地资源的更新时间`，并不是`现在时间`-`上次检查更新的时间`，所以合理推测实际上并不是没有自动更新，而是自动更新后发现没有新的更新
并不是，规则每天都会更新，手动更新就会显示出变化。但是这软件自动更新从来不会工作过。

**Comment by Mosney** [comment]
> > 并不是，规则每天都会更新，手动更新就会显示出变化。但是这软件自动更新从来不会工作过。

手动更新之后这个显示的时间的确会立刻更新成上述后者计算方法，但是重启之后又会恢复，可能是两个地方展现逻辑不同

**Comment by Remonli** [comment]
确实有这个问题。

**Comment by xiao-baii** [comment]
相同的问题+1

**Comment by KorenKrita** [comment]
相同问题+1

**Comment by aoxue** [comment]
相同问题+1
还没解决

**Comment by fireflycao** [comment]
相同问题+2
还没解决
