### ISSUE TITLE
关于配置文件路径

### ISSUE THREAD

**Issue by lintmx** [Dreamacro/clash#13]
希望修改为优先读取软件目录下, 该目录下没有配置文件再读取 $HOME 下的.

这样方便把软件放到 U 盘带着走.

**Comment by Dreamacro** [comment]
目前的想法是加一个 flag，比如 `clash -d .` 来自定义配置文件目录。

之所以没有做成 `优先读取软件目录下, 该目录下没有配置文件再读取 $HOME` 的原因是：这个项目最初的考虑是作为 `macOS / Linux` 下的一个常驻应用，而没有去考虑 Windows 下比较方便的使用方法。

**Comment by lintmx** [comment]
这样也不错, win 下可以通过一个 bat 文件解决 .

**Comment by Dreamacro** [comment]
@lintmx 会在下一个 release 支持
