### ISSUE TITLE
[Bug]基于IP-CIDR规则，UDP连接不符合预期

### ISSUE THREAD

**Issue by 786259135** [Dreamacro/clash#1301]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml

rules:
  - IP-CIDR,213.239.205.77/32,CN2GIA
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,DIRECT
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

**我预期会发生……？**

**实际上发生了什么？**

### 更多信息 More Information
![image](https://user-images.githubusercontent.com/16495257/111320341-d701ad00-86a1-11eb-9363-638509b4d7bd.png)

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/issues/934#issuecomment-683430258
