### ISSUE TITLE
[Feature]兼容SocksDroid的DNS设置（添加TCP）

### ISSUE THREAD

**Issue by cindymao56** [Dreamacro/clash#1312]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### 环境 Environment

* 使用者的操作系统 (the OS running on the client) 
Windows / Linux

* 网路环境或拓扑 (network conditions/topology)
 LAN （电脑连网，运行clash。手机与电脑在同一LAN中）

### 说明 Description

[SocksDroid](https://github.com/PeterCxy/SocksDroid) 是一个能让Android通过socks代理上网的app，想用这个app来使手机通过电脑的clash上网。
SocksDroid需要设置DNS IP/port（使用电脑作DNS），但仅支持TCP DNS。
![unnamed](https://user-images.githubusercontent.com/37578952/112707553-30d55480-8ea4-11eb-8cc8-4303ce551c61.png)

而clash目前只监听UDP DNS
### 可能的解决方案 Possible Solution
clash的DNS server也监听TCP

**Comment by Dreamacro** [comment]
可以试试 clash for android?

**Comment by wsvg14** [comment]
> 可以试试 clash for android?

插个嘴，cfa从去年9月之后就没跟进了，导致新的一些特性没有被支持，虽然日用问题不大。
