### ISSUE TITLE
[Bug] clash-core-service的log没有完全遵从config.yaml中的设定，且对包括过去产生的的log加上了文件锁

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [Dreamacro/clash#1313]
### Clash config

```yaml
log-level: silent
```

</details>

### Clash log

```
time="2021-03-27T17:44:54+08:00" level=info msg="Start initial compatible provider Proxy"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
  Windows

### 说明 Description
我使用的是CFW portable版本，以service模式工作
通过onedrive于各机器间同步，但由于log的生成且被占用导致同步被阻塞
我希望能够当设置log等级为slient时不生成log

### 重现问题的具体布骤 Steps to Reproduce
1. 启动clash-core-service
2. 第一个log文件产生
3. 关闭clash-core-service
4. 启动clash-core-service
5. 第二个log文件产生
6. 尝试删除第一个log -> 文件正在使用
7. 上述操作可反复执行

**我预期会发生……？**
同说明

**实际上发生了什么？**
每次启动都会产生一条log，且所有log文件都被占用
![image](https://user-images.githubusercontent.com/50797982/112717260-6ae73a80-8f26-11eb-9fb6-ef6197349b08.png)

**Comment by Dreamacro** [comment]
clash-core-service 是什么，问错仓库了吧
