### ISSUE TITLE
[hello]海外DOT DOH超时用不了

### ISSUE THREAD

**Issue by t-ca** [Dreamacro/clash#1314]
海外DOT DOH超时用不了

**Comment by t-ca** [comment]
另外
fallback
https://dns.cloudflare.com/dns-query
https://doh.opendns.com/dns-query
tls://dns.google
https://dns.google/dns-query
dot、doh有干扰，容易超时，能否访问看运气，运气不好的时候访问需要代理的网站浏览器提示dns找不到ip，国内网站无影响。此issues与fallback没太大关系，应该我改为8.8.8.8，问题依旧。

**Comment by Mosney** [comment]
用不了是常态，什么都能用就不会有本repo出现了

**Comment by phlinhng** [comment]
Clash 的 DNS 查询结果不用于实际连接，因此不设置海外 DNS 也无所谓（换句话说，让 Clash 拿到被污染的结果也无所谓）。如果執意要用海外 DNS，可以参考 https://github.com/Dreamacro/clash/issues/1264，让海外 DoH / DoT 的连接走代理。
