### ISSUE TITLE
[Feature]clash for Windows什么时候可以支持kcp呢？

### ISSUE THREAD

**Issue by Viekin** [Dreamacro/clash#1315]
如题，因为我安卓的手机也是使用的clash，已经可以用kcp了，Windows端近期会有计划支持kcp么

**Comment by akw5454521** [comment]
你安卓用的哪个???确定支持kcp?

**Comment by Viekin** [comment]
> 你安卓用的哪个???确定支持kcp?

我错了~应该是vim编辑配置文件退出的时候用错指令了，没有保存
