### ISSUE TITLE
[Feature]希望Fallback支持代理并抹除edns的client ip

### ISSUE THREAD

**Issue by v39lfy** [Dreamacro/clash#1316]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
OSX
* 使用者的操作系统 (the OS running on the client)
OSX
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他
……

### 说明 Description

clash的dns模块fallback没有使用代理。
我希望在fallback使用代理请求dns。我尝试了一下，它会显著提高连接速度。
我找到了相同的内容。但是问题被关闭了

### 可能的解决方案 Possible Solution
拜读了代码。抽象的非常棒。为简单的解决这个问题提供了前提条件。
我见所有到vps的连接方式抽象出来一个Adapter的概念。
而clash使用的dns库的client是继承net.Conn的
我觉得可以重写net.Conn 的Write和Read方法。(一个新类。和net.Conn组合的新类会使用当前的代理发送数据）
然后这个新类和D.Client组合。使其通过代理查询DNS

### 更多信息 More Information

**Comment by Dreamacro** [comment]
所有 clash 能拿到域名信息的连接都会以传输域名优先的方式发到各个代理。参考 https://github.com/Dreamacro/clash/issues/968#issuecomment-692609859

**Comment by Victor2333** [comment]
我碰到的问题是google的DoH和DoT都会超时，所以只能依赖GFW污染后的dns解析结果落在Geoip CN网段外，从而解决dns污染问题。

**Comment by v39lfy** [comment]
我主要是在tun模式下。 可能在socks5模式下， 链接能拿到域名信息(不太懂socks5协议细节)。在tun模式下DNS请求和向解析出来的IP发送请求是分开的。
所以我觉得增加fallback，默认使用代理解析域名的功能是特别有用的

**Comment by v39lfy** [comment]
这样通过代理请求目标网站，拿到的是离代理服务器最近的目前网站的主机IP

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/issues/1264#issuecomment-811057086 可以先看看这个
