### ISSUE TITLE
[Feature] 想利用clash控制孩子上网时间

### ISSUE THREAD

**Issue by ju-svg** [Dreamacro/clash#1317]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：
- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求
请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

想利用clash控制孩子上网时间

### 可能的解决方案 Possible Solution
  - SRC-IP-CIDR,192.168.50.3/32, Mon-Fri, 18:00-22:00, REJECT

**Comment by tudnew** [comment]
你这个装个openwrt用自带防火墙就可以做，其他类似软件也有，clash是个代理软件......

**Comment by Dreamacro** [comment]
其实是可以的，只要给 script 加一个 time 模块，但是不建议在 clash 里做这个

```yaml
mode: script
script:
  code: |
    def main(ctx, metadata):
      now := time.now()
      if metadata["src_ip"] == "ip" and now.hour => 18 and now.hour <= 22:
        return "REJECT"

      return "DIRECT"
```

**Comment by ju-svg** [comment]
多谢老大！

**Comment by Dreamacro** [comment]
@ju-svg 现在不行，得下个版本我把 time 模块加上

**Comment by tudnew** [comment]
@Dreamacro 大佬 ＃1262 ＃1264 这两个问题能不能优化下啊？

**Comment by Cedkis** [comment]
摊上你这么个父母真惨

**Comment by xuhaoyang** [comment]
> 摊上你这么个父母真惨

学生？

**Comment by Dreamacro** [comment]
time module added
