### ISSUE TITLE
Is it possible to have "Port" as a rule type?

### ISSUE THREAD

**Issue by 3andero** [Dreamacro/clash#132]
The latest version of Clash supports many types of rules - "Domain", "Geoip" etc. However, they are unable to satisfy the security needs of Chinese proxy users. Http connections are vulnerable to man-in-the-middle attack due to its plaintext transmission. As a proxy user in China, **I wonder if it is possible to add "Port" as a type of rule so I can bypass all Http connections, or if there are any other ways to bypass Http**.

**Comment by Dreamacro** [comment]
Can you provide some specific examples and usage scenarios?

**Comment by 3andero** [comment]
For instance, "www.tsinghua.edu.cn" only provides "Http" connections. I want to bypass all "Http" connections like this ("tcp:www.tsinghua.edu.cn:80"), and maybe this could be achieved by bypassing the port 80. 
I don't want my plaintext exposed to VPN suppliers, but my own servers are not fast enough. It would be better to let all http transmission connected through my own server and that is why I hope there is a rule  for ports.

**Comment by comzyh** [comment]
We are recreating iptables, again. :laughing:

**Comment by Dreamacro** [comment]
add `SRC-PORT` and `DST-PORT` in the lastest release.
