### ISSUE TITLE
关于trojan over gRPC的一点问题

### ISSUE THREAD

**Issue by maskedeken** [Dreamacro/clash#1325]
上面通过StreamGunWithTransport()产生的Conn，似乎没必要再调用这里的StreamConn()

https://github.com/Dreamacro/clash/blob/d0c829c578445b64041829a0633f6526055398a5/adapters/outbound/trojan.go#L111

**Comment by Dreamacro** [comment]
`StreamGunWithTransport` 只是包含了 grpc 的整个 wrapper，StreamConn 是 trojan 的 wrapper

**Comment by maskedeken** [comment]
> 
> 
> `StreamGunWithTransport` 只是包含了 grpc 的整个 wrapper，StreamConn 是 trojan 的 wrapper

看代码trojan的StreamConn是给Conn包一层tls，但grpc的conn已经有tls了，而且上面的DialContext对于grpc并没有再调用trojan的StreamConn

**Comment by maskedeken** [comment]
这里的字眼“want q"怪怪的，q是什么意思？
https://github.com/Dreamacro/clash/blob/d0c829c578445b64041829a0633f6526055398a5/component/gun/gun.go#L170

**Comment by Dreamacro** [comment]
> > `StreamGunWithTransport` 只是包含了 grpc 的整个 wrapper，StreamConn 是 trojan 的 wrapper
> 
> 看代码 trojan 的 StreamConn 是给 Conn 包一层 tls，但 grpc 的 conn 已经有 tls 了，而且上面的 DialContext 对于 grpc 并没有再调用 trojan 的 StreamConn
> 
> https://github.com/Dreamacro/clash/blob/d0c829c578445b64041829a0633f6526055398a5/adapters/outbound/trojan.go#L71

fixed in cc96187
