### ISSUE TITLE
最新的Dev版本判断home目录有问题

### ISSUE THREAD

**Issue by xuan880** [Dreamacro/clash#133]
在termux里面编译最新版的Dev版本，直接运行会报下面的错误，必须添加-d参数制定配置文件目录才能运行，开发版在在go的依赖版本升级到1.12之前的版本没有问题
~/clash   dev  ./bin/clash-dev FATA[0000] Initial configuration directory error: Can't create config directory /.config/clash: mkdir /.config: read-only file system

**Comment by Dreamacro** [comment]
go 1.12 改成了自带的函数
https://github.com/Dreamacro/clash/blob/d75f9ff78354b4bcf2eb8a552b0408a0431bb0eb/constant/path.go#L18
我之后会看一下这个函数有什么问题

**Comment by Dreamacro** [comment]
对于安卓，他返回的是根目录 https://golang.org/src/os/file.go?s=11606:11640#L379

**Comment by Dreamacro** [comment]
golang 修复了 https://github.com/golang/go/commit/bedb6a18d855d1968a685ccd90c81a43b3def9fa，等 release 吧

**Comment by Dreamacro** [comment]
d3b280a 先改回去，1.13 修复了改回来
