### ISSUE TITLE
[Feature] type: url-test 能否在节点tcp连接失败或者超时的情况下立即切换

### ISSUE THREAD

**Issue by fishg** [Dreamacro/clash#1332]
type: url-test
选中的节点如果突然故障，要至少等一个探测周期，能否判断是tcp connect失败或者超，直接从其他可用节点选择延迟最低的节点呢？

**Comment by fishg** [comment]
类似nginx的高可用切换的一种：
      server x.x.x.x:80 max_fails=1  fail_timeout=600s; 
可以配置连续失败几次后禁用，以及禁用时长。nginx默认是tcp 连接错误或者是连接超时来增加该计数的。

**Comment by Dreamacro** [comment]
只需要最多等大概 10s，https://github.com/Dreamacro/clash/blob/6c83ff3496542f12297eb971a611d3d3aea90297/adapters/outboundgroup/urltest.go#L64-L90

**Comment by fishg** [comment]
> 只需要最多等 10s
> https://github.com/Dreamacro/clash/blob/6c83ff3496542f12297eb971a611d3d3aea90297/adapters/outboundgroup/urltest.go#L64-L90

这里是不是缺了u.fastNode.Alive() 的判断呢？

**Comment by Dreamacro** [comment]
这里的意思是：10s 内的请求都会返回当前存活的最快的 proxy

**Comment by fishg** [comment]
> ~这里的意思是：10s 内的请求都会返回当前存活的最快的 proxy~
> 
> 确实少了，你是想提个 pr 改一下呢，还是我直接改

辛苦直接改下吧~ 我还不会写go。不过代码表意清晰，看懂逻辑了

**Comment by Dreamacro** [comment]
0a352379159d6ca6a0574c0fb6a5f64cad222d41 中修复了

**Comment by fishg** [comment]
> [0a35237](https://github.com/Dreamacro/clash/commit/0a352379159d6ca6a0574c0fb6a5f64cad222d41) 中修复了

赞！谢谢~

**Comment by mxdsdoonline** [comment]
不好意思,对代码不甚了解,想问一下上面的代码复制到rules就可以生效了吗?因为我看到你们的对话还要修改

**Comment by mxdsdoonline** [comment]
不好意思,对代码不甚了解,想问一下上面的代码复制到rules就可以生效了吗?因为我看到你们的对话还要修改

**Comment by mxdsdoonline** [comment]
小白想请教,这段代码添加到哪里,直接添加到rules?
