### ISSUE TITLE
[Feature]希望给proxy-group添加disable功能，更好的支援CDN规则~

### ISSUE THREAD

**Issue by zm24120** [Dreamacro/clash#1336]
### 说明 Description
希望能给proxy-group添加disable功能，方便某些CDN规则~

**功能背景：**
比如：NETFLIX 电视端，经常会使用亚马逊的CDN~需要在NETFLIX的规则里添加全量  亚马逊ip 规则才能正常观看
但是很多网站也会使用亚马逊的cdn，这时候就会导致分流错误。

如果proxy-group有disable选项，
那么当proxy-group为proxy时，则正常走代理，
**当为disable时，则认为指向proxy-group的rules为无，clash corel忽略该rule，继续向下查询规则**
这样便于在观看 NETFLIX 时，打开  亚马逊ip  proxy-group，不观看时候 直接关闭该proxy-group，
从而不影响下方和亚马逊ip 冲突的规则，更有灵活性

【该功能类似于 当前已经实现的 proxy-group的disable-udp: true】

配置举例：
proxy-group：
- name: NETFLIX
    type: select
    proxies:
      - ss1
      - ss2
      - DIRECT

- name: 亚马逊ip
    type: select
    proxies:
      - ss1
      - ss2
      - DIRECT
      **- DISABLE**

- name: 日本漫画
    type: select
    proxies:
      - 日本节点
      - DIRECT

rules:
#奈飞规则
  - DOMAIN-SUFFIX,netflix.com,NETFLIX
  - IP-CIDR,33.66.0.0/8,亚马逊ip
#某日漫网站
  - DOMAIN-SUFFIX,abc.com,日本漫画
  - IP-CIDR,33.66.0.0/8,日本漫画 (当使用同个cdn ip或者用网址规则但是解析为 33.66.0.23这种ip的时候，当前direct,proxy,无法满足分流需求)
  - 
### 可能的解决方案 Possible Solution
![图片](https://user-images.githubusercontent.com/53201527/113691292-dc7d7080-96fe-11eb-9935-aeab188c227b.png)

**Comment by jadesongplay** [comment]
坚决支持

**Comment by zm24120** [comment]
大佬怎么都不理我？是我没说清楚，还是觉得这个功能没必要呢？

再补充一个场景吧:
当规则添加了reject的去广告规则时候(参考acl4ssr规则)，如果现在如果想零时关闭，只能direct或者proxy~通常去广告规则涵盖了国内外网站，这时候就会影响正确分流，导致国外广告无法出墙，或者国内广告出墙

proxy-group：
 - name: 去广告
    type: select
    proxies:
     - REJECT
     - DIRECT

rule:
# 去广告
 - DOMAIN-SUFFIX,ad.google.com,去广告
 - DOMAIN-SUFFIX,ad.iqiyi.com,去广告
 # 分流规则
 - DOMAIN-SUFFIX,google.com,proxy
 - DOMAIN-SUFFIX,iqiyi.com,direct

如果这时候【去广告】的proxy-groups有disable功能，就不影响下面规则的分流


望大佬慎重考虑添加此功能

**Comment by Mosney** [comment]
莫名其妙的功能请求，你用的规则不全面罢了
```

  # > Netflix
   - DOMAIN-SUFFIX,fast.com,Netflix
   - DOMAIN-SUFFIX,netflix.com,Netflix
   - DOMAIN-SUFFIX,netflix.net,Netflix
   - DOMAIN-SUFFIX,nflxext.com,Netflix
   - DOMAIN-SUFFIX,nflximg.com,Netflix
   - DOMAIN-SUFFIX,nflximg.net,Netflix
   - DOMAIN-SUFFIX,nflxso.net,Netflix
   - DOMAIN-SUFFIX,nflxvideo.net,Netflix
   - DOMAIN-SUFFIX,netflixdnstest0.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest1.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest2.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest3.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest4.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest5.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest6.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest7.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest8.com,Netflix
   - DOMAIN-SUFFIX,netflixdnstest9.com,Netflix
   - DOMAIN-KEYWORD,dualstack.apiproxy-,Netflix
   - DOMAIN-KEYWORD,dualstack.ichnaea-web-,Netflix
   # > Netflix
   - IP-CIDR,23.246.0.0/18,Netflix
   - IP-CIDR,37.77.184.0/21,Netflix
   - IP-CIDR,45.57.0.0/17,Netflix
   - IP-CIDR,64.120.128.0/17,Netflix
   - IP-CIDR,66.197.128.0/17,Netflix
   - IP-CIDR,69.53.224.0/19,Netflix
   - IP-CIDR,108.175.32.0/20,Netflix
   - IP-CIDR,185.2.220.0/22,Netflix
   - IP-CIDR,185.9.188.0/22,Netflix
   - IP-CIDR,192.173.64.0/18,Netflix
   - IP-CIDR,198.38.96.0/19,Netflix
   - IP-CIDR,198.45.48.0/20,Netflix
   - IP-CIDR,207.45.72.0/22,Netflix
   - IP-CIDR,208.75.76.0/22,Netflix
```

**Comment by fishg** [comment]
这想法挺有意思，关键倒不是解决nf问题，加个PASS规则用于临时忽略一些group还是不错

**Comment by zm24120** [comment]
> 莫名其妙的功能请求，你用的规则不全面罢了
> 
> ```
> 
>   # > Netflix
>    - DOMAIN-SUFFIX,fast.com,Netflix
>    - DOMAIN-SUFFIX,netflix.com,Netflix
>    - DOMAIN-SUFFIX,netflix.net,Netflix
>    - DOMAIN-SUFFIX,nflxext.com,Netflix
>    - DOMAIN-SUFFIX,nflximg.com,Netflix
>    - DOMAIN-SUFFIX,nflximg.net,Netflix
>    - DOMAIN-SUFFIX,nflxso.net,Netflix
>    - DOMAIN-SUFFIX,nflxvideo.net,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest0.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest1.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest2.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest3.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest4.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest5.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest6.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest7.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest8.com,Netflix
>    - DOMAIN-SUFFIX,netflixdnstest9.com,Netflix
>    - DOMAIN-KEYWORD,dualstack.apiproxy-,Netflix
>    - DOMAIN-KEYWORD,dualstack.ichnaea-web-,Netflix
>    # > Netflix
>    - IP-CIDR,23.246.0.0/18,Netflix
>    - IP-CIDR,37.77.184.0/21,Netflix
>    - IP-CIDR,45.57.0.0/17,Netflix
>    - IP-CIDR,64.120.128.0/17,Netflix
>    - IP-CIDR,66.197.128.0/17,Netflix
>    - IP-CIDR,69.53.224.0/19,Netflix
>    - IP-CIDR,108.175.32.0/20,Netflix
>    - IP-CIDR,185.2.220.0/22,Netflix
>    - IP-CIDR,185.9.188.0/22,Netflix
>    - IP-CIDR,192.173.64.0/18,Netflix
>    - IP-CIDR,198.38.96.0/19,Netflix
>    - IP-CIDR,198.45.48.0/20,Netflix
>    - IP-CIDR,207.45.72.0/22,Netflix
>    - IP-CIDR,208.75.76.0/22,Netflix
> ```

参看acl4ssr的规则，很多亚马逊的cdn服务器，会影响其他使用亚马逊cdn的网站分流

**Comment by zm24120** [comment]
> 这想法挺有意思，关键倒不是解决nf问题，加个PASS规则用于临时忽略一些group还是不错

是的，很多场景可以更灵活应用~我觉得是挺有必要的
