### ISSUE TITLE
[Bug] grpc udp连接不会自动关闭

### ISSUE THREAD

**Issue by fishg** [Dreamacro/clash#1339]
grpc 如果产生了udp请求，连接不会自动关闭，会产生大量的udp活动连接

**Comment by Dreamacro** [comment]
连接不会自动关闭具体指什么，能说详细一些吗

**Comment by fishg** [comment]
![image](https://user-images.githubusercontent.com/1423545/114166706-accda300-9960-11eb-8dea-9aa5ebc97def.png)

又加上grpc节点抓了下截图，会出现udp连接一直在活跃列表里，不会出现在已关闭里

**Comment by fishg** [comment]
tcp走grpc 节点也有同样的问题，但是不是必现的，一般挂机一天会出现连接数积累。

**Comment by Dreamacro** [comment]
c9943fb 应该修复了
