### ISSUE TITLE
win10 1903 18351.1 版本exe无法启动.

### ISSUE THREAD

**Issue by zsmj1994** [Dreamacro/clash#134]

**Comment by Dreamacro** [comment]
用 cmd 打开的话报了什么错误？可以提供一下吗

**Comment by zsmj1994** [comment]
> 
> 
> 用 cmd 打开的话报了什么错误？可以提供一下吗

time="2019-03-09T20:26:24+08:00" level=fatal msg="Parse config error: Configuration file C:\\Users\\歆/.config/clash/config.yml is empty"

**Comment by Dreamacro** [comment]
@zsmj1994 你在 `C:\Users\歆/.config/clash/config.yml` 这个文件编辑配置吧。。这不是无法启动，只是你配置没有填好
