### ISSUE TITLE
using clash tun with adguard home

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1342]
hi
I use adguard home for dns resolver. and using clash tun as well.
but im getting error in adguard home because its listening to 198.18.0.1 and tun devices ip is 198.18.0.1. those have conflicts. is there anyway to change the tun ip to another ip like 198.18.0.3?
thanks

**Comment by isweibin** [comment]
Change the value of `fake-ip-range` ought to work.
