### ISSUE TITLE
ClashX 需要使用管理员权限安装一个帮助程序来帮助设置系统代理

### ISSUE THREAD

**Issue by Dev-Jabin** [Dreamacro/clash#1346]
Mac 每次重启时都会 弹出这个对话框，如果不安装的话clashx就会启动失败。
这是怎么回事儿呐？谢谢！
<img width="416" alt="clashX" src="https://user-images.githubusercontent.com/13827134/114294161-3307f780-9acf-11eb-8856-1aa6ee104fd2.png">

**Comment by Dreamacro** [comment]
升级系统或升级 clashx

**Comment by oushiun** [comment]
@Dreamacro 我在今天也遇到同样的问题，mac os(13.0.1) 和 clashx pro(1.95.1.1) 都是最新的版本

**Comment by oushiun** [comment]
我想我找到了解决办法  https://github.com/yichengchen/clashX/discussions/1019

**Comment by Fisher-Ding** [comment]
> 
work!
