### ISSUE TITLE
[Bug] grpc core

### ISSUE THREAD

**Issue by fishg** [Dreamacro/clash#1347]
基于最新的dev分支
2021-04-11 16:54:41 Watchdog: Clash Core Problem, Restart.
	github.com/Dreamacro/clash/tunnel/connection.go:155 +0xa5
created by github.com/Dreamacro/clash/tunnel.relay
	github.com/Dreamacro/clash/tunnel/connection.go:159 +0x190
github.com/Dreamacro/clash/tunnel.relay.func1(0xa39ea0, 0xc000306408, 0x7f23fe331bc0, 0xc00018e460, 0xc001071740)
	io/io.go:396 +0x8c
io.CopyBuffer(0xa2ce60, 0xc000292a10, 0xa2ce40, 0xc000292a30, 0xc000e00000, 0x5000, 0x8000, 0x8fc0a0, 0x901900, 0xc000f3fb00)
	io/io.go:423 +0x12c
io.copyBuffer(0xa2ce60, 0xc000292a10, 0xa2ce40, 0xc000292a30, 0xc000e00000, 0x5000, 0x8000, 0xc000292a30, 0xc000292a30, 0x912b60)
	github.com/Dreamacro/clash/tunnel/statistic/tracker.go:40 +0x55
github.com/Dreamacro/clash/tunnel/statistic.(*tcpTracker).Read(0xc00018e460, 0xc000e00000, 0x5000, 0x8000, 0x2000, 0x0, 0x0)
	github.com/Dreamacro/clash/component/gun/gun.go:138 +0x89a
github.com/Dreamacro/clash/component/gun.(*Conn).Read(0xc000f3fbc0, 0xc000e00000, 0x5000, 0x8000, 0xc0004c3dc8, 0x50e7ce, 0xc00138b400)
goroutine 16988 [running]:

panic: runtime error: slice bounds out of range [15:4]
2021-04-11 16:34:49 Reload OpenClash Firewall Rules

**Comment by canflyx** [comment]
我的也会自动关闭，不知道是不是因为grpc的问题。
2021-04-13 13:31:28 Watchdog: Clash Core Problem, Restart.
	github.com/Dreamacro/clash/tunnel/connection.go:150 +0xa5
created by github.com/Dreamacro/clash/tunnel.relay
	github.com/Dreamacro/clash/tunnel/connection.go:154 +0x190
github.com/Dreamacro/clash/tunnel.relay.func1(0xd4afd8, 0xc000e78640, 0x7fee81574278, 0xc0003f2560, 0xc00181ccc0)
	io/io.go:396 +0x8c
io.CopyBuffer(0xd38180, 0xc000e79070, 0xd38160, 0xc000e79080, 0xc001ada000, 0x5000, 0x8000, 0x8ebbe5, 0xc0015c38c0, 0xc000555f90)
	io/io.go:423 +0x12c
io.copyBuffer(0xd38180, 0xc000e79070, 0xd38160, 0xc000e79080, 0xc001ada000, 0x5000, 0x8000, 0xc000e79080, 0xc000e79080, 0xb91700)
	github.com/Dreamacro/clash/tunnel/statistic/tracker.go:40 +0x55
github.com/Dreamacro/clash/tunnel/statistic.(*tcpTracker).Read(0xc0003f2560, 0xc001ada000, 0x5000, 0x8000, 0x15b, 0x0, 0x0)
	github.com/Dreamacro/clash/component/gun/gun.go:134 +0x83e
github.com/Dreamacro/clash/component/gun.(*Conn).Read(0xc00066b7a0, 0xc001ada000, 0x5000, 0x8000, 0x15b, 0x0, 0x0)
goroutine 7296 [running]:

panic: runtime error: slice bounds out of range [15:6]

**Comment by fishg** [comment]
> 我的也会自动关闭，不知道是不是因为grpc的问题。
> 2021-04-13 13:31:28 Watchdog: Clash Core Problem, Restart.
> github.com/Dreamacro/clash/tunnel/connection.go:150 +0xa5
> created by github.com/Dreamacro/clash/tunnel.relay
> github.com/Dreamacro/clash/tunnel/connection.go:154 +0x190
> github.com/Dreamacro/clash/tunnel.relay.func1(0xd4afd8, 0xc000e78640, 0x7fee81574278, 0xc0003f2560, 0xc00181ccc0)
> io/io.go:396 +0x8c
> io.CopyBuffer(0xd38180, 0xc000e79070, 0xd38160, 0xc000e79080, 0xc001ada000, 0x5000, 0x8000, 0x8ebbe5, 0xc0015c38c0, 0xc000555f90)
> io/io.go:423 +0x12c
> io.copyBuffer(0xd38180, 0xc000e79070, 0xd38160, 0xc000e79080, 0xc001ada000, 0x5000, 0x8000, 0xc000e79080, 0xc000e79080, 0xb91700)
> github.com/Dreamacro/clash/tunnel/statistic/tracker.go:40 +0x55
> github.com/Dreamacro/clash/tunnel/statistic.(*tcpTracker).Read(0xc0003f2560, 0xc001ada000, 0x5000, 0x8000, 0x15b, 0x0, 0x0)
> github.com/Dreamacro/clash/component/gun/gun.go:134 +0x83e
> github.com/Dreamacro/clash/component/gun.(*Conn).Read(0xc00066b7a0, 0xc001ada000, 0x5000, 0x8000, 0x15b, 0x0, 0x0)
> goroutine 7296 [running]:
> 
> panic: runtime error: slice bounds out of range [15:6]

看起来是，fork临时修改了下

**Comment by fishg** [comment]
dev已修复
