### ISSUE TITLE
port和socks-port能否指定监听的IP地址

### ISSUE THREAD

**Issue by zhaibin18** [Dreamacro/clash#135]
目前配置文件这样写会报错
port: 192.168.1.1:7890

**Comment by Dreamacro** [comment]
有什么特殊的场景吗

**Comment by zhaibin18** [comment]
路由器上，不想监听ppp0，只监听内部给局域网内用，allow-lan: true会监听所有接口。

**Comment by comzyh** [comment]
iptables 或者 firewalld 过滤下？

zhaibin18 <notifications@github.com> 于 2019年3月16日周六 19:34写道：

**Comment by ruisiji** [comment]
@Dreamacro I'd like to replace `allowLan` with `bindAddress` to allow fine-grain control the bind address.

This is very helpful when a device has multiple interfaces, especially has a public IP address.

If you agree this approach, I can make a PR to implement it.

**Comment by Dreamacro** [comment]
@ruisiji replace `allowLan` is a big break change, both GUI and dashboard will be affected. I don't recommend to do it.

**Comment by ruisiji** [comment]
We can keep the backward compatibility, something like allow setting `bindAddress` to `true/false/x.x.x.x`, `true` is equal to `0.0.0.0` and `false` equal to `127.0.0.1`.

**Comment by Dreamacro** [comment]
```bindAddress: true``` look so weird. maybe we can provide a new config like `lan-address` to set specific address if `allow-lan` is true.

**Comment by ruisiji** [comment]
I don't know how does GUI and dashboard code work, but the logic should be easy to implement when switched to `bindAddress`.

* `allowLan: true` ==> `bindAddress: 0.0.0.0`
* `allowLan: false` ==> `bindAddress: 127.0.0.1`

We can provide enough time for GUI and dashboard to change the code logic before we deprecated the `allowLan`.

Introducing another extra parameter is a little complex for users since the use case can be done with a single parameter.

**Comment by Dreamacro** [comment]
But in most cases (even for me), don't need to bind a specific address. For most users is enough now.

```yaml
port: 7890
allow-lan: true # false
```

for advanced users, just add an external config

```yaml
port: 7890
allow-lan: true # false
lan-address: 192.168.0.2 # ==> 192.168.0.2:7890 for HTTP
```
the `lan-address` default is `:` , because `:` would bind dual stack address (:: and 0.0.0.0)

**Comment by ruisiji** [comment]
So the final approach will be something like:

> If allowLan is true, then find bindAddress, if it exists, set the bindAddress, otherwise bind all.

This seems reasonable and no breaking change, ok to me.

I can submit PR to implement this, for now I will use `bind-address`, are you ok with this?

Later when you finalize the format of the parameter, we can change them all in a separate PR.

**Comment by Dreamacro** [comment]
@ruisiji sure, could not be better. 👏

**Comment by ruisiji** [comment]
@Dreamacro PR: https://github.com/Dreamacro/clash/pull/255

I can't find a value to bind all IPv4 and IPv6 address, initially I want to use `*`, but this is a special char in YAML, need to quote it when using in YAML, so I choose `all` as the value.

**Comment by Dreamacro** [comment]
@ruisiji Is there a problem with quotes?

**Comment by ruisiji** [comment]
```
bind-address: "*"
bind-address: '*'
bind-address: all
```

They will be both converted to empty string "", and they both contain three chars, but `all` is easy to read/write.

From the document, only `:port` will listen to both IPv4 and IPv6 address: https://golang.org/pkg/net/#Dial

**Comment by ruisiji** [comment]
I found this: https://github.com/golang/go/commit/071908f3d809245eda42bf6eab071c323c67b7d2#diff-af10cab567dbd44651926d200c231fceR552

The interesting part is, when the bind address is 0.0.0.0, it actually binds all IPv4 and IPv6 addresses.

Will update the code to use `0.0.0.0` instead.

**Comment by Dreamacro** [comment]
@ruisiji maybe your link is outdated: https://github.com/golang/go/blob/master/src/net/dial.go#L684-701

**Comment by ruisiji** [comment]
Yes, the link is outdated, but the behavior keeps same.

I tested on CentOS 7, both `0.0.0.0` and `[::]` will listen all interfaces.

**Comment by Dreamacro** [comment]
@ruisiji but keep use `:port` is more clear than use `0.0.0.0:port`, It seems to be confusing

**Comment by ruisiji** [comment]
so, which bindAddress do you prefer to trigger a bind `:port`?

**Comment by Dreamacro** [comment]
I prefer `bind-address: '*'`

**Comment by ruisiji** [comment]
updated the PR, could you restart TravisCI build? https://travis-ci.org/Dreamacro/clash/builds/569169640
