### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RomanSmile** [Dreamacro/clash#1357]
为什么更新版本1.5.0 clash 无法连接，连接成功了突然断开更换任何配置节点也是无法连接，退回上一个版本1.4.2恢复正常使用，
来反馈一下是软件有了变化和老版本配置不兼容，还是哪里出现问题了？

**Comment by Dreamacro** [comment]
不知道是什么东西“无法连接”，也不知道是哪种类型的代理。你这什么信息都没有从何谈问题 🌚

**Comment by nameless3721** [comment]
盲猜是v2节点 因为新版支持vmess aead header support alterId=0的话服务端不更新会连不上 可以改为1或者更新服务端

**Comment by RomanSmile** [comment]
我用的是linux客户端，不是节点是整个config.yaml配置，一个配置中有很多类型节点v2 torjan ss ssr 不是节点，是更新的版本不能用，不好用明白了吗？

**Comment by RomanSmile** [comment]
我用的是linux客户端，不是节点是整个config.yaml配置，一个配置中有很多类型节点v2 torjan ss ssr 不是节点，是更新的版本不能用，不好用明白了吗？

**Comment by nameless3721** [comment]
那就建议先学一下如何提问吧 能明白就有鬼了 
![image](https://user-images.githubusercontent.com/50364156/114983099-2ae2fa00-9ecb-11eb-9959-2e8d0b0c51f3.png)
