### ISSUE TITLE
MT7620A 我该下载那个版本呢？

### ISSUE THREAD

**Issue by hxddev** [Dreamacro/clash#136]
我在斐讯 K2 路由器 OpenWrt 系统上面尝试了 mips 几个版本都试过了不能运行，报下面这个错误。

CPU 型号：MediaTek MT7620A ver:2 eco:6

```sh
./clash: line 1: syntax error: unexpected "("
```

**Comment by comzyh** [comment]
看报错你好像是在用shell执行clash，而不是执行文件。

**Comment by xudongcc** [comment]
补充一下 clash-linux-mipsle 会报这个错误。

```
Illegal instruction
```

**Comment by xudongcc** [comment]
@comzyh 应该是 openwrt 默认是 sh，如果不能执行会当做 sh 脚本执行？

我后来安装了 bash 又试了下，报错变成了：
![image](https://user-images.githubusercontent.com/12939654/54346895-d7b17400-4680-11e9-864a-ff486467af18.png)

目前看来 clash-linux-mipsle 可以被执行，但是报 `Illegal instruction` 错误。

操作系统 CPU 这些实在不懂... 求解答。

**Comment by comzyh** [comment]
cat /proc/cpuinfo
试一下？
顺便试下
file /bin/sh
uname -a


xudong <notifications@github.com> 于 2019年3月14日周四 17:48写道：

**Comment by xudongcc** [comment]
![image](https://user-images.githubusercontent.com/12939654/54409865-eb61e680-4723-11e9-9ea8-dd82598190b2.png)

**Comment by Dreamacro** [comment]
类似 https://github.com/shawn1m/overture/issues/26 你可以先尝试看看

**Comment by Dreamacro** [comment]
close because of no reply

**Comment by Leo-UofT** [comment]
MT7620A以及MT7621A的架构是mipsle-softfloat, 能否在releases中加上?
