### ISSUE TITLE
Error: i/o timeout

### ISSUE THREAD

**Issue by ljk31** [Dreamacro/clash#1360]
出现这样的error，无法连接
`17/04/2021, 16:28:03.261  [warning] [TCP] dial GLOBAL to xx.com error: krgame01.yootoo6oocoo1oo.xyz:3614 connect error: i/o timeout`

使用版本7b01e1，Mac端

请问怎样解决？谢谢。

**Comment by Dreamacro** [comment]
看起来是节点域名，检测与节点的连通性情况

**Comment by Mosney** [comment]
节点挂了 去找你的机场
