### ISSUE TITLE
Remote Configure File Support[Feature]

### ISSUE THREAD

**Issue by woyin** [Dreamacro/clash#1364]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
# No Need
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Windows, OpenWRT
……
* 使用者的操作系统 (the OS running on the client)
Windows, iOS(Loon)
……
* 网路环境或拓扑 (network conditions/topology)
Telecom Wi-Fi and 4G
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
No
……
* 其他
……

### 说明 Description

I used a subscribe service of trojan, SS and vmess. So I ran a `subconverter` to generate the config file.
Every time when the subscribe changed, I must re-generate a config file and replace the old one. 
Although it just take me 1-2 minutes to handle it, it would be better to use a remote configuration file. In this way there is no need to justify whether I need to re-generate the config file, it's always up-to-date.
But I've try to use the `subconverter` URI as the config file and got the error message that there is no such config file.

**Comment by Dreamacro** [comment]
use Proxy Provider instead https://github.com/Dreamacro/clash/wiki/configuration#proxy-providers

**Comment by woyin** [comment]
My expectation is met by Proxy Provider.
Thanks a lot for your help.
