### ISSUE TITLE
[Bug]fake-ip-filter不生效，依然解析出fake-ip

### ISSUE THREAD

**Issue by skill7899** [Dreamacro/clash#1375]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
fake-ip-filter:
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    # === LAN ===
    - '*.lan'
    - '*.futurespeed.cn'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
```

</details>

### Clash log

```
root@pve:~# nslookup mesu.apple.com 
Server:         192.168.60.110
Address:        192.168.60.110#53

Name:   mesu.apple.com
Address: 198.18.0.207
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
linux clash-linux-amd64-2021.04.08-premium
* 网路环境或拓扑 (network conditions/topology)
旁路
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)
无

### 说明 Description

正常应该解析出真实IP，但是解析出来是face-ip

**Comment by Dreamacro** [comment]
给出 dns 的配置，怀疑是配置格式问题

**Comment by skill7899** [comment]
> 给出 dns 的配置，怀疑是配置格式问题

dns:
  enable: true
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - 'tls://8.8.8.8:853'
  fallback-filter:
    geoip: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:1053

**Comment by Dreamacro** [comment]
@skill7899 你这里面也没有 `fake-ip-filter` 这个字段，当然没有效果了

**Comment by skill7899** [comment]
> @skill7899 你这里面也没有 `fake-ip-filter` 这个字段，当然没有效果了

缩进没对，麻烦了。谢谢
