### ISSUE TITLE
[Feature]log中warning显示来源ip

### ISSUE THREAD

**Issue by xyxu1024** [Dreamacro/clash#1377]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

log日志中提示warning的条目目前没有显示发起请求的来源ip，如：
```
time="2021-04-26T19:39:31+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to obylbuodjncqfyk error: couldn't find ip"
```
这样很难排查是哪个client发起的请求出了问题

### 可能的解决方案 Possible Solution

建议形如info条目
```
time="2021-04-26T19:39:31+08:00" level=warning msg="[TCP] 127.0.0.1:12345  dial DIRECT (match Match/) to obylbuodjncqfyk error: couldn't find ip"
```

**Comment by Dreamacro** [comment]
这个在 premium 的 tracing 里是有完整数据的

**Comment by xyxu1024** [comment]
@Dreamacro wiki页面中收不到tracing，应该如何使用？

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash-tracing
