### ISSUE TITLE
macOS 11.3 enhance mode 模块有问题

### ISSUE THREAD

**Issue by spacexnasa** [Dreamacro/clash#1381]
![image](https://user-images.githubusercontent.com/3109626/116335053-c861f600-a808-11eb-9733-734037e013d1.jpeg)

如图，无论是选
Gvisot 还是 system，只要勾选，系统就无法联网，去掉 Enhance Mode 恢复网络，应该是新系统更改了什么，造成无法使用，麻烦D大看下，谢谢了

**Comment by Dreamacro** [comment]
Auto Interface Detection 换成 clashxiface，检测问题已经修复了，macOS 11.3 路由的 Flag 变了。但是 clashx pro 更新前只能用这个方法解决

**Comment by spacexnasa** [comment]
> Auto Interface Detection 换成 clashxiface，检测问题已经修复了，macOS 11.3 路由的 Flag 变了。但是 clashx pro 更新前只能用这个方法解决

已经正常了，谢谢，等你后续的修复方案，多谢
