### ISSUE TITLE
[Bug]tun网卡无法创建

### ISSUE THREAD

**Issue by swwrww** [Dreamacro/clash#1389]
windows 10 21370.1 体验版 Windows 10 Feature Experience Pack 321.9601.0.3
无法创建tun网卡，tap模式正常
time="2021-05-04T20:53:01+08:00" level=info msg="[Wintun] WintunOpenAdapter: Device object file did not appear: 系统找不到指定的路径。 (Code 0x00000003)"
time="2021-05-04T20:53:01+08:00" level=info msg="[Wintun] OpenDeviceObject: Failed to connect to adapter: 系统找不到指定的路径。 (Code 0x00000003)"
time="2021-05-04T20:53:01+08:00" level=info msg="[Wintun] ForceCloseWintunAdapterHandle: Failed to get adapter object"
time="2021-05-04T20:53:01+08:00" level=info msg="[Wintun] WintunDeleteAdapter: Failed to force close adapter handles"
time="2021-05-04T20:53:01+08:00" level=info msg="[Wintun] CreateAdapter: Creating adapter"
time="2021-05-04T20:53:02+08:00" level=info msg="[Wintun] CreateAdapter: Failed to setup adapter: 操作成功完成。 (Code 0x00000000)"
time="2021-05-04T20:53:02+08:00" level=error msg="Start Tun interface error: Element not found."

**Comment by RtYkk** [comment]
https://git.zx2c4.com/wintun/commit/?id=fb416747dcfb6e53df5d249d07123989e4ddc796
确认下你的 wintun 是新版？两月的 commit 提到了这个，看起来已经修了啊。

> It appears that creation of the device object file might happen asynchronously, so this commit polls for it.

**Comment by swwrww** [comment]
> https://git.zx2c4.com/wintun/commit/?id=fb416747dcfb6e53df5d249d07123989e4ddc796
> 确认下你的 wintun 是新版？两月的 commit 提到了这个，看起来已经修了啊。
> 
> > It appears that creation of the device object file might happen asynchronously, so this commit polls for it.

谢谢,更新到Wintun 0.10.4版本后,可以正常使用了!
