### ISSUE TITLE
[Bug] 对VMESS的zero加密支持不完全（？）

### ISSUE THREAD

**Issue by TheCGDF** [Dreamacro/clash#1390]
- [ x ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [ √ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ x ] 我已经使用 dev 分支版本测试过，问题依旧存在
- [ √ ] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ √ ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

------------------------------------------------------------------

CFW和CFA从url导入带有zero加密的配置时，会提示未知加密方式zero

但是如果手动把配置文件修改为zero的话CFW是可以正常运行的

CFA没试，但ClashX却似乎神奇地解决了这个问题：https://github.com/yichengchen/clashX/issues/501

在CFA开了个[issue](https://github.com/Kr328/ClashForAndroid/issues/985)，被告知是core的问题

（那ClashX是怎么解决的？）

所以我也搞不清楚clash core到底支不支持zero，也所以标题后面加了个问号

**Comment by plutonemhikari** [comment]
我手动改配置也不支持

**Comment by TheCGDF** [comment]
> 我手动改配置也不支持

那可能是我把CFW的用法搞错了
