### ISSUE TITLE
[Bug]1.6.0 无法访问路由器后台。

### ISSUE THREAD

**Issue by ningsibuqu** [Dreamacro/clash#1395]
我发现更新后无法访问我的路由器后台 192.168.2.1
![image](https://user-images.githubusercontent.com/51028975/117560502-f379fe80-b0c0-11eb-8c59-41646445b186.png)
上图是 1.5.0 打开路由器后台

![image](https://user-images.githubusercontent.com/51028975/117560536-29b77e00-b0c1-11eb-9c46-2c52faa7306d.png)
这是 1.6.0 打开路由器后台

好像区别是 1.6.0 中路由器后台访问过了一遍 clash？

**Comment by Fndroid** [comment]
系统代理没有绕过这个内网段吧

**Comment by ningsibuqu** [comment]
> 系统代理没有绕过这个内网段吧

我替换了内核就这样了。

**Comment by OG-C** [comment]
浏览器安全DNS会导致这个情况，你切换个没有开启安全DNS的浏览器测试下

**Comment by wzg1015** [comment]
我也有这个问题. A本地设备通过http 走 B 设备局域网7890进行代理后, 路由器地址打开一直在转. A设备 本地代理则无该问题.

**Comment by HappyQuQu** [comment]
> 浏览器安全DNS会导致这个情况，你切换个没有开启安全DNS的浏览器测试下

我也出现这个问题 试了下关闭安全DNS还是无效
持续关注中

**Comment by HappyQuQu** [comment]
> 我也有这个问题. A本地设备通过http 走 B 设备局域网7890进行代理后, 路由器地址打开一直在转. A设备 本地代理则无该问题.

代理类型改成sock5 就没问题

**Comment by mazimao123** [comment]
去主页里取消掉系统代理，改用tun模式，性能更好

**Comment by lzyest** [comment]
主页里又一个允许lan，把自己局域网地址输入就好，最后一位用*
