### ISSUE TITLE
[Feature] 隐藏 GLOBAL 下的 DIRCET REJECT

### ISSUE THREAD

**Issue by JoinGitHubBa** [Dreamacro/clash#1399]
没什么作用，萌新还容易选到这两个。

**Comment by gzleangle** [comment]
反馈错地方啦，这是Clash core，不带图形界面的。如果是说Clash for Windows的话，Global下的Direct和Reject也是很有用的。

**Comment by JoinGitHubBa** [comment]
图形界面客户端也是读取 Clash Core 的数据。
Global下的Direct和Reject还有什么鲜为人知的用处？

**Comment by ndxx** [comment]
有关这个问题讨论在之前的issue #1205 中有提及，并且Owner对于“全局”的理解也在那个issue中。
