### ISSUE TITLE
bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

### ISSUE THREAD

**Issue by NV3S** [Dreamacro/clash#140]
win10+clash for windows+smart dns on WSL
突然无法走代理，日志提示如下：
`time="2019-03-18T07:09:07+08:00" level=warning msg="Proxy[DIRECT] connect [127.0.0.1 --> mobile.pipe.aria.microsoft.com] error: dial tcp XXXXXXXX:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2019-03-18T07:09:07+08:00" level=warning msg="Proxy[DIRECT] connect [127.0.0.1 --> mobile.pipe.aria.microsoft.com] error: dial tcp XXXXXXXX:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."`

然后试着把smart dns改了一下cachesize后重启了一下，就好了，请问日志这warning是？

**Comment by Dreamacro** [comment]
建立了太多的 socket 连接没有释放，导致不能再建立新的 socket 连接，应该是你本地回环了？

**Comment by NV3S** [comment]
你指的是用loopback吗？

**Comment by Dreamacro** [comment]
对 windows 不太了解，不知道为什么你这里会有这么多的 socket 连接

**Comment by NV3S** [comment]
`
log date:2019-03-21-144519

time="2019-03-21T21:48:06+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
time="2019-03-21T21:48:06+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154.XX.XX] error: 139.196.XX.XX:XXconnect error: dial tcp 139.196.XX.XX:XX: connectex: A socket operation was attempted to an unreachable network."
time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
time="2019-03-22T05:31:21+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154XX.XX] error: 139.196.XX.XX:XX connect error: dial tcp 139.196.XX.XX:XX: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
time="2019-03-22T05:31:21+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154.XX.XX] error: 139.196.XX.XX:XXconnect error: dial tcp 139.196.XX.XX:XX: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"

log date:2019-03-22-060727

time="2019-03-22T06:07:28+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-03-22T06:07:28+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2019-03-22T06:07:28+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2019-03-22T06:07:28+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
`

这两天都有重现，上面日志是"2019-03-21T21:48:06+08:00" 这个时段没有连上wifi，然后把笔记本合上睡眠了；"2019-03-22T05:31:21+08:00" 时唤醒笔记本（没连wifi），已经报错了。
然后重启了CFW，发现程序界面无法加载配置文件（没有改动过），首页无法显示Port、Socket Port等信息。
之后重启系统解决。

**Comment by Fndroid** [comment]
> ```
> 
> log date:2019-03-21-144519
> 
> time="2019-03-21T21:48:06+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> time="2019-03-21T21:48:06+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154.XX.XX] error: 139.196.XX.XX:XXconnect error: dial tcp 139.196.XX.XX:XX: connectex: A socket operation was attempted to an unreachable network."
> time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> time="2019-03-22T05:31:21+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154XX.XX] error: 139.196.XX.XX:XX connect error: dial tcp 139.196.XX.XX:XX: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
> time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> time="2019-03-22T05:31:21+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154.XX.XX] error: 139.196.XX.XX:XXconnect error: dial tcp 139.196.XX.XX:XX: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
> time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> 
> log date:2019-03-22-060727
> 
> time="2019-03-22T06:07:28+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> time="2019-03-22T06:07:28+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> time="2019-03-22T06:07:28+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> time="2019-03-22T06:07:28+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> ```
> 
> 这两天都有重现，上面日志是"2019-03-21T21:48:06+08:00" 这个时段没有连上wifi，然后把笔记本合上睡眠了；"2019-03-22T05:31:21+08:00" 时唤醒笔记本（没连wifi），已经报错了。
> 然后重启了CFW，发现程序界面无法加载配置文件（没有改动过），首页无法显示Port、Socket Port等信息。
> 之后重启系统解决。

@NV3S 升级到最新的Clash for Windows有出现过吗

**Comment by NV3S** [comment]
> > ```
> > 
> > log date:2019-03-21-144519
> > 
> > time="2019-03-21T21:48:06+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> > time="2019-03-21T21:48:06+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154.XX.XX] error: 139.196.XX.XX:XXconnect error: dial tcp 139.196.XX.XX:XX: connectex: A socket operation was attempted to an unreachable network."
> > time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> > time="2019-03-22T05:31:21+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154XX.XX] error: 139.196.XX.XX:XX connect error: dial tcp 139.196.XX.XX:XX: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
> > time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> > time="2019-03-22T05:31:21+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1 --> 149.154.XX.XX] error: 139.196.XX.XX:XXconnect error: dial tcp 139.196.XX.XX:XX: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
> > time="2019-03-22T05:31:21+08:00" level=info msg="127.0.0.1 --> 149.154.XX.XX match IPCIDR using Proxy"
> > 
> > log date:2019-03-22-060727
> > 
> > time="2019-03-22T06:07:28+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> > time="2019-03-22T06:07:28+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> > time="2019-03-22T06:07:28+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> > time="2019-03-22T06:07:28+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> > ```
> > 
> > 
> > 这两天都有重现，上面日志是"2019-03-21T21:48:06+08:00" 这个时段没有连上wifi，然后把笔记本合上睡眠了；"2019-03-22T05:31:21+08:00" 时唤醒笔记本（没连wifi），已经报错了。
> > 然后重启了CFW，发现程序界面无法加载配置文件（没有改动过），首页无法显示Port、Socket Port等信息。
> > 之后重启系统解决。
> 
> @NV3S 升级到最新的Clash for Windows有出现过吗

0.5.35还是有的，重现时候，在General页面，端口和一些配置信息条目不显示。只能通过重启系统解决。

**Comment by Dreamacro** [comment]
能执行一下 `netstat -ano` 来看一下是哪些连接地址没有释放吗

**Comment by NV3S** [comment]
> 能执行一下 `netstat -ano` 来看一下是哪些连接地址没有释放吗

重现时候我抓一下。
我出问题后我加了两个tcp参数在注册表里
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters]

"TcpTimedWaitDelay"=dword:0000001e
"MaxUserPort"=dword:0000fffe

```
用用看。

**Comment by Dreamacro** [comment]
reopen it if happen again
