### ISSUE TITLE
关于 fake-ip 在需要 “判定 A 记录是否存在” 场景下的疑问

### ISSUE THREAD

**Issue by cospotato** [Dreamacro/clash#1401]
当前的 fake-ip 模式会对不属于 `fake-ip-filter` 的地址都返回一个地址，即使 nameserver 中 A 记录不存在，这在某些场景下会出现问题

🌰例子：

1. clash 部署为透明网关
2. k8s 的 node 网关和 DNS 设置为 clash 的地址
3. 在 pod 中访问一个不存在的 svc 地址时，仍会解析得到 fake-ip 段的地址，但其实这个场景下期望返回解析失败

**Comment by Dreamacro** [comment]
fake-ip 在现有的实现下的一个特性是在某些情况下能够节省一次 DNS：应用程序所访问的域名被规则命中，直接走代理。与之相对应的是 redir-host 模式，在这个模式下程序一定会经过某个 DNS 拿到一个记录，再经过 clash 内部映射回对应的域名，这时候无论是不是匹配了规则，都必然会至少有一次 DNS 请求。

但两个模式下都有一些特定的问题：

fakeip:
* 在某些 UDP 的应用中，fakeip 会有干扰作用，导致打洞等行为出现问题
* 在 clash 作为网关的时候，类似 QQ 的快速登录这种与本地进行通信的相关请求（它通过的是域名）会失败
* ssh 的 known host 会记录下不正确的 ip
* 如你举的例子，某些情况下强行返回一个结果会导致意料之外的结果

但 fakeip 在绝大多数情况下都能正常工作，而且就体感而言会比 redir-host 好一些。所以弄了一个 `fake-ip-filter` 的配置用于绕过 fakeip 返回，并且也能够解决绝大多数的问题

redir-host

* DNS 被污染，导致多个域名解析到同一个地址，造成映射错误，访问到了其他域名，这也是有很多 issue 里面浏览器出现证书错误的原因
* 由于通常服务在部署的时候会使用相同一批机器作为网关，所以导致很多域名都会指向同一/多个 ip，这时候映射错误会导致规则匹配的错误，但不影响正常的访问

所以 fakeip + 一个维护的过滤列表是一个最好的选择。两个模式都有自己的问题，可以根据自己的实际情况去选择。对于你提到的这个 k8s 的问题，如果你能知道 k8s 服务发现所返回的域名列表，如 `+.svc.cluster.local` ，加入到 filter list 就行了
