### ISSUE TITLE
[Bug] 切换到不支持 UDP 的节点时，再切换回支持 UDP 的节点，使用旧策略建立的连接因为节点不支持 UDP 而选择直连，新策略应用时不会应用到这些连接

### ISSUE THREAD

**Issue by cielpy** [Dreamacro/clash#1403]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
无
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
OpenWrt
* 网路环境或拓扑 (network conditions/topology)
OpenWrt 作为主路由
* iptables，如果适用 (if applicable)
无关
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无关
* 其他 (any other information that would be useful)
……

### 说明 Description

发现这个问题源于在观看 Youtube 视频时，因为想换到比较快的节点而频繁切换节点后，发现怎么切换节点都没用，始终速度很慢

观察连接情况发现，有一个 UDP 连接走了直连，现象如下

![image](https://user-images.githubusercontent.com/3138493/118152802-b0fd4c80-b447-11eb-9fd6-cf19ac1b59ad.png)

日志中发现，因为切换到了不支持 UDP 的节点，此时若有 UDP 流量会选择直连 https://github.com/Dreamacro/clash/blob/3c54f99fea179ee86220052004870ce430c7638c/tunnel/tunnel.go#L345

换回支持 UDP 的节点后，UDP 连接不会受到影响，依旧直连，最后 Youtube 速度很慢，因为部分 Youtube 节点可以以很慢的速度传输数据

原因猜测，因为 yacd 和 Clash Dashboard 在切换策略时，关闭当前连接选项都是关闭使用当前策略的连接，而由于之前的 UDP 连接已经使用了直连，和当前策略无关，所以不会被关闭，继而造成不能正常访问 Youtube

### 重现问题的具体布骤 Steps to Reproduce

1. 使用支持 UDP 的节点观看  Youtube，要有 UDP 连接在跑数据，并不是所有数据传输都使用 UDP 传输
2. 切换到不支持 UDP 的节点，UDP 连接会走直连
3. 再切回支持 UDP 的节点，UDP 节点依旧是直连，访问缓慢

**我预期会发生……？**

期望可以正常速度访问

**实际上发生了什么？**

不能正常访问 Youtube

### 可能的解决方案 Possible Solution

我想到有几个办法

1. 切换策略时关闭所有连接
2. 切换策略时关闭之前因为不支持 UDP 而建立的连接

第一个办法在 dashboard 侧可以做，比较暴力，第二个需要 clash 记录这些连接，记录的条件是可以匹配到非直连规则，这样在切换策略时可以针对性的断开这些连接

**Comment by Dreamacro** [comment]
如果你用的是 clash.razord.top ，你会看到一个选项叫 `切换时打断包含策略组的连接`

**Comment by cielpy** [comment]
> 如果你用的是 clash.razord.top ，你会看到一个选项叫 `切换时打断包含策略组的连接`

不管用的，问题描述和复现步骤说明了，而且实测打开了 `切换时打断包含策略组的连接` 也是没用的

> 原因猜测，因为 yacd 和 Clash Dashboard 在切换策略时，关闭当前连接选项都是关闭使用当前策略的连接，而由于之前的 UDP 连接已经使用了直连，和当前策略无关，所以不会被关闭，继而造成不能正常访问 Youtube

复现步骤

1. 使用支持 UDP 的节点观看 Youtube，要有 UDP 连接在跑数据，并不是所有数据传输都使用 UDP 传输
2. 切换到不支持 UDP 的节点，UDP 连接会走直连
3. 再切回支持 UDP 的节点，UDP 节点依旧是直连，访问缓慢

因为第 2 步选择了不支持 UDP 的节点，UDP 连接被打断后再重新连接会选择直连，此时再切换回支持 UDP 的节点，这个直连连接不会被打断

**Comment by cielpy** [comment]
![image](https://user-images.githubusercontent.com/3138493/118392162-b2f32580-b66a-11eb-8af4-2d2c56bf8aef.png)

UDP 流量的产生是因为 Youtube 拉视频流时使用了 HTTP/3 协议，在 clash 能正常接收到 UDP 流量且节点支持 UDP 的情况下，Chrome 是可以连接成功的

所以 issue 里提到的问题会很容易出现 

HTTP/3连接建立成功 ----> 换到不支持 UDP 的节点 ----> HTTP/3 重建连接 ---->节点不支持 UDP ----> 选择直连 ----> 切换回支持 UDP 的节点 ----> 重建的直连连接没有使用被切换掉的策略（不支持 UDP 的那个），不会被断开 ----> 视频流拉取继续走直连 ----> 速度很慢
