### ISSUE TITLE
[Bug] 2021.05.08 Premium核心，TUN网卡显示“无网络访问权限”

### ISSUE THREAD

**Issue by returnL** [Dreamacro/clash#1407]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixinText: |-
  mixin: # object
    dns:
      enable: true
      listen: 0.0.0.0:53
      enhanced-mode: fake-ip
      fake-ip-range: 198.18.0.1/16
      fake-ip-filter:
        - "dns.msftncsi.com"
        - "www.msftncsi.com"
        - "www.msftconnecttest.com"
        - "+.qq.com"
        - "+.music.163.com"
        - "+.music.162.com"
        - "*.lan"
        - '*.*.*.*.srv.nintendo.net'
        - '*.*.*.stun.playstation.net'
        - 'xbox.*.microsoft.com'
        - '*.*.*.xboxlive.com'
      nameserver:
        - 114.114.114.114
        - 223.5.5.5
        - 119.29.29.29
    tun:
      enable: true
      stack: gvisor
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      interface-name: WLAN
      #auto-detect-interface: true # 自动检测出口网卡
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows 10 20H2 19042.985
* 网路环境或拓扑 (network conditions/topology)
光猫 - 路由器 - 终端
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)
无

### 重现问题的具体布骤 Steps to Reproduce

1. 2021.05.08 Premium核心，启用TUN模式，Clash网卡显示”IPv4连接：无网络访问权限“
![image](https://user-images.githubusercontent.com/44701395/118398709-6f111800-b68c-11eb-9abd-af7e3d32d50a.png)

2. 注销Microsoft Store登陆的账号，重新登陆，报错如下
![image](https://user-images.githubusercontent.com/44701395/118398694-59035780-b68c-11eb-842f-7fb348954aa2.png)

**我预期会发生……？**

能够正常登陆Microsoft Store

**实际上发生了什么？**

由于网卡显示”无网络访问权限“，微软系应用会以为没有网络，直接报错，实际上是有网的，浏览器中使用体验与04.08 Premium无差异，代理都正常。尝试了多个Clash衍生版本，包括CFW Clash.NET ClashXW，只要使用2021.05.08 Premium核心使用TUN模式都会存在这个问题。

### 可能的解决方案 Possible Solution

退回04.08 Premium

**Comment by Dreamacro** [comment]
`interface-name` 是在顶层的，不是在 tun 里面

**Comment by icpz** [comment]
试一下 fake-ip-filter 中的
'www.msftconnecttest.com' -> '+.msftconnecttest.com'

**Comment by returnL** [comment]
@Dreamacro 我修改了interface-name的位置，或者直接使用auto-detect-interface，网卡依旧实现无网络访问权限

**Comment by returnL** [comment]
> 试一下 fake-ip-filter 中的
> 'www.msftconnecttest.com' -> '+.msftconnecttest.com'

我试了一下，还是不行，Microsoft Store登陆时报错

**Comment by returnL** [comment]
我换回04.08 Premium，``auto-route``改回``macOS-auto-route``，网卡显示如图
![image](https://user-images.githubusercontent.com/44701395/118400481-63c1ea80-b694-11eb-8016-094dbeec9036.png)
Microsoft Store也能正常登陆了，其他设置都没有改

**Comment by icpz** [comment]
方便的话请使用有问题的内核依次尝试以下步骤：
1. enhanced-mode 改为 redir-host 模式
2. 在 clash 启动后在 powershell 或 cmd 中执行 `nslookup dns.msftncsi.com` 并请贴出结果
3. 在 clash 启动后浏览器访问 'http://www.msftconnecttest.com/connecttest.txt' 并贴出结果
4. 可以的话请提供注册表 HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\NlaSvc\Parameters\Internet 下所有键值截图

**Comment by returnL** [comment]
> 方便的话请使用有问题的内核依次尝试以下步骤：
> 
> 1. enhanced-mode 改为 redir-host 模式
> 2. 在 clash 启动后在 powershell 或 cmd 中执行 `nslookup dns.msftncsi.com` 并请贴出结果
> 3. 在 clash 启动后浏览器访问 'http://www.msftconnecttest.com/connecttest.txt' 并贴出结果
> 4. 可以的话请提供注册表 HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\NlaSvc\Parameters\Internet 下所有键值截图

步骤2结果
![image](https://user-images.githubusercontent.com/44701395/118400643-0f6b3a80-b695-11eb-948b-92d38f192334.png)
步骤3结果
![image](https://user-images.githubusercontent.com/44701395/118400656-185c0c00-b695-11eb-9e67-2090773c0274.png)
步骤3结果
![image](https://user-images.githubusercontent.com/44701395/118400688-3fb2d900-b695-11eb-9c3b-d05e5b95eaa5.png)

**Comment by icpz** [comment]
> > 方便的话请使用有问题的内核依次尝试以下步骤：
> > 
> > 1. enhanced-mode 改为 redir-host 模式
> > 2. 在 clash 启动后在 powershell 或 cmd 中执行 `nslookup dns.msftncsi.com` 并请贴出结果
> > 3. 在 clash 启动后浏览器访问 'http://www.msftconnecttest.com/connecttest.txt' 并贴出结果
> > 4. 可以的话请提供注册表 HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\NlaSvc\Parameters\Internet 下所有键值截图
> 
> 步骤2结果
> ![image](https://user-images.githubusercontent.com/44701395/118400643-0f6b3a80-b695-11eb-948b-92d38f192334.png)
> 步骤3结果
> ![image](https://user-images.githubusercontent.com/44701395/118400656-185c0c00-b695-11eb-9e67-2090773c0274.png)
> 步骤3结果
> ![image](https://user-images.githubusercontent.com/44701395/118400764-98827180-b695-11eb-9907-f3fa690e019f.png)

redir-host 模式也显示无网络访问权限么，打开 ms store 之后 clash 有没有相关连接日志

**Comment by returnL** [comment]
![image](https://user-images.githubusercontent.com/44701395/118401796-a508c900-b699-11eb-9cf0-76566f343796.png)
05.08 Premium我放了一段时间没管，IPv4连接会变成 Internet，此时MS Store可以正常登陆（fake-ip模式，配置和最开始一样)

**Comment by returnL** [comment]
@icpz redir-host也还是会显示无网络访问权限，我试下来，不管是fake-ip还是redir-host，只要是无网络访问权限，MS Store就无法登陆
log如下

**Comment by returnL** [comment]
我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，变成了”Internet"

**Comment by icpz** [comment]
> @icpz redir-host也还是会显示无网络访问权限，我试下来，不管是fake-ip还是redir-host，只要是无网络访问权限，MS Store就无法登陆
> log如下
> ```
> ...
> ```

当 win 监测到“无网络权限”，ms store 就不会真正发起请求，包括 onedrive 等微软的服务都是这样。这个行为不是 clash 能够影响的。

开启 clash 后过一段时间才显示为 Internet 说明 clash 刚启动时联网检测失败了，直到第二次检测尝试/网络状态切换（如开关 WLAN）触发了第二次检测才成功。

感谢提供信息，如果您可以继续帮忙 debug 的话还请联系我的邮箱 y@icpz.dev

**Comment by returnL** [comment]
> > @icpz redir-host也还是会显示无网络访问权限，我试下来，不管是fake-ip还是redir-host，只要是无网络访问权限，MS Store就无法登陆
> > log如下
> > ```
> > ...
> > ```
> 
> 当 win 监测到“无网络权限”，ms store 就不会真正发起请求，包括 onedrive 等微软的服务都是这样。这个行为不是 clash 能够影响的。
> 
> 开启 clash 后过一段时间才显示为 Internet 说明 clash 刚启动时联网检测失败了，直到第二次检测尝试/网络状态切换（如开关 WLAN）触发了第二次检测才成功。
> 
> 感谢提供信息，如果您可以继续帮忙 debug 的话还请联系我的邮箱 [y@icpz.dev](mailto:y@icpz.dev)

似乎04.08 Premium的重新检测会更快一点？因为04.08版本我关了TUN再立刻打开，Clash网卡的IPv4连接可以直接变成了”Internet"，而05.08 Premium等待的时间就要长得多

**Comment by icpz** [comment]
> > > @icpz redir-host也还是会显示无网络访问权限，我试下来，不管是fake-ip还是redir-host，只要是无网络访问权限，MS Store就无法登陆
> > > log如下
> > > ```
> > > ...
> > > ```
> > 
> > 
> > 当 win 监测到“无网络权限”，ms store 就不会真正发起请求，包括 onedrive 等微软的服务都是这样。这个行为不是 clash 能够影响的。
> > 开启 clash 后过一段时间才显示为 Internet 说明 clash 刚启动时联网检测失败了，直到第二次检测尝试/网络状态切换（如开关 WLAN）触发了第二次检测才成功。
> > 感谢提供信息，如果您可以继续帮忙 debug 的话还请联系我的邮箱 [y@icpz.dev](mailto:y@icpz.dev)
> 
> 似乎04.08 Premium的重新检测会更快一点？因为04.08版本我关了TUN再立刻打开，Clash网卡的IPv4连接可以直接变成了”Internet"，而05.08 Premium等待的时间就要长得多

是的，可能的原因是 05.08 先检测了 tun 地址的可用性。

请依次尝试以下两个 premium 内核看看有什么区别，上述变化发生在这两次 commit 
https://d7fb25a0.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f9ec9cf.zip
https://9821c3e1.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f90444b.zip

**Comment by returnL** [comment]
https://d7fb25a0.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f9ec9cf.zip 这个内核和04.08类似，重开TUN后很快就能重新检测。
https://9821c3e1.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f90444b.zip 这个和05.08类似，重开TUN后显示“无网络访问权限”

**Comment by icpz** [comment]
> https://d7fb25a0.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f9ec9cf.zip 这个内核和04.08类似，重开TUN后很快就能重新检测。
> https://9821c3e1.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f90444b.zip 这个和05.08类似，重开TUN后显示“无网络访问权限”

感谢反馈，请临时使用这个 binary 吧，里面包括了 05.08 的所有更新以及这个问题的 fix，注意请使用 gvisor 作为 stack 否则还是会有问题。

[clash-windows-amd64.zip](https://github.com/Dreamacro/clash/files/6489539/clash-windows-amd64.zip)

**Comment by returnL** [comment]
> > https://d7fb25a0.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f9ec9cf.zip 这个内核和04.08类似，重开TUN后很快就能重新检测。
> > https://9821c3e1.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f90444b.zip 这个和05.08类似，重开TUN后显示“无网络访问权限”
> 
> 感谢反馈，请临时使用这个 binary 吧，里面包括了 05.08 的所有更新以及这个问题的 fix，注意请使用 gvisor 作为 stack 否则还是会有问题。
> 
> [clash-windows-amd64.zip](https://github.com/Dreamacro/clash/files/6489539/clash-windows-amd64.zip)
> 

好的，十分感谢

**Comment by OG-C** [comment]
> 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"

原来如此

**Comment by OG-C** [comment]
> 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"

我和你不同，我重开WLAN会变成“无internet访问”；开关飞行模式会立刻变成“internet访问”

**Comment by returnL** [comment]
> > 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"
> 
> 我和你不同，我重开WLAN会变成“无internet访问”；开关飞行模式会立刻变成“internet访问”

换core后问题能解决就行了。我是开关WLAN或者开关飞行模式都有用

**Comment by OG-C** [comment]
> > > 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"
> > 
> > 
> > 我和你不同，我重开WLAN会变成“无internet访问”；开关飞行模式会立刻变成“internet访问”
> 
> 换core后问题能解决就行了。我是开关WLAN或者开关飞行模式都有用

请问如何更换core

**Comment by kingforme** [comment]
> > > > 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"
> > > 
> > > 
> > > 我和你不同，我重开WLAN会变成“无internet访问”；开关飞行模式会立刻变成“internet访问”
> > 
> > 
> > 换core后问题能解决就行了。我是开关WLAN或者开关飞行模式都有用
> 
> 请问如何更换core

1.下载旧版本并安装,进入C:\Users\(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64
2.复制目录下所有文件到其他盘
3.安装新版并退出,将旧版本core复制进C:\Users\(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64

**Comment by returnL** [comment]
> > > > > 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"
> > > > 
> > > > 
> > > > 我和你不同，我重开WLAN会变成“无internet访问”；开关飞行模式会立刻变成“internet访问”
> > > 
> > > 
> > > 换core后问题能解决就行了。我是开关WLAN或者开关飞行模式都有用
> > 
> > 
> > 请问如何更换core
> 
> 1.下载旧版本并安装,进入C:\Users(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64
> 2.复制目录下所有文件到其他盘
> 3.安装新版并退出,将旧版本core复制进C:\Users(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64

只要换`clash-win64.exe`就行了，用不着安装旧版再装新版这么麻烦

**Comment by OG-C** [comment]
> > > > > 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"
> > > > 
> > > > 
> > > > 我和你不同，我重开WLAN会变成“无internet访问”；开关飞行模式会立刻变成“internet访问”
> > > 
> > > 
> > > 换core后问题能解决就行了。我是开关WLAN或者开关飞行模式都有用
> > 
> > 
> > 请问如何更换core
> 
> 1.下载旧版本并安装,进入C:\Users(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64
> 2.复制目录下所有文件到其他盘
> 3.安装新版并退出,将旧版本core复制进C:\Users(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64

我的主目录是C:\Users\用户名\.config\clash

**Comment by returnL** [comment]
> > > > > > 我发现连接WLAN的情况下，关闭TUN并立刻重新打开，短时间内还是显示”无网络访问权限“（具体过多久会变成Internet我暂时还不知道）。此时在打开TUN的情况下，关闭WLAN再重开，Clash网卡的IPv4连接就不再是”无网络访问权限“，立刻变成了”Internet"
> > > > > 
> > > > > 
> > > > > 我和你不同，我重开WLAN会变成“无internet访问”；开关飞行模式会立刻变成“internet访问”
> > > > 
> > > > 
> > > > 换core后问题能解决就行了。我是开关WLAN或者开关飞行模式都有用
> > > 
> > > 
> > > 请问如何更换core
> > 
> > 
> > 1.下载旧版本并安装,进入C:\Users(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64
> > 2.复制目录下所有文件到其他盘
> > 3.安装新版并退出,将旧版本core复制进C:\Users(替换为你的用户名)\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64
> 
> 我的主目录是C:\Users\用户名.config\clash

那个只是配置文件的位置，核心不在那里

**Comment by CalmLong** [comment]
麻烦能发个完整的配置和步骤吗，我按上面操作了几次，一直都是 Clash 无法连接到 Internet，WIFI 开关和开飞行模式都没用，也更换 上面的 Clash 了，Win10 21H1

**Comment by kingforme** [comment]
1.打开clash,在任务管理器找到名为clash-win64.exe的进程,右键打开文件所在位置
2.下载旧版本核心（ 版本2021.04.08 ）
[clash-win64.zip](https://github.com/Dreamacro/clash/files/6558355/clash-win64.zip)
3.解压拖拽替换即可

**Comment by returnL** [comment]
> > https://d7fb25a0.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f9ec9cf.zip 这个内核和04.08类似，重开TUN后很快就能重新检测。
> > https://9821c3e1.clash-premium-nightly.pages.dev/clash-windows-amd64-nightly-f90444b.zip 这个和05.08类似，重开TUN后显示“无网络访问权限”
> 
> 感谢反馈，请临时使用这个 binary 吧，里面包括了 05.08 的所有更新以及这个问题的 fix，注意请使用 gvisor 作为 stack 否则还是会有问题。
> 
> [clash-windows-amd64.zip](https://github.com/Dreamacro/clash/files/6489539/clash-windows-amd64.zip)

@icpz 这个binary我最近发现一个问题，我使用CFW的Mixin来实现TUN模式，关闭Mixin后，TUN模式关闭，Clash网卡却有概率无法关闭，等待几分钟后网卡依旧存在，导致无法上网

**Comment by ameyukisora** [comment]
台式机win10 21H1，cfw0.15.10替换了上面提供的core重启后TUN网卡依然显示“无网络访问权限”，物理拔网线后只剩下TUN网卡就显示Internet连接了（很神奇，明明物理拔线了反而显示正常），再插上网线后TUN网卡与物理网卡就都正常了。配置文件：

  ```yaml
  mixed-port: 7890
  allow-lan: true
  mode: Rule
  log-level: info
  external-controller: :9090
  experimental:
    ignore-resolve-fail: true
  dns:
    enable: true
    ipv6: false
    enhanced-mode: redir-host
    default-nameserver:
      - 119.29.29.29
      - 223.5.5.5
    nameserver:
      - https://doh.pub/dns-query
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
```

**Comment by WOSHIZHAZHA120** [comment]
导入此 [注册表](https://github.com/Dreamacro/clash/files/7804936/Windows_Network_Fix.zip) 貌似可以临时修复问题
记得备份注册表: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet
来源: https://www.bilibili.com/video/BV1v44y1x7zM

**Comment by returnL** [comment]
> 导入此 [注册表](https://github.com/Dreamacro/clash/files/7804936/Windows_Network_Fix.zip) 貌似可以临时修复问题
> 记得备份注册表: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet
> 来源: https://www.bilibili.com/video/BV1v44y1x7zM

你说的这个问题是Windows的，开不开clash都会这样。两个问题虽然造成的结果看起来很像，但并不是同一个原因

**Comment by WOSHIZHAZHA120** [comment]
> > 导入此 [注册表](https://github.com/Dreamacro/clash/files/7804936/Windows_Network_Fix.zip) 貌似可以临时修复问题
> > 记得备份注册表: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet
> > 来源: https://www.bilibili.com/video/BV1v44y1x7zM
> 
> 你说的这个问题是Windows的，开不开clash都会这样。两个问题虽然造成的结果看起来很像，但并不是同一个原因

哦哦，我主要是解决部分应用使用windows网络状态会导致没网的问题 比如微软商店

**Comment by lisansas** [comment]
> 台式机win10 21H1，cfw0.15.10替换了上面提供的core重启后TUN网卡依然显示“无网络访问权限”，物理拔网线后只剩下TUN网卡就显示Internet连接了（很神奇，明明物理拔线了反而显示正常），再插上网线后TUN网卡与物理网卡就都正常了。配置文件：
> 
> ```yaml
> mixed-port: 7890
> allow-lan: true
> mode: Rule
> log-level: info
> external-controller: :9090
> experimental:
>   ignore-resolve-fail: true
> dns:
>   enable: true
>   ipv6: false
>   enhanced-mode: redir-host
>   default-nameserver:
>     - 119.29.29.29
>     - 223.5.5.5
>   nameserver:
>     - https://doh.pub/dns-query
> tun:
>   enable: true
>   stack: gvisor
>   dns-hijack:
>     - 198.18.0.2:53
>   auto-route: true
>   auto-detect-interface: true
> ```

感谢，同样的问题，我也是台式机，试了几乎所有的办法都没搞定，把网线拔了再插上去好了。

**Comment by erbanku** [comment]
Windows 11 中遇到类似问题，从 https://release.dreamacro.workers.dev/ 下载最新版 Clash Core，并按照 https://github.com/Dreamacro/clash/issues/1407#issuecomment-850137368 替换后解决了，感谢。

**Comment by pg-adm1n** [comment]
开启飞行模式 然后再关闭 就可以了, 不过变成每次开机都需要这样的操作

**Comment by erbanku** [comment]
> Windows 11 中遇到类似问题，从 [release.dreamacro.workers.dev](https://release.dreamacro.workers.dev/) 下载最新版 Clash Core，并按照 [#1407 (comment)](https://github.com/Dreamacro/clash/issues/1407#issuecomment-850137368) 替换后解决了，感谢。

我在每次更新Clash版本后进行一次这个操作就完美解决，但每次更新会失效，或许比每次开机重复此操作会方便很多。

**Comment by pg-adm1n** [comment]
话说这个问题没有最终解决噢. 即便现在内核已经到了 2022.11.25 依然还有这个问题

**Comment by erbanku** [comment]
> 话说这个问题没有最终解决噢. 即便现在内核已经到了 2022.11.25 依然还有这个问题

用`latest`里面的`clash-windows-amd64-latest.zip`，替换可解决。

**Comment by RealGuruiwen** [comment]
> > 话说这个问题没有最终解决噢. 即便现在内核已经到了 2022.11.25 依然还有这个问题
> 
> 用`latest`里面的`clash-windows-amd64-latest.zip`，替换可解决。 链接：https://release.dreamacro.workers.dev/

我在替换内核后出现了服务模式安装不了的问题，请问您有遇到这样的情况吗？

**Comment by erbanku** [comment]
> > > 话说这个问题没有最终解决噢. 即便现在内核已经到了 2022.11.25 依然还有这个问题
> > 
> > 
> > 用`latest`里面的`clash-windows-amd64-latest.zip`，替换可解决。 链接：[release.dreamacro.workers.dev](https://release.dreamacro.workers.dev/)
> 
> 我在替换内核后出现了服务模式安装不了的问题，请问您有遇到这样的情况吗？

我也安装不了，但是完全没收到影响，正常用。

**Comment by ausar47** [comment]
一样的问题，得先开clash再连接网络才能成功

**Comment by leic4u** [comment]
> 话说这个问题没有最终解决噢. 即便现在内核已经到了 2022.11.25 依然还有这个问题

在 Clash for Windows 的 TUN Mode 设置里面，把 TUN Stack 改为 `system` 即可。
