### ISSUE TITLE
市场是否有iOS版本的需求

### ISSUE THREAD

**Issue by UnivexDont** [Dreamacro/clash#1408]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------
目前市场有安卓、windows和MAC版本，iOS都是用的Shadowrocket，加入开发一个iOS版本是否有市场需求，市场需求大嘛？

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

**Comment by spacexnasa** [comment]
多一种选择也可以的

**Comment by yonheng** [comment]
有ios的clash还是不错的

**Comment by coooliang** [comment]
shadowrocket收费

**Comment by Tenk2050** [comment]
想要

**Comment by disburden** [comment]
想要，我希望能全平台统一用一个软件

**Comment by Wrandz** [comment]
IOS上面有stash和choc，用的就是这个clash的核
