### ISSUE TITLE
[Feature] Proxy Providers兼容V2RAYN订阅地址

### ISSUE THREAD

**Issue by Hinlavic** [Dreamacro/clash#1409]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Windows
* 使用者的操作系统 (the OS running on the client)
Windows

### 说明 Description

由于历史原因，V2RAYN使用广泛，大多数机场提供的都是符合V2RAYN要求的订阅地址；虽然CLASH提供了Proxy Providers这个方便的功能，但却无法使用。
V2RAYN订阅地址通过两层base64编码将不同类型的服务器信息编码到一个地址中。
[订阅功能说明](https://github.com/2dust/v2rayN/wiki/%E8%AE%A2%E9%98%85%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E)
[分享链接格式说明(ver 2)](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))
联系过机场，机场表示不会提供CLASH地址！
### 可能的解决方案 Possible Solution

对于采用base64编码的订阅地址，按V2RAYN格式解码。

**Comment by Dreamacro** [comment]
同样不会提供其他软件的订阅格式支持
