### ISSUE TITLE
Overlong log when connection fails

### ISSUE THREAD

**Issue by littlef0x** [Dreamacro/clash#141]
I use Clash for Windows(0.5.28, with dev branch of Clash) as my client and the default log level is info. It is useful to debug sometimes, but I find occasionally that there's a 708MB log file. Clash generated about 5540000 'connect [127.0.0.1 --> xxx.com] error: xxx.xxx connect error' messages in 2 hours, about 800 per second, for the same domain. I cannot remember what I was doing at that time. Maybe it's a server failure. But it's kind of bothering. Do you have any idea to deal with that? For example, limit the log frequency for each domain? Thanks.

**Comment by Dreamacro** [comment]
Logs are used to locate the cause of the problem. It is unusual to write a lot of logs here. You should try to solve the problem instead of get-out it, isn't it?

please provide more detail log to locate the root cause.

**Comment by littlef0x** [comment]
Yes, I agree.

I found another large log file since the 708MB one is not at hand now. [Here](https://gist.github.com/littlef0x/6f447b54892479b78cc5e1bed7829efb) is the Clash log along with Caddy log during the same time(I use Caddy+V2Ray on the server side). Irrelevant logs were ommited.
 
As you see, 19:19 was the system startup time. Then Clash tried to connect activity.windows.com via 'Blocked' proxy group. The first time it succeeded at 19:19:20,  but then failed, and generated over 120000 lines of error messages within 3 minutes. Then the connection went back to normal at 19:24:56. xxx.xxx.xxx is the masked server domain.

As for Caddy, it did not receive request from my PC(websocket) during that time, but it recieved request from mobile phone(h/2, different path). Meanwhile, I have service monitor on the server side, so it can be excluded that the server was down or Caddy/V2Ray service was down. I think the failure was due to network disturbance. 

I've no idea whether it is a Clash bug or the system did connect to server at such a frequency. If it is the latter I think it maybe acceptable to limit the log frequency since thousands of repeating logs makes no sense.

**Comment by Dreamacro** [comment]
Is this still happening in recent?

**Comment by littlef0x** [comment]
No, I guess. I checked the recent one week's logs in both of my computers and found nothing like this. It happened at least 3 times in March. Since CFW deletes logs regularly, I've no idea whether it happens after then.

**Comment by Dreamacro** [comment]
ok, if it happens again, you can reopen this issue.

**Comment by littlef0x** [comment]
Well, it occured yesterday, lasted for about 5 hours and generated a 1.8 GB log file with over 14,660,000 lines. Still, the content is:

> time="2019-05-20Txx:xx:xx+08:00" level=warning msg="Proxy[Default] connect [127.0.0.1 --> activity.windows.com] error: xxx.xxx.xxx:443 connect error"
> time="2019-05-20Txx:xx:xx+08:00" level=info msg="127.0.0.1 --> activity.windows.com match MATCH using Default"

BTW, I found another log file with about 90,000 lines of such error, which seems to be a DNS server disturbance:

> time="2019-05-16Txx:xx:xx+08:00" level=info msg="127.0.0.1 --> activity.windows.com match MATCH using Default"
> time="2019-05-16Txx:xx:xx+08:00" level=warning msg="Proxy[Default] connect [127.0.0.1 --> activity.windows.com] error: dial tcp: lookup activity.windows.com: no such host"

It seems that Windows send requests to activity.windows.com frequently. And when there's a network disturbance, it will retry at an extremely high frequency, and generate such large logs.

Windows 10 1809, version 17763.503, CFW v0.5.35

**Comment by Dreamacro** [comment]
I don't familiar with Windows, but clash won't retry by itself. All the request initiated by Windows and at that time there was no network. So I guess it was `hibernated`? I don't know what effect `hibernate` will have on clash. maybe @Fndroid would know.

**Comment by Fndroid** [comment]
@littlef0x 

I think you should proxy ``DOMAIN-SUFFIX,windows.com``.

DIRECT or REJECT might cause loop retry.

**Comment by littlef0x** [comment]
@Fndroid Thanks for your reply. When I found this issue, windows.com was in group Blocked, which means it will always use proxy. According to caddy log, the server didn't receive request from CFW when this problem occured. So I guess adding it to proxy list may not help.
But I've got an idea just now. How about adding activity.windows.com to the cfw-bypass part in config.yml?

**Comment by Fndroid** [comment]
> @Fndroid Thanks for your reply. When I found this issue, windows.com was in group Blocked, which means it will always use proxy. According to caddy log, the server didn't receive request from CFW when this problem occured. So I guess adding it to proxy list may not help.
> But I've got an idea just now. How about adding activity.windows.com to the cfw-bypass part in config.yml?

This might works

**Comment by littlef0x** [comment]
@Dreamacro Do you mean the auto hibernation function of Windows? I guess it cannot account for this issue since I've disabled auto hibernation. Moreover, I always leave my computer on at night, but this issue doesn't occur frequently. I prefer to ascribe it to network disturbance.

**Comment by littlef0x** [comment]
@Fndroid OK, I'll try it. And if it occurs again, I'll let you know.
