### ISSUE TITLE
DNS request timed out

### ISSUE THREAD

**Issue by wzy461143268** [Dreamacro/clash#1414]
mixin:
  dns:
    enable: true                   # set true to enable dns (default is false)
    ipv6: false                    # default is false
    enhanced-mode: redir-host      # or fake-ip
    use-hosts: true                # lookup hosts and return IP record
    nameserver:
      - 119.29.29.29
      - 119.28.28.28
      - 1.0.0.1
      - 114.114.114.114
    fallback:                      # concurrent request with nameserver, 
      - tls://dns.rubyfish.cn:853
  interface-name: WLAN
  tun:
    enable: true
    stack: system
    dns-hijack:
      - 8.8.8.8:53
      - tcp://8.8.8.8:53
    auto-route: true

mixin配置如上，powershell nslookup命令输出如下。
PS C:\Users\wy461> nslookup baidu.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  198.18.0.2

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时

实测tun是已经起到作用了，部分不走系统udp流量被接管了，部分不走系统代理的软件也能正常被代理。
clash日志nslookup命令没有dns查询记录，浏览器浏览网页能看到对应网址查询记录。
![image](https://user-images.githubusercontent.com/47234030/119079303-6e7cd680-ba2a-11eb-84c0-4c92f67bb616.png)
clash网卡状态正常

**Comment by icpz** [comment]
windows 下需要 hijack 198.18.0.2

**Comment by wzy461143268** [comment]
> windows 下需要 hijack 198.18.0.2

我改成hijack: -192.18.0.2:53
并没有解决这个问题

**Comment by icpz** [comment]
> > windows 下需要 hijack 198.18.0.2
> 
> 我改成hijack: -192.18.0.2:53
> 并没有解决这个问题

是 198.18.0.2 不是 192.18.0.2

**Comment by wzy461143268** [comment]
> > > windows 下需要 hijack 198.18.0.2
> > 
> > 
> > 我改成hijack: -192.18.0.2:53
> > 并没有解决这个问题
> 
> 是 198.18.0.2 不是 192.18.0.2

dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8 # 真实请求DNS，可多设置几个
    - 114.114.114.114
# interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true # 自动检测出口网卡
这份配置可以直接用，原配置即使监听198.18.0.2也不行。
