### ISSUE TITLE
Clash and ICMP [Bug]

### ISSUE THREAD

**Issue by stupicode** [Dreamacro/clash#1416]
Clash stop working after my home ISP block the ICMP. ( I can't ping to anywhere )

It's work on mobile network. ICMP protocol is open.
 Any help ?

**Comment by icpz** [comment]
Clash is NOT an ICMP proxy. It only supports proxy TCP/UDP traffic.

**Comment by stupicode** [comment]
I think it's stop working because can't check connection, etc ping, latency...
Client : [ Clash core 2021.05.08 / clash for windows 0.15.7 ]

**Comment by icpz** [comment]
Could you please be more specific about "check connection"? Does this issue https://github.com/Dreamacro/clash/issues/1407 addresses your problem?
