### ISSUE TITLE
docker clash如何取消内置dns

### ISSUE THREAD

**Issue by yhsmer** [Dreamacro/clash#1419]
我在centos7上安装了docker版的clash并在~/.bashrc中配置代理之后，hosts失效了，看之前的issues发现是内置dns的问题，但是我无法在docker容器中找到如何取消内置dns

/ # cat ~/.config/clash/config.yaml 
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: 
dns:
    enable: false
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query']
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }

**Comment by ArchGuyWu** [comment]
你把dns:连同下面的内容删掉应该就可以了，这些内容不存在时会默认禁用内置dns

**Comment by ArchGuyWu** [comment]
你把dns:连同下面的内容删掉应该就可以了，这些内容不存在时会默认禁用内置dns

**Comment by yhsmer** [comment]
> 你把dns:连同下面的内容删掉应该就可以了，这些内容不存在时会默认禁用内置dns

![image](https://user-images.githubusercontent.com/43242838/119435584-fe818f80-bd4c-11eb-98d2-28e51ce72859.png)
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: 
proxies:
我尝试这样做了，但是并不起作用
