### ISSUE TITLE
[Bug]开启TUN再开启热点会导致断网

### ISSUE THREAD

**Issue by OG-C** [Dreamacro/clash#1420]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 我已经使用 dev 分支版本测试过，问题依旧存在
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

### 环境 Environment

WIN10 20H2
WIFI

### 说明 Description
PC开启TUN功能后，再开启热点会导致断网

### 重现问题的具体布骤 Steps to Reproduce

1. [开启TUN]
2. [开启WIN系统的“移动热点”功能]
3. [断网]

**Comment by RtYkk** [comment]
Fndroid/clash_for_windows_pkg#1444
