### ISSUE TITLE
节点自动选择失效，需手动指定节点[Bug]

### ISSUE THREAD

**Issue by yflwz** [Dreamacro/clash#1426]
系统：ubuntu20.04 lst
clash版本：1.5.0 and 1.6.0
config:
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 192.168.5.252:9090

  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300

在策略组中节点的选择如果是自动选择节点，访问不了google等墙外网站，国内等其他访问正常；
手动选择节点后墙内墙外都可正常访问。

**Comment by sxueck** [comment]
请将log-level等级设置为debug，将日志传上来供分析
