### ISSUE TITLE
[Bug] external-ui JavaScript MIME type error

### ISSUE THREAD

**Issue by LR7SKQUO** [Dreamacro/clash#1428]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: debug
external-controller: '127.0.0.1:9090'
external-ui: clash-dashboard-gh-pages
```

</details>

### Clash log

```
C:\Users\11111111\Tools\clashcore>clash-core -d .\Profile
time="2021-05-27T12:07:57+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-05-27T12:07:57+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Win10 Pro 1909 (OS Build 18363.1556)
* 网路环境或拓扑 (network conditions/topology)
irrelevant
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
irrelevant
* 其他 (any other information that would be useful)
Clash v1.6.0 windows amd64 with go1.16.3 Sat May  8 11:30:51 UTC 2021
chrome 90.0.4430.212 (Official Build) (64-bit)
firefox 88.0.1 (64-bit)

### 说明 Description

when the browser accessing clash dashboard (https://github.com/Dreamacro/clash-dashboard) hosted by clash core, only a blank page appears. checking the console of the browser' web dev tools, two warning messages:
```
vendor.8b5c8dcc.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
index.c70f54c3.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### 重现问题的具体布骤 Steps to Reproduce

1. download the [Profile.zip](https://github.com/Dreamacro/clash/files/6551340/Profile.zip) and extract into a local folder, then put clash core exe file into the parent folder
```bash
│  clash-core.exe
│
└─Profile
    │  config.yaml
    │  Country.mmdb
    │
    └─clash-dashboard-gh-pages
        │  CNAME
        │  index.html
        │
        └─assets
                index.bcc2628f.css
                index.c70f54c3.js
                logo.b453e72f.png
                vendor.8b5c8dcc.js
```
2. in the parent folder, run "clash-core -d .\Profile"
3. using chrome/firefox to access http://127.0.0.1:9090/ui/, you should get a blank page. check the web developer tools, there will be warning messages in console tab.

**我预期会发生……？**

the dashboard shows correctly

**实际上发生了什么？**

only a blank page

**Comment by Dreamacro** [comment]
Cannot be reproduced on the latest version

```yaml
external-controller: 127.0.0.1:9999
external-ui: clash-dashboard-gh-pages
```

**Comment by Fndroid** [comment]
Cannot be reproduced too.
Try access it through a incognito window?

**Comment by ysc3839** [comment]
This is likely your system's issue. Because golang read mime type from Windows registry. Maybe somebody changed the mime type in registry.
https://github.com/golang/go/issues/32350#issuecomment-525122172

**Comment by LR7SKQUO** [comment]
> This is likely your system's issue. Because golang read mime type from Windows registry. Maybe somebody changed the mime type in registry.
> [golang/go#32350 (comment)](https://github.com/golang/go/issues/32350#issuecomment-525122172)

@ysc3839 is correct. In my computer, the mime type from win reg is not correct:
```
C:\Users\11111111>reg query HKCR\.js /v "Content Type"

HKEY_CLASSES_ROOT\.js
    Content Type    REG_SZ    text/plain
```

I checked some other PCs, there is no "Content Type" for this ".js" in win10 by default. And on these PCs, there is no problem.
```
C:\Users\11111111>reg query HKCR\.js /v "Content Type"


ERROR: The system was unable to find the specified registry key or value.
```

once I remove the "Content Type" registry from HKCR\.js, the problem solved.

Thank you for all your support.
