### ISSUE TITLE
crash in ubuntu 18.04

### ISSUE THREAD

**Issue by chinanoahli** [Dreamacro/clash#143]
here was the crash log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8114cfd]

goroutine 71 [running]:
net.networkNumberAndMask(0x0, 0x4, 0x4, 0x9dce34c, 0x4, 0x4, 0x4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/ip.go:477 +0x1d
net.(*IPNet).Contains(0x0, 0x9dce34c, 0x4, 0x4, 0x4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/ip.go:501 +0x25
github.com/Dreamacro/clash/rules.(*IPCIDR).IsMatch(0x9e5d980, 0x987a0c0, 0x9e5d980)
	/home/travis/gopath/src/github.com/Dreamacro/clash/rules/ipcidr.go:27 +0x57
github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0x987a390, 0x987a0c0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:179 +0x118
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0x987a390, 0x845d000, 0x9ed2000)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:135 +0x3f7
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:93 +0x7e
```

First my user name was not `travis`, second I tried i386 and x64 version, both crashed.
And I did try different versions, they all crashed.

**Comment by Dreamacro** [comment]
There must be something wrong with your `IP-CIDR` or `SOURCE-IP-CIDR` payload, but this crash was unexpected, I would fix it later.

For solving your issue, please check out your `Rule`.

**Comment by zhaibin18** [comment]
I have the same error,here is my rule:

Rule:
- DOMAIN-SUFFIX,google.com,Proxy
- DOMAIN-KEYWORD,google,Proxy
- DOMAIN,google.com,Proxy
- DOMAIN-SUFFIX,ad.com,REJECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT

- GEOIP,CN,DIRECT
# FINAL would remove after prerelease
# you also can use `FINAL,Proxy` or `FINAL,,Proxy` now
- MATCH,Proxy

**Comment by zhaibin18** [comment]
I have error below:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x52f823]

goroutine 28 [running]:
github.com/Dreamacro/clash/constant.(*Metadata).String(0xc0000909b0, 0x10, 0x10)
        /home/travis/gopath/src/github.com/Dreamacro/clash/constant/metadata.go:45 +0x33
github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc000090460, 0xc0000909b0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:181 +0x3b5
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc000090460, 0x8f0560, 0xc0001660a0)
        /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:135 +0x51c
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
        /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:93 +0x93

**Comment by Dreamacro** [comment]
@zhaibin18 Are you using the latest version?

**Comment by zhaibin18** [comment]
@Dreamacro Yes, I download from github today.

**Comment by beyondkmp** [comment]
> I have error below:
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x52f823]
> 
> goroutine 28 [running]:
> github.com/Dreamacro/clash/constant.(*Metadata).String(0xc0000909b0, 0x10, 0x10)
> /home/travis/gopath/src/github.com/Dreamacro/clash/constant/metadata.go:45 +0x33
> github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc000090460, 0xc0000909b0, 0x0, 0x0, 0x0, 0x0)
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:181 +0x3b5
> github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc000090460, 0x8f0560, 0xc0001660a0)
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:135 +0x51c
> created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:93 +0x93

You also run clash in ubuntu 18.04?

**Comment by chinanoahli** [comment]
It there any possible to create a configure file syntax checker for clash, I still remembered I was trying to create a script to auto generate configure file using ipdeny.com's IP zone file by awk, there are some empty lines.
That makes some line in the configure file looks like this:
```
- IP-CIDR,,Proxy
- IP-CIDR,,Proxy
``` 
clash keep crashed that time, so that I had to read the configure file line by line, because clash can not tell which line was wrong, that make me CRAZY!!

**Comment by Dreamacro** [comment]
@chinanoahli It will be fixed in the next release.

**Comment by zhaibin18** [comment]
> I have error below:
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x52f823]
> 
> goroutine 28 [running]:
> github.com/Dreamacro/clash/constant.(*Metadata).String(0xc0000909b0, 0x10, 0x10)
> /home/travis/gopath/src/github.com/Dreamacro/clash/constant/metadata.go:45 +0x33
> github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc000090460, 0xc0000909b0, 0x0, 0x0, 0x0, 0x0)
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:181 +0x3b5
> github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc000090460, 0x8f0560, 0xc0001660a0)
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:135 +0x51c
> created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:93 +0x93

I find that if a iphone use the http proxy with system setting,clash randomly crash.

**Comment by Dreamacro** [comment]
@chinanoahli added valid check on dev branch

**Comment by chinanoahli** [comment]
> @chinanoahli added valid check on dev branch

It worked! At least I can know which line was wrong!
