### ISSUE TITLE
[Bug] server为域名而不是ip的节点在clash启动后自动的health check失败，但是手动的成功

### ISSUE THREAD

**Issue by Victor2333** [Dreamacro/clash#1430]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
proxys:
  - {name: "🇲🇾 专线 马来西亚 B2 [3.5x | PCCW]", server: a.b.c.d.node.cyou, port: 8071, type: ssr, cipher: ********, password: *****, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: ************, obfs-param: ****************, udp: true}
  - {name: "🇭🇰 深港专线[倍率:2.5]", server: 1.2.3.4, port: 14286, type: ss, cipher:*****************, password: *******, plugin: obfs, plugin-opts: {mode: http, host: wns.windows.com}, udp: true}
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Ubuntu
* 网路环境或拓扑 (network conditions/topology)
旁路有
* iptables，如果适用 (if applicable)
#!/usr/bin/env bash

#ip tuntap add mode tun user root name utun
#ip link set utun up

while ! ip address show "utun" > /dev/null; do
        sleep 1
done

ip rule add fwmark 120 table 101
ip route add default dev utun table 101

iptables -t mangle -N clash
iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A clash -j MARK --set-xmark 120

iptables -t mangle -A PREROUTING -s 192.168.0.0/16 -j clash

### 重现问题的具体布骤 Steps to Reproduce

1. 启动clash cmd: clash -d .
2. ui页面查看url test情况
3. host 为 域名的所有的health check全都超时失败，当把域名换成ip地址，health check成功，在ui页面上点击测试，域名的server也能测试成功。

**我预期会发生……？**

在服务重启后，能供自动healtch check domain name 作为server的节点
**实际上发生了什么？**

![image](https://user-images.githubusercontent.com/20839187/119943356-84a80b00-bfc5-11eb-986e-f9f0f7018173.png)
灰色的节点是server为域名而不是ip的节点，但是点击右上角的icon可以成功health check.
点击hc icon后的结果:
![image](https://user-images.githubusercontent.com/20839187/119943808-1ca5f480-bfc6-11eb-82b1-1986a5058141.png)

**Comment by Victor2333** [comment]
Not an issue. 看起来是节点的问题。

**Comment by juewuy** [comment]
我也遇见了类似的问题
手动点击dashboard上的测速后一部分节点变可用，如果不点击则始终显示为不可用
但是手动切换到实际可用的节点，实际一样是可用的

**Comment by Victor2333** [comment]
> 我也遇见了类似的问题
> 手动点击dashboard上的测速后一部分节点变可用，如果不点击则始终显示为不可用
> 但是手动切换到实际可用的节点，实际一样是可用的

我也是，但过段时间就好了。启动的时候也是不好的。

**Comment by juewuy** [comment]
怀疑是性能问题，同样配置文件使用armv7或x86的内核就没问题
使用7620单核CPU的mipsle内核就会出现问题
