### ISSUE TITLE
[Bug]script rule_providers 匹配次序

### ISSUE THREAD

**Issue by Olivercoco** [Dreamacro/clash#1432]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```script:
  code: |
    def main(ctx, metadata):
        port_list = [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8888, 8889]
        ruleset_action = {"Reject": "AdBlock",
            "Special": "DIRECT",
            "PROXY": "Proxy",
            "Domestic": "Domestic",
            "Domestic IPs": "Domestic",
            "LAN": "DIRECT"
            }
        port = int(metadata["dst_port"])

        if port not in port_list:
            return "DIRECT"

        for rule_name in ctx.rule_providers.keys():
            if ctx.rule_providers[rule_name].match(metadata):
                return ruleset_action[rule_name]

        ip = metadata["dst_ip"] or ctx.resolve_ip(metadata["host"])

        if ip == "":
          return "DIRECT"

        code = ctx.geoip(ip)

        if code == "CN":
          return "Domestic"

        return "Others"
……
```

</details>

### Clash log

```
time="2021-05-29T15:50:53+08:00" level=info msg="[Script] matched PROXY"
time="2021-05-29T15:50:53+08:00" level=info msg="[TCP] 127.0.0.1:13941 --> mtalk.google.com using Proxy by Script"
time="2021-05-29T15:50:53+08:00" level=info msg="[Script] matched Special"
time="2021-05-29T15:50:53+08:00" level=info msg="[TCP] 127.0.0.1:1433 --> mtalk.google.com using DIRECT by Script"
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows 10 1809
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

PROXY/Special都是rule_providers。Special在前，mtalk.google.com如果按次序应该是直连，但实际上会随机匹配到不同结果。

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by Dreamacro** [comment]
这是因为 map/dictionary 是无序的吧，我不太清楚在 python 里面字典是不是也是无序的，但是在 go 里面 map 就是无序的，所以 key 遍历出来很可能就不一样了。

可以使用 tuple 数组来保证顺序

**Comment by mwhds97** [comment]
避免使用 ctx.rule_providers.keys() 即可。经最新的 clash core 测试，手动定义的 dict 是有序的，例如上述 config.yaml 中的 ruleset_action
