### ISSUE TITLE
[Bug] macOS 11.4 ClashX 突然无法打开

### ISSUE THREAD

**Issue by georgezouq** [Dreamacro/clash#1444]
### 说明 Description

昨天下午 ClashX突然无法打开，弹出报错 Fail on launch protect，You origin Config has been renamed 后自动退出：

我用的远程地址订阅，不确定是否由于远程配置文件改变导致了问题。尝试删除 ～/.config/ 下的配置文件后重装，依然无法打开

**我预期会发生……？**

ClashX应该被正常打开

**实际上发生了什么？**

ClashX 闪了一个报错后 就退出了

### 可能的解决方案 Possible Solution

是否对远程更新的配置文件的容错机制有一些问题

### 更多信息 More Information

系统：macOS 11.4

**Comment by cnmars** [comment]
同样的问题  先用clashx pro

**Comment by Dreamacro** [comment]
clashx pro 正常么，还是说两个都不能正常使用？

**Comment by georgezouq** [comment]
@Dreamacro 刚试了 Pro 是正常的 ClashX 无法打开

**Comment by Dreamacro** [comment]
clashx 更新了，但我建议还是用 clashx pro，还能有增强模式
