### ISSUE TITLE
频繁出现 tcp: i/o timeout 导致微信、QQ 头像加载失败

### ISSUE THREAD

**Issue by ghost** [Dreamacro/clash#145]
![image](https://user-images.githubusercontent.com/32955697/54584627-d69e8f00-4a52-11e9-90b8-11dbf3f0d3d0.png)
时不时出现连接超时的情况，比如 QQ 接收图片，QQ、微信查看好友头像时，其他情况也遇见过超时导致图片加载失败。

另外发现一些工具，例如Postman 在请求 API 时也会较频繁的出现报代理错误的问题。

**Comment by Dreamacro** [comment]
你是用了自定义 dns 吗，如果是的话先关掉自定义 dns 一段时间

**Comment by nanhezzb** [comment]
是的，在系统设置里面使用了114和Google的DNS。

**Comment by nanhezzb** [comment]
> 你是用了自定义 dns 吗，如果是的话先关掉自定义 dns 一段时间

尝试注释 DNS 配置，清除本地的 DNS，刷新 DNS 之后使用「直连」，还是出现在加载 QQ
微信头像时超时导致的加载慢问题。

**Comment by Dreamacro** [comment]
我这里 macOS 的 QQ 和微信没有任何问题，你是 windows 吗

**Comment by nanhezzb** [comment]
> 我这里 macOS 的 QQ 和微信没有任何问题，你是 windows 吗
macOS 10.14.3 使用的客户端是 ClashX

**Comment by Dreamacro** [comment]
尝试着重启一下电脑？我这里两台设备都没遇到这个问题，我用 paw 的时候也没遇到请求错误的问题

**Comment by EasyChris** [comment]
同样有出现类似的情况
```code
2019/04/05 12:48:17:379  [warning] Proxy[DIRECT] connect [127.0.0.1 --> www.googleapis.com] error: dial tcp 74.125.136.95:443: i/o timeout
```

我在规则中配置了
```
# dev port
- DOMAIN-SUFFIX,google.com,Proxy
- DOMAIN-SUFFIX,googleapis.com,Proxy
- DOMAIN-KEYWORD,googleapis,Proxy
```

但是不知道为什么还是会出现不会match的情况

```
2019/04/05 12:51:47:378  [info] 127.0.0.1 --> accounts.google.com doesn't match any rule using DIRECT
```

**Comment by EasyChris** [comment]
在config里面同时启用 proxy 和  auto 解决了这个问题，之前我只启用了 auto
```
- { name: "auto", type: url-test, proxies: ["server"], url: "http://www.gstatic.com/generate_204", interval: 300 } 
- { name: "Proxy", type: select, proxies: ["server"] 
```

**Comment by Dreamacro** [comment]
@EasyChris 
```yml
Rule:
- DOMAIN-KEYWORD,googleapis,Proxy
```

上述的 “Proxy” 等价于

```yml
Proxy:
- { name: "Proxy" }
# 或者
Proxy Group:
- { name: "Proxy" }
```

**Comment by EasyChris** [comment]
@Dreamacro 了解

**Comment by Dreamacro** [comment]
@EasyChris 对的，就是这么设计的

**Comment by Dreamacro** [comment]
Close because of long time no response.
