### ISSUE TITLE
想要请教一下关于Mixin添加rules的问题

### ISSUE THREAD

**Issue by sgds24** [Dreamacro/clash#1452]
我用的是YAML的方法
以下是我的代码：
mixin: # object
parsers:
  - reg: https://subcon.dlj.tf.+$
    yaml:
      prepend-rules:
        - DOMAIN-SUFFIX,github.io,🚀 手动切换
        - DOMAIN-SUFFIX,github.com,🚀 手动切换
        - DOMAIN-SUFFIX,hangame.com,🚀 手动切换

它不能达到效果请各位帮忙看看

**Comment by Dreamacro** [comment]
clash 本身不提供 mixin 的功能，mixin 的功能应该到 clash for windows 仓库里问
