### ISSUE TITLE
[Feature]请问威联通里的config文件应该放在什么地方

### ISSUE THREAD

**Issue by simonchan204** [Dreamacro/clash#1454]
威联通453-Bmini，docker拉取clash镜像安装后，config文件应该放在什么地方呢？
全局搜索也找不到.config/clash 这个文件夹，config.yaml也找不到
望解答，感谢。

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/clash-as-a-daemon#docker

**Comment by simonchan204** [comment]
感谢回答。我又重新安装了几次，搜索扩展名发现config文件会自动创建在隐藏得很深的位置，因此在安装前在高级设置--环境--path的值设置成自定义文件夹，运行一次就发现config文件了，给后来者提供一下思路。

**Comment by tjcfnerd** [comment]
> 感谢回答。我又重新安装了几次，搜索扩展名发现config文件会自动创建在隐藏得很深的位置，因此在安装前在高级设置--环境--path的值设置成自定义文件夹，运行一次就发现config文件了，给后来者提供一下思路。
`{"environment": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"], "resource": {"device": [], "gpu": [], "limit": {}}, "network": {"hostname": "clash-1", "port": [[7890, 7890, "TCP"], [7891, 7891, "TCP"], [9090, 9090, "TCP"]], "mode": "nat"}, "links": {}, "arch": "amd64", "image": "dreamacro/clash", "command": "", "volume": {"new": [], "host": {"/share/Container/container-station-data/lib/docker/containers/clash/ui": {"bind": "ui", "ro": false}, "/share/Container/container-station-data/lib/docker/containers/clash/config.yaml": {"bind": "root/.config/clash/config.yaml", "ro": false}}, "container": []}, "working_dir": "", "version": "latest", "entrypoint": "/clash", "user": "", "autostart": true, "gpu": false, "type": "docker", "privileged": false, "name": "clash-1"}`
在qnap.json里指定了config文件位置，但是还是运行不起来，控制台显示FATA[0000] Parse config error: read /root/.config/clash/config.yaml: is a directory
这各问题困扰好久了，到底怎么设置才能运行起来- -麻烦知道的解答一下
