### ISSUE TITLE
Domestic DNS handling for other countries [Feature]

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1456]
Hi
when using default nameserver its purpose is to use the dns for geoip;cn sites.
is there any way to use domestic dns for other countries like geoip:ir?
thanks

**Comment by liofoil** [comment]
You can do that by simply replacing current geoip database with your desired country.

**Comment by fsheidaiee** [comment]
> You can do that by simply replacing current geoip database with your desired country.

you mean replacing the .mmdb file? how can I download it only for my country?

**Comment by liofoil** [comment]
Yes, you just need to replace the .mmdb file. As to source for database only for your country, I think google may be more helpful than me.

**Comment by Dreamacro** [comment]
@fsheidaiee Do you mean adding a GEOIP country code to the configurable field? What are your current scenarios?

like this:
```
fallback-filter:
    geoip: true
    geoip-code: IR
```

**Comment by fsheidaiee** [comment]
> @fsheidaiee Do you mean adding a GEOIP country code to the configurable field? What are your current scenarios?
> 
> like this:
> 
> ```yaml
> fallback-filter:
>     geoip: true
>     geoip-code: IR
> ```

Hi
my scenario is to use specific dns resolver (say 5.200.200.200) for ip's within Iran.
what should I do?

**Comment by Dreamacro** [comment]
If the clash adds the `geoip-code` (temporary) field, the whole flow will follow:

1. nameserver and fallback concurrent requests
2. nameserver find IP belongs to Iran
3. use the fallback result

Does this work for you?

**Comment by fsheidaiee** [comment]
> If the clash adds the `geoip-code` (temporary) field, the whole flow will follow:
> 
> 1. nameserver and fallback concurrent requests
> 2. nameserver find IP belongs to Iran
> 3. use the fallback result
> 
> Does this work for you?

No it doesnt work
whenever i turn on fallback filter and test from 'https://browserleaks.com/dns', I see both fallback dns servers and nameservers together handling dns.

**Comment by Dreamacro** [comment]
@fsheidaiee `geoip-code` not implementation yet. I was just wondering if it would help you to have such a parameter.

**Comment by fsheidaiee** [comment]
> @fsheidaiee `geoip-code` not implementation yet. I was just wondering if it would help you to have such a parameter.

Yes of course.
using domestic dns for my specific country would help me a lot
thanks

**Comment by Dreamacro** [comment]
@fsheidaiee add `geoip-code` on dev, have a try

**Comment by fsheidaiee** [comment]
> @fsheidaiee add `geoip-code` on dev, have a try

what is dev? is there a beta channel? i need the premium core to test. is premium core dev available too?
