### ISSUE TITLE
read: connection reset by peer

### ISSUE THREAD

**Issue by ayanamiblhx** [Dreamacro/clash#1457]
**报错信息**
clash在centos里面配置好之后使用curl http://www.google.com后出现错误
`dial Proxy (match DomainKeyword/google) to www.google.com error: dial jike-cn2.ddns-only.xyz:30511 error: read tcp4 172.24.53.41:44546->223.84.158.109:30511: read: connection reset by peer`
同时clash dashboard里面的节点全部爆红

**日志信息**
[root@iZmu0fa4hv0jwzZ clash]# ./clash-linux-amd64 -d .
INFO[0000] Start initial compatible provider Proxy      
INFO[0000] Start initial compatible provider Domestic   
INFO[0000] Start initial compatible provider Others     
INFO[0000] Start initial compatible provider AsianTV    
INFO[0000] Start initial compatible provider GlobalTV   
INFO[0000] RESTful API listening at: 0.0.0.0:9090       
INFO[0000] HTTP proxy listening at: :7890               
INFO[0000] SOCKS proxy listening at: :7891              
INFO[0000] Redir proxy listening at: :7892              
WARN[0009] [TCP] dial Proxy (match DomainKeyword/google) to www.google.com error: dial jike-cn2.ddns-only.xyz:30511 error: read tcp4 172.24.53.41:44546->223.84.158.109:30511: read: connection reset by peer 

**策略组**
![image](https://user-images.githubusercontent.com/63199041/123389537-9254ae80-d5cc-11eb-9cc9-4bd73f78a9da.png)

**环境信息**
系统：CentOs8.2
clash版本：clash-linux-amd64 1.6.0

**clash配置信息**
[root@iZmu0fa4hv0jwzZ clash]# ls
clash-linux-amd64  config.yaml  Country.mmdb

**环境变量**
export http_proxy="http://127.0.0.1:7890"
export https_proxy="http://127.0.0.1:7890"

**Comment by Dreamacro** [comment]
这个是和 server 的连通性问题吧？检查一下是否能够连通你的 server

**Comment by ayanamiblhx** [comment]
> 这个是和 server 的连通性问题吧？检查一下是否能够连通你的 server

我这边windows上能连通server，Linux上就不行

**Comment by jacklu2016** [comment]
解决了吗？

**Comment by brucecui1998** [comment]
关注一手，请问解决了吗
