### ISSUE TITLE
[Feature] UDP fallback feature

### ISSUE THREAD

**Issue by mghadam** [Dreamacro/clash#1458]
I have searched on the [issue tracker](https://github.com/Dreamacro/clash/issues/438) before creating the issue. 

It is needed to keep the IP address the same in some UDP applications such as VOIP calls. 

On shadowsocks android, it is possible to define a profile as the UDP fallback profile when using v2ray plugin. This allows us to route our TCP traffic through cloudflare for example, and for UDP traffic use the main shadowsocks profile on the same server.

With Clash for Android, such feature is missing. We can only define `udp: true` for profiles that can handle UDP traffic, otherwise UDP traffic will be routed directly.

It will be really useful if Clash for Android adds a feature like `udpfallback: ss0` where we can define the profile name `ss0` we want to route our UDP traffic through rather than direct UDP connections.

**Comment by Dreamacro** [comment]
#1337 is a pull request for UDP improvements (not in English)

> On shadowsocks android, it is possible to define a profile as the UDP fallback profile when using v2ray plugin. This allows us to route our TCP traffic through cloudflare for example, and for UDP traffic use the main shadowsocks profile on the same server.

on shadowsocks, only TCP traffic through v2ray-plugin, and UDP traffic through the raw shadowsocks protocol.

so when you define a v2ray-plugin ss node, the TCP and UDP traffic should be effected
