### ISSUE TITLE
Feature request: DOMAIN-SUFFIX rule support tld

### ISSUE THREAD

**Issue by LazyZhu** [Dreamacro/clash#146]
DOMAIN-SUFFIX支持顶级域名就可以加入
`- DOMAIN-SUFFIX,cn,DIRECT`
`- DOMAIN-SUFFIX,uk,Proxy`
这样的规则

**Comment by Dreamacro** [comment]
现在应该这样也可以使用的吧

**Comment by LazyZhu** [comment]
我这里测试了的,结果不行..

**Comment by Dreamacro** [comment]
我这测试是可以的, 你把这条规则放到最顶部 `- DOMAIN-SUFFIX,cn,DIRECT`

**Comment by LazyZhu** [comment]
这样可以了,难道按配置规则的顺序匹配的?

**Comment by Dreamacro** [comment]
@LazyZhu 对，总的有个优先级，不然你同时写 `DOMAIN-SUFFIX,cn,DIRECT` 和 `GEOIP,CN,DIRECT` 的时候，我匹配哪个？
