### ISSUE TITLE
您好，请问clash可以把http的流量和https的流量分开代理吗？

### ISSUE THREAD

**Issue by ID-10086** [Dreamacro/clash#1462]
您好，我尝试把http的流量和https的流量分开走两个代理，但是参考了script和rule的关键字之后似乎没有找到合适的方法。请问现在clash支持这样做嘛？

**Comment by Dreamacro** [comment]
script 可以区分 80 和 443 端口，能区分绝大多数 HTTP 和 HTTPS 流量

**Comment by beloved123** [comment]
这个看到啦，我目前是通过这个区分的，但还是不死心就来问下:satisfied:
