### ISSUE TITLE
[Bug] 服务器和clash断开连接，但浏览器和clash保持连接，导致浏览器加载资源异常

### ISSUE THREAD

**Issue by ttttmr** [Dreamacro/clash#1465]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 20001
mode: Rule
```

</details>

### Clash log

```
INFO[0000] Start initial compatible provider xxxx
INFO[0000] Authentication of local server updated
INFO[0000] Mixed(http+socks5) proxy listening at: 127.0.0.1:20001
DEBU[0001] [DNS] alive.github.com --> 140.82.112.26
INFO[0002] [TCP] 127.0.0.1:61054 --> alive.github.com match DomainKeyword(github) using PROXY[xxxx]
DEBU[0007] [DNS] xxxx --> 10.211.55.29
INFO[0007] [TCP] 127.0.0.1:61144 --> xxxx match IPCIDR(10.0.0.0/8) using DIRECT
DEBU[0010] [DNS] xxxx --> 10.211.55.29
INFO[0010] [TCP] 127.0.0.1:61165 --> xxxx match IPCIDR(10.0.0.0/8) using DIRECT
DEBU[0010] [DNS] xxxx --> 10.211.55.29
INFO[0010] [TCP] 127.0.0.1:61167 --> xxxx match IPCIDR(10.0.0.0/8) using DIRECT
DEBU[0010] [DNS] xxxx --> 10.211.55.29
INFO[0010] [TCP] 127.0.0.1:61168 --> xxxx match IPCIDR(10.0.0.0/8) using DIRECT
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Clash v1.6.0 darwin amd64 with go1.16.3 Sat May  8 11:30:49 UTC 2021
* 网路环境或拓扑 (network conditions/topology)
PD虚拟机的NAT网络
浏览器使用SwitchyOmega，设置的HTTP代理
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. 开启代理用浏览器访问一个http服务

**我预期会发生……？**

正常打开
**实际上发生了什么？**

页面卡住，有一个js一直在加载，手动esc停止加载之后可以看到卡了1分多
![image](https://user-images.githubusercontent.com/32825326/123896982-3192f080-d995-11eb-8bcd-3b9474fd448f.png)

### 更多信息 More Information

测试不走clash代理，直连可以正常打开
测试使用Charles代理访问可以正常打开

用wireshark抓包看了下，似乎clash到服务器的传输都正常，传完RST了
![image](https://user-images.githubusercontent.com/32825326/123896156-951c1e80-d993-11eb-8d08-8619c8223e37.png)
本地同时抓浏览器到clash的，出现了一个continuation，然后一直keep-alive
![image](https://user-images.githubusercontent.com/32825326/123896326-f04e1100-d993-11eb-94ca-357778077002.png)
![image](https://user-images.githubusercontent.com/32825326/123896758-baf5f300-d994-11eb-93c7-cf9a9a275d41.png)

这个js文件60k
服务器响应
首页html响应HTTP/1.1 200 OK，没有设置Connection
js响应HTTP/1.1 200 OK，设置了Connection: close

clash似乎在响应里都加上了Connection: keep-alive
首页html响应
![image](https://user-images.githubusercontent.com/32825326/123898026-145f2180-d997-11eb-91b5-b1649c897b81.png)
js响应
![image](https://user-images.githubusercontent.com/32825326/123898003-0b6e5000-d997-11eb-8dcb-8f0edfb66587.png)

目前推测是两边连接不一致导致的，但也没法断定

**Comment by Dreamacro** [comment]
是 http 而不是 https 的话建议试试 dev 分支，对 http 做了一个重构处理

**Comment by ttttmr** [comment]
好的，我试试

**Comment by ttttmr** [comment]
dev分支也不行
![image](https://user-images.githubusercontent.com/32825326/123913813-3a91bb00-d9b1-11eb-86da-8f4f501fdc7e.png)
跟的是js请求的那个tcp流
上面是浏览器到clash，一直keep-alive
下面是clash到服务器，服务器FIN了，clash一直没断

**Comment by Dreamacro** [comment]
你这个 HTTP server 是用什么搭建的，我怎么可以复现这个环境

**Comment by ttttmr** [comment]
同事用go写的一个server，环境似乎没法分享，可以尝试手动构造回http包
首页html响应HTTP/1.1 200 OK，没有设置Connection
js响应HTTP/1.1 200 OK，设置了Connection: close

我测了下上一个版本（v1.5.0）没有问题，只有v1.6.0有问题
![image](https://user-images.githubusercontent.com/32825326/123917946-f0f79f00-d9b5-11eb-9b5c-e3639af5667d.png)
commit好像不多，方便定位问题
