### ISSUE TITLE
[Bug]由Clash内核向Cloudflare CDN节点发起的vmess+wss访问会触发ban ip

### ISSUE THREAD

**Issue by 1-1-2** [Dreamacro/clash#1468]
>具体现象：通过 clash 内核发起 vmess+wss 访问，会触发约2~5min的 CF CDN 节点全面阻断，无法与CF CDN节点进行通讯，具体表现为TLS一次握手超时。该阻断会波及同一拨号网络下的所有设备，猜测是针对出口ip的ban，故称ban ip

------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7890
ipv6: false
mode: rule
log-level: debug

proxies:
  - name: "CDN"
    type: vmess
    server: 104.19.86.42
    port: 443
    uuid: 438ea20e-91e3-43a8-8516-cf7538b82958
    alterId: 0
    cipher: auto
    udp: false
    tls: true
    skip-cert-verify: false
    servername: fake.domain.io
    network: ws
    ws-path: /ray
    ws-headers:
      Host: fake.domain.io

rules:
  - MATCH,CDN
```

</details>

### Clash log

这是 Clash Prenium 内核 log

```
>clashP-windows-amd64.exe -v
Clash 2021.05.08 windows amd64 with go1.16.3 Sat May  8 11:39:56 UTC 2021

>clashP-windows-amd64.exe -f TEST.yml
time="2021-07-01T22:51:29+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-07-01T22:51:42+08:00" level=warning msg="[TCP] dial CDN (match Match/) to www.cloudflare.com error: dial 104.19.86.42:443 error: 530 "
time="2021-07-01T22:53:30+08:00" level=warning msg="[TCP] dial CDN (match Match/) to www.cloudflare.com error: dial 104.19.86.42:443 error: read tcp4 192.168.1.6:14156->104.19.86.42:443: i/o timeout"
```

这是 Clash 内核 log

```
>clash-windows-amd64.exe -v
Clash v1.6.0 windows amd64 with go1.16.3 Sat May  8 11:30:51 UTC 2021

>clash-windows-amd64.exe -f TEST.yml
time="2021-07-01T23:12:52+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-07-01T23:12:59+08:00" level=warning msg="[TCP] dial CDN (match Match/) to www.cloudflare.com error: dial 104.19.86.42:443 error: 530 "
time="2021-07-01T23:15:54+08:00" level=warning msg="[TCP] dial CDN (match Match/) to www.cloudflare.com error: 104.19.86.42:443 connect error: dial tcp4 104.19.86.42:443: i/o timeout"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Microsoft Windows [版本 10.0.19041.1052]
* 网路环境或拓扑 (network conditions/topology)
PC ->-WiFi->- Optical Network Unit ->- ISP
* iptables，如果适用 (if applicable)
…未指定…
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有，但复现过程测试请求不经过 DNS
* 其他 (any other information that would be useful)
…暂无…

### 重现问题的具体布骤 Steps to Reproduce

**注：这里先放必要步骤，更详细的重现、佐证步骤将在“更多信息”中详述**

1. 在cmd中调用上述配置文件运行clash

   ```shell
   clash-windows-amd64.exe -f config.yaml
   ```

2. 通过curl调用代理，发起任意访问

   ```shell
   curl -v -x 127.0.0.1:7890 https://www.cloudflare.com
   ```

   此时会提示 error 530

3. 重复2一次

   此时会提示 timeout

**我预期会发生……？**

将在“更多信息”中详述

**实际上发生了什么？**

将在“更多信息”中详述

### 可能的解决方案 Possible Solution

先开脑洞说下主观推断，想到两种可能（纯属脑洞，望冷静分析）：

1. 由clash发起的 vmess+wss 访问存在特征，可被识别并阻断
2. 阻断方存在两种可能：ISP（GFW），Cloudflare。可能性不作排序判断，但将在下方提供测试信息辅助各位判断。

至于怎么解决——设法消除可能存在的访问指纹？

#### 先作小结 TLDR

具体现象：通过 clash 内核发起 vmess+wss 访问，会触发约2~5min的 CF CDN 节点全面阻断，无法与CF CDN节点进行通讯，具体表现为TLS一次握手超时。

已测试可触发 ban ip 的软件&平台：

1. Clash @ Windows 10 20H1
2. Clash for Windows @ MacOS Big Sur 20F14 / Windows 10 20H1
3. ClashX @ MacOS Big Sur 20F14
4. ClashDotNetFramework @ Windows 10 20H1

未出现类似现象软件&平台：

1. Clash for Android @ MIUI12
2. v2rayN @ Windows 10 20H1
3. Qv2ray @ MacOS Big Sur 20F14

已测试网络：

CMCC/Unicom @ GD-SZ
CMCC/Unicom/Telecom @ GD-GZ
Telecom/CMCC @ GD-FS

#### 问题的发现

老实交代一下，鄙人长期借助GUI调用clash，上述命令行调用clash是为了追根溯源现学现卖的。

为实现低成本科学上网，我借助了CF 的 CDN 进行流量转发，仅小范围使用，每个月流量不到100G，稳定使用逾一年。这一问题始于2021年6月29日约晚上9点，大概从这个时候开始发现无法访问外网，当时使用的是客户端clash for windows(CFW)，所有流经CF CDN的链路均提示 timeout。以前也遇到过类似的情况，较为少见且但在至多十数分钟后便会恢复如初，理解为可以接受的网络波动。但这次不一样，只要不关闭CFW，情况会一直持续，甚至同一拨号网络下的其余设备，如笔记本、手机均无法访问以CF为CDN的网站，即便这些流量不通过我运行在PC上的代理。

#### 重现佐证

1. 监测bat脚本

   这个脚本会循环通过指定的 anycast 节点访问在 cf cdn 上的资源，返回 status code 及总时间

   注：该URL是CF主页上数据量最小的资源链接，如需测试可以修改为任一托管于cf cdn上的URL

   ```batch
   @echo off & Setlocal Enabledelayedexpansion
   SET IP[00]=104.19.5.198 
   SET IP[01]=104.19.48.92 
   SET IP[02]=104.19.32.148
   SET IP[03]=104.21.104.11
   SET IP[04]=104.19.63.240
   SET IP[05]=104.19.84.192
   SET IP[06]=104.21.13.59 
   SET IP[07]=104.19.68.117
   SET DOMAIN=www.cloudflare.com
   SET URL=https://www.cloudflare.com/page-data/app-data.json
   
   :Loop
   FOR /F "usebackq delims== tokens=2" %%I IN (`SET IP`) DO (
       REM set /p="%%I | " < NUL
       curl --silent --max-time 4 --resolve "%DOMAIN%:443:%%I" --write-out "%%I\t|  [%%{http_code}] %%{time_total}s\n" %URL%
   )
   goto :Loop
   ```

   正常情况下会不断返回页面内容和信息如下

   <details>
     <summary>bat输出正常log</summary>

   ```
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.5.198    |  [200] 0.125000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.48.92    |  [200] 0.328000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.32.148   |  [200] 0.344000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.21.104.11   |  [200] 3.125000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.63.240   |  [200] 0.578000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.84.192   |  [200] 0.422000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.21.13.59    |  [200] 3.235000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.68.117   |  [200] 0.203000s
   ```

   </details>

2. 借助TLDR部分任一可触发ban ip的客户端以测试配置运行

   说明：这里的配置是完全无效的，但可以被clash解析并正常发出请求。我个人测试时已尝试过用有效配置进行。

   例如，下面的 server ip 可以是任一可通过Host区分回源的节点，比如随便写的 104.21.21.21 ；UUID是`uuidgen`的；域名也是无效的。

   **重点是，这一无效配置依旧可以触发 ban ip**

   ```yaml
   mixed-port: 7890
   ipv6: false
   mode: rule
   log-level: debug
   
   proxies:
     - name: "CDN"
       type: vmess
       server: 104.19.86.42
       port: 443
       uuid: 438ea20e-91e3-43a8-8516-cf7538b82958
       alterId: 0
       cipher: auto
       udp: false
       tls: true
       skip-cert-verify: false
       servername: fake.domain.io
       network: ws
       ws-path: /ray
       ws-headers:
         Host: fake.domain.io
   
   rules:
     - MATCH,CDN
   ```

   操作：

   1. GUI客户端

      点击访问测速，通过代理发起对诸如对 `https://www.gstatic.com/generate_204` 的请求

   2. 命令行客户端

      ```shell
      curl -v -x 127.0.0.1:7890 http://www.cloudflare.com
      ```

      或者与bat中url一致的

      ```shell
      curl -v -x 127.0.0.1:7890 --resolve www.cloudflare.com:443:104.21.21.21 https://www.cloudflare.com/page-data/app-data.json
      ```

      也可以是别的什么网页

      ```shell
      curl -v -x 127.0.0.1:7890 --resolve skk.moe:443:104.21.21.21 https://skk.moe
      ```

      

3. 现象

   从clash的log来看第一次访问会触发 error 530，第二次访问会返回timeout；也可能第一次访问就直接timeout。

   从 bat 的返回结果来看，会是

   <details>
     <summary>bat输出异常log</summary>

   ```
   104.19.5.198    |  [000] 4.016000s
   104.19.48.92    |  [000] 4.016000s
   104.19.32.148   |  [000] 4.000000s
   104.21.104.11   |  [000] 4.000000s
   104.19.63.240   |  [000] 4.015000s
   104.19.84.192   |  [000] 4.015000s
   104.21.13.59    |  [000] 4.016000s
   104.19.68.117   |  [000] 4.016000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.5.198    |  [200] 0.328000s
   104.19.48.92    |  [000] 4.016000s
   104.19.32.148   |  [000] 4.015000s
   104.21.104.11   |  [000] 4.000000s
   104.19.63.240   |  [000] 4.015000s
   104.19.84.192   |  [000] 4.015000s
   104.21.13.59    |  [000] 4.016000s
   104.19.68.117   |  [000] 4.000000s
   104.19.5.198    |  [000] 4.015000s
   104.19.48.92    |  [000] 4.016000s
   {"webpackCompilationHash":"9da334b764731aa8e2f0"}
   104.19.32.148   |  [200] 0.313000s
   104.21.104.11   |  [000] 4.016000s
   104.19.63.240   |  [000] 4.016000s
   104.19.84.192   |  [000] 4.015000s
   104.21.13.59    |  [000] 4.015000s
   104.19.68.117   |  [000] 4.015000s
   104.19.5.198    |  [000] 4.016000s
   104.19.48.92    |  [000] 4.000000s
   104.19.32.148   |  [000] 4.000000s
   ```

   </details>

   有可能会夹杂几个漏出来的200，但不难发现，基本所有可用的 anycast 节点都被阻断了。甚至是CF的主页

   ```
   >curl -v https://www.cloudflare.com -4
   * Rebuilt URL to: https://www.cloudflare.com/
   *   Trying 104.16.123.96...
   * TCP_NODELAY set
   * connect to 104.16.123.96 port 443 failed: Timed out
   *   Trying 104.16.124.96...
   * TCP_NODELAY set
   * connect to 104.16.124.96 port 443 failed: Timed out
   * Failed to connect to www.cloudflare.com port 443: Timed out
   * Closing connection 0
   curl: (7) Failed to connect to www.cloudflare.com port 443: Timed out
   ```

   简直杀疯了！但V6是正常的 `curl -vvv https://www.cloudflare.com -6` 可以正常返回。

   <details>
     <summary>CF主页ipv6正常返回</summary>

   ```
   >curl -v https://www.cloudflare.com -6 -o NUL
   * Rebuilt URL to: https://www.cloudflare.com/
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2606:4700::6810:7c60...
   * TCP_NODELAY set
   * Connected to www.cloudflare.com (2606:4700::6810:7c60) port 443 (#0)
   * schannel: SSL/TLS connection with www.cloudflare.com port 443 (step 1/3)
   * schannel: checking server certificate revocation
   * schannel: sending initial handshake data: sending 189 bytes...
   * schannel: sent initial handshake data: sent 189 bytes
   * schannel: SSL/TLS connection with www.cloudflare.com port 443 (step 2/3)
   * schannel: failed to receive handshake, need more data
   * schannel: SSL/TLS connection with www.cloudflare.com port 443 (step 2/3)
   * schannel: encrypted data got 2703
   * schannel: encrypted data buffer: offset 2703 length 4096
   * schannel: sending next handshake data: sending 93 bytes...
   * schannel: SSL/TLS connection with www.cloudflare.com port 443 (step 2/3)
   * schannel: encrypted data got 258
   * schannel: encrypted data buffer: offset 258 length 4096
   * schannel: SSL/TLS handshake complete
   * schannel: SSL/TLS connection with www.cloudflare.com port 443 (step 3/3)
   * schannel: stored credential handle in session cache
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET / HTTP/1.1
   > Host: www.cloudflare.com
   > User-Agent: curl/7.55.1
   > Accept: */*
   ...CONTENT...
   ```

   </details>

   也是这一点，我觉得大概率不是 CF 官方封锁。加之特殊时期，但不排除以后会长期开启，VMESS+WSS@CDN的操作或将终结。

4. 恢复

   在写下这句话的时候测得约180s可恢复直连访问，但再触发代理访问，继续ban 3min。。。

#### Wireshark抓包

1. v2rayN 有效访问，不触发阻断

![image](https://user-images.githubusercontent.com/50569812/124162777-6c9a3e80-dad1-11eb-9bb5-e2acb87ce75b.png)

2. Clash 访问，触发阻断

![image](https://user-images.githubusercontent.com/50569812/124163878-a3248900-dad2-11eb-841e-ffc8ce931f02.png)

3. Clash for Windows @ Windows 访问，触发阻断

![image](https://user-images.githubusercontent.com/50569812/124163042-c3a01380-dad1-11eb-97f7-9b38e84436d5.png)

4. Clash for Windows @ MacOS 访问，触发阻断

![image](https://user-images.githubusercontent.com/50569812/124163172-e5999600-dad1-11eb-808e-1905e700410a.png)

FINALLY

我尝试过用 v2rayN 以 IP 直连的方式代理流量，短时间内未由触发ban

不敢尝试用 clash 的直连，那样我怕连这篇 ISSUE 都发不出来了。。。。

这里有个奇怪的点是 Clash for Android 是唯一有clash的特性但不触发阻断的客户端，具体原因不详。

能力有限，以上基本是我能想到的所有了，还需要补充请 comment。

**Comment by dogfight3601** [comment]
相同情况
在Windows下使用时会触发ban CF ASN所以IP段
直连服务器IP的情况下正常
猜测应该是针对CF IP段的策略

Android (Clash for Android)正常
iOS (shadowrocket)正常
Windows (V2RAYN)正常

**Comment by Dreamacro** [comment]
尝试一下加个 UA header 呢？

**Comment by Filterrr** [comment]
同样问题

**Comment by 1-1-2** [comment]
> 尝试一下加个 UA header 呢？

请问ws协议的UA是参照这个配置书写吗？https://github.com/Dreamacro/clash/issues/1398#issuecomment-837668629

我有看过服务端在能够正常通讯的时间段内产生的log，各个客户端之间没有区别，所以没有尝试。现已加入Todo List.万一呢( ˙-˙ )

**Comment by CSd4FSMP** [comment]
> 尝试一下加个 UA header 呢？

尝试加入UA,问题依旧

    ws-headers:
      Host: "{hostname}"
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

CF日志由

用户代理 Go-http-client/1.1
变更为
用户代理 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

**Comment by OG-C** [comment]
测试的是CFA的哪个版本？难道是闭源core导致的问题？

> 相同情况
> 在Windows下使用时会触发ban CF ASN所以IP段 (VMESS+TLS+WS)
> 直连服务器IP的情况下正常
> 猜测应该是针对CF IP段的策略
> 
> Android (Clash for Android)正常
> iOS (shadowrocket)正常
> Windows (V2RAYN)正常

**Comment by dogfight360** [comment]
> 测试的是CFA的哪个版本？难道是闭源core导致的问题？
> 
> > 相同情况
> > 在Windows下使用时会触发ban CF ASN所以IP段 (VMESS+TLS+WS)
> > 直连服务器IP的情况下正常
> > 猜测应该是针对CF IP段的策略
> > Android (Clash for Android)正常
> > iOS (shadowrocket)正常
> > Windows (V2RAYN)正常

CFA两个版本都试过,play商店以及GitHub上最新的release,均正常
比较怀疑是桌面端的TLS握手特征导致的
桌面端与移动端的握手Cipher Suites位置固定,但顺序不同

**Comment by CSd4FSMP** [comment]
> 测试的是CFA的哪个版本？难道是闭源core导致的问题？
> 
> > 相同情况
> > 在Windows下使用时会触发ban CF ASN所以IP段 (VMESS+TLS+WS)
> > 直连服务器IP的情况下正常
> > 猜测应该是针对CF IP段的策略
> > Android (Clash for Android)正常
> > iOS (shadowrocket)正常
> > Windows (V2RAYN)正常

CFA两个版本都试过,play商店以及GitHub上最新的release,均正常
比较怀疑是桌面端的TLS握手特征导致的
桌面端与移动端的握手Cipher Suites位置固定,但顺序不同

**Comment by CSd4FSMP** [comment]
> 尝试一下加个 UA header 呢？

确认是握手Cipher Suites特征导致
手动指定替换为移动端的排序后一切恢复正常不再掐断
加一个可选项吧?可以让使用者自己指定握手算法

\src\github.com\Dreamacro\clash\adapters\outbound\vmess.go
line 295
		tlsConfig := &tls.Config{
			InsecureSkipVerify: v.option.SkipCertVerify,
			ServerName:         v.option.ServerName,
			PreferServerCipherSuites:         true,
		}
		
		tlsConfig.CipherSuites = []uint16{
		tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
		tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
		tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
		tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
		tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
		tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
		tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
		tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
		tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
		tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
		tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
		tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
		tls.TLS_RSA_WITH_AES_128_CBC_SHA,
		tls.TLS_RSA_WITH_AES_256_CBC_SHA,
		tls.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,
		tls.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
		tls.TLS_CHACHA20_POLY1305_SHA256,
		tls.TLS_AES_128_GCM_SHA256,
		tls.TLS_AES_256_GCM_SHA384,
		}

**Comment by Skyxim** [comment]
> > 尝试一下加个 UA header 呢？
> 
> 确认是握手Cipher Suites特征导致
> 手动指定替换为移动端的排序后一切恢复正常不再掐断
> 加一个可选项吧?可以让使用者自己指定握手算法
> 
> \src\github.com\Dreamacro\clash\adapters\outbound\vmess.go
> line 295
> 
> ```
> 		tlsConfig := &tls.Config{
> 			InsecureSkipVerify: v.option.SkipCertVerify,
> 			ServerName:         v.option.ServerName,
> 			PreferServerCipherSuites:         true,
> 		}
> 		
> 		tlsConfig.CipherSuites = []uint16{
> 		tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
> 		tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
> 		tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
> 		tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
> 		tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
> 		tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
> 		tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
> 		tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
> 		tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
> 		tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
> 		tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
> 		tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
> 		tls.TLS_RSA_WITH_AES_128_CBC_SHA,
> 		tls.TLS_RSA_WITH_AES_256_CBC_SHA,
> 		tls.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,
> 		tls.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
> 		tls.TLS_CHACHA20_POLY1305_SHA256,
> 		tls.TLS_AES_128_GCM_SHA256,
> 		tls.TLS_AES_256_GCM_SHA384,
> 		}
> ```

但是同vmess v2ray仓库好像也没指定CipherSuites（也许我没找到）是不是可能还有其他的原因，这个方法是治标不治本

**Comment by Dreamacro** [comment]
@CSd4FSMP 看了一下 v2ray ws 的 tls.Config ，有一个 NextProtos 的差异

https://github.com/Dreamacro/clash/blob/6091fcdfece557284ef519816111e86537d56775/transport/vmess/websocket.go#L133 改成这个试试？
```
dialer.TLSClientConfig = &tls.Config{
	ServerName:         c.Host,
	InsecureSkipVerify: c.SkipCertVerify,
	ClientSessionCache: c.SessionCache,
	NextProtos: "http/1.1",
}
```

**Comment by CSd4FSMP** [comment]
> @CSd4FSMP 看了一下 v2ray ws 的 tls.Config，有一个 NextProtos 的差异
> 
> https://github.com/Dreamacro/clash/blob/6091fcdfece557284ef519816111e86537d56775/transport/vmess/websocket.go#L133
> 
> 改成这个试试？
> ```go
> dialer.TLSClientConfig = &tls.Config{
> 	ServerName:         c.Host,
> 	InsecureSkipVerify: c.SkipCertVerify,
> 	ClientSessionCache: c.SessionCache,
> 	NextProtos: "http/1.1",
> }
> ```

不行.又掐断了

**Comment by Dreamacro** [comment]
@CSd4FSMP 与 v2ray 的 client 抓包对比了下，除了 NextProtos 外，v2ray 没有 `ClientSessionCache`，注释掉 `ClientSessionCache` 试试呢？

**Comment by CSd4FSMP** [comment]
> @CSd4FSMP 与 v2ray 的 client 抓包对比了下，除了 NextProtos 外，v2ray 没有 `ClientSessionCache`，注释掉 `ClientSessionCache` 试试呢？

试了,依旧

顺便对比了V2rayN与CFA的Cipher Suites,两者顺序是相同的

**Comment by JvoYs8W** [comment]
同样的问题，是因为100周年吗？

**Comment by iKingEast** [comment]
用ClashDotNetFramework问题可以复现问题，但是出现问题的同时，同一网络下的小火箭却可以正常使用。

**Comment by plutonemhikari** [comment]
clash的Linux版遇到同样问题，cipher顺序是aes的几个在前面，跟clash for Android的顺序不同。可能是不同平台的tls指纹不同？不过玄学的地方就是，v2ray-core不是和clash用的同一套tls库吗

**Comment by aliali-li** [comment]
Same here. 

What's more, during this blockage, except CF anycast nodes, I get banned from connecting other famous VPS providers. When I use Clash for Windows with a **DO** London node (vmess+wss+CF CDN) and trigger this blockage, my Android tablet under the same Wifi can't even use Outline app nor SSH to connect **another** node (**VULTR** LA, with ss-libev). 
The weird thing is I can ping and tcping the latter Vultr LA VPS without any error, I just can't get connected to it. 

After 3 mins, I use Clash for Windows to connect this Vultr ss-libev node, everything works fine.

I know nothing about computer networking, any bro could tell me why I can't connect my Vultr VPS while I can ping & tcping it successfully?

**Comment by 404gods** [comment]
我也出现这个问题，我是在路由器上安装的Merlin Clash插件，节点协议是vmess+ws 套的cf cdn，现在只要开启clash，连clash官网都无法访问，自定义规则为直连也不行。希望这个问题早点能解决。

**Comment by Dreamacro** [comment]
995aa7a8fc641fa00b44ad290ac59c3e4c2a565f 尝试调整为和 v2ray 一样的 tls config，有条件的可以先试试

**Comment by CSd4FSMP** [comment]
> [995aa7a](https://github.com/Dreamacro/clash/commit/995aa7a8fc641fa00b44ad290ac59c3e4c2a565f) 尝试调整为和 v2ray 一样的 tls config，有条件的可以先试试

已恢复正常使用
看了下前面测试的时候CFW放错目录了

**Comment by Dreamacro** [comment]
那我 release 一下吧，就先 close 这个 issue 了

**Comment by 1-1-2** [comment]
Well done! 已恢复正常使用

**Comment by jaychoubaby** [comment]
> Well done! 已恢复正常使用

请问怎么恢复的啊？用clash windows客户端的要怎么办？要等他们更新？
