### ISSUE TITLE
[Bug] trojan URLTest block

### ISSUE THREAD

**Issue by bineyond** [Dreamacro/clash#1482]
此 trojan 节点测试，不会超时退出，会一直阻塞 Proxy.URLTest    url：http://www.google.com/generate_204

{"name":"","server":"server","type":"trojan","country":"🇳🇱 NL","port":443,"password":"7e6256a0-b4ab-11eb-bc8f-1239d0255272","skip-cert-verify":true,"udp":true}

**Comment by Dreamacro** [comment]
阻塞在了 tls handshake, go 1.17 加入的 handshakeContext 应该可以解决。URLTest 里的 TLSHandshakeTimeout 貌似没起到作用

**Comment by bineyond** [comment]
3Q，我更新 go 1.17 验证下

**Comment by zhangguanzhang** [comment]
> 阻塞在了 tls handshake, go 1.17 加入的 handshakeContext 应该可以解决。URLTest 里的 TLSHandshakeTimeout 貌似没起到作用



> 阻塞在了 tls handshake, go 1.17 加入的 handshakeContext 应该可以解决。URLTest 里的 TLSHandshakeTimeout 貌似没起到作用

release的golang版本是多少，我用go version 查不到二进制的go版本号

**Comment by thank243** [comment]
`github.com/!dreamacro/clash@v1.9.0/transport/trojan/trojan.go:71`

至今未修复。Trojan依然会重现此bug。
