### ISSUE TITLE
[Feature] 测速方式修改成两次HEAD请求的时间间隔会否更好

### ISSUE THREAD

**Issue by Skyxim** [Dreamacro/clash#1483]
现在的测速发起一个HEAD给服务器，但是由于握手方式，并不能真正反映服务器的实际延迟，而是一个握手延迟，这样使用最低延迟的策略组时

可否修改成在第一个HEAD请求返回后发起第二个计算时间间隔？

从而得出实际到测速网站的一个rtt时间，而忽略握手带来的时间消耗。毕竟握手不是每次握手需要进行的

**Comment by Dreamacro** [comment]
其实这种完整走一次 TCP 连接+握手+HTTP 请求才算是 「真正反映服务器的实际延迟」。取两次只会让带有 mux 的代理协议受益。而浏览器实际访问时，即使代理协议没有 mux，实际上对于现代网站来说也都会打开对应的 HTTP2 连接、以及 Keep Alive。

所以我认为发两次只会造成某些代理协议的延迟减少，从而给使用者一个延迟低的心理安慰

**Comment by Skyxim** [comment]
> 其实这种完整走一次 TCP 连接+握手+HTTP 请求才算是 「真正反映服务器的实际延迟」。取两次只会让带有 mux 的代理协议受益。而浏览器实际访问时，即使代理协议没有 mux，实际上对于现代网站来说也都会打开对应的 HTTP2 连接、以及 Keep Alive。
> 
> 所以我认为发两次只会造成某些代理协议的延迟减少，从而给使用者一个延迟低的心理安慰

也是最近用trojan在个低延迟的vps上建立了个简单发现 urltest 就没选到过这个新的节点，感觉有些不公平
