### ISSUE TITLE
ubuntu下终端怎么使用clash代理

### ISSUE THREAD

**Issue by kong-learning** [Dreamacro/clash#1493]

**Comment by plutonemhikari** [comment]
很多种方法，
1. 设置环境变量http_proxy和https_proxy，但有的程序不支持
2. 有个工具叫procychains你可以搜一下，但是有些静态链接的程序不支持
3. 用redirect，要手动设置iptables
4. 用premium核的tun模式，也要手动设置iptables

**Comment by recall704** [comment]
https://gist.github.com/recall704/5598f4997a8c511c658879c771504bdb

不太会的话，现在虚拟机里面玩玩，玩熟悉了再上。

**Comment by hadkins1** [comment]
修改你的 .bash_profile 文件，加入以下内容：
```
# Setting Terminal HTTP Proxy
MY_HTTP_PROXY_SERVER=http://127.0.0.1:7893
MY_HTTPS_PROXY_SERVER=http://127.0.0.1:7893
export http_proxy=$MY_HTTP_PROXY_SERVER
export https_proxy=$MY_HTTPS_PROXY_SERVER
export HTTP_PROXY=$MY_HTTP_PROXY_SERVER
export HTTPS_PROXY=$MY_HTTPS_PROXY_SERVER
```

**Comment by AKmoex** [comment]
目前个人采用的方案是docker+clash，使用起来异常方便，具体可见我写的这篇 [Ubuntu20.04下配置代理](http://jianshu.com)

**Comment by ayuayue** [comment]
> 目前个人采用的方案是docker+clash，使用起来异常方便，具体可见我写的这篇 [Ubuntu20.04下配置代理](http://jianshu.com)
文章没了

**Comment by AKmoex** [comment]
> > 目前个人采用的方案是docker+clash，使用起来异常方便，具体可见我写的这篇 [Ubuntu20.04下配置代理](http://jianshu.com)
> > 文章没了
请见这里：[Ubuntu20.04下配置代理](https://blog.akmoex.com/archives/ubuntu-settings)

**Comment by SheepAndWolf** [comment]
> > > 目前个人采用的方案是docker+clash，使用起来异常方便，具体可见我写的这篇 [Ubuntu20.04下配置代理](http://jianshu.com)
> > > 文章没了
> > > 请见这里：[Ubuntu20.04下配置代理](https://blog.akmoex.com/archives/ubuntu-settings)

文章又没了

**Comment by AKmoex** [comment]
@SheepAndWolf 去我博客（就上面那个连接）找这篇文章就行了
