### ISSUE TITLE
关于 http/https proxy 的问题

### ISSUE THREAD

**Issue by humiaozuzu** [Dreamacro/clash#15]
看到 readme 中写到有支持，但是在配置文件里加入的时候发现不支持，`config/config.go` 中也没有看到解析相关配置的代码

**Comment by Dreamacro** [comment]
这个 HTTP(S) 指的是 `inbound` 也就是流量流入的入口，不是和 ss/vmess 一样的 `outbound` 流量出口。之所以不加上 HTTPS 的原因是不确定是否所有的 HTTPS 代理服务器都能承接 TCP 流量（不单单是 HTTP 协议），所有一直在考虑中。

**Comment by Dreamacro** [comment]
这个 HTTP(S) 指的是 `inbound` 也就是流量流入的入口，不是和 ss/vmess 一样的 `outbound` 流量出口。之所以不加上 HTTPS 的原因是不确定是否所有的 HTTPS 代理服务器都能承接 TCP 流量（不单单是 HTTP 协议），所有一直在考虑中。

**Comment by Dreamacro** [comment]
如果没有其他问题我就先 close 这个 issue 了，需要的话在 reopen。

**Comment by humiaozuzu** [comment]
是支持的，走 HTTP connect 就行了。Surge 也是实现了一样的模式

**Comment by Dreamacro** [comment]
因为 HTTPS 代理用的不多, 所以不太清楚大多数 HTTPS 代理的实现方式, 如果是 CONNECT 方式的话, 实现也很容易。

**Comment by leosama** [comment]
同一个问题，配置了好一会发现原来还不支持该模式

**Comment by beyondkmp** [comment]
> 看到 readme 中写到有支持，但是在配置文件里加入的时候发现不支持，`config/config.go` 中也没有看到解析相关配置的代码

#52

**Comment by Ansen** [comment]
建议支持一下 vmess的 h2协议，感谢
