### ISSUE TITLE
连接建立，但没有流量

### ISSUE THREAD

**Issue by hzqd** [Dreamacro/clash#1500]
升级到 wsl2 后，我更新了`~/.ssh/config`的 ip 地址为虚拟网卡地址，连接会在建立的一瞬间断开。
于是我关闭了 Windows 防火墙，此时 connections 一直显示有连接，但就是没流量。

![image](https://user-images.githubusercontent.com/40200761/126591680-d65e3920-5129-4ce8-993f-4464b1849e0a.png)

我应该如何修复此问题？

**Comment by Fndroid** [comment]
没看明白你想表达的问题？

如果是WSL2不能使用Clash代理那是正常的，WSL2有独立网段但是可以通过Clash的Allow LAN设置物理网卡地址连接Clash的HTTP/SOCKS5代理，或者直接使用Clash的TUN模式接管物理机网络从而代理WSL网络。

**Comment by hzqd** [comment]
问题在于我已经 Allow LAN，也看到 WSL 的地址显示了，但依然存在这个问题：
· WSL 中：http 代理可用，但是 ssh 没有流量。

**Comment by hzqd** [comment]
是部分节点的问题，多尝试其他节点后，现在可以了。
