### ISSUE TITLE
[Feature]添加自定义Geoip

### ISSUE THREAD

**Issue by chuizi1997** [Dreamacro/clash#1510]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Macos
* 使用者的操作系统 (the OS running on the client)
Macos
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

**Comment by ben-august** [comment]
+1
*ray都可以更新geoip.dat.希望clash也支持。如果*ray服务端使用geoip数据和客户端clash的geoip数据对不上的话，很容易分流出错。比如clash设置geoip cn direct，但是某个ip被识别走proxy了，而服务端设置了geoip cn block，服务端的geoip数据库把这个ip识别为cn，于是网页无法访问。希望能增加自定义更新geoip数据库来源和更新间隔。谢谢！
