### ISSUE TITLE
配置文件目录相对路径

### ISSUE THREAD

**Issue by fxzxmicah** [Dreamacro/clash#1512]
是否支持指定配置文件目录为相对于clash可执行文件的相对路径呢？（简单尝试过，应该是不支持）如果不支持是否可以为此添加支持呢？

**Comment by Dreamacro** [comment]
`clash -d ../foo/bar`

**Comment by fxzxmicah** [comment]
哦，对，不仅仅是指默认配置文件夹路径，还有Restful API指定要切换的配置文件路径的部分。
