### ISSUE TITLE
ClashX DNS 不能监听 127.0.0.1 端口

### ISSUE THREAD

**Issue by winkee01** [Dreamacro/clash#1520]
改成 0.0.0.0:853 就能成功监听，如果设置成 127.0.0.1:853，失败。

macOS Big Sur
ClashX 1.65.0

**Comment by Dreamacro** [comment]
开在低位端口需要 sudo 权限，建议开在高位端口。macOS 绑定 0.0.0.0 的低位端口不需要 sudo
