### ISSUE TITLE
[Feature] 同一节点在load-balance与select输出日志不同上的一些疑问

### ISSUE THREAD

**Issue by akw5454521** [Dreamacro/clash#1521]
以前用的都是select组，但是今年6月墙突然升级为对大流量无差别封锁，于是开始尝试负载均衡，但是使用中发现了一些问题，于是来请教下

select: 对于不支持UDP的snell协议，如果客户端发起了UDP连接，日志输出是 [debug] UDP is not supported

load-balance: 节点和协议与上边相同，但是日志变成了 [warn] error: no support

1). 因此我想确认下，这里是否是仅仅日志输出不同，clash不会有什么行为上的区别吧？比如多次尝试造成性能上的消耗之类的

2). 另外观察日志，还发现了问题，就是使用select时，最多出现一两条UDP，之后客户端便不会再尝试，而是全改为使用TCP连接(此客户端会同时尝试2种协议连接)，但是在load-balance下，出现[warn]的数量远大于一两条，鉴于我这个group里全部是snell协议，因此想确认下，如果clash选的第一个proxy不支持UDP，那逻辑是不是会继续选择后一个proxy，直到连接成功呢？

另外我还建了一个group，是ss和vmess组成的，这里的vmess支持UDP而ss不支持，节点我也都标注好了。当我使用select里的ss节点时，UDP给出的日志是走direct，这个我在 #934 里已经确认过了是正常的，然而此ss节点在load-balance里，日志显示UDP是正常连接，不是direct或者no support，就是正常的连接，但是因为此客户端会同时尝试两种协议，故无法确定UDP连接是否能正常从代理服务器拿到数据(但是机场节点说是不支持UDP)

3). 因此想确认下，clash在这里的行为，是无视了udp: false而去正常连接的吗还是实际上走了direct但是日志没那么显示呢？

**Comment by Dreamacro** [comment]
1. 两个日志输出是一样的，由于在连接时无法预知 load-balance 里的代理到底支不支持 udp，所以在 load-balance 上也有 disable-udp 这个字段用于标识整个 load-balance 是否支持 udp。

2. 不会，目前的向后尝试只会针对于节点是否正常，而不是是否支持 UDP

3. 在 group 上标注 disable-udp

**Comment by akw5454521** [comment]
> 1. 两个日志输出是一样的，由于在连接时无法预知 load-balance 里的代理到底支不支持 udp，所以在 load-balance 上也有 disable-udp 这个字段用于标识整个 load-balance 是否支持 udp。
> 2. 不会，目前的向后尝试只会针对于节点是否正常，而不是是否支持 UDP
> 3. 在 group 上标注 disable-udp

感谢回复，抱歉我忘了说了，我用的客户端的core是1.0版的premium core，当时应该是没有关闭group UDP的相关commits的，因此想重新确认下，这个版本的行为跟最新版的没有差异吧？主要是日志每次出现[warn]的数量最少都是6条，数量比我节点还多，看着有点虚……
