### ISSUE TITLE
原理问题

### ISSUE THREAD

**Issue by xiran2018** [Dreamacro/clash#1528]
请问代码在哪里设置的在客户端的主机上启动代理，从而可以代理主机上的所有流量？这部分没有找到呢，没有看到启动客户端主机系统代理的代码
我上边说的可能不太清楚，我的意思是，在哪里调用的函数，从而让客户端主机的所有流量都能转发给客户端上的clash，从而让客户端上的clash转发流量到代理服务器上

**Comment by icpz** [comment]
这是 premium 版本的功能
