### ISSUE TITLE
[Bug] [ShadowsocksR] panic: runtime error: slice bounds out of range [:-256]

### ISSUE THREAD

**Issue by CoelWu** [Dreamacro/clash#1534]
------------------------------------------------------------------

### Clash config

用户不方便公开, 总结了一下是dummy+plain+auth_chain_a
```yaml
……
```

</details>

### Clash log

```
panic: runtime error: slice bounds out of range [:-256]

goroutine 314 [running]:
github.com/Dreamacro/clash/transport/ssr/protocol.(*authChainA).Decode(0x129ac280, 0x12996550, 0x12996564, 0x0, 0x0)
	github.com/Dreamacro/clash/transport/ssr/protocol/auth_chain_a.go:133 +0x5f0
github.com/Dreamacro/clash/transport/ssr/protocol.(*Conn).Read(0x12996540, 0x129e2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/transport/ssr/protocol/stream.go:30 +0x1d5
net/http.(*persistConn).Read(0x129b6140, 0x129e2000, 0x1000, 0x1000, 0x38, 0x0, 0x1)
	net/http/transport.go:1922 +0x143
bufio.(*Reader).fill(0x129b8270)
	bufio/bufio.go:101 +0xeb
bufio.(*Reader).Peek(0x129b8270, 0x1, 0x12998580, 0x126142b0, 0x1, 0x0, 0x9a44ce)
	bufio/bufio.go:139 +0x41
net/http.(*persistConn).readLoop(0x129b6140)
	net/http/transport.go:2083 +0x184
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xa48
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1.选择配置文件
2.panic发生
3. ……

**我预期会发生……？**
没有发生panic

**实际上发生了什么？**
 panic: runtime error: slice bounds out of range [:-256]

### 更多信息 More Information
看过之前的一个issue也有提到，不过貌似stale了

**Comment by Dreamacro** [comment]
pr welcome

**Comment by zhangguanzhang** [comment]
need close this issue

**Comment by Dreamacro** [comment]
Thanks for the heads up @zhangguanzhang
