### ISSUE TITLE
[Bug] auto-route 配置好后流量仍然不进入 tun

### ISSUE THREAD

**Issue by URARUA** [Dreamacro/clash#1537]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description
auto-route 配置好后流量仍然不进入 tun

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

### 更多信息 More Information
![image_2021-08-11_10-18-34](https://user-images.githubusercontent.com/24853208/128961867-ef405438-731e-40c3-b059-d174a1dd8707.png)
![image_2021-08-11_10-29-35](https://user-images.githubusercontent.com/24853208/128961886-48c44ce1-0569-4f1c-92a3-b877ebc11f4a.png)

**Comment by icpz** [comment]
This issue will be fixed in next release. For guys who is also facing this issue, please try this binary 
[clash-windows-amd64-2021.07.03-27-gdec6ae2.zip](https://github.com/Dreamacro/clash/files/6968634/clash-windows-amd64-2021.07.03-27-gdec6ae2.zip).
