### ISSUE TITLE
是否考虑结合go-tun2socks项目来解决不走代理的那些程序的问题

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#154]
最近接触了一个项目，https://github.com/eycorsican/go-tun2socks ，完成度很高，试着从tun的角度去使用socks代理，有没有可能clash试着集成该项目，从tun这个方面考虑那些不走代理的程序的问题

**Comment by Dreamacro** [comment]
这个我之前看到过了，没做的原因是 UDP 还没做，这个项目也是基于 github.com/songgao/water ，到时候 UDP 做了在考虑加上这个，否则 fakeip 之后不支持 UDP relay 会导致很多请求失效。

**Comment by xuhaoyang** [comment]
Android 急需tun，解决一些莫名其妙的问题:)

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/releases/tag/TUN 可以试试实验性的 TUN 二进制
