### ISSUE TITLE
Adding support for aes-128-gcm,aes-192-gcm,chacha20-ietf-poly1305,xchacha20-ietf-poly1305 ciphers in SSR type

### ISSUE THREAD

**Issue by kingofnull** [Dreamacro/clash#1540]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
proxies:
  - {"type":"ssr","name":"SSR_19_9604","server":"superstar.hk.03.free.srayx.xyz","port":"23003","protocol":"origin","cipher":"chacha20-ietf-poly1305","obfs":"plain","password":"d04b8ab9-ea3d-4b36-9701-83e61491e024"}

```

### Clash log

```
time="2021-08-12T19:52:16+04:30" level=fatal msg="Parse config error: initial proxy provider File error: proxy 18 error: chacha20-ietf-poly1305 is not dummy or a supported stream cipher in ssr"

```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

In configuration doc about SSR cipher said 

> all stream ciphers in ss

 but bunch of then aren't! I test one by one and this aren't supported yet:

- aes-128-gcm
- aes-192-gcm
- chacha20-ietf-poly1305
- xchacha20-ietf-poly1305

**Comment by updater1234** [comment]
你确定SSR支持这几个加密算法吗？

**Comment by Dreamacro** [comment]
AEAD ciphers does not belong to shadowsocksr

**Comment by kingofnull** [comment]
Other clients like Sagranet and SSR support it.

**Comment by kingofnull** [comment]
> AEAD ciphers does not belong to shadowsocksr

Other clients like Sagranet and SSR support it.
