### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by JMVoid** [Dreamacro/clash#1543]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

1. 请问restful api(external-controller) 中/proxies 是无法取得proxy的详细配置信息。只有基本信息，例如：name和type，history. 请问proxies api无法获取proxy的详细配置信息是安全的考虑吗？
2. restful api中 /rules只有get 而没有提供put, patch功能，请问是否有安全的考虑及未来考虑增加rules 修改的接口？

谢谢

**Comment by Dreamacro** [comment]
1. 对的，不提供节点的具体信息
2. rules 的 patch 没有，但可以通过配置文件的整个热更新替换掉 rules
