### ISSUE TITLE
[Feature] 能否实现类似 v2ray sniffing 的域名侦测机制

### ISSUE THREAD

**Issue by ihotte** [Dreamacro/clash#1554]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

现在的 Clash 透明代理下规则匹配依赖 clash 内部 DNS 域名和 IP 的映射关系，这样就需要将所有的 DNS 请求预先导入 Clash。路由端劫持 DNS 请求会极大影响整个系统 DNS 解析的稳定性，机场提供的配置文件也是五花八门导致 clash 在 OpenWrt 上的插件设置及其复杂，经常导致 Clash 进程无法启动，进而导致整个内网环境 DNS 解析出现问题。

能否实现类似 v2ray sniffing 的域名侦测机制？ 以便将 DNS 请求从 Clash 中分离出来，使用 ipset 方式实现透明代理。

**Comment by escape0707** [comment]
I'm using cgroup to classify traffic from processes I want to proxy and I don't. But if I set some process (for example, qbittorrent) in the cgroup that will not get TPROXY to clash, I have to let them use real DNS resolved result.

I don't know how to configure fake-ip if I have this kind of requirement.
