### ISSUE TITLE
[Feature] adblocking with dns with tun/tap mode in windows

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1556]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

adblocking with DNS (like adguard or rethink dns and similar servers), fails to work when using vpn or clash with tun/tap mode.
the reason I think is that, vpn server or proxy server get the chance to get involved with name resolution alongside dns server, so ads will get the chance to be resolved with proxy server address, not the dns server, so ads wont be blocked.
proxifier has two options
1.  "Use target hostname in proxy request if available" : https://www.proxifier.com/docs/win-v4/proxy-advanced.html (BTW you should disable sniffing in v2ray/xray core but its apparently off by default in clash which is a good thing)
2. set name resolution to use system dns (instead of resolve hostnames with proxy server): https://www.proxifier.com/docs/win-v4/dns.html
setting these two options in proxifier while setting adblocker dns server in your system (like rethink and adguard dns) will get you blocking ads with dns. and even if you test dns leak here: "https://browserleaks.com/dns", you will only see the dns server addresses (you will not see proxy server address alongside you dns provider)

but if you use a vpn or tun/tap mode in clash, and test dns leak, you will see the proxy/vpn server address as name resolver there alongside your dns provider and that's the problem getting in the way of blocking ads with dns.
please consider an option to solve this issue.
thanks

### Possible Solution

consider similar options like proxifier app.
thanks

**Comment by ttimasdf** [comment]
v2ray 或 Xray 的 domain sniffing 是你所需的功能，Clash应该不支持。 [入站代理 | Project X](https://xtls.github.io/config/inbound.html#inboundobject)

> 流量探测主要作用于在透明代理等用途. 比如一个典型流程如下:
>
> 1. 如有一个设备上网,去访问 abc.com,首先设备通过 DNS 查询得到 abc.com 的 IP 是 1.2.3.4,然后设备会向 1.2.3.4 去发起连接.
> 2. 如果不设置嗅探,Xray 收到的连接请求是 1.2.3.4,并不能用于域名规则的路由分流.
> 3. 当设置了 sniffing 中的 enable 为 true,Xray 处理此连接的流量时,会从流量的数据中,嗅探出域名,即 abc.com
> 4. Xray 会把 1.2.3.4 重置为 abc.com.路由就可以根据域名去进行路由的域名规则的分流
> 
> 因为变成了一个向 abc.com 请求的连接, 就可以做更多的事情, 除了路由域名规则分流, 还能重新做 DNS 解析等其他工作.
>
> 当设置了 sniffing 中的 enable 为 true, 还能嗅探出 bittorrent 类型的流量, 然后可以在路由中配置"protocol"项来设置规则处理 BT 流量, 比如服务端用来拦截 BT 流量, 或客户端固定转发 BT 流量到某个 VPS 去等.

**Comment by ttimasdf** [comment]
Related: #1554

**Comment by fsheidaiee** [comment]
This issue has been solved after updating the core to v1.8 and premium core to Premium 2021.11.08 due to this change in the core :
"redir-host no remote DNS request anymore"

thanks developers.
