### ISSUE TITLE
希望加入vmess的tcp混淆

### ISSUE THREAD

**Issue by poemsiu** [Dreamacro/clash#156]
希望支持tcp的header混淆，感谢

**Comment by Dreamacro** [comment]
据我说知纯 tcp 的 vmess 协议没有 header 这个东西，还是说你说的是 websocket 的 header

**Comment by DesperadoJ** [comment]
> 据我说知纯 tcp 的 vmess 协议没有 header 这个东西，还是说你说的是 websocket 的 header

https://www.v2ray.com/chapter_02/transport/tcp.html#httpheaderobject
TCP 可以添加 HTTP Header，希望 Clash 加入支持

**Comment by Dreamacro** [comment]
@DesperadoJ 我看到了，如果实现不是很复杂的话我就支持一下

**Comment by lifansama** [comment]
如果有http header的话是不是就能用这个了？
https://github.com/liberal-boy/v2ray-http-header-bypass

**Comment by manyang901** [comment]
希望作者有时间支持一下tcp header

**Comment by zhj9709** [comment]
一年了，希望可以支持一下

**Comment by betaxab** [comment]
同样希望跟进 vmess HTTP 混淆的支持，谢谢。

**Comment by Rasta0501** [comment]
希望大佬早日加入tcp+http混淆

**Comment by Dreamacro** [comment]
done

**Comment by Rasta0501** [comment]
大佬我发现个问题，示例写法中怎么没有host，http混淆的域名，ss配置写法有
![Snipaste_2020-04-03_13-06-01](https://user-images.githubusercontent.com/25950481/78326075-0102b200-75ac-11ea-9222-f2f873ea9f06.png)
![Snipaste_2020-04-03_13-06-11](https://user-images.githubusercontent.com/25950481/78326085-052ecf80-75ac-11ea-9908-4d31d8e30e9c.png)

**Comment by manyang901** [comment]
headers:
  Host:

**Comment by anypasss** [comment]
2021年了tcp + http 何时才能出？

**Comment by zhj9709** [comment]
> 2021年了tcp + http 何时才能出？

上面回复你都不看的吗？早就加了
