### ISSUE TITLE
Which rule does 'cdninstagram.com' match?

### ISSUE THREAD

**Issue by Azureki** [Dreamacro/clash#157]
## Rule matching
I can visit `https://www.instagram.com/` but cannot load pictures. And the pictures' domain is `cdninstagram.com`.

The log(log-level is debug):
> DEBU[0003] [DNS] www.instagram.com --> 8.7.198.45       
INFO[0003] 127.0.0.1 --> www.instagram.com match FINAL using auto

There is no log of `cdninstagram.com`.

My rule is the same as that in [README.md](https://github.com/Dreamacro/clash/blob/master/README.md).
I think that `cdninstagram.com` doesn't match anyone, so clash should use `MATCH,auto`.

However, I couldn't see the log of `cdninstagram.com` untill I comment **BOTH** `IP-CIDR,127.0.0.0/8,DIRECT` **AND** `GEOIP,CN,DIRECT`.
I cannot figure out an answer because apparently the domain should match neither of them.

## dns

`dig instagram.com` returns a ip while `dig cdninstagram.com` doesn't.
I suggest that's why clash doesn't output the log of `cdninstagram.com`.

I uncomment the `dns`, while there is an error in the log:
> ERRO[0000] Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied

Then I cp my config to `/root` and `sudo clash`. No  error.
But this time I cannot visit any websites except `google.com` and CN sites.

> ping 1.1.1.1
64 bytes from 1.1.1.1: icmp_seq=2 ttl=49 time=80.3 ms
tcping 1.1.1.1 -p 53
Connected to 1.1.1.1[:53]: seq=4 time=95.37 ms

I have poor knowledge of network. Who can tell me why this happened and how can I solve the problem?

**Comment by Fndroid** [comment]
``8.7.198.45`` is a wrong IP from DNS cache pollution.

The latest version of Clash will display dns failure log.

I suggest you to set your DNS in config.yml like below and test again so that you can confirm this issue:
```yaml
dns:
  enable: On
  nameserver:
    - 'tls://dns.rubyfish.cn:853'
    - 'tls://1.1.1.1:853'
```

**Comment by Azureki** [comment]
@Fndroid 

Thx. This config solved my problem.

**Comment by Azureki** [comment]
BTW, The sample dns config in [README.md](https://github.com/Dreamacro/clash/blob/master/README.md) seems to have a flaw.

Changing 
```
fallback:
  - tcp://1.1.1.1
```
to
```
fallback:
  - tcp://1.1.1.1:853
```
also solved my problem. 
I suppose that the missing port is necessary due to tcp.

**Comment by Fndroid** [comment]
DNS ``1.1.1.1`` takes 53(by default) for TCP queries.

By the way, you could use a more exhaustive rule configs like [this](https://github.com/lhie1/Rules/blob/master/Clash/Rule.yml).

This will help you proxy domains from Instagram and you don't need to config your dns like above.

If you could read Chinese and want to know why, check my [artical](https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D) .

**Comment by Azureki** [comment]
感谢回复。

在ipip.net看了一下那个被污染的ip似乎是美国的，按您的文章所说clash`直接将host发送给代理服务器`，没有使用这个ip，所以才能访问。
至于log里为什么没有`cdninstagram.com`嘛，我想了想：dns查询根本没有返回`cdninstagram.com`的ip（甚至被污染的ip都没有……），所以clash不能决定匹配哪条规则。

不过我真的用`tcp://1.1.1.1:53`和`1.1.1.1`都可以，用`tcp://1.1.1.1`不行……不过这个也不重要就是了。
（ver 0.12.0 linux)

**Comment by Dreamacro** [comment]
@Azureki 0.1.2 没有 tcp 的 dns client 支持

**Comment by Azureki** [comment]
> @Azureki 0.1.2 没有 tcp 的 dns client 支持

原来是这样……还没更新，看了一下0.13.0的Features才知道（
