### ISSUE TITLE
[Bug] 关于default-nameserver的bug

### ISSUE THREAD

**Issue by testiknn** [Dreamacro/clash#1582]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.6.5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
default-nameserver:
    - tls://1.1.1.2:853
    - 8.8.4.4
    - tcp://8.8.8.8:53
    - https://1.1.1.2/dns-query
```

### Clash log

```shell
time="" level=fatal msg="Parse config error: default nameserver should be pure IP"
```

### Description

经过测试，在default-nameserver里使用
tcp、DOH都会报错无法启动，使用udp、DOT这两种就可以正常启动。
（以上列举的纯IP DNS服务器已在fallback里测试可用可正常工作）

为什么要在default-nameserver里使用DOT/DOH，是由于中国部分地区DNS已经不解析某些顶级域名。

**Comment by icpz** [comment]
default-nameserver 是其它 doh/dot 的 bootstrap server。不是用来解析普通域名的，你需要的是 nameserver 域

clash 会使用 default-nameserver 中的 dns 来解析 nameserver 中的域名，再使用 nameserver 中的 doh/dot 来解析来自客户端的请求。因此 default-nameserver 必须是纯 ip 的。
