### ISSUE TITLE
最新版本运行报错 Linux mint

### ISSUE THREAD

**Issue by crazythinking** [Dreamacro/clash#159]
INFO[0000] Can't find MMDB, start download              
FATA[0000] Initial configuration directory error: Can't download MMDB: Get http://117.143.109.180/cache/geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz?ich_args2=136-09213309034582_fa43a65ce0c2c83864409013a9d4a406_10001002_9c896128dfc2f7d9943d518939a83798_a9da1a476bc9d26515c5af07fd3ecba4: read tcp 192.168.31.72:56294->117.143.109.180:80: read: connection reset by peer 

请问怎么解

**Comment by appleyuchi** [comment]
> 大概是被墙了，去 http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz 下载解压命名为 `Country.mmdb` 放在 clash 的配置文件夹下

请问配置文件夹是哪个啊？我下载下来只有clash-linux-amd64一个文件啊，谢谢

**Comment by 2567366108** [comment]
> 上面也被墙了，到https://dev.maxmind.com/geoip/geoip2/geolite2下载了

具体要怎么下载呢？

**Comment by Dreamacro** [comment]
@2567366108 https://github.com/Dreamacro/maxmind-geoip

**Comment by xiyiyia** [comment]
> @2567366108 https://github.com/Dreamacro/maxmind-geoip

hello,
I try the way to solve this problem, but it comes anoher error. 
'Cant load mmdb: error opening database: invalid MaxMind DB file'
Did I use the wrong way to transform the file? On my Ubuntu, I just rename it.
Thank you

**Comment by yukino-tan** [comment]
> > 上面也被墙了，到[https://dev.maxmind.com/geoip/geoip2/geolite2下载了](https://dev.maxmind.com/geoip/geoip2/geolite2%E4%B8%8B%E8%BD%BD%E4%BA%86)
> 
> 具体要怎么下载呢？

https://github.com/wp-statistics/GeoLite2-Country

> > 上面也被墙了，到[https://dev.maxmind.com/geoip/geoip2/geolite2下载了](https://dev.maxmind.com/geoip/geoip2/geolite2%E4%B8%8B%E8%BD%BD%E4%BA%86)
> 
> 具体要怎么下载呢？

https://github.com/wp-statistics/GeoLite2-Country

**Comment by yukino-tan** [comment]
> > 上面也被墙了，到[https://dev.maxmind.com/geoip/geoip2/geolite2下载了](https://dev.maxmind.com/geoip/geoip2/geolite2%E4%B8%8B%E8%BD%BD%E4%BA%86)
> 
> 具体要怎么下载呢？

https://github.com/wp-statistics/GeoLite2-Country

**Comment by yukino-tan** [comment]
> > 上面也被墙了，到[https://dev.maxmind.com/geoip/geoip2/geolite2下载了](https://dev.maxmind.com/geoip/geoip2/geolite2%E4%B8%8B%E8%BD%BD%E4%BA%86)
> 
> 具体要怎么下载呢？

https://github.com/wp-statistics/GeoLite2-Country

**Comment by johnbriton** [comment]
> > 大概是被墙了，去 http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz 下载解压命名为 `Country.mmdb` 放在 clash 的配置文件夹下
> 
> 请问配置文件夹是哪个啊？我下载下来只有clash-linux-amd64一个文件啊，谢谢

.config文件夹应该是被隐藏了。可以用`ls -a`命令可以查看隐藏文件夹

**Comment by ac1982** [comment]
Windows 用户的配置文件在 ```C:\Users\Somebody\.config\clash```

**Comment by weaming** [comment]
`https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb` 在 linux-amd64-1.2.0 clash 上还是报错

**Comment by rrwang05** [comment]
> `https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb` 在 linux-amd64-1.2.0 clash 上还是报错

我也是下载了这个Country.mmdb文件，也是报错，请问解决了吗？

**Comment by weaming** [comment]
> > `https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb` 在 linux-amd64-1.2.0 clash 上还是报错
> 
> 我也是下载了这个Country.mmdb文件，也是报错，请问解决了吗？

没有，后来应该是它自己下载好了
