### ISSUE TITLE
Feature request: KCP support

### ISSUE THREAD

**Issue by opengit** [Dreamacro/clash#16]
Just like the title described.Thanks for your excellent work.

**Comment by Dreamacro** [comment]
The support of KCP has not been added yet, so if you want to use KCP in clash now, you can run a SOCKS5 port with vmess and KCP, then use `socks5` in clash instead.

**Comment by opengit** [comment]
ok.thanks.but i find that the speed test doesn't test the socks5 when i use socks5.

**Comment by Dreamacro** [comment]
The speed is not automatically tested unless you use the API. What do you mean by "doesn't test the socks5 when I use socks5".

**Comment by ma6254** [comment]
kcp is very useful , why not support

**Comment by hadifarnoud** [comment]
kcp still not supported?

**Comment by Zxilly** [comment]
Any progress?

**Comment by future-death** [comment]
希望可以添加kcp协议，需求应该还蛮大的
