### ISSUE TITLE
Clash面板有时会跳回默认设置

### ISSUE THREAD

**Issue by freefrank** [Dreamacro/clash#160]
在国外翻墙回国，把一些中国相关的设置设为proxy，海外的设为direct，
有时这些selector会自动跳回默认的中国direct，海外direct。

**Comment by Dreamacro** [comment]
没有看懂你说的，详细展开下

**Comment by mumeblossom** [comment]
你说的是ClashX或者Clash for Windows吧

**Comment by Dreamacro** [comment]
close because long time no feedback
