### ISSUE TITLE
[Feature] 希望能够支持正则匹配URL规则

### ISSUE THREAD

**Issue by JOJOforshaun** [Dreamacro/clash#1601]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

希望能够支持正则匹配URL规则，就类似小火箭重写的那种功能

**Comment by ysc3839** [comment]
> 目前并没有做 mitm 的打算

https://github.com/Dreamacro/clash/issues/227#issuecomment-508693628

**Comment by necan** [comment]
可以考虑 正则匹配 hostname，不一定要匹配 URL，毕竟 hostname 不需要 mitm。
