### ISSUE TITLE
[Feature] 希望Rules支持正则匹配

### ISSUE THREAD

**Issue by necan** [Dreamacro/clash#1606]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

如果Rules能支持正则匹配，那就更方便了！

### Possible Solution

Rules的原始配置键名无需更改，只需将值的格式改为 `/^(\d+)/` 这种，类似于 JavaScript 的正则表达式。
例如 `IP-CIDR: IP-CIDR,127.0.0.0/8,DIRECT` 可以写成 `IP-CIDR: IP-CIDR,/^127\.\d+\.\d+\.\d+$/,DIRECT`

**Comment by fakeboboliu** [comment]
推荐给出场景，你的描述无法说服人实现
