### ISSUE TITLE
[Feature] 脚本外置

### ISSUE THREAD

**Issue by necan** [Dreamacro/clash#1607]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

希望能外置 Python 脚本，而不是写在配置里面，方便调试 Python 脚本，就像 Rule Providers 那样配置。

### Possible Solution

就像 Rule Providers 那样配置。例如

从网络加载
`config.yaml`
```script:
  code:
    type: http
    url:https://xxx.com/script.py
    interval: 3600
    path: script.py
```

从本地加载
`config.yaml`
```script:
  code:
    type: file
    path: script.py
```

`script.py`
```python
def main(ctx, metadata):
  now = time.now()
  if metadata["src_ip"] == "ip" and now.hour => 18 and now.hour <= 22:
    return "REJECT"

  return "DIRECT"
```

**Comment by nb5p** [comment]
目前是支持脚本外置从本地加载的

**Comment by necan** [comment]
@nb5p 能给个样例吗？我在文档上没找到外置脚本的写法。

**Comment by nb5p** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium 2020.08.16
