### ISSUE TITLE
[Bug] 浏览器配置HTTP代理后无法打开padavan管理页面

### ISSUE THREAD

**Issue by necan** [Dreamacro/clash#1609]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2021.09.07 windows amd64 with go1.17 Tue Sep  7 13:56:10 UTC 2021

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7891
socks-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
rules:
 - MATCH,DIRECT
```

### Clash log

```shell
C:\Users\admin\Desktop>clash -f config.yaml
time="2021-09-12T11:13:04+08:00" level=info msg="HTTP proxy listening at: [::]:7891"
time="2021-09-12T11:13:04+08:00" level=info msg="RESTful API listening at: [::]:9090"
time="2021-09-12T11:13:04+08:00" level=info msg="SOCKS proxy listening at: [::]:7892"
time="2021-09-12T11:13:04+08:00" level=info msg="[TCP] 127.0.0.1:63275 --> alive.github.com:443 match Match() using DIRECT"
time="2021-09-12T11:13:07+08:00" level=info msg="[TCP] 127.0.0.1:54488 --> 192.168.2.1:80 match Match() using DIRECT"
time="2021-09-12T11:13:07+08:00" level=info msg="[TCP] 127.0.0.1:56377 --> 192.168.2.1:80 match Match() using DIRECT"
time="2021-09-12T11:13:07+08:00" level=info msg="[TCP] 127.0.0.1:63422 --> 192.168.2.1:80 match Match() using DIRECT"
time="2021-09-12T11:13:07+08:00" level=info msg="[TCP] 127.0.0.1:60595 --> 192.168.2.1:80 match Match() using DIRECT"
time="2021-09-12T11:13:07+08:00" level=info msg="[TCP] 127.0.0.1:60850 --> 192.168.2.1:80 match Match() using DIRECT"
```

### Description

Chrome 浏览器通过 SwitchyOmega 配置 http 代理后，无法打开 padavan 管理页面，一直卡在 192.168.2.1 页面，但是除此之外的其他网站都没有任何问题。

起初我以为是代理的影响，但是我发现规则里面局域网 IP 已经走了直连，为了排除是规则的问题。于是我干脆改配置，只留下 `MATCH,DIRECT` 让所有请求都走直连，再测试一下，发现问题依旧。

我又换成 socks5 代理，发现居然没有此问题！

看来 clash 的 http 代理存在 BUG！

另外我还注意到 iOS 和 MacOS 上打开 padavan 管理界面也很慢，但至少能打开，v2ex 上有[相关讨论](https://www.v2ex.com/t/790986)，不知道 padavan 的管理页面是不是有什么特别之处。

**Comment by ningsibuqu** [comment]
https://github.com/Dreamacro/clash/issues/1395
