### ISSUE TITLE
[Bug] 手机QQ给电脑QQ发文件，手机发送完，但是电脑端接收时会传输中断

### ISSUE THREAD

**Issue by zhixuans** [Dreamacro/clash#1611]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.7.1

### What OS are you seeing the problem on?

macOS

### Clash config

需要时再提供

### Description

clash_for_windows 0.16.2之后的版本，手机QQ给电脑QQ发文件，会传输中断，不论用规则、全局、直链都会出问题，只有关闭系统代理才正常，换0.16.1就没这种问题，尝试更换成1.6.0（5月8日）的clash core就能正常传输。

clashX 1.60.0之后的版本也是一样的问题，但是没办法换clash core

所以猜测可能是clash core的问题，或者是客户端没有适配某些新特性？

**Comment by cjwddtc** [comment]
这个所有人都能看到，你不要直接发节点信息啊

**Comment by zhixuans** [comment]
暂无解决
