### ISSUE TITLE
[Feature] Request add SNI or Host in SOCKS5 (socks5 over tls)

### ISSUE THREAD

**Issue by djoeni** [Dreamacro/clash#1623]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Please add option SNI or Host in Socks5 protocol...there seems option SNI on HTTP(S) protocol

**Comment by fakeboboliu** [comment]
Currently, socks5 over tls has no defacto standard. 
It's unable to write an implementation, PR is welcome if you can.
