### ISSUE TITLE
clash-linux-amd64.tar.gz无法在64位Ubuntu16.04运行

### ISSUE THREAD

**Issue by conanlee88** [Dreamacro/clash#163]
clash-linux-amd64.tar.gz
有GUI界面吗?系统进程里面看到是有在运行,但没有什么反应

**Comment by Dreamacro** [comment]
clash 是二进制，不包含 GUI 部分

**Comment by conanlee88** [comment]
运行后,控制台没有任何日志输出,这是正常的吗?除了config.yml需要配置以外,还有其他需要手动配置的文件吗?

**Comment by Dreamacro** [comment]
没有了，如果不是用 GUI 的话，还需要手动设置系统代理。

**Comment by conanlee88** [comment]
确实是代理的原因,哈哈哈,谢啦
