### ISSUE TITLE
Where to put mmdb?

### ISSUE THREAD

**Issue by drafting-dreams** [Dreamacro/clash#164]
I'm trying to use clash for windows. And I ran the exe file in command line. It can't download mmdb from the commandline. Then I downloaded the file from the browser. But I don't know where to put it so the exe file can detect it.

**Comment by imgk** [comment]
If the config path is not set with "-d ", clash with use folder located at "C:/Users/$YOURUSERNAME$/.config/clash", or use this https://github.com/imgk/TrayedClash/releases

**Comment by Dreamacro** [comment]
`%HOMEPATH%/.clash` and rename `Country.mmdb`

**Comment by drafting-dreams** [comment]
Thanks guys, this really helped me!
