### ISSUE TITLE
开发者能否增加对http/2协议的支持 

### ISSUE THREAD

**Issue by pikaqiu-ru** [Dreamacro/clash#1642]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

clash好像不支持http/2协议，希望开发者能增加对http/2协议的支持

**Comment by akw5454521** [comment]
- name: "vmess-h2"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    network: h2
    tls: true
    h2-opts:
      host:
        - http.example.com
        - http-alt.example.com
      path: /


  - name: vmess-grpc
    server: server
    port: 443
    type: vmess
    uuid: uuid
    alterId: 32
    cipher: auto
    network: grpc
    tls: true
    servername: example.com
    # skip-cert-verify: true
    grpc-opts:
      grpc-service-name: "example"


能认真看看文档吗

**Comment by xh116** [comment]
楼主问的是纯https的正向代理吧

**Comment by JanWhite** [comment]
`curl -I https://www.google.com
HTTP/1.1 200 Connection established
Connection: close

HTTP/2 200
content-type: text/html; charset=ISO-8859-1
...`
