### ISSUE TITLE
[Feature] fake-ip模式下，对国内域名返回真实ip地址

### ISSUE THREAD

**Issue by InsOnYou** [Dreamacro/clash#1644]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

少数网站用假ip去连接会出问题（比如英雄联盟语音）。国内网站使用fake-ip也不会节约dns解析的时间，可不可以添加这个功能：如果命中域名规则DIRECT，则让clash返回真实ip地址。

**Comment by Ariesly** [comment]
自个把白名单弄到这个 filter 吧...

```yaml
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
```

或者增强个可以外置这个 filter 列表的功能. 
```yaml
# e.g.
fake-ip-filter:
    type: file
    path: ./fake-ip-filter.yaml
```

**Comment by emacsnt** [comment]
> 少数网站用假ip去连接会出问题（比如英雄联盟语音）。国内网站使用fake-ip也不会节约dns解析的时间，可不可以添加这个功能：如果命中域名规则DIRECT，则让clash返回真实ip地址。

时间顺序不对， 按照理解，fake-ip是遇到dns请求立刻返回fake ip，然后才对上级dns发起dns请求，才能知道真实的ip。
同意楼上的说法，应该自行设置白名单filter

**Comment by miniers** [comment]
可以搭配前置mosdns，完美解决这个问题

**Comment by XuuKoo** [comment]
> 可以搭配前置mosdns，完美解决这个问题

思路可以具体说一下嘛

**Comment by miniers** [comment]
> 

主DNS切换为mosdns，通过配置文件指定国内域名走国内dns，国外的走clash的dns即可

**Comment by XuuKoo** [comment]
> > 
> 
> 
> 
> 主DNS切换为mosdns，通过配置文件指定国内域名走国内dns，国外的走clash的dns即可

我这么配置的你看可以吗：
clash开启tun、dns劫持0.0.0.0:53，clash的dns配置下的fallback里写mosdns的本地监听端口。
mosdns把server下的地址改为本地的某个端口（填入clash dns配置下fallback那个），upstream设为8.8.8.8。
由于有tun，所以mosdns的请求会走代理。国内地址clash会用dns配置下的nameserver解析的结果，国外地址会用fallback下也就是mosdns返回的解析结果。

**Comment by miniers** [comment]
> > 主DNS切换为mosdns，通过配置文件指定国内域名走国内dns，国外的走clash的dns即可
> 
> 我这么配置的你看可以吗： clash开启tun、dns劫持0.0.0.0:53，clash的dns配置下的fallback里写mosdns的本地监听端口。 mosdns把server下的地址改为本地的某个端口（填入clash dns配置下fallback那个），upstream设为8.8.8.8。 由于有tun，所以mosdns的请求会走代理。国内地址clash会用dns配置下的nameserver解析的结果，国外地址会用fallback下也就是mosdns返回的解析结果。

😂,和我的实现方式不一样，我的clash只启动了dns，但是没有劫持dns，mosdns监听在53端口，所有dns请求都会先到mosdns，mosdns通过配置规则来判断域名是否为国内的，国内直接走国内的dns服务，国外的走clash的dns服务

**Comment by XuuKoo** [comment]
> > > 主DNS切换为mosdns，通过配置文件指定国内域名走国内dns，国外的走clash的dns即可
> 
> > 
> 
> > 我这么配置的你看可以吗： clash开启tun、dns劫持0.0.0.0:53，clash的dns配置下的fallback里写mosdns的本地监听端口。 mosdns把server下的地址改为本地的某个端口（填入clash dns配置下fallback那个），upstream设为8.8.8.8。 由于有tun，所以mosdns的请求会走代理。国内地址clash会用dns配置下的nameserver解析的结果，国外地址会用fallback下也就是mosdns返回的解析结果。
> 
> 
> 
> 😂,和我的实现方式不一样，我的clash只启动了dns，但是没有劫持dns，mosdns监听在53端口，所有dns请求都会先到mosdns，mosdns通过配置规则来判断域名是否为国内的，国内直接走国内的dns服务，国外的走clash的dns服务

相关配置文件方便分享一下嘛

**Comment by miniers** [comment]
> > > > 主DNS切换为mosdns，通过配置文件指定国内域名走国内dns，国外的走clash的dns即可
> > 
> > 
> > > 
> > 
> > 
> > > 我这么配置的你看可以吗： clash开启tun、dns劫持0.0.0.0:53，clash的dns配置下的fallback里写mosdns的本地监听端口。 mosdns把server下的地址改为本地的某个端口（填入clash dns配置下fallback那个），upstream设为8.8.8.8。 由于有tun，所以mosdns的请求会走代理。国内地址clash会用dns配置下的nameserver解析的结果，国外地址会用fallback下也就是mosdns返回的解析结果。
> > 
> > 
> > 😂,和我的实现方式不一样，我的clash只启动了dns，但是没有劫持dns，mosdns监听在53端口，所有dns请求都会先到mosdns，mosdns通过配置规则来判断域名是否为国内的，国内直接走国内的dns服务，国外的走clash的dns服务
> 
> 相关配置文件方便分享一下嘛
[https://github.com/IrineSistiana/mosdns/wiki/Configuration#%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF](https://github.com/IrineSistiana/mosdns/wiki/Configuration#%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF)

**Comment by XuuKoo** [comment]
> > > > > 主DNS切换为mosdns，通过配置文件指定国内域名走国内dns，国外的走clash的dns即可
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我这么配置的你看可以吗： clash开启tun、dns劫持0.0.0.0:53，clash的dns配置下的fallback里写mosdns的本地监听端口。 mosdns把server下的地址改为本地的某个端口（填入clash dns配置下fallback那个），upstream设为8.8.8.8。 由于有tun，所以mosdns的请求会走代理。国内地址clash会用dns配置下的nameserver解析的结果，国外地址会用fallback下也就是mosdns返回的解析结果。
> 
> > > 
> 
> > > 
> 
> > > 😂,和我的实现方式不一样，我的clash只启动了dns，但是没有劫持dns，mosdns监听在53端口，所有dns请求都会先到mosdns，mosdns通过配置规则来判断域名是否为国内的，国内直接走国内的dns服务，国外的走clash的dns服务
> 
> > 
> 
> > 相关配置文件方便分享一下嘛
> 
> 
> 
> [https://github.com/IrineSistiana/mosdns/wiki/Configuration#%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF](https://github.com/IrineSistiana/mosdns/wiki/Configuration#%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF)
> 
> 配置模板的复杂配置就是

我没太理解“clash只启动dns但不劫持dns”想了解一下您clash的配置。

我用mosdns的本意是想：clash中匹配MATCH,PROXY的域名也能远程解析（默认是有代理规则的域名才远程解析，但不可能把所有要代理的域名都写出来），由于clash的dns请求无法走代理，是直连，为了针对所有代理的域名能够得到在远程服务器上解析的dns结果，所以用了我上述的方案。我也是刚折腾这个dns，不知道有没有什么问题或者更好的思路。

**Comment by miniers** [comment]
> 我用mosdns的本意是想：clash中匹配MATCH,PROXY的域名也能远程解析（默认是有代理规则的域名才远程解析，但不可能把所有要代理的域名都写出来），由于clash的dns请求无法走代理，是直连，为了针对所有代理的域名能够得到在远程服务器上解析的dns结果，所以用了我上述的方案。我也是刚折腾这个dns，不知道有没有什么问题或者更好的思路。

你得需求和这个issues不一样的，我没有你的这种需求，所以也不太清楚了😂

**Comment by XuuKoo** [comment]
> > 我用mosdns的本意是想：clash中匹配MATCH,PROXY的域名也能远程解析（默认是有代理规则的域名才远程解析，但不可能把所有要代理的域名都写出来），由于clash的dns请求无法走代理，是直连，为了针对所有代理的域名能够得到在远程服务器上解析的dns结果，所以用了我上述的方案。我也是刚折腾这个dns，不知道有没有什么问题或者更好的思路。
> 
> 
> 
> 你得需求和这个issues不一样的，我没有你的这种需求，所以也不太清楚了😂
> 
> 

我也是刚开始折腾，到处搜方案和配置，有的东西可能理解还不到位。哈哈。谢谢你。

**Comment by InsOnYou** [comment]
此问题已经解决，我在Clash的DNS下游加一个分流器（AdGuardHome、smartDNS、dnsmasq之类都可以），将国内域名列表添加到国内DNS和单独的ipset（不走clash内核）。目前效果良好，几乎所有国内流量都不经过clash了。

**Comment by XuuKoo** [comment]
> > > > > 主DNS切换为mosdns，通过配置文件指定国内域名走国内dns，国外的走clash的dns即可
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 我这么配置的你看可以吗： clash开启tun、dns劫持0.0.0.0:53，clash的dns配置下的fallback里写mosdns的本地监听端口。 mosdns把server下的地址改为本地的某个端口（填入clash dns配置下fallback那个），upstream设为8.8.8.8。 由于有tun，所以mosdns的请求会走代理。国内地址clash会用dns配置下的nameserver解析的结果，国外地址会用fallback下也就是mosdns返回的解析结果。
> > > 
> > > 
> > > 😂,和我的实现方式不一样，我的clash只启动了dns，但是没有劫持dns，mosdns监听在53端口，所有dns请求都会先到mosdns，mosdns通过配置规则来判断域名是否为国内的，国内直接走国内的dns服务，国外的走clash的dns服务
> > 
> > 
> > 相关配置文件方便分享一下嘛
> 
> [IrineSistiana/mosdns/wiki/Configuration#%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF](https://github.com/IrineSistiana/mosdns/wiki/Configuration#%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF) 配置模板的复杂配置就是

你mosdns监听的哪个地址的53端口，另外系统的dns地址要修改吗？

**Comment by LittleBlacklb** [comment]
`dnsmasq` 也可以的 我是``dnsmasq`设置上游dns服务器是`clash-dns` 可以参考这篇
> https://www.willnet.net/index.php/archives/345/
