### ISSUE TITLE
[Feature] 自动从当前使用的outbound interface的dhcp获取dns nameserver

### ISSUE THREAD

**Issue by ElemenTP** [Dreamacro/clash#1654]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

可否为dns from dhcp增加一项功能，自动从clash当前使用的outbound interface的dhcp获取dns nameserver。

**Comment by JanWhite** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/dns#nameserver
