### ISSUE TITLE
[Feature] 希望在设置ipv6: true后节点域名解析能优先使用AAAA记录

### ISSUE THREAD

**Issue by AssICan** [Dreamacro/clash#1656]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

和[这个issue](https://github.com/Dreamacro/clash/issues/321)有点相似，但不完全相同。
在clash中，如果节点域名同时有AAAA和A记录，即使开启了ipv6: true，也会优先使用节点IPV4的地址。套了CloudFlare的节点会同时有AAAA和A记录，请问有办法在clash中优先使用AAAA记录吗？（除了cname接入CF的办法），因为教育网到Cloudflare ipv6地址的速度比较快，到V4很可能会绕美。

**Comment by a76yyyy** [comment]
应该是可以设置是否优先

**Comment by AssICan** [comment]
> happy eyeballs 似乎能解决这个问题，目前 fallback 时间是 0，常规做法是 300ms。

可否考虑在clash中根据ipv6:true/false或者额外增加一个变量来调整fallback时间？

**Comment by jzl2163** [comment]
> happy eyeballs 似乎能解决这个问题，目前 fallback 时间是 0，常规做法是 300ms。

我应该如何做才能修改这个数值呢？

**Comment by NepPure** [comment]
大佬们 关于ipv6的这个问题有解决方案了吗
