### ISSUE TITLE
请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功

### ISSUE THREAD

**Issue by huiruo** [Dreamacro/clash#1675]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-amd64-v1.7.1

### Clash config

```yaml
Ubuntu 21.04
```

### Clash log

```shell
_
```

### Description

我下载了clash-linux-amd64-v1.7.1发现并不能安装成功，最好有相关配置教程

**Comment by huiruo** [comment]
我导入了配置文件，并且打开了开关，但是也不能访问google,还要配置其他的吗，我在win上是可以成功的，linux应用截图：
![2021-10-19 01-53-16屏幕截图](https://user-images.githubusercontent.com/11364222/137782893-cce59ffc-e60e-4c52-b945-d0e41aa8fc3b.png)
![2021-10-19 01-57-22屏幕截图](https://user-images.githubusercontent.com/11364222/137782900-587cf47a-7ef9-442d-a38b-b0702e618d7f.png)
![2021-10-19 01-57-44屏幕截图](https://user-images.githubusercontent.com/11364222/137782905-84bcca99-a496-4507-859f-f57fa60c3b5f.png)

**Comment by RuojiWang** [comment]
输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）：


我看别人正常情况好像都是这样的：


这是什么情况啊，有大佬知道么？

**Comment by lizenghui** [comment]
> 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： ![140316417-aac2ef4a-b8d4-4331-ae76-80f2cabb8f4d](https://user-images.githubusercontent.com/14054362/140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689.png)
> 
> 我看别人正常情况好像都是这样的： ![140316583-1eb8db42-5afd-4ce1-a2d5-828723e26324](https://user-images.githubusercontent.com/14054362/140329347-84ec3601-3c1e-4b30-8f82-ffec021aa616.jpg) ![140316593-bce586df-9d77-4dbd-a4f1-39b744d6f622](https://user-images.githubusercontent.com/14054362/140329354-b6006b64-0e1c-4071-94e2-4df13e52e63c.jpg)
> 
> 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。

你这看起来当前目录没有clash的配置文件。
external-controller: :9090   这个是API的配置端口   你的端口都没启用   肯定不能访问。

**Comment by huiruo** [comment]
配置文件以什么文件命名？内容是哪里下载？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月5日(周五) 晚上7:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675)




  
输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： 
 
我看别人正常情况好像都是这样的：  
 
这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。
  
你这看起来当前目录没有clash的配置文件。
 external-controller: :9090   这个是API的配置端口   你的端口都没启用   肯定不能访问。

**Comment by lizenghui** [comment]
> 配置文件以什么文件命名？内容是哪里下载？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月5日(周五) 晚上7:49 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675) 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： 我看别人正常情况好像都是这样的： 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请阅读clash文档

**Comment by RuojiWang** [comment]
> 配置文件以什么文件命名？内容是哪里下载？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月5日(周五) 晚上7:49 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675) 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： 我看别人正常情况好像都是这样的： 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> > 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： ![140316417-aac2ef4a-b8d4-4331-ae76-80f2cabb8f4d](https://user-images.githubusercontent.com/14054362/140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689.png)
> > 我看别人正常情况好像都是这样的： ![140316583-1eb8db42-5afd-4ce1-a2d5-828723e26324](https://user-images.githubusercontent.com/14054362/140329347-84ec3601-3c1e-4b30-8f82-ffec021aa616.jpg) ![140316593-bce586df-9d77-4dbd-a4f1-39b744d6f622](https://user-images.githubusercontent.com/14054362/140329354-b6006b64-0e1c-4071-94e2-4df13e52e63c.jpg)
> > 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。
> 
> 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。

这是我的clash文件夹（clash二进制文件所在位置），这些文件确实从订阅的网站下载下来了
![微信截图_20211106151558](https://user-images.githubusercontent.com/14054362/140601586-bdc75788-5da8-4aa1-b122-d12c93f06ea2.png)

这是我的.config下面的clash文件夹，一开始里面的两个文件打开是空的，我把上面的clash文件夹里面的文件复制进去了（因为我无法使用clash，但是看有人这样做就可以用了，于是我也复制进去。。）
![微信截图_20211106151657](https://user-images.githubusercontent.com/14054362/140601591-73341623-14d8-49ca-99f3-d3a1d5e9efca.png)

我在这里买的clash订阅，然后他的安装使用步骤如下图所示，前面一两步和他步骤一样，主要是第三个图我输入./clash的输出和他们不一样
![微信截图_20211106152034](https://user-images.githubusercontent.com/14054362/140601594-2d5087a1-4e3d-4a96-9fde-2a5a5e7157df.png)
![微信截图_20211106152052](https://user-images.githubusercontent.com/14054362/140601595-0bf81f4b-502f-434c-b185-5081b1620749.png)

**Comment by lizenghui** [comment]
> > 配置文件以什么文件命名？内容是哪里下载？
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年11月5日(周五) 晚上7:49 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675) 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： 我看别人正常情况好像都是这样的： 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > > 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： ![140316417-aac2ef4a-b8d4-4331-ae76-80f2cabb8f4d](https://user-images.githubusercontent.com/14054362/140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689.png)
> > > 我看别人正常情况好像都是这样的： ![140316583-1eb8db42-5afd-4ce1-a2d5-828723e26324](https://user-images.githubusercontent.com/14054362/140329347-84ec3601-3c1e-4b30-8f82-ffec021aa616.jpg) ![140316593-bce586df-9d77-4dbd-a4f1-39b744d6f622](https://user-images.githubusercontent.com/14054362/140329354-b6006b64-0e1c-4071-94e2-4df13e52e63c.jpg)
> > > 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。
> > 
> > 
> > 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。
> 
> 这是我的clash文件夹（clash二进制文件所在位置），这些文件确实从订阅的网站下载下来了 ![微信截图_20211106151558](https://user-images.githubusercontent.com/14054362/140601586-bdc75788-5da8-4aa1-b122-d12c93f06ea2.png)
> 
> 这是我的.config下面的clash文件夹，一开始里面的两个文件打开是空的，我把上面的clash文件夹里面的文件复制进去了（因为我无法使用clash，但是看有人这样做就可以用了，于是我也复制进去。。） ![微信截图_20211106151657](https://user-images.githubusercontent.com/14054362/140601591-73341623-14d8-49ca-99f3-d3a1d5e9efca.png)
> 
> 我在这里买的clash订阅，然后他的安装使用步骤如下图所示，前面一两步和他步骤一样，主要是第三个图我输入./clash的输出和他们不一样 ![微信截图_20211106152034](https://user-images.githubusercontent.com/14054362/140601594-2d5087a1-4e3d-4a96-9fde-2a5a5e7157df.png) ![微信截图_20211106152052](https://user-images.githubusercontent.com/14054362/140601595-0bf81f4b-502f-434c-b185-5081b1620749.png)

你输出什么

**Comment by RuojiWang** [comment]
> > > 配置文件以什么文件命名？内容是哪里下载？
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年11月5日(周五) 晚上7:49 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675) 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： 我看别人正常情况好像都是这样的： 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > > > 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： ![140316417-aac2ef4a-b8d4-4331-ae76-80f2cabb8f4d](https://user-images.githubusercontent.com/14054362/140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689.png)
> > > > 我看别人正常情况好像都是这样的： ![140316583-1eb8db42-5afd-4ce1-a2d5-828723e26324](https://user-images.githubusercontent.com/14054362/140329347-84ec3601-3c1e-4b30-8f82-ffec021aa616.jpg) ![140316593-bce586df-9d77-4dbd-a4f1-39b744d6f622](https://user-images.githubusercontent.com/14054362/140329354-b6006b64-0e1c-4071-94e2-4df13e52e63c.jpg)
> > > > 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。
> > > 
> > > 
> > > 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。
> > 
> > 
> > 这是我的clash文件夹（clash二进制文件所在位置），这些文件确实从订阅的网站下载下来了 ![微信截图_20211106151558](https://user-images.githubusercontent.com/14054362/140601586-bdc75788-5da8-4aa1-b122-d12c93f06ea2.png)
> > 这是我的.config下面的clash文件夹，一开始里面的两个文件打开是空的，我把上面的clash文件夹里面的文件复制进去了（因为我无法使用clash，但是看有人这样做就可以用了，于是我也复制进去。。） ![微信截图_20211106151657](https://user-images.githubusercontent.com/14054362/140601591-73341623-14d8-49ca-99f3-d3a1d5e9efca.png)
> > 我在这里买的clash订阅，然后他的安装使用步骤如下图所示，前面一两步和他步骤一样，主要是第三个图我输入./clash的输出和他们不一样 ![微信截图_20211106152034](https://user-images.githubusercontent.com/14054362/140601594-2d5087a1-4e3d-4a96-9fde-2a5a5e7157df.png) ![微信截图_20211106152052](https://user-images.githubusercontent.com/14054362/140601595-0bf81f4b-502f-434c-b185-5081b1620749.png)
> 
> 你输出什么

我输入./clash输出的结果如下图所示，然后clash dashborad点击确定也进不到选择节点的页面。。
![140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689 (1)](https://user-images.githubusercontent.com/14054362/140601882-98a33dbb-2f71-4355-8411-77e432d57995.png)

**Comment by lizenghui** [comment]
> > > > 配置文件以什么文件命名？内容是哪里下载？
> > > > […](#)
> > > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年11月5日(周五) 晚上7:49 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675) 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： 我看别人正常情况好像都是这样的： 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > > > 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： ![140316417-aac2ef4a-b8d4-4331-ae76-80f2cabb8f4d](https://user-images.githubusercontent.com/14054362/140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689.png)
> > > > > 我看别人正常情况好像都是这样的： ![140316583-1eb8db42-5afd-4ce1-a2d5-828723e26324](https://user-images.githubusercontent.com/14054362/140329347-84ec3601-3c1e-4b30-8f82-ffec021aa616.jpg) ![140316593-bce586df-9d77-4dbd-a4f1-39b744d6f622](https://user-images.githubusercontent.com/14054362/140329354-b6006b64-0e1c-4071-94e2-4df13e52e63c.jpg)
> > > > > 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。
> > > > 
> > > > 
> > > > 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。
> > > 
> > > 
> > > 这是我的clash文件夹（clash二进制文件所在位置），这些文件确实从订阅的网站下载下来了 ![微信截图_20211106151558](https://user-images.githubusercontent.com/14054362/140601586-bdc75788-5da8-4aa1-b122-d12c93f06ea2.png)
> > > 这是我的.config下面的clash文件夹，一开始里面的两个文件打开是空的，我把上面的clash文件夹里面的文件复制进去了（因为我无法使用clash，但是看有人这样做就可以用了，于是我也复制进去。。） ![微信截图_20211106151657](https://user-images.githubusercontent.com/14054362/140601591-73341623-14d8-49ca-99f3-d3a1d5e9efca.png)
> > > 我在这里买的clash订阅，然后他的安装使用步骤如下图所示，前面一两步和他步骤一样，主要是第三个图我输入./clash的输出和他们不一样 ![微信截图_20211106152034](https://user-images.githubusercontent.com/14054362/140601594-2d5087a1-4e3d-4a96-9fde-2a5a5e7157df.png) ![微信截图_20211106152052](https://user-images.githubusercontent.com/14054362/140601595-0bf81f4b-502f-434c-b185-5081b1620749.png)
> > 
> > 
> > 你输出什么
> 
> 我输入./clash输出的结果如下图所示，然后clash dashborad点击确定也进不到选择节点的页面。。 ![140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689 (1)](https://user-images.githubusercontent.com/14054362/140601882-98a33dbb-2f71-4355-8411-77e432d57995.png)

你当前目录下是不是没有clash的配置文件，clash的配置文件是config.yaml

**Comment by ZhangZh3ng** [comment]
兄弟，我也遇到这个问题了，你把下载的config.yml重命名为config.yaml试试

**Comment by huiruo** [comment]
我解决了，在ubuntu设置全局代理，对应端口



---原始邮件---
发件人: "Zhang ***@***.***&gt;
发送时间: 2021年11月11日(周四) 下午4:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675)




 
兄弟，我也遇到这个问题了，你把下载的config.yml重命名为config.yaml试试

**Comment by RuojiWang** [comment]
> 兄弟，我也遇到这个问题了，你把下载的config.yml重命名为config.yaml试试
我现在把clash软件目录和.config/clash下面的两个config.yml都重命名问config.yaml了，然后在clash的文件夹下面执行./clash -d .  效果如下图所示= =！好像还是不对。
![微信截图_20211115222211](https://user-images.githubusercontent.com/14054362/141797876-2697cbaf-c6c3-48a5-a4d1-6193772c2beb.png)

原来的config.yaml（原来clash文件夹下面有config.yaml文件）和config.yml内容如下图所示，是不是这两个文件中的内容有问题（主要担心右边的文件需要配置）？
![微信截图_20211115223151](https://user-images.githubusercontent.com/14054362/141799372-dcfab296-97b2-457d-8849-cf8623a30fb1.png)

**Comment by RuojiWang** [comment]
> 我解决了，在ubuntu设置全局代理，对应端口
> […](#)
> ---原始邮件--- 发件人: "Zhang ***@***.***&gt; 发送时间: 2021年11月11日(周四) 下午4:22 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675) 兄弟，我也遇到这个问题了，你把下载的config.yml重命名为config.yaml试试 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

兄弟你说的设置是指下图的最后一个步骤吧，我连倒数第二个步骤点击确定都看不到页面= =！
![140601595-0bf81f4b-502f-434c-b185-5081b1620749](https://user-images.githubusercontent.com/14054362/141800246-fe3eae07-5dec-466e-b321-88a8206822f5.png)

**Comment by RuojiWang** [comment]
> 兄弟，我也遇到这个问题了，你把下载的config.yml重命名为config.yaml试试

感谢，问题解决了。
厂家远程协助半个小时就解决问题咯。
是厂家的使用教程没有跟着版本更新（图片和文字都和新版本有些出入，第一次使用的搞不懂什么情况，一直以为自己哪里配置没有对），直接把config.yml更新为config.yaml，其他的大体按照教程操作就可以了。

**Comment by RuojiWang** [comment]
> > > > > 配置文件以什么文件命名？内容是哪里下载？
> > > > > […](#)
> > > > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年11月5日(周五) 晚上7:49 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Dreamacro/clash] 请问ubuntu 怎么安装clash, 我下载了clash-linux-amd64-v1.7.1发现并不能安装成功 (#1675) 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： 我看别人正常情况好像都是这样的： 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > 
> > > > 
> > > > > > 输入./clash -d . 和访问 Clash Dashboard的页面是这样的（点击Clash Dashboard的确定没有反应）： ![140316417-aac2ef4a-b8d4-4331-ae76-80f2cabb8f4d](https://user-images.githubusercontent.com/14054362/140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689.png)
> > > > > > 我看别人正常情况好像都是这样的： ![140316583-1eb8db42-5afd-4ce1-a2d5-828723e26324](https://user-images.githubusercontent.com/14054362/140329347-84ec3601-3c1e-4b30-8f82-ffec021aa616.jpg) ![140316593-bce586df-9d77-4dbd-a4f1-39b744d6f622](https://user-images.githubusercontent.com/14054362/140329354-b6006b64-0e1c-4071-94e2-4df13e52e63c.jpg)
> > > > > > 这是什么情况啊，有大佬知道么？ 我好像运行clash就有问题，更不要说是打开Dashboard了。。。
> > > > > 
> > > > > 
> > > > > 你这看起来当前目录没有clash的配置文件。 external-controller: :9090 这个是API的配置端口 你的端口都没启用 肯定不能访问。
> > > > 
> > > > 
> > > > 这是我的clash文件夹（clash二进制文件所在位置），这些文件确实从订阅的网站下载下来了 ![微信截图_20211106151558](https://user-images.githubusercontent.com/14054362/140601586-bdc75788-5da8-4aa1-b122-d12c93f06ea2.png)
> > > > 这是我的.config下面的clash文件夹，一开始里面的两个文件打开是空的，我把上面的clash文件夹里面的文件复制进去了（因为我无法使用clash，但是看有人这样做就可以用了，于是我也复制进去。。） ![微信截图_20211106151657](https://user-images.githubusercontent.com/14054362/140601591-73341623-14d8-49ca-99f3-d3a1d5e9efca.png)
> > > > 我在这里买的clash订阅，然后他的安装使用步骤如下图所示，前面一两步和他步骤一样，主要是第三个图我输入./clash的输出和他们不一样 ![微信截图_20211106152034](https://user-images.githubusercontent.com/14054362/140601594-2d5087a1-4e3d-4a96-9fde-2a5a5e7157df.png) ![微信截图_20211106152052](https://user-images.githubusercontent.com/14054362/140601595-0bf81f4b-502f-434c-b185-5081b1620749.png)
> > > 
> > > 
> > > 你输出什么
> > 
> > 
> > 我输入./clash输出的结果如下图所示，然后clash dashborad点击确定也进不到选择节点的页面。。 ![140329309-68b1b63c-8ea0-48a5-8e1b-46d9c4f04689 (1)](https://user-images.githubusercontent.com/14054362/140601882-98a33dbb-2f71-4355-8411-77e432d57995.png)
> 
> 你当前目录下是不是没有clash的配置文件，clash的配置文件是config.yaml

感谢，问题解决了。
当下的目录是有config.yaml的，但是这个文件有问题，需要用config.yml复制替换。

厂家远程协助半个小时就解决问题咯。
是厂家的使用教程没有跟着版本更新（图片和文字都和新版本有些出入，第一次使用的搞不懂什么情况，一直以为自己哪里配置没有对），直接把config.yml更新为config.yaml，其他的大体按照教程操作就可以了。
