### ISSUE TITLE
可否支持配置文件滚动更新或者加一个保留栏目

### ISSUE THREAD

**Issue by HuLian21** [Dreamacro/clash#169]
有的时候需要自己对文件进行修改，添加规则/代理(例如标准socks5/http)，添加特定URL的指定代理线路，而这些改动会在通过url更新后清除，可否添加用户保留配置的栏目？

**Comment by Dreamacro** [comment]
没有理解你再说什么，展开详细说一下

**Comment by HuLian21** [comment]
就是类似ssr的user.rule
因为现在clash用户很多是通过服务商给的链接订阅的，而这种更新配置文件的方式是完全覆盖前一个配置文件的。
有些情况下，下载的配置文件不能完全覆盖用户需求，需要用户手动做些修改，但是一旦更新订阅，所有节点和规则又被完全覆盖了。。。
能否支持多个配置文件共同使用呢，比如我自建一个user.yml 然后在里面加入需要的规则和节点，同时从别的服务商给的链接下载xxxcloud.yml，一旦规则冲突就以user.yml为准。

**Comment by Dreamacro** [comment]
但是规则实际上是和代理向绑定的，不能互相使用。而且 clash 本身没提供订阅功能，订阅是 GUI 实现的。你应该去对应 GUI 下去请求实现。

**Comment by diemus** [comment]
我觉得proxy和rule相互绑定影响了配置的灵活性。rule显然需要有专门的小组维护，类似gfwlist的pac，并且用户一般会有一些定制化需求。而服务商应该专注于提供proxy，而不是去替用户决定哪些网站该使用什么代理。clash 本身虽然没提供订阅功能，但是这种结构会影响订阅功能，对用户不太友好，我觉得是不是proxy和rule分开会好一点？这样可以分开订阅。

**Comment by Dreamacro** [comment]
@diemus 规则本身就是和代理组相互绑定的，如果你认为他们不应该相互绑定，那么你应该提出一个解决方案，需要给出更详细的细节。

**Comment by kejaxe** [comment]
> @diemus 规则本身就是和代理组相互绑定的，如果你认为他们不应该相互绑定，那么你应该提出一个解决方案，需要给出更详细的细节。

能否做一个选项的部分，代替现有的直接对应服务器
例：规则一→选项1→A服务器/reject/直连

**Comment by Dreamacro** [comment]
@kejaxe 看起来你只要在 Proxy Group 加一个 select 类型的代理组就可以做到
