### ISSUE TITLE
[Feature] resolve domains in bypass routes with direct dns

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1703]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hi
as you can see in sagernet/anxray app which have v2fly/xray core there is an option that can resolve direct domains with specific dns.
I hope you can add this feature to clash core.
thanks
![sagernet](https://user-images.githubusercontent.com/74687186/139517607-13ade9b2-1c19-4000-9d1d-e3661f28446f.jpg)

### Possible Solution

use sagernet and v2fly documentation.
https://github.com/SagerNet/SagerNet
https://www.v2fly.org/config/dns.html

**Comment by luwah** [comment]
nameserver-policy:
    'www.baidu.com': '114.114.114.114'
    '+.internal.crop.com': '10.0.0.1'

**Comment by fsheidaiee** [comment]
> nameserver-policy: 'www.baidu.com': '114.114.114.114' '+.internal.crop.com': '10.0.0.1'

this is only for specific domains, the feature in sagernet implements dns on all ip/domains that has direct connection.

**Comment by luwah** [comment]
All DNS questions are sent directly to the nameserver, without proxies involved.

Please refer to the "configration" in Wiki.

**Comment by fsheidaiee** [comment]
> All DNS questions are sent directly to the nameserver, without proxies involved.
> 
> Please refer to the "configration" in Wiki.

I know that.
want im suggesting is a new feature.
as you can see.
sagernet has two fields for dns.
one is remote dns: whis is used for all domains. (and its can also be sent directly to the server if configured like this: for example: https+local://1.0.0.1.com/dns-query)
the second is called "direct dns" direct dns does not mean that the dns request sent directly to server. this dns server is used for domains that has direct connection in rules.
for example if you set direct connection for geoip: cn or geosite: cn, all sites with geoip or geosite of china will be resolved through direct dns not the remote dns.
