### ISSUE TITLE
[Bug] TAP连接显示错误

### ISSUE THREAD

**Issue by bemarkt** [Dreamacro/clash#1704]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.09.15/nightly-g3bc258c

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
ip = metadata["dst_ip"] or ctx.resolve_ip(metadata["host"])
if ip == "":
  return "DIRECT"
code = ctx.geoip(ip)
if code == "CN":
  return "DIRECT"
elif metadata["network"] == "udp":
  return "🇭🇰 深港专线"
```

### Clash log

```shell
time="2021-10-29T17:07:45+08:00" level=info msg="[UDP] 127.0.0.1:63457 --> 155.133.235.18:27020 using 🇭🇰 深港专线 by Script"
time="2021-10-29T17:07:45+08:00" level=info msg="[UDP] 127.0.0.1:63456 --> 155.133.233.98:27048 using 🇭🇰 深港专线 by Script"
time="2021-10-29T17:07:45+08:00" level=info msg="[UDP] 127.0.0.1:63460 --> 155.133.249.194:27054 using 🇭🇰 深港专线 by Script"
time="2021-10-29T17:07:45+08:00" level=info msg="[UDP] 127.0.0.1:63461 --> 139.45.193.10:27015 using 🇭🇰 深港专线 by Script"
```

### Description

通过 cfw以及 clash-dashboard比对上述日志第一条连接皆为：

![image](https://user-images.githubusercontent.com/25723505/139524804-185532f0-eda0-4732-923c-87ddf887f071.png)

跟日志中的 IP不相同，正确连接 IP为日志中 IP ，连接中显示为错误的 IP（该错误 ip 进行过 udp 连接

结果会导致下图类似状况，`同一` ip显示不同策略。

![image](https://user-images.githubusercontent.com/25723505/139524902-54116414-493f-44c2-a75d-be96d074fb2c.png)

（该图为两者反转，155为显示错误 ip且在之前连接后断掉，而后持续连接43，43应为连接显示ip）

**Comment by bemarkt** [comment]
另在最新clash premium版中 Windows TUN的 udp仍有该问题 #1627  
使用gvisor udp查询显示更少，system一般，使用tap正常，使用netch的wintun模式正常。~~可能一瞬间udp发包过多受限制了？~~

**Comment by Dreamacro** [comment]
dns 用的是 redir-host？

**Comment by bemarkt** [comment]
> dns 用的是 redir-host？

用的fake-ip 连接是直接通过ip连的

**Comment by bemarkt** [comment]
已修复
