### ISSUE TITLE
[Bug] windows 11好像不能安装

### ISSUE THREAD

**Issue by jimboybo** [Dreamacro/clash#1706]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

windows 11 下无法安装成功，不知道是什么原因？surface pro 8硬件

### Possible Solution

希望帮忙windows 11安装成功

**Comment by Dreamacro** [comment]
clash 并不需要安装, 提错地方了
