### ISSUE TITLE
Does the clash support PROCESS-NAME rule to handle specific process's traffic ?

### ISSUE THREAD

**Issue by ingjieye** [Dreamacro/clash#171]

**Comment by Dreamacro** [comment]
I haven't found a way to convert from `net.Conn` to process name yet. so clash doesn't support `PROCESS-NAME` now.

**Comment by gihnius** [comment]
This will be a super cool feature!
@Dreamacro  pls  reference https://github.com/weaveworks/procspy

**Comment by Dreamacro** [comment]
@gihnius have a quick look for this project I found out that it uses `os/exec` to get the TCP process list on Darwin. it's unreliable.

**Comment by mugkid** [comment]
This feature will be really helpful if added. It'll prevent apps from using google.com to check wether the user have access to certain network condition.

**Comment by Dreamacro** [comment]
@mugkid but it's hard to implementation in go.
