### ISSUE TITLE
linux服务器中只能使用终端，没有可视化界面怎么使用clash

### ISSUE THREAD

**Issue by zlsfe** [Dreamacro/clash#1710]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

![image](https://user-images.githubusercontent.com/60097556/139825115-12bf170d-5159-47da-957f-3d10c549c0ec.png)
接下来的操作怎么在终端下用命令行实现？

**Comment by Dreamacro** [comment]
Duplicate of #1688

**Comment by zlsfe** [comment]
可以介绍一下怎么使用https://github.com/Dreamacro/clash-ctl吗

**Comment by zlsfe** [comment]
> Duplicate of #1688

可以介绍一下怎么使用https://github.com/Dreamacro/clash-ctl 吗
