### ISSUE TITLE
[Feature] 能否增加一种fallback结合url-test的模式，故障的时候去选最快节点，而不是选下一个节点

### ISSUE THREAD

**Issue by jiangmw** [Dreamacro/clash#1724]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

能否增加一种fallback结合url-test的模式，故障的时候去选最快节点，而不是选下一个可用节点

**Comment by Dreamacro** [comment]
url-test 目前就是最快的节点故障时，会重新找当前最快的 alive 节点

**Comment by jiangmw** [comment]
> url-test 目前就是最快的节点故障时，会重新找当前最快的 alive 节点

想要的是当前节点故障的时候才去测速选最快，url-test并不是这样

**Comment by chimaoshu** [comment]
> > url-test 目前就是最快的节点故障时，会重新找当前最快的 alive 节点
> 
> 想要的是当前节点故障的时候才去测速选最快，url-test并不是这样吧？

你设置一个url-test的规则组a，然后设置一个fallback规则组，包含主节点和前面的规则组a，这样不就是：主节点故障的时候fallback到url-test的规则组，在url-test里面选择一个最快的。

**Comment by miffyrcee** [comment]
我觉得是速度最快，而不是延迟最快才好。

**Comment by matthuo333** [comment]
> > > url-test 目前就是最快的节点故障时，会重新找当前最快的 alive 节点
> > 
> > 
> > 想要的是当前节点故障的时候才去测速选最快，url-test并不是这样吧？
> 
> 你设置一个url-test的规则组a，然后设置一个fallback规则组，包含主节点和前面的规则组a，这样不就是：主节点故障的时候fallback到url-test的规则组，在url-test里面选择一个最快的。
实际用过? 我测试下来，发现刚启动core后，fallback完全不准，总是跳到最后个节点上。运行差不多5-10分钟后，不会跳到最后个，但是urltest组其实有效，但是仍然跳开。（轮询间隔时间两个组有差50s）.

**Comment by matthuo333** [comment]
> 我觉得是速度最快，而不是延迟最快才好。

有好的方案么？

**Comment by matthuo333** [comment]
如果 Fallback A  嵌套 一个 fallback B  ,   A 是中节点是B 的子集。  A 节点全线无效。此时， A 组会选择 fallback B 么？ 目前测试下来不会。
