### ISSUE TITLE
如何让SwitchyOmega控制代理

### ISSUE THREAD

**Issue by durongzhang** [Dreamacro/clash#173]
发现使用clash后，SwitchyOmega的分发没有用了，只会走clash的规则，如何配置才能使SwitchyOmega起作用

**Comment by Dreamacro** [comment]
```yml
Rule:
 - MATCH,ProxyName
```

**Comment by fengmao31** [comment]
这是clash里面的规则，我们问的是浏览器里面的。因为希望整体走国内，只有浏览器走国外。这样OneNote笔记不会同步错误。

**Comment by erenlu** [comment]
你好，请问问题解决了吗，我目前也是这样的疑惑。 想在clash上使用直连模式，chrome上利用switchomega去分流。

**Comment by fengmao31** [comment]
udp转发解除限制就行

**Comment by fengmao31** [comment]
onenote里面勾选OneNote for window10就行

**Comment by ethancn** [comment]
用 `PROCESS-NAME` 就行了，放在规则的最前面：

```
PROCESS-NAME,chrome.exe,Proxy
```

Mac的话进程名好像是 `Google Chrome Helper`。

**Comment by jiahe224** [comment]
rules:
  PROCESS-NAME,chrome.exe,Proxy

**Comment by jiahe224** [comment]
新心得，switchy中的代理配置将代理端口改为clash使用的7890即可，常见的其它如V2rayN是10808，Trojan-QT5是51837，TrojanX是1080

**Comment by hzx505** [comment]
CLASH 的 system proxy 系统代理 关闭 就可以拉，

**Comment by palemoky** [comment]
> 用 `PROCESS-NAME` 就行了，放在规则的最前面：
> 
> ```
> PROCESS-NAME,chrome.exe,Proxy
> ```
> 
> Mac 的话进程名好像是 `Google Chrome Helper`。

Clash for Windows 的Proxy需要全大写 PROXY，不然配置文件一直报错 rule[0] 问题，我找了半天才发现是大小写的问题

**Comment by AndyJZhao** [comment]
SwitchyOmega设置：
端口为Clash 的端口 7890。

ClashX 设置：
Proxy Mode：Global
Set as System Proxy: Off
