### ISSUE TITLE
[Bug] Win下 1.8.0 版本 重启程序或计算机后 不能创建tun网卡

### ISSUE THREAD

**Issue by uuip** [Dreamacro/clash#1737]
### Verify steps

- []  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- []  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash pro 1.8.0

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
    enable: true
    stack: system
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
```

### Clash log

```shell
time="2021-11-14T10:29:42+08:00" level=info msg="RESTful API listening at: 127.0.0.1:64035"
time="2021-11-14T10:29:42+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:1090"
time="2021-11-14T10:29:42+08:00" level=info msg="Start initial provider amy"
time="2021-11-14T10:29:42+08:00" level=info msg="Start initial provider iplc"
time="2021-11-14T10:29:42+08:00" level=info msg="Start initial provider mdss"
time="2021-11-14T10:29:42+08:00" level=info msg="Start initial compatible provider PROXY"
time="2021-11-14T10:29:42+08:00" level=info msg="Start initial rule provider proxy"
time="2021-11-14T10:29:42+08:00" level=info msg="Start initial rule provider reject"
time="2021-11-14T10:29:42+08:00" level=info msg="Start initial rule provider direct"
time="2021-11-14T10:29:42+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-11-14T10:29:57+08:00" level=error msg="Start Tun interface error: error creating interface: Cannot create a file when that file already exists."
```

### Description

1. 计算机重启后，启动程序无法创建tun网卡。
2. 在clash for windows 里执行重启命令，重启后无法创建tun网卡。
3. 退出 clash for windows ，再打开程序无法创建tun网卡。
 clash for windows 版本 0.18.8，它使用的clash 为1.8.0

已测试 将 cfw的clash 和 wintun 换成上个版本1.7.1和 wintun 0.12的，问题不再出现。

**Comment by Dreamacro** [comment]
看 premium 更新日志

**Comment by uuip** [comment]
我查看过日志。
本机wintun是0.14.1. 
adjust system stack behavior 是调整了什么？
@Dreamacro
