### ISSUE TITLE
后台模式

### ISSUE THREAD

**Issue by updater1234** [Dreamacro/clash#174]
你好请问，可以添加一种静默在后台而不用弹窗的模式吗？就类似于v2ray中的wv2ray.exe这样。

**Comment by yichengchen** [comment]
clash是命令行程序不会弹窗吧…

**Comment by guzzhao** [comment]
vbs启动:
`CreateObject("WScript.Shell").Run "clash.exe -d .",0       `

**Comment by Dreamacro** [comment]
如果不会操作，可以直接用 windows 的 gui “clash for windows”

**Comment by updater1234** [comment]
了解，我先试一下vbs的方法。

**Comment by Kr328** [comment]
也可以尝试 https://github.com/kohsuke/winsw 将 clash 启动为 Windows服务

**Comment by Dreamacro** [comment]
close because of no more feedback
