### ISSUE TITLE
[Feature] 为proxy-providers 添加 skip-cert-verify: true 支持

### ISSUE THREAD

**Issue by issenn** [Dreamacro/clash#1741]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在添加 proxy-providers 的时候提示：
initial proxy provider 'others' error: Get "https://www.*******.com/clash/proxies": x509: certificate has expired or is not yet valid: current time 2021-11-15T09:21:22+08:00 is after 2021-06-02T14:44:58Z

源域名的证书过期了。希望能为 proxy-providers 添加 skip-cert-verify: true 支持。

**Comment by fakeboboliu** [comment]
代理自签也就算了，provider 允许自签/过期显然带来的危险性要高于允许代理自签

**Comment by issenn** [comment]
确实，挺不安全的。我个人用其他方式绕一下。

**Comment by issenn** [comment]
确实，挺不安全的。我个人用其他方式绕一下。

**Comment by issenn** [comment]
确实，挺不安全的。我个人用其他方式绕一下。
