### ISSUE TITLE
[Feature] it is support ss plugin  cloak  ?

### ISSUE THREAD

**Issue by taylorwin** [Dreamacro/clash#1743]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

cloak : https://github.com/cbeuw/Cloak

If it is supported, how should I configure it?
I did not find any help information in this wiki help
https://github.com/Dreamacro/clash/wiki

**Comment by fakeboboliu** [comment]
nope, but PR is welcome.

**Comment by taylorwin** [comment]
> nope, but PR is welcome.

Does xray-plugin support clash ？

**Comment by k3r3hor3** [comment]
> > nope, but PR is welcome.
> 
> Does xray-plugin support clash ？

- name: "ss2"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: obfs
  plugin-opts:
    mode: tls # or http
    # host: bing.com

- name: "ss3"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket # no QUIC now
    # tls: true # wss
    # skip-cert-verify: true
    # host: bing.com
    # path: "/"
    # mux: true
    # headers:
    #   custom: value

**Comment by k3r3hor3** [comment]
> > nope, but PR is welcome.
> 
> Does xray-plugin support clash ？

`- name: "ss2"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: obfs
  plugin-opts:
    mode: tls # or http
    # host: bing.com

- name: "ss3"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket # no QUIC now
    # tls: true # wss
    # skip-cert-verify: true
    # host: bing.com
    # path: "/"
    # mux: true
    # headers:
    #   custom: value
`
