### ISSUE TITLE
socket: too many open files on openwrt x86-64

### ISSUE THREAD

**Issue by KangKai1982** [Dreamacro/clash#177]
amd64版本在openwrt x86-64上运行时，报错socket: too many open files，lsof查看clash打开超过10000个

**Comment by beyondkmp** [comment]
@KangKai1982  看下是udp还是tcp?

**Comment by KangKai1982** [comment]
@beyondkmp TCP而且超大量的IPv6链接

> clash     25589 30546 clash      root  884u     IPv6             720707      0t0        TCP localhost:1234->192.168.1.2:45480 (ESTABLISHED)


基本上所有端口挨个开了一遍

**Comment by beyondkmp** [comment]
应该是有什么程序在一直重试吧

**Comment by KangKai1982** [comment]
只是在客户端电脑上的chrome里开了个youtube而已

**Comment by Dreamacro** [comment]
clash 的日志呢

**Comment by KangKai1982** [comment]
@Dreamacro 就只是这样，开了个YouTube，203这个ip应该是googlecn的

> WARN[0052] Proxy[DIRECT] connect [192.168.1.2 --> 203.208.40.78] error: dial tcp 203.208.40.78:443: socket: too many open files
WARN[0057] Proxy[DIRECT] connect [192.168.1.2 --> 203.208.40.78] error: dial tcp 203.208.40.78:443: socket: too many open files
WARN[0057] Proxy[DIRECT] connect [192.168.1.2 --> 203.208.40.78] error: dial tcp 203.208.40.78:443: socket: too many open files

**Comment by Dreamacro** [comment]
没有 host 你是没有用 clash 的 dns server 吧

**Comment by KangKai1982** [comment]
没用clash的dns server
因为之前配置好了ipset/iptables的转发，我只是用clash替代了ss-redir而已

**Comment by Dreamacro** [comment]
我觉得应该是 iptables 的某个设置让 clash 变成环了

**Comment by KangKai1982** [comment]
那我把clash配置成globe方式先试试看

**Comment by KangKai1982** [comment]
@Dreamacro 似乎是geoip和iptables里的gfwlist发生了冲突，注释掉geoip rule似乎正常了
