### ISSUE TITLE
[Feature] Request to have the image for linux/arm/v6

### ISSUE THREAD

**Issue by LinuxSuRen** [Dreamacro/clash#1770]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

I cannot use the image `ghcr.io/dreamacro/clash` on Raspberry PI1. Below is the error log output:

```shell
root@raspberrypi:~# docker run -d --restart=always -p 7890:7890 ghcr.io/dreamacro/clash
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
```

### Possible Solution

IMO, it's possible to have support for `linux/arm/v6`

**Comment by thank243** [comment]
You can compile it on your pc.

**Comment by LinuxSuRen** [comment]
hi @thank243 , thanks for your response. Of course, I can do that. But I still hope I can use the image from the official repo.
