### ISSUE TITLE
[Feature] redir模式下IPv6的问题

### ISSUE THREAD

**Issue by paladin4fan** [Dreamacro/clash#1800]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

redir-host模式 不再支持代理DNS解析
之前匹配到规则的时候 DNS请求一起转发给服务器 不支持ipv6的服务器也可以正常回落到v4

现在本地解析后 碰到YouTube这些有ipv6地址的网站 会直接往代理服务器塞ipv6地址，代理服务器如果不支持v6 就会立刻ERR_CONNECTION_CLOSED
似乎是因为被代理了 浏览器不会判断IPv6地址响应超时而改成请求IPv4
于是一直重试访问v6地址
![image](https://user-images.githubusercontent.com/34474436/144733216-cdf4c193-924f-4dd8-93f8-cd75fd1aa2f6.png)

### Possible Solution

有没有办法在TPROXY发送ipv6代理返回空内容时 强制换成redir转发Ipv4请求呢

**Comment by Dreamacro** [comment]
建议 fakeip

**Comment by paladin4fan** [comment]
> 建议 fakeip

关于这两个DNS模式 我想请教一个问题
Fake-IP比起Redir-Host更快的原因是因为立刻返回fake-ip地址的缘故，但是如果没命中域名规则 这个也要由Clash进行一次解析吧 是否速度上就一样了呢

**Comment by Dreamacro** [comment]
@paladin4fan 这两个模式主要都是为了解决透明代理怎么获取域名的问题，redir-host 模式有天然的缺陷，所以更建议 fakeip

**Comment by paladin4fan** [comment]
> @paladin4fan 这两个模式主要都是为了解决透明代理怎么获取域名的问题，redir-host 模式有天然的缺陷，所以更建议 fakeip

那这个版本之前 是不是命中了域名规则 redir模式也要先解析一次DNS 记录下对应关系后 才把整个host发给服务端呢

**Comment by Dreamacro** [comment]
@paladin4fan 对的，redir-host 没有省任何 dns 请求。fakeip 有可能可以省下一次 dns

**Comment by paladin4fan** [comment]
> @paladin4fan 对的，redir-host 没有省任何 dns 请求。fakeip 有可能可以省下一次 dns

明白了 之前只知道域名规则都会把整个host发给服务器 但是一直没明白fake-ip为什么会更快
那么之前首次解析的DNS也是从本地解析的吗
