### ISSUE TITLE
[Feature] add app list for disable/enable use clash

### ISSUE THREAD

**Issue by morteza-farhadi** [Dreamacro/clash#1806]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

add custom list of all app in OS and for each app set radio button
when radio button on app use clash protocol and when radio off app don't use clash
tnx

**Comment by Misaka-0x447f** [comment]
这看起来不是 clash core 应该干的事...

**Comment by Misaka-0x447f** [comment]
seems not something that clash core should implement....
