### ISSUE TITLE
[Feature] add wireguard protocol support

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#1827]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hi
please add wireguard protocol support in the core.
thanks

### Possible Solution

see sagernet project

**Comment by fsheidaiee** [comment]
No solution?

**Comment by BirkhoffLee** [comment]
Wireguard configuration:
```
[Interface]
PrivateKey = ...
Address = ...
MTU = ...
Table = 6666
PostUp = ip rule add from <Address> table 6666

[Peer]
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
PublicKey = ...
Endpoint = ...
```

Assume `wg0` to be Wireguard interface name

Clash:
```yaml
proxy-groups:
  - name: Wireguard
    type: select
    interface-name: wg0
    proxies:
      - DIRECT
rules:
  - DOMAIN,google.com,Wireguard
```

**Comment by ZERO4OREZ** [comment]
> 

I setup my wireguard tun, and it worked between my server and client. However, all traffic goes throught this tun. I think I can  use clash to make some traffic just go DIRECT instead. So how this config work? It seems all traffic goes throught wireguard still. Please.

**Comment by ZERO4OREZ** [comment]
> Wireguard configuration:
> 
> ```
> [Interface]
> PrivateKey = ...
> Address = ...
> MTU = ...
> Table = 6666
> PostUp = ip rule add from <Address> table 6666
> 
> [Peer]
> AllowedIPs = 0.0.0.0/0
> AllowedIPs = ::/0
> PublicKey = ...
> Endpoint = ...
> ```
> 
> Assume `wg0` to be Wireguard interface name
> 
> Clash:
> 
> ```yaml
> proxy-groups:
>   - name: Wireguard
>     type: select
>     interface-name: wg0
>     proxies:
>       - DIRECT
> rules:
>   - DOMAIN,google.com,Wireguard
> ```
> 
> This should perform better than whereas if Clash implemented its own userspace Wireguard client. Wireguard is supported in the kernel.

I setup my wireguard tun, and it worked between my server and client. However, all traffic goes throught this tun. I think I can  use clash to make some traffic just go DIRECT instead. So how this config work? It seems all traffic goes throught wireguard still. Please.

**Comment by BirkhoffLee** [comment]
> > Wireguard configuration:
> > ```
> > [Interface]
> > PrivateKey = ...
> > Address = ...
> > MTU = ...
> > Table = 6666
> > PostUp = ip rule add from <Address> table 6666
> > 
> > [Peer]
> > AllowedIPs = 0.0.0.0/0
> > AllowedIPs = ::/0
> > PublicKey = ...
> > Endpoint = ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Assume `wg0` to be Wireguard interface name
> > Clash:
> > ```yaml
> > proxy-groups:
> >   - name: Wireguard
> >     type: select
> >     interface-name: wg0
> >     proxies:
> >       - DIRECT
> > rules:
> >   - DOMAIN,google.com,Wireguard
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should perform better than whereas if Clash implemented its own userspace Wireguard client. Wireguard is supported in the kernel.
> 
> I setup my wireguard tun, and it worked between my server and client. However, all traffic goes through this tun. I think I can use clash to make some traffic just go DIRECT instead. So how does this config work? It seems like all traffic go through wireguard still. Please.

```yaml
rules:
  - DOMAIN,google.com,Wireguard
  - MATCH,DIRECT
```

**Comment by ZERO4OREZ** [comment]
> > > Wireguard configuration:
> > > ```
> > > [Interface]
> > > PrivateKey = ...
> > > Address = ...
> > > MTU = ...
> > > Table = 6666
> > > PostUp = ip rule add from <Address> table 6666
> > > 
> > > [Peer]
> > > AllowedIPs = 0.0.0.0/0
> > > AllowedIPs = ::/0
> > > PublicKey = ...
> > > Endpoint = ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Assume `wg0` to be Wireguard interface name
> > > Clash:
> > > ```yaml
> > > proxy-groups:
> > >   - name: Wireguard
> > >     type: select
> > >     interface-name: wg0
> > >     proxies:
> > >       - DIRECT
> > > rules:
> > >   - DOMAIN,google.com,Wireguard
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This should perform better than whereas if Clash implemented its own userspace Wireguard client. Wireguard is supported in the kernel.
> > 
> > 
> > I setup my wireguard tun, and it worked between my server and client. However, all traffic goes through this tun. I think I can use clash to make some traffic just go DIRECT instead. So how does this config work? It seems like all traffic go through wireguard still. Please.
> 
> ```yaml
> rules:
>   - DOMAIN,google.com,Wireguard
>   - MATCH,DIRECT
> ```

Thanks. So DIRECT has two meaning here, right? In `proxies: - DIRECT` it means traffic would go through the interface wg0 DIRECTly, and others goes without any wrap in `MATCH, DIRECT`?

**Comment by BirkhoffLee** [comment]
That's correct. In
```yaml
proxy-groups:
  - name: Wireguard
    type: select
    interface-name: wg0
    proxies:
      - DIRECT
```
It's DIRECT **through** the wg0 interface.

**Comment by ZERO4OREZ** [comment]
> That's correct. In
> 
> ```yaml
> proxy-groups:
>   - name: Wireguard
>     type: select
>     interface-name: wg0
>     proxies:
>       - DIRECT
> ```
> 
> It's DIRECT **through** the wg0 interface.

Thank you.
