### ISSUE TITLE
[Bug] TUN+fake ip下根据规则直连的UDP连接会无法发出

### ISSUE THREAD

**Issue by codafi21** [Dreamacro/clash#1831]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [ ]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2021.12.07 premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
![image](https://user-images.githubusercontent.com/93474348/146550383-cf4ec8c0-cdb3-4620-8403-951ffae1ceb5.png)
```

### Clash log

```shell
time="2021-12-17T19:28:36+08:00" level=warning msg="[UDP] dial 🎯 全球直连 (match DomainSuffix/www.gstatic.com) to www.gstatic.com:443 error: listen udp :0: An invalid argument was supplied."
time="2021-12-17T19:28:36+08:00" level=warning msg="[UDP] dial 🎯 全球直连 (match DomainSuffix/www.gstatic.com) to www.gstatic.com:443 error: listen udp :0: An invalid argument was supplied."
time="2021-12-17T19:28:36+08:00" level=warning msg="[UDP] dial 🎯 全球直连 (match DomainSuffix/www.gstatic.com) to www.gstatic.com:443 error: listen udp :0: An invalid argument was supplied."
time="2021-12-17T19:28:38+08:00" level=warning msg="[UDP] dial 🎯 全球直连 (match DomainSuffix/www.gstatic.com) to www.gstatic.com:443 error: listen udp :0: An invalid argument was supplied."
time="2021-12-17T19:28:40+08:00" level=warning msg="[UDP] dial 🎯 全球直连 (match DomainSuffix/www.gstatic.com) to www.gstatic.com:443 error: listen udp :0: An invalid argument was supplied."
```

### Description

根据规则直连的UDP连接会无法发出,将相应域名改为海外节点连接则不会报错，如下图
![image](https://user-images.githubusercontent.com/93474348/146551002-f9deff18-0d65-4526-a2f8-8e257c0d83bf.png)

**Comment by lddsb** [comment]
I have the same problem

**Comment by zzzqu** [comment]
同有这个问题，应该是新版core的问题，回退之后就好了

**Comment by Fndroid** [comment]
怎么复现的呢？

**Comment by zzzqu** [comment]
> 怎么复现的呢？
就是最新版开启fakeip和tun 打qq语音或者英雄联盟查看日志 就会有error: listen udp :0: An invalid argument was supplied.

**Comment by zzzqu** [comment]
> 怎么复现的呢？ ![image](https://user-images.githubusercontent.com/16091562/147354416-b72d48f4-17d8-4308-8815-79df700cf165.png)

更新core之前的版本18.7无此问题

**Comment by HamsterReserved** [comment]
我这边遇到了类似的错误，排查得到的结论是互联网接口禁用了 IPv6 协议栈导致的。遇到此问题的各位也可检查一下看是不是同样的问题。

![ipv6](https://user-images.githubusercontent.com/10322384/147905999-9dfb3281-4268-4119-8bf3-6e9bac32a522.jpg)

**Comment by zzzqu** [comment]
实测开启ipv6就可以了，不过这样会导致dns泄露，不知道有什么好的方法

**Comment by HamsterReserved** [comment]
> 实测开启ipv6就可以了，不过这样会导致dns泄露，不知道有什么好的方法

可以用 MinHook 把 https://github.com/Dreamacro/clash/issues/1872#issuecomment-1003900438 这里提到的 setsockopt 返回值改为 0.

**Comment by Dreamacro** [comment]
maybe fixed on 2021.01.03

**Comment by ruisiji** [comment]
Seems this issue still exist in latest releases(2022.01.27 & 2022.01.03) on Linux, the error message is following:

> level=warning msg="[UDP] dial DIRECT (match GeoIP/CN) to 0.debian.pool.ntp.org:123 error: not support"
> level=warning msg="[UDP] dial DIRECT (match Match/) to cdnjs.cloudflare.com:443 error: not support"

More details can be found here: https://github.com/Dreamacro/clash/issues/1953
