### ISSUE TITLE
[Feature] type: http增加或者能修改headers

### ISSUE THREAD

**Issue by 363137946** [Dreamacro/clash#1832]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

proxies:
  - name: anyproxy
    type: http
    server: xxxxxx
    port: xxx

clash支持在http代理中增加headers吗，像下面这样
proxies:
  - name: anyproxy
    type: http
    server: xxxxxx
    port: xxx
    headers:
        - myserver:  xxxxxx

**Comment by ManiaciaChao** [comment]
clash后面跑个mitmproxy就行了
