### ISSUE TITLE
[Bug] docker clash cpu占用率周期性飙升

### ISSUE THREAD

**Issue by omitcn** [Dreamacro/clash#1835]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [ ]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [ ]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

docker pull dreamacro/clash:dev

### What OS are you seeing the problem on?

Linux

### Clash log

```shell
root@inhome:/home/soft/tomcat# podman logs clash
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider ✈️Telegram"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider 🎬国外媒体"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider 🚀直接连接"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider ⚓️其他流量"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider 🎬哔哩哔哩"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider 🎬Youtube"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider 🔰国外流量"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider 🎬Netflix"
time="2021-12-14T08:31:48Z" level=info msg="Start initial compatible provider 🍎苹果服务"
time="2021-12-14T08:31:48Z" level=info msg="RESTful API listening at: [::]:9090"
```

### Description

我用的阿里云轻量应用服务器，debian10.5 后台监控如下所示：
![image](https://user-images.githubusercontent.com/46101725/146700505-85927e3e-b1da-4347-9898-c6972bff9675.png)
使用top命令结果如下
![clash](https://user-images.githubusercontent.com/46101725/146700728-5dee0656-5782-45cd-8c63-e9a8c86ce668.jpg)
e3e-b1da-4347-9898-c6972bff9675.png)

**Comment by Dreamacro** [comment]
没有任何其他日志？

**Comment by omitcn** [comment]
> 没有任何其他日志？

能告诉下获取具体日志的方法吗？我不太了解

**Comment by Dreamacro** [comment]
podman logs 没有日志么

**Comment by omitcn** [comment]
> podman logs 没有日志么
podman logs clash获取的日志在上面有，clash log部分，你看一下，但是很少，感觉没啥有价值的信息
