### ISSUE TITLE
路由器如何配置[Feature] 

### ISSUE THREAD

**Issue by nances** [Dreamacro/clash#1858]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

1.您好，请教一个问题路由器里面如何配置，目前支持该功能么

**Comment by thank243** [comment]
建议移步openclash
