### ISSUE TITLE
[Feature] DIRECT 支持路由转发

### ISSUE THREAD

**Issue by cospotato** [Dreamacro/clash#1876]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

请问有没有可能让 `DIRECT` 模式支持直接路由流量，而不是通过 clash 转发呢？
因为这样做本质上是由 clash 做了一次 NAT 转发，而直接路由的好处是，在有大量 `DIRECT` 连接发起的时候，clash 仅将包通过 3 层路由转发出去，之后可以由路由器或者网关设备等来持有 NAT 连接，从而提高转发性能。

**Comment by flyhigherpi** [comment]
DIRECT是因为你的规则声明了DIRECT吧，规则怎么匹配到的，当然是因为进入CLASH匹配啊。所以不管你想怎么搞，流量还是进了CLASH走了一圈
国内IP用IPTABLES 过滤掉就是

**Comment by MonwF** [comment]
话说如何给内置的 direct 流量添加so mark，放到proxygroup里似乎无效

**Comment by semglassie** [comment]
多此一举，自己iptables加条过滤命令让他不要进入clash就行了

**Comment by cospotato** [comment]
> 多此一举，自己iptables加条过滤命令让他不要进入clash就行了

**Comment by cospotato** [comment]
> 多此一举，自己iptables加条过滤命令让他不要进入clash就行了

@semglassie 可能你没理解这个需求，我预期是经过 clash 走到 DIRECT channel 的流量保持原状直接转发，相当于在 clash 里做了 FORWARD，因为目前进入 clash 的再出来的包源地址就变成了 clash 的 ip，相当于做了 NAT，但我不想 NAT，内网地址已经用 iptables RETURN 了

**Comment by cospotato** [comment]
> 国内IP用IPTABLES 过滤掉就是

@flyhigherpi 嗯嗯，是声明了 DIRECT，这里的需求主要就是让匹配到 DIRECT 的包不修改源地址原样转发，而不是在 clash 里做了 NAT，毕竟国内地址千千万，更新 clash 的 rule 总比一条条的去维护一个庞大的 iptables 列表方便

**Comment by liofoil** [comment]
赞同这个提议，实测有些网站经过clash内核后就算是判定为DIRECT也可能有一些非预期行为：一直转圈，部分模块卡死之类。目前是通过iptable绕过解决的，不过这样DIRECT规则就失去了意义。

**Comment by skill7899** [comment]
> 

要是解决了q一下，直接forward而不是nat，nat导致一些跑cdn的跑不了。我现在也是用iptables的方式

**Comment by cospotato** [comment]
remove `Stale`

**Comment by cospotato** [comment]
remove `Stale`

**Comment by cospotato** [comment]
remove Stale

**Comment by cospotato** [comment]
remove `Stale`

**Comment by cospotato** [comment]
reopen
