### ISSUE TITLE
[Bug] 只有配置了GOEIP, CN, DIRECT的情况下Destination IP才有ip

### ISSUE THREAD

**Issue by soncy** [Dreamacro/clash#1886]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.01.03

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
- RULE-SET,Proxy,PROXY
- GEOIP, CN, DIRECT
- MATCH,DIRECT
```

### Description

只有配上了- GEOIP, CN, DIRECT后，控制面板中的Destination IP才有direct域名的ip值，如果只配置- MATCH,DIRECT，则direct的域名没有ip值，请问一下这个是程序实现的预期行为么？这里的处理逻辑是什么样的呢？谢谢

没有- GEOIP, CN, DIRECT，只有的- MATCH,DIRECT情况
<img width="1728" alt="QQ20220106-234559@2x" src="https://user-images.githubusercontent.com/1466481/148409787-5df4bb2a-ec51-4c06-851a-1c7a747ef419.png">

有- GEOIP, CN, DIRECT和- MATCH,DIRECT情况
<img width="1610" alt="QQ20220106-234255@2x" src="https://user-images.githubusercontent.com/1466481/148409842-e7d56701-a26a-4b66-bf6c-9ef06e511585.png">

**Comment by luwah** [comment]
GEOIP是需要先DNS解析，判定是CN后再走DIRECT
没有GEOIP就直接按照规则走MATCH，无需判定都会走DIRECT

**Comment by soncy** [comment]
> GEOIP是需要先DNS解析，判定是CN后再走DIRECT
> 没有GEOIP就直接按照规则走MATCH，无需判定都会走DIRECT

走DIRECT不是都应该要做DNS解析么？

**Comment by luwah** [comment]
应该是判定规则和DNS解析在这两种情况下运行的先后顺序不一样

**Comment by soncy** [comment]
> 应该是判定规则和DNS解析在这两种情况下运行的先后顺序不一样
> GEOIP,CN,DIRECT,no-resolve和GEOIP,CN,DIRECT应该是不一样的

嗯，也就是说逻辑可能是  MATCH,DIRECT这种情况是先direct再dns解析，所以没有捕获到Destination IP，只有先dns解析再direct的才能捕获到，是不是可以这样理解？

**Comment by luwah** [comment]
no-resolve is an additional option for GEOIP, IP-CIDR, or IP-CIDR6 rules. Append ,no-resolve to these rules to enable. Clash by default translates the domain names to IP addresses when encountering IP rules. Clash skips the IP rules with this option enabled when encountering packets that have an FQDN target.
可以参考wiki页面configuration最后一段。

**Comment by soncy** [comment]
> 

嗯，这个逻辑我能明白，不太清楚的是不是所有DIRECT都会走DNS，这两种规则下的数据流向是什么样的？
