### ISSUE TITLE
关于trojan grpc配置

### ISSUE THREAD

**Issue by zoeins** [Dreamacro/clash#1888]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

clash是否支持trojan grpc，如果支持怎么配置，我把h1和h2分别前置测试了下，并不能正常使用。

**Comment by qist** [comment]
clash配置
  - name: trojan-grpc
    server: xxx.com
    port: 443
    type: trojan
    password: "password"
    network: grpc
    alpn:
      - h2
    sni: xxx.com
    skip-cert-verify: false
    #udp: true
    grpc-opts:
      grpc-service-name: "trojan"

xray配置：
{
    "inbounds": [
        {
            "port": 6565,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "tag":"VLESSTROJAN",
            "settings": {
                "clients": [
                    {
                        "password": "password",
                        "email": "xxx.com_VLESS_gRPC"
                    }
                ]
            },
            "streamSettings": {
                "network": "grpc",
                "security": "none",
                "grpcSettings": {
                    "serviceName": "trojan"
                }
                }
            }
    ]
}
nginx配置：
    location /trojan {
        if ($content_type !~ "application/grpc") {
                return 404;
        }
        client_max_body_size 0;
        client_body_timeout 1071906480m;
        grpc_set_header X-Real-IP $clientRealIp;
        grpc_read_timeout 1071906480m;
        grpc_pass grpc://127.0.0.1:6565;
    }

**Comment by egg1234** [comment]
nginx配置：
grpc_set_header X-Real-IP $clientRealIp;

should be as below :
grpc_set_header X-Real-IP $remote_addr;

otherwise "nginx -t" will report syntax wrong.

**Comment by fredericky123** [comment]
> clash配置
> 
> ```
>   - name: trojan-grpc
>     server: xxx.com
>     port: 443
>     type: trojan
>     password: "password"
>     network: grpc
>     alpn:
>       - h2
>     sni: xxx.com
>     skip-cert-verify: false
>     #udp: true
>     grpc-opts:
>       grpc-service-name: "trojan"
> ```
> 
> xray配置：
> 
> ```
> {
>     "inbounds": [
>         {
>             "port": 6565,
>             "listen": "127.0.0.1",
>             "protocol": "trojan",
>             "tag":"VLESSTROJAN",
>             "settings": {
>                 "clients": [
>                     {
>                         "password": "password",
>                         "email": "xxx.com_VLESS_gRPC"
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "grpc",
>                 "security": "none",
>                 "grpcSettings": {
>                     "serviceName": "trojan"
>                 }
>                 }
>             }
>     ]
> }
> ```
> 
> nginx配置：
> 
> ```
>     location /trojan {
>         if ($content_type !~ "application/grpc") {
>                 return 404;
>         }
>         client_max_body_size 0;
>         client_body_timeout 1071906480m;
>         grpc_set_header X-Real-IP $remote_addr;  #cdn $proxy_add_x_forwarded_for
>         grpc_read_timeout 1071906480m;
>         grpc_pass grpc://127.0.0.1:6565;
>     }
> ```

我用这个配置怎么也无法正常使用，求问应该如何配置clash的trojan grpc

**Comment by qist** [comment]
走cdn 了么如果是 clash配置 添加 
```
    alpn:
      - http/1.1
      - h2
```
nginx  记得开启h2 支持
```
server {
	listen 443 ssl http2;
	server_name example.com;

	index index.html;
	root /var/www/html;

	ssl_certificate /path/to/example.cer;
	ssl_certificate_key /path/to/example.key;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
	
	client_header_timeout 52w;
        keepalive_timeout 52w;
	# 在 location 后填写 /你的 ServiceName
	location /你的 ServiceName {
		if ($content_type !~ "application/grpc") {
			return 404;
		}
		client_max_body_size 0;
		client_body_buffer_size 512k;
		grpc_set_header X-Real-IP $remote_addr;
		client_body_timeout 52w;
		grpc_read_timeout 52w;
		grpc_pass grpc://127.0.0.1:6565;
	}
}
```

**Comment by fredericky123** [comment]
走了
目前配置如下：
<img width="372" alt="image" src="https://user-images.githubusercontent.com/13982749/167104745-2cedd7f7-d820-41c5-8571-a9879dc21517.png">
https://github.com/mack-a/v2ray-agent/issues/396
用的这个脚本，ngix应该是开启了h2

**Comment by bruce531** [comment]
> 走了,依然出现问题 目前配置如下： <img alt="image" width="372" src="https://user-images.githubusercontent.com/13982749/167104745-2cedd7f7-d820-41c5-8571-a9879dc21517.png"> [mack-a/v2ray-agent#396](https://github.com/mack-a/v2ray-agent/issues/396) 用的这个脚本，ngix应该是开启了h2

直接复制了上几层那个的脚本，和你的图片一样，http/1.1这一行有没都行，套cdn可以正常上网。用的也是macka的脚本。试试更新clash最新版
