### ISSUE TITLE
clash-linux-armv7-v0.14.0.gz不能运行于华硕RT-AC68U上

### ISSUE THREAD

**Issue by JACK-THINK** [Dreamacro/clash#189]
## RT-AC68U的uname如下：
Linux RT-AC68U 2.6.36.4brcmarm #1 SMP PREEMPT Sat Feb 2 13:25:24 EST 2019 armv7l GNU/Linux

## clash运行提示如下：
![Snipaste_2019-05-19_17-11-31](https://user-images.githubusercontent.com/21015855/57980105-577d0580-7a59-11e9-8e26-ff0189abfcc4.png)

个人认为是编译的问题。如您方便，请提供支持，谢谢。

**Comment by Dreamacro** [comment]
请自行选择正确的编译版本，如果没有请自行编译

**Comment by comzyh** [comment]
根据 https://github.com/cyfdecyf/cow/issues/137 的一些信息

建议尝试尝试 ARMv5 的版本

**Comment by gzelvis** [comment]
> ## RT-AC68U的uname如下：
> Linux RT-AC68U 2.6.36.4brcmarm #1 SMP PREEMPT Sat Feb 2 13:25:24 EST 2019 armv7l GNU/Linux
> 
> ## clash运行提示如下：
> ![Snipaste_2019-05-19_17-11-31](https://user-images.githubusercontent.com/21015855/57980105-577d0580-7a59-11e9-8e26-ff0189abfcc4.png)
> 
> 个人认为是编译的问题。如您方便，请提供支持，谢谢。

想请教下，路由器上的Clash，如何做到开机自启动？另外DNS那块你是怎么配的

**Comment by JACK-THINK** [comment]
@comzyh 
谢谢，您的建议确实可行，已测试成功。

**Comment by JACK-THINK** [comment]
@gzelvis 
1. 华硕原厂固件和梅林固件可参考我的项目：[SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER)。当前还不包含本程序，但你可以参照ss和v2ray自行编写。等有时间了我会把本程序加入我的项目
2. OpenWRT可编写Procd启动脚本
