### ISSUE TITLE
[Bug] The 1.9.0 kernel cannot be used properly1.9.0内核不能正常使用

### ISSUE THREAD

**Issue by XZ1314XZ** [Dreamacro/clash#1891]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9.0

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
The same YAML configuration file, with no changes, works with any of the following versions of 1.9.0 (such as 1.80 and 1.71), but in the latest version of 1.9.0 all failed, and the test delay was not possible, but the test found that if the server address in the YAML configuration file is IP, it works
同样的yaml配置文件，无任何更改，能在1.9.0的以下任意版本（如1.80和1.71版本）正常使用，但是在最新版1.9.0全部出错，并且都无法测试延迟，但是测试发现如果yaml配置文件中的服务器地址是IP的话，可以正常使用
```

### Description

The same YAML configuration file, with no changes, works with any of the following versions of 1.9.0 (such as 1.80 and 1.71), but in the latest version of 1.9.0 all failed, and the test delay was not possible, but the test found that if the server address in the YAML configuration file is IP, it works
同样的yaml配置文件，无任何更改，能在1.9.0的以下任意版本（如1.80和1.71版本）正常使用，但是在最新版1.9.0全部出错，并且都无法测试延迟，但是测试发现如果yaml配置文件中的服务器地址是IP的话，可以正常使用

**Comment by kyleli666** [comment]
你的问题会不会是这个原因？vmess协议的YAML写法在这一版里改了，Release note里有写，就是影响面感觉有点大😂

**Comment by qiyuey** [comment]
有什么好的解决办法吗？已经回退了

**Comment by mengdie101** [comment]
{name: "***", server: ***, port: ***, type: vmess, uuid: ***, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /path, headers: {Host: www.baidu.com}}}
节点ws-opts那里按这个格式修改一下，搜索替换几秒钟

**Comment by manlge** [comment]
我这里采用的是订阅配置文件，订阅服务器没有做ws-opts适配，只能退回1.8版，要用1.9只能放弃订阅自己写配置，建议还是把兼容添加上吧。

**Comment by zhongfly** [comment]
> 我这里采用的是proxy-providers订阅配置文件，订阅服务器没有做ws-opts适配，还是使用的ws-path和ws-headers，目前只能退回1.8版，要用1.9只能放弃订阅自己写配置，建议还是把兼容添加上吧。

clash1.7.0版本就已经告知了将在2022年取消兼容，请要求服务提供商做适配

**Comment by adrianzhang** [comment]
> {name: "***", server: ***, port: ***, type: vmess, uuid: ***, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /path, headers: {Host: [www.baidu.com}}}](http://www.baidu.com%7D%7D%7D) 节点ws-opts那里按这个格式修改一下，搜索替换几秒钟

同样的故障，Linux amd版，按此格式改了也不能用，回退到1.8.0版本则故障解除。

**Comment by ITJesse** [comment]
最后一个能用的版本是 v0.19.4
