### ISSUE TITLE
url-test是否会成为特征被识别？

### ISSUE THREAD

**Issue by bruce531** [Dreamacro/clash#1896]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

每隔5分钟（或者别的间隔时间）就向多个服务器发送命令测试延迟，这样定时的行为是否特征明显，是否会被识别。另外测试的网址应该是加密的吧？不然大家都用同一个，又被看到，那可就太明显了。

**Comment by 2ndMessiah** [comment]
😹

**Comment by pfangzhi** [comment]
无知好可怕。你随意打开一个大型网站可能就连了几十上百次你所谓的这个测试地址。因为他们是公共静态服务器。
