### ISSUE TITLE
[Feature] 能否让 url-test 可以选择

### ISSUE THREAD

**Issue by RikudouPatrickstar** [Dreamacro/clash#1897]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

例如，在 url-test 中选择 节点A，优先使用 节点A；
当 节点A 不可用，则自动切换到延迟最低的节点；
如果 节点A 可用或者恢复可用，则再切换到 节点A。

**Comment by pfangzhi** [comment]
你建立两个 url-test组，然后再建立一个fallback组来自动可用切换url-test组不就行了，多看看configuration.

**Comment by RikudouPatrickstar** [comment]
> 你建立两个 url-test组，然后再建立一个fallback组来自动可用切换url-test组不就行了，多看看configuration.

我现在就是这么干的，按地区分了5组，select url-test fallback 组合使用一共15组，满满一页，其中10组是不可选的。我就是来提出能不能优化下

**Comment by RikudouPatrickstar** [comment]
我的意思就是，让 url-test 成为一种改进的 select，而不是现在这样作为一个以延迟为优先级的 fallback

**Comment by pfangzhi** [comment]
我明白你意思，你就是想用url-test测速自动选择一个最低延迟的然后使用的时候如果故障了切换下一个，原来的恢复了延迟并且低的话依然用回原来这个，url-test本来就是这个功能呀，你的问题出在测速样本上，比如我测试延迟的地址就是youtube页面，节点连接youtube最低的时候就会使用，测速时间到了测速连不上youtube时候就立马timeout了，自动变成另一个可用最低延迟转发出去数据，当然原来用的节点如果速度恢复联通了，那下个测速周期的时候发现这个节点能连了并且速度最快的话自动就切换过去呀。你需要评估的是你url-test延迟的标准是什么网站，你吧测速样本网站改成google那么节点速度就是连接到google的延迟而不是国内国际都可能最快的gstatic。

**Comment by pfangzhi** [comment]
yacd你可以 参考下，他们是按测速延迟低到高排列的，Sele选择时候很方便

**Comment by RikudouPatrickstar** [comment]
> 我明白你意思，你就是想用url-test测速自动选择一个最低延迟的然后使用的时候如果故障了切换下一个，原来的恢复了延迟并且低的话依然用回原来这个，url-test本来就是这个功能呀，你的问题出在测速样本上，比如我测试延迟的地址就是youtube页面，节点连接youtube最低的时候就会使用，测速时间到了测速连不上youtube时候就立马timeout了，自动变成另一个可用最低延迟转发出去数据，当然原来用的节点如果速度恢复联通了，那下个测速周期的时候发现这个节点能连了并且速度最快的话自动就切换过去呀。你需要评估的是你url-test延迟的标准是什么网站，你吧测速样本网站改成google那么节点速度就是连接到google的延迟而不是国内国际都可能最快的gstatic。

不不不，我的意思是可以手动指定一个，不指定的话就直接用延迟最低的（和现在的功能一样）。如果如果指定了且指定节点发生故障，就切换为延迟最低的，并不是要求真的最快，而仅仅是保证时刻可用。

**Comment by RikudouPatrickstar** [comment]
上面那张图里面，fallback 后面第一个节点是 select，第二个是 url-test

**Comment by pfangzhi** [comment]
按程序的逻辑处理优先顺序的规则只能是你图上那种方式实现。
