### ISSUE TITLE
[Feature] 加密算法能否添加rc4支持

### ISSUE THREAD

**Issue by xvkong** [Dreamacro/clash#1900]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

有些ssr服务器采用rc4算法，目前内置的rc4-md5不匹配，能否添加rc4支持，

**Comment by Rakau** [comment]
~~为什么要用一个5年前就删库的代理软件？~~

建议换机场
