### ISSUE TITLE
支付宝IPv6地址异常

### ISSUE THREAD

**Issue by xuan880** [Dreamacro/clash#191]
最近支付宝开始走IPv6地址了,发现通过clash代理,支付宝连接异常,IPv6地址只截取了最开头的16位,下面的截图可以看出来,支付宝从amdc.alipay.com这个地址获得了ipv6地址,但是clash判断的时候2400:b200:300:10::5这个地址只截取了最开头的2400,导致连接失败.
我的环境是emui9.1系统,tmux下运行,clash是最新的Dev版,使用方式是通过设置APN代理.
![Screenshot_20190523_234225_com termux](https://user-images.githubusercontent.com/2383369/58296553-be5a4000-7e06-11e9-94a8-476eaf5d2e65.jpg)
![Screenshot_20190523_234345_com guoshi httpcanary](https://user-images.githubusercontent.com/2383369/58296554-be5a4000-7e06-11e9-8625-f6dcb0d6d45b.jpg)
![Screenshot_20190523_234355_com guoshi httpcanary](https://user-images.githubusercontent.com/2383369/58296555-bef2d680-7e06-11e9-9aed-7b7e5fd031b3.jpg)

**Comment by comzyh** [comment]
我去试了下 Socks5 的方式，没复现。

你的Clash 是怎么用的?  iptables redirect ?而且用了ip6tables redirect ? 

你这个国内线路是 DIRECT 还是 ss 还是什么其他类型 ?

**Comment by xuan880** [comment]
> 我去试了下 Socks5 的方式，没复现。
> 
> 你的Clash 是怎么用的? iptables redirect ?而且用了ip6tables redirect ?
> 
> 你这个国内线路是 DIRECT 还是 ss 还是什么其他类型 ?

curl测试ipv6网站没有问题,就是支付宝有问题,我是通过设置APN代理来使用的.

**Comment by comzyh** [comment]
初步判断是支付宝写出 bug 了，CONNECT 没加方括号

正常情况下 CONNECT 的 ipv6 地址两边应该加方括号

```
$ nc 127.0.0.1 8081
CONNECT [2404:6800:4008:c06::66]:443 HTTP/1.1


HTTP/1.1 200 Connection established
```

Clash 日志

```
INFO[0322] 127.0.0.1 --> 2404:6800:4008:c06::66 match MATCH using DIRECT 
WARN[0323] Proxy[DIRECT] connect [127.0.0.1 --> 2404:6800:4008:c06::66] error: dial tcp [2404:6800:4008:c06::66]:443: connect: network is unreachable
```

异常情况:

```
$ nc 127.0.0.1 8081
CONNECT 2404:6800:4008:c06::66:443 HTTP/1.1


HTTP/1.1 200 Connection established
```

Clash 日志 

```
DEBU[0238] [DNS] resolve 2404 error: All DNS requests failed 
INFO[0238] 127.0.0.1 --> 2404 match MATCH using DIRECT  
WARN[0238] Proxy[DIRECT] connect [127.0.0.1 --> 2404] error: dial tcp: address 2404:6800:4008:c06::66:443: too many colons in address 
```

 表现和你说的一样，不过APN我不了解，暂且当成 HTTP 代理，所以不能确定就是这个原因。你有条件可以抓包看看。

**Comment by beyondkmp** [comment]
https://github.com/golang/go/issues/31024

**Comment by xuan880** [comment]
支付宝似乎修复了此问题.
