### ISSUE TITLE
[Feature] Making Country.mmdb optional

### ISSUE THREAD

**Issue by fa1se** [Dreamacro/clash#1910]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

It's basically a reopen of #399. So I know it doesn't take much to have Country.mmdb anyway, but still it doesn't make much sense to have it downloaded mandatorily even when neither GEOIP rules nor DNS feature is in use.

### Possible Solution

Here's a solution without parsing configuration file in advance:

##### Step one

We either remove the check completely, or add a new command-line flag like `-no-mmdb` to skip it explicitly.

https://github.com/Dreamacro/clash/blob/8c6d0c6757ee39354cfcdeafbf2bd25b9909e8c1/config/initial.go#L73-L76

##### Step two

When an `mmdb.Instance()` is required but the file isn't available, we either evaluate the matcher to `false` and throw an warning, or at this time we try fetching the file the way initialization does currently.

https://github.com/Dreamacro/clash/blob/8c6d0c6757ee39354cfcdeafbf2bd25b9909e8c1/dns/filters.go#L20

https://github.com/Dreamacro/clash/blob/8c6d0c6757ee39354cfcdeafbf2bd25b9909e8c1/rule/geoip.go#L29

I can implement a easy fix if any of this genuinely looks good while you don't have the time.

**Comment by uqix** [comment]
`-no-mmdb` would be a so nice option, could you reopen this issue?
