### ISSUE TITLE
[Bug]  Clash  v1.9.0特定中转模式下 无法使用

### ISSUE THREAD

**Issue by aiastia** [Dreamacro/clash#1916]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v0.19.0

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
模式1 
- { name: 'cf', type: vmess, server: 中转机ip, port: 10160, uuid: ***, alterId: 0, cipher: auto, udp: true, tls: true, servername: 开启cdn的域名, network: ws, ws-path: /, ws-headers: { Host: 开启cdn的域名 } }
模式2
 - { name: 'cf', type: vmess, server: 开启cdn的域名, port: 10160, uuid: ***, alterId: 0, cipher: auto, udp: true, tls: true, servername: 开启cdn的域名, network: ws, ws-path: /, ws-headers: { Host: 开启cdn的域名 } }
```

### Description

 节点配置cf cdn  然后通过一个中转转发到cf 域名/ip 。
链路如下（clash -中转 -cf -落地  ）
其中 clash win 0.19.5 
server 写中转ip 然后hous 等全部写 cf 域名  (模式1）
此时无法使用 提示timeout  版本降低clash win 版本 到 0.19.4 恢复正常

后尝试 自行更换Clash 的核心版本 v1.9.0 https://github.com/Dreamacro/clash/releases/download/v1.9.0/clash-windows-amd64-v1.9.0.zip
 模式一 仍然错误
模式二正常
更换 v1.8.0
https://github.com/Dreamacro/clash/releases/download/v1.8.0/clash-windows-amd64-v1.8.0.zip
 模式一 二 都正常

**Comment by Dreamacro** [comment]
read https://github.com/Dreamacro/clash/releases/tag/v1.9.0
