### ISSUE TITLE
mips_24kc适配版本

### ISSUE THREAD

**Issue by wangxin6** [Dreamacro/clash#192]
请问openwrt下mips_24kc适配releas中的哪个版本？谢谢。

**Comment by comzyh** [comment]
mips_24kc 是 32 位架构，你也没有提供其他信息
按这个顺序都试试

- mips-hardfloat
- mipsle
- mips-softfloat

**Comment by wangxin6** [comment]
我目前用的是netgear wndr4300的路由器。所以想编译一个适配的ipk

**Comment by comzyh** [comment]
那估计是 mips-softfloat

**Comment by wangxin6** [comment]
网上找了一圈没看到相关资料。

**Comment by comzyh** [comment]
啊，我说 Release 里面的 `clash-linux-mips-softfloat-v0.14.0.gz`

**Comment by wangxin6** [comment]
我知道你说的文件。

我的意思是netgear wndr4300架构是mips_24kc，无法对应releas中的版本。在网上找了一圈没看到相关资料，所以发了这个issue。

**Comment by Dreamacro** [comment]
你发 issue 我也不知道这个是什么架构的，你总不能让我买一台来试吧🌚

**Comment by wangxin6** [comment]
在我的路由器上执行

> opkg print-architecture

显示的结果是

> arch mips_24kc

**Comment by ztechie** [comment]
system type : Atheros AR9344 rev 2
machine : NETGEAR WNDR4300
processor : 0
cpu model : MIPS 74Kc V4.12
BogoMIPS : 278.93
wait instruction : yes
microsecond timers : yes
tlb_entries : 32
extra interrupt vector : yes
hardware watchpoint : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa : mips1 mips2 mips32r1 mips32r2
ASEs implemented : mips16 dsp dsp2
shadow register sets : 1
kscratch registers : 0
package : 0
core : 0
VCED exceptions : not available
VCEI exceptions : not available

**Comment by ztechie** [comment]
clash-linux-mips-softfloat-v0.14.0.gz
可以在WNDR4300上面运行.已测试

**Comment by ztechie** [comment]
可以在WNDR4300上面运行 比较吃力，运行几分钟就提示内存溢出
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x4ebcd2, 0x16)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:617 +0x60
runtime.sysMap(0x5400000, 0x400000, 0x850638)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/mem_linux.go:170 +0x108
runtime.(*linearAlloc).alloc(0x844414, 0x400000, 0x400000, 0x850638, 0x8e800)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/malloc.go:1299 +0xd8
runtime.(*mheap).sysAlloc(0x844140, 0x8000, 0x0, 0x3b2cc)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/malloc.go:539 +0x7c
runtime.(*mheap).grow(0x844140, 0x4, 0x0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/mheap.go:1232 +0x4c
runtime.(*mheap).allocSpanLocked(0x844140, 0x4, 0x850660, 0x124ddf)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/mheap.go:1150 +0x4dc
runtime.(*mheap).allocManual(0x844140, 0x4, 0x850660, 0x0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/mheap.go:1077 +0x60
runtime.stackpoolalloc(0x84e8a4, 0x53ea000)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/stack.go:179 +0x88
runtime.stackcacherefill(0x77c30004, 0x3f3420)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/stack.go:262 +0x60
runtime.stackalloc(0x800, 0x4dc3a0, 0x1000039)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/s

**Comment by wangxin6** [comment]
hardfloat可以用么？会不会好点。

**Comment by ztechie** [comment]
clash-linux-mips-softfloat-v0.14.0就是这个版本才能在4300运行啊，运行起来没几分钟就内存溢出了

**Comment by wangxin6** [comment]
溢出可能是由于GEOIP造成的。之前看见有人在3800上使用，不知道是不是又同样问题。可惜帖子找不到了，不然可以问一下。

**Comment by comzyh** [comment]
AR9344 好像没有硬件浮点

wangxin6 <notifications@github.com> 于 2019年5月31日周五 09:53写道：

**Comment by ztechie** [comment]
9410     1 root     S     790m 158%   0% /etc/clash/clash -d /etc/clash ARMV7启动成功后。内存占用过大，一会就被系统杀掉进程了

**Comment by ztechie** [comment]
Mem: 106056K used, 404884K free, 1340K shrd, 9452K buff, 34816K cached
CPU:   0% usr   0% sys   0% nic 100% idle   0% io   0% irq   0% sirq
Load average: 0.14 0.11 0.04 1/98 9704
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 9410     1 root     S     790m 158%   0% /etc/clash/clash -d /etc/clash

**Comment by wangxin6** [comment]
外接U盘做buffer，可行么？

**Comment by ztechie** [comment]
VSZ    %VSZ7
90m    158%
不知道为什么会占用这么大

**Comment by Dreamacro** [comment]
Close because of the issue resolved.

**Comment by Dreamacro** [comment]
@ztechie go 的内存占用似乎不能这么直接看。

**Comment by ztechie** [comment]
实际内存占用很低，这个是虚拟内存，应该是加载goeip的数据库，加了个sawp并没有移动到sawp
