### ISSUE TITLE
[Feature] 自定义geoip数据库来源

### ISSUE THREAD

**Issue by ben-august** [Dreamacro/clash#1921]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

*ray都可以更新geoip.dat.希望clash也支持。如果ray服务端使用geoip数据和客户端clash的geoip数据对不上的话，很容易分流出错。比如clash设置geoip cn direct，但是某个ip被识别走proxy了，而服务端设置了geoip cn block，服务端的geoip数据库把这个ip识别为cn，于是网页无法访问。希望能增加自定义更新geoip数据库来源和更新间隔。谢谢！

### Possible Solution

增加geoip数据库更新接口。

**Comment by Dreamacro** [comment]
这些工作我更推荐各类 GUI 来完成
