### ISSUE TITLE
[Bug] i can't use vmess in version 2.5.4 but in versions below that version can be used vmess I have reported to Kr328 but upstream and told to report to Dreamacro because all the protocols used are from Dreamacro and I'm a clash for android user

### ISSUE THREAD

**Issue by Bimasingkong** [Dreamacro/clash#1923]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash for android verion 2.5.4

### What OS are you seeing the problem on?

macOS, Windows, Linux, OpenBSD/FreeBSD

### Clash config

```yaml
Iam use clash for android
```

### Clash log

```shell
Not log capture
```

### Description

I can't use the vmess protocol
![150376596-0b890463-6d61-48bb-ad18-afd93edcbaf8](https://user-images.githubusercontent.com/98108857/150386691-d132715c-ba76-478d-a9a7-b1956ca91dec.jpg)
![150376594-c5b8e5bf-cdf1-4ec4-8395-de902a1ea8d7](https://user-images.githubusercontent.com/98108857/150386700-dcc393d1-5cc9-4929-9ea1-4070ee5e91f5.jpg)
![150376588-386d12f3-06ed-40dd-8feb-e3fbc229ed50](https://user-images.githubusercontent.com/98108857/150386704-f1fb0829-cc6c-41a2-981b-10e08d246979.jpg)
![150376579-13e70845-da75-48bd-9768-bd67afa77017](https://user-images.githubusercontent.com/98108857/150386707-e9ffcd92-2695-4be0-9cab-8d0f2541b2ff.jpg)

**Comment by bankroft** [comment]
the vmess api changed,it may help you: https://lancellc.gitbook.io/clash/clash-config-file/proxies/config-a-vmess-proxy

**Comment by qist** [comment]
https://github.com/Dreamacro/clash/wiki/configuration

**Comment by Bimasingkong** [comment]
I am use vmess tls mode do not work in 2.5.4
But in 2.5.3 work 
I am use this in 2.5.4 do not work but in2.5.3 is work this configuration
- name: "vmess"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    # network: ws
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: v2ray.com
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol
