### ISSUE TITLE
[Bug] 个别节点vmess h2 测速无法超时

### ISSUE THREAD

**Issue by SZbTh6** [Dreamacro/clash#1928]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9.1

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxies:
  - {name: "nodes", server: s.xxxx.xyz, port: 32021, type: vmess, uuid: xxxx, alterId: 1, cipher: auto, tls: true, network: h2, h2-opts: {path: /panelmyadmin, host: [s.xxxx.xyz]}}
```

### Description

这个节点会概率性阻塞在这，conn无法close。如果需要节点信息可以tg下bright。
```golang
	if pc.closed == nil {
		pc.closed = err
		pc.t.decConnsPerHost(pc.cacheKey)
		// Close HTTP/1 (pc.alt == nil) connection.
		// HTTP/2 closes its connection itself.
		if pc.alt == nil {
			if err != errCallerOwnsConn {
				pc.conn.Close()  //在此阻塞并且无法 step in
			}
			close(pc.closech)
		}
	}
```
`/go1.17.5/src/net/http/transport.go:2708`

**Comment by Dreamacro** [comment]
dev 应该已修复

**Comment by SZbTh6** [comment]
go get -u @dev 最新版依然存在。
