### ISSUE TITLE
[Feature] 建议添加Shadowsocks加密方式none

### ISSUE THREAD

**Issue by lg0v0** [Dreamacro/clash#1929]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

建议添加Shadowsocks加密方式none

**Comment by layou233** [comment]
那不是跟SOCKS没有区别……

**Comment by forever8938** [comment]
问题是不支持ss over wss

**Comment by jack338c** [comment]
initialize error: cipher not supported"
这个问题我也想知道，怎么可以让Shadowsocks加密方式为none
