### ISSUE TITLE
Vmess 配置

### ISSUE THREAD

**Issue by man2018** [Dreamacro/clash#193]
- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, network: ws, ws-path: /path, ws-headers: { Host: v2ray.com } } 我的配置是后面还有个tls: true参数，我配置后是不通的，这个有办法解决吗，感谢。还是我配置错了呢

**Comment by man2018** [comment]
@man2018 我是有/path headers tls的。我在v2rayN上面就是正常的

**Comment by man2018** [comment]
解决了，谢谢大佬

**Comment by lelesu** [comment]
倒是说说怎么解决的啊
