### ISSUE TITLE
[Feature] Support for geosite.dat from v2fly/domain-list-community

### ISSUE THREAD

**Issue by fa1se** [Dreamacro/clash#1932]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Obviously clash is now on the `RULE-SET` way and there already exists [solution](https://github.com/Kr328/V2rayDomains2Clash) for the conversion.
But setting up `rule-providers` requires a little too much extra configuration, so direct support for `GEOSITE` rule would make things much easier.

### Possible Solution

I've written a simple [parser](https://github.com/fa1se/dlc-parser) for `dlc.dat`, since importing the v2ray would result in a huge binary size increase.
And combined with the `trie` component I've also implemented an example [here](https://github.com/fa1se/clash/tree/feature/geosite). It simply works like this:

```yaml
rules:
  - GEOSITE,category-ads,REJECT
  - GEOSITE,geolocation-cn,DIRECT
  - MATCH,PROXY
```

This geosite component may also be used with other parts like DNS query if ever needed.

I can PR if such feature is still relevant to this project.

**Comment by Gwenhaell** [comment]
There is a [downstream branch here](https://github.com/MetaCubeX/Clash.Meta/tree/Alpha) that supports the geosite loader and the default file loader is `memconservative` for speed.
