### ISSUE TITLE
[Bug] chash内存占用抽风直接飙到4G多

### ISSUE THREAD

**Issue by joosly** [Dreamacro/clash#1938]
### Verify steps

- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.19.6

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
无
```

### Clash log

```shell
直接奔溃了，没找到日志
```

### Description

![image](https://user-images.githubusercontent.com/59339700/151357099-e44e492a-711b-4154-9ee6-8dc3ef9ec794.png)

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium

**Comment by pfangzhi** [comment]
dns服务器地址换换。我这里用tcp://223.5.5.5 很大机会会内存一直上涨到3个多g然后崩溃。

**Comment by fishg** [comment]
dns 不回包确实好像会一直积累
