### ISSUE TITLE
[Feature Request] 配置热加载

### ISSUE THREAD

**Issue by antonchen** [Dreamacro/clash#194]
写了个 [OpenWrt 插件](https://github.com/antonchen/clash-for-openwrt/tree/master)，其中订阅功能会每天定时更新订阅，这个过程中会修改配置文件。

目前担心重启时新 DNS 请求缓存被污染的记录，没有更新订阅时重启。

请问是否考虑支持配置热加载？

**Comment by Fndroid** [comment]
https://clash.gitbook.io/doc/restful-api/config#zhong-xin-jia-zai-pei-zhi-wen-jian

这个不行？

**Comment by antonchen** [comment]
原来有 API，看了下能满足需求。

**Comment by Fndroid** [comment]
https://clash.gitbook.io/doc/restful-api/config#zhong-xin-jia-zai-pei-zhi-wen-jian
