### ISSUE TITLE
[Feature] Add Support for TCP Fast Open

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#1942]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

TFO是个有点争议的feature，看了一下像v2ray是支持TFO的，但是go-shadowsocks2没有支持。

我个人认为TFO是一种`nice to have`的feature，诚然它在公网上可能会有特征明显易被识别的风险，但clash并不一定是用来翻墙的，而且这个tfo作为选项自己也可以选择关闭。另外，在一些稳定或者专有网络环境下开启TFO确实对降低TCP连接的延迟有很大的帮助。

所以开这个ISSUE的意思是想问一下作者对于TFO的看法，以及如有后续的PR是否会接受。

**Comment by gdyan2001** [comment]
+1

**Comment by zhudan** [comment]
+1支持TFO
