### ISSUE TITLE
[Feature] Is it possible to increase the default fake-ip range

### ISSUE THREAD

**Issue by ruisiji** [Dreamacro/clash#1943]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

The current default fake-ip range is `198.18.0.0/16` which contains 65536 IP addresses.

According to Wikipedia, the reserved IP range is `198.18.0.0/15` which contains 131072 IP addresses.

By changing the default fake-ip range will double the IP range capacity and will not impact on existing users.

https://en.wikipedia.org/wiki/Reserved_IP_addresses

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/configuration search `fake-ip-range`
