### ISSUE TITLE
Config yaml with ws-path

### ISSUE THREAD

**Issue by leelaylay** [Dreamacro/clash#195]
I use the configuration below and can not connect to the server while I use the same config in V2RayX successfully. I guess that the `ws_path: /23456A/` cannot be recognized successfully.
```yaml
# ws+tls+ws-path
- { name: "vmess1", type: vmess, server: XXXX.XXXX.com, port: 58312, uuid: XXXX, alterId: 16, cipher: auto, network: ws, ws-path: /23456A/ , tls: true, ws-headers: { Host: XXXX.XXXX.com }}
```

**Comment by Dreamacro** [comment]
maybe you should try `ws-path: "/23456A/"`

**Comment by leelaylay** [comment]
> maybe you should try `ws-path: "/23456A/"`

I have tried but it doesn't work.

**Comment by Dreamacro** [comment]
can you provide all your v2ray configure?

**Comment by Dreamacro** [comment]
close because of long time no response.
