### ISSUE TITLE
[Feature] Server filters 

### ISSUE THREAD

**Issue by MPTres** [Dreamacro/clash#1950]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Add proxy filter functionality to allow "filtering out".

First of all, i'd like to thank the devs for adding the "filter" property to the proxy providers. It's been very helpful.
So, here is the feature request.

Since clash uses golang's regexp engine, it does not support backreferences/lookbehinds . 
This makes imposible to create some complex  filters, like servers that must include some words, but do not include others.

An example. Let's say that i want to get all the servers that include the words  "stream", "video" , but do not include the words "japan" "australia", "prime". This is, get all the "stream|video" servers, except the servers for those countries or for prime.

A regexp for that would require backreferences or lookbehinds, which golang (and therefore clash) does not support. 

### Possible Solution

A couple of possible solutions.

The first one, would be to check the provider filter with  a regexp engine that supports backreferences, like **pcre**.
But that would require adding another dependency of packages that are not very often updated. Not ideal.

Another could be  adding a second "filter out" property (optional) in the proxy provider configuration.
Then clash could check both to determine if a server needs to be filtered.
Using the previous example, a sample config could be:

```yml
myProvider:
    type: file
    path: myprovider.yaml  
    filter: '(?i)(stream|video|)'
    filterout:  '(?i)(japan|australia|prime)'
```

 
How this would work??

In the case that there is only one of those filters set, the functionality is simple.
The app would just include the servers that match the  `filter` regexp  (like it's doing now) or those that DO NOT match the `filterout` regexp. (depending on which filter property is set)

Then, we have the special case in which both `filter` and `filterout`  are set in the configuration.
In this case,  `filter` would take precedence.  If `filter`  does not match , discard the server (as it's done now). 
If it does, then go to check  `filterout`. If it matches, discard the server. If it does not match, then keep it.

This could make possible to make more advanced filters, like the previous "include a list of words, but not others" example.
And it would be backwards compatible, not affecting current configurations. 
Making  `filterout`  optional, if it is not in the configuration or is empty, it would work exactly as it's working now.

I hope it was not very confusing.

**Comment by puttin** [comment]
filter out feels amazing for bypassing the limit of golang regex
