### ISSUE TITLE
v1.9.0去掉了VMess配置文件旧格式的兼容是基于何种考虑？

### ISSUE THREAD

**Issue by f2sky** [Dreamacro/clash#1951]
### Description

1、不了解为何要去掉对旧格式的兼容支持，没有找到相关解释和说明，求指教和解答；
Change
remove forward compatible codes in 2022 as agreed
1）migrate cache
2）**ws-headers and ws-path on vmess**
2、去掉兼容之后，新版配置文件相关格式是怎样的？服务端和客户端都该如何修改？
同样没有找到解释和说明。
3、更新是否应该考虑小白用户的使用？
我相信有很多人跟我一样并非程序员，是小白用户，使用也就买现成的机场，顶多用别人分享的一键脚本搭建一下服务，此次更新没有说明该如何修改，包括Google Play 商店也无更新说明和更新导致不可用提示。
此次Android 和 macOS 更新客户端之后，直接导致手机、电脑均无法连接外网。

求了解相关细节的朋友解答，感谢！

**Comment by caixukundashabi** [comment]
兄弟  你的配置文件格式可以发我 参考一下吗

**Comment by f2sky** [comment]
> 兄弟 你的配置文件格式可以发我 参考一下吗
@caixukundashabi 
1.9.0 版本之前可用的 VMess 配置格式：
# VMess
- name: "VMess"
  type: vmess
  server: xxx
  port: 443
  uuid: xxx
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: false
  network: ws
  ws-path: /xxx/
  # ws-headers: #这一行后面不要写东西
  # Host: v2ray.com # 填你的主机名
  # VMess-auto-IP（自选IP）

**Comment by zhongfly** [comment]
https://github.com/Dreamacro/clash/wiki/configuration

**Comment by forever8938** [comment]
那你为什么要升级新版？

**Comment by tree-white** [comment]
一开始我还以为机场挂了，确实捣腾了有一小段时间，下载回旧版本后发现是版本修改问题，装回旧版本就行了，主要是我下载新版本完全是点了自动更新。。

**Comment by csy19960309** [comment]
这是机场主和用户需要考虑的问题。核心的开发者需要向前走。

**Comment by AntiMoron** [comment]
@forever8938 软件天天弹提示更新好吧。弹的时候也没人说不兼容啊。安全上网本来就不容易弹完了还得检查半天。一个代理软件可以不玩geek了好吗，代码改那两个字段有啥用？

**Comment by akw5454521** [comment]
你给开发者钱了吗？钱不是给了机场主了？那拿了钱的机场主为什么不把本职工作给做好？

**Comment by AntiMoron** [comment]
@akw5454521 开源软件做的好坏 还不让人说了？  不搞兼容性那不就是一开始没想明白或者没有节操么？

咋的，你意淫啥是啥被？你说完 我就得突然就是机场主了 就得把忍受软件给我带来麻烦当做本职工作了？

**Comment by AntiMoron** [comment]
@akw5454521 你知道为啥前端圈angular没有react、vue火么？angular那api三天两头不兼容，隔几个月搞一个大版本。原来工作做版本升级所有人都吃了屎一样。react、vue做大版本升级，早早的某个小版本就把api标记未来会deperacated, 然后才敢下个大版本干掉。clashx升级小版本 就搞这么不兼容，美其名曰往前走？ “往前”这步做好了么？

没做好，就要被喷。你在一个开源平台，就是这样的。

**Comment by AntiMoron** [comment]
如有不服我再举一个例子。@akw5454521

swift语言出来1.0到2.x改了很多iOS圈内都用的api的名字比如随机数的方法，3.x swift又把他们改回去了. 
就算是苹果在他的生态绝对独裁，也还是尊重兼容性好吧。没做好的就是会变回去。而且后续swift升级总是有迁移文档、方法。编辑器可以一键迁移。

反观本软件，贱兮兮提示一个升级，我升了。直接不能用，我就得debug半天。孰优孰劣？

我建议后续讨论做个“理中客”，别张嘴就是意淫的论点论据。我挺反感的

**Comment by c15412** [comment]
更新还把ipv6的软件的6to4隧道地址的GEOIP识别给去掉了，连[::192.168.1.3:]都给我标记成Match了，见鬼

**Comment by heham** [comment]
原来是这样，搞了好久，v2ray上正常到了clash就不行

**Comment by forever8938** [comment]
建议发邮件训斥开发者

**Comment by AntiMoron** [comment]
@forever8938 Issue不就已经提问题了？ 开发者订阅issue本身就有邮件提醒。

你姿势太低，阴阳都没什么水平

**Comment by forever8938** [comment]
@AntiMoron 我得提醒你，这个仓库只提供二进制文件，哪来的弹出更新？

**Comment by AntiMoron** [comment]
![image](https://user-images.githubusercontent.com/6587734/154307680-bac2de29-f611-484f-b66c-96abec14762e.png)
@forever8938 这玩意儿默认安装自动勾选你弄清楚过没有？

**Comment by AntiMoron** [comment]
哦 对了 怕你说出上面“为什么要更新”类似的“为什么勾选”的蠢问题 我提前提供了这个是默认值的回答。

**Comment by AntiMoron** [comment]
我现在注意到了，已经取消勾选了

**Comment by AntiMoron** [comment]
走了，没劲。

**Comment by z-x-f** [comment]
有一说一，这个自动更新不是clash的锅

**Comment by forever8938** [comment]
这里只有二进制文件，没有GUI，要讲几遍？你装的这玩意是这里下载的吗？而且这个自动更新，更新的是配置文件，不是Clash程序。

**Comment by AntiMoron** [comment]
@z-x-f 我突然意识到这个问题，那赶紧匿了。不过不兼容问题我依然该喷还得喷

**Comment by AntiMoron** [comment]
@forever8938 GUI clash-x更新的主要就是内核版本，本次不兼容改动没有升级大版本还是要喷。

**Comment by techblack** [comment]
> @forever8938 GUI clash-x更新的主要就是内核版本，本次不兼容改动没有升级大版本还是要喷。

1. GUI的问题你去喷GUI啊，来Core这里提什么？
2. 为什么要改这个字段? 因为现在的手段越来越多,tcp/grpc/ws/wss等等，原有的字段设计已经不满足统一性，或者说已经落后了。难道一个软件，从设计之初就是完美的？后续一点不让改 ？
3. 这个项目的出现就是一个geek行为。

**Comment by chenxuuu** [comment]
怪不得用不了了，原来是配置文件格式变了
完全没有看到任何提示，搜了半天才看到这个issue，感谢提问者

**Comment by starambler** [comment]
学习了，我的也用不了。原来是这个原因

**Comment by michzhan** [comment]
今天下午折腾了一下午，终于搞定了，原来是格式有变换

**Comment by dingdang0227** [comment]
兄弟 有没有下载链接 clash安卓手机的加我 17816761576
