### ISSUE TITLE
能否添加 HBO 和 迪士尼+的分流

### ISSUE THREAD

**Issue by yuxiang26291** [Dreamacro/clash#1957]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

能否添加 HBO 和 迪士尼+的分流

**Comment by akw5454521** [comment]
能
