### ISSUE TITLE
obfs混淆参数填写

### ISSUE THREAD

**Issue by nasaboy** [Dreamacro/clash#196]
- { name: "ss1", type: ss, server: server, port: 443, cipher: AEAD_CHACHA20_POLY1305, password: "password", udp: true } 
这一行服务器里obfs的参数该如何填写？
参照下面旧版的服务参数填写，每次都是错误的，所以才来请教一下。

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/blob/master/README.md

**Comment by nasaboy** [comment]
哦
