### ISSUE TITLE
[Feature] Chrome Extenstion

### ISSUE THREAD

**Issue by modaresimr** [Dreamacro/clash#1966]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

It would be nice if there is a possibility to have clash in chrome extension. I know it is written in Go lang but is it possible to have it as a chrome extension too?

**Comment by Dreamacro** [comment]
#1975
