### ISSUE TITLE
v1.9.0 win-386报毒，请帮忙分析

### ISSUE THREAD

**Issue by 7x0** [Dreamacro/clash#1969]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9.0

### Clash config

```yaml
No config
```

### Description

URL:https://github.com/Dreamacro/clash/releases/download/v1.9.0/clash-windows-386-v1.9.0.zip

微步分析报告：https://s.threatbook.cn/report/file/95a259a63f256cdaadef651439519cbf25f7c869ef2aac5fc95f869c1a7229b5/?sign=history&env=win7_sp1_enx86_office2013

<img width="958" alt="Screen Shot 2022-02-15 at 5 14 32 PM" src="https://user-images.githubusercontent.com/45502788/154030383-21d23376-104b-47e4-8a8b-902e968ed834.png">
<img width="907" alt="Screen Shot 2022-02-15 at 5 14 24 PM" src="https://user-images.githubusercontent.com/45502788/154030412-6a32e931-0efb-4203-ac02-d45bc7adbc3d.png">

**Comment by Dabrit** [comment]
你想让我们分析啥

**Comment by LexsionLee** [comment]
那么，是什么原因导致的呢？

**Comment by JonasGao** [comment]
1.10.0 版本。v3 的版本，我也报毒了。不过 v1 的版本倒是没有报毒就比较奇怪。
![image](https://user-images.githubusercontent.com/4549584/160069540-61fa4ce6-4b06-4c9f-8111-acf218484e72.png)

暂时也懒得去分析哪里导致的报毒。担心安全的同学，建议跑在 Docker 里好了。
