### ISSUE TITLE
suggest making .yaml as default config file extension

### ISSUE THREAD

**Issue by ruisiji** [Dreamacro/clash#197]
According to wikipedia: https://en.wikipedia.org/wiki/YAML

> The official recommended filename extension for YAML files has been .yaml[8] since 2006.[9]

* https://yaml.org/faq.html

**Comment by Dreamacro** [comment]
Emmm, it's necessary. I would compatible both `.yml` and `.yaml`. but I can't remove `.yml` due to it's a breaking change.

**Comment by ruisiji** [comment]
Yeah, agree with not removing `.yml`.

I suggest to change the behavior, to search `config.yaml` first then search `config.yml`. It is very rare case that current users have both `config.yaml` and `config.yml` in same directory.

Another change would be document change, update all `.yml` to `.yaml`.

I provide feedback, @Dreamacro you make the decision.

**Comment by Dreamacro** [comment]
used `config.yaml` as default configuration in dev branch, old `.yml` would forward compatibility until 1.0.
