### ISSUE TITLE
[Feature] proxy-providers的节点应该可为空

### ISSUE THREAD

**Issue by ghost** [Dreamacro/clash#1974]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

proxy-providers中通过url获取到的节点可以为空。
在实际使用中，proxy-providers被广泛用于根据地区分组节点，例如
HK:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=你的订阅链接&list=true&udp=true&include=(?=.*(\u9999\u6E2F|HK|(?i)Hong))"
    interval: 3600
    path: ./hk.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
当无符合地区节点时，clash直接报错无法启动!

**Comment by ileeoyo** [comment]
有同样的问题

**Comment by gdyan2001** [comment]
+1

**Comment by PingZi-Wing** [comment]
我也有类似问题，希望允许存在空节点组。
[https://github.com/Fndroid/clash_for_windows_pkg/issues/3117#issue-1268211443](url)

**Comment by PingZi-Wing** [comment]
https://github.com/Dreamacro/clash/issues/2175#issuecomment-1159468812

**Comment by yeehonglee** [comment]
+1 希望provider的filter没匹配到不直接报错，有些机场可能会下线某个地区节点，造成报错

**Comment by lilyblessing** [comment]
+1，一更新部分节点缺失了直接整个配置项都不能用非常不合理，健壮度、鲁棒性
