### ISSUE TITLE
可以开发 谷歌浏览器扩展【.crx】版本的clash吗？

### ISSUE THREAD

**Issue by 1457384613gh** [Dreamacro/clash#1975]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

可以开发 谷歌浏览器扩展【.crx】版本的clash吗？
发现，有好多 VPN软件，都有 谷歌浏览器扩展【.crx】版本，并且上架了谷歌网上应用店。
以前的安卓经典游戏【割绳子】（怪物吃糖果），好像，也有大神移植成了 【.crx】扩展。

clash 可以开发成【.crx】扩展吗？可以应用于 Cloudready 和 ChromeOS Flex，还有安装谷歌内核浏览器的各种操作系统，这样似乎更加便利。

**Comment by Dreamacro** [comment]
做不到

**Comment by 1457384613gh** [comment]
> 做不到

你的意思是，clash内核比较复杂，而 【.crx】扩展比较简单，无法实现 clash内核各种高级的功能吗？还是，需要高手开发？

**Comment by humorwang** [comment]
我的理解。clash 是一个本地的vpn客户端，本地加密传数据到墙外，而你所述vpn插件都是别人在境内部署好了vpn客户端，你先通过本地网络明文将数据送到墙内别人部署好的vpn客户端加密再传输到墙外。这是完全不一样的传输方式。而chrome 本身不能做为客户端进行加解密数据包操作，所以做不到。
