### ISSUE TITLE
OpenWrt上怎样才能让clash使用另外一个用户启动运行？

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#198]
为了让OUTPUT链能够也做到redirect，搜了很多内容，仿照aria2的做法，在`/etc/passwd`中新建了用户
```
daemon:*:1:1:daemon:/var:/bin/false
ftp:*:55:55:ftp:/home/ftp:/bin/false
network:*:101:101:network:/var:/bin/false
nobody:*:65534:65534:nobody:/var:/bin/false
dnsmasq:x:453:453:dnsmasq:/var/run/dnsmasq:/bin/false
aria2:x:6800:6800:aria2:/var/run/aria2:/bin/false
clash:$1$PBImsd83$v5XnVzYn2x0S79BEtfKto.:7890:7890:clash:/var/run/clash:/bin/false
```
然后使用init.d启动
```
procd_open_instance clash
	procd_set_param command /usr/bin/clash -d /etc/clash
	procd_set_param user clash
	procd_close_instance
```

但启动后的用户依然是root，请问如何才能实现啊

**Comment by Dreamacro** [comment]
这类问题不适合在 clash issue 中提问吧，这里只解决使用 clash 中遇到的 clash 本身的问题

**Comment by tony1016** [comment]
又可以成功了，似乎要重启路由器

**Comment by DaPoHou** [comment]
> 为了让OUTPUT链能够也做到redirect，搜了很多内容，仿照aria2的做法，在`/etc/passwd`中新建了用户
> 
> ```
> daemon:*:1:1:daemon:/var:/bin/false
> ftp:*:55:55:ftp:/home/ftp:/bin/false
> network:*:101:101:network:/var:/bin/false
> nobody:*:65534:65534:nobody:/var:/bin/false
> dnsmasq:x:453:453:dnsmasq:/var/run/dnsmasq:/bin/false
> aria2:x:6800:6800:aria2:/var/run/aria2:/bin/false
> clash:$1$PBImsd83$v5XnVzYn2x0S79BEtfKto.:7890:7890:clash:/var/run/clash:/bin/false
> ```
> 
> 然后使用init.d启动
> 
> ```
> procd_open_instance clash
> 	procd_set_param command /usr/bin/clash -d /etc/clash
> 	procd_set_param user clash
> 	procd_close_instance
> ```
> 
> 但启动后的用户依然是root，请问如何才能实现啊

请问有详细教程吗？我也想这样，谢谢。
