### ISSUE TITLE
[Feature] 希望relay策略组支持udp流量转发

### ISSUE THREAD

**Issue by liofoil** [Dreamacro/clash#1982]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

希望relay策略组，也即链式代理能够支持udp转发。
目前我有两个均支持udp代理的线路，将其组成relay策略组后clash core会将所有发往core的udp连接直连处理。

我的需求是这样，将两个节点称为 node1和 node2。node1 是机场的国内中转，但是落地不太干净，被许多网站屏蔽；于是我自建了 node2，node2 国内直连效果不佳，但IP较为“干净”，所以希望通过relay策略组进行链式代理（tcp&udp）。

**Comment by liofoil** [comment]
> 都是自己的小鸡的话，直接Dokodemo Door

因为第一个节点是机场的，所以没办法

**Comment by EkkoG** [comment]
同样的需求，请求支持

**Comment by EkkoG** [comment]
Surge 也没有支持这个特性，是技术方面的原因吗

**Comment by liofoil** [comment]
> Surge 也没有支持这个特性，是技术方面的原因吗

surge支持的呀，udp也能转发，用underlying proxy就行了，在节点那儿设置

**Comment by liofoil** [comment]
刷新刷新

**Comment by reloadui-manji** [comment]
同求，很需要这个功能。

**Comment by Dukewill** [comment]
同样希望能解开udp的封印

**Comment by robustmaster** [comment]
同求。

**Comment by leic4u** [comment]
+1

**Comment by Jessense** [comment]
同求
