### ISSUE TITLE
[Bug] error: x509: cannot validate certificate for xxx.xxx.xxx.xxx because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by dmanbu** [Dreamacro/clash#1986]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.9.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxies:
  - {name: 🇭🇰 tencent-HK, server: xxx.xxx.xxx.xxx, port: 38003, type: vmess, uuid: 36e46da7-cb3c-4c24-9b4d-b3c5b9ecf78e, alterId: 0, cipher: auto, tls: true, skip-cert-verify: false, network: ws, ws-path: /xxx, ws-headers: {Host: sub-converter.xxx.com}}
```

### Clash log

```shell
节点选择 (match DomainKeyword/google) to www.google.com:80 error: dial xxx.xxx.xxx.xxx:38003 error: x509: cannot validate certificate for xxx.xxx.xxx.xxx because it doesn't contain any IP SANs"
```

### Description

我有一个v2ray+Websocket+TLS的代理，客户端到服务端中间还有个Haproxy做的TCP代理，xxx.xxx.xxx.xxx是haproxy的IP地址
客户端 clash linux版使用的是当前这个项目
客户端 clash win版使用的是 https://github.com/Fndroid/clash_for_windows_pkg 这个项目
现在linux版和win版配置都是一样的，win版使用没有问题，linux使用时，却报错了，也就是证书问题，请问那里配置有问题么？

**Comment by Dreamacro** [comment]
看更新日志

**Comment by dmanbu** [comment]
@Dreamacro 
对于 ws-headers 和 ws-path 有替代配置么？还是说，我只能降版本？

**Comment by Dreamacro** [comment]
参考 wiki 里的配置
