### ISSUE TITLE
代理节点选择问题

### ISSUE THREAD

**Issue by j0ck1e** [Dreamacro/clash#199]
我在proxy里面写了多个节点，但日志里发现程序只使用了第一个节点，第一个节点并不是最优的
clash是如何选择节点的？
目前支持负载均衡吗？

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/blob/master/README.md `Proxy Group`

**Comment by ntgeralt** [comment]
> https://github.com/Dreamacro/clash/blob/master/README.md `Proxy Group`

Did you hide it somewhere?

**Comment by Dreamacro** [comment]
@ntgeralt 🤔what?

**Comment by ntgeralt** [comment]
I'm looking for some config.yaml templates. couldn't find them on your page...

**Comment by Dreamacro** [comment]
@ntgeralt click "This is an example configuration file"

**Comment by ntgeralt** [comment]
@Dreamacro You taught me a lesson.
