### ISSUE TITLE
[Feature] 能否增加第二个 Socks5 全局端口，绕过域名规则匹配

### ISSUE THREAD

**Issue by ihotte** [Dreamacro/clash#1995]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

能否增加第二个 Socks5 全局端口，绕过域名规则匹配？

比如使用 SwitchyOmega 插件时，由于机场域名规则比较混乱可能导致部分网站无法正常访问，不知道有没有方法可以在不修改代理规则的情况下绕过规则匹配，直接发送到代理服务器。

行为比较类似 Shadowsocks 可以由客户端决定是否走代理服务器。
尤其是将 Clash 放在路由器上，内网用户无法干预代理规则，如果新增一个全局代理的 socks5 端口，配合 SwitchyOmega 插件 GFWList 自动切换模式就完美了。

**Comment by Dreamacro** [comment]
选择全局代理

**Comment by ihotte** [comment]
我再路由上安装的 clash 选择全局会影响所有用户，一般客户端都是透明代理，电脑谷歌浏览器用 SwitchyOmega 插件走 socks5。

**Comment by hronro** [comment]
我之前提出过类似的建议，并且更加通用：https://github.com/Dreamacro/clash/issues/1242

**Comment by ihotte** [comment]
> 我之前提出过类似的建议，并且更加通用：#1242

在路由上部署有全局翻墙或者 DNS 分流、奈非代理的只能再开一个其他客户端了。

**Comment by DevoStage** [comment]
手动写规则  https://lancellc.gitbook.io/clash/
当你从上往下完整看完后你就知道该怎么做了

**Comment by qist** [comment]
使用rule-providers 去动态更新规则啊。proxy-providers更新代理节点。用这两个配合就可以了。

**Comment by 04bondgoods** [comment]
如果是macos或类似系统的话，可以这么操作：
1. 增加一个本地回环地址`127.0.0.2`
`sudo ifconfig lo0 alias 127.0.0.2` 参考：https://its301.com/article/weixin_34114823/92561442
2. 指定`src-cidr,127.0.0.2`为直连
