### ISSUE TITLE
[Bug] arch linux 的 PROCESS-NAME 的判断

### ISSUE THREAD

**Issue by viqbgrg** [Dreamacro/clash#1998]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.9.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
- PROCESS-NAME,chrome,proxy
```

### Description

在 arch linux 上面 clash 获取的 PROCESS-NAME 是这个
chrome --type=utility --utility-sub-type=network.mojom.NetworkService --lang=zh-CN --service-sandbox-type=none 
导致 strings.EqualFold(cached.(string), ps.process) 与 chrome 判断的时候为false
这个能不能通过前缀来判断呢?

**Comment by Dreamacro** [comment]
@Kr328 /cc

**Comment by Kr328** [comment]
> @Kr328 /cc

chromium 的 cmdline 会使用 空格 作为分隔符 (一般的正常的进程是 '\0'

**Comment by viqbgrg** [comment]
> > @Kr328 /cc
> 
> chromium 的 cmdline 会使用 空格 作为分隔符 (一般的正常的进程是 '\0'

不光是chrome，我看了其它也是完整的命令行

**Comment by Kr328** [comment]
> > > @Kr328 /cc
> > 
> > 
> > chromium 的 cmdline 会使用 空格 作为分隔符 (一般的正常的进程是 '\0'
> 
> 不光是chrome，我看了其它也是完整的命令行

![图片](https://user-images.githubusercontent.com/39107975/156866155-1ed2317f-9d1e-48af-82d4-04f6f3f1cc92.png)
这是 Firefox 注意 `firefox` 之后的 `00`

![图片](https://user-images.githubusercontent.com/39107975/156866206-3bff1d43-1d56-4dcc-80f4-2c03185acbd9.png)
这是 Chromium 注意 `chromium` 之后的 `20`

Firefox 的实现是 Linux 下的标准实现
