### ISSUE TITLE
Restful API fetch 跨域失败

### ISSUE THREAD

**Issue by lintmx** [Dreamacro/clash#20]
Clash 版本：v0.8.1
平台： macOS 10.14

当开启 secret 后使用 fetch 请求 /configs 时需要预检请求 OPTIONS ，该请求未返回 Access-Control-Allow-Origin 头导致跨域失败。

fetch 请求
<img width="866" alt="2018-10-27 12 59 46" src="https://user-images.githubusercontent.com/10807435/47599808-77c77300-d9e8-11e8-9554-c2b2e9f2fe26.png">

fetch 代码
<img width="807" alt="2018-10-27 13 00 58" src="https://user-images.githubusercontent.com/10807435/47599810-77c77300-d9e8-11e8-821e-01d2bb6f85b7.png">

但是使用 xhr 请求却成功返回了相应的跨域头
<img width="869" alt="2018-10-27 13 00 17" src="https://user-images.githubusercontent.com/10807435/47599809-77c77300-d9e8-11e8-9f51-e0024bb56b40.png">
xhr 代码
<img width="509" alt="2018-10-27 13 01 19" src="https://user-images.githubusercontent.com/10807435/47599811-78600980-d9e8-11e8-9736-6823b6bcb8e4.png">

**Comment by lintmx** [comment]
fetch 请求测试代码

```javascript
let url = "http://localhost:9090/configs"
let headers = new Headers({
    "Authentication": "Bearer 123"
})
let requestInit = {
    method: 'GET',
    headers: headers,
    mode: 'cors'
}
let configRequest = new Request(url, requestInit)

fetch(configRequest).then(response => {
    if (response.ok) {
        return response.json()
    } else {
        throw new Error("Get Clash Config Error.");
    }
}).then(json => {
    console.log(json)
}).catch(error => {
    console.log(error)
})
```

**Comment by Dreamacro** [comment]
`Authentication` ==> `Authorization`

```js
const url = "http://localhost:9090/configs"
const param = {
    method: 'GET',
    headers: {
        "Authorization": "Bearer 123"
    },
    mode: 'cors'
}

fetch(url, param)
    .then(resp => resp.json())
    .then(json => console.log(json))
    .catch(error => console.error(error))
```

**Comment by lintmx** [comment]
感谢，是我疏忽了。
