### ISSUE TITLE
MacBook 14 M1 Pro clashxpro the icon in the status bar is not displayed, and the process has been started

### ISSUE THREAD

**Issue by along-KAL** [Dreamacro/clash#2014]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [ ]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [ ]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [ ]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clashxpro

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
default config
```

### Description

MacBook 14 M1 Pro clashxpro the icon in the status bar is not displayed, and the process has been started

**Comment by FoxDaxian** [comment]
same issues. Are there any result can resolve this problem?
