### ISSUE TITLE
[Bug] 可以实现在系统代理下，为某个应用程序设置不走代理的白名单吗？

### ISSUE THREAD

**Issue by fredericky123** [Dreamacro/clash#2015]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

开启系统代理后，outlook for mac os 最新版会无法及时收发邮件，如何避免这个应用走代理

**Comment by fredericky123** [comment]
我在规则里设置了这个，不过好像没啥用
  - PROCESS-NAME,Microsoft Outlook,DIRECT

**Comment by fredericky123** [comment]
outlook 的进程如下，我应该如何为其设置不走代理的白名单，感谢大佬们指点
![image](https://user-images.githubusercontent.com/13982749/157183457-b86c8092-9f48-4633-bec9-4b164416ef9f.png)

**Comment by fredericky123** [comment]
提供系统代理下，outlook mac不能正常使用的提示细节
![image](https://user-images.githubusercontent.com/13982749/157186719-e5f623aa-e171-4a86-843e-3a3ed7258d75.png)

**Comment by huiyuerandy** [comment]
我也遇到同样的问题 不知道怎么解决  
请问最后你解决了吗？

**Comment by Wrandz** [comment]
它这个似乎软件那一方认为的，等于你direct，但是软件还是认为走了代理。试试cfw里面的PAC呢？

**Comment by fredericky123** [comment]
> 我也遇到同样的问题 不知道怎么解决 请问最后你解决了吗？

并没有解决

**Comment by liuyu-f** [comment]
尝试使用地址规则而非针对app的规则呗。
`- DOMAIN-KEYWORD,outlook,Domestic`
