### ISSUE TITLE
MerlinClash 中如何对指定的IP地址（如Xbox/PS）设定游戏模式？

### ISSUE THREAD

**Issue by chunguangfu** [Dreamacro/clash#2018]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

MerlinClash 中如何在路由器端对指定的IP地址（如Xbox/PS）设定游戏模式？

**Comment by liofoil** [comment]
建议你去merlinclash的群组去问，这里是clash内核的项目
