### ISSUE TITLE
Feature request: Add a config option to not log timestamps

### ISSUE THREAD

**Issue by BirkhoffLee** [Dreamacro/clash#202]
This will be quite useful when output is redirected to logging system that already adds timestamps.

```
Jun 13 13:41:39 OpenWrt clash[20663]: time="2019-06-13T13:41:39Z" level=info msg="10.0.1.7 --> s3.amazonaws.com match MATCH using rixCloud"
```

I believe this is the way to go:
```
log.SetFormatter(&log.TextFormatter{
    DisableTimestamp: true
})
```
at https://github.com/Dreamacro/clash/blob/dev/log/log.go#L18

**Comment by darren** [comment]
why it was closed? 
Is there any option to disable the timestamp?
