### ISSUE TITLE
[Feature]  支持隐藏节点，能实现GRPC的负载均衡

### ISSUE THREAD

**Issue by himanhimao** [Dreamacro/clash#2020]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

如果支持隐藏节点配置的话，可以借助proxy_group的loadbanlace实现grpc的负载均衡， 如果暴露了节点，用户会手动选择，最后会导致不平衡 所以希望支持隐藏节点功能

**Comment by fakeboboliu** [comment]
https://github.com/Dreamacro/clash/blob/master/hub/route/proxies.go

建议自己动手

**Comment by nobody-99** [comment]
附议
