### ISSUE TITLE
[Feature] Could you please update an version for Android/iOS platform? 

### ISSUE THREAD

**Issue by RoyHANABI** [Dreamacro/clash#2030]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Mobile phone user needs your great support...

**Comment by U201413497** [comment]
Android:https://github.com/Kr328/ClashForAndroid/releases
IOS:https://apps.apple.com/us/app/stash-rule-based-proxy/id1596063349
     or
      https://apps.apple.com/us/app/choc/id1582542227

**Comment by RoyHANABI** [comment]
Thanks a lot!

**Comment by RoyHANABI** [comment]
Thanks a lot!
