### ISSUE TITLE
Request Redistribution for clash-premium

### ISSUE THREAD

**Issue by CamberLoid** [Dreamacro/clash#2032]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hello, this is Camber from Anthon Open Source Community(AOSC). I'm considering about packaging and redistributing the close-source clash-premium via AOSC OS package repository.

I have noticed the issue #1033 . As DDoSolitary pointed, clash-premium seems not have any license or EULA. Therefore I'm hereby asking for permission to package and redistribute the clash-premium binaries.

If you agree, I will:
- begin the packaging process of clash-premium, which will only use unmodified binaries from GitHub Release. Package script will be publicly available on [AOSC-Dev/aosc-os-abbs](https://github.com/AOSC-Dev/aosc-os-abbs) and my personal fork [CamberLoid/aosc-os-abbs](https://github.com/CamberLoid/aosc-os-abbs);
- upload the package to AOSC OS package repository, which is publicly available;
- not make profit from the package we provide, as AOSC is a non-profit community.

It would be nice of you if you can provide binaries for these additional architectures:
- RISC-V 64-bit `GOARCH=riscv64`
- PowerPC 64-bit Little Endian `GOARCH=ppc64le`

Much appreciated for reviewing my request.

**Comment by Dreamacro** [comment]
Redistribution of binary is welcome.

For RISC-V 64-bit and PowerPC 64-bit Little Endian, will anyone really use clash on them? If they do, I can add these two options

BTW: I recently made an s3 bucket with historical versions using Cloudflare worker and Storj https://release.dreamacro.workers.dev/ (No SLA Guarantee)

**Comment by CamberLoid** [comment]
> Redistribution of binary is welcome.

Thanks for your response. I will begin packaging process immediately.

> For RISC-V 64-bit and PowerPC 64-bit Little Endian, will anyone really use clash on them? If they do, I can add these two options

We have minor users using these to architecture. So we would appreciate it if you can add these two options.

Closing the issue now.

**Comment by CamberLoid** [comment]
Hi and sorry to bother again.
Since our distribution supports RISC-V 64-bit and POWER and we expect to have users for both ports, would it be possible to provide binaries for the aforementioned architectures? We would appreciate it for hearing your response.

**Comment by KexyBiscuit** [comment]
Golang 1.19 adds support for linux/loongarch64, please consider adding prebuilt binaries for it, thanks! @Dreamacro

**Comment by Dreamacro** [comment]
@KexyBiscuit Are you using the loogarch64 CPU? I'm not sure if anyone is actually using clash with this architecture. 🙊

**Comment by yqt** [comment]
Upvote for RISC-V 64-bit binary of premium version!
I get a pretty nice RISC-V SBC with 2x gigabit ethernet from StarFive and try to max out the power of it as a Linux gateway :)

**Comment by Dreamacro** [comment]
@yqt premium latest added riscv64,have a try

**Comment by yqt** [comment]
> @yqt premium latest added riscv64,have a try
wow, thank you!
