### ISSUE TITLE
[Bug] This program can only be run on AMD64 processors with v3 microarchitecture support. 

### ISSUE THREAD

**Issue by tangli159** [Dreamacro/clash#2035]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

docker clash-premium latest&2022.03.19

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
配置文件没有修改过，使用docker 2021.12.07 镜像一切正常。
```

### Clash log

```shell
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
```

### Description

![image](https://user-images.githubusercontent.com/50565072/159143474-f0bec8cc-8a94-4f3f-a9a9-a505dcaead28.png)
使用最新的两个镜像出现上述日志报错，使用2021.12.07镜像没问题。查看了premium更新日志发现有提到v3什么的，但是不太懂这个。我是在x86的nas上运行的docker，请问还能用新版本的镜像么？不能支持的话我就老老实实坚持旧版啦~望回复，谢谢

**Comment by luwah** [comment]
建议看看1.10.0的更新日志
