### ISSUE TITLE
[Bug] This program can only be run on AMD64 processors with v3 microarchitecture support.

### ISSUE THREAD

**Issue by haha209** [Dreamacro/clash#2036]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.10.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
无
```

### Clash log

```shell
> docker logs clash 
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
This program can only be run on AMD64 processors with v3 microarchitecture support.
```

### Description

使用1.10.0的docker镜像就报错，无法启动，退回1.9.0镜像就没问题，正常使用
看更新日志里有add darwin-amd64-v3 linux-amd64-v3 freebsd-amd64-v3 and windows-amd64-v3 for modern CPU. 以后就不支持旧的cpu了？

**Comment by weaving118** [comment]
问题+1，请求出一个v1版本的tag把，很多都是虚拟机，软路由，NAS上跑容器的

**Comment by weaving118** [comment]
补充下，用到是这个版本的容器： dreamacro/clash-premium:2022.03.19

**Comment by LB-DotFish** [comment]
昨天docker自动升级后，就不能用了

**Comment by Dreamacro** [comment]
`dreamacro/clash-premium:latest`

`dreamacro/clash:dev`

现在使用的是 GOAMD64 v1

**Comment by LB-DotFish** [comment]
> `dreamacro/clash-premium:latest`
> 
> `dreamacro/clash:dev`
> 
> 现在使用的是 GOAMD64 v1

@Dreamacro 请问clash以后的版本是不是都不支持x86的处理器了吗？clash-premium这个镜像能解决现在的问题？我按clash的方式做了配置，但好像没起作用，这个镜像也没用文档，请问要怎么配置呢？

**Comment by 1kchen** [comment]
但似乎最新的也是一样。dreamacro/clash-premium:2022.03.21

**Comment by 1kchen** [comment]
> 

但似乎最新的也是一样。dreamacro/clash-premium:2022.03.21

**Comment by 1kchen** [comment]
> `dreamacro/clash-premium:latest`
> 
> `dreamacro/clash:dev`
> 
> 现在使用的是 GOAMD64 v1

但似乎最新的也是一样。dreamacro/clash-premium:2022.03.21
