### ISSUE TITLE
[Bug] Rule Provider规则匹配错误

### ISSUE THREAD

**Issue by Y32Gcnte8z** [Dreamacro/clash#2037]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Prmeium 2022.03.19

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 18000

rules:
  - GEOIP,LAN,DIRECT,no-resolve
  - RULE-SET,reject,REJECT 
  - MATCH,PROXY
```

### Clash log

```shell
2022-03-20 12:56:31[info] [TCP] 198.18.0.1:50134 --> mail.google.com:443 match RuleSet(reject) using REJECT
2022-03-20 12:56:31[info] [TCP] 198.18.0.1:50136 --> mail.google.com:443 match RuleSet(reject) using REJECT
2022-03-20 12:56:31[info] [TCP] 198.18.0.1:50138 --> mail.google.com:443 match RuleSet(reject) using REJECT
2022-03-20 12:56:31[info] [TCP] 198.18.0.1:50140 --> mail.google.com:443 match RuleSet(reject) using REJECT
2022-03-20 12:56:31[info] [TCP] 198.18.0.1:50142 --> mail.google.com:443 match RuleSet(reject) using REJECT
```

### Description

我所使用的rule set规则来自于这个[链接](https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt)，这个规则中并没有包含mail.google.com，然而日志却显示mail.google.com匹配到了这个rule set，以至于出现了意料外的行为。在一模一样的配置文件下，之前的版本（Premium 2022.01.27及之前）完全正常。

**Comment by Dreamacro** [comment]
https://release.dreamacro.workers.dev/ 试试 latest 里的

**Comment by Y32Gcnte8z** [comment]
> https://release.dreamacro.workers.dev/ 试试 latest 里的

这一版ok了
