### ISSUE TITLE
process path的格式是什么

### ISSUE THREAD

**Issue by fredericky123** [Dreamacro/clash#2038]
感谢各位贡献者
看到wiki还没更新，不知该如何设置
- PROCESS-PATH,Applications/Microsoft Outlook.app/Contents/MacOS/Microsoft Outlook,DIRECT
目前这样设置是错的

**Comment by j2yych** [comment]
哈喽 请问下是在rules下配置吗.我尝试了无效

**Comment by fredericky123** [comment]
> 哈喽 请问下是在rules下配置吗.我尝试了无效

我发现我配置完了也没效果

**Comment by gonejack** [comment]
瞄了眼代码，要用绝对路径吧

**Comment by fredericky123** [comment]
> * PROCESS-PATH,Applications/Microsoft Outlook.app/Contents/MacOS/Microsoft Outlook,DIRECT

比如怎么给outlook设置例外呢？
这个就是软件安装的位置

**Comment by gonejack** [comment]
我看代码猜的：

`PROCESS-PATH,Applications/Microsoft Outlook.app/Contents/MacOS/Microsoft Outlook,DIRECT` 这里 加个 `/` 在 `Applications` 前面

**Comment by fredericky123** [comment]
> 我看代码猜的：
> 
> `PROCESS-PATH,Applications/Microsoft Outlook.app/Contents/MacOS/Microsoft Outlook,DIRECT` 这里 加个 `/` 在 `Applications` 前面

我加了 不过依然是无效的

**Comment by fredericky123** [comment]
难道因为一个软件运行的同时还有其他进程的存在？

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/159437466-1ded2a81-c566-40bd-bc43-83985c217880.png)

**Comment by gonejack** [comment]
搞错了，`Applications`不在根目录，还得加上 `/System`，查路径可以在终端这样敲

```
$ ps aux | grep -i mail
xxxx  1629   0.3  1.1 410290160 176736   ??  S     9:37AM   1:54.17 /System/Applications/Mail.app/Contents/MacOS/Mail
```

**Comment by Dreamacro** [comment]
为什么不用 PROCESS-NAME 呢，就用活动管理器里的名字就行了

**Comment by fredericky123** [comment]
> ps aux | grep -i mail

我用了活动监视器的三个名字，好像依然是无效的，真是奇怪了

**Comment by gonejack** [comment]
Outlook 是兼容 Clash 的 socks5 接口的，之前一直在用没毛病，是不是其他地方错了

**Comment by fredericky123** [comment]
> Outlook 是兼容 Clash 的 socks5 接口的，之前一直在用没毛病，是不是其他地方错了

用旧版的outlook一点都没问题，用现在这个改版后的新outlook就一直会提示socks接口导致收发邮件不及时

**Comment by 04bondgoods** [comment]
> 为什么不用 PROCESS-NAME 呢，就用活动管理器里的名字就行了

比如同时开两个相同的进程，但需要分别使用不同的POLICY，这时PROCESS-NAME就无法胜任。

**Comment by huiyuerandy** [comment]
> 为什么不用 PROCESS-NAME 呢，就用活动管理器里的名字就行了

我吧infuse用process-name  还是没用不知道为啥

**Comment by huiyuerandy** [comment]
> 前一直在用没毛病，是不是其他地方错了

我想把infuse 不走代理 也搞不定。。。头疼死了
