### ISSUE TITLE
为什么用dig命令查询域名，在日志里没有记录？

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#204]
很奇怪，用dig命令没有日志，用curl直接拉网站，就有dns日志

**Comment by tony1016** [comment]
很奇怪，用dig命令没有日志，用curl直接拉网站，就有dns日志

**Comment by Dreamacro** [comment]
因为打日志的地方不在 dns server

**Comment by tony1016** [comment]
> 因为打日志的地方不在 dns server

不太明白，你是说在SystemOut里面吗

**Comment by Dreamacro** [comment]
dig 没有实际发出一个经过 clash 代理层的请求，目前的 dns 解析 debug 日志只在代理层有，dig 直接经过 dns server 之后返回，所以现在没有日志。

**Comment by comzyh** [comment]
打开 debug 模式也没有吗

tony1016 <notifications@github.com> 于 2019年6月15日周六 15:19写道：

**Comment by tony1016** [comment]
是的，没有

Comzyh <notifications@github.com> 于 2019年6月21日周五 上午9:08写道：
