### ISSUE TITLE
wsl通过clash进行代理，但是端口拒绝访问

### ISSUE THREAD

**Issue by leezanla** [Dreamacro/clash#2044]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

![image](https://user-images.githubusercontent.com/30462256/160073299-725301b2-6232-490d-ab81-71b2c2c4a9a6.png)

**Comment by comzyh** [comment]
感觉首先应该检查 43.1 端口开了没。
然后看看
```
# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: false
```
