### ISSUE TITLE
[Feature] 让providers可以通过代理来更新

### ISSUE THREAD

**Issue by Zhou-Account-Remember** [Dreamacro/clash#2046]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我现在使用的providers的URL需要使用代理来访问。目前Clash Core只能通过直连来更新providers。为什么profiles可以通过代理来更新，providers就不能？

**Comment by fakeboboliu** [comment]
> 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题

Clash 不存在 Profile 的概念，Profile 由外部程序控制

**Comment by Zhou-Account-Remember** [comment]
> Clash 不存在 Profile 的概念，Profile 由外部程序控制

就是说profiles是由外部程序来更新，providers是由Clash Core来更新。
原来如此。不过应该也可以做到让更新providers的流量通过代理吧？
