### ISSUE TITLE
[Bug] 使用 Clash 连续多次跑满速的网速测试，100%崩溃

### ISSUE THREAD

**Issue by vibbow** [Dreamacro/clash#2048]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2022.03.21 linux amd64 with go1.18 Mon 21 Mar 2022 01:54:21 PM UTC

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
mode: Rule
log-level: info
ipv6: false
rules:
- MATCH,DIRECT
```

### Clash log

```shell
panic: runtime error: slice bounds out of range [:8192] with capacity 4096

goroutine 599 [running]:
bufio.(*Reader).ReadSlice(0xc00051c5a0, 0x0?)
        bufio/bufio.go:346 +0x22d
bufio.(*Reader).ReadLine(0xc00051c5a0)
        bufio/bufio.go:400 +0x27
net/textproto.(*Reader).readLineSlice(0xc000229230)
        net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
        net/textproto/reader.go:38
net/http.readRequest(0xc0001af170?)
        net/http/request.go:1029 +0x79
github.com/Dreamacro/clash/listener/http.HandleConn({0xd185a8, 0xc0002612c8}, 0x7fac3e6942d8?, 0xc000127980)
        github.com/Dreamacro/clash/listener/http/proxy.go:32 +0x308
created by github.com/Dreamacro/clash/listener/http.NewWithAuthenticate.func1
        github.com/Dreamacro/clash/listener/http/server.go:60 +0xd8
```

### Description

局域网有三台电脑(虚拟机)，分别是：
A - 浏览器客户端
B - 运行 Clash 的系统
C - 托管 LibreSpeed 的测速系统

在 A电脑 上设置 HTTP Proxy 为 B电脑 上的 Clash。
在 A电脑 上访问 C电脑 的 Librespeed，进行网速测试

当一轮测速完成后，立刻再进行一轮测速。
每次进行到第三轮的Upload测试时，Clash 100%崩溃。

该崩溃现象仅可在 OpenClash @ OpenWrt 及 Clash Premiun @ Ubuntu 20.04 上100%复现。
Clash for Windows @ Windows 10 上无法复现。

**Comment by techblack** [comment]
> 经过对比测试，该崩溃现象从 v1.6.5 引入
> 
> 之前的版本均不会崩溃，从v1.6.5 开始100%崩溃

使用1.10.0呢？

**Comment by vibbow** [comment]
> > 经过对比测试，该崩溃现象从 v1.6.5 引入
> > 之前的版本均不会崩溃，从v1.6.5 开始100%崩溃
> 
> 使用1.10.0呢？

也会崩溃的

**Comment by result-bit** [comment]
2022.1.27 这个版本没问题

**Comment by hronro** [comment]
not stale

**Comment by BirkhoffLee** [comment]
@vibbow 最新版 Clash Premium 是否还可复现？

**Comment by vibbow** [comment]
现在无法复现了
