### ISSUE TITLE
[Feature] win11 适配

### ISSUE THREAD

**Issue by v1nw1n** [Dreamacro/clash#2049]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

无法在win11上运行

**Comment by xianshenglu** [comment]
我也遇到了，终端显示
```
time="2022-05-02T12:57:06+08:00" level=info msg="Can't find MMDB, start download"
```

**Comment by jacklu2016** [comment]
怎么解决>？
