### ISSUE TITLE
配置多个Vmess节点提示 yaml: line 140: did not find expected key

### ISSUE THREAD

**Issue by Orocker** [Dreamacro/clash#2051]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

配置文件如下，我有多个v2ray节点，除了server地址不一样，其他选项都是一样的，修改之后提示 `yaml: line 140: did not find expected key`，是不是相同的UUID会被视为一个节点，和server无关？
`
  - name: "v2ray"
    type: vmess
    server: 4.xx.com
    port: 888
    uuid: uuid
    alterId: 3
    cipher: aes-128-gcm

  - name: "v2ray"
    type: vmess
    server: 5.xx.com
    port: 888
    uuid: uuid
    alterId: 3
    cipher: aes-128-gcm
`

**Comment by qist** [comment]
```  
# vmess
  # cipher support auto/aes-128-gcm/chacha20-poly1305/none
  - name: "vmess"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    # network: ws
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: v2ray.com
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol
```
name 你别写一样得名字。

**Comment by Orocker** [comment]
`
  - name: "v2ray"
    type: vmess
    server: 4.xx.com
    port: 888
    uuid: uuid
    alterId: 3
    cipher: aes-128-gcm

  - name: "xx"
    type: vmess
    server: 5.xx.com
    port: 888
    uuid: uuid
    alterId: 3
    cipher: aes-128-gcm
`

试了一下，第一个的name必须是v2ray, 后面的name可以自定
