### ISSUE TITLE
RESTful web API 配置了 但进不去 无法使用编辑外部控制设置

### ISSUE THREAD

**Issue by Cost11** [Dreamacro/clash#2057]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10.0

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
省略节点配置和规则
```

### Description

![image](https://user-images.githubusercontent.com/37539782/161499576-a392b5c8-0ae3-4939-9b9f-68358f9bd216.png)
之前老版本还试过可以用 最近想用却不行了 不知道怎么回事
是不是因为没配置external-ui: folder，但我始终没看明白这个是怎么配置的，我查阅资料说后面要加静态页面的（如clash-dashboard）相对路径或绝对路径，不明白这项external-ui: folder怎么配置，yaml中相对路径（跟配置文件一个文件夹）如何表达
现在的情况就是进到截图的页面进不去了 不知道该怎么搞了，环境是本机，Windows本机上

**Comment by dHvpkntUJa** [comment]
https://zhuanlan.zhihu.com/p/414533145

用别人提供的现成网站，不需要设置external-ui

**Comment by Cost11** [comment]
> https://zhuanlan.zhihu.com/p/414533145
> 
> 用别人提供的网站，不需要设置external-ui

你的意思是 设置没问题 是浏览器的问题？

**Comment by dHvpkntUJa** [comment]
> > https://zhuanlan.zhihu.com/p/414533145
> > 用别人提供的网站，不需要设置external-ui
> 
> 你的意思是 设置没问题 是浏览器的问题？

看浏览器控制台

**Comment by dHvpkntUJa** [comment]
> > > > https://zhuanlan.zhihu.com/p/414533145
> > > > 用别人提供的网站，不需要设置external-ui
> > > 
> > > 
> > > 你的意思是 设置没问题 是浏览器的问题？
> > 
> > 
> > 看浏览器控制台
> 
> 怎么看？反正按照你的介绍 问题已经解决了
> 
> ![image](https://user-images.githubusercontent.com/37539782/161750886-7c10384c-39b5-41a4-a717-8c26de82b99e.png) 又有个新问题 这两个ipv6的意义或者说区别在哪？只开上一个 不开dns那个能直连的时候用吗？还是只能两者同开或者同关？ 我想实现#640这个问题的第一种情况在 Fake IP 模式下应该可以支持直连访问 ipv6 资源和 ipv6 的节点 但是目前不能理解这两个选项的含义 或者说配置方式

第一个是否启用ipv6支持，第二个是否接收AAAA记录，举个例子，用ipv6 pt第一个true，第二个false。

**Comment by Cost11** [comment]
> 



> > > > > https://zhuanlan.zhihu.com/p/414533145
> > > > > 用别人提供的网站，不需要设置external-ui
> > > > 
> > > > 
> > > > 你的意思是 设置没问题 是浏览器的问题？
> > > 
> > > 
> > > 看浏览器控制台
> > 
> > 
> > 怎么看？反正按照你的介绍 问题已经解决了
> > ![image](https://user-images.githubusercontent.com/37539782/161750886-7c10384c-39b5-41a4-a717-8c26de82b99e.png) 又有个新问题 这两个ipv6的意义或者说区别在哪？只开上一个 不开dns那个能直连的时候用吗？还是只能两者同开或者同关？ 我想实现#640这个问题的第一种情况在 Fake IP 模式下应该可以支持直连访问 ipv6 资源和 ipv6 的节点 但是目前不能理解这两个选项的含义 或者说配置方式
> 
> 第一个是否启用ipv6支持，第二个是否接收AAAA记录，举个例子，用ipv6 pt第一个true，第二个false。

还是没太理解 第一个true是意味着能用ipv6访问吗？接收AAAA记录是什么行为？AAAA记录不是网址解析ipv6时的一种类型吗？就是AAAA记录应该对应一个ipv6地址

**Comment by dHvpkntUJa** [comment]
https://zh.wikipedia.org/wiki/DNS%E8%AE%B0%E5%BD%95%E7%B1%BB%E5%9E%8B%E5%88%97%E8%A1%A8

现在很多DNS都是双栈的，而且不少代理不支持ipv6，可能会变成直连。

**Comment by Cost11** [comment]
> 



> https://zh.wikipedia.org/wiki/DNS%E8%AE%B0%E5%BD%95%E7%B1%BB%E5%9E%8B%E5%88%97%E8%A1%A8
> 
> 现在很多DNS都是双栈的，而且不少代理不支持ipv6，可能会变成直连。

我的机器是有ipv6地址的 是不是意味的支持ipv6  这似乎要看供应商  那如果我的机器支持ipv6 是不是也不一定要第二个是true 因为很多DNS是双栈  是吗？？？

**Comment by dHvpkntUJa** [comment]
> > 
> 
> > https://zh.wikipedia.org/wiki/DNS%E8%AE%B0%E5%BD%95%E7%B1%BB%E5%9E%8B%E5%88%97%E8%A1%A8
> > 现在很多DNS都是双栈的，而且不少代理不支持ipv6，可能会变成直连。
> 
> 我的机器是有ipv6地址的 是不是意味的支持ipv6 这似乎要看供应商 那如果我的机器支持ipv6 是不是也不一定要第二个是true 因为很多DNS是双栈 是吗？？？

https://test-ipv6.com/index.html.zh_CN
从你的电脑到公网的任意环节不支持或者屏蔽ipv6，都可能导致ipv6不能用。
第二个主要是防止你的ipv4 dns解析到ipv6上去，相比ipv4+cdn，ipv6的优点是公网ip更易获得，没有这个需求不需要ipv6.

**Comment by Cost11** [comment]
> > > 
> > 
> > 
> > > https://zh.wikipedia.org/wiki/DNS%E8%AE%B0%E5%BD%95%E7%B1%BB%E5%9E%8B%E5%88%97%E8%A1%A8
> > > 现在很多DNS都是双栈的，而且不少代理不支持ipv6，可能会变成直连。
> > 
> > 
> > 我的机器是有ipv6地址的 是不是意味的支持ipv6 这似乎要看供应商 那如果我的机器支持ipv6 是不是也不一定要第二个是true 因为很多DNS是双栈 是吗？？？
> 
> https://test-ipv6.com/index.html.zh_CN 从你的电脑到公网的任意环节不支持或者屏蔽ipv6，都可能导致ipv6不能用。 第二个主要是防止你的ipv4 dns解析到ipv6上去，相比ipv4+cdn，ipv6的优点是公网ip更易获得，没有这个需求不需要ipv6.

这个我昨天就测了  是通的
你的第二点是什么意思 没明白 
是相比之下 ipv4 dns解析到ipv6上更容易 所以？？？

**Comment by dHvpkntUJa** [comment]
> > > > 
> > > 
> > > 
> > > > https://zh.wikipedia.org/wiki/DNS%E8%AE%B0%E5%BD%95%E7%B1%BB%E5%9E%8B%E5%88%97%E8%A1%A8
> > > > 现在很多DNS都是双栈的，而且不少代理不支持ipv6，可能会变成直连。
> > > 
> > > 
> > > 我的机器是有ipv6地址的 是不是意味的支持ipv6 这似乎要看供应商 那如果我的机器支持ipv6 是不是也不一定要第二个是true 因为很多DNS是双栈 是吗？？？
> > 
> > 
> > https://test-ipv6.com/index.html.zh_CN 从你的电脑到公网的任意环节不支持或者屏蔽ipv6，都可能导致ipv6不能用。 第二个主要是防止你的ipv4 dns解析到ipv6上去，相比ipv4+cdn，ipv6的优点是公网ip更易获得，没有这个需求不需要ipv6.
> 
> 这个我昨天就测了 是通的 你的第二点是什么意思 没明白 是相比之下 ipv4 dns解析到ipv6上更容易 所以？？？

网络有时会很卡

**Comment by Cost11** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > https://zh.wikipedia.org/wiki/DNS%E8%AE%B0%E5%BD%95%E7%B1%BB%E5%9E%8B%E5%88%97%E8%A1%A8
> > > > > 现在很多DNS都是双栈的，而且不少代理不支持ipv6，可能会变成直连。
> > > > 
> > > > 
> > > > 我的机器是有ipv6地址的 是不是意味的支持ipv6 这似乎要看供应商 那如果我的机器支持ipv6 是不是也不一定要第二个是true 因为很多DNS是双栈 是吗？？？
> > > 
> > > 
> > > https://test-ipv6.com/index.html.zh_CN 从你的电脑到公网的任意环节不支持或者屏蔽ipv6，都可能导致ipv6不能用。 第二个主要是防止你的ipv4 dns解析到ipv6上去，相比ipv4+cdn，ipv6的优点是公网ip更易获得，没有这个需求不需要ipv6.
> > 
> > 
> > 这个我昨天就测了 是通的 你的第二点是什么意思 没明白 是相比之下 ipv4 dns解析到ipv6上更容易 所以？？？
> 
> 网络有时会很卡

那我应该怎么配置 都是默认false吗  ？还是第一个可以true

**Comment by dHvpkntUJa** [comment]
![image](https://user-images.githubusercontent.com/102517173/161981098-07420938-a544-4ca8-8509-ca4c76334757.png)
![image](https://user-images.githubusercontent.com/102517173/161981192-80e7fd1b-2a6c-403a-ae14-1fb0edfb2be1.png)
取决于你的需求

**Comment by Cost11** [comment]
> ![image](https://user-images.githubusercontent.com/102517173/161981098-07420938-a544-4ca8-8509-ca4c76334757.png) ![image](https://user-images.githubusercontent.com/102517173/161981192-80e7fd1b-2a6c-403a-ae14-1fb0edfb2be1.png) 取决于你的需求

我是希望哪怕走国外的不能用ipv6 希望国内的能走ipv6走ipv6  但前提不能太影响上网体验 比如国内的能走ipv6走ipv6 但网络有时会很卡 这个有时如果是偶尔可以勉强接收 如果是一直 就不要了  这样的需求我改如何设置

**Comment by Cost11** [comment]
> 每个人的网络情况不一样，我回答不了你，你自己试试不就知道了。

不是 我主要还是没彻底理解 两个ipv6的含义  如果第一true 第二个false 是意味着什么  两个都是true意味着什么

**Comment by dHvpkntUJa** [comment]
![image](https://user-images.githubusercontent.com/102517173/161983539-46583fb7-6e8a-4e6b-9fb3-09d95a94acc3.png)
这是我的理解，要不你问问其他人吧

**Comment by Cost11** [comment]
> ![image](https://user-images.githubusercontent.com/102517173/161983539-46583fb7-6e8a-4e6b-9fb3-09d95a94acc3.png) 这是我的理解，要不你问问其他人吧

我能说我没理解你的理解吗2333  ipv6 pt第一true  那如果第二个也是true 会怎么样？

**Comment by dHvpkntUJa** [comment]
> > ![image](https://user-images.githubusercontent.com/102517173/161983539-46583fb7-6e8a-4e6b-9fb3-09d95a94acc3.png) 这是我的理解，要不你问问其他人吧
> 
> 我能说我没理解你的理解吗2333 ipv6 pt第一true 那如果第二个也是true 会怎么样？

网络有时会卡，至于你问的卡的次数多吗，有多卡，这我哪知道，每个人的网络又不一样。
想折腾，就按自己想法做，想省事，两个默认都是false

**Comment by Cost11** [comment]
ok
