### ISSUE TITLE
请问路由器开启Clash后，局域网内某台设备如何不走Clash？

### ISSUE THREAD

**Issue by tonyzhou777** [Dreamacro/clash#206]
请问路由器开启Clash后，局域网内某台设备如何不走Clash？
请问如何设置？还是说Clash必须是全局代理，然后Clash内部分流？

**Comment by Dreamacro** [comment]
放进来直接 `SRC-IP-CIDR,ip/32,DIRECT` 呗

**Comment by tonyzhou777** [comment]
好的，十分感谢，请问这个“ SRC-IP-CIDR"在哪个文档里有描述？谢谢

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/blob/master/README.md

**Comment by tonyzhou777** [comment]
我试了半天，我想让172.16.0.10不走Clash。
“- SOURCE-IP-CIDR,172.16.0.10/32,DIRECT” 只有这么设定才好使，为何SRC-IP-CIDR还未生效？使用的koolshare，是因为dev分支里还没变动吗？
谢谢。

**Comment by Dreamacro** [comment]
没更新吧，clash 上一个 release 就有 `SRC-IP-CIDR` 了
