### ISSUE TITLE
clashX 设置process-name 和path 都失效

### ISSUE THREAD

**Issue by huiyuerandy** [Dreamacro/clash#2061]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

只要打开系统代理infuse 就不能用，连接不上nas，关闭系统代理就可以用infuse连接emby。试了process-name 和绝对路径 都没用，不知道怎么办。

### Possible Solution

clashx 1.91.1
macos 12.3

**Comment by dHvpkntUJa** [comment]
direct不行的话，可以试试proxyIgnoreList

**Comment by huiyuerandy** [comment]
> direct不行的话，可以试试proxyIgnoreList

我研究一下什么事 proxyIgnoreList

**Comment by huiyuerandy** [comment]
发现了一个奇怪的问题 用infuse 添加emby服务器的话 我输入ip可以 但是输入ddns域名 就不行了 好奇怪啊 我把域名在配置文件各种设置也不行 放弃了。。。

**Comment by dHvpkntUJa** [comment]
如果域名不开clash能用、开了就用不了的话，可以把域名写到clash的host礼试试

**Comment by EvanLuo42** [comment]
我也有相同问题，但我的emby不是自建。infuse打开之后就会连不上，关掉clash又可以了。

**Comment by huiyuerandy** [comment]
> 
请问怎么在配置文件里面写hosts？

**Comment by dHvpkntUJa** [comment]
![image](https://user-images.githubusercontent.com/102517173/167243848-03f12cb5-f302-4167-8bb6-74c837d25fd7.png)

**Comment by jheroy** [comment]
我也遇到这个问题了, 不过可以关掉系统代理, 使用增强模式(fake-ip), 这样infuse就可以正常访问.

**Comment by BirkhoffLee** [comment]
这里是 Clash core，建议 ClashX 相关问题在 https://github.com/yichengchen/clashX/discussions 讨论
