### ISSUE TITLE
[Feature] 自动测速增加惩罚机制

### ISSUE THREAD

**Issue by vlcheng** [Dreamacro/clash#2062]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### 适用前提：
1. fallback或者url-test类型的节点分组；（load-balance类型不熟悉，请用过的朋友补充）
2. 分组下的节点/子分组出现波动，**短时间内时断时续**；

多数人使用的都是机场订阅，难免会发生节点波动的情况，但目前clash并不能有效识别和避免选中这种故障节点/子分组。

### 具体现象：
- fallback分组：在前置位和后置位的节点/子分组之间反复切换；
- url-test分组：故障节点/子分组短时间恢复且延迟满足tolerance要求触发选中；

一旦故障节点被选中，就会造成测速窗口期内服务不可用。目前能够干预的只有interval参数，过分压缩interval可能影响移动设备的性能和续航，增加interval则会进一步延长服务不可用的时间。

### 惩罚机制：
某个节点/子分组在最近x次测速中发生y次timeout，那么接下来的n个测速周期里都屏蔽它，屏蔽过程中正常测速，但即使恢复也不切回去，期间再次触发惩罚则动态延长屏蔽周期。
_如果分组内所有节点/子分组都被屏蔽，则不执行屏蔽行为（防止设备断网恢复后全员被屏蔽）。

### 缺点/不足：
在前几次timeout期间依然会产生服务中断，不过等节点进小黑屋之后就能恢复可用，配合适当的interval可以降低节点波动带来的影响，减少人工干预。

**Comment by JohanChane** [comment]
这个我有点经验。因为我一般是用节点池的，节点是不稳定的。一般测速的节点延时最低的不一定是最好用的，好用节点一般在延时较低的前几个节点。可以维护一个延时较低的节点集合，然后用 fallback 模式选择集合中节点。至于集合中经常超时的节点可以排除出集合。我目前使用 url-test 和 fallback 结合的，看网页不会卡，但是看 1080p 的视频要手动选择节点。比如我的一个配置 [config_basic](https://github.com/JohanChane/IccRes/blob/main/clash/config_basic.yaml)。
