### ISSUE TITLE
[Feature] 通过主机名访问局域网内的设备

### ISSUE THREAD

**Issue by powersee** [Dreamacro/clash#2064]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

作者大大您好，我现在的 clash 是运行在家里的一台服务器上的，然后我是在手机上面，WiFi设置那里，代理设置为手动，然后填写我的服务器 ip ，以及端口 7893

这样我的手机可以正常使用代理访问网站。

但是我有一个需求，就是有时我需要访问家里的服务器或者 nas 设备，平时我都是在浏览器里输入服务器的主机名，例如 http://ubuntu:9000 ，就可以访问到我的 Ubuntu 服务器开启的 9000 端口。

但是现在这样设置代理之后，我的手机就没法通过主机名来访问局域网内的设备了。

我有尝试阅读文档 https://lancellc.gitbook.io/clash/

然后我试过在我的 yaml 配置文件里，添加

`- DOMAIN-SUFFIX,ubuntu,DIRECT`

之后重启 clash 还是不行。

所以想来请教一下，如果让 clash 不解析这类局域网设备名？我应该怎么修改配置文件，才可以达到在浏览器输入 nas 主机名，就可以直接访问。

我目前的解决方法是在手机的代理设置那里，设定哪些网站不走代理，可以达到我的目的，但是我想了解修改修改 yaml 文件来达到我的目的，期待您的答复，谢谢。

**Comment by luwah** [comment]
在config里面添加hosts试试

**Comment by powersee** [comment]
> 在config里面添加hosts试试

好点，感谢，问题已解决。

我是直接在 config.yaml 里添加这一段

```
hosts:
        'ubuntu': '192.168.68.172'
```

关联： #636
