### ISSUE TITLE
[Feature] 可否考虑添加方便部署的机制

### ISSUE THREAD

**Issue by chenjk110** [Dreamacro/clash#2065]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

最近使用 AdGuard Home 时候
发现有个 -s 参数很方便，该参数可以自动在系统中添加服务，方便新用户的部署
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/14145521/162610671-dc5f0736-c0c1-4787-8092-0758b07e83a8.png">

**Comment by chenjk110** [comment]
AdGuard Home 服务特性的相关源码

https://github.com/AdguardTeam/AdGuardHome/blob/master/internal/home/service.go

**Comment by RtYkk** [comment]
https://github.com/Kr328/clash-premium-installer
https://github.com/juewuy/ShellClash
