### ISSUE TITLE
[Feature] dns-hijack是否可以支持劫持发往所有地址的DNS？

### ISSUE THREAD

**Issue by Y32Gcnte8z** [Dreamacro/clash#2068]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Linux系统上auto-route和auto-detect-interface不能自动设置系统DNS，需要在配置文件里的dns-hijack字段逐一添加本机使用的DNS，如果网络环境变化，DNS服务器变化，则需要修改配置文件，很不方便。
如果TUN模式的dns-hijack字段支持劫持所有目标地址的DNS，那就可以通过类似
```yaml
dns-hijack:
  - 0.0.0.0:53
  - tcp://0.0.0.0:53
```
这样的设置，就可以不用逐一设置不同的DNS了

**Comment by moonheart** [comment]
可以设置 any:53 或 tcp://any:53 参考文档 https://github.com/Dreamacro/clash/wiki/premium-core-features#tun-device

**Comment by Dreamacro** [comment]
我都忘了在做完的时候 close 了
