### ISSUE TITLE
[Feature] 重启clash保留之前统计下载总量和上传总量

### ISSUE THREAD

**Issue by qibao07** [Dreamacro/clash#2069]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

通过`/connections`接口可以获取`downloadTotal `和`uploadTotal `属性，可是clash重启后就从0重新统计。

### Possible Solution

使用配置指定是否记录`downloadTotal `和`uploadTotal `属性，是则记录并重启时恢复。否则，不记录也不从记录中恢复。

**Comment by Dreamacro** [comment]
持久化这个拿来做什么？

**Comment by chenweiwen07** [comment]
@Dreamacro 我这边是想每天凌晨记录一次使用流量的情况，通过计算两天之差就能知道那天使用多少流量。如果流量一直都是累积的是没问题的，但重启clash统计的流量变为零结果就有点问题了。

**Comment by Dreamacro** [comment]
更建议把这些访问数据存在一个专门的地方，如 https://github.com/Dreamacro/clash-tracing

**Comment by chenweiwen07** [comment]
感谢作者的推荐，还是希望可以采纳。谢谢

**Comment by caicaicai** [comment]
自己实现一下，也不是很难。。

**Comment by qibao07** [comment]
@caicaicai 
不会go语言，搞个分支，搭个环境，优雅实现功能，编译打包之类，构建docker镜像，还是挺难的吧。

**Comment by caicaicai** [comment]
刚才看了下代码， 可以考虑通过component/tunnel/statistic/manager.go 获取统计的信息， 可以考虑复用他的 component/profile/cachefile/cache.go来持久化数据，init的时候从缓存加载数据，每次更新这个total的时候刷到缓存里面去。

**Comment by caicaicai** [comment]
每个人的想法不一样，你觉得酷炫的功能，人家可能觉得是垃圾。自己尝试捯饬捯饬源码，编译个自己的分支，加上自己喜欢的功能，如果可能再贡献过来，这才是开源的魅力所在。

**Comment by qibao07** [comment]
@caicaicai
我也没觉得我自己说的一定不是你所说的垃圾。
提个建议罢了。

**Comment by caicaicai** [comment]
我没说你提的建议是垃圾，我只是打个比方。我觉得你提的建议蛮好的，每次重启丢统计确实恼火。
