### ISSUE TITLE
建议增加对Policy Name的检查

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#207]
建议 clash 在启动读取 config 的时候对 rule 里的 policy name 进行检查，如果策略不存在的话可以直接报错，而不是直接启动。

（比如我之前把`DIRECT`写成了`DERICT`，从而一直导致策略不匹配，找了很久才发现，所以如果能在初始化的时候就检查一遍会很方便的。）

**Comment by Dreamacro** [comment]
already implemented in the dev branch.
