### ISSUE TITLE
[疑问] clash 目前是否支持指定远端用于查询 DNS 的服务器 以及 dns.nameserver-policy 是仅用于判断或是指定远端服务器用于解析的DNS？

### ISSUE THREAD

**Issue by GrilledPear** [Dreamacro/clash#2070]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

https://github.com/Dreamacro/clash/issues/1201#issuecomment-767313580

https://github.com/Dreamacro/clash/issues/857#issuecomment-698709598

原话是“Clash 的 DNS 解析结果只用于判断，最终都会发送到远端服务器重新解析”

疑问一是： `dns.nameserver-policy` 指定的 DNS 服务器也是仅用于判断？

如果是，那么目前是否有办法指定远端使用的 DNS？

疑问二是：在 Global 模式下，clash 的行为是什么？clash 是否会略过 DNS 的分流判断并直接向远端通信？

**Comment by Dreamacro** [comment]
1. 也是仅用于判断，发往代理的还是域名。这个主要用途是一些公司中都有自己的 dns 服务器用于解析一些内网域名，这些都是直连能访问到的。我不知道你的使用场景是什么，但没有代理支持指定 dns，只能把 ip 发过去。
现在唯一的办法就是通过 script 控制，但这个稍微麻烦些。

2. Global 模式和 Rule 模式的行为仅仅只是统一指向同一个节点，可以近似等价于
```yaml
rules:
    - MATCH,xxxx
```

**Comment by GrilledPear** [comment]
感谢回复，两个基本的疑问都解决了，还有疑问的是下面这个：

对于 `不知道你的使用场景是什么，但没有代理支持指定 dns，只能把 ip 发过去` ，这个分开来讲

场景：使用云服务商提供的服务器，对于服务器没有控制权，无法修改服务器系统 DNS。

对于这个场景，面对远端是黑箱的情况，如果出现不同 DNS 延迟差别很大的现象，能做到手动指定一个可用性更好的 DNS

比如下图是使用在线 mtr 对两个常见 DNS 的测试情况，8.8.4.4 的延时优于 1.0.0.1 的：

![image](https://user-images.githubusercontent.com/90295422/163100782-9272ab2a-26a6-49b8-b573-269d44b81ed9.png)

上面截图的例子不是非常明显的区别，但是云服务商千差万别，出现极端情况的概率也是有的（比如一些服务商的“家宽”，就会出现一些莫名其妙的 DNS）

`但没有代理支持指定 dns，只能把 ip 发过去` 这点，是以前使用 v2ray 时的一个功能，按照 v2ray 文档的说法，它支持把指定 DNS 的查询转发到远端（来源：https://selierlin.github.io/v2ray/app/dns.html#6）

**Comment by Dreamacro** [comment]
@GrilledPear 你的意思是，把域名发给服务器，然后用服务器自带的 dns 解析出的 ip 不是最佳 ip？

**Comment by GrilledPear** [comment]
@Dreamacro 

> 你的意思是，把域名发给服务器，然后用服务器自带的 dns 解析出的 ip 不是最佳 ip？

是的，有些服务商服务器设置的 DNS 可能是当地 isp 分配的 DNS，可能会出现问题，比如下面这个截图里的例子：

![image](https://user-images.githubusercontent.com/90295422/163125725-1a424ab0-6868-473a-88e7-6023aa50adc1.png)

**Comment by Dreamacro** [comment]
@GrilledPear server 端应该是能自定义 dns 的吧？在 server 端设置 dns 后还是发域名应该就行了吧？

**Comment by GrilledPear** [comment]
@Dreamacro  但是可惜目前的情况是，使用云服务商（机场）提供的配置，没有服务器的控制权。 这样的情况下这个问题感觉就无解了。。

**Comment by InspoOnU** [comment]
> 

请问实现这个，script的代码应该怎么写？

**Comment by InspoOnU** [comment]
> 1. 也是仅用于判断，发往代理的还是域名。这个主要用途是一些公司中都有自己的 dns 服务器用于解析一些内网域名，这些都是直连能访问到的。我不知道你的使用场景是什么，但没有代理支持指定 dns，只能把 ip 发过去。
>    现在唯一的办法就是通过 script 控制，但这个稍微麻烦些。
> 2. Global 模式和 Rule 模式的行为仅仅只是统一指向同一个节点，可以近似等价于
> 
> ```yaml
> rules:
>     - MATCH,xxxx
> ```

请问script的代码要怎么写才能实现这个呢？
