### ISSUE TITLE
[Feature] 应该在 ostree (silverblue) 上如何安装 Clash Premium？

### ISSUE THREAD

**Issue by PengCheong** [Dreamacro/clash#2075]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前我在使用 Fedora 35 Silverblue，能通过 `rpm-ostree install clash` 来进行安装 Clash，仅能通过 Clash core 运行并在系统中设置代理的方式上网，但是我无法安装 Clash Premium。

我尝试过使用 [Kr328/clash-premium-installer](<https://github.com/Kr328/clash-premium-installer>) 来进行安装，但是在 Silverblue 中 `/usr/bin/` 是只读的，该脚本不能在我的电脑上正确运行。

系统已经安装 `nftables` 以及 `iproute`，通过 Flathub 安装的 Clash For Windows 点击 Service Mode 的安装也是没有反应的。

另外一个就是我通过 Toolbox 中执行 clash-premium-installer 是正常的，但是在 Toolbox 的操作并不能影响到该 Container 外，也不能使用 systemctl 来进行控制 Clash Premium 的开启 / 使用。

### Possible Solution

（虽然很笨）我尝试用 Clash Premium 替换掉 `/usr/bin/clash`，但正如你所想该操作是被拒绝的。于是我尝试找了一些方法来把我的硬盘进行挂载，挂载没有报错，但是替换操作仍被提示 `Read-only file system`

**Comment by fakeboboliu** [comment]
显然你不应该直接使用文件替换，那是不符合 silverblue 设计的操作

正确的方案可以是：
 - (最简单) 直接把文件放在用户目录，因为为什么不呢，又不影响使用
 - `ostree admin unlock` ，这会挂载一个可写的 overlay，重启后会丢失
 - 自己做一个 rpm 包然后装个 overlay 出来，这里有 [我做好的 rpm](https://github.com/Dreamacro/clash/files/8491381/clash-premium-2022.04.11-1.x86_64.rpm.gz)，你可以参考我的 [build 文件](https://github.com/Dreamacro/clash/files/8491397/clash-premium-rpmbuild.zip) 自己整，这很简单，我只花了几分钟准备这个文件

自己做 rpm 包就可以直接双击来装了：
![](https://user-images.githubusercontent.com/7552030/163452222-1ec22525-f177-480d-9a10-a292094a578a.png)

然后 `clash` 已经存在在 `/usr/bin`：
![](https://user-images.githubusercontent.com/7552030/163452992-596f720f-8924-429b-92f7-8af6f51d5737.png)

不用担心，更新也不会影响这个本地安装的层：
![](https://user-images.githubusercontent.com/7552030/163453001-78698fd8-955b-46ad-ae53-590a25e27bea.png)

更新后，可以看到版本更新了，clash 依旧可用：
![](https://user-images.githubusercontent.com/7552030/163453010-4f522347-df5c-4458-8afd-54975d733000.png)

**Comment by PengCheong** [comment]
Cheong Peng, [4/15/22 2:55 PM]
@fakeboboliu 非常感谢你的帮助，我现在确实能够在 Silverblue 上运行起来 Clash Premium 了

我尝试重新打包并加入开机自启动，但我对 Linux 非常不熟悉导致始终打包失败，但是发现 /etc/systemd/system/ 是可读写的，因此我直接在该处新建了 `clash.service`。

以下是我的做法，希望能为其他需要的人提供帮助：

Step 1:

```bash
sudo sh -c 'echo -e "[Unit]\nDescription=A rule based proxy tunnel\nAfter=network-online.target\n\n[Service]\nType=simple\nRestart=on-aboard\nExecStart=/usr/bin/clash -d /etc/clash\n\n[Install]\nWantedBy=default.target" > /etc/systemd/system/clash.service'
```

Step 2:

```bash
sudo systemctl --system enable clash.service && systemctl start clash.service
```
