### ISSUE TITLE
[Feature] 支持将订阅地址直接作为代理集使用

### ISSUE THREAD

**Issue by InspoOnU** [Dreamacro/clash#2076]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前，Clash的订阅地址下载下来是一个html文件，直接将这个地址填进Proxy-provider里会报错：
`initial proxy provider XXX error: yaml: unmarshal errors:`
``line 1: cannot unmarshal !!str `XXX... ` into provider.ProxySchema``
只有用第三方订阅转换后的地址才能正常使用。

### Possible Solution

下载Proxy Provider里的订阅地址后，如果是html，Clash自动将其转换成yaml文件（就像订阅一般配置一样）。从而用provider写文件，或者同时使用多家机场时，可以简化写文件的步骤。

**Comment by Wrandz** [comment]
我曾经试过在proxy provide那里的http后面直接用机场订阅地址，是可以的欸，不知道为啥你这不行。

**Comment by lambdaplus** [comment]
> 

机场提供的必须是yaml格式文件才可以

**Comment by lambdaplus** [comment]
这个问题应该交由机场来决定，由机场提供yaml格式的订阅，或者交由clash的GUI来做转换

**Comment by ctaoist** [comment]
这个本来就是支持的吧，你机场提供的好像不是标准的yaml文件

**Comment by vlcheng** [comment]
没猜错的话你使用的是ss机场，请尝试在订阅地址后加上`&flag=clash`来获得yaml文件

**Comment by haobarry** [comment]
> 

请问如何自动转为标准的yaml文件??

**Comment by vlcheng** [comment]
> > 
> 
> 请问如何自动转为标准的yaml文件??


1. 文本内容，后缀名不限
2. 使用yaml语法
3. 包含proxies字段

yaml是一种语法，不是特指文件后缀名。只要符合上述条件clash即可正常读取到节点。

如果不确定可以先用订阅转换转一下。
