### ISSUE TITLE
[Feature] 请求增加URL Rewrite功能

### ISSUE THREAD

**Issue by Ricolxwz** [Dreamacro/clash#2081]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

请求增加URL Rewrite功能, 将google.cn重定向到google.com

**Comment by akw5454521** [comment]
https://github.com/Dreamacro/clash/issues/709#issuecomment-632006318
