### ISSUE TITLE
[Feature] `allow-lan` 为 `false` 时同时绑定 `::1`

### ISSUE THREAD

**Issue by Henry-ZHR** [Dreamacro/clash#2089]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前行为是如果 `allow-lan` 为 `false` 则只绑定 `127.0.0.1` ([listener/listener.go#L357](https://github.com/Dreamacro/clash/blob/30d4668008b493b65e7d6982b4c43bb34871e13c/listener/listener.go#L357))，这种情况下无法使用 `ip6tables` 的 tproxy 直接将 ipv6 流量转发到 clash（至少直接 `--on-ip 127.0.0.1` 会报 `Address family for hostname not supported`，如果有其他方法也请告知）

虽然 `allow-lan` 设为 `true` 可以“解决”问题，但这样本身安全性有所下降

### Possible Solution

允许多个 `bind-address` 应该也可以？

**Comment by ShenHongFei** [comment]
我也希望 allow-lan 为 false 的时候能够同时绑定 127.0.0.1 和 ::1, 这样才可以用 `http://localhost:端口/` 来作为 HTTP 代理地址，同时支持 IPv4 和 IPv6 的应用程序
https://github.com/Dreamacro/clash/blob/30d4668008b493b65e7d6982b4c43bb34871e13c/listener/listener.go#L90
这里支持传入 localhost 吗？
