### ISSUE TITLE
[Feature] 用GO写了一个跨平台的轻量Clash客户端

### ISSUE THREAD

**Issue by ctaoist** [Dreamacro/clash#2090]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

只是对 Clash Premium 的简单封装

- 简洁轻量，占内存低，只有托盘图标，没有别的界面
- 开机启动
- 设置系统代理
- 一键更新 Clash Premium
- 跨平台

https://github.com/ctaoist/clashweblite

**Comment by Karmylr** [comment]
牛逼

**Comment by akw5454521** [comment]
之前有ClashWeb了，要不重新起个名字？

**Comment by cukkk** [comment]
测试了，很好！辛苦了！但我用win7或者win10,都有错误提示，虽然不影响使用，但影响使用体验，希望改进，谢谢！

**Comment by ctaoist** [comment]
> 之前有ClashWeb了，要不重新起个名字？

看了一下，改成ClashWebLite了
