### ISSUE TITLE
[Feature] 从链接自动更新配置文件功能

### ISSUE THREAD

**Issue by LYX-Rain** [Dreamacro/clash#2091]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

能不能添加一个可以从链接自动更新配置文件的功能？

**Comment by Wrandz** [comment]
cfw不是已经可以做到了

**Comment by LYX-Rain** [comment]
> 

用docker部署服务器还不行
