### ISSUE TITLE
[Feature] 有个问题想问一下 ssr的文档有吗

### ISSUE THREAD

**Issue by tanzi1997** [Dreamacro/clash#2094]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

类似于
		+--------+----------+
		| Random | HMAC-MD5 |
		+--------+----------+
		|    1   |     6    |
		+--------+----------+

**Comment by Dreamacro** [comment]
应用软件本身并不提供协议规范
