### ISSUE TITLE
[Feature] 选择下载速度最快的节点

### ISSUE THREAD

**Issue by takenusername** [Dreamacro/clash#2095]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

由于机场参差不齐，单纯一个 url-test 并不能直观检测节点的质量。有些高 ping 的下载很快（图一），低 ping 的反而没快到哪里去（图二）。导致高下载速度节点始终利用不到，只能手动 select 。

所以我建议增加按下载速度优先选择。
**考虑到测速时会占用大量宽带，可以不做轮询由用户自己选择测速否，并且存储节点下载速度文件以备不经常切换网络和重启后使用，下一轮测速后覆盖。** 配置参数可有并发数和单个测速时长。

在使用 SSRspeed-reborn 测速我的节点后，5并发+5秒测试时长在总用时上大大缩小，并且和第一组测试结果相差无几。（见下表）

||第一组|第二组|
|--|--|--|
|节点|同个机场115节点|同个机场115节点|
|测试参数|1并发+单个5秒测试时长|5并发+单个5秒测试时长|
|测试用时|10分钟|1分30秒|
|使用流量|≈3.86GB|≈3.8GB|

|图一|图二|
|--|--|
| <img src="https://i.imgur.com/BHyrLPr.jpg"> | <img src="https://i.imgur.com/vL0uBvJ.jpg"> |

**Comment by akw5454521** [comment]
代理客户端不应该做这种事情

**Comment by naa-nac** [comment]
@takenusername 问个题外话 SSRspeed-reborn 这个测速程序 如何控制测速时长呢,配置文件里只有控制线程的参数

**Comment by takenusername** [comment]
@naa-nac webgui 高级，默认并发2+15秒。


![Imgur](https://i.imgur.com/XYpdWcc.jpg)

**Comment by naa-nac** [comment]
@takenusername 感谢解答,之前一直使用命令行测试,打开webgui后发现我与您使用的好像不是同一个程序
好像名称也不一样,我的只有基础和进阶选项进阶里面也没有并发数和测试时长参数
<details>
<summary>stairspeedtest_reborn</summary>
![1](https://user-images.githubusercontent.com/97013229/164960022-7e6e9366-dcfe-481e-8816-ae0b37f089e8.png)
</details>
可以指路一下您使用的程序的下载地址吗,感谢

**Comment by takenusername** [comment]
@naa-nac https://github.com/xxf098/LiteSpeedTest

**Comment by naa-nac** [comment]
@takenusername 感谢解答,之前一直使用命令行测试,打开webgui后发现我与您使用的好像不是同一个程序
好像名称也不一样,只有基础和进阶选项进阶里面也没有并发数和测试时长参数
可以指路一下您使用的程序的下载地址吗,感谢
<details><summary>stairspeedtest_reborn</summary>
<img src = "https://user-images.githubusercontent.com/97013229/164960386-1b6df7d0-5193-4832-a709-0d97f2546f81.png" width = "60%">
</details>
我才弄好图片格式您都回答完了谢谢

**Comment by zhu0629** [comment]
> @takenusername 感谢解答,之前一直使用命令行测试,打开webgui后发现我与您使用的好像不是同一个程序 好像名称也不一样,只有基础和进阶选项进阶里面也没有并发数和测试时长参数 可以指路一下您使用的程序的下载地址吗,感谢
> 
> stairspeedtest_reborn
> 我才弄好图片格式您都回答完了谢谢

就是这个程序
@naa-nac https://github.com/xxf098/LiteSpeedTest

**Comment by takenusername** [comment]
算了

**Comment by youhun00** [comment]
### 写了个 WEB yacd 面版的 Tampermonkey 凑合着用吧 (有时候 ping 低并不代表能用 )
`// ==UserScript==
// @name         BindWidth TestSpeed
// @version      0.1
// @description  Clash WEB BindWidth TestSpeed
// @match        http://192.168.0.1:9090/*
// ==/UserScript==

!(function () {
    /**
     * WEB 面板 适用 yacd Version 0.3.6 https://github.com/yaling888/yacd
     * 其他面板请自行更改 相关节点获取Class类名 / 按钮Class
     */
    const config = {
        server : 'http://192.168.0.1:9090',
        initTime : 6000, // 初始化时间  和节点数量相关 节点越多 需要的时间越长 /ms
        speedTime : 1000, // 开始测速时间 和 节点设置速度相关 节点设置速度越慢 需要的时间越长 /ms
        speedTimeout : 300000, // 测速超时时间 (下载时间) /ms
        speedUrl : 'http://cachefly.cachefly.net/5mb.test', // 测速地址 需要加入GfwList
        sectionNameType : '🚀 节点选择',
        allSpeedBtn: '<button class="_btn_lzu00_1 _circular_lzu00_27" style="--color-btn-bg: #e67f3c;--color-btn-fg: #fff;" onclick="testAllSpeed()"><svg class="" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon></svg></button>', // 一键全部测速按钮样式
        groupHead: '_groupHead_5pmv2_5', // 一键全部测速按钮插入节点
        proxiesList: '_list_1oy7w_1', // 全部节点列表父元素
        speedBtn: { // 节点测速按钮样式
            class: '_proxyLatency_hz69v_1',
            style: 'color: #67c23a;',
        }, 
    };
    let testSpeed = function (obj) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                obj.innerText = '测速开始';
                let startTime = (new Date()).getTime();
                let endTime = startTime;
                config.request = config.request ||  new XMLHttpRequest();
                config.request.open('GET', config.speedUrl + "?" + (new Date()).getTime(), true);
                config.request.responseType = "application/octet-stream";
                config.request.timeout = config.speedTimeout;
                config.request.onreadystatechange = function () {
                    if (config.request.readyState == 2) {
                        startTime = (new Date().getTime());
                        obj.innerText = '测速中...';
                        obj.setAttribute('style', 'color: #f00');
                    }
                    if (config.request.readyState == 3) {
                        endTime = (new Date().getTime());
                        let duration = (endTime - startTime) / 1000;
                        let bitsLoaded = config.request.responseText.length;
                        let speedKbps = ((bitsLoaded / duration).toFixed(2) / 1024).toFixed(2);
                        let speedMbps = (speedKbps / 1024).toFixed(2);
                        let speed = speedMbps > 1 ? speedMbps + 'M/s' : speedKbps + 'K/s';
                        obj.innerText = speed;
                    }
                    if (config.request.readyState == 4) {
                        endTime = (new Date().getTime());
                        let duration = (endTime - startTime) / 1000;
                        let bitsLoaded = config.request.responseText.length;
                        let speedKbps = ((bitsLoaded / duration).toFixed(2) / 1024).toFixed(2);
                        let speedMbps = (speedKbps / 1024).toFixed(2);
                        let speed = speedMbps > 1 ? speedMbps + 'M/s' : speedKbps + 'K/s';
                        obj.innerText = speed;
                        obj.setAttribute('style', 'color: #67c23a');
                        config.request = null;
                        resolve(speed);
                    }
                };
                config.request.ontimeout = (r => {
                    config.request = null;
                    resolve('0k');
                });
                config.request.send();
            }, config.speedTime);
        });
    };
    function _init() {
        if(!document.getElementsByClassName(config.groupHead)[0]) {
            return;
        }
         // 一键全部测速
        let btn = document.createElement('div');
        btn.innerHTML = config.allSpeedBtn;
        document.getElementsByClassName(config.groupHead)[0].appendChild(btn);
        // 节点列表插入测速按钮
        document.getElementsByClassName(config.proxiesList)[0].childNodes.forEach(v => {
            if (["Direct", "Reject", "Relay", "Selector", "Fallback", "URLTest", "LoadBalance", "Unknown"].indexOf(v.childNodes[1].childNodes[0].innerText) == '-1') {
                let span = document.createElement('span');
                span.setAttribute('class', config.speedBtn.class);
                span.setAttribute('style', config.speedBtn.style);
                span.setAttribute('id', '_proxySpeed_' + btoa(encodeURIComponent(v.childNodes[0].childNodes[0].innerText)));
                span.setAttribute('onclick', 'runBindWidth(this)');
                span.innerText = '测速';
                v.childNodes[1].appendChild(span);
            }
        });
    }
    window.runBindWidth = async function (obj) {
        // 关闭所有链接
        let cont = await fetch(config.server + '/connections');
        cont = await cont.json();
        cont.connections = cont.connections || [];
        cont.connections.forEach(v => {
            fetch(config.server + '/connections/' + v.id,{
                headers: {
                    'Content-Type': "application/json"
                },
                method: "DELETE",
            })
        })
        // 开始测速
        return await testSpeed( obj);
    };
    window.proxiesToSet = async function (name) {
        return await fetch( config.server + "/proxies/" + encodeURIComponent(config.sectionNameType), {
            headers: {
                'Content-Type': "application/json"
            },
            method: "PUT",
            body: JSON.stringify({
                name: name
            })
        });
    };
    window.testAllSpeed = async function () {
        config.allTestList = Array.from(document.getElementsByClassName(config.proxiesList)[0].childNodes) || [];
        while (config.allTestList.length) {
            let v = config.allTestList.shift();
            if (["Direct", "Reject", "Relay", "Selector", "Fallback", "URLTest", "LoadBalance", "Unknown"].indexOf(v.childNodes[1].childNodes[0].innerText) == '-1') {
                let res = await proxiesToSet(v.childNodes[0].childNodes[0].innerText);
                if (res.ok) {
                    await runBindWidth(document.getElementById('_proxySpeed_' + btoa(encodeURIComponent(v.childNodes[0].childNodes[0].innerText))));
                }
            }
        }
    };
    setTimeout(() => {
        _init();
    }, config.initTime);
})();
`
