### ISSUE TITLE
[Feature] 请求增加VMess-QUIC  Trojan-QUIC

### ISSUE THREAD

**Issue by qist** [Dreamacro/clash#2098]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

请求增加VMess-QUIC  Trojan-QUIC

**Comment by moranno** [comment]
复议+1

**Comment by mlch911** [comment]
+1

**Comment by bash99** [comment]
+1

某些服务端实现比如verysimple的quic借鉴了hysertia，能启用 bbr 拥塞控制，具有很优秀的速度和延时，同时又没有grpc的偶尔阻塞问题，某些ISP最近udp QoS似乎没有了（暂时就我观察，北京的某些ISP，443端口的UDP没被QOS）。
