### ISSUE TITLE
第11代CPU N5105 DOCKER 显示This program can only be run on AMD64 processors with v3 microarchitecture support

### ISSUE THREAD

**Issue by czxinshui** [Dreamacro/clash#2108]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10.0

### Clash config

```yaml
第11代CPU N5105 DOCKER 显示This program can only be run on AMD64 processors with v3 microarchitecture support
```

### Clash log

```shell
第11代CPU N5105 DOCKER 显示This program can only be run on AMD64 processors with v3 microarchitecture support
```

### Description

第11代CPU N5105 DOCKER 显示This program can only be run on AMD64 processors with v3 microarchitecture support

**Comment by shikkoku** [comment]
https://github.com/golang/go/wiki/MinimumRequirements#amd64

你的CPU似乎不支持AVX2

**Comment by sisrfeng** [comment]
> Go supports compiling to specific microarchitectures using environment variables, e.g. GOAMD64 for go1.18 and later. Binaries will check at startup whether the requested microarchitecture level is supported. For example, a binary built with GOAMD64=v3 will fail on a CPU that doesn't have LZCNT support.



![image](https://user-images.githubusercontent.com/53520949/196164442-ac703e02-a7f5-4d30-abd9-c13570a37e72.png)

![image](https://user-images.githubusercontent.com/53520949/196164644-23c15839-ae23-442a-a82e-1b72c62b6c51.png)
