### ISSUE TITLE
[Feature]  fake-ip-filter、fallback-filter、hosts 引用 Rule Provider

### ISSUE THREAD

**Issue by arm64-v9a** [Dreamacro/clash#2111]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

 fake-ip-filter、fallback-filter、hosts 支持引用 domain 类型的 Rule Provider

**Comment by Wanderingkang** [comment]
我也一直在等这个问题，希望大佬解决一下吧

**Comment by Wanderingkang** [comment]
大佬，能增加一下国内的域名直接扔给国内的dns功能就最好了
