### ISSUE TITLE
[Feature] Metrics Support

### ISSUE THREAD

**Issue by STRRL** [Dreamacro/clash#2113]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

🤩🤩 俺最近看到了您的新成果, https://github.com/Dreamacro/clash-tracing, 实在是太酷了! 

看上去, 目前的数据采集的方式是通过收集日志然后做聚合;
维护一个 logging stack, 然后再在路由器上跑一个日志收集器, 对于我来说负担有些重了.

看上去某些数据是可以通过 metrics 来进行计算的.

我想为 clash-core 引入类似于 /metrics 的 HTTP Endpoint. 

如果您觉得可行的话, 我很有兴趣进行贡献!

相关的 issue:

- https://github.com/Dreamacro/clash/issues/799
- https://github.com/Dreamacro/clash/issues/1155

### Possible Solution

为 clash 引入 /metrics HTTP Endpoint, 作为可开关的特性;

覆盖的范围:

- go runtime
- API 统计
- 用量数据
- ...

**Comment by Dreamacro** [comment]
目前基本的想法是在 clash 这端不做任何数据留存，通过 websocket 暴露出去，对于目前所给出的数据来说没有什么问题。

loki + grafana 的占用本身就不是很小，vector 本身的占用就更小了，要是 vector 支持了 websocket 的 source，还能省下一个 go 的 reporter。一开始用的是 influxdb，后面因为 influxdb 2 的正式版出来后需要强制使用 flux，干脆换成了类似 prometheus 的 loki，比 influxdb 的占用稍微节省了一些。

pprof 的版本我自己有在跑，二进制会大 0.4M 左右，我不太知道 go 的 runtime 中有哪些数据是适合现在 tracing 的形式的。不太能理解 /metrics 有相对于目前暴露 websocket 有多少优势，可以展开说说

**Comment by STRRL** [comment]
tldr; 没啥优势, 就是写了一堆代码(复杂度 ++ ), 让监控数据的处理逻辑可能会简单一点(复杂度 --), 运算 overhead 小一点; 然后它比较好玩;

> 目前基本的想法是在 clash 这端不做任何数据留存;

这点我和您的观点应该是一致的,  clash 里不会存长久的历史数据, 只会有一个 aggregate 数据. 

我对目前 clash 与 clash-tracing 的工作方式知之甚少, 只是猜的话应该是 reporter 去通过 API 读取 clash 的 log, 然后推到 vector, 然后 vector 处理后 sink 到 loki; 最后通过 grafana 展示;

> 维护一个 logging stack, 然后再在路由器上跑一个日志收集器, 对于我来说负担有些重了.

其实俺后来想了想, clash-tracing 所启动的组件其实也并不算太多; 另外维护一个 metrics stack 和 logging stack 区别并不是太大; 这个观点其实没啥意义;

> pprof 的版本我自己有在跑，二进制会大 0.4M 左右，我不太知道 go 的 runtime 中有哪些数据是适合现在 tracing 的形式的。不太能理解 /metrics 有相对于目前暴露 websocket 有多少优势，可以展开说说

go runtime 中其实包含了较多的性能数据, 但是其实用户一般也不关心, 只是看上去好玩; 

只是看 clash-tracing 中提供的 grafana dashboard 的话, 看上去这些图表都非常适合使用 metrics 来统计, 用 metrics 来实现可能会更加"优雅"一些;

另外, metrics 相对于现在通过 logging 内容来统计, 我能想到的好处可能是:

- 数据采集/处理逻辑短, 便于维护;
- 数据处理 overhead 会比较小;
- 如果未来依赖的项目使用了 prometheus 的 client, 也可以一同暴露出去;
- 好玩; 

如果 HTTP Endpoint 只是暴露 pprof 的性能数据的话, 意义不大; 需要我们再为 clash 写采集 metrics 的逻辑(埋点);

另外 metrics 只能做它擅长的事情, 比如说
- 过去 n 小时内, 某个用户访问的次数;
- 过去 n 小时内, dial 的延迟分布热力图
- "实时" 网速等

**Comment by Dreamacro** [comment]
> 另外 metrics 只能做它擅长的事情, 比如说
>
> 过去 n 小时内, 某个用户访问的次数;
> 过去 n 小时内, dial 的延迟分布热力图
> "实时" 网速等

目前 tracing api 做的就是这个，它暴露的也是一些 "metrics" 数据，具体的数据聚合也是通过查询 loki 完成的

> 它做不了:
> 
> 某日某时某分, dial 某个网站的延迟是 n 秒; 这种就需要 event stream (也就是 logging) 来做了

这个目前也是有的，感兴趣的话可以 `websocat ws://localhost:9090/api/profile/tracing`，目前 go 部分做的就是把 websocket 返回的 json 丢给 vector，让它收集到 loki。等什么时候支持 websocket source、或者有哪个便于实现鉴权的通用 source，就可以不需要 go 上报这个部分了。

**Comment by STRRL** [comment]
> > 另外 metrics 只能做它擅长的事情, 比如说
> > 过去 n 小时内, 某个用户访问的次数;
> > 过去 n 小时内, dial 的延迟分布热力图
> > "实时" 网速等
> 
> 目前 tracing api 做的就是这个，它暴露的也是一些 "metrics" 数据，具体的数据聚合也是通过查询 loki 完成的

嗯, 唯一区别就是一个暴露 metrics, 储存时序数据; 另一个采集 logging stream, 储存结构化日志(还是原文日志, 俺不太清楚..);

您目前还有兴趣接收并 Review 相关 PR 吗? :D

**Comment by STRRL** [comment]
> > > 另外 metrics 只能做它擅长的事情, 比如说
> > > 过去 n 小时内, 某个用户访问的次数;
> > > 过去 n 小时内, dial 的延迟分布热力图
> > > "实时" 网速等
> > 
> > 
> > 目前 tracing api 做的就是这个，它暴露的也是一些 "metrics" 数据，具体的数据聚合也是通过查询 loki 完成的
> 
> 嗯, 唯一区别就是一个暴露 metrics, 储存时序数据; 另一个采集 logging stream, 储存结构化日志(还是原文日志, 俺不太清楚..);
> 
> 您目前还有兴趣接收并 Review 相关 PR 吗? :D

Kindly ping. @Dreamacro. :heart:
