### ISSUE TITLE
[Feature] 订阅链接用不了，但在v2rayN里可以用

### ISSUE THREAD

**Issue by redstoneleo** [Dreamacro/clash#2114]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

具体讨论请看 https://github.com/Fndroid/clash_for_windows_pkg/issues/2972

**Comment by Dreamacro** [comment]
并不支持其他配置格式，有需要的话自己使用其他工具进行转换
