### ISSUE TITLE
新功能需求: 提供API接口切换代理,达到 使用动态IP

### ISSUE THREAD

**Issue by AtlantisDe** [Dreamacro/clash#2117]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### 新功能需求: 提供API接口切换代理,达到 使用动态IP

```c#
主要设计,提供其它软件,可以操作.clash
达到轮换 切换代理目的.

大概就是需要这几个功能:
1. 获取代理列表
2. 代理存活状态
3. 发送指令 使用哪个代理.

```

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/external-controller-API-reference
