### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by hexin-lin-1024** [Dreamacro/clash#2118]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

几个功能建议：

IPVersionPreference：在DNS解析中，优先选择哪一种，双栈网络丢弃非偏好选项，
`IPVersionPreference:IPv4`
`nslookup example.com  
11.11.11.11  
2406::0001`
则只返回 `11.11.11.11`。

LogicalOperators: 支持规则中逻辑运算符，
`- AND,((DOMAIN,baidu.com),(NETWORK,UDP)),DIRECT`
(Clash.Meta写法)

ProtocolMatch: 允许通过协议匹配规则，支持定义正则表达式明文匹配，内置基础协议如v4, v6, tcp, udp, icmp等。
 `protocols:  
    - BT,"(tor­rent|.tor­rent|peer_id=|in­fo_hash|get_peers|find­_n­ode|Bit­Tor­rent|an­nounce_peer|an­nounce.php?passkey=)" `
`rules:
    - Protocol, BT, Final
    - Protocol, IPv6, V6Nodes`

精准，自定义的分流是Clash的一大优势，若可以添加以上功能，Clash必将锦上添花。

**Comment by Masaiki** [comment]
支持ip版本偏好这一部分
目前貌似是优先返回ipv4
但我访问 http://www.nhc.gov.cn/ 貌似还是优先返回了ipv6地址 有点迷茫
