### ISSUE TITLE
[Feature] nameserver 指定 interface

### ISSUE THREAD

**Issue by Bowser1704** [Dreamacro/clash#2121]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

对于 TUN 模式

对于公司内网的访问，可以使用 `nameserver-policy` 直接获取正确的 ip。

clash 会用全局指定的 interface 或者 `auto-detect-interface` 找到的 interface 访问公司内网的 DNS server。

这在公司内网是直连的情况是没有问题的，但是公司内网需要用 vpn 访问的时候，则没办法走 vpn 访问 DNS，因为直接走了出口 interface。

### Possible Solution

可以在 `nameserver` 指定 interface。

**Comment by Bowser1704** [comment]
在 nameserver struct 里有一个 interface 字段，没有使用，是可以扩展来指定网络的 interface 吗？

https://github.com/Dreamacro/clash/blob/5dd94c8298e2f7d0a264eb95835b9510e988441a/dns/resolver.go#L304-L308

https://github.com/Dreamacro/clash/blob/5dd94c8298e2f7d0a264eb95835b9510e988441a/config/config.go#L506-L512

**Comment by Dreamacro** [comment]
Already implemented in code
