### ISSUE TITLE
[Bug] fakeip 无法通过优选ipv6接入cdn

### ISSUE THREAD

**Issue by fredericky123** [Dreamacro/clash#2122]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.10

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
见下图
```

### Description

<img width="460" alt="image" src="https://user-images.githubusercontent.com/13982749/167752984-c1a478c3-5b87-4e81-b868-0b337723e3ea.png">
配置好了服务器，通过shadowsocks或者qv2ray能通过优选ipv6连接服务器，可是在clash下却连接不上，不知为何，难道是dns的处理模式不同？

**Comment by fredericky123** [comment]
附上ipv6的dns配置及路由配置
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: true # default is false
  listen: 127.0.0.1:53
  default-nameserver: # resolve dns nameserver host, should fill pure IP
     - 114.114.114.114
     - 223.5.5.5
     - 8.8.8.8
     - 8.8.4.4
     - 1.2.4.8

  enhanced-mode: fake-ip #  # or fake-ip /redir-host
  fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
  fake-ip-filter: # fake ip white domain list
     - '*.lan'
     - localhost.ptlogin2.qq.com
  nameserver:
     - 1.1.1.1
     - 176.103.130.130
     - 119.29.29.29
     - 8.8.8.8
     - 8.8.4.4
     - 1.2.4.8
     - 114.114.114.114
     - 223.5.5.5
     - tls://dns.rubyfish.cn:853 # dns over tls
     - https://1.1.1.1/dns-query # dns over https
     - dhcp://en0 # dns from dhcp
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
     # - 127.0.0.1
     - 1.1.1.1
     - 8.8.8.8
     - 8.8.4.4
     - 1.2.4.8
     - 114.114.114.114
     - 223.5.5.5
    # - tcp://1.1.1.1
  fallback-filter:
     geoip: true # default
     ipcidr: # ips in these subnets will be considered polluted
       - 240.0.0.0/4

  - IP-CIDR6,::/0,DIRECT

**Comment by dHvpkntUJa** [comment]
clash 好像是选择响应快的

**Comment by fredericky123** [comment]
> clash 好像是选择响应快的

关键是ipv6那个链接测试 ping不通 
还没到选择环节

**Comment by Joseph-ink** [comment]
你IPv6地址写法不对，多看看文档和别人的配置
```
server: "2606::"
```
