### ISSUE TITLE
怎么配置绕过某个节点呢

### ISSUE THREAD

**Issue by yunyuyuan** [Dreamacro/clash#2124]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

一个订阅地址里有很多节点，有的是测试节点，延迟低但非常不稳定。

怎么设置《自动选择》的同时，绕过特定节点呢

**Comment by luwah** [comment]
建议在proxy-provider中使用filter选择所需节点，目前暂不支持排除节点
或者使用订阅转换工具直接排除

**Comment by dHvpkntUJa** [comment]
1.自己写配件文件
2.用cfw的parser添加append-proxy-groups

**Comment by Lolicon-A** [comment]
> 1.自己写配件文件 2.用cfw的parser添加append-proxy-groups

这个方法怎么使用？请问有具体示例吗？
