### ISSUE TITLE
一直自动更换节点 不太稳定

### ISSUE THREAD

**Issue by shawokou123** [Dreamacro/clash#2127]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

使用版本：
clash-darwin-amd64-v3-v1.10.6

电脑系统：
macOS 12.3

求助问题：
在macos的终端，使用该版本的clash，目前唯一问题是，clash会一直不停的更换节点，有时候会更换到坏的节点上.
如何设定，在众多节点上选择某个速度快的，然后稳定在该节点，等该节点不能使用后，再进行更换。
这样会比较稳定。

**Comment by luwah** [comment]
urltest是指延时短，不是指速度快，想减少自动切换可以尝试tolerance参数
fallback可以满足“节点无响应后再切换”，但是未必是速度快的

**Comment by shawokou123** [comment]
@luwah 非常感谢您的答复，tolerance参数 如何调整，可以实现  “节点无响应后再切换”   的效果？ 请您指教！

**Comment by shawokou123** [comment]
> urltest是指延时短，不是指速度快，想减少自动切换可以尝试tolerance参数
> fallback可以满足“节点无响应后再切换”，但是未必是速度快的

非常感谢您的答复，tolerance参数 如何调整，可以实现 “节点无响应后再切换” 的效果？ 请您指教
还有，tolerance参数 这个参数在哪个地方？  我是小白，请您指教！

**Comment by luwah** [comment]
建议参考https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto
例如：
A延迟100，B延迟110，选A，因为100<110

添加tolerance为100后
A延迟100，B延迟110，选A；
再测试A延迟150，B延迟110，选A，因为150<100+100；
再测试A延迟210，B延迟110，选B，因为210>100+100
实际设置建议根据自己的网络情况，不一定设置为100

**Comment by shawokou123** [comment]
@luwah 您指的是这样设置么？请您帮我看下，我以下是否正确， 若不正确，请帮助修改：


  proxy-groups:
  - name: "auto"
    type: url-test
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 100
