### ISSUE TITLE
go install方式无法正常安装clash命令行版本

### ISSUE THREAD

**Issue by shawokou123** [Dreamacro/clash#2128]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.10.6 

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
go install github.com/Dreamacro/clash@latest

使用如上命令，安装 clash v1.10.6 ,但是无法正常安装，一直出现如下错误提示：
go: github.com/Dreamacro/clash@latest: module github.com/Dreamacro/clash: Get "https://proxy.golang.org/github.com/%21dreamacro/clash/@v/list": EOF
```

### Description

go install github.com/Dreamacro/clash@latest

使用如上命令，安装 clash v1.10.6 ,但是无法正常安装，一直出现如下错误提示：

go: github.com/Dreamacro/clash@latest: module github.com/Dreamacro/clash: Get "https://proxy.golang.org/github.com/%21dreamacro/clash/@v/list": EOF

**Comment by Dreamacro** [comment]
网络问题 切换源即可

**Comment by shawokou123** [comment]
能不能给一个可以使用的源

**Comment by AaronChen0** [comment]
```
go env -w GOPROXY=https://goproxy.cn,direct
```
or
```
go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
```

**Comment by shawokou123** [comment]
非常感谢
