### ISSUE TITLE
[求助] 在安卓系统上使用clash 知乎无法正常打开

### ISSUE THREAD

**Issue by shawokou123** [Dreamacro/clash#2132]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

如标题所示
我在安卓系统上使用clash，chrome等都可以正常使用。
但是纽约时报中文版app和 知乎app，不能正常上网。

该如何去做？

**Comment by qist** [comment]
一些规则。https://github.com/Loyalsoldier/clash-rules

**Comment by dHvpkntUJa** [comment]
看看分应用代理的设置

**Comment by shawokou123** [comment]
> 看看分应用代理的设置

您好！如何查看？具体如何设置!急求

**Comment by shawokou123** [comment]
我指的是，命令行版本的clash，如何实现 分应用代理设置

**Comment by shawokou123** [comment]
我的分流设置没有问题，在chrome浏览器是，查询ip是国内的，没有问题。
现在问题就是出在，如果打开 知乎app，不能正常访问。
是安卓系统内的 clash 命令行版本
