### ISSUE TITLE
在路由器上这两种错误是什么问题呢，谢谢作者

### ISSUE THREAD

**Issue by ztechie** [Dreamacro/clash#214]
time="2019-06-22T23:57:04Z" level=warning msg="Proxy[DIRECT] connect [101.71.37.28 --> 139.227.10.35] error: dial tcp 139.227.10.35:17457: connect: connection refused"
time="2019-06-22T23:57:04Z" level=warning msg="Proxy[DIRECT] connect [10.0.0.235 --> 115.219.38.189] error: dial tcp 115.219.38.189:63741: i/o timeout"

**Comment by ztechie** [comment]
在direct模式下的网址就会这样

**Comment by Dreamacro** [comment]
字面意思，一个连接被拒绝，一个连接超时。
