### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by ddebao** [Dreamacro/clash#2142]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb v1.0.0 这个站点是您的吗，它似乎不能正常访问了。

**Comment by akw5454521** [comment]
@GFW 快解决一下，不要不识抬举

**Comment by yangshuochina** [comment]
明明是cdn.jsdelivr.net域名被污染了，这个也能过来提Issues？

**Comment by qist** [comment]
https://github.com/Loyalsoldier/geoip 自己去手动下载呗。

**Comment by ddebao** [comment]
thanks! @qist
