### ISSUE TITLE
[Feature] 点击面板的 Proxies 内的 Button 切换代理

### ISSUE THREAD

**Issue by Innei** [Dreamacro/clash#2152]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/41265413/170073559-6acaa40c-0157-4397-b575-8d1e53548d61.png">

点击这些 Button 不能切换代理，测完 ping 之后，需要上面去找很麻烦。

### Possible Solution

点击 Button 可以切换代理，至于要把这个代理应用到具体哪个模式上，可以弹出一个菜单来选择。

**Comment by zhongfly** [comment]
ClashX的问题 请去 https://github.com/yichengchen/clashX 反馈
这里是clash内核的仓库，没有GUI的

**Comment by Innei** [comment]
好的
