### ISSUE TITLE
[Bug] 无法设置 IPv6 DNS 为 nameserver

### ISSUE THREAD

**Issue by kdurov** [Dreamacro/clash#2160]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.05.18

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
nameserver:
  - 1.1.1.1
  - "2001:da8::666"
  - "2001::"


  default-nameserver:
  - "2001:da8::666"
  - "2001::"
```

### Clash log

```shell
使用引号包起 v6 DNS 时，去掉引号同样报错
FATA[0000] Parse config error: DNS NameServer[2] format error: address 2001:da8::666: too many colons in address

使用 [] 包起 v6 DNS 时候：
line 75: cannot unmarshal !!seq into string
```

### Description

可以连接解析出来的 AAAA 结果
可以使用 v6 的 proxy
但是无法设置 IPv6 DNS为 nameserver 或者 default-nameserver

DNS 是用 NAS 自建的，v4没有公网IP。在外只能用 v6 连接。
用 v6 only VPS 自建的 DNS 服务器也同理无法使用。

**Comment by Dreamacro** [comment]
可以使用完整的地址 `"[2001:da8::666]:53"`

**Comment by kdurov** [comment]
感谢回复。
能否把这个添加到 config 模版文件中呢？顺带加上 proxy 里面节点地址 v6 情况下需要加引号的问题。

顺便请教下 default-nameserver 里面的 DNS 服务器是否**只**用来解析 nameserver 中的 DoH/DoT 等地址呢？
担心访问域名被 ISP 记录，nameserver 都是自建服务器。不过 default-nameserver 用的是 ISP 分配的 DNS，
这种情况下实际访问地址的解析并不会经过 default-nameserver 里面的 DNS 对吧。

**Comment by Dreamacro** [comment]
对，只解析 DoH/DoT 的域名，防止回环用的
