### ISSUE TITLE
[Feature] 请问这个软件有PAC模式吗

### ISSUE THREAD

**Issue by qq421962914** [Dreamacro/clash#2161]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

请问这个软件有PAC模式吗

**Comment by spzeno** [comment]
可以自己加规则呀

**Comment by linyu003** [comment]
+1 
PAC模式是有必要的。我的场景是，公司有自己的VPN，Clash无论是的tun，还是系统代理，都会和公司的VPN冲突。 
使用SSR的PAC模式可以完美解决这个问题，如果Clash也有这个功能就好了。
Clash的Rule模式和PAC是有本质区别的

**Comment by CharlotteFallices** [comment]
[TProxy](https://lancellc.gitbook.io/clash/start-clash/clash-udp-tproxy-support) 👀

**Comment by qist** [comment]
自己找份pac脚本文件然后把里面的代理地址改成你的clash的地址，pac 文件可以使用nginx提供下载。就可以了。

**Comment by linyu003** [comment]
> 自己找份pac脚本文件然后把里面的代理地址改成你的clash的地址，pac 文件可以使用nginx提供下载。就可以了。

感谢帮助，这确实是目前可行的一个办法。

但是对clash原生支持PAC的需求仍然存在。
修改的规则的时候还要亲手去改PAC文件，实在有点麻烦，更高级的规则分类也难以实现。
