### ISSUE TITLE
[Feature] 相同名字的节点

### ISSUE THREAD

**Issue by ErnestDong** [Dreamacro/clash#2164]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

因为使用流量有时候会到账户上限，我使用两个来自同一个 proxy-provider 的代理节点，两份提供的节点名（`proxies`的`name`）是一样的，例如 `HK-1`，请问有什么方法能同时使用这两个provider呢？谢谢！

**Comment by PingZi-Wing** [comment]
一个曲线救国的方法，前提需要iOS设备、Surge或ShadowRocket或Loon或Quantumult X 或Stash软件。使用Sub-Store（参考链接https://t.me/cool_scripts）订阅机场，并重命名节点名，然后托管订阅引用即可。

**Comment by itKelis** [comment]
使用cfw可以快速切换订阅

**Comment by BirkhoffLee** [comment]
Clash core 无法支持这个功能
