### ISSUE TITLE
[Feature] 能让某个节点的流量回环到clash里吗

### ISSUE THREAD

**Issue by Bitcion** [Dreamacro/clash#2165]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

节点不太稳定，但是是Netflix原生节点，所以想让这个节点走其他节点的代理使用。

指定单个节点回流是最好的吧，如果是所有流量回流就回环了

**Comment by akw5454521** [comment]
- name: "relay" type: relay proxies: - http - vmess - ss1 - ss2

**Comment by CharlotteFallices** [comment]
Maybe set "this node" as the outbound of "other node" will work?

**Comment by techblack** [comment]
use relay
