### ISSUE TITLE
[Feature] 支持trojan-go的encryption参数

### ISSUE THREAD

**Issue by hyhy01** [Dreamacro/clash#2168]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

```sh
encryption=ss%3Baes-256-gcm%3Afuckgfw
```
https://p4gefau1t.github.io/trojan-go/developer/url/ 
这个参数找不到怎么配

**Comment by skill7899** [comment]
顺带把mux也支持一下。。
