### ISSUE TITLE
代理的 fallback 能自定义时间 

### ISSUE THREAD

**Issue by feng92f** [Dreamacro/clash#217]
如果一个代理的测试响应时间过长了，比如超过 2000ms，那么可以设置这个代理服务器为不可用。可能的方法是，在fallback模式里设置一个自定义的timeout。

**Comment by xqXQzzz1** [comment]
fallback是全部测完选择第一个还是按顺序测，满足条件就不测了？

**Comment by Dreamacro** [comment]
新增了一个 tolerance 配置，应该能更好的符合你的要求

**Comment by xqXQzzz1** [comment]
![图片](https://user-images.githubusercontent.com/35725489/86434032-eff24a00-bd2e-11ea-977c-b5f7e610d8d5.png)
![图片](https://user-images.githubusercontent.com/35725489/86434048-faacdf00-bd2e-11ea-82af-4de55b971654.png)
似乎不起作用

> 
> 
> 新增了一个 tolerance 配置，应该能更好的符合你的要求

**Comment by feng92f** [comment]
> ![图片](https://user-images.githubusercontent.com/35725489/86434032-eff24a00-bd2e-11ea-977c-b5f7e610d8d5.png)
> ![图片](https://user-images.githubusercontent.com/35725489/86434048-faacdf00-bd2e-11ea-82af-4de55b971654.png)
> 似乎不起作用
> 
> > 新增了一个 tolerance 配置，应该能更好的符合你的要求

你这个图里有SSR 你确定是新版的clash吗？

**Comment by xqXQzzz1** [comment]
> 
> 
> > ![图片](https://user-images.githubusercontent.com/35725489/86434032-eff24a00-bd2e-11ea-977c-b5f7e610d8d5.png)
> > ![图片](https://user-images.githubusercontent.com/35725489/86434048-faacdf00-bd2e-11ea-82af-4de55b971654.png)
> > 似乎不起作用
> > > 新增了一个 tolerance 配置，应该能更好的符合你的要求
> 
> 你这个图里有SSR 你确定是新版的clash吗？

开源版本，加上了SSR的pr。
另外看了看wiki发现fallback没有tolerance的属性
![图片](https://user-images.githubusercontent.com/35725489/86434724-bfabab00-bd30-11ea-8f84-f60a715e293b.png)

**Comment by feng92f** [comment]
@Dreamacro @xjasonlyu x 最开始这个需求是想有两组服务器，一个无限流量A，一个快速的服务器1T流量。通过fallback+timeout可以实现优先使用A服务器，如果A太慢了，就换到B。
现在新特性的tolerance可以实现，就是fallback里是A Group url-test with tolerance 和 B Group url-test with or without tolerance 。这样 当A组全都超时的时候，就会到B组。

**Comment by xqXQzzz1** [comment]
> 
> 
> @Dreamacro @xjasonlyu x 最开始这个需求是想有两组服务器，一个无限流量A，一个快速的服务器1T流量。通过fallback+timeout可以实现优先使用A服务器，如果A太慢了，就换到B。
> 现在新特性的tolerance可以实现，就是fallback里是A Group url-test with tolerance 和 B Group url-test with or without tolerance 。这样 当A组全都超时的时候，就会到B组。

请问一下，url-test的tolerance是哪种方式：
1，仅仅返回一个timeout，仍然切换最快的节点
2，在设定值内，不切换节点
