### ISSUE TITLE
[Feature] 根据 WiFi SSID 或 LAN IP address 来启用/禁用规则

### ISSUE THREAD

**Issue by helloBeren** [Dreamacro/clash#2170]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

rules:
  - DOMAIN-SUFFIX,example.com,vpn
  - IP-CIDR,10.0.0.0/8,vpn,no-resolve

请教一下，我启用了tun模式，在proxies里面设置了vpn的服务器，有没有办法根据wifi或者有线网络获得的公司ip（单纯通过wifi的名称来判断也可以，顶多我去公司只用wifi不用网线了），来自动启用禁用上面这两条vpn规则，感激不尽。其实就是公司以外的网络自动启用这两条规则，去了公司就自动禁用这两条规则。

**Comment by BirkhoffLee** [comment]
估计不会实现，自己写 shell script 比较实际咯
把 vpn 换成一个 proxy group，在 shell script 里呼叫 external controller api 切换这个 proxy group 的 proxy（vpn 跟 DIRECT）
