### ISSUE TITLE
[求助] 

### ISSUE THREAD

**Issue by supermangithu** [Dreamacro/clash#2174]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

你好，怎样让openvpn通过clash客户端走上网流量？
也就是openvpn over clash？
在.ovpn文件加上
remote  xxxxxx
http-proxy 127.0.0.1 7890
http-proxy-retry
后续应该怎样做？

**Comment by CharlotteFallices** [comment]
You may need to provide some additional information:
- Are you using OpenVPN Access Server, OpenVPN Cloud, or Community Solution?
- In the case of Access Server, what is the OpenVPN Server Version?

**Comment by BirkhoffLee** [comment]
https://github.com/Dreamacro/clash/wiki/Examples#use-with-openconnect
