### ISSUE TITLE
[Feature] 希望provider的filter没匹配到的时候不直接报错，而是添加- DIRECT节点

### ISSUE THREAD

**Issue by Geniucker** [Dreamacro/clash#2175]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

希望provider的filter没匹配到的时候不直接报错，而是添加- DIRECT节点。  
目前如果filter的值无法被匹配到会直接报错

**Comment by PingZi-Wing** [comment]
有类似问题，我觉得允许存在空节点代理组更合适。
#1974

**Comment by NutterChen** [comment]
+1

**Comment by PingZi-Wing** [comment]
我来提供一个曲线救国的方法，前提需要iOS设备、Surge或ShadowRocket或Loon或Quantumult X 或Stash软件。使用Sub-Store（参考链接[https://t.me/cool_scripts]）订阅机场，同时新建本地无效节点订阅，比如我添加了美日韩无效节点，然后整合本地节点和机场（托管订阅）为clash格式的gist片段，打开托管自动同步，最后引用gist片段为provider。这样因为无效节点的存在，即使机场没有美日韩节点也不会报错。另外可以使用ghproxy加速gist引用，https://ghproxy.com/接gist片段的raw链接，raw链接需要删除随机符，raw链接应为https://gist.githubusercontent.com/用户名/xxxxxx/raw/片段名。
