### ISSUE TITLE
请问为什么这个OPENWRT 的OPENCLASH 一直在转圈，自动刷新始终无法关闭？

### ISSUE THREAD

**Issue by kevinyang68** [Dreamacro/clash#2177]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

请问为什么这个OPENWRT 的OPENCLASH 一直在转圈，自动刷新始终无法关闭？，点击关闭后，在重新回到运行状态页面，又是自动刷新开的。

**Comment by Dreamacro** [comment]
去对的地方发 issue 吧
