### ISSUE TITLE
更新至0.15版本之后自定义hosts失效

### ISSUE THREAD

**Issue by Azureki** [Dreamacro/clash#218]
系统：linux

在文件`/etc/hosts`中加入：`ip customdom.com`，然后在clash中配置文件中，将代理的server改为`custom.com`。

并且我取消注释了DNS部分。

日志：
> WARN[0014] Proxy[Proxy] connect [127.0.0.1 --> ip] error: customdom.com:port connect error: All DNS requests failed

看来是DNS问题，因为域名是我自己编的，所以根据这个域名查不到ip。
可是`0.14`版本是可以这么做的。

**Comment by Dreamacro** [comment]
只要开启了自定义 dns，那么 hosts 就是不生效的

**Comment by Azureki** [comment]
但是0.14版本确实是可以这样的…
所以是因为0.14版还不完善？

**Comment by Dreamacro** [comment]
之前的版本节点的域名解析即使打开了自定义 dns 也走的系统 dns，release changelog 里也提到了这个改变

**Comment by Azureki** [comment]
原来如此，感谢回复。

**Comment by kuroroXF** [comment]
关闭自定义DNS会不会导致不安全比如DNS污染。

**Comment by yuki-216** [comment]
希望能够支持自定义dns后，仍可以使用host
