### ISSUE TITLE
[Bug] 无法向 WireGuard 的本地网卡发送请求

### ISSUE THREAD

**Issue by neteroster** [Dreamacro/clash#2180]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.05.08 (Premium) 64944

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
...
proxies:
  -
    name: "A"
    type: socks5
    server: 10.10.0.2
    port: 8888
...
```

### Clash log

```shell
time="2022-06-15T14:47:30+08:00" level=warning msg="[TCP] dial * (match IPCIDR/149.154.160.0/20) to *:80 error: 10.10.0.2:8888 connect error: dial tcp4 10.10.0.2:8888: i/o timeout"
```

### Description

如题，WireGuard 本地配置

```
[Interface]
PrivateKey = *
ListenPort = 16383
Address = 10.10.0.1/32
MTU = 1440

[Peer]
PublicKey = *
AllowedIPs = 10.10.0.0/24
Endpoint = *
```

然后远端是 10.10.0.2，其 8888 端口开了一个 socks5 服务，但是 clash 看起来没法连接 10.10.0.2 (`error: 10.10.0.2:8888 connect error: dial tcp4 10.10.0.2:8888: i/o timeout`)

经测试 Telegram 的代理可正常使用 10.10.0.2 上 8888 的 socks5 服务

![image](https://user-images.githubusercontent.com/10304206/173762436-36265180-6cb4-4d73-b5dc-334a9c589cfa.png)

**Comment by Dreamacro** [comment]
给这个 socks5 配置加个 interface-name

**Comment by neteroster** [comment]
感谢，已解决！
