### ISSUE TITLE
[Feature] Premium Scripting Support ipset 

### ISSUE THREAD

**Issue by sskaje** [Dreamacro/clash#2181]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

需求是能根据客户端的 IP 来选择代理，现有体系下，可以使用 script，判断 src_ip 。

期望是，脚本支持从 ipset 里判断，对应的命令是 `ipset test SRC_CLASH 192.168.2.2`，这样可以在不重启或者 reload 的情况下，实现规则的调整。

```
if ctx.in_ipset(src_ip, "SRC_CLASH_FULL"):
    return "PROXY"
```

### Possible Solution

没怎么写过 golang ，随手搜了几个可能的ipset golang wrapper

https://github.com/janeczku/go-ipset
https://github.com/gonetx/ipset
https://pkg.go.dev/github.com/gmccue/go-ipset
https://pkg.go.dev/k8s.io/kubernetes/pkg/util/ipset

**Comment by Dreamacro** [comment]
不知道什么场景下需要频繁变动 src 的规则，而且 src ip 的数量一般相对较少。

`SRC-IP-CIDR` 不能解决么

**Comment by sskaje** [comment]
开发需求，低优先级。

我自己之前基于WireGuard的方案，使用 ipset 管理列表规则，使用 PBR 允许将特定客户机的流量全量走 VPN 或者使用 NAT 通过 redsock 转发 TCP 到 Charles proxy 里实现流量劫持分析。
前者常出现在规则调试或者其他某些需要全量走外网的场景；后一个场景，基本可以在路由器上抛弃 redsocks。

但是目前的实现方式，需要重启或者 rest api 去重新加载配置，如果操作频繁，家里会影响其他设备上网。

**Comment by sskaje** [comment]
我懂你的意思了，这个方案可以，结合DHCP直接把常用的目标预定义好，也是个不错的视线，我先用这个方案，谢谢
