### ISSUE TITLE
mkcp or kcptun surport

### ISSUE THREAD

**Issue by future-death** [Dreamacro/clash#2186]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

希望增加对kcp传输协议的支持。

**Comment by cambrian07** [comment]
any progress?
