### ISSUE TITLE
config.yaml能否支持include其它文件

### ISSUE THREAD

**Issue by xdaniel9** [Dreamacro/clash#219]
这样的话，纯代理、流媒体、去广告等不同类规则可以写在不同文件里，而且可以和proxy服务器信息分开，规则可以直接放github上。
如果能支持include url就更好了，像这样`include https://xxxx.xxx.yaml`，这样多台终端只要在一台电脑上更新规则然后git push，其它终端自动更新规则

**Comment by contributionls** [comment]
@xdaniel9 Hey,I have the same problem.So,I made the online merge, template utils <https://utils.men> for this.

You can merge multi config urls, make the final url.

I was using it now,you can try it if you like.

**Comment by ruisiji** [comment]
和这个有点重复了，RuleSet 会比 include 更好用一些。

https://github.com/Dreamacro/clash/issues/79

**Comment by BirkhoffLee** [comment]
#272
