### ISSUE TITLE
被shortcuts给REJECT掉的UDP通信却还是会触发一次DNS查询

### ISSUE THREAD

**Issue by Y32Gcnte8z** [Dreamacro/clash#2192]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.06.19

### Clash config

```yaml
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443

rules:
  - SCRIPT,quic,REJECT
```

### Description

被REJECT掉的UDP通信却还是触发了DNS查询，这样会通过DNS暴露正在访问的网站，本来想通过只匹配域名规则不用IP规则来避免的，QUIC也都REJECT掉了，结果还是破功了，有什么解决办法吗？按理说这是被REJECT掉的UDP，不需要查询真实IP地址的。

**Comment by Dreamacro** [comment]
使用 no-resolve

```
rules:
  - SCRIPT,quic,REJECT,no-resolve
```

**Comment by returnL** [comment]
> > 使用 no-resolve
> > ```
> > rules:
> >   - SCRIPT,quic,REJECT,no-resolve
> > ```
> 
> 没加no-resolve之前是所有经过了script规则的都触发了dns查询，加了之后，普通的tcp连接确实不会有dns查询了，但是被这条规则reject掉的udp通信还是会有一次dns查询，100%复现

我也碰到了同样的问题。我是用了adguard home作为clash的上游DNS，通过查看adguard home的日志来判断某个域名有没有触发DNS解析。

我的规则里YouTube的域名在不加`SCRIPT,quic,REJECT`这条规则时，都是远端解析，在adguard home的日志里看不到YouTube的域名。

加上`SCRIPT,quic,REJECT`之后，其他配置都不改变的情况下，adguard home的日志里面能看到YouTube的域名，应该可以判断出是这条规则`SCRIPT,quic,REJECT`触发了DNS解析。

加上`no-resolve`变成`SCRIPT,quic,REJECT,no-resolve`之后，同时看clash和adguard home的日志可以发现，YouTube的TCP连接在adguard home的日志里看不到了，没有触发DNS解析，和不加`SCRIPT,quic,REJECT`规则时一样，但是YouTube的UDP连接依旧会在adguard home的日志里面看到，应该被REJECT掉的UDP连接触发了DNS解析

**Comment by emacsnt** [comment]
实测观察下来,只要经过shortcut的，不管是reject还是匹配其他规则，都会触发dns查询，和规则是否包含ip无关。

**Comment by emacsnt** [comment]
似乎在最新版里面这个问题修正了[fakeip logic improve (can help reduce the list of fake ip-filters, .e.g full-cone on Nintendo Switch network test)
](https://github.com/Dreamacro/clash/releases/tag/v1.11.4)

**Comment by emacsnt** [comment]
> > 似乎在最新版里面这个问题修正了[Fix: fakeip udp should not replace with another ip)
> > ](https://github.com/Dreamacro/clash/commit/5497adaba1ff81be5225ebd0849964bba5b23987)
> 
> 并没有

用了7月7日的premium版本，我本地已经无法再现这个问题了

**Comment by emacsnt** [comment]
> > > > 似乎在最新版里面这个问题修正了[Fix: fakeip udp should not replace with another ip)
> > > > ](https://github.com/Dreamacro/clash/commit/5497adaba1ff81be5225ebd0849964bba5b23987)
> > > 
> > > 
> > > 并没有
> > 
> > 
> > 用了7月7日的premium版本，我本地已经无法再现这个问题了
> 
> 我还是100%复现啊hushed，你是抓包看了确定被reject掉的udp都不会触发dns查询吗
没有抓包，就是看debug日志:)

**Comment by sleepyyyyy** [comment]
udp连接发送到目标策略组时，是不是以IP形式发送的？（对比tcp以域名形式发送）
如果是的话,大概是reject没做特别处理，所以最后也要解析成ip，在这一步触发了dns解析

**Comment by 10ta** [comment]
> > > 使用 no-resolve
> > > ```
> > > rules:
> > >   - SCRIPT,quic,REJECT,no-resolve
> > > ```
> > 
> > 
> > 没加no-resolve之前是所有经过了script规则的都触发了dns查询，加了之后，普通的tcp连接确实不会有dns查询了，但是被这条规则reject掉的udp通信还是会有一次dns查询，100%复现
> 
> 我也碰到了同样的问题。我是用了adguard home作为clash的上游DNS，通过查看adguard home的日志来判断某个域名有没有触发DNS解析。
> 
> 我的规则里YouTube的域名在不加`SCRIPT,quic,REJECT`这条规则时，都是远端解析，在adguard home的日志里看不到YouTube的域名。
> 
> 加上`SCRIPT,quic,REJECT`之后，其他配置都不改变的情况下，adguard home的日志里面能看到YouTube的域名，应该可以判断出是这条规则`SCRIPT,quic,REJECT`触发了DNS解析。
> 
> 加上`no-resolve`变成`SCRIPT,quic,REJECT,no-resolve`之后，同时看clash和adguard home的日志可以发现，YouTube的TCP连接在adguard home的日志里看不到了，没有触发DNS解析，和不加`SCRIPT,quic,REJECT`规则时一样，但是YouTube的UDP连接依旧会在adguard home的日志里面看到，应该被REJECT掉的UDP连接触发了DNS解析


`May 17 17:49:59 debian Clash[6447]: 17:49:59 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=rr2---sn-nx57ynlk.googlevideo.com. answer=["159.65.107.38"]

May 17 17:49:59 debian Clash[6447]: 17:49:59 DBG [UDP] accept session lAddr=10.1.0.16:51255 rAddr=rr2---sn-nx57ynlk.googlevideo.com:443 inbound=TUN

May 17 17:49:59 debian Clash[6447]: 17:49:59 INF [UDP] connected lAddr=10.1.0.16:51255 rAddr=rr2---sn-nx57ynlk.googlevideo.com:443 mode=rule rule=Script(QUIC) proxy=REJECT`

配置同你, premium 0416还是存在这个问题, 
看日志的顺序, 是先DNS再REJECT

**Comment by InspoOnU** [comment]
2023.05.29 这个问题依然存在：UDP被REJECT掉会触发DNS查询，不管加没加no-resolve

**Comment by Wrandz** [comment]
2023.08.03，这个问题似乎已经修复了，我已经无法复现

**Comment by 10ta** [comment]
```
03:42:00 DBG [UDP] accept session lAddr=127.0.0.1:49414 rAddr=graph.instagram.com:443 inbound=Socks5
03:42:00 INF [UDP] connected lAddr=127.0.0.1:49414 rAddr=graph.instagram.com:443 mode=rule rule=Script(QUIC) proxy=REJECT
03:42:00 DBG [DNS] dns response source=https://120.53.53.53/dns-query qType=A name=graph.instagram.com. answer=["4.78.139.50"]
```
0722 Premium 复现
