### ISSUE TITLE
Clash DNS returned both IPv4 and IPv6 addresses for double stack domain unexpectedly 

### ISSUE THREAD

**Issue by hexin-lin-1024** [Dreamacro/clash#2197]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.05.18-18-g9435cc5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
ipv6:true
```

### Description

在代码(resolver.go)中，注释写到优先返回IPv4地址，但实际上测试双栈网站时，仍会返回IPv4与IPv6的结果，导致IPv6被优先选择。
解决方案：不会Go，恕不能给出具体代码。但理论上改下ResolveIP这个函数即可；或者可以在配置文件中加入IPVersionPreference选项，如果用户指定了v4或v6则丢弃另一个结果。

**Comment by Dreamacro** [comment]
clash 有两个 ipv6 选项，一个是全局禁止访问 ipv6 ip。另一个是针对 clash 的 dns server，使其不解析 AAAA 记录

**Comment by hexin-lin-1024** [comment]
> 事实上我全部打开了两个选项，刚才又试了下，结果
![image](https://user-images.githubusercontent.com/87570146/177329993-ca9e9954-e263-4518-8e14-efafd0298de0.png)
比较神奇，但是好像有时候又能起效，根据标准，Clash若想实现IPv4记录优先，应当在有A记录时过滤AAAA记录。

**Comment by hexin-lin-1024** [comment]
> > 事实上我全部打开了两个选项，刚才又试了下，结果
> > ![image](https://user-images.githubusercontent.com/87570146/177329993-ca9e9954-e263-4518-8e14-efafd0298de0.png)
> > 比较神奇，但是好像有时候又能起效，根据标准，Clash若想实现IPv4记录优先，应当在有A记录时过滤AAAA记录。

所以我认为，关键点就在这个函数
`func (r *Resolver) ResolveIP(host string) (ip net.IP, err error) {
}`
对于Clash来说，既然程序要实现IPv4优先，这应当被视为漏洞而不是功能请求。

**Comment by Dreamacro** [comment]
```yaml
dns:
    ipv6: false
```

nslookup 的行为也不奇怪，返回 A/AAAA 请求最快的罢了

**Comment by hexin-lin-1024** [comment]
或者能否提供一个选项，让用户在双栈网站过滤掉AAAA记录，因为从RFC规定来说，客户端会先行请求AAAA记录，如果不存在再请求A记录。设置`dns:
    ipv6: false`后使纯IPv6网站也无法使用。

**Comment by hexin-lin-1024** [comment]
> ```yaml
> dns:
>     ipv6: false
> ```
> 
> nslookup 的行为也不奇怪，返回 A/AAAA 请求最快的罢了

另外如您所说，那么这个函数的这行注释是什么意思呢`// ResolveIP request with TypeA and TypeAAAA, priority return TypeA`

**Comment by hexin-lin-1024** [comment]
> 这个函数是内部调用的，不表现在其他行为里。主要是 udp 连接解析和规则解析里用

为了实现该功能（指双栈过滤IPv6），实际上我应当在哪里修改？

**Comment by hexin-lin-1024** [comment]
@Dreamacro 请您指教，我真的不知道在哪里改
