### ISSUE TITLE
[Feature] 黑白郎君添加规则后，CLASH界面失效

### ISSUE THREAD

**Issue by Davonng** [Dreamacro/clash#2200]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

黑白郎君添加规则后，CLASH界面失效
程序本身依然是运行的，尝试重启路由器，问题依旧存在
<img width="761" alt="image" src="https://user-images.githubusercontent.com/108177028/177031839-970cf30b-58bc-4887-abf2-464f7cc4c29e.png">

**Comment by Dreamacro** [comment]
与本项目没有直接联系
