### ISSUE TITLE
[Feature] 希望load-balance功能避开延迟测试不可用节点

### ISSUE THREAD

**Issue by ICEY1W32** [Dreamacro/clash#2202]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

load-balance是对全部节点生效的，如果group中有节点延迟测试不可用，仍然会被选上连接，这样就算只有一个不可用，时不时选上都很难受，目前只能手动去删除不可用节点

是不是应该调整为在测试可用的节点里面进行负载均衡才更符合实际需求？

**Comment by Dreamacro** [comment]
现在就是避开的，会参考健康检查测试的结果

**Comment by ICEY1W32** [comment]
检查了配置，应该是部分节点反复失效导致日志里面出现了不可用节点的记录
