### ISSUE TITLE
[Bug] Chrome Dashboard 进不去

### ISSUE THREAD

**Issue by AsceticBear** [Dreamacro/clash#2207]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 

### Clash version

v1.9.0

### What OS are you seeing the problem on?

Linux

### Description

![image](https://user-images.githubusercontent.com/11801722/177516753-2540b6f6-2f95-4539-b7d3-e503a5787a75.png)

Dashboard 显示无法加载，之前是可以的，最近升级了一下 Chrome，就无法正常工作了。有什么解决办法吗？

**Comment by GunKneeNeon** [comment]
我这边也进不去，之前也都是好好的，已经一个月了，升级了最新的v1.11.4问题依旧。
