### ISSUE TITLE
[Bug] 在显卡占用过高时，Clash出现“主窗口崩溃了”并处于无响应状态

### ISSUE THREAD

**Issue by chenshipei** [Dreamacro/clash#2208]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

0.19.5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
allow-lan: true
external-controller: 127.0.0.1:51064
```

### Description

在显卡占用过高时，Clash出现“主窗口崩溃了”并处于无响应状态，使得所有占用显卡的进程被杀死导致系统不稳定

**Comment by imxieke** [comment]
跑错片场了吧大哥  这是命令行版本  没有界面的 0.19 你用的应该是 clash for windows 吧？ 
你去 https://github.com/Fndroid/clash_for_windows_pkg/issues 这问问
