### ISSUE TITLE
[Feature] Premium Releases 如何订阅

### ISSUE THREAD

**Issue by ttttmr** [Dreamacro/clash#2209]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

对于普通版本可以简单的在GitHub Watch，但 Premium 并不是完全同步更新，而且 Premium Releases 是编辑，GitHub并不会有通知，有没有比较方便的可以在 Premium Releases 收到通知

### Possible Solution

有RSS订阅或者GitHub通知比较好

**Comment by imxieke** [comment]
自己脚本定时抓取不就行了么 😢 

```shell
 curl -sL https://github.com/Dreamacro/clash/releases/tag/premium | grep -E "<title>" | awk -F ' ' '{print $3}'
```
