### ISSUE TITLE
[求助] ClashX订阅后配置文件会自动更新，有没有方法能够覆盖部分更新

### ISSUE THREAD

**Issue by wyx-scottwu** [Dreamacro/clash#2210]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

订阅后的配置文件自动更新，但是默认未修改的配置文件部分代理是直连的方式，导致代理不成功，有没有方法可以覆盖着一部分配置的方法
例如
 - DOMAIN,translate.googleapis.com,🎯 全球直连

我需要它是
 - DOMAIN,translate.googleapis.com,🔰 节点选择

**Comment by BirkhoffLee** [comment]
https://github.com/yichengchen/clashX/discussions
