### ISSUE TITLE
[Feature] sniff only to dns without additional servers when enabling tls sniffing

### ISSUE THREAD

**Issue by fsheidaiee** [Dreamacro/clash#2212]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hi
when enabling tls sniffing in latest premium core, I see google dns resolver added to my dns servers.
when disabling this option the google dns resolver is gone.
please fix this feature enabling sniffing without adding additional dns servers.

### Possible Solution

sagernet and matsuri clients on android with vpn mode have sniffing without addinional dns servers involved.
thanks

**Comment by samlux04** [comment]
Oh so this is where the "DNS leaks" come from.
