### ISSUE TITLE
[Feature] 能否支持domain:port规则

### ISSUE THREAD

**Issue by aiaiwuai** [Dreamacro/clash#2215]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

实际使用中某些域名/IP的特定端口需要proxy

**Comment by LiMoon** [comment]
請問在 RULES 設定下，如何讓
目標可以設定PORT走PROXY呢？

例如
a.com
但只需要 PORT走 80，其他端口只走DIRECT？

**Comment by Dreamacro** [comment]
@LiMoon 一样是 shortcut
