### ISSUE TITLE
[Feature] 请问clash有打算支持KCPTUN吗

### ISSUE THREAD

**Issue by corn2597** [Dreamacro/clash#2219]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

如题

**Comment by BirkhoffLee** [comment]
前几年讨论过了，没有考虑支持
