### ISSUE TITLE
启用ipv6之后只会走ipv6地址

### ISSUE THREAD

**Issue by xuan880** [Dreamacro/clash#222]
v0.15.0的版本在dns设置中开启了ipv6之后如果解析的域名有ipv6地址,就只会走ipv6,如果本地网络没有ipv6地址不会回退到ipv4,导致网站无法打开,必须关闭ipv6才行,如果网络情况比较复杂的话用起来没有之前的好,
例如我的设备在宿舍有ipv6地址,在公司没有ipv6地址,我希望开启ipv6之后,优先走v6的地址,如果连接失败回退到v4进行连接.

**Comment by Dreamacro** [comment]
> 没有之前的好

意味着之前应该走的都是 v4, 如果对 v6 不是很强烈要求可以不开启 `ipv6: true`

**Comment by xuan880** [comment]
> > 没有之前的好
> 
> 意味着之前应该走的都是 v4, 如果对 v6 不是很强烈要求可以不开启 `ipv6: true`

并不是,以前的版本是如果有ipv6地址就走ipv6,没有就是ipv4,而且我想用ipv6,但是不能保证所有连接的网络都能分配到ipv6地址,所以希望有回退机制.

**Comment by Dreamacro** [comment]
现在也许解决了

**Comment by xuan880** [comment]
0.17.1的tun版本还是有这个问题,在dns开启了ipv6之后如果连接的网络没有ipv6地址,clash还是会尝试连接ipv6地址,然后不停的报错,例如连接10086官网的时候:
2020-01-10 16:37:51[warning] dial 国内路线 error: dial tcp6 [2409:8089:1020:5010:1000::12]:80: connect: network is unreachable
国内路线是我自己定义的路线,默认就是DIRECT直连.

**Comment by xuan880** [comment]
> 现在也许解决了

0.17.1的tun版本还是有这个问题,在dns开启了ipv6之后如果连接的网络没有ipv6地址,clash还是会尝试连接ipv6地址,然后不停的报错,例如连接10086官网的时候:
2020-01-10 16:37:51[warning] dial 国内路线 error: dial tcp6 [2409:8089:1020:5010:1000::12]:80: connect: network is unreachable
国内路线是我自己定义的路线,默认就是DIRECT直连.
