### ISSUE TITLE
[Feature] 关于支持TUIC

### ISSUE THREAD

**Issue by moranno** [Dreamacro/clash#2222]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

用了几天的[tuic](https://github.com/EAimTY/tuic)，用下来是一个比[hysteria](https://github.com/HyNetwork/hysteria)更具有普适性的方案。

对比[tuic](https://github.com/EAimTY/tuic)和[hysteria](https://github.com/HyNetwork/hysteria)，
hy使用自己的拥塞控制(?)可以手动设置带宽上限来暴力发包，速度更快，但对VPS不太友好，CPU跑满，IDC可能认为你ddos。
tuic使用BBR等拥塞控制，更克制，更友好，测试下来也有5-10倍的单线程提升（多线程50倍）。

希望Clash core能增加其支持。

**Comment by skill7899** [comment]
在没支持之前，你可以自已部一个tuic的客服端，开启本地socket然后用clash配一个socket的代理转向tuic。。我的hysteria就是这么干。

**Comment by betaxab** [comment]
@Dreamacro 希望能观察一下这个项目，听说使用这个项目受到GFW影响的人很少。

**Comment by EkkoG** [comment]
not stale

**Comment by skill7899** [comment]
可以用clashMeta，支持tuic
https://github.com/MetaCubeX/Clash.Meta/blob/Meta/docs/config.yaml

**Comment by gengjiawen** [comment]
not stale

**Comment by Dreamacro** [comment]
This thread will need to be discussed when the official go QUIC library is available

**Comment by hsz0707** [comment]
哈哈不过时

**Comment by Thundercup** [comment]
最近更新的tuic v5版本效果很好，希望能够支持
