### ISSUE TITLE
[help]core secret

### ISSUE THREAD

**Issue by mmjiushimm** [Dreamacro/clash#2224]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description
![image](https://user-images.githubusercontent.com/2263808/178934599-c3628797-4c37-48ea-8e8e-22e69a22eed4.png)

what does core secret stands for?
why should i generate it?
thanks in advance.

**Comment by shikkoku** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues
