### ISSUE TITLE
[Feature] 按需为 cache.db 设置文件锁

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [Dreamacro/clash#2227]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我把 clash 放在 onedrive 中运行，因为文件被占用会有这样的一条提示
![image](https://user-images.githubusercontent.com/50797982/179774553-dacf798e-a6e9-40aa-9052-576a50ed4e4a.png)
![image](https://user-images.githubusercontent.com/50797982/179773717-45b0437f-3443-4b73-be55-a0c0764d3414.png)

### Possible Solution

或许允许读取就可以解决？

**Comment by ElemenTP** [comment]
这个是存储proxygroup选项和tracing信息的数据库，要经常写入所以一直独占。建议把cache.db设置为不同步
