### ISSUE TITLE
v0.15 不启用自定义dns，代理不走ipv6？

### ISSUE THREAD

**Issue by Azureki** [Dreamacro/clash#223]
v0.14不启用自定义dns的时候，本地有ipv6地址的话，本地是用ipv6连接vps的。
v0.15只有开启了自定义dns，本地和vps才使用ipv6连接。

（搜了一下issues，似乎用ipv6的人不是很多。

**Comment by Dreamacro** [comment]
我看一下系统库看能不能自动双栈

**Comment by Dreamacro** [comment]
现在不开启自定义 dns 也是双栈的了
