### ISSUE TITLE
[Feature] Release能不能用.tar.gz打包而不是纯gzip打包

### ISSUE THREAD

**Issue by changhe3** [Dreamacro/clash#2242]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

想写个powershell script自动下载解压快写哭了，Windows上只有tar没有gzip

**Comment by ElemenTP** [comment]
考虑一下7z？

**Comment by zhongfly** [comment]
很好解决，解压前下载7zr.exe (x86) : 7-Zip console executable，调用它解压就行了

**Comment by changhe3** [comment]
我是想用Windows下运行然后在上传的。。最好的解决方法：安装wsl，用bash orz
