### ISSUE TITLE
[Feature] 能否支持一下 meta core 的 PASS 跳过策略？

### ISSUE THREAD

**Issue by 2-3-5-7** [Dreamacro/clash#2243]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

PASS跳过策略就是可以在 proxy-groups 中可手动选择 `PASS`（除了 REJECT 和 DIRECT 以外的另一个策略），即继续向下匹配规则的意思，这是 Meta core PASS 的 [场景和介绍文档](https://docs.metacubex.one/function/proxygroups/pass) 。

我个人的场景是，假定 TUN 模式必须开启，有时需要将浏览器的全部流量发给流量分析软件的代理端口，有时需要正常浏览网页，用 Clash 规则匹配 Netflix 等流媒体。

如果支持 PASS，我可以添加规则匹配浏览器的 process-name，然后手动选择是发给流量分析软件，还是 PASS 继续向下匹配流媒体规则。现在要实现就只能手动改配置文件了。

能否看看支持一下呢？

**Comment by Dreamacro** [comment]
除了 select 之外的代理组甚至是嵌套代理组遇到 PASS 都会有特别奇怪的行为，这不是个好的解决方法

**Comment by 2-3-5-7** [comment]
嗯，我理解对代码设计上影响不好，PASS 在逻辑上好像也不能算作代理的一种。

我也想过，设计一个 GUI 的 rule 开关，我可以 disable 这条规则，让其继续向下匹配。但这样是不改动就太大了。

大佬有什么好的办法吗？
