### ISSUE TITLE
[Help] use-hosts这个参数到底有啥作用

### ISSUE THREAD

**Issue by pscj** [Dreamacro/clash#2244]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

看文档描述就是fake-ip模式下会去查询域名对应的IP代替假IP，那是不是和之前的redir-host模式差不多了？ 有点搞不懂

**Comment by Dreamacro** [comment]
`redir-host` 其实是个错误的命名，不用纠结，当做这个东西不存在就行。use-hosts 是让 dns server 返回 clash `hosts` 字段里对应记录的配置。

**Comment by pscj** [comment]
又看了一下hosts的注释，这下彻底明白了
