### ISSUE TITLE
socks udp inbound 怎么打开

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#225]
看到 clash 有udp支持，但是设置了ss proxy 的 udp=true，但还是无法转发udp包，查看地址监听，发现socks并没有监听本地代理端口下的udp协议，而只有tcp的，那么所以clash的udp relay要怎么配置呢？

**Comment by Dreamacro** [comment]
socks5 的 udp 是 over tcp 的，通过数据包决定是走 tcp 还是 udp

**Comment by xjasonlyu** [comment]
这具体是什么意思呢？是需要连接的socks客户端用tcp去请求clash转发udp，然后比如用ss proxy转发出去？

但是一般socks client实现udp代理不是一般都是直接发送带socks协议头的udp请求过去，然后转发就可以了吗？

所以这样目前的clash的socks实现是不是不可以直接用来代理普通的udp转发请求了呢

**Comment by Dreamacro** [comment]
socks5 的 udp 转发也是通过 tcp 来的，只要连接端支持 socks5 的 udp 连接，就可以直接用

**Comment by xjasonlyu** [comment]
可是我用go-tun2socks连接clash是没法转发udp的，但连v2ray core是可以的。
这就有点搞不明白了_(:_」∠)_

**Comment by xjasonlyu** [comment]
socks udp 的代理不应该是

1. 客户端tcp连接发送 udp associate 请求
2. 服务端回复，并提供udp的监听地址
3. 客户端用带有协议头的udp包请求上一步返回的地址
4. 服务端验证后转发udp包

所以你说的socks udp over tcp是指第一步的请求嘛？🤔因为实际上中转的话都是走udp的啊

**Comment by Dreamacro** [comment]
是的，剩下的应该没什么问题。有什么方便的测试 socks5 udp 的工具吗

**Comment by xjasonlyu** [comment]
我去测试一下，网上现成的测试socks udp的工具好像没有找到。

**Comment by xjasonlyu** [comment]
我测试了一下，问题应该是出在`clash`的`tcp`答复上面
根据 socks5 [rfc1928](https://tools.ietf.org/html/rfc1928) 文档中的说法
```
+----+-----+-------+------+----------+----------+
|VER | REP |  RSV  | ATYP | BND.ADDR | BND.PORT |
+----+-----+-------+------+----------+----------+
| 1  |  1  | X'00' |  1   | Variable |    2     |
+----+-----+-------+------+----------+----------+
o  BND.ADDR       server bound address
o  BND.PORT       server bound port in network octet order
```
`socks5 server`是应该要返回`bind address`的（貌似tcp relay时这段不重要，可以直接全部返回0，因为client直连socks tcp监听地址就可以了，但`udp associate`是需要这个地址来确定连接的）

比如以`v2ray`的`socks udp associate`为例，`client<-->server`之间的`tcp`对话是
```
>>> b'\x05\x01\x00'
<<< b'\x05\x00'
>>> b'\x05\x03\x00\x01\x01\x01\x01\x01\x00\x00'
<<< b'\x05\x00\x00\x01\x7f\x00\x00\x01\x04='  # socks server 返回了 client 需要连接的udp地址端口
```

而`clash`的`udp associate`返回是
```
>>> b'\x05\x01\x00'
<<< b'\x05\x00'
>>> b'\x05\x03\x00\x01\x01\x01\x01\x01\x00\x00'
<<< b'\x05\x00\x00\x01\x00\x00\x00\x00\x00\x00' # clash 返回的全部为0了，所以client就无法知道具体的连接地址了
```
PS: `clash core`用的最新的`Pre-release 0.15.0`版本

**Comment by Dreamacro** [comment]
@xjasonlyu 感谢发现问题，我看看怎么修比较合适

**Comment by xjasonlyu** [comment]
问题应该是在这代码上
https://github.com/Dreamacro/clash/blob/34338e7107c1868124f8aab2446f6b71c9b0640f/component/socks5/socks5.go#L152
这里应该要做一个判断
1. 如果是`CONNECT X'01'`命令的话，`bind address`应该返回`clash socks`监听的地址。（虽然单纯的tcp relay可以不需要，因为有些客户端会直接忽略）
2. 如果是`UDP ASSOCIATE X'03'`命令的话，`bind address`就必须返回建立的`udp listener`监听的地址了。

这里有个建议就是`clash`直接在`config`上配置`udp`是否开启的选项就可以了，这样也不需要每次有`udp associate`的请求就每次创建一个`udp listener`，而是直接在`tcp`答复那个环节返回预先建立好的udp地址就可以了。

**Comment by Dreamacro** [comment]
`udp: true` 在代理上的考虑是，并不是所有的代理节点都支持 udp 代理，所有如果全局设定的话可能由于规则匹配的问题，最后请求了不支持 udp 的节点。

至于 bind 的问题，我这边看看怎么处理合适

**Comment by xjasonlyu** [comment]
1. 
`udp: true`这个全局选项是可以的，因为如果代理支持`udp`转发的话，就直接通过这个代理转发`udp`，如果代理不支持的话，就直接`Reject`忽略掉就可以了。以上的效果是和现在的针对不同代理选择是否转发`udp`的结果是一样的，就是如果代理支持`udp`，那么转发，否则不转发。

其实话说回来，这个逻辑不应该是`代理是否支持udp转发`，而是`inbound socks`作为一个`socks server`，它是否支持`udp`转发，而至于最后转发成功与否是`outbound`代理的事情了，就不归`inbound`管了。（代理是否支持应该只是作为`socks server`一个判断是需要继续下去的`flag`）

~~（其实有个复杂的方案就是`config`配置`udp`转发直接全局开启并监听端口，然后代理节点上配置是否支持`udp`，之后再在`socks handshake`那里做判断，如果目前策略里的代理支持`udp`转发的，那就回复`X'00' succeeded`，如果不支持的话就返回`X'07' Command not supported`。）~~

2. 
bind其实有一个比较tricky的问题，因为如果`clash`的`allow-lan: false`那其实只要返回`127.0.0.1:port`这样的`bind address`就可以了，这个情况下很简单没有问题。但是如果`allow-lan: true`的话，那么倘若返回`0.0.0.0:port`，有些client会使用`socks server`的地址来代替这个`0.0.0.0`成功发送udp包，但又有些client会直接拿这个`0.0.0.0:port`来创建`udp socket`结果就error了。

这个`v2ray`的解决办法是配置一个`socks udp address`，它默认为`127.0.0.1`，但如果需要为lan开启的话，可以手动设置成比如`192.168.1.2`之类的自己的lan地址（仅供参考）。

3.
这个没有问题，但正如`1`中提到的，`全局udp`配置实现起来逻辑似乎更好一些，而且也不需要频繁建立udp监听。再而且倘若是`allow-lan: true`，并且主机有防火墙，那么如果每次`udp`监听的端口都不一样的话那肯定是没发转发其他地址的`udp`的，所以这也是另一个好处为什么最好配置里`udp`直接全局创建监听了。

**Comment by Dreamacro** [comment]
1. inbound 肯定是一直开着的不需要设置是否开启，`udp: true` 只是识别代理是否支持 udp, 没有好的方法主动得知代理是否支持 udp

2. 没太看懂，client 连接一般不会指定端口，一般是自动分配一个，所以不太可能出现重复使用的情况

**Comment by xjasonlyu** [comment]
1. 代理后面的`udp=true`这个选项的确是最好的方法来确定是否支持转发的了。你说`inbound`的udp转发是一直开启的吗？可是我`lsof socks-port`并没有看到udp端口在监听啊（我觉得还是全局配置一个enable-udp的选项比较好啦，这样比较逻辑清晰`socks server`到底需不需要监听一个udp端口）

2. 这个不是说client指不指定端口，而是在`allow-lan=true`的情况下，server返回的要让client连接的ip地址应该是server的lan地址而不是`localhost`或者`0.0.0.0`，这是一个需要注意的地方。（这个bind地址是指server的udp监听地址啊，这个跟client没有关系，client udp连接过去的地址当然是系统随机分配的）

**Comment by xjasonlyu** [comment]
发现这里还有一个问题，目前的实现里，这个`conn`是个`tcp conn`，但显然最后的`udp relay`是全部走udp的，所以这个`udpOverTcp`的说法也是不对的。

https://github.com/Dreamacro/clash/blob/34338e7107c1868124f8aab2446f6b71c9b0640f/proxy/socks/tcp.go#L65

https://github.com/Dreamacro/clash/blob/34338e7107c1868124f8aab2446f6b71c9b0640f/tunnel/connection.go#L71

**Comment by xjasonlyu** [comment]
Fixed in https://github.com/Dreamacro/clash/pull/233
