### ISSUE TITLE
[Feature] 能不能针对通过127.0.0.1:7890主动代理的程序 进行全局代理或者单独的代理策略

### ISSUE THREAD

**Issue by threerog** [Dreamacro/clash#2254]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

原issues地址:https://github.com/Fndroid/clash_for_windows_pkg/issues/3291

**Comment by threerog** [comment]
我是Shadowsocks转过来的新手，之前没有遇到类似问题，只要是主动代理到Shadowsocks的程序或者请求都是走vpn代理

**Comment by akw5454521** [comment]
- SRC-PORT,7777,DIRECT
用这个规则

**Comment by Lemmingh** [comment]
`SRC-PORT` 是匹配 source endpoint port。

而这个 issue 谈的是 proxy port。

不是一个东西。

**Comment by Lemmingh** [comment]
这个想法可以表述为：

* 设置多个端口，分别指定不同的策略。

* Multiple proxy inbound ports with different policies.

已经有很多人提过了。(#2001)

作者的回应大致为：

* 意义不明。(<https://github.com/Dreamacro/clash/issues/306#issuecomment-572486870>)

* 试试 [Premium](<https://github.com/Dreamacro/clash/wiki/premium-core-features>) 的 Script mode。

* 仔细写 [rule](<https://github.com/Dreamacro/clash/wiki/configuration>)。

---

我也不理解你的想法。这好像是部署机场时才会有的需求。出现在客户端上恐怕是徒增复杂度。

如果你的需求 **真的** 无法用 rule 解决，必须区分 proxy port，不妨考虑 [V2Ray](<https://www.v2fly.org/>)，利用 `InboundObject` 的 `tag`。

---

你用代理上网是 **你** 用代理上网，跟代理用什么上网没关系。它可以就地直连，可以发给另一个代理，也可以是死胡同。

发给 Clash 的东西会流向哪里，取决于 **你写的 rule**。

如果这个概念很难理解，想想企业里的出站防火墙。

**Comment by threerog** [comment]
> 

假设目标程序名称不固定且有很多子程序进程，ip地址动态变化不知道具体信息或域名的情况下 如何配置rule

**Comment by Lemmingh** [comment]
你这一段等价于“毫无特征”。没法写。

**Comment by z-x-f** [comment]
surge有个in-port和src-ip搭配就很好用

**Comment by BirkhoffLee** [comment]
Clash 单一实例的 inbound 都是走到一起的，建议多开一个实例专门用这个用途

**Comment by firefrog321** [comment]
同遇到这个问题，python爬虫想通过代理分担一点请求，降低本机ip请求国内网址速率。但是软件还是使用了rule，强制用本机ip去请求国内网址，不使用代理。v2rayn没有这个问题
