### ISSUE TITLE
开启代理后Windows的etc设置全部失效

### ISSUE THREAD

**Issue by winbug** [Dreamacro/clash#2256]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

打开代理后，
windows目录下的etc文件
所有设置的
127.0.0.1 xxx.com
127.0.0.1 xxxx.net
之类的设置全部失效，都可以访问了。
请问如何解决？

**Comment by wx00** [comment]
如有启用 dns 功能，在配置文件 `dns` 部分可以设置 `use-hosts: true` ：
```
# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  use-hosts: true # lookup hosts and return IP record
```

如未启用 dns 功能，可考虑将 hosts 文件内容写到配置文件 `hosts` 部分：
```
# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'
```

以上功能我都没用过，不确定效果。

如果是为了阻止访问对应域名，也可以在 `rules` 部分设置对应域名的规则：
```
rules:
  - blabla
  - DOMAIN,ad.example.com,REJECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - blabla
```

配置文件说明见 [wiki-configuration](https://github.com/Dreamacro/clash/wiki/configuration)

**Comment by Lemmingh** [comment]
> 打开代理后
>
> 都可以访问了

由该描述可以推测，在当前设置的规则 (rule) 下，Clash 判定这些域名要走代理。（不妨查日志以检验这个猜想。）

所以，解决该问题必须改动 rule。

若要阻止访问域名（及子域），出于性能考虑，宜 **头插** 匹配 `DOMAIN-SUFFIX` 的 `REJECT` rule。

---

Clash 中的 DNS 解析有 2 个基本用途：

* 给 IP rule 提供匹配参考值。

* 在直连 (`DIRECT`) 时确定目标 IP。

当 Clash DNS server 关闭时 (`dns.enable: false`)，Clash 使用操作系统的 DNS （在 Windows 下，即 Windows DNS client）。

总之，Clash 中的 DNS 解析仅用于判定。

通过代理连网时，真正的 DNS 解析发生在远端（代理服务器）。

---

> etc 文件

Hosts 文件 (`%SystemRoot%\System32\drivers\etc\hosts`) 实际上是向 Windows DNS client cache 中加入不会过期的记录。

本地的 cache 自然无法影响远端的 DNS。

---

Clash config 中的 `hosts` 与 `dns.use-hosts` 是配套使用的，与操作系统的 Hosts 无关。

<https://github.com/Dreamacro/clash/blob/8c7c8f43741923d6a7650dc723b4b51b0f540777/config/config.go#L630-L632>
