### ISSUE TITLE
[Feature] 禁用Clash的DNS缓存

### ISSUE THREAD

**Issue by devioa** [Dreamacro/clash#2257]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

已经有本地DNS服务器缓存查询结果了，测了下Clash内核似乎还是使用的Optimistic DNS机制，请问可以禁用吗？

**Comment by cjwddtc** [comment]
你本地不要缓存查询结果，会干扰到clash的域名规则吧。。。

**Comment by devioa** [comment]
> 你本地不要缓存查询结果，会干扰到clash的域名规则吧。。。

你没审明白我的意思
我现在是一个嵌套多DNS服务查询链路的环境，DNSMASQ(53)→AdGuardHome(5360)→Clash(1053)→SmartDNS(6053)→namerserver分组规则避免污染→通过多个上级DoH解析
我的意思是Clash的上级已经有smartdns去查询并缓存结果了，Clash收到下级adguardhome域名查询请求只需要转发给smartdns然后等待返回值即可，现在smartdns缓存了，Clash也缓存，在一些情况下会返回错误的A记录，导致网页加载变慢或者访问异常

**Comment by devioa** [comment]
> 你本地不要缓存查询结果，会干扰到clash的域名规则吧。。。

而且域名规则只有在Clash Internal DNS完全被禁用的情况下才会失效（只有IPCDR有效），这个我也是已经测试过的
