### ISSUE TITLE
[Feature] TUN 模式下使用 fake-ip 访问 IPv6 地址

### ISSUE THREAD

**Issue by slusludy** [Dreamacro/clash#2258]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

TUN 网络接口只有 IPv4，无法打开像 https://[2606:4700:4700::1111]/ 的这种域名是 IPv6 地址的网站（这无伤大雅），也无法 ssh 登录只有 IPv6 而没有 IPv4 的 VPS。
在 TUN 模式下登录只有 IPv6 的 VPS 的方法之一是到 DNS 服务商网站建立一条解析到 VPS 的 IPv6 的 DNS 记录，使用这个域名来登录 ssh，从而登录时 Clash 会给 ssh 返回 IPv4 的 fake-ip，可以成功登录。
但也有一些问题

- 每次 ssh 登录时域名都会被 Clash 解析到不同的 fake-ip，导致每次登录时 ~/.ssh/known_hosts 都会对不同的 fake-ip 新增一条公钥记录。可以让 `profile.store-fake-ip` 为 `true` 来解决这个问题。

- 要新建 DNS 记录。

### Possible Solution

在 Clash 的配置文件的 `hosts` 新建一个将域名解析到 VPS 的 IPv6 的条目，在 TUN 模式下每次访问这个域名时 Clash 都返回同一个 IPv4 fake-ip。

**Comment by rockyzhng** [comment]
呼吁clash的tun支持IPv6

**Comment by slusludy** [comment]
在 VPS 的 hosts 文件而非 DNS 服务商，将 VPS 的 IPv6 解析到我控制的域名，这样也能在 TUN 模式用域名 ssh 登录只有 IPv6 的 VPS
