### ISSUE TITLE
[Bug] mode从rule改为global之后，油管无法访问

### ISSUE THREAD

**Issue by none2003** [Dreamacro/clash#2263]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.11.4

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7891
socks-port: 7890
allow-lan: true
mode: global
log-level: debug
external-controller: :9090
proxies:
  ...
proxy-groups:
  ...
rules:
  ...
```

### Clash log

```shell
time="2022-08-12T22:41:16+08:00" level=warning msg="[TCP] dial GLOBAL to www.youtube.com:443 error: dial tcp4 172.217.163.46:443: i/o timeout"
time="2022-08-12T22:41:21+08:00" level=warning msg="[TCP] dial GLOBAL to www.youtube.com:443 error: dial tcp4 172.217.160.110:443: i/o timeout"
time="2022-08-12T22:41:26+08:00" level=warning msg="[TCP] dial GLOBAL to www.youtube.com:443 error: dial tcp4 142.251.42.238:443: i/o timeout"
```

### Description

订阅规则：ACL4SSR_Online 默认版

直接用"clash-windows-amd64.exe -f config.yaml"执行的

先在config.yaml里设置为规则模式，油管可以正常访问
time="2022-08-12T22:35:02+08:00" level=info msg="[TCP] 127.0.0.1:9230 --> youtube.com:443 match DomainKeyword(youtube) using 🌍 国外媒体[XXXXXXX]"
time="2022-08-12T22:35:07+08:00" level=info msg="[TCP] 127.0.0.1:9240 --> [www.youtube.com:443](http://www.youtube.com:443/) match DomainKeyword(youtube) using 🌍 国外媒体[XXXXXXX]"

接着将配置文件里面的mode改为Global，发现油管不能访问了，给出了前面的timeout的报错。

如果需要更多日志请reply，谢谢。

**Comment by qist** [comment]
Global 模式你用的是DIRECT的把。

**Comment by marsoyang1** [comment]
我也是 一样，只要是开global模式，就一直连接超时，有什么解决办法吗

**Comment by marsoyang1** [comment]
我也是 一样，只要是开global模式，就一直连接超时，有什么解决办法吗
