### ISSUE TITLE
[Feature] 能否指定，所有 clash 在运行中产生文件的位置

### ISSUE THREAD

**Issue by paomian** [Dreamacro/clash#2267]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

比如 
* provider.yaml
* cache.db
* Country.mmdb

按照 linux 设计惯例，程序的配置文件和运行需要的缓存等文件是需要不同的权限的，比如大部分软件的运行中产生的文件都是写在 /var 文件夹下，是否 clash 也可以支持指定运行时产生文件的位置。因为和配置文件在同一文件夹下，我不是很容易的把配置放在一个需要较高文件权限的文件夹且同时使用一个较低权限的用于去运行 clash 这样会导致运行时文件无法写入

### Possible Solution

增加新的选项来指定这些文件的位置

**Comment by Dreamacro** [comment]
`clash -d path`
