### ISSUE TITLE
具体要怎么做才可以让clash获取到订阅节点的流量和日期的信息

### ISSUE THREAD

**Issue by iloccc** [Dreamacro/clash#2269]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

请问服务器怎么配置才可以实现订阅或者节点在clash客户端上显示流量和过期日期等信息？
看资料说在响应头添加subscription-userinfo就可以了，但这个具体应该怎么样加呢，我没有明白。
图中2,3订阅可以显示信息，1却不行，应该怎么做？感谢解答！
![捕获](https://user-images.githubusercontent.com/110537486/185781245-f4631d01-36af-4ed7-91d6-f5bbff8dc187.PNG)

**Comment by Lemmingh** [comment]
https://github.com/crossutility/Quantumult/blob/master/extra-subscription-feature.md
