### ISSUE TITLE
规则支持是否支持USER-AGENT这种写法？

### ISSUE THREAD

**Issue by wangxin6** [Dreamacro/clash#227]
比如：

- USER-AGENT,*YouTubeMusic*,Music
- USER-AGENT,*com.google.ios.youtubemusic*,Music

**Comment by Dreamacro** [comment]
目前没有的，USER-AGENT 要支持的话必须开启 MIMT，否则对于 HTTPS 请求根本拿不到 USER-AGENT，目前并没有做 MIMT 的打算。

**Comment by soffchen** [comment]
HTTPS 的时候 User-Agent 字段应该还是可以看到的，不需要 MITM 哦

```
CONNECT ip.cn:443 HTTP/1.1
Host: ip.cn:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3860.5 Safari/537.36
```

再往下才是加密的

麻烦加这个功能，要不 YouTube Premium 光靠域名规则经常不够有效 :(

**Comment by Synchronized1** [comment]
希望能添加这种USER-AGENT写法...YouTube总是匹配不够全

**Comment by HugeDicks** [comment]
> HTTPS 的时候 User-Agent 字段应该还是可以看到的，不需要 MITM 哦
> 
> ```
> CONNECT ip.cn:443 HTTP/1.1
> Host: ip.cn:443
> Proxy-Connection: keep-alive
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3860.5 Safari/537.36
> ```
> 
> 再往下才是加密的
> 
> 麻烦加这个功能，要不 YouTube Premium 光靠域名规则经常不够有效 :(

你这是用的http inbound吧？如果是socks5 inbound就看不到了。
HTTPS的USER-AGENT字段不是明文，你抓到的这个是http proxy通讯的http header里的。
两个USER-AGENT是可以不同的。
