### ISSUE TITLE
[Feature] Add log file option and log rotation

### ISSUE THREAD

**Issue by kevinniu666** [Dreamacro/clash#2272]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Please help to add configuration for log file. e.g.
clash -f config.yaml -l /var/log/clash.log

### Possible Solution

It will be great if log rotation is supported as well.

**Comment by BirkhoffLee** [comment]
You're supposed to redirect log to syslog and use logrotate for this, my best guess this is wontfix
