### ISSUE TITLE
[Feature] 能否添加redir-port的ipv6支持

### ISSUE THREAD

**Issue by ghost** [Dreamacro/clash#2273]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

现在ipv6越来越普及，clash的redir-port目前还仅支持ipv4，能否添加ipv6的支持？

### Possible Solution

 实现起来并不复杂，我试了下，补丁如下
[diff.txt](https://github.com/Dreamacro/clash/files/9411778/diff.txt)

git apply diff.txt

在linux中测试，可以使redir-port支持ipv6

**Comment by BirkhoffLee** [comment]
實現了的話可以發 pull request，d7o 會 review 的

**Comment by nilxbit** [comment]
@BirkhoffLee  问题是我只修改了linux的代码，其他系统mac,freebsd 我没设备，没办法修改，还是希望作者增强一下clash对ipv6的支持，毕竟ipv6已经很普及了

**Comment by BirkhoffLee** [comment]
之后 redir-port 要弃用了，估计不会再加新功能了 😢

**Comment by nilxbit** [comment]
@BirkhoffLee  redir-port 要弃用了？？那以后透明代理岂不是只能用 tproxy-port 了，既然这样，这个issue我关闭了

**Comment by BirkhoffLee** [comment]
哇，我看错了。我是指 redir-host 要弃用了 😵‍💫 不好意思。我帮你 reopen
