### ISSUE TITLE
[Question] 安装过程中出现这个问题不会解决

### ISSUE THREAD

**Issue by KevinChan1024** [Dreamacro/clash#2275]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

![image](https://user-images.githubusercontent.com/49362487/186618929-c3489dcd-4e65-4b92-a5da-f5bee20f2a52.png)

**Comment by 786259135** [comment]
7890端口被占用，7891、7892无权限。开了多个客户端？

**Comment by KevinChan1024** [comment]
> 

恩，用虚拟机的。现在这个问题已经解决了。不过又出现新问题了。
![image](https://user-images.githubusercontent.com/49362487/186641871-9ddda696-a3e8-456f-bc47-362f79306c27.png)
这样搞好后，登不上外国网站，国内网站可以登

**Comment by BirkhoffLee** [comment]
發一下配置跟 `curl -v https://google.com` 的結果
