### ISSUE TITLE
编译 clash 1.11.8 需要 go >= 1.19  

### ISSUE THREAD

**Issue by Linerre** [Dreamacro/clash#2278]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash 1.11.4

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
和编译 clash 1.11.8 有关，故没有 clash config
```

### Description

我在 Gentoo 上编译安装了 clash 1.11.4, 这几天升级到 1.11.8 时，用 go 1.18.5 编译报错：

```
cd /var/tmp/portage/net-proxy/clash-1.11.8/work/clash-1.11.8                           
/usr/lib/go/pkg/tool/linux_amd64/compile -o $WORK/b224/_pkg_.a -trimpath "/var/tmp/portage/
net-proxy/clash-1.11.8/work/clash-1.11.8/component/process=>github.com/Dreamacro/clash/comp
onent/process;$WORK/b224=>" -p github.com/Dreamacro/clash/component/process -lang=go1.18 -c
omplete -buildid TFXbXWU-gOewXjsDyzE5/TFXbXWU-gOewXjsDyzE5 -goversion go1.18.5 -c=4 -noloca
limports -importcfg $WORK/b224/importcfg -pack ./component/process/process.go ./component/p
rocess/process_linux.go                                                                    
# github.com/Dreamacro/clash/component/process                                             
component/process/process_linux.go:169:16: undefined: fmt.Appendf 
```

这个 fmt.Appendf 应该是 go 1.19 提供的，我用 go 1.19 编译 clash 1.11.8 就没问题

**Comment by Dreamacro** [comment]
对的，需要 latest 的 go

**Comment by Linerre** [comment]
好的，我去给打包的人说一声，感谢～

**Comment by z760087139** [comment]
wiki 上写的是1.18，需要同步更新
https://github.com/Dreamacro/clash/wiki#getting-started
