### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by wangxin6** [Dreamacro/clash#228]
使用最新的release版本中的DNS fake-ip模式。在日志文件中会发现以下警告信息：

`time="2019-07-05T14:35:14Z" level=warning msg="Proxy[DIRECT] connect [10.0.1.179 --> 198.18.0.34] error: dial tcp 198.18.0.34:80: i/o timeout"`

`time="2019-07-05T14:35:06Z" level=warning msg="Proxy[DIRECT] connect [10.0.1.179 --> 198.18.0.40] error: dial tcp 198.18.0.40:443: i/o timeout"`

**Comment by wangxin6** [comment]
类似的一些错误：
`time="2019-07-05T17:29:35Z" level=warning msg="Proxy[DIRECT] connect [10.0.1.123 --> 198.18.0.91] error: dial tcp 198.18.0.91:10091: i/o timeout"`

**Comment by xjasonlyu** [comment]
这个可能是你客户端DNS缓存没有及时更新，clash的fake-ip模式已经把ttl设置为1了。（跟i/o没关系，解析不出来原域名你也没法连）

**Comment by wangxin6** [comment]
80/443不用说，10091是我VPS的端口。应该和客户端DNS缓存无关。

**Comment by xjasonlyu** [comment]
这个跟端口没有关系，是你的请求地址（即fake-ip）无法被IPToHost函数解析回原来的请求地址。

**Comment by wangxin6** [comment]
> 这个跟端口没有关系，是你的请求地址（即fake-ip）无法被IPToHost函数解析回原来的请求地址。
换句话就是正常的反馈。不用理睬？

**Comment by xjasonlyu** [comment]
并不是，是clash的DNS缓存里没有解析这个fake-ip的记录，所以你应该是客户端DNS没有刷新。

**Comment by wangxin6** [comment]
那么我应该怎么做呢？

**Comment by xjasonlyu** [comment]
使用最新的clash，确保ttl是1，上述都确认过之后，检查相应的客户端是不是有cache之类的忽略ttl的机制，关掉它。差不多就这样了，你没有具体说清楚是什么客户端，没法具体说明。

**Comment by wangxin6** [comment]
最新的clash - Yes.
确保ttl是1 - How?

我现在的使用场景是：路由器使用clash番茄，规则定义SRC-IP-CIDR bypass FireStick IP，FireStick安装SS番茄。这样在路由器的日志里面就会看到类似警告：
`time="2019-07-05T17:29:35Z" level=warning msg="Proxy[DIRECT] connect [10.0.1.123 --> 198.18.0.91] error: dial tcp 198.18.0.91:10091: i/o timeout"`

其中10.0.1.123是firestick ip， 10091是VPS端口。

**Comment by xjasonlyu** [comment]
看你这个像是客户端试图去连接VPS然后clash的DNS cache没有这条fake-ip record。你试一下别用vps的域名，直接用ip应该就好了。

**Comment by wangxin6** [comment]
fake-ip模式下，无法更新geoip文件

日志如下：

... --2019-07-09 21:59:17--  https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
Resolving geolite.maxmind.com... 198.18.0.2, 198.18.0.1
Connecting to geolite.maxmind.com|198.18.0.2|:443...

**Comment by SukkaW** [comment]
我认为可能是 Clash 把节点域名解析到了 Fake IP，出现这种情况的原因可能是 DNS 回环、或者 Clash 接管了整个设备的 DNS。

**Comment by xjasonlyu** [comment]
> 我认为可能是 Clash 把节点域名解析到了 Fake IP，出现这种情况的原因可能是 DNS 回环、或者 Clash 接管了整个设备的 DNS。

Clash是不会修改系统DNS的，所以不可能主动接管DNS，可能是客户端哪里配置错了？

**Comment by SukkaW** [comment]
@xjasonlyu 

```
dial tcp 198.18.0.91:10091: i/o timeout
```

你看他日志里，连 Fake IP 的是 10091 端口。正常的 Web Application 哪里会用 10091 端口？所以首先可以肯定节点域名指向 Fake IP 了。至于他怎么配出来就没必要关心了，他自己又不交代什么系统什么设备。

**Comment by xjasonlyu** [comment]
@SukkaW 嗯，这个应该不算是 clash core 的问题，这个 issue 也可以 close 了。

**Comment by wangxin6** [comment]
ClashX，使用GEOIP规则模式。在safari里输入微信网页版<wx.qq.com>失败。查看日志可以看到对 443 端口 timeout

2019/08/13 13:07:33:718  [info] 127.0.0.1 --> js.aq.qq.com match GEOIP using DIRECT
2019/08/13 13:07:38:721  [warning] Proxy[DIRECT] connect [127.0.0.1 --> js.aq.qq.com] error: dial tcp 182.254.76.118:443: i/o timeout

**Comment by Dreamacro** [comment]
@wangxin6  在我的机器上正常, 无法复现

**Comment by wangxin6** [comment]
具体的表现是网页无法加载二维码。必须退出clashX，二维码才能加载成功。登录以后，使用clashX没有问题。

**Comment by Dreamacro** [comment]
@wangxin6 是不是在什么特殊的网络环境下，vpn 或者什么其他影响解析的东西

**Comment by wangxin6** [comment]
类似的一个问题。访问网页版微信<wx.qq.com>，浏览器访问到res.wx.qq.com无法响应，导致二维码无法加载，但是log上看不出问题。关掉clashX或者直连后，问题解决。

2019/08/21 09:01:26:325  [info] 127.0.0.1 --> wx.qq.com match GEOIP using DIRECT
2019/08/21 09:01:27:187  [info] 127.0.0.1 --> res.wx.qq.com match GEOIP using DIRECT

**Comment by coulis1018** [comment]
我的也有这个问题，发现凡是打开带qq.com的地址，日志里都会打印出timeout，有些网页能打开，有些现实连接已被重置

**Comment by asdf12303116** [comment]
同样问题，wx.qq.com稳定复现， 
环境 linux  iptables 转发所有流量至clash, 转发dns至clash
访问wx.qq.com时出现问题，正常使用时还有个别网页也会触发.
日志如下

level=info msg="192.168.0.113 --> 183.61.49.164 match GEOIP using Domestic"                                                                   
level=info msg="192.168.0.113 --> 183.61.49.164 match GEOIP using Domestic"                                                                   
level=info msg="192.168.0.113 --> 183.61.49.164 match GEOIP using Domestic"                                                                   
level=info msg="192.168.0.113 --> 58.205.214.142 match GEOIP using Domestic"                                                                  
level=info msg="192.168.0.113 --> 220.194.223.79 match GEOIP using Domestic"                                                                  
level=warning msg="Proxy[Domestic] connect [192.168.0.113 --> wx.qq.com] error: dial tcp 182.254.78.160:443: i/o timeout"
level=info msg="192.168.0.113 --> wx.qq.com match DomainSuffix using Domestic"

**Comment by wangxin6** [comment]
不再复现
