### ISSUE TITLE
[Feature] Support TCP inbound for Clash DNS server

### ISSUE THREAD

**Issue by findlayfeng** [Dreamacro/clash#2280]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

dns其实是udp/tcp双协议的，本地服务器却只支持udp。

**Comment by itKelis** [comment]
clash的dns支持tcp，这是你的dns服务器问题

**Comment by findlayfeng** [comment]
我描述的可能有问题，不是支持远端dns的tcp，是支持监听本地的53/tcp端口，我大致翻了一下源代码，的确只监听了 udp

**Comment by findlayfeng** [comment]
[	udpAddr, err := net.ResolveUDPAddr("udp", addr)](https://github.com/Dreamacro/clash/blob/425b6e0dc098535874a29ccc45a5c5ebece324ce/dns/server.go#L79)
@itKelis

**Comment by findlayfeng** [comment]
@BirkhoffLee 请重开一下问题，该问题没有得到解决
