### ISSUE TITLE
[Question] 有没有可能让国内的ipv6绕过代理？

### ISSUE THREAD

**Issue by zeuszc** [Dreamacro/clash#2283]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前ipv6的支持还是不太好，一打开一堆ipv6的网站就打不开了(连ipv6 test都打不开)
实在不知道有没有办法，能不能干脆多一个功能，把ipv6的都绕过代理呢？

**Comment by Karmylr** [comment]
这不是clash该干的，是iptables该干的吧

**Comment by zouyq** [comment]
参考OpenClash的实现
