### ISSUE TITLE
[Question] 双WAN口怎么指定默认走某一个WAN口

### ISSUE THREAD

**Issue by netboy2008** [Dreamacro/clash#2286]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

路由器是双WAN上行，一个是电信、一个是移动，正常开启，没有什么问题，使用clash后，是否可以定义出接口为某一个wan口啊

**Comment by netboy2008** [comment]
对了，安装了妙妙呜的双wan脚本，来区分不动目的自动走不同的接口

**Comment by BirkhoffLee** [comment]
`interface-name`
