### ISSUE TITLE
网络有限制，但是为什么测速却有显示呢？

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#229]
因为护网，我司把除了443之外的端口都封闭了，按理说非443的都用不了了，实际测试也是用不了的，但为什么测速却都有速度显示而不是fail呢？？

**Comment by Dreamacro** [comment]
如果你的节点都是 443 端口的话，这没什么毛病吧

**Comment by tony1016** [comment]
都是机场买的，显然都不是啊😯，只有一个我自建的可用的是443

Dreamacro <notifications@github.com> 于 2019年7月9日周二 上午11:56写道：

**Comment by Dreamacro** [comment]
那我就不知道你是怎么确定被封锁的了，我就正常的 dial tcp 而已

**Comment by tony1016** [comment]
Ok，让我再做一些测试吧。我们使用了一款上网控制设备来控制只能访问80和443。

Dreamacro <notifications@github.com> 于 2019年7月9日周二 下午12:29写道：

**Comment by tony1016** [comment]
> 那我就不知道你是怎么确定被封锁的了，我就正常的 dial tcp 而已

```
* transfer closed with outstanding read data remaining
* stopped the pause stream!
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

感觉应该是返回200后，流被中断了，确实不是软件问题
