### ISSUE TITLE
About the problem of 'cannot execute binary file: Exec format error'

### ISSUE THREAD

**Issue by olliecheung** [Dreamacro/clash#2294]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [ ]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-amd64-2022.08.26.gz, clash-linux-amd64-2022.07.07.gz

### What OS are you seeing the problem on?

Ubuntu 22.04.1 LTS 64bit

### Clash config

```yaml
root@admin:/usr/local/bin# clash
bash: /usr/local/bin/clash: cannot execute binary file: Exec format error
```

### Description

Hi Dreamacro,

Actually, I don't think that it is a bug, but it might have been tampered by somebody.

I'm using Clash-premium now, the version of which is clash-linux-amd64-2022.07.07.

Today I wanted to upgrade Clash-premium to version 2022.08.26, only to find that problem when I executed the binary file. The problem was 'cannot execute binary file: Exec format error'.

Then I downloaded the program of version 2022.07.07 from your website again,  but the problem remained the same.

Finally, I tried another method, that is, I used the version 2022.07.07, which I backuped in my computer the other day. The problem didn't appear.

Would you please check whether there are any problems with the programs offered on your website?

**Comment by Dreamacro** [comment]
Cannot be reproduced in debian

**Comment by olliecheung** [comment]
> Cannot be reproduced in debian

Dreamacro, 
您的意思是新版本不支持在Ubuntu内运行吗？
或者这个问题应该怎么解决呢？
谢谢！

**Comment by Dreamacro** [comment]
Ubuntu 20 测试没有问题，建议重新下载

**Comment by olliecheung** [comment]
> Ubuntu 20 测试没有问题，建议重新下载

Hi Dreamacro,
题述问题已经解决，在重新下载后。
感谢您的回复！
