### ISSUE TITLE
socks5 协议测速不显示

### ISSUE THREAD

**Issue by tingxueren** [Dreamacro/clash#23]
如题，socks5 协议进行 speed test 时无显示，实际使用没有问题。
优先级比较低，有空的时候辛苦排期进行修复。

感谢您开发的软件。

**Comment by Dreamacro** [comment]
我这里是可以对 `socks5` 这种类型用 API 进行测速的，你所说的应该是 GUI 不会对 `socks5` 测速吧，你可以找对应的 GUI 开发提 issue。

如果还有问题可以在这下面留言，我先 close 了。

**Comment by tingxueren** [comment]
多谢，我区GUI开发那边提下 issue
