### ISSUE TITLE
能否支持pac代理类型？

### ISSUE THREAD

**Issue by kery** [Dreamacro/clash#230]
类似SwitchyOmega的PAC profile。有了这个功能就可以继承PAC脚本里的规则了。

使用场景：
公司里原本使用PAC脚本里的规则访问网络。在使用clash后，流量先根据clash里的规则路由，剩余的流量根据PAC脚本里的规则路由。如：
Proxy:
    - name: pac
      type: pac
      url: http://xxx.xxx/proxy.pac (or file://path/proxy.pac)

Rule:
    DOMAIN-KEYWORD,google,SS
    MATCH,pac

没有这个功能的话，需要自己手动把PAC脚本里的规则翻译成clash的规则。如果PAC脚本经常更新，翻译起来会比较麻烦。

当然实现细节以及使用方式还有待商榷，这里只是举个例子。

**Comment by xjasonlyu** [comment]
PAC功能没有必要啊，clash的规则已经比较完善了，完全不需要增加一个PAC策略。其次你要转换的话直接用script转换就好了，没必要每次都手动转换。

**Comment by kery** [comment]
是可以写个脚本转换，但还是避免不了一些手动的操作。比如合并转换结果到clash的规则、决定什么时候去更新PAC。如果实现此功能，可以在每次启动clash时去自动加载PAC，甚至可以定义更新周期。

实现这个功能应该避免不了要引入一个JavaScript解释器，不知道对最后的体积有多大影响。这里已经有人实现了一个库https://github.com/jackwakefield/gopac。

如果能够优雅地实现此功能，对clash现有的规划或者说架构影响不大的话，我个人还是挺希望加上的。

**Comment by Dreamacro** [comment]
@kery gopac 里的 javascript 解释器太久了，不支持新的语法，之后可能会往 clash 加一个 embedded script 来写 rule。可能是 js 变化太快了，以至于我现在并没有找到一个轻量并支持新语法的 js 解释器（类似 quickjs）。python 的方言 https://github.com/google/starlark-go 倒是挺合适，就是 python 在链式方面不太友好。

**Comment by kery** [comment]
是的，JavaScript解释器是个麻烦的事情。

其实这个功能的使用场景并不是特别的多，有则是锦上添花，没有也不会对使用有多大影响。

**Comment by Dreamacro** [comment]
aka #272, 用于替代 pac

**Comment by jaychou315** [comment]
不支持PAC好像onenote代理不上去啊，换了V2RAY用PAC代理能上

**Comment by chenxuuu** [comment]
@jaychou315 因为uwp软件走localhost代理会直接被拒绝掉导致连不上网。。。

**Comment by redstoneleo** [comment]
> @jaychou315 因为uwp软件走localhost代理会直接被拒绝掉导致连不上网。。。

对，不支持pac模式的话也会有这个问题https://github.com/2dust/v2rayN/issues/2065

**Comment by bushnerd** [comment]
> @jaychou315 因为uwp软件走localhost代理会直接被拒绝掉导致连不上网。。。

换成PAC的话，返回的代理地址也是localhost，请问你解决了吗？
