### ISSUE TITLE
[Feature] fake ip加入分流规则是否可行

### ISSUE THREAD

**Issue by bli22ard** [Dreamacro/clash#2303]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在我的理解里，fake-ip模式的主要作用是让clash 能在三层获取到的原始的域名，这样在透明代理时候，可以实现根据域名的规则处理。redir-host方式在两个以上域名被污染到同一个ip时候，clash在三层无法还原出想访问的对应的域名，从而会影响规则判断的准确性。

我的场景
os：openwrt
arch: armv8
clash： v1.11.8
使用fake-ip模式下，使用tproxy部署的透明代理
```
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
```
我的nameserver 设置了 DoH  这样在开机启动时候会存在一个问题，设备开机，系统时间是2013年，启动时候，会进行时间同步，时间同步的域名解析出fake-ip，时间同步客户端和fake-ip建立连接，clash收到请求进行规则判断，用nameserver解析，时间不对验证doh证书失败，进入先有鸡还是先有蛋的问题
![image](https://user-images.githubusercontent.com/3320896/189609969-766863ae-455b-4296-875e-ed1f84458709.png)
这个问题，有一种解决办法就是把时间服务器的域名放到fallback-filter. domain中，这样可以解决这个问题，但是需要找到时间服务器域名也比较麻烦。
既然是这样，那是不是可以，进行dns解析时，先对域名进行规则判断，如果需要代理，那么返回fake ip，如果不需要代理，那么解析出真实ip返回。大多数情况下的大多数域名是不需要代理的，需要代理的域名是少部分。
不知道这个方案是否可行
我做了尝试更改
https://github.com/bli22ard/clash/commit/e65c903a8b0c25485c886f8c89a83228091f1c2c
经过简单测试可以正常工作

**Comment by Dreamacro** [comment]
试试, ntp 域名在系统里应该就是固定的，也很好找
```yaml
nameserver-policy:
    'ntp.xxx.xxx': '114.114.114.114'
```

**Comment by bli22ard** [comment]
> 试试, ntp 域名在系统里应该就是固定的，也很好找
> 
> ```yaml
> dns:
>   nameserver-policy:
>     'ntp.xxx.xxx': '114.114.114.114'
> ```

全部fake-ip不单是这个问题，还会有一些设备检测到dns 是内网地址，认为没有联网的。如果fake-ip分流的话， 应该没有明显的弊端吧

**Comment by bli22ard** [comment]
@Dreamacro 我自己改的分流，只有代理的返回fake ip， 不代理的正常返回， 我用了段时间感觉很好。如果要兼容以前，那就再加一个选项，比如叫 fake-ip-intellij 。可以改成这个样子吗

**Comment by leohxj** [comment]
还有一种场景, 如果域名规则判断需要直接, 代理客户端还是需要解析 DNS , 进行 ip 查询吧

**Comment by bli22ard** [comment]
> 还有一种场景, 如果域名规则判断需要直接, 代理客户端还是需要解析 DNS , 进行 ip 查询吧

是的， 如果判断ip需要直连，会按照正常得规则进行解析。只有需要代理的ip才需要 返回fake-ip

@Dreamacro  这方法不可行吗，存在什么问题吗

**Comment by InspoOnU** [comment]
我觉得可行，只要命中了DIRECT规则就返回正常IP。这对提升兼容性挺好的，不然路由器上用，fake-ip filter要写一大串。

**Comment by bli22ard** [comment]
> 我觉得可行，只要命中了DIRECT规则就返回正常IP。这对提升兼容性挺好的，不然路由器上用，fake-ip filter要写一大串。

可是  @Dreamacro  不回复。我认为全部fake-ip没有必要

**Comment by bli22ard** [comment]
@Dreamacro 大佬，这个方案是不是可行？
