### ISSUE TITLE
[Feature] Is mkcp supported?

### ISSUE THREAD

**Issue by leialbert** [Dreamacro/clash#2308]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Is mkcp supported? 

If not, when will it be supported or at which version?

thanks.

**Comment by Dreamacro** [comment]
mKCP is not supported because it contains changes to the original KCP that are not easily maintained.
