### ISSUE TITLE
dev版本hosts中的几个小bug

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#231]
1.
https://github.com/Dreamacro/clash/blob/0dd2a6dee5fdbf8598f47328ae44f81338b3fe8a/dns/middleware.go#L39
这行后面应该是少了一个`w.WriteMsg(msg)`，导致了fakeip模式下DNS请求延时增加。

2.
https://github.com/Dreamacro/clash/blob/0dd2a6dee5fdbf8598f47328ae44f81338b3fe8a/dns/middleware.go#L81
这里应该做一个类型转换判断，e.g.
```
ip, ok := host.Data.(net.IP)
if !ok {
    next(w, r)
    return
}
```
因为我好像在测试时，例如当hosts为`"*.example.com": "127.0.0.1"`，
此时`dig example.com`会直接panic，因为`host.Data`应该是`nil`了

3.
https://github.com/Dreamacro/clash/issues/208#issuecomment-511309419
这个应该不算bug吧，就如上面提到的，clash的hosts能不能在启动的时候加载一下本地的hosts文件。

**Comment by Dreamacro** [comment]
1. fixed
2. 由于没有泛型，所以现在只能用别扭的 interface, 由于 host 是自定义的，所以不存在内容不是 `net.IP` 的情况
3. 不算 bug，windows 不好操作导致如果 *unix 实现的话，对 windows 会有割裂

**Comment by xjasonlyu** [comment]
2. 有时候好像会有`host.Data == nil`的情况。
3. 这个好像问题也不大，应该就是判断一下GOOS然后按路径去读取hosts吧。

**Comment by Dreamacro** [comment]
2. 知道原因了, fixed

3. 考虑过 host 变更的时候，clash 还需要监听 host 吗？这过于复杂了

**Comment by xjasonlyu** [comment]
3. Coredns里的hosts逻辑是设置一个reload的时间，定时重新去读取hosts，感觉这样也是挺不错的。

**Comment by Dreamacro** [comment]
windows 权限复杂，不太想花时间处理 windows 的各种可能发生的奇怪问题

**Comment by xjasonlyu** [comment]
还发现了一个问题，
https://github.com/Dreamacro/clash/blob/3497fdaf45e06e75b558646735b7e335c58b6ffd/component/domain-trie/tire.go#L31
这里如果想添加一个`"localhost": "127.0.0.1"`就报错了，我觉得这几行其实意义不大吧，自定义hosts有些时候就是想简短一点的。

**Comment by Dreamacro** [comment]
@xjasonlyu 改了，原本是为了禁止 `com` 这种 host，不过好像没啥必要
