### ISSUE TITLE
[Feature] 对 DoH DNS 提供指定 IP 支持

### ISSUE THREAD

**Issue by lybtongji** [Dreamacro/clash#2311]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

希望对 DoH 的 DNS 能够指定 IP。有些公共 DNS 部分 IP 被 block，希望可以自己手动指定正常使用的 IP，一方面可以避免 DoH 频繁的 DNS timeout，另一方面也可以节省 DoH 的 IP 解析时间。

**Comment by BirkhoffLee** [comment]
hosts?

**Comment by lybtongji** [comment]
> hosts?

对一般 PC 可以这样处理，但在 Android 上如果没有 root 是无法修改 hosts 的
