### ISSUE TITLE
[Feature] SRC-IP Proxy rule

### ISSUE THREAD

**Issue by cornoctopus** [Dreamacro/clash#2312]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hi. Thanks for your great work. Want to know, Clash has SRC-IP-CIDR rule but is it possible to implement rule like SRC-IP? In example - 3 clients connect to router with Clash, Clash has rules like: 
SRC-IP,192.168.1.22,proxy1
SRC-IP,192.168.1.24,proxy2
SRC-IP,192.168.1.12,proxy3
Then Clash handle every connection from source ip to specific proxy.

**Comment by BirkhoffLee** [comment]
wdym? isn't `src-ip-cidr` exactly what you need?

**Comment by cornoctopus** [comment]
> wdym? isn't `src-ip-cidr` exactly what you need?
Yep, I'm not very experienced. Can achieve it with /32.
