### ISSUE TITLE
[Feature] filter 能否支持复杂正则筛选

### ISSUE THREAD

**Issue by tom2almighty** [Dreamacro/clash#2317]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

filter 正则筛选不支持复杂正则，如正向否定预查，已知有项目实现了 go 中的复杂正则，不知能否支持，项目如下：[regexp2](http://www.github.com/dlclark/regexp2)

**Comment by BirkhoffLee** [comment]
scripts 試試？
