### ISSUE TITLE
[Feature Request]希望fallback自动选择最快的节点，而不是按顺序

### ISSUE THREAD

**Issue by ltu00** [Dreamacro/clash#232]
用url-test的话，机场显示同时在线设备太多了。在当前线路不行的情况下，重新选个最快线路挺好的，不用一直测试延迟，又可以保证线路可用。

**Comment by Dreamacro** [comment]
机场同时在线设备不应该按连接算，fallback 如果自动选择最快的节点，那又和 url-test 有什么分别。。。

**Comment by ltu00** [comment]
> 快的节点，那又和 ur

只我没表达好？我想说的是只有在当前线路不行时，自动切换到最快那个线路，只要当前线路正常就不用切换，保持检测当前线路是否可用就行。

**Comment by Dreamacro** [comment]
延迟是一定要测的，没有一种好的手段在代理过程中确定节点是否可用，所以周期用 url 测试是一种很可靠的办法。所有的代理组都需要周期的测试节点是否可用，你可以理解为是一种健康检查。

**Comment by ltu00** [comment]
> 延迟是一定要测的，没有一种好的手段在代理过程中确定节点是否可用，所以周期用 url 测试是一种很可靠的办法。所有的代理组都需要周期的测试节点是否可用，你可以理解为是一种健康检查。

嗯，那可以做成下面这样？ 
 只对当前使用的线路进行周期url测试，如果测试失败，则开始对组内其它线路进行url测试，切换到url测试最快的那条。

**Comment by maoyinglm** [comment]
大佬，怎么对当前线路周期ULR尝试
