### ISSUE TITLE
[Feature] create an option for clients who use http proxy for internet connection (ISA,...)

### ISSUE THREAD

**Issue by ali-masoudi** [Dreamacro/clash#2320]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hi
In many situation users in a company would connect to internet via http proxy, so i ask you to add feature for this.
first connect clash through http proxy (ip,port,user,pass) to internet
then bypass censorship via clash

**Comment by BirkhoffLee** [comment]
You can use proxy chain feature to relay your connections to Internet proxy servers via your HTTP proxy
