### ISSUE TITLE
[Question] 若 clash 作为 dnsmasq/mosdns 上游，fake ip 被下游缓存，是否会过期失效

### ISSUE THREAD

**Issue by lucewang** [Dreamacro/clash#2321]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

若 clash 作为 dnsmasq/mosdns 上游，使用fake ip mode，则dnsmasq/mosdns会缓存fake ip，下次client请求可能会使用缓存过的fakeip 直接发给clash，如果此时clash fake ip 缓存已更新，则找不到对应的域名，请问
1 这种场景会不会发生？
2 clash 对这种场景是如何处理的？

**Comment by BirkhoffLee** [comment]
1. 會
2. 處理不了

**Comment by lucewang** [comment]
谢谢，这样如果使用clash做上游，还是采用redirhost比较好，稍微牺牲下性能，不过作为下游已经分流了，可以接受

**Comment by xuan880** [comment]
你如果没有开启
store-fake-ip: true
参数,那么每次重启地址池里面对应的映射都会变化,开启之后会保存对应的映射关系,重启后对应的映射关系依旧存在.

**Comment by topsite** [comment]
> 

所以那开启好还是关闭好呢。

**Comment by xuan880** [comment]
> > 
> 
> 所以那开启好还是关闭好呢。

根据你的需求,明显是开启好.
