### ISSUE TITLE
[Feature] use system dns as default-nameserver

### ISSUE THREAD

**Issue by iamtrazy** [Dreamacro/clash#2322]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

i have my own doh server . when i set it as my nameserver in clash it needs to lookup that address using default-nameserver . i want that to be my hotspot gateway ip . on older android devices i can manually set it as 192.168.43.1 but with new mobile phones my gateway ip keeps changing , is there any way to automatically get system dns as my default-nameserver

### Possible Solution

set a way to get system default dns server as default-nameserver without specifying an ip address

**Comment by Dreamacro** [comment]
use dhcp dns instead

**Comment by iamtrazy** [comment]
for some reason using gateway ip directly as nameserver works but using dhcp://wlp2s0 doesnt work , also on windows using dhcp://Wi-Fi doesnt work.

**Comment by iamtrazy** [comment]
all DNS requests failed, first error: DHCP not responding 

this is constantly on the log

**Comment by ElemenTP** [comment]
This has been discussed before: #1495
