### ISSUE TITLE
[Bug] macOS 无法开启 `redir-port`

### ISSUE THREAD

**Issue by cntrump** [Dreamacro/clash#2326]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

8.1.1

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
redir-port: 7892
```

### Clash log

```shell
➜ ./clash
INFO[0000] Start initial compatible provider AUTO       
INFO[0000] Start initial compatible provider PROXY      
INFO[0000] Start initial compatible provider FINAL      
WARN[0000] Failed to start Redir UDP Listener: not supported on current platform 
INFO[0000] Redirect proxy listening at: 127.0.0.1:7892  
INFO[0000] RESTful API listening at: 127.0.0.1:9090     
ERRO[0000] Start Redir server error: not supported on current platform
```

### Description

https://github.com/Dreamacro/clash/wiki/Configuration

配置文档里写的：

```yaml
# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892
```

是支持 macOS 的。

**Comment by Dreamacro** [comment]
这里 redirect 是指在 macOS 支持 tcp，但是不支持 udp（linux 这里其实是 TPROXY 的 udp）。而且 macOS 上其实 redirect 没有太多用处，在 macOS 上还是建议使用 premium 的 tun。
