### ISSUE TITLE
[Feature]  Auto Proxy based on DNS response

### ISSUE THREAD

**Issue by hiddify** [Dreamacro/clash#2329]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Usually the DNS server respond with a fake ip if the website is blocked for example in Iran it is (10.10.10.45)

It helps to recognize whether the site is blocked or not.
So if we detect a response with this ip we can use proxy otherwise we can use direct connection.

I see that similar feature is exist in DNS section but for proxy section it is really helpful.

**Comment by Dreamacro** [comment]
```yaml
rules:
  - IP-CIDR, 10.10.10.1/24,Proxy
  - MATCH,DIRECT
```

It will match ipcidr after resolving the DNS
