### ISSUE TITLE
[Bug] Certificate problem in old OS

### ISSUE THREAD

**Issue by SSgumS** [Dreamacro/clash#2333]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.08.26 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
-
```

### Clash log

```shell
x509: certificate has expired or is not yet valid.
```

### Description

Hello
It seems that clash only uses os-built-in Root CAs to validate certificates.
In OSs old enough not to have the new let's encrypt Root CA, this behavior causes a problem in validating certificates. For example, I've encountered this error on a Windows 7 device (using Clash for Windows Premium) and several (not much) old Android devices (using Clash for Android Premium). I should state that there isn't such a problem in modern OSs (aka, there are no problems with the certificate itself).
If you somehow embed popular Root CAs in Clash, it could contribute to compatibility tolerance of clash in general.
Thanks

**Comment by ElemenTP** [comment]
May be you can install the latest root CAs to those old OSs manually.

**Comment by SSgumS** [comment]
> May be you can install the latest root CAs to those old OSs manually.

In Windows, yes we can. But in Android I don't know if there is any possible way in a non-root device.
The main point of my suggestion was reducing the dependency of Clash to OS to have a better compatibility; Like how most browsers are.

**Comment by Lemmingh** [comment]
> embed popular Root CAs in Clash
> Like how most browsers are

Chrome and Chromium-based browsers collectively hold about 80% of the global market share. **They just use OS's certificate store.**

Safari also uses OS's certificate store.

Firefox, whose share is around 8%, uses NSS and loads default root certificates from security modules shipped with NSS. NSS is a comprehensive cryptographic solution heavily used in Mozilla products.

Thus, **your statement is not valid**.

---

> reducing the dependency of Clash to OS to have a better compatibility

Forking [standard libraries](<https://cs.opensource.google/go/go/+/master:src/crypto/tls/>) would actually **hinder** compatibility and significantly increase maintenance burden. It's discouraged for apps to re-implement fundamental libraries, unless no other choice exists, and the team is backed by formidable dev and security experts.

If something in addition to `skip-cert-verify` is really needed, I'd suggest loading user-provided certificates.

**Comment by SSgumS** [comment]
> Chrome and Chromium-based browsers collectively hold about 80% of the global market share. **They just use OS's certificate store.**

https://www.chromium.org/Home/chromium-security/root-ca-policy/
A part of the page mentioned:
> Historically, Chrome has integrated with the Root Store provided by the platform on which it is running. In Chrome 105, Chrome began a platform-by-platform transition from relying on the host operating system’s Root Store to its own on Windows, macOS, ChromeOS, Linux, and Android. This change makes Chrome more secure and promotes consistent user and developer experiences across platforms. Apple policies prevent the Chrome Root Store and corresponding Chrome Certificate Verifier from being used on Chrome for iOS.

>

**Comment by ZeronoFreya** [comment]
[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to gmscompliance-pa.googleapis.com:443 error: dial hz.tunnls.top:233 error: x509: certificate has expired or is not yet valid: current time 2023-11-07T11:52:59+8000:00 is after 2021-09-30T14:01:15Z

The device has stopped updating for a long time, is it hopeless?

**Comment by ppvan** [comment]
@ElemenTP can you provide some guides?
> May be you can install the latest root CAs to those old OSs manually.

I have a rooted android 6.0 device but i don't know how to install root CAs
