### ISSUE TITLE
[Feature] convert to yaml

### ISSUE THREAD

**Issue by zeptola20** [Dreamacro/clash#2334]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Can we convert the other protocols like shadowsocks or v2ray to yaml file?
And Do you know any source for download clash config?

**Comment by ElemenTP** [comment]
[tindy2013/subconverter](https://github.com/tindy2013/subconverter)  
You can use this tool to convert configs from other protocols to clash config file
