### ISSUE TITLE
[Feature] Change TLS fingerprint

### ISSUE THREAD

**Issue by psamim** [Dreamacro/clash#2339]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hi,

Recently, [it has been reported](https://github.com/net4people/bbs/issues/129) that almost all TLS-based protocols are blocked due to TLS fingerprints. I personally can no longer use Trojan on some networks with Clash.

In response to this, [there is an ongoing PR in trojan-go](https://github.com/p4gefau1t/trojan-go/pull/464) to replace Go's standard [cryto/tls](https://pkg.go.dev/crypto/tls) with [uTLS](https://github.com/refraction-networking/utls).

Is it possible to have this feature in clash too?
I know [there has been discussions about not using uTLS](https://github.com/Dreamacro/clash/issues/706#issuecomment-636578170), but I think it is necessary now for all TLS-based protocols.

Thanks

### Possible Solution

Replace Go's standard [cryto/tls](https://pkg.go.dev/crypto/tls) with [uTLS](https://github.com/refraction-networking/utls).

**Comment by psamim** [comment]
I cannot even update/download profile subscriptions. I can open the subscription URL in Chrome and Firefox without any issue, but it is blocked when requested by Clash or even curl. The request is definitely blocked by checking is client TLS fingerprint.

**Comment by SakuraSakuraSakuraChan** [comment]
Yeah, it's about time

**Comment by rfbzs** [comment]
> I can open the subscription URL in Chrome and Firefox without any issue, but it is blocked when requested by Clash or even curl.

Yes, I have the same problem.

**Comment by erfanmetallica** [comment]
This is a very important feature needed because we can just use Trojan-go to bypass gfw (IR@N)

**Comment by hiddify** [comment]
> I cannot even update/download profile subscriptions. I can open the subscription URL in Chrome and Firefox without any issue, but it is blocked when requested by Clash or even curl. The request is definitely blocked by checking client TLS fingerprint.

In android client, do you get handshake fail error?

**Comment by psamim** [comment]
> > I cannot even update/download profile subscriptions. I can open the subscription URL in Chrome and Firefox without any issue, but it is blocked when requested by Clash or even curl. The request is definitely blocked by checking client TLS fingerprint.
> 
> In android client, do you get handshake fail error?

Yes, "net/http: TLS handshake timeout".

**Comment by hiddify** [comment]
Okay it seems that all of us has a same issue
