### ISSUE TITLE
[Feature] New protocol to bypass the detection of TLS in TLS

### ISSUE THREAD

**Issue by SakuraSakuraSakuraChan** [Dreamacro/clash#2341]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

自10月3日起，很多使用TLS加密的代理用途VPS被封端口，协议包括 vmess+wss Trojan VLESS Naiveproxy 等等，目前有自称是GFW供应商员工的账号在Github上做了说明 https://github.com/net4people/bbs/issues/129 。简单说就是跨境TLS流量使用大小超过一定阈值时，会将流量发送一份到供应商处进行分析，基于DPI或是机器学习之类的来分析出TLS加密内部的TLS握手特征，因为https网站都会有这种握手，无法避免，因此会被通过包长度或者时间之类的分析出来，等到判定为代理用途后就会拉清单。因为握手特征明显，vmess 的二次加密或者 Naiveproxy 的数据填充都没有作用。只有访问http网站才没有这种特征，但这在2022年显然不现实

### Possible Solution

希望Clash能支持一些新的协议来避免TLS in TLS识别，目前有两种思路，拼接TLS类和UDP类
之前VLESS支持的issue里好想看到过xTLS不会支持，因此建议考虑下 Verysimple 的 Lazy Encryption，是对标xTLS的，但是号称使用标准的TLS包，因此应该没有依赖问题，并且少一次加密速度快很多，希望能考虑下 https://github.com/e1732a364fed/v2ray_simple/wiki/%E5%85%B3%E4%BA%8Elazy%E4%B8%8Extls

还有就是UDP类，GFW供应商员工在TG群里表示目前UDP类的还没办法做到内部TLS识别，因此也是一种思路，*ray的QUIC和Hysteria因为使用的quic-go包比较大估计大佬不愿意用，tuic是rust写的工程量不小，因此建议看下今年新的mieru
https://github.com/enfein/mieru/blob/main/docs/protocol.md
go写的类似shadowsocks的协议但是有UDP传输方式并且也有数据填充，因此被新手段检测到的几率比较低

**Comment by moranno** [comment]
借楼重申下请求支持ss2022

**Comment by qist** [comment]
UDP GFW 一直有干扰，接入意义不大。

**Comment by SakuraSakuraSakuraChan** [comment]
> UDP GFW 一直有干扰，接入意义不大。

只知道运营商一直有QoS，但没听说GFW有干扰，Hysteria和tuic用户也没见过表示被干扰的

**Comment by betaxab** [comment]
> 只知道运营商一直有QoS，但没听说GFW有干扰，Hysteria和tuic用户也没见过表示被干扰的

这两个受众比较小。我估计多了一样

**Comment by qingmuhy** [comment]
> 借楼重申下请求支持ss2022

我也觉得这种完全无特征流量不错，希望支持。

**Comment by MrSaeedNasiri** [comment]
伊朗 (GFW) 现在可以检测并阻止 SS、SSR、VMESS 和 TROJAN。
它很快就会在其他 FW 中发生。

**Comment by PeterWang-dev** [comment]
GFW最近变高，trojan tls被封，确实需要新协议
