### ISSUE TITLE
[Feature] Whitelist mode for "nameserver"

### ISSUE THREAD

**Issue by 57a4c324e742** [Dreamacro/clash#2346]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

It looks like Clash was designed to send all queries to both default server and fallback server, and pick result from fallback server if the result could be polluted.

What if the queries send to local DNS server will be used as evidence of a crime by the government in the future?
Use DNS server outside the country only could prevent this happen, but it may cause some website slow or not able to load.

### Possible Solution

A whitelist mode for "nameserver" is required to ensure only legal website's domain will send to local DNS server.

**Comment by BirkhoffLee** [comment]
Use a customised DNS upstream in your local network, this might not be implemented in any foreseeable future
