### ISSUE TITLE
bug: yaml / yml

### ISSUE THREAD

**Issue by winguse** [Dreamacro/clash#235]
初始化对时候：

```
$ clash
INFO[0000] Can't find config, create an empty file      
INFO[0000] Can't find MMDB, start download              
FATA[0001] Parse config error: open /home/winguse/.config/clash/config.yml: no such file or directory 
```

实际上，创建了一个 yaml 文件，但现在的版本用的是 yml。

**Comment by Dreamacro** [comment]
现在版本用的就是 yaml，建议把 `.yml` 改成 `.yaml`，1.0 时会强制使用 `.yaml`

**Comment by winguse** [comment]
上面的情况是，自动创建的和默认读的，不是一个后缀

**Comment by Dreamacro** [comment]
现在的做法是，优先读 `.yaml` 如果文件不存在或者长度为 0，则读取 `.yml`

**Comment by faynwol** [comment]
win平台读的是yaml没问题
mac读的是yml，即使存在yaml也报错，就很迷

**Comment by ruisiji** [comment]
I created a PR to fix this issue: https://github.com/Dreamacro/clash/pull/253

The reason is: clash initialize will create an empty config.yaml file, when parsing this file clash found it is empty, then clash will try to use config.yml, but there is not config.yml.
