### ISSUE TITLE
[Feature] 不支持的协议能不能直接过滤掉，不要弹出提示。

### ISSUE THREAD

**Issue by vpei** [Dreamacro/clash#2359]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

[Feature] 不支持的协议或错误的节点能不能直接过滤掉，不要弹出提示。

TLS must be true with h2/grpc network.

### Possible Solution

[Feature] 不支持的协议或错误的节点能不能直接过滤掉，不要弹出提示。

TLS must be true with h2/grpc network.

**Comment by Dreamacro** [comment]
这是配置错误，不是不支持

**Comment by vpei** [comment]
> 这是配置错误，不是不支持

这样的错误节点可能忽略掉，毕竟有很多节点，只有一个错了，其他的就都用不了。

**Comment by Dreamacro** [comment]
@vpei 有了错误应该修正错误，忽略错误只会有更多的 issue 提出 "为什么 xxx 功能不能用"、"节点为什么配置里有但控制面板上看不到" 之类的问题。
