### ISSUE TITLE
Problems with WebSocket connections establishment

### ISSUE THREAD

**Issue by ky0nch3ng** [Dreamacro/clash#236]
failed: Error in connection establishment: net::ERR_PROXY_CONNECTION_FAILED

**Spotify**

![](https://imgur.com/BVu2RMd.png)

**Slack**

![](https://imgur.com/POiBgfr.png)

**Comment by Dreamacro** [comment]
works fine on my macbook pro. maybe you should checkout your network settings?

**Comment by ky0nch3ng** [comment]
I use clashX as my proxy manager.
If you uncheck HTTP/HTTPS proxy, use socks5 proxy only, WebSocket connections is work.

![](https://imgur.com/NXkg9uc.png)

**Comment by Dreamacro** [comment]
Even if use HTTP/HTTPS proxy, it works well. can you provide your general config?

**Comment by ky0nch3ng** [comment]
I use `Global` mode usually, rules part is useless for me.

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
Proxy:
  - {"name":"test","type":"ss","server":"1.1.1.1","port":1024,"cipher":"aes-256-gcm","password":"password"}

'Proxy Group':
    - { name: "PROXY", type: select, proxies: ["test"] }
```

**Comment by Dreamacro** [comment]
Can you install `socat` and `websocat` with homebrew?

```
$ brew install socat websocat
```

And connect with echo.websocket.org

```
$ websocat -t --ws-c-uri=wss://echo.websocket.org/ - ws-c:ssl-connect:cmd:'socat - proxy:127.0.0.1:echo.websocket.org:443,proxyport=7890'
```

**Comment by ky0nch3ng** [comment]
@Dreamacro 

```
websocat -t --ws-c-uri=wss://echo.websocket.org/ - ws-c:ssl-connect:cmd:'socat - proxy:127.0.0.1:echo.websocket.org:443,proxyport=7890'
[WARN  websocat::ssl_peer] Connected to TLS without proper verification of certificate. Use --tls-domain option.
```

**Comment by Dreamacro** [comment]
对的然后输几个字符回车试试，能返回一样的东西吗

**Comment by ky0nch3ng** [comment]
Yes, it looks like there is no problem right now, I will temporarily close the issue, thank you for your detailed answer.

**Comment by HouCoder** [comment]
I'm having the same problem on my Slack this morning.

**Comment by Dreamacro** [comment]
@HouCoder maybe restart clashx can solve this problem, but I don't know why....

**Comment by HouCoder** [comment]
Right now I'm using company VPN, it seems to me that Clash can't route WS requests over proxy.

**Comment by ky0nch3ng** [comment]
@HouCoder @Dreamacro 
https://github.com/yichengchen/clashX/issues/179

clashx socks5 setting bug in lastest version.

**Comment by HouCoder** [comment]
It works again after updating to the latest ClashX, I forgot to check which version I was using before. 😵

**Comment by Alice-space** [comment]
https://www.v2ex.com/t/811568

**Comment by CaliInn-Li** [comment]
> https://www.v2ex.com/t/811568

感谢，我出现的问题是：
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/40906144/164585985-2ff81119-7877-4dd7-9cef-3f63db66cff9.png">

这确实是webkit的bug导致的。我粘贴一下原帖的解决方案：
> 经过搜索后发现在 Safari 里的开发->试验性功能->NSURLSession WebSocket 取消勾选后问题消失，打扰了
