### ISSUE TITLE
[Feature] 支持带订阅地址启动

### ISSUE THREAD

**Issue by Charlie17Li** [Dreamacro/clash#2366]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前Clash启动时，入参配置是目录or文件
```
[root@master ~]# clash -h
Usage of clash:
  -d string
        set configuration directory
  -ext-ctl string
        override external controller address
  -ext-ui string
        override external ui directory
  -f string
        specify configuration file
  -secret string
        override secret for RESTful API
  -t    test configuration and exit
  -v    show current version of clash
```

是否能支持直接 `-url 订阅地址` 方式启动？
场景：在远程安装clash启动时，需要使用clashx等其他工具将地址换成配置文件，在上传到远端服务器上在重新启动，若订阅地址需要更新，则需要重复上述步骤

**Comment by techblack** [comment]
使用proxy-providers
