### ISSUE TITLE
unify the cipher format to meet the upstream

### ISSUE THREAD

**Issue by ruisiji** [Dreamacro/clash#237]
As far as I know, there are many shadowsocks clients that allow user choosing the cipher/encrypt-method, both of the format is lower case with `-`.

But for Clash, the format in document contains lower case, upper case, `-` and `_`:

> AEAD_AES_128_GCM AEAD_AES_192_GCM AEAD_AES_256_GCM AEAD_CHACHA20_POLY1305 AES-128-CTR AES-192-CTR AES-256-CTR AES-128-CFB AES-192-CFB AES-256-CFB CHACHA20-IETF XCHACHA20 chacha20 rc4-md5 xchacha20-ietf-poly1305

Following is the shadowsocks-libev cipher format, they are clear and easy to read.

```
   -m <encrypt_method>        Encrypt method: rc4-md5,
                              aes-128-gcm, aes-192-gcm, aes-256-gcm,
                              aes-128-cfb, aes-192-cfb, aes-256-cfb,
                              aes-128-ctr, aes-192-ctr, aes-256-ctr,
                              camellia-128-cfb, camellia-192-cfb,
                              camellia-256-cfb, bf-cfb,
                              chacha20-ietf-poly1305,
                              xchacha20-ietf-poly1305,
                              salsa20, chacha20 and chacha20-ietf.
                              The default cipher is chacha20-ietf-poly1305.
```

I know the Clash or go-shadowsocks2 have some internal conversions that makes both of the formats work fine. But it is better to unify the formats and use a single format to expose in document.

I vote the lower case with `-` since the lower case with `-` is more readable than upper case for most people that don't have English as primary language.

**Comment by Dreamacro** [comment]
If you believe these formats are very helpful, would be great if you could contribute and submit a PR. 👏

**Comment by ruisiji** [comment]
Thank you for quick response, will submit a PR soon.

**Comment by Dreamacro** [comment]
#238
