### ISSUE TITLE
There are two major failures of clash

### ISSUE THREAD

**Issue by iavgo** [Dreamacro/clash#2371]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

There are two major failures of clash. One is that it does not support importing nodes, and the other is that it does not support the vless protocol until now, even though clash is a very good software.

vless has a very good advantage over other protocols in terms of resource consumption and speed

**Comment by BirkhoffLee** [comment]
1. Clash does not handle importing handles. You can utilise the API or have your own configuration file generator.
2. I believe there have been prior discussions regarding VLESS support, check the issues.

**Comment by BirkhoffLee** [comment]
`proxy-providers` should do what you described- it just came off my head
