### ISSUE TITLE
[Feature]关于再提对Hysteria的支持

### ISSUE THREAD

**Issue by moranno** [Dreamacro/clash#2372]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在上个讨论中：https://github.com/Dreamacro/clash/issues/1863
@Dreamacro 提到

> quic-go is not a good QUIC implementation, but it is the only QUIC implementation for golang. So with the options available, I don't want to integrate quic-go. hysteria uses a fork quic-go, It makes me even less want to integrate it.

这里有一个各quic库的性能对比：https://interop.seemann.io/
可以看到quic-go的性能在所有quic实现中都名列前茅，所以想Dreamacro能否再次考虑对其支持？
在最近的大屠杀中，基于tcp的协议基本都死光了。

### Possible Solution

另外，我这边把目前活跃的一些项目作者都联系上了，不知 @Dreamacro 是否有兴趣也加个tg群一起讨论下，互通有无？
我tg：@missmoranno
我也会力所能及的为这些好项目做一些资金支持。

**Comment by pfangzhi** [comment]
这个貌似很不稳定吧，虽然说能连时候速度较快，但那是udp的功劳，国内环境还是很不稳定的。

**Comment by skill7899** [comment]
Clash.Meta已经实现了这个对接

**Comment by moranno** [comment]
> Clash.Meta已经实现了这个对接

用meta的客户端比较少，cfw自动更新的时候也不会带meta内核。

**Comment by A7610605** [comment]
> 这个貌似很不稳定吧，虽然说能连时候速度较快，但那是udp的功劳，国内环境还是很不稳定的。

哪方面不稳定？还是你只是听说，连用都没用过？电信联通我用着都很稳啊，美西随便一台VPS，速度快延迟又低，甚至美服炉石都能玩电表。一句UDP的功劳就把别人的贡献都抹杀了，都不需要懂技术，拿同样的TUIC来对比下就知道了

**Comment by shaojs321** [comment]
确实不稳定 ，我用hy经常断流，不是clash的问题是国内udp环境的问题

**Comment by moranno** [comment]
> 确实不稳定 ，我用hy经常断流，不是clash的问题是国内udp环境的问题

可能是客户端的问题。手机容易断流，电脑不会断。

**Comment by BirkhoffLee** [comment]
在原本的 issue 讨论吧
