### ISSUE TITLE
[Feature] 希望未被选中且lazy为true的group完全不进行延迟测试

### ISSUE THREAD

**Issue by SakuraSakuraSakuraChan** [Dreamacro/clash#2380]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前Clash对于load-balance等group的行为是启动时会测试一次延迟，后续按照interval间隔来测，如lazy为true的话后续不进行测试。

希望能稍做一下调整：如果一个group没有被选中且lazy为true，那就完全不测试（暂时想不出有任何负面影响），选中时再进行测试。提出这点主要是目前墙比较狠，检测TLS in TLS准确率比较高，因此每次Clash(for android)启动时我好几个节点都要去连接一下谷歌，会增加一丢丢风险（主要是CFA目前不会按照配置文件group里的url来测试，也没办法说服那边 https://github.com/Kr328/ClashForAndroid/issues/1726 ），因此只能希望核心这边能从行为上减少一些测延迟的步骤。

**Comment by Sanchew** [comment]
改成false 就好了,   但是似乎没有作用,   我看原码 如果为true的情况下  只有手动测试时  才会调用healthcheck 
但无论是  url-test还是fallback 只要当前线路能连通  就不会做线路切换,  这与预想的不同,  但我似乎还没找到哪里出问题了

**Comment by SakuraSakuraSakuraChan** [comment]
> 改成false 就好了, 但是似乎没有作用, 我看原码 如果为true的情况下 只有手动测试时 才会调用healthcheck 但无论是 url-test还是fallback 只要当前线路能连通 就不会做线路切换, 这与预想的不同, 但我似乎还没找到哪里出问题了

我的标题写的可能有歧义了，编辑了一下

**Comment by nobody-99** [comment]
好像把interval设置成负数就是不测试

**Comment by ksync1** [comment]
> 改成false 就好了, 但是似乎没有作用, 我看原码 如果为true的情况下 只有手动测试时 才会调用healthcheck 但无论是 url-test还是fallback 只要当前线路能连通 就不会做线路切换, 这与预想的不同, 但我似乎还没找到哪里出问题了

@Sanchew 请问如果将某个proxy-group设置了lazy属性(fallback配置), 是只有程序启动时会测试下选择这个group下的某个proxy吗(测试完成后只要程序不退出, 永远不切换)? 还是说 lazy 属性针对的是这一个 group, 只有这个group没有被使用才不测试, 因为我看关于这个配置的描述是这样的:
 `when lazy open, proxy group and proxy provider that have not been used during the cycle will not be speed tested.`

举个例子, 假设我的配置是下面这样的, 设置了 fallback 和 lazy 属性, 且程序第一次启动监测 fallback 到了 ss2. 那么有了 lazy 属性能不能保证只要程序不重启, 一直维持在 ss2?
还是说因为lazy规则只有当 proxy-vps 整个组没被使用时才生效, 这里因为 proxy-groups 被使用了, 只不过fallback到ss2, lazy规则不生效, 继续按照 interval 参数进行周期性监测?

因为不知道怎么看clash有没有检测过两个proxy, 不知道怎么测试, 希望帮忙解答下.

```YML
proxy-groups:
  - name: "proxy-vps"
    type: fallback
    proxies:
      - ss1
      - ss2
    url: 'https://google.com/'
    interval: 14400
    lazy: true
````
