### ISSUE TITLE
[Feature] 能否添加 log-file 选项，保存日志到文件

### ISSUE THREAD

**Issue by zhonghes** [Dreamacro/clash#2384]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前 clash 只支持设置日志级别，希望可以添加 `log-file` 选项保存日志到文件；
添加 `log-max-days` 选项，设置保存日志的最大天数；

### Possible Solution

其中 `log-file` 可以通过在 https://github.com/Dreamacro/clash/log/log.go 文件中添加 SetLogFile() 函数，然后调用实现：
```go
func SetLogFile(logFIle string) {
        f, err := os.OpenFile(logFIle, os.O_WRONLY|os.O_CREATE, 0755)
        if err != nil {
                fmt.Printf("err: %v\n", err)
        }
	log.SetOutput(f)
}
```

**Comment by zhonghes** [comment]
> systemd & logrotate does this well

bug when want using Clash in your Golang program，or using in windows, this will be very useful.

**Comment by sanzhang007** [comment]
curl -H "Upgrade: websocket" -H "Connection: Upgrade" -H "Sec-WebSocket-Version: 13" -H "Sec-webSocket-Key: eeZn6lg/rOu8QbKwltqHDA==" 127.0.0.1:9090/logs --output - >>./desktop/clash.log

这样不就可以读取定向到文件了么
