### ISSUE TITLE
能否增加一个直接在托盘菜单测试延迟以及显示延迟的功能

### ISSUE THREAD

**Issue by SteveFan0802** [Dreamacro/clash#2387]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

需要手动切换节点，但每次点开很繁琐

**Comment by Dreamacro** [comment]
与二进制程序无关
