### ISSUE TITLE
哪个ip是访问国内网站的ip 晕了

### ISSUE THREAD

**Issue by fredericky123** [Dreamacro/clash#2388]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.95

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
无需
```

### Description

开启增强模式，用的规则模式，dns解析设置127.0.0.1，用adguard，访问国内的站长工具，发现ip均不一样，好奇怪，为啥访问国内网站还不一样？
访问https://www.ip138.com/ 测得ip为
<img width="250" alt="image" src="https://user-images.githubusercontent.com/13982749/199728113-f2776835-370c-40ea-83c9-34a94a6cb6ee.png">

访问ipip.net 测得ip为
<img width="240" alt="image" src="https://user-images.githubusercontent.com/13982749/199728322-1d6bba41-ea0f-4788-9214-b46aed15d6db.png">
而mac自带的网络适配器显示，访问的ip为
<img width="250" alt="image" src="https://user-images.githubusercontent.com/13982749/199728527-07108151-88b3-45b9-8ab3-068efc31ca0d.png">

我yun晕了，究竟哪个才是访问国内网站被记录的ip

**Comment by ElemenTP** [comment]
第一个219.142.*.*的IP是你的公网IP，是访问国内网站被记录的IP。后者172.22.*.*是你的内网IP，仅用于局域网内。如果不能理解，建议简单学习一下计算机网络基础。

**Comment by fredericky123** [comment]
第二个访问ipip.nt测的ip是114. 又是咋回事呢

**Comment by ElemenTP** [comment]
> 第二个访问ipip.net测的ip是114. 又是咋回事呢

可能是由于以上两个网站的服务器不同，你的网络在访问他们时网络出口不一样。查了一下，一个属于北京移动一个属于北京电信

**Comment by fredericky123** [comment]
好的吧 感谢 我以为访问两个网站的ip应该是相同的
实际上我的ip 是校园网 应该都不是这两个
奇怪


> > 第二个访问ipip.net测的ip是114. 又是咋回事呢
> 
> 可能是由于以上两个网站的服务器不同，你的网络在访问他们时网络出口不一样。查了一下，一个属于北京移动一个属于北京电信

**Comment by techblack** [comment]
这没什么奇怪的，一般的学校都会购置三大运营商的带宽来分担教育网带宽的负担，因此你的出口ip可能是校园网，电信移动等等，可能随机，也可能按照一定的规律进行分流
可以使用该工具查看你几乎所有可能的出口IP
https://ip.orz.tools/

**Comment by fredericky123** [comment]
> 这没什么奇怪的，一般的学校都会购置三大运营商的带宽来分担教育网带宽的负担，因此你的出口ip可能是校园网，电信移动等等，可能随机，也可能按照一定的规律进行分流 可以使用该工具查看你几乎所有可能的出口IP https://ip.orz.tools/

这一下醍醐灌顶 理解了 感谢这个小工具
