### ISSUE TITLE
[Bug] Clash DNS 无法正确响应AAAA查询

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#2389]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash-linux-amd64-2022.08.26

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
ipv6: false
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:5053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.local"
  nameserver:
  - 127.0.0.1:6053
  default-nameserver:
  - 127.0.0.1:6053
```

### Clash log

```shell
DEBUG下无纯DNS查询日志
```

### Description

如上配置文件所示的ipv6:false DNS里的ipv6:true的时候，使用dig查询AAAA记录返回空值。
直接查询clash上游DNS可正确响应，可排除上游问题。

（由于没找到dev分支的二进制在哪下载，故实际上并未使用dev分支代码进行测试）

```
root:~/ # dig AAAA dns.google @127.1 -p 5053                      [22:13:47]

; <<>> DiG 9.18.7 <<>> AAAA dns.google @127.1 -p 5053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10563
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns.google.                    IN      AAAA

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5053(127.1) (UDP)
;; WHEN: Thu Nov 03 22:15:57 CST 2022
;; MSG SIZE  rcvd: 28

root:~/ # dig AAAA dns.google @127.1 -p 6053                      [22:15:57]

; <<>> DiG 9.18.7 <<>> AAAA dns.google @127.1 -p 6053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20488
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dns.google.                    IN      AAAA

;; ANSWER SECTION:
dns.google.             768     IN      AAAA    2001:4860:4860::8888
dns.google.             768     IN      AAAA    2001:4860:4860::8844

;; Query time: 0 msec
;; SERVER: 127.0.0.1#6053(127.1) (UDP)
;; WHEN: Thu Nov 03 22:15:58 CST 2022
;; MSG SIZE  rcvd: 95
```

**Comment by Dreamacro** [comment]
我这里没办法复现，但使用的不是 127 上的 dns server

```
13:18:45 DBG [DNS] dns response source=dhcp://192.168.31.1:53(en0) qType=AAAA name=dns.google. answer=["2001:4860:4860::8888","2001:4860:4860::8844"]
```

**Comment by Dreamacro** [comment]
fakeip 不返回 aaaa 记录是正常的，他不是实际请求的 ip

**Comment by BirkhoffLee** [comment]
> > fakeip 不返回 aaaa 记录是正常的，他不是实际请求的 ip
> 
> 但是这会导致纯V6域名完全无法连接啊，无论clash是否接管IPV6流量

除非客户端只请求 AAAA，不然 Clash 返回的 A 记录一样是会正常解析并发到代理那边的，可以仔细看一下 wiki 对于这部分的说明

**Comment by BirkhoffLee** [comment]
> 如果你是指用 fakeip 的 A 记录 流量被 clash 接管后会自动重定向到 v6 地址正常连接的话

对的，现在设计就是这样。可以简单理解为 fake ip inbound 只有 v4 的支持，但是 outbound 可以正常走 v6 出去的

**Comment by BirkhoffLee** [comment]
不知道你说的 V6 only 的直连站点 是什么意思，如果你是说 web 的话，现在 modern browser 会同时请求 A 和 AAAA 的，所以一定会收到 Clash 返回的 A 记录

**Comment by BirkhoffLee** [comment]
DEBUG 的日志应该会有提示吧，不然就是 clash 的配置写错了
我很久没用 v6 了也没法给你测试
