### ISSUE TITLE
[Feature] 是否有计划支持ASN规则

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#2391]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前市面上的代理软件基本都新增了ASN类型的规则，可替代或互补GeoIP规则，请问clash有此方面的开发计划吗？

### Possible Solution

详见
https://github.com/VirgilClyne/GetSomeFries/wiki/🌐-ASN#安装链接

**Comment by liangyi9812** [comment]
再顶一下🥰
