### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lili2012** [Dreamacro/clash#2395]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash tun 1.11.8

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
no need
```

### Clash log

```shell
no need
```

### Description

https://release.dreamacro.workers.dev/2022.08.26/clash-windows-amd64-2022.08.26.zip
When I run this exe in administrator mode the console output gibberish:
<img width="666" alt="微信图片_20221105220955" src="https://user-images.githubusercontent.com/14124820/200123981-1eb1d52e-98ff-45ef-835c-ae5c013750b4.png">

when I run it unprevilleged it's output is quite normal:
![image](https://user-images.githubusercontent.com/14124820/200123884-7a233dc2-ef74-4b83-a892-4fa81612c66e.png)

only Premium core has this problem.
my OS is windows 11 22h2.

**Comment by Dreamacro** [comment]
It doesn't look like the problem of clash itself. I'm not sure why windows doesn't render ANSI code properly in admin mode.

**Comment by lili2012** [comment]
Could you tell me how do you output colorful text within console?

**Comment by Dreamacro** [comment]
try https://duffney.io/usingansiescapesequencespowershell/

**Comment by lili2012** [comment]
https://superuser.com/a/1300251/1550114
I set
