### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Youyufa** [Dreamacro/clash#2402]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

您好，我想在Jetson 系列的 ARM 平台使用Clash，CPU 使用ARMv8 指令集，目前软件的 arm64-v7能否兼容？后续是否会开发 v8 版本？谢谢！

**Comment by Dreamacro** [comment]
直接使用 arm64 版本

**Comment by Youyufa** [comment]
systemctl 一直无法启动clash service
