### ISSUE TITLE
询问一下clash relay代理模式是否为层层加密

### ISSUE THREAD

**Issue by zlx021120** [Dreamacro/clash#2411]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

客户端在一次完整请求过程中
本地>>鸡场节点>>落地鸡>>目标网站||目标网站>>落地鸡>>鸡场节点>>本地
ralay配置
 -  name: "relay1"
    type: relay
    proxies:
      - 机场节点
      - 落地机
***************
这个过程中"机场服务器可以看到数据包内容吗"，我阅读了配置文件似乎并没有找到相关解答，我的能力又不支持我阅读源代码
我在v2ray使用文档中知道v2ray是会对数据包层层加密，中间节点(鸡场节点)无法查看数据包具体内容(文档链接:https://guide.v2fly.org/advanced/outboundproxy.html)

**Comment by Dreamacro** [comment]
是的

**Comment by ijrou** [comment]
> 是的

简洁明了，简意赅，惜字如金...

**Comment by zlx021120** [comment]
> > 是的
> 
> 简洁明了，言简意赅，惜字如金...

首先对于大部分非技术人员 不会去关心具体的原理 作者已经很好的告诉我们 不需要担心使用relay协议中转节点造成的隐私泄露
其次作者也没有任何义务去回答粉丝的提问，作者能在百忙之中抽出时间回复我很感谢
你说的多少有点阴阳怪气了
其实应该怪我 是我不了解"链式转发" 在错误的地方提了问题

**Comment by ijrou** [comment]
> > > 是的
> > 
> > 
> > 简洁明了，言简意赅，惜字如金...
> 
> 首先对于大部分非技术人员 不会去关心具体的原理 作者已经很好的告诉我们 不需要担心使用relay协议中转节点造成的隐私泄露 其次作者也没有任何义务去回答粉丝的提问，作者能在百忙之中抽出时间回复我很感谢 你说的多少有点阴阳怪气了 其实应该怪我 是我不了解"链式转发" 在错误的地方提了问题

我并没有什么阴阳怪气，请你不要过多揣摩别人怎么想的，我不知道你想引战还是什么，你要是不知道别人想表达什么，就不要胡乱表述出来。。。这让我和作者感到很迷惑...

**Comment by zlx021120** [comment]
> > > > 是的
> > > 
> > > 
> > > 简洁明了，言简意赅，惜字如金...
> > 
> > 
> > 首先对于大部分非技术人员 不会去关心具体的原理 作者已经很好的告诉我们 不需要担心使用relay协议中转节点造成的隐私泄露 其次作者也没有任何义务去回答粉丝的提问，作者能在百忙之中抽出时间回复我很感谢 你说的多少有点阴阳怪气了 其实应该怪我 是我不了解"链式转发" 在错误的地方提了问题
> 
> 我并没有什么阴阳怪气，请你不要过多揣摩别人怎么想的，我不知道你想引战还是什么，你要是不知道别人想表达什么，就不要胡乱表述出来。。。这让我和作者感到很迷惑...

没有引战的意思
是我语文不好 认为"惜字如金"是贬义，刚才查了一下才知道是中性词
抱歉 我的问题 向你道歉
