### ISSUE TITLE
[Bug] Premium core TUN priority in routing table

### ISSUE THREAD

**Issue by lili2012** [Dreamacro/clash#2415]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash tun 1.11.8

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
暂时不需要
```

### Clash log

```shell
暂时不需要
```

### Description

同时使用openvpn和clash tun, 路由表 clash tun 的metric 小于 openvpn,
```
  Network        Destination           Netmask               Gateway              Interface  Metric
 0.0.0.0           128.0.0.0               198.18.0.2             198.18.0.1              0
 10.0.0.0         255.0.0.0               192.168.202.1       192.168.202.70             281
```
有什么好的方法可以让10.0.0.0 优先走openvpn 而不是clash tun

**Comment by ssz66666** [comment]
`10.0.0.0/8` 前缀是比 `0.0.0.0/1` 长的，本来就会选择下一跳为`192.168.202.1`（即OpenVPN）的路由。
Metric只有在匹配到的多条路由前缀长度相同时才会用于路由选择，见微软文档：[https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-tcpip-interfaces-interface-routes-route-metric](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-tcpip-interfaces-interface-routes-route-metric)
