### ISSUE TITLE
[BUG?] Fake IP may break smb

### ISSUE THREAD

**Issue by Kr328** [Dreamacro/clash#242]
一些应用程序 (例如 Solid Explorer)
在连接 smb 主机时 需要将主机名解析到IP
会进行以下尝试
  1. DNS 查询
  2. netbios 广播

Fake IP 在 DNS  查询时 立即返回 fakeip
导致 应用程序 不会再进行 netbios 广播
最终连接时 会连接到 一个 不存在的域名 导致 smb 错误

**Comment by Dreamacro** [comment]
那你有什么好的建议吗

**Comment by Kr328** [comment]
@Dreamacro 遇到 *.local 或者 没有二级域名 的 先尝试 查询 是否存在 再决定 是否 返回 fakeip (吗

**Comment by BirkhoffLee** [comment]
fyi 剛剛測試 Surge 的增強模式 DNS，解析 `*.local 或者 没有二级域名(类似 abcdef)` 都是返回 fake ip

**Comment by xjasonlyu** [comment]
@BirkhoffLee 对的，所以我在开着Surge增强模式的时候在Network里打不开SMB。

**Comment by AnyoeDove** [comment]
Surge 的 [Misc Options](https://manual.nssurge.com/others/misc-options.html) 中有一个配置项 `always-real-ip` , 会对配置的主机名返回真实 IP 地址。或许 clash 也可以考虑添加一下。

**Comment by Fndroid** [comment]
dns里维护一个real-ip列表看起来比较优雅

**Comment by Dreamacro** [comment]
如果 fake ip 支持 host 呢

**Comment by Kr328** [comment]
@Dreamacro 要使用 netbios 的话 就需要 DNS 返回错误

**Comment by Dreamacro** [comment]
Now fakeip only works in A or AAAA type

**Comment by Dreamacro** [comment]
maybe already fixed

**Comment by cyanlink** [comment]
此问题是否现在又出现了？我使用的是CFW的默认TUN模式设置（fake-ip），如果开启TUN，则无法连接到samba服务器，log处显示dial failed。我可以新开启一个issue来进一步描述这个问题和提供信息。我的子网是192.168.31.0。
```
17:27:30 WRN [TCP] dial failed error=dial tcp4 192.168.164.1:139: i/o timeout proxy=🎯 全球直连 rAddr=192.168.164.1:139 rule=IPCIDR rulePayload=192.168.0.0/16
17:27:30 WRN [TCP] dial failed error=dial tcp4 192.168.43.1:445: i/o timeout proxy=🎯 全球直连 rAddr=192.168.43.1:445 rule=IPCIDR rulePayload=192.168.0.0/16
17:27:30 WRN [TCP] dial failed error=dial tcp4 192.168.253.1:139: i/o timeout proxy=🎯 全球直连 rAddr=192.168.253.1:139 rule=IPCIDR rulePayload=192.168.0.0/16
```
