### ISSUE TITLE
[Question] Howto Shadowsocks

### ISSUE THREAD

**Issue by bcookatpcsd** [Dreamacro/clash#2421]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash v1.11.12-1-gde264c4 linux amd64 with go1.19.3

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
looking for a working configuration.. I cannot find or create a working configuration in English.
```

### Description

iPhone or Android or PC.. with a shadowsocks client; trying to configure clash as a shadowsocks server.  I understand the provided configuration file is mainly a reference, but, a basic working configuration I cannot find or create.

Thank you in advance.

**Comment by BirkhoffLee** [comment]
Clash cannot be configured to run a shadowsocks server.
