### ISSUE TITLE
[Feature] It is recommended to provide Android version of the client, or to use cross-platform frameworks for development, such as flutter

### ISSUE THREAD

**Issue by BraveHL** [Dreamacro/clash#2422]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

It is recommended to provide Android version of the client, or to use cross-platform frameworks for development, such as flutter

**Comment by BirkhoffLee** [comment]
For the Android variant, see https://github.com/Kr328/ClashForAndroid.
