### ISSUE TITLE
[Question]  Why the "www.clash.one" error?

### ISSUE THREAD

**Issue by lijoe123** [Dreamacro/clash#2424]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

您好！！！！为什么www.clash.one 今天上不上去了，然后clash app 也连不上了，怎么办呢？

**Comment by haohao145** [comment]
I also encountered this problem

**Comment by techblack** [comment]
www.clash.one 是一家订阅链接提供商（看起来跑路了），并且以名字混淆了与clash的关系，**和本项目无任何关系**。

**Comment by lijoe123** [comment]
那请问该怎么找订阅链接呢？
谢谢您！！！！

**Comment by lijoe123** [comment]
@haohao145 Do you know the **twitter ID** of [www.clash.one](http://www.clash.one/) ?

**Comment by jess9997** [comment]
clash APP 发生什么了 节点无法更新
