### ISSUE TITLE
[Feature] 怎么在macos安装clash

### ISSUE THREAD

**Issue by ioriandy4** [Dreamacro/clash#2426]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

下载darwin安装包后，解压是一个没有后缀的文件，macos怎么安装？？我的mac是m1的cpu
![image](https://user-images.githubusercontent.com/7553775/202892894-8ba22e08-c7c3-4116-bbf8-189f8bd76ddf.png)

**Comment by Infatuation-Fei** [comment]
这只是内核，你可以去下载ClashX或者Clash For Windows的Mac版
