### ISSUE TITLE
期待clash增加对naiveproxy 协议的支持[Feature] 

### ISSUE THREAD

**Issue by alvisxinbin** [Dreamacro/clash#2427]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

一直用clash 用了很多年，非常喜欢。近来用了naiveproxy 搭建节点后发现clash不支持这个协议，因为naiveproxy的安全性比较高，现在翻墙用这个的人也越来越多了，期盼clash能够支持这个协议。
如果有需求的朋友积极给我回帖，让技术团队看到我们的心声。谢谢。

**Comment by Dreamacro** [comment]
Duplicate of #706
