### ISSUE TITLE
Improvement: Resolve real SRV records for fake-ip mode

### ISSUE THREAD

**Issue by BirkhoffLee** [Dreamacro/clash#243]
> A Service record (SRV record) is a specification of data in the Domain Name System defining the location, i.e., the hostname and port number, of servers for specified services.

Therefore, there's no point to resolve a SRV record to a fake IP which is what Clash currently does. And this behavior also affects, for example, Teamspeak, which uses SRV records to resolve server addresses. This potentially affects more applications like Minecraft and some other games if Clash is used in TAP devices/transparent proxy.

A reasonable solution is to simply resolve the SRV record thru a real DNS server, and return it to the user, which is what Surge does here.

**Comment by Dreamacro** [comment]
Now fakeip only works in A or AAAA type

**Comment by babylife** [comment]
will Reidr-Host support srv record ,and how to configurate it ?
