### ISSUE TITLE
[Feature] Add ws & tls Vmess support

### ISSUE THREAD

**Issue by Airuop** [Dreamacro/clash#2432]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hello
When we select vmess with ws & tls options
We cannot connect to the server
Error: x509: Cannot verify certificate for 130.11.xx.xx because it does not contain any SAN IP

### Possible Solution

Please Add ws & tls Vmess support

**Comment by Dreamacro** [comment]
Look https://github.com/Dreamacro/clash/wiki/Configuration carefully
