### ISSUE TITLE
Wiki中缺少关于proxy provider filter的说明

### ISSUE THREAD

**Issue by ktmzcpl** [Dreamacro/clash#2433]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

https://github.com/Dreamacro/clash/pull/1511 merge后已过一年，但wiki中并未对其进行说明。
若非偶然浏览到，会以为没有此功能。

如果详细说明过于麻烦，至少给一个指向该pr的链接？

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/Configuration#proxy-providers 简单加了一行
