### ISSUE TITLE
[Question] Premium版本匹配rule的算法和开源版本一样吗？

### ISSUE THREAD

**Issue by njpig** [Dreamacro/clash#2435]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Premium版本匹配rule的算法和开源版本一样吗？

如果不是，请问Premium版本使用的是什么算法？

**Comment by BirkhoffLee** [comment]
你遇到什么问题

**Comment by njpig** [comment]
学习一下，没遇到什么问题
