### ISSUE TITLE
[Feature] clash.razord.top的标题位置太少

### ISSUE THREAD

**Issue by laughtLOOL** [Dreamacro/clash#2436]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

![image](https://user-images.githubusercontent.com/83571492/204081647-71db277c-2f0a-48d0-9af1-a4654823dc11.png)
横着的网页标题的位置只有5个格子，太难受了有些策略名字长会显示缩略的...
而竖版能显示全
![image](https://user-images.githubusercontent.com/83571492/204081801-3d60fda4-241a-49d4-9652-009a86241bb9.png)

路由器的版本也是这样，求能像连接那样能调整位置或着把位置挪宽一点
![image](https://user-images.githubusercontent.com/83571492/204081733-435cb443-8abb-4c59-bf12-90b0619affa0.png)

### Possible Solution

![image](https://user-images.githubusercontent.com/83571492/204081832-5d5f3aa5-4375-4bd9-abff-f8995e0d19f1.png)
目前是只能在元素里把这个数值调大，显示的效果就能看全了
![image](https://user-images.githubusercontent.com/83571492/204081879-d3594939-90db-4d8e-86fb-6c14157dc43a.png)

**Comment by SplitGemini** [comment]
你提的不是这个仓库的内容

**Comment by laughtLOOL** [comment]
> 
我看见这里有讨论这个网页的问题所以也在这里说了

**Comment by pfangzhi** [comment]
有没有可能是你的设备不行，我1080p显示器显示这个页面每行十个节点信息空余的还很大，如果你用1280类的显示器看的话那最多可能就显示四五个节点框框。
