### ISSUE TITLE
[Super Bad] Windows和Xbox拒绝域名解析得到的IP，无法上网 

### ISSUE THREAD

**Issue by yykhysn** [Dreamacro/clash#244]
当客户端（Windows电脑）发出DNS请求时，服务器端将返回保留地址的假IP/Fake IP﻿。随后客服端向假IP发起的流量（如正常IP一样连接）被转到服务器端，服务器端进行映射并向真实IP发起连接。

但当Windows收到保留地址/假IP的应答时，会认为域名无法解析，不向假IP发起连接。所以此种网络环境中，不管是浏览器，其他应用程序或者操作系统本身，都无法访问网络，如果这网络需要域名解析的话。

Windows太聪明了，知道DNS解析得到的是假的IP ，不像其他终端，包括手机、电视、游戏机及非Windows电脑那样，能正常访问网络。

请问这是普遍的问题还是我自己的问题，如果只是我自己的问题，请告诉我如何解决。快帮帮我，求你了，我快绝望死了。

**Comment by Dreamacro** [comment]
我没有 windows 的机子，没法验证你说的 `但当 Windows 收到保留地址/假 IP 的应答时，会认为域名无法解析，不向假 IP 发起连接。`

而且 `Windows 太聪明了，知道 DNS 解析得到的是假的 IP，不像其他终端，包括手机、电视、游戏机及非 Windows 电脑那样，能正常访问网络。` 这么处理我不觉得是太聪明了，而是自作聪明了。

**Comment by Joey-996** [comment]
> 我没有 windows 的机子，没法验证你说的 `但当 Windows 收到保留地址/假 IP 的应答时，会认为域名无法解析，不向假 IP 发起连接。`
> 
> 而且 `Windows 太聪明了，知道 DNS 解析得到的是假的 IP，不像其他终端，包括手机、电视、游戏机及非 Windows 电脑那样，能正常访问网络。` 如果 windows 真的这么处理的话我不觉得是太聪明了，而是自作聪明了。

我也出现了这个问题,我只要开启clash,本地解析的就不能访问,后来我用规则把解析的地址后缀为.test的域名direct,我查看过日志确实走向diret,然后完美解决了,但是近期出了0.6.3更新了最新版本,我把家里的更新了,结果尽管direct 但是都还是失效打开本地解析的域名失败,查过日志也没问题,后来降级为0.0.35还是不可以.不知道什么原因

**Comment by xjasonlyu** [comment]
windows似乎不处理类似`198.18.0.0/16`，`240.0.0.0/8`的保留段ip，你把fake-ip的范围改成不和内网段冲突的，例如`10.123.0.0/16`就能解决问题。（未在clash上实测过，但是tun2socks有过这样的问题就是这么解决的）

**Comment by yykhysn** [comment]
> windows似乎不处理类似`198.18.0.0/16`，`240.0.0.0/8`的保留段ip，你把fake-ip的范围改成不和内网段冲突的，例如`10.123.0.0/16`就能解决问题。（未在clash上实测过，但是tun2socks有过这样的问题就是这么解决的）

怎么修改，我在yml的配置文件写上fake-ip-range: 10.123.0.0/16，可解析域名还是198的IP  @xjasonlyu

**Comment by xjasonlyu** [comment]
那就是你配置哪里出错了。

**Comment by yykhysn** [comment]
> windows似乎不处理类似`198.18.0.0/16`，`240.0.0.0/8`的保留段ip，你把fake-ip的范围改成不和内网段冲突的，例如`10.123.0.0/16`就能解决问题。（未在clash上实测过，但是tun2socks有过这样的问题就是这么解决的）

这样修改后，问题还是没解决。 @xjasonlyu

**Comment by BuerFang** [comment]
介绍我的情况：
我是用的是 openclash，并且在内网搭建了 AdGuard DNS， 所以在设置中自定义了上游dns，
开启Fake-ip 模式window和你是一样的问题，所有的域名都无法解析。
我先把 AdGuard DNS从自定义DNS中去除了， 发现chrome可以正常访问网络了，但是ie还是无法正常使用。然后我重启了电脑，ie也可以正常使用了。
后面测试了一次，每次我把openclash的模式切换到另外一个模式，如果电脑此时是开机的，都需要重启一次，ie才正常解析。
希望对你有帮助。

**Comment by yykhysn** [comment]
我理解你的意思是，Windows每次连接网络进行的检查，一旦检查通过了，之后上游网关变化，它不管。所以电脑启动时，关闭Clash，而后Windows确认网络无误后，将Clash开启。聪明如你，机智过人，这样就骗过了Windows。
          顺便一提，不重启电脑只重启网络试试——有线的话控制面板重启网卡，无线的就断开、重连WIFI，这样比电脑重启快不少。 @BuerFang 

        对于这个issue，我最开始认为Windows有DNS Rebind Protection的机制，会丢弃不可路由的IP，但我把FAKE IP的范围写成了正常公网IP，问题也依然存在。接着我开始怀疑ICMP，Windows检查网络时会进行Ping的检查，于是我在上游路由器上把Fake IP网段的ICMP劫持了，仍然无解。现在结合Xbox上的错误提示，服务不可达，怀疑Windows在做的是一个UDP检查。

        以上就是我目前所进行过的尝试和进展，还望对大家有帮助。
        谢谢各位

**Comment by yykhysn** [comment]
使用lru cache-store fake-ip后，Windows及Xbox无法解析域名的问题得到解决。期待尽早支持Fake IP的UDP响应以及UDP的透明代理。Clash is so Awesome!

**Comment by Yohoa** [comment]
> 我理解你的意思是，Windows每次连接网络进行的检查，一旦检查通过了，之后上游网关变化，它不管。所以电脑启动时，关闭Clash，而后Windows确认网络无误后，将Clash开启。聪明如你，机智过人，这样就骗过了Windows。
> 
> 顺便一提，不重启电脑只重启网络试试——有线的话控制面板重启网卡，无线的就断开、重连WIFI，这样比电脑重启快不少。 @BuerFang
> 
> 对于这个issue，我最开始认为Windows有DNS Rebind Protection的机制，会丢弃不可路由的IP，但我把FAKE IP的范围写成了正常公网IP，问题也依然存在。接着我开始怀疑ICMP，Windows检查网络时会进行Ping的检查，于是我在上游路由器上把Fake IP网段的ICMP劫持了，仍然无解。现在结合Xbox上的错误提示，服务不可达，怀疑Windows在做的是一个UDP检查。
> 
> 以上就是我目前所进行过的尝试和进展，还望对大家有帮助。
> 
> 谢谢各位

原来是这样，看来我遇到过的XBOX 在设置里“所有服务均可用”，而在主菜单说“连接到Xbox Live”问题，就是上游未能处理UDP 流量所导致的了。多谢你的探索和实验！

**Comment by heavenkiller2018** [comment]
那怎么解决呢？而且也出现类似的局域网用openclash做旁路由， 其他都OK，就微信显示"当前网络不稳定，请检查你的网络设置"， 应该也同样是这个原理吧？

**Comment by lambdaplus** [comment]
参考 [https://github.com/vernesong/OpenClash/issues/2050](url)
启用fallback ，添加这四行
`

  '*.msftconnecttest.com'
  '*.msftncsi.com'
  'msftconnecttest.com'
  'msftncsi.com'

`

整体如下


`

fallback:
    - tls://8.8.8.8:853 # Google
    - tls://1.1.1.1 # cloudflare
    - https://1.1.1.1/dns-query # cloudflare
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '*.msftconnecttest.com'
      - '*.msftncsi.com'
      - 'msftconnecttest.com'
      - 'msftncsi.com'
      
 `

**Comment by twbworld** [comment]
## 我已解决, 方法:

![image](https://github.com/vernesong/OpenClash/assets/52546134/a83cd2a2-0312-43bc-ad62-e1f65a5f57d6)
### 从这受到启发:
https://github.com/vernesong/OpenClash/issues/6
