### ISSUE TITLE
[Bug] Clash Premium TUN模式，当代理服务器为本地环回地址，且设置auto-detect-interface时，UDP全部丢包且不报错

### ISSUE THREAD

**Issue by ssz66666** [Dreamacro/clash#2442]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Premium 2022.11.25

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:12345
secret: ""
mode: rule
ipv6: false
log-level: debug

proxies:
  - name: Proxy
    type: ss
    server: 127.0.0.1
    port: 8388
    udp: true
    cipher: chacha20-ietf-poly1305
    password: "password"
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true # auto set global route
  auto-detect-interface: true # conflict with interface-name
dns:
  enable: true
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
rules:
- MATCH, Proxy
```

### Clash log

```shell
> .\clash-windows-amd64.exe -f  .\config.yml
22:58:49 INF [API] listening addr=127.0.0.1:12345
22:58:49 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
22:58:49 INF [Inbound] TUN listening iface=Clash gateway=198.18.0.1
22:58:49 DBG [TUN] hijack udp dns addr=198.18.0.2:53
22:58:49 DBG [DNS] dns response source=114.114.114.114:53 qType=A name=www.msftconnecttest.com. answer=["23.220.255.17","23.220.255.6"]
22:58:49 DBG [TCP] accept connection lAddr=198.18.0.1:58759 rAddr=www.msftconnecttest.com:80 inbound=TUN
22:58:49 INF [TCP] connected lAddr=198.18.0.1:58759 rAddr=www.msftconnecttest.com:80 mode=rule rule=Match() proxy=Proxy
...
22:59:14 DBG [UDP] accept session lAddr=198.18.0.1:52597 rAddr=8.8.8.8:53 inbound=TUN
22:59:14 INF [UDP] connected lAddr=198.18.0.1:52597 rAddr=8.8.8.8:53 mode=rule rule=Match() proxy=Proxy
22:59:16 DBG [UDP] accept session lAddr=198.18.0.1:52602 rAddr=8.8.8.8:53 inbound=TUN
22:59:16 INF [UDP] connected lAddr=198.18.0.1:52602 rAddr=8.8.8.8:53 mode=rule rule=Match() proxy=Proxy
22:59:18 DBG [UDP] accept session lAddr=198.18.0.1:52604 rAddr=8.8.8.8:53 inbound=TUN
22:59:18 INF [UDP] connected lAddr=198.18.0.1:52604 rAddr=8.8.8.8:53 mode=rule rule=Match() proxy=Proxy
22:59:20 DBG [UDP] accept session lAddr=198.18.0.1:52606 rAddr=8.8.8.8:53 inbound=TUN
22:59:20 INF [UDP] connected lAddr=198.18.0.1:52606 rAddr=8.8.8.8:53 mode=rule rule=Match() proxy=Proxy
22:59:22 DBG [UDP] accept session lAddr=198.18.0.1:52608 rAddr=8.8.8.8:53 inbound=TUN
22:59:22 INF [UDP] connected lAddr=198.18.0.1:52608 rAddr=8.8.8.8:53 mode=rule rule=Match() proxy=Proxy
```

## 问题描述/使用场景
使用Clash Premium TUN模式，当代理服务器为本地环回地址，且设置`auto-detect-interface: true`时，TCP能正常转发但UDP会全部丢包。
```
> nslookup google.com 8.8.8.8
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时
```
如果使代理服务器监听在`0.0.0.0:PORT` / `[::]:PORT`，并将Clash配置的代理服务器地址改为非本地环回地址的其他地址（如网卡局域网地址），则UDP转发正常。

同一问题issue：https://github.com/Fndroid/clash_for_windows_pkg/issues/3370

### 典型使用场景
希望利用Clash的规则分流功能和TUN模式，将一个提供了SOCKS5接口的第三方代理软件转换成全局代理，用于游戏/WebRTC等需要UDP通信的场景。

## 复现方法
1. 手动配置在本地环回地址（127.0.0.1）配置一socks5或者shadowsocks服务器（提前绑定上行接口，确保不会出现路由环路）。
2. 使用Clash Premium 2022.11.25，连接1.中配置的代理服务器，并开启TUN模式。在配置中，开启TUN选项里的`auto-detect-interface`选项。DNS选项中开启`fake-ip`模式。
3. 打开浏览器，发现**TCP流量可正常转发**。
4. 尝试UDP协议应用（如使用`nslookup google.com 8.8.8.8`），发现无法正常转发。
  a. 日志中没有任何UDP包发送失败的报错。
  b. netstat发现客户端每用一个新端口发送UDP报文，clash就会正常监听新的随机UDP端口`0.0.0.0:port`。根据日志判断`ListenPacketContext`应该执行成功了。
  c. Wireshark抓包发现，部署在本地环回地址的代理服务器没有收到clash的任何UDP报文。TCP报文则完全正常。

## 其他发现
1. **若关闭TUN模式中的`auto-detect-interface`选项，则UDP流量能够正常转发。**
2. 开启`auto-detect-interface`选项，但使用DIRECT模式时，UDP流量能够正常转发。
3. 代理服务器地址不是本地环回地址时，UDP流量能够正常转发。

因为涉及Clash Premium的闭源部分功能（TUN模式），故放弃进一步诊断，先提交issue。

**Comment by ertuil** [comment]
我这边也发现并复现了相关问题

**Comment by ssz66666** [comment]
测试Premium 2023.03.18版本已修复此问题。
