### ISSUE TITLE
[Feature] zerotier或者easyConnet使用vpn时域解析后进不到vpn

### ISSUE THREAD

**Issue by skill7899** [Dreamacro/clash#2446]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

mac clashx  目前环境是easyConnet连上的vpn，然后访问的地址是一个域名地址这个域名访问解析出来的ip是要经vpn才能访问。但是经过了clash后，因为不会再走一次路由表，所以他会从en0直接出去了，导致访问不成功。zerotier也是一样的问题。希望加一个选项规则功能，指定一些域名解析出来IP后，流回到路由表。

**Comment by lee-cq** [comment]
Wiki中有提到 Clash流量从哪一个接口出站可以尝试一下： interface-name: en0
https://github.com/Dreamacro/clash/wiki/Configuration

**Comment by skill7899** [comment]
> Wiki中有提到 Clash流量从哪一个接口出站可以尝试一下： interface-name: en0 将此配置指定到为 ZeroTier 的虚拟接口名称。 https://github.com/Dreamacro/clash/wiki/Configuration

这个是统一的口，我要是指定的就成了我其它的上不了网了。特别有多个vpn的时候。这种指定不行的。

**Comment by ElemenTP** [comment]
> > Wiki中有提到 Clash流量从哪一个接口出站可以尝试一下： interface-name: en0 将此配置指定到为 ZeroTier 的虚拟接口名称。 https://github.com/Dreamacro/clash/wiki/Configuration
> 
> 这个是统一的口，我要是指定的就成了我其它的上不了网了。特别有多个vpn的时候。这种指定不行的。

分流规则中可以设置某组使用特定interface
[Configuration/proxy-groups](https://github.com/Dreamacro/clash/wiki/Configuration#:~:text=%23%20direct%20to%20another%20infacename%20or%20fwmark%2C%20also%20supported%20on%20proxy%0A%20%20%2D%20name%3A%20en1%0A%20%20%20%20type%3A%20select%0A%20%20%20%20interface%2Dname%3A%20en1%0A%20%20%20%20routing%2Dmark%3A%206667%0A%20%20%20%20proxies%3A%0A%20%20%20%20%20%20%2D%20DIRECT)

**Comment by Wrandz** [comment]
我开vpn的时候，访问校内服务器，是可以的，情况似乎和你一样啊。我在clash中能看到我访问了该服务器，并且似乎最终所有的流量都走VPN了。就算我访问google，也是先走vpn，从校内过一趟，再到节点服务器。

**Comment by skill7899** [comment]
> > > Wiki中有提到 Clash流量从哪一个接口出站可以尝试一下： interface-name: en0 将此配置指定到为 ZeroTier 的虚拟接口名称。 https://github.com/Dreamacro/clash/wiki/Configuration
> > 
> > 
> > 这个是统一的口，我要是指定的就成了我其它的上不了网了。特别有多个vpn的时候。这种指定不行的。
> 
> 分流规则中可以设置某组使用特定interface [Configuration/proxy-groups](https://github.com/Dreamacro/clash/wiki/Configuration#:~:text=%23%20direct%20to%20another%20infacename%20or%20fwmark%2C%20also%20supported%20on%20proxy%0A%20%20%2D%20name%3A%20en1%0A%20%20%20%20type%3A%20select%0A%20%20%20%20interface%2Dname%3A%20en1%0A%20%20%20%20routing%2Dmark%3A%206667%0A%20%20%20%20proxies%3A%0A%20%20%20%20%20%20%2D%20DIRECT)
> 
> ```yaml
> proxy-groups:
>   # direct to another infacename or fwmark, also supported on proxy
>   - name: en1
>     type: select
>     interface-name: en1
>     routing-mark: 6667
>     proxies:
>       - DIRECT 
> ```

这个我试了不行，不知道是不是mac不生效。另外这样指定interface-name的话，每次zerotier或者easyConnet生成的虚拟口都不是指定名称的。也不灵活

**Comment by BirkhoffLee** [comment]
> 这个我试了不行，不知道是不是mac不生效

dial failed 说明你的这个 feth4415 访问不到 192.168.60.10

> 每次zerotier或者easyConnet生成的虚拟口都不是指定名称的。也不灵活

只能这样，Clash 也没法帮你通灵到底是哪个 interface

**Comment by skill7899** [comment]
> > 这个我试了不行，不知道是不是mac不生效
> 
> dial failed 说明你的这个 feth4415 访问不到 192.168.60.10
> 
> > 每次zerotier或者easyConnet生成的虚拟口都不是指定名称的。也不灵活
> 
> 只能这样，Clash 也没法帮你通灵到底是哪个 interface

其实可以再出去走一次路由表的
