### ISSUE TITLE
clash_pro 增强模式 icmp

### ISSUE THREAD

**Issue by spacexnasa** [Dreamacro/clash#2448]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.11.25

### Clash config

```yaml
redir-port: 3127
mixed-port: 3129
external-controller: 127.0.0.1:9090
.....
```

### Clash log

```shell
没有错误日志
```

### Description

其他机器比如没有安装 clash 的，或者不开启增强模式,ping 2.2.2.2，是不通的，但是开启了增强模式，ping 什么 ip 都通，这个是啥问题

**Comment by ElemenTP** [comment]
https://github.com/Dreamacro/clash/issues/1416#issuecomment-846383012
clash仅代理TCP和UDP流量，TUN网卡对收到的ICMP包的处理是直接回复

**Comment by spacexnasa** [comment]
> [#1416 (comment)](https://github.com/Dreamacro/clash/issues/1416#issuecomment-846383012)
> clash仅代理TCP和UDP流量，TUN网卡对收到的ICMP包的处理是直接回复

好的，谢谢，我看 icmp 既不是 tcp 也不是 udp，如果收到 icmp，直接回复那就解释的通了
