### ISSUE TITLE
[Feature] May I ask about the difference between amd64 and amd64-v3?

### ISSUE THREAD

**Issue by imxys** [Dreamacro/clash#2452]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [x]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

I don't know why amd64 and amd64-v3 versions are there in Releases.

I cannot find a good answer on google, even though I remember seeing it once before... Like v3 version supports a new instructions sets or something?

I try to know this by opening "issues -> open discussions" page but only with a 404 page...
https://github.com/Dreamacro/clash/discussions

Which version should I download?

Sorry for my poor English, Here is my Chinese meaning:
我不知道amd64跟amd64-v3有什么区别。
谷歌百度比应好像都没找到东西，虽然印象里以前看到是v3支持了什么指令集？
我想点开issure页面的讨论，但是只能看到404
所以应该下载哪个版本，还是都差不多？

### Possible Solution

Add a new page on wiki, or explain the difference between amd64 and amd64-v3, which will help me select the version to use.
Thanks a lot!

**Comment by ElemenTP** [comment]
amd64版兼容所有amd64处理器，amd64-v3版仅兼容支持AVX2指令集及以上的amd64处理器。后者在支持的处理器上，性能会强于前者
