### ISSUE TITLE
[Question] 如何实现将一个网关的流量传递到另外一个网关上进行透明代理？

### ISSUE THREAD

**Issue by x2c3z4** [Dreamacro/clash#2457]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

latest

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
N/A
```

### Clash log

```shell
N/A
```

### Description

需求：
Node A 192.168.2.10/24
Node B 192.168.3.10/24

Node A，Node B 分别作为对应子网的网关。
现在 Node A 上启动 clash，redir-port 监听 7892.

Node A 上 iptables nat 表如下:
```
...
-A PREROUTING -p tcp -j CLASH_EXTERNAL
-A POSTROUTING -o ens192 -j MASQUERADE
-A CLASH_EXTERNAL -d 0.0.0.0/8 -j RETURN
-A CLASH_EXTERNAL -d 127.0.0.0/8 -j RETURN
-A CLASH_EXTERNAL -d 224.0.0.0/4 -j RETURN
-A CLASH_EXTERNAL -d 172.16.0.0/12 -j RETURN
-A CLASH_EXTERNAL -d 127.0.0.0/8 -j RETURN
-A CLASH_EXTERNAL -d 169.254.0.0/16 -j RETURN
-A CLASH_EXTERNAL -d 240.0.0.0/4 -j RETURN
-A CLASH_EXTERNAL -d 192.168.0.0/16 -j RETURN
-A CLASH_EXTERNAL -d 10.0.0.0/8 -j RETURN
-A CLASH_EXTERNAL -p tcp -j REDIRECT --to-ports 7892
...
```
可以完美透明代理。
现在*不*在 Node B 上不启动 clash，且想将透明代理流量转到 A 的 7892 端口来完成访问，并将响应发回到 B 的子网机器，如何做呢？

**Comment by BirkhoffLee** [comment]
node b 设置 default route 到 node a
