### ISSUE TITLE
[Bug] Premium 2022.11.25内核使用tun模式+dns增强模式为redir-host情况下，走代理的网站mapping失败，出现非安全连接错误

### ISSUE THREAD

**Issue by ericsyj** [Dreamacro/clash#2459]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.11.25

### What OS are you seeing the problem on?

Windows, Linux

### Clash config

```yaml
dns:
  enable: true
  ipv6: true
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - tls://223.6.6.6
```

### Clash log

```shell
clash log无任何报错
```

### Description

在最新的Premium 2022.11.25内核中，在使用tun模式+dns增强模式为redir-host情况下，走代理的许多网站大量出现非安全连接的隐私错误，而国内直连的网站无问题，同样的节点和配置使用clash.meta内核和开源v1.7.1内核就没问题，本人在openwrt的shellclash（尝试meta内核、premium内核、开源内核）以及windows下的clash for windows（premium内核）和clash verge（meta内核）进行尝试，发现只有premium内核出现此错误，目前不知道是什么原因导致了mapping失败，clash的日志上并任何没有报错。
![image](https://user-images.githubusercontent.com/97294040/206744788-40b1fe3b-060d-463e-8073-18a56d6fd120.png)

**Comment by Dreamacro** [comment]
redir-host 不建议用，也不解决相关的问题
