### ISSUE TITLE
[Question] 请问下哪里能够下载到 2021.12.07 的 Premium 版本呢？

### ISSUE THREAD

**Issue by gotounix** [Dreamacro/clash#2460]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

请问下哪里能够下载到 2021.12.07 的 Premium 版本呢？谢谢！

**Comment by Karmylr** [comment]
https://release.dreamacro.workers.dev/

**Comment by gotounix** [comment]
@Karmylr 这里面都是2022的啊，没有2021的啊？！你怎么找到2021的？

**Comment by Karmylr** [comment]
> @Karmylr 这里面都是2022的啊，没有2021的啊？！你怎么找到2021的？

不好意思，看错了，以为你要最新的
