### ISSUE TITLE
[Feature] 我的onedrive同步把我的流量全部耗尽了, 555, 请问如何让onedrive不代理

### ISSUE THREAD

**Issue by shawchen123** [Dreamacro/clash#2462]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我的onedrive同步把我的流量全部耗尽了, 555, 请问如何让onedrive不代理

**Comment by QS0x01** [comment]
[v](https://github.com/Dreamacro/clash/wiki/Configuration)

**Comment by ViperThanks** [comment]
> > https://github.com/Dreamacro/clash/wiki/Configuration
> 
> 我看不懂"^"

那就从源头上找问题,找一个多一点流量的机场咯

**Comment by sceraser** [comment]
找一个支持onedrive分流的规则
