### ISSUE TITLE
请求添加snell v4.0支持 

### ISSUE THREAD

**Issue by zmywxx** [Dreamacro/clash#2466]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

https://manual.nssurge.com/others/snell.html
请求增加对snell v4的支持

**Comment by Dreamacro** [comment]
```

The Snell protocol is intended for Surge users only. Please do not reverse-analyze the protocol and make a compatible client of it. We want to keep the user base as small as possible, thanks for understanding.

```
