### ISSUE TITLE
[Question] tun模式性能问题

### ISSUE THREAD

**Issue by Zhuangkh** [Dreamacro/clash#2467]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在Debian下使用clash以tun模式`stack: system`作为旁路由供局域网内其他设备使用，cpu 为amd 2200G.

日常场景千兆宽带测试300M左右速度，降低其余cpu负载后可测得接近400M速度(直通不过clash可跑满).

请问tun有无优化的可能？又或者什么性能的cpu才可能跑满😂

**Comment by Zhuangkh** [comment]
相关issue https://github.com/Dreamacro/clash/issues/1405

去年的讨论中似乎没有解决方案，不知道有没有任何新看法

**Comment by Dreamacro** [comment]
cpu 不太好可以打开 auto-redir 来降低 tcp 负载

**Comment by Zhuangkh** [comment]
@Dreamacro 
测试了auto-redir选项, 确实能降低一定负载, 测速也高了100兆左右, 但仍和理想带宽差距较大. 是否还有其它可能的方案供参考尝试?

**Comment by Zhuangkh** [comment]
> HTTP代理还不行就没办法了

我个人理解是HTTP代理不大适合作为旁路网关🤨

**Comment by xuan880** [comment]
> @Dreamacro 测试了auto-redir选项, 确实能降低一定负载, 测速也高了100兆左右, 但仍和理想带宽差距较大. 是否还有其它可能的方案供参考尝试?

你要不试试不用auto-redir参数来设置,而是通过iptables直接转发,我就没有通过auto-tun和auto-redir来设置透明代理,而是通过iptables来设置的,用的是斐讯n1,tcp跑满带宽不是问题.UPD走tun的话倒是依旧只有100M左右.
