### ISSUE TITLE
[Bug] 不支持 shadowsocks 的 http 混淆

### ISSUE THREAD

**Issue by xpader** [Dreamacro/clash#2468]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.11.12

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxies:
  - name: "SS"
    type: ss
    server: 12.33.45.66
    port: 8080
    password: "shadowpass"
    cipher: aes-128-gcm
    plugin: obfs
    plugin-opts:
      mode: http
      host: test.example.com
      path: "/mm/"
```

### Clash log

```shell
time="2022-12-16T16:39:57Z" level=info msg="[TCP] 192.168.1.23:59911 --> www.google.com:443 using GLOBAL"
time="2022-12-16T16:39:57Z" level=info msg="[TCP] 192.168.1.23:59914 --> www.google.com:443 using GLOBAL"
```

### Description

该配置在 xray/v2ray 的 outbound 配置示例如下：
```
{
      "tag": "proxy",
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "12.33.45.66",
            "method": "aes-128-gcm",
            "ota": false,
            "password": "shadowpass",
            "port": 8080,
            "level": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "/mm/"
              ],
              "headers": {
                "Host": [
                  "test.example.com"
                ],
                "User-Agent": [
                  "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                ],
                "Accept-Encoding": [
                  "gzip, deflate"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache"
              }
            }
          }
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    }
```
在 v2ray 中是可以正常连接的，在 iOS 的 Shadowrocket 里也只是添加 Shadowsocks 配置后在混淆里选择 http 填上 Host 和 Path 就可以了。
但是在 Clash 中按如上的方式配置后并不能连接成功。

**Comment by xpader** [comment]
Clash 放弃治疗了吗？

**Comment by UjuiUjuMandan** [comment]
simple-obfs 不支持设置 path 吧，我在[这里](https://github.com/shadowsocks/simple-obfs )都没看到。
我下载了 [Android 版本的 simple-obfs](https://github.com/shadowsocks/simple-obfs-android)，也没有设置 path 的地方捏。
另外，这个插件都被弃用了，为什么不用 [v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin) ？

**Comment by BirkhoffLee** [comment]
> Clash 放弃治疗了吗？

代码都是开源的，你可以自己写
