### ISSUE TITLE
[Bug]?1.10版本DNS解析错误 

### ISSUE THREAD

**Issue by wlhgtc** [Dreamacro/clash#247]
具体如下：
公司有VPN,指定了特定网址时(git.xxxx.com)解析DNS的服务器。
但是这个如果直接配置在网络偏好设置上，Clash是无法解析的。
但写在conf文件中可以解决。
对DNS服务器的访问是没问题的，且ping网址也可通，但是无法网页访问。
具体细节可见：https://github.com/yichengchen/clashX/issues/173
Mac系统，使用Clash-X
之前1.9版本是可以的，1.10+的新版本不行。
在Clash-X上提问，作者让来这里提issue。 @Dreamacro

**Comment by Dreamacro** [comment]
把内网 dns 加到 nameserver 里，或者干脆不用自定义 dns。

**Comment by wlhgtc** [comment]
目前就是把内网 dns 加到 nameserver 内部了。
不用的话上不去内网:(
但是由于是配置文件使用的是托管，所以每次都会更新覆盖掉，然后再手动添加，很麻烦。
因为之前的版本是可以识别网络偏好设置中配置的DNS的。
所以就像确认下，新版本的不识别是刻意为之还是bug？

**Comment by Dreamacro** [comment]
是个 feature，现在直连的域名解析也走 custom dns，如果你开了自定义 dns 的话

**Comment by wlhgtc** [comment]
thx，那我只能自己手动改了:<

**Comment by Dreamacro** [comment]
写一个简单的 API merge 配置呗

**Comment by wlhgtc** [comment]
@Dreamacro  能具体说一下吗，刚搞这个，不太懂

**Comment by wlhgtc** [comment]
@Dreamacro  抱歉，又来重新提这个问题了。
再更新Clash-X 1.10.1版本后，出现了内网DNS服务器和外网DNS服务器无法共存的问题：
1.如果内网和外网DNS服务器共存，则内网的请求是DNS failed。
2.只保留内网的DNS服务器，一切正常
同样的配置文件，Clash-X 1.10.0版本无此问题。
内网DNS:
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
  - 10.2.0.2
  - 10.1.0.2
  tls://dns.rubyfish.cn:853
  fallback:
  tls://1.1.1.1:853
  tls://1.0.0.1:853
  tls://dns.google:853
```




内网+外网DNS:
```
  dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
  -117.50.10.10
  -119.29.29.29
  -223.5.5.5
  - 10.2.0.2
  - 10.1.0.2
  tls://dns.rubyfish.cn:853
  fallback:
  tls://1.1.1.1:853
  tls://1.0.0.1:853
  tls://dns.google:853
```

想问下这个问题的原因。
