### ISSUE TITLE
[Feature] 更改TCP最长连接时间

### ISSUE THREAD

**Issue by WindowsMEMZ** [Dreamacro/clash#2477]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

如题，Clash似乎没有办法更改TCP最大连接时间，始终限制为120秒

**Comment by SakuraSakuraSakuraChan** [comment]
服务端决定的吧
