### ISSUE TITLE
[Question] create TUN interface on Windows without admin privilege?

### ISSUE THREAD

**Issue by toymil** [Dreamacro/clash#2482]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

On Windows, do users of group `Network Configuration Operators` have enough permission to create network adapter?  The description of the group says:
> Members in this group can have some administrative privileges to manage configuration of networking features

I have tried it on clash premium v`2022.11.25` with an account in the NCO group, and still got the error:
```
ERR [Inbound] start failed error=Error creating interface: Access is denied. type=TUN stackType=gvisor inet=198.18.0.1/16
```
Not sure if this is a program logic problem or users of NCO group actually don't have enough permission to create network adapter.

**Comment by toymil** [comment]
bump

**Comment by BirkhoffLee** [comment]
` Error creating interface: Access is denied`
You get it

**Comment by cmj2002** [comment]
I have a same issue. The problem occurs randomly on my computer and I haven't found a way to reproduce it yet. I have found the following error logs in `C:\Windows\INF\setupapi.dev.log`:

```
>>>  [Delete Device - SWD\WINTUN\{44393EFC-29C4-25E4-B684-F168B398A2B4}]
>>>  Section start 2023/10/25 08:09:28.902
      cmd: "C:\Users\[Redacted]\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64\clash-win64.exe" -d C:\Users\[Redacted]\.config\clash
!    dvi: Query-and-Remove failed: 0x05: CR_INVALID_DEVNODE.
<<<  Section end 2023/10/25 08:09:28.942
<<<  [Exit status: SUCCESS]
```

It seems that this is not just a permission issue, but maybe an incorrect call to the Windows device API. I will check the device tree and look for the cause the next time this issue occurs.
