### ISSUE TITLE
[Feature] 关于解决proxy-provider url 配置为订阅地址无法下载的问题

### ISSUE THREAD

**Issue by JMVoid** [Dreamacro/clash#2483]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在proxy-provider中URL使用机场订阅链接，在某些机场会无法完成远程拉取，直接报EOF的错误。

### Possible Solution

经过实现在, 在vehicle.go 的Read()中的http request中增加 User-Agent参数可以避免该问题.

**Comment by KevinXC5** [comment]
支持一下，这个问题困扰很久了，希望作者可以尽快修复一下，感谢！！
