### ISSUE TITLE
[Feature] TUN模式下设定本地局域网不走代理走直连

### ISSUE THREAD

**Issue by EliDoves** [Dreamacro/clash#2487]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

大佬们，请问一下Clash for windows开启了TUN模式clash接管系统流量之后，如何设置特定的ip或者域名不走代理呢，我配置好了TUN模式，可以正常工作，但有个问题我本地局域网都走了代理了，在配置文件里设置了cfw-bypass也不起作用

**Comment by Wrandz** [comment]
你是怎么做到用cfw的tun接管整个局域网的流量的？

**Comment by wheat0r** [comment]
cfw的话，可以试试用diff方式添加例外策略

**Comment by EliDoves** [comment]
> cfw的话，可以试试用diff方式添加例外策略

好的谢谢，我试试

**Comment by reuwi** [comment]
@Wrandz @wheat0r 请问我在规则列表里配置了局域网的ip直连，然后直接访问ip的时候是没问题的，但是访问这个ip对应的域名就匹配不到局域网ip直连规则，要怎么配置呢？
```
rules:
 - DOMAIN-SUFFIX,local,🎯 全球直连
 - IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve
 - IP-CIDR,10.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,172.16.0.0/12,🎯 全球直连,no-resolve
 - IP-CIDR,127.0.0.0/8,🎯 全球直连,no-resolve
 ```
日志：
```
2023/07/26 16:00:23.460  [debug]  [DNS] dns response source=172.16.40.25:53 qType=A name=aaa.com. answer=["172.18.78.169"]
2023/07/26 16:00:23.477  [info]  [TCP] connected lAddr=198.18.0.1:58126 rAddr=aaa.com:80 mode=rule rule=Match() proxy=🐟 漏网之鱼[V101 香港]
```
