### ISSUE TITLE
[Feature] bind-address支持绑定到多个地址

### ISSUE THREAD

**Issue by canoziia** [Dreamacro/clash#2488]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

当在有多个局域网地址的机器上运行clash的时候，只能监听一个地址，比较不方便，希望bind-address能用逗号分隔监听的多个地址

### Possible Solution

```
bind-address: "127.0.0.1,192.168.1.1"
```
大概像这样

**Comment by vcup** [comment]
您是否在找: `bind-address: "0.0.0.0"`

**Comment by canoziia** [comment]
> 您是否在找: `bind-address: "0.0.0.0"`

如果要绑定到所有地址只要`bind-address: "*"`就好了，问题是有公网的话又要做防火墙，挺麻烦的

**Comment by Misaka-0x447f** [comment]
希望能 bind-address: "192.168.1.1/24, 10.0.0.1/24"

**Comment by cnsino** [comment]
bind-address: "127.0.0.1,192.168.1.1"

**Comment by Dreamacro** [comment]
使用 #2818 即可
