### ISSUE TITLE
[Bug] script 模式 resolve_process_name 无法解析 WSA 中流量的进程名导致无法联网

### ISSUE THREAD

**Issue by 2-3-5-7** [Dreamacro/clash#2489]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.11.25 Premium

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
script:
  code: |
    def main(ctx, meta):
      if meta['type'] == 'TUN':
        ctx.log('--> [%s](%s) %s:%s -> %s:%s, HOST %s' % (meta['type'], meta['network'], meta['src_ip'], meta['src_port'], meta['dst_ip'], meta['dst_port'], meta['host']))
        proc = ctx.resolve_process_name(meta)
        ctx.log('--> 22')
```

### Clash log

```shell
09:58:18 INF [Script] --> [TUN](tcp) 198.18.0.1:10500 -> :80, HOST www.baidu.com
09:58:18 WRN [Script] find process path failed error=process not found lAddr=198.18.0.1:10500 rAddr=www.baidu.com:80
09:58:18 WRN [Metadata] parse failed error=process not found
```

### Description

Win11 开启 TUN，WSA(Windows Subsystem for Android) 中的应用都不能联网了。我记得之前版本不会挂掉，但没留意 resolve_process_name 的返回值。目前从日志上看调 resolve_process_name 后就挂了，22 没打印出来。

查到一个类似问题 [#1125](https://github.com/Dreamacro/clash/issues/1125) ，好像也没解决 resolve_process_name 报错后无法继续执行的问题？

补充：试了下 2022.08.26 Premium 没问题，[v 0.20.6](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.20.6)

**Comment by Dreamacro** [comment]
使用 latest premium

**Comment by 2-3-5-7** [comment]
大佬，你说的是这里的版本吗？https://release.dreamacro.workers.dev/latest/  ，这个只是 core，Clash for Windows 还没有修复的版本是吗？
