### ISSUE TITLE
如何配置global mode？

### ISSUE THREAD

**Issue by IsoaSFlus** [Dreamacro/clash#249]
readme里面的那个配置文件示范的是rule mode，我在网上也搜了一下，好像也没发现global的配置，请教一下global mode该如何配置？

**Comment by Dreamacro** [comment]
```yaml
mode: Global
```

通过 API 控制特殊的全局代理组 GLOBAL 切换代理

**Comment by thank243** [comment]
除了通过api控制外，可以直接写在配置文件内么？如果可以，能发个模板吗？

**Comment by Dreamacro** [comment]
@thank243 README.md

**Comment by thank243** [comment]
似乎并没有看见模板，直接把mode改为global模式后，提示无法match然后默认直连了。

**Comment by Dreamacro** [comment]
@thank243 显示 bug，实际是全局

**Comment by sususu98** [comment]
好像不是显示bug，我`clash.exe -d .`在自定义的文件夹中打开clash mode为global，通过api可以得到如下信息
```
            "history": [],
            "name": "GLOBAL",
            "now": "DIRECT",
            "type": "Selector"
```
可以看到Global的默认代理是Direct的
所以可以请教一下 @Dreamacro 我如何通过api修改Global的默认连接
```
put( http://127.0.0.1:9090/proxies/Global, data={'name':'xxxxxx'}
```
会返回<Response [404]>

**Comment by kzhui125** [comment]
研究半天，也没发现能直接通过配置文件配置global走代理跑起来。。。

@Dreamacro

**Comment by thank243** [comment]
可以用个折中的办法，规则直接写match proxy

KZ ***@***.***> 于2021年4月1日周四 下午1:22写道：

**Comment by imyhxy** [comment]
我也没找到通过配置文件的办法，可能用的人太少了，只能通过API控制
