### ISSUE TITLE
[Feature] 请重新考虑proxy-providers支持Base64编码

### ISSUE THREAD

**Issue by carllx** [Dreamacro/clash#2494]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我是一名 Clash 的用户，我发现在2020年的 issue #1005 中已经提出了支持 Base64 编码的建议。

然而，这两年来越来越多的机场订阅使用了 Base64 编码，这是为了更好地保护网络安全性。但由于 Clash 不支持 Base64 解码，我们无法使用 provider来自动更新订阅。这不仅影响了我们的使用体验，也限制了我们能使用的机场数量。

因此, 我请求开发者重新考虑支持 Base64 编码，以跟上网络安全性的趋势并让 Clash 更好地满足用户的需求。

此外, 我请求在新建的 issue 中使用 "Relates to" 标记将其 Relates to #1005 . 这样可以帮助开发者更好地组织和跟踪问题。

谢谢

**Comment by fakeboboliu** [comment]
> 这是为了更好地保护网络安全性

在 http 中传输 base64 不能 “保护网络安全性”，它只能让你以为自己得到了保护

**Comment by WnPro** [comment]
base64编码只是一个**8bit字节码的编码传输方式**，与安全性**没有**任何关系。
目前clash使用的是直接加载远程配置文件（即*.yaml文件）的方式实现Provider，配置文件是由提供商写好的专用于clash的配置文件，不仅仅包括了代理服务器地址、登录方式等信息，同时也包括了诸如rules，mode等等信息。而一般的订阅地址（比如v2ray-core）所使用的你所谓base64编码的订阅，只包括类似 `trojan://your.doman.name/others` `ss://your.domain.name/others` 的订阅地址信息，并不包括clash必要的配置信息。
建议阁下重新阅读clash的文档，自行讲上述内容转换/添加至您的clash配置文件。如果阁下遭遇了困难，推荐使用对应平台的其他基于clash的客户端，比如 [clash for windows](https://github.com/Fndroid/clash_for_windows_pkg)，或者其他提供clash专用配置文件的提供商。

**Comment by nov12** [comment]
当时是我提出那个建议，可惜被无情拒绝了……我现在用自己搭建的subconvert来解决此问题。

**Comment by Dreamacro** [comment]
@fakeboboliu @WnPro 说得对
