### ISSUE TITLE
clash-premium的docker拉取不了

### ISSUE THREAD

**Issue by jaesony** [Dreamacro/clash#2495]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

系统是routeros。cpu是armv7，新版拉取不了，只能退回到2022.11.25版

**Comment by Dreamacro** [comment]
怎么拉取不了的至少说一下啊，我看 docker hub 都有

**Comment by jaesony** [comment]
error response getting manifests: 404
was unable to import, container 0d8ad45e-b1c0-4380-b720-906baf7db7fc
log显示上述两条错误

**Comment by Dreamacro** [comment]
我拉了没问题，不要使用国内镜像源

**Comment by w01230** [comment]
Seems known issue of routeros and under fixing
https://forum.mikrotik.com/viewtopic.php?t=193727
