### ISSUE TITLE
Clash如何对来自IPv6的DNS提供服务

### ISSUE THREAD

**Issue by yykhysn** [Dreamacro/clash#250]
配置文件中DNS部分
listen: 0.0.0.0:53
只能对IPv4的DNS查询进行响应，如果我需要Clash提供的DNS服务也对Lan中IPv6发来的DNS进行响应，要如何配置？

**Comment by Dreamacro** [comment]
试试

```yaml
listen: ':53'
```

**Comment by yykhysn** [comment]
在双栈网络中，客户端会发两个DNS请求，一个发往IPv4的DNS服务器，另一个发向IPv6的DNS服务器。
这就需要将V4和V6的DNS请求都定向给Clash，Clash在V4、V6都进行监听。

listen: ':53'，只写端口号吗？我试试看
