### ISSUE TITLE
[HELP] Server A to Server B with real user ip

### ISSUE THREAD

**Issue by MrVb0** [Dreamacro/clash#2503]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Hello
I have 2 servers: server A and server B
Server A is in my country and Server B is in a foreign country
I want to bypass filtering by installing xrayr on server B (V2board-XrayR).
But direct connections to forigen servers from the GFW side are severely disrupted
So I want to establish a connection from server A to server B as follows:
Client > Server A > Server B (XrayR)

- I want the user's real IP to reach server B. (to use Global Device Limit XrayR)
- Also, I want some of the sites and IPs I want not to go to the server and open directly with server A (preferably open with the user's real IP / or / at least open with the IP of server A)

Is this possible with this script?
How can I do this?
Thank you for helping me in this work.

**Comment by SakuraSakuraSakuraChan** [comment]
Nginx & proxy protocol
