### ISSUE TITLE
[Bug] Strange behavior of clash (tested in cfw and cfa)

### ISSUE THREAD

**Issue by smaznet** [Dreamacro/clash#2505]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2.5.12 premium 

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
 - blah blah
```

### Description

Hi there i using clash for a while but recently i found a strange issue with clash

![IMG_20230123_112525_117](https://user-images.githubusercontent.com/10239885/213989898-64798922-62a0-4124-92c2-8019344ecf2a.jpg)

## what's this feature and how i can disable it?
Issue with this feature is all non resolved domains redirected to my server and i don't want handle that requests

**Comment by fakeboboliu** [comment]
That's how enhanced mode works.

There's a dilemma: DNS leaks or let the server handle all reqs.
To achieve your "i don't want handle that requests" goal, add an 'IP-CIDR' or 'GEOIP' rule to your rules and enjoy your DNS leak.

**Comment by coo1520** [comment]
nice!!!
