### ISSUE TITLE
[Feature] 可否为proxy-groups也添加filter功能

### ISSUE THREAD

**Issue by shnode** [Dreamacro/clash#2509]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

proxy-providers内确实有filter功能，但是希望在proxy-groups也添加一下，因为我有数条订阅，只想为如HBOMAX这个组筛选出美国节点，但是如果用proxy-providers的filter的话就比较复杂了，看了一下其他人教的，要重复写好几遍，也不利于后期的维护，虽然有第三方的clash核心支持了这个功能，但是我还是只想使用原版clash，谢谢。

**Comment by HamlinSergei** [comment]
我也有同样的困扰，一直没有好的解决办法

**Comment by taurusxin** [comment]
+1 希望能给 group 也增加 filter 功能，便于筛选节点
