### ISSUE TITLE
[Feature] 请求对vmess协议的zero加密方式进行支持

### ISSUE THREAD

**Issue by RookieBoy-lgbt** [Dreamacro/clash#2510]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

之前有人在issue中提到过希望对vmess zero加密方式进行支持 #1390 #1699 ，但都过期了。现在使用vmess协议大都采取vmess+tls+ws的方式，采用这种方式vmess协议本身已经不需要再进行加密了，因此希望作者能添加对vmess zero加密方式的支持。

**Comment by fakeboboliu** [comment]
这件事没有意义，因为 clash 目前的 none 并没有 #1699 中提及的 AEAD w/o E 机制，所以就没有 overhead。

但是也可以有意义，起码省个 buffer。
