### ISSUE TITLE
[Feature] store-fake-ip：add mysql support

### ISSUE THREAD

**Issue by terrancesiu** [Dreamacro/clash#2511]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Currently Fake-IP uses local files to store domain name and IP mappins, when I use distributed multi-point deployment of Clash and multiple Clash hosts to form a highly available network through OSPF, the domain name and IPs generated by Clash on different nodes are inconsistent, it leads to anomalies in client access.

I have tried to use NFS to share configurations and directories of Clash, but the result is not good, so is it possible to add mysql support to avoid the above problems.

**Comment by Dreamacro** [comment]
> when I use distributed multi-point deployment of Clash and multiple Clash hosts to form a highly available network through OSPF

I would like to know your usage scenario and more detailed network topology.

BTW, MySQL is not suitable for fakeip storage.

**Comment by terrancesiu** [comment]
![ospf-clash](https://user-images.githubusercontent.com/3016284/215370236-6d109c2a-d032-4dd6-b2fc-ca33d5fad21f.png)

Thank you for your reply.
I want the traffic balance to be sent to Singapore and Tokyo, so I need the domain records stored in both Clash to be the same.
The ip address of all utun interfaces:198.18.0.1/16.

**Comment by fakeboboliu** [comment]
it's reasonable, but I would recommend Redis or Memcached instead of MySQL for this situation.
