### ISSUE TITLE
[Bug] Wiki 中 Clash-Premium-Features 链接需更新

### ISSUE THREAD

**Issue by yi-Xu-0100** [Dreamacro/clash#2517]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash wiki

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
none
```

### Clash log

```shell
none
```

### Description

![image](https://user-images.githubusercontent.com/25523606/216068999-0133c468-1d53-464a-8b44-fa2e8253a900.png)

![image](https://user-images.githubusercontent.com/25523606/216068892-9255e275-ed32-457c-a8f9-21c50ec8b1a9.png)

旧链接：https://github.com/Dreamacro/clash/wiki/premium-core-features
新链接：https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features

Wiki 页面链接需要更新一下

**Comment by yi-Xu-0100** [comment]
@Dreamacro 似乎仍然是这样，但是我没法重开这个 issue 了。

**Comment by Dreamacro** [comment]
fixed
