### ISSUE TITLE
[Feature Request] GeoIP对IPv6进行分流

### ISSUE THREAD

**Issue by yykhysn** [Dreamacro/clash#252]
直连有IPv6，同时代理也拥有IPv6服务器，强烈需要对IPv6地址也进行分流。
但Clash所用GeoIP，IPv6匹配不到任何国家。
事实上Clash所用的GeoIP数据库——MaxMind GeoLite2包含有IPv6数据，并支持查询IPv6。
请问yml配置文件中应用怎样的语法来进行Geo IPv6规则匹配，GeoIP6吗还是……？
如果目前Clash没有实现GeoIP的IPv6分流，请尽快实现。

**Comment by yichengchen** [comment]
<img width="680" alt="Snipaste_2019-08-21_19-23-14" src="https://user-images.githubusercontent.com/11733500/63428123-5dfc8e00-c449-11e9-83d6-dee268c36083.png">

尝试了一下直接就可以支持ipv6查询

**Comment by yykhysn** [comment]
是支持ipv6查询，但不支持IPv4/IPv6分流。当目标地址是IPv6时，Clash不会在代理节点中特意寻找IPv6的代理节点。Clash会用IPv4的节点去连接IPv6地址，导致连接失败，无法访问。 @Dreamacro @yichengchen

**Comment by Dreamacro** [comment]
是不支持 ipv6/v4 分流，但目前绝大部分双栈应用会使用域名作为双栈兼容的方法，但如果是使用域名，则不存在 `Clash 会用 IPv4 的节点去连接 IPv6 地址，也会用 IPv6 的节点去连接 IPv4 地址，导致连接失败，无法访问`
