### ISSUE TITLE
[Bug] 文档缺少内容

### ISSUE THREAD

**Issue by ddzzkunye** [Dreamacro/clash#2520]
### Verify steps

- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

NAN

### Clash config

```yaml
null
```

### Description

没有  **strategy: consistent-hashing #or round-robin**  项  v1.11.4 / V1.3.0 / V0.13.0 / v0.12.0更新
没有  **lazy** 项 V1.3.0更新

**Comment by ddzzkunye** [comment]
https://github.com/Dreamacro/clash/releases/tag/v1.11.4
https://github.com/Dreamacro/clash/releases/tag/v1.3.0
https://github.com/Dreamacro/clash/releases/tag/v0.13.0
https://github.com/Dreamacro/clash/releases/tag/v0.12.0

**Comment by Dreamacro** [comment]
都有啊

**Comment by ddzzkunye** [comment]
奥我知道配置文件样例里有，
我是说链接的那段没有
