### ISSUE TITLE
[Bug] 开启 IPV6 后内核崩溃 panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by iKeqing** [Dreamacro/clash#2524]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2023.01.29

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: true
hosts:
  services.googleapis.cn: 216.58.200.67
  www.google.cn: 216.58.200.67
external-controller: 0.0.0.0:9090
clash-for-android:
  append-system-dns: false
profile:
  tracing: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:
  - "[2402:4e00::]:53"
  - 119.29.29.29
  nameserver:
  - "[2402:4e00::]:53"
  - 119.29.29.29
```

### Clash log

```shell
github.com/miekg/dns@v1.1.50/server.go:533 +0x3f0
created by github.com/miekg/dns.(*Server).serveUDP
	github.com/miekg/dns@v1.1.50/server.go:603 +0x1cc
github.com/miekg/dns.(*Server).serveUDPPacket(0x4000000240, 0x400027bc20?, {0x40004fc000, 0x3b, 0x200}, {0xa71780?, 0x400019a068}, 0x400066a380, {0x0?, 0x0})
	github.com/miekg/dns@v1.1.50/server.go:659 +0x3b8
github.com/miekg/dns.(*Server).serveDNS(0x4000000240, {0x40004fc000, 0x3b, 0x200}, 0x400023a880)
	github.com/Dreamacro/clash/dns/server.go:35 +0x30
github.com/Dreamacro/clash/dns.(*Server).ServeDNS(0x40004fc000?, {0xa74128, 0x400023a880}, 0x40004fc000?)
	github.com/Dreamacro/clash/dns/server.go:60 +0xe8
github.com/Dreamacro/clash/dns.handlerWithContext(0x40001962a0, 0x40001a77a0)
	github.com/Dreamacro/clash/dns/middleware.go:31 +0x554
github.com/Dreamacro/clash/dns.withHosts.func1.1(0x40001fb6e0?, 0x40001a77a0?)
	github.com/Dreamacro/clash/dns/middleware.go:114 +0xa0
github.com/Dreamacro/clash/dns.withFakeIP.func1.1(0x40001fb6e0, 0x40003f1cb4?)
	github.com/Dreamacro/clash/dns/middleware.go:76 +0xd8
github.com/Dreamacro/clash/dns.withMapping.func1.1(0x40004d2f50?, 0x40001a77a0?)
	github.com/Dreamacro/clash/dns/middleware.go:133 +0x104
github.com/Dreamacro/clash/dns.withResolver.func1(0x40003f1c58?, 0x40001a77a0)
	github.com/Dreamacro/clash/dns/resolver.go:129
github.com/Dreamacro/clash/dns.(*Resolver).Exchange(...)
	github.com/Dreamacro/clash/dns/resolver.go:151 +0x284
github.com/Dreamacro/clash/dns.(*Resolver).ExchangeContext(0x400052c480, {0xa6d1d0?, 0x40000b6000}, 0x40001a77a0)
	github.com/Dreamacro/clash/dns/resolver.go:159 +0xd0
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache(0x400052c480, {0xa6d1d0, 0x40000b6000}, 0x40001a77a0)
	github.com/Dreamacro/clash/common/compatible/singleflight.go:11 +0x54
github.com/Dreamacro/clash/common/compatible.(*Group[...]).Do(0x0, {0x400032a7c0?, 0x2f?}, 0xa5d9a8?)
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:104 +0x1c8
golang.org/x/sync/singleflight.(*Group).Do(0x400052c4f0, {0x400032a7c0, 0x33}, 0x8f98ac?)
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:196 +0xa4
golang.org/x/sync/singleflight.(*Group).doCall(0x7dbc20?, 0x4000302810?, {0x400032a7c0?, 0x33?}, 0x8f98ac?)
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:161 +0x2e8
golang.org/x/sync/singleflight.(*Group).doCall.func1()
goroutine 823 [running]:
	github.com/miekg/dns@v1.1.50/server.go:533 +0x3f0
created by github.com/miekg/dns.(*Server).serveUDP
	github.com/miekg/dns@v1.1.50/server.go:603 +0x1cc
github.com/miekg/dns.(*Server).serveUDPPacket(0x4000000240, 0x400027bc20?, {0x40004fc000, 0x3b, 0x200}, {0xa71780?, 0x400019a068}, 0x400066a380, {0x0?, 0x0})
	github.com/miekg/dns@v1.1.50/server.go:659 +0x3b8
github.com/miekg/dns.(*Server).serveDNS(0x4000000240, {0x40004fc000, 0x3b, 0x200}, 0x400023a880)
	github.com/Dreamacro/clash/dns/server.go:35 +0x30
github.com/Dreamacro/clash/dns.(*Server).ServeDNS(0x40004fc000?, {0xa74128, 0x400023a880}, 0x40004fc000?)
	github.com/Dreamacro/clash/dns/server.go:60 +0xe8
github.com/Dreamacro/clash/dns.handlerWithContext(0x40001962a0, 0x40001a77a0)
	github.com/Dreamacro/clash/dns/middleware.go:31 +0x554
github.com/Dreamacro/clash/dns.withHosts.func1.1(0x40001fb6e0?, 0x40001a77a0?)
	github.com/Dreamacro/clash/dns/middleware.go:114 +0xa0
github.com/Dreamacro/clash/dns.withFakeIP.func1.1(0x40001fb6e0, 0x40003f1cb4?)
	github.com/Dreamacro/clash/dns/middleware.go:76 +0xd8
github.com/Dreamacro/clash/dns.withMapping.func1.1(0x40004d2f50?, 0x40001a77a0?)
	github.com/Dreamacro/clash/dns/middleware.go:133 +0x104
github.com/Dreamacro/clash/dns.withResolver.func1(0x40003f1c58?, 0x40001a77a0)
	github.com/Dreamacro/clash/dns/resolver.go:129
github.com/Dreamacro/clash/dns.(*Resolver).Exchange(...)
	github.com/Dreamacro/clash/dns/resolver.go:151 +0x284
github.com/Dreamacro/clash/dns.(*Resolver).ExchangeContext(0x400052c480, {0xa6d1d0?, 0x40000b6000}, 0x40001a77a0)
	github.com/Dreamacro/clash/dns/resolver.go:159 +0xd0
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache(0x400052c480, {0xa6d1d0, 0x40000b6000}, 0x40001a77a0)
	github.com/Dreamacro/clash/common/compatible/singleflight.go:11 +0x54
github.com/Dreamacro/clash/common/compatible.(*Group[...]).Do(0x0, {0x400032a7c0?, 0x2f?}, 0xa5d9a8?)
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:104 +0x1c8
golang.org/x/sync/singleflight.(*Group).Do(0x400052c4f0, {0x400032a7c0, 0x33}, 0x8f98ac?)
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:191 +0x84
golang.org/x/sync/singleflight.(*Group).doCall(0x7dbc20?, 0x4000302810?, {0x400032a7c0?, 0x33?}, 0x8f98ac?)
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:189 +0x60
golang.org/x/sync/singleflight.(*Group).doCall.func2(0x40006638f6, 0x400020df90, 0x4000400000?)
	github.com/Dreamacro/clash/common/compatible/singleflight.go:12 +0x30
github.com/Dreamacro/clash/common/compatible.(*Group[...]).Do.func1()
	github.com/Dreamacro/clash/dns/resolver.go:189 +0x27c
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache.func1()
	github.com/Dreamacro/clash/dns/resolver.go:165 +0x70
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache.func1.1()
	github.com/Dreamacro/clash/dns/util.go:24 +0x264
github.com/Dreamacro/clash/dns.putMsgToCache(0x4000663a40?, {0x400032aa40?, 0x40001a77a0?}, 0x0?)
	runtime/panic.go:884 +0x20c
panic({0x8911e0, 0x40001da630})
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:184 +0x40
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
	golang.org/x/sync@v0.1.0/singleflight/singleflight.go:35 +0x28
golang.org/x/sync/singleflight.newPanicError({0x8911e0?, 0x40001da630})
	runtime/debug/stack.go:24 +0x64
runtime/debug.Stack()
panic: runtime error: index out of range [0] with length 0
```

### Description

开启 IPV6 后内核崩溃 panic: runtime error: index out of range [0] with length 0

**Comment by Dreamacro** [comment]
没有能够复现，能给出造成 panic 的请求吗

**Comment by iKeqing** [comment]
感谢回复，

附上几次崩溃前的log
```
07:06:37 DBG [Matcher] find process failed error=process not found addr=183.232.250.161
07:06:37 INF [UDP] connected lAddr=192.168.11.149:6905 rAddr=183.232.250.159:20001 mode=rule rule=RuleSet(ChinaMax_Classical) proxy=DIRECT
07:06:37 INF [UDP] connected lAddr=192.168.11.149:12696 rAddr=183.232.250.161:20002 mode=rule rule=RuleSet(ChinaMax_Classical) proxy=DIRECT
07:06:37 DBG [DNS] dns response source=[2402:4e00::]:53 qType=A name=www.google.com. answer=["199.59.148.97"]
07:06:37 DBG [DNS] dns response source=119.29.29.29:53 qType=AAAA name=www.google.com. answer=["2001::4a75:b29b"]
07:06:37 DBG [TCP] accept connection lAddr=192.168.11.223:54614 rAddr=www.google.com:443 inbound=Redir
07:06:37 DBG [Matcher] resolve success host=www.google.com ip=199.59.148.97
07:06:37 DBG [Matcher] find process failed error=process not found addr=www.google.com
panic: runtime error: index out of range [0] with length 0
```

另外一次
`07:05:35 DBG [DNS] dns response source=119.29.29.29:53 qType=AAAA name=dns.weixin.qq.com.cn. answer=["2409:8702:4860:10::4d"]
07:05:35 DBG [TCP] accept connection lAddr=192.168.11.237:54883 rAddr=27-courier.push.apple.com:5223 inbound=Redir
07:05:35 DBG [Matcher] resolve success host=27-courier.push.apple.com ip=17.57.145.167
07:05:35 DBG [Matcher] find process failed error=process not found addr=27-courier.push.apple.com
07:05:35 DBG [DNS] response empty request={"Id":20857,"Response":true,"Opcode":0,"Authoritative":false,"Truncated":false,"RecursionDesired":true,"RecursionAvailable":true,"Zero":false,"AuthenticatedData":false,"CheckingDisabled":false,"Rcode":4,"Question":[{"Name":"27-courier.push.apple.com.","Qtype":65,"Qclass":1}],"Answer":null,"Ns":null,"Extra":null,"Source":"119.29.29.29:53"}
07:05:35 INF [TCP] connected lAddr=192.168.11.237:54883 rAddr=27-courier.push.apple.com:5223 mode=rule rule=RuleSet(Apple) proxy=Apple[DIRECT]
panic: runtime error: index out of range [0] with length 0

runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
golang.org/x/sync/singleflight.newPanicError({0x73b4e0?, 0x400032ac18})
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:35 +0x28
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:184 +0x40
panic({0x73b4e0, 0x400032ac18})
        runtime/panic.go:884 +0x20c
github.com/Dreamacro/clash/dns.putMsgToCache(0x4000325a30?, {0x40001daf00?, 0x400287f4d0?}, 0x0?)
        github.com/Dreamacro/clash/dns/util.go:24 +0x264
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache.func1.1()
        github.com/Dreamacro/clash/dns/resolver.go:165 +0x70
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache.func1()
        github.com/Dreamacro/clash/dns/resolver.go:189 +0x27c
github.com/Dreamacro/clash/common/compatible.(*Group[...]).Do.func1()
        github.com/Dreamacro/clash/common/compatible/singleflight.go:12 +0x30
golang.org/x/sync/singleflight.(*Group).doCall.func2(0x40004658e6, 0x4000385c70, 0x4000194000?)
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:189 +0x60
golang.org/x/sync/singleflight.(*Group).doCall(0x692b00?, 0x4000301d70?, {0x400020c800?, 0x32?}, 0x79feef?)
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:191 +0x84
golang.org/x/sync/singleflight.(*Group).Do(0x4000306460, {0x400020c800, 0x32}, 0x79feef?)
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:104 +0x1c8
github.com/Dreamacro/clash/common/compatible.(*Group[...]).Do(0x0, {0x400020c800?, 0x2e?}, 0x8deae0?)
        github.com/Dreamacro/clash/common/compatible/singleflight.go:11 +0x54
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache(0x40003063f0, {0x8ec530, 0x40000b6000}, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/resolver.go:159 +0xd0
github.com/Dreamacro/clash/dns.(*Resolver).ExchangeContext(0x40003063f0, {0x8ec530?, 0x40000b6000}, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/resolver.go:151 +0x284
github.com/Dreamacro/clash/dns.(*Resolver).Exchange(...)
        github.com/Dreamacro/clash/dns/resolver.go:129
github.com/Dreamacro/clash/dns.withResolver.func1(0x4000325bd8?, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/middleware.go:139 +0x104
github.com/Dreamacro/clash/dns.withMapping.func1.1(0x4000191450?, 0x400287f4d0?)
        github.com/Dreamacro/clash/dns/middleware.go:76 +0xd8
github.com/Dreamacro/clash/dns.withFakeIP.func1.1(0x400054e030, 0x604020087612a01?)
        github.com/Dreamacro/clash/dns/middleware.go:120 +0xa0
github.com/Dreamacro/clash/dns.withHosts.func1.1(0x400054e030?, 0x400287f4d0?)
        github.com/Dreamacro/clash/dns/middleware.go:31 +0x554
github.com/Dreamacro/clash/dns.handlerWithContext(0x400000c258, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/server.go:60 +0xe8
github.com/Dreamacro/clash/dns.(*Server).ServeDNS(0x4000228000?, {0x8f3110, 0x40002c1280}, 0x4000228000?)
        github.com/Dreamacro/clash/dns/server.go:35 +0x30
github.com/miekg/dns.(*Server).serveDNS(0x4000000240, {0x4000228000, 0x3a, 0x200}, 0x40002c1280)
        github.com/miekg/dns@v1.1.50/server.go:659 +0x3b8
github.com/miekg/dns.(*Server).serveUDPPacket(0x4000000240, 0x74f84?, {0x4000228000, 0x3a, 0x200}, {0x8f0820?, 0x400000e068}, 0x4001389080, {0x0?, 0x0})
        github.com/miekg/dns@v1.1.50/server.go:603 +0x1cc
created by github.com/miekg/dns.(*Server).serveUDP
        github.com/miekg/dns@v1.1.50/server.go:533 +0x3f0


goroutine 474 [running]:
golang.org/x/sync/singleflight.(*Group).doCall.func1()
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:161 +0x2e8
golang.org/x/sync/singleflight.(*Group).doCall(0x692b00?, 0x4000301d70?, {0x400020c800?, 0x32?}, 0x79feef?)
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:196 +0xa4
golang.org/x/sync/singleflight.(*Group).Do(0x4000306460, {0x400020c800, 0x32}, 0x79feef?)
        golang.org/x/sync@v0.1.0/singleflight/singleflight.go:104 +0x1c8
github.com/Dreamacro/clash/common/compatible.(*Group[...]).Do(0x0, {0x400020c800?, 0x2e?}, 0x8deae0?)
        github.com/Dreamacro/clash/common/compatible/singleflight.go:11 +0x54
github.com/Dreamacro/clash/dns.(*Resolver).exchangeWithoutCache(0x40003063f0, {0x8ec530, 0x40000b6000}, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/resolver.go:159 +0xd0
github.com/Dreamacro/clash/dns.(*Resolver).ExchangeContext(0x40003063f0, {0x8ec530?, 0x40000b6000}, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/resolver.go:151 +0x284
github.com/Dreamacro/clash/dns.(*Resolver).Exchange(...)
        github.com/Dreamacro/clash/dns/resolver.go:129
github.com/Dreamacro/clash/dns.withResolver.func1(0x4000325bd8?, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/middleware.go:139 +0x104
github.com/Dreamacro/clash/dns.withMapping.func1.1(0x4000191450?, 0x400287f4d0?)
        github.com/Dreamacro/clash/dns/middleware.go:76 +0xd8
github.com/Dreamacro/clash/dns.withFakeIP.func1.1(0x400054e030, 0x604020087612a01?)
        github.com/Dreamacro/clash/dns/middleware.go:120 +0xa0
github.com/Dreamacro/clash/dns.withHosts.func1.1(0x400054e030?, 0x400287f4d0?)
        github.com/Dreamacro/clash/dns/middleware.go:31 +0x554
github.com/Dreamacro/clash/dns.handlerWithContext(0x400000c258, 0x400287f4d0)
        github.com/Dreamacro/clash/dns/server.go:60 +0xe8
github.com/Dreamacro/clash/dns.(*Server).ServeDNS(0x4000228000?, {0x8f3110, 0x40002c1280}, 0x4000228000?)
        github.com/Dreamacro/clash/dns/server.go:35 +0x30
github.com/miekg/dns.(*Server).serveDNS(0x4000000240, {0x4000228000, 0x3a, 0x200}, 0x40002c1280)
        github.com/miekg/dns@v1.1.50/server.go:659 +0x3b8
github.com/miekg/dns.(*Server).serveUDPPacket(0x4000000240, 0x74f84?, {0x4000228000, 0x3a, 0x200}, {0x8f0820?, 0x400000e068}, 0x4001389080, {0x0?, 0x0})
        github.com/miekg/dns@v1.1.50/server.go:603 +0x1cc
created by github.com/miekg/dns.(*Server).serveUDP
        github.com/miekg/dns@v1.1.50/server.go:533 +0x3f0`

**Comment by Dreamacro** [comment]
没有找到为什么会发生这个 panic, 可以使用下面这个二进制并开启 debug 日志，在 panic 时把日志给出

[clash-linux-amd64.zip](https://github.com/Dreamacro/clash/files/10703574/clash-linux-amd64.zip)
