### ISSUE TITLE
[Feature] 能加个测速功能吗？

### ISSUE THREAD

**Issue by JZLss** [Dreamacro/clash#2525]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

光有个延迟有些时候不太够用，看一些流媒体没有测速就很头疼，希望作者能加个测速功能。

**Comment by Tun2Sucks** [comment]
不是core应该做的事情
