### ISSUE TITLE
[Bug] Clash WS 0-RTT 不生效，已测试多种服务端对比生效情况

### ISSUE THREAD

**Issue by SimonTLS** [Dreamacro/clash#2531]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.11.25

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
- {name: sing-server, server: 1.1.1.1, port: 2001, type: vmess, uuid: xxx, alterId: 0, cipher: auto, network: ws, ws-opts: {path: /xxx, headers: {Host: xxx.xxx}, max-early-data: 2048, early-data-header-name: Sec-WebSocket-Protocol}, udp: true}
  - {name: xray-server, server: 1.1.1.1, port: 2002, type: vmess, uuid: xxx, alterId: 0, cipher: auto, network: ws, ws-opts: {path: /xxx, headers: {Host: xxx.xxx}, max-early-data: 2048, early-data-header-name: Sec-WebSocket-Protocol}, udp: true}
  - {name: v2ray-v4-server, server: 1.1.1.1, port: 2003, type: vmess, uuid: xxx, alterId: 0, cipher: auto, network: ws, ws-opts: {path: /xxx, headers: {Host: xxx.xxx}, max-early-data: 2048, early-data-header-name: Sec-WebSocket-Protocol}, udp: true}
  - {name: xray-server-client, server: 127.0.0.1, port: 10808, type: socks5}
```

### Clash log

```shell
no error
```

### Description

![image](https://user-images.githubusercontent.com/58877008/217258453-cb3f6136-1d68-44c5-8c21-1c8b5efd1f20.png)
多种服务端测试，WS 0-RTT 均不生效。对比的生效情况为双端 xray，客户端 v2rayn 添加 ?ed=2048。
已根据 https://github.com/Dreamacro/clash/issues/2400 中提到的测试配置，配置 v2ray v4 服务端。

**Comment by moranno** [comment]
我也有相同的情况，不生效，请问你现在进展如何，有没有摸索通？

**Comment by moranno** [comment]
隔壁clashmeta修复了。

**Comment by moranno** [comment]
请 @Dreamacro 参照这个提交也修复一下这个问题？
https://github.com/MetaCubeX/Clash.Meta/commit/75680c5866ebc497016120cda9afc39c3e13a0aa

**Comment by moranno** [comment]
请问 @Dreamacro 是否修复有进展，我可以付费支持修复。

**Comment by qiqizjl** [comment]
这个问题看起来好像没解决？
