### ISSUE TITLE
[Feature] 请增加 DNS的ttl时长

### ISSUE THREAD

**Issue by yjps** [Dreamacro/clash#2533]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我在docker内用Clash Premiumclash TUN 作为透明网关，主路由使用routeros，建一条静态路由将fakeip的网段指向docker clash。
我的routeros向clash查询dns的时候，得到的dns ttl只有3秒，这个时间太短了。
![image](https://user-images.githubusercontent.com/32375607/217732296-1d471ff2-2ab8-40c8-b467-98900670937c.png)

希望可以将clash返回的dns ttl时间延长到10分钟。

**Comment by yjps** [comment]
![image](https://user-images.githubusercontent.com/32375607/217731556-7ba53fe3-96e7-45a5-986e-5c2746fb080f.png)

**Comment by techblack** [comment]
fake ip作为一种临时的ip，短一点是合理的，（例如没有开启ip持久化存储选项
可以上面套个adguard Home来强制覆盖clash的ttl，顺便还能去个广告
