### ISSUE TITLE
[Feature] nameserver-policy 允许多个dns

### ISSUE THREAD

**Issue by kokutoukiritsugu** [Dreamacro/clash#2534]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

公司地区1,公司地区2,vpn
3个地方的dns都不一样
希望可以支持多个dns, 内网网站就都可以访问了.

nameserver-policy:
  *.xxx.yyy:adns,bdns,cdns

### Possible Solution

希望可以支持多个dns, 内网网站就都可以访问了.

nameserver-policy:
  *.xxx.yyy:adns,bdns,cdns

**Comment by kokutoukiritsugu** [comment]
#2527

**Comment by xuan880** [comment]
直接把公司的dns填写的nameserver里面就行了,请求内部域名时,内网dns返回基本是最快的,完全可以返回内网IP,我就是这样用的.
