### ISSUE TITLE
[Feature] fake-ip-filter 能否支持以文件形式导入列表

### ISSUE THREAD

**Issue by nick008a** [Dreamacro/clash#2536]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

希望实现 对大陆的域名不使用fake-ip，直接返回真实ip。目前的做法是需要把GEOSITE 手工一行行抄写到fake-ip-filter 里，很麻烦。

https://github.com/MetaCubeX/Clash.Meta/issues/366
https://github.com/vernesong/OpenClash/issues/2988

**Comment by Dreamacro** [comment]
需求不合理，把大陆域名加到 fakeip filter 里不是 fakeip 的使用方式。建议不使用 fakeip

**Comment by Dreamacro** [comment]
@arm64-v9a 删除 redir-host 和需不需要大量 fakeip-filter 列表没有关联。stun 并不需要查到 dns 真实 ip 才能正常工作

**Comment by cjwddtc** [comment]
目前确实大部分都是可以的，就暴雪系的比较坑。

**Comment by cjwddtc** [comment]
能不能介绍下这个东西什么原理？或者说为什么即使我udp和tcp都劫持了依然需要这个功能屏蔽部分域名的fakeip解析呢？ @Dreamacro

**Comment by trawor** [comment]
比如: 一台性能很差的旁路由跑clash,  主路由把dns指向了旁路由并设置只有fakeip走静态路由表到旁路由, 这样来实现透明代理的目的.

我希望把**所有国内网站全都用fake-ip-filter返回原本的dns ip**, 这样国内流量就不会进入clash了, 可以想象一下国内视频/测速等大流量场景.

**Comment by BirkhoffLee** [comment]
> It is only used in the fake-ip-filter for a few domain name mappings. I know that it can be bypassed and "recovered" in fake-ip mode. If fake-ip-filter finds that it has been abused, I will delete the domain mapping mode completely.
