### ISSUE TITLE
i want to how to create a clash config sing a trojan config

### ISSUE THREAD

**Issue by DFanso** [Dreamacro/clash#2538]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

i have a trojan config which created using my server and i want to create a clash config using that trojan config can anyone give me a tutorial to create that thank you

**Comment by Dreamacro** [comment]
Refer to full clash config https://github.com/Dreamacro/clash/wiki/Configuration
