### ISSUE TITLE
[Feature Request] DNS 的可行自动化方案

### ISSUE THREAD

**Issue by winguse** [Dreamacro/clash#254]
我这里破一下一些个人发现，可能别人也发现了，不过我好像也还没看到过有其他人发表过类似的发现。

先说结论：对于被污染的域名，不管墙外是否有应答（哪怕 DNS 本身不存在），目前防火墙都会给一个错误应答。

```
 $ dig www.google.com @8.8.8.8
```

![image](https://user-images.githubusercontent.com/1443504/62603124-d2064480-b927-11e9-86ef-d1890e6ac00e.png)

上图中：
1. 是请求包
2. 防火墙错误应答
3. 真实应答
4. ICMP 不可到达应答（以前没见过）

今天做实验的时候，发现情况已经发生了一点变化，之前防火墙会有两个错误应答，没有 ICMP 包。

```
 $ dig www.google.com @8.8.8.7 # 这个 IP 是不存在的，至少不存在 DNS
```

![image](https://user-images.githubusercontent.com/1443504/62603314-417c3400-b928-11e9-8506-0c2f6de369ed.png)

可以看到，有应答。

重复以上实验，但是把域名换成不受防火墙影响的域名，则前者没有干扰包返回，后者没有任何应答。

由此，我们可以有一个机制自动检测受干扰的域名，并且可以自动化规则。由于墙离查询者比较近，所以干扰包会先抵达，这样干扰会有效，不过若以此作为检测的思路，检测的速度应该是有保证的。

当然，因为墙跟真实服务器的响应包距离查询者不一样，他们的 TTL 也是有特征的，可以根据这个过滤掉干扰包。[这里](https://github.com/winguse/fuck-gfw-scripts/blob/master/anti_dns_spoofing.sh)是之前我写过的一个脚本。

当然了，这个自然是有风险的，因为你访问了啥域名，会被人发现。但是由于墙是两面工作的，我们可以把检测放到墙外服务器寻求隐匿性。

例如在墙外的主机上面

```
$ dig www.google.com @61.135.169.121 # 墙内 IP
```

你是可以看到响应的。

---

补充其他 DNS 发现：

对于 TCP 的 DNS 查询，墙的做法是 TCP REST，若忽略 RST 包（iptables），则可能可以拿到正确结果（“可能”是因为远端也会收到 RST 包）。

另外，Open DNS 可以通过 443 端口 udp 查询不受干扰。

**Comment by Kr328** [comment]
用 fake-ip / redir-host 后 基本上就不会受到 DNS污染 的影响
因为都是在远程服务器解析

**Comment by xjasonlyu** [comment]
我觉得可能是ISP的原因吧，我家的浙江电信就没这个问题，没有DNS被强制污染的问题，只有某些时段`8.8.8.8`之类的丢包问题。而且上述的TCP RST也没有，tcp直连`8.8.8.8`纯属只看当天网络状况，`8.8.8.7`之类的 fake DNS 地址也并不会收到响应。

**Comment by winguse** [comment]
@Kr328 这里不是要解决 DNS 污染的问题，而是自动检测网站是不是被墙

**Comment by comzyh** [comment]
https://github.com/shawn1m/overture

这个项目是专门做 DNS 方面工作的，你可以在那也问问 :smile:
