### ISSUE TITLE
[Bug] TCP请求无法得到预期响应

### ISSUE THREAD

**Issue by nange** [Dreamacro/clash#2540]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.13.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
log-level: debug
rules:
  - MATCH,DIRECT
```

### Clash log

```shell
INFO[0000] Mixed(http+socks) proxy listening at: 127.0.0.1:7890 
INFO[0025] [TCP] 127.0.0.1:50518 --> my-server-ip:port match Match() using DIRECT
```

### Description

# Bug重现
## 代码准备
**测试客户端代码:**
```go
package main

import (
	"fmt"
	"net"
	"os"

	"golang.org/x/net/proxy"
)

func main() {
	if len(os.Args) <= 1 {
		fmt.Println("please enter some greeting message")
		return
	}

	dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:7890", nil, proxy.Direct)
	if err != nil {
		fmt.Println("create socks5 dialer:", err.Error())
		return
	}
	conn, err := dialer.Dial("tcp", "your-server-ip:port")
	if err != nil {
		fmt.Println("dial:", err.Error())
		return
	}
	defer conn.Close()

	if _, err := conn.Write([]byte(os.Args[1])); err != nil {
		fmt.Println("write greeting message to remote:", err.Error())
		return
	}

	if err := conn.(*net.TCPConn).CloseWrite(); err != nil {
		fmt.Println("close write:", err.Error())
		return
	}

	ret := make([]byte, 1024)
	nr, err := conn.Read(ret)
	if err != nil {
		fmt.Println("read from remote:", err.Error())
		if nr > 0 {
			fmt.Println("read from remote:", string(ret[:nr]))
		}
		return
	}
	fmt.Println("read from remote:", string(ret[:nr]))
}

```
**测试服务端代码:**
```go
package main

import (
	"fmt"
	"net"
	"os"
	"time"
)

func main() {
	if len(os.Args) <= 1 {
		fmt.Println("please set server port using os.Args[1]")
		return
	}
	lis, err := net.Listen("tcp", ":"+os.Args[1])
	if err != nil {
		fmt.Println("listen:", err.Error())
		return
	}
	fmt.Println("server listen on :" + os.Args[1])
	for {
		conn, err := lis.Accept()
		if err != nil {
			fmt.Println("accept:", err.Error())
			break
		}
		go handleConn(conn)
	}
}

func handleConn(conn net.Conn) {
	defer conn.Close()

	for {
		b := make([]byte, 1024)
		nr, err := conn.Read(b)
		if err != nil {
			fmt.Println("read:", err.Error())
			if nr > 0 {
				fmt.Println("read err, bug got:", b[:nr])
			}
			return
		}
		fmt.Println("read:", string(b[:nr]))
		time.Sleep(10 * time.Second)
		if _, err := conn.Write(b[:nr]); err != nil {
			fmt.Println("write to remote:", err.Error())
		}
	}
}

```
## 测试步骤
1. 编译服务端和客户端代码
2. 在服务器上运行服务端二进制
3. 本机运行clash
4. 本机运行客户端二进制（如：./test hello）

## 预期结果
本机打印：
```
read from remote: hello
```
## 实际结果
本机打印：
```
read from remote: EOF
```

# Bug分析
通过查看代码，发现`common/net/relay.go` 实现可能不正确：
```go
// Relay copies between left and right bidirectionally.
func Relay(leftConn, rightConn net.Conn) {
	ch := make(chan error)

	go func() {
		// Wrapping to avoid using *net.TCPConn.(ReadFrom)
		// See also https://github.com/Dreamacro/clash/pull/1209
		_, err := io.Copy(WriteOnlyWriter{Writer: leftConn}, ReadOnlyReader{Reader: rightConn})
		leftConn.SetReadDeadline(time.Now())   // 这里通过设置deadline，是不正确的
		ch <- err
	}()

	io.Copy(WriteOnlyWriter{Writer: rightConn}, ReadOnlyReader{Reader: leftConn})
	rightConn.SetReadDeadline(time.Now())  // 这里通过设置deadline，是不正确的
	<-ch
}
```
通过`SetReadDeadline`的方式，让另一个`io.Copy`退出的做法是不正确的，原因是：很可能TCP的其中一方只是关闭了写请求，但是其还需要继续的从另一方进行读请求。直接`SetReadDeadline`可能造成丢失部分读请求数据，就像上面测试程序那样。

正确的做法是：在`io.Copy`结束后，调用`Writer`方的`CloseWrite`方法，通知远端，另一方已经关闭写入（本质上底层是向对方发送FIN包）。

## 修复此Bug的伪代码
```go
type CloseWriter interface {
	CloseWrite() error
}

// Relay copies between left and right bidirectionally.
func Relay(leftConn, rightConn net.Conn) {
	ch := make(chan error)

	go func() {
		// Wrapping to avoid using *net.TCPConn.(ReadFrom)
		// See also https://github.com/Dreamacro/clash/pull/1209
		_, err := io.Copy(WriteOnlyWriter{Writer: leftConn}, ReadOnlyReader{Reader: rightConn})
		leftConn.(CloseWriter).CloseWrite()  // 调用CloseWrite，结束数据写入，远端读请求会收到io.EOF
		ch <- err
	}()

	io.Copy(WriteOnlyWriter{Writer: rightConn}, ReadOnlyReader{Reader: leftConn})
	rightConn.(CloseWriter).CloseWrite()  // 调用CloseWrite，结束数据写入，远端读请求会收到io.EOF
	<-ch
}
```

我本地以Direct的代理模式，测试了上述修复模式，测试结果符合预期，能够修复上述Bug。 

但要把所有情况下的`leftConn`, `rightConn`都加上`CloseWriter`支持，我尝试了一下，还是比较困难，改动较大，加之我不太熟悉Clash代码，希望更熟悉代码的人来做此事，可能会做部分代码重构。

**Comment by Dreamacro** [comment]
之前这里没做半双工传递的原因是某次测试时发现如果不加立即超时，另一半 copy 很可能连接就会一直在那并且不会关闭（具体情况记不清了）。

你这有什么需要关闭单向写的实际场景吗？

**Comment by nange** [comment]
> 之前这里没做半双工传递的原因是某次测试时发现如果不加立即超时，另一半 copy 很可能连接就会一直在那并且不会关闭（具体情况记不清了）。

另一半不会关闭，严重怀疑就是因为没有调用`CloseWrite`造成的，因为另一方一直无法收到FIN包(EOF)，就一直没有关闭链接导致。


> 你这有什么需要关闭单向写的实际场景吗？

很难说实际的场景，因为这不是那么容易重现的。但我自己也写了一个代理程序（Easyss），之前代码上也有同样的问题，偶尔会遇到一些软件的意外断流（也包括浏览器），后面做了代码修复后，目前没有再出现断流，当然我本身也做了些其他修改，因此不能100%说就是这个修改修复的。然后想出了上面的一个简单的测试程序用来复现问题，顺便看了看社区常见的代理软件，也都有类似的问题，所以也想给社区做点贡献。

**Comment by Dreamacro** [comment]
> 因为另一方一直无法收到FIN包(EOF)，就一直没有关闭链接导致。

我没法控制服务端的行为，所以如果服务端没有正确实现这个行为，可能会导致连接一直无法断开，所以目前这个“错误”的行为能解决这个问题

**Comment by nange** [comment]
> > 因为另一方一直无法收到FIN包(EOF)，就一直没有关闭链接导致。
> 
> 我没法控制服务端的行为，所以如果服务端没有正确实现这个行为，可能会导致连接一直无法断开，所以目前这个“错误”的行为能解决这个问题

这里需要做一个抉择，就是代理是要保持和实际情况一致呢，还是要用一个“错误”的行为去解决一个服务端的可能的错误行为（小概率的）。如果服务端本身存在错误行为，即使没有代理存在，实际的客户端也可能是无法正常关闭链接的。

我会选择和实际行为保持一致，以及数据的完整性。如果你更在意代理这里一定不能出现连接没有被关闭的情况，那我觉得也OK，只是大家的关注和在意点不同而已。

**Comment by Dreamacro** [comment]
这里指的服务端是代理服务端，不是实际连接的服务器。暂时没有在 realworld 找到一个会半关闭且影响实际使用的场景（如果有你可以举例）。

**Comment by nange** [comment]
哦，你是指clash的下游，如Shadowsocks的服务端之类的是吧。 这个确实没法控制，而且我大概看了一下，好多下游也基本上都有这个问题。不过这是一个链条，链条只要有一个地方没有处理对，就会造成整体的不正确。 
不过话说回来，我确实也还没有找不到真实场景中，能复现的方法。 根据你的反馈，我建议就先关闭这个issue了，如果后续我有遇到真实场景中能复现的方法了，再到这个issue来说明一下。 你觉得呢？

**Comment by Dreamacro** [comment]
感谢🤝
