### ISSUE TITLE
google.com 偶发的无法访问, say hello 出错 [Bug] 

### ISSUE THREAD

**Issue by Sanchew** [Dreamacro/clash#2541]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.01.29 Premium

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
开启tun全局模式dns也配置的无问题
```

### Description

google 一天总会发生几次无法访问,   
`
curl https://www.google.com -vvv
*   Trying 172.217.163.36:443...
* Connected to www.google.com (172.217.163.36) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
`
以上测试是在tun 而且是全局模式的情况下测试的   什么错误啊怎么解决
而且这个问题只现在在google.com这个域名上,  youtube可以正常访问  
 
过一会就没问题了  请求ip依然是172.217.163.36
`
*   Trying 172.217.163.36:443...
* Connected to www.google.com (172.217.163.36) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN, server accepted to use h2
`

**Comment by Dreamacro** [comment]
不要用 redir-host

**Comment by Sanchew** [comment]
> 不要用 redir-host

这是默认值吗,  我没配置,  我换成fakeip试试 谢谢大佬

**Comment by Dreamacro** [comment]
下个版本就已经移除了，没有默认值，而且一直都推荐 fakeip

**Comment by Sanchew** [comment]
非常感谢,
