### ISSUE TITLE
[求助] clash for MAC, 笔记本和手机连校园网wifi可以正常翻墙，笔记本和台式机连接网线之后能连接但是不能上网，求大佬帮忙解决一下

### ISSUE THREAD

**Issue by jiukeeeeee** [Dreamacro/clash#2544]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

之前mac笔记本和windows台式机连网线都可以正常翻墙，某个时间之后突然都不能翻墙了，只有连接wifi的时候可以，我使用的是学校的校园网，连上要输入账号密码的那种，wifi太慢还经常掉线，用着很不舒服。求大佬帮忙解决一下 感谢！

**Comment by KazeW** [comment]
你的意思是无线方式可以用，有线方式不行？ 有线和无线的网络入口是同一个吗？有没有可能就是无线被限制了

**Comment by KazeW** [comment]
你的意思是无线方式可以用，有线方式不行？ 有线和无线的网络入口是同一个吗？有没有可能就是有线被限制了
