### ISSUE TITLE
[Feature] 多个url测速取平均值

### ISSUE THREAD

**Issue by zjplab** [Dreamacro/clash#2545]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

需求: 对于一个proxy group, 我可能用来用来作为通用上网的group, instagram.com, google.com, github.com例如这三个网站.
我希望在在proxy group中有引入多重url的功能, 用户可以提供url权重, 默认均为1(取平均)

### Possible Solution

同时对这几个Url测速, 并配上权重

**Comment by Dreamacro** [comment]
你可以通过 API 来自行实现这一点

**Comment by zjplab** [comment]
@Dreamacro 我看了https://lancellc.gitbook.io/clash/clash-config-file/script这里的例子,没有发现测速相关的API。 此外我用过的是Clash for Windows, 他们那似乎只提供了parser功能，更不知道从哪入手了
