### ISSUE TITLE
[Question] 默认geoip无法正确的判断谷歌ip的归属地并正确分流的问题

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#2546]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我希望能根据访问服务器所在地来决定使用哪个节点，通常来讲香港日本以及台湾的节点速度会更快，但是不是所有网站在世界各地都有服务器，很多网站的服务器可能只在美国或者欧洲有，这时候使用亚洲的服务器虽然也能访问，但是速度就比不上对应区域的高质量节点了。
按照clash设计，通过geoip选定不同区域后转发给对应的节点即可，但是对于比如youtube之类的网页，这种方案解析出来的ip全部都会变成美国，所有流量也都走了美国，即使明明谷歌在台湾和日本都有节点，而只要单纯的删掉GEOIP,US,xxx这一条规则（最后的fallback是台湾的节点），解析出来的ip就会正常的恢复到台湾的ip。

ps. 可能的补充，我用的redir-host，因为我有时需要使用ping来测试延迟。

**Comment by cjwddtc** [comment]
经过反复调试，发现是默认的mmdb数据库没有正确的识别谷歌在日本和台湾的地址，全部都是别成了美国。挂在这里看有没有人有精度更高的数据库。

**Comment by SakuraSakuraSakuraChan** [comment]
> 很多网站的服务器可能只在美国或者欧洲有，这时候使用亚洲的服务器虽然也能访问，但是速度就比不上对应区域的高质量节点了

大网站就算亚洲没有DC也通常会有CDN，而且有缓存，所以还是比你用“对应区域节点”快

> 但是对于比如youtube之类的网页，这种方案解析出来的ip全部都会变成美国

油管的CDN全球都有，请自行通过DNS设置解决


另外，redir-host在之后的版本里不会有了

**Comment by cjwddtc** [comment]
> 油管的CDN全球都有，请自行通过DNS设置解决
我后面已经解释过原有了，我的dns是没问题的，只是默认的goeip的地址库不能正确识别谷歌在台湾和日本的ip
> 大网站就算亚洲没有DC也通常会有CDN，而且有缓存，所以还是比你用“对应区域节点”快
 问题就是很多时候不光要访问大网站，当你访问小网页甚至下载资源的时候，美国节点的速度就会吊打亚洲节点，而且"大网站youtube"在香港已经没有节点了，我就需要手动换成日本/台湾的节点来保证体验，所以如果能实现的话，显然"根据dns返回的地址区域来决定选择不同的节点"是优于"固定选择某个近距离节点"

当然目前由于没有免费且精准度高geoip数据库，这个自动根据地域分流的计划只能破产了。我提问一开始确实没有考虑到是geoip数据精度不够的问题，误以为的clash的某个特殊dns解析方式引发的问题，因此才来提这个issue

另外关于redir-host的问题，我建议最好不要移除redir-host的支持，clash是工作在传输层的，只能接受某几个特定的传输层协议的流量（tcp和udp)，fake-ip理论上却要求必须劫持能网络层流量才能完美实现。此外实际使用过程中如果需要绕过某个局域网设备时（比如bt客户端），复杂度会增加（dns也需要单独绕开劫持）。

**Comment by wmyfelix** [comment]
之前看到过这种讨论，这两天我可以尝试一下通过配置文件实现类似策略，但不认为效果会比直连最快节点好。

**Comment by cjwddtc** [comment]
https://db-ip.com/ 这个网站有免费能正确解析谷歌ip归属地的mmdb数据库，目前已经成功实现了根据节点归属地分流。
