### ISSUE TITLE
[Feature] rules 能否考虑支持url匹配

### ISSUE THREAD

**Issue by yuhaya** [Dreamacro/clash#2552]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

这个想法的原始目的是为了节省带宽
现有的rules只支持ip以及域名过滤
能否支持url匹配过滤从而走不同的代理
比如给某个服务器做代理，将一些静态资源的请求，比如图片，文档这些，占用带宽很大的单独走其它的线路

### Possible Solution

或者有其它的见解方式能否实现这种功能

**Comment by sandwichBob** [comment]
现在都用https，这实际上是不可行的，因为具体url是加密的。

**Comment by BirkhoffLee** [comment]
MITM is not going to be implemented.
