### ISSUE TITLE
添加配置文件URL显示错误

### ISSUE THREAD

**Issue by 18234068849** [Dreamacro/clash#2555]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

![image](https://user-images.githubusercontent.com/25168008/220255930-a4069214-ec17-431b-9a83-4100ca186c56.png)

**Comment by NavinChen** [comment]
我也是这样，更新最新版的clashxpro以后，一直报这个

**Comment by gg4924** [comment]
新版的clash现在只支持fake-ip模式。你的配置文件里用的是redir-host，不支持，要不你就用老版本的核心吧。

**Comment by Dreamacro** [comment]
Duplicate of #2559
