### ISSUE TITLE
什么时候加入xtls-rprx-vision

### ISSUE THREAD

**Issue by cxbl-ops** [Dreamacro/clash#2556]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

什么时候加入xtls-rprx-vision

**Comment by qist** [comment]
vless 都没添加为啥要加xtls-rprx-vision

**Comment by 1219099256** [comment]
可能需要一段时间证明其稳定性才会支持

**Comment by BirkhoffLee** [comment]
https://github.com/Dreamacro/clash/issues/1185
