### ISSUE TITLE
载入配置文件会提示：托管配置文件格式不正确：invalid mode： redir-host

### ISSUE THREAD

**Issue by YBY-BaoYuan** [Dreamacro/clash#2559]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

托管配置文件格式不正确：invalid mode： redir-host
<img width="262" alt="image" src="https://user-images.githubusercontent.com/93755812/220317666-b9d21fe2-1574-480e-8627-6f3ded1aa84d.png">

**Comment by gg4924** [comment]
新版的clash现在只支持fake-ip模式。你的配置文件里用的是redir-host，不支持，要不你就用老版本的核心吧。如果能够修改增强模式（enhanced-mode）的话，可以设置为fake-ip。

**Comment by Dreamacro** [comment]
更新到最新回自动用 fakeip，或者用旧版

**Comment by thank243** [comment]
If I use clash as a bypass gateway, redir-host is a useful mode for ip probe. Only oversea ip use clash gw. @Dreamacro

**Comment by Initial01LingXu** [comment]
可以把配置文件中的enhanced-mode: redir-host改成enhanced-mode: fake-ip，就不会出现这个提示，仍能正常使用，但会不会有其他问题就不知道了。

**Comment by Ealsen** [comment]
> 可以把配置文件中的enhanced-mode: redir-host改成enhanced-mode: fake-ip，就不会出现这个提示，仍能正常使用，但会不会有其他问题就不知道了。

这样确实可以用，不过更新订阅还是要重新改一次

**Comment by Ealsen** [comment]
> 更新到最新会自动用 fakeip，或者用旧版

最新版0.20.17

我的不会自动用

不知道为什么

**Comment by JoeTAndy** [comment]
①，不能点击Update

**Comment by JoeTAndy** [comment]
②，直接双击Download下来的这个File使其生效即可

**Comment by Ealsen** [comment]
> ②，直接双击Download下来的这个File使其生效即可

明白了

**Comment by Sytom** [comment]
![微信图片编辑_20230228172031](https://user-images.githubusercontent.com/30535521/221808635-daab8dc7-9765-4672-9eff-a1ba5becb164.jpg)
<img width="612" alt="微信截图_20230228171942" src="https://user-images.githubusercontent.com/30535521/221808656-babb4318-4fe2-4569-bb5d-185aac4f746c.png">
我是在这里加了这个配置刷新订阅也能用

**Comment by Ealsen** [comment]
> ![微信图片编辑_20230228172031](https://user-images.githubusercontent.com/30535521/221808635-daab8dc7-9765-4672-9eff-a1ba5becb164.jpg)
> <img width="612" alt="微信截图_20230228171942" src="https://user-images.githubusercontent.com/30535521/221808656-babb4318-4fe2-4569-bb5d-185aac4f746c.png">
> 我是在这里加了这个配置刷新订阅也能用

如果你是用tun模式的话，就不会出现刷新不能用的问题

**Comment by EddyLee88** [comment]
对, v0.20.17已经不支持redir-host了, 需要使用fake-ip, 应该联系供应商将你们的订阅配置中的dns.enhanced-mode修改为fake-ip;
当然, 也可以使用CFW的预处理配置功能:
```
parsers:
  - url: https://此处替换为你的订阅地址
    yaml:
      commands:
        - dns.enhanced-mode=fake-ip
```
使用以上代码配置预处理配置, 即可每次更新订阅都覆盖enhanced-mode为fake-ip
更多用法可以参考官方文档[配置文件预处理](https://docs.cfw.lbyczf.com/contents/parser.html)
我也是研究了很久才搞定, 希望可以帮到你

**Comment by 1154910** [comment]
还是不行

**Comment by 1154910** [comment]
> 对， v0.20.17已经不支持redir-host了， 需要使用fake-ip， 应该联系供应商将你们的订阅配置中的dns.enhanced-mode修改为fake-ip; 当然， 也可以使用CFW的预处理配置功能：
> 
> ```
> parsers:
>   - url: https://此处替换为你的订阅地址
>     yaml:
>       commands:
>         - dns.enhanced-mode=fake-ip
> ```
> 
> 使用以上代码配置预处理配置， 即可每次更新订阅都覆盖enhanced-mode为fake-ip 更多用法可以参考官方文档[配置文件预处理](https://docs.cfw.lbyczf.com/contents/parser.html) 我也是研究了很久才搞定， 希望可以帮到你

改了也还是不行TT

**Comment by Jiang92** [comment]
如果要改预处理配置，建议将
`- url: https://此处替换为你的订阅地址`
替换为
`- reg: ^.*$`

还有另一种方法，在混合配置的YAML直接改就行，改完就好了
![image](https://user-images.githubusercontent.com/89497237/230004368-04ddf63e-72a5-4de3-8e7a-88138d112920.png)

忘记这个混合配置是不是初始就有，没有的话建议参考文档
![CF$L%1F347GFOE0T0VKY~ H](https://user-images.githubusercontent.com/89497237/230006394-53831761-b17c-4004-a700-69016a8998ec.png)

**Comment by Codave** [comment]
推荐使用ClashX Pro，可完美解决此问题。

**Comment by Jiang92** [comment]
自己收集整理了clash配置，懒得在折腾了，目前运行得很好，直接躺平

**Comment by ztys1** [comment]
![CleanShot 2023-05-17 at 21 44 24@2x](https://github.com/Dreamacro/clash/assets/75885375/a7adc843-62c7-4b08-a771-9d66a150ff9e)

**Comment by andriannnnn** [comment]
还好 我已经更新了v2board的配置文件  ：）

**Comment by runforprogram** [comment]
> 

我用url匹配https://5c68ed15.ghelper.me/clash/09b70b63c005a88bc076d6072df445ae 保存后,显示Parsers为0,
使用  - reg: ^.*$ 显示Parsers为1,看起来url匹配不上
