### ISSUE TITLE
[Feature] rules如何匹配udp

### ISSUE THREAD

**Issue by hxse** [Dreamacro/clash#2561]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

```
rules:
- MATCH, Proxy
```

我开启了tun模式, 这样写可以用match匹配到udp, 但是我想把udp分流出来,有办法实现吗
代码可能类似于:
```
rules:
- UDP, Proxy
- MATCH, Proxy
```

**Comment by Dreamacro** [comment]
script shortcut

**Comment by Karmylr** [comment]
script或者meta

**Comment by asipirin1120** [comment]
> script或者meta

希望给出写法。谢谢！
官方文档中的match_provider似乎无法匹配最后的match。

**Comment by BirkhoffLee** [comment]
https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#script
