### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Alan055** [Dreamacro/clash#2562]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

可以用wget 或 curl 可以翻墙，但是跑起来的爬虫服务，无法翻墙

### Clash config

```yaml
如题，我linux在大陆，使用了clash，通过wget和curl测试youtube和google都是可以翻墙的，但是通过自己部署的爬虫脚本服务，发送ajax请求，却无法进行翻墙，拿不到外网的资源～，求助～～～
```

### Description

如题，我linux在大陆，使用了clash，通过wget和curl测试youtube和google都是可以翻墙的，但是通过自己部署的爬虫脚本服务，发送ajax请求，却无法进行翻墙，拿不到外网的资源～，求助～～～

**Comment by Alan055** [comment]
已收到，我会尽快查看的，谢谢（自动回复）

**Comment by BirkhoffLee** [comment]
Give move info
