### ISSUE TITLE
[Feature] A网络本身要求必须通过代理服务器上网， 如何设置clash？

### ISSUE THREAD

**Issue by useforgithub** [Dreamacro/clash#2563]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

A网络本身要求必须通过代理服务器上网，我也没有在clash中找到设置自身代理的地方。
那我现在只能把windows代理设置为A网络要求的代理服务器，再开启clash代理会导致windows代理被覆盖，无法上网。

### Possible Solution

支持给clash自身设置上网代理服务器。

**Comment by xuan880** [comment]
可以用relay来实现,先创建一个A网络的代理,然后创建relay型代理组,第一个选用A网络代理,后面在启用其他代理.

**Comment by ZhuangJiayu** [comment]
gost 或者 glider
