### ISSUE TITLE
[Feature] 解析proxy-providers优先解析http类型的

### ISSUE THREAD

**Issue by Geniucker** [Dreamacro/clash#2567]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [x]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我想使用一个http类型的provider获取节点，然后再用其他file类型的provider做国家地区分类，但是现在第一次运行的时候file类型的provider会报找不到对应的文件，如果优先解析http类型的provider并下载文件就能解决这个问题。

**Comment by wmyfelix** [comment]
没懂，按国家分类可尝试这个项目https://github.com/wmyfelix/ClashAddons

**Comment by wmyfelix** [comment]
原来clash已经有filter option了，可以忽略我的旧玩具。

**Comment by wmyfelix** [comment]
你可以尝试把远程文件的selection置于本地的之前，这样会大概会优先下载。

**Comment by Geniucker** [comment]
> 你可以尝试把远程文件的selection置于本地的之前，这样会大概会优先下载。

这个试过了没用

**Comment by Geniucker** [comment]
> 没懂，按国家分类可尝试这个项目https://github.com/wmyfelix/ClashAddons

我国家分类原先也是是全http类型，但是这样的缺点是请求书非常多，所以我就想一个拉取全部节点，然后别的provider就只用来分类

**Comment by Geniucker** [comment]
我原来的想法和你是一样的<https://github.com/geniucker/sub-conv>  
你可以看一下最近一次revert的commit你可能就知道我在说什么了  
虽然代码也是a piece of shit

**Comment by wmyfelix** [comment]
嗯嗯我看了，明显你这个更scalable。我目前是定时pull订阅和rules然后cache到仓库里，同时生成providers。一直想做成你这种接口配一个前端，我研究下你的代码。

**Comment by wmyfelix** [comment]
这个pr可以满足你我的需求
https://github.com/Dreamacro/clash/pull/2518

**Comment by Geniucker** [comment]
确实，把filter放到proxy-group会省很多事

**Comment by Geniucker** [comment]
> 

似乎meta内核已经支持了，但是我这个不是我一个人在用还不能马上改🥲

**Comment by wmyfelix** [comment]
（我也要上车

On Feb 26, 2023 1:56 PM, Geniucker ***@***.***> wrote:

似乎meta内核已经支持了，但是我这个不是我一个人在用还不能马上改🥲

**Comment by Geniucker** [comment]
> （我也要上车

来点星星哈哈哈

**Comment by Dreamacro** [comment]
pr merged
