### ISSUE TITLE
[Feature Request]增加direct和reject内置代理类型

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#257]
这其实是Surge的一个特性：[Built-in Policy](https://manual.nssurge.com/policy/built-in.html)
clash实现不复杂，相当于alias一下：
```yaml
Proxy:
  - { name: "On", type: direct }
  - { name: "Off", type: reject }
```
增加这两个Proxy类型，有时候就不需要依赖DIRECT，REJECT这两个内置Proxy Group的策略了，可以更加灵活地配置文件。
而且如果以后实现了tun了的话，还可以增加`interface`的选项，e.g.
```yaml
Proxy:
  - { name: "WiFi", type: direct, interface: en2 }
```
就可以这样来指定出口。

**Comment by jsnjycwyz** [comment]
> @jsnjycwyz REJECT DIRECT

懂了
