### ISSUE TITLE
[求助] 请问clash是否支持重写userAgent呢

### ISSUE THREAD

**Issue by IDeLoveYou** [Dreamacro/clash#2574]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

由于我们校园网会检测userAgent的值来判断是否多设备在线，于是我在软路由上加了一个代理，使所有经过软路由的请求都修改为一致，但是我在电脑使用clash时，clash帮我发的请求不知道该怎么修改ua，我在config.yaml 的顶层配置增加
`userAgent: 'clash/1.1'`
但是clash发的请求并没有修改到userAgent的值，我想请问clash是否支持重写userAgent呢？支持的话该怎么设置呢

**Comment by techblack** [comment]
校园网只能检测到80,8080等纯http请求的ua，而经过clash代理的请求基本都是加密的tls或者ss等协议的，校园网是无法检测的，你要关注的DIRECT的请求，这些请求中可能含有纯http的，这些请求经过你的软路由，应该也会正常的被处理ua，如果你要本地进行处理，可以建一个direct链，把请求转发到你的可以修改ua的socks/http/ss等的服务器

**Comment by IDeLoveYou** [comment]
丢，懂了，听君一席话胜读十年书
