### ISSUE TITLE
[Feature] Force rewrite HTTP to HTTPS

### ISSUE THREAD

**Issue by QS0x01** [Dreamacro/clash#2575]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

chatGPT 给了我这样一个结果

![image](https://user-images.githubusercontent.com/119924985/222164810-4a226db9-a3ef-42e5-8fc8-d38253d194a1.png)

但是 ACL4SSR 的项目里并没有这个文件。

![image](https://user-images.githubusercontent.com/119924985/222165028-232336e1-995d-4405-b718-1fe342584c65.png)

但是 wiki 的配置文件里 Ctrl + F 没找到关键词，搜了下历史 issues 还发现了这个 https://github.com/Dreamacro/clash/issues/915

所以想来问问是 chatGPT 在胡扯还是这项特性被移除了？

**Comment by QS0x01** [comment]
试了下 clash 应该是没有这个特性的。老老实实装了 light proxy 解决问题。

![image](https://user-images.githubusercontent.com/119924985/222175607-0ccd6a03-8290-4e46-b508-06592ffc11a0.png)

**Comment by Dreamacro** [comment]
chatgpt 在瞎扯
