### ISSUE TITLE
[Feature] Killswitch and Split tunneling

### ISSUE THREAD

**Issue by Terrast** [Dreamacro/clash#2577]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

I think having these two options could make Clash a perfect VPN. I hope you consider adding these two to the app!

**Comment by BirkhoffLee** [comment]
1. What do you mean by Killswitch?
2. Split tunneling: Clash does not alter the routing table by default unless you specify the auto-route options in Clash Premium
