### ISSUE TITLE
fake-ip模式下，ntp客户端无法正常同步时间。

### ISSUE THREAD

**Issue by NV3S** [Dreamacro/clash#258]
在本人网络环境中，在旁路由上和pc上，分别部署了openclash和cfw（测试和使用时仅开启一个）。
使用诸如windows时间同步（域名time.windows.com/外解析ip 40.119.6.228/52.173.193.166等多个）时，如果使用了clash的fake-ip模式，时间同步（时间服务器域名方式）就失败了。
其他ntp客户端，比如旁路由自己的时间同步，以及ap、网内的智能电视，都是无法在旁路由fake-ip模式下同步时间，pc则是在cfw fake-ip模式下测试。改用redir-host则同步正常。

因为有一些ntp服务器无法更改，比如智能电视，并且如果使用ip的情况可能会遇到ip变动导致失效的问题，所以还是希望以域名进行同步。

请问这是特性使然，还是能够通过设置或者更新解决？

**Comment by Dreamacro** [comment]
ntp 协议是 UDP 的，fake-ip 不能是因为 UDP 流量没有流入现有的 UDP inbound (socks5)。redir-host 可以是因为 iptable 对 UDP 流量进行直连。tproxy 实现在 macOS 下没找到响应的 go 实现。要完全解决可能要等之后的 TUN。

**Comment by NV3S** [comment]
收到

**Comment by NV3S** [comment]
https://github.com/vernesong/OpenClash/releases/tag/v0.33.7-beta
openclash 0.33.7版通过建立了一个域名名单让特定域名走特定dns提供了一种解决方案。

**Comment by yykhysn** [comment]
目前可用 tproxy将UDP流量交给redsocks，而后redsocks再将UDP流量封在TCP中，打向Clash的Socks5端口，而实现UDP的透明代理吗？ @Dreamacro
