### ISSUE TITLE
[Feature] clash能支持多个端口本地代理分流吗

### ISSUE THREAD

**Issue by piqihaha** [Dreamacro/clash#2583]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前发现好像只能开一个本地代理端口，默认的7890那个
我想有没有办法开N个本地代理端口， 
比如我开了10个浏览器，每个浏览器设置不同的本地代理端口，
然后10个浏览器都不同的IP ？
或者有没有其他可替代的机场客户端能实现呢

**Comment by Dreamacro** [comment]
可以通过 PROCESS-PATH 区分不同的浏览器流量

**Comment by piqihaha** [comment]
> 以通过 PROCESS-PATH 区分不同的浏览器流量

有没有配置文件模版发一个 我参考参考呢

**Comment by jackwan990** [comment]
@Dreamacro 
同问这个问题，实在是不知道在配置文件哪里配置以及配置的格式。
开启两个chrome浏览器，chromeA和chromeA，希望chromeA能走一个代理a ip，chromeB能走另外一个代理b ip
希望通过 PROCESS-PATH 来实现chromeA和chromeA走不同的ip。请问再配置文件哪里写以及配置格式？谢谢

**Comment by BirkhoffLee** [comment]
https://github.com/Dreamacro/clash/wiki

**Comment by guocuixia** [comment]
> 可以通过 PROCESS-PATH 区分不同的浏览器流量

请教如何配置呢？
