### ISSUE TITLE
用户不清楚自己的操作系统应该下载那一个版本的clash安装包。

### ISSUE THREAD

**Issue by Pan-will** [Dreamacro/clash#2585]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

<img width="874" alt="image" src="https://user-images.githubusercontent.com/50573470/222969777-2f738d44-e451-439e-bb3a-e272c356e9d9.png">
如上图，不如考虑将各个版本的安装包加上：for mac 、 for  mac  M1/M2、for Windows 32bits、for Windows 64bits、for Linux, 等等。
对用户来说更加友好。

**Comment by pfangzhi** [comment]
以cpu来区分的，比如linux吧，我要使用的就有三个架构的，mt7621的，arm64版本的，in特尔和amd的最新的还分x86和x64，一看你就是那种只会用windows的那种的人，就算windows10现在也区分 arm和x86架构的。只是你 没见过而已。

**Comment by wmyfelix** [comment]
@Pan-will 这样确实会好一点，但是我觉得更适合写在wiki这种地方。

**Comment by BirkhoffLee** [comment]
之后会写进 wiki 改善，感谢建议
