### ISSUE TITLE
[Bug] TUN模式下WIN7表现是路由转发失败以及无法nslookup到ip地址

### ISSUE THREAD

**Issue by pfangzhi** [Dreamacro/clash#2592]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.03.04

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
 enable: true
 stack: system
 dns-hijack: ['198.18.0.2:53']
 auto-route: true
 auto-detect-interface: true
```

### Description

新版本的clash无法正常路由表，WIN7系统异常，同版本同配置Win10系统没问题，换成2023.01.27版本的话在Win7和Win10上都没有问题

**Comment by pfangzhi** [comment]
[90m16:32:06[0m [31mWRN[0m [TUN] auto set route failed [31merror=failed to
set DNS: netsh: exit status 1: "\xb7\xfe\xce\xf1\xc9\xd0δ\xc6\xf4\xb6\xaf\xa1\x
a3\n\n\n\xb7\xfe\xce\xf1\xc9\xd0δ\xc6\xf4\xb6\xaf\xa1\xa3"[0m
[90m16:32:06[0m [32mINF[0m [Inbound] TUN listening [36miface=[90mClash[0m
 [36mgateway=[90m198.18.0.1[0m
[90m16:32:12[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:57345[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:12[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:57349[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:12[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:57348[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:18[0m [31mWRN[0m [TCP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:57205[0m [36mrAddr=[90mmtalk.g
oogle.com:5228[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:18[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:50368[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:18[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:57345[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:18[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:50369[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:23[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:50370[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:23[0m [31mWRN[0m [TCP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:57206[0m [36mrAddr=[90mmtalk.g
oogle.com:5228[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m
[90m16:32:23[0m [31mWRN[0m [UDP] dial failed [31merror=4.8x8.top:442 connec
t error: all DNS requests failed, first error: context deadline exceeded[0m [3
6mproxy=[90mfz[0m [36mlAddr=[90m198.18.0.1:50371[0m [36mrAddr=[90m223.5.5
.5:53[0m [36mrule=[90mMatch[0m [36mrulePayload=[90m[0m

**Comment by pfangzhi** [comment]
经过一天的测试，问题应该是出在自动路由器设置这里，如果不采用自动设置路由器的话，手工输入dns为 198.18.0.2那么本地tun透明代理没有问题。同样配置在win10系统没有这个问题，1.29日前的版本没有任何问题。

**Comment by Dreamacro** [comment]
调用的是 https://github.com/WireGuard/wireguard-windows 来设置的 dns，估计也不支持 win7 了
