### ISSUE TITLE
[Feature] Add a certain "stickiness" to fallback proxy group

### ISSUE THREAD

**Issue by VZiChoushaDui** [Dreamacro/clash#2593]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Suppose we have a fallback proxy group with two servers A and B, and with health check interval of 60 seconds. We prefer users to connect to A when it's available.

Now, let's suppose on a certain network, server A is suffering from many packet losses, but not completely blocked, and only 10% of health check pings go through successfully.

Upon a failed health check of A, proxy group switches to server B. But then, as 10% of health check pings for A are successful, there's a 10% chance on each health check interval that fallback sees A as available and switches back to A.

Now, user will have a very poor connection to server A until the next health check interval or for the timeout period of the connection to A, where it will be switching back to B again. This oscillation can occur in the lifetime of the Clash for user in this network, resulting in an unreliable connection.

Obviously, the url-test proxy group can't help in this scenario either, because the reliability of the connection might not have a correlation with its ping time, and also we can't set priority for url-test group.

### Possible Solution

A solution to this might be an optional property for the fallback proxy group, requiring multiple consecutive health check successes before switching back to a higher priority server. (And possibly also multiple consecutive failures before switching to a lower priority server, for the opposite scenario)

If such option exists, in the described scenario, after user switches to B, it will need for example 3 positive health checks in a row from server A before switching back to A, and as it's unlikely to happen in this scenario, user will remain on server B on this network, but finally will switch back to A whenever a *reliable* connection to A is possible.

**Comment by VZiChoushaDui** [comment]
If there's an interest regarding this from the project maintainers, we can try implementing and submitting a pr.

**Comment by Dreamacro** [comment]
@VZiChoushaDui If it does not affect the current health check code, you can try it at any time. However, if the health check code needs to be modified, more discussion is needed.
