### ISSUE TITLE
[Bug] mac m1 无法通过 clash_test

### ISSUE THREAD

**Issue by daveyuuuu** [Dreamacro/clash#2594]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.13.0

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
mixed-port: 10000
log-level: silent
```

### Clash log

```shell
$ make test                                           
go test -p 1 -v ./...
=== RUN   TestClash_Basic
time="2023-03-08T18:12:13+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:10000"
    clash_test.go:657: 
                Error Trace:    /Users/yuzhiwei02/temp/clash/test/clash_test.go:657
                Error:          Should be true
                Test:           TestClash_Basic
--- FAIL: TestClash_Basic (5.02s)
=== RUN   TestClash_DNS
--- PASS: TestClash_DNS (1.21s)
=== RUN   TestClash_DNSHostAndFakeIP
--- PASS: TestClash_DNSHostAndFakeIP (1.18s)
=== RUN   TestClash_SnellObfsHTTP
--- PASS: TestClash_SnellObfsHTTP (1.52s)
=== RUN   TestClash_SnellObfsTLS
--- PASS: TestClash_SnellObfsTLS (1.48s)
=== RUN   TestClash_Snell
--- PASS: TestClash_Snell (1.48s)
=== RUN   TestClash_Snellv3
--- PASS: TestClash_Snellv3 (1.85s)
=== RUN   TestClash_Shadowsocks
--- PASS: TestClash_Shadowsocks (1.86s)
=== RUN   TestClash_ShadowsocksObfsHTTP
--- PASS: TestClash_ShadowsocksObfsHTTP (2.36s)
=== RUN   TestClash_ShadowsocksObfsTLS
--- PASS: TestClash_ShadowsocksObfsTLS (2.40s)
=== RUN   TestClash_ShadowsocksV2RayPlugin
--- PASS: TestClash_ShadowsocksV2RayPlugin (2.39s)
=== RUN   TestClash_Trojan
--- PASS: TestClash_Trojan (2.34s)
=== RUN   TestClash_TrojanGrpc
--- PASS: TestClash_TrojanGrpc (1.89s)
=== RUN   TestClash_TrojanWebsocket
--- PASS: TestClash_TrojanWebsocket (1.89s)
=== RUN   TestClash_Vmess
--- PASS: TestClash_Vmess (1.81s)
=== RUN   TestClash_VmessTLS
--- PASS: TestClash_VmessTLS (1.89s)
=== RUN   TestClash_VmessHTTP2
--- PASS: TestClash_VmessHTTP2 (3.92s)
=== RUN   TestClash_VmessHTTP
--- PASS: TestClash_VmessHTTP (1.85s)
=== RUN   TestClash_VmessWebsocket
--- PASS: TestClash_VmessWebsocket (1.86s)
=== RUN   TestClash_VmessWebsocketTLS
--- PASS: TestClash_VmessWebsocketTLS (1.87s)
=== RUN   TestClash_VmessWebsocketTLSZero
--- PASS: TestClash_VmessWebsocketTLSZero (1.87s)
=== RUN   TestClash_VmessGrpc
--- PASS: TestClash_VmessGrpc (2.89s)
=== RUN   TestClash_VmessWebsocket0RTT
--- PASS: TestClash_VmessWebsocket0RTT (1.83s)
=== RUN   TestClash_VmessWebsocketXray0RTT
--- PASS: TestClash_VmessWebsocketXray0RTT (1.84s)
FAIL
FAIL    clash-test      51.190s
FAIL
make: *** [test] Error 1
```

### Description

用了以 clash 为核心的软件有一段时间了，前来学习一下用法
但是在运行单元测试时，无法通过 TestClash_basic 测试，通过以下几种尝试可通过测试，但不清楚为啥，所以提个 issue
1. 注释了 init 函数中对 isDarwin 的判断分支，即 localIP 使用 127.0.0.1 可通过
2. 在 listener.go 中，genAddr 函数返回中 127.0.0.1 替换为 0.0.0.0 可通过

不清楚两个方法的影响，所以没提 pr

**Comment by Dreamacro** [comment]
这里可以直接把 localip 换成 127.0.0.1，localip 是用来让不支持 network=host 的 macOS docker 容器里访问宿主机使用的。

**Comment by daveyuuuu** [comment]
> 这里可以直接把 localip 换成 127.0.0.1，localip 是用来让不支持 network=host 的 macOS docker 容器里访问宿主机使用的。

啊，确实！我这改完了只单独测了 clash_test，其他的一起测了下果然 fail 了...明白了~ 多谢~

**Comment by Dreamacro** [comment]
可以 pr 把这里改成 127 👀
