### ISSUE TITLE
[Question] 如何命令行切换代理

### ISSUE THREAD

**Issue by imzhuhl** [Dreamacro/clash#2603]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我在没有图形界面的 linux 配置 clash，看了 github wiki 和 gitbook 的文档，但是不明白启动了以后如何切换代理节点，有没有相关资料可以分享

**Comment by Dreamacro** [comment]
http://clash.razord.top 可以打开审查元素看请求的 api

**Comment by imzhuhl** [comment]
明白了

**Comment by Dreamacro** [comment]
这里也有 https://github.com/Dreamacro/clash/wiki/External-controller-API-Reference

**Comment by Elite-zx** [comment]
请问怎么配置 config.yaml 以修改节点，要修改那些字段呢

**Comment by jinghan23** [comment]
请问有没有详细一点的解释呢，不明白什么是审查元素，api reference的文档看得很迷惑不知道怎么用

**Comment by jinghan23** [comment]
请问这个GUI怎么用

> > 请问有没有详细一点的解释呢，不明白什么是审查元素，api reference的文档看得很迷惑不知道怎么用
> 
> 先了解一下前端浏览器调试跟 RESTful API 的基本知识就不迷惑了，文档已经很清楚了。既然很迷惑那用现成的 [GUI](http://clash.razord.top/) 不好吗？
