### ISSUE TITLE
[Feature] 运行时加载第三方插件 (如 ss +v2ray_plugin)

### ISSUE THREAD

**Issue by triggered96** [Dreamacro/clash#2604]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Clash 拥有强大的分流功能策略，实现节点切换。这一点我非常值得欣赏。我也看过该项目下的issue，也有一些提及添加其他协议 https://github.com/Dreamacro/clash/issues/2427，比如基于http/2的naive。

目前如果通过 Clash 配合 naive 使用，就需要 通过 socks 5 进行转发。 但不方便的是，如果节点列表有多个 naive 配置的节点，就需要开多个naive，配置多个 socks 放置到clash中来进行切换，很不便捷。 为此作者能否考虑 类似之前 ss +v2ray_plugin 两个程序那样，加载第三方内核插件？

思路：
1、将naive 放置到 /usr/sbin/目录中。
2、Clash 配置 https 代理协议，通过plugin来指定该协议是否通过本地的 /usr/sbin/naive 来执行。

当切换到该协议时，clash会分配一个随机未被占用的端口作为 socks端口，同时通过该 socks端口 启用 naive 来执行。clash配置的节点信息也同时用于在naive中启动执行。

```
  - name: "naiveproxy-https"
    type: https
    server: example.com
    port: 443
    username: "username"
    password: "password"
    host-resolver-rules: "MAP example.com 172.26.0.34"
    plugin: naive-plugin
  - name: "naiveproxy-quic"
    type: quic
    server: example
    port: 443
    username: "username"
    password: "password"
    host-resolver-rules: "MAP example.com 172.26.0.34"
    plugin: naive-plugin
```

当用户选择节点naiveproxy-https时，clash会把 server、port（clash随机生成未分配的端口）、username、password、host-resolver-rules 传递给  /usr/sbin/naive 来执行。
```
# 后台naive会被执行
naive --listen=socks://[addr][:port] --proxy=<proto>://<user>:<pass>@<hostname>[:<port>]
```

当用户切换另一个节点时，该后台的 naive 进程会被kill 掉（生命周期结束），直到用户切换下一个节点是 naiveproxy-https 时。

注意：naive可用通过配置文件配置，也可以通过命令行方式配置，但我觉得通过命令行方式配置比较合适。
```
    {
      "listen": "...",
      "proxy": "..."
    }
```

**Comment by triggered96** [comment]
我相信该功能也是绝大多数人呼吁的。

**Comment by triggered96** [comment]
上述方案好处在于，naive内核可用单独更新，同时兼具clash强大的分流功能。

**Comment by m2acgi** [comment]
直接用 shell 脚本来做不是更好？

**Comment by guider** [comment]
同求 目前naive 协议还是非常重要的，
