### ISSUE TITLE
[Bug] X86版本Linux下，vmess协议都不能用了

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#2606]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

premium.3.4

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
- { name: 🇭🇰香港01｜HGC｜2x, type: vmess, server: xxx, port: 49111, uuid: xxx, alterId: 0, cipher: auto, udp: true }
```

### Clash log

```shell
没有任何异常
```

### Description

同一个局域网下，手机上节点都正常，Linux下全部都是红色，不知道原因

**Comment by Dreamacro** [comment]
同步下时间吧

**Comment by tony1016** [comment]
> 同步下时间吧

真的这个问题，就差两分钟而已，感谢
