### ISSUE TITLE
[Question] What is the difference between `v1.13.0.gz` and `v3-v1.13.0.gz`?

### ISSUE THREAD

**Issue by Ackerven** [Dreamacro/clash#2611]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

First of all, I'm very sorry for opening a question in the issue, I opened the discussion page but its state is 404.

I found a description of the version in the wiki.

![image](https://user-images.githubusercontent.com/70303900/225193562-e50d65f1-cd11-4b97-9241-ec08f7150c56.png)

Does `v3-v1.13.0.gz` stand for Clash Premium version?

**Comment by goodffd** [comment]
add darwin-amd64-v3 linux-amd64-v3 freebsd-amd64-v3 and windows-amd64-v3 for modern CPU. A detailed description can be found [here](https://golang.org/wiki/MinimumRequirements#amd64).

**Comment by Dreamacro** [comment]
thanks @goodffd
