### ISSUE TITLE
开启dns后，debug提示：All DNS requests failed

### ISSUE THREAD

**Issue by cjjdaq** [Dreamacro/clash#262]
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 127.0.0.1:5353

clash监听53，上游是dnsmasq的5353，用来dns分流。
路由透明代理,debug一直提示一下日志。正向解析正常。
{"type":"debug","payload":"[DNS Server] Exchange 234.0.168.192.in-addr.arpa. IN PTR failed: All DNS requests failed"}
{"type":"debug","payload":"[DNS Server] Exchange 234.0.168.192.in-addr.arpa. IN PTR failed: All DNS requests failed"}
{"type":"debug","payload":"[DNS Server] Exchange 234.0.168.192.in-addr.arpa. IN PTR failed: All DNS requests failed"}
{"type":"debug","payload":"[DNS Server] Exchange 81.0.168.192.in-addr.arpa. IN PTR failed: All DNS requests failed"}
{"type":"debug","payload":"[DNS Server] Exchange 81.0.168.192.in-addr.arpa. IN PTR failed: All DNS requests failed"}
{"type":"debug","payload":"[DNS Server] Exchange 81.0.168.192.in-addr.arpa. IN PTR failed: All DNS requests failed"}

还有一些proxy中的服务器提示解析出错
{"type":"debug","payload":"[DNS] response msg error: \u0026dns.Msg{MsgHdr:dns.MsgHdr{Id:0xea05, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:\"服务器域名.\", Qtype:0x1c, Qclass:0x1}},

**Comment by Fndroid** [comment]
> ```
> nameserver:
>    - 127.0.0.1:5353
> ```

说明设置的这个 DNS 服务器解析不了

**Comment by cjjdaq** [comment]
但是将端口调换，127.0.0.1：5353换成53，而且将clash的换成5353，就没有这种提示了

**Comment by Dreamacro** [comment]
> 上游是 dnsmasq 的 1053

> nameserver:
> - 127.0.0.1:5353

端口错了？

**Comment by cjjdaq** [comment]
@Dreamacro 
写错了，上有的dnsmasq端口就是5353.不是1053。

**Comment by comzyh** [comment]
我也遇到了 
Qtype=0x1c 即 AAAA，也就是目标服务器没有 AAAA 记录，即没有 ipv6 地址

**Comment by Andychencn** [comment]
我遇到了相同的问题，环境是clash for windows 8.1版直连外网，使用TAP模式做全局透明代理。dns的nameserver直接填写的外网dns服务器。Clash的本地dns端口也配置的53
addr.arpa的问题和顶楼一模一样，proxy的解析错误我通过配置ipv6: false解决了。目前代理使用正常，不过addr.arpa的错误日志每分钟就会生成10条左右，出现非常频繁。

**Comment by Dreamacro** [comment]
最新版本还遇到的话再 open

**Comment by shensven** [comment]
我也遇到了DNS请求失败的是的问题，不清楚是不是我自己配置的问题

#899

**Comment by coderbean** [comment]
遇到了同样的问题，没有在配置文件中指定dns服务器。开启了增强模式，表现时微信表情无法显示
```
020/08/26 13:47:09:673  [warning] dial 🍎 苹果服务 error: All DNS requests failed, first error: use default dns resolve failed: couldn't find ip
2020/08/26 13:47:09:674  [warning] dial 🍎 苹果服务 error: All DNS requests failed, first error: use default dns resolve failed: couldn't find ip
2020/08/26 13:47:09:676  [warning] dial 🍎 苹果服务 error: All DNS requests failed, first error: use default dns resolve failed: couldn't find ip
```
