### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by zhl111** [Dreamacro/clash#2620]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

windows-386-1.13

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
无
```

### Clash log

```shell
无
```

### Description

双击安装时出现问题：
time="2023-03-16T13:56:01+08:00" level=info msg="RESTful API listening at: 127.0.0.1:14657"
time="2023-03-16T13:56:01+08:00" level=error msg="Start Mixed(http+socks) server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

不知如何解决，救救
我已经关闭了我认为有干扰的软件，似乎也没有效果

**Comment by Dreamacro** [comment]
也许你应该直接装个 clash for windows

**Comment by Ember14** [comment]
遇到相同问题。Encounter same proplem.
Prompt: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by BirkhoffLee** [comment]
盲猜 windows 防火墙问题
