### ISSUE TITLE
[Bug] [TUN] auto set route failed error=netlink receive: address family not supported by protocol

### ISSUE THREAD

**Issue by jizusun** [Dreamacro/clash#2623]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash 2023.03.04 linux amd64 with go1.20.1 Sat Mar  4 02:54:15 UTC 2023

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
dns:
  enable: true
  listen: 0.0.0.0:54
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
  fake-ip-filter:
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"

tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - tcp://8.8.8.8:53
  auto-route: true # auto set global route
  auto-detect-interface: true # conflict with interface-name
```

### Clash log

```shell
➜  ~ sudo -E clash
14:22:18 INF [Config] initial compatible provider name=auto-cn
14:22:18 INF [Config] initial compatible provider name=auto
14:22:18 INF [DNS] server listening addr=0.0.0.0:54
14:22:18 INF [API] listening addr=0.0.0.0:9090
14:22:18 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
14:22:18 DBG [TUN] interface up iface=utun gateway=198.18.0.1
14:22:18 DBG [TUN] mtu updated iface=utun gateway=198.18.0.1
14:22:18 WRN [TUN] auto set route failed error=netlink receive: address family not supported by protocol
14:22:18 INF [Inbound] TUN listening iface=utun gateway=198.18.0.1
14:22:18 DBG [TUN] interface up iface=utun gateway=198.18.0.1
14:22:18 DBG [TUN] mtu updated iface=utun gateway=198.18.0.1
```

### Description

重启了一下Linux就不行了，报错如log中所示。
有没有可能是更新了linux内核，内核太新了？
```
➜  uname -a
Linux ubuntu 5.15.0-68-generic #75-Ubuntu SMP Fri Feb 24 13:01:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Dreamacro** [comment]
不是内核问题，我内核是 6.1

/cc @Kr328

**Comment by jizusun** [comment]
> 

After enabling `ipv6` in `GRUB` the `auto-route` works again.

```
# Edit the GRUB configuration file
sudo nano /etc/default/grub

# Find the line that starts with GRUB_CMDLINE_LINUX_DEFAULT and add the following options:
ipv6.disable=0 ipv6.addrconf=0

# Save and exit the file

# Update GRUB configuration
sudo update-grub

# Reboot the system
sudo reboot

```
