### ISSUE TITLE
[Feature] Can we add regular expression support to DOMAIN-KEYWORD

### ISSUE THREAD

**Issue by PaTTeeL** [Dreamacro/clash#2628]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Can we add regular expression support to DOMAIN-KEYWORD?

So we can have the rule `DOMAIN-KEYWORD,baomitu|fastgit|jsdelivr|sevencdn|statically|staticfile|unpkg,DIRECT` in one line instead of adding a separate line for each keyword as now we do below:
```
DOMAIN-KEYWORD,baomitu,DIRECT
DOMAIN-KEYWORD,fastgit,DIRECT
DOMAIN-KEYWORD,jsdelivr,DIRECT
DOMAIN-KEYWORD,sevencdn,DIRECT
DOMAIN-KEYWORD,statically,DIRECT
DOMAIN-KEYWORD,staticfile,DIRECT
DOMAIN-KEYWORD,unpkg,DIRECT
```
And combining keywords of the same category together may make the user-defined rule list shorter and easier to read?

**Comment by BirkhoffLee** [comment]
There's currently no plan on implementing this. However you could submit a PR and we could consider merging it.
