### ISSUE TITLE
[Bug] 删除配置中的enhanced-mode字段后 无法根据域名分流

### ISSUE THREAD

**Issue by zhiqiang02** [Dreamacro/clash#2629]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

premium 2023.03.18 

### Clash config

```yaml
dns: 
  enable: true
  # enhanced-mode: fake-ip
  .......
```

### Clash log

02:48:20 INF [UDP] connected, doesn't match any rule lAddr=198.18.0.1:55098 rAddr=198.18.0.2:53 proxy=DIRECT
02:48:20 INF [UDP] connected, doesn't match any rule lAddr=198.18.0.1:55093 rAddr=198.18.0.2:53 proxy=DIRECT
02:48:20 INF [UDP] connected, doesn't match any rule lAddr=198.18.0.1:55094 rAddr=198.18.0.2:53 proxy=DIRECT
......

### Description

由于在clash wiki上看到因redir-host移除把dns.enhanced-mode字段注释掉了，于是自己手贱跟着删了。。。
猜测是删掉该字段后clash拿不到域名
加上即恢复，但还是希望排查并修复

**Comment by Dreamacro** [comment]
删除了 redir-host，fakeip 还在

**Comment by leiusual** [comment]
呃，我也以为删除后 默认值就是 fake-ip 了。。。

**Comment by SakuraSakuraSakuraChan** [comment]
> 猜测是删掉该字段后clash拿不到域名

猜对了，就是拿不到，没什么排查修复的
