### ISSUE TITLE
[Help] 运行Clash后，所有的监听端口都在ipv6上

### ISSUE THREAD

**Issue by GunKneeNeon** [Dreamacro/clash#2630]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Clash version

clash v1.13.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
1 port: 7890
    2 socks-port: 7891
    3 redir-port: 7892
    4 allow-lan: true
    5 mode: Rule
    6 log-level: info
    7 external-controller: 0.0.0.0:9090
    8 dns:
    9    enable: true # set true to enable dns (default is false)
   10    ipv6: false # default is false
   11    listen: 0.0.0.0:1053
   12    enhanced-mode: redir-host # or fake-ip
   13    fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
   14    nameserver:
   15       - https://doh.pub/dns-query
   16       - https://dns.alidns.com/dns-query
   17       - https://i.233py.com/dns-query
   18    fallback:
   19       - https://cloudflare-dns.com/dns-query
   20       - https://doh.opendns.com/dns-query
   21       - https://dns.google/dns-query
   22       - https://dns.nextdns.io/dns-query
   23       - https://doh.233py.com/dns-query
```

### Clash log

```shell
INFO[0002] RESTful API listening at: [::]:9090
WARN[0002] [CacheFile] can't open cache file: open /etc/clash/cache.db: permission denied
INFO[0002] HTTP proxy listening at: [::]:7890
INFO[0002] SOCKS proxy listening at: [::]:7891
INFO[0002] Redirect proxy listening at: [::]:7892
WARN[0002] [DNS] redir-host is deprecated, please use fake-ip instead
INFO[0002] DNS server listening at: [::]:1053
```

### Description

请问为什么我的clash运行后，端口都监听在ipv6上面？这个造成的主要问题是我无法访问dashboard。

PS：不好意思这边是提交的bug分类，因为我发帖前选择开讨论那一栏，结果弹出了404。

**Comment by Dreamacro** [comment]
默认应该是监听在双栈下的吧？不影响

**Comment by GunKneeNeon** [comment]
> 默认应该是监听在双栈下的吧？不影响

这是我用`netstat -l`看到的内容：

netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:8070            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:netbios-ssn     0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8087            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:smtp            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:microsoft-ds    0.0.0.0:*               LISTEN
tcp6       0      0 [::]:9090               [::]:*                  LISTEN
tcp6       0      0 [::]:netbios-ssn        [::]:*                  LISTEN
tcp6       0      0 [::]:7890               [::]:*                  LISTEN
tcp6       0      0 [::]:7891               [::]:*                  LISTEN
tcp6       0      0 [::]:7892               [::]:*                  LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
tcp6       0      0 [::]:microsoft-ds       [::]:*                  LISTEN
udp        0      0 192.168.0.25:netbios-ns 0.0.0.0:*
udp        0      0 192.168.0.3:netbios-ns  0.0.0.0:*
udp        0      0 0.0.0.0:netbios-ns      0.0.0.0:*
udp        0      0 192.168.0.2:netbios-dgm 0.0.0.0:*
udp        0      0 192.168.0.3:netbios-dgm 0.0.0.0:*
udp        0      0 0.0.0.0:netbios-dgm     0.0.0.0:*
udp6       0      0 [::]:1053               [::]:*
udp6       0      0 [::]:7891               [::]:*
udp6       0      0 [::]:7892               [::]:*

9090端口只在tcp6下有，tcp下没有。我用浏览器访问 `192.168.0.3:9090/ui` 的结果是`404 page not found`
请一定要帮我想想办法，这个问题已经困扰我很久了，我尝试了几个版本都是一样。

**Comment by Dreamacro** [comment]
返回404恰恰说明正常啊，默认是没有 gui 的，你得自己配置 ui 目录

**Comment by GunKneeNeon** [comment]
> 返回404恰恰说明正常啊，默认是没有 gui 的，你得自己配置 ui 目录

太感谢了，问题解决了。
不知道为什么，很久之前用的版本是自带ui的，所以没有习惯自己来配置，后面下载的都没有了，就搞不清是哪里弄错了。

**Comment by Dreamacro** [comment]
没有自带过，你肯定哪里弄错了
