### ISSUE TITLE
[Feature] 当某个直连网站域名的一个 IP 超时时，则从 DNS 解析的结果中换用其他 IP 连接该域名

### ISSUE THREAD

**Issue by WangHaonie** [Dreamacro/clash#2631]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

有些直连的网站可能会因为运营商线路或目标服务器出现了问题导致超时无法访问，则从 DNS 解析返回的结果中换用其他 IP 访问。假设要访问某国内网站 example.cn，DNS 解析返回结果为 10.0.0.1, 10.0.0.2 (或更多)，但此时访问 10.0.0.1 超时，这个情况下就可以尝试换 10.0.0.2 去连接这个网站就有可能正常访问，若不行就再换一个 IP。但如果某网站只有一个 IP，那就没法了。

纯小白提出，若有不合理的地方欢迎指出

**Comment by pfangzhi** [comment]
你真的是小白

**Comment by BirkhoffLee** [comment]
smartdns可以试试，clash不会支持这个功能
