### ISSUE TITLE
clash开启后只有ipv6代理，怎么回事？

### ISSUE THREAD

**Issue by dhz110** [Dreamacro/clash#2633]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

3月 21 08:47:32 debian clash[6701]: time="2023-03-21T08:47:32+08:00" level=info msg="Mixed(http+socks) proxy listening at: **[::]:7890**"
3月 21 08:47:32 debian clash[6701]: time="2023-03-21T08:47:32+08:00" level=info msg="RESTful API listening at: **[::]:9090**"

**Comment by BirkhoffLee** [comment]
v4 v6都有
