### ISSUE TITLE
[Feature] Chisel support

### ISSUE THREAD

**Issue by leshniak** [Dreamacro/clash#2636]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

I would like to suggest adding chisel support as a transport layer (https://github.com/jpillora/chisel). It supports TCP/UDP tunnels over HTTPS+WS. I'm heavily using both, clash and chisel, would love to have a client in one tool.

**Comment by Dreamacro** [comment]
But chisel doesn't seem to have any additional advantages over clash's existing protocols, so why choose the chisel?

**Comment by leshniak** [comment]
It has one advantage - a good multiplexing support, thanks to SSH proxy layer. Protocols from v2ray-core create many TLS handshakes and their muxing abilities are poor. In my use-case, I'd like to imitate one connection with a huge transfer (like while downloading a video file) rather than many small ones.
