### ISSUE TITLE
[Feature] Linux上部署clash，但是ping外网都不通，通过VNC打开浏览器来访问反而可以，求助

### ISSUE THREAD

**Issue by PPPeanut** [Dreamacro/clash#2637]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

![image](https://user-images.githubusercontent.com/25226443/226805111-a4e79a9d-e3f9-46fc-8a0f-4eb926e3fb23.png)
![image](https://user-images.githubusercontent.com/25226443/226805215-9c905e81-ca09-4255-96e7-b5aba4a02f3e.png)

命令行访问不了，用VNC连过去开浏览器可以，请问是我哪里漏了配置吗

clash UI上这个system proxy显示没开的，有影响吗
![屏幕截图 2023-03-22 124951](https://user-images.githubusercontent.com/25226443/226805034-8f781674-622d-484f-b100-fa77d2a85f73.png)

**Comment by FuckBug** [comment]
你的配置和设置都没问题。

ping命令是使用的ICMP协议，位于网络层。而Socks5代理是在会话层，自然就无法ping通。

终端要想走代理，需要在终端中设置（具体端口号以本地配置文件为主）：
```
export http_proxy="http://127.0.0.1:7890"
export https_proxy="http://127.0.0.1:7890"
```
测试：`curl -I www.google.com`
