### ISSUE TITLE
从0.16.1升级到0.17.5后原有配置文件失效

### ISSUE THREAD

**Issue by boyeye** [Dreamacro/clash#264]
0.16.1-beta升级到 0.17.5-beta后，原有配置文件失效，开始以为配置文件有问题，反复修改检查，发现并无异常，并且在clashx上反复验证都一切正常，一一排除问题发现是升级新版本后出现的问题，再刷回老版本，一切问题都消失了，估计新版本升级的同时也有部分冲突产生了，我不懂技术只是从科学上网的角度看问题，比较肤浅了，谢谢解答一下，加油！

**Comment by Dreamacro** [comment]
clash 只有 v0.15.0, 如果是 koolclash 的请在相关 repo 下提问

**Comment by boyeye** [comment]
非常感谢🙏
