### ISSUE TITLE
[Feature] 希望能够增加自动订阅功能

### ISSUE THREAD

**Issue by Mr-LiuDC** [Dreamacro/clash#2649]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前 Clash 只用用 config.yml 配置文件，希望可以自动根据订阅链接定期更新。

**Comment by Dreamacro** [comment]
这些工作 GUI 来做比较适合

**Comment by seayxu** [comment]
如果支持，在Linux系统中就很友好了，希望可以考虑一下

**Comment by luoxiao-xy** [comment]
同求

**Comment by lili2012** [comment]
> 要善于使用`proxy-providers`，为什么让机场控制你的配置文件呢，更新机场提供的节点就可以了。

我这里测试发现proxy-providers里一元机场的配置文件下载不下来。

**Comment by orwithout** [comment]
我自己建立了个订阅服务，通过更新订阅配置，来控制整个代理网络
我在routeros 的容器中使用clash
现在得自己写routeros脚本来跟新订阅服务

使用订阅更新配置，感觉是个非常强大的功能。软件定义网络？
希望core 也能自己实现，例如当环境变量 Subscription_url 存在则从变量的地址中下载配置……
