### ISSUE TITLE
[Feature] 希望 fake-ip-filter 能支持匹配域名关键字

### ISSUE THREAD

**Issue by DustinWin** [Dreamacro/clash#2654]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前 fake-ip-filter 只能匹配域名 domain，如：
```
- xxx.com
- '+.xxx.com'
- 'xxx.*.*'
```
希望能匹配域名关键字 keyword，并支持关键字前缀或后缀，如：
```
- '*xxx*'
- '*xxx'
- 'xxx*'
```

**Comment by fakeboboliu** [comment]
fake-ip-filter 是用线段树的，支持每一段单独关键词的话会造成几倍的性能损失。
如果再进一步，有了一段内的关键词肯定会有人要整体一起正则，那又是几倍的性能损失。

我认为不太可能，即使作为一个可选功能。

**Comment by BirkhoffLee** [comment]
根据目前的开发 roadmap，没有进一步完善 fake-ip-filter 的计划
