### ISSUE TITLE
[Question] Why do Proxy-Providers not be an array?

### ISSUE THREAD

**Issue by QS0x01** [Dreamacro/clash#2656]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

编写配置文件时，其它几个对象，如 proxies, proxy-groups, rules 都是数组。
于是下意识给 proxy-providers 的子项也加了 “-”，然后一看文档发现不一样。

### Possible Solution

仅好奇，无需PR。

**Comment by Dreamacro** [comment]
rules 是数组这个不需要解释了吧？

至于为什么 proxies, proxy-groups 需要数组是因为一开始 proxy-groups 支持嵌套，为了防止相互嵌套导致的循环依赖问题，写成数组的形式是最简单的，即写在前面的不能嵌套写在后面的 group。并且数组的形式能在 GUI 中提供和配置文件相同的顺序。

后面由于添加了循环依赖检测，所以「为了防止相互嵌套导致的循环依赖问题」这个需求不需要了，但这个时候没有必要从数组形式 break change 成 map 的形式。

proxy-providers 打一开始就没有循环依赖的问题，由于 name 也是唯一的，所以把它做成了 map 的形式

**Comment by QS0x01** [comment]
感谢解答。
