### ISSUE TITLE
[Feature] 局域网 https 代理不支持

### ISSUE THREAD

**Issue by John-zhan** [Dreamacro/clash#2657]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

局域网中的机器想要使用 局域网中别的机器的clash代理，发现https curl 拉不下来出现问题。经过4个小时的折腾发现clash 不支持局域网中 转发 https 代理，http 是可以的，我现在局域网中就是用的http 的代理。

我目前还有个问题，局域网中安卓上的telegram 无法使用，Windows上的telegram 却可以

**Comment by C8H7N** [comment]
终端下(Unix like)代理https直接使用
`export https_proxy=http://ip:7890`
即可
安卓tg要自己手动去setting设置代理 默认不走系统代理
