### ISSUE TITLE
请问如何打开cache.db文件？

### ISSUE THREAD

**Issue by yjps** [Dreamacro/clash#2658]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我有个dot dns在公网，我的设备与clash内网是通的，dns服务器与内网不通。
我想要打开cache.db文件，把里面的fakeip数据直接复制进公网dns服务器里。
请问要如何开打cache.db文件呢？或者有什么方法可以导出域名与fake-ip的对应关系。

**Comment by hinak0** [comment]
数据库是`BoltDB`
