### ISSUE TITLE
希望能做下MIMT已经变能精准的实现流量分流

### ISSUE THREAD

**Issue by cjjdaq** [Dreamacro/clash#266]
做mimt能够更好的识别流量实现流量分流。

**Comment by Kr328** [comment]
需要找到能够稳定的 给所有平台安装证书的方法

**Comment by cjjdaq** [comment]
这个应该属于高级一点的功能了。至于证书安装应该由用户自己搞定

**Comment by boyeye** [comment]
更正一下，是MitM

**Comment by ttimasdf** [comment]
为啥需要MITM？有SNI解析还不够么？

**Comment by BirkhoffLee** [comment]
作者目前不打算做 MITM：https://github.com/Dreamacro/clash/issues/227#issuecomment-508693628

**Comment by ddkwork** [comment]
设上证书之后websocket tls异常，读取协议升级返回eof，https正常
