### ISSUE TITLE
分应用程序走代理[Feature] 

### ISSUE THREAD

**Issue by Karonolandiis** [Dreamacro/clash#2664]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

在不使用Tun的时候，有的应用程序既不走系统代理也没有设置代理的选项，那么就只有开启tun让所有的应用程序都走clash的代理，但这样是很没必要的，因为大多数应用程序不需要代理。那么，是否可以实现在开启tun之后，按照应用程序名字来走代理呢？注意：不是rule里面的PROCESS-NAME XXX, DIRECT，而是直接类似bypass，完全不经过clash。

**Comment by Dreamacro** [comment]
> 那么，是否可以实现在开启 tun 之后，按照应用程序名字来走代理呢？

没有，这东西没有通用的解决方案
