### ISSUE TITLE
[Feature] 只有ubuntu下上不去chatgpt，总是报错国家地区不支持

### ISSUE THREAD

**Issue by bdxuyidong** [Dreamacro/clash#2667]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

ubuntu20.04，clash for windows v20.04。在global模式下连不上外网，google都上不去。在rule模式下能上google但是上不去chatgpt（已经使用美国或英国节点）。代理商提供的节点没有问题，同样的节点我在windows和安卓下用v2ray都能很快连上chatgpt。clash的GUI客户端我已经重装了好几次了，希望大家帮个忙，由于科研需求最近需要在ubuntu下使用chatgpt。
![Screenshot from 2023-04-08 11-53-20](https://user-images.githubusercontent.com/82100273/230702055-97ed2099-9f62-4568-a97a-e7b5390bcc15.png)
![Screenshot from 2023-04-08 11-55-05](https://user-images.githubusercontent.com/82100273/230702108-7f336f3f-8d1d-4518-aeeb-201312db8095.png)
感谢大伙了

**Comment by 1779587460** [comment]
是用wine运行CFW吗？
直接用clash-verge试试？

**Comment by Dreamacro** [comment]
装个新版吧

**Comment by justbelieveyourself** [comment]
global模式可能需要手动选择节点，你看下是不是这样

**Comment by banping957** [comment]
我是设置了规则，但还是直连，也是醉了，不知道哪里有问题

**Comment by BirkhoffLee** [comment]
如果是 cfw 的问题建议移步 https://github.com/Fndroid/clash_for_windows_pkg/issues
如果是规则问题请看 wiki
