### ISSUE TITLE
现在支持二级代理吗？谢谢 希望尽快支持 

### ISSUE THREAD

**Issue by MonsterRHD** [Dreamacro/clash#267]
现在支持二级代理吗？谢谢 希望尽快支持

**Comment by popu125** [comment]
![2471912.jpg](https://i.loli.net/2019/08/16/1sdfShqOZxtl52L.jpg)

**Comment by MonsterRHD** [comment]
前置代理 ，请问支持吗？

**Comment by ruisiji** [comment]
Could explain what is `前置代理`? What's you use case for this?

**Comment by MonsterRHD** [comment]
> 可以解释一下是`前置代理`什么？你用的是什么案例？

有两台服务器 称为（B服务器 C服务器）
我要连接C的服务器节点，但是C服务器对于我来说 网络延迟高，B服务器连接C服务器网络延迟很低，我连接B服务器网络延迟也很低，所以要加速网络 ，我需要连接B服务器，让B服务器代理C服务器

**Comment by BirkhoffLee** [comment]
到這邊討論 #434
