### ISSUE TITLE
[Bug] unexpected fault address

### ISSUE THREAD

**Issue by Ex-Origin** [Dreamacro/clash#2674]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2023.03.18

### Clash config

```yaml
tun:
    enable: true
    stack: system # or gvisor
    auto-route: false # auto set global route
    auto-detect-interface: false # conflict with interface-name
    dns-hijack:
        - 198.18.0.2:53
mixed-port: 7890
bind-address: 0.0.0.0
allow-lan: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: true
    default-nameserver: [114.114.114.114, 8.8.8.8]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://114.114.114.114/dns-query', 'https://223.5.5.5/dns-query']
    fallback: ['https://8.8.8.8/dns-query', 'https://1.1.1.1/dns-query', 'https://9.9.9.9/dns-query']
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
```

### Clash log

```shell
07:19:59 INF [TCP] connected lAddr=198.18.0.1:57062 rAddr=clientservices.googleapis.com:443 mode=rule rule=Domain(clientservices.googleapis.com) proxy=🎯 全球直连
07:20:02 INF [TCP] connected lAddr=198.18.0.1:35168 rAddr=1.1.1.1:443 mode=rule rule=IPCIDR(1.1.1.1/32) proxy=AutoEastAsia
07:20:02 INF [TCP] connected lAddr=198.18.0.1:54738 rAddr=9.9.9.9:443 mode=rule rule=IPCIDR(9.9.9.9/32) proxy=AutoAmerica
```

### Description

```
Mar 30 21:07:43 ubuntu clash-service[5443]: Start Service Successfully
Apr 13 07:20:07 ubuntu clash-service[5456]: unexpected fault address 0x7ff47958c5d1
Apr 13 07:20:07 ubuntu clash-service[5456]: fatal error: fault
Apr 13 07:20:07 ubuntu clash-service[5456]: [signal SIGBUS: bus error code=0x2 addr=0x7ff47958c5d1 pc=0x9242ad]
Apr 13 07:20:07 ubuntu clash-service[5456]: goroutine 20188051 [running]:
Apr 13 07:20:07 ubuntu clash-service[5456]: runtime.throw({0xc811b8?, 0x20?})
Apr 13 07:20:07 ubuntu clash-service[5456]:         runtime/panic.go:1047 +0x5d fp=0xc000f7b230 sp=0xc000f7b200 pc=0x4365fd
Apr 13 07:20:07 ubuntu clash-service[5456]: runtime.sigpanic()
```
[clash.log](https://github.com/Dreamacro/clash/files/11217402/clash.log)

**Comment by Dreamacro** [comment]
是刚启动就 panic 吗？

**Comment by Ex-Origin** [comment]
不是的，运行十多天了

**Comment by Dreamacro** [comment]
试试 latest 呢？

**Comment by Ex-Origin** [comment]
用的是最新版本，我设置了定时脚本更新Country.mmdb，早上6点20更新之后不久，程序就崩溃了，两次都是这样。一更新Country.mmdb后不久clash就会这样崩溃。

**Comment by Dreamacro** [comment]
程序是以 mmap 的方式读取 mmdb 的，所以造成了读取问题吧，替换 mmdb 后重启 clash

**Comment by Ex-Origin** [comment]
了解
