### ISSUE TITLE
docker clash 节点不稳定 不通

### ISSUE THREAD

**Issue by Joy-yuhuan** [Dreamacro/clash#2675]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Version v1.14.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
```

### Description

同样一个订阅节点，在win clash显示没有问题，但是在docker clash 显示节点不通。
![111](https://user-images.githubusercontent.com/76980536/231647051-6d861829-b8aa-45ce-bdff-7acdec38cfbf.jpg)
![222](https://user-images.githubusercontent.com/76980536/231647106-3f45e26c-eb5c-442f-8c97-5b5a5b713935.jpg)

**Comment by Joy-yuhuan** [comment]
用的群辉搭建的docker

**Comment by Dreamacro** [comment]
同步下时间吧

**Comment by Joy-yuhuan** [comment]
> 同步下时间吧

感谢，真的是群辉时间延长了好久，同步一下好了，谢谢！
