### ISSUE TITLE
API无法查看节点信息，是我打开的方式不对吗？

### ISSUE THREAD

**Issue by harbinbeer** [Dreamacro/clash#2679]
### Verify steps

- [ ]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [ ]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

关于API的用法：
`http://192.168.123.254:9090/proxies` 
返回全部节点列表和当前活动节点
`now	"448683"`

但是
 `http://192.168.123.254:9090/proxies/448683` 
只返回
`message	"Resource not found"`

自己编译的master版本
`# clash -v                                                    
Clash unknown version linux arm64 with go1.20.2 unknown time
`

**Comment by harbinbeer** [comment]
> 这个 `"448683"` 是不是在 `proxy-providers` 里面？

是的

**Comment by harbinbeer** [comment]
http://192.168.123.254:9090/proxies#43586
http://192.168.123.254:9090/proxies/#43586
返回都是全部节点，也就是跟
http://192.168.123.254:9090/proxies
相同内容，请问还有什么补充吗？

**Comment by BirkhoffLee** [comment]
https://github.com/Dreamacro/clash/wiki/External-controller-API-Reference#proxies
