### ISSUE TITLE
[Feature] 可以根据监听的端口进行分流代理吗

### ISSUE THREAD

**Issue by Jeffrey-deng** [Dreamacro/clash#2681]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

例如我的clash，监听的两个端口

- 7890 http
- 7891 socks

当我使用 `7890` 时那就走常用的规则处理
当我使用 `7891` 时，那就走如下类似的规则，让它全局代理
`     - BIND-PORT,7891,PROXY`

这样的使用场景是，我的系统代理设置为 `7890` 端口，这样国内国外都能用，
然后当一个软件需要全局代理时，就可以手动指定这个软件的代理为 `7891` 端口
而且这样可以配合浏览器插件 `Proxy SwitchyOmega` 使用，需要代理的网站就用 SwitchyOmega 指定到 `7891` 端口代理，
因为浏览器插件添加需要代理的网站更加方便。

或者有其他能实现这种需求的方式吗？

我现在只能通过启用两个代理软件来实现这个

**Comment by BirkhoffLee** [comment]
> 而且这样可以配合浏览器插件 Proxy SwitchyOmega 使用，需要代理的网站就用 SwitchyOmega 指定到 7891 端口代理，

Clash 已经有提供这些功能

>  可以根据监听的端口进行分流代理吗

不能，之前已经讨论过

**Comment by Jeffrey-deng** [comment]
> > A rule-based tunnel in Go.
> 
> 使用 `PROCESS-NAME` 规则，放弃 `Proxy SwitchyOmega`

软件多用户配置的，例如浏览器，进程名识别不了
而且clash安装在路由器中的话，也获取不了进程名

**Comment by BirkhoffLee** [comment]
有需求的话开两个 clash 也行问题不大
