### ISSUE TITLE
[Feature] How to do whitelist-mode proxy?

### ISSUE THREAD

**Issue by icefery** [Dreamacro/clash#2682]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

How to do whitelist-mode proxy?

I want to do docker image pull proxy, but `no_proxy` environment variable on Linux or `bypass` configuration on Clash-for-Windows works as blacklist-mode.

So there are 3 necessary steps as follow:

1. Config systemd daemon proxy, reload systemd daemon, restart docker

   ```shell
   tee /etc/systemd/system/docker.service.d/proxy.conf <<- 'EOF'
   [Service]
   Environment="HTTP_PROXY=http://127.0.0.1:7890"
   Environment="HTTPS_PROXY=http://127.0.0.1:7890"
   EOF
   systemctl daemon-reload
   systemctl restart docker
   ```

2. Run `docker pull`

   ```shell
   systemctl daemon-reload
   systemctl restart docker
   docker pull registry.k8s.io/pause
   ```

3. Remove systemd daemon proxy, reload systemd daemon, restart docker

   ```shell
   :> /etc/systemd/system/docker.service.d/proxy.conf
   systemctl daemon-reload
   systemctl restart docker
   ```

Is there a way to config Clash like this, so Clash will skip proxy unless hosts are in whitelist?

```yaml
whitelist:
  - registry.k8s.io
  - ghcr.io
```

**Comment by BirkhoffLee** [comment]
```yaml
rules:
  - DOMAIN,registry.k8s.io,DIRECT
  - DOMAIN,ghcr.io,DIRECT
```
