### ISSUE TITLE
是否兼容任意TCP数据包？

### ISSUE THREAD

**Issue by oilel** [Dreamacro/clash#2683]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

http和https也采用TCP，但是TCP协议能实现的肯定不止http和https。能否转发任意TCP数据包？比如自己随便写一点内容，以TCP形式发出去。

**Comment by Dreamacro** [comment]
支持 layer4 (TCP/UDP) 的代理
