### ISSUE TITLE
VSCODE 使用arduino插件下载M5STACK开发板库的时候代理不生效，换成SSR后代理成功，请问这种情况是正常的吗？

### ISSUE THREAD

**Issue by SJJ-dot** [Dreamacro/clash#2686]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

VSCODE 使用arduino插件下载M5STACK开发板库的时候代理不生效，换成SSR后代理成功，请问这种情况是正常的吗？

**Comment by QS0x01** [comment]
log 呢？log 呢？log 呢？
没接管到连接？接管到连接但是直连了？代理了但是连接被掐了？
没有 log 不如问问神奇的小海螺。

**Comment by SJJ-dot** [comment]
> log 呢？log 呢？log 呢？ 没接管到连接？接管到连接但是直连了？代理了但是连接被掐了？ 没有 log 不如问问神奇的小海螺。

我看连接里面没有对应的链接， @QS0x01

**Comment by QS0x01** [comment]
那可能是不遵循系统代理，开 tun 劫持可解。

**Comment by SJJ-dot** [comment]
PAC模式可以HTTP模式不行是为啥呢
