### ISSUE TITLE
[Feature] wireguard协议是否可以随机IP

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#2689]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前wireguard协议需要配置ip字段，这导致一套config不能共享给其他人使用。是否可以支持随机ip呢？

### Possible Solution

比如默认配置只需要配置网段192.168.1.0/24，clash初始化的时候占用192.168.1.254，然后随机ping 192.168.1.0/24段一个地址，如果ping不通，则当作可用，占用这个地址

**Comment by BirkhoffLee** [comment]
Wireguard 的 peer 本来就是一对一
有这需求就弄个 cron 搭配 clash api 自己调整吧
