### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by wangxin6** [Dreamacro/clash#269]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12aa4]

goroutine 19296 [running]:
strings.IndexByte(...)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/strings/strings.go:151
strings.Index(0x0, 0x14, 0x478ce9, 0x1, 0x4000928b18)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/strings/strings.go:953 +0x520
strings.Contains(...)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/strings/strings.go:99
github.com/miekg/dns.domainNameLen(0x0, 0x14, 0xc, 0x0, 0x4000928b01, 0x4000718640)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/msg.go:1020 +0x74
github.com/miekg/dns.(*Question).len(...)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/types.go:219
github.com/miekg/dns.msgLenWithCompressionMap(0x40001261b0, 0x0, 0x4000249590)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/msg.go:994 +0x230
github.com/miekg/dns.(*Msg).packBufferWithCompressionMap(0x40001261b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4000928d00, 0x4000129500, 0x4000928d00, 0x8, ...)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/msg.go:820 +0x14c
github.com/miekg/dns.(*Msg).PackBuffer(0x40001261b0, 0x0, 0x0, 0x0, 0x0, 0x4000418380, 0x1b, 0x4000418280, 0x4000928d98)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/msg.go:766 +0x68
github.com/miekg/dns.(*Msg).Pack(...)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/msg.go:754
github.com/miekg/dns.(*response).WriteMsg(0x40003ec960, 0x40001261b0, 0x1, 0x40001ecea0)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:665 +0x48
github.com/Dreamacro/clash/dns.withResolver.func1(0x528900, 0x40003ec960, 0x4000265170)
	/home/travis/gopath/src/github.com/alliswell2day/clash/dns/middleware.go:47 +0x260
github.com/Dreamacro/clash/dns.(*Server).ServeDNS(0x400021a560, 0x528900, 0x40003ec960, 0x4000265170)
	/home/travis/gopath/src/github.com/alliswell2day/clash/dns/server.go:27 +0x70
github.com/miekg/dns.(*Server).serveDNS(0x400040a100, 0x40005de400, 0x25, 0x200, 0x40003ec960)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:603 +0x248
github.com/miekg/dns.(*Server).serveUDPPacket(0x400040a100, 0x400021e1e4, 0x40005de400, 0x25, 0x200, 0x40001400e8, 0x400048ce40)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:549 +0xa8
created by github.com/miekg/dns.(*Server).serveUDP
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:479 +0x1f4

以上错误发生在
Model：Raspberry Pi 3 Model B Rev 1.2，
Firmware Version：OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.218.48077-4468345)， 
Kernel Version	4.9.184
clash：0.15.1-dev, 
luci：frainzy1477/luci-app-clash，0.330

**Comment by Dreamacro** [comment]
看起来像是 dns 库抛出的错，有办法能稳定复现吗

**Comment by wangxin6** [comment]
偶然发现的。无法复现

**Comment by Dreamacro** [comment]
如果还出现再打开这个 issue
