### ISSUE TITLE
[Feature] 我的路由器是华硕RT-AX68U，需要下载armv8,但是没有，armv7可以用吗

### ISSUE THREAD

**Issue by kissmymouth** [Dreamacro/clash#2691]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我的路由器是华硕RT-AX68U，需要下载armv8,但是没有，armv7可以用吗

**Comment by Dreamacro** [comment]
arm64 就行
