### ISSUE TITLE
[Bug] 外网无法访问 Clash SOCKS proxy

### ISSUE THREAD

**Issue by bhj8** [Dreamacro/clash#2694]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

我想通过公网，访问clash的代理。类似在内网访问那样。（clash开启LAN模式）
我确信我设置的没错的，内网的其它端口能够成功映射到公网，我能拨通。我在局域网也能成功访问clash。（clash开启LAN模式）
但是我无论如何都没办法在公网上，访问clash。（我端口映射绝对没错）
这是哪里的问题？clash是否拥有这种功能，或者可能性？

想要这个功能的理由很简单，因为我家中的宽带是电信的，有公网IP。代理情况非常稳定。当我出差时，会遇到各种各样的网络，可以稳定连接我家，但无法稳定连接代理。（因为电信有GIA，懂得都懂）这时候，我能通过家里的电脑的clash访问代理。那么就会变得非常可靠

**Comment by QS0x01** [comment]
你这怎么比机器翻译还机器

**Comment by bhj8** [comment]
> 你这怎么比机器翻译机器味还重。
> 
> 不建议映射公网，公网会有人扫描端口，clash 的认证并不方便。

嘻嘻，可能是我GPT4用多了。clash认证可以用帐号和密码，我配置文件里设置一个贼复杂的，感觉安全性还可以。
那有没有其他办法解决这个问题呢，提点几个关键词。（我已经查了很多资料。。。叹气）

**Comment by AprilGrimoire** [comment]
可以考虑套一层ssh?

**Comment by BirkhoffLee** [comment]
> > 你这怎么比机器翻译机器味还重。
> > 不建议映射公网，公网会有人扫描端口，clash 的认证并不方便。
> 
> 嘻嘻，可能是我GPT4用多了。clash认证可以用帐号和密码，我配置文件里设置一个贼复杂的，感觉安全性还可以。 那有没有其他办法解决这个问题呢，提点几个关键词。（我已经查了很多资料。。。叹气）

VPN 回内网，例如 wireguard，openvpn 都行

**Comment by bhj8** [comment]
我升级clash到最新版本后，再次尝试了该设置。现在完全正常。
谢谢大家。

**Comment by bhj8** [comment]
额，但是我不敢这么用。因为公网到clash的流量是不加密的。（好像只有http和socks5）虽然稳定，但是我不敢用。

**Comment by Apolsus** [comment]
但是现在还是有很诡异的事情发生。在服务器上执行 curl -x hostip:7890 https://www.whatismyip.com ，一切正常，但是在客户端执行这个命令，就完全不行。这不是由于防火墙问题引起的，curl -x hostip:7890 https://www.google.com 就可以在客户端正常执行。服务器上 clash 也会给出转发日志。curl -v 结果显示 TLS 握手第二阶段，目标网站关闭了连接。最后，openai 和 wahtismyip.com 都是这样的，上不去

**Comment by bhj8** [comment]
> 但是现在还是有很诡异的事情发生。在服务器上执行 curl -x hostip:7890 https://www.whatismyip.com ，一切正常，但是在客户端执行这个命令，就完全不行。这不是由于防火墙问题引起的，curl -x hostip:7890 https://www.google.com 就可以在客户端正常执行。服务器上 clash 也会给出转发日志。curl -v 结果显示 TLS 握手第二阶段，目标网站关闭了连接。最后，openai 和 wahtismyip.com 都是这样的，上不去

据我所知，因为clash技术限制，LAN模式，好像只支持HTTP协议。
