### ISSUE TITLE
[Question] TUN模式ssh git@github.com报错kex_exchange_identification Connection closed by remote host

### ISSUE THREAD

**Issue by javenwang** [Dreamacro/clash#2695]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.04.13 Premium

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 127.0.0.1
  fallback:
    - 127.0.0.1
  fake-ip-filter:
    - +.*
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

### Clash log

```shell
[2023-04-23 16:04:36][DEBUG] [TCP] accept connection lAddr=198.18.0.1:56794 rAddr=github.com:22 inbound=TUN
[2023-04-23 16:04:36][DEBUG] [Matcher] resolve success host=github.com ip=20.205.243.166
[2023-04-23 16:04:37][INFO] [TCP] connected lAddr=198.18.0.1:56794 rAddr=github.com:22 mode=rule rule=DomainKeyword(github) proxy=🪜梯子
[2023-04-23 16:04:38][DEBUG] [TCP] accept connection lAddr=198.18.0.1:56796 rAddr=101.227.132.78:80 inbound=TUN
[2023-04-23 16:04:38][INFO] [TCP] connected lAddr=198.18.0.1:56796 rAddr=101.227.132.78:80 mode=rule rule=GeoIP(CN) proxy=DIRECT
[2023-04-23 16:04:39][DEBUG] [TUN] hijack udp dns addr=8.8.8.8:53
[2023-04-23 16:04:39][DEBUG] [TUN] hijack udp dns addr=8.8.8.8:53
```

### Description

开启了TUN之后，ssh github.com报错：
```
 ssh -v git@github.com
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/javenwang/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to github.com port 22.
debug1: Connection established.
debug1: identity file /Users/javenwang/.ssh/id_rsa type 0
debug1: identity file /Users/javenwang/.ssh/id_rsa-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ed25519 type 3
debug1: identity file /Users/javenwang/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/javenwang/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_xmss type -1
debug1: identity file /Users/javenwang/.ssh/id_xmss-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_dsa type -1
debug1: identity file /Users/javenwang/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
```
但用ssh.github.com:443则没问题：
```
 ssh -p 443 git@ssh.github.com
PTY allocation request failed on channel 0
Hi javenwang! You've successfully authenticated, but GitHub does not provide shell access.
Connection to ssh.github.com closed.
```

**Comment by Dreamacro** [comment]
无法复现，换个节点试试？

**Comment by javenwang** [comment]
已经换了节点，也换了网络环境，必现，但换了gitlab试却没问题：
```
 ssh git@gitlab.com
PTY allocation request failed on channel 0
Welcome to GitLab, @javenwang!
Connection to gitlab.com closed.
```
也就是说只有在开启TUN模式，且ssh github.com（用默认22端口）时才能重现，其他站点暂时没发现问题

**Comment by Dreamacro** [comment]
fake-ip-filter 使用这种绕过方式产生的问题自己解决

**Comment by javenwang** [comment]
应该与fake-ip-filter的方式无关，把fake-ip-filter清空后使用fake-ip也依然报同样的错误（可以看到github.com解析为198.18.0.24）：
```
 ~  dig github.com           

; <<>> DiG 9.10.6 <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19974
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0001, udp: 4096
;; QUESTION SECTION:
;github.com.			IN	A

;; ANSWER SECTION:
github.com.		1	IN	A	198.18.0.24

;; Query time: 49 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Apr 24 15:17:01 CST 2023
;; MSG SIZE  rcvd: 65

 ~  ssh -v git@github.com
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/javenwang/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to github.com port 22.
debug1: Connection established.
debug1: identity file /Users/javenwang/.ssh/id_rsa type 0
debug1: identity file /Users/javenwang/.ssh/id_rsa-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/javenwang/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ed25519 type 3
debug1: identity file /Users/javenwang/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/javenwang/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_xmss type -1
debug1: identity file /Users/javenwang/.ssh/id_xmss-cert type -1
debug1: identity file /Users/javenwang/.ssh/id_dsa type -1
debug1: identity file /Users/javenwang/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
kex_exchange_identification: Connection closed by remote host
Connection closed by 198.18.0.24 port 22
 ✘  ~  
```

**Comment by Dreamacro** [comment]
确实可能不是因为这个的问题，但是使用这个方式可能造成奇怪的问题，为了避免最终查原因查到是它造成的而浪费的大量时间，所以拒绝回答这类配置产生的问题。

你用的啥代理，正确匹配了规则么

**Comment by xue-lei** [comment]
也可能是线路限制了22端口

**Comment by javenwang** [comment]
> 确实可能不是因为这个的问题，但是使用这个方式可能造成奇怪的问题，为了避免最终查原因查到是它造成的而浪费的大量时间，所以拒绝回答这类配置产生的问题。

能理解，所以我禁止了fake-ip-filter的+.*规则，再尝试也能重现。实际上一开始并没有这条规则，出现了这个问题，我怀疑是fake ip导致的，于是加上这条规则。

> 
> 你用的啥代理，正确匹配了规则么

我也是用了clash很长时间了，匹配规则什么的也比较熟悉，之前没有用TUN，只是命令行很麻烦，每次连github都要设置环境变量，所以才想尝试TUN

至于 @xue-lei 提到的：
> 也可能是线路限制了22端口

我换了网络环境（家、公司）都试过，报一样的错误。而且看ssh日志其实github的22端口可以连接，只是在握手协商阶段失败了

**Comment by Dreamacro** [comment]
> 我换了网络环境（家、公司）都试过，报一样的错误。而且看 ssh 日志其实 github 的 22 端口可以连接，只是在握手协商阶段失败了

和你自己的环境没关系，看日志是看不出能不能连接的，因为和 ssh 命令握手的是 clash。理论上就是你的梯子访问 github.com 22 端口有问题，你如果有 vps 可以自己搭一个 ss 试试

**Comment by javenwang** [comment]
> 和你自己的环境没关系，看日志是看不出能不能连接的，因为和 ssh 命令握手的是 clash。理论上就是你的梯子访问 github.com 22 端口有问题，你如果有 vps 可以自己搭一个 ss 试试

感觉至少连接已经建立了：
```
 ~  ssh -v git@github.com
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/javenwang/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to github.com port 22.
debug1: Connection established.
        ^^^^^^^^^^^^^^^^^^^^^^ 这里说明已经建立连接了，接下来是握手
```
如果说我的梯子访问github.com:22有问题，那之前不用TUN的时候、用socks5代理是正常的就不好解释了。我再尝试换别的梯子试试

**Comment by Dreamacro** [comment]
> 感觉至少连接已经建立了

这个还是连到 clash，这里是一定能连上的

**Comment by BirkhoffLee** [comment]
> > 和你自己的环境没关系，看日志是看不出能不能连接的，因为和 ssh 命令握手的是 clash。理论上就是你的梯子访问 github.com 22 端口有问题，你如果有 vps 可以自己搭一个 ss 试试
> 
> 感觉至少连接已经建立了：
> 
> ```
>  ~  ssh -v git@github.com
> OpenSSH_9.0p1, LibreSSL 3.3.6
> debug1: Reading configuration data /Users/javenwang/.ssh/config
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
> debug1: /etc/ssh/ssh_config line 54: Applying options for *
> debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
> debug1: Connecting to github.com port 22.
> debug1: Connection established.
>         ^^^^^^^^^^^^^^^^^^^^^^ 这里说明已经建立连接了，接下来是握手
> ```
> 
> 如果说我的梯子访问github.com:22有问题，那之前不用TUN的时候、用socks5代理是正常的就不好解释了。我再尝试换别的梯子试试

最快的方式就是 tcpdump 看一下连接具体数据包，这样子开一个 issue 无非盲人摸象

**Comment by woyin** [comment]
> > 我换了网络环境（家、公司）都试过，报一样的错误。而且看 ssh 日志其实 github 的 22 端口可以连接，只是在握手协商阶段失败了
> 
> 和你自己的环境没关系，看日志是看不出能不能连接的，因为和 ssh 命令握手的是 clash。理论上就是你的梯子访问 github.com 22 端口有问题，你如果有 vps 可以自己搭一个 ss 试试

我有类似的问题。
我已经自建了，无论是trojan还是vmess都有同样的问题。

**Comment by woyin** [comment]
@javenwang @Dreamacro 
 这里面我还遇到了一个更有趣的事情。
执行 `ssh git@github.com -p 2222`强制指定一个错误的端口，会得到同样的错误信息，即`kex_exchange_identification: Connection closed by remote host`

看起来是ssh 出去的时候，根本就没有到github.com 就断了，即根本就没有从clash出去。
<img width="687" alt="image" src="https://github.com/Dreamacro/clash/assets/35319250/969d2e73-87c0-4edc-9c5e-5ade936d5737">

**Comment by javenwang** [comment]
@woyin 我用这个方法解决，你可以参考一下：[Using SSH over the HTTPS port](https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port)

**Comment by woyin** [comment]
> @woyin 我用这个方法解决，你可以参考一下：[Using SSH over the HTTPS port](https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port)

我换成了shadowrocket 了，实在是折腾不动了。 @javenwang

**Comment by woyin** [comment]
@Dreamacro 再补充一个现象。
不打开enhanced-mode的时候，通过Wireshark可以抓到正常的sshv2的数据包，并且可以正常链接。
但一旦启用了enhanced-mode，通过Wireshark抓到任何sshv2的数据包，应该是clash接管了所有流量从而无法识别。

不了解后面的原理，无法进一步排查。如果需要tcpdump进行抓包的话，是否可以提供相关指令执行？
