### ISSUE TITLE
[Feature] clash for ios

### ISSUE THREAD

**Issue by navidx96** [Dreamacro/clash#2698]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

please release this app for ios user

**Comment by BirkhoffLee** [comment]
This is the Clash core project. We do not make or distribute platform-specific apps.
