### ISSUE TITLE
[Bug] auto-redir功能开启失败

### ISSUE THREAD

**Issue by gitthehit** [Dreamacro/clash#2699]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2023.4.16

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 1080
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
tun:
  enable: true
  stack: system
  auto-redir: true
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
```

### Clash log

```shell
14:23:16 INF [Config] initial compatible provider name=all_proxy
14:23:16 INF [DNS] server listening addr=[::]:53
14:23:16 INF [Inbound] Mixed(http+socks) listening addr=[::]:1080
14:23:16 INF [API] listening addr=[::]:9090
14:23:16 DBG [TUN] interface up iface=utun gateway=198.18.0.2
14:23:16 DBG [TUN] mtu updated iface=utun gateway=198.18.0.2
14:23:16 DBG [TUN] interface up iface=utun gateway=198.18.0.2
14:23:16 DBG [TUN] mtu updated iface=utun gateway=198.18.0.2
14:23:16 WRN [TUN] auto redir start failed error=apply nftables: conn.Receive: netlink receive: no such file or directory
14:23:16 DBG [TUN] interface up iface=utun gateway=198.18.0.1
14:23:16 DBG [TUN] mtu updated iface=utun gateway=198.18.0.1
14:23:16 DBG [TUN] interface up iface=utun gateway=198.18.0.1
14:23:16 DBG [TUN] mtu updated iface=utun gateway=198.18.0.1
14:23:16 INF [Inbound] TUN listening iface=utun gateway=198.18.0.1
```

### Description

使用tun模式的auto-redir失效，开启以后日志报warning。

**Comment by Dreamacro** [comment]
需要内核支持

**Comment by gitthehit** [comment]
请问如何查看内核是否支持呢？或者怎样开启内核支持？

**Comment by Dreamacro** [comment]
依赖 netlink

**Comment by gitthehit** [comment]
我使用的树莓派4b的raspberry pi os，应该是支持netlink的吧

**Comment by gitthehit** [comment]
重启解决
