### ISSUE TITLE
[Bug] Firefox插件SmartProxy与ShadowSocks节点时出现的问题

### ISSUE THREAD

**Issue by IcyCathedral** [Dreamacro/clash#2702]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

55725

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
not needed
```

### Clash log

```shell
not needed
```

### Description

这是一个与浏览器有关的小问题，或者说也不算小问题，是最近才发现的。
浏览器为firefox（普通版或开发者版），clash代理模式为全局模式，匹配网址规则全是SmartProxy设置的；
使用插件smartProxy智能判断转发Clash，当选用节点协议为ShadowSocks协议的节点时，访问会出现：
==============
建立安全连接失败

连接到 www.google.com 时发生错误。PR_END_OF_FILE_ERROR

错误代码：PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

详细了解…
==============
但是，使用Vmess节点则正常；

**然而下面情况却可正常访问**

1.SmartProxy改用系统代理，然后Clash开启“系统代理”；
2.同样使用SmartProxy的Edge浏览器，用法和出现BUG的firefox一样
3.Firefox中的同类插件Proxy SwitchOmega，用法和出现BUG的firefox几乎一样

因为SwitchOmega感觉不够好用，所以我坚持用SmartProxy，试着提一下这个也不知道问题出在Clash还是插件的BUG上吧。
以前酸酸乳等也不会出现这个问题，但那是很久以前的事了

**Comment by BirkhoffLee** [comment]
听起来跟 clash 本身没啥关系，是你使用的 smartproxy 插件 bug，建议你去那边 report issue
