### ISSUE TITLE
[Feature] Provide the compiled version of armv7l architecture CPU

### ISSUE THREAD

**Issue by XYUU** [Dreamacro/clash#2704]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Can you add the compiled version of the armv7l architecture CPU? At present, some routers and optical modem devices use the armv7l architecture instructions.

**Comment by Dreamacro** [comment]
have you try `linux-armv7`?

**Comment by XYUU** [comment]
> have you try `linux-armv7`?
I tried the armv7 version, and it suggested an illegal instruction. The difference between the armv7 and armv7l architectures is the little endian of the data.

**Comment by Dreamacro** [comment]
Go does not provide armv7l, so just use armv5.
