### ISSUE TITLE
WeChat视频出现断流

### ISSUE THREAD

**Issue by Mr-Sheep** [Dreamacro/clash#271]
我的Clash是部署在RPi 4上的，作为本地的透明代理，需要代理的客户端用ROS mangle mark。
但是在播放微信视频时会出现卡顿（家里人拿微信视频是否流畅作为wifi好坏的评判标准，很无奈）

日志发现WeChat的请求是发向了203.205.0.0/16，该ip段部分服务器位于HK，导致Geoip的判断失效
添加了如下规则，但是问题仍然存在
IP-CIDR,203.205.0.0/16,DIRECT

**Comment by Dreamacro** [comment]
如果是直连也会卡顿，等待 #265 完成🌚

**Comment by Dreamacro** [comment]
maybe fixed in latest dev

**Comment by xdaniel9** [comment]
v0.17.1还是出现断流，direct也没用
