### ISSUE TITLE
[Feature] 能否根据http response的 code 禁止某些节点，比如403，那就废弃这个节点了。

### ISSUE THREAD

**Issue by lmmir** [Dreamacro/clash#2712]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 

### 描述

load-balance ，负载均衡的时候 有些网站会把ip屏蔽了，也就是这个节点对我来说用不了，能否自动过滤掉这个节点，下次不用了。

**Comment by Akariln** [comment]
你可以试试更改 load-balance 连接测试用的 url 。
