### ISSUE TITLE
[Feature] <希望早日能支持vless协议>

### ISSUE THREAD

**Issue by hubumulity** [Dreamacro/clash#2718]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 

### 描述

现在vless协议基本已经成为主流协议，但是遗憾的是clash并不支持。

**Comment by BirkhoffLee** [comment]
duplicate

**Comment by f2sky** [comment]
通过关键词我查看了好几个有关「支持VLESS」的提议，结果就是提议被关闭，且上锁。不允许继续讨论下去。

我觉得这不是一个技术问题，而是开发者的个人恩怨问题，就是 Clash 的核心开发者看 VLESS 的开发者不顺眼，就是不愿意支持。原因很简单，Clash （非分支项目）目前支持的协议要么过于陈旧，要么早已被防火墙攻破，要么需要配置第三方插件来补足，使用体验早已大不如前。

目前的 VLESS XTLS Vision 经过很长时间的沉淀，在当前是非常不错的选择。GFW 是不断升级的，翻墙协议也必须快速升级换代，抱残守缺不是一个正确的态度，至少在对待 GFW 的对抗这件事情上。虽然当前 VLESS XTLS Vision 好用，但不保证过段时候不被 GFW 攻破，这就需要协议、工具一起合作。

我认为 Clash 不会支持 VLESS 协议，这是**核心开发者的个人主观好恶，而非客观技术选择**。

这个 Clash.Meta 分支项目已经支持 VLESS 了，想用的直接去这里：[Clash.Meta](https://github.com/MetaCubeX/Clash.Meta)

**Comment by qyj19920704** [comment]
duplicate

**Comment by aiening** [comment]
duplicate

**Comment by Xicrosoft** [comment]
duplicate!

**Comment by Rainsheep** [comment]
duplicate!

**Comment by lostmaniac** [comment]
duplicate!
