### ISSUE TITLE
[Feature] 自己写了一个节点测速并自动删除的工具但是效率还是很低很低

### ISSUE THREAD

**Issue by Mronezc** [Dreamacro/clash#2722]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 

### 描述

闲来没事干写个筛选并删除失效节点工具玩玩节点池，从核心上放弃了v2ray/xray,因为不支持ssr(有时候ssr节点还蛮不错的),sing-box看起来也不错但是文档偏少，最终选择了clash,但是我测试效果时还算满意，不过节点池有的节点众多跑下来很久很久很久下载10mb文件取平均值，有没有办法可以多线程，或者多配置文件加载(如果可以的话大佬们给个思路什么的)自己太菜了，写出来效率太慢了跟没写一样

**Comment by techblack** [comment]
对于节点池测速，同步测试多节点，对速度影响比较大（会互相抢占带宽），除非你口子非常大
1 .可以把下载文件缩小到5M?
2. 先测连通性，和tcping，少于xxx的就直接丢掉
3. https://github.com/faceair/clash-speedtest

**Comment by Mronezc** [comment]
> 对于节点池测速，同步测试多节点，对速度影响比较大（会互相抢占带宽），除非你口子非常大 1 .可以把下载文件缩小到5M? 2. 先测连通性，和tcping，少于xxx的就直接丢掉 3. https://github.com/faceair/clash-speedtest

感谢，这样也算是一个可行的办法，测试每个节点的url test就能知道多少能用了
