### ISSUE TITLE
[Bug] <Wiki 中clash as a Service在Linux中重启后无法正常工作>

### ISSUE THREAD

**Issue by science2468** [Dreamacro/clash#2725]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

1.15.1

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
mixed-port: 1080
allow-lan: true
bind-address: '192.168.0.106'
mode: global

[max@bogon ~]$ cat /etc/systemd/system/clash.service
[Unit]
Description=Clash daemon, A rule-based proxy in Go.
After=network.target

[Service]
ExecStart=/usr/local/bin/clash -d /home/max/.config/clash/ # Wiki中service的配置和改过后的效果相同，都是重启后无法正常工作，需要再次执行“sudo systemctl restart clash.service
Restart=always

[Install]
WantedBy=multi-user.target
```

### 日志输出

```Text
5月 10 19:10:12 localhost systemd[1]: Started Clash daemon, A rule-based proxy in Go..
5月 10 19:10:12 localhost.localdomain clash[1005]: time="2023-05-10T19:10:12-04:00" level=error msg="Start Mixed(http+socks) server error: listen tcp 192.168.0.106:1080: bind: cannot assign requested address"
```

### 问题描述

rocky Linux9.1环境，clash 作为systemd服务，电脑重启后显示无法绑定这个地址（192.168.0.106-也就是本机内网IP），测试后发现，执行`sudo systemctl restart clash.service`后可以正常使用。

### 复现步骤

rockyLinux9.1
sudo vim /etc/systemd/system/clash.service
`[Unit]
Description=Clash daemon, A rule-based proxy in Go.
After=network.target

[Service]
ExecStart=/usr/local/bin/clash -d /home/max/.config/clash/
Restart=always

[Install]
WantedBy=multi-user.target`
sudo systemctl daemon-reload
sudo systemctl start clash.service
sudo systemctl enable clash.service
sudo reboot
#重启后，start 后无法【tab】补全，只能执行sudo systemctl restart clash.service
[max@bogon ~]$ sudo systemctl restart clash.service
[max@bogon ~]$ sudo systemctl status clash.service
● clash.service - Clash daemon, A rule-based proxy in Go.
     Loaded: loaded (/etc/systemd/system/clash.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2023-05-10 19:29:55 EDT; 3s ago
   Main PID: 2751 (clash)
      Tasks: 8 (limit: 47864)
     Memory: 4.6M
        CPU: 9ms
     CGroup: /system.slice/clash.service
             └─2751 /usr/local/bin/clash -d /home/max/.config/clash/

5月 10 19:29:55 bogon systemd[1]: Started Clash daemon, A rule-based proxy in Go..
5月 10 19:29:55 bogon clash[2751]: time="2023-05-10T19:29:55-04:00" level=info msg="Mixed(http+socks) proxy listening at: 192.168.0.106:1080"

**Comment by BirkhoffLee** [comment]
试下 `After=network-online.target`

**Comment by science2468** [comment]
> 试下 `After=network-online.target`

### **谢谢！问题解决了。**

### 贴出来给相同或类似问题一个思路！
rocky Linux9.1下我的完整service配置
`[Unit]
Description=Clash daemon, A rule-based proxy in Go.
After=network-online.target

[Service]
ExecStart=/usr/local/bin/clash -d /home/max/.config/clash/
Restart=always

[Install]
WantedBy=multi-user.target`
#重启后日志如下
[max@localhost ~]$ sudo reboot
[sudo] max 的密码：
Connection to 192.168.0.106 closed by remote host.
Connection to 192.168.0.106 closed.

C:\Users\max>ssh max@192.168.0.106
max@192.168.0.106's password:
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Thu May 11 02:35:57 2023
[max@bogon ~]$ sudo systemctl status clash.service
[sudo] max 的密码：
● clash.service - Clash daemon, A rule-based proxy in Go.
     Loaded: loaded (/etc/systemd/system/clash.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2023-05-11 02:35:56 EDT; 1min 45s ago
   Main PID: 1296 (clash)
      Tasks: 8 (limit: 47864)
     Memory: 11.1M
        CPU: 40ms
     CGroup: /system.slice/clash.service
             └─1296 /usr/local/bin/clash -d /home/max/.config/clash/

5月 11 02:35:56 bogon systemd[1]: Started Clash daemon, A rule-based proxy in Go..
5月 11 02:35:56 bogon clash[1296]: time="2023-05-11T02:35:56-04:00" level=info msg="Mixed(http+socks) proxy listening at: 192.168.0.106:1080"
