### ISSUE TITLE
[Feature] Shadowsocks Reduced IV Head Entropy

### ISSUE THREAD

**Issue by BirkhoffLee** [Dreamacro/clash#2729]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 

### 描述

根据 [gfw.report](https://gfw.report/publications/usenixsecurity23/zh/#8-1-%E5%8F%AF%E5%AE%9A%E5%88%B6%E7%9A%84%E6%9C%89%E6%95%88%E8%BD%BD%E8%8D%B7%E5%89%8D%E7%BC%80) 的实验显示：

> [算法1](https://gfw.report/publications/usenixsecurity23/zh/#alg:blocking)中的豁免规则Ex2和Ex5只查看连接中的前几个字节。这样做能让GFW高效地豁免不是完全加密的流量；但这样的做法同时也使其可以被用来规避检测。具体来说，我们建议在（翻墙）连接的第一个数据包的有效载荷上预置一个可定制的前缀。
> 
> 可定制的IV头。 Shadowsocks连接以初始化向量（IV）开始，根据加密方式的不同，其长度为16或32字节 [[22](https://gfw.report/publications/usenixsecurity23/zh/#Xshadowsocks)]。正如[第4.2节](https://gfw.report/publications/usenixsecurity23/zh/#sec:ascii-exemption)所介绍的，将IV的前6个（或更多）字节变成可打印的ASCII，将使这些连接被Ex2规则豁免。同样，将IV的前3、4或5个字节变成普通协议头，将使连接被Ex5规则豁免（例如，将IV的前3个字节变成0x16 0x03 0x03）。这些对策只需对客户端进行很小的改动，而对服务器没有任何改动，因此已经被许多流行的翻墙工具所采用 [[72](https://gfw.report/publications/usenixsecurity23/zh/#Xshadowsocks-rust-salt),[62](https://gfw.report/publications/usenixsecurity23/zh/#Xv2ray-salt),[48](https://gfw.report/publications/usenixsecurity23/zh/#Xsagernet-salt),[56](https://gfw.report/publications/usenixsecurity23/zh/#Xoutline-salt)]。将32字节IV的前几个字节限制为可打印的ASCII，不会将其随机性降低到影响加密安全性的程度。例如，即使将前6个字节固定为某个可打印的ASCII，IV中仍然有26个随机字节，这仍然比典型的16字节IV的随机性要大。

以下仓库已经实现

- https://github.com/shadowsocks/shadowsocks-rust/commit/53aab484f8daba6f5cee6896b034af943cc3d406
- https://github.com/v2fly/v2ray-core/pull/1552
- https://github.com/SagerNet/v2ray-core/commit/27fad5daaa1c33ed1c928d6c447df983a88d14a3
- https://github.com/Jigsaw-Code/outline-client/pull/1454

**Comment by Dreamacro** [comment]
虽然这个报告发布时间挺新，但有些东西已经过时，似乎现在已经没有类似的策略了
