### ISSUE TITLE
能否提供对urltest策略组的节点重新选取的API

### ISSUE THREAD

**Issue by tslling** [Dreamacro/clash#273]
urltest策略组里选取节点的时机只由interval控制，不到测试时间点不会触发切换。如果之前被测速选中的节点在下一个测试时间点到来之前挂掉了，那它没有机会被替换掉。这样用户测速发现被选中的节点延迟很高，但是不能手动切换了。

希望提供一个对urltest策略组重新选取节点的API，可以让用户提前手动重选节点。

**Comment by cjjdaq** [comment]
是会遇到这种情况，如果interval设置的比较大，那么好尴尬。

**Comment by Dreamacro** [comment]
目前对节点测速就能做到
