### ISSUE TITLE
[Bug] 可以访问google网站,但无法访问YouTube官网

### ISSUE THREAD

**Issue by fuqiyang11** [Dreamacro/clash#2735]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://github.com/Dreamacro/clash/wiki/) **and was unable to solve the issue**
- [X] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash v1.15.1-10-g7f1b50f darwin amd64 with go1.20.4 2023年 5月12日 星期五 08时30分25秒 UTC

### Operating System

macOS (darwin)

### Architecture

amd64

### Configuration File

```YAML
#port: 64000
socks-port: 64000
#mixed-port: 64000

log-level: debug
allow-lan: true
bind-address: '*'
interface-name: en0

# RESTful web API listening address
#external-controller: 192.168.3.39:9090

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

proxies:
  - name: "socks"
    type: socks5
    server: xxxx
    port: 64222
    username: xxxx
    password: xxxx
    # tls: true
    # skip-cert-verify: true
    # udp: true

rules:
  - GEOIP,CN,DIRECT
  - MATCH,socks
```

### Log

```Text
WARN[0000] [CacheFile] can't open cache file: timeout   
INFO[0000] SOCKS proxy listening at: [::]:64000         
DEBU[0004] [DNS] www.google.com.hk --> 199.59.149.201   
DEBU[0004] [DNS] adservice.google.com.hk --> 69.162.134.178 
INFO[0005] [TCP] 127.0.0.1:50082 --> www.google.com.hk:443 match Match() using socks 
INFO[0005] [TCP] 127.0.0.1:50084 --> adservice.google.com.hk:443 match Match() using socks 
DEBU[0006] [DNS] adservice.google.com --> 220.181.174.38 
INFO[0006] [TCP] 127.0.0.1:50086 --> adservice.google.com:443 match GeoIP(CN) using DIRECT 
DEBU[0007] [DNS] googleads.g.doubleclick.net --> 220.181.174.230 
INFO[0007] [TCP] 127.0.0.1:50088 --> googleads.g.doubleclick.net:443 match GeoIP(CN) using DIRECT 
DEBU[0015] [DNS] play.google.com --> 142.251.42.238     
DEBU[0015] [DNS] www.youtube.com --> 172.217.160.110    
INFO[0015] [TCP] 127.0.0.1:50091 --> play.google.com:443 match Match() using socks 
INFO[0016] [TCP] 127.0.0.1:50093 --> www.youtube.com:443 match Match() using socks 
DEBU[0016] [DNS] www.youtube.com --> 172.217.160.110    
INFO[0016] [TCP] 127.0.0.1:50095 --> www.youtube.com:443 match Match() using socks 
DEBU[0016] [DNS] www.youtube.com --> 172.217.160.110    
INFO[0017] [TCP] 127.0.0.1:50097 --> www.youtube.com:443 match Match() using socks
```

### Description

can access www.google.com
can't access www.youtube.com

### Reproduction Steps

1.set socks5 for safari

2. access google.com and YouTube.com

**Comment by fuqiyang11** [comment]
在safari中设置了代理
![image](https://github.com/Dreamacro/clash/assets/18230345/92494647-b7d2-460d-84aa-6ed8df10ee3b)

**Comment by Dreamacro** [comment]
如果你仅仅是想使用 clash 的话，建议直接使用 ClashX Pro
