### ISSUE TITLE
[Bug] <问题标题>

### ISSUE THREAD

**Issue by rookie-lian** [Dreamacro/clash#2737]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

0.20.23

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
1
```

### 日志输出

```Text
1
```

### 问题描述

clash会偶然丢失配置文件。比如说我用了一会，就不能使用了，打开面板，点击proxies，发现所有分组都没有了，然后也不能更新订阅，过一会就会好

### 复现步骤

正常使用就好

**Comment by xaotag** [comment]
Windows直接用的内核启动？

**Comment by rookie-lian** [comment]
> > Windows直接用的内核启动？
> 
> 看看通用配置文件

明天发你谢谢了
