### ISSUE TITLE
这个yaml用缩进来表示结构好反人类啊，不注意就无法启动

### ISSUE THREAD

**Issue by cjjdaq** [Dreamacro/clash#274]
是否有想过使用其他的配置语言，像toml，hocon这种更加直观可读写的呢。yaml有时候少个空格多个空格，都启动报错，对新手真是不太友好。

**Comment by Dreamacro** [comment]
建议你先拿 toml 或者 hocon 写一遍 clash 现在所有的配置，如果你觉得比 yaml 可读性、可写性好你再重新打开这个 issue，并带上原因。
