### ISSUE TITLE
[Feature] 内建一个帮助诊断的 http server 

### ISSUE THREAD

**Issue by BirkhoffLee** [Dreamacro/clash#2745]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 

### 描述

经过长期维护 issue 后，为了更加容易的帮助诊断连接问题，我有一个 proposal

clash 内建一个 http server，在 router 里「监听」在如 http://diagnostics.clash 的位置上，最初期可以只 generate 一个 204 response，可以用来判断用户的 connectivity problem 出在哪里

例如有 user 说 tun 无法接管流量这类的抽象 issue，可以先让对方 curl 这个诊断的 url，确认这个环境下 clash 到底有没有收到这个包

**Comment by pfangzhi** [comment]
tracert 和  clash的连接状态以及非常清楚的告诉你数据走到哪里了，clash核心不应该来解决小白问题

**Comment by BirkhoffLee** [comment]
tracert 只显示 icmp 状态
