### ISSUE TITLE
[Feature] what is the difference between v3 and normal version?

### ISSUE THREAD

**Issue by SimZhou** [Dreamacro/clash#2749]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://github.com/Dreamacro/clash/wiki/)

### Description

Hi, I don't understand the difference between v3 version and normal version:
![image](https://github.com/Dreamacro/clash/assets/11748629/96f6a172-35f0-4d9f-aa5a-f23bc432d2bc)
which to choose?

and I cannot find it anywhere:
![image](https://github.com/Dreamacro/clash/assets/11748629/99946051-7312-4e64-890d-de4a89a8bf6e)

**Comment by BirkhoffLee** [comment]
duplicate of https://github.com/Dreamacro/clash/issues/2611

**Comment by BirkhoffLee** [comment]
https://github.com/Dreamacro/clash/pull/2752
