### ISSUE TITLE
crypto/rand: blocked for 60 seconds waiting to read random data from the kernel

### ISSUE THREAD

**Issue by wangxin6** [Dreamacro/clash#275]
日志中出现如下错误：

crypto/rand: blocked for 60 seconds waiting to read random data from the kernel

平台：OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.230.62073-cb54693)
内核：aarch64_cortex-a53
clash: 0.15.1-dev

**Comment by wangxin6** [comment]
在设备重启以后会出现此问题，解决方法就是停止calsh，再重新启动clash

**Comment by Dreamacro** [comment]
出现的时候是全部阻塞住了吗

**Comment by wangxin6** [comment]
是的。所有网站都无法访问，等60秒也没有用。

**Comment by wangxin6** [comment]
https://github.com/rancher/k3s/issues/347
https://github.com/rancher/k3s/pull/342
https://github.com/rancher/k3s/pull/226

找到其他类似的问题。目前我也是在Pi上面碰见的这个问题。

**Comment by wangxin6** [comment]
opkg install haveged.

重启以后问题解决。
