### ISSUE TITLE
[Bug] centos7 tun 模式 其他机器ping不通198.18.0.1

### ISSUE THREAD

**Issue by lixiaomeng8520** [Dreamacro/clash#2751]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [x] 我已经仔细阅读 [官方 Wiki](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.04.16 linux amd64 with go1.20.3 Sun Apr 16 13:20:30 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
interface-name: eth0
tun:
  enable: true
  stack: system
  auto-route: true
  dns-hijack:
    - any:53
```

### 问题描述

在centos7上使用clash Premium做透明网关，发现其他机器无法上网，经测试其他机器无法ping通198.18.0.1。
但是同样的配置在ubuntu22上做网关，其他机器却可以正常ping通。

前置：
1. centos7上已开启ip_forward，关闭selinux，关闭firewalld，iptables规则均为空，且默认ACCEPT。
2. 其他机器已设置网关IP和DNS IP。

抓包测试（centos7）：
1. eth0上可以抓到其他机器请求的icmp包，但是没有响应的包。
2. utun上无任何icmp包。

抓包测试（ubuntu22）：
eth0和utun均有正常数据包

**Comment by BirkhoffLee** [comment]
启用 tun.auto-redir

**Comment by BirkhoffLee** [comment]
https://dreamacro.github.io/clash/premium/tun-device.html#linux-macos-or-android

**Comment by lixiaomeng8520** [comment]
@BirkhoffLee 启用了，依然不行

配置
```yaml
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true
  dns-hijack:
    - any:53
```

日志
```
May 20 08:37:59 localhost.localdomain systemd[1]: Started Clash daemon, A rule-based proxy in Go..
-- Subject: Unit clash.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit clash.service has finished starting up.
-- 
-- The start-up result is done.
May 20 08:37:59 localhost.localdomain polkitd[504]: Unregistered Authentication Agent for unix-process:3343:12674873 (system bus name :1.146, object path /org/freedesktop/Pol
May 20 08:37:59 localhost.localdomain kernel: IPv6: ADDRCONF(NETDEV_UP): slave: link is not ready
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Config] initial compatible provider name=Domestic
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Config] initial compatible provider name=Others
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Config] initial compatible provider name=GlobalTV
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Config] initial compatible provider name=AsianTV
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Config] initial compatible provider name=Proxy
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [DNS] server listening addr=[::]:53
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Inbound] HTTP proxy listening addr=[::]:7890
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [API] listening addr=[::]:9090
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Inbound] SOCKS proxy listening addr=[::]:7891
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Inbound] Redirect proxy listening addr=[::]:7892
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 DBG [TUN] mtu updated iface=utun gateway=198.18.0.2
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 DBG [TUN] interface up iface=utun gateway=198.18.0.2
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 DBG [TUN] mtu updated iface=utun gateway=198.18.0.2
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 DBG [TUN] interface up iface=utun gateway=198.18.0.2
May 20 08:37:59 localhost.localdomain clash[3352]: 08:37:59 INF [Inbound] TUN listening iface=utun gateway=198.18.0.1
May 20 08:37:59 localhost.localdomain kernel: IPv6: ADDRCONF(NETDEV_CHANGE): slave: link becomes ready
```

**Comment by howge** [comment]
遇到同样的问题，透明网关可以劫持内网dns请求，并且返回一个fake ip段的ip，但是无法进行网络通信，甚至clash服务器也无法http访问被劫持的域名，可以ping通， 系统CentOS 7.9   内核3.10， clash 最新版本， 初步怀疑是系统内核版本太低来，换Ubuntu试试，待确认

**Comment by howge** [comment]
> 遇到同样的问题，透明网关可以劫持内网dns请求，并且返回一个fake ip段的ip，但是无法进行网络通信，甚至clash服务器也无法http访问被劫持的域名，可以ping通， 系统CentOS 7.9 内核3.10， clash 最新版本， 初步怀疑是系统内核版本太低来，换Ubuntu试试，待确认

我将系统换成Ubuntu 22 ，内核5.x ， clash-linux-amd64-2023.05.19.gz  ，it works !!!!   config.yaml 配置如下:
`
port: 7890
 socks-port: 7891
 redir-port: 7892
 tproxy-port: 7893
 allow-lan: true
 bind-address: "*"
 mode: Rule
 log-level: debug
 external-controller: 0.0.0.0:9090
 secret: ""
 #external-ui: /opt/clash-dashboard

dns:
   enable: true
   listen: 0.0.0.0:53
   enhanced-mode: fake-ip
   fake-ip-range: 198.18.0.1/16
   nameserver:
     - 119.29.29.29 # DNSpod DNS 17ms
     - 223.5.5.5 # 阿里 19ms
   fallback:
    - tls://8.8.8.8:853         # Google DNS over TLS 50ms
    - tls://8.8.4.4:853         # cloudflare DNS over TLS 50ms
    - https://1.1.1.1/dns-query # cloudflare DNS over HTTPS
    - https://dns.google/dns-query # Google DNS over HTTPS

   fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4


 tun:
   enable: true
   stack: system
   auto-route: true
   auto-detect-interface: true
   dns-hijack:
     - any:53
   auto-redir: true
`

**Comment by lixiaomeng8520** [comment]
@howge 主要是我用不惯ubuntu，平常还是以centos为主，所以想看看有没有解决办法

**Comment by howge** [comment]
> 

可以升级下内核试试

**Comment by SeasonLinCN** [comment]
centos 7.4同遇到此问题
