### ISSUE TITLE
[Feature] 无法使用不支持CONNECT方法的下级http代理

### ISSUE THREAD

**Issue by xinstein** [Dreamacro/clash#2764]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash v1.16.0 linux amd64 with go1.20.4

### Operating System

Linux

### Architecture

amd64

### Configuration File

```YAML
proxies:
  - name: myhttpproxy # which does not understand CONNECT method
    type: http
    server: xxx.xxx.xxx.xxx
    port: yyyyy
```

### Log

```Text
clashproxy_1  | time="2023-05-24T03:52:51Z" level=warning msg="[TCP] dial myhttpproxy (match DomainSuffix/XXXXXXXXXX) XXXXXXXXXXXX:XXXXXX --> XXXXXXXXXXXXX:YYYY error: can not connect remote err code: 400"
```

### Description

I used tcpdump to capture packets and observed the following:
1. When I use `http_proxy=myhttpproxyaddr:port curl http://xxxxxxx` it returns 200 normally, the http packet shows a GET request and a normal reply from the proxy server.
2. When I configure this into clash and use clash as proxy `http_proxy=myclashaddr:port curl http://xxxxxxx` it returns 400, the http packet shows a CONNECT request, and the proxy server replied with 400 `Your browser sent a request that this server could not understand.`

### Reproduction Steps

already described in Description

**Comment by Dreamacro** [comment]
This is not a bug, it is already comment that the http outbound proxy only requests the CONNECT method of proxy

**Comment by xinstein** [comment]
> This is not a bug, it is already comment that the http outbound proxy only requests the CONNECT method of proxy

Sorry, must have missed that comment. Changed the subject, would this be hard to implement? Do you think a new goer (me) could take a try?

**Comment by xinstein** [comment]
I found this file [adapter/outboubd/http.go](https://github.com/Dreamacro/clash/blob/master/adapter/outbound/http.go), do you think it would be enough to edit this file in order to add the choice to use GET instead of CONNECT?

I'm still a hello-worlder in go, but I have some experience of async programming in python. If you can give me a rough guide, I'm willing to try this task.

**Comment by Dreamacro** [comment]
Writing a working non-CONNECT http proxy is not difficult, the hard part is to implement each part correctly. Although the RFC specifies how each part should be done, there are so many of them, and there are other legacy clients, that it's a big problem to deal with compatibility issues

**Comment by Dreamacro** [comment]
clash's non-CONNECT http server has also gone through several versions and has encountered a lot of edge cases. 

If you want to try it, you are always welcome. If the go standard library contains similar code, you can refer to it. It would be nice if you could call the go standard library directly instead of copying it out.

**Comment by Dreamacro** [comment]
Also note that CONNECT is a TCP Layer 4 proxy that can proxy non-HTTP traffic, but a normal HTTP proxy does not. You also need to think about how to handle non-http traffic into these nodes.
