### ISSUE TITLE
[Bug] Upstream FreeBSD ports patch

### ISSUE THREAD

**Issue by yonas** [Dreamacro/clash#2766]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

current

### Operating System

OpenBSD / FreeBSD

### Architecture

amd64

### Configuration File

```YAML
N/A
```

### Log

```Text
N/A
```

### Description

Please commit this patch:

```
--- listener/redir/tcp_freebsd.go.orig	2023-05-24 08:01:04 UTC
+++ listener/redir/tcp_freebsd.go
@@ -46,7 +46,8 @@ func parserPacket(conn net.Conn) (socks5.Addr, error) 
 func getorigdst(fd uintptr) (netip.AddrPort, error) {
 	addr := unix.RawSockaddrInet4{}
 	size := uint32(unsafe.Sizeof(addr))
-	if err := socketcall(GETSOCKOPT, fd, syscall.IPPROTO_IP, SO_ORIGINAL_DST, uintptr(unsafe.Pointer(&addr)), uintptr(unsafe.Pointer(&size)), 0); err != nil {
+	 _, _, err := syscall.Syscall6(syscall.SYS_GETSOCKOPT, fd, syscall.IPPROTO_IP, SO_ORIGINAL_DST, uintptr(unsafe.Pointer(&addr)), uintptr(unsafe.Pointer(&size)), 0);
+	if err != 0 {
 		return netip.AddrPort{}, err
 	}
 	port := binary.BigEndian.Uint16((*(*[2]byte)(unsafe.Pointer(&addr.Port)))[:])
@@ -56,7 +57,8 @@ func getorigdst(fd uintptr) (netip.AddrPort, error) {
 func getorigdst6(fd uintptr) (netip.AddrPort, error) {
 	addr := unix.RawSockaddrInet6{}
 	size := uint32(unsafe.Sizeof(addr))
-	if err := socketcall(GETSOCKOPT, fd, syscall.IPPROTO_IPV6, IP6T_SO_ORIGINAL_DST, uintptr(unsafe.Pointer(&addr)), uintptr(unsafe.Pointer(&size)), 0); err != nil {
+	_, _, err := syscall.Syscall6(syscall.SYS_GETSOCKOPT, fd, syscall.IPPROTO_IPV6, IP6T_SO_ORIGINAL_DST, uintptr(unsafe.Pointer(&addr)), uintptr(unsafe.Pointer(&size)), 0);
+	if err != 0 {
 		return netip.AddrPort{}, err
 	}
 	port := binary.BigEndian.Uint16((*(*[2]byte)(unsafe.Pointer(&addr.Port)))[:])

```

### Reproduction Steps

N/A

**Comment by Dreamacro** [comment]
plz create a pr for this

**Comment by yonas** [comment]
@Dreamacro I've created https://github.com/Dreamacro/clash/pull/2768

**Comment by yonas** [comment]
#2768 committed. Closing.
