### ISSUE TITLE
[Feature] premium code open source

### ISSUE THREAD

**Issue by crtthas** [Dreamacro/clash#2770]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/)

### Description

Is the premium code open source? i can't get the latest version on tag premium.

**Comment by Dreamacro** [comment]
it's closed source
