### ISSUE TITLE
How to control traffic of the outbound

### ISSUE THREAD

**Issue by thinkluffy** [Dreamacro/clash#2777]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/)

### Description

I am using Clash for a while, and everything works well, thanks for your great work!

We have lots of devices in my network, and I use the rule to split the traffic between domestic and international. The domestic traffic goes directly, while the international traffic goes through a proxy. The domestic bandwidth is wide, but the international bandwidth is narrow, so I want to **set different speed limits for the domestic and international of each device.**

I have already made a tc(traffic control command in Linux) rule to limit the network speed of each device as the domestic limit. **What is the proper way to achieve that for international traffic** please?

**Comment by Dreamacro** [comment]
> We have lots of devices in my network

It sounds like you are using clash as a gateway for office network traffic (at least for overseas traffic). But I'm curious as to how many of these devices are.

> I have already made a tc(traffic control command in Linux) rule to limit the network speed of each device as the domestic limit.

It sounds like you are handling the traffic to clash or not on your own. clash is a four-layer proxy, so for a TCP connection that needs a proxy, you end up with two TCP connections, and you can't find their correspondence.

There are two ways to achieve what you need

1. use eBPF with clash connections API. But it requires clash to add a proxy-side connection local address. You can speed limit the connection with this information, but a proxy protocol with a UDP based complicates the situation.

2. Implement a built-in speed limit in clash. The simplest way in Go is the bucket token, which is a very effective solution

**Comment by thinkluffy** [comment]
Appreciate your quick reply!
Yes, I am using Clash as a gateway, there are about 200 devices connecting meantime.
I prefer method 2, but I am using the premium edition of Clash. Do I need to rebuild the Clash binary? Is it possible to use premium any longer?

**Comment by Dreamacro** [comment]
Unfortunately, premium version is not open source.

However, it would be interesting to add some metadata about the connection (e.g. speed limit, priority ipv6, etc.). But there is no clear idea of how to put it on config with a clear purpose.

There are several ideas:
```yaml
rules:
  - DOMAIN,foo.com,speed=100mbps
  - if: src_ip = "192.168.22.1"
    name: bar
    metadata:
       prefer-v6: true
       speed: 100mbps
    rules:
       - MATCH,DIRECT
  - MATCH,DIRECT,prefer-v6
```
