### ISSUE TITLE
Clash是否有类似Surge增强模式作为网关的功能？

### ISSUE THREAD

**Issue by cndanili** [Dreamacro/clash#278]
我的Clash是运行在Docker上的，MacOS X和iPhone都可以使用Socks和Http模式进行代理。
但是Apple TV没有办法设置代理，只能用修改网关和DNS的方式。
看到Surge有增强模式，可以达到网关效果，我看了issues好像是tun模式？
但是看了issue发现tun在Clash上并没有实现，所以他们通过iptables的方式进行redirect。
但是Docker上使用fake ip DNS进行iptables的redirect找不到教程，也不知道如何启动Clash增强模式中的网关功能，能否给盏明灯，教教我这样的小白。

**Comment by comzyh** [comment]
docker 如果使用桥接网络是不可能使用 主机的 iptables redirect 的

可以直接不用 docker 跑clash，或者让docker container 的网络工作在 host 模式下。

uncertainty principle <notifications@github.com> 于 2019年9月27日周五 14:30写道：

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/releases/tag/TUN 可以试试实验性的 TUN 二进制
