### ISSUE TITLE
[Feature] proxy-providers获得的节点如何启用skip-cert-verify: true选项

### ISSUE THREAD

**Issue by LzNOHentai** [Dreamacro/clash#2784]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

使用自定义配置文件，利用proxy-providers功能订阅链接获取到Trojan节点。
但似乎providers获取到的节点无法更改skip-cert-verify属性，导致TLS x509错误，无法连接节点。

如果直接使用官方订阅，查看配置文件可以看到官方的Trojan节点配置启用了skip-cert-verify: true
请问能否为providers获取到的节点添加相关功能？

**Comment by Dreamacro** [comment]
这应该时你配置提供的地方没写上对应的配置吧，与 clash 本身没关系。provider 里面的节点配置和普通节点配置支持的东西一致

**Comment by LzNOHentai** [comment]
> 这应该时你配置提供的地方没写上对应的配置吧，与 clash 本身没关系。provider 里面的节点配置和普通节点配置支持的东西一致

由于我用的机场订阅链接限制开的比较高，同时屏蔽了第三方订阅转换，所以我必须用他们官方的订阅转换转一手订阅填进providers的URL。
研究了一下，订阅转换面板进阶功能里有提供“跳过证书验证”选项，打开就行了，那没事了。

不过考虑到单独proxy功能可以配置skip-cert-verify，并且并非所有订阅转换都会在面板上开放scv选项。所以clash core给providers加个skip-cert-verify会不会更合理？

**Comment by Dreamacro** [comment]
不合理，`skip-cert-verify` 本身不建议打开，所以不能做成一个覆盖配置
