### ISSUE TITLE
[Feature] <有两种以上的过滤方式时，Fallback-filter的处理逻辑是怎样的>

### ISSUE THREAD

**Issue by fxchby** [Dreamacro/clash#2786]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

clash的fallback-filter有3种过滤方式：

- geoip
- ipcidr
- domain
当同时配置以下两种过滤方式时，比如下面的配置：
`fallback-filter:

    geoip: true

    geoip-code: CN

    ipcidr:

      - 240.0.0.0/4`
     
针对以下配置，对于DNS解析结果的处理逻辑，网上的说法是：

- 如果nameserver的解析结果为国内IP，就选用该IP地址作为最终的解析结果；
- 如果为国外IP，则选择fallback的解析结果

如果处理逻辑如上所述，上述ipcidr规则，不是永远不会进行匹配吗？
我不知道是不是我理解出错，能不能详细说一下当同时配置两种以上的过滤方式时，fallback-filter的处理逻辑？

**Comment by deuteros-gex** [comment]
https://dreamacro.github.io/clash/configuration/configuration-reference.html#configuration-reference
搜fallback关键词，写得挺清楚，读完不应该有啥疑问啊。

> 如果处理逻辑如上所述，上述ipcidr规则，不是永远不会进行匹配吗？

这个推论怎么来的？能详细解释一下吗？用文字，或者画个流程图都行，展示清楚自己的思路，这样才方便纠正。

**Comment by fxchby** [comment]
下方文字是关于fallback的配置和相关说明，摘自
https://dreamacro.github.io/clash/configuration/configuration-reference.html#configuration-reference
摘录：
# When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1
  #   - 'tcp://1.1.1.1#en0'

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  # fallback-filter:
  #   geoip: true
  #   geoip-code: CN
  #   ipcidr:
  #     - 240.0.0.0/4
  #   domain:
  #     - '+.google.com'
  #     - '+.facebook.com'
  #     - '+.youtube.com'

上述配置中，一共有设置了3种配置方式，分别是geoip-code、ipcidr和domain。
关于geoip的说明有两段：
 The answers from fallback servers are used when the GEOIP country  is not `CN`.
 IP address resolved with servers in `nameserver` is used when  `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
根据上述两段说明，我的理解是：当geoip设置为true时，对于'nameserver'中返回的解析IP：

- 如果该IP属于CN范围，则选用该解析IP作为最终的解析结果
- 如果该IP不属于CN工业园，则选择‘fallback'的解析IP作为最终的解析结果

也就是说，当geoip设置为ture时，通过该geoip就可以决定最终的解析结果。
这样一来，我就有这样的疑问：后面的ipcidr规则和domain，是不是就永远不会进行匹配了。
是不是只有当geoip设置为false时，才会尝试去匹配后面的ipcidr规则，来决定最终的解析结果？

**Comment by deuteros-gex** [comment]
三个判定条件之间，当然是“或”连接啊。
为啥就读不出这层意思呢，总不能让github上的大伙儿带你做reading comprehensive咯

要是不擅长咬文嚼字，也完全可以设计个简单实验来验证啊，clash for windows就有dns调试功能
<img width="449" alt="image" src="https://github.com/Dreamacro/clash/assets/67225583/b1fecafc-3702-42cd-8422-074fd8b7f622">

**Comment by MutoMagic** [comment]
根据注释，按我的理解，当geoip为true时ipcidr确实不会进行匹配，至于domain是否遵循我也不清楚，文档里并没有对此的描述。

**Comment by QeEn888** [comment]
geoip
可选值为 true/false

是否启用 fallback filter
