### ISSUE TITLE
Has IPv6 Redirect been Supported Now? IPv6的重定向是否已经支持？

### ISSUE THREAD

**Issue by yykhysn** [Dreamacro/clash#279]
Linux 的ip6tables tcp 重定向是否已经支持？

当把ipv6的TCP流量重定向给Clash时，客户端所有的IPv6 TCP 连接都是ERR_EMPTY_RESPONSE。

**Comment by comzyh** [comment]
目前还没有支持。
不过为什么要把 ipv6 的 TCP 流量重定向给 clash 呢?

**Comment by yykhysn** [comment]
> 目前还没有支持。
> 不过为什么要把 ipv6 的 TCP 流量重定向给 clash 呢?

 Linux盒子（路由器）上对IPv6的流量做透明代理，不然IPv6被墙的网站不能访问。 @comzyh

**Comment by yuguorui** [comment]
有很多网站已经被IPv6阻断，纯IPv4能上，在有IPv6的情况下反而上不了。

**Comment by yykhysn** [comment]
> 有很多网站已经被IPv6阻断，纯IPv4能上，在有IPv6的情况下反而上不了。

所以希望尽早加入IPv6重定向的支持（使IPv6流量能到达Clash）以及Clash代理的IPv6优选，进行ipv6的Url测试，只将IPv6远程地址代理给具有IPv6网络的服务器（ipv4地址的代理服务器，但接入了ipv6网络；或本身就是ipv6地址配置的代理服务器）

**Comment by yuguorui** [comment]
我提个了PR，请大大们审阅 https://github.com/Dreamacro/clash/pull/362

**Comment by cielpy** [comment]
请问目前的版本是否支持了呢
