### ISSUE TITLE
[Feature] Clash 考虑支持PCRE的filter吗？或者支持filterout属性用于过滤不想要的部分

### ISSUE THREAD

**Issue by puttin** [Dreamacro/clash#2794]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

前置有个Issue提出了包括PCRE和filterout的选项

https://github.com/Dreamacro/clash/issues/1950

### 可能的解决方案

same as https://github.com/Dreamacro/clash/issues/1950

* PCRE compatible regex engine instead of Golang internal one
* `filterout` to filter out

**Comment by puttin** [comment]
看着当前过滤的逻辑就是https://github.com/Dreamacro/clash/blob/4d66da2277ddaf41f83bd889b064c0a584f7a8ad/adapter/provider/provider.go#L289

也就是如果要支持filterout 需要增加一个参数解析，并且在https://github.com/Dreamacro/clash/blob/4d66da2277ddaf41f83bd889b064c0a584f7a8ad/adapter/outboundgroup/parser.go#L110
附近处理一下

**Comment by Dreamacro** [comment]
welcome to create a pr for #2673

**Comment by puttin** [comment]
> welcome to create a pr for #2673

filterout 还能整整，换个引擎对我这种没咋弄过golang的要求还是有点高😓

现在clash会有unit test之类的保障稳定性么…

**Comment by Dreamacro** [comment]
替换很简单，但两者并不互相兼容，测试也没用

**Comment by Dreamacro** [comment]
maybe #2802 fixed
