### ISSUE TITLE
[Feature] 在Docker容器内检测来源进程

### ISSUE THREAD

**Issue by 5G3U2UXp5nbfQ86Uqv** [Dreamacro/clash#2805]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

我想在docker里面运行clash（host是linux系统），使用的是官方的premium 映像，但是rule中的PROCESS-NAME 并不正常工作，检测不到连接的来源

### 可能的解决方案

阅读源码后，我可以理解不工作的理由：因为docker里面和host的/proc 不是同一个

我可以将host 的/proc mount 到docker里面，但不能mount到/proc，因为这样会把docker里面本来的覆盖掉，只能用另一个名字。

如果clash可以提供一个使用另外的路径替代 /proc 来检测进程的启动选项，等类似功能，那么这个功能应该就能正常工作了（对于host也是linux的情况）

**Comment by 5G3U2UXp5nbfQ86Uqv** [comment]
我已经本地实现了一个运行正常的，支持该功能的 branch，但是实现过程中发现dev版本的commit PR #2781 中似乎让 linux 中在 `netlink` 的通信的部分就报了 `netlink receive no such file or directory` 的错误（与docker无关，本地直接运行即报错）而无法识别进程。所以是基于master版本的更改。

所以实际上还发现了一个 dev 版本的bug？我是不是该新开一个issue

**Comment by Kr328** [comment]
现在查找进程分两步

1. 从内核 sock_diag 接口查找相应 socket 对应的 inode，这个行为受 net namespace 影响，只能查找到当前 namespace 内的。新的 dev 中的实现提供了四元组精确查找 socket，使得开销从 2ms 降低至 2us，但可能引起了你说的问题，你可以尝试在 sock_diag(7) 寻找解决方案。
2. 从 inode 查找对应的 pid，这个行为受 pid namespace 影响，只能查找到当前 pid namespace 的，当然 bind mount host 的 /proc 到 容器内也许是可行的。

**Comment by 5G3U2UXp5nbfQ86Uqv** [comment]
我的系统是群晖DSM7.2，测试后发现新的方式好像就是无法获得结果，才疏学浅搞不明白原因，感觉和群晖这系统有关。

实际上想在docker里面跑的动机就是每次更新之后系统文件都会重置，要重装clash，很麻烦

直接mount的话更改/proc目录之后，第二步是能正常进行的

**Comment by ImmortalD** [comment]
docker创建容器和和主机共享网络名称空间,进程名称空间就能看到了主机的进程了,docker里面的/proc和host就是一样了,不应该来挂载主机的/proc到docker: 

```bash
docker run -it --rm --pid=host --net=host ubuntu bash
```
