### ISSUE TITLE
[求教] 如何利用parsers给配置文件增加DNS地址？

### ISSUE THREAD

**Issue by Soizzer** [Dreamacro/clash#2808]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

如何利用parsers给配置文件增加DNS地址，比如增加配置文件DNS中 “default-nameserver”、“nameserver”、“fallback”部分的DNS地址。

看了“配置文件预处理”的帮助文件，添加规则、策略组、节点这些我都会了，可是“添加DNS地址”的没有看到类似说明。

求大佬帮助！

**Comment by Dreamacro** [comment]
clash binary 没有 parsers
