### ISSUE TITLE
[url-test] <自动删除长时间无效的节点 >

### ISSUE THREAD

**Issue by John-zhan** [Dreamacro/clash#2810]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

好多免费节点，一两天就会失效，但是手动删除节点就很费事。所以我认为可以有这么一个启动选项，或者是在dash-board 可以触发的按钮。启动选项后，一个节点累计延迟无法到达50次就删掉节点

**Comment by ac169** [comment]
这个问题和我之前的提问（[https://github.com/Dreamacro/clash/issues/2809#issue-1773898109](url)）类似，都集中在订阅节点检测和管理方面！

**Comment by Dreamacro** [comment]
这类功能不在 clash binary 的功能支持范围内
