### ISSUE TITLE
[Feature] 建议支持URL级别的代理控制

### ISSUE THREAD

**Issue by zhouwenyang** [Dreamacro/clash#2811]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

比如我只想代理下面的网址
github.com/login/*

但是我不想代理
github.com

也就说github.com除了login这个路径，其他路径都不走代理。
有没有什么办法？

**Comment by Dreamacro** [comment]
url 级别需要 mitm，这不在目前的 clash roadmap 内。
