### ISSUE TITLE
通过APi切换代理节点不成功

### ISSUE THREAD

**Issue by jxadcx** [Dreamacro/clash#2812]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/)

### Description

`headers = {

        "Authorization": "Bearer fa846fc1-40ec-4754-bb0f-a5d70c994e2b",
    }
    url = "http://127.0.0.1:9929/proxies/FSCloud"
    data = {"name": "fscloud 日本 - 002"}
    data = {"name": nodes.json()['proxies']["fscloud 日本 - 002"]['name']}
    response = requests.put(url, headers=headers, data=data)

    print(response.text)
    print(response)
`
![image](https://github.com/Dreamacro/clash/assets/128202731/4779397d-c600-4170-a860-e8f82838d861)
![image](https://github.com/Dreamacro/clash/assets/128202731/58a46af6-bb3b-4e9f-9b45-fa67fb28ebd1)

响应
{"message":"Body invalid"}
<Response [400]>
![image](https://github.com/Dreamacro/clash/assets/128202731/e09e40dc-5941-4de9-8b8f-5e21a1a8c184)

节点名字是正确的

**Comment by yhkun** [comment]
给 data加上json编码
`import json
json.dumps(data)
`
