### ISSUE TITLE
[Feature] 流量统计

### ISSUE THREAD

**Issue by djkcyl** [Dreamacro/clash#2819]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

https://github.com/Fndroid/clash_for_windows_pkg/issues/4623

能否增加一个流量统计的功能，大概是记录每个域名都走了什么规则，用了多少流量这样

### 可能的解决方案

大概可以用 sqlite 或者什么其他的方式存储这些数据？

**Comment by dyf991645** [comment]
https://github.com/Dreamacro/clash-tracing
