### ISSUE TITLE
[Bug] wrong address field of socks5 UDP ASSOCIATE

### ISSUE THREAD

**Issue by Hackerl** [Dreamacro/clash#2821]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [X] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash 2023.05.29 linux amd64 with go1.20.4 Mon May 29 14:56:49 UTC 2023

### Operating System

Linux

### Architecture

amd64

### Configuration File

```YAML
proxies:
  - name: test
    type: socks5
    server: 127.0.0.1
    port: 1080
    udp: true
```

### Description

According to the description of the [socks5 RFC](https://www.rfc-editor.org/rfc/rfc1928), the address field in the UDP ASSOCIATE request is not the target address, but the client address that will be used to send data later, which is used for the server to control permissions and prevent any address from sending data to the proxy port.

> UDP ASSOCIATE
The UDP ASSOCIATE request is used to establish an association within
the UDP relay process to handle UDP datagrams.  The DST.ADDR and
DST.PORT fields contain the address and port that the client expects
to use to send UDP datagrams on for the association.  The server MAY
use this information to limit access to the association.  If the
client is not in possesion of the information at the time of the UDP
ASSOCIATE, the client MUST use a port number and address of all
zeros.
A UDP association terminates when the TCP connection that the UDP
ASSOCIATE request arrived on terminates.
In the reply to a UDP ASSOCIATE request, the BND.PORT and BND.ADDR
fields indicate the port number/address where the client MUST send
UDP request messages to be relayed.

```go
// https://github.com/Dreamacro/clash/blob/master/adapter/outbound/socks5.go#L113
bindAddr, err := socks5.ClientHandshake(c, serializesSocksAddr(metadata), socks5.CmdUDPAssociate, user)
```
If you don't want access control, you can fill the address field with ipv4 "0.0.0.0:0".

**Comment by Dreamacro** [comment]
fixed on ac3fd60
