### ISSUE TITLE
[Feature]望对mips_siflower构架支持 

### ISSUE THREAD

**Issue by wangjony** [Dreamacro/clash#2822]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

使用GL.iNet SF1200无线路由器，该使用国产矽昌SF19A28芯片，无法安装，提示架构不支持，经过查询，该路由虽然也是mips架构，但由于经过了魔改，为mips_siflower构架，虽然小众了一点，但GL.iNet提供了完整的源代码，希望能够增加对国产芯片的支持，不甚感激！

**Comment by Dreamacro** [comment]
go 支持，这边就能支持。go 不支持的我这里也没办法

**Comment by wangjony** [comment]
> go 支持，这边就能支持。go 不支持的我这里也没办法

感谢大佬回复，官方源码是支持的，官方链接：https://github.com/Siflower/1806_SDK

**Comment by Dreamacro** [comment]
官方有没有源码没意义，得看 go

**Comment by Rongronggg9** [comment]
I come here as @wangjony had opened an issue requiring porting Golang to `mips_siflower`. I think it is unnecessary to really "port" to it, see also https://github.com/golang/go/issues/61254#issuecomment-1630622112.

Considering that the binary of Clash is statically linked and targets MIPS32, I suppose `clash-linux-mipsle` should be able to execute on it. @wangjony, could you please test if https://github.com/Dreamacro/clash/releases/download/v1.17.0/clash-linux-mipsle-hardfloat-v1.17.0.gz and https://github.com/Dreamacro/clash/releases/download/v1.17.0/clash-linux-mipsle-softfloat-v1.17.0.gz are able to execute on your device? If this is not the case, what error message do you see?

**Comment by iGerman00** [comment]
Came here same way as @Rongronggg9. I am not sure what this software is, however, I am always happy to test. I can confirm that on this architecture, both packages seem to be launchable and functional to the best of my testing. 

```
root@Router:/tmp# ./clash-linux-mipsle-hardfloat
INFO[0000] Can't find config, create a initial config file
INFO[0000] Can't find MMDB, start download
INFO[0006] Mixed(http+socks) proxy listening at: 127.0.0.1:7890
root@Router:/tmp# ./clash-linux-mipsle-hardfloat --help
Usage of ./clash-linux-mipsle-hardfloat:
  -d string
        set configuration directory
  -ext-ctl string
        override external controller address
  -ext-ui string
        override external ui directory
  -f string
        specify configuration file
  -secret string
        override secret for RESTful API
  -t    test configuration and exit
  -v    show current version of clash
root@Router:/tmp# ./clash-linux-mipsle-hardfloat -v
Clash v1.17.0 linux mipsle with go1.20.5 Fri Jun 30 13:09:54 UTC 2023
root@Router:/tmp#
```

```
root@Router:/tmp# ./clash-linux-mipsle-softfloat
INFO[0000] Mixed(http+socks) proxy listening at: 127.0.0.1:7890
root@Router:/tmp# ./clash-linux-mipsle-softfloat --help
Usage of ./clash-linux-mipsle-softfloat:
  -d string
        set configuration directory
  -ext-ctl string
        override external controller address
  -ext-ui string
        override external ui directory
  -f string
        specify configuration file
  -secret string
        override secret for RESTful API
  -t    test configuration and exit
  -v    show current version of clash
root@Router:/tmp# ./clash-linux-mipsle-softfloat -v
Clash v1.17.0 linux mipsle with go1.20.5 Fri Jun 30 13:09:15 UTC 2023
root@Router:/tmp#
```

If you are aware, how is that built? I am not very experienced with Golang. I would love to try and compile Tailscale for this device.

**Comment by Dreamacro** [comment]
@iGerman00 you can search ** mipsle-softfloat** on clash Makefile for Go compile env，and then you can try it on build tailscale

**Comment by Rongronggg9** [comment]
> I would love to try and compile Tailscale for this device.

@iGerman00 Hmm, have you tried https://pkgs.tailscale.com/stable/tailscale_1.44.0_mipsle.tgz ? I suppose it should work on `mips_siflower` as it is statically linked too.

**Comment by iGerman00** [comment]
> > I would love to try and compile Tailscale for this device.
> 
> @iGerman00 Hmm, have you tried https://pkgs.tailscale.com/stable/tailscale_1.44.0_mipsle.tgz ? I suppose it should work on `mips_siflower` as it is statically linked too.

Ok update, I managed to compile a combined binary, but it's so huge for a router at 30mb, that's mipsle softfloat, but trying to compress it with upx (4.0.2) it will segfault

**Comment by Rongronggg9** [comment]
> I'm pretty sure the packages they provide aren't statically linked so they won't work

Interesting to know. How can you prove that? I didn't see any evidence indicating that their binaries are dynamically linked from the analysis of `readelf`, `file` and `ldd`. And what error did you see when you executed them? Their binaries seem to be soft-float, consuming more RAM compared to hard-float binaries. OOM may occur.

**Comment by Dreamacro** [comment]
It looks like the original problem has been solved, so close
