### ISSUE TITLE
[Bug] <dualStackDialContext may cause tcp connetion leak>

### ISSUE THREAD

**Issue by bigjordon** [Dreamacro/clash#2825]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

v1.17.0

### Operating System

macOS (darwin)

### Architecture

amd64

### Configuration File

```YAML
mixed-port: 7890
log-level: debug
```

### Description

startRacer := func(ctx context.Context, network, host string, ipv6 bool) {
		result := dialResult{ipv6: ipv6, done: true}
		defer func() {
			select {
			case results <- result:
			case <-returned:
				if result.Conn != nil {
					result.Conn.Close()
				}
			}
		}()

If both results are success, the second one not close properly

**Comment by Dreamacro** [comment]
两个同时成功，一个会进 results，另一个由于 returned close 了，会走 close 逻辑

**Comment by bigjordon** [comment]
是的，`results`没有关闭，保证了会走returned close。
