### ISSUE TITLE
[Feature] 添加逻辑判断规则，Add logical judgement rule.

### ISSUE THREAD

**Issue by HAMAN23333** [Dreamacro/clash#2835]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

目前clash的使用体验近乎完美了，也有parser预处理等其他软件没有的功能，就是在规则方面要是能有逻辑判断就更好了

例:

```yaml
rules:
  
  #OR(或):地址段为202.6.114.0/24，或者域名为csdn.com
  - OR,((IP-CIDR,202.6.114.0/24),(DOMAIN,csdn.com)),REJECT
  
  #NOT(否)：域名不为baidu.com访问
  - NOT,(DOMAIN,baidu.com),PROXY

  #AND(和)：来自192.168.1.201地址的666端口入站
  - AND,((SRC-IP-CIDR,192.168.1.201/32),(SRC-PORT,666)),DIRECT
  
  #规则集为Privacy或者关键字为ad，不包括误杀规则集
  - AND,((OR,((RULE-SET,Privacy),(DOMAIN-KEYWORD,ad))),(NOT,(RULE-SET,Advertisem-DIRECT))),REJECT
```

**AND：** 和，多条件必须同时满足
**OR：** 或，满足一个条件即可
**NOT：** 否，不为这个条件的

### 可能的解决方案

- 逻辑判断规则支持多层嵌套，注意括号的用法；

- 写法可能决定执行效率，可根据情况适当优化：

> 1. AND,((GEOSITE,gfw),(RULE-SET,GOOGLE)),DIRECT
> 2. AND,((RULE-SET,GOOGLE),(GEOSITE,gfw)),DIRECT
>日常中访问谷歌系频繁的情况下，写法2效率明显高于写法1，因为2先匹配谷歌连接，然后再匹配gfw。

**Comment by Dreamacro** [comment]
https://dreamacro.github.io/clash/premium/script-shortcuts.html

**Comment by HAMAN23333** [comment]
> https://dreamacro.github.io/clash/premium/script-shortcuts.html

试了一下确实可以这么实现，可以关issue了。

'''
rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,Lan,DIRECT
  - if: (not(match_provider('Direct'))) and (match_provider('Advertising') or
      match_provider('Advertising_Domain'))
    name: AD
    rules:
      - MATCH,REJECT
  - RULE-SET,Download,⚡ 下载
  - RULE-SET,PrivateTracker,⚡ 下载
'''
