### ISSUE TITLE
[Bug]  不支持ipv6的trojan服务器

### ISSUE THREAD

**Issue by Ex-Origin** [Dreamacro/clash#2838]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.05.29 linux amd64 with go1.20.4 Thu Jun  1 14:44:02 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
proxies:
    - { name: 'my-server', type: trojan, server: 2409:8a48:a443:f640:cc41:494f:f4ac:5451, port: 4443, password: aMyll4tzAU4cR5lW-a2KR46z9bj4Sk45q, udp: false, sni: cloudflare.com, skip-cert-verify: true}
```

### 问题描述

clash不支持ipv6的trojan服务器，使用tcpdump进行网卡监控，主机并没有向ipv6的trojan服务器发送任何请求。

**Comment by Dreamacro** [comment]
`[2409:8a48:a443:f640:cc41:494f:f4ac]:5451`
