### ISSUE TITLE
[Bug] `fatal error: sigaction failed` when trying to run on MediaTek MT7621AT

### ISSUE THREAD

**Issue by shvchk** [Dreamacro/clash#2842]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

1.17.0

### Operating System

Linux

### Architecture

mipsle-hardfloat

### Configuration File

N/A, can't even run `clash --help`

### Log

No log, it just fails to run with the following error:

```
fatal error: sigaction failed

runtime stack:
runtime.throw({0x67aca8, 0x10})
        runtime/panic.go:1047 +0x54 fp=0x7fffecd8 sp=0x7fffecc4 pc=0x55714
runtime.sysSigaction.func1()
        runtime/os_linux.go:555 +0x4c fp=0x7fffece4 sp=0x7fffecd8 pc=0x8e3c4
runtime.sysSigaction(0x80, 0x0, 0x7fffed10)
        runtime/os_linux.go:554 +0x7c fp=0x7fffecfc sp=0x7fffece4 pc=0x51830
runtime.sigaction(...)
        runtime/sigaction.go:15
runtime.getsig(...)
        runtime/os_linux.go:521
runtime.initsig(0x0)
        runtime/signal_unix.go:134 +0xe4 fp=0x7fffed30 sp=0x7fffecfc pc=0x72788
runtime.mstartm0()
        runtime/proc.go:1523 +0x70 fp=0x7fffed38 sp=0x7fffed30 pc=0x5cfbc
runtime.mstart1()
        runtime/proc.go:1495 +0x94 fp=0x7fffed48 sp=0x7fffed38 pc=0x5ceb4
runtime.mstart0()
        runtime/proc.go:1456 +0x78 fp=0x7fffed5c sp=0x7fffed48 pc=0x5cdfc
runtime.mstart()
        runtime/asm_mipsx.s:89 +0x14 fp=0x7fffed60 sp=0x7fffed5c pc=0x93e6c

goroutine 1 [runnable]:
runtime.main()
        runtime/proc.go:145 fp=0xc287ec sp=0xc287ec pc=0x59060
runtime.goexit()
        runtime/asm_mipsx.s:617 +0x4 fp=0xc287ec sp=0xc287ec pc=0x962a0
```

### Description

I'm trying to run clash on a [Fibertool FT-AIR-DUO-G](https://wikidevi.wi-cat.ru/Fibertool_FT-AIR-DUO-G) router. How do I debug, what goes wrong (maybe I don't have some dependencies installed)?

```
> uname -a
Linux Wive-NG-HQ 3.4.114.313 #1 SMP 21042023 mips GNU/Linux
```

```
> lsmod
Module                  Size  Used by
wireguard             107199  0
ext4                  286191  1
mbcache                 5134  1 ext4
jbd2                   51198  1 ext4
usb_storage            31137  1
hw_nat                 19005  0
mt7615_ap            2139140  2
nf_nat_ftp              1121  0
nf_conntrack_ftp        5201  1 nf_nat_ftp
```

### Reproduction Steps

```sh
t="mipsle-hardfloat"
wget -qO- "https://github.com/Dreamacro/clash/releases/download/v1.17.0/clash-linux-${t}-v1.17.0.gz" | gunzip -c > clash
chmod +x clash
./clash --help
```

**Comment by shvchk** [comment]
Same on v1.18.0:

```
> ./clash --help
fatal error: sigaction failed

runtime stack:
runtime.throw({0x67f03e, 0x10})
        runtime/panic.go:1077 +0x54 fp=0x7fffece0 sp=0x7fffeccc pc=0x5a1fc
runtime.sysSigaction.func1()
        runtime/os_linux.go:560 +0x4c fp=0x7fffecec sp=0x7fffece0 pc=0x940dc
runtime.sysSigaction(0x80, 0x0, 0x7fffed1c)
        runtime/os_linux.go:559 +0x7c fp=0x7fffed04 sp=0x7fffecec pc=0x5648c
runtime.sigaction(...)
        runtime/sigaction.go:15
runtime.getsig(...)
        runtime/os_linux.go:526
runtime.initsig(0x0)
        runtime/signal_unix.go:134 +0x100 fp=0x7fffed40 sp=0x7fffed04 pc=0x77f50
runtime.mstartm0()
        runtime/proc.go:1624 +0x70 fp=0x7fffed48 sp=0x7fffed40 pc=0x61e80
runtime.mstart1()
        runtime/proc.go:1596 +0x94 fp=0x7fffed58 sp=0x7fffed48 pc=0x61d78
runtime.mstart0()
        runtime/proc.go:1557 +0x7c fp=0x7fffed6c sp=0x7fffed58 pc=0x61cc4
runtime.mstart()
        runtime/asm_mipsx.s:89 +0x14 fp=0x7fffed70 sp=0x7fffed6c pc=0x9bdd0

goroutine 1 [runnable]:
runtime.main()
        runtime/proc.go:144 fp=0xc287ec sp=0xc287ec pc=0x5dddc
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0xc287ec sp=0xc287ec pc=0x9e204
```

**Comment by Dreamacro** [comment]
Have you tried running other mips artifacts?

**Comment by shvchk** [comment]
Yep, mipsle-hardfloat and mipsle-softfloat are the only one that *try* to run (although failing with the same fatal error). When trying any other shell complains that executable is of wrong type or something like that. 

Maybe not Clash's fault, since I have tried other Go apps today, and have the same problem. Will test with some minimal Go hello world later today. I have no experience with Go, maybe I'm missing something obvious, maybe my router OS lacks something to support running Go apps?

**Comment by Dreamacro** [comment]
run `go tool dist list` can list all golang support platform

**Comment by shvchk** [comment]
Tested with a hello world Go program, doesn't run. Therefore, it's definitely not a Clash's problem. Closing.
