### ISSUE TITLE
每个节点单独分配一个http port

### ISSUE THREAD

**Issue by lmmir** [Dreamacro/clash#2843]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

每个节点单独分配一个http proxy port

### 可能的解决方案

每个节点单独分配一个http proxy port

**Comment by unknownUser99999** [comment]
> 为什么...？

因为每个应用需要使用不同的代理端口分流

**Comment by rthacker87** [comment]
如果是在linux环境，你通过shell或者python这样的工具一次启动多个clash呢？是不是可以满足每个node一个port的实现

**Comment by unknownUser99999** [comment]
> 如果是在linux环境，你通过shell或者python这样的工具一次启动多个clash呢？是不是可以满足每个node一个port的实现

linux这个确实可以

**Comment by unknownUser99999** [comment]
> > > 为什么...？
> > 
> > 
> > 因为每个应用需要使用不同的代理端口分流
> 
> 不是可以路由吗？把不同的应用流量路由到不同的出口

路由我感觉有时候不起作用，而且可能会漏流量，有的流量比如a.exe调用b.exe这种，其实配置了a也没啥用。我觉得可能他自己程序有代理端口的话可能能包含完，不过这个确实挺难搞

**Comment by lmmir** [comment]
这样程序可以按照自己方式进行代理使用了，程序可以自己进行负载均衡逻辑处理

**Comment by BirkhoffLee** [comment]
这个问题之前提过，clash 不干这活
