### ISSUE TITLE
使用LocalAddr实现TUN分流

### ISSUE THREAD

**Issue by Fndroid** [Dreamacro/clash#285]
由于Clash多outbound模式下，使用tun2socks会出现环路无法上网。

目前CFW使用的方案是使用Clash的fake-ip，在路由表中设定fake-ip段发送数据至TAP网卡，但是这样部分直接使用IP通讯的APP就不能被代理。

和[Mellow](https://github.com/eycorsican/Mellow)作者沟通之后发现其实可以使用两个默认路由来做：
```
route delete default
route add default 10.255.0.1
route add default 192.168.1.1 -ifscope en0
```

https://github.com/Dreamacro/clash/blob/0d51877fcdab1392c4dedfce0fabfb494998d6cb/adapters/outbound/util.go#L112

这里设定Dialer的LocalAddr为本机地址（192.168.50.123:0），就能让Clash的请求绕过TAP。这样IP类的请求也能通过TAP进入Clash。

不知道Mac的TUN是怎么样实现的，理论上这种方法同时适用Windows/Linux/macOS，希望可以增加配置这个LocalAddr字段的方法。

参考：https://github.com/eycorsican/go-tun2socks/blob/f12913c17d2e5a05d98ec24f05d8dcc5d7816b39/proxy/d/tcp.go#L82

**Comment by luckypoem** [comment]
@Fndroid 
clash是否也包含tun2socks功能，从而可以做全局（整台机器的）代理？

**Comment by chenzhiwei** [comment]
@Fndroid @luckypoem  请问这个问题最终怎样解决的？

我这里在 Linux 直接用 systemd 管理的 clash，IP通讯的流量是无法过clash的，除非将IPCIDR加到路由表里，让其走clash utun，但是这样实在太麻烦了。

至于将 clash utun （默认为192.18.0.1）设置成默认路由，我这里测试了一下是不可行的，也许是我方法用错了，但是最是没搞定。

cc @Dreamacro

**Comment by Fndroid** [comment]
@chenzhiwei win上已经实现了。至于linux应该能直接用tun吧，把utun设置成默认路由就行了，配置加上interface-name到物理网卡就行

**Comment by chenzhiwei** [comment]
@Fndroid  谢谢。

我觉得这样应该也行，但是无论我设置两个默认路由，还是只将clash utun设置成默认路由（会无法联网）都不行。

将 clash rules 里面的 IPCIDR 添加到路由表里是可以的，但是太麻烦了。

等等看看 @Dreamacro 有什么建议吧。
