### ISSUE TITLE
优化kernel对wireguard的支持

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [Dreamacro/clash#2852]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

我也参考了下其他的issue，包括meta内核的issue，但都发现对于clash内核原生支持wireguard的处理都不是非常理想
希望作者团队可以考虑下优化内核原生对wireguard的支持，非常感谢，辛苦了

**Comment by BirkhoffLee** [comment]
没听懂

**Comment by C63H88CoN14O14P** [comment]
> 没听懂

就是目前clash内核对于wireguard的协议的运行效率不及wireguard客户端

**Comment by BirkhoffLee** [comment]
wiki 写的很清楚
clash 是 userspace wireguard
你所说的 wireguard 客户端是 kernel space wireguard 的 ui

**Comment by peanut996** [comment]
> wiki 写的很清楚 clash 是 userspace wireguard 你所说的 wireguard 客户端是 kernel space wireguard 的 ui

看过一篇博客的benchmark，wireguard-go和kernel wireguard的吞吐量差距也不是很大，但是疑惑的是在使用体验上会这么明显
![image](https://github.com/Dreamacro/clash/assets/32303768/daf1fff5-ec21-4f29-96e6-13273083e01c)

[refer](https://tailscale.com/blog/throughput-improvements/)
