### ISSUE TITLE
[Feature] 进程路径前缀匹配的规则方式

### ISSUE THREAD

**Issue by MysticalMusings** [Dreamacro/clash#2856]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

对于进程匹配的方式，当同一目录下的执行文件太多时，一条一条的添加进程规则比较繁琐。

类似于域名前缀匹配，希望能增加通过进程路径前缀匹配的方式，比如说叫 `PROCESS-PREFIX`：
```YAML
rules:
  - PROCESS-PREFIX,D:/example,PROXY
```

这样，在`D:/example`目录下的文件都会通过代理的方式连接。

~或者更大胆一点的，正则表达式的匹配~

### 可能的解决方案

（不知道是否容易实现，或者是否影响性能）

**Comment by Dreamacro** [comment]
使用 https://dreamacro.github.io/clash/premium/script-shortcuts.html
