### ISSUE TITLE
url-test工作和预期不同

### ISSUE THREAD

**Issue by maplewf** [Dreamacro/clash#2857]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash 2023.07.22 linux amd64 with go1.20.6 Sat Jul 22 09:42:37 UTC 2023

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
proxies:
  - name: http_proxy
    type: http
    server: 10.12.6.11
    port: 12345

proxy-groups:
  - name: auto_switch
    type: url-test
    proxies:
      - http_proxy
      - DIRECT
    url: "http://yahoo.co.jp"
    interval: 15

rules: # match in order
  ... 省略一些规则
  - RULE-SET,proxy,auto_switch
  ... 省略一些规则
  - MATCH,auto_switch
```

### 日志输出

```Text
...一开始clash启动时
11:53:39 INF [TCP] connected lAddr=127.0.0.1:49390 rAddr=outlook.office.com:443 mode=rule rule=RuleSet(proxy) proxy=auto_switch[http_proxy]
11:53:50 INF [TCP] connected lAddr=127.0.0.1:41736 rAddr=www.google.com.hk:443 mode=rule rule=RuleSet(proxy) proxy=auto_switch[http_proxy]
...过了十几秒
11:54:00 INF [TCP] connected lAddr=127.0.0.1:57282 rAddr=clients4.google.com:443 mode=rule rule=RuleSet(proxy) proxy=auto_switch[DIRECT]
11:54:12 INF [TCP] connected lAddr=127.0.0.1:56802 rAddr=www.google.com:443 mode=rule rule=RuleSet(proxy) proxy=auto_switch[DIRECT]
11:54:12 INF [TCP] connected lAddr=127.0.0.1:56806 rAddr=www.google.com.hk:443 mode=rule rule=RuleSet(proxy) proxy=auto_switch[DIRECT]
```

### 问题描述

我采用了以上这种url-test的方式为一些可能需要的网页加速，因为http_proxy有时可能不可用，那就用DIRECT的方式，如果可用，那就通过url测速的方式选择延时小的一方，以上的日志所产生的环境中http_proxy是可用的。当clash启动的时候，一开始它使用了proxy，但是十几秒以后它就切换到了DIRECT，并且一直就这么保持下去了。我自己用httping测试了一下url:

这是DIRECT的情况：
httping -g http://yahoo.co.jp
PING yahoo.co.jp:80 (/):
connected to 182.22.16.123:80 (400 bytes), seq=0 time=221.07 ms 
connected to 182.22.24.252:80 (400 bytes), seq=1 time=178.95 ms 
connected to 182.22.31.124:80 (400 bytes), seq=2 time=251.46 ms 
connected to 183.79.217.124:80 (400 bytes), seq=3 time=188.22 ms 
...

这是proxy的情况：
httping -g http://yahoo.co.jp -x 10.12.6.11:12345
PING yahoo.co.jp:80 (/):
connected to yahoo.co.jp:80 (541 bytes), seq=0 time= 93.16 ms 
connected to yahoo.co.jp:80 (541 bytes), seq=1 time= 83.18 ms 
connected to yahoo.co.jp:80 (541 bytes), seq=2 time= 84.60 ms 
...

差别还是非常大的，但是为什么clash就一直使用延时大的那个呢？我查阅了wiki，里面对于url-test的描述也十分有限，我不知道我的配置有什么问题吗？还是确实url-test就这个行为？还是DIRECT有什么特殊的处理？

**Comment by Dreamacro** [comment]
你调用 clash 的 api，里面存着最近 10 次的测速结果，你可以先看一下那个信息
