### ISSUE TITLE
[Documentation Enhancement] TUN device, DNS server doc clarity

### ISSUE THREAD

**Issue by Meowzz95** [Dreamacro/clash#2870]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/)

### Description

Thank you for the nice open-source project and the effort to maintain the documentation. I'd like to help improve the doc if someone is able to shine some light on the below.

I've read the official documentation on [Clash DNS](https://dreamacro.github.io/clash/configuration/dns.html), [Configuration Reference](https://dreamacro.github.io/clash/configuration/configuration-reference.html) and [TUN Device,](https://dreamacro.github.io/clash/premium/tun-device.html) however, I'm still quite confused on how these components work together and how does one affect another.

In particular, I found the following not well explained in the documentation:

### Section 1
In `tun` object, what does `dns-hijack` do exactly, to my understanding, this helps to hijack DNS requests sent to the TUN device so that we can maintain an in-memory mapping of url and IP so that rule-based routing can work, otherwise we don't know the URL at the TUN device level at all. Questions:
- Do we have to enable DNS server for it to work?
  - if no, does clash use system DNS to resolve the domain? If clash uses system DNS to resolve, is this subject to monitoring? (the DNS provider, for example, the ISP will be able to monitor the DNS queries?)
  - if yes, it doesn't seem to throw an error if the DNS server is not enabled

I've tested disabling DNS-hijack, manually pointing my DNS server to 127.0.0.1 and enabling clash DNS server, and it works correctly. So is there any concern if one set up in this way?

### Section 2
For DNS server, the current doc states: 
> All DNS questions are sent directly to the nameserver, without proxies

However, according to my test, if the traffic is routed to an outbound, the DNS request seems to be processed by the outbound.

Example:
Let's say there is a private DNS record pointing to a private IP that only outbound KITTY can access, the URL is "cute.kitty.com".
I have a DNS server setting like this
```
default-nameserver:
    - 8.8.8.8
nameserver:
    - https://dns.google/dns-query
```
and a rule to route DOMAIN-SUFFIX kitty.com to outbound KITTY.
According to the doc, this DNS should be resolved by Google directly without proxy, however, I **can** access "cute.kitty.com" correctly, which means both the DNS request and the network traffic is routed to outbound KITTY. I actually like this behaviour (since it makes my life easier, I don't need to take care of the private DNS part), but this behaviour doesn't seem to align with the documentation.

Furthermore, if one decides to route ALL traffic to outbounds (no direct), then the nameserver set in the `dns` object seems to be useless (because all DNS resolutions are processed by outbounds)

### Section 3

auto-route is nice, should we share some internal workings so that we understand it better? For example, how do we manipulate the routing table? How do we restore the routing table upon exit? What happens if there's a crash?

### Possible Solution

I can help to make a PR to the documentation if I can get a better understanding of the above topics. Thanks!

**Comment by Dreamacro** [comment]
> this helps to hijack DNS requests sent to the TUN device so that we can maintain an in-memory mapping of url and IP

it's the host, not URL

> Do we have to enable DNS server for it to work?

If you don't care about host, you don't need it. If you care, DNS server is a must.

> If clash uses system DNS to resolve, is this subject to monitoring? 

If you care about this, use DoH or use tunnel proxy UDP DNS

> Furthermore, if one decides to route ALL traffic to outbounds (no direct), then the nameserver set in the dns object seems to be useless (because all DNS resolutions are processed by outbounds)

It will only be used for rule matching if it is not DIRECT.
