### ISSUE TITLE
[Feature] 希望支持同时使用多个 mmdb 文件

### ISSUE THREAD

**Issue by Loyalsoldier** [Dreamacro/clash#2881]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

由于 MaxMind mmdb 文件格式的限制，同一个 IP / CIDR 只能归属于一个列表中，譬如 `1.1.1.1` 只能归属于 `澳大利亚 au` 或者 `cloudflare`，而不能同时归属于 `澳大利亚 au` 和 `cloudflare`，导致两个问题：

- 定制 mmdb 文件时必须控制列表写入顺序，一个 IP / CIDR 只存在于“**后写入**”的列表中
- 如果 GEOIP 规则中出现如下规则，则无法做到「**所有澳大利亚 au IP 走 proxy**」的目的，因为「澳大利亚 au」列表中缺少了 「1.1.1.1」这个 IP（`1.1.1.1` 归属于 `cloudflare`）：

```
- GEOIP,au,proxy
- GEOIP,cloudflare,another-proxy
```

**支持同时使用多个 mmdb 文件的好处：**

- 降低定制 mmdb 文件的复杂度和难度；
- 通过定制 mmdb 文件，可以只保留需要使用的 IP / CIDR 列表，显著减少 Clash 内存占用；
- 实现上述规则的正确分流。

**Comment by InspoOnU** [comment]
为啥不用rule-set
