### ISSUE TITLE
[Bug] http的header大小写问题

### ISSUE THREAD

**Issue by darkbfly** [Dreamacro/clash#2886]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash v1.18.0 windows amd64 with go1.21.0 Thu Aug 17 14:55:18 UTC 2023

### 适用的作业系统

Windows

### 适用的硬件架构

amd64-v3

### 配置文件

```YAML
# Profile Template for clash verge
port: 9988
allow-lan: true
log-level: debug
mode: rule
proxies:

proxy-groups:

rules:
```

### 日志输出

```Text
time="2023-08-18T15:21:55+08:00" level=info msg="inbound http://:9988 create success."
time="2023-08-18T15:21:57+08:00" level=info msg="[TCP] 127.0.0.1:45254 --> 127.0.0.1:16000 doesn't match any rule using DIRECT"
```

### 问题描述

当http报文通过clash发给后台时 自定义的header会变为大写 例如timestamp: 1234567890123 会变为 Timestamp: 1234567890123

### 复现步骤

代理运行到9988 无任何配置信息
建立一个socket监听 16000
执行 `curl -k -X POST -H "timestamp: 1234567890123" --data 123123 -x http://127.0.0.1:9988 http://127.0.0.1:16000/test`
监听收到
```
POST /test HTTP/1.1
Host: 127.0.0.1:16000
User-Agent: curl/8.0.1
Content-Length: 6
Accept: */*
Content-Type: application/x-www-form-urlencoded
Timestamp: 1234567890123
Accept-Encoding: gzip

123123
```

执行 `curl -k -X POST -H "timestamp: 1234567890123" --data 123123  http://127.0.0.1:16000/test`
监听收到
```
POST /test HTTP/1.1
Host: 127.0.0.1:16000
User-Agent: curl/8.0.1
Accept: */*
timestamp: 1234567890123
Content-Length: 6
Content-Type: application/x-www-form-urlencoded

123123
```

**Comment by Dreamacro** [comment]
rfc2616 表明，header 不应该是大小写敏感的，所以 header 是否大小写不应该是一个 bug

**Comment by darkbfly** [comment]
我理解您的意思了 那比如的确有这样的需求的话 这个情况下如何能正确处理 比如多一个配置项这样的?

**Comment by Dreamacro** [comment]
多一个配置项不能解决问题，应该在接收处正确处理 header 的行为

**Comment by darkbfly** [comment]
好的 谢谢
