### ISSUE TITLE
[Bug] Clash v1.18.0 linux arm v7版本无法监听0.0.0.0:7890

### ISSUE THREAD

**Issue by U201413497** [Dreamacro/clash#2887]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [X] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

Clash v1.18.0 linux arm with go1.21.0

### 适用的作业系统

Linux

### 适用的硬件架构

armv7

### 配置文件

```YAML
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: Rule
```

### 日志输出

```Text
root@onecloud:~# ./clash clash.yaml
INFO[0000] inbound mixed://127.0.0.1:7890 create success.
```

### 问题描述

inbound的配置内容如上，按照教程配置的。监听的还是127.0.0.1:7890,而不是0.0.0.0:7890

**Comment by Dreamacro** [comment]
没有复现，检查一下配置文件是否用对

**Comment by U201413497** [comment]
不好意思，找到问题了。可以关闭，谢谢。

**Comment by natsu-22** [comment]
我遇到了同样的问题，请问如何解决的呢
