### ISSUE TITLE
[Feature] 关于quic的支持

### ISSUE THREAD

**Issue by Zxilly** [Dreamacro/clash#2888]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

之前的讨论已经被关闭并锁定。

### 描述

目前，clash 不支持任何基于 udp 的协议。
在之前的讨论（#1863,#2372）中，关于 Hysteria 的支持已经被讨论过多次，主要的问题应该是 quic-go 这个实现是否应该被引入。
在之前的版本中，quic-go 一直依赖修改过的官方 tls 库，但是在 go1.21 后，quic-go 已经能够直接依赖官方标准库运行（[quic-go 0.37.0](https://github.com/quic-go/quic-go/releases/tag/v0.37.0) ）。而在 https://github.com/Dreamacro/clash/commit/cb8c732375f25c305636cfa6d5297d60beae7a39 中， clash core 已经 migrate 到 go1.21，因此对于 Hysteria 及 v2ray-quic 的支持是否能够纳入考虑？

**Comment by Dreamacro** [comment]
等官方 quic 库，没记错的话 Hysteria 是魔改 quic-go，引入很多相似但不相同的东西感觉十分可怕

**Comment by Zxilly** [comment]
/x/net 里已经有 quic 的实现了，但是看起来距离可用还有一定的距离 ([/x/net/internal](https://cs.opensource.google/go/x/net/+/master:internal/quic/doc.go))
Hysteria 魔改的原因是 quic-go 不支持自定义 congestion，而官方实现看起来也只会支持 rfc 9002 定义的 reno。Hysteria 的问题短时间内应该解决不了，可能 v2ray-quic 可以先提上议程？

**Comment by Dreamacro** [comment]
等官方 quic 实现，要用 quic-go 应该早用了，也不会等到现在
