### ISSUE TITLE
Clash抓取到的都是内网地址，导致GEOIP规则失效

### ISSUE THREAD

**Issue by Andychencn** [Dreamacro/clash#289]
我在自己的二级路由器和PC上部署了Clash，两台设备直连一级路由，一级路由通过光猫拨号上网。
配置规则geoip cn direct以后设置到系统级代理，发现PC所有流量都通过代理出去了。查看Logs发现Clash 抓取到的IP地址都是15开头的内网私有地址，PC上通过Ping可以获得正确的目标IP地址。
二级路由上配置了自定义dns，查看debug路由自定义dns已经生效了，但是和PC一样所有流量都通过代理出去了。
一级路由上没有配置任何服务，只有简单的拨号上网功能。
![BUG1](https://user-images.githubusercontent.com/54764347/64073922-24444680-ccd7-11e9-8b36-6db27121006e.PNG)
![Screenshot_20190901-164521_Chrome](https://user-images.githubusercontent.com/54764347/64074011-23f87b00-ccd8-11e9-99ec-a2bad36feef1.jpg)

**Comment by comzyh** [comment]
> Clash 抓取到的IP地址都是15开头的内网私有地址

这是什么意思？source 是 15开头还是 目标IP 是 15开头？截图里好像啥都没有。

**Comment by Andychencn** [comment]
> > Clash 抓取到的IP地址都是15开头的内网私有地址
> 
> 这是什么意思？source 是 15开头还是 目标IP 是 15开头？截图里好像啥都没有。

目标是15开头，所以直接匹配了match规则走了代理。
