### ISSUE TITLE
[Bug] [Parser Error] m.filter is not a function

### ISSUE THREAD

**Issue by Bannirui** [Dreamacro/clash#2899]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

v0.20.32

### Operating System

Linux

### Architecture

amd64

### Configuration File

```YAML
parsers: # array
    url: {your-url}
    yaml:
      prepend-rules:
        - DOMAIN-KEYWORD,bilibili,Proxy
```

### Description

First of all, i define prepend rules in Parsers file(Settings->Profiles->Parsers).  It will throw an Exception(Download profile failed with error: [Parser Error] m.filter is not a function) since i attempt to update profile(Profiles).

As a before/after, no error occurs while discarding Parser file(settings->Profiles->Parsers).

**Comment by Dreamacro** [comment]
parsers isn't a clash feature
