### ISSUE TITLE
[Feature] support PROCESS-PATH-PREFIX like rule

### ISSUE THREAD

**Issue by hiberabyss** [Dreamacro/clash#2902]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/)

### Description

Suggest support `PROCESS-PATH-PREFIX` rule which will match process with specific path prefix.

In macOS, some application like Chrome may have many processes with different names. To make rule took effect from Chrome, we need to add several `PROCESS-NAME` rules, it's not convenient.

If `PROCESS-PATH-PREFIX` supported, we could just specify `/Applications/Google Chrome.app` to make rule work for Chrome.

If this feature is reasonable, I could try to implement it.

**Comment by hiberabyss** [comment]
> use script shortcuts instead https://dreamacro.github.io/clash/premium/script-shortcuts.html

Could the script shortcut also be supported in rule provider?

**Comment by hiberabyss** [comment]
@Dreamacro I'm curious how the process-path worked.

I use script shortcut for chrome:

```
chrome: hasPrefix(process_path, '/Applications/Google Chrome.app')
```

It worked fine for most website. However, for some website, it did not work; the rule could not be matched.

Is the path info could not got for some website?

**Comment by Dreamacro** [comment]
@hiberabyss add a PROCRSS-NAME rule on the top, and then you can find all information on connections page

**Comment by hiberabyss** [comment]
Amazing, it worked even if the PROCESS-NAME rule has nothing to do with chrome. Thanks!
