### ISSUE TITLE
[Feature] Add DNS field for proxies in yaml

### ISSUE THREAD

**Issue by aereobert** [Dreamacro/clash#2904]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I have looked for my idea in [the issue tracker](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement), **and found none of which being related**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/)

### Description

This would be useful for some badly configured enterprise networks. 

Let's say that some stupid company used their own local DNS to resolve their OA servers (same domain but different servers for LAN and WAN), and other public servers like google. When you are trying to use Clash to jump back to the network on your laptop, if you set the DNS globally in the config file, you cannot use the private DNS because it is not always accessible in WAN, and setting the private DNS regardlessly leads to slow DNS resolving for all websites. Things gets shitty vice versa, when you are in the LAN, you switch proxy group to DIRECT, and boom you cannot access OA because you used DNS outside. 

### Possible Solution

Therefore, it would be great to provide possibility to config DNS in the proxy itself. When using a specific proxy, use the corresponding DNS. (e.g., Proxy ExpressVPN with DNS 1.1.1.1, Proxy Company with DNS 10.10.10.1)

Thanks!

**Comment by Dreamacro** [comment]
Perhaps what you are looking for is `nameserver-policy`

**Comment by aereobert** [comment]
Hi, thanks for your reply, but I think nameserver-policy cannot fulfill the need.

Let's say the company has domain.com, and there are two DNS servers, 192.168.1.1 for LAN in the company, and 1.1.1.1 for WAN worldwide. the former resolves domain.com to 192.168.1.2, while the latter resolves to 33.33.33.33. In this scenario, you cannot just set the nameserver-policy to bind domain to DNS, setting nameserver-policy either 192.168.1.1 or 1.1.1.1 will not work when you move your laptop between WAN or LAN. This scenario is frequent in company settings.

Therefore, I would suggest adding fields like dns-override for the proxy. Thanks!
