### ISSUE TITLE
panic: interface conversion: interface {} is map[interface {}]interface {}, not string

### ISSUE THREAD

**Issue by tianxiangkid** [Dreamacro/clash#291]
panic: interface conversion: interface {} is map[interface {}]interface {}, not string

goroutine 1 [running]:
github.com/Dreamacro/clash/config.proxyGroupsDagSort(0xdc69c0, 0x8, 0x8, 0x16, 0xc28088)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/config/utils.go:78 +0x16c0
github.com/Dreamacro/clash/config.parseProxies(0xc9a0a0, 0xc68370, 0x0, 0x0)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/config/config.go:296 +0x8d0
github.com/Dreamacro/clash/config.Parse(0xc1a4c0, 0x16, 0x2, 0xc1a4c0, 0x16)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/config/config.go:170 +0xe0
github.com/Dreamacro/clash/hub/executor.ParseWithPath(...)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/hub/executor/executor.go:21
github.com/Dreamacro/clash/hub/executor.Parse(0xa, 0x4fab37, 0xb)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/hub/executor/executor.go:16 +0xb0
github.com/Dreamacro/clash/hub.Parse(0x7fd29b5e, 0xa)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/hub/hub.go:10 +0x34
main.main()
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/main.go:51 +0x188

wndr 3700v4
openwrt 18.04
貌似是解json出错？

**Comment by Dreamacro** [comment]
@comzyh cc

**Comment by comzyh** [comment]
配置文件能贴下吗，去掉敏感数据。

我觉得你的配置文件可能有问题，比如 proxyName 不是字符串之类的。

**Comment by comzyh** [comment]
我认为你可能是配置文件某个 proxies 数组里面有不是 字符串的元素。

**Comment by tianxiangkid** [comment]
> 我认为你可能是配置文件某个 proxies 数组里面有不是 字符串的元素。

您好，我看了， proxies 数组没有非字符串元素，而且这个配置文件在我另一个路由器里面是可以正常使用的

**Comment by tianxiangkid** [comment]
> 我认为你可能是配置文件某个 proxies 数组里面有不是 字符串的元素。

应该是我调用的外壳，在脚本处理上有问题，容我读一下，谢谢回复

**Comment by Dreamacro** [comment]
@tianxiangkid 最好提供配置文件 方便排查 panic

**Comment by comzyh** [comment]
我可以复现这个问题，使用错误格式的配置就行，例如 

```yaml
'Proxy Group':
  - { name: Proxy, type: select, proxies: [{}]}
```

```
panic: interface conversion: interface {} is map[interface {}]interface {}, not string

goroutine 1 [running]:
github.com/Dreamacro/clash/config.proxyGroupsDagSort(0xc0000a84b0, 0x9, 0x9, 0x4, 0xc000245708)
	/home/comzyh/go/src/github.com/Dreamacro/clash/config/utils.go:75 +0x1783
github.com/Dreamacro/clash/config.parseProxies(0xc0000da420, 0xc0000f0240, 0x0, 0x0)
	/home/comzyh/go/src/github.com/Dreamacro/clash/config/config.go:307 +0x14a1
github.com/Dreamacro/clash/config.Parse(0xc00002e360, 0x26, 0x2, 0xc00002e360, 0x26)
	/home/comzyh/go/src/github.com/Dreamacro/clash/config/config.go:172 +0xf9
github.com/Dreamacro/clash/hub/executor.ParseWithPath(...)
	/home/comzyh/go/src/github.com/Dreamacro/clash/hub/executor/executor.go:21
github.com/Dreamacro/clash/hub/executor.Parse(0x1a, 0x8e877d, 0xb)
	/home/comzyh/go/src/github.com/Dreamacro/clash/hub/executor/executor.go:16 +0x8b
github.com/Dreamacro/clash/hub.Parse(0xc0000265c0, 0x1a)
	/home/comzyh/go/src/github.com/Dreamacro/clash/hub/hub.go:10 +0x26
main.main()
	/home/comzyh/Projects/clash/main.go:51 +0x105
exit status 2

```

**Comment by Dreamacro** [comment]
对配置的校验在底下 `decoder.Decode`, 但在 `proxyGroupsDagSort` 中进行 check 是不好的，当初看的时候如果看到你对 map 的 `proxies` 有依赖的话，可能就不会合了，如果没有什么好的方法解决这个问题的话，可能会 revert 这个 commit。

**Comment by beyondkmp** [comment]
@comzyh 检测成环的commit, 能列举个成环的配置的吗？proxy group是顺序录入，好像成不了环

**Comment by comzyh** [comment]
> @comzyh 检测成环的commit, 能列举个成环的配置的吗？proxy group是顺序录入，好像成不了环

@beyondkmp 
#89 的主要目的还是允许 `Proxy Group` 前面的组依赖后面的组，从而使得在 UI 中以配置文件中书写的顺序展示 ProxyGroup 成为可能。检测环是附加的功能也是必须的，在 #89 前因为后面的组中 proxies 中的项必须已经出现过，没有检测环的需求。

对于环给出一个例子:
```
'Proxy Group':
  - { name: Proxy1, type: select, proxies: [ "Proxy2"]}
  - { name: Proxy2, type: select, proxies: [ "Proxy1"]}
```
目前 #89 给出报错
> FATA[0000] Parse config error: Loop is detected in ProxyGroup, please check following ProxyGroups: [Proxy2 Proxy1] 

#89 的主要目的体现在
```
'Proxy Group':
  - { name: Proxy1, type: select, proxies: [ "Proxy2"]}
  - { name: Proxy2, type: select, proxies: [ "Proxy" ]}
```

Proxy2 依赖 Proxy1，但是 Proxy1 是后读入的，在 #89 前这是不合法的，但是现在可以处理这种情况。

**Comment by beyondkmp** [comment]
@comzyh 
```yaml
'Proxy Group':
  - { name: Proxy1, type: select, proxies: [ "Proxy2"]}
  - { name: Proxy2, type: select, proxies: [ "Proxy" ]}
```
这个例子解析proxy1的时候会报错，会报找不到proxy2的。所以应该是不存在环的。

**Comment by comzyh** [comment]
> 对配置的校验在底下 `decoder.Decode`, 但在 `proxyGroupsDagSort` 中进行 check 是不好的，当初看的时候如果看到你对 map 的 `proxies` 有依赖的话，可能就不会合了，如果没有什么好的方法解决这个问题的话，可能会 revert 这个 commit。

sort 对 proxies 依赖是必然的，要不然没法确定各个 `ProxyGroup` 依赖关系。
revert 倒是不必，当时设计`proxyGroupsDagSort`这个函数的时候就是 plugable 的，只做一个排序，去掉完全没问题的那种。

考虑未来需求变化，目前没看出各个ProxyGroup 的 Option 不符合 `Proxies []string` 的可能，我觉得可以复用已有 Decoder 然后 check 一下?

顺便，要不要让 `FallbackOption`, `LoadBalanceOption`, `SelectorOption`, `URLTestOption` 都继承一个 `ProxyGroupOption` 之类的东西?
```
type ProxyGroupOption {
	Name    string   `proxy:"name"`
	Proxies []string `proxy:"proxies"`
}
```
或者，排序遇到 proxies 相关问题只报个warning，然后留给后面处理也可以。

**Comment by comzyh** [comment]
> @comzyh
> 
> ```yaml
> 'Proxy Group':
>   - { name: Proxy1, type: select, proxies: [ "Proxy2"]}
>   - { name: Proxy2, type: select, proxies: [ "Proxy" ]}
> ```
> 
> 这个例子解析proxy1的时候会报错，会报找不到proxy2的。所以应该是不存在环的。

#89 就是为了允许这种情况，在 #89 后这种就不会报错了。但是出现了新问题：要处理环

**Comment by Dreamacro** [comment]
fixed
