### ISSUE TITLE
[Feature] <可以提升一下clash的并发能力吗>

### ISSUE THREAD

**Issue by mIgLLL** [Dreamacro/clash#2948]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

目前我在使用海外的ip爬虫，需要挂clash，但线程数一高于8就会导致clash崩溃（全部服务器掉线、全红屏），而且重新开启clash也没法解决，只能重启电脑。我看到代码里clash使用的是queue来进行并发的，能不能再改进一下效率呢？如果能提升到20或者30的话就太好啦！

### 可能的解决方案

我觉得使用queue来进行多线程管理可能太简单了，而且是FIFO的order，是否可以考虑一下乱序的threadpool？

**Comment by techblack** [comment]
重新开启clash没法解决，看起来不像是clash的问题。

**Comment by peanut996** [comment]
和clash没关系 要是并发比8还低 那对于普通用户基本就处于不可用状态了

**Comment by mIgLLL** [comment]
所以是“机场那边ban掉了我吗”，我再试试别的机场。

我开了12个selenium，然后限制每次只能有8个线程进行访问。

**Comment by mIgLLL** [comment]
> 你这是被高防ban了吧。 我100+线程，每个线程一个节点，同时爬一个视频站，跑满千兆都没红过。

能细说一下怎么设置一个线程一个节点吗？谢谢

**Comment by mIgLLL** [comment]
> > 能细说一下怎么设置一个线程一个节点吗？谢谢
> 
> 最简单的方法，建立一个 group 让每个新进来的连接使用不同的节点。 round-robin 套两层，先优先选择不同机场防止被ban，后同一机场内不同地区节点防止复用。
> 
> 如果想要控制一个线程始终使用同一节点就比较麻烦了，建议从 process-name 下手。

谢谢，我找到了一个“负载均衡”的方法[https://jiasupanda.com/clash-load-balance](url)来实现每次的请求依次使用不同的节点

然后我通过diff删掉了一些ping值一直都不太好的节点，现在已经成功把浏览器访问需求分布到不同节点上了，感恩！
