### ISSUE TITLE
[Feature] Allow Lan Bind 网卡IP 本机127.0.0.1无法访问

### ISSUE THREAD

**Issue by QYG2297248353** [Dreamacro/clash#2949]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

相关问题：https://github.com/Dreamacro/clash/issues/2893#issue-1858111857
回复中未解决实际使用需求

![image](https://github.com/Dreamacro/clash/assets/56836951/e27268ab-5630-4eb1-a76b-0913fa6b4f2e)
配置中只允许单个网卡实现
![image](https://github.com/Dreamacro/clash/assets/56836951/653705f2-4c1e-4410-a5df-020ec6ae7c2b)
我想允许部分网口允许访问同时不影响本机127.0.0.1
经过试验开启allow-lan: true后
指定网卡Ip后127.0.0.1:7890就无法访问，指定127.0.0.1，其他网卡均无法访问(相当于allow-lan: false)

修改DHCP server 影响的服务太多，要改的太多，有的地方还只能是碰到了才知道哪里要改
我希望：
开启 Allow Lan后不影响127.0.0.1本机访问
或
绑定ip允许使用 ',' 分割 实现多个网卡绑定

_Originally posted by @QYG2297248353 in https://github.com/Dreamacro/clash/issues/2893#issuecomment-1738355987_
            

### 可能的解决方案

开启 Allow Lan后不影响127.0.0.1本机访问
或
绑定ip允许使用 ',' 分割 实现多个网卡绑定

**Comment by fakeboboliu** [comment]
目前来看这样改 bind-address 的话有一系列用到这个东西的地方需要修改，
我暂时无法理解这样做的必要性，就不帮忙 PR 了。

但是不改的话或许可以考虑一个 IP 起一个实例，
这样还方便根据不同的网卡来源分流，都不用另加规则了（
