### ISSUE TITLE
[Feature] <标题> 关于一些使用clash的gui的开源建议

### ISSUE THREAD

**Issue by unknownUser99999** [Dreamacro/clash#2955]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

我觉得既然他用了你的开源代码，那我觉得有必要让他的gui代码也开源。因为我觉得如果不开源的话，很难保证安全性。就比如clash for windows
我是这样觉得的，反正作者是有权利让使用他的开源clash核心代码的人开源gui的，就看你们怎么觉得了

### 可能的解决方案

禁止非开源gui的安全隐患。

**Comment by pinguo-chenhuaibing** [comment]
good idea

**Comment by xuhaoyang** [comment]
问题别人也没用开源core啊

**Comment by AkariiinMKII** [comment]
cfw使用的是闭源内核clash premium

**Comment by unknownUser99999** [comment]
> 问题别人也没用开源core啊

对，我刚发现，所以散了吧，不过安全性保证不了就是了

**Comment by pinguo-chenhuaibing** [comment]
> 问题别人也没用开源core啊

但是介绍里面写的：A Windows/macOS/Linux GUI based on Clash and Electron.没有说是用：clash premium

**Comment by AkariiinMKII** [comment]
> > 问题别人也没用开源core啊
> 
> 但是介绍里面写的：A Windows/macOS/Linux GUI based on Clash and Electron.没有说是用：clash premium

不用premium core哪来的tun和rule provider呢

**Comment by xuhaoyang** [comment]
想etc怎么都能从字字句句中，etc起来。没意思

**Comment by unknownUser99999** [comment]
> etc

什么意思

**Comment by moleoxa** [comment]
gui 使用的是 api 和 binary 交流，闭源使用开源 core 都没问题，人家完全可以说他发布的只是“壳”

**Comment by unknownUser99999** [comment]
> gui 使用的是 api 和 binary 交流，闭源使用开源 core 都没问题，人家完全可以说他发布的只是“壳”

你开心就好

**Comment by Anonyame** [comment]
所以今天CFW删库跑路了。
