### ISSUE TITLE
建议：退出APP的时候，自动关闭系统代理。

### ISSUE THREAD

**Issue by ZWWBOSS** [Dreamacro/clash#2977]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

1. 经过多次的测试， 如果程序正在使用系统代理（system proxy）， 然后直接退出APP，会导致PC内的部分APP会出现无法连接网络的问题。

所以我希望在APP退出的时候能够自动关闭系统的代理。这样不会影响到系统内的其他APP的联网功能。
特别是小白在使用的时候，偶尔使用翻墙， 然后没关闭，直接关了机，就很容易出现联网问题， 其他人也不好找问题所在。
（测试APP： Epic Game Launcher， Figma）

**Comment by kkocdko** [comment]
这种东西没办法做，因为系统代理的配置是没有历史记录的，盖上去之后就不知道之前是什么了。强行要做的话弄个文件记录覆盖之前的值看似能解决，但不要忽略，系统代理中途也可能被手动修改，于是就会出现退出的时候被盖回去的反直觉情况。

小白就应该直接使用 tun 模式。tun 模式无需任何手动配置，而且退出之后设备被下掉自然就恢复回去了。

**Comment by elonsky** [comment]
这个个人感觉没太大必要折腾，使用场景不一样。在有些场景下希望APP意外退出的时候能保持网络状态

**Comment by ZWWBOSS** [comment]
原来如此， 感谢各位的耐心回复
