### ISSUE TITLE
[Feature] 希望能够加入针对子目录的规则支持

### ISSUE THREAD

**Issue by Sharuru** [Dreamacro/clash#2980]
### 先决条件

- [X] 我了解这里是 Clash 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/Dreamacro/clash/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 

### 描述

假设有一个站点的网址是 `www.example.com`，希望能够提供一种方式使 `www.example.com/good` 走规则 A，`www.example.com/bad` 走规则 B。

目前 Clash 提供的规则关键字中似乎没有支持这样的功能，尝试用 Script 实现，但是发现 host 拿到的依然只有域名。
能够理解如果加入了类似的匹配规则可能会造成额外的访问故障，但是仍然希望作者能够考虑以下，谢谢！

### 可能的解决方案

- 提供一个比如 `SUBDIR` 之类的关键词满足功能。
- `DOMAIN-SUFFIX` 之类的关键词允许使用比如：`DOMAIN-SUFFIX,example.com/good,RULE_A` 的方式来满足功能。
- 在 Script 提供的变量中加入一个比如 `full_path` 之类的新属性以满足功能。

**Comment by iKira** [comment]
https://github.com/Dreamacro/clash/issues/2811#issuecomment-1608814136

**Comment by Sharuru** [comment]
> [#2811 (comment)](https://github.com/Dreamacro/clash/issues/2811#issuecomment-1608814136)
> url 级别需要 mitm，这不在目前的 clash roadmap 内。
