### ISSUE TITLE
在Windows下clash dns无法监听非53端口

### ISSUE THREAD

**Issue by vibbow** [Dreamacro/clash#299]
如果 clash dns 监听在非 53 端口，虽然端口可以监听成功，但是所有查询均失败（无论是通过本机查询，还是通过局域网其他电脑查询）。

只要让 clash dns 监听在 53 端口，则查询无任何问题。

在 Linux 下监听非53端口则没有任何问题。

---

Clash 版本：
Clash for Windows 0.7.7 自带 clash

clash-win64.exe -v
Clash unknown version windows amd64 unknown time

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/64852922-ee934c00-d64c-11e9-91d5-340b7cb199e3.png)

这边测试是没问题的，建议你下载0.7.6版本再尝试，这个0.7.7对TAP做了一些更改（下版本回退）可能会影响到DNS查询

**Comment by vibbow** [comment]
奇怪了，我dns部分是这样设定的：

···
dns:
  enable: true
  enhanced-mode: redir-host
  listen: :55443
  nameserver:
    - 114.114.114.114
···

看网络里clash已经在监听55443端口
查询的响应是这样的

···
nslookup
默认服务器:  MI-R3G.lan
Address:  192.168.123.1

> server 127.0.0.1
默认服务器:  localhost.localdomain
Address:  127.0.0.1

> set port=55443
> baidu.com
服务器:  localhost.localdomain
Address:  127.0.0.1

*** localhost.localdomain 找不到 baidu.com: No response from server
···

**Comment by Fndroid** [comment]
nslookup 似乎某些版本是没有 ``set port=xxx`` 这个设置的，但是用 WSL 的 dig 命令是没问题的
