### ISSUE TITLE
macOS Siri&App Store issue

### ISSUE THREAD

**Issue by Tsahao** [Dreamacro/clash#3]
1. some app can't be download. There are listed as follow:
https://itunes.apple.com/cn/app/spark-love-your-email-again/id1176895641?l=en&mt=12
https://itunes.apple.com/cn/app/toolbox-for-keynote-templates/id582635628?l=en&mt=12
https://itunes.apple.com/cn/app/autodesk-sketchbook/id863486266?l=en&mt=12

I was told: Unexpected Error.We could not complete your purchase.

Even if I change my config to only "FINAL,,DIRECT", it still doesn't work.

2. Siri would response connection error.

**Comment by Dreamacro** [comment]
测试了一下的确是这样，会想办法解决这个问题

**Comment by Dreamacro** [comment]
`dev` 分支已经修复了这个问题，会在下个版本合到主分支中。

产生的原因是 `RoundTrip` 函数请求错误的原因，现在整个 HTTP 代理改成了从 TCP 层直接转发。

顺便解决了 Firefox 的一个小坑。
