### ISSUE TITLE
软件卡死求解

### ISSUE THREAD

**Issue by jiaxiaoyang** [Dreamacro/clash#303]
我买的新xx节点挂上会有崩溃的问题，不知道怎么回事
日志：
panic: runtime error: slice bounds out of range [:877] with capacity 517
goroutine 11308 [running]:
bytes.(*Buffer).ReadFrom(0xc001210cd8, 0x9adae0, 0xc0001ded80, 0x409bdc, 0x886140, 0x8d41e0)
	/usr/local/go/src/bytes/buffer.go:209 +0x1b9
crypto/tls.(*Conn).readFromUntil(0xc001210a80, 0x2bb4f98, 0xc0003c4930, 0x5, 0xc0003c4930, 0xc000f97a18)
	/usr/local/go/src/crypto/tls/conn.go:802 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc001210a80, 0xc000f97c00, 0x5c59a6, 0xc001210c48)
	/usr/local/go/src/crypto/tls/conn.go:609 +0x12b
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).readHandshake(0xc001210a80, 0xc000463c16, 0xc000463c80, 0x106, 0x180)
	/usr/local/go/src/crypto/tls/conn.go:993 +0x74
crypto/tls.(*Conn).clientHandshake(0xc001210a80, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:171 +0x1a4
crypto/tls.(*Conn).Handshake(0xc001210a80, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1362 +0x132
net/http.(*persistConn).addTLS.func2(0x0, 0xc001210a80, 0xc0000a54a0, 0xc0013a7bc0)
	/usr/local/go/src/net/http/transport.go:1401 +0x49
created by net/http.(*persistConn).addTLS
	/usr/local/go/src/net/http/transport.go:1397 +0x1b1

**Comment by Dreamacro** [comment]
系统 平台 版本

**Comment by jiaxiaoyang** [comment]
win10，clash for windows，0.7.8最新版
