### ISSUE TITLE
arch linux 启动报错

### ISSUE THREAD

**Issue by rogerogerogeroger** [Dreamacro/clash#304]
➜  bin ./clash -d ~/.config/clash/                              
INFO[0000] Can't find MMDB, start download              
FATA[0001] Parse config error: Proxy Auto: The number of proxies cannot be 0

**Comment by Dreamacro** [comment]
查看你配置文件中的 Proxy Group `Proxy Auto`

**Comment by thank243** [comment]
心疼大佬，每天还要处理这种低级问题。

**Comment by 2567366108** [comment]
> 心疼大佬，每天还要处理这种低级问题。

你狠牛逼吗？

**Comment by thank243** [comment]
> > 心疼大佬，每天还要处理这种低级问题。
> 
> 你狠牛逼吗？

有没说你，你激动个p。家里待久了，脑子长蛆了？

**Comment by zhanghg1983** [comment]
各位大佬，我用的是manjaro 的xcfe，然后软件管理用的是networkmanager-applet，代理里面没有手动项目，clash没法启动系统代理，应该怎么配置clash，帮忙指点一下，谢谢
