### ISSUE TITLE
clash udp透明代理出现问题

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#305]
我试图在linux搭建透明代理作为网关翻墙，tcp的透明代理已经可以正常的使用，但是udp的我按照搜索到的方法
```
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -A PREROUTING -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A PREROUTING -p udp -j TPROXY --on-port 12345 --tproxy-mark 1
```
开启代理之后，我并不知道如何测试是否能够使用，但是steam无法正常登录（提示连接服务器失败）`iptables -t mangle -F` 后就恢复正常，是否clash本身不支持udp，还是配置文件中需要添加额外的选项开启？

**Comment by Dreamacro** [comment]
#234 另外不支持 tproxy != 不支持 udp
