### ISSUE TITLE
GEOIP规则问题

### ISSUE THREAD

**Issue by ted423** [Dreamacro/clash#309]
103.224.182.251 无论百度还是https://www.maxmind.com/en/geoip-demo
查询都是在澳大利亚
但是判定却在US里。
GEOIP,US,DIRECT 就走direct
选走代理就走代理

**Comment by Dreamacro** [comment]
https://ipip.net 里是 US, 另外 mmdb 版本可能会造成误差

**Comment by ted423** [comment]
> https://ipip.net 里是 US, 另外 mmdb 版本可能会造成误差

了解了，另外log里能不能把GEOIP的名字带一下？不然找起来有点不方便
