### ISSUE TITLE
V2Ray动态端口支持

### ISSUE THREAD

**Issue by WeirdoShaw** [Dreamacro/clash#31]
希望能添加V2Ray动态端口支持。

**Comment by Dreamacro** [comment]
不会做太多比较不常用的功能，比如 `WireGuard`、`动态端口` 之类的。而且 v2ray 的 `mKCP` 其实和 ss 用的 `KCP` 有着一些差别，暂时不是很愿意去做这些 ROI 比较低的东西

**Comment by nesnode** [comment]
希望能支持 vmess 协议的动态端口。

**Comment by w526433357** [comment]
附议，希望可以支持动态端口。谢谢。

**Comment by WritingWithFire** [comment]
附议，动态端口其实很常用的

**Comment by xmapst** [comment]
附议，动态端口其实很常用的
