### ISSUE TITLE
server not working with go-shadowsocks2: relay error: EOF

### ISSUE THREAD

**Issue by lonelykid** [Dreamacro/clash#312]
It's getting lots of errors like this with this fork.
2019/09/20 07:55:07 relay error: EOF.

with the official fork at shadowsocks/go-shadowsocks2. it's not getting EOF. Instead, it's getting lots of timeout, which is ignored by default.
2019/09/20 07:44:35 tcp.go:87: relay error: read tcp 127.0.0.1:7891->127.0.0.1:65062: i/o timeout

The server is redirecting to the actual ss server; working fine with shadowsocks-libev. I have another server of my own directing traffic with rinetd; it has no problem. Any clue on this? I'm switching from shadowsocksx-ng to clashx. But things is not working right. Thank you!

**Comment by Dreamacro** [comment]
plz show your config.yaml and server params

**Comment by lonelykid** [comment]
Thank you for your reply. The thing is I don't know how they redirect traffic to another server. I have no problem when I use rinetd myself. If you would like, I could send you the server info so you could give it a try.

**Comment by BirkhoffLee** [comment]
Close due to inactivity
