### ISSUE TITLE
fallback、url-test  BUG

### ISSUE THREAD

**Issue by ne1llee** [Dreamacro/clash#313]
fallback或url-test 模式中，如果有某个节点没有测速成功并且结果不是fail的时候，fallback、url-test会优先选择这类节点，最终导致上不了网。

**Comment by Dreamacro** [comment]
> 没有测速成功并且结果不是 fail

是什么意思

**Comment by ne1llee** [comment]
比如说我有10个节点 第一个节点一直没有速度，这两种模式都会选到没有速度那个节点上去

**Comment by cjjdaq** [comment]
对，最近经常遇到。明明那个节点已经挂掉了。但是不知道url-test为什么还会选择挂掉的那个节点。

**Comment by HppZ** [comment]
我这里好像也有问题，设置 url test 后就连不上了。

**Comment by NV3S** [comment]
> 对，最近经常遇到。明明那个节点已经挂掉了。但是不知道url-test为什么还会选择挂掉的那个节点。

对 还有urltest长时间停留在高延迟的节点

**Comment by Dreamacro** [comment]
maybe fixed in latest dev
