### ISSUE TITLE
在 fake-ip 模式下请求 AAAA 记录不应该返回 ipv4 地址

### ISSUE THREAD

**Issue by vibbow** [Dreamacro/clash#314]
![QQ截图20190921003152](https://user-images.githubusercontent.com/6408107/65343381-722dd980-dc07-11e9-8bf8-6728bada47e0.png)

Clash 在 fake-ip 模式下，请求 AAAA 记录时依然返回了 IPv4 地址，这个是不符合预期的，会导致有外网 IPv6 地址的 Windows 无法正常处理所有 dns 请求，除非强行指定 IPv4 模式。

重现版本：b76737b

**Comment by Dreamacro** [comment]
fixed in latest dev
