### ISSUE TITLE
一些小疑问 以及一个建议

### ISSUE THREAD

**Issue by ted423** [Dreamacro/clash#315]
我用的Clash for windows

有时候会遇到一个网站先是打不开，然后刷新下可以正常连接,后面就正常了，并且此时代理似乎没有报错
举例，网站是www.beitai.pt(有时候别的网站也会遇到)
首先这个网站是直连可以访问的，走代理是因为我遇到了一些连接性的问题。

log长这样

`
time="2019-09-21T16:19:58+08:00" level=info msg="127.0.0.1 --> 91.108.56.140 match GEOIP using Proxy[极游A-HK]"
time="2019-09-21T16:19:58+08:00" level=info msg="127.0.0.1 --> 91.108.56.140 match GEOIP using Proxy[极游A-HK]"
time="2019-09-21T16:19:59+08:00" level=info msg="127.0.0.1 --> bolt.dropbox.com match DomainSuffix using Proxy[极游A-HK]"
time="2019-09-21T16:20:00+08:00" level=warning msg="dial DIRECT error: dial tcp 91.108.56.140:80: i/o timeout"
time="2019-09-21T16:20:00+08:00" level=warning msg="dial DIRECT error: dial tcp 91.108.56.140:80: i/o timeout"
time="2019-09-21T16:20:00+08:00" level=warning msg="dial DIRECT error: dial tcp 91.108.56.140:443: i/o timeout"
time="2019-09-21T16:20:00+08:00" level=warning msg="dial DIRECT error: dial tcp 91.108.56.140:80: i/o timeout"
time="2019-09-21T16:20:01+08:00" level=info msg="127.0.0.1 --> 91.108.56.140 match GEOIP using Proxy[极游A-HK]"
time="2019-09-21T16:20:01+08:00" level=info msg="127.0.0.1 --> 91.108.56.140 match GEOIP using Proxy[极游A-HK]"
time="2019-09-21T16:20:01+08:00" level=warning msg="dial DIRECT error: dial tcp 91.108.56.140:443: i/o timeout"
time="2019-09-21T16:20:01+08:00" level=warning msg="dial DIRECT error: dial tcp 91.108.56.140:80: i/o timeout"
time="2019-09-21T16:20:39+08:00" level=info msg="127.0.0.1 --> d.dropbox.com match DomainSuffix using Proxy[极游A-HK]"
time="2019-09-21T16:20:57+08:00" level=info msg="127.0.0.1 --> bolt.dropbox.com match DomainSuffix using Proxy[极游A-HK]"

time="2019-09-21T16:21:27+08:00" level=info msg="127.0.0.1 --> www.beitai.pt match DomainSuffix using Proxy[极游A-HK]"
time="2019-09-21T16:21:42+08:00" level=info msg="127.0.0.1 --> 182.254.116.117 match GEOIP using DIRECT"
time="2019-09-21T16:21:58+08:00" level=info msg="127.0.0.1 --> d.dropbox.com match DomainSuffix using Proxy[极游A-HK]"
`
上面的log中间拿掉了内网域名
另一个问题
GEOIP我只设了
  - GEOIP,GB,Proxy
  - GEOIP,NL,Proxy

其他geoIP包括US都是走的DIRECT，但不知道为什么 91.108.56.140 先走代理 然后又跑去直连 
是否GEOIP 有点不大稳定，并且是否会影响性能？因为我印象里我的Firefox用pac就因为使用dnsResolve导致了正常网页的加载问题。

另一个就是在clash for windows的issue里提到的 
~~https://github.com/Fndroid/clash_for_windows_pkg/issues/204~~

我的理解Clash没法按应用走规则，不知道我的理解是否有误？
以下的提议是根据上面的疑问，如果我的理解有误可以跳过。
首先部分应用会使用多个端口，所以SRC-PORT似乎不太好用。
希望能增加个全局代理的端口设置，走这个可以让整个应用全走代理从而绕过clash的规则，因为像Dropbox和telegram这些应用是需要全局走代理的，相比dropbox还好，telegram的连接是IP，规则写起来比较麻烦，而且我觉得应用直接全局会省些CPU？另一方面，我有时候验证网站是被墙了还是挂了还是连代理无法访问会切全局代理或直连，但如果直接在Clash里切势必会影响到别的应用。

**Comment by BirkhoffLee** [comment]
關於你的問題，中間有沒有切換節點？
有其他問題麻煩另外開 issue。

**Comment by ted423** [comment]
> 關於你的問題，中間有沒有切換節點？
> 有其他問題麻煩另外開 issue。

好像在某次更新后没在出现，我都忘了有这个issue了
