### ISSUE TITLE
Disabling multiplexing (aka "mux=0")

### ISSUE THREAD

**Issue by Dukewill** [Dreamacro/clash#316]
Is it possible to introduce a new parameter which can deactivate multiplexing for the latest v2ray-plugin? e.g. "mux=0"

This new function would make it easier to build a general platform (ss + v2ray-plugin)  on server side for different clients.

Thanks quite a lot!

FYR: https://github.com/shadowsocks/v2ray-plugin/pull/123

**Comment by Dreamacro** [comment]
have implemented in the latest dev branch
