### ISSUE TITLE
FR: Tray icon upload/download activity indicators and latency indicator

### ISSUE THREAD

**Issue by feidaman** [Dreamacro/clash#318]
As a former user of Shadowsocks for Windows, I miss the network activity indicators on the tray icon. They are a good way to judge whether the current server is 'good' or 'bad'. Alternatively, 
 a 5 segment indicator on the tray icon could be used to indicate latency, so users can quickly diagnose connection  issues.

Here are some icon ideas:

![Icon ideas](https://user-images.githubusercontent.com/11704566/65383473-a5c44d00-dd48-11e9-8cb9-a4d0785fc071.png)

The bottom icon shows latency (orange), upload speed (green) and download speed (red).

Maybe the icon thing could be optional. For clarity, I propose getting rid of the cat icon when the indicators are enabled.

Thanks!

**Comment by Dreamacro** [comment]
clash aims to provide a cross-platform command-line binary. your requirement should implementation with a GUI wrapper.
