### ISSUE TITLE
FR: Ability to switch servers from the tray menu

### ISSUE THREAD

**Issue by feidaman** [Dreamacro/clash#319]
It would be nice to be able to switch profiles and servers directly from the tray icon menu, without having to open the app. Ideally the active profile server list should be on the top menu level to make switching quicker.

Shadowsocks for Windows had this feature though the server list was in a SUBmenu which is not as convenient as the top-level menu, but still convenient.

Thank you!

**Comment by Dreamacro** [comment]
duplicate with #318
