### ISSUE TITLE
[Feature Request] 追加本地网络分配的dns

### ISSUE THREAD

**Issue by tete1030** [Dreamacro/clash#323]
Hi, 我刚开始使用clash，不太熟悉，所以这个建议可能已经有了。

我希望的功能和Surge中能够指定“system”作为dns server一样，相当于在dns server列表中自动追加系统被分配的dns。

因为我本地网络是校园网，使用了多个ISP的混合线路，校内提供的DNS会优化线路，并且响应延迟更低，因此希望能在dns中加入校园网的dns（连上校园网后会自动通过dhcp分配）。可是当我切换到其他网络时，我又不希望该dns server继续在列表中。所以“system”选项就可以实现这种需求。

**Comment by Dreamacro** [comment]
启动时读取一遍都不是难事，但网络变动了呢，clash 不会监听任何系统变化

**Comment by tete1030** [comment]
以后会不会考虑监听这些变化？或者允许外部应用触发网络更新事件。这样也方便今后实现network-specific的规则
不过这种需求确实小众了点

**Comment by Dreamacro** [comment]
不会，因为跨平台的话，这种东西实现起来挺脏的。。。

**Comment by comzyh** [comment]
@tete1030 
network-specific 的规则挺有吸引力的，比如放在手机上不同wifi不同策略。不过这个东西应该让客户端实现更好

**Comment by happyeddie** [comment]
很期待这个功能，在办公网尤其有用
不知道为什么，公司把一些职能内网访问的域名，做了外网解析，但外网是访问不了的……
