### ISSUE TITLE
timeout parameter unused

### ISSUE THREAD

**Issue by tslling** [Dreamacro/clash#328]
Hi, I use this api("/proxies/:name/delay") to get delay of proxy, but the provided```timeout``` is ignored and the real timeout is always five seconds. This API works only when clash managed to get the delay in five seconds.
It looks this is the related code:
https://github.com/Dreamacro/clash/blob/c38469330dac9f2dd23f76a234957a51808e17db/adapters/outbound/base.go#L160-L163

If I provide a timeout shorter than five seconds, I can not get this test terminated early because ```p.Dial``` is stuck.
If I provide a timeout longer than five seconds, this test won't last longer because ```p.Dial``` just returns after five seconds.

**Comment by Dreamacro** [comment]
`Dial` context is under development.
