### ISSUE TITLE
Wait() of picker lost error info

### ISSUE THREAD

**Issue by tslling** [Dreamacro/clash#329]
```Wait()``` in picker just returns a ```interface{}```
https://github.com/Dreamacro/clash/blob/c38469330dac9f2dd23f76a234957a51808e17db/common/picker/picker.go#L37
 in this case we can not tell if the common task succeed or not, we now check the returned ```interface{}``` is nil or not to guess the task is succeed or not.
https://github.com/Dreamacro/clash/blob/c38469330dac9f2dd23f76a234957a51808e17db/dns/resolver.go#L189-L192
https://github.com/Dreamacro/clash/blob/c38469330dac9f2dd23f76a234957a51808e17db/hub/route/proxies.go#L120-L125
This will not always work, also we lost detailed error info. IMO, including an ```err``` member in picker to explicitly specify this task is succeed or not will be clearer. 

BTW, the following ```Picker``` is initialized without ```cancel```, this seems to be a bug.
https://github.com/Dreamacro/clash/blob/c38469330dac9f2dd23f76a234957a51808e17db/common/picker/picker.go#L30-L33

**Comment by Dreamacro** [comment]
#326

**Comment by tslling** [comment]
#326 does not intent to solve the first problem. I mean a more explicit error info, for example, let ```Wait``` returns an ```error```:

```go
func (p *Picker) Wait() (interface{}, error)
```

so we can do this:
```go
if ele, err := picker.Wait(); err != nil{
    // do some thing
}
```
instead of this:
```go
ele := picker.Wait()
if ele != nil{
    // do some thing
}
```

**Comment by comwrg** [comment]
Each task may have an error, so this means may not only one error.
You mean if all task failed, return the first task error, or?

**Comment by tslling** [comment]
> Each task may have an error, so this means may not only one error.
> You mean if all task failed, return the first task error, or?

returning a random one is acceptable, since ```picker``` is used to do a **common** task, those errors are likely to be similar.

**Comment by Dreamacro** [comment]
fixed in https://github.com/Dreamacro/clash/commit/5c03613858be0a494ddb42a511a065c890c7ac86
