### ISSUE TITLE
规则支持从文件读取

### ISSUE THREAD

**Issue by lizhaode** [Dreamacro/clash#33]
比如domain proxy 这种的规则，有可能是非常多的，如果全写在默认的配置文件中，显得有点太重了，维护不够方便。希望能像SpechtLite那样，支持从文件中读取规则

**Comment by Dreamacro** [comment]
@zwpaper 规则和代理以及代理组实际上是强相关的，所以分开反而增加了心智负担

**Comment by blackteajing** [comment]
因为最近正在试着用php合并规则，这个事挺麻烦的，毕竟各种维护的很不错的规则项目里代理和代理组也都是随个人习惯起名，有人叫auto有人叫url-test,有人叫PROXY，也有人叫proxy.... 肯定能调整好，毕竟就是来来回回改数组就是了，但是不太容易找到通用规律。

**Comment by Dreamacro** [comment]
会在实现 rule-set 的时候支持

**Comment by dcy10000** [comment]
@Dreamacro 希望能早日支持。因为一般的配置文件由服务商提供。如果把个人想要自定义的规则写在里头。会导致下次更新配置文件时被覆盖。
希望支持的功能：也就是提供一个单独的用户 Rule 文件。这里的 Rule 规则优先级高于config.yml里面的 Rule 就行

**Comment by BirkhoffLee** [comment]
I'll leave further discussion to #272. This will be closed after the feature is implemented.

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium 实现了部分规则集功能
