### ISSUE TITLE
泡芙云Linux安装失败-log-level=info: command not found

### ISSUE THREAD

**Issue by hosea7456** [Dreamacro/clash#331]
hosea@hosea:~/clash$  ./clash -d .
INFO[0000] Can't find config, create an empty file      
INFO[0000] Can't find MMDB, start download              
FATA[0003] Parse config error: Proxy Proxy: 'proxies' is not a slice 
hosea@hosea:~/clash$ wget -O config.yml https://www.paofusub.com/link/LmSPnpAqjeCDrCnx?clash=1&log-level=info
[1] 26749

Redirecting output to ‘wget-log’.
log-level=info: command not found
hosea@hosea:~/clash$

**Comment by Dreamacro** [comment]
```
$ wget --content-disposition "https://www.paofusub.com/link/LmSPnpAqjeCDrCnx?clash=1&log-level=info"
```

**Comment by hosea7456** [comment]
已安装成功，谢谢！@Dreamacro

**Comment by MartinPeng7** [comment]
大佬们，请问泡芙云使用官方提供的 config.yml 配置文件后，报如下错误：
`FATA[0023] Parse config error: ProxyGroup Proxy: 'proxies' is not a slice `
该问题怎么解决呢？配置文件的标准格式是怎样的？

**Comment by Dreamacro** [comment]
@MartinPeng7 看 README.md

**Comment by XiaoZiYuan** [comment]
> 大佬们，请问泡芙云使用官方提供的 config.yml 配置文件后，报如下错误：
> `FATA[0023] Parse config error: ProxyGroup Proxy: 'proxies' is not a slice `
> 该问题怎么解决呢？配置文件的标准格式是怎样的？

朋友,你解决这个问题了吗

**Comment by FanZhenQuan** [comment]
@MartinPeng7  你好，请问这个问题你解决了吗？官方给的配置文件一直报错。readme里面的模板也有问题！

**Comment by morangeous** [comment]
显然，这是那些机场主为了省事，直接抄过来的clash linux教程，配置文件中没有任何节点的信息，根本不能用。
solution：在windows下配置一遍，一般windows下的配置文件是能用的，找到配置文件，我的配置文件在c:/users/your-user-name/.config/clash/yml下，找到最新的yml文件，将linux下的yml文件中proxies字段以下的内容全部用从windows中得到的配置文件的对应部分替换，保存之后重新启动clash。通过访问http://clash.razord.top/#/proxies 而不是127.0.0.1:9090来更换proxy，更换完成之后应该就可以使用了。
