### ISSUE TITLE
Recommended configuration rule for gfw please

### ISSUE THREAD

**Issue by suntong** [Dreamacro/clash#333]
Hi, 

It is widely understood that we use clash for gfw, so use this issue tracker for user-contributed rule for gfw please, as everyone new to this will be benefit from it.

I.e., please reply with your rule configuration for gfw please. 
And I volunteer to compile everyone's reply together in this OP. 
Thanks.

**Comment by BirkhoffLee** [comment]
There are other repositories for the rules, for example https://github.com/Hackl0us/SS-Rule-Snippet. Please do understand this issue tracker is only for bug reports, feature requests or questions. However I'll leave this issue open and everyone will still be able to comment.
