### ISSUE TITLE
How to use clash

### ISSUE THREAD

**Issue by suntong** [Dreamacro/clash#334]
Can somebody explain, very briefly, how to use clash practically please?

Let me start with my understanding:

- prepare `$HOME/.config/clash/config.yaml` file with the following content:

```
# port of SOCKS5
socks-port: 7891

# set log level to stdout (default is info)
# info / warning / error / debug / silent
log-level: info

dns: # custom dns setting
  enable: true # set true to enable dns (default is false, use system dns)

Proxy:

# shadowsocks
# The types of cipher are consistent with go-shadowsocks2
# support AEAD_AES_128_GCM AEAD_AES_192_GCM AEAD_AES_256_GCM AEAD_CHACHA20_POLY1305 AES-128-CTR AES-192-CTR AES-256-CTR AES-128-CFB AES-192-CFB AES-256-CFB CHACHA20-IETF XCHACHA20
# In addition to what go-shadowsocks2 supports, it also supports chacha20 rc4-md5 xchacha20-ietf-poly1305
- { name: "ss1", type: ss, server: server, port: 443, cipher: AEAD_CHACHA20_POLY1305, password: "password", udp: true }

```

- start `clash` in terminal by simply run `clash`, or daemonize it with `pm2 start clash`. 
  * ss-local, simple-obfs, v2ray-plugin and v2ray-core are not required.
  * need to do `sudo clash` only if you use the lower port.

- configure you browser to socks5 localhost:7891, and start browsing.

Is that so? 
Have I misread or missed anything (apart from rule configuration which is covered in #333)? 

Please help.
And I volunteer to compile everyone's reply together in this OP.
Thanks.

**Comment by Dreamacro** [comment]
> start clash in terminal by simply run clash, or daemonize it with pm2 start clash. Q1:, no need to start sslocal on your own, right? Q2: do I need sudo clash?.

ss-local simple-obfs v2ray-plugin v2ray-core is not required.

need `sudo` if you use the lower port

dns for custom dns setting, `enable: false` use system dns

**Comment by suntong** [comment]
Thanks @Dreamacro, OP updated as per new input.

**Comment by suntong** [comment]
Oh, by "_lower port_" you meant ports with numbers 0–1023, i.e., the [system or well-known ports](https://en.wikipedia.org/wiki/Registered_port), right?

**Comment by BirkhoffLee** [comment]
Yes. Gotta close this now, reopen if you have any further concerns.
