### ISSUE TITLE
对504等代理返回，clash没有正确判断为代理不可用

### ISSUE THREAD

**Issue by cindymao56** [Dreamacro/clash#335]
使用fallback模式时，http代理返回带html内容的504错误时，clash误判这个代理可用

**Comment by Dreamacro** [comment]
理论上不会，health check 是通过这个代理去请求一个 url，并判断这个 url 是否返回 < 400

**Comment by cjjdaq** [comment]
但是在用auto的时候，日志里会提示504，但不会立刻切换其它正常线路去。

**Comment by Dreamacro** [comment]
Fixed in latest dev
