### ISSUE TITLE
希望控制API可以修改策略组和代理规则

### ISSUE THREAD

**Issue by tossp** [Dreamacro/clash#339]
非常感谢clash项目
无聊重写了一套dashboard

希望可以添加修改config.yml的相关api，这样就可以不用在路由器上手动改配置或者更新出口节点了

演示地址：
国内 http://app.tossp.com
github 镜像 http://app.gh.tossp.com

![image](https://user-images.githubusercontent.com/2138631/66097531-4fb99a00-e5d1-11e9-8b5f-6957766968cf.png)

![image](https://user-images.githubusercontent.com/2138631/66097570-6fe95900-e5d1-11e9-9843-e3ca40b02dde.png)

**Comment by Dreamacro** [comment]
直接改动配置文件这个东西其实比较糟糕
* go 目前的 yaml 库应该不能保持原配置文件的注释、空行或者 json 结构。
* proxy 的删除会有级联操作的业务逻辑
* rule 目前是一个数组，所有增删改查比较繁琐，需要用 index

所以目前 clash 只提供了热更整个配置文件的方法

**Comment by comwrg** [comment]
个人觉得把还是要增加文件包含的功能
比如像`nginx`的`conf`中的包含是这样的`include servers/*;`
实现也并没有任何难度

**Comment by cjjdaq** [comment]
文件包含功能好，配置操作更灵活。

**Comment by tossp** [comment]
@Dreamacro 热更整个配置文件的方法提供了吗？没找到接口呢？

**Comment by Dreamacro** [comment]
@tossp https://clash.gitbook.io/doc/restful-api/config

**Comment by tossp** [comment]
@Dreamacro 
我查看了 https://github.com/Dreamacro/clash/blob/d3c50cf89fb74f02e91211226009a2cd924a72ec/hub/route/configs.go#L24-L32

好像没有找到获取原始配置文件和热更整个配置的相关接口

**Comment by luvletter2333** [comment]
> 直接改动配置文件这个东西其实比较糟糕
> 
> * go 目前的 yaml 库应该不能保持原配置文件的注释、空行或者 json 结构。
> * proxy 的删除会有级联操作的业务逻辑
> * rule 目前是一个数组，所有增删改查比较繁琐，需要用 index
> 
> 所以目前 clash 只提供了热更整个配置文件的方法

我认为是否可以临时更新/添加Rule呢？每次需要临时增添Rule都得断开已有连接，还得重启
