### ISSUE TITLE
GEOIP,HK和GEOIP,TW几乎不生效

### ISSUE THREAD

**Issue by Howard-00** [Dreamacro/clash#343]
我希望连接港台服务器时使用港台的节点，然后添加了对应的规则
- GEOIP,HK,Proxy-hk
- GEOIP,TW,Proxy-tw
但是根据日志来看该规则几乎没有生效过

**Comment by soffchen** [comment]
举例说明哪几个 ip 段？你先用 ip 去查 geoip 是属于哪个国家代码的，再确定是否 clash 的问题。

**Comment by h0wardch3ng** [comment]
https://en.wikipedia.org/wiki/Anycast
