### ISSUE TITLE
rule模式无法连接ssh

### ISSUE THREAD

**Issue by CavalloneChen** [Dreamacro/clash#346]
当使用全局代理，并且配合 ```Proxycommand nc -X 5 -x 127.0.0.1:7891 %h %p```，我能够成功通过终端ssh连接到服务器，但是设置成代理模式后，我写了```DOMAIN,xxx.xxx.xxx.xxx,Proxy```这样的规则，却无法ssh连接上服务器，同时log告诉我 ```[warning] dial DIRECT error: dial tcp xxx.xxx.xxx.xxx:22: i/o timeout```

**Comment by Dreamacro** [comment]
规则写前边

**Comment by CavalloneChen** [comment]
问题解决了，是我规则没有写对，应该写成 ```IP-CIDR, xxx.xxx.xxx.xxx/22,Proxy```
