### ISSUE TITLE
可以支持对配置文件进行加密，防止泄露节点信息吗

### ISSUE THREAD

**Issue by Howard-00** [Dreamacro/clash#348]

**Comment by Dreamacro** [comment]
能说的详细点吗

**Comment by Howard-00** [comment]
> 能说的详细点吗

现在的clash配置文件都是明文的文本文件，可以直接从中读取到节点信息。有没有可能对这些信息加密，防止泄露

**Comment by Dreamacro** [comment]
我认为没有太大意义

**Comment by Dreamacro** [comment]
想要没有明文的配置文件可以从空配置文件打开，调用 API 发送新的配置。加密这个功能没有太大意义。如果有异议再打开这个问题
