### ISSUE TITLE
Documentations for REST API

### ISSUE THREAD

**Issue by balthild** [Dreamacro/clash#35]
I'm developing a proxy tool for GNU/Linux based on Clash, which would call the REST API.

Currently, I could know about the API by reading source codes, but it will be better if there're some documentations.

**Comment by Dreamacro** [comment]
Here is the API doc: https://clash.gitbook.io/doc

**Comment by balthild** [comment]
Thanks. And, maybe it should be referred in README.md.

**Comment by Dreamacro** [comment]
README.md will not be too detailed for reasons well known to all. 😶

**Comment by beyondkmp** [comment]
GUI in linux is awesome. I'm looking forward to it.
