### ISSUE TITLE
HTTPS代理不可用

### ISSUE THREAD

**Issue by codehz** [Dreamacro/clash#351]
具体配置形如
```yaml
{ name: "cf-https", type: http, server: <域名H>, port: <端口P>, username: "<用户名>", password: "<密码>", tls: true }
```
日志如下
```
level=warning msg="Proxy[target] connect [127.0.0.1 --> www.google.com] error: <IP>:<端口P> connect error"
```
而在命令行使用
```
https_proxy=https://<用户名>:<密码>@<域名H>:<端口P> curl -o /dev/null https://www.google.com
```
可以正常下载，而且代理连接http时也能用

**Comment by Dreamacro** [comment]
仅支持 CONNECT 的隧道，你的 https 代理是吗

**Comment by codehz** [comment]
不支持CONNECT的话命令行也没法连接 https://www.google.com 啊
具体方法是在远程直接使用v2ray建立http inbound并绑定至0.0.0.0，然后通过Cloudflare Spectrum技术的TCP隧道配合EDGE TLS Terminate实现连接

**Comment by codehz** [comment]
下面是curl的日志
<details>
* Rebuilt URL to: https://google.com/
*   Trying ***...
* TCP_NODELAY set
* Connected to *** (***) port * (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Proxy certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jan 13 00:00:00 2019 GMT
*  expire date: Jan 13 12:00:00 2020 GMT
*  subjectAltName: host "***" matched cert's "***"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
* allocate connect buffer!
* Establish HTTP proxy tunnel to google.com:443
* Proxy auth using Basic with user 'test'
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> Proxy-Authorization: Basic dGVzdDp0ZXN0
> User-Agent: curl/7.58.0
> Proxy-Connection: Keep-Alive
> 
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.google.com
*  start date: Sep 17 13:30:43 2019 GMT
*  expire date: Dec 10 13:30:43 2019 GMT
*  subjectAltName: host "google.com" matched cert's "google.com"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x558436c10580)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: google.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 301 
< location: https://www.google.com/
< content-type: text/html; charset=UTF-8
< date: Fri, 11 Oct 2019 06:28:10 GMT
< expires: Sun, 10 Nov 2019 06:28:10 GMT
< cache-control: public, max-age=2592000
< server: gws
< content-length: 220
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
< 
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection #0 to host *** left intact
</details>

**Comment by Dreamacro** [comment]
给一份 V2ray 的配置方便复现

**Comment by codehz** [comment]
```
{
"inbounds": [{
  "protocol": "http",
  "listen": "0.0.0.0",
  "port": 8889,
  "settings": {
    "accounts": [{"user": "codehz", "pass": "boom"}]
  }
}],
"outbounds": [{
  "protocol": "freedom",
  "settings": {
    "timeout": 30
  }
}]
}
```
然后TLS不是在V2ray这一层处理的，而是在Cloudflare Spectrum (标准的cloudflare似乎不支持代理)
基本就是这样，没测试直接http的，等会我测试下）

**Comment by Dreamacro** [comment]
v2ray 好像处理 CONNECT 有点问题，我直接搭了个 HTTP 的好像不支持 CONNECT

```
$ curl -x 'ip:port' -v https://google.com
```

**Comment by codehz** [comment]
（

> v2ray 好像处理 CONNECT 有点问题，我直接搭了个 HTTP 的好像不支持 CONNECT
> 
> ```
> $ curl -x 'ip:port' -v https://google.com
> ```

用https_proxy环境变量，不要用x选项

**Comment by abae136ab** [comment]
有结果了吗？也想用https代理，ss和vmess封锁太严重了。

**Comment by codehz** [comment]
@abae136ab 别想多了，https代理仅仅只能当做备用，延迟高加速度慢以及没证据表明更安全

**Comment by beyondkmp** [comment]
> v2ray 好像处理 CONNECT 有点问题，我直接搭了个 HTTP 的好像不支持 CONNECT
> 
> ```
> $ curl -x 'ip:port' -v https://google.com
> ```

我这边测试好像没有问题，直接用他的配置搭建的http代理

**Comment by Dreamacro** [comment]
close because of long time no response

**Comment by nightamber** [comment]
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/26924871/156807796-cde2b1bc-6031-448c-91fe-a93673ab838a.png">
我遇到这样的问题 是不是也因为http 不支持
