### ISSUE TITLE
Support shadowsocks behind http proxy or other proxy, make proxy could be joined into a chain

### ISSUE THREAD

**Issue by syhily** [Dreamacro/clash#36]
My company urge us connect to outside network behind a http proxy.
Could clash support proxy chain which would let shadowsocks send its TCP connect through a http proxy.

**Comment by beyondkmp** [comment]
you can use clash and proxifier .

**Comment by Dreamacro** [comment]
I'd consider HTTPS inbound proxy after the implement of `DNS` server and client.

**Comment by bemike** [comment]
> My company urge us connect to outside network behind a http proxy.
> Could clash support proxy chain which would let shadowsocks send its TCP connect through a http proxy.

You might want to try proxychains to work around.

**Comment by syhily** [comment]
> > My company urge us connect to outside network behind a http proxy.
> > Could clash support proxy chain which would let shadowsocks send its TCP connect through a http proxy.
> 
> You might want to try proxychains to work around.

Tks, proxychains could be way to work through, but this would make the connection setting more complex.

**Comment by Dreamacro** [comment]
closed #52

**Comment by syhily** [comment]
I mean, clash has a built-in shadowsocks support. What I need is that the clash's built-in shadowsocks could send its TCP package through a HTTP proxy. This would just like what 
 a proxychains has already do.

@Dreamacro

**Comment by Dreamacro** [comment]
@syhily 
In 0.10.x, clash is already supported HTTP CONNECT proxy, which could send TCP package through the HTTP proxy.

**Comment by beyondkmp** [comment]
you want this? 
```bash
client -> socks -> shadowsocks -> http proxy 
```

**Comment by syhily** [comment]
> you want this?
> 
> ```shell
> client -> socks -> shadowsocks -> http proxy 
> ```

Yeah.

**Comment by NightMachinary** [comment]
Can someone help me with `client -> socks -> shadowsocks -> http proxy `? I live in Iran, and the gov has enacted a super Draconian firewall recently which blocks almost all connections. I have access to a http proxy (not my server) that enables me to escape the new firewall, but the old firewall (which is still quite aggressive) is still there. I want to be able to connect my shadowsocks server (which is located in UK and is accessible from the said http proxy.).

If someone has any ideas on how I can ssh via this http proxy, that works, too. I tried `ssh ... -o 'ProxyCommand /usr/local/bin/corkscrew proxy_ip 80 %h %p ~/.auth'` but it failed with `Proxy could not open connnection to %h:  Proxy Authentication Required`.

**Comment by Dreamacro** [comment]
@NightMachinary if your http proxy is CONNECT method, you can use http proxy client in clash. And set `ProxyCommand nc -X 5 -x 127.0.0.1:7891 %h %p` to your ssh config.
