### ISSUE TITLE
hosts如何起作用

### ISSUE THREAD

**Issue by trott90** [Dreamacro/clash#363]
配置文件如下
hosts:
  'adashx.m.taobao.com': 0.0.0.0
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 1.2.4.8
    - 114.114.114.114

但windows下用nslookup的时候，返回的还是实际的IP

nslookup adashx.m.taobao.com 127.0.0.1
服务器:  localhost
Address:  127.0.0.1

非权威应答:
名称:    adashx.m.taobao.com.gds.alibabadns.com
Address:  140.205.252.97
Aliases:  adashx.m.taobao.com

**Comment by Dreamacro** [comment]
hosts 不影响 dns, 也不修改系统 hosts，只在经过 clash 的流量中起作用

**Comment by Dreamacro** [comment]
close because of long time no response
