### ISSUE TITLE
dns ipv6的问题

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#366]
我使用透明网桥来翻墙，通过在网桥中执行
```
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
```
来劫持dns使用clash的dns解析，我的上级路由器（是联通网关）开启了ipv6，我试图通过将clash里dns中的ipv6设为false来避免电脑使用ipv6的地址（翻墙服务器不支持ipv6），但是依然clash的dns依然会解析出ipv6的地址，这使得有一部分支持ipv6的网站无法翻墙。
![image](https://user-images.githubusercontent.com/6771700/67097358-835d0c80-f1ec-11e9-925e-2befd6027a8a.png)
解析出的地址中除了ipv6的地址都是可以使用的，在翻墙的vps中wget可以正确的获得网页的信息。

**Comment by cjwddtc** [comment]
我尝试在win10下关闭ipv6协议栈，即可正确联网，但是似乎clash里dns的配置并不符合预期，即使关闭ipv6，dns依然会下发ipv6的地址。

**Comment by Dreamacro** [comment]
dns 中的 ipv6 设为 false 不能避免电脑使用 ipv6 的地址，因为他并不改变 dns server 的行为。这个字段的作用在于经过 clash 的流量在请求时不使用 v6 地址

**Comment by comzyh** [comment]
> dns 中的 ipv6 设为 false 不能避免电脑使用 ipv6 的地址，因为他并不改变 dns server 的行为。这个字段的作用在于经过 clash 的流量在请求时不使用 v6 地址

这样的吗，原来我一直也理解错了。这确实有点 confusing，毕竟 ipv6 选项是在 DNS 下面的。
