### ISSUE TITLE
请问大佬的clash电报群如何加入？

### ISSUE THREAD

**Issue by zxlhhyccc** [Dreamacro/clash#367]

**Comment by Dreamacro** [comment]
maybe it does not exist.

**Comment by FromTG** [comment]
纸飞机有两种类型的群组——公共群组和私人群组。
公共组可以根据可用性具有管理员所需的自定义URL。如果您知道群组名称的用户名或相关字符，则可以找到公共 Telegram 群组。这里有一个导航群 @sobaidu  先点击右上角放大镜然后输入前面的字符 里面收集了一些优质的纸飞机群
除非您被邀请添加，否则您无法搜索或加入私人群组。因此，您是否可以加入完全取决于群组的创建者或管理员。私人群组通常有很长的复杂 URL，您需要共享这些 URL 以邀请新成员。
