### ISSUE TITLE
[Feature request]DNS服务支持TCP

### ISSUE THREAD

**Issue by cindymao56** [Dreamacro/clash#368]

**Comment by Dreamacro** [comment]
有什么是需要 tcp dns server 的吗

**Comment by cindymao56** [comment]
网络有时udp不通，qos
有tcp就好了

**Comment by Dreamacro** [comment]
如果是在公网部署 dns server 的话建议使用其他专门用来做 dns server 的软件

**Comment by cindymao56** [comment]
我试过了用dnsmasq，把它的上游dns设置为clash.
不过，用tcp连接dnsmasq时，dnsmasq也用tcp去向上游查询

有什么建议没

**Comment by comzyh** [comment]
这个 feature 我做过，当时主要是因为 UDP DNS truncated 时，客户端会选 TCP 重试。

现在即使增加了 UDPsize (#139)，偶尔也会有这个问题，但是还不知道原因。

**Comment by cindymao56** [comment]
对了，还有，如果我用专门软件做dns，转发到clash，那clash收到的lookup from 127.0.0.1，那根据域名分流的规则还能生效吗？

**Comment by comzyh** [comment]
> 对了，还有，如果我用专门软件做dns，转发到clash，那clash收到的lookup from 127.0.0.1。实际连接的IP又是另一个。那根据域名分流的规则还能生效吗？

能的
