### ISSUE TITLE
please support ssR and kcp in vmess

### ISSUE THREAD

**Issue by mizhewei** [Dreamacro/clash#37]
please support ssR and kcp in vmess
I want to unblock Netflix, but my vpn is only for ssr or kcp in vmess.
Would you plan to add these?

**Comment by Dreamacro** [comment]
clash would **not** support ssr.

as for kcp, the vmess use mkcp, which is different from kcp in ss. so the plan to support kcp will come after the other features are done.

**Comment by mizhewei** [comment]
thank you for replying, looking forward to it

**Comment by aunhappy** [comment]
any progress?

**Comment by jinva** [comment]
any progress?
