### ISSUE TITLE
v2ray-plugin mux 好像有问题

### ISSUE THREAD

**Issue by XGFan** [Dreamacro/clash#370]
服务端使用 **go-shadowsocks2** + **v2ray-plugin** (https://github.com/shadowsocks/v2ray-plugin)
客户端使用 **clash**

由于v2ray-plugin默认开启`mux=1` ，所以在clash设置`mux:true`

**代理访问http内容正常。https就出错。**

日志等级设置为debug，但没有什么有价值的信息。

只有在服务端设置`mux=0`，
并且在clash设置`mux:false`
才能正常使用。

BTW: 使用go-shadowsocks2 作为client一切正常，服务端也使用了let's encrypt签发的有效证书
```
./shadowsocks2-macos -c 'ss://chacha20-ietf:password@my.domain.com:8443' -socks :1080 -verbose --plugin v2ray-plugin  --plugin-opts "tls;host=my.domain.com"
```

**Comment by fishg** [comment]
这个mux不准备支持https了吗？
