### ISSUE TITLE
期待机场能提供图形化的策略组/规则管理

### ISSUE THREAD

**Issue by Alifather** [Dreamacro/clash#371]
目前在用一个Clash的机场托管的规则只能用表达式追加规则，既不能修改也不能删减，很纳闷，要是有像Windows客户端那样的图形化管理就太好了，能否把节点订阅和规则托管分开，提供第三方托管服务让所有机场的节点都可以直接订阅规则

**Comment by KinsonSiu** [comment]
&若当前节点失效时自动切换切换至策略组中的其他节点，不知道这些需求是客户端开发者就可以做到还是需要原作的更新？

**Comment by jinzhuming** [comment]
> &若当前节点失效时自动切换切换至策略组中的其他节点，不知道这些需求是客户端开发者就可以做到还是需要原作的更新？

事实上现在是有这个功能的，auto-test 我记得就是这样，自动测速选择最快的，当然这个最快的必须要能链通，另外 fall-back 应该也是会避开失效节点。
关于你说的订阅和规则分开，官方目前好像不支持这个功能，之前有看到说在实现某个功能的时候可能会添加，不过我自己在做的一个客户端在尝试做这个功能，如果客户端作者想添加，应该是有办法的，比如分别解析两个配置文件，取其中一个的规则，另一个的节点，生成一个新的配置文件，这样就做到了你说的订阅和规则分开，但是目前几个客户端的作者可能因为工作量或者其他实现方面的困难没有添加这个功能。

**Comment by Alifather** [comment]
> > &若当前节点失效时自动切换切换至策略组中的其他节点，不知道这些需求是客户端开发者就可以做到还是需要原作的更新？
> 
> 事实上现在是有这个功能的，auto-test 我记得就是这样，自动测速选择最快的，当然这个最快的必须要能链通，另外 fall-back 应该也是会避开失效节点。
> 关于你说的订阅和规则分开，官方目前好像不支持这个功能，之前有看到说在实现某个功能的时候可能会添加，不过我自己在做的一个客户端在尝试做这个功能，如果客户端作者想添加，应该是有办法的，比如分别解析两个配置文件，取其中一个的规则，另一个的节点，生成一个新的配置文件，这样就做到了你说的订阅和规则分开，但是目前几个客户端的作者可能因为工作量或者其他实现方面的困难没有添加这个功能。

我在Windows、Android、KoolClash端都没有找到auto-test，是都还没做么？如果要把规则和订阅分开，是不是应该还需要有人出来建立平台负责更新，我觉得像ABP那样有官方平台可以让用户选择规则去更新很好

**Comment by wjx0912** [comment]
@Alifather 
README.md 里面 name: "auto"     type: url-test
不就是你需要的吗？

**Comment by Dreamacro** [comment]
close because of no response for a long time
