### ISSUE TITLE
几种出错，甚至程序死掉

### ISSUE THREAD

**Issue by Justsoos** [Dreamacro/clash#377]
clashX 1.16.4  macos 10.13.6 v2ray
发现：
1，配置内有特殊符号，比如★
2，proxies 里有名字重复的
3，proxy：name 有重复的

类似全局，如果恰好有两个名字一样，程序就无法使用了。这个……
程序无法使用，无法进入设置，严重的情况下，无法重启，只能重装（也许是 config.yaml 不会被重置的原因，必须手动删除）

另，`https://tgbot.lbyczf.com/v2rayn2clash?url=`
这个在线转换服务不知道是谁做的，也没有考虑如上的问题，转出来的名字带特殊符号，名字重复
@yichengchen

**Comment by Dreamacro** [comment]
2 3 是 feature

**Comment by Justsoos** [comment]
这个 feature 是为了强调机场运营能力，并淘汰没有设置开发人员的不合格机场？ 
哈哈

**Comment by Dreamacro** [comment]
配置有问题不让跑有问题吗? 有问题还让跑才是大问题吧. 另外 emoji 都能存在, 不存在有特殊符号不让使用的.

**Comment by Justsoos** [comment]
问题是，config.yaml 配置文件（我没直接用过 clash，只用过clashx）多个配置逻辑是使用同命名空间，如果不同机场，不同订阅之间有重复，是很大可能的，而且只是使用 markdown（假设我没看错）语法作配置文件，这个…… 太凶险了吧，md 的语法，控制字符的奇葩，根本不适合作配置文件啊，这些都并非用户之错，用户也很难纠正和发现。
用户，开发者，机场之间，总要有背锅的，选谁呢？
哈哈，这真是个世纪难题

**Comment by Dreamacro** [comment]
多个配置直接不互相影响. 配置文件是 yaml 🤪. blame 之前记得先了解清楚.

**Comment by Justsoos** [comment]
呵呵，我只记得，这是第一次装软件，不得不崩溃后第二次卸载的。作者和程序都很强大，不敢blame，哈哈

**Comment by yichengchen** [comment]
请提供崩溃log

**Comment by Justsoos** [comment]
@yichengchen @Dreamacro 有劳了，作其他需求，系统卸了，有机会再说。
目前用 v2rayN，对重复名字，有特殊字符，重复标记，ss混排订阅，乱入订阅导入都没问题。
![image](https://user-images.githubusercontent.com/3480043/67569525-ac881a80-f761-11e9-95fb-802614eedf6c.png)

**Comment by Justsoos** [comment]
https://github.com/Fndroid/jsbox_script
哦，找到了，原来你在这藏着呢
 @Fndroid 
从你 js 那转换了v2ray 的订阅，生成的 config.yaml 没有去重复名字，导入到clashx里就造成了程序死锁。
两边都没责任，用户不知所措啊。哈哈哈

**Comment by yichengchen** [comment]
辛苦了 希望再也没有机会

**Comment by Justsoos** [comment]
会的，这里已经涉及到三个领域分工的开发者，谁都不背锅。
这事儿还会发生的。哈哈～

**Comment by Justsoos** [comment]
![image](https://user-images.githubusercontent.com/3480043/67571849-8d8c8700-f767-11e9-92ee-8316f3856e6e.png)

@Fndroid  你不露这一小手，我还找不到你呢。哈哈

**Comment by Justsoos** [comment]
其实是四个产品，v2rayX也有类似名字空间 bug，而且提示非常不明显。
开源社区的问题整合是个经常有机会碰面的大故事 @yichengchen  即便关了 issues 也会的 哈～

**Comment by Fndroid** [comment]
> ![image](https://user-images.githubusercontent.com/3480043/67571849-8d8c8700-f767-11e9-92ee-8316f3856e6e.png)
> 
> @Fndroid 你不露这一小手，我还找不到你呢。哈哈

我点这个只是觉得你这段话说得有点莫名其妙，并且多数内容都不对。建议你稍微了解清楚一下软件再做反馈可能会比较好。

> 从你 js 那转换了v2ray 的订阅，生成的 config.yaml 没有去重复名字，导入到clashx里就造成了程序死锁。

名字重复无法转换说明API不能符合你的要求，建议你自行编写一个再做转换。目前这个接口做不到帮你筛选要删掉哪些节点。

**Comment by Justsoos** [comment]
@Fndroid  我并没有说是你一个人背锅，这个问题本应是机场主、订阅制造人的锅。
但这个流程导致用户用不了的问题，目前就是「三不管」领域。
四个软件/产品，围绕 v2ray 的一个订阅如何解读造成的协议混乱。
本来不是大事儿，但目前看，越是产业链越长，越容易出现各种没法分锅的现象。

**Comment by Fndroid** [comment]
> @Fndroid 我并没有说是你一个人背锅，这个问题本应是机场主、订阅制造人的锅。
> 但这个流程导致用户用不了的问题，目前就是「三不管」领域。
> 四个软件/产品，围绕 v2ray 的一个订阅如何解读造成的协议混乱。
> 本来不是大事儿，但目前看，越是产业链越长，越容易出现各种没法分锅的现象。

我认为你搞错了这个前提，v2ray官方并没有任何关于“订阅”的说明文档，所以讨论结束

**Comment by willww64** [comment]
@Dreamacro @yichengchen @Fndroid 我一个旁观者看了都有点来气，这人除了阴阳怪气给别人添堵外不会干别的了，这种人以后理都不要理。你们为开源贡献真是辛苦了。

**Comment by Justsoos** [comment]
现在这个时代还有程序员不作 name 空间检查导致 bug，还有脑残后面捧臭脚。你们这社区也就这点水平了

**Comment by willww64** [comment]
> 现在这个时代还有程序员不作 name 空间检查导致 bug，还有脑残后面捧臭脚。你们这社区也就这点水平了

你是真够无聊的。是不是正常说话的话会浑身发痒，非得阴阳怪气才舒服？想解决问题的话，好好提意见，或者你能力可以，可以提 Merge Request，如果作者不接受，你可以 fork 一个自己开发。喷别人前，好好照照镜子，你嘴比人家脚还臭。就此打住，懒得回你了。
