### ISSUE TITLE
请问树莓派应该选择哪个版本

### ISSUE THREAD

**Issue by Aithosa** [Dreamacro/clash#378]
你好，我希望在树莓派设备上运行clash，release里有一些arm的文件，请问哪一个可以用？

* `clash-linux-armv5-v0.16.0.gz    3.14 MB`
* `clash-linux-armv6-v0.16.0.gz    3.13 MB`
* `clash-linux-armv7-v0.16.0.gz    3.13 MB`
* `clash-linux-armv8-v0.16.0.gz    3.08 MB`

请问是不是还和树莓派的版本有关？我的设备是raspberry pi zero。

**Comment by lddsb** [comment]
这个跟你的CPU有关

**Comment by ntgeralt** [comment]
你谷歌一下会找到 v6 v7

**Comment by wuyouning** [comment]
树莓派4 用armv7
zero就不知道了，你用命令行查一下
