### ISSUE TITLE
fake-ip: AAAA 记录应该用一个IPv6 的 IP 池

### ISSUE THREAD

**Issue by h0cheung** [Dreamacro/clash#379]

**Comment by Dreamacro** [comment]
现在的应用都是双栈的 拿不到 v6 ip 自然会请求 v4 难道有那种直连 v6 的应用？

**Comment by TMily** [comment]
为了避免NAT并启用UDP我连接公司电脑的RDP使用的DDNS是只有AAAA记录的,启用增强模式会导致这样的连接直接失败~~

**Comment by comzyh** [comment]
我觉得要不 IPv6 暂时直接返回真实 IP？

**Comment by TMily** [comment]
或者根据规则将直连域名的解析正常返回

**Comment by xiaomingplus** [comment]
同求

**Comment by ic0xgkk** [comment]
这个IPv6支持能做的，最近正好也在找能和BGP联合的方案，fakeip如果能返回IPv6地址的话，可用的池子能大很多（就是可能得考虑一下LRU的gc了），转化到其他场景上也会更有价值。ss的redir本质上就是把流拷贝到另外一个流去（其他协议我估计应该差不多吧），头部填上地址端口，让remote帮它发起连接，所以这种模式的经常会出现session timeout，但是在路由器上，一个session在被各种手段redirect（好比iptables）之后，PC到路由器的是一个会话，路由器会重新发起一个新的session用于转发流到服务器。所以，在PC这一侧，不论是v4还是v6都是没问题的，域名和原本正确的IP能关联好就行了，但是直接访问IP肯定就是不行的了。

**Comment by Dreamacro** [comment]
@ic0xgkk 如果你需要可以单开一个 issue 说明一下你目前的使用场景，以及为什么需要 ipv6
