### ISSUE TITLE
[Feature Request] bootstrap DNS

### ISSUE THREAD

**Issue by h0cheung** [Dreamacro/clash#380]
希望增加单独的bootstrap DNS，只用来解析DoH和DoT自身的域名，在DNS全部为DoH或者DoT时可以避免出现问题。（cloudflare的DNS可以直接通过https://1.1.1.1/dns-query访问，但是国内的rubyfish等似乎没有对IP地址申请证书，只能使用域名）

**Comment by Dreamacro** [comment]
麻烦编辑好标题和正文，不要用一句话表述

**Comment by Dreamacro** [comment]
`default-nameserver` implementated
