### ISSUE TITLE
如果我想用终端也走代理 我应该如何设置http_proxy

### ISSUE THREAD

**Issue by boyandtoy** [Dreamacro/clash#384]

**Comment by Dreamacro** [comment]
export https_proxy=http://127.0.0.1:7890;export http_proxy=http://127.0.0.1:7890;export all_proxy=socks5://127.0.0.1:7891

**Comment by PYMAQ** [comment]
请问怎么设置配置文件才能在macos（m1）终端中直接git clone github的链接，而不是每次要下载都要复制这一串“export https_proxy=http://127.0.0.1:7890;export/ http_proxy=http://127.0.0.1:7890;export/ all_proxy=socks5://127.0.0.1:7891”。
我的需求是：直接在配置里面设置好https_proxy等，然后终端这边直接git clone就行了。请问有大神能教教吗？
目前的配置文件是yaml的。
<img width="920" alt="image" src="https://user-images.githubusercontent.com/30351634/154045605-987db6ee-5c85-4dae-bf62-48678b24b24c.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/30351634/154045650-33e462b1-cdcb-4158-8bba-181b863212e3.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/30351634/154045722-f7e131e3-5000-482c-b8bd-c01dc2e26df9.png">

不知道具体要怎么输入才行？请问有大佬有空指点一下吗？

**Comment by biggbuddy** [comment]
> 

1. export https_proxy=http://127.0.0.1:7890;export/ http_proxy=http://127.0.0.1:7890;export/ all_proxy=socks5://127.0.0.1:7891
把这一串命令放到你的终端初始化配置文件里面, 比如如果你用的是bash, 那么可以把它放到 ~/.bashrc 文件的最后面, 这样每次打开终端, 也就把这一行命令初始化好了
2. 有clash客户端本来就支持增强模式, 你可以找找看, 貌似叫 ClashX? 
3. 在自己连接的网络上游, 部署梯子, 比如搞一个软路由, 里面装个openwrt之类的, 直接在openwrt里面配置科学上网, 这样也就在实现所有的客户端都自带梯子, 不再在客户端搞什么了
