### ISSUE TITLE
是否可以支持 TPROXY

### ISSUE THREAD

**Issue by kuyagic** [Dreamacro/clash#387]
是否能支持 TPROXY 方式得 tcp 和 udp 代理功能.

**Comment by Dreamacro** [comment]
tproxy 比较适合 udp 吧

**Comment by kuyagic** [comment]
没错 说是这么说 但是 都支持TPROXY的话 切换软件也比较方便.... 可以mangle 表里建立n个软件对应的chain....

**Comment by techblack** [comment]
redir 能有TPROXY udp支持就太好了，路由上透明就很方便了

**Comment by maskedeken** [comment]
> 
> 
> 没错 说是这么说 但是 都支持TPROXY的话 切换软件也比较方便.... 可以mangle 表里建立n个软件对应的chain....

[https://github.com/Dreamacro/clash/pull/1049](https://github.com/Dreamacro/clash/pull/1049)
