### ISSUE TITLE
redir-host透明代理无法翻墙

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#388]
似乎是更新到0.16版本之后，使用redir-host模式翻墙就会出现问题，比如youtube网站能打开，但是视频永远都加载不出来，直接使用socks5代理就能够正确地翻墙，使用fake-ip也可以正确的翻墙，但是redir-host就会出现这种诡异的错误，还有比如我直接wget www.google.com 发现解析出的是错误的地址，而使用nslookup www.google.com 却能够解析出正确的地址。刷新dns缓存后依然如故。

**Comment by Dreamacro** [comment]
是 ipv6 问题吗
