### ISSUE TITLE
openclash下配置问题

### ISSUE THREAD

**Issue by SinTod** [Dreamacro/clash#389]
问题一：
在fakeip模式下由于所有域名解析都由clash返回fakeip，所以导致配置的openvpn域名也返回了198网段的ip导致连接失败。（临时修改配置文件为IP解决），问下这种情况有没有办法使用配置解决？

问题二：
访问控制问题，之前koolss的访问控制功能 比如某个主机不走代理，现在openclash可以通过SRC-IP-CIDR配置实现，但是之前的只代理端口这个功能可否用配置实现呢？想实现80,443端口根据规则判断，其他端口直连，看了文档找到了下面两个配置。
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)
这两个配置可以实现对端口的配置，不过我想设置非80,443的话是要把所有端口都生成一条规则么。这样的话配置可能要上万条。。。看了下surge的文档是支持NOT逻辑的，不知道clash是否支持。

btw，数据目标端口和数据源端口不太清楚什么意思，请问可以帮忙解释下吗 谢谢啦~

**Comment by Dreamacro** [comment]
问题一：找 openclash repo 提 issue
问题二：就是目标端口和来源端口

```
- DST-PORT,80,DIRECT 
- DST-PORT,443,DIRECT 
```

没有 NOT 逻辑，或许之后的 rule script 会解决各种逻辑问题

**Comment by SinTod** [comment]
可能理解错了- - 我的意思是只有80 443 走规则判断 其余端口直连这样

**Comment by Dreamacro** [comment]
```
- DST-PORT,80,Proxy
- DST-PORT,443,Proxy
```

**Comment by SinTod** [comment]
这样的加就是 80 443 都PROXY了呀 不能分流
应该是 NOT DST-PORT,80，443,DIRECT
我还是先等等 rule script 的feature吧~~
谢谢啦
