### ISSUE TITLE
关于socks5/http代理认证配置

### ISSUE THREAD

**Issue by abae136ab** [Dreamacro/clash#394]
如果开启socks5/http代理认证，需要在Profiles里自建或者订阅的配置文件内加入
#authentication of local SOCKS5/HTTP(S) server
authentication:
- “username:password"
开启用户名密码认证，然而clash代理端口的配置又存在于general YML配置文件内，能否把这部分合并到general YML内，这样Profiles里配置文件更新订阅就不会把认证配置更新没了。
port: 7890
socks-port: 7891
#authentication of local SOCKS5/HTTP(S) server
authentication:
- “username:password"

现在每次更新profiles里的配置文件，都需要重新编辑加入认证配置，比较麻烦，请考虑能否更改认证配置的位置？谢谢！

**Comment by BirkhoffLee** [comment]
這個問題不隸屬於 Clash core 的處理範圍，請詢問衍生版的作者
