### ISSUE TITLE
[Feature Request] 增添端口段Rule

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#395]
clash作为网关透明代理时，适用于需要访问Gdrive的主机上同时有BT下载等不适合整个`SRC-IP`都`DIRECT`的场景下，将BT客户端连接发起端口限定在某个范围内，例如`SRC-PORT,45678-56789,DIRECT`，如果使用现有的Rule似乎需要添加很多行，即使对性能的影响不大，类似的重复规则也完全毫无意义且不够优雅。
  
翻了翻历史issue，似乎没找到相关的内容，因此单独开了一个功能请求，如有遗漏还望指出。我能想到把BT流量过滤出来的方法只能是通过源端口了，不知是否还有其它解决方案，另外 #272 是否能顺便解决这一场景下的需求？

**Comment by Dreamacro** [comment]
所有复杂的带有条件的规则都交给 #272

**Comment by comzyh** [comment]
现在用 redir 模式的时候，我用 iptables 过滤目标端口号，你也可以暂时用这个方案。

我现在也比较好奇有什么好方法阻断 BT

**Comment by Mosney** [comment]
> 现在用 redir 模式的时候，我用 iptables 过滤目标端口号，你也可以暂时用这个方案。
> 
> 我现在也比较好奇有什么好方法阻断 BT

没办法根据目标端口号过滤，因为其他peer的端口号是不可预料的，只能在像qb这种能控制发起连接的端口范围的客户端上可以通过过滤来源端口号来过滤BT流量。阻断BT的话，可能需要DPI之类的吧

**Comment by Dreamacro** [comment]
用 script 控制逻辑的方式解决端口区间问题 https://github.com/Dreamacro/clash/releases/tag/premium
