### ISSUE TITLE
热更新API返回 Configuration file is empty

### ISSUE THREAD

**Issue by nncy** [Dreamacro/clash#397]
**问题描述:**
      在使用重新加载配置这个API的时候，指定一个正常的配置文件，返回 Configuration file xx is empty
**详细信息:**
       linux 拥有两个用户: clash,  l0snight; clash core 是由clash用户启动。
       在l0snight用户下，执行:
`curl -X PUT -d '{"force": true, "path": "/home/l0snight/.config/clash/config.yaml"}' http://127.0.0.1:9090/configs`
       返回: 
`{"message":"Configuration file /home/l0snight/.config/clash/config.yaml is empty"}`
       然而指定的配置文件是可以令clash正常运行的配置文件，不知是否是我操作问题。

**Comment by Dreamacro** [comment]
应该是 `/home/l0snight/.config/clash/config.yaml` 文件没有权限读，当前因为要兼容旧的 `.yml` 后缀，所以可能抛出的错误有些问题

**Comment by Dreamacro** [comment]
另外 force 参数是 querystring，不是 body

**Comment by nncy** [comment]
明白了，谢谢
