### ISSUE TITLE
 is there any way to start without Country.mmdb (for testing)

### ISSUE THREAD

**Issue by ntgeralt** [Dreamacro/clash#399]
Country.mmdb file seems quite large.
 Is there any way to simplify it or without it.

**Comment by Dreamacro** [comment]
Unfortunately, clash depends on `Country.mmdb` in many situations

**Comment by ntgeralt** [comment]
Maybe you can consider one of the options, such as v2ray can run without geoip.dat in lightweight equipment.

**Comment by Dreamacro** [comment]
Yes, but I don't have enough time to do it. 🤦🏻
