### ISSUE TITLE
切换线路浏览器需要重启才能更新

### ISSUE THREAD

**Issue by Tsahao** [Dreamacro/clash#4]
切换到其他线路后 浏览器还是使用旧的IP

clashX 的 set as system proxy 选项重新开启无效

重启 clashX app 有效
重启浏览器有效

系统：macOS Mojave
浏览器 Safari,  Chrome

**Comment by Dreamacro** [comment]
因为在切换模式的时候不会断开现有连接，这个会跟当前连接查看一起做

**Comment by kojirou1994** [comment]
不能加个选项切换服务器的时候强制断开连接吗

**Comment by kamingchan** [comment]
這個在 Surge 3 是 feature 到了 Clash 就成 Bug 了⋯⋯

**Comment by Dreamacro** [comment]
现在有 api 可以主动断开了
