### ISSUE TITLE
规则区分大小写

### ISSUE THREAD

**Issue by bb2** [Dreamacro/clash#40]
发现域名大写就不能被识别了,可以考虑自动转换成小写，或在日志中给出提示

> https://github.com/Fndroid/clash_for_windows_pkg/issues/18#issue-381843080

**Comment by Dreamacro** [comment]
这个应该是浏览器层面的事情，我这里 chrome 会自动转换成小写，另外也没有大写的域名。

**Comment by bb2** [comment]
是啊，正是因为域名没有大写之分，这样的规则写下去就是无效的。所以建议考虑自动把配置文件里的大写域名转换成小写。或在日志中提示有这样一条无效规则。

**Comment by Dreamacro** [comment]
把 `DOMAIN`、`DOMAIN-SUFFIX`、`DOMAIN-KEYWORD` 的输入自动小写化了。

**Comment by yuanli-cn** [comment]
最近发现Freenas安装一些plugin的时候会访问pkg.FreeBSD.org...
