### ISSUE TITLE
我自己搭的，这个怎么配置呢？

### ISSUE THREAD

**Issue by itcodes** [Dreamacro/clash#400]
地址 (Address) =
端口 (Port) = 
用户ID (User ID / UUID) = 
额外ID (Alter Id) = 
传输协议 (Network) = 
伪装类型 (header type) = 
我只有这些信息。然后我怎么配置yaml 呢？？

**Comment by Dreamacro** [comment]
follow `README.md` first, plz

**Comment by itcodes** [comment]
![image](https://user-images.githubusercontent.com/8282645/68830579-02a80800-06e7-11ea-8bf4-2fe6142a0124.png)

**Comment by Dreamacro** [comment]
注释的部分是可选项，根据自己的服务端配置使用

**Comment by itcodes** [comment]
@Dreamacro 我服务端的配置，我第一个里面基本写了。但是这样还是无法连接啊。不知道啥原因。

**Comment by Dreamacro** [comment]
你又没给服务端配置，我怎么知道你用的什么。clash 的 vmess 配置以及很极简了

**Comment by itcodes** [comment]
@Dreamacro 哦哦。我用的是 233 那个一键部署。传输协议用的 tcp_http

**Comment by Dreamacro** [comment]
tcp_http 目前不支持，所有支持的模式 README.md 都写了
