### ISSUE TITLE
ss + v2ray-plugin 设置问题

### ISSUE THREAD

**Issue by MurrddoL** [Dreamacro/clash#402]
shadowsocks.exe  +  v2ray-plugin.exe设置如下，可以正常上外网
地址：xxx.xxx.xxx
端口：443
密码：pwd123
加密：chacha20-ietf
插件：v2ray-plugin
插件选项：tls;host=xxx.xxx.xxx;path=/s
插件参数：fast-open=false

clash 设置如下，不能上外网
- name: "ss_plugin"
  type: ss
  server: xxx.xxx.xxx
  port: 443
  cipher: chacha20-ietf
  password: "pwd123"
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket
    tls: true
    skip-cert-verify: true
    host: xxx.xxx.xxx
    path: "/s"
    mux: true

不知道问题在哪

**Comment by Dreamacro** [comment]
缩进。。。

**Comment by MurrddoL** [comment]
有缩进：
- name: "ss_plugin"
  type: ss
  server: xxx.xxx.xxx
  port: 443
  cipher: chacha20-ietf
  password: "pwd123"
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket
    tls: true
    skip-cert-verify: true
    host: xxx.xxx.xxx
    path: "/s"
    mux: true

**Comment by kenvint** [comment]
我也遇到了，v2ray正常，clash在直接灰不可选
区别只在   ws-path: 
配置        ws-path: /ps

            v2ray正常，clash灰

配置           ws-path: ""

两者都正常

问题不知道怎么解决

**Comment by kzw200015** [comment]
```
{name: xxx, server: xxx.xxx, port: 443, type: ss, cipher: aes-256-gcm, password: xxxxxx, plugin: v2ray-plugin, plugin-opts: {mode: websocket, host: xxx.xxx, path: /ss, tls: true, mux: false}}
```
我也遇到了同样的问题，换用ss+v2ray-plugin没有问题
```
tls;mode=websocket;host=xxx.xxx;path=/ss
```

**Comment by kzw200015** [comment]
> ```
> {name: xxx, server: xxx.xxx, port: 443, type: ss, cipher: aes-256-gcm, password: xxxxxx, plugin: v2ray-plugin, plugin-opts: {mode: websocket, host: xxx.xxx, path: /ss, tls: true, mux: false}}
> ```
> 
> 我也遇到了同样的问题，换用ss+v2ray-plugin没有问题
> 
> ```
> tls;mode=websocket;host=xxx.xxx;path=/ss
> ```

好吧，我的问题是客户端mux没打开，看了一下源码，原来mux是默认开启的

**Comment by MurrddoL** [comment]
> > ```
> > {name: xxx, server: xxx.xxx, port: 443, type: ss, cipher: aes-256-gcm, password: xxxxxx, plugin: v2ray-plugin, plugin-opts: {mode: websocket, host: xxx.xxx, path: /ss, tls: true, mux: false}}
> > ```
> > 
> > 
> > 我也遇到了同样的问题，换用ss+v2ray-plugin没有问题
> > ```
> > tls;mode=websocket;host=xxx.xxx;path=/ss
> > ```
> 
> 好吧，我的问题是客户端mux没打开，看了一下源码，原来mux是默认开启的

在clash 成功配置了ss + v2ray-plugin 么？

**Comment by litebeyond123** [comment]
> > > ```
> > > {name: xxx, server: xxx.xxx, port: 443, type: ss, cipher: aes-256-gcm, password: xxxxxx, plugin: v2ray-plugin, plugin-opts: {mode: websocket, host: xxx.xxx, path: /ss, tls: true, mux: false}}
> > > ```
> > > 
> > > 
> > > 我也遇到了同样的问题，换用ss+v2ray-plugin没有问题
> > > ```
> > > tls;mode=websocket;host=xxx.xxx;path=/ss
> > > ```
> > 
> > 
> > 好吧，我的问题是客户端mux没打开，看了一下源码，原来mux是默认开启的
> 
> 在clash 成功配置了ss + v2ray-plugin 么？

clash的配置和quanmult x基本一致，自测参数照着quanmult x的填写，tls: false, mux: false是可用的，然而这样是不是没有用到v2ray-plugin？

**Comment by xianren78** [comment]
这个问题依然没得到解决

**Comment by ipfans** [comment]
@Dreamacro  看起来这个bug与 https://github.com/Dreamacro/clash/issues/370 这个相关。

我在同样的环境下复现成功

```yaml
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket
      tls: true
      host: lblblbl.com
      path: "/websocket"
      mux: true
```

服务器`v2ray-plugin`同样开启了mux。如果当前设备代理端口为`6890`：

```html
$ https_proxy=http://127.0.0.1:6890 http_proxy=http://127.0.0.1:6890 all_proxy=socks5://127.0.0.1:6890 curl http://www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.hk/url?sa=p&amp;hl=zh-CN&amp;pref=hkredirect&amp;pval=yes&amp;q=http://www.google.com.hk/&amp;ust=1597977406184723&amp;usg=AOvVaw2Z_CCEV2JVer7o_nKWyU8L">here</A>.
</BODY></HTML>

$ https_proxy=http://127.0.0.1:6890 http_proxy=http://127.0.0.1:6890 all_proxy=socks5://127.0.0.1:6890 curl https://www.google.com
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
```

可以复现的条件为：1. 存在websocket Path(服务器server为caddy进行分流)；2. 服务端开启mux，客户端同时开启mux。

如果客户端设置mux为false，则执行该命令会卡住。

**Comment by occamrazor1492** [comment]
I am hitting exactly the same issue on 1.31.3.2 clashX
