### ISSUE TITLE
关于匹配DIRECT规则的连接NAT类型仍为Symmetric的问题

### ISSUE THREAD

**Issue by Cook21** [Dreamacro/clash#403]
平时使用Netch将游戏导向Socks5代理, 以前用ShadowSocks的时候NAT类型一直为FullCone, 最近换用Netch之后发现NAT类型变为最差的Symmetric, 在clash中改为直连之后竟然还是Symmetric而且无论是redir-host还是fake-ip都这样.

**Comment by BirkhoffLee** [comment]
Fixed in #441
