### ISSUE TITLE
更新geoip数据库的接口？我想自己开发个Linux版的QT clash gui，我在帮助文档只发现一些基础api接口来控制clash

### ISSUE THREAD

**Issue by chaichunyang** [Dreamacro/clash#404]
本人想在Linux上面使用clash，不过目前没有找到任何可用的linux版本clash

遂想自行开发一个，我这么做是否要注意一些版权问题？

界面主要借鉴win版本，但是win版本有一个更新geoip数据库的功能

clash是否有一个更新geoip database的接口可供调用？

以上，感谢！

**Comment by Dreamacro** [comment]
clash 遵循 GPL 3.0, 只要开源一般没什么限制

GeoIP 库不需要单独开接口吧，http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz 直接下载这个解压覆盖 Country.mmdb 就行了

**Comment by chaichunyang** [comment]
好的，我看clash启动后，自己下载了一个，以为会有接口。感谢回复！
