### ISSUE TITLE
关于 GEOIP 和 fake-ip 的一个设想

### ISSUE THREAD

**Issue by Howard-00** [Dreamacro/clash#408]
按照目前 Clash 的功能，fakeip 模式下，域名规则可以跳过 DNS，从而避免连接国外 DNS 带来的额外时间开销，但收集大量的国内外域名并不方便。对此，是否可以考虑给 GEOIP 和 MATCH 规则添加一个 save 选项，把域名用文件记录下来，并将记录的结果视为域名规则，下次再访问时便不用进行 DNS 查询。如果记录域名数量过多，可以采用 LRU 逐出。

**Comment by Fndroid** [comment]
DNS本来就已经有缓存了，不是频繁重启都不需要写到本地了

**Comment by Dreamacro** [comment]
现在 fakeip 下域名规则就是跳过 DNS 的，你一定是把 IP 规则写前面了
