### ISSUE TITLE
HTTPS 代理無法使用。

### ISSUE THREAD

**Issue by XiaoTeemo** [Dreamacro/clash#409]
某機場的 HTTPS 伺服器，任何一個節點，使用 1 分鐘後就會出現：

[warning] dial Proxy error: server:443 connect error

如果一直有請求，就一直是這個報錯，斷開 5 分鐘左右再使用又能使用 1 分鐘左右。

Clash/ClashX/Clash for Windows 及它們最近幾個月的版本都有這個狀況。

各種配置文件/DNS 方案試了無效。

用 Surge GOST Quantumult Shadowrocket 連接都沒有問題。

我可以提供節點，幫忙檢查下嗎？

**Comment by Dreamacro** [comment]
那么你要怎么把节点给我呢

**Comment by XiaoTeemo** [comment]
收到後請回覆，準備刪掉這條。感謝！
  - name: "HK"
    username: 156529675
    password: 0n8mHkV44l
    type: http
    server: base64:bjVhZ3U1cGJrLnRyYWRld2luZC5saW5r
    port: 8443
    tls: true
    skip-cert-verify: true
  - name: "TW"
    username: 156529675
    password: 0n8mHkV44l
    type: http
    server: base64:cnB4ZzU0dDV3LnR3LXRmbi5kYXRhcG9ydC54eXo=
    port: 443
    tls: true
    skip-cert-verify: true

**Comment by Dreamacro** [comment]
看起来是连接数过多导致服务端不能及时接受连接，是机场有连接数限制吗

**Comment by XiaoTeemo** [comment]
沒有連接數限制，同一臺機，用 GOST 就很穩定，很多用戶都是這個情況。

**Comment by gamerenzz** [comment]
请问https节点怎么配置？

**Comment by soffchen** [comment]
> 请问https节点怎么配置？

```
  - { name: "xxx", type: http, server: xxxx.net, port: 1234, username: "xxx", password: "xxx", tls: true, skip-cert-verify: true }
```

**Comment by soffchen** [comment]
长期在使用 https，好好的 :)

机场问题的可能性比较大些

**Comment by gamerenzz** [comment]
> > 请问https摘要怎么配置？
> 
> ```
>   - { name: "xxx", type: http, server: xxxx.net, port: 1234, username: "xxx", password: "xxx", tls: true, skip-cert-verify: true }
> ```

好的，谢谢了，

**Comment by XiaoTeemo** [comment]
今天測試了一臺電腦：
ClashX 1.16.7 失敗。
ClashX 1.16.6 幾小時過去了沒問題。

**Comment by XiaoTeemo** [comment]
@Dreamacro 用了 3 小时 ClashX 1.16.6  ，休眠了 3 小时，然后还是挂了。

**Comment by boysye** [comment]
https 用户名和密码为空时如何处理？我把他们注释掉或者留空，启动都显示libclash exits too fast（exist code:1）

**Comment by boysye** [comment]
https 用户名和密码为空时如何处理？我把他们注释掉或者留空，启动都显示错误。

**Comment by CalZzz** [comment]
> 长期在使用 https，好好的 :)
> 
> 机场问题的可能性比较大些

我也在使用題主所說的這個機場。他們的節點用 ShadowRocket / Gost / Quantumult / Surge 連都OK，不會斷線。用瀏覽器插件 SwitchyOmega 也很流暢。

但是用基於 Clash 的各種 GUI 封裝的客戶端，都會出現開了幾個網頁以後就持續連不上的問題。

我可以提供這個機場的節點給您測試。希望作者大佬們能夠看看是什麼情況。

**Comment by CalZzz** [comment]
> 看起来是连接数过多导致服务端不能及时接受连接，是机场有连接数限制吗

我和機場的技術人員確認過，應該是沒有限制連接數。我可以提供節點，以供作者大大測試。

**Comment by CalZzz** [comment]
> 那么你要怎么把节点给我呢

作者大大你用 Telegram 嗎？我在 Telegram 上和你溝通？

**Comment by dodowhat** [comment]
同样的问题+1。我的服务端用的Gost，且是自建服务，也是这个问题。目前的解决方案是在本地又开了一个Gost服务，将远端的https转成本地http代理，然后再用Clash去连接，这是PC上的做法。至于手机上直接用Surge/ShadowRocket/Surfboard了，据了解遇到同样问题的人很多，

**Comment by BirkhoffLee** [comment]
問題還存在嗎？

**Comment by XiaoTeemo** [comment]
> 問題還存在嗎？

正常了
