### ISSUE TITLE
Feature Request: 简化局域网规则

### ISSUE THREAD

**Issue by nobody-65534** [Dreamacro/clash#41]
请问除了使用`IP-CIDR`一条一条的添加外，还有什么更简单的方法可以返回局域网流量吗？

**Comment by WeirdoShaw** [comment]
```
Rule:
  - 'IP-LOCAL,,RETURN'
  - 'IP-PRIVATE,,RETURN'
  - 'IP-CIDR,LOCAL,RETURN'
  - 'IP-CIDR,PRIVATE,RETURN'
```
个人愚见，您意下如何？

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium 实现了部分规则集功能

**Comment by necan** [comment]
例如像 Chrome 的 [Bypass List](https://developer.chrome.com/docs/extensions/reference/proxy/#bypass-list) 的 `<local>` 这样。
