### ISSUE TITLE
url-test 能否支持重定向？

### ISSUE THREAD

**Issue by Azureki** [Dreamacro/clash#411]
我 url-test 中的 url 在其他软件中填的是 `http://bing.com`，可以正常使用。今天在 clash 中改了之后发现并不支持重定向。因此最终只会按顺序[1]选择第一个节点。

一般国外ip访问 `http://bing.com` 会重定向到 `www.bing.com`，所以配置中改成 `http://www.bing.com` 就没问题了。
但是还有些 ip，因为服务商（ali）的原因被归到国内，于是重定向到`cn.bing.com`，配置中 url 应该填 `cn.bing.com` 。

这时候就有问题了，非国内的 ip 访问 cn.bing.com 还是会被重定向到 `www.bing.com`，不能既填 `http://www.bing.com`，又填`http://cn.bing.com`。
所以，能否支持重定向呢？

错误信息：
```
2019/11/22 10:40:22 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Content-Length: 114816
Content-Type: text/html; charset=utf-8
P3P: CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"
Set-Cookie: SRCHD=AF=NOFORM; domain=.bing.com; expires=Mon, 22-Nov-2021 02:40:22 GMT; path=/
Set-Cookie: SRCHUID=V=2&GUID=81A82895B9DC4D3086ED5A4F496FC1E7&dmnchg=1; domain=.bing.com; expires=Mon, 22-Nov-2021 02:40:22 GMT; path=/
Set-Cookie: SRCHUSR=DOB=20191122; domain=.bing.com; expires=Mon, 22-Nov-2021 02:40:22 GMT; path=/
Set-Cookie: _SS=SID=07D64C0BA0D96D461C944217A1116CF7; domain=.bing.com; path=/
X-MSEdge-Ref: Ref A: 176CBE6792E64A8FAAD70627617D14D7 Ref B: HK2EDGE1117 Ref C: 2019-11-22T02:40:22Z
Set-Cookie: _EDGE_S=F=1&SID=07D64C0BA0D96D461C944217A1116CF7; path=/; httponly; domain=bing.com
Set-Cookie: _EDGE_V=1; path=/; httponly; expires=Wed, 16-Dec-2020 02:40:22 GMT; domain=bing.com
Set-Cookie: MUID=232E3F2031036EFC1CE2313C30CB6FB1; path=/; expires=Wed, 16-Dec-2020 02:40:22 GMT; domain=bing.com
Set-Cookie: MUIDB=232E3F2031036EFC1CE2313C30CB6FB1; path=/; httponly; expires=Wed, 16-Dec-2020 02:40:22 GMT
Date: Fri, 22 Nov 2019 02:40:22 GMT

"; err=<nil>
```

-----
注释：
[1]. 严格来说是这样：如果有不被重定向的节点，就在这里面选；如果没有，则按顺序选。

**Comment by Dreamacro** [comment]
follow 没什么意义啊，这个 test 的目的不是完整请求这个网址

**Comment by Azureki** [comment]
抱歉，我判断错了。

因为以前surge上一直用的bing，所以我想当然以为是重定向问题。刚刚在surge上也把url改成了`http://www.gstatic.com/generate_204`，发现surge还是可以正常工作。
这就非常神奇了。

情景是这样的：我需要测速的是中转节点，并非所有网站都通过国外服务器，有些网站会分流至国内的服务器。所以即使另一端挂了，gstatic 这样的网站还是可以访问的，因此就无法用这个网站来选择节点。
不过这确实就是预期的结果。

但是 surge 却还是可以用 gstatic 选择……所以它才是不正常的一个。
这可能算是 surge 的 feature 吧……也不知道 surge 是怎么实现的，就算了吧。

**Comment by qzi** [comment]
好像还是不支持url write
