### ISSUE TITLE
错误x509:certificate

### ISSUE THREAD

**Issue by kenvint** [Dreamacro/clash#414]
Proxy:
  - name: US
    type: vmess
    server: **12.1*2.**3
    port: 443
    uuid: UUID
    alterId: 233
    cipher: auto
    network: ws
    ws-path: /panel
    tls: true

以上，yml文件配置，在v2rayN里可用，但是clash不可用，log-debug下报
Dial [Proxy] failed
DIial [srever name] error: x509: certificate
siged by unknown authority [time]

**Comment by beyondkmp** [comment]
添加配置 `skip-cert-verify: true`

**Comment by philosopher233** [comment]
> 添加配置 `skip-cert-verify: true`

@beyondkmp 您好, 我最近几天才开始用clash, 配置完trojan, 遇到了同样的问题, 请问只有添加`skip-cert-verify: true`才能正常运行吗?
