### ISSUE TITLE
[question] Difference between FAKE-IP and REDIR-HOST?

### ISSUE THREAD

**Issue by paulgit** [Dreamacro/clash#415]
I am trying to find documentation or an explanation on the difference between the DNS enhanced mode setting of FAKE-IP and REDIR_HOST and the advantages/disadvantages for each. 

Can anyone help?

Thanks

**Comment by Dreamacro** [comment]
[this](https://medium.com/@TachyonDevel/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0) seems help for you.

**Comment by CPCer** [comment]
and [this](https://lancellc.gitbook.io/clash/clash-config-file/dns)
