### ISSUE TITLE
Can't find MMDB, start download              

### ISSUE THREAD

**Issue by appleyuchi** [Dreamacro/clash#416]
(python3.6) appleyuchi@ubuntu:v2ray$ ./clash-linux-amd64 
INFO[0000] Can't find MMDB, start download              
FATA[0000] Initial configuration directory error: Can't download MMDB: Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz: EOF 

原来的问题被关闭了，所以重新开了个：
https://github.com/Dreamacro/clash/issues/159

请问所谓的配置文件夹在哪里呢？
我下载了clash之后，解压后只有一个可执行文件，谢谢！

**Comment by Dreamacro** [comment]
read https://github.com/Dreamacro/clash#config first

**Comment by epicure1998** [comment]
请问楼主的问题解决了吗， 我也安装clash的时候遇到了同样的问题，想问下你是怎么解决的

**Comment by xianshenglu** [comment]
我也没有找到 Country.mmdb 在哪， start download 之后，就没反应了，@Dreamacro

**Comment by gengzhy** [comment]
我把Country.mmdb下载到同级目录下了，但是依然报错：**Can't find MMDB**，请问是如何解决呢？ Country.mmdb文件需要放在哪个路径？或者命名有什么规范？

**Comment by gengzhy** [comment]
我把Country.mmdb下载到与class执行文件同级目录下了，但是依然报错：Can't find MMDB，请问是如何解决呢？ Country.mmdb文件需要放在哪个路径？或者命名有什么规范？

**Comment by RinChanNOWWW** [comment]
手动下载 Country.mmdb 之后并放到 clash 所在目录下之后需要加一个命令行选项 `-d .`。 比如：

```bash
$ ls
cache.db  clash  clash-dashboard  config.yaml  Country.mmdb
$ ./clash -f config.yaml -d .
```

这样就可以正常运行了 @gengzhy。
