### ISSUE TITLE
如何指定tls版本？

### ISSUE THREAD

**Issue by Mr-Sheep** [Dreamacro/clash#417]
在Surge這類的軟件中，在配置文件中可以指定tls的版本
請問在Clash中如何實現？

**Comment by Dreamacro** [comment]
没法指定 tls 版本，有什么特殊需要？

**Comment by Mr-Sheep** [comment]
可否实现类似于下面的配置方法
tls13=true
因爲我指定了CF最低版本的tls爲1.3
或者目前的Clash是否會默認優先使用tls1.3？

**Comment by Dreamacro** [comment]
对 会优先协商 tls 1.3, 不支持就降级 1.2

**Comment by Mr-Sheep** [comment]
明白了，感謝
