### ISSUE TITLE
[question] Clash 的 DNS 与上游服务器是如何连接的？

### ISSUE THREAD

**Issue by Howard-00** [Dreamacro/clash#418]
我没有设置特殊端口 DNS 或 DoH，并且在 Rule 开头加了以下规则
```
- DST-PORT,853,REJECT
- DST-PORT,53,REJECT
```
仍然可以正常使用，切换到 redir-host 后 nslookup 也能得到正确结果，是不是它不受 Rule 的控制。如果是的话它会直连还是代理？直连的话 fallback 里的国外 53 端口不是很容易被污染？代理的话它走的又是哪个节点？
另外节点服务器的域名也是通过 Clash DNS 解析吗？

**Comment by Dreamacro** [comment]
DNS 不走代理，直连

节点服务器通过 Clash DNS 解析
