### ISSUE TITLE
[Feature Request] Clash Virtual Gateway

### ISSUE THREAD

**Issue by lincolnguang** [Dreamacro/clash#419]
## What is Clash Virtual Gateway?

**Clash Virtual Gateway** is a part of clash, it worked on TAP or TUN mode. It will handle raw tcp socket, or all the traffic clash can’t handle now, redirect them to a right destination.

**Clash Virtual Gateway** will also start a Fake-DNS server, all the DNS request will be handled, and then send to upstream DNS server. Fake-DNS can be disabled alone.

Users can chooses enable/disable **Clash Virtual Gateway**.

## How to redirect?

Http or Https traffic can be directed, proxied or rejected to a destination by clash now.

TCP or UDP traffic can be directed, proxied or rejected (if necessary) to a destination.

Due to some reasons, ICMP can’t be proxied, so it will be directed to a destination.

### Skip proxy

Forces some connection (IP, IP-range or Domain) handled by Clash Virtual Gateway.

Example:
`skip-proxy:10.0.0.0/16, bing.com, *.weibo.com`

### Always Real-IP

It can be IP, IP-range or Domain.

Clash will return a real IP address instead of a fake IP address. When Clash Virtual Gateway handle a DNS request and domains in this field, DNS request will send directly to upstream DNS server. This will be more helpful in solving Clash crashed when trying connect to smb in local network and fix other questions when using fake-ip mode.

Clash should consider add default Real-IP inside.

Example:

`real-ip: 127.0.0.1, 10.0.0.0/12, *.apple.com`

### Hijack-DNS

Some devices or software always use a hardcoded DNS server. For example, Google Speakers always use 8.8.8.8. Clash Virtual Gateway in Fake-DNS modes’ DNS answer will not be accepted. 

By using this opinion, Clash can Hijack all dns query to Fake-DNS server. Hijack DNS will more useful on router.

It can be port number and ip.

Example:

`hijack-dns: 8.8.8.8`   Hijack all dns query from 8.8.8.8 to Fake-DNS server.
`hijack-dns: *:53`       Hijack all dns query

### Excluded Routes

Use this option to bypass specific IP ranges to allow all traffic to pass through. 

It can be IP range.

Example:  

`excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 127.0.0.0/12`

This option only works for Clash Virtual Gateway. Requests handled by Clash will not be affected. Users may use `skip-proxy` and `excluded-routes` together to bypass specific traffic.

**Comment by lincolnguang** [comment]
### Included Routes

Redirect clash itself traffic to Clash Virtual Gateway. For example, DoH or DoT traffic can be handled, and go proxy or direct. 

It can be IP range.

Example:

included-routes = 192.18.0.1

**Comment by BirkhoffLee** [comment]
Thanks for the feature request. We now have a WIP experimental TUN in [Releases](https://github.com/Dreamacro/clash/releases).
