### ISSUE TITLE
求助如何加载ui

### ISSUE THREAD

**Issue by zsq19958629** [Dreamacro/clash#420]
clash已经通过docker的方式运行起来了，但是没有教程详细的教如何把ui模式开启来。求帮助，谢谢。

**Comment by Dreamacro** [comment]
1. 通过 `external-controller` 把端口暴露到宿主机上，通过已经部署好的界面（具体在哪自己找）连接到这个端口

2. 下载编译好的 dashboard，通过 `external-ui` + volume 把文件夹挂载进去，最后访问 http://api/ui

**Comment by zsq19958629** [comment]
我通过192.168.2.2:9090/ui已经能够访问到ui文件夹下的文件列表了。
不过，ui的页面还是没有显示出来。

**Comment by Dreamacro** [comment]
说明你没写对目录或目录里没 dashboard

**Comment by zsq19958629** [comment]
Docker运行命令行
`docker run -it --name ClashSSR -v /root/clashSSR/config.yaml:/root/.config/clash/config.yaml:ro -v /root/clashSSR/ui:/ui -p 9090:9090 -p
7890:7890 -p 7891:7891 junxy/clash
`
config.yaml片段
`port: 7890
socks-port: 7891
# redir-port: 7892
allow-lan: true
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
#secret: ""
external-ui: /ui
# experimental feature
experimental:
  ignore-resolve-fail: true # ignore dns resolve fail, default value is true`

ui文件部分，通过github下载到clash-dashboard-0.3.0.zip压缩包，把clash-dashboard-0.3.0.zip\clash-dashboard-0.3.0内的所有文件放到“/root/clashSSR/ui”目录下。

请问，这样正确吗？
谢谢~

**Comment by zsq19958629** [comment]
Docker运行命令行
docker run -it --name ClashSSR -v /root/clashSSR/config.yaml:/root/.config/clash/config.yaml:ro -v /root/clashSSR/ui:/ui -p 9090:9090 -p 7890:7890 -p 7891:7891 junxy/clash

config.yaml片段
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
#secret: ""
external-ui: /ui
experimental feature
experimental:
ignore-resolve-fail: true

ui文件部分，通过github下载到clash-dashboard-0.3.0.zip压缩包，把clash-dashboard-0.3.0.zip\clash-dashboard-0.3.0内的所有文件放到“/root/clashSSR/ui”目录下。

请问，这样正确吗？
谢谢~

**Comment by Dreamacro** [comment]
第三方 docker 镜像的问题暂不解决

**Comment by yuguansu** [comment]
我在群晖docker上尝试了几次，成功加载ui，以下操作步骤供参考：
1、下载docker包最新版本，创建容器clash
2、config.yaml中添加参数（原来没有）：external-ui: /ui
3、下载UI文件夹 [yacd.tar.xz](https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz)，解压后和config.yaml放在同一个路径下
4、配置文件夹映射（左边要改成上述3中实际存放ui文件夹路径）：./ui:/ui
5、以管理员权限启动clash
