### ISSUE TITLE
如何查看被代理的哪个程序在下载?

### ISSUE THREAD

**Issue by FaiChou** [Dreamacro/clash#421]
使用的是客户端 clashX, 但是在它的 GitHub 上没找到 issue, 所以在这里提问下:

电脑重启后, iStat 菜单栏流量检测出网络一直在下载, 一直占据流量下载的 process 是 clashX. 当时自己并没有手动开启其他任何第三方 app, 打开 Activity Monitor 查看流量也只是显示 clashX 一直在下载, 其他的 process 并没有下载.

因为自己的系统并没有将 vmess 的代理放到全局, 屈指可数的用代理的 app 「 telegram/浏览器」也没有打开, 检查了 clashX 客户端是最新的也没有正在更新, 所以不明白网络到底哪一个在占用.

所以有方法检查哪一个进程在占用 vmess 的代理网络吗?

**Comment by Dreamacro** [comment]
dashboard 「连接」页面

**Comment by FaiChou** [comment]
@Dreamacro  谢谢, 没想到这么简单 😂.

刚才奇怪的网络下载已经消失不见了

**Comment by movethink** [comment]
> dashboard 「连接」页面

这个是指啥？
