### ISSUE TITLE
打开clashx之后，mac系统配置的hosts就会失效

### ISSUE THREAD

**Issue by lichen0501** [Dreamacro/clash#423]
本地开发需要在hosts中添加域名解析到本地，只要打开clashx客户端，勾选设置为代理系统，就会无法通过域名访问

**Comment by Dreamacro** [comment]
开启自定义 dns 是这样的，clash 自己也有 hosts，你可以直接设置 hosts 或关掉自定义 dns

**Comment by yaoshanliang** [comment]
> 开启自定义 dns 是这样的，clash 自己也有 hosts，你可以直接设置 hosts 或关掉自定义 dns

在哪里设置？可以同时使用内部hosts

**Comment by mizi-lin** [comment]
@yaoshanliang  在配置文件中，关闭dns

**Comment by JosephMing** [comment]
> @yaoshanliang 在配置文件中，关闭dns
> 
> ```yaml
> dns:
>   enable: true # set true to enable dns (default is false)
>   listen: 127.0.0.1:53
>   nameserver:
>      - 119.28.28.28
>      - 114.114.114.114
>   fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
>      - tls://1.0.0.1:853
>      - tls://dns.google:853
> ```
> 
> ```yaml
> dns:
>   enable: false
> ```

![image](https://user-images.githubusercontent.com/31059354/100201335-eadea300-2f3a-11eb-8410-e2f004224ffb.png)
如此设置必不管用，系统配置的hosts还是不起作用

**Comment by fancyoung** [comment]
> > @yaoshanliang 在配置文件中，关闭dns
> > ```yaml
> > dns:
> >   enable: true # set true to enable dns (default is false)
> >   listen: 127.0.0.1:53
> >   nameserver:
> >      - 119.28.28.28
> >      - 114.114.114.114
> >   fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
> >      - tls://1.0.0.1:853
> >      - tls://dns.google:853
> > ```
> > 
> > 
> > ```yaml
> > dns:
> >   enable: false
> > ```
> 
> ![image](https://user-images.githubusercontent.com/31059354/100201335-eadea300-2f3a-11eb-8410-e2f004224ffb.png)
> 如此设置并不生效，系统配置的hosts还是不起作用

1. enable 要改完 false。
2. 点“重载配置文件”。

测试可用

**Comment by JosephMing** [comment]
> > > @yaoshanliang 在配置文件中，关闭dns
> > > ```yaml
> > > dns:
> > >   enable: true # set true to enable dns (default is false)
> > >   listen: 127.0.0.1:53
> > >   nameserver:
> > >      - 119.28.28.28
> > >      - 114.114.114.114
> > >   fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
> > >      - tls://1.0.0.1:853
> > >      - tls://dns.google:853
> > > ```
> > > 
> > > 
> > > ```yaml
> > > dns:
> > >   enable: false
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31059354/100201335-eadea300-2f3a-11eb-8410-e2f004224ffb.png)
> > 如此设置并不生效，系统配置的hosts还是不起作用
> 
> 1. enable 要改完 false。
> 2. 点“重载配置文件”。
> 
> 测试可用

是因为我打开了 使用 iCloud

**Comment by pengRW** [comment]
确实可用, 多谢大哥

**Comment by darrenliuwei** [comment]
> 2\. 点“重载配置文件”

在哪里点“重载配置文件”呀？

**Comment by JosephMing** [comment]
> > 2. 点“重载配置文件”
> 
> 在哪里点“重载配置文件”呀？

![image](https://user-images.githubusercontent.com/31059354/109904669-8c168b80-7cd8-11eb-95e3-9c9336a18fa7.png)

**Comment by darrenliuwei** [comment]
> > > 1. 点“重载配置文件”
> > 
> > 
> > 在哪里点“重载配置文件”呀？
> 
> ![image](https://user-images.githubusercontent.com/31059354/109904669-8c168b80-7cd8-11eb-95e3-9c9336a18fa7.png)

谢谢~

**Comment by huyuaning** [comment]
解决了，多谢大哥

**Comment by RRRoger** [comment]
谢谢 已解决

**Comment by Anr-C** [comment]
改为 flase，整块注释保平安，解决了，感谢。

**Comment by Prophetia086** [comment]
请问为什么1.50.1版本，设置dns enable 为false，已经不管用了？还是不能解析本地hosts

**Comment by wzlee** [comment]
编辑~/.config/clash/proxyIgnoreList.plist(如果没有该文件，则新建)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>192.168.0.0/16</string>
	<string>10.0.0.0/8</string>
	<string>172.16.0.0/12</string>
	<string>127.0.0.1</string>
	<string>localhost</string>
	<string>*.local</string>
	<string>*.crashlytics.com</string>
	<!-- 上面的不能删掉 -->
	...加入新的域名，如：<string>*.baidu.com</string>
</array>
</plist>
```
重启clashx

**Comment by pianozcl** [comment]
> ，系统配置的hosts还是不起作用

我也是改了配置为false，不起作用，最后问题解决了吗

**Comment by bennieniu** [comment]
> > ，系统配置的hosts还是不起作用
> 
> 我也是改了配置为false，不起作用，最后问题解决了吗

1. 不要使用icloud
2. 添加proxyIgnore配置文件

**Comment by liuxiaoqigui** [comment]
怎么不适用

> > > ，系统配置的hosts还是不起作用
> > 
> > 
> > 我也是改了配置为false，不起作用，最后问题解决了吗
> 
> 1. 不要使用icloud
> 2. 添加proxyIgnore配置文件

不使用iCloud  怎么关闭啊

**Comment by liuxiaoqigui** [comment]
> > > ，系统配置的hosts还是不起作用
> > 
> > 
> > 我也是改了配置为false，不起作用，最后问题解决了吗
> 
> 1. 不要使用icloud
> 2. 添加proxyIgnore配置文件

![image](https://user-images.githubusercontent.com/30720244/140682763-35ebd3a7-695c-4d78-992e-1602ee0cbc9c.png)
还是不行啊

**Comment by Hxhzfd** [comment]
windows 重载配置在哪

**Comment by kkomler** [comment]
解决了，感谢感谢

**Comment by Gui052** [comment]
> 

解决了吗？

**Comment by DosLee** [comment]
> 编辑~/.config/clash/proxyIgnoreList.plist(如果没有该文件，则新建)
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> 	<string>192.168.0.0/16</string>
> 	<string>10.0.0.0/8</string>
> 	<string>172.16.0.0/12</string>
> 	<string>127.0.0.1</string>
> 	<string>localhost</string>
> 	<string>*.local</string>
> 	<string>*.crashlytics.com</string>
> 	
> 	...加入新的域名，如：<string>*.baidu.com</string>
> </array>
> </plist>
> ```
> 
> 重启clashx

亲测好用，感谢

**Comment by mshyh** [comment]
@kkomler 怎么解决的

**Comment by lidakai** [comment]
> 

nice 可行

**Comment by XuShall** [comment]
因为订阅的链接是远程的,它会自动更新,每次都修改dns 非常麻烦.

**Comment by jitash** [comment]
大家可以看看这个博主的，我用着不错
https://www.hifool.cn/posts/f42b65b0/

**Comment by lait233** [comment]
等一个好办法.同样被此问题困扰 惆怅

**Comment by tiiaan** [comment]
ClashX version 1.96.2
<img width="535" alt="Screen Shot 2023-01-28 at 22 19 44" src="https://user-images.githubusercontent.com/72431352/215271578-2c76a388-d5c4-4c78-ba9e-bb9eb2f8ed7e.png">
<img width="421" alt="Screen Shot 2023-01-28 at 22 20 19" src="https://user-images.githubusercontent.com/72431352/215271636-bcab9c67-0072-48fd-abce-fde1e388397a.png">
再重启就好了

**Comment by a13135556916** [comment]
> https://www.hifool.cn/posts/f42b65b0/

我试过了，不行

**Comment by crazylxr** [comment]
> ClashX version 1.96.2 <img alt="Screen Shot 2023-01-28 at 22 19 44" width="535" src="https://user-images.githubusercontent.com/72431352/215271578-2c76a388-d5c4-4c78-ba9e-bb9eb2f8ed7e.png"> <img alt="Screen Shot 2023-01-28 at 22 20 19" width="421" src="https://user-images.githubusercontent.com/72431352/215271636-bcab9c67-0072-48fd-abce-fde1e388397a.png"> 设置白名单，再重启就好了

nice，好用

**Comment by Prophetia086** [comment]
> 

非常好用，多谢！

**Comment by Prophetia086** [comment]
> ClashX version 1.96.2
> <img alt="Screen Shot 2023-01-28 at 22 19 44" width="535" src="https://user-images.githubusercontent.com/72431352/215271578-2c76a388-d5c4-4c78-ba9e-bb9eb2f8ed7e.png">
> <img alt="Screen Shot 2023-01-28 at 22 20 19" width="421" src="https://user-images.githubusercontent.com/72431352/215271636-bcab9c67-0072-48fd-abce-fde1e388397a.png">
> 设置白名单，再重启就好了

非常好用，多谢！

**Comment by zhouwencn** [comment]
> > ClashX version 1.96.2
> > <img alt="Screen Shot 2023-01-28 at 22 19 44" width="535" src="https://user-images.githubusercontent.com/72431352/215271578-2c76a388-d5c4-4c78-ba9e-bb9eb2f8ed7e.png">
> > <img alt="Screen Shot 2023-01-28 at 22 20 19" width="421" src="https://user-images.githubusercontent.com/72431352/215271636-bcab9c67-0072-48fd-abce-fde1e388397a.png">
> > 设置白名单，再重启就好了
> 
> 非常好用，多谢！

 clash pro好像没有settings配置啊

**Comment by terwer** [comment]
非常感谢，dns 禁用之后 解决了我的问题。

**Comment by 1021683053** [comment]
> 因为订阅的链接是远程的,它会自动更新,每次都修改dns 非常麻烦. 已经2022年了 不知道还有没有更好的方案

其他方式可以处理

**Comment by visionChengc** [comment]
很不错

**Comment by wy5211** [comment]
1. 
![image](https://github.com/Dreamacro/clash/assets/54129434/d3953e78-11e8-4bbb-8f66-542c361e6205)


2. 
![image](https://github.com/Dreamacro/clash/assets/54129434/1c1d527c-6f87-4cc3-ba24-1152c2b1f951)


3. 重启 clashX

**Comment by yoyo837** [comment]
> ![image](https://user-images.githubusercontent.com/54129434/275318219-d3953e78-11e8-4bbb-8f66-542c361e6205.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/54129434/275318233-1c1d527c-6f87-4cc3-ba24-1152c2b1f951.png)
> 
> 3. 重启 clashX

我记得之前好像试过没用
