### ISSUE TITLE
url-test 似乎不能忽略DNS时间对最终结果的影响

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#426]
目前观察到的现象是从首次测速结果来看正在用的节点远比其他节点延迟更低，且使用url-test的策略组自动选择的节点也基本跟正在使用的节点重合，推测是正在使用的节点存在DNS缓存导致测速时速度更有优势。
如果url-test策略组检测组内节点速度也是仅用首次测速的结果的话就会影响结果的准确性，在设置的检测时间间隔比较长且节点延迟差距不是很大的情况下大概率会一直保持在某个节点不动。
不知是否可以把url-test包含DNS查询时间的首次测试结果抛弃掉，用第二次或后几次的均值/中值作为节点的延迟表现？

**Comment by Dreamacro** [comment]
现在除了第一次，剩下的请求基本会复用 dns 缓存
