### ISSUE TITLE
clashx 拦截了虚拟机域名，导致vagrant无法使用

### ISSUE THREAD

**Issue by dzymail** [Dreamacro/clash#428]
我装了vagrant虚拟机，在/etc/hosts里面设置了自己的假域名abc.test，指向ip,192.168.10.10。此时用ip可以直接访问我的虚拟机，但是用域名不行。
我的定义的规则是国外用代理，国内直联，剩下的没定义的直联，而且局域网设置了 192.168.0.0/16 这些类似网段。
如果关闭【作为系统代理这个选项】或者退出 clashx，域名访问vagrant没问题，一启用clash我的vagrant就无法用域名连接。

**Comment by Dreamacro** [comment]
1. 启用了自定义 DNS: 用 clash 的 hosts
2. 不启用: 不会有问题

**Comment by nicewahson** [comment]
访问内网域名，日志显示match DomainKeyword using DIRECT，但是还是不能访问怎么破

**Comment by bobolau** [comment]
add file ~/.config/clash/proxyIgnoreList.plist
more detail see https://github.com/yichengchen/clashX

**Comment by zhangxuehao** [comment]
> 访问内网域名，日志显示match DomainKeyword using DIRECT，但是还是不能访问怎么破

请问你解决了吗？
