### ISSUE TITLE
多个fallback代理组中使用Direct导致判断结果异常

### ISSUE THREAD

**Issue by teschangelo636** [Dreamacro/clash#431]
Proxy Group:
  - name: WORK1
    proxies:
      - DIRECT
      - WORK1PROXY
    type: fallback
    url: http://192.168.1.1:80
    interval: "60"
  - name: WORK2
    proxies:
      - DIRECT
      - WORK2PROXY
    type: fallback
    url: http://192.168.2.1:80
    interval: "60"

以上配置的目的在于我的电脑在WORK1的网络中时使WORK1直连，WORK2使用代理，如果在WORK2时WORK1代理WORK2直连，但是软件的最终结果是要么两个都直连，要么两个都走代理

**Comment by comzyh** [comment]
目前fallback的延迟信息是保存在节点数据结构中的，不是保存在组里面。
所以现在判断逻辑就是一个节点在最新的(无论是以哪个URL为目标)测试存活，就认为这个节点存活。
所以目前的逻辑下用不同的URL测试相同的节点达不到你想要的效果。
