### ISSUE TITLE
[Feature Request] 能否考虑支持节点的嵌套中转？

### ISSUE THREAD

**Issue by h0cheung** [Dreamacro/clash#434]
虽然大部分机场都有自定义中转设置，但这只局限在同一机场的节点相互中转，而且修改很不灵活，且不支持节点链 A-B 与 A-C 同时存在。
而在本地开多个代理工具实例，把 i+1 级代理的前置代理设置为 i 级代理，固定单节点效果不错，但在节点较多时分流非常不好处理。
因此，clash 有没有可能开这个头，原生支持节点的嵌套中转，解决这一个痛点？

**Comment by Theresa2876** [comment]
+1，同希望增加这个功能，类似于V2ray的proxy setting。

**Comment by xjasonlyu** [comment]
+1，希望可以如下配置：

```
Proxy:
- a
- b
- c
Proxy Group:
- { name: B, type: url-test, proxies: [a, b] }
- { name: A, type: select, proxies: [B], forward:  c }
```

这样就可以在策略组A中通过代理c来转发策略组B的流量了

**Comment by Dreamacro** [comment]
close by #539
