### ISSUE TITLE
这是偷跑么 啥也没干 跑这么快 国内都打开超慢了 关了就好了 

### ISSUE THREAD

**Issue by yuzhenghuan** [Dreamacro/clash#435]
<img width="599" alt="QQ20191218-171629@2x" src="https://user-images.githubusercontent.com/43665741/71074139-b3a93300-21bc-11ea-9b60-002a189a038c.png">

**Comment by beyondkmp** [comment]
@yuzhenghuan  苹果自带的系统更新，或者是xcode的更新。自己看下是哪个连接的下载就知道了。
