### ISSUE TITLE
osx terminal 设置代理无效

### ISSUE THREAD

**Issue by miroda** [Dreamacro/clash#437]
在terminal里面设置 代理，无效，请问有人知道吗？

**Comment by Dreamacro** [comment]
信息不足，无法回答

**Comment by soffchen** [comment]
https://github.com/rofl0r/proxychains-ng

**Comment by hurongyang** [comment]
例如命令行登录 MySQL，mysql -h 'remote_ip' -u root -p，我的流量不能被代理。

**Comment by Dreamacro** [comment]
是这样的，虽然有环境变量，但是应用程序不一定会遵守这个环境变量，也就是他不会根据已填的代理进行连接。surge 会有一个 TUN 并且通过路由表拦截所有的流量，clash 也正在加 TUN，现在只能拦截所有有域名的连接。
