### ISSUE TITLE
[Question] How does Clash handle the UDP traffic

### ISSUE THREAD

**Issue by ruisiji** [Dreamacro/clash#438]
I usually use Shadowsocks over HTTPS and V2ray over HTTPS as my preferred profiles.

But seems they don't support forwarding UDP traffic, can someone tell me how Clash handles UDP traffic?

For Shadowsocks Android, the owner implemented a feature: UDP fallback profile https://github.com/shadowsocks/shadowsocks-android/issues/2064

**Comment by Dreamacro** [comment]
Clash inbound Socks5 support UDP, but most client doesn't support it in the real world. And I already implemented TUN mode. It's unstable now, I use it as a gateway like surge but works on macos/linux. If you want to test it. I can provide the binary of your platform.

**Comment by ruisiji** [comment]
Thanks, can you provide the `amd64` binary?

**Comment by Dreamacro** [comment]
https://send.firefox.com/download/b8029887a6325c97/#1JJyJQkYJGCc4260mauJIQ

Clash TUN 101:

**Works only on fake-ip now** with config:

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114

tun:
  enable: true
```

Run clash with sudo:

```
$ ./clash
```

**macOS should run an external command**

```
# replace ip cidr and tun name
$ sudo route -n add -net 10.19.0.1/16 -interface utun2
```

set the gateway and dns server, then enjoy the clash

**Comment by ruisiji** [comment]
Hi, I used the config you provided, but encountered some issues:

My OS is: Ubuntu 18.04.2, Vagrant on macOS

My curl binary: https://github.com/curl/curl/blob/master/docs/HTTP3.md#quiche-version

After starting Clash, my routes are:

```
default via 10.0.2.2 dev enp0s3
10.0.2.0/24 dev enp0s3 proto kernel scope link src 10.0.2.15
10.0.2.2 dev enp0s3 proto dhcp scope link src 10.0.2.15 metric 100
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1
```

Interface:

```
8: utun: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 198.18.0.1/16 scope global utun
       valid_lft forever preferred_lft forever
    inet6 fe80::159e:6096:53a:2daf/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

`blog.cloudflare.com` is set to use PROXY.

## Case 1

1. start clash
2. curl -v https://blog.cloudflare.com/status

    No output in Clash binary, seems Clash does not proxy this url.

3. curl --http3 -v https://blog.cloudflare.com/status

    No output in Clash binary, seems Clash does not proxy this url.

## Case 2

1. start clash
2. export all_proxy=socks5://127.0.0.1:7891
3. curl -v https://blog.cloudflare.com/status

    Not sure why Clash use DIRECT for blog.cloudflare.com
    INFO[0629] 127.0.0.1 --> 104.18.27.46 match Match using DIRECT

4. curl --http3 -v https://blog.cloudflare.com/status

    curl hang, clash no output

## Case 3

1. start clash
2. export https_proxy=http://127.0.0.1:7890
3. curl -v https://blog.cloudflare.com/status

    works as expected.

4. curl --http3 -v https://blog.cloudflare.com/status

    curl failed with `connect to 127.0.0.1 port 7890 failed: Connection refused`
    no clash output

## Case 4

1. start clash
2. set 198.18.0.1 as default gateway
3. curl -v https://blog.cloudflare.com/status

    with or without `--http3`, clash output following, seems clash in a loop to itself.

    INFO[0301] 198.18.0.1 --> 104.18.26.46 match Match using DIRECT
    INFO[0304] 198.18.0.1 --> 104.18.26.46 match Match using DIRECT
    INFO[0305] 198.18.0.1 --> 104.18.26.46 match Match using DIRECT
    INFO[0305] 198.18.0.1 --> 104.18.26.46 match Match using DIRECT

**Comment by yichengchen** [comment]
@ruisiji seems you are no setting fakeip range as same as dreamacro. You should apply your route command ip address by 198.18.0.1/16

**Comment by ruisiji** [comment]
The default range is `198.18.0.1/16`, when I explicitly set to this cidr, the issues still exist.

**Comment by Dreamacro** [comment]
@ruisiji should use clash dns server as your device dns.

The way you can ensure clash TUN works:

`dig baidu.com @clashdns` and get a fakeip

`curl -H "Host: baidu.com" fakeip`

**Comment by ruisiji** [comment]
@Dreamacro Thank you for pointing this out. After changing the DNS Server, everything works as expected.

**Comment by chenzhiwei** [comment]
借贵宝地给@yichengchen 反馈个 ClashX Pro 的问题，开启TUN模式时它无法和 Cisco Anyconnect 一起工作，Cisco Anyconnect  会一直不间断的重连。

**Comment by BrandoZhang** [comment]
> 借贵宝地给@yichengchen 反馈个 ClashX Pro 的问题，开启TUN模式时它无法和 Cisco Anyconnect 一起工作，Cisco Anyconnect 会一直不间断的重连。

Have the same issue. I am searching for the best practice to work with Clash and Cisco Anyconnect.
