### ISSUE TITLE
rest full api 如何重新加载配置文件

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#440]
我使用`curl -X PUT -d path=/etc/clash/config.yaml http://127.0.0.1:9090/configs`
会报错，{"message":"Body invalid"}

**Comment by Dreamacro** [comment]
使用 `application/json` 而不是 `application/x-www-form-urlencoded`

**Comment by cjwddtc** [comment]
我是用`curl -X PUT -H "Content-Type: application/json" -d '{"path","/etc/clash/config.yaml"}' http://127.0.0.1:9090/configs`，报错`{"message":"Body invalid"}`

**Comment by Dreamacro** [comment]
`{"path": "/etc/clash/config.yaml"}`

**Comment by cjwddtc** [comment]
好了，谢谢

**Comment by a-wing** [comment]
这里好像还有个问题
https://clash.gitbook.io/doc/restful-api/config
> Body Parameters
> path optional

文档上是可选字段，但实际上这个字段是必选的
body 如果为空，Body invalid
如何没有 path 字段， path is not a absoluted path

**Comment by fxzxmicah** [comment]
在Windows上使用`curl -X PUT -H "Content-Type:application/json" -d '{"path","D:/clash/config.yaml"}' http://127.0.0.1:9090/configs`依旧会出现`{"message":"Body invalid"}`，请问是此方法在Windows上不受支持吗？

**Comment by Dreamacro** [comment]
@fxzxmicah https://github.com/Dreamacro/clash/issues/440#issuecomment-568172730

**Comment by fxzxmicah** [comment]
> @fxzxmicah [#440 (comment)](https://github.com/Dreamacro/clash/issues/440#issuecomment-568172730)

不好意思，打扰了，我已经解决了，是CMD的引号问题，需要写成这样：`curl -X PUT -H "Content-Type:application/json" -d "{\"path\",\"D:\\clash\\config.yaml\"}" http://127.0.0.1:9090/configs`
