### ISSUE TITLE
在网站用QQ号登陆关联账号   不能用电脑上已登陆的QQ直接登陆

### ISSUE THREAD

**Issue by qq704361748** [Dreamacro/clash#442]
在网站用QQ号登陆关联账号   不能用电脑上已登陆的QQ直接登陆，断开clash的代理刷新立马正常

**Comment by Dreamacro** [comment]
给个网站看看?

**Comment by qq704361748** [comment]
> 给个网站看看?
https://www.dd373.com

**Comment by Dreamacro** [comment]
定位到问题了，你应该是路由器用户或者开了 fakeip dns 吧？qq 用了一个 127.0.0.1 记录的域名，和 fakeip 有冲突。我想想怎么解决

**Comment by qq704361748** [comment]
> 定位到问题了，你应该是路由器用户或开了fakeip dns吧？qq用了一个127.0.0.1记录的域名，和fakeip有冲突。我想想怎么解决

校园网   fakeip开没开不确定

**Comment by BirkhoffLee** [comment]
@qq704361748 最新版還有一樣問題嗎？順便確認一下是不是有用 fake-ip
