### ISSUE TITLE
When using tun on Linux, telegram seems can't to connect 

### ISSUE THREAD

**Issue by L0snight** [Dreamacro/clash#443]
When i use tun mode on Linux, everything works well except Telegram. There is nothing about tg in logs. But when i use socket5 to connect tg, it shows logs like:
` 127.0.0.1 --> 149.154.175.50 match IPCIDR using PROXY`. 
How can i solve this problem? Thanks

**Comment by Dreamacro** [comment]
Telegram dial IP directly instead of using a domain. TUN mode does not work with this now.

**Comment by L0snight** [comment]
Thanks for replying

**Comment by black-desk** [comment]
I meet this same problem today. Is tun still cannot work with telegram?
