### ISSUE TITLE
设置为系统代理之后无法打开ftp页面

### ISSUE THREAD

**Issue by hongwanzhang** [Dreamacro/clash#445]
你好，设置为系统代理之后无法打开ftp页面，请问这是为什么？需要怎么设置？

**Comment by hongwanzhang** [comment]
搞定了，过滤关键词ftp就行了

**Comment by xiaolaiyuguo** [comment]
兄弟，方便说说详细操作么？我用v2rayx可以打开ftp页面，clashr不能。

**Comment by hwanz** [comment]
> 兄弟，方便说说详细操作么？我用v2rayx可以打开ftp页面，clashr不能。

clash for windows：设置—system proxy bypass—过滤ftp

**Comment by saytesnake** [comment]
@hwanz 老哥，我也遇到了这样的问题，bypass 应该怎么写才能过滤 ftp，我尝试了各种写法都不行，clash for windows，挺苦恼的。
