### ISSUE TITLE
日志等级

### ISSUE THREAD

**Issue by updater1234** [Dreamacro/clash#45]
请问可以在log-level里添加一个none的等级吗，即不显示任何日志？

**Comment by Dreamacro** [comment]
加了个 `silent` 等级，不过建议还是使用 `error` 或者 `warning`

**Comment by squallgold** [comment]
> 加了个 `silent` 等级，不过建议还是使用 `error` 或者 `warning`

请问debug日志能记录LAN过来的源IP地址吗？如果有多个内网IP通过clash FQ出去，我想要保留访问记录如：时间，源IP，目标IP/域名/URL等。
