### ISSUE TITLE
[Feature Request] 添加 VMess Mux 支持

### ISSUE THREAD

**Issue by bcd61** [Dreamacro/clash#450]
部分机场使用cdn，可能会限制单ip并发数量，未开启Mux情况使用下会造成大量 HTTP 429 错误，致使基本上网需求的功能部分瘫痪，同状态下使用其他软件开启Mux未出现异常。
之前的issue里开发者提到VMess协议并未适配支持Mux，但代码中Shadowsocks的V2ray-plugin进行了简单的适配。现请求实现完整的VMess Mux功能。

**Comment by thank243** [comment]
这个并不会增加网速，最多降低连接时间，具体去官网翻手册

**Comment by bcd61** [comment]
@thank243 与网速等问题不相关，请看问题描述，CDN 返回 429 Too Many Requests 错误

**Comment by AvailCat** [comment]
Same here.

It's useful for user who own a server with high latency with TLS + WebSocket. TTFB > 1.2s really awful.

**Comment by Dreamacro** [comment]
V2ray 里包含的 Mux.Cool 协议与代理协议过于耦合，属于设计不合理（与另一个真正和协议无关的 mux https://github.com/xtaci/smux 对比来说），所以暂时不打算做这个支持

**Comment by XuuKoo** [comment]
> 
> 
> V2ray 里包含的 Mux.Cool 协议与代理协议过于耦合，属于设计不合理（与另一个真正和协议无关的 mux https://github.com/xtaci/smux 对比来说），所以暂时不打算做这个支持

trojan-go的smux有计划支持吗？
