### ISSUE TITLE
一部分应用在fake-ip模式下不能上网

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#452]
我试图通过用fake-ip替换redir-host来减少使用美国服务器时漫长的域名解析时间，但是我发现国服的星际争霸2游戏在fake-ip模式下无法联网，我大概了解fake-ip和redir-host的区别，我理解中这种情况大概率是因为客户端使用了写死的ip替代了域名，我试图通过日志找到这个固定的ip，但是没有找到，是否有什么方法可以找到这个固定的ip？

**Comment by Dreamacro** [comment]
IP 的话目前应该走的是直连
