### ISSUE TITLE
请问怎样才能在开启clash windows系统全局代理的情况下，同时在chrome上用代理插件？

### ISSUE THREAD

**Issue by leahhartman** [Dreamacro/clash#454]
请问怎样才能在开启clash windows系统全局代理的情况下，同时在chrome上用代理插件？实现电脑全局的clash代理IP跟Chrome的插件代理IP不一样，也就是Chrome用Chrome的IP，电脑用电脑的IP。我试了，是chrome打不开网页了。求解决办法，万分感谢...

**Comment by liby** [comment]
没看懂你的 issue，
不过盲猜你需要 [Proxy SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif)
怎么用，自行搜索

**Comment by sceraser** [comment]
你的意思是在关闭全局代理的情况下，Chrome任然可以代理？

**Comment by BirkhoffLee** [comment]
Proxy SwitchyOmega is a good solution. This is not related to Clash core.

**Comment by necowong** [comment]
> 请问怎样才能在开启clash windows系统全局代理的情况下，同时在chrome上用代理插件？实现电脑全局的clash代理IP跟Chrome的插件代理IP不一样，也就是Chrome用Chrome的IP，电脑用电脑的IP。我试了，是chrome打不开网页了。求解决办法，万分感谢...

我也有这个需求
