### ISSUE TITLE
[BUG] UDP Reject not working

### ISSUE THREAD

**Issue by Kr328** [Dreamacro/clash#455]
Reject 没有声明 UDP 支持
https://github.com/Dreamacro/clash/blob/6ce7b6ef835726ff0875f63cbbfeddc3975165ee/adapters/outbound/reject.go#L20-L27

在 tunnel 进行匹配时
https://github.com/Dreamacro/clash/blob/6ce7b6ef835726ff0875f63cbbfeddc3975165ee/tunnel/tunnel.go#L303-L314

UDP 遇到 Reject 只会 忽略 并匹配下一条规则

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/commit/9dda9324947ffce869b10aa6e34a1d51bc030b06 fixed
