### ISSUE TITLE
有没有什么方法可以自动连接可以访问的线路? Is there any way to timeout automatically switch to an accessible line?

### ISSUE THREAD

**Issue by inwikipedia** [Dreamacro/clash#456]
有没有什么方法可以让当前timeout的线路自动连接可以不是timeout的线路
![image](https://user-images.githubusercontent.com/644260/71568786-d57faf80-2b04-11ea-9f4b-ac419231f81a.png)

Is there any way to make the current timeout line automatically connect the line that is not timeout

**Comment by Dreamacro** [comment]
Proxy Group `url-test` and `fallback`

**Comment by vanppo** [comment]
> Proxy Group `url-test` and `fallback`

这两种 type 有什么联系么，如果 url-test 分组里面所有节点都挂掉了，是不是自动会去  fallback 里面找呢？
