### ISSUE TITLE
[BUG or Feature?] HTTP Provider Vehicle  

### ISSUE THREAD

**Issue by Kr328** [Dreamacro/clash#457]
https://github.com/Dreamacro/clash/blob/9dda9324947ffce869b10aa6e34a1d51bc030b06/adapters/provider/vehicle.go#L72-L105

目前 一些些 小小的 问题

1. HTTP 请求 无视 Status Code
预期行为应该是 仅 2xx 的 response 才算成功 吗 (
2. provider 配置 即使 **解析失败** 也会被 持久化
预期行为应该是 解析成功 了 再 持久化 吗 (

**Comment by Dreamacro** [comment]
1 不打紧的，不管怎么样后面都要解析。2 是 bug

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/commit/b19a49335fdbccc60794903c01e230e074d41169 fixed
