### ISSUE TITLE
不知后期能加入脚本支持吗？

### ISSUE THREAD

**Issue by jiahe224** [Dreamacro/clash#459]
不知后期能加入脚本支持吗？得知网友用圈的脚本功能来屏蔽微信公众号的广告，但目前安卓平台还没有支持脚本的代理App，急需从0到1。问了clash for Android的作者，回复说需要母程序支持，所以非常希望能加入

**Comment by Dreamacro** [comment]
如果你指的是 quan surge 这种类型的脚步，那大概率是没有。如果是 #272，那还是会有的

**Comment by jiahe224** [comment]
> 如果你指的是 quan surge 这种类型的脚步，那大概率是没有。如果是 #272，那还是会有的

想说的是Quantumult，既然没有的话，那看来安卓想屏蔽微信公众号广告只能root后用xposed了

**Comment by zfk513** [comment]
> > 如果你指的是 quan surge 这种类型的脚步，那大概率是没有。如果是 #272，那还是会有的
> 
> 想说的是Quantumult，既然没有的话，那看来安卓想屏蔽微信公众号广告只能root后用xposed了

啥软件可以屏蔽微信公众号和朋友圈广告?
