### ISSUE TITLE
windows chrome 使用 switchyomega 插件时内存上涨导致标签页崩溃

### ISSUE THREAD

**Issue by ShadowLyin** [Dreamacro/clash#46]
这问题已经在这里讨论过
https://github.com/Fndroid/clash_for_windows_pkg/issues/11
最后发现是reject规则导致页面崩溃

**Comment by beyondkmp** [comment]
@ShadowLyin 有空可以帮忙测试下

**Comment by ShadowLyin** [comment]
> @ShadowLyin 有空可以帮忙测试下

我不知道如何测试，我只是一个cfw用户。。

**Comment by Dreamacro** [comment]
Fixed in #47
