### ISSUE TITLE
[Feature Request]在已经安装GeoLite2的情况下，不再下载

### ISSUE THREAD

**Issue by YangtseSu** [Dreamacro/clash#460]
一些linux发行版，例如Archlinux官方源中有geoip2-database。
community/geoip2-database 20191203-1
    GeoLite2 IP geolocation databases compiled by MaxMind

希望能检测系统是否存在数据库，在存在的情况下，不再尝试下载。

**Comment by Dreamacro** [comment]
不缺这 4 MB 吧？实在不想维护两份可以自己 ln 软链一下吧？

**Comment by nb5p** [comment]
这位大哥可能是想用系统的包管理器管理IP databases

**Comment by Dreamacro** [comment]
@nb5p 软链他不好用吗

**Comment by YangtseSu** [comment]
initial mmdb的时候再加个if，检测系统有没这个文件，有的话自动给ln -s就更香了。
没空就算了，无伤大雅。

**Comment by Dreamacro** [comment]
@YangtseSu pacman 的包地址难道和 apk、apt、snap 的一样吗？这是一个无底洞
