### ISSUE TITLE
0.17.0版本程序意外中止

### ISSUE THREAD

**Issue by thank243** [Dreamacro/clash#462]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x7e267c]

goroutine 38 [running]:
github.com/Dreamacro/clash/dns.(*Resolver).FakeIPEnabled(...)
	/home/runner/work/clash/clash/dns/resolver.go:171
github.com/Dreamacro/clash/dns.(*Resolver).IsFakeIP(...)
	/home/runner/work/clash/clash/dns/resolver.go:176
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleUDPConn(0xc0000cb6c0, 0xc000449220)
	/home/runner/work/clash/clash/tunnel/tunnel.go:191 +0x2ec
github.com/Dreamacro/clash/tunnel.(*Tunnel).processUDP(0xc0000cb6c0)
	/home/runner/work/clash/clash/tunnel/tunnel.go:107 +0x50
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	/home/runner/work/clash/clash/tunnel/tunnel.go:117 +0x62

换回16没此问题。

**Comment by Dreamacro** [comment]
dev 昨天修了
