### ISSUE TITLE
0.17版的clash无法运行

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#463]
使用全新的空目录作为配置文件目录时报错下载这个失败`http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz`
无法解析域名geolite.maxmind.com，我直接用我的服务器（在国外）也同样无法访问这个url。

**Comment by soffchen** [comment]
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

不能直接下载了，以后得用 license key

**Comment by cjwddtc** [comment]
那怎么办呢？我被迫从docker镜像里面去解压那个文件，总不能每次都用这种方法吧

**Comment by soffchen** [comment]
Blog 下面写得很清楚了哦，自己注册一个账号，获取 license key，以后直接带 key wget 就可以了

**Comment by wangxin6** [comment]
https://github.com/Dreamacro/maxmind-geoip/releases

**Comment by cjwddtc** [comment]
这个应该在`https://github.com/Dreamacro/maxmind-geoip/releases`应该在readme里面说一下，或者直接把程序中的url替换成这个比较好

**Comment by soffchen** [comment]
dev 分支已经改好了的

**Comment by Dreamacro** [comment]
dev 昨天就修了
