### ISSUE TITLE
[Feature Request] Single mmdb instance & export mmdb load api

### ISSUE THREAD

**Issue by Kr328** [Dreamacro/clash#466]
~~又又又是 Clash for Android 的 问题 (x~~

能不能 导出 mmdb 的 载入 方法 

https://github.com/Dreamacro/clash/blob/14a3ff32f6647fd0262f6239d43a8ea1762c7ca2/dns/resolver.go#L313-L319

https://github.com/Dreamacro/clash/blob/14a3ff32f6647fd0262f6239d43a8ea1762c7ca2/rules/geoip.go#L49-L55

Clash for Android 计划 分割每个 Profiles 的 HomeDir 以 防止 provider 持久化的数据 跨配置

因此 HomeDir 是不定的 
Clash 的 mmdb 载入是 Lazy Load

需要一个立即载入文件或立即从 []byte 中载入 的 API (进程内就好 (不需要 web api

**Comment by comzyh** [comment]
Android 可以 symbol link 吗？

**Comment by Kr328** [comment]
> Android 可以 symbol link 吗？

Google 不保证可用 (
而且打算 允许 把 HomeDir 暴露在 `/sdcard/Android/data/com.github.kr328.clash/files` 下
这个地方一定不能用 (虚拟 `fat32`
