### ISSUE TITLE
v0.17.1/0.17.0开机启动失败，0.16.0正常。请问是什么原因？

### ISSUE THREAD

**Issue by 358985526** [Dreamacro/clash#470]
is:issue is:open clash-linux-armv5-v0.17.1/0.17.0启动项失效？通过命令/clash/clash-linux-armv5 -d /clash & 无法开机运行，0.16.0正常。请问是什么原因？

**Comment by Dreamacro** [comment]
报错呢？

**Comment by 358985526** [comment]
> 报错呢？

没有提示，v0.17.1/0.17.0在终端 通过命令/clash/clash-linux-armv5 -d /clash 可以正常运行，就是添加到开机启动后（rc.local，init.d），开机无法执行，0.16.0可以正常执行。各种开机启动方式都试了，还是不行

**Comment by 358985526** [comment]
> 报错呢？

是不是新版本中/clash/clash-linux-armv5 -d /clash这个命令有变化？

**Comment by Dreamacro** [comment]
没变化过，直接跑没问题说明基本不是我这的问题了。至于具体是什么问题，我没有精力做这个事

**Comment by 358985526** [comment]
解决了，多加一个f，指定配置文件可以开机运行！/clash/clash -d /clash -f /clash/config.yaml
