### ISSUE TITLE
[Bug] Not working when using vmess

### ISSUE THREAD

**Issue by kmahyyg** [Dreamacro/clash#472]
- Binary source: v0.17.1 packed by ArchLinuxCN repo.
- Both VM and Host is under the same network and using the same LAN.
- The SS and V2RAY server on the remote side is confirmed working and NOT blocked by GFW.

System: Both Arch Linux Latest.

- Host can use VMESS proxy server in socks5, redir port not tested.
- VM can only use SS server and works perfectly in both redir port and socks5 port. Clash is running under a isolated UID to make sure it won't get a dead loop.

DNS set to `223.5.5.5` on host, but point to clash itself on VM.

Clash config is set to `fake-ip` DNS mode.

When I test under my VM using `curl --socks5-hostname PROXY:PORT -L -vvv https://github.com`, I get: (148 is my VM local IP.)

![image](https://user-images.githubusercontent.com/16604643/71945668-68ee6a00-3202-11ea-82b8-80ebb6aa9fae.png)

![image](https://user-images.githubusercontent.com/16604643/71946217-24fc6480-3204-11ea-86c3-249f8a6ea20c.png)

Seems SSL handshake is not correctly handled.

**Comment by Dreamacro** [comment]
What I understand is, ss works fine and vmess works unexpected? can you provide dns config and clash log. I guess your ss server is an IP and vmess server is a domain.

**Comment by kmahyyg** [comment]
> What I understand is, ss works fine and vmess works unexpected? can you provide dns config and clash log. I guess your ss server is an IP and vmess server is a domain.

Yes, SS works fine. VMESS cannot get TLS handshake.

DNS Config:

```
dns:
  enable: true
  enhanced-mode: fake-ip
  fallback:
  - 1.1.1.1
  - 223.5.5.5
  - 8.8.8.8
  ipv6: false
  listen: 0.0.0.0:53
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
```

Clash Log:

![image](https://user-images.githubusercontent.com/16604643/71947054-87eefb00-3206-11ea-949b-b093271654b3.png)

![image](https://user-images.githubusercontent.com/16604643/71947084-a228d900-3206-11ea-8c73-0348d09968a3.png)

**Comment by kmahyyg** [comment]
Vmess Server is a domain, SS Server is a domain. 

But there's something different in domain length:

SS Server is : `daily-xxx.xx.nsxxxxxx.xxxxxxxxx.xyz`  (replace letters with x, but ensure length is the same)

V2Ray Server is: `xxxxxxx-xxxxxxxxxxx-xxxx-careful-xxxxxxx.xxxx.xxxxxxxxxx.com`

**Comment by kmahyyg** [comment]
I tried to replace to the corresponding IP, the Vmess still not working.

**Comment by Dreamacro** [comment]
what your v2ray server config?

**Comment by kmahyyg** [comment]
SS:

```
- cipher: chacha20-ietf
  name: 日用专线 香港 01 [0.2]
  password: PASSWORD
  port: PORT
  server: SERVERNAME
  type: ss
```


 V2:
```
- alterId: 38
  cipher: auto
  name: xxxx HK
  port: PORT
  server: SERVERNAME
  type: vmess
  udp: true
  uuid: 918b28e6-xxxx-xxxx-xxxx-d399733ca83f
```

The same config works on my host's Clash, but VM's clash is not working.

**Comment by kmahyyg** [comment]
I tried to run a strace against openssl and curl and clash. 

Got this on clash:

[test.clash.log](https://github.com/Dreamacro/clash/files/4033534/test.clash.log)

Openssl and curl both worked fine. The problem is that the seems while using clash with vmess, the clash responded nothing to curl.

**Comment by kmahyyg** [comment]
The previous problem exists only on Arch Linux Brand NEW installation. I strongly doubt that it's related to system SSL config but no evidence. When I migrated to Debian-based distro, it works perfectly.

Not related to clash itself since golang programs are all static-linked and the SSL implementation is done by golang itself instead of using OpenSSL in my memory.

Thanks for help.
