### ISSUE TITLE
fake-ip-filter里面的*号只匹配当前级别的子域名

### ISSUE THREAD

**Issue by xuan880** [Dreamacro/clash#473]
tun模式下我想要某个域名不走fake IP ,于是通过  fake-ip-filter添加了白名单,结果发现*号只匹配本级别的域名,例如
*.abcd.com
这个规则,可以匹配到www.abcd.com,a.abcd.com这个三级域名,但是a.b.abcd.com这种四级域名,甚至更高级别的域名都无法匹配到.
导致想要让一个域名完全走白名单要添加很多规则.

**Comment by Dreamacro** [comment]
* 只匹配 n 级域名是预期结果，至于多级域名，其他软件有用什么符号来表示吗

**Comment by xuan880** [comment]
>     * 只匹配 n 级域名是预期结果，至于多级域名，其他软件有用什么符号来表示吗

v2ray是通过
domain:abcd.com
来匹配所有的子域名,另一个软件是通过
**.abcd.com
来匹配所有子域名,
*.abcd.com来匹配三级域名.

**Comment by Dreamacro** [comment]
`另一个软件` 指的是？

**Comment by xuan880** [comment]
> `另一个软件` 指的是？

叫goproxy,我没用过只是他的文档中是这样写的.

**Comment by Dreamacro** [comment]
这样啊，那就有待协商。如果是一个通用的常用软件，那倒是可以参考一下

**Comment by Masstone** [comment]
- '*.pool.ntp.org'
     - '*.android.pool.ntp.org'

这样写android.pool.ntp.org会失效。。。。也有点怪

**Comment by yeliex** [comment]
一般会认为 **代表不限层级的匹配? 或者可以支持正则匹配

**Comment by Dreamacro** [comment]
增加了 dot wildcard https://github.com/Dreamacro/clash/commit/65dab4e34f5cd1a09e4d6b8523f16c6f872880e3

**Comment by ShaoNinja** [comment]
如何支持IP地址？
