### ISSUE TITLE
[suggestion] support ssr protocol

### ISSUE THREAD

**Issue by TerriblePanda** [Dreamacro/clash#478]
support ssr protocol
it is used widely.

**Comment by yichengchen** [comment]
pr which is elegant and not implement shadowsocks twice is wellcomed

**Comment by Dreamacro** [comment]
ssr is unmaintainable and prejudiced to me. As @yichengchen says, pr welcome.

**Comment by sh4d0wfiend** [comment]
@Dreamacro Do you mind if I add a basic SSR implementation based on [this library](https://github.com/chanceplus/shadowsocksR)? I suggest we could make SSR usable first and then consider a long-term plan for better integration.

**Comment by Dreamacro** [comment]
@sh4d0wfiend I don't want to spend time with SSR, but PR welcome
