### ISSUE TITLE
全局连接下显示DIRECT

### ISSUE THREAD

**Issue by XiaoTeemo** [Dreamacro/clash#483]
「全局连接」模式下，选中节点 Youtube 可以打开，但显示 DIRECT 。
2020/01/17 16:00:26:637  [info] 127.0.0.1 --> youtube.com doesn't match any rule using DIRECT
2020/01/17 16:00:26:640  [info] 127.0.0.1 --> youtube.com doesn't match any rule using DIRECT

**Comment by Dreamacro** [comment]
显示的 Bug，但不影响使用

**Comment by Dreamacro** [comment]
fixed in dev
