### ISSUE TITLE
clash 透明代理 启动后并未监听53端口

### ISSUE THREAD

**Issue by USDao** [Dreamacro/clash#484]
环境：centos 7.6 作为gw
clash 版本：Clash v0.17.1 linux amd64 Wed Jan  1 10:31:59 UTC 2020
dns配置：
dns:
enable: true
ipv6: false
listen: :53
enhanced-mode: redir-host
nameserver:
  - 119.29.29.29
  - 223.5.5.5
fallback:
  - tls://dns.rubyfish.cn:853
  - https://dns.rubyfish.cn/dns-query
  - https://dns.google/dns-query
启动日志：
 clash -d /etc/clash/
INFO[0000] Start initial compatible provider PROXY      
INFO[0000] Start initial compatible provider Hijacking  
INFO[0000] Start initial compatible provider HKMTMedia  
INFO[0000] Start initial compatible provider GlobalMedia 
INFO[0000] Start initial compatible provider Apple      
INFO[0000] Start initial compatible provider Final      
INFO[0000] Start initial compatible provider Auto       
INFO[0000] HTTP proxy listening at: :7890               
INFO[0000] Redir proxy listening at: :7892              
INFO[0000] SOCKS proxy listening at: :7891              
INFO[0000] RESTful API listening at: 127.0.0.1:9090  

/usr/sbin/sestatus -v  
SELinux status:                 disabled

root启动 
程序可以正常运行，但是就是53端口没起来 是否配置错误呢

**Comment by Dreamacro** [comment]
':53'
