### ISSUE TITLE
请问384梅林改应该使用哪个版本的呢

### ISSUE THREAD

**Issue by harryyifei** [Dreamacro/clash#485]
如题
尝试了armv8无法离线呀

**Comment by Comah** [comment]
哪有那么简单 不是离线包

**Comment by vensterlz** [comment]
需要看路由器版本的。常见的86u可以使用arm8直接运行，复制到路由器上，ssh登录进去设定一下开机启动以及iptables即可。其他的需要检查一下看看。不过，大概率你的梅林是国内改版的，这个不是都有一个软件中心么？

**Comment by harryyifei** [comment]
> 需要看路由器版本的。常见的86u可以使用arm8直接运行，复制到路由器上，ssh登录进去设定一下开机启动以及iptables即可。其他的需要检查一下看看。不过，大概率你的梅林是国内改版的，这个不是都有一个软件中心么？

明白啦，感谢🙏

**Comment by BirkhoffLee** [comment]
@harryyifei 沒問題的話 close issue，謝謝
