### ISSUE TITLE
SOCK5+VMESS协议，UDP无法正常处理

### ISSUE THREAD

**Issue by techblack** [Dreamacro/clash#486]
配置：
#port: 7890
socks-port: 7891
#redir-port: 7892
allow-lan: true
mode: Global

出口为SOCK5，并且使用SSTAP连接
clash使用vmess（websocket）协议日志内会产生大量UDP连接的信息，DNS解析非常缓慢
使用ss协议，DNS解析速度正常，且其他UDP应用也正常

**Comment by techblack** [comment]
连接前使用NatTypeTester测试  NAT type为：PortRestrictedCone
使用同一vmess节点(已经udp:true):
开启V2RAY SOCK5出口，使用SSTAP连接，NAT type为：FullCone
开启Clash SOCK5出口，使用SSTAP连接，NAT type为：UdpBlocked
使用同一ss节点:
开启V2RAY SOCK5出口，使用SSTAP连接，NAT type为：FullCone
开启Clash SOCK5出口，使用SSTAP连接，NAT type为：FullCone

**Comment by techblack** [comment]
Clash 版本：Clash v0.17.1
V2ray版本:   V2Ray 4.21.3

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/commit/26ce3e8814db8249a17f8bfda6ac50572d7ca6ac 为提升 NAT 等级做了一些工作，让 TUN 模式的 UDP 行为更加正常，你也可以试试效果。vmess 协议对于 UDP 的处理是流式的，要做到 fullcone 理论上除了 hack 内部的实现，不然不太可能做到（Outbuound sock5 另说，我没看过他 socks5 的实现）。

**Comment by techblack** [comment]
@Dreamacro    目前是使用vmess的情况下，clash的sock5无法正常处理UDP，比如无法解析IP，或者进行NAT TYPE测试（UdpBlocked），但是换成ss协议一切正常。

然后我又采用了另一种方式：
开启clash vmess协议连接，打开sock5端口在1080上

然后开启v2ray  config.json
 "inbounds": [ 
    {
    "protocol": "socks",
    "port": 1081,
    "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1",
        "userLevel": 0
    }
    }
  ],
  "outbounds": [
  { 
    "tag": "local",  //标识符TAG
    "protocol": "socks",
    "settings": {
      "servers": [{
      "address": "127.0.0.1",
      "port": 1080,
      "auth": "noauth"
      }]
    }
  }
  ],


此时 sock5 1081 UDP正常
就是经过了v2ray中转一下，就可以用了，直接用clash的sock5UDP就是无法使用的

**Comment by techblack** [comment]
未使用V2RAY的clash（vmess）日志。
time="2020-01-31T17:09:57+08:00" level=info msg="Start initial compatible provider Auto"
time="2020-01-31T17:09:57+08:00" level=info msg="RESTful API listening at: 0.0.0.0:9090"
time="2020-01-31T17:09:57+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:1080"
time="2020-01-31T17:10:14+08:00" level=info msg="[UDP] 127.0.0.1 --> 45.32.217.190 match Match using Auto[WIKI]"
time="2020-01-31T17:10:15+08:00" level=info msg="[UDP] 127.0.0.1 --> 8.8.8.8 match Match using Auto[WIKI]"
time="2020-01-31T17:10:16+08:00" level=info msg="[UDP] 127.0.0.1 --> 8.8.4.4 match Match using Auto[WIKI]"
time="2020-01-31T17:10:18+08:00" level=info msg="[UDP] 127.0.0.1 --> 45.32.217.190 match Match using Auto[WIKI]"
time="2020-01-31T17:10:21+08:00" level=info msg="[UDP] 127.0.0.1 --> 45.32.217.190 match Match using Auto[WIKI]"

结果都是没有收到

**Comment by Dreamacro** [comment]
试试 dev 分支的 clash

**Comment by techblack** [comment]
您好，问题依旧存在

**Comment by techblack** [comment]
我觉得问题应该出在这：
```
{
"protocol": "socks",
"port": 1081,
"settings": {
    "auth": "noauth",
    "udp": true,
    "ip": "127.0.0.1", //应该是这里
    "userLevel": 0
}
```
因为我通过抓包发现Source的地址并不是127.0.0.1 可能导致返回来的包错误的选择了返回的地址

**Comment by techblack** [comment]
而v2ray为sock5设置了一个ip address 从而保证了udp可以正确返回

**Comment by techblack** [comment]
并且使用dev版本后，ss的udp也不正常了。 vmess/ss都只能发出一个udp包

**Comment by Dreamacro** [comment]
@techblack socks5 的 udp 在我这正常

**Comment by sealszzz** [comment]
好心人告诉我 dev 分支的 clash，怎么下载，或者该怎么编译

**Comment by techblack** [comment]
> 好心人告诉我 dev 分支的 clash，怎么下载，或者该怎么编译
git clone -b dev https://github.com/Dreamacro/clash.git
