### ISSUE TITLE
tls报错

### ISSUE THREAD

**Issue by updater1234** [Dreamacro/clash#487]
在使用clash for windows观看YouTube时视频中断，然后查看日志发现报错如下

goroutine 6408 [running]:
bytes.(*Buffer).ReadFrom(0xc000057758, 0x9a5da0, 0xc0005a2be0, 0x40a11c, 0x87f420, 0x8eed80)
	c:/go/src/bytes/buffer.go:209 +0x1b9
crypto/tls.(*Conn).readFromUntil(0xc000057500, 0x1424ff8, 0xc000092068, 0x816, 0xc000092068, 0x0)
	c:/go/src/crypto/tls/conn.go:802 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000057500, 0x0, 0x0, 0x0)
	c:/go/src/crypto/tls/conn.go:654 +0x58b
crypto/tls.(*Conn).readRecord(...)
	c:/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc000057500, 0xc0005367dc, 0x2, 0x2, 0x0, 0x0, 0x0)
	c:/go/src/crypto/tls/conn.go:1255 +0x168
io.ReadAtLeast(0x1424fb8, 0xc000057500, 0xc0005367dc, 0x2, 0x2, 0x2, 0x0, 0x5000, 0x7ee)
	c:/go/src/io/io.go:310 +0x8e
io.ReadFull(...)
	c:/go/src/io/io.go:329
github.com/Dreamacro/clash/component/vmess.(*aeadReader).Read(0xc0001b0320, 0xc0006bb000, 0x5000, 0x5000, 0x0, 0x0, 0xc00004c1d8)
	C:/golang-projects/clash/component/vmess/aead.go:82 +0x1c6
github.com/Dreamacro/clash/component/vmess.(*Conn).Read(0xc00059a000, 0xc0006bb000, 0x5000, 0x5000, 0x5000, 0x7ee, 0x0)
	C:/golang-projects/clash/component/vmess/conn.go:47 +0x103
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Read(0xc000525fe0, 0xc0006bb000, 0x5000, 0x5000, 0x7ee, 0x0, 0x0)
	C:/golang-projects/clash/tunnel/tracker.go:37 +0x5f
io.copyBuffer(0x1425328, 0xc000517da0, 0x1425348, 0xc000525fe0, 0xc0006bb000, 0x5000, 0x5000, 0x8d11a0, 0xc000508100, 0x1425348)
	c:/go/src/io/io.go:402 +0x129
io.CopyBuffer(0x1425328, 0xc000517da0, 0x1425348, 0xc000525fe0, 0xc0006bb000, 0x5000, 0x5000, 0x1000000010000, 0xc0003b2360, 0x0)
	c:/go/src/io/io.go:375 +0x89
github.com/Dreamacro/clash/tunnel.relay.func1(0x9b2320, 0xc000517da0, 0x146a6b8, 0xc000525fe0, 0xc0003b2480)
	C:/golang-projects/clash/tunnel/connection.go:125 +0x134
created by github.com/Dreamacro/clash/tunnel.relay
	C:/golang-projects/clash/tunnel/connection.go:123 +0xaa

**Comment by Dreamacro** [comment]
看起来这个二进制不是 release 的，如果还出现再 open
