### ISSUE TITLE
路由器上运行Clash出现的问题

### ISSUE THREAD

**Issue by xingezhang** [Dreamacro/clash#492]
我在ubnt ERX上运行clash，dns无论是设置fake-ip或redir-host，都无法访问google。

redir-host模式的dns设置如下：
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 'tls://dns.rubyfish.cn:853'
    - 'tls://1.1.1.1:853'
    - 'tcp://1.1.1.1'
    - 'tcp://208.67.222.222:443'
    - 'tls://dns.google'

fake-ip模式的dns设置如下：
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114

然后debug时，会报：53被占用，这是因为dnsmasq和clash冲突吗？该如何解决？

启动clash时，有iptables设置如下：
<img width="682" alt="截屏2020-02-0123 20 03" src="https://user-images.githubusercontent.com/13484700/73594444-7f5dbc00-4549-11ea-8058-bc0f5b9380eb.png">

<img width="682" alt="截屏2020-02-0123 20 03" src="https://user-images.githubusercontent.com/13484700/73594484-c8157500-4549-11ea-9ba2-ffecebbaae3d.png">

**Comment by xingezhang** [comment]
问题解决了，少写了一个iptables规则
iptables -t nat -A PREROUTING -p tcp -j clash

**Comment by xingezhang** [comment]
截图上传看不到
再试一次
<img width="682" alt="截屏2020-02-0123 20 03" src="https://user-images.githubusercontent.com/13484700/73594489-dbc0db80-4549-11ea-8e8d-edd6b3114b71.png">

**Comment by thank243** [comment]
listen: 0.0.0.0:53 改为其他端口。然后去dnsmasq转发

**Comment by xingezhang** [comment]
@thank243 非常感谢您的回复，问题已经解决了。

**Comment by gcl52** [comment]
> @thank243 非常感谢您的回复，问题已经解决了。

请问有er4的clash吗？请求帮助，如何联系你？谢谢！
