### ISSUE TITLE
Clash在lede下崩溃

### ISSUE THREAD

**Issue by luoyi519** [Dreamacro/clash#493]
我的clash装在lede上功能运行正常，但时不时会崩溃，被watchdog重启，平均1天一次，看了下debug的日志又正常，问下还有什么方法可以查下崩溃的原因(或者其他的日志)，多谢

UI: vernesong / OpenClash
LEde: 17.01

**Comment by luoyi519** [comment]
路由器比较老wndr4300
用的内核是https://github.com/Dreamacro/clash/releases/download/v0.17.1/clash-linux-mips-softfloat-v0.17.1.gz

**Comment by Dreamacro** [comment]
崩溃栈在 stdout 或 stderr 上

**Comment by peterwjp2017** [comment]
> 路由器比较老wndr4300
> 用的内核是https://github.com/Dreamacro/clash/releases/download/v0.17.1/clash-linux-mips-softfloat-v0.17.1.gz

WNDR4300用clash很消耗资源 不知道为什么

**Comment by luoyi519** [comment]
> 崩溃栈在 stdout 或 stderr 上

实在没找到stdout和stderr，也没找到有转储的迹象。
但发现vsz超高，感觉像是 wndr4300 的小内存跑softfloat 内核内存不够引起的。

 PID  PPID USER     STAT   VSZ   %VSZ %CPU  COMMAND
19223     1 root       S        660m  539%   1%   /etc/openclash/clash -d /etc/openclas
 1324     1 root        S         1684   1%   1%       /usr/sbin/hostapd -s -P /var/run/wifi
13621     2 root       SW       0        0%   1% [kworker/0:1]

**Comment by luoyi519** [comment]
> > 路由器比较老wndr4300
> > 用的内核是https://github.com/Dreamacro/clash/releases/download/v0.17.1/clash-linux-mips-softfloat-v0.17.1.gz
> 
> WNDR4300用clash很消耗资源 不知道为什么
WNDR4300好像只能用softfloat，比较费cpu，ytb 2k cpu差不多要20%～40%

**Comment by thank243** [comment]
![image](https://user-images.githubusercontent.com/11692994/73838411-943e9600-484e-11ea-9f9f-ea0b91c5c997.png)
我也是，每次出现这个情况就会崩。之前0.16版本很少出现。

**Comment by thank243** [comment]
> > 崩溃栈在 stdout 或 stderr 上
> 
> 实在没找到stdout和stderr，也没找到有转储的迹象。
> 但发现vsz超高，感觉像是 wndr4300 的小内存跑softfloat 内核内存不够引起的。
> 
> PID PPID USER STAT VSZ %VSZ %CPU COMMAND
> 19223 1 root S 660m 539% 1% /etc/openclash/clash -d /etc/openclas
> 1324 1 root S 1684 1% 1% /usr/sbin/hostapd -s -P /var/run/wifi
> 13621 2 root SW 0 0% 1% [kworker/0:1]
我软路由跑。直接112M内存就没了

**Comment by thank243** [comment]
这几天观察了下，应该是进去死循环了。output表会redir fakeip地址回redir端口，进去后由于映射丢失，路由器继续向外请求fakeip，然后又进入output表。楼主改成redir-host看故障继续存在不？但是，路由器本身就不能代理了。

**Comment by luoyi519** [comment]
我这个clash用的是 vernesong / OpenClash的执行文件，和这里的不一样，另外查了一下wndr4300只能用软件模拟浮点。
