### ISSUE TITLE
fallback 组的一个问题

### ISSUE THREAD

**Issue by neteroster** [Dreamacro/clash#496]
### 描述
现有两个 Shadowsocks 服务器 A 和 B。在一个 fallback 组中只有这两个服务器。A 优先。

正常访问时，所有请求均通过 A。此时切断 A 服务器上的 Shadowsocks 服务，可以发现接下来除前几个超时的请求，其余请求会立刻被导向服务器 B。

此时重新启动 A 服务器上的 Shadowsocks 服务并结束 B 上的服务，clash 在下一个 fallback 自动测速之前都会试图连接服务器 B（手动点击 Dashboard 的“测速”也能立刻让 clash 切换服务器）。

请问这是正常现象吗？是否能在连接失败后即时检查服务器可用性并切换呢？

谢谢！

**Comment by Dreamacro** [comment]
对的，现在不会在全部都失效的时候重新进行一次健康检查，不过这个应该可以加

**Comment by neteroster** [comment]
谢谢！期待加入。
