### ISSUE TITLE
Mojave Beta6 检察系统更新失败&Siri问题依旧

### ISSUE THREAD

**Issue by Tsahao** [Dreamacro/clash#5]
断开代理后均恢复

**Comment by Dreamacro** [comment]
手头上暂时没有 Mojave 的机子，但之前 App Store 不能下载的情况的确有，更新过后现在 High Sierra 下都是正常的。

所以如果可以的话，请提供一些失败的信息，我才能更好地定位问题。

**Comment by Tsahao** [comment]
Siri problem and software update check solved on beta 7 yesterday. It may be a system bug.
