### ISSUE TITLE
经过clash代理的ssh无法正常连接，直连正常

### ISSUE THREAD

**Issue by ZvonimirSun** [Dreamacro/clash#50]
如题，我在``xshell``里设置了``clash``的``http``端口和``socks``端口，均无法正常建立ssh连接。
- 远程服务器直连正常，所以不是ssh的问题。
- 代理选择该节点能够正常访问谷歌等网站，且同一个节点使用v2rayn能够正常建立ssh连接，排除节点问题。
- 另外，通过规则后直连的远程主机能够正常建立ssh连接，通过规则后需要代理的主机则无法建立ssh连接。
- 使用的是``clash for windows 0.4.4``，核心使用的是最新``dev``版本的``clash``。
![image](https://user-images.githubusercontent.com/22871764/49153850-e5512100-f351-11e8-89a1-9044198919c9.png)

**Comment by beyondkmp** [comment]
有clash日志吗？

Sun Ziyang <notifications@github.com> 于 2018年11月28日周三 21:09写道：

**Comment by ZvonimirSun** [comment]
```
time="2018-11-28T20:54:27+08:00" level=info msg="myiphere match FINAL using Others"
```
这样的日志吗？我用的lhie的规则，Others走代理。

**Comment by Dreamacro** [comment]
macOS 下 ok，用的是 `ProxyCommand nc -x localhost:7891 -X 5 %h %p`

**Comment by beyondkmp** [comment]
看你的截图怎么端口是1080

Dreamacro <notifications@github.com> 于 2018年11月28日周三 21:20写道：

**Comment by ZvonimirSun** [comment]
@beyondkmp 我这么设置的。
```
port: 1080
socks-port: 1081
redir-port: null
allow-lan: true
mode: Rule
log-level: debug
external-controller: '127.0.0.1:9090'
secret: ''
```

**Comment by ZvonimirSun** [comment]
@Dreamacro 我是windows端的，用的``clash for windows``，不知道该怎么处理啊。

**Comment by Dreamacro** [comment]
windows 下没有类似 `~/.ssh/config` 这样的配置吗，如果有试试我上面那个

**Comment by ZvonimirSun** [comment]
@Dreamacro windows powershell里的ssh好像不行，不加这句直连可以，加了就显示下面的，我弄个linux子系统试试。
```
CreateProcessW failed error:2
posix_spawn: No such file or directory
```

**Comment by ZvonimirSun** [comment]
@Dreamacro 顺便我发现``config.yml``里的``log-level``似乎没有用，log文件里一直都是``info``级别。

**Comment by Dreamacro** [comment]
配置里的等级是二进制 stdout 的输出等级，GUI 里面调用日志接口是自己控制等级的

**Comment by beyondkmp** [comment]
> ```
> time="2018-11-28T20:54:27+08:00" level=info msg="myiphere match FINAL using Others"
> ```
> 这样的日志吗？我用的lhie的规则，Others走代理，不知道还有没有其他的日志，这边只有简单的。@beyondkmp

这个规则能不能改下，改成最简单的Proxy，就用一个规则

**Comment by derekwei** [comment]
如果 Clash 能支持多种协议就是个完美的系统代理管理工具了。希望能加入 HTTP, HTTPS 等协议支持

**Comment by beyondkmp** [comment]
> 如果 Clash 能支持多种协议就是个完美的系统代理管理工具了。希望能加入 HTTP, HTTPS 等协议支持

#52

**Comment by Dreamacro** [comment]
@ZvonimirSun 还有什么疑问吗

**Comment by MutingLeng** [comment]
@ZvonimirSun MobaXterm Personal 10.6 + cfw v 0.5.3 ，同样无法使用 cfw 的 socks5 或 http 代理连接 SSH 。请问你的 xshell 的问题解决了吗？

**Comment by ZvonimirSun** [comment]
没解决呢，搞不懂该怎么弄，我现在xshell上就暂时直接直连了。

MutingLeng <notifications@github.com> 于 2018年12月6日周四 12:03写道：

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/49692895-e713b380-fb9f-11e8-89fd-c57f95846e71.png)
试不出来，都正常连接

**Comment by Sansui233** [comment]
挖个坟，我也遇到这个问题很久都不知道为啥，今天突然解决了，因为我清除了所有known_hosts……用socks5代理时ssh会使用之前的存在的known_hosts而不是/etc/hosts文件里指定的ip（并不知道为什么）

**Comment by cesaryuan** [comment]
来挖个坟，一样的问题，楼主有解决办法吗？我试了同一个节点，用Clash不行，但是用WinXray可以
![image](https://user-images.githubusercontent.com/35998162/155509273-379bc07a-48d1-4b86-b26f-e5ae4c95fd9f.png)
Log里明明有记录，就是连不上
![image](https://user-images.githubusercontent.com/35998162/155509468-f89abde6-1d98-4541-862f-a3c97626a0f7.png)

**Comment by dislikediss** [comment]
我也遇到了这样的问题，是通过shellclash连接的

**Comment by lzcxhwmy** [comment]
我也遇到了这个问题，只要ssh服务器走代理就没法连接，我通过把ssh服务器的ip设为DIRECT解决了问题。

**Comment by AdamYoung71** [comment]
> 我也遇到了这个问题，只要ssh服务器走代理就没法连接，我通过把ssh服务器的ip设为DIRECT解决了问题。

请问一下是怎么改的呢？是在profile文件里加一条 - IP-CIDR, x,x,x,x, DIRECT 这样的吗？

**Comment by LetterLiGo** [comment]
我也来记录一下，clash和V2rayN等如果设置的代理端口是socks 7890，但是走http的话默认端口号+1，所以要在~/.ssh/config中写代理为：
Host github.com
  User git
  ProxyCommand connect -H 127.0.0.1:7891 %h %p

**Comment by AdamYoung71** [comment]
> 

刚试了一下还是不行，报错也变成这样了。
zsh:1: command not found: connect
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

**Comment by Gohan** [comment]
> > 
> 
> 刚试了一下还是不行，报错也变成这样了。 zsh:1: command not found: connect kex_exchange_identification: Connection closed by remote host Connection closed by UNKNOWN port 65535

今天遇到了一样的问题, 折腾了好一阵子, 对面的 ssh 端口是否是默认的 22?
我把对面端口改成自定义的, 就可以连接了.. 不太懂是为什么

**Comment by Gohan** [comment]
> 挖个坟，我也遇到这个问题很久都不知道为啥，今天突然解决了，因为我清除了所有known_hosts……用socks5代理时ssh会使用之前的存在的known_hosts而不是/etc/hosts文件里指定的ip（并不知道为什么）

可以是这个原因.. #挖坟

**Comment by Cphilo** [comment]
之前一直可以的 不太清楚原因 直连的话确实可以 但是通过socks5就会报错
```bash
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

**Comment by ChongChengAC** [comment]
> > 
> 
> 刚试了一下还是不行，报错也变成这样了。 zsh:1: command not found: connect kex_exchange_identification: Connection closed by remote host Connection closed by UNKNOWN port 65535

对于Proxycommand，linux上用nc命令，windows上用connect，可以参考[这篇文章](https://ericclose.github.io/git-proxy-config.html)

**Comment by programmer-zheng** [comment]
> 我也来记录一下，clash和V2rayN等如果设置的代理端口是socks 7890，但是走http的话默认端口号+1，所以要在~/.ssh/config中写代理为： Host github.com User git ProxyCommand connect -H 127.0.0.1:7891 %h %p

我Windows下添加后，提示 `CreateProcessW failed error:2
posix_spawnp: No such file or directory`
