### ISSUE TITLE
运行时出现的问题

### ISSUE THREAD

**Issue by gxd18** [Dreamacro/clash#503]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7bcbe9]

goroutine 321 [running]:
github.com/Dreamacro/clash/dns.(*geoipFilter).Match(0xcc56a8, 0xc0000b0a98, 0x4, 0x4, 0x0)

127.0.0.1:9090 显示{"hello":"clash"}
访问其他的网站失败

**Comment by Dreamacro** [comment]
就不能贴完整一点吗，看起来像是你的 mmdb 有问题

**Comment by gxd18** [comment]
现在这个问题没有啦，成功后浏览器访问显示建立安全链接失败

**Comment by Dreamacro** [comment]
53 等低端口需要 sudo

**Comment by gxd18** [comment]
没毛病啊，sudo后ERRO[0000] Start DNS server error错误确实没有啦，浏览器端仍显示建立安全链接失败啊
![图片1](https://user-images.githubusercontent.com/51391223/74295049-c14fe480-4d37-11ea-826a-3ff42a7b5d0c.png)

**Comment by Dreamacro** [comment]
不知道你用什么平台的什么 clash 客户端，你这个 dashboard 颜色不对

**Comment by gxd18** [comment]
linux下的clash-linux-amd64-v0.17.1

**Comment by gxd18** [comment]
这个东西必须使用pm2嘛

**Comment by Dreamacro** [comment]
@gxd18 没有要求，你这个 dashboard 为什么是紫色的

**Comment by gxd18** [comment]
这个我也不清楚啊，下午换了一个yaml文件，还是不可以。包就是在这里下的

**Comment by Dreamacro** [comment]
删除 Country.mmdb 然后重新下

**Comment by gxd18** [comment]
我又重新下载了一次，您看看是不是这个（我下载的是GeoLite2 Country )ps:谢谢您这么多次的耐心回答
![图片1](https://user-images.githubusercontent.com/51391223/74511231-7384d900-4efd-11ea-8acf-d439b39aa98f.png)

**Comment by Dreamacro** [comment]
是这个，你也可以到 https://github.com/Dreamacro/maxmind-geoip 去下载
