### ISSUE TITLE
Can not connect websocket in firefox

### ISSUE THREAD

**Issue by MisLink** [Dreamacro/clash#504]
OS: MacOS 1014.6
Firefox: 73.0

It seems a clashx bug, but clashx closed issue so I put it here.

While clashx works on global or rule(the rule includes this site) mode, A website like github using websocket can't establish connections and output these log:
<img width="1664" alt="图片" src="https://user-images.githubusercontent.com/8280169/74269922-44c40280-4d45-11ea-891a-d27efb37b6c6.png">
Chrome doesn't have this problem.

I checked #236, the websocket connections work well if disabled http(s) proxy. Also I tried the command at https://github.com/Dreamacro/clash/issues/236#issuecomment-514153649, I got the expected output.

Firefox network settings chosed "Use system proxy settings".

**Comment by Dreamacro** [comment]
This bug seems interesting. It causes by system socks5 proxy. Firefox and Chrome will use socks5 as Websocket proxy. If your set a socks5 proxy only, all request in Firefox will be failed. But I found out that if you set `Manual proxy configuration` with socks5 proxy by yourself, everything works fine 😂

**Comment by Dreamacro** [comment]
The root cause is that Firefox uses system socks proxy as socks4 instead of socks5. 🌚

**Comment by Dreamacro** [comment]
close because of it's not a clash bug

**Comment by jjhesk** [comment]
how to fix that, i tried all but none works..

**Comment by MisLink** [comment]
> how to fix that, i tried all but none works..

Just use manual proxy config, then you can specify socks version.
