### ISSUE TITLE
 Can't download MMDB

### ISSUE THREAD

**Issue by weienzhang** [Dreamacro/clash#506]
大家好，今天我下载了clash-linux-amd64-v0.17.1，解压运行之后，只在~/.config/clash目录下自动生成了config.yaml，没有Country.mmdb，在把我的配置文件内容复制进config.yaml再次运行可执行文件，会报下面的错误：

INFO[0000] Can't find config, create an empty file      
INFO[0000] Can't find MMDB, start download              
FATA[0030] Initial configuration directory error: Can't download MMDB: Get https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb: dial tcp 13.250.177.223:443: i/o timeout 

另外想问一下怎么配置可以直接在命令行运行clash呢，看了很多教程都没有这个过程的介绍。。。多谢啦

Hello everyone, today I downloaded clash-linux-amd64-v0.17.1. After decompression and running, only config.yaml was automatically generated in the ~ / .config / clash directory. There is no Country.mmdb. Copy into config.yaml and run the executable again, it will report the following error:

INFO [0000] Can't find config, create an empty file
INFO [0000] Can't find MMDB, start download
FATA [0030] Initial configuration directory error: Can't download MMDB: Get https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb: dial tcp 13.250.177.223:443: i / o timeout

In addition, I want to ask how to configure to run clash directly from the command line. After reading many tutorials, this process is not introduced. . . thanks

**Comment by xingezhang** [comment]
1. 可以手动下载，复制到指定目录。
2. 命令行运行命令：clash-linux-amd64 -d  config目录，也可以自己写一个service，开机启动

**Comment by Langyaer** [comment]
请问mmdb文件和yaml文件是什么关系，有什么作用

**Comment by liyongzheng666** [comment]
您好，我下载了一个Country放进去，还是提示我要下载。这种情况不知道您遇到过没

**Comment by mengranhu** [comment]
点开看看，country里面是不是正常的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 剑指牛马 ***@***.***>
发送时间: Saturday, May 14, 2022 2:07:17 PM
收件人: Dreamacro/clash ***@***.***>
抄送: Vanilla ***@***.***>; Comment ***@***.***>
主题: Re: [Dreamacro/clash] Can't download MMDB (#506)


您好，我下载了一个Country放进去，还是提示我要下载。这种情况不知道您遇到过没

―

**Comment by william20210206** [comment]
> 您好，我下载了一个Country放进去，还是提示我要下载。这种情况不知道您遇到过没

https://github.com/Dreamacro/clash/issues/854#issuecomment-1656675350 我的发现和方法
