### ISSUE TITLE
FATA[0372] Initial configuration directory error: Can't download MMDB: read tcp 192.168.101.25:43690->52.217.38.12:443: read: connection reset by peer 

### ISSUE THREAD

**Issue by ChunjieShan** [Dreamacro/clash#517]
版本为clash-linux-amd64-v0.17.1.gz

您好，我在使用clash之时，输入./clash，显示下载mmdb失败，bug信息为：
FATA[0372] Initial configuration directory error: Can't download MMDB: read tcp 192.168.101.25:43690->52.217.38.12:443: read: connection reset by peer 
请问应当如何解决呢？感谢！

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/maxmind-geoip/releases 下一个放进去

**Comment by ChunjieShan** [comment]
> https://github.com/Dreamacro/maxmind-geoip/releases 下一个放进去

感谢，我下载后重新运行，发现又报了这个bug
FATA[0000] Parse config error: ProxyGroup Proxy: 'proxies' is not a slice

**Comment by Dreamacro** [comment]
@ChunjieShan 检查你的配置文件，不要有多余的无用配置

**Comment by ChunjieShan** [comment]
> @ChunjieShan 检查你的配置文件，不要有多余的无用配置

我把原来的clash和.config里面的clash给删除后重新安装，执行./clash d .后还是报这个错，执行./clash后它又报了这个bug：FATA[0000] Parse config error: Configuration file /home/chunjieshan/.config/clash/config.yaml is empty

**Comment by Dreamacro** [comment]
字面意思啊，你配置是空的
