### ISSUE TITLE
[Feature Request] Port Trunk and Multipath TCP

### ISSUE THREAD

**Issue by lincolnguang** [Dreamacro/clash#518]
## What is Port Trunk?

**Port Trunk** refer to aggregation of two or more data link, and provide a single network for transport. 

When user connected to different networks at the same time, for example users connect to route (or routes) by wireless and LAN , clash can provider a high performance or high reliable network.

Port Trunk will provider following opinions:

1. Active-Backup: Only use one data link at a time, when this data link is down, Clash will automatically use another.
2. Load-Balance-Reduce-Latency: Clash will using the lowest latency data link for each server. 
3. Load-Balance-Round-Robin: Distribute traffic by sending packets sequentially to each data link.
4. Load-Balance-Dynamic: Complex algorithms are used to integrate network cards, calculate aggregation speeds, and standardize duplex settings to provide load balancing and fault tolerance.
6. Combine: Sending the same packet to all data link, and get fragment traffic at same time.

## What is Multipath TCP?

**Multipath TCP** (aka. mptcp) is an extension of a TCP protocol that allows two host to maintain the **same TCP** using multiple data links, such as voicing chating using 4G network automatically when WiFi signal is low.

Multipath TCP will provider following opinions:

1. Active-Backup: Only use one data link at a time, when this data link is down, Clash will automatically use another
2. Reduce-Latency: Using the lowest latency data link for each server. 
3. Combine: Sending packet fragment to all data link and receiving packet fragment from all data link, provide the lowest latency and highest performance.

Multipath TCP needs additional compatibility on proxy server. [More information](https://multipath-tcp.org/pmwiki.php/Users/HowToInstallMPTCP)

## What is different between Multipath TCP and Port Trunk?

Port Trunk is quite different with Multipath TCP. Both of them can provider a high performance or high reliable network. Clash should works only in one mode.

Multipath TCP always use **same TCP** on multiple data links to maintain connection between two host. Connections will automatically choose a right data links. When connections have to change to another data links, connections will still keep connected. Multipath TCP needs additional compatibility on proxy server, and if server doesn't have compatibility measures, Multipath TCP will not work correctly, especially on direct policy.

At the same time, in port trunk, one TCP links only connection on **one data links**. So when connections have to change to another data links, they will be discarded. However, port trunk works well in both proxy and direct policy in most of operational environment.

## Usage Scenario

Router and Mobile Phone.

Now clash only works in one data links.

Mobile phone is one typical scenario, typically they have at least two data links. At the same time, more and more people's mobile phone data plan is a unlimited plan. So Multipath TCP or Port Trunk can provide high quality network.

Router is the other, benefit from openWRT, users can easily config multi-PPPoE or PPPoE in different network provider. 
By the way, due to realise of netstack TUN setup need to use mark, openWRT built-in Multipath TCP and Port Trunk will loss efficacy, so Multipath TCP or Port Trunk support is also every important in Router.

**Comment by Dreamacro** [comment]
Trunking seems working on layer 2 and mTCP should write a tcp/ip stack. The ROI is too small to write it on an open-source project.
