### ISSUE TITLE
[Question] 新版发布计划

### ISSUE THREAD

**Issue by wongsyrone** [Dreamacro/clash#520]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [x] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

我发现有一些dev分支的commit没有合并到master分支中，那些大部分和UDP有关，我们是Clash下游(https://github.com/trojan-gfw/igniter-go-libs) ，想确认当前UDP修复的状态以及是否有新版发布计划。目前下游使用的是 
 (https://github.com/Dreamacro/clash/commit/f69f635e0b0ada91f68be3a8566cf36e51f81818) ，我们目前正在追踪UDP forwarding的bug。

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by Dreamacro** [comment]
UDP forwarding 具体那部分出了问题，能具体描述下吗？目前应该有主要两个 inbound 一个是 socks5 一个是 TUN。TUN 的 inbound 应该是没什么太大问题，我这都能正常使用。socks5 的 udp client 主要的问题是我找不到除 tun2socks 之外的能测试 socks5 inbound 的工具

**Comment by wongsyrone** [comment]
这里有下游的讨论串，目前我个人还没办法精确复现：https://github.com/trojan-gfw/igniter/issues/68

**Comment by wongsyrone** [comment]
我解释一下流程，默认绕过中国模式是先走clash，经过规则匹配后进go-tun2socks，全局是直接go-tun2socks。正在分别排除过程中

**Comment by Dreamacro** [comment]
@wongsyrone 目前修复了一个 socks5 inbound 可能的问题，如果你需要下游跟进 dev 分支的话，有一个最简单的办法: 在 go.mod 里把版本改成分支名 dev。然后运行 `go mod tidy` 即可。

**Comment by wongsyrone** [comment]
感谢，我先跟进 dev 分支了，只要没有 force push 就OK
