### ISSUE TITLE
如何设置clash同时使用IKEv2 类型的vpn和机场？

### ISSUE THREAD

**Issue by abletrue** [Dreamacro/clash#521]
请教各位大神，有没有办法设置clash 来实现用机场逛谷歌学术，点击链接以后就使用学校vpn？

拆分一下我的问题，
1 clash可以设置IKEv2类型的VPN么？
2 clash 可以同时使用 vpn和机场么？
3 我大概知道是通过 config.yaml设置规则来分流，可是因为前两个问题不知道怎么解决所以虽然修改了 config文件也没用。

不知道怎么修改config 文件，就瞎添加了一个Proxy，也不知道这个type是不是对的，port应该是哪里找。。我的vpn只教我们在iphone里面点击添加VPN然后选择IKEv2，然后按照提示输入地址账号密码即可。。。
下面是我瞎修改的内容：
Proxy:
	- name: "IKEv2"
	  type: IKEv2
	  server: vpn.***
	  port: 不知道
	  username: 我的用户名
	  password: 我的密码
	  pls: true
Proxy group:
机场的proxy group好像是会自己随时更新的，不知道有没有办法让他更新他的，我自定义的配置保留，
- name: Scholar
  type: select
  proxies:
  - IKEv2
  - DIRECT
  - Domestic
然后在添加具体的网址
- DOMAIN-SUFFIX,nature.com,Scholar
- DOMAIN-KEYWORD,nature,Scholar
- DOMAIN-SUFFIX,sciencedirect.com,Scholar
- DOMAIN-SUFFIX,sciencemag.org,Scholar
- DOMAIN-SUFFIX,oup.com,Scholar
- DOMAIN-KEYWORD,webofknowledge,Scholar
- DOMAIN-SUFFIX,webofknowledge.com,Scholar
- DOMAIN-SUFFIX,wiley.com,Scholar

改完以后完全没有效果。。。还请大神帮小白解惑。。

**Comment by neteroster** [comment]
1 不可以
2 不可以

你需要先弄清楚 VPN 和代理的区别。
