### ISSUE TITLE
[Bug]TUN模式速度慢

### ISSUE THREAD

**Issue by icetea0822** [Dreamacro/clash#532]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [√ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ √] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [√ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: ""
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)

OpenWrt R20.2.15 / LuCI Master (git-20.051.42827-3e80fef)

* 使用者的操作系统 (the OS running on the client)
WIN10

* 网路环境或拓扑 (network conditions/topology)
华硕86u作为主路由，N1作为旁路由。主路由开启HDCP，网关、DNS为N1的IP，N1网关、DNS为86u的IP

* iptables，如果适用 (if applicable)
root@OpenWrt:~# iptables -t nat -nL --line-number
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
2    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
3    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
5    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
6    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0

Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination
1    REDIRECT   tcp  --  0.0.0.0/0            198.18.0.0/16        redir ports 7892

Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0
2    postrouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
3    zone_lan_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
4    zone_vpn_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain MINIUPNPD (1 references)
num  target     prot opt source               destination

Chain MINIUPNPD-POSTROUTING (1 references)
num  target     prot opt source               destination

Chain openclash (1 references)
num  target     prot opt source               destination
1    RETURN     all  --  0.0.0.0/0            0.0.0.0/8
2    RETURN     all  --  0.0.0.0/0            10.0.0.0/8
3    RETURN     all  --  0.0.0.0/0            127.0.0.0/8
4    RETURN     all  --  0.0.0.0/0            169.254.0.0/16
5    RETURN     all  --  0.0.0.0/0            172.16.0.0/12
6    RETURN     all  --  0.0.0.0/0            192.168.0.0/16
7    RETURN     all  --  0.0.0.0/0            224.0.0.0/4
8    RETURN     all  --  0.0.0.0/0            240.0.0.0/4
9    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            redir ports 7892

Chain postrouting_lan_rule (1 references)
num  target     prot opt source               destination

Chain postrouting_rule (1 references)
num  target     prot opt source               destination

Chain postrouting_vpn_rule (1 references)
num  target     prot opt source               destination

Chain postrouting_wan_rule (1 references)
num  target     prot opt source               destination

Chain prerouting_lan_rule (1 references)
num  target     prot opt source               destination

Chain prerouting_rule (1 references)
num  target     prot opt source               destination

Chain prerouting_vpn_rule (1 references)
num  target     prot opt source               destination

Chain prerouting_wan_rule (1 references)
num  target     prot opt source               destination

Chain zone_lan_postrouting (1 references)
num  target     prot opt source               destination
1    MINIUPNPD-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0
2    postrouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan postrouting rule chain */

Chain zone_lan_prerouting (1 references)
num  target     prot opt source               destination
1    MINIUPNPD  all  --  0.0.0.0/0            0.0.0.0/0
2    prerouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan prerouting rule chain */

Chain zone_vpn_postrouting (1 references)
num  target     prot opt source               destination
1    postrouting_vpn_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom vpn postrouting rule chain */
2    FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_vpn_prerouting (1 references)
num  target     prot opt source               destination
1    prerouting_vpn_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom vpn prerouting rule chain */
2    FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_wan_postrouting (0 references)
num  target     prot opt source               destination
1    postrouting_wan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan postrouting rule chain */
2    FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_wan_prerouting (0 references)
num  target     prot opt source               destination
1    prerouting_wan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan prerouting rule chain */
2    FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
不清楚

* 其他
……

### 说明 Description

再TUN模式下，使用speedtest.net ，speedtest.cn测速均只有90M左右，普通模式则可以跑满我的200M带宽。客户端使用openclash，luci-clash也测试过情况相同。请查看一下是否是bug，感谢。

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**
速度正常

**实际上发生了什麽？**
tun模式下速度最高90M左右

**Comment by xuan880** [comment]
你的旁路由是斐讯N1?那么十有八九是CPU性能不够,我试过N1跑旁路由,速度也就只能达到100M左右的带宽,你测速的时候进N1看一下cpu占用就知道了.

**Comment by icetea0822** [comment]
> 你的旁路由是斐讯N1?那么十有八九是CPU性能不够,我试过N1跑旁路由,速度也就只能达到100M左右的带宽,你测速的时候进N1看一下cpu占用就知道了.

正常起码跑200是没问题的，平均在260兆左右沾满我的带宽同时cpu还有富余，只有tun模式下只能到90而且cpu就快满了

**Comment by imgk** [comment]
tun 模式使用 golang 写的网络栈处理流量，其他的模式由系统处理，这个速度就该是正常的吧

**Comment by icetea0822** [comment]
> tun 模式使用 golang 写的网络栈处理流量，其他的模式由系统处理，这个速度就该是正常的吧

如果真是这样那就尴尬了，我使用普通fakeip模式所有联机游戏都进不去，就等着tun模式呢

**Comment by ntgeralt** [comment]
N1 DNS为什么选择主路由IP而不是第三方DNS。感觉后者更合适

**Comment by icetea0822** [comment]
> N1 DNS为什么选择主路由IP而不是第三方DNS。感觉后者更合适

我改过感觉也没什么区别，就换回去了

**Comment by Dreamacro** [comment]
使用新版可以在 fakeip 网关上监听 iperf，来测试理论上的极限速度（可以两个网络栈都测试），一般和 CPU 有关，我的 mbp 极限是 3Gbps。不行就只能切回 redir-port 了。

**Comment by salivarick** [comment]
感觉和 utun 虚拟网卡有关，ethtool 看了一下
![image](https://user-images.githubusercontent.com/6178534/86535082-479bdb80-bf10-11ea-9ba1-973cc27930f7.png)

**Comment by Dreamacro** [comment]
@salivarick 没啥关系，你可以自己 iperf 在 utun 网关上监听测试

**Comment by cielpy** [comment]
J3455 同样只能到 90m 左右
