### ISSUE TITLE
[Bug]DNS不应该缓存状态为SERVFAIL的请求

### ISSUE THREAD

**Issue by CyberKoo** [Dreamacro/clash#538]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
# HTTP 端口
port: 7890

# SOCKS5 端口
socks-port: 7891

# Linux 及 macOS 的 redir 端口
redir-port: 7892

# 允许局域网机器访问
allow-lan: true

# Only applicable when setting allow-lan to true
# "*": bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: "0.0.0.0"

# Rule / Global/ Direct (默认为 Rule 模式)
mode: Rule

# 设置日志等级 (默认为 info)
# info / warning / error / debug / silent
log-level: info

# RESTful API for clash
external-controller: "0.0.0.0:9090"

# you can put the static web resource (such as clash-dashboard) to a directory, and clash would serve in `${API}/ui`
# input is a relative path to the configuration directory or an absolute path
external-ui: /opt/clash/yacd

# RESTful API 的口令 (可选)
secret: 123456

# experimental feature
experimental:
  ignore-resolve-fail: true # ignore dns resolve fail, default value is true

# # experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
# # static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'

# DNS 设置
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 127.0.0.1:9653
  nameserver:
    - 127.0.0.1:9853
  fallback:
    - 127.0.0.1:9753
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Arch Linux
* 使用者的操作系统 (the OS running on the client)
Windows 10
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
当上游DNS服务器返回SERVFAIL时，Clash不应该缓存这个状态。

引用于 [rfc2308#section-7.1](https://tools.ietf.org/html/rfc2308) 中的描述

> In either case a resolver MAY cache a server failure response.  If it
   does so it MUST NOT cache it for longer than five (5) minutes, and it
   MUST be cached against the specific query tuple <query name, type,
   class, server IP address>.

目前CLASH的实现中没有对DNS的缓存没有检查返回的状态，详见
https://github.com/Dreamacro/clash/blob/609869bf5a1d779b0ac6a0caca9ff9ea67b0c40f/dns/resolver.go#L109

当clash缓存这个带有失败状态的请求后，客户端再次查询DNS的时候会从缓存中直接拿出这个错误状态的结果出来，导致chrome出现ERR_NAME_NOT_RESOLVED错误。

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by Dreamacro** [comment]
Fixed in https://github.com/Dreamacro/clash/commit/c4994d642963c825b1070dc19d63511bbe536fc8

**Comment by nauxliu** [comment]
@Dreamacro 在使用 Premium 2020.10.09 版本，依然遇到这个问题。表现为 chrome 经常出现 ERR_NAME_NOT_RESOLVED 错误，用 nslookup 返回 `** server can't find onedrive.cpt.al: SERVFAIL`

**Comment by Dreamacro** [comment]
@nauxliu 这个应该是你的 dns server 有点问题

**Comment by nauxliu** [comment]
这是目前的配置，已经尝试换过一批 dns server 了，有什么建议的  server 配置让我尝试下吗？

```dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:53
  default-nameserver: # resolve dns nameserver host, should fill pure IP
    # aka Bootstrap DNS
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
  use-hosts: true # lookup hosts and return IP record
  fake-ip-filter: # fake ip white domain list, aka Always Real IP
    - "*.lan"
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
  fallback: # concurrent request with nameserver,
    # fallback used when GEOIP country isn't CN
    # - tcp://1.1.1.1
    # - tcp://8.8.8.8
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true # default
    ipcidr: # ips in these subnets will be considered polluted
      - 240.0.0.0/4
```
