### ISSUE TITLE
[Bug] Empty Config Detect

### ISSUE THREAD

**Issue by Kr328** [Dreamacro/clash#545]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
```

### Clash log

```
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Android
* 使用者的操作系统 (the OS running on the client)
Android
* 网路环境或拓扑 (network conditions/topology)
* iptables，如果适用 (if applicable)
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
* 其他

### 说明 Description
使用 config.parseConfig 载入一个 **空的配置文件** 时 没有返回错误

### 重现问题的具体布骤 Steps to Reproduce

1. config.ParseConfig(make([]byte ,0))

**我预期会发生……？**

返回一个 error

**实际上发生了什麽？**

返回了一个全是默认值的 Config 实例

### 可能的解决方案 Possible Solution

检查如果配置文件不存在任何一个 Proxy 或者 Provider 则返回 error

**Comment by Dreamacro** [comment]
clash 的配置文件是渐进式的，当你不需要某些功能的时候，你不需要知道其他配置是什么，例如我需要一个直连的 socks5 server，我只需要写上

```yaml
socks-port: 7890
```

即可获得一个本地直连的 socks5 server，倘若我需要局域网设备连接这个 socks5 server，只要加上一句

```yaml
socks-port: 7890
allow-lan: true
```

即可在局域网或公网上使用这个 server，并不是一定要存在一个 Proxy 或者 Provider 才能使用，直连也是一种使用方式。
