### ISSUE TITLE
[Bug]Dashboard无法连接

### ISSUE THREAD

**Issue by gumpfly** [Dreamacro/clash#546]
操作系统： archlinux

通过浏览器访问 http://clash.razord.top 进行策略组设置。端口和口令按yml文件中的external-controller内容输入，IP为127.0.0.1 端口：9090，但是一直进不去。

**Comment by linan** [comment]
和楼上一样，127.0.0.1，9090端口，然后用路由器ip和9090端口连接，dashboard一直进不去。
不过我是armv8安装在merlin上。

**Comment by 0x0x0x** [comment]
怎么解决的？之前还好好的，今天就进不去了，配置文件没错啊

**Comment by e71828** [comment]
127.0.0.1:9090
`{"hello":"clash"}`
没有解决

**Comment by gy528909** [comment]
这个问题解决了吗?我也遇到一样的了,访问后只有一个json {"hello":"clash"}
