### ISSUE TITLE
[Bug] DOMAIN-KEYWORD 不匹配一级域，如 dns.google

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#548]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
DOMAIN-KEYWORD,google,Default
```

### Clash log

```
[warning] dial MATCH error: dial tcp4 8.8.4.4:443: i/o timeout
```

### 环境 Environment

* Clash Core 的操作系统: OpenWrt 19.07.2
* 使用者的操作系统: Windows 10 LTSC
* ISP 有没有进行 DNS 污染: 否

### 重现问题的具体布骤 Steps to Reproduce

浏览器访问 https://dns.google ，规则中有 `DOMAIN-KEYWORD,google,Default`，其中Default为代理策略组，但是根据日志来看流量走向是DIRECT（日志中没有出现dns.google域名且只有与8.8.8.8/8.8.4.4通信超时，已排除访问端浏览器及系统存在DNS缓存，确定发起访问时首先发起了DNS查询）。
目前看来应该是clash针对域名关键词的匹配没有匹配一级域，不知道这是个bug还是feature？

**Comment by Dreamacro** [comment]
猜测是 clash 拿到的并不是域名，而是只有 IP 地址的请求

**Comment by Mosney** [comment]
> 猜测是 clash 拿到的并不是域名，而是只有 IP 地址的请求，所以没有匹配到 `DOMAIN-KEYWORD`

你是对的，直接使用socks代理请求是正常的，clash日志 `[info] [TCP] 10.1.1.123:34594 --> dns.google match DomainKeyword using Default`，看起来应该不是clash的问题。
奇怪的是用chrome浏览器打开dns.google，也能看到AdGuardHome日志里查询了这个域名，按理说我设置了AdGuardHome 0缓存和唯一上游为clash，这个DNS请求应该会被clash收到。我再排查一下其他环节好了，谢谢！

**Comment by Mosney** [comment]
破案了，之前部署DoT/H把几个DoT/H域名加到单独列表，DNS查询没走clash，是我蠢了…
