### ISSUE TITLE
可能会影响某些dns解析

### ISSUE THREAD

**Issue by TomatoFryEggs** [Dreamacro/clash#55]
使用clashx，mojave10.14
开启clashx后，dns解析超时，关闭后可以正常解析。更换114dns后问题解决。
已知有问题的的dns：123.123.123.123（北京联通默认dns）
目前已知网站
huaban.com
chinacdc.com

**Comment by beyondkmp** [comment]
下面分析的都是直接curl请求的时候抓包分析的：
dns正常解析的：
[dns_suc](https://beyondkmp.com/imgs/dns_suc.png)
dns解析非常长的时间：
[dns_failed](https://beyondkmp.com/imgs/dns_failed.png)

从上面的抓包来看，现在底层的dns resovel的时候都会请求A和AAAA记录，正常的都返回两个记录，即使没有AAAA记录也会返回一个空。

但是不正常的那个域名，就是一直不返回AAAA记录，使的底层去重复请求了三次，最后才用了A记录。这样可以判断是那个不正常的域名的权威dns服务器的配置是有问题的。

还有为什么不开clash用浏览器是直接可以打开的，浏览器是没有直接调用底层的dns 解析库，是自己实现一个dns 服务器和客户端，所以他的解析流程和系统底层dns解析库是不一样的。他应该是有解析返回A记录，就直接用A记录了。surge目前也是有自己的dns解析，所以也不会出问题。

**Comment by beyondkmp** [comment]
我已经试了，chinacdc.com 这个域名是没有问题的。 @TomatoFryEggs 你试试你的那个域名 行不行，看下是不是同一个问题？

**Comment by Dreamacro** [comment]
如果使用自定义 DNS 不能解决再重新打开这个 issue
