### ISSUE TITLE
clash做为网关和透明代理的设置问题请教

### ISSUE THREAD

**Issue by easonjim** [Dreamacro/clash#554]
版本：Clash v0.18.0-8-g68b82c9 linux amd64
背景：我用了TUN模式的clash，搭建透明代理和网关
配置文件：tun模式开启，fake-ip开启，允许局域网访问
实验环境：
PC1：
 - centos7.5
 - 192.168.43.185
 - 已经关闭防火墙、selinux、增加net.ipv4.ip_forward=1
 - 运行clash之后，只在/etc/resolv.conf增加nameserver 127.0.0.1，然后本机使用curl https://www.google.com是正常的；
PC2：
 - centos7.5
 - 192.168.43.186
 - 已经关闭防火墙、selinux

测试1：
在PC2上网关和DNS都设置成192.168.43.185，此时本机使用curl https://www.google.com是正常的；

测试2：
1、在PC2上DNS设置成192.168.43.185
2、在iptables增加本机转发规则：
 - iptables -t nat -A OUTPUT -p tcp -d 198.18.0.0/24 -j DNAT --to-destination 192.168.43.185
 - iptables -t nat -A OUTPUT -p udp -d 198.18.0.0/24 -j DNAT --to-destination 192.168.43.185
 - iptables -t nat -A OUTPUT -p icmp -d 198.18.0.0/24 -j DNAT --to-destination 192.168.43.185
通过以上设置，能正常ping www.google.com，返回的ip为198.18.0.2
但curl https://www.google.com不能访问，得到：curl: (7) Failed connect to www.google.com:443; 拒绝连接

请问是否是我的iptables规则写错了？还是需要clash服务器192.168.43.185也需要iptables的设置？
已经验证码route规则增加时正常的，但就是iptables设置不正常。
使用iptables的问题是由于我的网络上有很多层vlan，而clahs搭建再vlan1，pc2在vlan2，所以我想通过iptables的转发规则转发过去，这样我就不用修改pc2的网关。

**Comment by easonjim** [comment]
之前没有TUN模式的时候，使用fake-ip模式做为网关设置已经成功了。
1、在PC1上增加iptables规则，开启转发，并把防火墙和selinux都关闭
2、在PC2把网关指向PC1，dns解析指向198.19.0.1

PC1的iptables规则：
```shell
iptables -t nat -A PREROUTING -p udp --dport 53 -d 198.19.0.0/24 -j clash_dns
iptables -t nat -A PREROUTING -p tcp -j clash

iptables -t nat -A clash_dns -p udp --dport 53 -d 198.19.0.0/24 -j DNAT --to-destination 192.168.43.185:53
iptables -t nat -A clash_dns -p tcp --dport 53 -d 198.19.0.0/24 -j DNAT --to-destination 192.168.43.185:53

iptables -t nat -A clash -d 1.0.0.0/8 -j ACCEPT
iptables -t nat -A clash -d 10.0.0.0/8 -j ACCEPT
iptables -t nat -A clash -d 100.64.0.0/10 -j ACCEPT
iptables -t nat -A clash -d 127.0.0.0/8 -j ACCEPT
iptables -t nat -A clash -d 169.254.0.0/16 -j ACCEPT
iptables -t nat -A clash -d 172.16.0.0/12 -j ACCEPT
iptables -t nat -A clash -d 192.168.0.0/16 -j ACCEPT
iptables -t nat -A clash -d 224.0.0.0/4 -j ACCEPT
iptables -t nat -A clash -d 240.0.0.0/4 -j ACCEPT
iptables -t nat -A clash -d 192.168.43.185/32 -j ACCEPT

iptables -t nat -A clash -p tcp --dport 22 -d 192.168.43.185/32 -j ACCEPT

iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7892
```

**Comment by fbion** [comment]
mark

**Comment by OG-C** [comment]
据说在路由器DHCP网关设置里填clash机的局域网IP极客云
