### ISSUE TITLE
[Feature]请问能否做到符合 DIRECT 的规则不返回 fake ip

### ISSUE THREAD

**Issue by Old-Pussy** [Dreamacro/clash#557]
我的 clash 工作在 fake-ip 模式下，但是这与 DDNS 功能冲突。一开始我的想法是把 DDNS 域名加入DIRECT规则，但是这并不奏效。根据我的理解，需要走代理的域名才需要 fake ip，所以能不能把规则判断放在返回 ip 之前，并且不对 DIRECT 的域名返回 fake ip。

**Comment by Dreamacro** [comment]
fake-ip 白名单 `fake-ip-filter`
