### ISSUE TITLE
[Bug]三月二日的发布的tun版本无法上传文件

### ISSUE THREAD

**Issue by xuan880** [Dreamacro/clash#558]
### clash core config

tun:
  enable: true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5335
  enhanced-mode:  fake-ip
……
```

### Clash log
<!--
在下方附上 Clash Core 的日志，log level 最好使用 DEBUG
Paste the Clash core log below with the log level set to `DEBUG`.
-->
```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
arch linux 
* 使用者的操作系统 (the OS running on the client)
arch linux
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

<!--
请详细、清晰地表达你要提出的论述，例如这个问题如何影响到你？你想实现什么功能？
-->

### 重现问题的具体布骤 Steps to Reproduce

1. 使用三月二号发布的tun版本
2. 使用fakeip模式
3. 用浏览器打开上传页面，例如百度，gdrive等网站
4.上传文件

**我预期会发生……？**
文件正常上传

**实际上发生了什麽？**
文件无法上传

### 可能的解决方案 Possible Solution
<!-- 此项非必须，但是如果你有想法的话欢迎提出。 -->
<!-- Not obligatory, but suggest a fix/reason for the bug, -->
<!-- or ideas how to implement the addition or change -->

### 更多信息 More Information

**Comment by BirkhoffLee** [comment]
可以用 curl 重現嗎？

**Comment by xuan880** [comment]
> 可以用 curl 重現嗎？

不知道如何用curl复现,单纯的用curl的put指令来上传文件没有问题,但是用浏览器上传文件就是不行,不知道哪里出现了问题.

**Comment by BirkhoffLee** [comment]
調整 log level 到 debug 然後提供 log，加上瀏覽器的 inspect network 截圖

**Comment by xuan880** [comment]
> 調整 log level 到 debug 然後提供 log，加上瀏覽器的 inspect network 截圖

`INFO[0210] [TCP] 198.18.0.1:40946 --> drive.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0211] [TCP] 198.18.0.1:33748 --> fonts.googleapis.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0211] [TCP] 198.18.0.1:45232 --> apis.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
DEBU[0211] [DNS] www.gstatic.com --> 203.208.40.63      
DEBU[0211] [DNS] ssl.gstatic.com --> 203.208.41.56      
DEBU[0211] [DNS] fonts.gstatic.com --> 203.208.41.127   
INFO[0212] [TCP] 198.18.0.1:42664 --> www.gstatic.com match DomainSuffix using Proxy[cn2-v2ray-ws] 
INFO[0212] [TCP] 198.18.0.1:48112 --> ssl.gstatic.com match DomainSuffix using Proxy[cn2-v2ray-ws] 
INFO[0212] [TCP] 198.18.0.1:59684 --> fonts.gstatic.com match DomainSuffix using Proxy[cn2-v2ray-ws] 
INFO[0212] [TCP] 198.18.0.1:38288 --> lh3.googleusercontent.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0212] [TCP] 198.18.0.1:38562 --> clients6.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0212] [TCP] 198.18.0.1:51742 --> accounts.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0213] [TCP] 198.18.0.1:53590 --> aa.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0214] [TCP] 198.18.0.1:40216 --> www.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0214] [TCP] 198.18.0.1:56542 --> play.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0214] [TCP] 198.18.0.1:45648 --> drive-thirdparty.googleusercontent.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0214] [TCP] 198.18.0.1:33832 --> lh3.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0214] [TCP] 198.18.0.1:56554 --> play.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
DEBU[0214] [DNS] epns.eset.com --> 38.90.226.51         
DEBU[0214] [DNS] response msg error: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0x62ee, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:"epns.eset.com.", Qtype:0x1c, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)} 
INFO[0215] [TCP] 198.18.0.1:46682 --> epns.eset.com match Match using Proxy[cn2-v2ray-ws] 
INFO[0215] [TCP] 198.18.0.1:44614 --> addons-pa.clients6.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0217] [TCP] 198.18.0.1:53352 --> ogs.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0217] [TCP] 198.18.0.1:49820 --> cello.client-channel.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
INFO[0217] [TCP] 198.18.0.1:40912 --> clients4.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
DEBU[0219] [DNS] a978.i6g1.akamai.net --> 2600:1404:5400::172f:c20b 
INFO[0219] [UDP] 198.18.0.1:38274 --> teredo.ipv6.microsoft.com match DomainKeyword using 国内路线[DIRECT] 
INFO[0220] [TCP] 198.18.0.1:34330 --> a978.i6g1.akamai.net match Match using Proxy[cn2-v2ray-ws] 
INFO[0222] [TCP] 198.18.0.1:52344 --> signaler-pa.clients6.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
DEBU[0233] [DNS] imaphz.qiye.163.com --> 115.236.118.100 
INFO[0233] [TCP] 198.18.0.1:33034 --> imaphz.qiye.163.com match DomainSuffix using 国内路线[DIRECT] 
DEBU[0233] [DNS] gitcdn.xyz --> 104.31.84.90            
INFO[0233] [TCP] 198.18.0.1:35062 --> gitcdn.xyz match Match using Proxy[cn2-v2ray-ws] 
INFO[0236] [TCP] 198.18.0.1:54802 --> mail.google.com match DomainKeyword using Proxy[cn2-v2ray-ws] 
`
![image](https://user-images.githubusercontent.com/2383369/77709339-b7432600-7005-11ea-864c-673742659fe2.png)

**Comment by Dreamacro** [comment]
试试最新版，可以试试不同的网络栈
