### ISSUE TITLE
error: websocket: duplicate header not allowed: Connection

### ISSUE THREAD

**Issue by ls148478** [Dreamacro/clash#561]
提示重复 这种情况应该怎么不重复 因为拿来免流 这个参数有点重要

**Comment by Dreamacro** [comment]
`Connection` 这个 Header 看起来不允许自定义

**Comment by ls148478** [comment]
那它默认的值是多少啊 close或者keep-alive

**Comment by ls148478** [comment]
> `Connection` 这个Header看起来容自定义
那它默认的值是多少啊 close或者keep-alive

**Comment by Dreamacro** [comment]
https://github.com/gorilla/websocket/blob/master/client.go#L219

**Comment by ls148478** [comment]
> https://github.com/gorilla/websocket/blob/master/client.go#L219

唉 谢谢
