### ISSUE TITLE
[Feature]希望作者大佬能都添加TCP的DNS转发功能，以支持DNS解锁的Netflix流媒体服务

### ISSUE THREAD

**Issue by z877303287** [Dreamacro/clash#564]
如题，我在使用openclash过程中发现只有原生IP的才能顺利观看Netflix，DNS解锁的Netflix流媒体服务皆会显示代理错误，openclash的作者在最新一版中也提到了该情况。希望作者大佬能添加TCP的DNS转发功能，在这里跪谢了

**Comment by aaaisan** [comment]
跟你遇到同样的问题，我使用的ubuntu19.10，原版clash，也是只有原生Ip可以看，DNS解锁和中转方式都无法看

**Comment by aaaisan** [comment]
不对，补充一下，电脑端可以正常看，只有电视盒子不能看，使用的是fake-ip模式

**Comment by z877303287** [comment]
> 不对，补充一下，电脑端可以正常看，只有电视盒子不能看，使用的是fake-ip模式

目前无解，我路由器换了个插件用，clash用在电脑端，移动端了。

**Comment by pscj** [comment]
这种情况是系统dns没有指到clash的dns上去
