### ISSUE TITLE
[Feature] urltest 节点用歷史健康度排序

### ISSUE THREAD

**Issue by thank243** [Dreamacro/clash#566]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

我有大概50个节点，按现在urltest排序，简单粗暴，直接按一定时间后做个握手延迟，哪个节点在那个时间测试的延迟最短就选择哪个。
### 可能的解决方案 Possible Solution

我的想法是，能不能为每个节点增加个健康度检测，可以以24h为周期，不一定每日重置，就最近24h的健康度先排序，然后再按延迟最低选择，这样可以避免选择到当时延迟比较低的节点，但是丢包严重。

**Comment by Dreamacro** [comment]
interval 不就是干这个的？

**Comment by thank243** [comment]
到这个并没有历史健康度排序，对于那种延迟低，但是短时断开的节点无效。能不能像haproxy那样，做个L4check
