### ISSUE TITLE
[Feature] url-test 每次 每个url-test策略组都进行延迟测试貌似不太合理

### ISSUE THREAD

**Issue by Liquor030** [Dreamacro/clash#569]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [✔ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。
------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

url-test每次进行测试延迟的时候并非只测试正在使用的url-test策略组，而是将所有url-test策略组都进行测试，有点不太合理。

### 可能的解决方案 Possible Solution

我认为，应该只测试正在使用的url-test策略组的延迟就行了，没必要全部都测试一遍。

**Comment by Kr328** [comment]
没有正在使用的策略组为什么要留在配置文件里呢 删掉不是更好吗

**Comment by Liquor030** [comment]
> 没有正在使用的策略组为什么要留在配置文件里呢 删掉不是更好吗

没有正在使用，但是会用到呀，比如一些突发情况 某个机场的服务器挂掉，需要临时更换另一个机场。
