### ISSUE TITLE
[Feature] ssid proxy group support

### ISSUE THREAD

**Issue by genequ** [Dreamacro/clash#570]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 可能的解决方案 Possible Solution
格式可参考：
- { name: "Proxy", type: ssid, default: myproxy, ssid1: myproxy1, ssid2: myproxy2 }
### 更多信息 More Information
Surge：SSIDGroup = ssid, default = ProxyHTTP, cellular = ProxyHTTP, SSIDName = ProxySOCKS5
Quantumult: ssid=policy-name-4, Sample-A, Sample-B, LINK_22E171:Sample-B, LINK_22E172:Sample-C

**Comment by BirkhoffLee** [comment]
It’s not currently possible to implement SSID groups in Clash core but its derivatives AFAIK.

**Comment by Dreamacro** [comment]
It seems it's impossible to get ssid on Windows, macOS, and linux by syscall

**Comment by oemaix** [comment]
I think it is better to have it implemented as an optional feature, so that the derivatives in OSes (e.g. Android) that could get the SSID information  could just implement some interface or so to implement it.
