### ISSUE TITLE
[Feature] 关于集成 Gost 的大胆建议

### ISSUE THREAD

**Issue by soffchen** [Dreamacro/clash#573]
[Gost: GO Simple Tunnel - a simple tunnel written in golang](https://github.com/ginuerzh/gost)

原因:
* 很灵活，协议和传输灵活搭配，比如最新的 [Relay](https://docs.ginuerzh.xyz/gost/relay/) 协议搭配 TLS 传输效果不错，服务器端搭设也是一条命令搞定。
* 轻松支持 Proxy Chains
* TUN/TAP 支持也是现成的
* 非常活跃

像这样子？

```
  - name: "gost"
    type: gost
    forward: relay+tls://username:password@:12345 ss://aes-128-cfb:123456@:8338
```

**Comment by Dreamacro** [comment]
那为什么不直接用 gost 呢

**Comment by soffchen** [comment]
用 clash 的规则统一管理方便嘛，有时候用 gost 转出 socks，然后再到 clash 来用，还是不方便 :)

**Comment by Dreamacro** [comment]
那为什么不是在 gost 上加规则

**Comment by soffchen** [comment]
有道理

**Comment by moranno** [comment]
> 那为什么不直接用 gost 呢

如果clash可以支持gost的话，那机场用起来就很方便了。
毕竟现在用clash的客户端最多。
