### ISSUE TITLE
[Bug]某些特定网站死活不走代理的问题。如：www.eeuroparts.com

### ISSUE THREAD

**Issue by xmtomcom** [Dreamacro/clash#574]
你好，感谢开发出这么好的软件。但是我碰到一个问题，使用规则访问“www.eeuroparts.com”这个网站，即便是所有规则都选择“proxy”（包含others），仍然不会走代理。只有强行将网站加入到*.yaml文件中去，才可以使用代理。但是由于我使用的是第三方机场，一旦订阅更新，*.yaml又会被重置。目前我只有碰到这个网站，其他的others规则选择proxy就可以走代理。
  我试着在ip138查询了该网站的IP，除了真正的ip之外，还返回一个127.0.0.1（保留地址），不知道是否是因为这个原因，导致死活走不了代理，麻烦给解答一下吧，谢谢了！

**Comment by techblack** [comment]
这个网站在国内DNS上全部返回127.0.0.1，手动指定HOSTS吧
