### ISSUE TITLE
[Bug]使用clash的dns，某些域名在某些情况下无法正常解析。

### ISSUE THREAD

**Issue by cjjdaq** [Dreamacro/clash#575]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [✔ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [✔ ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [✔ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

### clash core config
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:9053
  enhanced-mode: redir-host
  nameserver:
    - 127.0.0.1:53

### Clash log
并无相关log显示

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
openwrt
* 使用者的操作系统 (the OS running on the client)
tplink摄像头。iphone
* 网路环境或拓扑 (network conditions/topology)
openwrt->（摄像头，手机）
* iptables，如果适用 (if applicable)
iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j DNAT --to 192.168.2.253:9053

### 说明 Description

在iPhone上（wifi链接到局域网中）
第一种情况： 直接打开http://v2.tgmmvip.com 没有问题。但如果开启quantumult X后，就无法打开了，quantumult X里提示dns error，此时关闭wifi，使用4g并开启quantumult X后可正常打开。
第二种情况：正常链接wifi，并开启quantumult X，同时删除下面这条iptables的劫持规则，域名可正常解析打开。
iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j DNAT --to 192.168.2.253:9053

不只这一个域名，前前后遇到很多域名都有此种情况。如果不使用iptables来劫持dns，又无法使用clash的域名分流。

同时家里的tplink摄像头系统里的网络检测也是这样的情况，如果开启clash的dns，并使用iptables劫持的话，就会显示网络未链接，删除iptables就正常。

### 重现问题的具体布骤 Steps to Reproduce

步骤如上

**Comment by cjjdaq** [comment]
希望能够跟进一下此问题

**Comment by Dreamacro** [comment]
麻烦提供一个更容易操作的最小重现方法，比如 dig 返回不正常之类的

**Comment by cjjdaq** [comment]
> 麻烦提供一个更容易操作的最小重现方法，比如 dig 返回不正常之类的

我现在是路由上clash监听53端口，上层是dnsmasq，只要将tplink的网络摄像头的dns设置未路由器的IP，在摄像头的系统里有个固件检查更新就一定会提示网络链接失败。这是最容易重现的。而在iphone上碰到的域名无法解析。这个很随机。但解析不了的时候，我在电脑上dig又是可以正常解析的。但如果不使用clash的dns功能就不会有此问题。我也很郁闷。

**Comment by Dreamacro** [comment]
开 debug log 的话有什么异常的 log 吗？或者有没有 panic

**Comment by cjjdaq** [comment]
> 开 debug log 的话有什么异常的 log 吗？或者有没有 panic

开debug也没有什么异常的log或者说很少有debug的log显示，终端也没有什么异常抛出。如果有debug或者异常我之前就提供出来了。但我可以肯定的是clash的dns问题，因为我直接用dnsmasq监听53，用iptables劫持就没有以上问题。

**Comment by cjjdaq** [comment]
就在刚刚，我又测试了一下发现，clash监听53，如果不用iptables劫持局域网的dns请求，摄像头网络正常，但如果clash所在的路由添加了
iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j DNAT --to 192.168.2.253:53这一句后，无论摄像头系统里的dns设置成什么，都显示网络链接不通。

**Comment by cjjdaq** [comment]
今天升级到最新版，依然还是有此情况。实在无法提供更多有效的信息了

**Comment by vensterlz** [comment]
> 今天升级到最新版，依然还是有此情况。实在无法提供更多有效的信息了

这个似乎是quantumult的问题。我也是类似的现象。家里的路由器开启了clash，如果手机上的quantumult不关闭的话个别国内网站就上不了。换用火箭的话就没有问题，关闭后所有的网络也一切正常。quantumult的日志提示为DNS fail。DNS设置也没问题。因为是个别网站的问题，所以问题很奇怪，但是应该没有出在clash上。

**Comment by cjjdaq** [comment]
> > 今天升级到最新版，依然还是有此情况。实在无法提供更多有效的信息了
> 
> 这个似乎是quantumult的问题。我也是类似的现象。家里的路由器开启了clash，如果手机上的quantumult不关闭的话个别国内网站就上不了。换用火箭的话就没有问题，关闭后所有的网络也一切正常。quantumult的日志提示为DNS fail。DNS设置也没问题。因为是个别网站的问题，所以问题很奇怪，但是应该没有出在clash上。

但是不关quantumult，把clash的dns换成其它的就没有问题。比如dnsmasq。再说，tplink摄像头可没有quantumult。所以问题还是再clash的dns上。

**Comment by sanxiu0** [comment]
小白表示我也有这个问题，dns无法解析以及无效的套字节，是怎么回事啊

**Comment by Liac-li** [comment]
于Ubuntu端在配置成功后 直接关闭了terminal后 再次打开便显示
Failed to start Redir UDP Listener: operation not permitted 

效果为：在设置中使用手动的网络代理下，只能开未被墙的，而打开Google的话
它使用了Proxy规则，但是
有
DEBU：[DNS] ocsp.pki.goog —> 203.208.43.79
FATA can’t load mmdb: error opening database: invalid MaxmiNd DB file 


请问是怎么回事是否是这个问题

**Comment by Dreamacro** [comment]
@Liac-li 重下 mmdb 文件，Redir UDP 应该需要较高的权限运行，而且最好使用某种 daemon 工具跑 clash。

这个问题很久没有后续，先关闭

**Comment by isping** [comment]
解析本地域名也同样出错，关闭CLASH症状消失。
