### ISSUE TITLE
[Feature] dns选项支持禁用ipv6

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#578]
是否可以为dns配置增加一个选线，控制clash的dns服务永远不会返回ipv6的地址？
目前dns配置中的ipv6选项好像是向上游查询是是否使用ipv6的地址

**Comment by BirkhoffLee** [comment]
這邊邏輯比較複雜，未來還要改，所以暫時不會新增

目前dns配置中的ipv6选项的說明：When resolving a domain, Clash resolves both A/AAAA by default (but v4 is preferred when connecting). If set to false, Clash won't ask for AAAA. This has nothing to do with the Clash DNS server itself, nor does it prioritises IPv6 connection when both v4/v6 is available
