### ISSUE TITLE
我想问下，我这路由应该用哪个版本的clash？

### ISSUE THREAD

**Issue by mchotdograp** [Dreamacro/clash#579]
搜了几个地方，也没看明白到底用哪个版本的合适，我的是：
NETGEAR WNDR3800
CPU型号 | Atheros AR7161 rev 2
CPU主频 | 680 MHz
内存频率 | 340 MHz
闪存容量 | 16 MB
固件版本 | OpenWrt Barrier Breaker 14.07 r47805 元旦版 by 明月永在
内核版本 | 3.10.70
如果有清楚的，麻烦请告知一下，感谢！🙏

**Comment by ysc3839** [comment]
搜索 AR7161 便可知道这是 MIPS 24k 的 CPU，再查阅 OpenWrt 源代码可知道是 [big endian](https://github.com/openwrt/openwrt/blob/5c2e409be7053b8ef994a2af7034b0210437ac31/target/linux/ar71xx/config-4.14#L294)，所以选择 mips-softfloat。

**Comment by mchotdograp** [comment]
谢谢您的回答！我下载了，但是这个是gz格式的，我记得openwrt安装不是用ipk格式的吗

**Comment by ysc3839** [comment]
不一定需要系统包管理安装，直接使用普通的压缩包也可以的。

**Comment by mchotdograp** [comment]
是不是就得ssh命令行操作了，界面这种GUI方式这种不行了？

**Comment by xingezhang** [comment]
这只是可执行文件，解压缩后传进路由器，还需要自己写启动脚本
