### ISSUE TITLE
关于Clash配置文件语法的问题

### ISSUE THREAD

**Issue by tea1111980** [Dreamacro/clash#583]
请问作者，有没有关于Clash配置文件语法编写的规范手册？
即：Clash配置文件里的每个符号和编写格式是什么意思的解释。谢谢。

**Comment by Dreamacro** [comment]
格式的话可以看 https://www.ruanyifeng.com/blog/2016/07/yaml.html

**Comment by tea1111980** [comment]
还有一个问题，就是：
    url-test
    fallback
    select

这三种类型，可以同时在同一个yaml配置文件里启用吗？如果是同时启用，它们之间不会“打架”吗？

我试了一下，同时启用的话，浏览网页非常的慢，如果只启用fallback一个类型的话，要快许多。
而且，同时启用的话有时会报错。不知道什么原因，配置都是对的也报错。只用其中的一个就很好。

**Comment by Dreamacro** [comment]
不影响的吧，group 之间是可以互相嵌套的。报错说明写错了，慢应该是你配置指向有问题，和是不是同时使用无关

**Comment by tea1111980** [comment]
> 不影响的吧，group 之间是可以互相嵌套的。报错说明写错了，慢应该是你配置指向有问题，和是不是同时使用无关

哦，那我就放心了，谢谢你的解答。

**Comment by tea1111980** [comment]
> 不影响的吧，group 之间是可以互相嵌套的。报错说明写错了，慢应该是你配置指向有问题，和是不是同时使用无关

大佬，经过 2个多月的研究，对于 `代理分组` 里面的 4个类型 已经理解差不多了，不过有个问题：

在使用中发现，使用 类型为: `url-test` 时，它无法自动测速 并 自动切换代理。非得手动测速之后，才会自动切换到延时最低的代理。

超时，我已经设置的 不大 不小了 ( 1500ms ) 1.5秒左右。

请问这是使用不当 造成的 `url-test` 不能通过延时变化 自动切换代理吗？

**Comment by Ninzero** [comment]
> 测速超时，我已经设置的 不大 不小了 (1500ms) 1.5 秒左右。
@tea1111980 这个单位应该是秒吧, 你这是 1500s 的意思.

**Comment by tea1111980** [comment]
> > 测速超时，我已经设置的 不大 不小了 (1500ms) 1.5 秒左右。
> 
> @tea1111980 这个单位应该是秒吧, 你这是 1500s 的意思.

不是，测速里面的时间 是以 毫秒为单位的。 1000毫秒 = 1秒

**Comment by jialeichn** [comment]
> > > 测速超时，我已经设置的 不大 不小了 (1500ms) 1.5 秒左右。
> > 
> > 
> > @tea1111980 这个单位应该是秒吧, 你这是 1500s 的意思.
> 
> 
> 
> @Ninzero 测速里面 `interval` 的时间 应该是 毫秒(ms) 为单位的吧？
> 
> 我是看 Clash API 里面说的

interval单位是秒，看了clash的节点健康检查代码，如下：
`func (hc *HealthCheck) process() {
	ticker := time.NewTicker(time.Duration(hc.interval) * time.Second)

	go hc.check()
	for {
		select {
		case <-ticker.C:
			now := time.Now().Unix()
			if !hc.lazy || now-hc.lastTouch.Load() < int64(hc.interval) {
				hc.check()
			}
		case <-hc.done:
			ticker.Stop()
			return
		}
	}
}`
