### ISSUE TITLE
[Feature] load-balance 结合 url-test，使用延迟最低的 n 个节点

### ISSUE THREAD

**Issue by h0cheung** [Dreamacro/clash#590]
如题，这样在使用负载均衡的同时避开一些状况不佳的节点，可以提高使用体验

**Comment by RunStar99** [comment]
load-balance可以加一个参数，指定延迟前n的节点参与负载均衡

**Comment by Dreamacro** [comment]
load-balance 的节点列表不能频繁变动，否则 load-balance 组将毫无意义
