### ISSUE TITLE
请问clashx怎么设置终端代理呢？

### ISSUE THREAD

**Issue by poisonoff** [Dreamacro/clash#592]
【不好意思，实在没有找到有效的解决方案所以在这里求助..】
请问macOS 如何设置终端走代理（v2ray）呢？clashx复制终端代理命令不行。

**Comment by ysc3839** [comment]
你复制终端代理命令后进行了什么操作？“不行”是怎么个不行？

**Comment by poisonoff** [comment]
> 你复制终端代理命令后进行了什么操作？“不行”是怎么个不行？

复制终端命令在终端执行，然后还是无法ping 通Google.com

**Comment by ysc3839** [comment]
ping 使用的是 ICMP 协议，不支持代理。
你可以执行 `curl -vv https://www.google.com` 看看有没有走代理。

**Comment by poisonoff** [comment]
> ping 使用的是 ICMP 协议，不支持代理。
> 你可以执行 `curl -vv https://www.google.com` 看看有没有走代理。

成功走代理了，原来如此，非常感谢！

**Comment by Joeycz** [comment]
> > ping 使用的是 ICMP 协议，不支持代理。
> > 你可以执行 `curl -vv https://www.google.com` 看看有没有走代理。
> 
> 成功走代理了，原来如此，非常感谢！

所以这个最后怎么解决的啊，我也是ping不通

**Comment by ysc3839** [comment]
@Joeycz 没办法解决 ping 的问题，要测试的话可以改用 curl 等支持代理的工具。

**Comment by hdc8899** [comment]
请问复制终端代理命令在终端执行，终端就可以走代理了吗？

**Comment by RuoyuChen10** [comment]
比如你用的socks5端口是7891，你就在终端先输入：

```shell
export ALL_PROXY=socks5://127.0.0.1:7891
```

然后就可以终端翻墙了。

**Comment by IWSR** [comment]
我有个疑惑，我使用系统代理命令后curl google.com是可以连接通的，但是当我curl cip.cc时，返回的依然是我直连的IP信息，想不太明白这是为什么？

**Comment by jiabinbin** [comment]
> 我有个疑惑，我使用系统代理命令后curl google.com是可以连接通的，但是当我curl cip.cc时，返回的依然是我直连的IP信息，想不太明白这是为什么？

我也是这样，还在好奇

**Comment by jeffwcx** [comment]
> 我有个疑惑，我使用系统代理命令后curl google.com是可以连接通的，但是当我curl cip.cc时，返回的依然是我直连的IP信息，想不太明白这是为什么？

可能是因为你的代理有规则判断，cip.cc是国内域名，直连了。你设为全局代理，估计就会是代理服务器地址了。

**Comment by Xuzan9396** [comment]
@jeffwcx    clashx 改了全局 curl www.google.com 直接都访问不了，
![image](https://user-images.githubusercontent.com/24741439/124897565-005b9580-e011-11eb-8941-9f2d65c1240e.png)
改成规则判断 curl www.google.com 可以访问
但是ip 还是当前本地ip,全局不生效吗

设置规则
```bash
    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
    export http_proxy="http://127.0.0.1:7890"
    export https_proxy=$http_proxy
```

**Comment by jeffwcx** [comment]
@Xuzan9396 我是这么设置的：

![image](https://user-images.githubusercontent.com/14073775/124908711-34888380-e01c-11eb-86e2-c3faa7544d17.png)

用的时候执行proxy

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/125013535-925daf80-e09e-11eb-8bee-caee6a53c260.png)
@jeffwcx 
你可以设置socks5端口吗，为啥我显示为0，而且编辑不了，你的是用的哪个版本

**Comment by jeffwcx** [comment]
@Xuzan9396 
![image](https://user-images.githubusercontent.com/14073775/125236653-f4c0e500-e316-11eb-8395-05cd00ea45a5.png)

**Comment by Xuzan9396** [comment]
没问题了，我写了一篇博客总结了一下 https://blog.csdn.net/qq_36517296/article/details/118599195

**Comment by liux2** [comment]
@Xuzan9396 macos 如果有m1，推荐使用ios的ssr

**Comment by Xuzan9396** [comment]
@liux2 这个是什么软件，有没有链接

**Comment by liux2** [comment]
> @liux2 这个是什么软件，有没有链接

就app store换美服搜ssr的全称，m1记得在ios app里面搜

**Comment by Jfef** [comment]
我想知道一个事情，我设置了命令行走代理
我使用的clash 
设置命令
`export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
export all_proxy=socks5://127.0.0.1:7891`

我可以使用
```
curl -vv https://www.google.com
```

成功获取结果
```
* Uses proxy env variable https_proxy == 'http://127.0.0.1:7890'
*   Trying 127.0.0.1:7890...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" 
```


然后，我使用 ssh 来登录服务器，
ssh 是否自动走的代理呢？

或者说我还是需要其他一些操作呢？


任何建议都是有帮助的，谢谢！

**Comment by Jfef** [comment]
> > 我想知道一个事情，我设置了命令行走代理
> > 我使用的clash
> > 设置命令
> > `export http_proxy=http://127.0.0.1:7890
> > export https_proxy=http://127.0.0.1:7890
> > export all_proxy=socks5://127.0.0.1:7891`
> > 我可以使用
> > ```
> > 
> > curl -vv https://www.google.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 成功获取结果
> > ```
> > 
> > * Uses proxy env variable https_proxy == 'http://127.0.0.1:7890'
> > 
> > *   Trying 127.0.0.1:7890...
> > 
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > 
> >                                  Dload  Upload   Total   Spent    Left  Speed
> > 
> >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后，我使用 ssh 来登录服务器，
> > ssh 是否自动走的代理呢？
> > 或者说我还是需要其他一些操作呢？
> > 任何建议都是有帮助的，谢谢！
> 
> 你想内网穿透？

我想问的是：Terminal 设置了代理，然后，我使用这个terminal ，用ssh登录远程的服务器，走的是代理的端口路线吗？
还是直接路线？如果走的不是代理端口，那么如何设置呢？

>给出一下我最后的解决方法，我是用putty 设置代理的解决的。

**Comment by GJBlog** [comment]
> 

我试了设置全局也不好使，需要手动改下ClashX的规则文件

**Comment by Leyls** [comment]
> @Xuzan9396 macos 如果有m1，推荐使用ios的ssr
> <img alt="Screen Shot" width="1182" src="https://user-images.githubusercontent.com/23517453/125675837-922ddbc7-9221-4f55-acd1-a38138c14e6f.png">

能问下这个图右边是mac啥软件吗

**Comment by zhanghay** [comment]
> > > ping 使用的是 ICMP 协议，不支持代理。
> > > 你可以执行 `curl -vv https://www.google.com` 看看有没有走代理。
> > 
> > 
> > 成功走代理了，原来如此，非常感谢！
> 
> 所以这个最后怎么解决的啊，我也是ping不通

ping 不支持的

**Comment by sudoyang** [comment]
各位，apt有的包拉不下来，但测试代理已经通了，不知有遇到同样问题的吗？
卡在这里，
0% [Connecting to brave-browser-apt-release.s3.brave.com (2001::d155:e565)] [Connecting to linux.dropbox.com (2001::6ca0:a553)] [Connecting t

Err:25 https://repo.vivaldi.com/stable/deb stable InRelease
  Cannot initiate the connection to repo.vivaldi.com:443 (2001::9df0:a29). - connect (101: Network is unreachable) Could not connect to repo.vivaldi.com:443 (45.77.186.255), connection timed out
Err:26 http://linux.dropbox.com/ubuntu disco InRelease 
  Cannot initiate the connection to linux.dropbox.com:80 (2001::6ca0:a553). - connect (101: Network is unreachable) Could not connect to linux.dropbox.com:80 (199.59.148.89), connection timed out
Err:27 https://brave-browser-apt-release.s3.brave.com stable InRelease
  Cannot initiate the connection to brave-browser-apt-release.s3.brave.com:443 (2001::d155:e565). - connect (101: Network is unreachable) Could not connect to brave-browser-apt-release.s3.brave.com:443 (199.16.156.40), connection timed out



curl https的时候没反应，curl http正常
➜  ~ export http_proxy=127.0.0.1:7890;export https_proxy=$http_proxyx
➜  ~ curl -I https://www.google.com 
^C
➜  ~ export http_proxy=127.0.0.1:7890;export https_proxy=$http_proxyx
➜  ~ export http_proxy=127.0.0.1:7890;export https_proxy=$http_proxy
➜  ~ curl -I http://www.google.com   
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: private
Connection: keep-alive
Content-Type: text/html; charset=ISO-8859-1
Date: Sun, 30 Oct 2022 10:00:50 GMT
Expires: Sun, 30 Oct 2022 10:00:50 GMT
Keep-Alive: timeout=4
P3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Proxy-Connection: keep-alive
Server: gws
Set-Cookie: 1P_JAR=2022-10-30-10; expires=Tue, 29-Nov-2022 10:00:50 GMT; path=/; domain=.google.com; Secure
Set-Cookie: AEC=AakniGPhJKxIgZwnCA2AJzXhqNxQGPR_QW7GtUhcw_Mf60EKgdLAP5tT2A; expires=Fri, 28-Apr-2023 10:00:50 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
Set-Cookie: NID=511=kJB2wzukYlXGP_hratvxkT-WnOUeThaAkI1s78PSWn9j5ZPIGBXxJ_266-shUlwDqil19f7LNqoyp1w4a7XUhpg5IlvS-C2zyh5Py06xGnStqUl5NjeDP-EmsY2ypyRyAWFgDAY9x-WUcGVXnfENjxl3lOO7JXgrt7NyyRn0jwg; expires=Mon, 01-May-2023 10:00:50 GMT; path=/; domain=.google.com; HttpOnly
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

**Comment by Unusualmay** [comment]
> 

想咨询一下clashx 的规则文件怎么修改呢？

**Comment by 104gogo** [comment]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/8522646/220884651-bfeb5c93-d0be-4994-bdc3-1682c0ab5860.png">
复制到终端里面，然后回车。

用下面的命令测试
```
curl -vv https://www.google.com/
```

**Comment by qq443672581** [comment]
> <img alt="image" width="315" src="https://user-images.githubusercontent.com/8522646/220884651-bfeb5c93-d0be-4994-bdc3-1682c0ab5860.png">
> 
> 复制到终端里面，然后回车。
> 用下面的命令测试
> 
> ```
> curl -vv https://www.google.com/
> ```

简单快捷

**Comment by LOpSSH** [comment]
ping会不会走代理，这我不清楚。但是有不少服务器是icmp-prohibited的。

**Comment by diamont1001** [comment]
> <img alt="image" width="315" src="https://user-images.githubusercontent.com/8522646/220884651-bfeb5c93-d0be-4994-bdc3-1682c0ab5860.png">
> 
> 复制到终端里面，然后回车。
> 用下面的命令测试
> 
> ```
> curl -vv https://www.google.com/
> ```

这个好

**Comment by zhangfiona** [comment]
可以选择增强模式

**Comment by qq443672581** [comment]
> 

哪里有增强模式

**Comment by zhangfiona** [comment]
> > 
> 
> 哪里有增强模式

clashX pro: Command+E

**Comment by thelou1s** [comment]
brew install走代理吗？

**Comment by zaofengzhou** [comment]
> > <img alt="image" width="315" src="https://user-images.githubusercontent.com/8522646/220884651-bfeb5c93-d0be-4994-bdc3-1682c0ab5860.png">
> > 复制到终端里面，然后回车。
> > 用下面的命令测试
> > ```
> > curl -vv https://www.google.com/
> > ```
> 
> 简单快捷,但貌似只对当前cmd窗口起作用，不过这样正好，需要的时候启用代理，避免没必要的代理

想知道为啥一定要全局模式
