### ISSUE TITLE
[Bug]ClashX 配置中v2ray协议若直接填写SSL证书路径, 则无法ping通服务器

### ISSUE THREAD

**Issue by kocx2046** [Dreamacro/clash#595]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
  
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. V2ray信息如上填写完全正确，SSL证书处填入路径
2. Clashx ping fail
<img width="229" alt="Screen Shot 2020-03-23 at 5 54 20 PM" src="https://user-images.githubusercontent.com/59362011/77305122-73fc6500-6d30-11ea-927d-31a3ae495fd5.png">

3. 改为直接填写证书及内容后，可以ping通
4. V2ray config:
  {
      "listen": "0.0.0.0",
      "port": 49392,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "alterId": 64,
            "id": "fe5825e9-fake-uuid-here-a847ecf07811"
          }
        ],
        "disableInsecureEncryption": true
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "certificates": [
            {
              "certificateFile": "/www/server/panel/ssl/certificate.pem",
              "keyFile": "/www/server/panel/ssl/privateKey.pem"
            }
          ],
          "serverName": "example.xyz"
        },
**我预期会发生……？**

**实际上发生了什麽？**

**Comment by BirkhoffLee** [comment]
這裡是 Clash core

**Comment by GeorgeChen0821** [comment]
> 這裡是 Clash core

不好意思 ，但是我在clashx 提问，那里作者说可能是core issue

**Comment by beyondkmp** [comment]
@GeorgeChen0821 `"allowInsecure": true`

**Comment by GeorgeChen0821** [comment]
> @GeorgeChen0821 `"allowInsecure": true`,  或者clash的配置 `skip-cert-verify: true`

这样有效的，但是会不会增加被墙的风险呢？

**Comment by beyondkmp** [comment]
去申请一个正规有效的证书

GeorgeChen0821 <notifications@github.com> 于 2020年3月29日周日 12:57写道：

**Comment by GeorgeChen0821** [comment]
> 去申请一个正规有效的证书
> 提出这个问题的前提就是已经有SSL的前提下呀😂

**Comment by LewisXZC** [comment]
我也遇到了同样的问题， cert 用的是let's encrypt issue的cert。

**Comment by Dreamacro** [comment]
@GeorgeChen0821 ws 的 Host 可以设置 tls 的 sni
