### ISSUE TITLE
托福网站无法打开

### ISSUE THREAD

**Issue by Tsahao** [Dreamacro/clash#6]
网站 https://toefl.etest.net.cn
进入点击中文版时，无法正常打开。
中文版链接本来应为“https://toefl.etest.net.cn/cn”
但开启代理时就会跳转到“https://toefl.etest.net.cnhttp//toefl.etest.net.cn/cn”
开启代理时直接访问中文版链接 https://toefl.etest.net.cn/cn 正常

日志如下
```
2018/08/15 19:22:40:624 [info] toefl.etest.net.cn match DomainSuffix using DIRECT
2018/08/15 19:22:47:628 [info] toefl.etest.net.cnhttp match FINAL using Proxy
```

截图如下
![](https://ws1.sinaimg.cn/large/0069RVTdly1fuam02pq70j31he0zudjj.jpg)

**Comment by Tsahao** [comment]
同样问题出现在 http://pi.cs.tsinghua.edu.cn/

**Comment by Tsahao** [comment]
同样问题出现在 http://www.computerhistory.org/atchm/creating-magic-a-conversation-with-original-iphone-engineers-software-team-lead-scott-forstall/

**Comment by Dreamacro** [comment]
问题的原因以及定位清楚了，HTTP 下某些承载流量的 `Web Server` 不支持直接传输代理流量。

想到一种解决方案，但还不太确定会不会产生某种问题。如果需要详细的讨论可以加 Telegram Group，在 Github 处理流程即可。

**Comment by Dreamacro** [comment]
现在切换回了以前的版本（某些 App Store app 无法下载）, 根本原因是 apple 服务器的不规范以及 golang 在遇到这种错误的时候没法忽略这个错误。现在大多数 golang 实现的 http proxy server 都具有这个问题 （如 v2ray、goproxy）。已经给 golang 提了 issue 并加入到 1.12 版本的标记中。目前的话会想一个折中的办法临时解决这个问题。

**Comment by driftingdream** [comment]
> 问题的原因以及定位清楚了，HTTP 下某些承载流量的 `Web Server` 不支持直接传输代理流量。
> 
> 想到一种解决方案，但还不太确定会不会产生某种问题。如果需要详细的讨论可以加 Telegram Group，在 Github 处理流程即可。

Telegram Group链接？
