### ISSUE TITLE
clash 的 http 代理功能和部分 PHP 实现不兼容

### ISSUE THREAD

**Issue by vibbow** [Dreamacro/clash#60]
以下代码在 privoxy 和 Brup Suite 提供的 HTTP代理下均可正常工作 (将 clash socks 设为上级代理)
但是在 clash 提供的 HTTP代理下，clash疑似会卡到连接超时为止。

```php
<?php

$fileUrl = 'http://repo.packagist.org/packages.json';

$options = array (
  'http' => 
  array (
    'follow_location' => 0,
    'max_redirects' => 20,
    'proxy' => 'tcp://127.0.0.1:8888',
    'request_fulluri' => true,
    'protocol_version' => 1.1,
    'header' => 
    array (
      0 => 'Accept-Encoding: gzip',
      1 => 'Connection: close',
      2 => 'User-Agent: Composer/source (Windows NT; 10.0; PHP 7.2.12)',
    ),
    'ignore_errors' => true,
  )
);

$context = stream_context_create($options);

$result = file_get_contents($fileUrl, false, $context);

echo zlib_decode($result);
```

**Comment by vibbow** [comment]
附加说明：
在 clash 提供的 http代理下，以上代码会等待60秒，然后收到返回的结果。

**Comment by beyondkmp** [comment]
> 附加说明：
> 在 clash 提供的 http代理下，以上代码会等待60秒，然后收到返回的结果。

每次都是60s吗？

**Comment by vibbow** [comment]
> 
> 
> > 附加说明：
> > 在 clash 提供的 http代理下，以上代码会等待60秒，然后收到返回的结果。
> 
> 每次都是60s吗？

对的，每次都是60秒，然后收到响应结果。

**Comment by beyondkmp** [comment]
> > > 附加说明：
> > > 在 clash 提供的 http代理下，以上代码会等待60秒，然后收到返回的结果。
> > 
> > 
> > 每次都是60s吗？
> 
> 对的，每次都是60秒，然后收到响应结果。

不会php,我看下curl能构造出来不

**Comment by vibbow** [comment]
> 
> 
> > > > 附加说明：
> > > > 在 clash 提供的 http代理下，以上代码会等待60秒，然后收到返回的结果。
> > > 
> > > 
> > > 每次都是60s吗？
> > 
> > 
> > 对的，每次都是60秒，然后收到响应结果。
> 
> 不会php,我看下curl能构造出来不

我测试过curl，是没问题的。

**Comment by beyondkmp** [comment]
对应的头部都加上了？

**Comment by vibbow** [comment]
> 
> 
> 对应的头部都加上了？

从 burp suite 的抓包来看，是identical的。

**Comment by vibbow** [comment]
我开始以为是漏了什么header，导致clash无法正常解析。
但是用curl模拟了一个一模一样头的请求，发过去就是正常的。

**Comment by beyondkmp** [comment]
抓包看是，php一直没有断开，最后应该是60tcp发了fin包断开

**Comment by vibbow** [comment]
直接请求源站返回的header
```
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 07 Dec 2018 11:23:53 GMT
Content-Type: application/json
Content-Length: 1492
Last-Modified: Fri, 07 Dec 2018 11:23:39 GMT
Connection: close
Vary: Accept-Encoding
ETag: "5c0a583b-2b2"
```

Clash返回的header
```
HTTP/1.1 200 OK
Content-Length: 1492
Connection: keep-alive
Content-Type: application/json
Date: Fri, 07 Dec 2018 11:28:02 GMT
Etag: "5c0a58ed-2b3"
Keep-Alive: timeout=4
Last-Modified: Fri, 07 Dec 2018 11:26:37 GMT
Proxy-Connection: keep-alive
Server: nginx
Vary: Accept-Encoding
```

**Comment by beyondkmp** [comment]
应该是多加的几个头部引起的问题

**Comment by vibbow** [comment]
> 
> 
> 应该是多加的几个头部引起的问题

应该是因为Clash没有遵循客户端的要求关闭连接。
客户端要求了 Connection: close，数据传输完成后就应该关闭连接了。
但是Clash依然保持了连接，导致客户端继续在等待。

**Comment by beyondkmp** [comment]
> 我大概知道原因了。
> 
> PHP在请求的时候发送了 `Connection: close` Header
> 但是 Clash 在返回的时候依然返回了 `Connection: Keep-Alive`

你说的对，我看下怎么修

**Comment by beyondkmp** [comment]
你可以先参考这个实现下 https://stackoverflow.com/questions/18187419/get-file-contents-when-connection-is-keep-alive， 自己先判断下content-length

**Comment by vibbow** [comment]
这个不是我写的代码，是Composer的代码......
我只是把其中受影响的核心部分提炼出来了...
