### ISSUE TITLE
[Feature] Verify integrity of Country.mmdb upon starting

### ISSUE THREAD

**Issue by chinanoahli** [Dreamacro/clash#602]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

在windows上使用时发现，如果首次启动且当config.yaml存在而Country.mmdb不存在时，如果Country.mmdb下载不成功，就会造成闪退。

或者Country.mmdb下载不完整也会造成闪退。

是否可以更改成首次启动先检查config.yaml而非Country.mmdb，如果config.yaml里面有有效的服务器则使用代理下载Country.mmdb，而不是直接先下载Country.mmdb？

或者至少将Country.mmdb的载点放到国内比较好访问的位置……

**Comment by Dreamacro** [comment]
这没法形成闭环，规则等功能依赖 Country.mmdb，就算解析完了配置也不一定能正常下载。国内没发现免费可信的资源存储服务。

Country.mmdb 不完整不会造成「闪退」。之所以产生所谓的「闪退」是因为你使用的方式有问题。在 windows 上，正确的使用方式并不是双击打开。

**Comment by chinanoahli** [comment]
> 这没法形成闭环，规则等功能依赖 Country.mmdb，就算解析完了配置也不一定能正常下载。国内没发现免费可信的资源存储服务。
> 
> Country.mmdb 不完整不会造成「闪退」。之所以产生所谓的「闪退」是因为你使用的方式有问题。在 windows 上，正确的使用方式并不是双击打开。

即使在cmd中运行也会直接退出

**Comment by chinanoahli** [comment]
如果配置包含有效线路的情况下，可以直接通过某一条线路下载，这样也会有问题吗？

**Comment by Dreamacro** [comment]
失败退出是一个正常的行为，因为这是一个启动必要的组件

> 如果配置包含有效线路的情况下，可以直接通过某一条线路下载，这样也会有问题吗？
增加了太多不必要的复杂度

**Comment by chinanoahli** [comment]
至少增加Country.mmdb完整性检查，如果文件无效，删除并重新下载也是可以的吧？

**Comment by Dreamacro** [comment]
这个倒是可以

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/commit/84f627f302cda03f8be509f5bba2e69e5fe4ccf9
