### ISSUE TITLE
[Bug]在fallback模式下，连不上首个服务器不会切换到下一个服务器

### ISSUE THREAD

**Issue by wsgtrsys** [Dreamacro/clash#605]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

Proxy Group:
-
  name: Proxy
  type: fallback
  url: 'https://www.gstatic.com/generate_204'
  interval: 300
  proxies:

### Clash log

Mar 27 21:16:05 raspberrypi clash[1690]: time="2020-03-27T21:16:05+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:16:05 raspberrypi clash[1690]: time="2020-03-27T21:16:05+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:16:11 raspberrypi dnsmasq-dhcp[408]: no address range available for DHCP request via ztuzet277j
Mar 27 21:16:35 raspberrypi clash[1690]: time="2020-03-27T21:16:35+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:16:35 raspberrypi clash[1690]: time="2020-03-27T21:16:35+08:00" level=warning msg="dial Others error: aaa_test.com:443 connect error"
Mar 27 21:16:35 raspberrypi clash[1690]: time="2020-03-27T21:16:35+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:16:35 raspberrypi clash[1690]: time="2020-03-27T21:16:35+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:16:35 raspberrypi clash[1690]: time="2020-03-27T21:16:35+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:16:35 raspberrypi clash[1690]: time="2020-03-27T21:16:35+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:01 raspberrypi CRON[1880]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Others error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:49 raspberrypi clash[1690]: time="2020-03-27T21:17:49+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Others error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Others error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:54 raspberrypi clash[1690]: time="2020-03-27T21:17:54+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:59 raspberrypi clash[1690]: time="2020-03-27T21:17:59+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:59 raspberrypi clash[1690]: time="2020-03-27T21:17:59+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:59 raspberrypi clash[1690]: time="2020-03-27T21:17:59+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:17:59 raspberrypi clash[1690]: time="2020-03-27T21:17:59+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:18:00 raspberrypi systemd[1]: Starting Cleanup of Temporary Directories...
Mar 27 21:18:01 raspberrypi systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Mar 27 21:18:01 raspberrypi systemd[1]: Started Cleanup of Temporary Directories.
Mar 27 21:18:07 raspberrypi clash[1690]: time="2020-03-27T21:18:07+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:18:07 raspberrypi clash[1690]: time="2020-03-27T21:18:07+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:18:13 raspberrypi clash[1690]: time="2020-03-27T21:18:13+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:18:21 raspberrypi clash[1690]: time="2020-03-27T21:18:21+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:19:10 raspberrypi clash[1690]: time="2020-03-27T21:19:10+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"
Mar 27 21:19:19 raspberrypi clash[1690]: time="2020-03-27T21:19:19+08:00" level=warning msg="dial Proxy error: aaa_test.com:443 connect error"

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
arm linux 树莓派
* 使用者的操作系统 (the OS running on the client)
windows 10
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

当一个服务器连不上，会切换到下一个。

**实际上发生了什麽？**

反复连接第一个服务器，不会切换到下一个。

**Comment by mting806** [comment]
interval: 300
表示5分钟检查一次
你的log 还不到5分钟

**Comment by wsgtrsys** [comment]
我把interval改为5之后，依然不行。
我估计现在的fallback模式是在能连上服务器后才开始检查链接是否可达。
但现在是connect error就出错了，不能进入到fallback的处理流程。

**Comment by myfingerhurt** [comment]
Same here with armv5

"type: fallback" failed to proceed with other good servers and got stuck for several hours

```
  - name: Proxy
    type: fallback
    proxies:
      - conaha-ws1
      - conaha-ws2
      - conaha-ws3
      - conaha-ws4
      - conaha-wsz
      - conaha-trojan
      - ntt-ss-50100-showme
      - ntt-ss-50100-1
    url: http://www.gstatic.com/generate_204
    interval: 120
```

stuck at WARN[2343] dial auto error: 1.0.0.1:443 connect error
terminated and change  type: fallback to url-test

```
root@RT-AC68U:/tmp/mnt/Entware/entware/etc/clash# clash -d .
INFO[0000] Start initial compatible provider auto
INFO[0000] Start initial compatible provider Proxy
INFO[0000] RESTful API listening at: 10.9.8.3:9090
INFO[0000] HTTP proxy listening at: 192.168.6.1:7890
INFO[0000] SOCKS proxy listening at: 192.168.6.1:7891
INFO[0000] Redir proxy listening at: 192.168.6.1:7892
INFO[0017] [TCP] 192.168.6.1:44621 --> 149.154.171.5 match IPCIDR using auto[conaha-50118-w04]
INFO[0019] [TCP] 192.168.6.1:44623 --> 149.154.171.5 match IPCIDR using auto[conaha-50118-w04]
INFO[0019] [TCP] 192.168.6.1:44619 --> 149.154.171.5 match IPCIDR using auto[conaha-50118-w04]
WARN[2343] dial auto error: 1.0.0.1:443 connect error
^C
stuck here for hours


root@RT-AC68U:/tmp/mnt/Entware/entware/etc/clash# clash -d .
router@RT-AC68U-8E68:/tmp/mnt/Entware/entware/etc/clash# clash -d .
INFO[0000] Start initial compatible provider Proxy
INFO[0000] Start initial compatible provider auto
INFO[0000] RESTful API listening at: 10.9.8.3:9090
INFO[0000] HTTP proxy listening at: 192.168.6.1:7890
INFO[0000] SOCKS proxy listening at: 192.168.6.1:7891
INFO[0000] Redir proxy listening at: 192.168.6.1:7892
INFO[0008] [TCP] 192.168.6.1:48779 --> 149.154.171.5 match IPCIDR using auto[ntt-ss-50118-showme]
INFO[0008] [TCP] 192.168.6.1:48781 --> 149.154.171.5 match IPCIDR using auto[ntt-ss-50118-showme]
INFO[0008] [TCP] 192.168.6.1:48783 --> 149.154.171.5 match IPCIDR using auto[ntt-ss-50118-showme]
```

**Comment by proletarius101** [comment]
Similar logic can be confirmed on test-url mode, too.
