### ISSUE TITLE
执行./clash -d . 出现问题 timeout 不明白什么意思

### ISSUE THREAD

**Issue by Wuotancp** [Dreamacro/clash#606]
tonny@tonny-PC:~/clash$ ./clash -d .
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890      
INFO[0005] [TCP] 127.0.0.1:53050 --> sdk1xyajs-data.xycdn.com doesn't match any rule using DIRECT 
INFO[0007] [TCP] 127.0.0.1:53054 --> gsp0.baidu.com doesn't match any rule using DIRECT 
WARN[0007] dial DIRECT error: dial tcp4 172.217.24.14:443: i/o timeout 
WARN[0012] dial DIRECT error: dial tcp4 172.217.24.14:443: i/o timeout 
WARN[0023] dial DIRECT error: dial tcp4 172.217.24.14:443: i/o timeout 
INFO[0024] [TCP] 127.0.0.1:53070 --> api.vc.bilibili.com doesn't match any rule using DIRECT 
INFO[0028] [TCP] 127.0.0.1:53080 --> sdk1xyajs-data.xycdn.com doesn't match any rule using DIRECT 
WARN[0031] dial DIRECT error: dial tcp4 172.217.24.14:443: i/o timeout 
INFO[0033] [TCP] 127.0.0.1:53090 --> translate.googleapis.com doesn't match any rule using DIRECT 
INFO[0033] [TCP] 127.0.0.1:53084 --> github.com doesn't match any rule using DIRECT 
INFO[0034] [TCP] 127.0.0.1:53088 --> github.githubassets.com doesn't match any rule using DIRECT 
INFO[0034] [TCP] 127.0.0.1:53086 --> github.com doesn't match any rule using DIRECT

**Comment by FoilHao** [comment]
I meet the same problem. Have you solved it?

**Comment by ruanhailiang** [comment]
I meet the same problem. Have you solved it?
