### ISSUE TITLE
[Feature] 为proxies api now 添加 all failed 状态

### ISSUE THREAD

**Issue by mting806** [Dreamacro/clash#607]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
api proxies 返回值 now 添加一个 failed 状态, 现在是 即使所有的服务器delay 为0 ， now 保持最后一次成功的服务器

我的一个应用场景是根据now的状态 热加载rule ， 目前我只能检查所有服务器最后一次 delay是不是都为0 来判断

**Comment by Dreamacro** [comment]
proxy API 会返回一个 history，包含最近十次的结果
