### ISSUE TITLE
[Feature] Add payload recycle for constant.UDPPacket

### ISSUE THREAD

**Issue by Kr328** [Dreamacro/clash#610]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

UDPPacket 接口的几个实现 (fakeConn
均从 pool.BufPool 中获取缓冲区 却没有回收
在接收大量 UDP 包时 可能会频繁 GC 影响性能
同时也不方便 inbound 实现 UDP 流量控制

### 可能的解决方案 Possible Solution

UDPPacket 中存在未被使用的函数 [Close](https://github.com/Dreamacro/clash/blob/206767247ea4c7f2a7ee4986ec638e54ad0dda35/constant/adapters.go#L139)
将这个函数的用途改成 回收缓冲区 似乎会更好

**Comment by Dreamacro** [comment]
fixed in https://github.com/Dreamacro/clash/commit/1825535abdfcf62461d6a61c94a1689165083dcb
