### ISSUE TITLE
fallback测速问题

### ISSUE THREAD

**Issue by xqXQzzz1** [Dreamacro/clash#611]
请问fallback选择方式是哪一种：
（1）全部测完选择第一个满足条件的；（2）按顺序测，满足条件就停止测速。
自动检测时（使用dashboard_Razord面板），发现所有的节点均检测延迟。
希望可以采用（2）的方式，这样可以减小机场的压力。
同时希望，可以自行设置fallback的timeout值。

**Comment by alexlee728** [comment]
@Dreamacro 感觉fallback可以优化成：按顺序测，满足条件（可以设置延时低于多少）就停止其他节点测速。
