### ISSUE TITLE
请教一个关于连接smb共享文件夹时候的问题

### ISSUE THREAD

**Issue by onlyJinx** [Dreamacro/clash#612]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
Rule:
  - IP-CIDR,192.168.1.1/24,DIRECT
  - IP-CIDR,192.168.137.1/24,DIRECT

……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
win10
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

大佬好 ,我电脑连接smb共享文件夹, 添加了这条规则后还是不能连接, 要关闭clash才可以正常连接,请问是我添加错了吗? 目标地址时 192.168.137.1, 添加的规则是  
- IP-CIDR,192.168.137.1/24,DIRECT
如果错了的话能否指点一下, 谢谢....

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by myfingerhurt** [comment]
Paste  your whole rules without server configurations.

**Comment by SuperNG6** [comment]
错了`- IP-CIDR,192.168.0.0/16,DIRECT`

**Comment by onlyJinx** [comment]
@myfingerhurt @SuperNG6 

thanks a lot, The problem has been solved.
