### ISSUE TITLE
[Feature]不同的规则命中同一个domain

### ISSUE THREAD

**Issue by zhea55** [Dreamacro/clash#614]
假如针对同一个网站有如下规则（这个域名的ip并不是这个，举例用）：

- IP-CIDR,121.51.0.0/16,DIRECT

- DOMAIN-SUFFIX,xclient.info,Proxy

我希望这个域名走代理，但实际上可能命中了上面的ip规则。

如果每个域名去查询ip，会很麻烦，我导入了国内的大量ip规则。

能不能有个优先级的规则

**Comment by Dreamacro** [comment]
把 ip 规则放下面

**Comment by 1-1-2** [comment]
规则是由上至下按顺序匹配的，在前的规则被触发，后面的就不会再进行匹配了
