### ISSUE TITLE
[Feature]使用DB-ip代替MaxMind作为GEOip的数据来源

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [Dreamacro/clash#615]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

使用DB-ip代替MaxMind作为GEOip的数据来源
并且希望以月为周期自动更新数据库
https://db-ip.com/db/download/ip-to-country-lite

### 可能的解决方案 Possible Solution

可以参考
https://github.com/qbittorrent/qBittorrent/pull/12014/files

**Comment by Dreamacro** [comment]
db-ip 提供了一个 mmdb 格式的 ip 数据，但是并没有一个稳定的下载地址，以及和 maxmind 相比，db-ip 有什么好处吗

**Comment by Natural-Harmonia-Gropius** [comment]
> db-ip 提供了一个 mmdb 格式的 ip 数据，但是并没有一个稳定的下载地址，以及和 maxmind 相比，db-ip 有什么好处吗

不需要license key

**Comment by BROBIRD** [comment]
> 
> 
> db-ip 提供了一个 mmdb 格式的 ip 数据，但是并没有一个稳定的下载地址，以及和 maxmind 相比，db-ip 有什么好处吗

似乎可以用爬虫定期抓取

**Comment by nasbdh9** [comment]
![QQ截图20200517020027](https://user-images.githubusercontent.com/26650222/82126932-9798d480-97e2-11ea-8cb4-a248126685ef.png)
![QQ截图20200517020114](https://user-images.githubusercontent.com/26650222/82126935-98ca0180-97e2-11ea-8789-a48b9c70cf82.png)

菜鸡互啄？...

**Comment by alecthw** [comment]
搞了个小项目，重新生成了GeoIP mmdb数据库，在MaxMind数据库的基础上，加入了china_ip_list和纯真CN数据库，重新生成了mmdb文件，匹配中国IP更为精确。
自己动手，丰衣足食
可以直接替换openclash中的Country.mmdb使用。
https://github.com/alecthw/mmdb_china_ip_list

**Comment by Dreamacro** [comment]
由于已有 @alecthw 的替代方案，问题 close
