### ISSUE TITLE
怎样配置Microsoft To Do应用绕过代理

### ISSUE THREAD

**Issue by wbmvincent** [Dreamacro/clash#620]
请问怎样配置这个应用直连？用抓包工具把该应用所有的链接请求都添加到规则里了还是无法同步，退出clash之后就正常

**Comment by beckball** [comment]
检查一下是否有所谓 微软服务 的列表在前 进行了先行匹配导致代理
或者最简单的方法 把这个uwp放回沙盒 就不会被clash接管（tap网卡模式可能不行

**Comment by jasoncool520** [comment]
> 请问怎样配置这个应用直连？用抓包工具把该应用所有的链接请求都添加到规则里了还是无法同步，退出clash之后就正常

请问下你是怎么解决的

**Comment by Her-ero** [comment]
> > 请问怎样配置这个应用直连？用抓包工具把该应用所有的链接请求都添加到规则里了还是无法同步，退出clash之后就正常
> 
> 请问下你是怎么解决的

https://github.com/Fndroid/clash_for_windows_pkg/issues/613
