### ISSUE TITLE
[Feature] 添加根据CNAME指向的FQDN匹配规则

### ISSUE THREAD

**Issue by Mosney** [Dreamacro/clash#621]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
OpenWrt 19.07.2 x86-64
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
没有，但存在IP路由黑洞，在GitHub相关IP上尤为严重

### 说明 Description
由于ISP存在路由黑洞，访问GitHub主站、pages、gist、cloudflareDNS等IP困难。
以GitHub为例，只在规则内添加GitHub相关域名不能匹配到使用自定义域名但实际托管在Pages网站、文档，并且因为将clash作为网关透明代理使用，不太能设置MATCH为PROXY。
### 可能的解决方案 Possible Solution
1. 受[AdGuardHome](https://github.com/AdguardTeam/AdGuardHome/commit/07a9c3bd452e474d0de31cce6b321156e9672b23)启发，clash似乎也可以根据CNAME指向的域名再匹配一次规则，上面的问题就不复存在。
2. 作为用户侧，将受影响的IP全部列入IPCIDR代理规则，例如在规则中添加GitHub所有IP，但这种方法存在明显弊端。

**Comment by Dreamacro** [comment]
不太好处理啊，现在最细粒度就是从 domain 到 ip，而且只要能反推域名，会直接把域名发给代理远程解析，所以应该不存在你说的这个问题

**Comment by Mosney** [comment]
举个例子，我本地的ISP无法直接打开Github pages，`ariang.mayswind.net` 这个网站就托管在Github pages，DNS给出的结果是cname到 `mayswind.github.io` 且它的A记录是`185.199.x.x`，浏览器发起的请求经过clash的时候只能匹配 `ariang.mayswind.net` 这个域名规则或`185.199.x.x`这个IP规则，反推域名也只能是`ariang.mayswind.net`和`185.199.x.x`互相反推，对于Github pages这种有很多私有域名指向的服务，域名规则特别难以套用，如果CNAME实现起来有困难的话只能把GitHub pages的IP都加上IPCIDR规则。

**Comment by lucifer9** [comment]
@Mosney 这种情况，感觉最好还是最后一条规则默认走代理。考虑到国内dns的现状，很多时候有些域名是有cname的但是必须翻墙用国外dns才能解析出来。比如 mail.koredump.org。所以为了cname正常，就得有个配置好的独立dns才行（clash本身dns的fallback机制只针对解析IP而不是cname）。比较起来还是默认走代理，常用国内域名单独列出来直连，再加上geoip，这样配置更加简洁明了。

**Comment by Mosney** [comment]
> @Mosney 这种情况，感觉最好还是最后一条规则默认走代理。考虑到国内dns的现状，很多时候有些域名是有cname的但是必须翻墙用国外dns才能解析出来。比如 mail.koredump.org。所以为了cname正常，就得有个配置好的独立dns才行（clash本身dns的fallback机制只针对解析IP而不是cname）。比较起来还是默认走代理，常用国内域名单独列出来直连，再加上geoip，这样配置更加简洁明了。

match走代理不适合作为网关透明代理用。你说的国内cname缺失的话，除去被污染的域名几乎没有公共DNS会直接返回最终的A结果，另外clash的两个DNS机制是当首要DNS组返回的Geo IP结果为非CN时取fallback组的结果，可以保证既不影响cdn友好性又不影响国外域名的正确解析，目前污染的IP都还是以fb、Twitter、softlayer为主的非CN IP，刨除上面提到的几乎没有的情况，你说的这个cname缺失并不会成立。

**Comment by Mosney** [comment]
当然，redir-host模式下match直连的副作用也很明显，只有域名规则时客户端直接向IP发起的TCP连接可能不会被成功反推出域名，只能匹配到match直连规则最终连接失败。
要是用fakeIP模式的话，作为网关透明代理的话副作用太大，很多服务会受影响（比如mDNS、NTP），跟着一路打补丁成本实在太高，反倒不如直接去查被墙服务的IP块，把常用的、容易反推失败的服务加到IP-CIDR规则里，例如我自己就手动查询GitHub和、Google和WikiMedia的IP块加到了规则里。

**Comment by lucifer9** [comment]
@Mosney 问题在于没人知道哪些域名被污染，除非自己遇到。所以也就没法估计可能被影响的范围。
用国内dns来解析的例子：
```
dig @114.114.114.114 mail.koredump.org cname

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> @114.114.114.114 mail.koredump.org cname
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 15800
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mail.koredump.org.		IN	CNAME

;; Query time: 23 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Thu Apr 16 22:59:41 CST 2020
;; MSG SIZE  rcvd: 35

```
可见查询cname压根儿没结果。但其实应该是 ghs.google.com。
而现在是要匹配cname，自然应该查cname而不是IP。所以clash内置的dns fallback机制对这种情况无效。除非强制直接用fallback解析cname。这就得本身配置了fallback且能正常工作才行。不知道实际用户里面满足这个要求的有多少比例。

另外请教一下，为什么说match走代理不适合作为网关透明代理呢？

**Comment by Mosney** [comment]
@lucifer9  
> 问题在于没人知道哪些域名被污染，除非自己遇到。所以也就没法估计可能被影响的范围。

https://github.com/gfwlist/gfwlist 这个仓库有足够长的历史了，早在clash出现前就已经有足够知名度了，另外还有各路现成的clash rules不也都基本包含了常用甚至非常用的被墙域名么？

> 所以clash内置的dns fallback机制对这种情况无效。

所以你真的试过在使用clash DNS切正确配置了上游的环境下查询一下这个域名么…你举例的这个域名我这边是没问题的，正常fallback并返回结果。

> 这就得本身配置了fallback且能正常工作才行。不知道实际用户里面满足这个要求的有多少比例。

我从这个issue一开始就说了使用场景是网关透明代理，而网关透明代理必然要正确配置DNS。并且我也提到了用户侧可能的解决方案。

> 另外请教一下，为什么说match走代理不适合作为网关透明代理呢？

前面说了
