### ISSUE TITLE
[Feature] 在linux上利用splice syscall提高转发性能

### ISSUE THREAD

**Issue by ccaapton** [Dreamacro/clash#622]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
archlinux
* 使用者的操作系统 (the OS running on the client)
Linux 5.5.1

### 说明 Description

Golang 2018年在linux上的加入io.Copy的优化，如果两端都是tcp socket,那么io.Copy会直接使用splice syscall在两个socket间拷贝数据，无需在user space和kernel space间来回拷贝。 参加[这里](https://acln.ro/articles/go-splice)，还有 https://github.com/golang/go/issues/10948 。benchmark的结论是当chunk size较大时，性能有显著提高。

### 可能的解决方案 Possible Solution

当平台为linux时，把io.CopyBuffer改为io.Copy

**Comment by Dreamacro** [comment]
https://golang.org/src/io/io.go?s=12796:12856#L353-L379

**Comment by ccaapton** [comment]
原来是这样:) 

那如果两端有readfrom或者writeto实现的话，是否是可以节约这些buffer allocation呢? https://github.com/Dreamacro/clash/blob/master/tunnel/connection.go #L125 #L132

**Comment by Dreamacro** [comment]
问题是传到 relay 的时候，两边就已经不是纯粹的 net.TCPConn 了，中间可能隔了很多层

**Comment by ccaapton** [comment]
明白了，多谢解释！
