### ISSUE TITLE
[Feature Request] Add a support of DNSSEC

### ISSUE THREAD

**Issue by lincolnguang** [Dreamacro/clash#626]
Thanks for submitting a feature request towards the Clash core!
But before so, please do the following checklist:

- [x] I have searched on the [issue tracker](……/) before creating the issue.

Please understand that we close issues that fail to follow the issue template.
------------------------------------------------------------------
* Is your ISP performing DNS pollution?

Yes.

### Description
> Engineers in the Internet Engineering Task Force (IETF), the organization responsible for the DNS protocol standards, long realized the lack of stronger authentication in DNS was a problem. Work on a solution began in the 1990s and the result was the DNSSEC Security Extensions (DNSSEC).

> DNSSEC strengthens authentication in DNS using digital signatures based on public key cryptography. With DNSSEC, it's not DNS queries and responses themselves that are cryptographically signed, but rather DNS data itself is signed by the owner of the data.

> Every DNS zone has a public/private key pair. The zone owner uses the zone's private key to sign DNS data in the zone and generate digital signatures over that data. As the name "private key" implies, this key material is kept secret by the zone owner. The zone's public key, however, is published in the zone itself for anyone to retrieve. Any recursive resolver that looks up data in the zone also retrieves the zone's public key, which it uses to validate the authenticity of the DNS data. The resolver confirms that the digital signature over the DNS data it retrieved is valid. If so, the DNS data is legitimate and is returned to the user. If the signature does not validate, the resolver assumes an attack, discards the data, and returns an error to the user.

> DNSSEC adds two important features to the DNS protocol:

> - Data origin authentication allows a resolver to cryptographically verify that the data it received actually came from the zone where it believes the data originated.
> - Data integrity protection allows the resolver to know that the data hasn't been modified in transit since it was originally signed by the zone owner with the zone's private key.

[More information](https://www.icann.org/resources/pages/dnssec-what-is-it-why-important-2019-03-05-en)

DNSSEC can help clash against DNS pollution, can provide a reliable DNS result by UDP (quicker than DNS over TLS/HTTPS).

Most of Public DNS server, including Adguard Home/Unbound/DNSmasq, has been provided DNSSEC supported. [How to check?](https://www.cloudflare.com/ssl/encrypted-sni/)

**Comment by Mosney** [comment]
DNSSEC对DNS污染几乎没有任何意义，且不说有多少域名做了DNSSEC支持，就算你知道你得到的结果是错误的你也无法通过原来的方式获取到正确的结果，毫无作用。再通俗一点，你开启DNSSEC只能是知道你被污染但是你什么也做不了。
