### ISSUE TITLE
请问一下，安装包无法安装

### ISSUE THREAD

**Issue by songyuc** [Dreamacro/clash#628]
尊敬的开发者，你好，我下载了安装包之后好像无法安装，显示这样的错误，
![图片](https://user-images.githubusercontent.com/27288110/78973189-f616c700-7b41-11ea-9765-9a451f6cf6da.png)
期待你的回复！

**Comment by AmBeta** [comment]
解压出来是可执行文件，在 shell 里可以直接用命令运行，参考文档。
你可能需要添加文件的执行权限：`chmod +x clash-linux-amd64-v0.19.0`

**Comment by songyuc** [comment]
@AmBeta ，好的，谢谢你的回复，
我输出了这样的结果，是对的吗？
```bash
$ wget -O config.yml https://www.crosszcloud.xyz/link/P5z9Ca9CmE3A47eu?clash=1&log-level=info
[1] 12248

正在把输出重定向至 “wget-log”。
log-level=info：未找到命令
```
