### ISSUE TITLE
[Feature] 根据入口协议类型分别设定不同的转发规则

### ISSUE THREAD

**Issue by zhx79513** [Dreamacro/clash#629]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 说明 Description

<p>    目前规则针对来源的关键字只有SRC-IP-CIDR和SRC-PORT，我想根据来源的协议类型（socks5, http）分别设定对应的规则。这样需要全局代理的可以通过socks5来转发，需要根据规则来进行代理的，可以用http转发。</p>
<p>    比如在浏览器里用SwitchyOmega来通过socks5协议转发给Clash，希望Clash能将socks5的连接无条件走代理，在其他支持系统代理的应用里，可以直接通过系统代理（http）来根据Clash的规则判断是否需要走代理。</p>
<p>    我目前遇到的情况是，如果我浏览器用系统代理，就无法使用自动更新的自动代理规则，需要在Clash里逐条手动添加，也无法为不在自动代理规则里的域名强制走代理；如果浏览器用SwichyOmega来控制，则Clash无法代理其他应用，比如用steam客户端打开社区；如果浏览器用SwichyOmega来控制，其他应用用Proxifier等强制代理软件转发到Clash的话，steam客户端打开社区会出现invalid SSL certificate错误。</p>

**Comment by Dreamacro** [comment]
目前的解决方案是通过 script 的方式控制你想要的逻辑 https://github.com/Dreamacro/clash/releases/tag/premium
