### ISSUE TITLE
[Bug] access redir port  cause log loop ...

### ISSUE THREAD

**Issue by Doraemon-2010** [Dreamacro/clash#634]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [1] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [1] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [1] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
……
```

### Clash log

```
……
```
ime="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59749 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59723 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59685 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59697 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59759 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59809 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59797 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59829 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59821 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59813 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59817 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59811 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59841 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59831 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59785 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59851 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59857 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:32811 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:60437 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:33669 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:34103 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:34115 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:34127 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59783 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:34141 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:35049 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:35081 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:35633 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:35635 --> 192.168.199.7 match IPCIDR using DIRECT"
time="2020-04-11T19:28:56+08:00" level=info msg="[TCP] 192.168.199.7:59771 --> 192.168.199.7 match IPCIDR using DIRECT"

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. 在手机上设置IP的地址设置代理服务器，使用 7892端口
2. 查看 clash 的日志在疯狂刷新，192.168.199.7:PORT -> 192.168.199.7 ， 回环导致刷新
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

### 可能的解决方案 Possible Solution

因为功能是可以正常使用的，只是大量的日志输出导致CPU/IO 占用过高。
一种方式是在规则中增加 PASS 规则，遇到的直接不处理对应IP，或者域名，
另外一种方式是在对比源地址和目标地址一致不处理？可能导致其他问题产生。

**Comment by CyberKoo** [comment]
类似问题已经提过了 #425

**Comment by Dreamacro** [comment]
redir 不是代理服务器。。。

**Comment by Doraemon-2010** [comment]
> redir 不是代理服务器。。。

不过这个异常使用会导致刷LOG。。或者回环。。应该避免。
可以不让用。不过不应该回环。。刷LOG。。虽然这些都是合理的。
不过不合理的用法，应该有防范。
