### ISSUE TITLE
运行之后没作用

### ISSUE THREAD

**Issue by daxinnan** [Dreamacro/clash#635]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```

`Rule规则那些需要上传，除了Proxy我不知道还有哪些算是敏感信息`
# HTTP 代理端口
port: 7890 

# SOCKS5 代理端口
socks-port: 7891 

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892 

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: '' 

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

```

### Clash log

```
./clash -d .
INFO[0000] Start initial compatible provider Others     
INFO[0000] Start initial compatible provider GlobalTV   
INFO[0000] Start initial compatible provider AsianTV    
INFO[0000] Start initial compatible provider Proxy      
INFO[0000] Start initial compatible provider Domestic   
INFO[0000] HTTP proxy listening at: :7890               
INFO[0000] SOCKS proxy listening at: :7891              
INFO[0000] Redir proxy listening at: :7892              
WARN[0000] Failed to start Redir UDP Listener: operation not permitted 
INFO[0000] RESTful API listening at: 0.0.0.0:9090     
DEBU[1209] [DNS] ocsp.digicert.com --> 117.18.237.29    
INFO[1209] [TCP] 127.0.0.1:57288 --> ocsp.digicert.com match Match using Others[V2-中转488|广东-香港|解锁|x2.0|V2ray] 
DEBU[1209] [DNS] ocsp.digicert.com --> 117.18.237.29    
INFO[1209] [TCP] 127.0.0.1:57292 --> ocsp.digicert.com match Match using Others[V2-中转488|广东-香港|解锁|x2.0|V2ray]
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Ubuntu 19.10
* 使用者的操作系统 (the OS running on the client)
Ubuntu 19.10
* 网路环境或拓扑 (network conditions/topology)
教育网有线
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. 在不使用任何工具直连校园网有线时可以访问`google.com.hk`，但是facebook，youtube都打不开。但是在win10笔记本上使用校园网无线使用`clash for windows`可以访问facebook等。
2. `dashboard`里代理下面全是灰的，点测速没有反应。
3. ……

**我预期会发生……？**

正常访问
**实际上发生了什麽？**

**Comment by Dreamacro** [comment]
二进制不会帮你去做添加系统代理的设置的，你可能需要自己往系统设置里添加代理

**Comment by daxinnan** [comment]
> 二进制不会帮你去做添加系统代理的设置的，你可能需要自己往系统设置里添加代理

我添加了系统代理的，
![image](https://user-images.githubusercontent.com/26436171/79448309-c836f400-8013-11ea-8c36-a24ead4dde18.png)

**Comment by Dreamacro** [comment]
如果日志里没有任何连接日志，说明流量没走到 clash

**Comment by daxinnan** [comment]
可能是校园网的问题，放弃了

**Comment by daxinnan** [comment]
找到原因了，是时间没有同步的问题，我是Ubuntu19.10,终端下运行
`sudo systemctl restart systemd-timesyncd.service`即可

**Comment by iloahz** [comment]
遇到同样的错误：
`WARN[0000] Failed to start Redir UDP Listener: operation not permitted`

用sudo运行clash则可以，系统是ubuntu 20.04。请问设计上运行clash需要sudo权限吗，还是我们系统设置的问题？

**Comment by xaotag** [comment]
@daxinnan 谢谢 👍

**Comment by lizenghui** [comment]
> 遇到同样的错误：
> `WARN[0000] Failed to start Redir UDP Listener: operation not permitted`
> 
> 用sudo运行clash则可以，系统是ubuntu 20.04。请问设计上运行clash需要sudo权限吗，还是我们系统设置的问题？

同问

**Comment by foreverlms** [comment]
> 遇到同样的错误：
> `WARN[0000] Failed to start Redir UDP Listener: operation not permitted`
> 
> 用sudo运行clash则可以，系统是ubuntu 20.04。请问设计上运行clash需要sudo权限吗，还是我们系统设置的问题？

同样的问题，来个人注意一下吧。

**Comment by xnxin** [comment]
Try this `sudo setcap cap_net_bind_service,cap_net_admin+ep /path/to/clash`

**Comment by increase24** [comment]
> Try this `sudo setcap cap_net_bind_service,cap_net_admin+ep /path/to/clash`

It works for issue "WARN[0000] Failed to start Redir UDP Listener: operation not permitted".

**Comment by 70iscoolest** [comment]
解决了，谢谢！
