### ISSUE TITLE
[Bug] hosts 不生效

### ISSUE THREAD

**Issue by h0cheung** [Dreamacro/clash#636]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
hosts:
  '<一个完整域名>': '198.19.0.133'
dns:
  enable: true
  listen: :12355
  ipv6: true
  enhanced-mode: redir-host
```
域名/IP 加/不加引号均测试过，都存在相同问题
### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Android（magisk）
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
-t nat -I OUTPUT -p tcp  -m owner --uid-owner ${CFA_UID} -d 198.19.0.133 -j REDIRECT --to-ports ${REDIR-PORT}

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无关
* 其他
……

### 说明 Description

配置 hosts 后进行 DNS 查询，仍能查询到正确结果，hosts 似乎没有起到作用
### 重现问题的具体布骤 Steps to Reproduce

1. 安装 clash for magisk，编译 clash（dev 分支，arm64 架构）替换文件
2. 运行一个配置，其中 DNS 配置如上
3. 通过 termux，使用 dig 命令指定 DNS 服务器与端口查询 hosts 中的域名

**我预期会发生……？**

结果为 198.19.0.133
**实际上发生了什麽？**

结果为实际 IP

**Comment by Dreamacro** [comment]
hosts 不会影响 dns server 的结果

**Comment by h0cheung** [comment]
@Dreamacro 后续版本可以考虑让 DNS Server 也支持 hosts 吗

**Comment by Dreamacro** [comment]
@h0cheung 一开始是有的，但后来我看系统的 hosts 其实也不会影响系统 dns 的 dig 结果，就改成了现在这样

**Comment by Love4Taylor** [comment]
@Dreamacro 但是这样会造成 CFW Tun 模式 和 CFA 无法使用 hosts 固定 IP，就很麻烦。

**Comment by zhigang** [comment]
@Dreamacro 不支持本地hosts确实很麻烦，现在想用本地hosts，就需要先关闭这个。

**Comment by happy-tao** [comment]
> > @Dreamacro 不支持本地hosts确实很麻烦，现在想用本地hosts，就需要先关闭这个。
> 
> 我使用的是Win10，没有使用 TAP Mode，但是我注意到这样一个细节：
> 
> 假如我想实现这样的hosts效果：192.168.1.1 : r.com
> 你可以专门设置一个规则，比如 DOMIAN:r.com,DIRECT，当设置为 直连时，Clash会自动走系统的 Hosts。

试了一下，如果是DIRECT，并不会直接走系统的Hosts，而是走解析后的域名。
尝试了Bypass绕过域名是有效的。
在CFW的Bypass配置中加入`- "r.com"` 或 `- "*.r.com"`。

**Comment by NyaMisty** [comment]
@Dreamacro  但是，Shadowrocket、Surge等等软件也都是支持设置DNS Override的啊。
系统dig不管hosts是因为libc会去查找hosts，问题是应用程序又不会去查clash的hosts

**Comment by ooing** [comment]
@zhigang   您是怎么解决的  ，这样子本地开发很不方便啊

**Comment by jitash** [comment]
+1

**Comment by Jinx-Q** [comment]
运行Clash后本地hosts失效解决方法：打开主界面，找到profiles修改yml配置，dns: enable: false

**Comment by SundayGoGo** [comment]
> AP Mode

host依然失效

**Comment by miozus** [comment]
```YAML
dns:
  enable: false
```
亲测有效：优先提高本地的端口映射关系。

只是 Notion 提示本地连接433被拒绝，我改成走代理。

**Comment by martjay** [comment]
> 

我这边并没有生效，我是直接复制你的代码粘贴到YAML规则里，试过重启clash仍然是hosts不生效

**Comment by ooing** [comment]
> > 
> 
> 我这边并没有生效，我是直接复制你的代码粘贴到YAML规则里，试过重启clash仍然是hosts不生效

@NyaMisty   贴出配置
