### ISSUE TITLE
[Bug] SOCKS5 的 UDP 处理似乎存在问题

### ISSUE THREAD

**Issue by neteroster** [Dreamacro/clash#639]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```YAML
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
experimental:
  ignore-resolve-fail: true
#...
```

### Clash log

无相关日志。

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
**Windows 10** 1909 (18363.778)
* 使用者的操作系统 (the OS running on the client)
**Windows 10** 1909 (18363.778)
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. 启动一个 [gost](https://github.com/ginuerzh/gost) 监听 `0.0.0.0:2333` 并通过代理链（SOCKS5 Clash）转发到远程服务器 `a.b.c.d`
```
./gost -L=udp://0.0.0.0:2333/a.b.c.d:51820 -F=socks5://127.0.0.1:7891
```
2. 使用 [WireGuard](https://www.wireguard.com/) 连接 `192.168.1.53:2333`。（注：这里用局域网 IP 而不是 `127.0.0.1` 是因为 WireGuard 的一个问题）。
3. 数据无法被正确转发

**我预期会发生……？**
数据应被正确转发：WireGuard <-> gost <-> Clash(SOCKS5) <-> ...

**实际上发生了什麽？**
数据未能被正确转发，日志无相关记录。

### 更多信息 More Information

gost 的 log:（注：由于 WireGuard 的一个问题，必须使用局域网 IP 连接，因此此处的 IP 是 `192.168.1.53` 而非 `127.0.0.1`）
```
PS ...> ./gost -L=udp://0.0.0.0:2333/a.b.c.d:51820 -F=socks5://127.0.0.1:7891
2020/04/17 11:57:53 route.go:645: udp://0.0.0.0:2333 on [::]:2333
2020/04/17 11:58:04 udp.go:118: [udp] 192.168.1.53:8000 -> [::]:2333 (1)
2020/04/17 11:58:04 forward.go:188: [udp] 192.168.1.53:8000 - [::]:2333
2020/04/17 11:58:04 forward.go:203: [udp] 192.168.1.53:8000 - [::]:2333 : EOF
2020/04/17 11:58:04 udp.go:111: [udp] 192.168.1.53:8000 closed (0)
2020/04/17 12:02:54 udp.go:118: [udp] 192.168.1.53:8000 -> [::]:2333 (1)
2020/04/17 12:02:54 forward.go:188: [udp] 192.168.1.53:8000 - [::]:2333
2020/04/17 12:02:54 forward.go:203: [udp] 192.168.1.53:8000 - [::]:2333 : EOF
2020/04/17 12:02:54 udp.go:111: [udp] 192.168.1.53:8000 closed (0)
2020/04/17 12:03:00 udp.go:118: [udp] 192.168.1.53:8000 -> [::]:2333 (1)
2020/04/17 12:03:00 forward.go:188: [udp] 192.168.1.53:8000 - [::]:2333
2020/04/17 12:03:00 forward.go:203: [udp] 192.168.1.53:8000 - [::]:2333 : EOF
2020/04/17 12:03:00 udp.go:111: [udp] 192.168.1.53:8000 closed (0)
```

但是，如果本地启动一个 gost SOCKS5 代理 `./gost -L=socks5://127.0.0.1:2334` 并转发给 gost 的 SOCKS5 服务 `./gost -L=udp://0.0.0.0:2333/a.b.c.d:51820 -F=socks5://127.0.0.1:2334` 这样是没问题的，所以我更倾向于这是 Clash 的问题，但是无法确认具体细节。没有找到专门能测试 SOCKS5 的 UDP 测试工具。

**Comment by Dreamacro** [comment]
cc @comzyh @xjasonlyu

**Comment by xjasonlyu** [comment]
@neteroster 你先用v2的这个socks配置试试行不行，我本地没有wg环境似乎不能复现你的问题。。

```json
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}
```

**Comment by neteroster** [comment]
@xjasonlyu 这个也不行。刚刚重新仔细读了一下 gost 的文档，其中提到

>如果要转发SOCKS5的BIND和UDP请求，代理链的末端(最后一个-F参数)必须是GOST SOCKS5类型代理。

所以应该是 gost 的 SOCKS5 内部用它自己的方法封装了 UDP，跟 Clash 没关系了。

谢谢你的帮助。

**Comment by xjasonlyu** [comment]
的确，看了一下gost源码，它的socks和rfc实现有一些不同。。
