### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by updater1234** [Dreamacro/clash#64]
./clash-linux 
INFO[0000] Can't find MMDB, start download              
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x784846]

goroutine 1 [running]:
github.com/Dreamacro/clash/config.parseDNS(0x0, 0xc00019c3c0, 0x4, 0x4)
	/home/travis/gopath/src/github.com/Dreamacro/clash/config/config.go:391 +0x26
github.com/Dreamacro/clash/config.Parse(0xc00027e000, 0x24, 0x19, 0x887bb3, 0xa)
	/home/travis/gopath/src/github.com/Dreamacro/clash/config/config.go:133 +0x142
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0xc00027e000, 0x24, 0x24, 0x8f0340, 0x10)
	/home/travis/gopath/src/github.com/Dreamacro/clash/hub/executor/executor.go:20 +0x35
github.com/Dreamacro/clash/hub/executor.Parse(0x10, 0x10, 0x8)
	/home/travis/gopath/src/github.com/Dreamacro/clash/hub/executor/executor.go:15 +0x45
github.com/Dreamacro/clash/hub.Parse(0xc000020220, 0x19)
	/home/travis/gopath/src/github.com/Dreamacro/clash/hub/hub.go:10 +0x26
main.main()
	/home/travis/gopath/src/github.com/Dreamacro/clash/main.go:39 +0x8b

系统:deepin15.8
请问这错误是软件自身问题还是与系统有关，该如何解决？

**Comment by Dreamacro** [comment]
是最新的 clash 吗

**Comment by updater1234** [comment]
对没错，一运行就报这个错

**Comment by beyondkmp** [comment]
> 对没错，一运行就报这个错

你的配置能给下吗？

**Comment by Dreamacro** [comment]
@updater1234 我这有点疏忽了，你如果不用 dns 先把 `dns:` 注释掉，我一会修复
