### ISSUE TITLE
[Feature]希望可以将trojan客户端更新为trojan-go并加入gost支持

### ISSUE THREAD

**Issue by openips** [Dreamacro/clash#641]
trojan-go
https://github.com/p4gefau1t/trojan-go
兼容trojan客户端
并且支持CDN流量中转(基于WebSocket over TLS/SSL)

gost
https://github.com/ginuerzh/gost

**Comment by Dreamacro** [comment]
没看懂，为什么要将内部实现的 Trojan 改成 trojan-go 的。还有 gost 支持是什么

**Comment by openips** [comment]
gost是另外一种科学上网方案的客户端
Trojan-go是增加了ws支持的Trojan 兼容trojan得同时增加了新功能

**Comment by Dreamacro** [comment]
理论上不会支持非 Trojan 官方协议，如果真的需要 gost 的功能建议直接用 gost

**Comment by openips** [comment]
好的 谢谢

**Comment by tanpengsccd** [comment]
主要是trojan-go + ws + tls 可以白嫖CDN，对于线路不好的小鸡鸡 会有些提升。希望作者 能考虑加入一下支持。
