### ISSUE TITLE
[Feature]Windows下可以用tap-windows，支持ipv6

### ISSUE THREAD

**Issue by a86913179** [Dreamacro/clash#646]
https://github.com/a86913179/clash-tap （我只会用batch，仅提供一个思路）

我通过batch把clash和badvpn-tun2socks结合起来，达到支持ipv6和udp远程解析并转发的效果，不管是使用fake-ip模式还是redir-host，在log里都能看到udp域名请求，并匹配规则分流，说明tun2socks正确转发了，然后edge chromium开启QUIC，打开youtube看到走的是UDP流量，说明UDP域名也远程解析了。而且ipv6也支持分流，根据geoip,cn,direct规则，国内ipv6走本地的ipv6，国外的ipv6走vps的ipv6。

目前流量（根据Rule：GEOIP,CN,DIRECT & MATCH,PROXY）是国内域名走config.yaml的nameserver解析，国外域名远程解析，TCP和UDP（IPv4 & IPv6）是国内直连，国外走代理。在我的Windows 10 Pro x64上完美运行。

本地千兆宽带实测走tap的直连流量可以跑满930Mbps（没有万兆设备），走tap的代理流量可以跑到700Mbps（GIA CN2线路原因，主机商带宽不足，如果是IPLC应该也可以跑到930Mbps）。

目前不管是badvpn-tun2socks还是go-tun2socks都没适配wintun，所以tap-windows是目前的唯一选择。因为go-tun2socks for windows还不支持ipv6，所以用了badvpn-tun2socks。

**Comment by Dreamacro** [comment]
也许这些你需要到 clash for windows 底下提
