### ISSUE TITLE
Install Clash server on Heroku ? Or Ubuntu VPS ?

### ISSUE THREAD

**Issue by ingnelson** [Dreamacro/clash#648]
Hi.
How can I install clash server on heroku ? 
Can somebody help or the admin add the way to create a server ?
I just install the clash on Android and I want to try it .

I hope you answer.

**Comment by Dreamacro** [comment]
clash just a client, not a server. and only provider HTTP or socks5 server. you can run the corresponding protocol server on your VPS.
