### ISSUE TITLE
[Bug] secret可以被绕过

### ISSUE THREAD

**Issue by Limgmk** [Dreamacro/clash#650]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [y ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [y ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [y ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [y ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

### 说明
只要在head中加入Authorization: Bearer就能绕过api鉴权

### 重现问题的具体布骤

发送请求时加入Authorization: Bearer加上空密码(一定要是空密码，错误密码不行)，即使配置文件中设置了secrect也能获取到数据
如图，空密码鉴权通过:
![Snipaste_2020-04-24_23-15-49](https://user-images.githubusercontent.com/45861815/80230563-a1934180-8641-11ea-9b55-7f4b111e821e.png)

密码错误鉴权不通过:
![Snipaste_2020-04-24_23-16-50](https://user-images.githubusercontent.com/45861815/80230446-7dcffb80-8641-11ea-986f-45bfabc7e45e.png)

密码正确鉴权通过:
![Snipaste_2020-04-24_23-17-13](https://user-images.githubusercontent.com/45861815/80230480-87596380-8641-11ea-881b-e6df54f0125a.png)

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by Dreamacro** [comment]
fixed in dev
