### ISSUE TITLE
通过RESTful API更改节点代理返回{"message":"Body invalid"}

### ISSUE THREAD

**Issue by YH0426** [Dreamacro/clash#659]
使用
```
curl -X GET http://127.0.0.1:9090/proxies/TestProxyGroup
```
能正常获取节点组信息

使用
```
curl -X PUT -H "Content-Type: application/json" --data '{"name":"REJECT"}' http://127.0.0.1:9090/proxies/TestProxyGrou
```
返回
```
{"message":"Body invalid"}  
```

**Comment by Dreamacro** [comment]
我本地测试正常

**Comment by thank243** [comment]
put方式似乎有点问题，data必须时字符串才行。这样会导致python报错。只有先dump成字符串才能执行。

**Comment by Dreamacro** [comment]
@thank243 是标准的 restful http server

**Comment by TommyLe1** [comment]
今天也遇到了一样的问题：
curl -X PUT -H "Content-Type: application/json" --data '{"name":"REJECT"}' http://127.0.0.1:9090/proxies/TestProxyGrou
curl -X PUT  --data "name=REJECT" http://127.0.0.1:9090/proxies/TestProxyGrou
都遇到一样的问题：{"message":"Body invalid"}  
系统是win10. 请问有没有解决办法呀？

**Comment by TommyLe1** [comment]
curl -X PUT --data '{"name":"testnode"}' --url "http://127.0.0.1:9090/proxies/test"
或者在python里面：
	api = "http://localhost:9090/proxies/test"
	paramDict = { 'name': "testnode" }
	response = requests.put(url=api, data=paramDict).json()
返回值都是body invalid,有点摸不着头脑。难道是我电脑哪里配置有问题吗？

**Comment by thank243** [comment]
marshal成str再提交。

**Comment by TommyLe1** [comment]
打印了一下返回的状态码是400 ，再查下资料看看能不能找到办法

**Comment by TommyLe1** [comment]
好的，我试一下再来反馈

**Comment by TommyLe1** [comment]
py代码：
	api = "http://127.0.0.1:9090/proxies/test"
	data = { 'name': "testnode" }
	paramDict = marshal.dumps(data)
	response = requests.put(url=api, data=paramDict)
	print(paramDict)
	print(response.status_code)
	print(response.json())
返回值：
b'\xfb\xda\x04name\xda\x08testnode0'
400
{'message': 'Body invalid'}

**Comment by thank243** [comment]
`params = json.dumps({"name": server['name']}, ensure_ascii=False) 
             req_url = requests.put(f"http://127.0.0.1:{config['controlPort']}/proxies/GLOBAL", 
                                    data=params.encode('utf-8'))`
测试通过

**Comment by TommyLe1** [comment]
代码成功运行了，非常感谢，由于确定了是data参数的问题，我发现curl在win10的cmd环境下data参数可以改为：
--data "{\"name\":\"testnode\"}"
也就不会报错了。
再次感谢！

**Comment by TommyLe1** [comment]
--data "{\\"name\\":\\"testnode\\"}"

**Comment by holmesconan** [comment]
@Dreamacro 为什么不直接接受 Content-Type: application/x-www-form-urlencoded，或者兼容也可以啊…… RESTful API 其实默认是 form 的吧？好像这种 JSON 模式的有点奇怪呢…… 我最近都放弃 RESTful 了，只有累死 proxies 这种明显有 resource 特点的才用一下，其他时候我都改成 JSON RPC 这种 API Schema 了……

**Comment by suqingdong** [comment]
> `params = json.dumps({"name": server['name']}, ensure_ascii=False)             req_url = requests.put(f"http://127.0.0.1:{config['controlPort']}/proxies/GLOBAL",                                    data=params.encode('utf-8'))` 测试通过

with `requests`, just use `json` instead of `data` parameter:
```python
requests.put('http://127.0.0.1:9090/proxies/GLOBAL', json={'name': 'xxxx'})
# <Response [204]>  means success
```
