### ISSUE TITLE
[Bug]节点转发存在顺序问题

### ISSUE THREAD

**Issue by finemist** [Dreamacro/clash#664]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [√] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [√] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [√] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
- name: 新加坡
    type: relay
    use:
      - hk
    proxies:
      - singapore
……
```

### 说明 Description
我注意到proxy-groups组里的节点总是按照先proxies再proxy-providers的方式排列的，一般情况下这很好用。但是当我使用中继功能时，程序便自动将proxies里的节点放到use之前，这和用户的预期不同

**我预期会发生……？**

Traffic: clash <-> hk <-> singapore <->  Internet
**实际上发生了什麽？**

Traffic: clash <-> singapore <-> hk <->  Internet

**Comment by Dreamacro** [comment]
这是一个目前预期的效果，即：proxies 总在 provider 之前，可以将 proxies 里的东西单独封装成一个 provider，在 use 字段里，会遵循 provider 的顺序。这不是一个 bug

**Comment by finemist** [comment]
感谢对程序细节的说明。将节点封装成provider确实可以解决这个问题
