### ISSUE TITLE
请教一下，有人尝试过在edgeRouterLite3路由上Lite3用clash透明代理吗？

### ISSUE THREAD

**Issue by JunShine** [Dreamacro/clash#666]
场景：
1.clash设置redir-port端口为7892，直接把clash部署到路由器上，http和sockets5代理都没问题可用的
2.EdgeRouter路由器，固件 v2.0.8-hotfix.1是基于Debian的。但是iptable没有xt_owner.ko不能用 --uid-owner

使用：
在路由增加iptables规则，在OUTPUT链上增加重定向到7892端口：
iptables -t nat -N Clash
iptables -t nat -A Clash -d 192.168.0.0/24 -j RETURN
iptables -t nat -A PREROUTING -p tcp -j Clash
iptables -t nat -A Clash -p tcp -j REDIRECT --to-ports 7892

问题：
所有网页都无法访问
curl www.baidu.com和curl www.google.com都是
curl: (7) Failed to connect to www.baidu.com port 80: Connection refused
这个什么原因呢，不太懂呃

**Comment by trott90** [comment]
edgerouterlite3上搞，OUTPUT链完全是不需要的啊

**Comment by JunShine** [comment]
> edgerouterlite3上搞，OUTPUT链完全是不需要的啊

能否请教一下怎么设置iptables呢~~不懂把流量转发到clash的redir-port端口呃。

**Comment by JunShine** [comment]
呃发现问题了，我在lite3路由用错用了mips64架构的程序了，导致clash可正常运行，但是redir-port是不生效的，iptables无论怎么设置clash都完全没有流量记录的。
