### ISSUE TITLE
[BUG] 规则匹配存在 DNS 解析行为时 双栈 Dial 失效

### ISSUE THREAD

**Issue by liuyunyue** [Dreamacro/clash#668]
无论电脑和手机都是ipv6优先的，但开启cfw或是cfa后，国内直连流量就变成ipv4优先了。这是否是clash内核的原因？是的话建议改成ipv6优先，目前国内ipv6速度还是不错的，谢谢

**Comment by Kr328** [comment]
目前 Clash 的实现为 同时连接 v4 v6 取 **优先建立的连接** 进行转发

速度不错为什么还会优先命中 IPv4

**Comment by liuyunyue** [comment]
> 目前 Clash 的实现为 同时连接 v4 v6 取 **优先建立的连接** 进行转发
> 
> 速度不错为什么还会优先命中 IPv4

When resolving a domain, Clash resolves both A/AAAA by default (but v4 is preferred when connecting). If set to false, Clash won't ask for AAAA. This has nothing to do with the Clash DNS server itself, nor does it prioritises IPv6 connection when both v4/v6 is available

**Comment by liuyunyue** [comment]
这#662中回复的是ipv4优先

还有我测了下国内视频网站，v4和v6延时几乎相同

**Comment by liuyunyue** [comment]
以现在国内国外ipv6的普及程度和网络环境，以及网络发展趋势，理应ipv6优先。弄个开关也好

**Comment by Kr328** [comment]
读代码 请 不要别人说什么你就信

如果你能让 `dualStackDailContext` 里的 v6 跑的更快 这个问题立即得到解决

https://github.com/Dreamacro/clash/blob/dev/component/dialer/dialer.go

**Comment by liuyunyue** [comment]
> 读代码 请 不要别人说什么你就信
> 
> 如果你能让 `dualStackDailContext` 里的 v6 跑的更快 这个问题立即得到解决
> 
> https://github.com/Dreamacro/clash/blob/dev/component/dialer/dialer.go

刚试了下，视频网站的数据服务器域名，ipv6延时十几ms，ipv4延时三十几ms，但事实是连接的ipv4，并没有连接ipv6地址

**Comment by Kr328** [comment]
请务必使用 tcping 而不是 ping

**Comment by liuyunyue** [comment]
> 请务必使用 tcping 而不是 ping

再次用tcping确认，还是选择延迟高的v4地址而不选择延迟低的v6地址
(这个毫无疑问，通过浏览器插件可以看到视频网站这个传输视频的域名，这个域名对应多个v4和v6地址，查询后发现他们并不是同一个地方的，v4是外省的，延迟比较高，但还是选择v4传输数据)

**Comment by Kr328** [comment]
1. DNS 流量经过 Clash 吗 (通过日志观察是否存在域名
2. Clash 的 DNS 与 主机的 DNS 是否一致 (不同区域  不同 DNS 解析到的 CDN 不同 很大程度上会影响延迟

**Comment by liuyunyue** [comment]
> 1. DNS 流量经过 Clash 吗 (通过日志观察是否存在域名
> 2. Clash 的 DNS 与 你测试目标网站的 DNS 是否一致 (不同区域  不同 DNS 解析到的 CDN 不同 很大程度上会影响延迟

我现在为了验证，拿自己域名测试了，域名同时设置一个v4地址和一个v6地址，v4地址60ms，v6地址20ms。
不开启cfa，浏览器访问的是v6地址的网页，开启cfa后，浏览器访问就变成v4地址的页面

拿cfw测试，不管配置文件有没有dns项，结果都是和上面一样

**Comment by Kr328** [comment]
懂了懂了 是个 Bug

标题改 `[BUG] 规则匹配存在 DNS 解析行为时 双栈 Dial 失效 `

明天找个时间修修

**Comment by liuyunyue** [comment]
> 懂了懂了 是个 Bug
> 
> 标题改 `[BUG] 规则匹配存在 DNS 解析行为时 双栈 Dial 失效 ` 吧
> 
> 明天找个时间修修

打开视频网站首页时，在监控面板还是可以看到一些ipv6流量，之后播放视频页面就很明显大流量走的v4，这个有劳分析原因了。

建议还是ipv6优先，这样比较完美

**Comment by Kr328** [comment]
强制 IPv6 优先是不可能的

你所属的运营商 IPv6 建设比较好 而其他人的可能不行

双栈 Dial 取最优 就是为了得到一个普适性结果

**Comment by liuyunyue** [comment]
> 强制 IPv6 优先是不可能的
> 
> 你所属的运营商 IPv6 建设比较好 而其他人的可能不行
> 
> 双栈 Dial 取最优 就是为了得到一个普适性结果

国内ipv6环境基本和ipv4一样了，只是卡在出国带宽，而clash的使用环境，出国基本影响不大(国内直连，国外代理)。况且安卓系统都是默认ipv6优先，也没见有什么问题

**Comment by Kr328** [comment]
1. **你不能代表全部用户** 在我的测试环境 移动4G IPv6 延迟总是高于 IPv4
2. 按照 Chromium 的 双栈逻辑 IPv6 回滚到 IPv4 需要 300ms 确认 IPv6 可用 也就意味着 假设 IPv6 完全不可用 单个连接的 **最低延迟将会是 300ms**

**Comment by comwrg** [comment]
因为这个最快是 **DNS的查询的时间** 和 建立连接的时间 的和。
https://github.com/Dreamacro/clash/blob/b085addbb029c56c57d017d58db4ccea736db67a/component/dialer/dialer.go#L129-L133
你说的只是建立连接时间最快。

**Comment by Kr328** [comment]
> 因为这个最快是 **DNS的查询的时间** 和 建立连接的时间 的和。
> https://github.com/Dreamacro/clash/blob/b085addbb029c56c57d017d58db4ccea736db67a/component/dialer/dialer.go#L129-L133
> 
> 
> 你说的只是建立连接时间最快。

难道同一个 DNS 响应延迟还能有差异不成 ?

而且一旦规则中触碰到 IP/GEOIP 规则 DNS **必然存在缓存**

**Comment by Dreamacro** [comment]
close by #672
