### ISSUE TITLE
[Feature] Check HTTP status code when testing latency at proxy.URLTest(ctx, url)

### ISSUE THREAD

**Issue by accel-world** [Dreamacro/clash#670]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

有一些网站会针对 IP 地址进行访问量限制，它们会对被限流的 IP 地址的访问返回 4xx 或 5xx （比如 509 Bandwidth Limit Exceeded）的 HTTP 状态码。但当下 clash 中的 URLTest() 并不检查返回的 HTTP 状态码，就可能发生如下的情况：在一个 url-test Proxy-Group 中，有些代理已经被测试延迟 URL 对应的网站限制访问，但因为延迟较低而被选中。
### 可能的解决方案 Possible Solution

在配置文件中 Proxy Group url-test 内增加一个可选项，如果某个代理测试延迟返回的 HTTP 状态码被包含在这个选项内，那么认为这个代理连接超时/连接错误。
### 更多信息 More Information
我没有接触过 Golang，一时半会没法提出一个 pull request，但我大致看了下，添加这个功能应该不是很难，如果没有精力的话我可以试着修改看看，但可能要等比较长的时间。

**Comment by Dreamacro** [comment]
我认为不会有什么影响，这个测试就是为了通过代理去访问一个 url，并且能收到一个正常的返回（>= 400 也是一次正常的 HTTP 返回）。他所能检测出错误的范围只是包括「代理服务不能正常运作」。

**Comment by accel-world** [comment]
> 
> 
> 我认为不会有什么影响，这个测试就是为了通过代理去访问一个 url，并且能收到一个正常的返回（>= 400 也是一次正常的 HTTP 返回）。他所能检测出错误的范围只是包括「代理服务不能正常运作」。

我明白你的意思，如果仅仅检查代理是否能正常工作，确实不需要检查返回的状态码。因此，我这里提出的不是bug而是一个功能建议。

我的逻辑是这样的：使用者可以自定义测试连通性所用的URL，一个在我看来比较自然的延伸想法是，将这个URL修改为测试我对连通性感兴趣的几个特定网站。另一方面，目前是依靠HTTP HEAD而非TCP握手去测试连通性/延迟，那么我对于HTTP层面发生的访问性问题感兴趣也是合理的。

或者这么来看，对于我提到的这种情况：
>
>
>有一些网站会针对 IP 地址进行访问量限制，它们会对被限流的 IP 地址的访问返回 4xx 或 5xx （比如 509 Bandwidth Limit Exceeded）的 HTTP 状态码。可能发生如下的情况：在一个 url-test Proxy-Group 中，有些代理已经被测试延迟 URL 对应的网站限制访问，但因为延迟较低而被选中。

如果不修改clash，去实现代理对某个网站可访问性的检测与自动failover的话，固然是有办法的：为感兴趣的限流站点A设置一条规则对应于一个类别为Selector的Proxy Group X，这个Proxy Group X中包含了一些候选的代理。然后外部常驻运行一个程序，周期性地检测经由clash访问站点A是否被限流，如果被限流，那么控制clash的Proxy Group X选择其它的代理。但我感觉为了这个想法而额外运行一个外部程序有些麻烦。

**Comment by Dreamacro** [comment]
TCP 握手不足以判断一个代理是否「可用」，因为即使你填写的 password/psk 是错的，仍然可以正常的进行 tcp 连接。所以采用了一个十分通用的、基于 TCP 的协议 HTTP，一个 request + response 可以很好地检测正确性。至于是否返回 429 Too Many Requests 或者 509 Bandwidth Limit Exceeded，我觉得意义不大，因为是 HEAD 请求，所以返回 200 还是 429、509 的时间差别不应该很大

**Comment by NyaMisty** [comment]
我觉得问题在于，确实有这种需求：“有一些网站会针对 IP 地址进行访问量限制，它们会对被限流的 IP 地址的访问返回 4xx 或 5xx （比如 509 Bandwidth Limit Exceeded）的 HTTP 状态码。可能发生如下的情况：在一个 url-test Proxy-Group 中，有些代理已经被测试延迟 URL 对应的网站限制访问，但因为延迟较低而被选中。”

而且目前script没法控制url-test的行为，我认为可以至少添加一个参数来控制一下，允许开启时根据http status code选择

**Comment by zjplab** [comment]
我给一个案例，chatgpt的代理服务器，很多服务器因为访问次数过分被rate limited。访问某些元素例如`https://chat.openai.com/favicon.ico`会得到403 Forbidden. 这时候url-test latency排序出来最快的节点反而可能是废节点

@Dreamacro

**Comment by lizeyan** [comment]
其实大家的需求是这样的：
用户有一大堆机场节点，但是其中有很多被Google Scholar或者 OpenAI 屏蔽了，用户想要通过 url-test 选出真正能访问这些网站的节点，而不只是连接速度最快的那些节点。

**Comment by cxzlw** [comment]
> 我认为不会有什么影响，这个测试就是为了通过代理去访问一个 url，并且能收到一个正常的返回（>= 400 也是一次正常的 HTTP 返回）。他所能检测出错误的范围只是包括「代理服务不能正常运作」。

> [A url will be used for benchmarking the latency. Recommand http.](https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto#url)

既然 url-test 的 url 默认是 `http://www.gstatic.com/generate_204` 且 _Recommand http_，就可能遇到代理商劫持该请求的情况。例如某代理流量用完后的行为是返回 `400 Bad Request`。
