### ISSUE TITLE
[Feature] 会支持profiles文件夹吗，现在是不是还不能使用订阅模式？

### ISSUE THREAD

**Issue by JohnYuanhao** [Dreamacro/clash#674]
我现在直接把clash for windows 的配置文件夹拿过来使用，然后发现不支持自动覆盖配置文件，未来会支持吗，还是说我需要修改什么东西？

**Comment by Dreamacro** [comment]
不会支持 profile 之类的东西，代理规则的热替换都通过 provider 解决
