### ISSUE TITLE
[Feature]能不能通过规则把dns流量转到 clash 的内置 DNS

### ISSUE THREAD

**Issue by rongjch** [Dreamacro/clash#677]
做一个透明代理网关，需要把dns劫持到clash，
而v2ray 可以直接通过配置规则把dns流量转到内置 DNS上。

**Comment by Dreamacro** [comment]
TUN mode 有 hijack-dns 的配置，但是并没有发布

**Comment by BirkhoffLee** [comment]
https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/clash-tun-mode-1#dns-hijack

**Comment by Dreamacro** [comment]
已有 https://github.com/Dreamacro/clash/releases/tag/premium 能 hijack dns
