### ISSUE TITLE
[Feature]可以增加包名规则吗

### ISSUE THREAD

**Issue by Rasta0501** [Dreamacro/clash#678]
本人现在使用安卓clash for android，也用过surfboard，surfboard支持一个包名规则，PROCESS-NAME,com.android.vending,Proxy，这是它的一条规则写法，就是说这个应用的网络请求全部Proxy。我向cfa那边提出请求，作者反应应该向上游core请求。我也不会这方面的东西，如果能实现最好。谢谢

**Comment by Rasta0501** [comment]
对应win是进程规则，mellow有实现。我只是提一下，不能实现也没关系，非常感谢作者开发的core

**Comment by Dreamacro** [comment]
#171
