### ISSUE TITLE
http伪装直写可以通过，不直写却报错

### ISSUE THREAD

**Issue by canflyx** [Dreamacro/clash#679]
http伪装：- { name: "xxxxx", type: vmess,  server: 1.1.1.1,  port: 80,  uuid: uuid,  alterId: 32,  cipher: auto,  udp: true ,  network: http,  http-opts: { method: "GET", hearders: { Host: www.bing.com } } }
可以通过。
使用
- name: "xxx"
  type: vmess
  server: 1.1.1.1
  port: 80
  uuid: uuid
  alterId: 32
  cipher: auto
  udp: true
  network: http
  http-opts:
     method: "GET"
     path:
       - '/'
     headers:
       Host: www.bing.com
       Connection:
         - keep-alive
报错
Parse config error: Proxy 4: 'http-opts.headers[Host]' is not a slice"

**Comment by Dreamacro** [comment]
Host 是一个数组

**Comment by xianren78** [comment]
Host: ["www.bing.com"] 还有一个http-opts: {path: ["/path"]}也要这样写。
