### ISSUE TITLE
开启微软服务代理后，无法登陆office 365账号

### ISSUE THREAD

**Issue by mklsw** [Dreamacro/clash#680]
开启微软服务代理后，无法登陆office 365账号，选直接连接也无效，关闭系统代理后可以正常登录

https://docs.microsoft.com/en-us/office/troubleshoot/activation/issue-when-activate-office-from-office-365

**Comment by cololi** [comment]
Windows用户请使用 [Clash Windows](https://github.com/Fndroid/clash_for_windows_pkg/releases) 并在应用中使用EnableLoopback.exe所有代理即可解决office无法连接的问题可参考 [Clash使用期间无法使用Outlook和OneNote #123](https://github.com/Fndroid/clash_for_windows_pkg/issues/123)

**Comment by Dreamacro** [comment]
@cololi thx for replying
