### ISSUE TITLE
[Feature] fake-ip-filter wildcard 规则不支持全域匹配

### ISSUE THREAD

**Issue by cygmris** [Dreamacro/clash#689]
添加一条`*.*.cluster.local`的fake-ip-filter规则.
发现 `a.b.cluster.local `可以生效，但是`a.b.c.cluster.local`或`a.b.c.d.cluster.local` 并不生效。

必须添加`*.*.*.*.cluster.local`的规则才可以使`a.b.c.d.cluster.local` 生效，极其不便，这样设计的目的是什么？

[mention openclash的另一个issue](https://github.com/vernesong/OpenClash/issues/437)

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/issues/272#issuecomment-626185069
