### ISSUE TITLE
配置文件的自定义header写法

### ISSUE THREAD

**Issue by KianLLL** [Dreamacro/clash#69]
自定义header的配置文件写法应该怎么写

**Comment by alexwwang** [comment]
You may refer to [https://github.com/Dreamacro/clash/commit/1607d3253fbe2216f5e2614d5128863b4eea5b2e](https://github.com/Dreamacro/clash/commit/1607d3253fbe2216f5e2614d5128863b4eea5b2e) to read the newest `readme.md`.

Of course you should build it from scratch on your local side first.

**Comment by Dreamacro** [comment]
实现了后会推送到 dev 分支并关闭 issue，会等到一定程度的 commit 时 release 新版本。具体配置看 dev 分支。
