### ISSUE TITLE
^Cach@ach-Lenovo-V110-15IKB:~/clash$ sudo ./clash -d . WARN[0000] MMDB invalid, remove and download             ERRO[0227] Start HTTP server error: listen tcp 127.0.0.1:7890: bind: address already in use 

### ISSUE THREAD

**Issue by shiyanlou-015555** [Dreamacro/clash#690]
^Cach@ach-Lenovo-V110-15IKB:~/clash$ sudo ./clash -d .
WARN[0000] MMDB invalid, remove and download            
ERRO[0227] Start HTTP server error: listen tcp 127.0.0.1:7890: bind: address already in use

**Comment by shiyanlou-015555** [comment]
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890

**Comment by shiyanlou-015555** [comment]
ach@ach-Lenovo-V110-15IKB:~$ cd clash/
ach@ach-Lenovo-V110-15IKB:~/clash$ ./clash -d .
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890      

^Cach@ach-Lenovo-V110-15IKB:~/clash$ ^C
ach@ach-Lenovo-V110-15IKB:~/clash$

**Comment by szdongjun** [comment]
具体怎么操作?我也遇这问题了

**Comment by szdongjun** [comment]
麻烦教一下,急

**Comment by disini** [comment]
请问这个问题要怎么解决呢？感激不尽！
