### ISSUE TITLE
[Bug]透明代理可能出现死循环

### ISSUE THREAD

**Issue by rongjch** [Dreamacro/clash#691]
clash开透明代理给局域网，但是一段时间之后出现爆CPU的情况，查看log，撑满了这些内容

> time="2020-05-12T14:26:39+08:00" level=info msg="[TCP] 172.18.90.172:13170 --> 172.18.90.172 match IPCIDR using DIRECT"
> time="2020-05-12T14:26:39+08:00" level=info msg="[TCP] 172.18.90.172:13172 --> 172.18.90.172 match IPCIDR using DIRECT"
> time="2020-05-12T14:26:39+08:00" level=info msg="[TCP] 172.18.90.172:13174 --> 172.18.90.172 match IPCIDR using DIRECT"
> time="2020-05-12T14:26:39+08:00" level=info msg="[TCP] 172.18.90.172:13176 --> 172.18.90.172 match IPCIDR using DIRECT"

172.18.90.172是eth0的IP。
防火墙规则里面有
iptables -t nat -A CLASH -d 172.18.0.0/16 -j RETURN
按道理说应该不会有这个log吧？
config.yaml里面也有
- IP-CIDR,172.18.0.0/16,REJECT
和
cfw-bypass:
    - 172.28.*

想问一下大家有没有试过这个情况？怎样规避还需要加什么规则？
比较奇怪的是我3个服务器其中一台是一天两次出现这个的频率，其他两台好像比较少出现这个。

**Comment by rongjch** [comment]
我好像可以重现这个情况了。。
外网
telnet 服务器ip 7892
然后就会出现上述问题，这是一个bug吧？

**Comment by Dreamacro** [comment]
duplicated #425
