### ISSUE TITLE
[Bug]代理链无法实现规则分流？

### ISSUE THREAD

**Issue by flyingwhitewhale** [Dreamacro/clash#692]
感谢duament和dreamacro大佬带来的代理链功能！
刚才测试了下，发现添加的代理链组无法显示RULE模式下，只能在GLOBAL模式下显示，如图
<img width="334" alt="Annotation 2020-05-12 222728" src="https://user-images.githubusercontent.com/30478118/81707808-731bc000-94a3-11ea-95a5-da060d65864f.png">
<img width="683" alt="4" src="https://user-images.githubusercontent.com/30478118/81707857-78790a80-94a3-11ea-9197-6019b86b5d1e.png">
<img width="359" alt="1" src="https://user-images.githubusercontent.com/30478118/81707892-7dd65500-94a3-11ea-802f-67028b73d71e.png">
<img width="537" alt="2" src="https://user-images.githubusercontent.com/30478118/81707929-829b0900-94a3-11ea-852a-1bacfb7d9c09.png">
<img width="805" alt="5" src="https://user-images.githubusercontent.com/30478118/81708192-a5c5b880-94a3-11ea-8356-4823992b4e1f.png">

不知是我设置问题，还是其他情况，请大佬指点一二，谢谢

**Comment by Dreamacro** [comment]
@Fndroid

**Comment by Fndroid** [comment]
Relay不能操作，也没有当前选中节点的说法就不显示了，加到规则里自然就生效。

close吧

**Comment by flyingwhitewhale** [comment]
<img width="815" alt="Annotation 2020-05-13 001934" src="https://user-images.githubusercontent.com/30478118/81719290-75841700-94af-11ea-857f-2083da0fb016.png">
感谢F大的指点和D大的帮忙，按F大的思路，把这个代理链嵌套到其他策略组，即可被引用了。谢谢
