### ISSUE TITLE
[Feature] 希望支持URL-REGEX

### ISSUE THREAD

**Issue by coderloverXH** [Dreamacro/clash#693]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
目前，大部分机场都有禁止BT下载的审计规则:(torrent|\.torrent|peer_id=|info_hash|get_peers|find_node|BitTorrent|announce_peer|announce\.php\?passkey=|Joker)。
Clash的分流规则主要是基于域名分流，而域名分流规则很难解决BT下载的分流问题。很多时候下载BT电影资源时不知不觉就走了代理，从而触发审计规则。
如果引入了URL-REGEX，能够较好地解决BT下载的分流问题。举例：让下载BT资源时走的是直连，只需用以下规则：URL-REGEX, (.+.)?(torrent|announce.php?passkey=|tracker|BitTorrent|bt_key|ed2k|find_node|get_peers|info_hash|magnet:|peer_id=|xunlei)(..+)?, DIRECT

**Comment by CyberKoo** [comment]
你想多了，这个规则只是禁止你下载torrent文件和与tracker进行交互。当你和tracker握手完成之后开始下载文件的时候是不会触发这条规则的。

**Comment by coderloverXH** [comment]
@CyberKoo  大佬，对于目前版本的Clash，如果让下载BT资源时走的是直连，而不是代理，有什么好的方法吗？

**Comment by Ninzero** [comment]
> @CyberKoo 大佬，对于目前版本的 Clash，如果让下载 BT 资源时走的是直连，而不是代理，有什么好的方法吗？

似乎一个方法是设置只代理几个常用端口比如说 443, 80 一类的, 但这确实是治标不治本. 我也很想知道有没有什么排除掉某些代理的好办法.

**Comment by CyberKoo** [comment]
如果是部署在路由上，可以使用src-ip-cidr排除掉nas/下载机的ip地址。
如果你使用的是linux可以使用一个单独的用户启动bt软件 然后使用iptables/nftables的owner模块直接绕过这个用户的流量。
windows下暂时不知道怎么处理，因为clash core目前支持process-name的匹配方式。

**Comment by h0cheung** [comment]
@CyberKoo Linux 下 iptables 绕过后还是会有流量触发审计规则，客户端为 qbittorrent enhanced edition，具体原因未知。

**Comment by cjjdaq** [comment]
前提是要支持MitM才能玩更多的高级功能。

**Comment by leihao** [comment]
其实 DOMAIN-KEYWORD,torrent 堪用
机场的BT规则都是明文全文匹配,撞上去的一般都是remote dns.
如果tracker的host name不带torrent等关键词,而且启用了https,机场根本拦不住

**Comment by IceCodeNew** [comment]
这个问题现在应该能用 process-name 解决le 。
