### ISSUE TITLE
[Bug]Direct connection failure

### ISSUE THREAD

**Issue by chaosVoid** [Dreamacro/clash#694]
According to the rules of outbound mode selection, there is a domain name in Mainland China that cannot be accessed.
Journal Japanese style [warning] dial DIRECT error: dial tcp4 xxx: 443: i / o timeout
The IP address in the warning is the domain name IP that cannot be accessed.
Already configured in clash.yaml-DOMAIN-SUFFIX, domain name.com, DIRECT and reload.
clashX version 1.20.0, macOS10.15.4

**Comment by Dreamacro** [comment]
plz offer some logs

**Comment by chaosVoid** [comment]
2020/05/18 16:28:11:253  [warning] dial Final error: couldn't find ip
2020/05/18 16:28:11:265  [warning] dial Final error: couldn't find ip
2020/05/18 16:28:11:276  [warning] dial Final error: couldn't find ip
Contact once, the log produces 3 records

clashX version 1.20.0, macOS10.15.4
I have set final to direct
My software says "An SSL error has occurred and a secure connection to the server cannot be established."

**Comment by Dreamacro** [comment]
seems dns resolve failed

**Comment by chaosVoid** [comment]
> 似乎DNS解析失败

This is an intranet domain name, which is resolved through the intranet dns. When I cancel "set as system proxy" for clashX, I can access it normally, so the direct connection of clashX is not a direct connection in the true sense.

**Comment by BirkhoffLee** [comment]
@chaosVoid This is the Clash core issue tracker, you will need to ask the author of ClashX for it's specific implementation. I'll close this for now, but feel free to re-open or open a new issue if you have any other concerns towards Clash core.
