### ISSUE TITLE
[Feature] Reload Configure API

### ISSUE THREAD

**Issue by septs** [Dreamacro/clash#695]
Provide an API for uninterrupted service, Reload Configure
New request, use new loaded configure
Existing connection, keep to closed

\* *uninterrupted* is keep current connection.

my idea:
```bash
curl $SUBSCRIPTION_LINK > config.yaml
curl localhost:9090/reload -H "Authentication: $SECRET"
```

**Comment by Dreamacro** [comment]
https://clash.gitbook.io/doc/restful-api/config
