### ISSUE TITLE
老毛子插件路由器内开启clash后iOS设备速度变慢

### ISSUE THREAD

**Issue by everypath** [Dreamacro/clash#698]
路由器启动clash后，所有iOS设备网络都变慢尤其是国内视频服务，包括但不限于国内服务。但安卓和windows设备均不受任何影响
希望修复这个bug

**Comment by jianhaochen** [comment]
老毛子路由器的clash问题
换掉老毛子，改用旁路由方案，完美解决

**Comment by everypath** [comment]
小白发问：那WiFi是不是连在主路由上，旁路由就可以关掉无线信号了

**Comment by jianhaochen** [comment]
可以的。旁路由建议可以使用树莓派。网上很多资料（树莓派旁路由+clash）可以搜看看。
