### ISSUE TITLE
remote desktop（mstsc） through clash（如何让远程桌面也走clash代理）

### ISSUE THREAD

**Issue by xfdywy** [Dreamacro/clash#699]
请问clash支持代理远程桌面类似的流量吗？或者如何操作才可以让windows上的远程桌面连接的流量也通过clash的代理。目前来看默认应该是不走代理的。

**Comment by xxstop** [comment]
直接软件proxifier

**Comment by BirkhoffLee** [comment]
要想辦法全局代理，這不是 Clash core 的相關問題了
