### ISSUE TITLE
能否在Proxy Group中写 direct 规则

### ISSUE THREAD

**Issue by luanwulin** [Dreamacro/clash#70]
有些国内域名希望可以选择是代理还是直连

**Comment by Dreamacro** [comment]
在 Rule 里的话可以写
```yml
Rule:
- DOMAIN-KEYWORD,example.com,DIRECT
- GEOIP,CN,DIECT
```

 虽然推荐直接用规则选择直连，当然 Proxy Group 里也可以
```yml
Proxy Group:
- { name: group, type: select, proxies: [a, DIRECT] }
```

**Comment by luanwulin** [comment]
@Dreamacro 明白了，顺便问下，我想从 surge 的 conf 迁移过来，以后是否会支持REJECT-TINYGIF force-remote-dns  no-resolve这几个特性呢？

**Comment by Dreamacro** [comment]
目前的所有规则都是 `force-remote-dns`, 本地的 dns 解析只做匹配规则用，`REJECT-TINYGIF` 可以考虑一下
