### ISSUE TITLE
[Feature Discussion] Temporarily Override the config.yaml

### ISSUE THREAD

**Issue by lincolnguang** [Dreamacro/clash#700]
- [x] I have searched on the [issue tracker](……/) before creating the issue.

## Environment

* the OS that the Clash core is running on
Debian 10
* the OS running on the client
Debian 10
* network conditions/topology
One-armed router

## Background Description
Due to complex network environments, different network environments require different config, users have to hosted multiple configs with roughly the same content. Especially, the following typical scenarios:

- Temporarily use `redir-host` instead of `fake-ip` when using DNS tools like `dig` or `nslookup`

- Temporarily add/remove a `proxy`(or a `proxy-provider`/a `proxy` in `proxy-provider`) or a `rule`(or a `rule-provider`/a rule in `rule-provider`) to test a new proxy or temporarily use another rules.

- Temporarily resolve all requests and send result(IP) to server.

- Users share one profile among devices, some settings might need modifying for different scenarios.

## Possible Solution

Based on clash work ways, I think using command-lines(or API) with script should be a best way to temporarily override.

**Just an example:**

Users should define a override part in `script` like this:

```
script:
  code: |
    def main(ctx, metadata, configdata):

    def ChangeEnhancedMode(configdata["enhanced-mode"]):
      if configdata["enhanced-mode"] = "fake-ip":
        let (cofigdata["enhanced-mode"] = "redir-host")
        ctx.log('[Script] enhanced-mode changed to redir-host')
        return
```
Users can override by command-lines like:

```
clash -or ChangeEnhancedMode
```
**or anyone have a better idea?**

**Comment by BirkhoffLee** [comment]
Similar feature was discussed and merged: https://github.com/Dreamacro/clash/issues/531
