### ISSUE TITLE
是不是不支持JustMySocks的obfs=tls啊？

### ISSUE THREAD

**Issue by YFTX2015** [Dreamacro/clash#701]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by Dreamacro** [comment]
不知道什么是 JustMySocks

**Comment by Ninzero** [comment]
> 不知道什么是 JustMySocks

这是 Bandwagon 推出的机场.

@YFTX2015 你试过
```
plugin: obfs
plugin-opts:
  mode: tls 
```

吗?

**Comment by YFTX2015** [comment]
插件就是按那样写的，不过仍然出错。

**Comment by YFTX2015** [comment]
我是照那个示例配置文件写的，把相关参数换成搬瓦工机场的，然后保存成一个新的config.yaml文件，再重新命名，放在.config>clash里面的，不晓得是不是这种操作不正确？

**Comment by yiiha33** [comment]
可以试下 plugin: simple-obfs

**Comment by YFTX2015** [comment]
已解决

**Comment by vi-si** [comment]
> 已解决

请问怎样设置，我也是用JMS
