### ISSUE TITLE
[Bug]dashboard进不去啊

### ISSUE THREAD

**Issue by nesteiner** [Dreamacro/clash#703]
这是`./clash`运行的结果  
```bash
(base) ➜  clash ./clash     
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890      
``` 
到后台`http://clash.razord.top/`，输入端口，一直弹出这个"编辑外部控制设置"的框框 (没设密码，社了密码输入也是这样，一直弹出来）
![2020-05-19 09-36-34 的屏幕截图](https://user-images.githubusercontent.com/46296608/82275418-54428f80-99b5-11ea-841f-33823beaabe4.png)

**Comment by Dreamacro** [comment]
external-controller: 127.0.0.1:9090, 不是 http proxy port

**Comment by nesteiner** [comment]
我端口输入的就是9090，我现在不知道怎么回事，github上图片看不到了

**Comment by zpike** [comment]
同遇到这个问题 还没解决？？？

**Comment by ArrantMender47** [comment]
一样的问题。。。。

**Comment by nesteiner** [comment]
@Dreamacro 如果clash运行没有问题，在终端上会显示什么？
@zpike @ArrantMender47 你们运行clash后终端显示了什么？跟我的差不多吗？ 有没有显示Restful API的地址？

**Comment by luoxin971** [comment]
这个问题为什么被关闭了啊，这个问题我也存在，求解决办法 @nesteiner @ArrantMender47 @zpike 你们解决了吗

**Comment by Joevaen** [comment]
臣附议！

**Comment by Playfish** [comment]
刚入坑,就发现没办法用,白砸钱了....一样的问题

**Comment by Playfish** [comment]
./clash -d . -ext-ctl "127.0.0.1:9090" 运行这个命令,就不会跳出来了

**Comment by Playfish** [comment]
访问不了vimeo.com,怎么破

**Comment by Joevaen** [comment]
@zpike @Dreamacro @Playfish @nesteiner 
兄弟们，这前面都写了是bug了，换个别的软件用，这个v2rayL亲测可用的：
[https://github.com/jiangxufeng/v2rayL](url)

**Comment by zpike** [comment]
推荐qv2ray。

**Comment by Playfish** [comment]
> @zpike @Dreamacro @Playfish @nesteiner
> 兄弟们，这前面都写了是bug了，换个别的软件用，这个v2rayL亲测可用的：
> [https://github.com/jiangxufeng/v2rayL](url)

老哥,我安装完了,点订阅没反应,需要什么操作不,感谢

**Comment by Joevaen** [comment]
> > @zpike @Dreamacro @Playfish @nesteiner
> > 兄弟们，这前面都写了是bug了，换个别的软件用，这个v2rayL亲测可用的：
> > [https://github.com/jiangxufeng/v2rayL](url)
> 
> 老哥,我安装完了,点订阅没反应,需要什么操作不,感谢

你之前在win上怎么订阅就怎么订阅，另外，修改下网络设置里面的http端口和socks端口，网络设置和v2rayL里的一致
![image](https://user-images.githubusercontent.com/46133615/92418934-e2c56180-f19c-11ea-80f8-c8f024a0d71c.png)

**Comment by Playfish** [comment]
> > > @zpike @Dreamacro @Playfish @nesteiner
> > > 兄弟们，这前面都写了是bug了，换个别的软件用，这个v2rayL亲测可用的：
> > > [https://github.com/jiangxufeng/v2rayL](url)
> > 
> > 
> > 老哥,我安装完了,点订阅没反应,需要什么操作不,感谢
> 
> 你之前在win上怎么订阅就怎么订阅，另外，修改下网络设置里面的http端口和socks端口，网络设置和v2rayL里的一致
> ![image](https://user-images.githubusercontent.com/46133615/92418934-e2c56180-f19c-11ea-80f8-c8f024a0d71c.png)
> 把下面改的和上面一样
> ![image](https://user-images.githubusercontent.com/46133615/92418969-0e484c00-f19d-11ea-9e5b-f700e7d43f8b.png)

感谢老哥，这个可用

**Comment by leondgarse** [comment]
刚开始用，遇到了同样的问题，我这边的原因是 Edge 浏览器的问题，似乎是打不开本地资源。查看 Network 界面有报错 `net::ERR_CONNECTION_REFUSED`，总之就是没找到配置文件
![Selection_361](https://user-images.githubusercontent.com/5744524/119449562-60e68a00-bd65-11eb-93bc-186485502d93.png)
换其他浏览器 Chrome / Firefox 就好了，可能跟其他人的原因不一样。

**Comment by woodBoat** [comment]
@leondgarse  @nesteiner @zpike @ArrantMender47 
`./clash -d [.yaml文件所在的目录]`

**Comment by zzm88** [comment]
https://clash.razord.top/ 连不上我的外部panel，改成http协议就进去了，是config里面可以配置吗

**Comment by woodBoat** [comment]
> https://clash.razord.top/ 连不上我的外部panel，改成http://clash.razord.top/ 就进去了，是config里面可以配置吗

使用https协议的话需要自己配置，具体过程较麻烦，而且两者使用无任何差别，完全没必要

**Comment by melodyjerry** [comment]
检查了下，配置文件没有动过。启动clash，能访问YouTube，但是dashboard面板就是连不上
![image](https://user-images.githubusercontent.com/47730856/132288177-53e661c3-5e41-49c2-a219-93c913bb3688.png)

**Comment by melodyjerry** [comment]
![image](https://user-images.githubusercontent.com/47730856/132289481-5fe8a1a4-f5b3-469b-9464-8a7fff3da1a7.png)

**Comment by nivenm** [comment]
> 在我的电脑上使用 Firefox 浏览器可以，使用 Chrome 浏览器不可以。然后按 F12 查看network相关信息，发现是跨域问题，参考这个[链接](http://metronic.net.cn/metronic/show-60902.html)解决了问题。

正解

**Comment by bugkiller-damo** [comment]
亲测换firefox有效

**Comment by lambdaplus** [comment]
> 在我的电脑上使用 Firefox 浏览器可以，使用 Chrome 浏览器不可以。然后按 F12 查看network相关信息，发现是跨域问题，参考这个[链接](http://metronic.net.cn/metronic/show-60902.html)解决了问题。

已解决,Nice

**Comment by xdddxxmx** [comment]
> 在我的电脑上使用 Firefox 浏览器可以，使用 Chrome 浏览器不可以。然后按 F12 查看network相关信息，发现是跨域问题，参考这个[链接](http://metronic.net.cn/metronic/show-60902.html)解决了问题。

谢谢 已经解决。

**Comment by FuChencan** [comment]
用F12发现这个报错。“The request client is not a secure context and the resource is in more-private address space private"。参照https://blog.csdn.net/lrx03145616256/article/details/121097483，把http://clash.razord.top改成https://clash.razord.top就打开了

**Comment by tangyili** [comment]
直接把浏览器里的ip地址，copy到对话框里的127.0.0.1上就可以了。

<img width="614" alt="截屏2022-05-17 17 50 54" src="https://user-images.githubusercontent.com/60964665/168785564-2928a49b-3b88-41d5-917d-9880ff242e19.png">

**Comment by Maple1401** [comment]
改成 https 访问就可以了

**Comment by BaronChushao** [comment]
> 在我的电脑上使用 Firefox 浏览器可以，使用 Chrome 浏览器不可以。然后按 F12 查看network相关信息，发现是跨域问题，参考这个[链接](http://metronic.net.cn/metronic/show-60902.html)解决了问题。

这个链接失效了，能说一下解决方法吗？

**Comment by nivenm** [comment]
谷歌浏览器输入chrome://flags/#block-insecure-private-network-requests
“Block insecure private network requests”设置为“Disabled”；重启浏览器

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月26日 22:46
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Dreamacro/clash] [Bug]dashboard进不去啊 (#703)


在我的电脑上使用 Firefox 浏览器可以，使用 Chrome 浏览器不可以。然后按 F12 查看network相关信息，发现是跨域问题，参考这个链接<http://metronic.net.cn/metronic/show-60902.html>解决了问题。

这个链接失效了，能说一下解决方法吗？

―

**Comment by IGqZ** [comment]
配置网络的时候 忽略的主机加上127.0.0.1

**Comment by 57SSG** [comment]
> 用F12发现这个报错。“The request client is not a secure context and the resource is in more-private address space private"。参照[https://blog.csdn.net/lrx03145616256/article/details/121097483，把http://clash.razord.top改成https://clash.razord.top就打开了](https://blog.csdn.net/lrx03145616256/article/details/121097483%EF%BC%8C%E6%8A%8Ahttp://clash.razord.top%E6%94%B9%E6%88%90https://clash.razord.top%E5%B0%B1%E6%89%93%E5%BC%80%E4%BA%86)

正解

**Comment by imlyi1992** [comment]
搞不定，换软件了。玩个锤子。

**Comment by zao111222333** [comment]
使用yacd的dashboard或许可以避免这个问题
https://github.com/haishanh/yacd/tree/gh-pages

我是直接输ip地址可以访问http, 但是加了层nginx后遇到该问题, 换了yacd后可以了
<img width="1501" alt="image" src="https://github.com/Dreamacro/clash/assets/57790433/91b25b35-8a23-4745-9442-58dd8966b28d">

**Comment by lightsky9627** [comment]
已经提出的解决方案不能满足需求，因为这类网站而关闭本地浏览器的跨域策略是不合理的。换别的了。

**Comment by FineaX** [comment]
> 谷歌浏览器输入chrome://flags/#block-insecure-private-network-requests “Block insecure private network requests”设置为“Disabled”；重启浏览器

牛逼

**Comment by nGkp5E76** [comment]
> > 谷歌浏览器输入chrome://flags/#block-insecure-private-network-requests “Block insecure private network requests”设置为“Disabled”；重启浏览器
> 
> 牛逼

直接加https 就行，上面给的 这个链接说的很清楚
[The request client is not a secure context and the resource is in more-private address space private_lrx03145616256的博客-CSDN博客]( https://blog.csdn.net/lrx03145616256/article/details/121097483 )
