### ISSUE TITLE
[Feature] 增加可以选择默认策略及策略内默认服务器的选项

### ISSUE THREAD

**Issue by nasbdh9** [Dreamacro/clash#705]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
 OpenWrt
* 使用者的操作系统 (the OS running on the client)
 Windows，Ubuntu

### 说明 Description
目前clash重启后策略选择和服务器选择会丢失然后按照每个条目第一项来运行
希望增加可以选择默认策略及策略内默认服务器的选项（或者说是标记？

**Comment by Dreamacro** [comment]
那么这第一个不就是所谓的「默认服务器」？

**Comment by keenwon** [comment]
小建议
最好的方式还是可以存个 session 之类的
下次启动自动连接上次关闭时已连接的

**Comment by nasbdh9** [comment]
> 那么这第一个不就是所谓的「默认服务器」？

服务器多的话每次都去排就有点麻烦，况且有些人直接用订阅的根本不会管配置的
