### ISSUE TITLE
期待支持naiveproxy

### ISSUE THREAD

**Issue by U201413497** [Dreamacro/clash#706]
clash目前几乎全平台都有客户端。

能否支持naiveproxy协议的代理，naiveproxy是和trojan类似，并且也是强大的。

官方github地址:https://github.com/klzgrad/naiveproxy

但只有win和linux还有openwrt的客户端。

如果clash能支持naiveproxy，将打通全平台。感谢，期待。

**Comment by maskedeken** [comment]
支持naiveproxy的协议不难，但是naiveproxy的优势不在协议而在它的chrome指纹，这是Go模仿不了的

**Comment by Dreamacro** [comment]
@maskedeken 其实也是有的 https://github.com/refraction-networking/utls，属于可以但没必要

**Comment by proletarius101** [comment]
No, it's necessary: https://github.com/v2ray/discussion/issues/704

**Comment by Dreamacro** [comment]
@proletarius101 I don't think go tls fingerprint is a problem that needs to be solved. The go client is very common in real-world. So keep the go default tls config is enough. Won't use https://github.com/refraction-networking/utls unless it's really necessary.

**Comment by proletarius101** [comment]
Yes, I mean clash is not affected

**Comment by darhwa** [comment]
naiveproxy如果不开padding的话，就是个标准的h2 tunnel。

我半个月前已经向v2ray那边提了实现该功能的PR v2ray/v2ray-core#2488， 开了issue v2ray/v2ray-core#2491，都没什么反应。真有这需求就去那边起哄一下呗。

应用我这个补丁之后，就可以在http outbound里直接设置h2代理，成为一个低配版naiveproxy。说它是低配因为还没有实现padding功能，而且golang的指纹毕竟比chrome要显眼。

padding实现起来应该也不难，后续如果真的很多人用上了，再考虑添加。

**Comment by proletarius101** [comment]
> naiveproxy如果不开padding的话，就是个标准的h2 tunnel客户端。

Naiveproxy is all about pretending to be Chrome. It doesn't make any sense if you only need a http proxy.

**Comment by darhwa** [comment]
> It doesn't make any sense if you only need a http proxy.

Not exactly. These golang tools (clash/v2ray) have no h2 handling in their http outbound. If you try to connect a h2-powered proxy server (i.e., caddy forwardproxy) using the current http outbound, what will happen? The client alpn has "h2", then negotiated protocol is h2, then client still treat it as h1, then server fails the connection. So it is even more a bug fix than a feature extension.

> Naiveproxy is all about pretending to be Chrome.

What Naiveproxy adds to a vanilla h2 tunnel are packet length obfuscation (WIP) and "HTTP Fast Open". I don't think Chrome fingerprint is another killer feature. If Chrome fingerprint has the collateral freedom, so does golang default fingerprint. But h2 tunnel itself already has a big advantage over h1 tunnel, the native multiplexing. Moreover, a h1 tunnel adds 1(TCP handshake) + 1(TLS 1.3 handshake) + 1(CONNECT request and 200 response) = 3 extra RTTs to each connection, while a h2 tunnel adds amortized 1 (only the CONNECT and 200).

**Comment by Dreamacro** [comment]
@darhwa 

I'm not sure if you know the difference between the two "http2 proxy" means:
1. The browser sends an HTTP2 request to the server.
in this case, HTTP CONNECT proxy can handle HTTP2 traffic in browser

2. An HTTP2 proxy which can handle the **difference host** proxy request.
in this case, use the feature of HTTP2 mux to handle **difference host** traffic. it can reduce TCP handshake but I can't find an RFC for this.

**Comment by darhwa** [comment]
@Dreamacro 

I always meant your case 2 (proxy by h2), not case 1 (proxy for h2).

> I can't find an RFC for this

[RFC7540#8.3](https://tools.ietf.org/html/rfc7540#section-8.3) covers the CONNECT method. If a proxy server supports h2 in alpn, it translates an inbound h2 stream to an outbound TCP connection. Nothing stops multiplexing, since tunnels are in independent h2 streams. Forward proxy supporting h2 frontend is not rare now. Such as haproxy, nghttpx, caddy forwardproxy, to name a few.

**Comment by Dreamacro** [comment]
@darhwa can you provide a caddy config file for http2 CONNECT proxy?

**Comment by darhwa** [comment]
First you need to install caddy with forwardproxy plugin:

```sh
curl https://getcaddy.com | bash -s personal http.forwardproxy
```

Config detail can be found at https://github.com/caddyserver/forwardproxy

**Comment by Liangnan1981** [comment]
什么时候可以支持naiveproxy啊？

**Comment by shaojs321** [comment]
> 什么时候可以支持naiveproxy啊？

+1

**Comment by bzdk** [comment]
+1

**Comment by LOpSSH** [comment]
强大体现在哪里...用起来有什么不一样的地方吗

**Comment by bzdk** [comment]
> 强大体现在哪里...用起来有什么不一样的地方吗

主要的优点可能就是基于Chrome指纹对抗GFW的审查在实际应用下的表现不错，对部分人来说这是一个现成可用的方案。但客户端生态还不够理想，Clash的支持会给这给这个方案的使用者带来实际的帮助。

**Comment by gustav183** [comment]
直到现在依然没支持naiveproxy，看来用这个协议的还是太少了

**Comment by segfault-bilibili** [comment]
我搞了个配置，虽然其实没多大X用，因为不能做到拖入配置即可用，必须额外跑一个naive客户端。

https://gist.github.com/segfault-bilibili/5fcf39911a892d5e3d3fc41994e15d34

（另外naive不是说直接把chrome的网络栈搬过来了么，整个网络栈实现都是chrome的来着）

**Comment by avtsavts2021** [comment]
插眼

**Comment by sf467** [comment]
插眼
