### ISSUE TITLE
[Feature]内置DNS Server同时监听TCP端口，支持TCP模式， 

### ISSUE THREAD

**Issue by trott90** [Dreamacro/clash#707]
我现在用iptables直接劫持8.8.8.8的DNS请求到Clash的DNS端口，不过我发现有的到8.8.8.8的DNS请求TCP的，因为Clash的DNS不支持TCP模式，所以只能转发到redir的端口，这个是可以工作，但由于本身这个DNS请求没有经过Clash，clash就不会知道这个IP的对于的域名是哪个，域名的规则实际上就不会起作用了

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/issues/677#issuecomment-630623819
