### ISSUE TITLE
[Feature]支持修改 request and response

### ISSUE THREAD

**Issue by silentcloud** [Dreamacro/clash#709]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

目前代理功能很赞，希望能留出接口或者其他方式能力支持修改 request 和 response；

**Comment by Dreamacro** [comment]
no plan for MitM #266

**Comment by silentcloud** [comment]
@Dreamacro go 应该有现成的的这方面的库，比如 https://github.com/google/martian（看到这个，不晓得是否合适），不能辛苦花时间集成一下？

**Comment by Dreamacro** [comment]
大多数问题都不在技术上 @silentcloud

**Comment by fr0der1c** [comment]
@Dreamacro 不在技术上那问题在哪呢？因为从 iOS 换到 Android 的缘故，我从 surge 换到了 clash，感觉可玩性降低了很多

**Comment by Jkkoi** [comment]
> @Dreamacro 不在技术上那问题在哪呢？因为从 iOS 换到 Android 的缘故，我从 surge 换到了 clash，感觉可玩性降低了很多

法律问题（

**Comment by Jkkoi** [comment]
> @Dreamacro 不在技术上那问题在哪呢？因为从 iOS 换到 Android 的缘故，我从 surge 换到了 clash，感觉可玩性降低了很多

法律问题、滥用问题

**Comment by ddkwork** [comment]
设置了证书握手不成功
