### ISSUE TITLE
自定义规则部分去掉减号

### ISSUE THREAD

**Issue by Allentong61** [Dreamacro/clash#71]
自定义规则的部分，开头有个横线。我知道这是yaml的语法规则，但是从ss/surge等应用导入规则就会太麻烦了，多了甚至只能用脚本处理。能否也支持没有横线开头的配置文件，直接粘贴过来就能用了，对通用性来说很有必要。

**Comment by Dreamacro** [comment]
不能，要遵守 yaml 的语法格式。不能让非标准格式 (指 surge 的自定义配置格式) 影响正常的标准配置格式。
