### ISSUE TITLE
[Bug] WSL上无法开启socks5代理

### ISSUE THREAD

**Issue by Limgmk** [Dreamacro/clash#713]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在

### clash core config

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: 127.0.0.1
```

### Clash log

```
INFO[0000] RESTful API listening at: 127.0.0.1:9090
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890
INFO[0000] SOCKS proxy listening at: 127.0.0.1:7891
ERRO[0000] Start SOCKS5 server error: invalid argument
```

### 环境 Environment
WSL

### 说明 Description
在wsl上运行 clash core , socks5 无法代理，报错如上。wsl的Ubuntu和Arch两个发行版均会出现该问题。我试过直接使用wsl构建dev分支，但情况还是这样。另外回退到0.19，在配置文件完全相同的情况下却并不会出现该问题。仅仅只有 socks5 不能用，http 是正常的。

**Comment by Limgmk** [comment]
版本是 WSL 1

**Comment by Mosney** [comment]
大概是WSL的特殊性，印象中之前用另外的程序bind端口也是报错，不过没深究

**Comment by Ninzero** [comment]
看起来像这个问题 [WSL Issue](https://github.com/microsoft/WSL/issues/1498)

**Comment by Dreamacro** [comment]
close because of #748
