### ISSUE TITLE
可否提供关于 Clash 配置文件的说明。

### ISSUE THREAD

**Issue by FX9590** [Dreamacro/clash#714]
类似[www.v2ray.com](url)这样的，主页上的文档[https://clash.gitbook.io/doc/](url)除了API啥都没有。
Clash for Windows 倒是有个[https://docs.cfw.lbyczf.com/](url)，但太粗略了。
在 Issues 中搜索，只有 YAML 的格式。 #583 
Google 中搜索，只有比较简单的解释。
实在是找不着了，麻烦给一个。

**Comment by Dreamacro** [comment]
搜索 (click to expand) 然后点击它

**Comment by Mosney** [comment]
通读示例配置文件即可

**Comment by BirkhoffLee** [comment]
https://lancellc.gitbook.io/clash/

**Comment by FX9590** [comment]
太感谢了诸位了，一直没注意到在哪。

**Comment by tea1111980** [comment]
> 太感谢了诸位了，一直没注意到在哪。

起先我也没注意，后来看到有一个 溅头  就点进去了，后来发现藏在里面呢。哈哈~！！
