### ISSUE TITLE
[Bug] Clash 配置中密码为0开头纯数字组成的字符串解析出错

### ISSUE THREAD

**Issue by llc1123** [Dreamacro/clash#716]
**描述出现的错误**
Clash 配置中的代理服务器密码为0开头的纯数字时（并且不是8进制数），无法正常解析该字段

**如何复现该错误**
复现步骤:
1. 配置中使用0开头的纯数字密码，并且该字段两端无引号（例：password: 0123456789）
2. 载入至Clash

**预期行为**
正常载入配置文件

**错误产生原因推测**
在yaml规范中，0开头的数字为8进制数，如出现不符合8进制的数字，则看作字符串。故 `password: 0123456789` 两端的引号可省略，而在客户端解析时，也应当作字符串处理。此处 Clash 错误地将其解析为数字类型，故产生错误。

**Comment by llc1123** [comment]
似乎是 yaml 解析库的问题
https://github.com/go-yaml/yaml/issues/157

**Comment by llc1123** [comment]
确认是 yaml 解析库的问题
https://github.com/go-yaml/yaml/issues/157

**Comment by Dreamacro** [comment]
这东西我也没法解决，只能自己用引号包起来了，clash 会时常更新上游，所以 yaml 库解决了，这边也会更新的
