### ISSUE TITLE
[Bug] TUN 無法處理 IP 直連

### ISSUE THREAD

**Issue by yanyumihuang** [Dreamacro/clash#719]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ 是] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题 
- [是 ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题 是
- [ 否] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在 是
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```tun的fakeip模式
……port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: debug
external-controller: :9010
secret: "qwerty"
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - '127.0.0.1:23'
experimental:
  interface-name: eth0
tun:
  enable: true  
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……树莓派
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……透明代理
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. 以tun的fake模式运行clash
2. 
3. ……

**我预期会发生……？**

能够代理局域网中的设备的流量
**实际上发生了什麽？**

实际上只处理了域名请求，ip的直连请求不进tun，比如tg
### 更多信息 More Information
我在使用了[https://beyondkmp.com/post/kone_clash/](url)
设定了一些路由规则
```for (( ; ; ))
do
    sleep 3
    ip address | grep 198.18.0.1
    a=$?
    if [ ${a} -eq 0 ];then
        break;
    fi
done

ip rule del from 192.168.2.3/32 table 100
ip rule del from 192.168.2.4/30 table 101
ip rule del from 192.168.2.8/29 table 102
ip rule del from 192.168.2.16/28 table 103
ip rule del from 192.168.2.32/27 table 104
ip rule del from 192.168.2.64/26 table 105
ip rule del from 192.168.2.128/25 table 106


ip rule add from 192.168.2.3/32 table 100
ip rule add from 192.168.2.4/30 table 101
ip rule add from 192.168.2.8/29 table 102
ip rule add from 192.168.2.16/28 table 103
ip rule add from 192.168.2.32/27 table 104
ip rule add from 192.168.2.64/26 table 105
ip rule add from 192.168.2.128/25 table 106

ip route add default via 198.18.0.1 dev utun table 100
ip route add default via 198.18.0.1 dev utun table 101
ip route add default via 198.18.0.1 dev utun table 102
ip route add default via 198.18.0.1 dev utun table 103
ip route add default via 198.18.0.1 dev utun table 104
ip route add default via 198.18.0.1 dev utun table 105
ip route add default via 198.18.0.1 dev utun table 106
 
可以也可以i代理ip类的请求，但王者荣耀的延迟检测出现了几百的ping，如果不执行连接中的路由规则，王者荣耀正常，但ip类请求失败

**Comment by yanyumihuang** [comment]
手动指定tg的代理可以正常进行代理

**Comment by yanliang721** [comment]
王者荣耀的延迟检测出现了几百的ping+1
已经快有一个月用clash没法打王者了。。。

**Comment by beyondkmp** [comment]
把qq.com的域名都过滤掉不就行了。
```
 fake-ip-filter: # fake ip white domain list
```
