### ISSUE TITLE
我司的网站需要VPN拨入才能访问，使用Clash后网站可以打开，邮箱无法连接imap和smtp

### ISSUE THREAD

**Issue by tony1016** [Dreamacro/clash#72]
操作系统：macOS
我司的网站需要VPN拨入才能访问，使用Clash后网站可以打开，邮箱无法连接imap和smtp
查看日志发现网页访问有日志信息，但是Apple Mail访问就没有日志信息

**Comment by beyondkmp** [comment]
apple mail会自动走系统代理吗？

**Comment by tony1016** [comment]
> apple mail会自动走系统代理吗？

是的，因为我同时配置了Gmail账号，开启代理后Gmail收发正常

**Comment by beyondkmp** [comment]
> > apple mail会自动走系统代理吗？
> 
> 是的，因为我同时配置了Gmail账号，开启代理后Gmail收发正常

连接上vpn后，gmail就不行？

**Comment by tony1016** [comment]
> @tony1016 是什么类型的 VPN？

SSL VPN

**Comment by beyondkmp** [comment]
> > @tony1016 是什么类型的 VPN？
> 
> SSL VPN

深信服的？还是anyconnect ?

**Comment by tony1016** [comment]
找到问题了，不知道为什么，我的配置文件是
```
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：info，级别越高日志输出量越大，越倾向于调试)
# 四个级别：info / warning / error / debug
log-level: info

# clash 的 RESTful API
external-controller: 127.0.0.1:9090
```

但实际上勾选设置系统代理后，Socks5代理的端口竟然设置的是0
<img width="590" alt="2018-12-19 2 49 16" src="https://user-images.githubusercontent.com/2218314/50203669-442c1800-039d-11e9-87bb-cc704499b34c.png">
<img width="329" alt="2018-12-19 2 49 35" src="https://user-images.githubusercontent.com/2218314/50203687-5312ca80-039d-11e9-9676-a551cbfdfebe.png">

手动改为7891后一切正常

**Comment by Dreamacro** [comment]
@tony1016 应该是 7891 这个端口被占用了，正常情况下应该不是这个状态，是不是修改过配置文件并热加载文件过，以及 clashx 的版本是多少

**Comment by tony1016** [comment]
> @tony1016 应该是 7891 这个端口被占用了，正常情况下应该不是这个状态，是不是修改过配置文件并热加载文件过，以及 clashx 的版本是多少

不知道是个什么情况造成的，没法重现，所以先关闭了

**Comment by NianguoWang** [comment]
> 找到问题了，不知道为什么，我的配置文件是
> 
> ```
> # HTTP 代理端口
> port: 7890
> 
> # SOCKS5 代理端口
> socks-port: 7891
> 
> # Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
> # redir-port: 7892
> 
> # 允许局域网的连接（可用来共享代理）
> allow-lan: false
> 
> # 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
> mode: Rule
> 
> # 设置日志输出级别 (默认级别：info，级别越高日志输出量越大，越倾向于调试)
> # 四个级别：info / warning / error / debug
> log-level: info
> 
> # clash 的 RESTful API
> external-controller: 127.0.0.1:9090
> ```
> 
> 但实际上勾选设置系统代理后，Socks5代理的端口竟然设置的是0
> <img alt="2018-12-19 2 49 16" width="590" src="https://user-images.githubusercontent.com/2218314/50203669-442c1800-039d-11e9-87bb-cc704499b34c.png">
> <img alt="2018-12-19 2 49 35" width="329" src="https://user-images.githubusercontent.com/2218314/50203687-5312ca80-039d-11e9-9676-a551cbfdfebe.png">
> 
> 手动改为7891后一切正常

我也存在跟你类似的情况，我司用的vpn是TunnelBlick，网站可以访问，但是git访问不了，我把ClashX的【设为系统代理】关掉，甚至退出也不管用，至今还没解决。

**Comment by fanjindong** [comment]
> > 找到问题了，不知道为什么，我的配置文件是
> > ```
> > # HTTP 代理端口
> > port: 7890
> > 
> > # SOCKS5 代理端口
> > socks-port: 7891
> > 
> > # Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
> > # redir-port: 7892
> > 
> > # 允许局域网的连接（可用来共享代理）
> > allow-lan: false
> > 
> > # 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
> > mode: Rule
> > 
> > # 设置日志输出级别 (默认级别：info，级别越高日志输出量越大，越倾向于调试)
> > # 四个级别：info / warning / error / debug
> > log-level: info
> > 
> > # clash 的 RESTful API
> > external-controller: 127.0.0.1:9090
> > ```
> > 
> > 
> > 但实际上勾选设置系统代理后，Socks5代理的端口竟然设置的是0
> > <img alt="2018-12-19 2 49 16" width="590" src="https://user-images.githubusercontent.com/2218314/50203669-442c1800-039d-11e9-87bb-cc704499b34c.png">
> > <img alt="2018-12-19 2 49 35" width="329" src="https://user-images.githubusercontent.com/2218314/50203687-5312ca80-039d-11e9-9676-a551cbfdfebe.png">
> > 手动改为7891后一切正常
> 
> 我也存在跟你类似的情况，我司用的vpn是TunnelBlick，网站可以访问，但是git访问不了，我把ClashX的【设为系统代理】关掉，甚至退出也不管用，至今还没解决。

+  1  我也是

**Comment by zhangyanan0525** [comment]
> > > 找到问题了，不知道为什么，我的配置文件是
> > > ```
> > > # HTTP 代理端口
> > > port: 7890
> > > 
> > > # SOCKS5 代理端口
> > > socks-port: 7891
> > > 
> > > # Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
> > > # redir-port: 7892
> > > 
> > > # 允许局域网的连接（可用来共享代理）
> > > allow-lan: false
> > > 
> > > # 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
> > > mode: Rule
> > > 
> > > # 设置日志输出级别 (默认级别：info，级别越高日志输出量越大，越倾向于调试)
> > > # 四个级别：info / warning / error / debug
> > > log-level: info
> > > 
> > > # clash 的 RESTful API
> > > external-controller: 127.0.0.1:9090
> > > ```
> > > 
> > > 
> > > 但实际上勾选设置系统代理后，Socks5代理的端口竟然设置的是0
> > > <img alt="2018-12-19 2 49 16" width="590" src="https://user-images.githubusercontent.com/2218314/50203669-442c1800-039d-11e9-87bb-cc704499b34c.png">
> > > <img alt="2018-12-19 2 49 35" width="329" src="https://user-images.githubusercontent.com/2218314/50203687-5312ca80-039d-11e9-9676-a551cbfdfebe.png">
> > > 手动改为7891后一切正常
> > 
> > 
> > 我也存在跟你类似的情况，我司用的vpn是TunnelBlick，网站可以访问，但是git访问不了，我把ClashX的【设为系统代理】关掉，甚至退出也不管用，至今还没解决。
> 
> * 1  我也是

+++++++1我也是。跟你情况一样样的。我现在感觉白买了。根本没法用。

**Comment by Dreamacro** [comment]
@zhangyanan0525 在哪花钱了？

**Comment by zhangyanan0525** [comment]
> @zhangyanan0525 在哪花钱了？

sorry.我刚说的有歧义。我删除了
