### ISSUE TITLE
[Bug] 订阅配置不兼容旧写法

### ISSUE THREAD

**Issue by atnewalex** [Dreamacro/clash#720]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [Y] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [Y] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```测试与本地配置无关
……
```

### Clash log

```
C:\Users\Administrator\Desktop\CLASH_Win32>clash -d ./cfg
time="2020-05-28T00:05:02+08:00" level=info msg="Start initial provider provider1"
time="2020-05-28T00:05:10+08:00" level=fatal msg="Parse config error: File must have a `proxies` field"
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……win32, win64
* 使用者的操作系统 (the OS running on the client)
……win10 64bit
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
本地配置文件兼容 Proxy ， proxies 两种写法；
远程订阅配置写 Proxy 会提示出错 level=fatal msg="Parse config error: File must have a `proxies` field
下载远程配置到本地仍然是  level=fatal msg="Parse config error: File must have a `proxies` 
修改下载的配置中 Proxy 为 proxies ，问题解决

我知道这不是问题，是机场没有跟进Clash
可能是作者忘记了

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by Dreamacro** [comment]
你的 provider 有问题吧，自己检查一下

**Comment by atnewalex** [comment]
在本地测试，当  2.yaml 写为 Proxy 则 level=fatal msg="Parse config error: File must have a `proxies` field"

当  2.yaml 写为 proxies 则正常，不知问题出在哪里？

我的 config.yaml 
----------------------------------------------------------------
socks-port: 7891
allow-lan: true
mode: Global
log-level: debug
external-controller: 0.0.0.0:9090
external-ui: dashboard
secret: ""

Proxy:
  - name: Ss4
    type: ss
    server: abc
    port: abc
    cipher: aes-256-gcm
    password: abc
    obfs: tls
    obfs-host: www.who.int

Proxy Group:
  - name: "Just My Socks"
    type: select
    proxies:
      - Ss4

  - name: "Final"
    type: select
    proxies:
      - "Just My Socks"

  - name: UseProvider
    type: select
    use:
      - test
    proxies:
      - Proxy
      - DIRECT

proxy-providers:
  test:
    type: file
    path: /2.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - MATCH,Final
--------------------------------------------------------------------------

我的  2.yaml
-----------------------------------------------------------------------------
socks-port: 7891
allow-lan: true
mode: Global
log-level: debug

external-controller: 0.0.0.0:9090
external-ui: dashboard
secret: ""

###################  出错  #################
Proxy:
##   命令行窗口日志： level=fatal msg="Parse config error: File must have a `proxies` field"
##########################################


###################  一切OK  #################
#proxies:
###########################################
  - name: Ss4
    type: ss
    server: 123.net
    port: 123
    cipher: aes-256-gcm
    password: 123
    obfs: tls
    obfs-host: www.who.int

Proxy Group:
  - name: "Final"
    type: select
    proxies:
      - "Ss4"

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - MATCH,Final

**Comment by atnewalex** [comment]
在本地测试如下：
请看下方 2.yaml

我的config.yaml
---------------------------------------
socks-port: 7891
allow-lan: true
mode: Global

log-level: debug

external-controller: 0.0.0.0:9090
external-ui: dashboard
secret: ""

Proxy:
  - name: Ss4
    type: ss
    server: abc
    port: abc
    cipher: aes-256-gcm
    password: qSZV
    obfs: tls
    obfs-host: www.who.int

Proxy Group:
  - name: "Final"
    type: select
    proxies:
      - Ss4

  - name: UseProvider
    type: select
    use:
      - test
    proxies:

proxy-providers:
  test:
    type: file
    path: /2.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT
  - MATCH,Final
-------------------------------------------------

我的 2.yaml
--------------------------------------------------
socks-port: 7891
allow-lan: true
mode: Global
# Rule / Global / Direct (default is Rule)

log-level: debug
# info / warning / error / debug / silent

external-controller: 0.0.0.0:9090
external-ui: dashboard
secret: ""

###################  出错  #################
Proxy:
##   命令行窗口日志： level=fatal msg="Parse config error: File must have a `proxies` field"
##########################################


###################  OK  #################
#proxies:
##########################################
  - name: Ss4
    type: ss
    server: abc
    port: abc
    cipher: aes-256-gcm
    password: qSZV
    obfs: tls
    obfs-host: www.who.int

Proxy Group:
  - name: "Final"
    type: select
    proxies:
      - "Ss4"

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT
  - MATCH,Final

**Comment by Dreamacro** [comment]
provider 路径看起来不太对

**Comment by atnewalex** [comment]
我是使用 -d 当前目录运行
clash -d ./cfg

目录结构：
run.bat---------内容----  clash.exe -d ./cfg
clash.exe
CFG-----此目录存放config.yaml, 2.yaml

**Comment by Dreamacro** [comment]
`./2.yaml` 和 `/2.yaml` 有本质差异

**Comment by atnewalex** [comment]
./2.yaml 和 /2.yaml 都是同样的报错
我将 2.yaml 上传至 开了http服务的192.168.50.120

config.yaml配置使用如下，依旧报错，将192.168.50.120/2.yaml   中 Proxy 改为 proxies ，则正常
proxy-providers:
  provider1:
    type: http
    url: "http://192.168.50.120/2.yaml"
    interval: 3600
    path: ./hk.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

**Comment by Dreamacro** [comment]
2.yaml 里就应该是 proxies 而不是 Proxy

**Comment by nauxliu** [comment]
我也遇到了相同的问题，机场提供的订阅配置里字段名是 `Proxy` 而不是 `proxies`，用来做 Proxy provider 就会报错

```
Parse config error: File must have a `proxies` field
```

看了下 [代码里](https://github.com/Dreamacro/clash/blob/646bd4eeb4bbea6628987be55a167c45e718f77a/adapters/provider/provider.go#L123) 确实没兼容字段名为 `Proxy` 的情况。

我刚接触 Clash，对以前的配置不太熟，`Proxy` 字段命名应该是老版本格式而 `proxies` 是新的格式吧？

**Comment by Dreamacro** [comment]
@nauxliu provider 是一个新的东西，不存在什么兼不兼容的问题，打一开始字段名就是 `proxies`
