### ISSUE TITLE
关于 V2Ray 中使用 TLS 的严重安全漏洞

### ISSUE THREAD

**Issue by Ninzero** [Dreamacro/clash#726]
你好, 由于这一问题似乎不能算作是一个 Bug, 因此没有使用预设的 Issue Template, 还请见谅.

在这一个 [Issue](https://github.com/v2ray/v2ray-core/issues/2509) 中, V2Ray 的默认 TLS 设置会导致极严重的安全问题, 使得 Client Hello 易于被识别. 目前的解决方案是开启客户端的 AllowInsecureCipher 选项. 我注意到 Clash 的配置中似乎并无这一选项, 且 Clash 是自行实现的 Vmess 协议, 我想请问一下在 Clash 中会存在这一异常的 Client Hello 吗? 如果会的话, 目前存在解决方案吗?

谢谢.

**Comment by Dreamacro** [comment]
clash 用的是默认的 tls 选项，并没有自定义 cipher，至于 go 的 tls 指纹，所有的 go 程序都会是一样的，目前不打算使用 uTLS 之类的库。

**Comment by tefiszx** [comment]
现在已经不是tls指纹的漏洞了，Vmess协议自身存在更高危的先天性缺陷。v2ray一夜崩塌。

**Comment by FANminiworld** [comment]
新的 issue  [https://github.com/v2ray/v2ray-core/issues/2523](url)  ，建议看一下
