### ISSUE TITLE
[Question] Is clash related to the latest v2ray issue (TLS Cipher Suite)

### ISSUE THREAD

**Issue by beacon1096** [Dreamacro/clash#727]
https://github.com/v2ray/v2ray-core/issues/2518
https://github.com/v2ray/discussion/issues/704

It's a recent issue which came up just about 12 hours ago, and I'm wondering does clash client send the specific cipher suite field in TLS client hello which leaks the server's info, making the server fail to disguise itself as a normal web server

**Comment by Ninzero** [comment]
I think it is a duplicate to https://github.com/Dreamacro/clash/issues/726

**Comment by beacon1096** [comment]
> 
> 
> I think it is a duplicate to #726

Just saw the answer in https://github.com/Dreamacro/clash/issues/726
closing this issue
thanks
