### ISSUE TITLE
希望能在进行DOH查询的时候支持http/2[Feature]

### ISSUE THREAD

**Issue by AssICan** [Dreamacro/clash#728]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
windows10
* 使用者的操作系统 (the OS running on the client)
windows10
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description
我在自己服务器上使用nginx搭建了一个doh server，然后在clash的配置文件中用doh的方式进行DNS查询。我在server端的日志里看到，clash是使用http1.1进行查询的，而firefox可以使用http2的方式进行查询。
这是clash查询的记录：
```
[01/Jun/2020:12:00:26 +0800] "POST /dns-query?bla=foo:443 HTTP/1.1" 200 109 "-" "Go-http-client/1.1
```
这是firefox查询的记录：
```
[01/Jun/2020:10:44:16 +0800] "POST /dns-query HTTP/2.0" 200 113 "-" "-"
```
大佬能否考虑在进行doh查询的时候支持http2呢？

**Comment by Dreamacro** [comment]
用最新的 dev 分支试试？

**Comment by AssICan** [comment]
感谢

**Comment by Dreamacro** [comment]
@AssICan 是可以了还是什么
