### ISSUE TITLE
[Feature]能否提供一个类似SwitchyOmega的通配符设置

### ISSUE THREAD

**Issue by jzdayz** [Dreamacro/clash#729]
![image](https://user-images.githubusercontent.com/35563513/83379793-f8452580-a40e-11ea-87cf-9532a3084c7d.png)
类似这种，公司的局域网都是10.1.1.1 之类的，一个个配太麻烦了。

**Comment by Dreamacro** [comment]
https://zh.wikipedia.org/wiki/%E6%97%A0%E7%B1%BB%E5%88%AB%E5%9F%9F%E9%97%B4%E8%B7%AF%E7%94%B1#CIDR%E5%92%8C%E6%8E%A9%E7%A0%81
