### ISSUE TITLE
[Feature]希望添加使用规则的时候，统计流经proxy的流量功能。

### ISSUE THREAD

**Issue by ch-boogeyman** [Dreamacro/clash#731]
这样方便看走了多少机场的流量。
![流量2](https://user-images.githubusercontent.com/46711557/83625477-87486e00-a5c6-11ea-8d62-ebc647b0b4b0.png)

**Comment by Liac-li** [comment]
于Ubuntu端在配置成功后 直接关闭了terminal后 再次打开便显示
Failed to start Redir UDP Listener: operation not permitted 

效果为：在设置中使用手动的网络代理下，只能开未被墙的，而打开Google的话
它使用了Proxy规则，但是
有
DEBU：[DNS] ocsp.pki.goog —> 203.208.43.79
FATA can’t load mmdb: error opening database: invalid MaxmiNd DB file 


请问是怎么回事

**Comment by waldens** [comment]
相关issue: 
#53 
https://github.com/Fndroid/clash_for_windows_pkg/issues/32

同期待这个功能，具体实现方式可以商榷，但总方向是希望知道，使用了多少代理的流量。因为很多代理节点是收费、有限流量的，会在乎使用了多少。

**Comment by pscj** [comment]
也需要此功能

**Comment by xinstein** [comment]
也需要此功能
