### ISSUE TITLE
[Bug]clash连接中转过的v2ray+ws+tls的节点和多ssl证书的问题

### ISSUE THREAD

**Issue by ztywyj** [Dreamacro/clash#734]
用clash连接国内nat中转的v2ray+ws+tls的节点出现了如下问题：
目标服务器上我装了宝塔，如果服务器中只有一个网站并申请了ssl证书的话，没有问题，延迟测试和连接都正常，经nat中转过后也能正常连接；但如果我给服务器里的另一个网站也申请了ssl证书，直接连接也没问题，但是经过中转后就无法连接了，其他使用v2ray-core的客户端没有这个问题，用clash core的客户端就有，下面是我clash配置文件里的节点写法
- name: " nat中转节点"
  type: vmess
  server: nat的公网入口ip
  port: 20000
  uuid: xxxxxx
  alterId: 32
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /xxxx/
  Host: 网站域名

**Comment by Restry** [comment]
@ztywyj  请问有解决办法吗？？
