### ISSUE TITLE
[Bug] HTTP代理无法使用完全限定域名（特指包含尾部点）

### ISSUE THREAD

**Issue by codehz** [Dreamacro/clash#737]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [x] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config
```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: Global
# 代理为shadowsocks，确认可用
```

### Clash log

```
time="2020-06-10T19:37:30+08:00" level=info msg="[TCP] 127.0.0.1:64096 --> qq.com. using GLOBAL"
time="2020-06-10T19:44:17+08:00" level=info msg="[TCP] 127.0.0.1:64552 --> www.youtube.com. using GLOBAL"
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Windows 10 (10.0.19619.1000)
* 使用者的操作系统 (the OS running on the client)
Same as above
* 网路环境或拓扑 (network conditions/topology)
(None)
* iptables，如果适用 (if applicable)
None
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无关
* 其他
暂无

### 说明 Description

使用http代理时，一旦使用了完全限定域名，就没有办法解析到目标地址了
RFC2616没有约束Request-URI不能为完全限定域名，因此使用包含尾部点的域名是允许的

### 重现问题的具体布骤 Steps to Reproduce

0. 运行clash
1. `http_proxy=http://127.0.0.1:7890 curl http://www.qq.com. -vv` (wsl)
2. (Alternative) 浏览器输入www.qq.com.

（https效果相同，但是不方便演示）

**我预期会发生……？**
```
* Uses proxy env variable http_proxy == 'http://127.0.0.1:7890'
*   Trying 127.0.0.1:7890...
* Connected to 127.0.0.1 (127.0.0.1) port 7890 (#0)
> GET http://www.qq.com./ HTTP/1.1
> Host: www.qq.com.
> User-Agent: curl/7.70.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Moved Temporarily
< Server: stgw/1.3.12.4_1.13.5
< Content-Type: text/html
< Content-Length: 169
< Location: https://www.qq.com/
< Date: Wed, 10 Jun 2020 11:54:18 GMT
< Connection: keep-alive
<
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>stgw/1.3.12.4_1.13.5</center>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

**实际上发生了什麽？**
```
* Uses proxy env variable http_proxy == 'http://127.0.0.1:7890'
*   Trying 127.0.0.1:7890...
* Connected to 127.0.0.1 (127.0.0.1) port 7890 (#0)
> GET http://www.qq.com./ HTTP/1.1
> Host: www.qq.com.
> User-Agent: curl/7.70.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

### 可能的解决方案 Possible Solution

正确实现完全限定域名解析逻辑。。。

### 更多信息 More Information
[Wiki: Fully_qualified_domain_name](https://en.wikipedia.org/wiki/Fully_qualified_domain_name)

**Comment by Dreamacro** [comment]
Fixed in f1b792bd2689b45767cdb5e0984925adfe63a679 , thanks for the report.
