### ISSUE TITLE
Mixin with TAP interface[Bug]

### ISSUE THREAD

**Issue by m4niacjp** [Dreamacro/clash#739]
When using MIXIN i add the following to the config file:

cfw-profile-mixin: 
dns:
   enable: true
   enhanced-mode: redir-host 
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
experimental:
   interface-name: Wi-Fi 

But when i load the my subscription is not taking this setting and TAP interface is not in use. If i open the subscription and manually insert the same as above it works as intended via TAP interface.

**Comment by Dreamacro** [comment]
no Mixin on clash, plz ask cfw
