### ISSUE TITLE
请问CFW规则和策略的优先级是不是比chrome插件switchyomega规则高？

### ISSUE THREAD

**Issue by Asrielwiki** [Dreamacro/clash#746]
在CFW开正常RULE模式，chrome插件switchyomega开全局模式下，百度到的ip地址仍然是本地地址。

switchyomega全局模式端口填写的是CFW的socks5端口。

一些国内的网站（如百度网盘），受地理位置和zf管控的影响，分享链接在不通过代理的情况下是打不开的。请问只能自己在CFW里面再写一条代理规则么？

有没有什么办法可以实现降低优先级之类的？

非常感谢！！

**Comment by Dreamacro** [comment]
SwitchyOmega 和系统代理是有冲突的（功能重合），要么关掉系统代理并将模式调成 Global，要么不用 SwitchyOmega。
