### ISSUE TITLE
[Bug] FATA[0000] Parse config error: unsupport behavior: classical

### ISSUE THREAD

**Issue by wd** [Dreamacro/clash#747]
请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
rule-providers:
  "gfwlist":
    type: file
    behavior: classical
    path: ./rules/gfwlist.yaml
```

### Clash log

```
INFO[0000] Start initial compatible provider proxy
FATA[0000] Parse config error: unsupport behavior: classical
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Linux tux 4.1.27 #2 SMP PREEMPT Wed Jul 31 14:51:32 EDT 2019 aarch64 ASUSWRT-Merlin

* 使用者的操作系统 (the OS running on the client)
路由器

* 网路环境或拓扑 (network conditions/topology)
路由器上面

* iptables，如果适用 (if applicable)
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
* 其他

### 重现问题的具体布骤 Steps to Reproduce

使用我上面贴的配置，然后执行 `./clash -d .` 会提示这个错误。

**我预期会发生……？**

按照文档描述的，https://lancellc.gitbook.io/clash/clash-config-file/rule-provider#behavior ，应该是支持 classical 的。

**实际上发生了什麽？**

提示不支持 classical

### 可能的解决方案 Possible Solution
不知道是不是 release 的版本还不支持，我昨天使用 docker 版本应该是支持的。

### 更多信息 More Information
我下载的这个版本 https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-armv8-2020.05.08.gz
```
./clash -v
Clash 2020.05.08 linux arm64 2020年 5月 8日 星期五 13时20分53秒 UTC
```
此外，还有一个问题，premium 和非 premium 的区别是什么？我找了一会也没有找到具体说明。目前我看着是有些文档里面写的功能好像在非 premium 里面不支持。premium 是付费版本吗？

**Comment by Dreamacro** [comment]
对的 release 版本会比较旧，软件更新都有一个周期。只有 clash pro 和 docker 版本是实时更新的。和普通版本的差别 https://github.com/Dreamacro/clash/releases/tag/premium 这里都有写。

premium 不收费，只是闭源的普通版本的超集，闭源的原因之一是开源的环境不友好。这个做法算是一种取舍之后的产物，会把一些比较 geek 的东西放到上面，目前比普通版大了 1/3 左右。觉得闭源有问题可以使用开源版本。

**Comment by Dreamacro** [comment]
下个 release 会跟着 1.0 发布

**Comment by wd** [comment]
那 1.0 大概计划什么时候发布呢？路由器上面没法用 docker 版本，就只有等发布了再用了。。

issue 我先关闭了。
