### ISSUE TITLE
Reconnect when switching proxy

### ISSUE THREAD

**Issue by Cowkine4** [Dreamacro/clash#749]
Closing old connections through an external interface was wrong. Both yacd and clash-dashboard were completely doing it the wrong way.
What surge has done is, when the underlying proxy has changed, the kernel itself should re-establish all connections on the old proxy server to the new one for us, instead of waiting for the client application to fail and then initiate a new connection. That would be way too late.

Same issue tracked here https://github.com/haishanh/yacd/issues/495

**Comment by Synchronized1** [comment]
I also think that closing old conns should be done by the kernel instead of GUI.

**Comment by Dreamacro** [comment]
It works well as my design. There are two common scenes:
1. I have visited Netflix on the HK node, but I want to check out the JP area. I ticked the option and select JP node.

2. I'm watching Youtube and I want to play Animal Crossing together. so I don't tick the option and select Game node.

BTW, TCP is stateful. so it is not possible to "continue" using the connection after disconnection, including Surge of course. So all we can do is expect the client will automatically retry after disconnecting

**Comment by Cowkine4** [comment]
Oh, i see. You're supposing users are going to frequently switch proxy manually through dashboard. 

As clash has a proxy policy called `url-test`, when the underlying proxy was switching to a faster proxy server, if the kernel did not kill old ones immediately, there would be one application connected to multiple servers at once, which may cause lots of problems.

I agree that TCP is stateful, so at least clash should kill the connections inside kernel for us, right?

**Comment by Cowkine4** [comment]
Plus, there are a few aspects could've been improved in `url-test` mode. The most important issue is that we don't always have to select the fastest one. We could determine a tolerance value for a proxy group, say, according to their variance. Switching proxy server frequently is not a good thing

**Comment by Dreamacro** [comment]
@Cowkine4 
1. `tolerance` is implemented on dev.
2. the url-test would reselect the `fast` node when dial error now

**Comment by Cowkine4** [comment]
@Dreamacro Much appreciated for you reply and this impressive project.

**Comment by Cowkine4** [comment]
> tolerance is implemented on dev.

I saw that patch. Besides a hand-tuned `tolerance` for flexibility, an auto value would also be great.

**Comment by Cowkine4** [comment]
> I have visited Netflix on the HK node, but I want to check out the JP area. I ticked the option and select the JP node. The browser would keep-alive TCP connections, so we can use the correct node.
> I'm watching Youtube and I want to play Animal Crossing together. so I don't tick the option and select Game node.

For these cases, I suggest put them into different proxy group. One for game console hosts, one for streaming, one for general websites, so that switch proxy inside one proxy group does not interfere with other proxies

**Comment by Dreamacro** [comment]
@Cowkine4  It just a simple case on my daily life. The real life is much more complicated. About 80% of the time I don't need to tick this checkbox. Only browser keep alive old connection and I want to switch to another area, I have to tick it.

IMO, I don't recommend use this checkbox. If clash handle all traffic in your family, everyone doesn't want their use to be interrupted (clash provides a precise closing of the connection API).

**Comment by Cowkine4** [comment]
> Only browser keep alive old connection and I want to switch to another area, I have to tick it.

As I mentioned, apple services was mostly affected in my cases. Take non-mobile devices for example, such as homepod, apple tv, oftentime they are having couple of persistent connections to the apple gateway servers for authentication, i suppose. And if the proxy server was changed automatically, later requests sent through the new proxy server will fail since authentication was still connecting through old proxies. This will definitely make these the homepod and appletv die for a loooooong time. And if proxies was changing frequently, these devices will be basically dysfunctional!

**Comment by Cowkine4** [comment]
For your concerns, maybe we could add a 'auto-kill' like option for proxy group?

**Comment by Dreamacro** [comment]
I'm afraid it's hard to implemented. connection and proxy/proxy-group are completely decoupled (only as a callee). 

BTW, all apple services use DIRECT for me

**Comment by Cowkine4** [comment]
using icloud in domestic network is way slower than going thru the overseas server, in terms of both response time and bandwidth.

You might as well compare syncing a single photo shot to icloud. In domestic network, that might take 30s to few minutes to start the upload regardless of the upload speed, these waiting time is much longer than uploading a 4k video clips to the icloud using proxies.

And for AppleTV+, domestic network sucks.

**Comment by Cowkine4** [comment]
> connection and proxy/proxy-group are completely decoupled (only as a callee).

Then you may need a third component to do this. Like what we've done in the web dashboard.

**Comment by Cowkine4** [comment]
Any update?
