### ISSUE TITLE
[Feature] Daemonising the clash app on Linux

### ISSUE THREAD

**Issue by ktechmidas** [Dreamacro/clash#754]
Just a small suggestion for the README, I'm willing to make a PR if needed and should I add the service file too? You can daemonise the app quite easily with systemd on any newer Linux distro... copy clash executable into /usr/local/bin then make a file called clash.service in /etc/systemd/system/

```
[Unit]
Description=Clash Daemon

[Service]
ExecStart=/usr/local/bin/clash -d /etc/clash/

[Install]
WantedBy=multi-user.target
```

Then just move your config.yml and Country.mmdb to /etc/clash/

Run systemctl enable clash and reboot. Clash will now come up automatically :)

Run systemctl status clash or journalctl -xe to get any logs/status

**Comment by Dreamacro** [comment]
maybe Wiki is the best choice

**Comment by BirkhoffLee** [comment]
Side note: I feel like we should start working on the official wiki documentation since Clash is now considered fairly stable.

**Comment by BirkhoffLee** [comment]
This is now included at https://github.com/Dreamacro/clash/wiki/Clash-as-a-daemon.

**Comment by septs** [comment]
suggest, systemd configuration file section use `ini` language hint it.

```ini
[Unit]
Description=Clash Daemon

[Service]
ExecStart=/usr/local/bin/clash -d /etc/clash/

[Install]
WantedBy=multi-user.target
```

**Comment by septs** [comment]
CC @Dreamacro

**Comment by Dreamacro** [comment]
@septs done

**Comment by v2sh1t** [comment]
not work on wsl
