### ISSUE TITLE
[Bug] Gvisor panic leads to ClashX Pro crash after config reloaded or wait for some time long enough

### ISSUE THREAD

**Issue by alexwwang** [Dreamacro/clash#755]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ *] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ *] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ *] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ *] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
port: 1234
socks-port: 5678
allow-lan: false
mode: Rule
log-level: info
```

### Clash log

```
panic: send on closed channel

goroutine 600 [running]:
gvisor.dev/gvisor/pkg/tcpip/link/channel.(*queue).Write(0xc0003ca340, 0xc000585ad0, 0x800, 0x0, 0xc0003a2084, 0x4, 0x0, 0x0, 0xc0003a2088, 0x4, ...)
	gvisor.dev/gvisor@v0.0.0/pkg/tcpip/link/channel/channel.go:85 +0x6d
gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).WritePacket(0xc0003ca0c0, 0xc0008a6b60, 0x0, 0x800, 0x0, 0x0, 0xc00000e960, 0x1, 0x1, 0x1, ...)
	gvisor.dev/gvisor@v0.0.0/pkg/tcpip/link/channel/channel.go:244 +0x1f2
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).WritePacket(0xc00054c120, 0xc0008a6b60, 0x0, 0x4000000011, 0x0, 0x0, 0xc00000e960, 0x1, 0x1, 0x1, ...)
	gvisor.dev/gvisor@v0.0.0/pkg/tcpip/network/ipv4/ipv4.go:301 +0x4ac
gvisor.dev/gvisor/pkg/tcpip/stack.(*Route).WritePacket(0xc0008a6b60, 0x0, 0x4000000011, 0x0, 0x0, 0xc00000e960, 0x1, 0x1, 0x1, 0xc000548a00, ...)
	gvisor.dev/gvisor@v0.0.0/pkg/tcpip/stack/route.go:161 +0xd1
github.com/Dreamacro/clash/proxy/stack/gvisor.writeUDP(0xc0008a6b60, 0xc00000e960, 0x1, 0x1, 0x1, 0xc0d20a1c4a, 0x10643672b, 0x1, 0xc000637ec8)
	github.com/Dreamacro/clash@v0.0.0/proxy/stack/gvisor/gvisor.go:291 +0x3e5
github.com/Dreamacro/clash/proxy/stack/gvisor.(*Gvisor).WriteTo(0xc00028e240, 0xc0006b0000, 0x1, 0x8000, 0x1068a8be0, 0xc0000dc600, 0x1068a8be0, 0xc000511f80, 0x1, 0x0, ...)
	github.com/Dreamacro/clash@v0.0.0/proxy/stack/gvisor/gvisor.go:201 +0x142
github.com/Dreamacro/clash/proxy/tun.(*packet).WriteBack(0xc00079afc0, 0xc0006b0000, 0x1, 0x8000, 0x1068a8be0, 0xc000511f80, 0xc000511f80, 0x0, 0x0)
	github.com/Dreamacro/clash@v0.0.0/proxy/tun/adapter.go:267 +0x84
github.com/Dreamacro/clash/tunnel.handleUDPToLocal(0x1068b0b20, 0xc00079afc0, 0x112dd5f00, 0xc000430520, 0xc00051a640, 0x10, 0x0, 0x0)
	github.com/Dreamacro/clash@v0.0.0/tunnel/connection.go:123 +0x21a
created by github.com/Dreamacro/clash/tunnel.handleUDPConn.func1
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:303 +0x5c3
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
ClashX Pro 1.20.4.3
* 使用者的操作系统 (the OS running on the client)
MacOS 10.15.4
* 网路环境或拓扑 (network conditions/topology)
NAT
* iptables，如果适用 (if applicable)
NA
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
NA
* 其他
NA

### 重现问题的具体布骤 Steps to Reproduce

1. Start ClashX Pro(cxp for short below)
2. Make sure `Enhance Mode Config` -> `Stack Mode` -> `Gvisor` is selected
3. Edit the `config.yaml` cxp loaded from `~/.config/clash/` online to make cxp sense the modification
4. Click the notification to let cxp update configuration
5. After updating succeeded, open Dashboard and then close the window by `x` upleft, which makes Gvisor panic and cxp crash, or just wait sometime for the crash happen.

**我预期会发生……？**

Nothing should happen

**实际上发生了什麽？**

cxp crashed.

### 可能的解决方案 Possible Solution

By switching `Stack Mode` to `System`, no more crash by far.

### 更多信息 More Information
Without changing configuration, there's also probility > 0 that cxp crash after the system come back from standby mode.

**Comment by Dreamacro** [comment]
maybe it fixed in last clashx pro release
