### ISSUE TITLE
Golang Process manager

### ISSUE THREAD

**Issue by mhf-ir** [Dreamacro/clash#757]
> Unfortunately, there is no native or elegant way to implement daemons on Golang. We recommend using third-party daemon management tools like PM2, Supervisor or the like to keep Clash running as a service.

https://github.com/immortal/immortal

**Comment by Dreamacro** [comment]
It looks good. But IMO, this kind of software is more suited to a third-party daemon to do this. Perhaps It's a mistake on README.md, I'll change it later.

**Comment by Dreamacro** [comment]
add a wiki https://github.com/Dreamacro/clash/wiki/Clash-as-a-daemon, and fixed readme
