### ISSUE TITLE
[Bug]redirt-host下hosts不生效，因为router.asus.com就进不去路由了

### ISSUE THREAD

**Issue by ccssyybb** [Dreamacro/clash#759]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ 是] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [是 ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ 是] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config

```
……
```
hosts:
router.asus.com: 192.168.2.1
### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

打开路由管理页面
**实际上发生了什麽？**

打不开
### 更多信息 More Information
查了是有存在这个问题。还是发一下看看大佬会不会重新开放这个hosts支持

**Comment by Dreamacro** [comment]
❌
```yaml
hosts:
router.asus.com: 192.168.2.1
```

⭕️
```yaml
hosts:
    router.asus.com: 192.168.2.1
```

**Comment by ccssyybb** [comment]
> ```yaml
> hosts:
> router.asus.com: 192.168.2.1
> ```
> 
> 
> 
> ```yaml
> hosts:
>     router.asus.com: 192.168.2.1
> ```

yaml是这样子写的，示例写错了。就是redir-host模式下不生效。看大大有准备开放支持没。

**Comment by Dreamacro** [comment]
是支持的，只是 resolve 不到，没法到 tunnel 里反映射，你可能需要加一个能解析 router.asus.com 的 dns
