### ISSUE TITLE
[Feature] Document 1.0 config changes

### ISSUE THREAD

**Issue by yatli** [Dreamacro/clash#764]
After upgrading to 1.0 the rules are no longer read from the old config, everything goes DIRECT.
The release notes mention "it has break changes" but it could be better if the config changes are pointed out.
Had to read config.go to get some ideas...

- Rule -> rules
- Proxy Groups -> proxy-groups
- Proxy ->proxies

**Comment by BirkhoffLee** [comment]
Sorted out in https://github.com/Dreamacro/clash/releases/tag/v1.0.0. Thanks.
