### ISSUE TITLE
[Bug]更新了最新1.0.0，RULE-SET提示不支持

### ISSUE THREAD

**Issue by ccssyybb** [Dreamacro/clash#769]
感谢你向 Clash Core 提交 issue！
在提交之前，请确认：

- [ 1] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [1 ] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 Openclash、Koolclash 等）的特定问题
- [ ] 我已经使用 Clash core 的 dev 分支版本测试过，问题依旧存在
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clash core config
jcadmin123@AX88U:/tmp/home/root# clash -v
Clash v1.0.0 linux arm Sat Jun 27 13:04:48 UTC 2020

proxies:
  - {name: "\U0001F1ED\U0001F1F0 香港1", server: , port: 3001, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港2", server: , port: 3002, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港3", server: , port: 3003, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港4", server: , port: 3004, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港5", server: , port: 3005, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港6", server: , port: 3006, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港7", server: , port: 3007, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港8", server: , port: 3008, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港9", server: , port: 3009, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港10", server: , port: 3010, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港11", server: , port: 3011, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港12", server: , port: 3012, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港13", server: , port: 3013, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港14", server: , port: 3014, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1ED\U0001F1F0 香港15", server: , port: 3015, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本1", server: , port: 4001, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本2", server: , port: 4002, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本3", server: , port: 4003, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本4", server: , port: 4004, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本5", server: , port: 4005, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本6", server: , port: 4006, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本7", server: , port: 4007, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本8", server: , port: 4008, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本9", server: , port: 4009, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EF\U0001F1F5 日本10", server: , port: 4010, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1F8\U0001F1EC 新加坡1", server: , port: 5001, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1F8\U0001F1EC 新加坡2", server: , port: 5002, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1F8\U0001F1EC 新加坡3", server: , port: 5003, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1F8\U0001F1EC 新加坡4", server: , port: 5004, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1F8\U0001F1EC 新加坡5", server: , port: 5005, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1FA\U0001F1F2 美国1", server: , port: 5041, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1FA\U0001F1F2 美国2", server: , port: 5042, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1FA\U0001F1F2 美国3", server: , port: 5043, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1FA\U0001F1F2 美国4", server: , port: 5044, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1FA\U0001F1F2 美国5", server: , port: 5045, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1FA\U0001F1F2 美国6", server: , port: 5046, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1E8\U0001F1F3 台湾1", server: , port: 5501, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1E8\U0001F1F3 台湾2", server: , port: 5502, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1F0\U0001F1F7 韩国", server: , port: 5603, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EE\U0001F1F3 印度", server: , port: 5605, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1E9\U0001F1EA 德国", server: , port: 5604, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1EC\U0001F1E7 英国", server: , port: 5601, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1F7\U0001F1FA 俄罗斯", server: , port: 5602, type: vmess, uuid: , alterId: 2, cipher: auto, tls: false}
  - {name: "\U0001F1FA\U0001F1F2 美国7-小带宽直连「0.2x」", server: , port: 443, type: vmess, uuid: , alterId: 2, cipher: auto, tls: true}
proxy-groups:
  - name: "节点选择"
    type: select
    proxies:
      - DIRECT
      - "\U0001F1ED\U0001F1F0 香港1"
      - "\U0001F1ED\U0001F1F0 香港2"
      - "\U0001F1ED\U0001F1F0 香港3"
      - "\U0001F1ED\U0001F1F0 香港4"
      - "\U0001F1ED\U0001F1F0 香港5"
      - "\U0001F1ED\U0001F1F0 香港6"
      - "\U0001F1ED\U0001F1F0 香港7"
      - "\U0001F1ED\U0001F1F0 香港8"
      - "\U0001F1ED\U0001F1F0 香港9"
      - "\U0001F1ED\U0001F1F0 香港10"
      - "\U0001F1ED\U0001F1F0 香港11"
      - "\U0001F1ED\U0001F1F0 香港12"
      - "\U0001F1ED\U0001F1F0 香港13"
      - "\U0001F1ED\U0001F1F0 香港14"
      - "\U0001F1ED\U0001F1F0 香港15"
      - "\U0001F1EF\U0001F1F5 日本1"
      - "\U0001F1EF\U0001F1F5 日本2"
      - "\U0001F1EF\U0001F1F5 日本3"
      - "\U0001F1EF\U0001F1F5 日本4"
      - "\U0001F1EF\U0001F1F5 日本5"
      - "\U0001F1EF\U0001F1F5 日本6"
      - "\U0001F1EF\U0001F1F5 日本7"
      - "\U0001F1EF\U0001F1F5 日本8"
      - "\U0001F1EF\U0001F1F5 日本9"
      - "\U0001F1EF\U0001F1F5 日本10"
      - "\U0001F1F8\U0001F1EC 新加坡1"
      - "\U0001F1F8\U0001F1EC 新加坡2"
      - "\U0001F1F8\U0001F1EC 新加坡3"
      - "\U0001F1F8\U0001F1EC 新加坡4"
      - "\U0001F1F8\U0001F1EC 新加坡5"
      - "\U0001F1FA\U0001F1F2 美国1"
      - "\U0001F1FA\U0001F1F2 美国2"
      - "\U0001F1FA\U0001F1F2 美国3"
      - "\U0001F1FA\U0001F1F2 美国4"
      - "\U0001F1FA\U0001F1F2 美国5"
      - "\U0001F1FA\U0001F1F2 美国6"
      - "\U0001F1E8\U0001F1F3 台湾1"
      - "\U0001F1E8\U0001F1F3 台湾2"
      - "\U0001F1F0\U0001F1F7 韩国"
      - "\U0001F1EE\U0001F1F3 印度"
      - "\U0001F1E9\U0001F1EA 德国"
      - "\U0001F1EC\U0001F1E7 英国"
      - "\U0001F1F7\U0001F1FA 俄罗斯"
      - "\U0001F1FA\U0001F1F2 美国7-小带宽直连「0.2x」"
rule-providers:
  ad-block:
    type: http
    behavior: classical
    path: ./online.d/ad.rule.yaml
    url: 'https://kuyagic.keybase.pub/clash-rule/ad.yaml'
    interval: 600
  lan:
    type: http
    behavior: classical
    path: ./online.d/lan.rule.yaml
    url: 'https://kuyagic.keybase.pub/clash-rule/lan.yaml'
    interval: 600
  china:
    type: http
    behavior: classical
    path: ./online.d/china.rule.yaml
    url: 'https://kuyagic.keybase.pub/clash-rule/china.yaml'
    interval: 600
  proxy:
    type: http
    behavior: classical
    path: ./online.d/proxy.rule.yaml
    url: 'https://kuyagic.keybase.pub/clash-rule/proxy.yaml'
    interval: 600
        
rules:
  - RULE-SET,ad-block,REJECT
  - RULE-SET,china,DRIECT
  - RULE-SET,lan,DRIECT
  - RULE-SET,proxy,节点选择
  
  # 最终规则
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT

port: 3333
socks-port: 23456
redir-port: 23457
allow-lan: true
mode: Rule
log-level: error
external-controller: 192.168.2.1:9990
experimental:
  ignore-resolve-fail: true
hosts:
  router.asus.com: 192.168.2.1
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:23453
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853
  fallback:
    - tls://1.1.1.1:853
    - tls://dns.google
### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

使用rrule-providers是否必须配合proxy-providers.用了两份配置文件，差别在于一份有proxy-providers。一份是proxies。
有proxy-providers的通过测试，上面贴出来的，报错不支持rule-set
### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……
执行clash
**我预期会发生……？**

运行
**实际上发生了什麽？**

INFO[0000] Start initial compatible provider 节点选择       
FATA[0000] Parse config error: Rules[0] [RULE-SET,ad-block,REJECT] error: unsupported rule type RULE-SET

**Comment by ccssyybb** [comment]
尝试用proxy-providers引用了本地的proxies.yaml(节点信息)，也是在rule-set卡住。
jcadmin123@AX88U:/tmp/home/root# /koolshare/bin/clash -d /koolshare/merlinclash/ -f /tmp/upload/TEST.yaml
INFO[0000] Start initial provider duyaoo-local          
FATA[0000] Parse config error: Rules[0] [RULE-SET,ad-block,REJECT] error: unsupported rule type RULE-SET

**Comment by BirkhoffLee** [comment]
Premium 內核

**Comment by ccssyybb** [comment]
> Premium 內核

嗯，换内核解决。但是面板出问题了。
面板显示的是之前设置过的页面，proxy-group都是之前的，新定义的RULE-SET的类名，一个都没出来，也就无法通过面板选择节点了，
![IMG_20200629_014441_420](https://user-images.githubusercontent.com/32236397/85955025-72d17880-b9ae-11ea-807b-9b96e2920b1c.jpg)
![IMG_20200629_014423_056](https://user-images.githubusercontent.com/32236397/85955027-7533d280-b9ae-11ea-98cd-87fa2e486b9d.jpg)
