### ISSUE TITLE
[Bug] clash 控制页面，设置->代理模式，无法选中「全局、规则、直连」，但实际还是有效的。

### ISSUE THREAD

**Issue by ningsibuqu** [Dreamacro/clash#771]
![image](https://user-images.githubusercontent.com/51028975/85979472-24a29080-ba13-11ea-9064-3317dd9e36dd.png)‘
如图，点选「全局、规则、直连」任意一个的时候，该选项正常情况应该是变成蓝色。

不过实际切换模式还是有效果的。

**Comment by Dreamacro** [comment]
不是用线上页面的吧？该更新了

**Comment by ningsibuqu** [comment]
> 不是用线上页面的吧？该更新了

http://127.0.0.1:9090/ui/#/proxies
是通过这个访问的，应该不是线上页面？

**Comment by Dreamacro** [comment]
不是，更新一下吧
