### ISSUE TITLE
日志报错

### ISSUE THREAD

**Issue by Qinyu-Xie** [Dreamacro/clash#773]
2020/06/30 12:36:59:474  [warning] dial PROXY error: sheldonyuki.xyz:443 connect error: x509: certificate has expired or is not yet valid: current time 2020-06-30T12:36:59+08:00 is after 2020-06-23T08:42:07Z

服务器应该没问题。 ios端的小火箭能用。 不懂证书为什么invalid

**Comment by Ninzero** [comment]
> sheldonyuki.xyz:443

这个域名的 TLS 证书过期了, Shadowrocket大概没有校验证书. 你要么更新一下证书, 要么添加
```yaml
skip-cert-verify: true
```
到你的 Clash 配置里面.
