### ISSUE TITLE
[Bug]，新版的配置文件一大推错误，请给我一份关于clash1.0.0 版本的正确的配置文件，谢谢

### ISSUE THREAD

**Issue by ydsjqt** [Dreamacro/clash#776]
版本1.0.0
使用一下页面的配置报了一大推的错误
https://github.com/Dreamacro/clash/wiki/configuration
环境 ubuntu20 客户端

clash-linux-amd64[45360]: time="2020-07-01T11:07:14+08:00" level=fatal msg="Parse config error: external-ui: /home/ysq/etc/clash/folder not exist"
把 面板ui注释掉之后并填写上正确的uuid之后
time="2020-07-01T11:09:26+08:00" level=fatal msg="Parse config error: Proxy 7: snell server:44046 initialize obfs error: key 'mode' missing"
把 snell 注释掉之后
clash-linux-amd64[45768]: time="2020-07-01T11:11:31+08:00" level=fatal msg="Parse config error: initial proxy provider test error: open /test.yaml: no such file or directo
等等 一大推问题

**Comment by Dreamacro** [comment]
整个配置是偏渐进式的，不需要的配置为什么要写上去呢，只挑你自己需要的写上去不好么
