### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Ros-ua** [Dreamacro/clash#777]
Hello
I got a message "Deprecated profile detected" and a link to https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0

"Rule" is no longer used , I should change to "rules"

after the change I get the message "Invalid mode"  in the very beginning of yml profile

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rules
log-level: info

There is no problems in changing Proxy, Proxy Group to proxies, proxy-groups in profile

**Comment by Dreamacro** [comment]
Rule ==> rules means

```yaml
Rule:
  - DOMAIN,google.com,Proxy
```

to

```yaml
rules:
  - DOMAIN,google.com,Proxy
```

instead of 

```yaml
mode: Rule
```

to

```yaml
mode: rules
```

**Comment by Ros-ua** [comment]
Yes, that is exactly what I mean
mode: rules lead to a mistake 
![2](https://user-images.githubusercontent.com/51153745/86325594-df7c9980-bc72-11ea-9cf8-4a54f74bb249.PNG)
![1](https://user-images.githubusercontent.com/51153745/86325606-e3a8b700-bc72-11ea-9f79-a265037f128c.PNG)

**Comment by Dreamacro** [comment]
```yaml
mode: rule # ⭕
# mode: Rule # ⭕
# mode: rules # ❌
```
