### ISSUE TITLE
咨询一下1.0以上版本和1.0以下配置文件问题，配置文件可以和程序在一个目录吗？

### ISSUE THREAD

**Issue by bbhxwl** [Dreamacro/clash#778]
我刚了解到这个软件，今天想尝试自己开发订阅网址，针对0.9版本做了订阅，没问题了，但是1.0.4版本用不了，提示错误，不知道为什么，有什么不兼容么？还有好像这个一直安装tap不成功，另外配置文件可以和程序打包在一个压缩文件吗？就是自己设置好了订阅网址，然后发给别人。

**Comment by Dreamacro** [comment]
没有 0.9 版本，也没有 1.0.4，你应该是用的什么 GUI，找对应 GUI 的仓库吧

**Comment by bbhxwl** [comment]
> 没有 0.9 版本，也没有 1.0.4，你应该是用的什么 GUI，clash 也没有 TAP，找对应 GUI 的仓库吧

说错了，https://github.com/Fndroid/clash_for_windows_pkg   0.10.4，订阅网址的规则会写了，想问一下，配置文件能放软件根目录么？比如订阅网址。
