### ISSUE TITLE
[Feature] Log something if configuration format is empty or invalid

### ISSUE THREAD

**Issue by theFm** [Dreamacro/clash#779]
### 说明 Description
When I updated my Clash in docker from 0.20.0 to 1.0.0, it stoped working due to breaking changes in configuration. That's fine. 

However, there is no log output from the job. It costs lots of time for me to figure out what's wrong.

### 可能的解决方案 Possible Solution

If Clash could log something when reads an empty/ invalid config, it will be very helpful. e.g,.

```
Config is empty, please check if it's due to configuration format change since 1.0.0
```

### 更多信息 More Information
It can become more confusing if people uses watchtower to update clash automatically with tag latest.

**Comment by Dreamacro** [comment]
yaml instead of yml

**Comment by theFm** [comment]
I don't use yml.

My .yaml config looks like this:
```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: ""
Proxy:
  - name: ...
```

If I just update images from 0.20.0 => 1.0.0 without changing (Proxy =>proxies, Rule =>rule), clash can be started in docke but it doesn't output anything (and doesn't serve any traffic).

My volumn mapping in docker
- /volume1/Data/clash/config.yaml:/root/.config/clash/config.yaml

FYI, I asked my airport to update its subscribe format as well.

**Comment by BirkhoffLee** [comment]
log-level
