### ISSUE TITLE
[Bug]请提供1.0.0config配置文件

### ISSUE THREAD

**Issue by denel23** [Dreamacro/clash#784]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by denel23** [comment]
![image](https://user-images.githubusercontent.com/31842977/86511550-e8b16600-be2c-11ea-9bf2-a2476a429268.png)
这个问题在哪解决？

**Comment by BirkhoffLee** [comment]
wiki 裡有
