### ISSUE TITLE
i/o timeout issue.

### ISSUE THREAD

**Issue by babybabyCloud** [Dreamacro/clash#785]
Why I will get warning like this:
WARN[0483] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0483] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0484] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0485] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0487] dial DIRECT error: dial tcp4 203.208.40.33:443: i/o timeout 
WARN[0487] dial DIRECT error: dial tcp4 52.206.227.240:443: i/o timeout 
WARN[0487] dial DIRECT error: dial tcp4 52.74.223.119:443: i/o timeout 
WARN[0488] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0488] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0489] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0490] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0493] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0493] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0494] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0495] dial DIRECT error: dial tcp4 31.13.85.1:443: i/o timeout 
WARN[0497] dial DIRECT error: dial tcp4 52.74.223.119:443: i/o timeout 
WARN[0507] dial DIRECT error: dial tcp4 52.74.223.119:443: i/o timeout

When I change my OS from Manjaro to Ubuntu.
I could access Google Golang.org when using Clash in Manjaro, but failed in Ubuntu.
They used the same config file.

Thanks.

**Comment by Tootooroo** [comment]
same problem

WARN[0482] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0483] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0488] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0493] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0498] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0504] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0508] dial GLOBAL error: dial tcp4 104.18.9.111:443: i/o timeout 
WARN[0509] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0513] dial GLOBAL error: dial tcp4 104.18.8.111:443: i/o timeout 
WARN[0514] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0518] dial GLOBAL error: dial tcp4 104.18.9.111:443: i/o timeout 
WARN[0519] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0523] dial GLOBAL error: dial tcp4 104.18.8.111:443: i/o timeout 
WARN[0524] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0528] dial GLOBAL error: dial tcp4 104.18.8.111:443: i/o timeout 
WARN[0529] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0533] dial GLOBAL error: dial tcp4 104.18.9.111:443: i/o timeout 
WARN[0534] dial GLOBAL error: dial tcp4 172.217.27.129:443: i/o timeout 
WARN[0538] dial GLOBAL error: dial tcp4 104.18.9.111:443: i/o timeout 
WARN[0543] dial GLOBAL error: dial tcp4 104.18.8.111:443: i/o timeout 
WARN[0548] dial GLOBAL error: dial tcp4 104.18.9.111:443: i/o timeout 
WARN[0553] dial GLOBAL error: dial tcp4 104.18.8.111:443: i/o timeout

**Comment by GeorgeMiao219** [comment]
Same here 
```
WARN[0035] dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout 
WARN[0036] dial DIRECT error: dial tcp4 172.217.25.14:443: i/o timeout 
WARN[0040] dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout 
WARN[0041] dial DIRECT error: dial tcp4 172.217.25.14:443: i/o timeout
```

**Comment by Long0x0** [comment]
At first, I went to `https://glados-subscribe.com/clash/xx/xx/xx/glados_new.yaml` directly to get the config file and got the same error. In fact, after downloading using the command in step 2 of  `https://glados.rocks/console/clash`, everything works fine for me. Don't know if this helps.

**Comment by wusatosi** [comment]
> > 是不是因为你的网络连接不畅通呢？看起来这些timeout 的IP ，其中有一部分在某些地区是不可以透过DIRECT规则连接的。 @babybabyCloud
> 
> 网络 应该没有问题吧 我用windows版的的安卓版的 都 好用， 唯独在linux上， google都 打不开

我这边也可以复现

**Comment by wusatosi** [comment]
> > 是不是因为你的网络连接不畅通呢？看起来这些timeout 的IP ，其中有一部分在某些地区是不可以透过DIRECT规则连接的。 @babybabyCloud
> 
> 网络 应该没有问题吧 我用windows版的的安卓版的 都 好用， 唯独在linux上， google都 打不开

????????? 我把Proxy的server地址从域名换成ip就好了，你试试看?

我看看能不能做一个复现case

**Comment by babybabyCloud** [comment]
> > > 是不是因为你的网络连接不畅通呢？看起来这些timeout 的IP ，其中有一部分在某些地区是不可以透过DIRECT规则连接的。 @babybabyCloud
> > 
> > 
> > 网络 应该没有问题吧 我用windows版的的安卓版的 都 好用， 唯独在linux上， google都 打不开
> 
> ????????? 我把Proxy的server地址从域名换成ip就好了，你试试看?
> 
> 我看看能不能做一个复现case

@wusatosi  可以提供一些更详细的信息嘛？

**Comment by wusatosi** [comment]
> > > > 是不是因为你的网络连接不畅通呢？看起来这些timeout 的IP ，其中有一部分在某些地区是不可以透过DIRECT规则连接的。 @babybabyCloud
> > > 
> > > 
> > > 网络 应该没有问题吧 我用windows版的的安卓版的 都 好用， 唯独在linux上， google都 打不开
> > 
> > 
> > ????????? 我把Proxy的server地址从域名换成ip就好了，你试试看?
> > 我看看能不能做一个复现case
> 
> @wusatosi 可以提供一些更详细的信息嘛？

```yaml
port: 7892
socks-port: 7891
allow-lan: false
mode: Rule
log-level: debug
external-controller: 0.0.0.0:7890
external-ui: ui
bind-address: 0.0.0.0

proxies:
  - name: server
    type: ss
    server: example.com -> 改成 ip 地址在我这就可以解决这个问题了
    port: 50662
    cipher: rc4-md5
    password: NlbCzx
    udp: true

proxy-groups:
  - name: auto
    type: load-balance
    proxies:
      - server
    url: 'http://cdn.jsdelivr.net/gh/wusatosi/netlify-connection-check@1/cc'
    interval: 10

rules:
  - MATCH,auto

```

**Comment by everglowbear** [comment]
您这个问题解决了么？我同样遇到此类问题，但是不知道该如何设置，8月底还在正常使用，昨天开始突然连接不上，甚至包括手机数据都无法连入。
dial 节点选择 error:sg-v30sc.360cdn.men:327 connect error:dial tcp4 120.232.194.246:327:i/o timeout
这是从日志中发现的问题，您看是否可以帮助解决。

**Comment by babybabyCloud** [comment]
> 您这个问题解决了么？我同样遇到此类问题，但是不知道该如何设置，8月底还在正常使用，昨天开始突然连接不上，甚至包括手机数据都无法连入。
> dial 节点选择 error:sg-v30sc.360cdn.men:327 connect error:dial tcp4 120.232.194.246:327:i/o timeout
> 这是从日志中发现的问题，您看是否可以帮助解决。

我刚才试了下，用的是1.1.0 貌似已经没有这个问题了
有什么问题可以私下联系， 谢谢

**Comment by babybabyCloud** [comment]
I don't meet this issue with 1.1.0.
It seems to be resovled.

Close this issue.

Thanks.
