### ISSUE TITLE
TUNclash 出现几个问题

### ISSUE THREAD

**Issue by denel23** [Dreamacro/clash#786]
1.启动Tun报错，在哪解决？
2.配置都没问题正常ping服务器但是无法翻墙是不是DNS问题？
![image](https://user-images.githubusercontent.com/31842977/86534584-ff7aba00-bf0b-11ea-8040-242ff70faf5b.png)
![image](https://user-images.githubusercontent.com/31842977/86534589-0e616c80-bf0c-11ea-8808-5f8622f50f64.png)
![image](https://user-images.githubusercontent.com/31842977/86534596-13262080-bf0c-11ea-84f1-540530cc61ff.png)
![image](https://user-images.githubusercontent.com/31842977/86534600-17ead480-bf0c-11ea-8fb6-ffb4ceb6f8d5.png)
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

experimental:
  ignore-resolve-fail: true
  interface-name: en0

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  default-nameserver:
    - 1.2.4.8
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  nameserver:
    - 1.2.4.8
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - https://dns.adguard.com/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

tun:
  enable: true
  stack: system # or gvisor
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
 
proxies:
  - name: 🇺🇸
    type: ss
    server: 
    port: 
    cipher:
    password: 
  - name: 🇩🇪
    type: ss
    server: 
    port: 
    cipher: 
    password: 

proxy-groups:
  - name: "auto"
    type: url-test
    proxies:
      - 🇺🇸
      - 🇩🇪
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: "Proxy"
    type: select
    proxies:
      - 🇺🇸
      - 🇩🇪
      - DIRECT
      - auto
      

rules:
- DOMAIN-SUFFIX,google.com,auto
- DOMAIN-KEYWORD,google,auto
- DOMAIN,google.com,auto
- DOMAIN-SUFFIX,ad.com,REJECT
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- DST-PORT,80,DIRECT
- SRC-PORT,7777,DIRECT
- MATCH,auto

**Comment by denel23** [comment]
补充一下：上不了google.com,TWitter等，可上youtube到底怎么回事？

**Comment by Dreamacro** [comment]
缺少 tun 模块

**Comment by denel23** [comment]
在路由器装tun模块还是？

**Comment by denel23** [comment]
![image](https://user-images.githubusercontent.com/31842977/86552452-a39b4a00-bf7a-11ea-84c7-cde7603ca598.png)

**Comment by denel23** [comment]
![image](https://user-images.githubusercontent.com/31842977/86552463-ad24b200-bf7a-11ea-9c80-f8d08ec40c02.png)

**Comment by maddie** [comment]
`luci-app-clash`相关问题怎么不去`luci-app-clash`的project里面发issue呢？

```
$ opkg update
$ opkg install kmod-tun
```
