### ISSUE TITLE
导入配置文件时由于配置了rule-providers可能导致下载远程规则失败

### ISSUE THREAD

**Issue by lg0v0** [Dreamacro/clash#789]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>
rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

rules:
  - RULE-SET,Unbreak,DIRECT

  - RULE-SET,Streaming,Streaming

  - RULE-SET,StreamingSE,StreamingSE

  - RULE-SET,Global,PROXY

  - RULE-SET,China,DIRECT

  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT

  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT

  - GEOIP,CN,DIRECT

  - MATCH,MATCH

</details>

### Clash log

![image](https://user-images.githubusercontent.com/28627729/86566518-5e880f80-bf9c-11ea-9590-be4ce5d5ed7a.png)
![image](https://user-images.githubusercontent.com/28627729/86571865-bc205a00-bfa4-11ea-96e2-668d26211799.png)

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Android，windows，Linux，macOS
* 网路环境或拓扑 (network conditions/topology)
无代理
* iptables，如果适用 (if applicable)
无
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
没有
* 其他 (any other information that would be useful)

### 说明 Description
当没有开启代理时，导入配置了rule-providers规则的配置文件，有可能会因为远程服务器(github)无法访问导致远程规则下载失败，从而导致配置文件无法导入。

先启动一个没有配置rule-providers规则的代理，然后再导入配置了rule-providers规则的配置文件，可暂时解决该问题。远程服务器无法访问，就无法导入配置文件，无法导入配置文件就无法开启代理，无法代理就无法访问远程服务器，所以这里变成了无限套娃。

我自己遇到这个问题是在Clash For Android遇到的，上面有个图片是在Clash For Windows遇到的。rule-providers这个字段是由clash本体来处理，我认为这个应该是clash本体的问题。

### 重现问题的具体布骤 Steps to Reproduce

1. 下载神机规则
2. 填写服务器信息
3. 导入神机规则配置文件
4.报错(如上图)

**我预期会发生……？**

预期有如上图，无法下载rule-providers下配置的远程规则

**实际上发生了什么？**

实际根据每个地区访问远程服务器(github)的连通性，会出现有些地区导入规则不会报错，有些地区导入规则会报错。是否报错根据配置文件是否配置rule-providers远程规则，以及远程服务器(github)是否可以连通而定

### 可能的解决方案 Possible Solution

先启动一个没有配置rule-providers规则的代理，然后再导入配置了rule-providers规则的配置文件，可暂时解决该问题

**Comment by Dreamacro** [comment]
建议不使用 github 的地址，或者用镜像 github raw 的地址。因为 rule provider 以及 proxy provider 并不会走代理进行请求，保持直连请求这个逻辑也是讨论后的结果。如果还有什么疑问可以再提出来

**Comment by ceilort** [comment]
我也是刚发现这个问题，尝试了在配置文件的hosts里加入了GitHub的劫持但依然报错，是否可以在读取时先挂载劫持条目呢？我代我自己|´・ω・)ノ

**Comment by hehehehehaha** [comment]
先换个无污染的 DNS ......

**Comment by xqXQzzz1** [comment]
> 建议不使用 github 的地址，或者用镜像 github raw 的地址。因为 rule provider 以及 proxy provider 并不会走代理进行请求，保持直连请求这个逻辑也是讨论后的结果。如果还有什么疑问可以再提出来

是否可以提供开关，让使用者自行选择是否代理。

**Comment by Edger** [comment]
> 建议不使用 github 的地址，或者用镜像 github raw 的地址。因为 rule provider 以及 proxy provider 并不会走代理进行请求，保持直连请求这个逻辑也是讨论后的结果。如果还有什么疑问可以再提出来

现在 Github 彻底被墙了，规则根本更新不了，rule provider 以及 proxy provider 不走代理进行请求这种设计感觉很不合理啊，至少也要给个开关吧

**Comment by Edger** [comment]
> 建议不使用 github 的地址，或者用镜像 github raw 的地址。因为 rule provider 以及 proxy provider 并不会走代理进行请求，保持直连请求这个逻辑也是讨论后的结果。如果还有什么疑问可以再提出来

现在 Github 彻底被墙了，规则根本更新不了，rule provider 以及 proxy provider 不走代理进行请求这种设计感觉很不合理啊，至少也要给个开关吧

**Comment by Edger** [comment]
@Dreamacro

**Comment by yuki-216** [comment]
建议给选项，不希望 rule provider 强制直连

**Comment by yhgjzx** [comment]
我用https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt这个远程rule还是这样，我用v2rayn开全局代理，8.8.8.8DNS还是这样，远程rule有问题吧
![屏幕截图 2022-06-06 170922](https://user-images.githubusercontent.com/34363547/172131613-92ff6a0e-7363-42d4-a081-45284b4a6889.png)

**Comment by Ret70** [comment]
> 

请问现在 rule跟proxy的provider还是默认走直接连接吗？
我担心provider走代理，那么隐私数据可能会被代理服务器获取。

**Comment by Ret70** [comment]
@Dreamacro

请问现在 rule跟proxy的provider还是默认走直接连接吗？
我担心provider走代理，那么隐私数据可能会被代理服务器获取。
