### ISSUE TITLE
能否支持 RULE-SET

### ISSUE THREAD

**Issue by zzq889** [Dreamacro/clash#79]
https://nssurge.zendesk.com/hc/zh-cn/articles/360010038714-Surge-Mac-3-Release-Note

类似 Surge 3 的这种支持外部规则集

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/projects/1

**Comment by ruisiji** [comment]
@Dreamacro Hi, are there any progresses on this feature?

**Comment by Dreamacro** [comment]
@ruisiji 后面思考了一下，RULE-SET 在使用和实现上都不太优雅，目前的想法是实现一个类似 `ruleScript` 的东西，利用 script 控制所有的规则匹配，这样优化空间也更大。但在对这个功能实现前，目前优先级更高的有这么几个：

1. TUN
2. Stream API
3. 选择、DNS 缓存持久化

所以实现让整个规则更简短的功能只能排后面了

**Comment by ruisiji** [comment]
I see, thanks for the update.

**Comment by ruisiji** [comment]
It is better to have a feature spec for `ruleScript`, so others can join the discussion and provide comments.

I can contribute on this.

My requirement is to separate the rules and proxies.

**Comment by Dreamacro** [comment]
@ruisiji #272
