### ISSUE TITLE
[Feature] DNS Server binding to multiple addresses DNS 服务器绑定多个地址

### ISSUE THREAD

**Issue by LEXUGE** [Dreamacro/clash#791]
希望 Clash 支持内建 DNS 服务器绑定多个地址， 比如 `127.0.0.1:53, 192.168.12.1:53` ，目前只能使用 `0.0.0.0:53` 但是这有些时候会和别的服务产生不必要的冲突 （比如 libvirtd 可能会要 `192.168.122.1:53`）

Clash currently only supports binding internal DNS Server to one address. I hope Clash could support multiple addresses binding in the future, like binding to both `127.0.0.1:53, 192.168.12.1:53`. Currently, I can only somewhat manage it by binding DNS Server to `0.0.0.0:53`, but which would unnecessarily conflict with other services, like libvirtd which wants `192.168.122.1:53`.

**Comment by LEXUGE** [comment]
This is demanding

**Comment by laggardkernel** [comment]
不清楚原生 clash 什么情况。但 clashx pro 原来是只能监听 0.0.0.0，后来改为了默认兼容 fake-ip 子网段内某个地址。

这个问题算是解决了吧。

**Comment by lyz05** [comment]
在Ubuntu 20.04上会有systemd-resolve进程监听在127.0.0.53:53上，在bind-address上我就无法使用全局监听 0.0.0.0:53，而我有多个网卡需要使用到Clash的DNS。所以，我也希望能够监听多个地址。
