### ISSUE TITLE
[Bug]2020.06.27-ARMv8版本无法访问IPv6节点。

### ISSUE THREAD

**Issue by sumsethan** [Dreamacro/clash#792]
在Armbian上相同配置仅更换客户端binary，Premium 2020.06.27-ARMv8版本无法访问IPv6地址及仅有AAAA记录的域名节点，换回Premium 2020.05.08-ARMv8版本则可正常访问。

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/configuration 搜索 ipv6

**Comment by sumsethan** [comment]
哦。。。新加了一个参数么。。。。记得以前只有dns里有个ipv6来着

**Comment by Dreamacro** [comment]
现在有两个 ipv6 选项
