### ISSUE TITLE
[Bug] Tun模式报All DNS requests failed, first error: context deadline exceeded

### ISSUE THREAD

**Issue by liaowang11** [Dreamacro/clash#793]
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
dns:
  enable: true
  listen: 0.0.0.0:1053
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: redir-host
  nameserver:
    - 233.5.5.5

tun:
  enable: true
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53

experimental:
  interface-name: en0

proxies:
- { name: "trojan", type: trojan, server: "abc.com", port: 443, password: "***", udp: true}
```

</details>

### Clash log

```
WARN[0127] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0127] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0127] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0127] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0127] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0127] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0127] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0133] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0133] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded
WARN[0133] dial MATCH error: abc.com:443 connect error: All DNS requests failed, first error: context deadline exceeded

```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macos
* 网路环境或拓扑 (network conditions/topology)

* iptables，如果适用 (if applicable)
none
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无
* 其他 (any other information that would be useful)

### 重现问题的具体布骤 Steps to Reproduce

1. 按照上面配置clash
2. sudo运行clash，因为要绑定1053端口
3. 自动配置了route，打开需要路由的某个页面报错

**我预期会发生……？**

正常连接上trojan服务器并路由请求
**实际上发生了什么？**
报错，页面无法打开

### 可能的解决方案 Possible Solution

不太清楚是不是因为我配置host用的域名，而域名需要解析，域名解析又需要连接远程trojan服务器？

**Comment by Dreamacro** [comment]
不会配置的话 建议直接用 clashx pro, 不需要设置 tun 字段及 dns 增强模式相关配置

**Comment by liaowang11** [comment]
> 不会配置的话 建议直接用 clashx pro, 不需要设置 tun 字段及 dns 增强模式相关配置

ClashX好像不支持tun模式？最近想尝试一下tun模式。按照 https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/setup-system-stack-in-real-ip-mode 配置的。不知道能否指点一下什么地方配置错了？我在linux下面也没配置成功过。😭

**Comment by Dreamacro** [comment]
clashx pro 支持的，真要手动的话看这个 https://github.com/Dreamacro/clash/releases/tag/premium

**Comment by liaowang11** [comment]
> clashx pro 支持的，真要手动的话看这个 [`premium` (release)](https://github.com/Dreamacro/clash/releases/tag/premium)

装clashx pro研究一下怎么配置的，多谢

**Comment by Sciroccogti** [comment]
也可能是 `interface name` 选错了（比如我
