### ISSUE TITLE
127.0.0.1:9090

### ISSUE THREAD

**Issue by e71828** [Dreamacro/clash#795]
127.0.0.1:9090
`{"hello":"clash"}`
没有解决

可以局域网远程配置么？
http://clash.razord.top/#/proxies只能在本机上啊
_Originally posted by @e71828 in https://github.com/Dreamacro/clash/issues/546#issuecomment-656027141_

**Comment by catna** [comment]
![image](https://user-images.githubusercontent.com/13216533/87049501-a1ade100-c22f-11ea-988a-bbc32e212f6a.png)
试试这么操作?

**Comment by e71828** [comment]
@catna 直接refuse了

**Comment by myfingerhurt** [comment]
Your 9090 has been taken by other processes.
Check it out by `lsof -i -P -n | grep 9090`

**Comment by JiangongWang** [comment]
我也也是同样的问题

**Comment by JiangongWang** [comment]
需要安装clash-dashboard服务

**Comment by e71828** [comment]
`clash   1691 ****    8u  IPv6  56412      0t0  TCP *:9090 (LISTEN)`

**Comment by John-zhan** [comment]
问题解决没
