### ISSUE TITLE
请问怎么更新10.4配置，我更新到11.0，看不到机场

### ISSUE THREAD

**Issue by ybbpascal** [Dreamacro/clash#797]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by echo860** [comment]
我的也是，所以我换回10.4了

**Comment by fernandoxu** [comment]
同

**Comment by Dreamacro** [comment]
Not a problem this repository needs to solve.
