### ISSUE TITLE
Add prometheus metrics [Feature]

### ISSUE THREAD

**Issue by mhf-ir** [Dreamacro/clash#799]
* Which user are connected.
* How much bandwidth send/receive for each user.

Sample output:
```
# how much longer user are connected
user_connected_sec{user="1"} 3600
user_connected_sec{user="2"} 1800

# how much user upload bytes to proxy server
user_upload_bytes{user="1"} 1024

# how much user download bytes from proxy server
user_download_bytes{user="1"} 2048
```

**Comment by Dreamacro** [comment]
Yeah, I was thinking of let clash as a scrape and stored event to time series database. The solution to this idea is to implement an event API (like `docker events`).

I don't know what `user` you're referring to here, maybe it's source IP? I think it's ROI is too low, so I'm putting it on hold. maybe you can help this project implement this API?

**Comment by mhf-ir** [comment]
> Yeah, I was thinking of let clash as a scrape and stored event to time series database. The solution to this idea is to implement an event API (like `docker events`).

Prometheus exporter is good solution, it's popular it's just http server that expose some metrics no log or push method. Simple and powerfull and golang friendly.

> I don't know what `user` you're referring to here, maybe it's source IP?

User might be a **username** field for socks for this example:
```yml
proxies:
  - name: "socks"
    type: socks5
    server: server
    port: 443
    username: username
    password: password
```

> maybe you can help this project implement this API?
Sorry i'm not expert enough but consider this feature in future

**Comment by elonzh** [comment]
metrics are really useful for production use, I think we should consider it.

**Comment by elonzh** [comment]
I am trying to write a [Prometheus exporter](https://github.com/elonzh/clash_exporter) by using the controller API, but there are some issues or features that need to be resolved in Clash.

1. Can't test single provider proxy, we can use the `/providers/proxies/<provider-name>/healthcheck` route as a workaround but we can not change the health check URL and timeout. Maybe we can provide a route like `/providers/proxies/<provider-name>/<proxy-name>/delay`?
2. Count total traffic bytes for a specific destination.
3. Provider URL check.
4. Provider level data usage for data usage alert.
5. Other metrics for connection like total connections counter(open or closed).

I will think about the solution and trying to implement it.

**Comment by elonzh** [comment]
@Dreamacro please reopen this issue

**Comment by Dreamacro** [comment]
@elonzh you can open another issue for it
