### ISSUE TITLE
[Bug]托管配置文件格式不正确: yaml: unmarshal errors:   line 1: cannot unmarshal !!str `<html><...` into config.RawConfig

### ISSUE THREAD

**Issue by SchafferWang0818** [Dreamacro/clash#801]
托管配置文件格式不正确: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `<html><...` into config.RawConfig

我在MacOS 10.15.5上面出现的, 查了好久没看到如何解决, 看到请回复解决方案.谢谢

**Comment by SchafferWang0818** [comment]
是在设置远程节点更新时出现的

**Comment by Dreamacro** [comment]
检查自己的配置

**Comment by MultiSuperK** [comment]
您好，我至今都在被这个问题困扰，能否解答究竟哪个版本不会出现unmarshal的问题

**Comment by MultiSuperK** [comment]
@SchafferWang0818 maybe we should see https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0
