### ISSUE TITLE
[Feature] 如果域名Match了REJECT，其实是不需要进行DNS查询的

### ISSUE THREAD

**Issue by trawor** [Dreamacro/clash#806]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
I use RULE-SET payload
```

### Clash log

```
DEBU[0128] [DNS] securepubads.g.doubleclick.net --> 203.208.39.230
INFO[0128] [TCP] 127.0.0.1:64542 --> securepubads.g.doubleclick.net match RuleSet using REJECT
DEBU[0128] [DNS] securepubads.g.doubleclick.net --> 203.208.39.230
INFO[0128] [TCP] 127.0.0.1:64543 --> securepubads.g.doubleclick.net match RuleSet using REJECT
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
clash-darwin-amd64-2020.06.27 `Premium` 
* 使用者的操作系统 (the OS running on the client)
macOS
* 网路环境或拓扑 (network conditions/topology)
NAT
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
YES
* 其他
……

### 可能的解决方案 Possible Solution

期待：如果域名Match了`REJECT`，其实是不需要进行DNS查询的

**Comment by Dreamacro** [comment]
增强模式不可能做到的，使用普通的 socks5 和 http 倒是可以，而且目前就是不 dns 解析
