### ISSUE TITLE
TPROXY的iptable怎么处理才好。按指导文档跟网上教程的例子，路由瞬间被爆

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#808]
用了06.27P核心。
![IMG_20200715_005948_857](https://user-images.githubusercontent.com/67776691/87454574-bf67b580-c636-11ea-8e3f-7e7e6d9ff3d6.jpg)
看到tp瞬间几万个包，然后网络卡顿。立马重启了

 redir-host的tproxy到底咋弄咯

**Comment by myfingerhurt** [comment]
Redirect your router's local traffic (OUTPUT Chain)is not recommended. 
Process PREROUTING Chain in mangle OR nat would be good enough for your needs.

**Comment by flyhigherpi** [comment]
目前写法，倒是不会炸路由了。给参考
ip rule add fwmark 1 lookup 100
		ip route add local default dev lo table 100
		iptables -t mangle -N merlinclash
		iptables -t mangle -F merlinclash
		#绕过内网
		
		#iptables -t mangle -A merlinclash -d 192.168.0.0/16 -j RETURN
		iptables -t mangle -A merlinclash -d 192.168.0.0/16 -p tcp -j RETURN
		iptables -t mangle -A merlinclash -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
		iptables -t mangle -A merlinclash -d 192.168.0.0/16 -p udp ! --dport 23453 -j RETURN
		iptables -t mangle -A merlinclash -d 10.0.0.0/8 -j RETURN
		iptables -t mangle -A merlinclash -d 0.0.0.0/8 -j RETURN
		iptables -t mangle -A merlinclash -d 127.0.0.0/8 -j RETURN
		iptables -t mangle -A merlinclash -d 169.254.0.0/16 -j RETURN
		iptables -t mangle -A merlinclash -d 172.16.0.0/12 -j RETURN
		iptables -t mangle -A merlinclash -d 224.0.0.0/4 -j RETURN
		iptables -t mangle -A merlinclash -d 240.0.0.0/4 -j RETURN	
		#转发UDP流量到clash端口
		iptables -t mangle -A merlinclash -p udp -j TPROXY --on-port "$proxy_port" --tproxy-mark 0x01/0x01
		#透明代理UDP流量到clash mangle链
		iptables -t mangle -A PREROUTING -p udp -i $bridge -j merlinclash
