### ISSUE TITLE
[Bug]Small problems, Chinese build timestamp and requiring unnecessary write permission

### ISSUE THREAD

**Issue by myfingerhurt** [Dreamacro/clash#809]
Thanks for opening an issue towards the Clash core!
But before so, please do the following checklist:

- [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
No
- [x] I have searched on the [issue tracker](……/) for a related issue.
Yes
- [x] I have tested using the dev branch, and the issue still exists.
Not possible
- [x] I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue
Yes
- [x] This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash
Yes

------------------------------------------------------------------

### Clash config

```yaml
rule-providers:
  Telegram:
    type: file
    behavior: classical
    path: ./RuleSet/Telegram.yaml
```
### Clash log
```
ubuntu@ss:~$ sudo -S -H -u clash clashp -d /home/ubuntu/.clash
INFO[0000] Start initial compatible provider Telegram
INFO[0000] Start initial compatible provider Twitter
INFO[0000] Start initial compatible provider notvps
INFO[0000] Start initial compatible provider Proxy
INFO[0000] Start initial rule provider Telegram
FATA[0000] Parse config error: initial rule provider Telegram error: open /home/ubuntu/.clash/RuleSet/Telegram.yaml: permission denied
```

### Environment

* (the OS that the Clash core is running on)
ubuntu 18.04 LTS

*  (any other information that would be useful)
```
> ls -al /home/ubuntu/.clash/RuleSet/Telegram.yaml
-rw-r--r-- 1 ubuntu ubuntu 847 Jul 15 17:04 /home/ubuntu/.clash/RuleSet/Telegram.yaml

> clashp -v
Clash 2020.06.27 linux amd64 2020年 6月27日 星期六 13时19分54秒 UTC <-- English info expected.
```

### Description

* [What you expected to happen] 
Normal operations.

* [What actually happened]  
With read-only *.yaml file, Clash-premium got permission denied and exited.

Clash-premium wants to write read-only Telegram.yaml.
Clash-premium writes very single rule-set *.yaml, every time it starts.

For file type rule-providers, write permission is not necessary.

**Comment by Dreamacro** [comment]
fixed, if you use docker, you can easily to use lastest premium binary on `dreamacro/clash-premium`
