### ISSUE TITLE
请问 IP-CIDR,192.168.5.1/24 这样的规则无法生效是咋回事

### ISSUE THREAD

**Issue by helfee** [Dreamacro/clash#81]
日志里根本无法匹配

**Comment by Dreamacro** [comment]
@helfee 有使用 GUI 吗，用的是哪种

**Comment by helfee** [comment]
找到原因了,我用ie测试的,局域网连接没勾选[对于本地地址不使用代理服务器],但发现高级里列出很多例外的网段,包含我要测试的段..删除后正常使用了,3Q~
