### ISSUE TITLE
[Bug]VMess 配置不支持 IPv6 地址的服务器

### ISSUE THREAD

**Issue by vaple** [Dreamacro/clash#815]
------------------------------------------------------------------

[https://github.com/Dreamacro/clash/issues/381](url) 这个问题之前已有出现，虽然closed但是似乎并未完全修复，同样的配置仅将ipv6改为ipv4即可使用
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
proxies:
  - {name: DigitalOcean, server: ipv6-address, port: port, type: vmess, uuid: uuid, alterId: 233, cipher: auto, tls: false}
```

</details>

### Clash log

```
time="2020-07-18T16:01:21+08:00" level=warning msg="dial GLOBAL error: [ipv6_address]:port connect error: ip version error"
```

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/configuration ipv6

**Comment by vaple** [comment]
呃，我设置了`ipv6: true`但是仍然不行，我填的是ipv6地址，这个选项不是控制ipv6解析的吗
