### ISSUE TITLE
[Question] Will classical behaviour in rule-provider influence the rule-match performance ?

### ISSUE THREAD

**Issue by gth7754125** [Dreamacro/clash#816]
According to rule-provider, will the `classical` behaviour work slower than `domain` or `ip-cidr` behaviour  on rule-matching ? 
Or add this mode just for easy to migrate the former rules written on config.yaml ?

**Comment by Dreamacro** [comment]
Of course, the speed of matching `domain` and `ip-cidr` is independent of list size, but `classical` is related to the list size
