### ISSUE TITLE
我的http代理端口总是显示0

### ISSUE THREAD

**Issue by causlayer** [Dreamacro/clash#818]
#---------------------------------------------------#
## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#
# Port of HTTP(S) proxy server on the local end
port: 1087
# Port of SOCKS5 proxy server on the local end
socks-port: 1086
# (HTTP and SOCKS5 in one port)
# mixed-port: 7890
# redir port for Linux and macOS
# redir-port: 7892
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: info

proxies:

proxy-groups:

rules:
  - DOMAIN-SUFFIX,google.com,DIRECT
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN,google.com,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT

这是我修改默认的config.yaml的文件，为何我这里的http代理端口还是0呢？谢谢

**Comment by tsln1998** [comment]
用的 dashboard 或者 gui 不支持 mixed-port

**Comment by causlayer** [comment]
port: 1087
socks-port: 1086
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: info
proxies:
proxy-groups:
rules:
  - DOMAIN-SUFFIX,google.com,DIRECT
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN,google.com,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
可是这样还是不行啊

**Comment by ozil-10** [comment]
插个眼

**Comment by liby** [comment]
这应该是 Clash X 的问题，不过只是一个显示问题，不影响使用；
但 Clash X 不能提 issue，实在纠结的话，你 @ 作者看看

**Comment by kylin17** [comment]
Windows 0.10.4版本今天遇到同样的问题，dashboard上的general选项卡显示port为0，然后开启系统代理后无法正常访问网页。
7890和9090均检查过，没有存在端口占用。

**Comment by kylin17** [comment]
日志里看到这段
`time="2020-08-15T12:58:19+08:00" level=error msg="Start Mixed(http and socks5) server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."`
这会是什么权限影响的？

**Comment by kylin17** [comment]
找到原因了，罗技鼠标有个`lghub-agent`的进程占用了9090端口导致。但不知道为什么用`netstat -ano |findstr 9090`没找到它，最后用资源监视器才发现。

**Comment by liby** [comment]
> 找到原因了，罗技鼠标有个`lghub-agent`的进程占用了9090端口导致。但不知道为什么用`netstat -ano |findstr 9090`没找到它，最后用资源监视器才发现。

那你看一下 Menu/Help/Prots 里的端口显示的是什么呢？
- 开启 `mixed-port` ：
![image](https://user-images.githubusercontent.com/38807139/90309354-8d3dc200-df1a-11ea-942e-18f69fbf661b.png)

- 关闭 `mixed-port`：
![image](https://user-images.githubusercontent.com/38807139/90309334-57004280-df1a-11ea-9628-337148ae4959.png)

感觉 `mixed-port` 是默认开启的，就算注释了这一行，也会使用 `http-port` 的设置

**Comment by kylin17** [comment]
@liby Windows版遇到的问题，Mac版本暂时没遇到过这个问题。

**Comment by nanxiaobei** [comment]
Mac ClashXR 也遇到了这个问题，而且在控制台无法修改端口，输入框像是假的，只能在本地配置文件里改

**Comment by wangshuai-007** [comment]
我用这个命令查找
```powershell
Get-Process -Id (Get-NetTCPConnection -LocalPort 7890).OwningProcess
```
没找到端口占用的应用，但是就是连接不上，无奈把`mixed-port`改成`9870`瞬间就可以用了
不知道什么原因

**Comment by winkee01** [comment]
请问 external-controller 是干啥的？
