### ISSUE TITLE
GEOIP 准确率不是很高啊，是否考虑支持 ipip.net?

### ISSUE THREAD

**Issue by antonchen** [Dreamacro/clash#82]
我比较讨厌很长的配置，所以我基于国家来做分流，达到就近节点代理的目的。
但我测试访问 www.google.com 时，解析到 IP 216.58.200.228，IP 物理位置应该是在台湾，但是 GEOIP 的结果是美国。

ipip.net 很早之前就能查到大部分 google 的正确物理位置，它们的免费版精度也完全符合需求，官网地址 https://www.ipip.net/product/client.html （需注册才能下载）

官方提供的 golang sdk https://github.com/ipipdotnet/ipdb-go

所以是否考虑支持 ipip.net 免费离线库呢？

**Comment by Dreamacro** [comment]
目前的 mmdb 我可以初始化启动直接下载到本机，但是注册才能下载就做不到这一点了。而且有 ipip.net 和 maxmind 两者详细的对比吗？光凭几个 IP 说明不了什么

**Comment by kamingchan** [comment]
IPIP 的准确率的确比 Maxmind 要高（至少在处理中国 IP 上），可以看看 149.129.87.21 这个地址，IPIP 可以识别出是香港阿里云，而 Maxmind 认为是中国 IP。

![image](https://user-images.githubusercontent.com/9930758/50772626-65f82b00-12c9-11e9-877a-71aa1a7148bd.png)

![image](https://user-images.githubusercontent.com/9930758/50772619-5d9ff000-12c9-11e9-9ac5-e07e25f60155.png)

**Comment by Dreamacro** [comment]
@kamingchan 所以怎么处理在不内嵌的情况下下载一个 ipip.net 的数据库？

**Comment by antonchen** [comment]
可以人工维护吗？建议在 Github 单独创建一个分支来存储库。

另外：我详细的看了下 ipip.net 的免费版，它只有中文版，可能需要把结果手动转换才能使用

**Comment by kamingchan** [comment]
@Dreamacro 咨询了一下 IPIP 那边的同事，他们的答复是下载需要注册是希望控制流量成本。如果我们需要使用的话，可以自行维护一个下载源。

**Comment by a89757** [comment]
不建议使用国内机构的数据源

**Comment by ShaoXinSen** [comment]
ipip的库参考下这个
https://github.com/17mon/china_ip_list

**Comment by kamingchan** [comment]
@ShaoXinSen 这里只有中国的 IP。

**Comment by ShaoXinSen** [comment]
@kamingchan
大部分人用geoip就是geoip cn direct
ipip提供的这个iplist正好就是，在其中的，那就判断cn好了

**Comment by ShaoXinSen** [comment]
这个不好的话，那考虑下提供额外配置支持ipip的库？

**Comment by kamingchan** [comment]
@Dreamacro @antonchen 我觉得可以增加一种规则类型吧。例如是 `IP-LIST,/PATH/TO/FILE,Proxy`，这样就可以利用上 https://github.com/17mon/china_ip_list 了。

**Comment by ShaoXinSen** [comment]
也可以考虑添加配置IPIP,CN,DIRECT 这种...
这种情况下就去找用户配置目录添加的ipip的数据库(当然这数据库要用户去下载)

**Comment by alexlee728** [comment]
> IPIP 的准确率的确比 Maxmind 要高（至少在处理中国 IP 上），可以看看 149.129.87.21 这个地址，IPIP 可以识别出是香港阿里云，而 Maxmind 认为是中国 IP。
> 
> ![image](https://user-images.githubusercontent.com/9930758/50772626-65f82b00-12c9-11e9-877a-71aa1a7148bd.png)
> 
> ![image](https://user-images.githubusercontent.com/9930758/50772619-5d9ff000-12c9-11e9-9ac5-e07e25f60155.png)

149.129.87.21 
maxmind 为新加坡
https://db-ip.com/149.129.87.21 为中国北京
ipip为香港阿里云

**Comment by alexlee728** [comment]
https://github.com/ipipdotnet/ipdb-go

**Comment by alexlee728** [comment]
https://github.com/ipipdotnet/ipdb-go

**Comment by Dreamacro** [comment]
ipip 一段时间改一次格式，要不起

**Comment by ysc3839** [comment]
不知道是否可以自己生成 mmdb，如果可以的话，把 ipip 的数据转换过去就好了。

**Comment by alexlee728** [comment]
> ipip 一段时间改一次格式，要不起

看go版本没有变动啊，都一年多了。

**Comment by dzxx36gyy** [comment]
> ipip 一段时间改一次格式，要不起

官方说以后不会改格式了，最终就是IPDB格式了

**Comment by antonchen** [comment]
> ipip 一段时间改一次格式，要不起

可以使用 https://github.com/firehol/blocklist-ipsets 自制 IP 库

**Comment by alexlee728** [comment]
https://github.com/firehol/blocklist-ipsets/blob/master/ipip_country/ipip_country_cn.netset

http://iplists.firehol.org/?ipset=ipip_country_cn

https://cdn.ipip.net/17mon/country.zip

**Comment by alexlee728** [comment]
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list

可以用这个解决，里面看起来就是ipip的数据转化来的。

**Comment by nasbdh9** [comment]
https://github.com/Dreamacro/clash/issues/615#issuecomment-629684935
@Dreamacro
既然可供选择的mmdb库很少，那是否可以考虑mmdb库以外的实现方式？

**Comment by Dreamacro** [comment]
@nasbdh9 mmdb 的格式相对来说是比较稳定和合理的，DBIP 也提供了 mmdb 的格式，你可以自己换

**Comment by alecthw** [comment]
搞了个小项目，重新生成了GeoIP mmdb数据库，在MaxMind数据库的基础上，加入了china_ip_list和纯真CN数据库，重新生成了mmdb文件，匹配中国IP更为精确。
自己动手，丰衣足食
可以直接替换openclash中的Country.mmdb使用。
https://github.com/alecthw/mmdb_china_ip_list

**Comment by Dreamacro** [comment]
由于已有 @alecthw 的替代方案，问题 close

**Comment by JMVoid** [comment]
做了个小程序， 将ipip的china_ip_list.txt转成MaxMind mmdb格式，https://github.com/JMVoid/ipip2mmdb 在release branch 下载Country.mmdb就好

**Comment by git10135405** [comment]
> 搞了个小项目，重新生成了GeoIP mmdb数据库，在MaxMind数据库的基础上，加入了china_ip_list和纯真CN数据库，重新生成了mmdb文件，匹配中国IP更为精确。
> 自己动手，丰衣足食
> 可以直接替换openclash中的Country.mmdb使用。
> https://github.com/alecthw/mmdb_china_ip_list

想问下，clash在rules中怎么实现添加你这个？

**Comment by alexlee728** [comment]
> > 搞了个小项目，重新生成了GeoIP mmdb数据库，在MaxMind数据库的基础上，加入了china_ip_list和纯真CN数据库，重新生成了mmdb文件，匹配中国IP更为精确。
> > 自己动手，丰衣足食
> > 可以直接替换openclash中的Country.mmdb使用。
> > https://github.com/alecthw/mmdb_china_ip_list
> 
> 想问下，clash在rules中怎么实现添加你这个？

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list

**Comment by git10135405** [comment]
@alexlee728 感觉用这个比较刷头条比较慢了？

**Comment by alexlee728** [comment]
> @alexlee728 感觉用这个比较刷头条比较慢了？

我用的GEOIP，这个数据大，不知道是不是用数据库效率更好点（不确定）
