### ISSUE TITLE
[Bug]Docker无限重启

### ISSUE THREAD

**Issue by lilunxm12** [Dreamacro/clash#821]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
clash    | time="2020-07-20T08:49:07Z" level=fatal msg="Parse config error: external-ui: /root/.config/clash/folder not exist"
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Ubuntu 20.04 LTS, Docker 19.03.12
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description
按照https://github.com/Dreamacro/clash/wiki/clash-as-a-daemon使用docker-compose起clash的容器,容器无限重启
docker-compose logs输出为
clash    | time="2020-07-20T08:49:07Z" level=fatal msg="Parse config error: external-ui: /root/.config/clash/folder not exist"

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
按照https://github.com/Dreamacro/clash/wiki/clash-as-a-daemon编写config.yaml和docker-compose.yaml,起容器
2. [Second Step]
容器正常启动
3. ……
无限重启

**我预期会发生……？**

clash正常运行

**实际上发生了什么？**

容器无限重启

### 更多信息 More Information
docker-compose.yaml:
version: '3'
services:
  clash:
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ~/config.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890"
      - "7891:7891"
    restart: unless-stopped
    network_mode: "bridge" # or "host" on Linux

**Comment by BirkhoffLee** [comment]
沒有 mount external-ui 指定的資料夾

**Comment by lilunxm12** [comment]
> 
> 沒有 mount external-ui 指定的資料夾
> […](#)
> On Jul 20, 2020, at 5:02 PM, lilunxm12 ***@***.***> wrote: ﻿ Clash config config.yaml Clash log clash | time="2020-07-20T08:49:07Z" level=fatal msg="Parse config error: external-ui: /root/.config/clash/folder not exist" …… 环境 Environment 操作系统 (the OS that the Clash core is running on) Ubuntu 20.04 LTS, Docker 19.03.12 …… 网路环境或拓扑 (network conditions/topology) …… iptables，如果适用 (if applicable) …… ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?) …… 其他 (any other information that would be useful) …… 说明 Description 按照[https://github.com/Dreamacro/clash/wiki/clash-as-a-daemon使用docker-compose起clash的容器,容器无限重启](https://github.com/Dreamacro/clash/wiki/clash-as-a-daemon%E4%BD%BF%E7%94%A8docker-compose%E8%B5%B7clash%E7%9A%84%E5%AE%B9%E5%99%A8,%E5%AE%B9%E5%99%A8%E6%97%A0%E9%99%90%E9%87%8D%E5%90%AF) docker-compose logs输出为 clash | time="2020-07-20T08:49:07Z" level=fatal msg="Parse config error: external-ui: /root/.config/clash/folder not exist" 重现问题的具体布骤 Steps to Reproduce [First Step] 按照[https://github.com/Dreamacro/clash/wiki/clash-as-a-daemon编写config.yaml和docker-compose.yaml,起容器](https://github.com/Dreamacro/clash/wiki/clash-as-a-daemon%E7%BC%96%E5%86%99config.yaml%E5%92%8Cdocker-compose.yaml,%E8%B5%B7%E5%AE%B9%E5%99%A8) [Second Step] 容器正常启动 …… 无限重启 我预期会发生……？ clash正常运行 实际上发生了什么？ 容器无限重启 可能的解决方案 Possible Solution 更多信息 More Information docker-compose.yaml: version: '3' services: clash: image: dreamacro/clash container_name: clash volumes: - ~/config.yaml:/root/.config/clash/config.yaml ports: - "7890:7890" - "7891:7891" restart: unless-stopped network_mode: "bridge" # or "host" on Linux — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢,config里把external-ui: folder注释掉就好了,没注意直接拷贝的config
