### ISSUE TITLE
请问,clash有按顺序加载配置的功能吗

### ISSUE THREAD

**Issue by dante2046** [Dreamacro/clash#823]
是否能按设定顺序加载多分配置呢
如果能是否有以下功能
有AB两分配置,
A只写了port和dns 等参数,
B也写了port,dns,以及代理,代理组和规则,的全部参数
先加载A 再加载B,就会忽略 B中的 port 和dns 等参数

**Comment by Dreamacro** [comment]
没有，这样增加了使用的复杂度

**Comment by dante2046** [comment]
看见cfw是用general控制port的
又看到clash可以用provider来读取其他的yaml文件。
小白以为有这种功能了，打扰了。
