### ISSUE TITLE
[Bug]文档更正

### ISSUE THREAD

**Issue by muink** [Dreamacro/clash#826]
[文档](https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode) 中的 `Full Core` 字段应更正为  `Full Cone`

**Comment by BirkhoffLee** [comment]
那個不是官方 documentation

**Comment by muink** [comment]
尴尬，那还是新版的 gitbook，没有对应的 git 库，页面也没有联系手段
不过确实蛮详细的，比官方 wiki 解释得更清楚
