### ISSUE TITLE
[Bug]Panic

### ISSUE THREAD

**Issue by wongsyrone** [Dreamacro/clash#827]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
07-22 16:36:35.710 15283     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
07-22 16:36:35.710 15283     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x731b49afc4]
07-22 16:36:35.710 15283     0 E Go      :
07-22 16:36:35.710 15283     0 E Go      : goroutine 624 [running]:
07-22 16:36:35.710 15283     0 E Go      : github.com/Dreamacro/clash/tunnel.handleTCPConn(0x731b73f7a0, 0x4000359e40)
07-22 16:36:35.710 15283     0 E Go      :      github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:264 +0x184
07-22 16:36:35.710 15283     0 E Go      : created by github.com/Dreamacro/clash/tunnel.process
07-22 16:36:35.710 15283     0 E Go      :      github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:118 +0xcc
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Android arm64-v8a Commit: https://github.com/Dreamacro/clash/commit/20eff200b100a6e8b59ffc36b63b93c6e9fbe2a7
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by Dreamacro** [comment]
看起来 panic 不是完整的，下面应该还有从哪个 inbound 进来的 stack。这个用的是哪个 inbound proxy 入口？

**Comment by wongsyrone** [comment]
SOCKS5 监听进Clash的，SOCKS5服务做唯一出站

**Comment by wongsyrone** [comment]
这段panic是检测igniter的时候发现的，完整adb输出在https://gist.github.com/wongsyrone/4e50af2deae612ef4766c3789d0fd42c

clash配置文件在 https://github.com/trojan-gfw/igniter/blob/master/app/src/main/res/raw/clash_config.yaml

Clash只做了极少更改，代码位于 https://github.com/trojan-gfw/clash/commits/igniter-go-libs

**Comment by Dreamacro** [comment]
有特殊修改过 tunnel 里 proxies 这个东西么，理论上如果从二进制入口进来的话，是不可能造成这个 panic 的

**Comment by wongsyrone** [comment]
tunnel没有修改proxies，只是关掉了统计

**Comment by wongsyrone** [comment]
对Clash的修改只有如下四个commit：

https://github.com/trojan-gfw/clash/commit/e26693ed8835b04d3ef91fb383cd427b50b24773
https://github.com/trojan-gfw/clash/commit/6120b61cac1daa27c0fcc76f3f5139f0d7c9cf84
https://github.com/trojan-gfw/clash/commit/c63963f896aba67683244ca6d37c6f2247944601
https://github.com/trojan-gfw/clash/commit/99a00a28b0dae1065dfcf8a66805e1afd9ee3c9d

**Comment by Dreamacro** [comment]
trojan-gfw@6120b61
trojan-gfw@99a00a2

这俩 patch 好像都没必要了，在最新的 dev 当中

**Comment by wongsyrone** [comment]
哪个dev commit修了吗，没有详细跟，只是根据adb里面panic做的修改

**Comment by Dreamacro** [comment]
这个 panic 是通过 https://github.com/trojan-gfw/igniter/blob/master/app/src/main/res/raw/clash_config.yaml 这个配置复现的么？测试用例在哪能看到？

**Comment by wongsyrone** [comment]
就是这个配置，使用igniter在点击停止的时候抓到的，不过不是100%复现

**Comment by wongsyrone** [comment]
这个配置中的端口号是通过regex匹配修改的，所以一直用的是旧版yaml配置格式。

**Comment by wongsyrone** [comment]
Clash的启停是通过 https://github.com/trojan-gfw/igniter-go-libs/blob/master/clash/clash.go 控制的，近期针对配置文件变化改了一下停止： https://github.com/trojan-gfw/igniter-go-libs/commit/890cee968ff0dfca1f304382839d289943ec8ff9 不过这个不应该导致这个panic呀

**Comment by Dreamacro** [comment]
问题找到了，这里在 stop 的时候是直接使用内部的 Config，导致最终 stop inbound 的时候，在 inbound 停止的时候，proxies 被清空，导致在没有 DIRECT 和 REJECT 的情况下还是处理了请求，最终 panic。可以走内部的 Parse 或者 ParseRawConfig 生成的 Config

而正常二进制并不会走到这一个 Path，所以二进制下是没这个问题的。

**Comment by wongsyrone** [comment]
有没有什么办法在RawConfig和Config之间互转并修改呢，请指教

**Comment by Dreamacro** [comment]
不知道你有没有什么特殊需求，这两个够么

从 yaml 解析
https://github.com/Dreamacro/clash/blob/35449bfa177ecead9d1de05ec74382958540e90b/config/config.go#L132

从 rawConfig 解析
https://github.com/Dreamacro/clash/blob/35449bfa177ecead9d1de05ec74382958540e90b/config/config.go#L174

**Comment by wongsyrone** [comment]
还需要一个修改yaml并序列化的方法，因为要修改General的socks-port和Proxies组里面的port，可以通过yaml.Marshal(RawConfig)实现吗

**Comment by Dreamacro** [comment]
RawConfig 是从 yaml 解析过来的直接对象，Config 是对 RawConfig 进行一次处理后真正被 clash 用到的一些东西

你需要的话两种都可以改，改 RawConfig 就和改 yaml 没太大区别
