### ISSUE TITLE
[help]rule-provider使用问题

### ISSUE THREAD

**Issue by muink** [Dreamacro/clash#828]
@Dreamacro 能帮我看看以下 rule-provider 配置是否正确吗

``` yaml
# classical
payload:
  - DOMAIN,localhost
  - DOMAIN-KEYWORD,localhost. # localhost.wwbizsrv.alibaba.com
  - DOMAIN-SUFFIX,local # ^.+\.local$
  - IP-CIDR,127.0.0.0/8
  - IP-CIDR,192.168.0.0/16
  - IP-CIDR,223.5.5.5/32
  - IP-CIDR6,[::1]/128
  - IP-CIDR6,[fc00::]/7
```

``` yaml
# ipcidr
payload:
  - '192.168.1.0/24'
  - '10.0.0.0.1/32'
  - '[::1]/128'
```

还有再问一下 `no-resolve` 这个选项如何在 rule-provider 配置中使用  
希望作者解惑

**Comment by OUZYcn** [comment]
#===================== OpenClash-Rule-Providers-Set =====================#
  常用隐私规则:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400
  Prime-Video:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/Prime-Video.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/Prime-Video.yaml
    interval: 86400
  国外流媒体合集:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  国外常用网站合集:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400
  国内流媒体国际版合集:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400
  国内域名白名单:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400
  国内IP白名单:
    type: http
    behavior: ipcidr
    path: /etc/openclash/rule_provider/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400
  反劫持规则:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/Hijacking.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    interval: 86400
#===================== OpenClash-Rule-Providers-Set-End =====================#

**Comment by aguero119** [comment]
请问下"GlobalTV"是引用的proxy groups里的"GlobalTV"吗?

**Comment by OUZYcn** [comment]
> 请问下"GlobalTV"是引用的proxy groups里的"GlobalTV"吗?

应该是这个 ： Streaming

**Comment by Mrered** [comment]
请问 `DOMAIN-KEYWORD` 如何在 `behaivor: domain` 里使用？
