### ISSUE TITLE
put / proxies/:name 含emoji 中文，请教下参数需如何处理呢？

### ISSUE THREAD

**Issue by flyhigherpi** [Dreamacro/clash#829]
比如：
pg="GLOBAL"
px="\u1F1ED\u1F1F0 %e9%a6%99%e6%b8%af4"
curl -sv -H "content-type: application/json" -X PUT "http://192.168.2.1:9990/proxies/$pg" -d '{"name": "$px"}'

尝试将emoji转义，中文urlencode，还是报
*   Trying 192.168.2.1:9990...
* Connected to 192.168.2.1 (192.168.2.1) port 9990 (#0)
> PUT /proxies/GLOBAL HTTP/1.1
> Host: 192.168.2.1:9990
> User-Agent: curl/7.69.1
> Accept: */*
> content-type: application/json
> Content-Length: 15
> 
* upload completely sent off: 15 out of 15 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=utf-8
< Vary: Origin
< Date: Thu, 23 Jul 2020 11:46:04 GMT
< Content-Length: 58
< 
{"message":"Selector update error: Proxy does not exist"}
* Connection #0 to host 192.168.2.1 left intact

比如策略组：🌍 国外媒体 
选定节点：🇭🇰 香港4
如何才能更新进去呢

**Comment by Dreamacro** [comment]
你可以尝试了解一下为什么 url 里需要转义，以及为什么 data 传东西的时候不需要转义

**Comment by flyhigherpi** [comment]
> 你可以尝试了解一下为什么 url 里需要转义，以及为什么 data 传东西的时候不需要转义

api这块没有指导教程，我唯一找到的例子是在issue，不过因为他举例的规则是GLOBAL跟japan1，不涉及表情跟中文。我多尝试几种组合吧

**Comment by flyhigherpi** [comment]
问题解决了一半，原来用工具转码，把空格转成了“+” 导致一直报错。
curl -X GET "http://192.168.2.1:9990/proxies/%f0%9f%8d%8e%20%e8%8b%b9%e6%9e%9c%e6%9c%8d%e5%8a%a1" -v
这样获取策略组/节点名 资料成功。
但是PUT的话，咋搞咯，大佬。
我把面板代码拆出来看，没看到这里的名字需要做什么处理。
t.changeProxySelected=function(e,n)
{
    return r(this,void 0,void 0,(function()
    {
        return o(this,(function(r){switch(r.label)
            {
                case 0:
                    return[4,t.getInstance()];
                case 1:
                    return[2,r.sent().put("proxies/"+encodeURIComponent(e),{name:n})]
            }
        }))
    }))
}
name:n

**Comment by flyhigherpi** [comment]
> 你可以尝试了解一下为什么 url 里需要转义，以及为什么 data 传东西的时候不需要转义

curl  -v -H "Content-Type: application/json; charset=utf-8" -X PUT "http://192.168.2.1:9990/proxies/%f0%9f%8d%8e%20%e8%8b%b9%e6%9e%9c%e6%9c%8d%e5%8a%a1" -d '{"name": "🇭🇰 香港1"}'
会报节点不存在。

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash-dashboard/blob/5cb05248a817f8d6af704b19506817a1f9b2c771/src/lib/request.ts#L232

**Comment by flyhigherpi** [comment]
> https://github.com/Dreamacro/clash-dashboard/blob/5cb05248a817f8d6af704b19506817a1f9b2c771/src/lib/request.ts#L232

感谢大佬。看完茅塞顿开，然后原来是路由SSH中文支持不大好，直接执行会报错。写了个test.sh。sh ./test.sh 就能通过了。感谢
