### ISSUE TITLE
[Bug] cipher: chacha20 not supported in latest clash

### ISSUE THREAD

**Issue by isslayne** [Dreamacro/clash#832]
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
{name: 🏳️‍🌈 18:01:56, server: flow.ssr.ac, port: 443, type: ssr, cipher: chacha20, password: breakwall, protocol: auth_chain_a, obfs: tls1.2_ticket_auth, protocol-param: "", obfs-param: ""}
……
```

</details>

### Clash log

```
 time="2020-07-24T18:22:17+08:00" level=fatal msg="Parse config error: Proxy 0: ssr world.cloud:1301 initialize cipher error: cipher not supported"
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
OpenWrt R20.7.20 / LuCI Master (git-20.191.36863-eee6bae)
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

yml配置文件输入加密协议为cipher: chacha20类型协议时，最新支持ssr的clash版本无法启动，log日志显示
 time="2020-07-24T18:22:17+08:00" level=fatal msg="Parse config error: Proxy 0: ssr ********  initialize cipher error: cipher not supported"

**Comment by Dreamacro** [comment]
chacha20 deprecated https://github.com/Dreamacro/clash/releases/tag/v0.17.0
