### ISSUE TITLE
[Bug]对clash软件自身设置proxy

### ISSUE THREAD

**Issue by plybb** [Dreamacro/clash#837]
issue中已经有人提到过“前置代理”“二级代理”，但是各种回答都把问题变得很复杂，如复杂的proxy chains。

**Comment by Fndroid** [comment]
用relay策略组

**Comment by plybb** [comment]
> 用relay策略组

非常感谢你的解答。除了下面这段语句，我还没找到relay更详细的语法说明，如果局域网使用的proxy server是：
ip:port@user:password
那么用relay应该如何使用呢？

proxy-groups:
- name: "select"
  type: select
  proxies:
    - ss1
    - ss2

- name: "relay"
  type: relay
  proxies:
    - select
    - vmess1

**Comment by ddasddd** [comment]
> > 用relay策略组
> 
> 非常感谢你的解答。我还没找到relay策略组更详细的语法说明，如果局域网使用的proxy server是：ip:port@user:password
> 那么relay策略组应该如何使用呢？
> 
> 以下设置经测试无效，不知错在哪里：
> 
> ```
> proxies:
>   - name: "http"
>     type: http
>     server: 局域网使用的代理服务器
>     port: 端口
>     username: username
>     password: password
> 
>  - name: "vmess-http"
>     type: vmess
>     server: server
>     port: 443
>     uuid: uuid
>     alterId: 32
>     cipher: auto
> 
> proxy-groups:
>   - name: "relay"
>     type: relay
>     proxies:
>       - http
>       - vmess
> ```

最后一行`vmess`改成`vmess-http`，proxies里填的是name不是type

**Comment by plybb** [comment]
>    最后一行`vmess`改成`vmess-http`，proxies里填的应该是name不是type
@ghost 非常感谢你的解答。在clash主界面，Proxies菜单已经加载成功，但是General菜单显示“could not connect to clash core”, clash左下显示"Disconnected"。

Logs日志显示如下，看不出错误，再次求助各位： 
`time="2020-07-31T10:45:23+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-07-31T10:45:23+08:00" level=info msg="Mixed(http+socks5) proxy listening at: :7890"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Video"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Auto-Backup"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Auto-Stable"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Auto-Edge"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Auto-Fast"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Auto"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Express"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider relay"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider NETFLIX"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Manual"
time="2020-07-31T10:45:23+08:00" level=info msg="Start initial compatible provider Proxy"
`
