### ISSUE TITLE
openwrt编译

### ISSUE THREAD

**Issue by xh0823** [Dreamacro/clash#838]
openwrt怎么编译到固件里面

**Comment by L0snight** [comment]
openwrt的编译问题和clash有什么关系

**Comment by xh0823** [comment]
是想把clash编译到L的的固件里面，怎么可以编译到里面

**Comment by xh0823** [comment]
> openwrt的编译问题和clash有什么关系

是想直接把clash编译到固件里面

**Comment by OUZYcn** [comment]
可以关闭这个thread了

**Comment by 281677160** [comment]
看你用云编译还是本地编译了，云编译的话，加这个 就搞定 git clone https://github.com/awesome-openwrt/luci-app-openclash package/luci-app-openclash

本地编译的话，应该是 cd package到这个文件夹 然后git clone https://github.com/awesome-openwrt/luci-app-openclash 然后cd .再继续编译吧

这个是clash的，上面是openclash，你要用clash就把连接替换下  https://github.com/frainzy1477/luci-app-clash

**Comment by 281677160** [comment]
有不懂的可以加我QQ281677160一起探讨的
