### ISSUE TITLE
[Bug] Tproxy UDP 出现公网IP回环问题

### ISSUE THREAD

**Issue by ClarkeCheng** [Dreamacro/clash#841]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
secret: ""
external-ui: /ui
ipv6: true
hosts:
dns:
  enable: true
  ipv6: true
  listen: :53
  enhanced-mode: redir-host
  default-nameserver:
    - 223.6.6.6
    - 223.5.5.5
  nameserver:
    - 223.6.6.6
    - 223.5.5.5
  fallback:
    - tls://dns.rubyfish.cn:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
```

</details>

### Clash log

```
# 为保护隐私，具体IP地址已隐去，但我保证 110.X.X.X 就是我获得的唯一一个公网IP
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:43175 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:45461 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:46220 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:60019 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:60926 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:58898 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:33386 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:47944 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:50386 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:51158 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:38119 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:34680 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:34524 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:40830 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:60244 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:48992 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:51814 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:52295 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:51326 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:51946 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:51020 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:45352 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:39182 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:39534 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:49979 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:53878 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:39799 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:34702 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:56976 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:50640 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:48189 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:42477 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:53896 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:41015 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:44360 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:51194 --> 110.X.X.X doesn't match any rule using DIRECT"
time="2020-07-29T06:27:03Z" level=info msg="[UDP] 110.X.X.X:41911 --> 110.X.X.X doesn't match any rule using DIRECT"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
openwrt，clash 通过 docker-compose 运行
* 网路环境或拓扑 (network conditions/topology)
软路由，系统通过 PPPoE 拨号可以获得一个公网IP
* iptables，如果适用 (if applicable)
```
ip rule add fwmark 1 lookup 100
ip route add local default dev lo table 100
iptables -t mangle -N clash
iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN    
iptables -t mangle -A clash -p udp -j TPROXY --on-port 7892 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING -p udp -j clash
```
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
```
# docker-compose.yml
  clash:
    container_name: clash
    image: dreamacro/clash:dev
    cap_add: 
      - NET_ADMIN
      - NET_BIND_SERVICE
    network_mode: host
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    restart: always
```

### 重现问题的具体布骤 Steps to Reproduce

1. 设置好 iptables
2. 在 windows 里 powershell 里执行`nslookup baidu.com 223.6.6.6`

**我预期会发生……？**

powershell 输出解析结果，同时 clash 里有 udp 的日志。

**实际上发生了什么？**

powershell 输出
```
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
```
同时 clash 里日志显示有大量的从公网IP到它自己的连接，而且系统运行变慢。

**Comment by flyhigherpi** [comment]
这个问题困扰了好久，后来通过指定流量入口曲线解决。
                ip rule add fwmark 1 lookup 100
		ip route add local default dev lo table 100
		iptables -t mangle -N merlinclash
		iptables -t mangle -F merlinclash
		#绕过内网
		iptables -t mangle -A merlinclash -d 192.168.0.0/16 -p tcp -j RETURN
		iptables -t mangle -A merlinclash -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
		iptables -t mangle -A merlinclash -d 192.168.0.0/16 -p udp ! --dport 23453 -j RETURN
		iptables -t mangle -A merlinclash -d 10.0.0.0/8 -j RETURN
		iptables -t mangle -A merlinclash -d 0.0.0.0/8 -j RETURN
		iptables -t mangle -A merlinclash -d 127.0.0.0/8 -j RETURN
		iptables -t mangle -A merlinclash -d 169.254.0.0/16 -j RETURN
		iptables -t mangle -A merlinclash -d 172.16.0.0/12 -j RETURN
		iptables -t mangle -A merlinclash -d 224.0.0.0/4 -j RETURN
		iptables -t mangle -A merlinclash -d 240.0.0.0/4 -j RETURN	
		#转发UDP流量到clash端口
		iptables -t mangle -A merlinclash -p udp -j TPROXY --on-port "$proxy_port" --tproxy-mark 0x01/0x01
		#透明代理UDP流量到clash mangle链
		iptables -t mangle -A PREROUTING -p udp -i $bridge -j merlinclash
我觉得关键还是最后一句。
仅供参考

**Comment by ClarkeCheng** [comment]
@flyhigherpi ，我把软路由改为旁路由模式，现在不会获取到公网IP了，iptables 使用和上面一样的话，nslookup 还是超时，而且 clash 里面没有任何 UDP 相关的日志输出。不知道是不是 clash 没收到 iptables 转发过来的数据。然后我又把
```
iptables -t mangle -A PREROUTING -p udp -j clash
```
改为
```
iptables -t mangle -A PREROUTING -p udp -i br-lan -j clash
```
nslookup 还是超时，虽然感谢你的解答，但是问题并没有解决。

**Comment by flyhigherpi** [comment]
> @flyhigherpi ，我把软路由改为旁路由模式，现在不会获取到公网IP了，iptables 使用和上面一样的话，nslookup 还是超时，而且 clash 里面没有任何 UDP 相关的日志输出。不知道是不是 clash 没收到 iptables 转发过来的数据。然后我又把
> 
> ```
> iptables -t mangle -A PREROUTING -p udp -j clash
> ```
> 
> 改为
> 
> ```
> iptables -t mangle -A PREROUTING -p udp -i br-lan -j clash
> ```
> 
> nslookup 还是超时，虽然感谢你的解答，但是问题并没有解决。

旁路油，要指定dns到路由ip吧，我梅林是br0，主路由。设备自定义dns就网络不通。得设为自动或者路由ip

**Comment by ClarkeCheng** [comment]
@flyhigherpi 这不是问题的关键，而且我早就设好了。
![image](https://user-images.githubusercontent.com/17330505/88923230-f929f480-d2a3-11ea-8c84-e4197efc4dc7.png)
问题在于，一执行 `iptables -t mangle -A PREROUTING -p udp -j clash`，就感觉所有 UDP 包都被阻断了，这些包去了哪里，clash 有没有收到，我也不知道。

**Comment by flyhigherpi** [comment]
> @flyhigherpi 这不是问题的关键，而且我早就设好了。
> ![image](https://user-images.githubusercontent.com/17330505/88923230-f929f480-d2a3-11ea-8c84-e4197efc4dc7.png)
> 问题在于，一执行 `iptables -t mangle -A PREROUTING -p udp -j clash`，就感觉所有 UDP 包都被阻断了，这些包去了哪里，clash 有没有收到，我也不知道。

连同FAKEIP的IPTABLES一起贴了。
               iptables -t nat -A PREROUTING -p tcp --dport $ssh_port -j ACCEPT
		#new
		iptables -t nat -N merlinclash
		iptables -t nat -A merlinclash -d 192.168.0.0/16 -j RETURN
		iptables -t nat -A merlinclash -d 10.0.0.0/8 -j RETURN
		iptables -t nat -A merlinclash -d 0.0.0.0/8 -j RETURN
		iptables -t nat -A merlinclash -d 127.0.0.0/8 -j RETURN
		iptables -t nat -A merlinclash -d 169.254.0.0/16 -j RETURN
		iptables -t nat -A merlinclash -d 172.16.0.0/12 -j RETURN
		iptables -t nat -A merlinclash -d 224.0.0.0/4 -j RETURN
		iptables -t nat -A merlinclash -d 240.0.0.0/4 -j RETURN

		#redirect to Clash
		iptables -t nat -A merlinclash -p tcp -j REDIRECT --to-ports $proxy_port
		iptables -t nat -A PREROUTING -p tcp -j merlinclash
		
		
		# fake-ip rules 【这条OUTPUT不能加，一加就回环炸网】
		#iptables -t nat -A OUTPUT -p tcp -d 198.18.0.0/16 -j REDIRECT --to-ports $proxy_port
		#DNS
		iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j DNAT --to-destination $lan_ipaddr:23453	

不过我都是在主路由下运行。旁路由，感觉声明网桥流量入口，可能有点怪，

**Comment by duament** [comment]
需要在 mangle 表绕过公网 IP，具体的话可以在 TPROXY 前加一条：
`iptables -t mangle -A clash -m addrtype --dst-type LOCAL -j RETURN`

**Comment by ClarkeCheng** [comment]
@duament 感谢解答！
