### ISSUE TITLE
[Feature]规则是否支持ipv6, 如何格式填写?

### ISSUE THREAD

**Issue by muink** [Dreamacro/clash#842]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 说明 Description

Clash 规则是否支持添加 IPv6 地址, 如果支持的话以下格式是否正确?

``` yaml
#classical
payload:
  - IP-CIDR,[::1]/128,no-resolve
```
``` yaml
#ip-cidr
payload:
  - '[::1]/128'
```

**Comment by Dreamacro** [comment]
Reference: https://golang.org/pkg/net/#ParseCIDR
