### ISSUE TITLE
目前clash尚不能完全发挥v2ray模块的潜能，建议修改配置方式

### ISSUE THREAD

**Issue by steeltalons1996** [Dreamacro/clash#844]
v2ray的协议不止有vmess这一个，过去可选的还有socks这种不加密，并通过socks+ws+tls取得更好的连接速度
socks+ws+tls详情：https://github.com/v2ray/discussion/issues/513

现在v2ray又出来个新的协议，过去的写个vmess就当v2ray的配置确实不适合了，建议直接增加个inbounds/outbounds参数对协议类型直接进行配置

**Comment by Dreamacro** [comment]
v2ray 是 v2ray, vmess 是 vmess，clash 代码中并没有 import v2ray 的代码，而是实现了 vmess 协议。所以并不存在什么「v2ray 模块」。

v2ray 和 clash 间有着不同的 Design Principles。所以有着不同的配置格式

**Comment by steeltalons1996** [comment]
> v2ray 是 v2ray, vmess 是 vmess，clash 代码中并没有 import v2ray 的代码，而是实现了 vmess 协议。所以并不存在什么「v2ray 模块」。
> 
> v2ray 和 clash 间有着不同的 Design Principles。所以有着不同的配置格式
原来如此，多谢

**Comment by steeltalons1996** [comment]
了解了，多谢
