### ISSUE TITLE
[Bug] ipv6节点bug

### ISSUE THREAD

**Issue by Bitcion** [Dreamacro/clash#847]
测试了一个ipv6地址节点，然后发现检测该节点一直超时，却可以访问多数翻墙资源
但无法代理访问ipv6.Google.com

如果改用该节点的ipv4地址，则正常显示延迟，且可以访问ipv6.google.com

也就是说，如果走v4通道连接节点，且节点支持v4v6，一切正常；但是走v6通道时，能连接节点使用v4代理，但是程序无法检测该节点延迟，且不能访问代理ipv6资源

**Comment by congifly** [comment]
我也有相似的问题，不过是完全无法连接ipv6节点，timeout且无法访问任何网页，两个ipv6选项都设置为true了
