### ISSUE TITLE
[Bug]tolerance选项是否会导致url-test不正常工作

### ISSUE THREAD

**Issue by dumin32** [Dreamacro/clash#851]
url-test 规则中，配置 tolerance 为 30ms（举例）

此时，一组节点刚好都进入缓慢工作状态，url-test 选出了最快的一个节点 X，延迟 2000 ms（矮子中挑高个）

后续所有节点恢复正常速度，这些节点中有更快速的节点 Y 延迟 150 ms，但是由于 X 节点的最新延迟在 1800ms 命中了快于之前的 2000ms + 30 ms 规则就直接返回 X 节点， 于是之后都一直 X 被选中

是否可以增加一个新选项配合，例如 minAcceptable : 200 ms  规定至少要低于 200ms 的才被接受不再一轮 url-test

**Comment by ddasddd** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto

**Comment by dumin32** [comment]
> https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto

我仿佛看了3遍这个文档，没明白你的用意？或许是你没仔细看我的问题？

**Comment by ddasddd** [comment]
> > https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto
> 
> 我反复看了3遍这个文档，没明白你的用意？或许是你没仔细看我的问题？

里面有tolerance的介绍，如果要切换新节点，需要新节点的延迟低于旧节点当前的延迟加上tolerance，否则继续使用旧节点，这个是看新节点的延迟是否达到要求，旧节点延迟只是被比较的值

**Comment by dumin32** [comment]
> 旧

不，反了。

是先比较旧节点的新延迟是否低于旧延迟+tolerance，是的话直接返回上次节点不再进行url-test轮询

所以才会发生我上面说的，如果旧节点的旧延迟是很高的值，就会导致 url-test不再进行，进而持续处于高延迟节点的状态

**Comment by ddasddd** [comment]
> > 旧
> 
> 不，反了。
> 
> 是先比较旧节点的新延迟是否低于旧延迟+tolerance，是的话直接返回上次节点不再进行url-test轮询
> 
> 所以才会发生我上面说的，如果旧节点的旧延迟是很高的值，就会导致 url-test不再进行，进而持续处于高延迟节点的状态

`Clash will only change proxy when the latency of the new Proxy is further below the tolerance plus the current delay of the old one.`
难道我翻译错了，或者说作者写错了

**Comment by ddasddd** [comment]
> > 旧
> 
> 不，反了。
> 
> 是先比较旧节点的新延迟是否低于旧延迟+tolerance，是的话直接返回上次节点不再进行url-test轮询
> 
> 所以才会发生我上面说的，如果旧节点的旧延迟是很高的值，就会导致 url-test不再进行，进而持续处于高延迟节点的状态

而且我刚才试了一下，没出现这个问题

**Comment by ddasddd** [comment]
> > 旧
> 
> 不，反了。
> 
> 是先比较旧节点的新延迟是否低于旧延迟+tolerance，是的话直接返回上次节点不再进行url-test轮询
> 
> 所以才会发生我上面说的，如果旧节点的旧延迟是很高的值，就会导致 url-test不再进行，进而持续处于高延迟节点的状态

应该是我理解错了

**Comment by dumin32** [comment]
不应该用  fast.new_latency < fast.last_latency + tolerance 来决定是否切换节点，这样就受制 last_latency 因素，一旦这个 last_latency 是糟糕的值就垮了

这个判断就应该用  fast.new_latency < conf.acceptable 延迟低于可接受范围，就不再选新的节点

**Comment by dumin32** [comment]
另外，如果配置这种策略，healthyCheck 期望应该只访问上次的 fast 节点先，一旦 fast 节点足够优秀到不需要切换，其他节点就不应该浪费去 url-test 一遍

**Comment by Fndroid** [comment]
感觉确实会有这个问题

**Comment by lifetyper** [comment]
不知道这样的策略行不行：
for new_proxy in all_proxies:
    if new_proxy.latency<(last_proxy.latency-tolerance):
       proxy_pool.add(new_proxy)
return fastest(proxy_pool)

也就是依然对所有节点做url-test然后选最快的，但前提是只有新节点的延迟显著低于旧节点(差值>tolerance),才把它加入这个选取池中。

因为有这样一种情况：
有时后同一地区的代理有好几个，他们之间延迟可能只差几毫秒或者十几毫秒。

我可能更倾向于用ProxyA，因为我觉得ProxyA更稳定，且在大部分时候url-test时都是最快的。

但url-test的结果有时候是有波动的，可能某次url-test中ProxyB比ProxyA快了2ms结果被选中了，但其实它的质量还是不如A。

只有当A的延迟开始出现问题，让B的延迟比A小50或者100ms，我才认为需要切换到B。

**Comment by dumin32** [comment]
楼上你要的跟上上层 @Fndroid #864 调整后的效果是一致的吧？

**Comment by lifetyper** [comment]
> 
> 
> 楼上你要的跟上上层 @Fndroid #864 调整后的效果是一致的吧？

嗯，应该是一样的，似乎已经merge了，看来我直接更新版本就好了。
谢谢。

**Comment by sweihub** [comment]
请问目前版本（clash core 2022.03.21）是怎么处理的，如果如文档所言，那必须要把tolerance设置为负数才有用，不然就会导致频繁的自动切换节点。

**tolerance**
Clash will only change proxy when the latency of the new Proxy is further below the tolerance plus the current delay of the old one. The default value is 0ms, and not necessary.

`new.latency < old.latency + tolerance`

**Comment by Wrandz** [comment]
@sweihub 我觉得是这样的，就是不管之前的延迟是多少，测一遍之后按照现在测的结果，比较最低的值和目前正在用的节点的值，差值大于tolerance，就切换，否则就不换。至于你给的那个公式里面，那个加号我觉得应该是减号。

**Comment by sweihub** [comment]
@Wrandz 文档确实是说"plus"，是加，不是减…… 

> **Tolerance**
> Clash will only change proxy when the latency of the new Proxy is further below the tolerance **plus** the current delay of the old one. The default value is 0ms, and not necessary.
> `new.latency < tolerance + old.latency`

我查看了代码，发现tolerance是一个uint16，无符号整数，所以设置为负数不工作，最佳参数是0.

[adapter/outboundgroup/urltest.go](https://github.com/Dreamacro/clash/blob/02333a859a57ddb528eb469f734ebc2669911ee9/adapter/outboundgroup/urltest.go)

```
func urlTestWithTolerance(tolerance uint16) urlTestOption {
   return func(u *URLTest) {
      u.tolerance = tolerance
   }
}
```

这个比较逻辑是有问题的，假设当前节点延迟是100ms，设置tolerance为50， 然后我发现一个新节点延迟是 110，于是 110 < 50 + 100, 把一个快速节点换到慢速节点上？所以只有设置tolerance为0是目前最佳参数。😁

**Comment by Fndroid** [comment]
@sweihub 上面这个文档并非官方，而且你都找到代码了，为什么不继续看下去呢

https://github.com/Dreamacro/clash/blob/30d4668008b493b65e7d6982b4c43bb34871e13c/adapter/outboundgroup/urltest.go#L91-L94
