### ISSUE TITLE
INFO[0000] Can't find MMDB, start download

### ISSUE THREAD

**Issue by hongyi-zhao** [Dreamacro/clash#854]
Hi,

On Ubuntu 20.04, I completed the building of clash git master version with `go build`. But when I try to start it with my own config file, it stucks at the following stage:
```
$ ./clash -f ../Clash_1596162482.yaml 
INFO[0000] Can't find MMDB, start download
```

I've downloaded the GeoLite2-Country.mmdb file from [here](https://raw.githubusercontent.com/wp-statistics/GeoLite2-Country/master/GeoLite2-Country.mmdb.gz) and put it at the same location where the config file resides. But still I mee the following problem:

```
$ ls -l GeoLite2-Country.mmdb
-rw-r--r-- 1 werner werner 4015582 Feb 12 00:12 GeoLite2-Country.mmdb
$ ./clash -d . -f Clash_1596162482.yaml 
INFO[0000] Can't find MMDB, start download 
```

Any hints for this problem?

Regards
HY

**Comment by Dreamacro** [comment]
should be renamed to "Country.mmdb"

**Comment by hongyi-zhao** [comment]
Thanks a lot. But it seems this version don't support ssr, see the following for more info: 



```
$ ./clash -d . -f Clash_1596162482.yaml 
FATA[0000] Parse config error: Proxy 0: Unsupport proxy type: ssr
```

Any hints for the version supporting ssr on Linux?

**Comment by Dreamacro** [comment]
ssr does not release yet. you can checkout the branch "dev", and build the binary for yourself

**Comment by hongyi-zhao** [comment]
Thanks a lot. It does the trick. Another question: ssr-libev vs this version, which is more efficient?

**Comment by Dreamacro** [comment]
The two applications don’t seem to be of the same. If the C code writing in a better way and includes hardware acceleration, the efficiency is definitely higher than Go

**Comment by hongyi-zhao** [comment]
I‘ve done some basic testings and found that the exactly as you said, ssr-libev shows an overwhelming performance advantage.

**Comment by Dreamacro** [comment]
sounds interesting. According to my knowledge, there shouldn't be many gaps between them.

**Comment by Dreamacro** [comment]
@hongyi-zhao Can you provider how you test and the benchmark?

**Comment by hongyi-zhao** [comment]
Setting a load-balancer, listening on a specific local port, with multiple ssr-libev servers as the upstream in haproxy's layer 4/tcp mode. Set the clash accordingly. Then testing them by downloading the same large file via the local proxies supplied by haproxy and clash.

**Comment by Dreamacro** [comment]
In your tests, what's the result of throughput and CPU load?

**Comment by hongyi-zhao** [comment]
I suspect there maybe some dns problem for my case that affect the testings result. Let me do some further check before feedback.

**Comment by liu-xuewen** [comment]
+1

**Comment by qslia** [comment]
How you fixed this problem?

**Comment by cdw200806** [comment]
+1

**Comment by cucdengjunli** [comment]
+1

**Comment by cdw200806** [comment]
ご連絡、ありがとうございます。これからもよろしくお願いします。

**Comment by cryacry** [comment]
![image](https://github.com/Dreamacro/clash/assets/73230634/f438253b-1e09-4e9b-9dd9-058ab563e6ec)

**Comment by cdw200806** [comment]
ご連絡、ありがとうございます。これからもよろしくお願いします。

**Comment by william20210206** [comment]
以root身份运行一次后会他会在/root/config/下自动建立clash目录，需要把country.mmdb和config文件复制一份放入这个目录里，就不会报找不到这两个文件了

**Comment by william20210206** [comment]
> 以root身份运行一次后会他会在/root/config/下自动建立clash目录，需要把country.mmdb和config.yml文件复制一份放入这个目录里，就不会报找不到这两个文件了

如果用其他身份同样的道理，不同身份调用需要在对应身份/config/clash目录下添加country.mmdb和config.yml文件
