### ISSUE TITLE
"Load balance" type for proxy group

### ISSUE THREAD

**Issue by 599316527** [Dreamacro/clash#86]
```yaml
'Proxy Group':
    - { name: xxxx, type: loadbalance, strategy: uri, _____________ }
```

Strategy: [uri](http://cbonte.github.io/haproxy-dconv/1.9/configuration.html#4-balance) <- ensures that the same URI will always be directed to the same server as long as no server goes up or down.

**Comment by Dreamacro** [comment]
这个 type 现在初步的想法是使用 `jump consistent hash`, 有什么更好的建议吗

**Comment by 599316527** [comment]
同时希望 load balance 能够统计使用状态，根据不同节点的延迟、速度分权重地命中。
这样的话，通过为速度快、延迟低的节点多分配几个位置，也可以用 jump consistent hash 来搞

**Comment by Dreamacro** [comment]
现在有个实验性的 release，你可以先看看

**Comment by lushann** [comment]
为什么 我使用load balance   proxy group 的时候，只会使用group里的第二个节点，实测两个节点都是可用的

**Comment by Dreamacro** [comment]
@lushann 两个太少了，最起码 10 个负载均衡才能达到一个比较好的效果

**Comment by qzi** [comment]
最近测试似乎proxy groups 里面 load-balance 策略会导致udp 请求io timeout，也不知道是不是因为节点够多，我在想如果10个节点根据eltd来balance，那如果超过10个顶级域名之后是怎么处理
