### ISSUE TITLE
[Feature] url-test与load-balance策略组未被引用时不自动进行延迟测试

### ISSUE THREAD

**Issue by System-Warning** [Dreamacro/clash#860]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ✓] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

### 说明 Description

url-test与load-balance策略组未被引用时仍然自动进行延迟测试，造成资源浪费。

### 可能的解决方案 Possible Solution

1. 建议只有策略组被引用时自动进行延迟测试，策略组没有被引用时不自动进行延迟测试。

2. 手动控制是否自动进行延迟测试。

**Comment by alexlee728** [comment]
遇到同样问题

**Comment by akw5454521** [comment]
支持这个建议，最好能作为一个true/false参数，根据配置文件来决定是在被选中时才测试还是一直会测试

**Comment by Dreamacro** [comment]
0402878daa904cc4c47cb459ff5b65168b864efc 所有的 group 和 provider 支持了「如果在周期内没被使用过，则不进行健康检查」，并默认打开
