### ISSUE TITLE
[Feature] Lacking "none" cipher in SSR support

### ISSUE THREAD

**Issue by Anankke** [Dreamacro/clash#865]
In #805 we got long-awaited SSR protocol support by @goomadao. While it's a real step forward for Clash, this great pull request, however, lacking an indispensable cipher "**_none_**." 

It's not a hard implementing feature, and in fact, #805 brings  [ "**_none_**" support](https://github.com/Dreamacro/clash/pull/805/files/1ecc41b1061a9319ba6a67494b0ee33e1676afa6#diff-39dc59119f43de1f6fad1f840fc3a33a) in the first place, which later was [removed](https://github.com/Dreamacro/clash/pull/805/commits/fe1f1a3d3e138534427cd16ed5e1b4ef9b1fec9b#diff-39dc59119f43de1f6fad1f840fc3a33a), and here follows the [review](https://github.com/Dreamacro/clash/pull/805#discussion_r458551793).

Code reuse is excellent if it keeps implemented features, and @goomadao [mentioned](https://github.com/Dreamacro/clash/pull/805#discussion_r458813788) "**_none_**" will be reimplemented if "needed," which derives this feature request that  "**_none_**" **IS** part of SSR protocol, vitally needed and should be brought up.

Again, thanks for the respectable work by @goomadao, and hoping "**_none_**" could be back soon™.

**Comment by Anankke** [comment]
PS:
![image](https://user-images.githubusercontent.com/40639066/89212301-38e92880-d591-11ea-96ed-c923e41fabda.png)
![image](https://user-images.githubusercontent.com/40639066/89212345-47cfdb00-d591-11ea-8ab5-0a2c5d928f5d.png)
![image](https://user-images.githubusercontent.com/40639066/89212376-53bb9d00-d591-11ea-8231-ee86e8840d14.png)
![image](https://user-images.githubusercontent.com/40639066/89212399-5ae2ab00-d591-11ea-880b-485beb3bd724.png)

#PrO_tIpS thanks

**Comment by NimaQu** [comment]
#make_ssr_intact_again

**Comment by sdjnmxd** [comment]
+1

for some special reasons, only SSR nodes whose encryption method is none are provided. I hope this function can be realized. Thanks to the developers

**Comment by aloneshepherd** [comment]
+1

for some special reasons, only SSR nodes whose encryption method is none are provided. I hope this function can be realized. Thanks to the developers

**Comment by CaliInn-Li** [comment]
+1

for some special reasons, only SSR nodes whose encryption method is none are provided. I hope this function can be realized. Thanks to the developers

**Comment by dukh1216** [comment]
+1

for some special reasons, only SSR nodes whose encryption method is none are provided. I hope this function can be realized. Thanks to the developers

**Comment by CoderTonyChan** [comment]
还是有人用none的 如果支持不填是不是可以解决？@Dreamacro

**Comment by bigbaldy1128** [comment]
@Dreamacro 我买的机场cipher也是none,没法使用，郁闷啊，这个功能什么时候能加呀？这都2021年了，是不是作者不打算做了?

**Comment by pompeyY** [comment]
现在还是没有吗？ 还是说有其他方案代替了哇  问题没解决怎么就关啦

**Comment by pompeyY** [comment]
貌似已经支持了  把none改成 dummy就可以了
