### ISSUE TITLE
Ubuntu16.04安装失败Parse config error: ProxyGroup Proxy: 'proxies' is not a slice`

### ISSUE THREAD

**Issue by yzg9353** [Dreamacro/clash#871]
`$ ./clash -d .
FATA[0000] Parse config error: ProxyGroup Proxy: 'proxies' is not a slice`
听说需要删除多余的配置,但是我需要如何找到多余的配置呢？

**Comment by Mr-Sheep** [comment]
你的配置有問題，檢查你的配置
#509 #320
