### ISSUE TITLE
请问现在使用vmess支持多路复用吗？

### ISSUE THREAD

**Issue by XuuKoo** [Dreamacro/clash#876]
在配置样例里，ss协议的v2 plugin下有mux参数，而vmess协议下却没有给出。
我尝试在vmess下增加mux: true，加载配置文件没有报错，但似乎看起来并不起作用。
请问vmess协议是否也支持mux多路复用？

**Comment by Shangbaize-Daoye** [comment]
如果你的客户端服务器端都是用v2ray-core，那无论socks、vmess、vless都是可以用mux的。但是clash我记得并没有为vmess实现mux，而且未来也不打算实现mux。毕竟clash设计理念不同。clash只是重新实现了vmess协议，没有直接用v2ray-core。

如果想用mux，还是换使用v2ray-core开发的客户端吧。比如Qv2ray。

**Comment by XuuKoo** [comment]
> 
> 
> 如果你的客户端服务器端都是用v2ray-core，那无论socks、vmess、vless都是可以用mux的。但是clash我记得并没有为vmess实现mux，而且未来也不打算实现mux。毕竟clash设计理念不同。clash只是重新实现了vmess协议，没有直接用v2ray-core。
> 
> 如果想用mux，还是换使用v2ray-core开发的客户端吧。比如Qv2ray。

感谢回复。

主要是clash的分流规则很好用，而且与其他的平台的app比如小火箭、quanx这些基本通用。qv2ray的路由规则单独一个体系，而且编辑也十分不便。

**Comment by U-v-U** [comment]
@XuuKoo Qv2ray 使用的是 V2Ray-Core 的路由体系，不存在所谓 “单独一个体系”

**Comment by XuuKoo** [comment]
> 
> 
> @XuuKoo Qv2ray 使用的是 V2Ray-Core 的路由体系，不存在所谓 “单独一个体系”

和clash、小火箭、quanx这些比 就是另一个体系了

**Comment by U-v-U** [comment]
V2Ray 不是 Clash,小火箭不是 V2Ray, Qx 也不是 V2Ray
我不认为核心和 GUI 能相比
