### ISSUE TITLE
Some problems on the loadbalance algorithm implemented in the current clash dev branch.

### ISSUE THREAD

**Issue by hongyi-zhao** [Dreamacro/clash#881]
Hi,

I use the git dev branch of clash for ssr supporting. For my case, I use more than 80 upstreams in the yaml file. But it seems that clash only support several upstreams ( ~ 6 ) in the loadbalancing queue. I'm not sure whether this is true or not.

Furthermore, what's the load balance algorithm implemented currently for clash? I want to know whether I can let clash stick to a specific upstream during the whole duration of a tcp-session. 

 Best regards

**Comment by Dreamacro** [comment]
> Furthermore, what's the load balance algorithm implemented currently for clash?

murmur3 with jump consistent hash

A large number of upstream servers is not recommended, but there is no limit to it

**Comment by hongyi-zhao** [comment]
Thanks a lot for your comments. But I still don't how to let clash stick to the same upstream during the whole tcp session. Any hints?

**Comment by Dreamacro** [comment]
@hongyi-zhao base on eTLD https://en.wikipedia.org/wiki/Public_Suffix_List, and fallback to IP when no hostname

**Comment by hongyi-zhao** [comment]
> @hongyi-zhao base on eTLD https://en.wikipedia.org/wiki/Public_Suffix_List, and fallback to IP when no hostname

I still can't figure out what's the relationship between the eTLD and the problem I want to solve. Any more hints?
