### ISSUE TITLE
[Bug] i686 SIGILL

### ISSUE THREAD

**Issue by mochaaP** [Dreamacro/clash#883]
------------------------------------------------------------------

### Clash config

不适用

### Clash log

不适用

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
- [Archlinux32](https://archlinux32.org)
- `Linux 5.7.10-zen1-1.0-zen-zen #1 ZEN SMP PREEMPT Fri, 24 Jul 2020 05:52:14 +0000 i686 unknown unknown GNU/Linux`

<details>
  <summary>/proc/cpuinfo</summary>

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 11
model name	: Mobile Intel(R) Pentium(R) III CPU - M  1200MHz
stepping	: 4
microcode	: 0x2
cpu MHz		: 1200.000
cache size	: 512 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 2
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 sep mtrr pge mca cmov pse36 mmx fxsr sse cpuid
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 2397.74
clflush size	: 32
cache_alignment	: 32
address sizes	: 36 bits physical, 32 bits virtual
power management:
```
</details>

### 重现问题的具体布骤 Steps to Reproduce

1. 新建一个 i686 架构的机器
2. 从 Release 下载任意 linux-386 二进制（Premium 或 CI）
3. 执行

**我预期会发生……？**

```
INFO[0000] Can't find config, create a initial config file
INFO[0000] Can't find MMDB, start download
```

**实际上发生了什么？**

```
“./clash-linux-386-2020.06.27” terminated by signal SIGILL (Illegal instruction)
```

### 更多信息 More Information
来自 Archlinux32 官方源构建的版本正常执行。

**Comment by Kr328** [comment]
https://golang.org/doc/go1.15#386

Golang 1.15 386 需要使用 SSE2 指令集

**Comment by mochaaP** [comment]
Closing.
