### ISSUE TITLE
[问题] Fake-ip mode的 DNS cache hit/miss rate

### ISSUE THREAD

**Issue by OUZYcn** [Dreamacro/clash#888]
**确定认知一致性，**
信息依据：[**Unofficial** Clash Wiki的DNS章节.](https://lancellc.gitbook.io/clash/clash-config-file/dns)
1. default-nameserver(Optional) 因为是可选，依据我的需求，也没设置。
2.  使用`fake-ip` mode，因此Clash会向客户机反馈一个fake-ip，于此同时**并行**向所设定的name server发出查询，并取得返回最快的一个结果。 当TTL到期，Clash会自动执行相同查询动作。 
3. 网络中存在：客户机 ， pfSense（PPPoE\FW\DHCPd）、openwrt（Clash）

**我的问题：**
1. 貌似由于Fake-ip模式的机制问题，客户机的DNS必须是Clash？
1.1 若不然，客户机- - pfSense（DNS:53, upstream:Clash）-- Clash (internet DNS)方式下。 客户机查询`www.baidu.com`拿到的IP是错误的，如果没有记错是OpenWRT IP地址。 接下来浏览器按照这个解析IP地址访问就是错误的了。 
2. 如果pfSense当作DNSd的话，我可以通过Telegraf将包括DNS有关的hit/miss数据传到InfluxDB，再通过Grafana生成图表。
2.1 但是现在是Clash完成DNS解析，那就想知道几个问题：
a. Clash的DNS 是有Cache的吧？缓存了fake-ip -- DNS A/AAA的hash table？
b. 有无方法知道类似如下数据？
```
total.num.queries=2812
total.num.queries_ip_ratelimited=0
total.num.cachehits=1749
total.num.cachemiss=1063
total.num.prefetch=107
total.num.expired=100
total.num.recursivereplies=1063
```
c. TTL到期且未有客户机再次访问该域名域名，也是自动再查询？
`Once the DNS expiration date **expires**, Clash still returns the same false IP to the client. At the same time, Clash requests the parsing results again upstream to re-establish the correspondence.`

d. Clash 的DNS是否支持同类DNS的设定，例如控制TTL、DNSSEC等，pfSense是可以的。

网络环境示意图：
![home networking](https://user-images.githubusercontent.com/47710598/89860070-1aa8ab80-dbd5-11ea-863b-872ad0e53be0.png)

**Comment by OUZYcn** [comment]
@Dreamacro 可否看看？

**Comment by Dreamacro** [comment]
1. 所有 dns 的入口点必须是 clash，否则会丢失域名数据
2. 没有采集器 (scrapers)
3. TTL 到期先返回记录，异步更新记录
4. 没有，有特殊需要自己开一个 dns server，clash 的 nameserver 写自己的上游 dns

**Comment by OUZYcn** [comment]
> * 所有 dns 的入口点必须是 clash，否则会丢失域名数据
> * 没有采集器 (scrapers)，fake dns 是 1000 长度的 LRU
> * TTL 到期先返回记录，异步更新记录
> * 没有，有特殊需要自己开一个 dns server，clash 的 nameserver 写自己的上游 dns

1. 这点已经了解清楚了。
2. changelog中查到了LRU cache algos，这1000是1000个dns hashmap记录？
3. 了解
4. 开个default-nameserver？支持上述的hit/miss查询吗？
