### ISSUE TITLE
[Feature] Has both the subscription's nodes and my own nodes at the same time.

### ISSUE THREAD

**Issue by yangxyo** [Dreamacro/clash#890]
- [x] I have searched on the [issue tracker](……/) before creating the issue.

There are similar issues like mine, but this is a clearer one.

------------------------------------------------------------------

Today I meet [clashX](https://github.com/yichengchen/clashX) it has one more subscription function than SS-NG. I love it.

I added a subscription and my own nodes, then, saved it, but when I update the subscription, my own nodes all gone.

Is there a way to achive it that has both the subscription's nodes and my own nodes at the same time?

@yichengchen

**Comment by yichengchen** [comment]
If you use subscription, it will override your config during update. If you want to have your own setting, It's better to use proxy-providers [wiki](https://github.com/Dreamacro/clash/wiki/configuration) to get subscription proxies, then write your own config.

btw, your subscription can be use as a proxy-providers link directly

**Comment by yangxyo** [comment]
Oh, I may didn't consider it clearly at that time. Thanks.
