### ISSUE TITLE
华硕GT-AC5300要下载哪个固件

### ISSUE THREAD

**Issue by haihang5000** [Dreamacro/clash#891]
第一次接触clash.我路由器是华硕GT-AC5300。刷了梅林固件版本：3.0.0.4.384_81974_koolshare.
我想安装.查了教程都没有我这个的。uname -a。得出Linux GT-AC5300-E210 4.1.27 #2 SMP PREEMPT Tue Jul 28 22:32:28 CST 2020 aarch64 Merlin-Koolshare-5300rog
aarch64.这个是要下载哪个。请帮忙。谢谢

**Comment by OUZYcn** [comment]
[AArch64 - ARM - WikiChip](https://en.wikichip.org/wiki/arm/aarch64)
AArch64 is the 64-bit execution state of the **ARMv8** ISA

你能搜索到这里，但是咋不再继续搜索。。。
clash-linux-armv8-v1.0.0.gz

**Comment by haihang5000** [comment]
> [AArch64-ARM-WikiChip](https://en.wikichip.org/wiki/arm/aarch64)
> AArch64是**ARMv8** ISA 的64位执行状态
> 
> 你能搜索到这里，但是咋不再继续搜索。。。。
> clash-linux-armv8-v1.0.0.gz

感謝你的解答。。我也是找不到。。谢谢。。
