### ISSUE TITLE
[Bug]ClashX控制台界面加载不出来，显示空白

### ISSUE THREAD

**Issue by miteasy** [Dreamacro/clash#892]
ClashX项目没有开放Issue功能，但我看到你也在ClashX项目成员当中。
我不是开发，也不懂开发，所以在这里提出bug。
使用的系统是Mac 10.15.6 (19G73)，从10.14升级到该版本操作系统之后。
打开运行ClashX 1.30.1，出现控制台加载不出来，白板的现象。
尝试装重装和重装其他版本无效。

如下图所示
![Xnip2020-08-12_03-03-24](https://user-images.githubusercontent.com/18578249/89938065-8d06a380-dc48-11ea-8461-da5fa3daab5f.jpg)

**Comment by Edogawa-Konan** [comment]
I encountered the same problem. When using the global mode, the display is blank, and it is normal to switch to the regular mode.

**Comment by Xheldon** [comment]
> I encountered the same problem. When using the global mode, the display is blank, and it is normal to switch to the regular mode.

+1

**Comment by Dreamacro** [comment]
@Edogawa-Konan @Xheldon will fix on next clashx release

**Comment by trennble** [comment]
not fix till now 😳

**Comment by Dreamacro** [comment]
@yichengchen /cc

**Comment by yichengchen** [comment]
@trennble Does the issue still occurs with the latest clashx/clashx pro? try to use the following command then restart clashx.
```
defaults delete com.west2online.ClashX
defaults delete com.west2online.ClashXPro
```
