### ISSUE TITLE
[Feature]希望能为 订阅/规则 的更新提供 前置代理/使用代理进行更新选项 

### ISSUE THREAD

**Issue by muink** [Dreamacro/clash#898]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

### 说明 Description

**gfw** 已经开始封锁使用 **tls1.3** 和 **esni** 的域名了，以直连的方式更新规则变得十分困难(比如 `gitlab.com/user/repo/-/raw/rule.yaml`)
而 **tls1.2** 的 `raw.githubusercontent.com` 一直都处于间歇性sni阻断的情况

希望能为规则的更新添加前置代理的选项，帮助快速更新规则/订阅
或为规则的更新保留至少一个驻留代理节点，并使用此类节点进行 规则/订阅 更新

**Comment by steeltalons1996** [comment]
这个大概要去找开发gui那边的，这边只是一个内核

另外既然有代理，可以考虑直接用代理服务器作为订阅地址

**Comment by muink** [comment]
> 这个大概要去找开发gui那边的，这边只是一个内核
> 
> 另外既然有代理，可以考虑直接用代理服务器作为订阅地址

cfw那边说是core的问题，我就来这里问了，这不又回去了么XD

**Comment by steeltalons1996** [comment]
好吧，我想当然了

不过就算加了这个功能对于初次订阅的人也没作用啊，cfw还能拖配置，安卓端只能手动导入手机文件了。有种太阳能手电筒的感觉

还是建议直接用代理服务器配置订阅比较好

**Comment by phlinhng** [comment]
我現在是使用 [FastGit](https://fastgit.org/) 項目的 `raw.fastgit.org` 來代替 `raw.githubusercontent.com`，暫時能解決這個問題。

**Comment by kery** [comment]
个人感觉实现这个Feature还是有用的，比如我在公司内使用Clash，所有流量都要经过一个HTTP代理服务器，如果没这个功能则无法获取rule-provider。

我没看过相关代码，按我的理解，在Clash启动时，可以按照rule去决定使用哪个outbound获取rule-provider。当然，在获取到之前，所有使用RULE-SET的规则不起作用而已（RULE-SET为空）。这样实现应该没什么副作用。
