### ISSUE TITLE
ipip.net 访问时出现错误日志

### ISSUE THREAD

**Issue by Tsahao** [Dreamacro/clash#9]
网站能正常打开，但是有错误日志：
`[warning] Proxy connect error: dial tcp: lookup xpxjhw6j24w8s6md.skt.ipip.net: no such host`

**Comment by Dreamacro** [comment]
这个问题不是 clash 的问题，在不开代理的情况下，访问 `ipip.net` 在控制台中也会有 `Failed to load resource` 的问题
