### ISSUE TITLE
[Feature] 关于tproxy的优化方案 

### ISSUE THREAD

**Issue by junknet** [Dreamacro/clash#901]
问题: tproxy模式下,代理本机流量如何防止 流量回环  例如 [#555](https://github.com/Dreamacro/clash/issues/555#issue-575239412)

目前解决方法: `iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner clash -j REDIRECT --to-port 7892` 
 此方法通过以clash用户启动服务的方法,iptables 区别出非clash用户流量重定向到tproxy端口

改良方案:
clash对公网发起连接时,设置 SO_MARK,同时配置文件增加so_mark 参数
```c
// 假设mark为0xff
mark = 255;
setsockopt(client_socket, SOL_SOCKET, SO_MARK, &mark, sizeof(mark));
```  
后续就可以利用iptables -m mark 0xff -j reutrn  优雅的放行clash发送的流量
(以上操作参考v2ray的实现

**Comment by cjwddtc** [comment]
很久以前有人提过这个事情，当时开发者（我我甚至都忘记是不是开发者了）认为uid的方式更好，理由是SO_MARK不跨平台。这样更符合设计。

**Comment by elonzh** [comment]
见　https://github.com/Dreamacro/clash/issues/158#issuecomment-489432691

**Comment by junknet** [comment]
确实，uid能更好的跨平台..
