### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ch-boogeyman** [Dreamacro/clash#906]
### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
win10
* 其他 (any other information that would be useful)
电脑装了360

system proxy开关经常会自动关闭，要手动重新开启，1小时内一般就会关闭一次。
求解决方案？
![0](https://user-images.githubusercontent.com/46711557/90505665-97afc400-e185-11ea-85de-befbd9d24cdd.png)

**Comment by GrayXu** [comment]
[系统代理自动关闭或打开 #312 Clash For Windows](https://github.com/Fndroid/clash_for_windows_pkg/issues/312)

**Comment by ch-boogeyman** [comment]
> [系统代理自动关闭或打开 #312 Clash For Windows](https://github.com/Fndroid/clash_for_windows_pkg/issues/312)

万万没想到是看图王的广告程序搞的鬼
![修改代理](https://user-images.githubusercontent.com/46711557/90712321-58908880-e2d5-11ea-95c0-f97008541988.png)
