### ISSUE TITLE
[Bug] Can't generate C header file for Mac OS when built it to a static library (*.a file)

### ISSUE THREAD

**Issue by hadkins1** [Dreamacro/clash#907]
Compile directive followed:
go build -buildmode=c-shared -ldflags="-s -w" -o goClash.a

Please tell me that is there any problem?  Looking forward to your reply.  Wish you happiness in work!
Thank you!

**Comment by Dreamacro** [comment]
reference: https://github.com/yichengchen/clashX/blob/master/ClashX/goClash/build_clash.py

**Comment by hadkins1** [comment]
> reference: https://github.com/yichengchen/clashX/blob/master/ClashX/goClash/build_clash.py

Thank you for your reply! You save my day.
