### ISSUE TITLE
[Feature] Add system dns entry in DNS section of the config

### ISSUE THREAD

**Issue by Utaea** [Dreamacro/clash#908]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
不适用
* 使用者的操作系统 (the OS running on the client)
不适用
* 网路环境或拓扑 (network conditions/topology)
不适用
* iptables，如果适用 (if applicable)
不适用
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
有
* 其他
……

### 说明 Description
Clash have implemented a built-in DNS server which is good for anti-DNS pollution. We're happy that we can specify the upstream DNS server for querying. But when speaking of subscription(config) distribution, we found that single DNS template could not achieve the best experience for all the users.

For example, when we added these lines to our configs
```jsonc
"dns": {
            "enable": true,
            "listen": "127.0.0.1:5533",
            "ipv6": true,

            "default-nameserver": [
                "223.5.5.5",
                "8.8.8.8"
            ],
            "nameserver": [
                "223.5.5.5",
                "8.8.8.8",
                "https://1.1.1.1/dns-query"
            ],
            // ...
}
```
And distribute to our users. Let's assume that the DNS server is deployed only in Los Angeles. User Alice who lives in LA may find it very efficient for the nameserver is geographically close to her location and she can get the best DNS query result for CDN. But user Ben who lives in New York may feels a little bit annoyed for he sometimes gets the IP which is originated from Los Angeles instead of New York.

Since the DNS provided by ISP is the most CDN friendly, I'm wondering if Clash could add a special entry to the `nameserver` of DNS section so that when the app initiate a DNS request, not only will Clash send requests to the DNS nameserver specified in the config but also send the requersts to the System DNS Server (or something like `getaddrinfo()`?)

中文
就像 Clash for Android 有个选项是追加系统 DNS 到 Clash 配置文件中那样，Clash 可不可以设置一个特殊的 DNS 服务器字段来表示让 Clash 去向系统 DNS 发起请求

现阶段 Clash 如果要开启内置 DNS 服务器的话就只能写死上游 DNS 服务器，然而如果上游 DNS 出口不在用户归属地就会出现 CDN 返回的是 DNS 出口所在的地区 IP 而非用户所在 DNS 的现象，因为系统 DNS 一般都是由 ISP 提供，他们的 DNS 对 CDN 应该是最友好的

就比如上面的那个配置文件，假定我们把这个字段设置为 `system_dns`，然后修改上面的配置文件为如下
<pre lang="jsonc">
"dns": {
            "enable": true,
            "listen": "127.0.0.1:5533",
            "ipv6": true,

            "default-nameserver": [
                "223.5.5.5",
                "8.8.8.8"
            ],
            "nameserver": [
                <i>"system_dns",</i>
                "223.5.5.5",
                "8.8.8.8",
                "https://1.1.1.1/dns-query"
            ],
            // ...
}
</pre>
或者设置一个单独的开关
<pre lang="jsonc">
"dns": {
            "enable": true,
            "listen": "127.0.0.1:5533",
            "ipv6": true,
            <i>"system-dns": true,</i>
            "default-nameserver": [
                "223.5.5.5",
                "8.8.8.8"
            ],
            "nameserver": [
                "223.5.5.5",
                "8.8.8.8",
                "https://1.1.1.1/dns-query"
            ],
            // ...
}
</pre>

而后 Clash 在收到 DNS 查询请求的时候就不光会向 223.5.5.5, 8.8.8.8, 1.1.1.1 发送请求，还会向系统 DNS 发起请求，个人觉得这可以靠类似于调用 `getaddrinfo()` 来实现这个功能？

这样，在分发配置文件（订阅）的时候就只需要设置一个无污染 fallback DNS 服务器即可，`nameserver` 段完全可由系统 DNS 负责解析或者在系统 DNS 之上再增加一两个 DNS 用于备用。

### 可能的解决方案 Possible Solution

增加一个特殊的配置选项用于依赖系统 DNS 进行解析

**Comment by NyaMisty** [comment]
This should be reopened!
