### ISSUE TITLE
[Bug] Pulse Secure 可以导致 Clash Core 崩溃.

### ISSUE THREAD

**Issue by lotusired** [Dreamacro/clash#911]
------------------------------------------------------------------

### Clash config
和 config 无关.

### Clash log

1. 正确读取了 Config 上的分组信息;
2. 提示正在监听 7890, 9090, 7891 端口;
3. 没有报错;
4. 之后不再滚动.

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows 10 (2004)
* 网路环境或拓扑 (network conditions/topology)
Ethernet
* iptables，如果适用 (if applicable)
Not applicable
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
No.
* 其他 (any other information that would be useful)
可以在纯净的虚拟机环境里用 Clash-CLI 复现, 确保不是别的软件冲突, 系统特殊设置, 或者 CFW 的问题.

### 说明 Description

Clash 和 Pulse Secure 会发生冲突, 从而导致 Clash Core 崩溃, 且重启软件不可修复, 必须重启操作系统.

### 重现问题的具体布骤 Steps to Reproduce

1. 启动 Clash 并启动系统代理;
2. 启动 Pulse Secure, 启动连接, 切断连接;
3. Clash 崩溃. 在重启操作系统前无法启动. 

**我预期会发生……？**

我明白先启动 Clash 再启动 Pulse Secure 的方法是错误的. 但是, 理论上在我关闭 Pulse Secure 和 Clash 之后应该可以重启 Clash...

**实际上发生了什么？**

...但是实际上不能. Clash 会监听 9090, 7890, 但是其实 Core 并没有运行起来.

### 可能的解决方案 Possible Solution

我在关闭 Pulse Secure 和 Clash 之后, 恢复了一次备份的注册表, 恢复了一遍网卡, 都没有用.

### 更多信息 More Information

我并不需要解决这个问题. 我完全可以让用户不要同时使用 pulse secure 和 clash, 但是这个诡异的 bug 也许能给开发者一些启发.
感谢!

**Comment by malone6** [comment]
这个问题能得到解决吗，是不是只能使用一个之前保证另一个提前退出？
