### ISSUE TITLE
[Feature] Option to redirect HTTP to HTTPS connections

### ISSUE THREAD

**Issue by emlimap** [Dreamacro/clash#915]
- [x] I have searched on the [issue tracker](……/) before creating the issue.

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Linux
* 使用者的操作系统 (the OS running on the client)
Ubuntu 20.04
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
No
* 其他
……

### 说明 Description
There are some apps which seem to connect over HTTP even though HTTPS is available. For example, video streaming apps stream video content over HTTP. This exposes a lot more information about user's viewing habits to their ISP and anyone in between.

Unfortunately it is hard to get them to redirect as a user. The only way possible is to get app developers to fix it on their own end but that isn't always successful.

### 可能的解决方案 Possible Solution

One solution is to potentially do an HTTP 301/302 redirect on those requests forcing client to connect over HTTPS. Similar to what HTTPS Everywhere extension for Chrome & Firefox does. This is something you can do with redirect option in Privoxy.

Other solution would be is to keep HTTP between client & clash but clash would in turn make HTTPS to server but this is complex. This might involve more work and load on clash.

The domains can be defined by user under rules. So it would look something like below for example.

```yaml
rules:
    - HTTPS-REDIRECT, example.com, proxy
```

**Comment by emlimap** [comment]
Thank you for the update and also for the program.

As a workaround, I have found another simple proxy (https://github.com/yeokm1/http-to-https-proxy) which I can use to do the HTTP to HTTPS proxying. Although the proxy does the HTTPS connection rather than doing the HTTP redirect.

So for connections that require HTTPS redirection, the connection would look like

Client -> Clash -> HTTP to HTTPS Proxy -> Server

For now this solution works for me.

**Comment by Dreamacro** [comment]
https://github.com/yeokm1/http-to-https-proxy only affects HTTP proxy. It's limited. clash support multi inbound and need MitM to redirect HTTP to HTTPS. I still think clash shouldn't do this without MitM.

**Comment by emlimap** [comment]
I totally agree. It should be part of MITM. Makes it easier to do HTTPS redirection and other things in the future. I was just trying it out as a workaround until clash implements it natively. 

I have been experimenting with setting Clash to proxy to Privoxy for URL's that needs HTTP to HTTPS redirection. One thing I noticed was that when clash is in the middle the redirect doesn't happen. Is this expected behaviour because of chaining proxies? It seems privoxy has some sort of fail-safe where it lets the HTTP through if a redirect fails.

Curl to example.com with proxy to Privoxy directly. Can see the request being redirected to HTTPS.
```
# curl -x "http://127.0.0.1:8118" -v http://example.com
* Expire in 0 ms for 6 (transfer 0x55b710387f50)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55b710387f50)
* Connected to 127.0.0.1 (127.0.0.1) port 8118 (#0)
> GET http://example.com/ HTTP/1.1
> Host: example.com
> User-Agent: curl/7.64.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 302 Local Redirect from Privoxy
< Location: https://example.com/
< Content-Length: 0
< Date: Sat, 12 Sep 2020 20:52:43 GMT
<
* Connection #0 to host 127.0.0.1 left intact
```
Privoxy log file report success as well

```
2020-09-12 20:52:43.822 7f741e71b700 Redirect: pcrs command "s@http://@https://@" changed "http://example.com/" to "https://example.com/" (1 hit).
2020-09-12 20:52:43.822 7f741e71b700 Redirect: New URL is: https://example.com/
```

Proxy to clash which in turn proxies to Privoxy
```
# curl -x "http://127.0.0.1:7890" -v http://example.com
* Expire in 0 ms for 6 (transfer 0x556b3535ff50)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x556b3535ff50)
* Connected to 127.0.0.1 (127.0.0.1) port 7890 (#0)
> GET http://example.com/ HTTP/1.1
> Host: example.com
> User-Agent: curl/7.64.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Content-Length: 1256
< Accept-Ranges: bytes
< Age: 190436
< Cache-Control: max-age=604800
< Connection: keep-alive
< Content-Type: text/html; charset=UTF-8
< Date: Sat, 12 Sep 2020 20:54:08 GMT
< Etag: "3147526947"
< Expires: Sat, 19 Sep 2020 20:54:08 GMT
< Keep-Alive: timeout=4
< Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
< Proxy-Connection: keep-alive
< Server: ECS (phd/FD6D)
< Vary: Accept-Encoding
< X-Cache: HIT
<
<!doctype html>

<truncated>

* Connection #0 to host 127.0.0.1 left intact
```
clash forwards the traffic to Privoxy
```
INFO[0181] [TCP] 127.0.0.1:51350 --> example.com match DomainSuffix(example.com) using s
```
Privoxy reports failure of redirect. it lets through on HTTP as redirect failed.
```
2020-09-12 20:54:07.978 7f741e71b700 Redirect: pcrs command "s@http://@https://@" didn't change "example.com:80".
2020-09-12 20:54:07.978 7f741e71b700 Request: example.com:80/
```

privoxy config

```
debug  4096
debug 128 # Debug redirects
debug 1
debug  8192
listen-address  127.0.0.1:8118
listen-address  [::1]:8118

logfile /tmp/logfile

actionsfile /etc/privoxy/https.action
```

`https.action` file.
```
{ +redirect{s@http://@https://@} }
example.com
```

clash config

```yaml
allow-lan: true
port: 7890
# port of SOCKS5
socks-port: 7891

log-level: debug

mode: rule

proxies:
  - name: "s"
    type: http
    server: 127.0.0.1
    port: 8118

rules:
    - DOMAIN-SUFFIX, example.com, s
    - MATCH, DIRECT
```
