### ISSUE TITLE
请教一下clash dns解析的问题

### ISSUE THREAD

**Issue by cjwddtc** [Dreamacro/clash#922]
我的理解中，clash的dns解析是由default-nameserver解析其他dns服务器地址，由nameserver解析请求的域名，然后为了对抗dns污染，如果fallback列表存在且fallback服务器返回了非中国区ip，那么就采用fallback返回的ip。这套方案应该已经能够解决dns污染的问题了，为什么还需要引入fallback-filter这一项呢？这一项的注释（配置文件的注释）说是这是用于对抗dns污染的手段，但是我的疑惑就在于fallback本身已经能够解决dns的污染了（我认为是这样的）。所以我还是不懂这一项的目的是什么。

**Comment by OUZYcn** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/dns

**Comment by trott90** [comment]
其实我有问题是如果设置了DNS和fallback， 对于有CDN的域名，解析出来是不同的IP，但这个域名本身又设置为direct连接的话，那clash会用哪个IP进行访问

**Comment by OUZYcn** [comment]
> 其实我有问题是如果设置了DNS和fallback， 对于有CDN的域名，解析出来是不同的IP，但这个域名本身又设置为direct连接的话，那clash会用哪个IP进行访问

那个IP先返回给Clash就访问哪个IP
