### ISSUE TITLE
error: unsupported rule type RULE-SET

### ISSUE THREAD

**Issue by hugbio** [Dreamacro/clash#923]
I am using clashX 1.30.1 (ClashCore 1.0), and there is a problem that the configuration cannot be used: error: unsupported rule type RULE-SET, what can I do? I want to use rule-providers

**Comment by Dreamacro** [comment]
download clashx pro

**Comment by testrain** [comment]
@Dreamacro Thanks for the work! But do u mean premium (https://github.com/Dreamacro/clash/releases/tag/premium) for the linux environment?
