### ISSUE TITLE
请问clash Linux 端是否有或者可以设置本地用户config文件

### ISSUE THREAD

**Issue by Zaoyee** [Dreamacro/clash#926]
刚使用clash，很多设置还不是特别熟悉。请问Linux是否有本地用户的config文件就像windows端的一样`Profiles/xxxx.yaml`.
在linux端，可以有设置默认节点的方法吗？谢谢

**Comment by Dreamacro** [comment]
不用 windows 不知道 Profiles 目录代表什么，展开一下？

**Comment by BirkhoffLee** [comment]
說的應該是 CFW 的功能吧
Clash 預設的設定檔是在 $HOME/.config/clash

**Comment by juewuy** [comment]
启动参数时 clash -d 后面添加你想要指定的配置目录即可，比如说clash -d /user/111
