### ISSUE TITLE
如何在配置文件的dns的nameserver中添加ipv6地址?

### ISSUE THREAD

**Issue by yang05051** [Dreamacro/clash#932]
我尝试这么写，会提示ip地址过长：
nameserver:
      - 2001:4860:4860::8888

**Comment by Dreamacro** [comment]
```yaml
nameserver:
  - [2001:4860:4860::8888]:53

```

**Comment by yang05051** [comment]
我这么写了之后，Clash for Windows会报错
![image](https://user-images.githubusercontent.com/31024419/91660502-eefc4f80-eb08-11ea-9306-0de257d34163.png)

**Comment by Dreamacro** [comment]
```yaml
nameserver:
  - "[2001:4860:4860::8888]:53"

```

**Comment by yang05051** [comment]
可以了，谢谢 😃

**Comment by yang05051** [comment]
还有个问题，nameserver添加了ipv6的dns解析地址，为什么还是无法访问ipv6网址呢? 服务器支持ipv6，使用代理模式支持ipv6，唯独添加了dns之后就无法访问了

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/configuration 搜 ipv6

**Comment by yang05051** [comment]
我在全局和dns下设置了 ipv6: true
但还是不行呀

**Comment by Nyarukocqc** [comment]
> 我在全局和dns下设置了 ipv6: true
> 但还是不行呀
- IP-CIDR6,::/0,DIRECT

**Comment by fredericky123** [comment]
> > 我在全局和dns下设置了 ipv6: true
> > 但还是不行呀
> 
> * IP-CIDR6,::/0,DIRECT

加这个还是不行，后来解决了嘛
