### ISSUE TITLE
[Feature] Vmess的UDP规则匹配和SS/Trojan不同，以及标注false的疑惑

### ISSUE THREAD

**Issue by akw5454521** [Dreamacro/clash#934]
### 说明 Description

在用trojan线路时查看日志，发现Youtube的UDP连接会走direct直连（TCP正常），然后上来查找了issue，在配置文件里添加了true后已经正常走代理。之后我用ss和vmess(tcp)线路想看看情况是否一样，结果发现还不一样：
ss线路，udp不做标注或标注为false时，UDP会直连；标注为true时，UDP会正常匹配规则走代理
vmess线路，udp不做标注、标注为false\true时，UDP均会正常匹配规则走代理

首先疑惑的地方就是vmess的情况和ss/trojan不一样，是因为vmess的实现原理不同吗？以及vmess无论怎么标注其结果都是一样的，那么这个标注的意义是什么？
还有就是将udp标注为false预期的作用究竟是什么？因为在wiki和各种说明中都没查到，只是大家都在说要标为true时udp才会正常。按照我个人浅薄的理解，标注为false时说明就应该不支持udp连接吧？(不包括dns)但从实际情况来看(ss和trojan连接)clash并没有阻止udp连接，而是走了direct
最后想问下如果标注false的预期行为不是阻止udp连接，那有没办法阻止(不建立连接)呢？因为我的ss和vmess线路的服务商是不支持udp连接(udp over tcp)的，但Youtube会同时建立udp和tcp连接(根据日志)，而服务器那边对于udp连接是不会返回任何数据的，导致资源浪费以及速度下降，因为这两种连接的目标域名都是类似的所以也没法通过域名规则来reject

不好意思问题有点多，希望不会耽误各位大佬的开发工作

**Comment by Dreamacro** [comment]
是一个 bug，dev 现在应该可以正常处理 UDP 这个 filed 了。

> 最后想问下如果标注 false 的预期行为不是阻止 udp 连接，那有没办法阻止(不建立连接)呢？

标注 false 是不使用 udp，如果规则匹配最终没有匹配到 udp 代理，会回退到直连。目前暂时没有禁用回退的配置

> 导致资源浪费以及速度下降，因为这两种连接的目标域名都是类似的所以也没法通过域名规则来 reject

不会导致速度下降，因为对于 UDP 来说，请求被吞或者没返回都是同样的表现。

**Comment by akw5454521** [comment]
> 是一个 bug，dev 现在应该可以正常处理 UDP 这个 filed 了。
> 
> > 最后想问下如果标注 false 的预期行为不是阻止 udp 连接，那有没办法阻止(不建立连接)呢？
> 
> 标注 false 是不使用 udp，如果规则匹配最终没有匹配到 udp 代理，会回退到直连。目前暂时没有禁用回退的配置
> 
> > 导致资源浪费以及速度下降，因为这两种连接的目标域名都是类似的所以也没法通过域名规则来 reject
> 
> 不会导致速度下降，因为对于 UDP 来说，请求被吞或者没返回都是同样的表现。

感谢大佬回复，我看到已经更新了，辛苦辛苦，坐等客户端跟进了

**Comment by silencebay** [comment]
> 是一个 bug，dev 现在应该可以正常处理 UDP 这个 filed 了。
> 
> > 最后想问下如果标注 false 的预期行为不是阻止 udp 连接，那有没办法阻止(不建立连接)呢？
> 
> 标注 false 是不使用 udp，如果规则匹配最终没有匹配到 udp 代理，会回退到直连。目前暂时没有禁用回退的配置
> 
> > 导致资源浪费以及速度下降，因为这两种连接的目标域名都是类似的所以也没法通过域名规则来 reject
> 
> 不会导致速度下降，因为对于 UDP 来说，请求被吞或者没返回都是同样的表现。

期待禁用回退的配置。手动 script 用 `and network == "udp"` 过滤 youtube，然后感觉总体上规则匹配速度慢了，不太会撸。
