### ISSUE TITLE
关于Enhanced Mode中的选项

### ISSUE THREAD

**Issue by callzhang** [Dreamacro/clash#935]
- DNS Mode: FakeIP/Mapping，我理解前者是推荐的对吗？
- Stack：gVisor和system 如何选择？
- Auto Interface Detechtion: Core/None/ClashXIFace 如何选择？
是否可以提供文档？

**Comment by laggardkernel** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/tun#stack

**Comment by callzhang** [comment]
Auto Interface Detechtion: Core/None/ClashXIFace 如何选择？

**Comment by Dreamacro** [comment]
@callzhang  除了 None 均可，如果你感受不到区别，说明选哪个并不重要
