### ISSUE TITLE
[Bug]设置了ipv6: true，但是仍然无法连接ipv6节点

### ISSUE THREAD

**Issue by Kennnnnnji** [Dreamacro/clash#943]
设置了`ipv6: true`，但是仍然无法连接ipv6节点，报错`ip version error`
![image](https://user-images.githubusercontent.com/34367558/92195114-c83e7000-ee9e-11ea-9258-28d8e331b14b.png)

**Comment by timwa0669** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/general#ipv6
ipv6总开关要开

**Comment by Kennnnnnji** [comment]
> https://lancellc.gitbook.io/clash/clash-config-file/general#ipv6
> ipv6总开关要开

总开关就是这个吧？已经打开了
![image](https://user-images.githubusercontent.com/34367558/92490366-848f9180-f223-11ea-94d5-783d10d9a91e.png)

**Comment by timwa0669** [comment]
不是dns里面的那个

**Comment by Kennnnnnji** [comment]
@timwa0669 这个不是dns啊

**Comment by rainsays** [comment]
遇到同样的问题，无论是地址还是ip都无法连接

**Comment by Kennnnnnji** [comment]
@rainsays 没有解决

**Comment by timwa0669** [comment]
这好像是cfw的问题，cfw开了ipv6总开关也没法使用ipv6

**Comment by ipyin** [comment]
cfw用Mixin在全局开ipv6可以解决

**Comment by nameless3721** [comment]
cfw 的话应该是要改配置文件夹里的config文件的
