### ISSUE TITLE
[Bug][0904部分解决] Vmess TCP模式 http带path混淆不工作 [目前直连可以用，但是不可用于vless回落]

### ISSUE THREAD

**Issue by xianren78** [Dreamacro/clash#944]
V2ray vless支持TCP http path混淆分流，于是进行测试了，很简单在v2ray tcp上加上
```
                        "header": {
                            "type": "http",
                            "request": {
                                "path": ["/vmesstcp"]
                                                }

```
然后在v2rayng客户端上加上path 为/vmesstcp就可以工作了，因此期望在clash上也可以很方便的工作。但是试了所有组合都不行。根据[#156](https://github.com/Dreamacro/clash/issues/156)应该是支持这种混淆方式的。
```- name: "Azure"
  type: vmess
  server: myazure.dom
  port: 443
  uuid: 070896a7-xxxx-4cd6-a243-db052bc0uuid
  alterId: 3
  cipher: none
  tls: true
  skip-cert-verify: true
  network: tcp #改成http也不行，我不确认这儿应该选什么
  http-opts:
   path:
     - '/vmesstcp'
```
加上method headers也不行，甚至我把v2rayng的配置导出来，然后写入clash，能运行，但是仍然不能用。
```- name: "Azure"
  type: vmess
  server: myazure.dom
  port: 443
  uuid: 070896a7-xxxx-4cd6-a243-db052bc0uuid
  alterId: 3
  cipher: none
  tls: true
  skip-cert-verify: true
  network: tcp #改成http也不行，我不确认这儿应该选什么
  http-opts:
   version: "1.1"
   method: "GET"
   path:
     - '/vmesstcp'
   headers:
    Connection:
      - keep-alive
    Host:
      -  myazure.dom
    Pragma:
      - no-cache
    User-Agent:
      - "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
    Accept-Encoding: 
      - "gzip, deflate"
```

**Comment by Dreamacro** [comment]
你应该把在 v2ray 上的相关配置发出来，不然我根本不知道具体情况

**Comment by xianren78** [comment]
> 你应该把在 v2ray 上的相关配置发出来，不然我根本不知道具体情况
```
{
			"port": 443,
			"protocol": "vmess",
			"tag": "vmessp",
			"settings": {
				"clients": [{
						"id": "uuid",
						"level": 0,
						"alterId": 64,
						"email": "email@gmail.com"
					}
				]
			},
			"streamSettings": {
		            "network": "tcp",
                             "security": "tls",
                    "tlsSettings": {
                         "certificates": [
                        {
                            "certificateFile": "/etc/letsencrypt/live/mydomain.com/fullchain.pem",
                            "keyFile": "/etc/letsencrypt/live/mydomain.com/privkey.pem"
                        }]},
				"tcpSettings": {
                        "header": {
                            "type": "http",
                            "request": {
                                "path": ["/vmesstcp"]
                                                }
                                           }
                                  }
			}
		}
'''

**Comment by rprx** [comment]
会不会 clash 的实现是 http 伪装在 tls 外面？（若是这样，建议修改为与 v2ray-core 一致）

**Comment by Dreamacro** [comment]
314ce1c249e042f75297c353e2b11e2f7fb9270f 给 `network: http` 支持了 tls，但不支持私有证书的使用

**Comment by xianren78** [comment]
> [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用

谢谢，在vless没被支持之前，先用vless 分流tcp+tls http伪装顶着。

**Comment by xianren78** [comment]
> [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用

这个版本我测试了。直连基本上没问题，但是用在vless回落场景下不能用，似乎传过来的数据被vless识别为websocket，没办法嗅探出其中的http path, 也没办法成功回落。（我测试成功过一次，但是后来就再也不成功了，原因未知）

**Comment by rprx** [comment]
> 
> 
> > [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用
> 
> 这个版本我测试了。直连基本上没问题，但是用在vless回落场景下不能用，似乎传过来的数据被vless识别为websocket，没办法嗅探出其中的http path, 也没办法成功回落。（我测试成功过一次，但是后来就再也不成功了，原因未知）

不是被 VLESS 识别为 WS。。。VLESS 只识别出 PATH 然后分流

**Comment by harv** [comment]
> > [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用
> 
> 这个版本我测试了。直连基本上没问题，但是用在vless回落场景下不能稳定使用，似乎传过来的数据vless有时候没办法嗅探出其中的http path, 也没办法成功回落。（我测试成功过两次，但是大部分时候不成功，原因未知）

看实现应该是因为`tls: true`后`http-opts`没有被使用，根本没有path，所以vless识别不出来

**Comment by xianren78** [comment]
> > > [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用
> > 
> > 
> > 这个版本我测试了。直连基本上没问题，但是用在vless回落场景下不能稳定使用，似乎传过来的数据vless有时候没办法嗅探出其中的http path, 也没办法成功回落。（我测试成功过两次，但是大部分时候不成功，原因未知）
> 
> 看实现应该是因为`tls: true`后`http-opts`没有被使用，根本没有path，所以vless识别不出来

好的，谢谢，解决了我的疑问

**Comment by Rakau** [comment]
> > > > [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用
> > > 
> > > 
> > > 这个版本我测试了。直连基本上没问题，但是用在vless回落场景下不能稳定使用，似乎传过来的数据vless有时候没办法嗅探出其中的http path, 也没办法成功回落。（我测试成功过两次，但是大部分时候不成功，原因未知）
> > 
> > 
> > 看实现应该是因为`tls: true`后`http-opts`没有被使用，根本没有path，所以vless识别不出来
> 
> 好的，谢谢，解决了我的疑问

现在能正常使用吗?

**Comment by xianren78** [comment]
不能用vless回落，可直连，原因如上。

Rakau <notifications@github.com> 于 2020年10月10日周六 19:14写道：

**Comment by rprx** [comment]
> > > [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用
> > 
> > 
> > 这个版本我测试了。直连基本上没问题，但是用在vless回落场景下不能稳定使用，似乎传过来的数据vless有时候没办法嗅探出其中的http path, 也没办法成功回落。（我测试成功过两次，但是大部分时候不成功，原因未知）
> 
> 看实现应该是因为`tls: true`后`http-opts`没有被使用，根本没有path，所以vless识别不出来

建议 PR

**Comment by xianren78** [comment]
> > > [314ce1c](https://github.com/Dreamacro/clash/commit/314ce1c249e042f75297c353e2b11e2f7fb9270f) 给 `network: http` 支持了 tls，但不支持私有证书的使用
> > 
> > 
> > 这个版本我测试了。直连基本上没问题，但是用在vless回落场景下不能稳定使用，似乎传过来的数据vless有时候没办法嗅探出其中的http path, 也没办法成功回落。（我测试成功过两次，但是大部分时候不成功，原因未知）
> 
> ~看实现应该是因为`tls: true`后`http-opts`没有被使用，根本没有path，所以vless识别不出来~
> 
> vless已经识别到了path，但是会报错
> 
> > [Info] [3044093528] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: fallback ends > context canceled
> > [Info] [4260388535] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
> > [Info] [4260388535] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe

VLESS识别到path会有日志的。

**Comment by eromoe** [comment]
域名到期换成 tcp+http 就无法链接，clash的配置文档太不完善了，ws+tls 的配置也和v2ray 官方不一样。

**Comment by eromoe** [comment]
把 `network: tcp` 改成 `network: http` 才可用。真是要吐槽

和v2ray 官方文档不一致，和 v2ray gui 客户端 也不一致
一般是：
      "network": "tcp",
      "headerType": "http",

结果clash 变成了 network: http    没有简明的文档解释 。 一般直接有一个配置页面解释清楚具体配置，不解释的话就和官方一致，怎么会这么混乱？？

**Comment by aawwsslll** [comment]
这样混淆会工作。不过我是没有开tls. 想用http混淆的，把哪个百度的网址改成你用的host即可。文档的规范里没有
这个host，我不知道是这个path生效的，还是说这个host有作用，但是按照v2ray的规范是有这个host的。
- name: tcp+http
    server: xxxxxx
    port: 8080
    type: vmess
    uuid: ec96e086-f299-4941-b4ac-dc2fd24cc759
    alterId: 0
    cipher: auto
    #udp: true
    network: http
    http-opts:
      method: "GET"
      path:
        - "www.baidu.com/"
      headers:
        host: 
          - "www.baidu.com"
        Connection:
          - keep-alive

**Comment by zyt0002** [comment]
> 把 `network: tcp` 改成 `network: http` 才可用。真是要吐槽
> 
> 和v2ray 官方文档不一致，和 v2ray gui 客户端 也不一致 一般是： "network": "tcp", "headerType": "http",
> 
> 结果clash 变成了 network: http 没有简明的文档解释 。 一般直接有一个配置页面解释清楚具体配置，不解释的话就和官方一致，怎么会这么混乱？？

能分享一下clash的配置文件吗，我也是想用tcp+http伪装，不知道怎么改，tls是不是不需要启用

**Comment by GdestinyG** [comment]
你好，现在可以用了吗，我试了填http-opts发现错误，无法运行

**Comment by GdestinyG** [comment]
> 

现在直连可以了，就是填不了混淆

**Comment by xibaluo** [comment]
> 

解决了我的问题，感谢
