### ISSUE TITLE
读取不到配置文件

### ISSUE THREAD

**Issue by xyijmn** [Dreamacro/clash#948]
我按照文档所给的 `-d` 指定配置文件目录的方式，clash 却始终读取不到 `config.yaml` 之中的配置，`config.yaml` 格式确信是正确的（因为是从 calshx 之中拷贝过来的），请求大佬指点一二，不胜感激。
![IMAGE 2020-09-06 02:46:31](https://user-images.githubusercontent.com/33377263/92311623-2bd5b400-efeb-11ea-8514-15183e87e56d.jpg)
![IMAGE 2020-09-06 02:46:35](https://user-images.githubusercontent.com/33377263/92311625-2e380e00-efeb-11ea-8558-c40f6e232506.jpg)

**Comment by Dreamacro** [comment]
看起来配置读到了，把配置简单去敏贴一下吧

**Comment by xyijmn** [comment]
> 看起来配置读到了，把配置简单去敏贴一下吧

非常抱歉打扰到了大大，问题找到了：因为使用了老版配置格式，更换为新版配置格式，问题解决。
