### ISSUE TITLE
Some poisoning IP can not use fallback DNS 

### ISSUE THREAD

**Issue by comzyh** [Dreamacro/clash#95]
For example, the following IP is poisoning IP, but their country code in GEOIP is empty, so clash will not use fallback DNS for them.

> 243.185.187.39
> 249.129.46.48
> 253.157.14.165

https://github.com/Dreamacro/clash/blob/49635eab6cbc5c667ea1d015d4f3c06851f53a01/dns/client.go#L134-L141

Why does clash use fallback when `record.Country.IsoCode == ""` ?

**Comment by Dreamacro** [comment]
> 1. when clash is restarted, internal DNS cache of clash will go disappear

Is that a problem?

> 2. clash DNS server doesn‘t apply DNS TTL countdown, so there is a chance that a downstream DNS 

It will be fixed later.

> 3. multiple different domains may have same “poisoned” IP, so only one of the domains can establish a correct connection.

I don't understand what it means.

**Comment by comzyh** [comment]
github.com and google.com my have identical ip from poisoned dns cache.

Dreamacro <notifications@github.com> 于 2019年1月19日周六 19:53写道：

**Comment by BirkhoffLee** [comment]
I am having exact same issue that Clash
is getting poisoned IP addresses. This makes redir and dns feature literally unusable. It happens on many domains including google.com,duckduckgo.com, etc

**Comment by comzyh** [comment]
> > 1. when clash is restarted, internal DNS cache of clash will go disappear
> 
> Is that a problem?

I think No.1 is a problem, for Android devices,  shutting down and restarting is not a rare case.

**Comment by comzyh** [comment]
Update， I found that some DNS poisoning is using `0.0.0.0` now, and multiple IP direct to the same `0.0.0.0`,  and #105  works well for me now.

```
dig www.google.com @10.10.0.21
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 60429
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 4; ADDITIONAL: 4

;; QUESTION SECTION:
;; www.google.com. IN A

;; ANSWER SECTION:
www.google.com. 13331 IN A 0.0.0.0

;; AUTHORITY SECTION:
google.com. 1548 IN NS ns3.google.com.
google.com. 1548 IN NS ns4.google.com.
google.com. 1548 IN NS ns1.google.com.
google.com. 1548 IN NS ns2.google.com.

;; ADDITIONAL SECTION:
ns1.google.com. 69955 IN A 216.239.32.10
ns4.google.com. 192082 IN A 216.239.38.10
ns1.google.com. 203873 IN AAAA 2001:4860:4802:32::a
ns2.google.com. 75511 IN AAAA 2001:4860:4802:34::a
```

**Comment by SukkaW** [comment]
![image](https://user-images.githubusercontent.com/40715044/53575892-7d5ae280-3bad-11e9-8454-95bae43e1811.png)

I have exact same poisoning at `youtube.com` (Apex domain). This happened when I am using clash redir feature (on KoolClash).

**Comment by comzyh** [comment]
Here is the Wikipedia [link](https://zh.wikipedia.org/wiki/%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BC%93%E5%AD%98%E6%B1%A1%E6%9F%93) of the polluted IP address. 
As you know, most of them are overseas IP addresses. I don't know other fature yet.

**Comment by Dreamacro** [comment]
close because of #105
