### ISSUE TITLE
[Bug]连接出现以下情况，该如何解决？

### ISSUE THREAD

**Issue by everglowbear** [Dreamacro/clash#950]
PC端和手机端订阅最新地址之后无法正常连接
按照配置教程重新订阅、重启设备、重装应用等方法仍然无法解决问题
日志内容显示如下：
dial 节点选择 error:sg-v30sc.360cdn.men:327
connect error:dial tcp4 120.232.194.246:327:i/o
timeout
dial 节点选择 error:sg-v30sc.360cdn.men:327
connect error:dial tcp4 120.232.194.246:327:i/o
timeout
dial 节点选择 error:sg-v30sc.360cdn.men:327
connect error:dial tcp4 120.232.194.246:327:i/o
timeout
dial 节点选择 error:sg-v30sc.360cdn.men:327
connect error:dial tcp4 120.232.194.246:327:i/o
timeout

请问以上问题该如何解决？一开始以为是账户套餐时间到期续费180天，两天过后仍然无法解决此问题，请求帮助。谢谢

**Comment by Dreamacro** [comment]
检查一下到 120.232.194.246:327 的连通性

**Comment by everglowbear** [comment]
> 检查一下到 120.232.194.246:327 的连通性

找不到主机

**Comment by Dreamacro** [comment]
所以这就是节点的问题了，我这没法解决

**Comment by everglowbear** [comment]
> 所以这就是节点的问题了，我这没法解决

那这么说的话就是所有的节点都无法使用，那怎么办。。。等待Clash的人处理？过两天再看？
