### ISSUE TITLE
[Bug][Core v1.1.0] 当配置包含 `IP-CIDR,[v6 addr]/cidr,DIRECT` 时出现 `Parse config error` 错误

### ISSUE THREAD

**Issue by IceCodeNew** [Dreamacro/clash#951]
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 我已经使用 dev 分支版本测试过，问题依旧存在
- [x] 我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题
- [x] 这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题

------------------------------------------------------------------

### Clash config

<details>
  <summary>ipcidr.yaml</summary>

```yaml
rules:
  - 'GEOIP,CN,DIRECT'
  - 'IP-CIDR,115.27.0.0/16,DIRECT'
  - 'IP-CIDR,162.105.0.0/16,DIRECT'
  - 'IP-CIDR,202.112.7.0/24,DIRECT'
  - 'IP-CIDR,202.112.8.0/24,DIRECT'
  - 'IP-CIDR,222.29.0.0/17,DIRECT'
  - 'IP-CIDR,222.29.128.0/19,DIRECT'
  - 'IP-CIDR,[2001:da8:201::]/48,DIRECT'
  - 'MATCH,AutoSelect'
```

</details>

### Clash log

```
time="2020-09-06T16:11:07+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-09-06T16:11:07+08:00" level=fatal msg="Parse config error: Rules[7] [IP-CIDR,[2001:da8:201::]/48,DIRECT] error: payload error"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows 10
* 网路环境或拓扑 (network conditions/topology)
略
* iptables，如果适用 (if applicable)
不适用
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
问题无关且已提前解决
* 其他 (any other information that would be useful)
略

### 说明 Description

当配置包含 `IP-CIDR,[v6 addr]/cidr,DIRECT` 时出现 `Parse config error` 错误，
而我是从 [文档](https://lancellc.gitbook.io/clash/clash-config-file/rules/ip-based-rule) 里直接 copy 出来的用法，严格按照格式配置的。

### 重现问题的具体布骤 Steps to Reproduce

1. 在 CFW GUI 的 Profiles 页导入 ipcidr.yaml，确保其内容是上面提供的配置
2. 回到 GUI general 页，可以观察到 Core 启动失败的提示

**我预期会发生……？**

Core 正确解析以下规则：
```
rules:
  - 'IP-CIDR,[2001:da8:201::]/48,DIRECT'
```

**实际上发生了什么？**

解析过程中出现 payload error

**Comment by IceCodeNew** [comment]
参考 [官方文档](https://github.com/Dreamacro/clash/wiki/configuration) 改成了如下配置：
```yaml
  - 'IP-CIDR6,[2001:da8:201::/48],DIRECT'
```

```diff
- 'IP-CIDR,[2001:da8:201::]/48,DIRECT'
+ 'IP-CIDR6,[2001:da8:201::/48],DIRECT'
```

回到 GUI general 页发现内核还是启动失败，日志如下：
```
time="2020-09-06T16:30:19+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-09-06T16:30:19+08:00" level=fatal msg="Parse config error: Rules[7] [IP-CIDR6,[2001:da8:201::/48],DIRECT] error: payload error"
```

**Comment by Loyalsoldier** [comment]
```
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,[2011:dab8:3456:82a0::]/50,DIRECT
```

**Comment by IceCodeNew** [comment]
> ```
> IP-CIDR,127.0.0.0/8,DIRECT
> IP-CIDR,[2011:dab8:3456:82a0::]/50,DIRECT
> ```

就是你说的这种我先试过了报错才换了下面这一种的，

**Comment by Dreamacro** [comment]
https://golang.org/pkg/net/#ParseCIDR

**Comment by IceCodeNew** [comment]
> [golang.org/pkg/net/#ParseCIDR](https://golang.org/pkg/net/#ParseCIDR)

看懂了，这里根本就不该加中括号，直接 `  - 'IP-CIDR,2001:da8:201::/48,DIRECT'` 就对了。

文档真的该更新了。

**Comment by Dreamacro** [comment]
那边的文档不是我写的 😂，已经改了
