### ISSUE TITLE
[Feature] 支持 REJECT-TINYGIF

### ISSUE THREAD

**Issue by IceCodeNew** [Dreamacro/clash#953]
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

------------------------------------------------------------------

### 说明 Description
在 18 年的一个 [Issue #70](https://github.com/Dreamacro/clash/issues/70#issuecomment-446289647) 里作者曾说到：
> `REJECT-TINYGIF` 可以考虑一下

我觉得有必要把这项 feature request 单独发出来，否则这个点子大概会一直被遗忘下去吧。
我用这个关键词找不到任何提交记录或者历史 PR，所以估计过去从来没有人往这个方向努力过。

**Comment by Fndroid** [comment]
HTTP的广告也不多见了吧，而且还不一定能骗过去重试机制。

还不如把现在的REJECT延长一点时间再丢掉。

**Comment by IceCodeNew** [comment]
> HTTP的广告也不多见了吧，而且还不一定能骗过去重试机制。
> 
> 还不如把现在的REJECT延长一点时间再丢掉。

有的流氓广告针对这一点有疯狂重试的反应……
