### ISSUE TITLE
[Bug] Proxies里的server不支持ipv6

### ISSUE THREAD

**Issue by timwa0669** [Dreamacro/clash#956]
### Clash config
mixed-port: 1080
external-controller: 127.0.0.1:9090
allow-lan: true
mode: rule
log-level: debug

proxies:
  - {name: dns_proxy, server: mirrors6.tuna.tsinghua.edu.cn, port: 1, type: ss, cipher: rc4-md5, password: test, udp: true}
  - {name: ip_proxy, server: 2001::32, port: 1, type: ss, cipher: rc4-md5, password: test, udp: true}

proxy-groups:
  - name: Test
    type: select
    proxies:
      - dns_proxy
      - ip_proxy

rules:
  - MATCH,Test

### Clash log

使用dns_proxy：
2020-09-08 17:45:29[warning] dial Test error: mirrors6.tuna.tsinghua.edu.cn:1 connect error: couldn't find ip

使用ip_proxy  proxies服务器server的ipv6地址未加中括号:
2020-09-08 17:47:14[warning] dial Test error: [2001::32]:1 connect error: ip version error

使用ip_proxy  proxies服务器server的ipv6地址加中括号：
无法加载配置文件，报错：
Proxy 1: 'server' expected type 'string', got uncoverable type '[]interface{}'

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
macOS 10.15.6 Premium 2020.08.16
……
* 网路环境或拓扑 (network conditions/topology)
有公网ipv6地址的网络环境
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
配置中的域名地址无污染
……
* 其他 (any other information that would be useful)
……

### 说明 Description
通过relay实现ipv6 to ipv4的过程中发现此bug
### 重现问题的具体布骤 Steps to Reproduce

1. 直接加载配置文件复现bug：
dns无法解析ipv6地址  和  ip version error

ip_proxy里的server对应的ipv6地址加上中括号后再加载
加载配置文件失败

### 更多信息 More Information
追加，哪怕直接走DIRECT，也没法通过ipv6进行连接，测试地址:
https://mirrors6.tuna.tsinghua.edu.cn/
https://[2606:4700:4700::1111]/

**Comment by Dreamacro** [comment]
ipv6 总开关开了吗 默认是 false

**Comment by timwa0669** [comment]
已解决

**Comment by FredYuuu** [comment]
> 已解决

请问是如何解决的，我在配置文件里添加
ipv6: true
之后 log 依然报错 connect error: ip version error

**Comment by timwa0669** [comment]
Config Example:
...
ipv6: true
...
dns:
  ...
  ipv6: true
  ...

**Comment by FredYuuu** [comment]
> ## Config Example:
> ... ipv6: true ... dns:     ...     ipv6: true     ...

两项ipv6都设置为true之后，clashX和clashX pro 的ip version error依然存在而且会 crash
clash for windows 同样报错，但没有 crash 

此ipv6节点 我在同样网络环境下的 shadowrocket 上验证过是可以连通的

**Comment by yoshyv** [comment]
@Dreamacro 

你好，
在 https://dreamacro.github.io/clash/configuration/getting-started.html#ipv6-addresses
写到IPv6地址需要用方括号包起来。

```
Special Syntaxes
There are some special syntaxes in Clash configuration files, of which you might want to be aware:

IPv6 Addresses
You should wrap IPv6 addresses in square brackets, for example:
[aaaa::a8aa:ff:fe09:57d8]
```

然而正如这位所说，server里面的IPv6是不能有方括号的。否则回出现双重括号的问题。日志会如下报错

`[WARN] [TCP] dial failed error=[[2400:省略]]:12345 connect error: address [[2400:省略]]:12345: missing port in address proxy=PROXY lAddr=127.0.0.1:53259`

能否在优化下server里面括号的处理呢？和其他地方的v6处理统一起来？

此外还有别的syntax不统一的地方，例如在大部分地方，节点名称是可以用引号包起来的。然而在分流规则 
`TYPE,ARGUMENT,POLICY` 里面的 POLICY 处，是不能加括号的否则加载配置直接报错。（可能是这里有escape处理？）
