### ISSUE TITLE
[Feature] Pro version on Docker

### ISSUE THREAD

**Issue by jinyu121** [Dreamacro/clash#966]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。
------------------------------------------------------------------
### 说明 Description

目前Docker镜像没有Pro版，在路由器/NAS上使用不太方便。

希望能顺手加上Pro版的Docker。感谢。

**Comment by Dreamacro** [comment]
`docker push dreamacro/clash-premium`
