### ISSUE TITLE
[疑问]有关clash dns 解析中fallback组的意义的疑问

### ISSUE THREAD

**Issue by secretandanon** [Dreamacro/clash#968]
我想问一下，如果在redir-host模式下，被GeoIP判定不为CN时走fallback，如果同时又符合代理条件，那么直接将host发送到远端解析，也就是说客户端拿到的ip是否是真的都没关系了（因为如果判定为代理还要从远端解析），那么，我想问下fallback组的意义何在，不如直接用nameserver中的污染的，反正也要从远端解析。
（ps: 我个人认为，只有当一个域名的被污染了且判定不是走代理的时候，fallback才真正起效）

另外，请求fallback中的dns（如tls://dns.google等）时可能会有非常高的延迟，这样的话客户端等待的时间太长了吧

**Comment by ffegya** [comment]
问题 #642 我已经看了，但是没有解决我的困惑

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/issues/857#issuecomment-691668821

**Comment by Mosney** [comment]
1. 为了匹配IP规则，你用不到不代表其他人用不到
2. 有的时候污染会污染到保留IP段，此时浏览器/客户端会直接停止响应，比如YouTube被污染到240段
3. 获取到正确的IP，即使CDN不是那么的友好，也可以避免clash在某些特殊情况下无法重新还原hostname时成功连接。
4. 某些特殊情况下必须获取正确的IP

**Comment by Mosney** [comment]
另外你完全可以不设置fallback组，或者为fallback设置一个延迟不高的DNS，如果你看过文档的话就知道这些都不是必需的。请学会合理使用工具而不是只因自己用不到/觉得没必要就来质疑这些设置项是否有必要存在

**Comment by muink** [comment]
不通过代理的域名且被污染，fallback的作用就出来了

**Comment by muink** [comment]
如果能保证提供的nameserver不受污染，fallback就没什么作用了

**Comment by ffegya** [comment]
感谢大家，我明白了，我把思路大致说下。
1.若将clash 的dns 配置为redir-host模式，fallback-filter中geoip设置为true， 对于每一个dns请求，clash会并发的请求所有nameserver、fallback中的dns服务器，然后，clash得到返回最快的dns服务器的解析结果ip，判断是否为CN，若为是，则直接返回nameserver组中解析速度最快的ip地址，若为否，则直接返回fallback组中解析最快的ip地址。这里nameserver组和fallback组的解析动作都是直连的，不经过proxy，若最后判定需要走代理，则clash会将domain与tcp请求通过某种协议发送到远端，在远端重新进行解析，然后与客户端建立联系，如果判定为直连，则就用客户端得到的ip进行tcp 请求
2.若将clash的dns配置为fake-ip模式，对于每一个dns请求，clash会立即返回一个fake ip地址，并记录下此域名与fake ip的对应关系，若判定规则中需要根据ip判定，则请求nameserver组中的dns服务器，得到ip，再根据规则判定。若最后判定需要走代理，则clash会将domain与tcp请求打包通过某种协议发送到远端，在远端重新进行解析，然后与客户端建立联系，如果判定为直连，则就用客户端得到的fake-ip与nameserver中解析到的结果Ip建立联系，进行tcp连接

请大家帮我看看说的对不对，哪怕有一点不对的也指出来，谢谢

**Comment by ffegya** [comment]
@Dreamacro

**Comment by Dreamacro** [comment]
2 不太对，就算是 fakeip ，在执行域名的解析的时候，fallback 都会参与的

**Comment by ffegya** [comment]
@Dreamacro ，感谢 我进行了修改，请查看

**Comment by Creling** [comment]
> ### 感谢大家，我明白了，我把思路大致说下。
> 1.**若将clash 的dns 配置为redir-host模式**，fallback-filter中geoip设置为true， 对于每一个dns请求，clash会并发的请求所有nameserver、fallback中的dns服务器，然后，clash得到nameserver中返回最快的dns服务器的解析结果ip，判断是否为CN，若为是，则直接返回nameserver组中解析速度最快的ip地址，若为否，则直接返回fallback组中解析最快的ip地址。这里nameserver组和fallback组的解析动作都是直连的，不经过proxy，若最后判定需要走代理，则clash会将domain与tcp请求通过_某种协议_发送到远端，在远端重新进行解析，然后与客户端建立联系，如果判定为直连，则就用客户端得到的ip进行tcp 请求 2.**若将clash的dns配置为fake-ip模式**，fallback-filter中geoip设置为true，对于每一个dns请求，clash会立即返回一个fake ip地址，并记录下此域名与fake ip的对应关系，若判定规则中需要根据ip判定，则并发的请求所有nameserver、fallback中的dns服务器，然后，clash得到nameserver中返回最快的dns服务器的解析结果ip，得到ip，判断是否为CN，若为是，则使用nameserver组中解析速度最快的ip地址，若为否，则使用fallback组中解析最快的ip地址。再根据规则判定。若最后判定需要走代理，则clash会将domain与tcp请求打包通过_某种协议_发送到远端，在远端重新进行解析，然后与客户端建立联系，如果判定为直连，则就用客户端得到的fake-ip与前面判断好使用的Ip建立联系，进行tcp连接
> 
> **请大家帮我看看说的对不对，哪怕有一点不对的也指出来，谢谢**

请问，这一解释在`clash premium 2022.6.19`中是否仍然适用？

目前，在使用redir-host及clash内置的dns服务，并设置nameserver为223.5.5.5时，遇到了严重的dns污染问题：访问google.com会被引导向twitter的ip。如果按照上述解释的描述，域名会在远端被重新解析，那么，似乎不应该出现此类现象？

@Dreamacro

**Comment by Dreamacro** [comment]
redir-host 早已不建议使用, 使用出现的任何问题请自行解决
