### ISSUE TITLE
请问clash 可以实现强制解析代理的远程dns吗？如果可以这么实现呢

### ISSUE THREAD

**Issue by shukehi** [Dreamacro/clash#969]
![Screenshot_20200915-103727](https://user-images.githubusercontent.com/46439764/93159023-e8dcb480-f73f-11ea-93e0-089116730956.png)
![Screenshot_20200915-103719](https://user-images.githubusercontent.com/46439764/93159044-f134ef80-f73f-11ea-94da-4a443c7bfe72.png)
使用clash 代理后 whoer 检测到DNS不符，请问有什么方式可以实现直接使用代理IP的DNS。

**Comment by muink** [comment]
这个dns结果既不是本地dns地址也不是远程dns地址
不知道它是怎么检测的

**Comment by shukehi** [comment]
> 这个dns结果既不是本地dns地址也不是远程dns地址
> 不知道它是怎么检测的

proxifier 和 小火箭可以直接强制使用远程的dns解析，解析到的是代理ip对应的dns，而clash解析的dns是国内的

**Comment by 101818** [comment]
这就是fake-ip模式

**Comment by silmace** [comment]
上面那个老哥说的很正确
https://blog.skk.moe/post/alternate-surge-koolclash-as-gateway/
https://blog.skk.moe/post/what-happend-to-dns-in-proxy/
在看完这两篇文章后，聪明的你一定会想到解决办法

**Comment by Fndroid** [comment]
> 而clash解析的dns是国内的

这句话是错的，clash本来就只能远程解析。

至于你上面的测试，把 mode 改成 global 大概就没问题了，大概率是你规则问题。

**Comment by nameless3721** [comment]
> > 这个dns结果既不是本地dns地址也不是远程dns地址
> > 不知道它是怎么检测的
> 
> proxifier 和 小火箭可以直接强制使用远程的dns解析，解析到的是代理ip对应的dns，而clash解析的dns是国内的
这个只是骗小白的玩意 
 nameserver:
    - https://doh.opendns.com/dns-query
    - https://1.0.0.1/dns-query
你nameserver的dns用国外的就行了大概就是他根据你用的哪国dns来查询他给的域名来判断 全局模式不知道是不是不会本地解析直接全丢国外的原因所以显示节点国外  rule模式会用nameserver查询一次所以他读了这个 只要nameserver用国外dns就行了  不过不建议访问如www.baidu.com 有国外ip的会很卡也没啥意义只是看起来舒服？实际clash走代理已经是远程解析的如果你是自己搭建节点的话看日志就好了  proxifier 和 小火箭应该只是让解析的dns先走了代理的关系相当于服务器用设置的dns来替你本地解析所以可以显示国外clash的dns是走直连解析后再判断吧
![JB`)%M@MDGGKAC)2NMI4TR](https://user-images.githubusercontent.com/50364156/95497132-d2dbb000-09dc-11eb-9807-90d6b7a9cfc4.png)
香港节点显示新加坡是阿里8. ip识别有问题 显示日本的dns是直连的opendns给了日本服务器了 如果想要其他国家dns就换其他国家专属的dns但是不能被劫持了

**Comment by akw5454521** [comment]
啊这

![Screenshot_20201020-043127_Samsung Internet Beta](https://user-images.githubusercontent.com/68607321/96911675-beff7600-14d3-11eb-8a5a-3df8cb02626c.jpg)

**Comment by sachmx001** [comment]
这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……

**Comment by silmace** [comment]
> 这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……

没人逼你用，没有人应该为你付出劳动成果，自己看不懂源代码，看不懂英文，看不懂文档，别在这露出自己是上帝的样子，上面那个贡献者已经回答的很简单了。clash拿到dns解析之后只是用来判断是否需要走代理，远程还要再解析一次

**Comment by sachmx001** [comment]
别在这装模作样了，大家的行业不同，也许在这个领域你是专家，但到了别人那里，别人就是专家，你就是小白了，大家都各有所长，有什么好装的？你除了这编程、网络之类的，其他行业你会几个？不要告诉你全能……这些东西，不是说看不懂，但对不是这个专业的人来说，需要花更多的时间精力成本去搞懂，整个社会，大家其实都是在互相为别人服务，医生给你看病，老师给你教孩子，电子厂给你生产电器，你为别人开发软件，你要是只是自娱自乐，那你在一边自乐去好了，也别放出来让大家用，既然又是想拿出来给人用的，那就做得尽量简单易懂点，节约别人的学习成本！大家互相服务，仅此而已，别在自己擅长的方面装的个什么一样，记住，你不是全能者，你也有求教别人的一天！不为社会服务让社会为你服务？以为自己都是乔布斯呢？



---原始邮件---
发件人: "diligent-boy"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上10:24
收件人: "Dreamacro/clash"<clash@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Dreamacro/clash] 请问clash 可以实现强制解析代理的远程dns吗？如果可以这么实现呢 (#969)




  
这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……
  
没人逼你用，没有人应该为你付出劳动成果，自己看不懂源代码，看不懂英文，看不懂文档，别在这露出自己是上帝的样子，上面那个贡献者已经回答的很简单了。clash拿到dns解析之后只是用来判断是否需要走代理，远程还要再解析一次

**Comment by AkariiinMKII** [comment]
> 别在这装模作样了，大家的行业不同，也许在这个领域你是专家，但到了别人那里，别人就是专家，你就是小白了，大家都各有所长，有什么好装的？你除了这编程、网络之类的，其他行业你会几个？不要告诉你全能……这些东西，不是说看不懂，但对不是这个专业的人来说，需要花更多的时间精力成本去搞懂，整个社会，大家其实都是在互相为别人服务，医生给你看病，老师给你教孩子，电子厂给你生产电器，你为别人开发软件，你要是只是自娱自乐，那你在一边自乐去好了，也别放出来让大家用，既然又是想拿出来给人用的，那就做得尽量简单易懂点，节约别人的学习成本！大家互相服务，仅此而已，别在自己擅长的方面装的个什么一样，记住，你不是全能者，你也有求教别人的一天！不为社会服务让社会为你服务？以为自己都是乔布斯呢？
> 
> 
> 
> ---原始邮件---
> 发件人: "diligent-boy"<notifications@github.com&gt;
> 发送时间: 2020年11月29日(周日) 晚上10:24
> 收件人: "Dreamacro/clash"<clash@noreply.github.com&gt;;
> 抄送: "Comment"<comment@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
> 主题: Re: [Dreamacro/clash] 请问clash 可以实现强制解析代理的远程dns吗？如果可以这么实现呢 (#969)
> 
> 
> 
> 
>   
> 这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……
>   
> 没人逼你用，没有人应该为你付出劳动成果，自己看不懂源代码，看不懂英文，看不懂文档，别在这露出自己是上帝的样子，上面那个贡献者已经回答的很简单了。clash拿到dns解析之后只是用来判断是否需要走代理，远程还要再解析一次
>  
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

放心吧，不会有求你的那天，诶嘿~

**Comment by sachmx001** [comment]
嗯，你继续这自我的个性，保持到老！千万别改！😁



---原始邮件---
发件人: "AkariiinMKII"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上10:52
收件人: "Dreamacro/clash"<clash@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Dreamacro/clash] 请问clash 可以实现强制解析代理的远程dns吗？如果可以这么实现呢 (#969)




  
别在这装模作样了，大家的行业不同，也许在这个领域你是专家，但到了别人那里，别人就是专家，你就是小白了，大家都各有所长，有什么好装的？你除了这编程、网络之类的，其他行业你会几个？不要告诉你全能……这些东西，不是说看不懂，但对不是这个专业的人来说，需要花更多的时间精力成本去搞懂，整个社会，大家其实都是在互相为别人服务，医生给你看病，老师给你教孩子，电子厂给你生产电器，你为别人开发软件，你要是只是自娱自乐，那你在一边自乐去好了，也别放出来让大家用，既然又是想拿出来给人用的，那就做得尽量简单易懂点，节约别人的学习成本！大家互相服务，仅此而已，别在自己擅长的方面装的个什么一样，记住，你不是全能者，你也有求教别人的一天！不为社会服务让社会为你服务？以为自己都是乔布斯呢？
 
---原始邮件---
 发件人: "diligent-boy"<notifications@github.com&gt;
 发送时间: 2020年11月29日(周日) 晚上10:24
 收件人: "Dreamacro/clash"<clash@noreply.github.com&gt;;
 抄送: "Comment"<comment@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
 主题: Re: [Dreamacro/clash] 请问clash 可以实现强制解析代理的远程dns吗？如果可以这么实现呢 (#969)
 
这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……
 
没人逼你用，没有人应该为你付出劳动成果，自己看不懂源代码，看不懂英文，看不懂文档，别在这露出自己是上帝的样子，上面那个贡献者已经回答的很简单了。clash拿到dns解析之后只是用来判断是否需要走代理，远程还要再解析一次
 
—
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
  
放心吧，不会有求你的那天，诶嘿~

**Comment by coderloverXH** [comment]
> 这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……

Clash面向的是希望获得更好的科学上网体验的用户。像恁这种像连基本折腾

> 这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……

Clash面向的是希望获得更好的科学上网体验的高端用户群体。像恁这种连基本动手能力都没有的键盘侠，恁也配用Clash? 哈哈哈，请滚回去用恁的蓝灯或老王VPN吧，一键翻墙更适合恁！

**Comment by sachmx001** [comment]
哦



---原始邮件---
发件人: "coderloverXH"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上11:21
收件人: "Dreamacro/clash"<clash@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [Dreamacro/clash] 请问clash 可以实现强制解析代理的远程dns吗？如果可以这么实现呢 (#969)




  
这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……
  
Clash面向的是希望获得更好的科学上网体验的用户。像恁这种像连基本折腾
  
这些开发者啊，有些时候就是为了展示自己的技术，云里雾里、绕来绕去的，我用户需要的就是一个功能而已，你把这个功能实现了就行，绕那么多，谁tm有功夫来跟你绕？网络时代，大家都这么忙，分工合作就是为了节约大家时间，尽量弄点浅显易懂，让大家的对接成本尽量低一点，这就是为社会做贡献了，没有人会来关心你那狗屁技术水平，大家只关心自己的利益，把简单事情复杂化，只是让人觉得厌烦……一个漠视用户需求的人，也就不用装模作样地在频道上可怜兮兮地求打赏了……
  
Clash面向的是希望获得更好的科学上网体验的高端用户群体。像恁这种连基本动手能力都没有的键盘侠，恁也配用Clash? 哈哈哈，请滚回去用恁的蓝灯或老王VPN吧，一键翻墙更适合恁！
