### ISSUE TITLE
Dashboard面板仅显示{"hello":"clash"}

### ISSUE THREAD

**Issue by wuJflower** [Dreamacro/clash#970]
127.0.0.1:9090
`{"hello":"clash"}`
没有解决

@Dreamacro

_Originally posted by @e71828 in https://github.com/Dreamacro/clash/issues/546#issuecomment-656027141_

**Comment by wuJflower** [comment]
http://clash.razord.top/#/proxies  
连接成功但是代理是空的

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0

**Comment by liby** [comment]
@Dreamacro 抱歉打扰一下，
我在 [breaking-changes-in-1.0.0 ]( https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0) 这个 Change log 中并没有看到有关 Web UI 的修改或者迁移，请问在哪可以看到相关的文档？比如为什么要访问 http://clash.razord.top 就可以看到 Web UI，之前的 127.0.0.1:9090 应该也有这个效果吧，是什么时候迁移的，比较想找到这部分的文档，期待您的回复🙏

**Comment by e71828** [comment]
@liby 应该在 config.yaml 里面有这样的字段
```
external-controller: 0.0.0.0:9090
external-ui: ui
```

同时在，`config.yaml`的当前文件夹下有名为`ui`的网页资源文件
```
root@lab:/etc/clash$ ls
config.yaml  Country.mmdb  ui  update.sh  yacd
```

**Comment by a12591771** [comment]
我的配置好之后不能通过本地ip:port/ui的方式访问，通过SSH端口转发之后，可以用127.0.0.1:port/ui访问；

**Comment by John-zhan** [comment]
怎么操作呢，我也遇到了同样的问题，当然我已经配置了external-ui: path

**Comment by gy528909** [comment]
> external-ui: ui
麻烦问一下ui的网页资源是自动生成的吗？还是需要额外下载的？我下载启动clash后没有找到这个文件。
