### ISSUE TITLE
[Bug]desc of load-balance is not correct about eTLD

### ISSUE THREAD

**Issue by alsotang** [Dreamacro/clash#972]
https://github.com/Dreamacro/clash/wiki/configuration

`# load-balance: The request of the same eTLD will be dial to the same proxy.` 

Above should be 

`# load-balance: The request of the same eTLD+1 will be dial to the same proxy.` 

eTLD means `.com`, `.co.jp` or `.co.uk`, it's a top-level domain but not a valid hostname.

In the scenario of load-balance, we care about hostname but not a tld.

**Comment by Dreamacro** [comment]
fixed
