### ISSUE TITLE
[Feature] proxy-groups增加一个文件下载测试类型，选出下载最快的节点为最优节点

### ISSUE THREAD

**Issue by ClarkeCheng** [Dreamacro/clash#980]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
……
* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

这个功能就像 url-test那样，先指定一个要下载的文件的 url，再指定一个超时时间，让一组被测代理去下载这个文件，在指定的时间内下载的数据最多的那个节点为最优节点。

**Comment by Fndroid** [comment]
下载的时候宽带被占满了怎么上网？

**Comment by adamw92** [comment]
每5分钟对n个节点进行一轮每个节点30秒谁下载的内容最多的带宽测试？
24*7的占满你的宽带和线路么

**Comment by akw5454521** [comment]
手里的线路，在高峰期/非高峰期是个什么速度，心里边应该都有数吧

**Comment by Pointvar** [comment]
感觉可以加上这个功能，很实用。
高峰期也可以很快的选择最优线路，每次实用其他软件测速后调整配置比较麻烦的

**Comment by sanzhang007** [comment]
自动测速,看视频突然就卡了.............,还是不写的好
