### ISSUE TITLE
[Feature]  关于使用、操作体验的一个功能需求

### ISSUE THREAD

**Issue by fadingchen** [Dreamacro/clash#981]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求
我没有在 issue 中找到类似的请求。

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### Clash core config

```
……
```

### Clash log

```
……
```

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
 mac os 
……
* 使用者的操作系统 (the OS running on the client)
操作系统 mac os 10.15
……
* 网路环境或拓扑 (network conditions/topology)
局域网
……
* iptables，如果适用 (if applicable)

……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
无污染
* 其他
……

### 说明 Description

**### **我有一个产品的优化建议，能不能在测试结果的反馈时间获取数据以后，做排序，用时少的服务拍在上面，失效的在最下面，可以不用下拉到最下面，就能快速的了解列表中服务的健康状态，have a good time，peace&love ****

### 可能的解决方案 Possible Solution

- [ ] **解决方案 1：定时排序，为了减少能源损耗，可以在一个短时间周期内，定时排序**

- [ ] **解决方案 2：可以给出一个触发操作的入口，留给用户去触发手动排序，触发会有一个 10 秒的间隔期，防止鼠标误操作**

**Comment by Dreamacro** [comment]
这个项目不包含 GUI 部分，应该提给相应的 GUI repo

**Comment by fadingchen** [comment]
> 这个项目不包含 GUI 部分，应该提给相应的 GUI repo

请问 负责 Gui 的团队是哪位大神，怎么转给他们呢

**Comment by Ninzero** [comment]
你用的是 macOS 我猜是 [ClashX](https://github.com/yichengchen/clashX)

**Comment by iamqk** [comment]
clashx非常“专制” 不能提issue😄

**Comment by woyaoshangPKU** [comment]
clash for windows支持😀

> 
> 请问 负责 Gui 的团队是哪位大神，怎么转给他们呢

**Comment by fadingchen** [comment]
> clashx非常“专制” 不能提issue😄

我说我怎么着了半天，都找不到新增的按钮，不得已才去内核组里写了 issue。

**Comment by fadingchen** [comment]
排序的功能，在win版本的客户端已经实现了。mac版本请同步一下该功能

**Comment by iamqk** [comment]
> 排序的功能，在win版本的客户端已经实现了。mac版本请同步一下该功能

你联系一下clashx作者吧，这里回复她也不一定看得到

**Comment by iamqk** [comment]
> 排序的功能，在win版本的客户端已经实现了。mac版本请同步一下该功能

作者开了issue的权限了，可以去问了
