### ISSUE TITLE
为什么我在ubuntu上编译的dev分支无法在openwrt下执行呢

### ISSUE THREAD

**Issue by secretandanon** [Dreamacro/clash#985]

**Comment by maddie** [comment]
检查编译时`GOOS`, `GOARCH`以及`GOARM`或`GOMIPS`设置

**Comment by secretandanon** [comment]
我检查了，我用的是最新版的golang来编译的好像是1.19，是不是要用cgo来编译呀

**Comment by secretandanon** [comment]
好了，加个CGO_ENABLED=0，就可以了，就是我很奇怪，为什么我编译出来的文件大小比release中的要大呢

**Comment by Dreamacro** [comment]
你不用 make 构建的吗
