### ISSUE TITLE
[Bug]0923384.Athena版本与购物党冲突，开启服务 购物党无法使用

### ISSUE THREAD

**Issue by odrip** [Dreamacro/clash#987]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
……
```

</details>

### Clash log

```
……
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by angelknight007** [comment]
merlinclash的问题去电报群反馈，你这个 八成是规则问题

**Comment by flyhigherpi** [comment]
我在大佬这里看到了啥，手动狗头
