### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by dazirangege** [Dreamacro/clash#988]
在下方附上 Clash Core 脱敏后的配置内容
Paste the Clash core configuration below.
-->
```
# (HTTP and SOCKS5 in one port)
mixed-port: 7891
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: warning

proxies:

proxy-groups:

rules:
  - DOMAIN-SUFFIX,google.com,DIRECT
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN,google.com,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
……
```

**Comment by dazirangege** [comment]
> 在下方附上 Clash Core 脱敏后的配置内容
> Paste the Clash core configuration below.
> -->
> 
> ```
> # (HTTP and SOCKS5 in one port)
> mixed-port: 1086
> # RESTful API for clash
> external-controller: 127.0.0.1:9090
> allow-lan: false
> mode: rule
> log-level: warning
> 
> proxies:
> 
> proxy-groups:
> 
> rules:
>   - DOMAIN-SUFFIX,google.com,DIRECT
>   - DOMAIN-KEYWORD,google,DIRECT
>   - DOMAIN,google.com,DIRECT
>   - DOMAIN-SUFFIX,ad.com,REJECT
>   - GEOIP,CN,DIRECT
>   - MATCH,DIRECT
> ……
> ```
> 
> ### 说明 Description

**Comment by dazirangege** [comment]
我的电脑是mac，用的代理工具是clashX ，appstore下载的telegram需要设置socks5才能使用。

clashX里有两个配置文件，一个是config，一个是我的配置文件，config里设置的mixed-port为1086，clashX显示的socks端口也是1086，通过telegram 设置socks5 127.0.0.1:1086 失败。

**Comment by nameless3721** [comment]
telegram.org 建议下载左边的版本   mac专版的tg那个就算设置对也有可能连不了的bug 不想换的话你可以用clashxpro的增强模式clashx的gayhub里面找找就有

> 我的电脑是mac，用的代理工具是clashX ，appstore下载的telegram需要设置socks5才能使用。
> 
> clashX里有两个配置文件，一个是config，一个是我的配置文件，config里设置的mixed-port为1086，clashX显示的socks端口也是1086，通过telegram 设置socks5 127.0.0.1:1086 失败。

**Comment by Dreamacro** [comment]
如果只是 tg 的 socks5 连不上的话就是 tg 老 bug 了，强退 tg 再打开就好了

**Comment by RRRoger** [comment]
> 如果只是 tg 的 socks5 连不上的话就是 tg 老 bug 了，强退 tg 再打开就好了

Cool!!!  it works

**Comment by inix** [comment]
> 如果只是 tg 的 socks5 连不上的话就是 tg 老 bug 了，强退 tg 再打开就好了

但是我用v2rayu，不用退出也可以直接连，很奇怪

**Comment by Dreamacro** [comment]
@inix 只是安装 tg 首次会出现，后面就不再出现了。这是 tg 的问题，与 socks5 实现应该没关系

**Comment by inix** [comment]
> @inix 只是安装 tg 首次会出现，后面就不再出现了。这是 tg 的问题，与 socks5 实现应该没关系

ClashX就是无法连接，退出也不管用，v2rayu可以连。 也不知道怎么回事。
