### ISSUE TITLE
[Feature] 由于Clash默认使用的MaxMind Country.mmdb中对某些dns污染的IIP判断为china IP. 导致代理失败。

### ISSUE THREAD

**Issue by JMVoid** [Dreamacro/clash#989]
由于Clash默认使用的MaxMind Country.mmdb中对某些dns污染的IIP判断为china IP. 导致代理失败， 经过查询IPIP.net，这些IP会被正确分类到海外IP, 因此是否Clash考虑增加到ipip.net的china_ip_list.txt增加支持？多谢

**Comment by ysc3839** [comment]
可以自行生成 mmdb #82

**Comment by JMVoid** [comment]
感谢回复。用https://github.com/alecthw/mmdb_china_ip_list 最新china_ip_list.mmdb 数据。做了下测试,  几个被污染的IP[103.200.30.143, 118.184.26.113, 103.228.130.61]还是判断为CN. 先关闭这个Issue了

**Comment by JMVoid** [comment]
做了个小程序， 将ipip的china_ip_list.txt转成MaxMind mmdb格式，https://github.com/JMVoid/ipip2mmdb 在release branch 下载Country.mmdb就好
