### ISSUE TITLE
使用Socks代理端口的时候IPCIDR规则无效

### ISSUE THREAD

**Issue by xuan880** [Dreamacro/clash#99]
如果代理使用Socks端口那么IPCIDR就会无效.
IPCIDR规则
- IP-CIDR,192.168.0.0/16,DIRECT
使用Socks端口
2019-01-21 10:45:06[info] 192.168.135.100 match FINAL using Proxy
2019-01-21 10:45:06[info] 192.168.135.100 match FINAL using Proxy 
http端口
2019-01-21 10:45:29[info] 192.168.135.100 match IPCIDR using DIRECT
2019-01-21 10:45:29[info] 192.168.135.100 match IPCIDR using DIRECT

**Comment by beyondkmp** [comment]
`curl --socks5-hostname 127.1:7891 http://192.168.123.89` , 这样的目前在socks代理里面是直接将这个ip当成域名的。

**Comment by comzyh** [comment]
我这里 Chrome 用 socks5 连接时也是传的字符串Hostname，然后这个包含 IP 的字符串 在 Clash 会 DNS 解析失败得不到 IP，只能匹配域名规则。

**Comment by beyondkmp** [comment]
用socks的代理http服务的都会有这个问题

**Comment by beyondkmp** [comment]
> > 用socks的代理http服务的都会有这个问题
> 
> 但是
> ![](https://camo.githubusercontent.com/e6d44ad510a292120016c5eef3b99b018a43d601/687474703a2f2f6361696a692e7363757365656b2e636f6d2f33306330333438623962306639383637316633313934353432633164356331612e706e67)
> surge没问题。（跑
确实是可以，这个clash要修复下。

**Comment by Dreamacro** [comment]
#100 Fixed in dev branch
