### ISSUE TITLE
[Bug] Clash (Pre version) has a very important bug about geoip

### ISSUE THREAD

**Issue by secretandanon** [Dreamacro/clash#992]
当使用pre版本的rule_provider功能时存在bug, 
具体现象:
在使用fake-ip模式&&tun模式&&script模式时会出现.

### 复现
fake-ip-range: 198.18.0.1/16
在rule_provider添加如下项目
rule-providers:
  geoip:
    type: file
    behavior: classical
    path: ./rule-providers/geoip.yaml
其中:
geoip.yaml
payload:
  \- GEOIP,CN
 \ -GEOIP,LAN

并使用scripts脚本
if ctx.rule_providers["geoip"].match(metadata):
       return "DIRECT"
else:
      return "PROXY"

你将会发现geoip为cn时走的是proxy而不是direct, 这就是问题所在
猜测,可能此时判断geoip时是根据fake-ip来判断的
当换成

     ip = ctx.resolve_ip(metadata["host"])
     if ip == "":
       return "DIRECT"
     code = ctx.geoip(ip)
     if code == "LAN" or code == "CN":
       return "DIRECT"
     return "PROXY"

来判断时正常

**Comment by Dreamacro** [comment]
不是根据 fake-ip 来判断的，是另一个原因，我发个 fix 吧

**Comment by secretandanon** [comment]
Thanks

**Comment by Dreamacro** [comment]
下载最新的试试

**Comment by secretandanon** [comment]
@Dreamacro 从哪里下载呢

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium 统一在这里

**Comment by secretandanon** [comment]
@Dreamacro  问题依然存在

**Comment by secretandanon** [comment]
geoip.yaml
payload:
  \- GEOIP,CN
 \-GEOIP,LAN

**Comment by secretandanon** [comment]
我的geoip是这样写的，还是不行
     if ctx.rule_providers["geoip"].match(metadata):
         return "DIRECT"
     return "PROXY"

**Comment by secretandanon** [comment]
@Dreamacro ，反复测试后问题并没有改变
我的geoip.yaml文件
payload:
&nbsp;\- GEOIP,CN
&nbsp;\- GEOIP,LAN
script脚本判断
if ctx.rule_providers["geoip"].match(metadata):
&nbsp;&nbsp;return "DIRECT"
return "PROXY"

**Comment by Dreamacro** [comment]
这个问题是这样的，由于 script 包含了所有的匹配过程，所以包含 resolve ip 在内，所有的流程都是由你自己去控制，如果你需要使用需要 ip 的 rule provider，你需要把结果赋值到 metadata 中

```python
metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])
if ctx.rule_providers["geoip"].match(metadata):
  return "DIRECT"
return "PROXY"
```

**Comment by secretandanon** [comment]
@Dreamacro 问题依然存在，添加完这句后，所有走direct的网页全打不开，查看log，提示dst_ip应该被赋一个ip值

**Comment by Dreamacro** [comment]
你是不是解析失败了，可以用 ctx.log() 调试一下

**Comment by secretandanon** [comment]
是的，有时解析出来ip为空，我不知道为什么有时解析出来ip为空，

**Comment by secretandanon** [comment]
我加了个判断，if ip!=""，我才去geoip，就好了

**Comment by Dreamacro** [comment]
为空说明解析结果为空或者超时了
