### ISSUE TITLE
[Bug] DNS not using IPv6 address

### ISSUE THREAD

**Issue by kotori2** [Dreamacro/clash#993]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml

port: 7890
mode: direct
ipv6: true
log-level: debug
dns:
  enable: true
  ipv6: true
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
```

</details>

### Clash log

```
% ./clash-darwin-amd64-v1.1.0
INFO[0000] HTTP proxy listening at: 127.0.0.1:7890
INFO[0006] [TCP] 127.0.0.1:55891 --> ip.sb using DIRECT
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
`Darwin Hackintosh 20.1.0 Darwin Kernel Version 20.1.0: Thu Sep 17 22:14:18 PDT 2020; root:xnu-7195.40.84.171.5~4/RELEASE_X86_64 x86_64`
* 网路环境或拓扑 (network conditions/topology)
IPv4/IPv6 SLAAC+DHCPv6
* iptables，如果适用 (if applicable)
not applicable
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
not applicable
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce
`curl ip.sb -6 --proxy 127.0.0.1:7890`

**我预期会发生……？**

my ipv6 address shows up in output

**实际上发生了什么？**

my ipv4 address shows up in output

### 可能的解决方案 Possible Solution

Both of the dns addresses supports ipv6, but it seems clash is not using them. It seems if I add an ipv6 dns then clash will use ipv6 dns to get AAAA record. 
```
% nslookup -query=AAAA ip.sb 223.5.5.5
Server:		223.5.5.5
Address:	223.5.5.5#53

Non-authoritative answer:
ip.sb	has AAAA address 2606:4700:3036::ac43:b0d9
ip.sb	has AAAA address 2606:4700:3037::681c:bc

Authoritative answers can be found from:
```

**Comment by ysc3839** [comment]
IIRC, that IP address `127.0.0.1:55891` is your curl client socket address. Because you are using IPv4 loopback (127.0.0.1), so it shows IPv4 in output.

**Comment by Dreamacro** [comment]
1. clash get the request to ip.sb
2. match rule to DIRECT
3. dual-stack dial and ipv4 tcp dial fastest
4. return ipv4 ip

**Comment by kotori2** [comment]
> IIRC, that IP address `127.0.0.1:55891` is your curl client socket address. Because you are using IPv4 loopback (127.0.0.1), so it shows IPv4 in output.

@ysc3839 Actually curl will handle this for you
```
% curl -vv -6 ip.sb --proxy "127.0.0.1:7890" -k
*   Trying ::ffff:127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (::ffff:127.0.0.1) port 7890 (#0)
> GET http://ip.sb/ HTTP/1.1
> Host: ip.sb
> User-Agent: curl/7.64.1
> Accept: */*
> Proxy-Connection: Keep-Alive
```

**Comment by kotori2** [comment]
> * clash get the request to ip.sb
> * match rule to DIRECT
> * dual-stack dial and ipv4 tcp dial fastest
> * return ipv4 ip

make sense

**Comment by ysc3839** [comment]
@kotori2 I think `::ffff:127.0.0.1` is just a reverse DNS of 127.0.0.1. You should try `[::1]:7890`.

**Comment by kotori2** [comment]
@ysc3839 It won't make difference tho.
I think it just send a `HTTP Connect` request inside the proxy HTTP request.
```
% curl -vv -6 ip.sb --proxy "[::1]:7890" -k
*   Trying ::1...
* TCP_NODELAY set
* Connected to ::1 (::1) port 7890 (#0)
> GET http://ip.sb/ HTTP/1.1
> Host: ip.sb
> User-Agent: curl/7.64.1
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Content-Length: 14
< Cache-Control: no-cache
< Cf-Cache-Status: DYNAMIC
< Cf-Ray: 5d9bd96f0e0aeafc-LAX
< Cf-Request-Id: 05754639620000eafc58059200000001
< Connection: keep-alive
< Content-Type: text/plain
< Date: Mon, 28 Sep 2020 07:46:13 GMT
< Keep-Alive: timeout=4
< Proxy-Connection: keep-alive
< Server: cloudflare
< Set-Cookie: [REDACTED]
< X-Content-Type-Options: nosniff
<
[IPv4 address]
* Connection #0 to host ::1 left intact
* Closing connection 0
```

**Comment by ysc3839** [comment]
@kotori2 I misunderstood you. I think you are talking about the IP address in clash log.
