### ISSUE TITLE
[Feature] 手动设置TCP KeepAlive定时器

### ISSUE THREAD

**Issue by ankino17** [Dreamacro/clash#996]
感谢你向 Clash Core 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* Clash Core 的操作系统 (the OS that the Clash core is running on)
Android 10 (Kernel 4.14.117)

### 说明 Description
在移动设备中使用较低的心跳值会导致高耗电 手动设置心跳值可改善

### 可能的解决方案 Possible Solution

建议增加全局参数 可以修改KeepAlive值 或者关闭KeepAlive行为
https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/adapters/outbound/util.go#L55-L60
https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/adapters/outboundgroup/util.go#L48-L53
https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/proxy/redir/tcp.go#L57
https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/proxy/socks/tcp.go#L62
### 更多信息 More Information
![image](https://user-images.githubusercontent.com/29777681/94511337-9de89400-024b-11eb-8d68-0c2ed595893e.png)
https://github.com/v2ray/v2ray-core/issues/2564
https://github.com/Kr328/ClashForAndroid/issues/102
https://github.com/Kr328/ClashForAndroid/issues/505
https://github.com/golang/go/issues/23459

**Comment by Dreamacro** [comment]
有什么实际的测试去辅证去除 KeepAlive 后，对耗电有所改善么

**Comment by ankino17** [comment]
理论上心跳间隔增大 射频耗电会改善 但是Clash For Android闭源 我无法测试
SS-Android使用的libev核心不使用so_keepalive 全局模式下耗电比Clash For Android低
有空的话我用闭源前的版本做测试

**Comment by kongminhao** [comment]
似乎并没有留一个合理的口去关闭这个 KeepAlive。感觉上不对代码做大的改动的话，只能加全局变量或者用环境变量了。

**Comment by ankino17** [comment]
我正在编译Android的早期版本 核心代码里有一些改动
https://github.com/Kr328/clash/blob/edcbe27147be64a1a8d8417f43dbcdb0e403e079/adapters/outbound/util.go#L55-L61
其实默认的keepalive是启用的 只有手动关闭才行 注释掉这两句会导致启用keepalive并将默认心跳设为15s

**Comment by kongminhao** [comment]
> 我正在编译Android的早期版本 核心代码里有一些改动
> https://github.com/Kr328/clash/blob/edcbe27147be64a1a8d8417f43dbcdb0e403e079/adapters/outbound/util.go#L55-L61
> 其实默认的keepalive是启用的 只有手动关闭才行 注释掉这两句会导致启用keepalive并将默认心跳设为15s
> https://github.com/golang/go/blob/6fc094ceaf87659217dd0b2184e0a8749f6e3d39/src/net/dial.go#L14-L18

tcp.SetKeepAlive(false)

这样就可以了吧。

**Comment by ankino17** [comment]
> > 我正在编译Android的早期版本 核心代码里有一些改动
> > https://github.com/Kr328/clash/blob/edcbe27147be64a1a8d8417f43dbcdb0e403e079/adapters/outbound/util.go#L55-L61
> > 其实默认的keepalive是启用的 只有手动关闭才行 注释掉这两句会导致启用keepalive并将默认心跳设为15s
> > https://github.com/golang/go/blob/6fc094ceaf87659217dd0b2184e0a8749f6e3d39/src/net/dial.go#L14-L18
> 
> tcp.SetKeepAlive(false)
> 
> 这样就可以了吧。

是的

**Comment by ankino17** [comment]
> > > 我正在编译Android的早期版本 核心代码里有一些改动
> > > https://github.com/Kr328/clash/blob/edcbe27147be64a1a8d8417f43dbcdb0e403e079/adapters/outbound/util.go#L55-L61
> > > 其实默认的keepalive是启用的 只有手动关闭才行 注释掉这两句会导致启用keepalive并将默认心跳设为15s
> > > https://github.com/golang/go/blob/6fc094ceaf87659217dd0b2184e0a8749f6e3d39/src/net/dial.go#L14-L18
> > 
> > 
> > tcp.SetKeepAlive(false)
> > 这样就可以了吧。
> 
> 是的

基于Clash For Android v1.3.2
https://file.io/Kqr9Fz9H37yd

**Comment by ankino17** [comment]
这是v2.1.6
![image](https://user-images.githubusercontent.com/29777681/94885918-2eb9ac80-04a4-11eb-8509-d9f750f10716.png)
这是基于v1.3.2改动的版本
![image](https://user-images.githubusercontent.com/29777681/94885986-5741a680-04a4-11eb-8ea2-7c6fe0789960.png)

**Comment by Kr328** [comment]
> @Kr328 可以一起看一下这个改动是否能降低移动端的耗电量，或者还有什么其他的措施能够降低移动端设备的耗电问题

除了关掉 tcp keep alive 还有就是让 ticker 可以在某些时候休眠 (比如熄灭屏幕 (需要能让 UI 控制停用 ticker

**Comment by Dreamacro** [comment]
是 health check 的那个 ticker 么？打算做一个 lazy 的 health check，只在代理组所在的代理被使用时，ticker 才生效并进行健康检查

**Comment by Kr328** [comment]
@Dreamacro 除了 health 还有 provider 甚至 connection manager (

以及似乎 lazy health check 不是很好控制 (

**Comment by Dreamacro** [comment]
connection manager 没有 ticker 吧

**Comment by Kr328** [comment]
> connection manager 没有 ticker 吧

有的 (就是那个每秒刷新一次的那个 (

**Comment by Dreamacro** [comment]
处理完这些东西，大概能节省电量到一个什么程度？

**Comment by Kr328** [comment]
> 处理完这些东西，大概能节省电量到一个什么程度？还是说目前的 clash for android 已经做了一些工作来节省电量？

目前我自己的分支里 只增加了 ticker 休眠 但是反馈不足 没有统计

大概 TCP Keep Alive 才是大头吧 (

**Comment by ankino17** [comment]
@Dreamacro @Kr328 有计划吗？
