### ISSUE TITLE
[Bug] 某些情况下UDP转发不可达

### ISSUE THREAD

**Issue by xjasonlyu** [Dreamacro/clash#997]
------------------------------------------------------------------

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
ANY

### 说明 Description

无意中发现（以Socks为例，其他协议还没细看），当Clash Core运行在桥接模式下的Docker（e.g. 10.1.0.3）里，然后另一个Clash（e.g. 10.0.0.3）去发送UDP会失败，原因大概是因为：

https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/component/socks5/socks5.go#L189-L197

服务端这里`rw.LocalAddr()`返回的是Docker容器里的地址，即`10.1.0.3:port`，

https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/adapters/outbound/socks5.go#L106-L125

但是客户端在连接时用返回的`bindAddr`不在网段内，是无法路由过去的。

理论上应该是要用`bindAddr`作为发送地址的，如果直接用socks服务端的地址是可以转发的，但是好像不太RFC。所以，有没有什么好的解决办法（比如返回一个NAT外的`bindAddr`，毕竟这看起来更像是一个服务端的BUG？）。🤔😑

**Comment by Dreamacro** [comment]
自定义这个 bind addr 原本想做的，后面由于暂时没遇到问题就搁置了

**Comment by huyz-git** [comment]
挖一下这个 issue

自定义 bind addr 这个功能有进展么？目前 clash 这种返回 UDP ASSOCIATE 的连接地址的方式是没法在 nat 内给 nat 外提供带 udp 的 socks server 的。

另外，socks client 这边也有一个可以考虑的改进点：当收到的 bind addr 是不能 dial 的 ip （如 0.0.0.0）时，改为 dial tcp 地址（参考 https://github.com/v2fly/v2ray-core/pull/522 ）。有些 socks server 是一律返回监听的 ip 作为 bind addr 的，即可能返回 0.0.0.0 这种 bind addr。目前 clash 连接这些 socks server 时 udp 都是不通的，因为 clash 会试图直接 dial 0.0.0.0。

**Comment by xjasonlyu** [comment]
> 自定义 bind addr 这个功能有进展么？目前 clash 这种返回 UDP ASSOCIATE 的连接地址的方式是没法在 nat 内给 nat 外提供带 udp 的 socks server 的。

对，复杂一点的情况是不行的，目前Clash返回的BINDADDR是根据客户端连接过来的localaddr获取的。。

> 另外，socks client 这边也有一个可以考虑的改进点：当收到的 bind addr 是不能 dial 的 ip （如 0.0.0.0）时，改为 dial tcp 地址（参考 v2fly/v2ray-core#522 ）。有些 socks server 是一律返回监听的 ip 作为 bind addr 的，即可能返回 0.0.0.0 这种 bind addr。目前 clash 连接这些 socks server 时 udp 都是不通的，因为 clash 会试图直接 dial 0.0.0.0。

嗯，返回`0.0.0.0`这个在RFC规范里没有，只能算是一种拓展实现（gost就是），添加这个支持也挺简单的，还是看作者意见 @Dreamacro

**Comment by huyz-git** [comment]
> > 自定义 bind addr 这个功能有进展么？目前 clash 这种返回 UDP ASSOCIATE 的连接地址的方式是没法在 nat 内给 nat 外提供带 udp 的 socks server 的。
> 
> 对，复杂一点的情况是不行的，目前Clash返回的BINDADDR是根据客户端连接过来的localaddr获取的。。
> 
> > 另外，socks client 这边也有一个可以考虑的改进点：当收到的 bind addr 是不能 dial 的 ip （如 0.0.0.0）时，改为 dial tcp 地址（参考 [v2fly/v2ray-core#522](https://github.com/v2fly/v2ray-core/pull/522) ）。有些 socks server 是一律返回监听的 ip 作为 bind addr 的，即可能返回 0.0.0.0 这种 bind addr。目前 clash 连接这些 socks server 时 udp 都是不通的，因为 clash 会试图直接 dial 0.0.0.0。
> 
> 嗯，返回`0.0.0.0`这个在RFC规范里没有，只能算是一种拓展实现（gost就是），添加这个支持也挺简单的，还是看作者意见 @Dreamacro

我目前感觉最理想情况是这样：
- server 端支持自定义 bind addr，类似这样：
```yaml
socks:
  port: 7891
  udp-addr: "a.b.c.d" # return custom ip
# if no udp-addr specified, then return localaddr as current
```
- client 端拓展实现一下 https://github.com/v2fly/v2ray-core/pull/522 。即当收到不能连接的 ip 如 0.0.0.0 时，就尝试往 tcp 的 ip 连。这样可以支持连接更多种类的 socks server。
