### ISSUE TITLE
[Bug] Start time 

### ISSUE THREAD

**Issue by Xan-Kerem** [Dreamacro/clash#998]
Hi there!
when I wanna use Clash on ubuntu 18.04 I get this error!
 ./clash-linux-amd64-v1.1.0 
ERRO[0000] Start HTTP server error: listen tcp 127.0.0.1:7890: bind: address already in use 
How can I fix this?
Thanks in advance
Xan-Kerem

**Comment by Dreamacro** [comment]
checkout if port 7890 is already used
